import { v } from "@/content/vocab/builder";
import type { VocabRow } from "@/content/vocab/types";

export const adjectivesRows: VocabRow[] = [
  v("big", "/大的", "/bɪɡ/", "adj.", 1, 0.15, "A big house.", "大房子。", "big city", { ant: ["small"], syn: ["large"] }),
  v("small", "/小的", "/smɔːl/", "adj.", 1, 0.15, "A small cup.", "小杯子。", "small town", { ant: ["big", "large"], syn: ["little"] }),
  v("large", "/大的；大量的", "/lɑːrdʒ/", "adj.", 1, 0.3, "A large pizza.", "一个大披萨。", "a large pizza", { syn: ["big"], ant: ["small"] }),
  v("long", "/长的；久的", "/lɔːŋ/", "adj.", 1, 0.2, "Long hair.", "长发。", "long time", { ant: ["short"] }),
  v("short", "/短的；矮的", "/ʃɔːrt/", "adj.", 1, 0.2, "A short walk.", "短距离散步。", "short story", { ant: ["long", "tall"] }),
  v("tall", "/高的", "/tɔːl/", "adj.", 1, 0.2, "He is tall.", "他个子高。", "tall building", { ant: ["short"] }),
  v("new", "/新的", "/nuː/", "adj.", 1, 0.15, "New shoes!", "新鞋！", "brand new", { ant: ["old"] }),
  v("old", "/旧的；老的；……岁", "/oʊld/", "adj.", 1, 0.2, "An old friend.", "老朋友。", "ten years old", { ant: ["new", "young"] }),
  v("young", "/年轻的", "/jʌŋ/", "adj.", 1, 0.2, "Young people like it.", "年轻人喜欢它。", "young man", { ant: ["old"] }),

  v("bad", "/坏的；糟糕的", "/bæd/", "adj.", 1, 0.2, "Bad weather today.", "今天天气糟。", "feel bad", { ant: ["good"] }),
  v("great", "/很棒的", "/ɡreɪt/", "adj.", 1, 0.2, "Great job!", "干得好！", "great idea"),
  v("hot", "/热的；辣的", "/hɑːt/", "adj.", 1, 0.2, "Hot water, please.", "请给热水。", "hot day", { ant: ["cold"] }),
  v("cold", "/冷的；感冒", "/koʊld/", "adj./n.", 1, 0.2, "The water is cold.", "水是凉的。", "catch a cold", { ant: ["hot"] }),
  v("warm", "/温暖的", "/wɔːrm/", "adj.", 2, 0.25, "Warm clothes in winter.", "冬天穿暖和衣服。", "keep warm", { ant: ["cool"] }),
  v("cool", "/凉爽的；酷", "/kuːl/", "adj.", 1, 0.25, "Cool air at night.", "夜里凉快。", "stay cool", { ant: ["warm"] }),
  v("dry", "/干的；干燥的", "/draɪ/", "adj.", 3, 0.35, "My hands are dry.", "我的手很干。", "dry air", { ant: ["wet"] }),
  v("wet", "/湿的", "/wet/", "adj.", 2, 0.3, "Wet shoes again?", "鞋子又湿了？", "wet clothes", { ant: ["dry"] }),
  v("fast", "/快的", "/fæst/", "adj./adv.", 1, 0.25, "A fast car.", "快车。", "run fast", { ant: ["slow"] }),
  v("slow", "/慢的", "/sloʊ/", "adj./adv.", 1, 0.25, "Slow down!", "慢一点！", "slow down", { ant: ["fast"] }),
  v("easy", "/容易的", "/ˈiːzi/", "adj.", 1, 0.25, "Easy question.", "简单的问题。", "take it easy", { ant: ["hard"] }),
  v("hard", "/难的；努力地；硬", "/hɑːrd/", "adj./adv.", 1, 0.3, "Work hard.", "努力工作。", "work hard", { ant: ["easy"] }),
  v("happy", "/开心的", "/ˈhæpi/", "adj.", 1, 0.2, "I am happy today.", "我今天开心。", "happy birthday", { ant: ["sad"] }),
  v("sad", "/难过的", "/sæd/", "adj.", 1, 0.2, "Why so sad?", "为什么难过？", "feel sad", { ant: ["happy"] }),
  v("tired", "/累的", "/ˈtaɪərd/", "adj.", 1, 0.25, "Tired after work.", "下班后很累。", "feel tired"),
  v("angry", "/生气的", "/ˈæŋɡri/", "adj.", 2, 0.3, "Don't be angry.", "别生气。", "get angry"),
  v("afraid", "/害怕的", "/əˈfreɪd/", "adj.", 1, 0.35, "Don't be afraid.", "别怕。", "be afraid of"),
  v("busy", "/忙的", "/ˈbɪzi/", "adj.", 1, 0.25, "Busy this week.", "这周很忙。", "busy day", { ant: ["free"] }),
  v("free", "/免费的；有空的", "/friː/", "adj.", 1, 0.25, "Free on Sunday?", "周日有空吗？", "free time", { ant: ["busy"] }),
  v("right", "/对的；右边", "/raɪt/", "adj./n.", 1, 0.25, "Turn right here.", "这里右转。", "all right", { ant: ["wrong"] }),
  v("wrong", "/错的", "/rɔːŋ/", "adj.", 1, 0.25, "Wrong number.", "打错电话了。", "go wrong", { ant: ["right"] }),
  v("same", "/相同的", "/seɪm/", "adj.", 1, 0.3, "Same as before.", "和之前一样。", "the same", { ant: ["different"] }),
  v("different", "/不同的", "/ˈdɪfrənt/", "adj.", 1, 0.3, "Different colors.", "不同颜色。", "be different from", { ant: ["same"] }),
  v("beautiful", "/美丽的", "/ˈbjuːtɪfl/", "adj.", 1, 0.3, "A beautiful day.", "美好的一天。", "beautiful weather"),
  v("clean", "/干净的；清洁", "/kliːn/", "adj./v.", 1, 0.25, "Keep it clean.", "保持干净。", "clean up", { ant: ["dirty"] }),
  v("dirty", "/脏的", "/ˈdɜːrti/", "adj.", 1, 0.25, "Dirty dishes.", "脏盘子。", "dirty clothes", { ant: ["clean"] }),
  v("cheap", "/便宜的", "/tʃiːp/", "adj.", 1, 0.25, "Cheap and good.", "便宜又好。", "cheap tickets", { ant: ["expensive"] }),
  v("expensive", "/贵的", "/ɪkˈspensɪv/", "adj.", 1, 0.35, "Too expensive for me.", "对我来说太贵了。", "an expensive car", { ant: ["cheap"] }),
  v("strong", "/强壮的；浓的", "/strɔːŋ/", "adj.", 1, 0.3, "Strong coffee.", "浓咖啡。", "strong body", { ant: ["weak"] }),
  v("weak", "/弱的", "/wiːk/", "adj.", 2, 0.35, "Weak tea.", "淡茶。", "weak signal", { ant: ["strong"] }),
  v("quiet", "/安静的", "/ˈkwaɪət/", "adj.", 1, 0.3, "A quiet street.", "安静的街道。", "keep quiet"),
  v("little", "/小的；少的", "/ˈlɪtl/", "adj./det.", 1, 0.2, "A little dog.", "小狗。", "a little water", { syn: ["small"], ant: ["big"] }),
  v("quick", "/快的；迅速的", "/kwɪk/", "adj.", 1, 0.25, "Give me a quick answer.", "给我一个快速的回答。", "a quick answer", { syn: ["fast"], ant: ["slow"] }),
  v("full", "/满的；饱的", "/fʊl/", "adj.", 1, 0.3, "I am full.", "我饱了。", "a full cup"),
];
