import { v } from "@/content/vocab/builder";
import type { VocabRow } from "@/content/vocab/types";

export const verbsDaily2Rows: VocabRow[] = [
  v("arrive", "/到达", "/əˈraɪv/", "v.", 1, 0.35, "The bus arrives at eight.", "公交车八点到。", "arrive at"),
  v("rest", "/休息", "/rest/", "v./n.", 1, 0.3, "Rest your eyes.", "让眼睛休息一下。", "take a rest"),
  v("cook", "/做饭；厨师", "/kʊk/", "v./n.", 1, 0.3, "Dad cooks on Sunday.", "爸爸周日做饭。", "cook dinner"),
  v("bake", "/烤", "/beɪk/", "v.", 3, 0.4, "Bake a cake.", "烤个蛋糕。", "bake bread"),
  v("boil", "/煮沸", "/bɔɪl/", "v.", 3, 0.4, "Boil the water first.", "先把水烧开。", "boiling water"),
  v("fry", "/油炸", "/fraɪ/", "v.", 3, 0.4, "Fry an egg.", "煎个蛋。", "fried rice"),
  v("taste", "/尝；味道", "/teɪst/", "v./n.", 2, 0.35, "Taste the soup.", "尝尝汤。", "taste good"),
  v("smell", "/闻；气味", "/smel/", "v./n.", 2, 0.35, "The bread smells great.", "面包闻起来很香。", "smell good"),
  v("feel", "/感觉", "/fiːl/", "v.", 1, 0.25, "I feel tired.", "我觉得累。", "feel better"),
  v("touch", "/触摸", "/tʌtʃ/", "v./n.", 2, 0.35, "Don't touch it!", "别碰它！", "keep in touch"),
  v("hold", "/握住；举行", "/hoʊld/", "v.", 1, 0.3, "Hold my hand.", "牵着我的手。", "hold on"),
  v("pull", "/拉", "/pʊl/", "v.", 2, 0.3, "Pull the door.", "拉门。", "pull up"),
  v("push", "/推", "/pʊʃ/", "v.", 2, 0.3, "Push, don't pull.", "推，别拉。", "give it a push"),
  v("lift", "/举起；电梯(英)", "/lɪft/", "v./n.", 2, 0.35, "Lift the box.", "抬起箱子。", "lift up"),
  v("drop", "/掉落；放弃", "/drɑːp/", "v.", 1, 0.3, "Don't drop the glass.", "别把杯子摔了。", "drop by"),
  v("throw", "/扔", "/θroʊ/", "v.", 1, 0.3, "Throw it away.", "把它扔了。", "throw away"),
  v("catch", "/抓住；赶上", "/kætʃ/", "v.", 1, 0.3, "Catch the ball!", "接住球！", "catch the bus"),
  v("climb", "/爬", "/klaɪm/", "v.", 2, 0.35, "Climb the hill.", "爬山。", "climb up"),
  v("jump", "/跳", "/dʒʌmp/", "v.", 1, 0.25, "Jump high!", "跳高点！", "jump over"),
  v("swim", "/游泳", "/swɪm/", "v.", 1, 0.25, "Swim every summer.", "每年夏天游泳。", "go swimming"),
  v("fly", "/飞；驾驶飞机", "/flaɪ/", "v.", 1, 0.25, "Birds fly south.", "鸟南飞。", "fly a kite"),
  v("ride", "/骑；乘", "/raɪd/", "v.", 1, 0.25, "Ride your bike carefully.", "小心骑车。", "ride a bike"),
  v("paint", "/刷漆；绘画", "/peɪnt/", "v./n.", 2, 0.35, "Paint the wall white.", "把墙刷成白色。", "wet paint"),
  v("draw", "/画", "/drɔː/", "v.", 1, 0.25, "Draw a cat.", "画只猫。", "draw a picture"),
  v("dance", "/跳舞", "/dæns/", "v./n.", 1, 0.25, "They dance well.", "他们舞跳得好。", "go dancing"),
  v("laugh", "/笑", "/læf/", "v./n.", 1, 0.25, "Laugh out loud.", "放声大笑。", "laugh at"),
  v("cry", "/哭", "/kraɪ/", "v.", 1, 0.25, "Babies cry at night.", "婴儿夜里哭。", "cry over"),
  v("smile", "/微笑", "/smaɪl/", "v./n.", 1, 0.2, "She smiles a lot.", "她常微笑。", "big smile"),
  v("shout", "/喊叫", "/ʃaʊt/", "v.", 2, 0.3, "Don't shout at me.", "别冲我喊。", "shout at"),
  v("whisper", "/低声说", "/ˈwɪspər/", "v.", 3, 0.45, "They whisper in class.", "他们在课堂上窃窃私语。", "in a whisper"),
  v("knock", "/敲", "/nɑːk/", "v./n.", 2, 0.3, "Knock on the door.", "敲门。", "knock on"),
  v("lock", "/锁", "/lɑːk/", "v./n.", 2, 0.3, "Lock the door, please.", "请锁门。", "lock up"),
  v("fix", "/修理", "/fɪks/", "v.", 2, 0.3, "Can you fix it?", "你能修好它吗？", "fix the car"),
  v("measure", "/测量", "/ˈmeʒər/", "v.", 4, 0.5, "Measure the room.", "量一下房间。", "measure twice"),
  v("weigh", "/称重", "/weɪ/", "v.", 4, 0.5, "Weigh the apples.", "称一下苹果。", "weigh yourself"),
];
