import { v } from "@/content/vocab/builder";
import type { VocabRow } from "@/content/vocab/types";

export const adjectivesFeelRows: VocabRow[] = [
  v("calm", "/平静的", "/kɑːm/", "adj.", 2, 0.3, "Stay calm.", "保持冷静。", "keep calm"),
  v("nervous", "/紧张的", "/ˈnɜːrvəs/", "adj.", 1, 0.3, "I feel nervous.", "我觉得紧张。", "feel nervous"),
  v("excited", "/兴奋的", "/ɪkˈsaɪtɪd/", "adj.", 1, 0.3, "So excited!", "太兴奋了！", "get excited about the news"),
  v("bored", "/无聊的", "/bɔːrd/", "adj.", 1, 0.3, "I am bored.", "我好无聊。", "get bored"),
  v("lonely", "/孤独的", "/ˈloʊnli/", "adj.", 2, 0.35, "He feels lonely.", "他觉得孤独。", "feel lonely"),
  v("proud", "/骄傲的", "/praʊd/", "adj.", 1, 0.3, "Proud of you!", "为你骄傲！", "be proud of"),
  v("shy", "/害羞的", "/ʃaɪ/", "adj.", 2, 0.3, "A shy smile.", "羞涩的微笑。", "a shy smile"),
  v("brave", "/勇敢的", "/breɪv/", "adj.", 2, 0.3, "Be brave!", "勇敢点！", "be brave"),
  v("kind", "/善良的；种类", "/kaɪnd/", "adj./n.", 1, 0.25, "She is kind.", "她很善良。", "kind of"),
  v("polite", "/有礼貌的", "/pəˈlaɪt/", "adj.", 1, 0.3, "Be polite.", "礼貌点。", "polite way"),
  v("rude", "/粗鲁的", "/ruːd/", "adj.", 2, 0.3, "That was rude.", "那很无礼。", "rude of"),
  v("friendly", "/友好的", "/ˈfrendli/", "adj.", 1, 0.25, "Friendly people here.", "这里的人很友好。", "friendly people"),
  v("funny", "/有趣的", "/ˈfʌni/", "adj.", 1, 0.25, "A funny movie.", "有趣的电影。", "so funny"),
  v("serious", "/严肃的；认真的", "/ˈsɪriəs/", "adj.", 1, 0.3, "Are you serious?", "你是认真的吗？", "a serious problem"),
  v("gentle", "/温和的", "/ˈdʒentl/", "adj.", 3, 0.35, "Be gentle with it.", "对它温柔点。", "gentle voice"),
  v("strict", "/严格的", "/strɪkt/", "adj.", 2, 0.35, "A strict teacher.", "严格的老师。", "strict rules"),
  v("patient", "/耐心的；病人", "/ˈpeɪʃnt/", "adj./n.", 1, 0.3, "Be patient.", "耐心点。", "patient with"),
  v("curious", "/好奇的", "/ˈkjʊriəs/", "adj.", 3, 0.4, "Curious kids ask a lot.", "好奇的孩子问得多。", "curious about"),
  v("thankful", "/感激的", "/ˈθæŋkfl/", "adj.", 3, 0.35, "I am thankful.", "我心怀感激。", "thankful for"),
  v("worried", "/担心的", "/ˈwɜːrid/", "adj.", 1, 0.3, "Worried about money?", "担心钱吗？", "worried about"),
  v("scared", "/害怕的", "/skerd/", "adj.", 1, 0.3, "Scared of dogs?", "怕狗吗？", "scared of"),
  v("surprised", "/惊讶的", "/sərˈpraɪzd/", "adj.", 1, 0.3, "Surprised to see you!", "见到你真惊喜！", "surprised by"),
  v("confused", "/困惑的", "/kənˈfjuːzd/", "adj.", 1, 0.3, "Still confused.", "还是不明白。", "get confused"),
  v("confident", "/自信的", "/ˈkɑːnfɪdənt/", "adj.", 1, 0.3, "Be confident!", "自信点！", "confident about"),
  v("comfortable", "/舒适的", "/ˈkʌmfərtəbl/", "adj.", 1, 0.3, "Comfortable shoes.", "舒服的鞋。", "feel comfortable"),
  v("relaxed", "/放松的", "/rɪˈlækst/", "adj.", 2, 0.3, "Stay relaxed.", "放轻松。", "stay relaxed"),
  v("cheerful", "/开心的；乐观的", "/ˈtʃɪrfl/", "adj.", 3, 0.35, "She is cheerful.", "她很开朗。", "cheerful mood"),
  v("honest", "/诚实的", "/ˈɑːnɪst/", "adj.", 1, 0.3, "Be honest.", "诚实点。", "to be honest"),
  v("lazy", "/懒的", "/ˈleɪzi/", "adj.", 1, 0.25, "Lazy Sunday.", "慵懒周日。", "lazy day"),
  v("smart", "/聪明的", "/smɑːrt/", "adj.", 1, 0.25, "Smart choice!", "明智的选择！", "smart smart kid"),
  v("stupid", "/愚蠢的", "/ˈstuːpɪd/", "adj.", 1, 0.25, "My mistake.", "我的错。", "my stupid silly idea"),
  v("silly", "/傻乎乎的", "/ˈsɪli/", "adj.", 2, 0.25, "Silly joke!", "傻乎乎的笑话！", "silly question"),
];