import { v } from "@/content/vocab/builder";
import type { VocabRow } from "@/content/vocab/types";

export const adjectivesDesc2Rows: VocabRow[] = [
  v("soft", "/软的；柔和的", "/sɔːft/", "adj.", 1, 0.25, "A soft pillow.", "软枕头。", "soft light"),
  v("smooth", "/光滑的；顺利的", "/smuːð/", "adj.", 2, 0.35, "Smooth surface.", "光滑表面。", "smooth road"),
  v("rough", "/粗糙的；大致的", "/rʌf/", "adj.", 2, 0.35, "Rough hands.", "粗糙的手。", "rough day"),
  v("sharp", "/锋利的；急剧的", "/ʃɑːrp/", "adj.", 1, 0.3, "A sharp knife.", "锋利的刀。", "sharp knife"),
  v("thick", "/厚的；浓的", "/θɪk/", "adj.", 1, 0.3, "Thick soup.", "浓汤。", "thick hair"),
  v("thin", "/薄的；瘦的", "/θɪn/", "adj.", 1, 0.3, "Thin paper.", "薄纸。", "thin ice"),
  v("wide", "/宽的", "/waɪd/", "adj.", 1, 0.25, "A wide road.", "宽马路。", "wide open"),
  v("narrow", "/窄的", "/ˈneroʊ/", "adj.", 2, 0.35, "Narrow street.", "窄街。", "narrow road"),
  v("deep", "/深的", "/diːp/", "adj.", 1, 0.25, "Deep water.", "深水区。", "take a deep breath"),
  v("shallow", "/浅的", "/ˈʃæloʊ/", "adj.", 4, 0.45, "Shallow end.", "浅水区。", "shallow water"),
  v("flat", "/平的；瘪的", "/flæt/", "adj./n.", 1, 0.3, "Flat tire.", "车胎没气了。", "flat tire"),
  v("round", "/圆的；回合", "/raʊnd/", "adj./n.", 1, 0.25, "A round table.", "圆桌。", "round face"),
  v("square", "/正方形的；广场", "/skwer/", "adj./n.", 1, 0.25, "Square box.", "方盒子。", "city square"),
  v("straight", "/直的；径直", "/streɪt/", "adj./adv.", 1, 0.25, "Straight line.", "直线。", "go straight"),
  v("curly", "/卷曲的", "/ˈkɜːrli/", "adj.", 3, 0.35, "Curly hair.", "卷发。", "curly hair"),
  v("bright", "/明亮的；聪明的", "/braɪt/", "adj.", 1, 0.25, "Bright room.", "明亮的房间。", "bright future"),
  v("dark", "/黑暗的；深色", "/dɑːrk/", "adj./n.", 1, 0.2, "Dark blue.", "深蓝。", "in the dark"),
  v("loud", "/大声的", "/laʊd/", "adj.", 1, 0.2, "Loud music.", "音乐很吵。", "too loud"),
  v("heavy", "/重的", "/ˈhevi/", "adj.", 1, 0.2, "Heavy bag.", "重包。", "heavy rain"),
  v("dense", "/稠密的", "/dens/", "adj.", 4, 0.5, "Dense forest.", "密林。", "dense fog"),
  v("sweet", "/甜的", "/swiːt/", "adj.", 1, 0.2, "Sweet tea.", "甜茶。", "sweet dreams"),
  v("sour", "/酸的", "/ˈsaʊər/", "adj.", 2, 0.3, "Sour lemon.", "酸柠檬。", "sour taste"),
  v("bitter", "/苦的", "/ˈbɪtər/", "adj.", 2, 0.35, "Bitter coffee.", "苦咖啡。", "bitter taste"),
  v("spicy", "/辣的", "/ˈspaɪsi/", "adj.", 2, 0.3, "Spicy food!", "辣的食物！", "too spicy"),
  v("salty", "/咸的", "/ˈsɔːlti/", "adj.", 2, 0.3, "Salty soup.", "汤咸了。", "salty food"),
  v("fresh", "/新鲜的", "/freʃ/", "adj.", 1, 0.2, "Fresh bread.", "新鲜面包。", "fresh fruit"),
  v("stale", "/不新鲜的", "/steɪl/", "adj.", 4, 0.45, "Stale bread.", "不新鲜的面包。", "stale bread"),
  v("ripe", "/熟的", "/raɪp/", "adj.", 4, 0.4, "Ripe banana.", "熟香蕉。", "ripe fruit"),
  v("raw", "/生的", "/rɔː/", "adj.", 3, 0.4, "Raw fish?", "生鱼？", "raw vegetables"),
  v("firm", "/结实的；公司", "/fɜːrm/", "adj./n.", 3, 0.4, "Firm handshake.", "有力的握手。", "a law firm"),
  v("loose", "/松的", "/luːs/", "adj.", 3, 0.4, "Loose shirt.", "宽松衬衫。", "loose clothes"),
  v("tight", "/紧的", "/taɪt/", "adj.", 1, 0.25, "Tight shoes.", "鞋太紧。", "tight budget"),
  v("empty", "/空的", "/ˈempti/", "adj.", 1, 0.2, "Empty cup.", "空杯子。", "an empty street"),
  v("solid", "/固体的；扎实的", "/ˈsɑːlɪd/", "adj./n.", 3, 0.45, "Solid ground.", "坚实的地面。", "solid food"),
];