import { v } from "@/content/vocab/builder";
import type { VocabRow } from "@/content/vocab/types";

export const jobs2Rows: VocabRow[] = [
  v("chef", "/主厨", "/ʃef/", "n.", 3, 0.35, "The chef cooks fast.", "主厨做菜快。", "head chef"),
  v("baker", "/面包师", "/ˈbeɪkər/", "n.", 4, 0.4, "The baker starts early.", "面包师起得早。", "the baker"),
  v("server", "/服务员", "/ˈsɜːrvər/", "n.", 2, 0.3, "Our server is nice.", "我们服务员很好。", "ask the server"),
  v("cashier", "/收银员", "/kæˈʃɪr/", "n.", 2, 0.3, "Pay at the cashier.", "在收银台付款。", "the cashier"),
  v("salesperson", "/销售员", "/ˈseɪlzpɜːrsn/", "n.", 3, 0.35, "A helpful salesperson.", "热心的销售员。", "a salesperson"),
  v("engineer", "/工程师", "/ˌendʒɪˈnɪr/", "n.", 1, 0.3, "She is an engineer.", "她是工程师。", "software engineer"),
  v("lawyer", "/律师", "/ˈlɔːjər/", "n.", 1, 0.3, "Call a lawyer first.", "先联系律师。", "hire a lawyer"),
  v("judge", "/法官；判断", "/dʒʌdʒ/", "n./v.", 2, 0.35, "The judge listens.", "法官在听。", "don't judge"),
  v("police", "/警察（部门）", "/pəˈliːs/", "n.", 1, 0.25, "Call the police!", "报警！", "call the police"),
  v("soldier", "/士兵", "/ˈsoʊldʒər/", "n.", 2, 0.3, "A young soldier.", "年轻士兵。", "a soldier"),
  v("pilot", "/飞行员", "/ˈpaɪlət/", "n.", 2, 0.3, "The pilot speaks now.", "飞行员现在广播。", "the pilot"),
  v("mechanic", "/修理工", "/məˈkænɪk/", "n.", 3, 0.35, "The mechanic fixed it.", "修理工修好了。", "ask a mechanic"),
  v("plumber", "/水管工", "/ˈplʌmər/", "n.", 3, 0.4, "We need a plumber.", "我们需要水管工。", "call a plumber"),
  v("electrician", "/电工", "/ɪˌlekˈtrɪʃn/", "n.", 4, 0.45, "The electrician came.", "电工来过了。", "call an electrician"),
  v("carpenter", "/木匠", "/ˈkɑːrpəntər/", "n.", 4, 0.45, "A carpenter builds it.", "木匠来装。", "hire a carpenter"),
  v("barber", "/理发师", "/ˈbɑːrbər/", "n.", 3, 0.35, "The barber cut my hair.", "理发师给我剪了头发。", "go to the barber"),
  v("journalist", "/记者", "/ˈdʒɜːrnəlɪst/", "n.", 3, 0.4, "A journalist called.", "记者打来电话。", "a journalist"),
  v("reporter", "/记者；报告人", "/rɪˈpɔːrtər/", "n.", 2, 0.35, "The reporter asks questions.", "记者提问。", "a reporter"),
  v("photographer", "/摄影师", "/fəˈtɑːɡrəfər/", "n.", 3, 0.4, "A photographer took photos.", "摄影师拍了照。", "a photographer"),
  v("artist", "/艺术家", "/ˈɑːrtɪst/", "n.", 1, 0.3, "The artist draws well.", "这位画家画得好。", "an artist"),
  v("musician", "/音乐家", "/mjuˈzɪʃn/", "n.", 2, 0.35, "Musicians practice daily.", "音乐家每天练习。", "a musician"),
  v("actor", "/演员", "/ˈæktər/", "n.", 1, 0.25, "He is an actor.", "他是演员。", "an actor"),
  v("singer", "/歌手", "/ˈsɪŋər/", "n.", 1, 0.25, "The singer waves.", "歌手挥手。", "the singer"),
  v("dancer", "/舞者", "/ˈdænsər/", "n.", 2, 0.3, "Dancers train hard.", "舞者训练刻苦。", "the dancer"),
  v("scientist", "/科学家", "/ˈsaɪəntɪst/", "n.", 1, 0.3, "Scientists study weather.", "科学家研究天气。", "a scientist"),
  v("programmer", "/程序员", "/ˈproʊɡræmər/", "n.", 2, 0.35, "Programmers write code.", "程序员写代码。", "a programmer"),
  v("designer", "/设计师", "/dɪˈzaɪnər/", "n.", 1, 0.3, "A designer made this.", "这是设计师做的。", "a designer"),
  v("translator", "/译者", "/trænsˈleɪtər/", "n.", 3, 0.4, "The translator works fast.", "译者速度快。", "a translator"),
  v("guide", "/导游；指导", "/ɡaɪd/", "n./v.", 1, 0.3, "Our guide smiles.", "导游微笑着。", "tour guide"),
  v("coach", "/教练", "/koʊtʃ/", "n./v.", 1, 0.3, "The coach shouts less.", "教练少喊了。", "the coach"),
];