import { v } from "@/content/vocab/builder";
import type { VocabRow } from "@/content/vocab/types";

export const homeObjects2Rows: VocabRow[] = [
  v("mirror", "/镜子", "/ˈmɪrər/", "n.", 1, 0.2, "Look in the mirror.", "照镜子。", "in the mirror"),
  v("comb", "/梳子；梳理", "/koʊm/", "n./v.", 2, 0.25, "Comb your hair.", "梳头发。", "comb your hair"),
  v("brush", "/刷子；刷", "/brʌʃ/", "n./v.", 1, 0.2, "Brush twice a day.", "一天刷两次。", "tooth brushbrush your teeth"),
  v("soap", "/肥皂", "/soʊp/", "n.", 1, 0.2, "Wash with soap.", "用肥皂洗。", "hand soapa bar of soap"),
  v("shampoo", "/洗发水", "/ʃæmˈpuː/", "n.", 1, 0.25, "New shampoo smells nice.", "新洗发水很香。", "use shampoo"),
  v("toothbrush", "/牙刷", "/ˈtuːθbrʌʃ/", "n.", 1, 0.25, "Change your toothbrush often.", "常换牙刷。", "a new toothbrushtoothbrush"),
  v("toothpaste", "/牙膏", "/ˈtuːθpeɪst/", "n.", 1, 0.25, "Toothpaste on the brush.", "挤牙膏。", "a tube of toothpaste"),
  v("towel", "/毛巾", "/ˈtaʊəl/", "n.", 1, 0.2, "A dry towel.", "干毛巾。", "bath towela towel"),
  v("blanket", "/毯子", "/ˈblæŋkɪt/", "n.", 1, 0.2, "Warm blanket.", "暖毯子。", "under the blanket"),
  v("pillow", "/枕头", "/ˈpɪloʊ/", "n.", 1, 0.2, "Soft pillows help sleep.", "软枕头好睡。", "two pillows"),
  v("sheet", "/床单；一张纸", "/ʃiːt/", "n.", 2, 0.25, "Clean sheets.", "干净床单。", "bed sheets"),
  v("curtain", "/窗帘", "/ˈkɜːrtn/", "n.", 1, 0.25, "Close the curtains.", "拉上窗帘。", "draw the curtainsclose the curtains"),
  v("carpet", "/地毯", "/ˈkɑːrpɪt/", "n.", 2, 0.25, "A red carpet.", "红地毯。", "on the carpet"),
  v("bucket", "/桶", "/ˈbʌkɪt/", "n.", 2, 0.25, "A bucket of water.", "一桶水。", "a bucket of"),
  v("broom", "/扫帚", "/bruːm/", "n.", 2, 0.25, "Sweep with a broom.", "用扫帚扫。", "a broom"),
  v("bin", "/垃圾桶", "/bɪn/", "n.", 2, 0.2, "Throw it in the bin.", "扔进垃圾桶。", "recycling binthe bin"),
  v("drawer", "/抽屉", "/drɔːr/", "n.", 1, 0.25, "Keys in the drawer.", "钥匙在抽屉里。", "top drawerthe drawer"),
  v("shelf", "/架子", "/ʃelf/", "n.", 1, 0.25, "Books on the shelf.", "书在架上。", "top shelfa shelf"),
  v("ladder", "/梯子", "/ˈlædər/", "n.", 2, 0.3, "Climb the ladder.", "爬梯子。", "a ladder"),
  v("candle", "/蜡烛", "/ˈkændl/", "n.", 1, 0.2, "Light the candles.", "点蜡烛。", "birthday candleslight candles"),
  v("battery", "/电池", "/ˈbætəri/", "n.", 1, 0.25, "Battery is dead.", "电池没电了。", "low battery"),
  v("charger", "/充电器", "/ˈtʃɑːrdʒər/", "n.", 1, 0.25, "Where is my charger?", "我充电器呢？", "phone charger"),
  v("plug", "/插头", "/plʌɡ/", "n./v.", 2, 0.3, "Plug it in.", "插上电。", "plug in"),
  v("switch", "/开关；转换", "/swɪtʃ/", "n./v.", 1, 0.3, "Switch off the light.", "关灯。", "switch on"),
  v("remote", "/遥控器", "/rɪˈmoʊt/", "n.", 2, 0.3, "Hand me the remote.", "递一下遥控器。", "the TV remote"),
  v("speaker", "/音箱；演讲者", "/ˈspiːkər/", "n.", 1, 0.3, "Turn up the speaker.", "调大音量。", "a speaker"),
  v("screen", "/屏幕", "/skriːn/", "n.", 1, 0.25, "Clean your screen.", "擦屏幕。", "phone screen"),
  v("keyboard", "/键盘", "/ˈkiːbɔːrd/", "n.", 1, 0.25, "A clean keyboard.", "干净的键盘。", "type on keyboarda keyboard"),
  v("basket", "/篮子", "/ˈbæskɪt/", "n.", 1, 0.2, "A shopping basket.", "购物篮。", "laundry basketa basket"),
  v("jar", "/罐子", "/dʒɑːr/", "n.", 2, 0.2, "A jar of jam.", "一罐果酱。", "a jar of"),
  v("bottle", "/瓶子", "/ˈbɑːtl/", "n.", 1, 0.15, "A bottle of water.", "一瓶水。", "a bottle of"),
  v("envelope", "/信封", "/ˈenvəloʊp/", "n.", 2, 0.25, "Seal the envelope.", "封好信封。", "an envelope"),
];