import { v } from "@/content/vocab/builder";
import type { VocabRow } from "@/content/vocab/types";

/** Laboratory & scientific method - Phase 10 chunk-g. */
export const scienceLabRows: VocabRow[] = [
  v("hypothesis", "/假设；假说", "/haɪˈpɑːθəsɪs/", "n.", 5, 0.45, "The data did not support our hypothesis.", "数据不支持我们的假设。", "test a hypothesis"),
  v("variable-n2", "/变量；可变的", "/ˈveriəbl/", "n./adj.", 4, 0.35, "Keep every other variable constant.", "保持其他所有变量不变。", "control the variables"),
  v("control-group", "/对照组", "/kənˈtroʊl ɡruːp/", "n.", 6, 0.5, "Half the mice served as the control group.", "一半小鼠作为对照组。", "a placebo control group"),
  v("sample-size", "/样本量", "/ˈsæmpəl saɪz/", "n.", 6, 0.5, "A larger sample size improves reliability.", "样本量越大可靠性越高。", "increase the sample size"),
  v("beaker", "/烧杯", "/ˈbiːkər/", "n.", 6, 0.4, "Pour the acid into a glass beaker.", "把酸倒进玻璃烧杯里。", "a heatproof beaker"),
  v("flask", "/烧瓶；长颈瓶", "/flæsk/", "n.", 5, 0.35, "The liquid bubbled inside the flask.", "液体在烧瓶里冒泡。", "a conical flask"),
  v("microscope", "/显微镜", "/ˈmaɪkrəskoʊp/", "n.", 5, 0.3, "Cells look amazing under a microscope.", "细胞在显微镜下非常奇妙。", "examine cells under a microscope"),
  v("telescope", "/望远镜", "/ˈtelɪskoʊp/", "n.", 5, 0.3, "We pointed the telescope at Saturn.", "我们把望远镜对准土星。", "a powerful telescope"),
  v("centrifuge", "/离心机；离心分离", "/ˈsentrɪfjuːdʒ/", "n./v.", 7, 0.65, "Spin the blood samples in a centrifuge.", "把血样放进离心机旋转。", "centrifuge the sample"),
  v("petri-dish", "/培养皿", "/ˈpiːtri dɪʃ/", "n.", 7, 0.55, "Bacteria grew overnight in the petri dish.", "细菌在培养皿中一夜生长。", "culture bacteria in a petri dish"),
  v("pipette", "/移液管；吸量管", "/paɪˈpet/", "n.", 7, 0.6, "Use a pipette to transfer two drops.", "用移液管转移两滴。", "a sterile pipette"),
  v("reagent", "/试剂", "/riˈeɪdʒənt/", "n.", 7, 0.7, "Add the reagent drop by drop.", "逐滴加入试剂。", "a chemical reagent"),
  v("specimen", "/样本；标本", "/ˈspesɪmən/", "n.", 6, 0.5, "Label every specimen clearly.", "清楚标注每个标本。", "collect a tissue specimen"),
  v("calibration", "/校准；标定", "/ˌkælɪˈbreɪʃn/", "n.", 7, 0.65, "Annual calibration keeps instruments honest.", "年度校准保证仪器准确。", "sensor calibration"),
  v("observation", "/观察；观测", "/ˌɑːbzərˈveɪʃn/", "n.", 3, 0.25, "Careful observation beats guessing.", "仔细观察胜过瞎猜。", "make detailed observations"),
  v("lab-report", "/实验报告", "/ˈlæb rɪˌpɔːrt/", "n.", 4, 0.3, "Write the lab report tonight.", "今晚写实验报告。", "hand in a lab report"),
  v("peer-review", "/同行评审", "/ˌpɪr rɪˈvjuː/", "n./v.", 6, 0.55, "Peer review filters weak studies.", "同行评审过滤薄弱研究。", "pass peer review"),
  v("data-set", "/数据集", "/ˈdeɪtə set/", "n.", 5, 0.4, "The data set spans twenty years.", "该数据集跨越二十年。", "analyze a large data set"),
  v("correlation", "/相关性", "/ˌkɔːrəˈleɪʃn/", "n.", 6, 0.55, "Correlation does not prove cause.", "相关性不能证明因果。", "a strong correlation"),
  v("causation", "/因果关系", "/kɔːˈzeɪʃn/", "n.", 7, 0.65, "Proving causation requires experiments.", "证明因果关系需要实验。", "establish causation"),
  v("empirical", "/经验的；实证的", "/ɪmˈpɪrɪkl/", "adj.", 7, 0.6, "Base claims on empirical results.", "让结论基于实证结果。", "empirical evidence"),
  v("replicate", "/复制；重现", "/ˈreplɪkeɪt/", "v.", 6, 0.55, "Other labs failed to replicate the result.", "其他实验室未能复制该结果。", "replicate the findings"),
  v("quantitative", "/定量的", "/ˈkwɑːntɪteɪtɪv/", "adj.", 7, 0.65, "Quantitative data suits statistics.", "定量数据适合统计。", "quantitative analysis"),
  v("qualitative", "/定性的", "/ˈkwɑːlɪteɪtɪv/", "adj.", 6, 0.6, "Qualitative feedback revealed surprises.", "定性反馈揭示了意外发现。", "qualitative interviews"),
  v("apparatus", "/仪器；设备", "/ˌæpəˈrætəs/", "n.", 7, 0.6, "Assemble the glass apparatus carefully.", "小心组装玻璃仪器。", "laboratory apparatus"),
  v("goggles", "/护目镜", "/ˈɡɑːɡlz/", "n.", 4, 0.3, "Wear safety goggles at all times.", "全程佩戴护目镜。", "protective goggles"),
  v("hazard", "/危险；隐患", "/ˈhæzərd/", "n.", 5, 0.45, "Read the hazard labels first.", "先读危险标识。", "a potential hazard"),
  v("ventilation", "/通风", "/ˌventɪˈleɪʃn/", "n.", 6, 0.5, "Good ventilation clears toxic fumes.", "良好通风能排除毒烟。", "proper ventilation"),
  v("sterilize", "/消毒；灭菌", "/ˈsterəlaɪz/", "v.", 7, 0.6, "Sterilize the tools before surgery.", "术前给器械消毒。", "sterilize equipment"),
  v("dissect", "/解剖；剖析", "/dɪˈsekt/", "v.", 6, 0.55, "We dissected a frog in biology class.", "生物课上我们解剖了青蛙。", "dissect a specimen"),
  v("microbe", "/微生物", "/ˈmaɪkroʊb/", "n.", 6, 0.55, "A spoonful of soil holds billions of microbes.", "一勺土壤中就有数十亿微生物。", "beneficial soil microbes"),
  v("pathogen", "/病原体", "/ˈpæθədʒən/", "n.", 7, 0.7, "The pathogen spreads through dirty water.", "病原体通过污水传播。", "identify the pathogen"),
  v("catalyst", "/催化剂；促进因素", "/ˈkætəlɪst/", "n.", 7, 0.65, "The catalyst speeds up the reaction.", "催化剂加速反应。", "act as a catalyst"),
  v("solvent", "/溶剂；有溶解力的", "/ˈsɑːlvənt/", "n./adj.", 7, 0.6, "Water is a common solvent.", "水是常见溶剂。", "an organic solvent"),
  v("mixture", "/混合物", "/ˈmɪkstʃər/", "n.", 3, 0.25, "It is a mixture of sand and salt.", "这是沙和盐的混合物。", "a sticky mixture"),
  v("molecule", "/分子", "/ˈmɑːlɪkjuːl/", "n.", 5, 0.4, "A water molecule has three atoms.", "一个水分子有三个原子。", "a single molecule"),
  v("atom-n2", "/原子", "/ˈætəm/", "n.", 4, 0.3, "Atoms are incredibly small.", "原子极其微小。", "split the atom"),
  v("particle-n2", "/粒子；颗粒", "/ˈpɑːrtɪkl/", "n.", 4, 0.35, "Dust particles floated in the sunlight.", "灰尘颗粒在阳光中漂浮。", "tiny particles"),
  v("density-level", "/密度", "/ˈdensəti/", "n.", 5, 0.4, "Lead has a very high density.", "铅的密度非常高。", "low-density material"),
  v("void-space", "/空隙；真空空间", "/vɔɪd/", "n.", 6, 0.55, "Sound dies in the cold void of space.", "声音在寒冷的太空虚空中消失。", "the void of space"),
  v("friction-force", "/摩擦；摩擦力", "/ˈfrɪkʃn/", "n.", 4, 0.3, "Friction heats the brakes.", "摩擦使刹车发热。", "reduce friction"),
  v("chemical-formula", "/公式；配方", "/ˈfɔːrmjələ/", "n.", 4, 0.3, "Memorize this chemical formula.", "记住这个化学式。", "a chemical formula"),
  v("combustion-engine", "/燃烧", "/kəmˈbʌstʃən/", "n.", 7, 0.65, "Combustion releases heat and light.", "燃烧释放热和光。", "internal combustion engine"),
  v("oxidation-process", "/氧化", "/ˌɑːksɪˈdeɪʃn/", "n.", 7, 0.7, "Rust is slow oxidation.", "生锈是缓慢的氧化。", "prevent oxidation"),
  v("distillation-unit", "/蒸馏", "/ˌdɪstɪˈleɪʃn/", "n.", 7, 0.7, "Distillation purifies seawater.", "蒸馏净化海水。", "water distillation"),
  v("filtration-system", "/过滤", "/fɪlˈtreɪʃn/", "n.", 6, 0.6, "Filtration removes impurities.", "过滤去除杂质。", "a filtration system"),
  v("evaporation-rate", "/蒸发", "/ɪˌvæpəˈreɪʃn/", "n.", 5, 0.5, "Evaporation cools the wet surface.", "蒸发使湿表面冷却。", "rapid evaporation"),
  v("condensation-water", "/冷凝；凝结", "/ˌkɑːndenˈseɪʃn/", "n.", 6, 0.55, "Condensation formed on the cold lid.", "冷盖子上形成了凝结水。", "water condensation"),
  v("anomaly-detection", "/异常；反常", "/əˈnɑːməli/", "n.", 7, 0.65, "The anomaly puzzled researchers.", "异常现象让研究者困惑。", "detect an anomaly"),
  v("sampling-bias", "/抽样偏差", "/ˈsæmpəlɪŋ ˈbaɪəs/", "n.", 7, 0.65, "Tiny samples create sampling bias.", "过小的样本会产生抽样偏差。", "reduce sampling bias"),
  v("validity-check", "/有效性", "/vəˈlɪdəti/", "n.", 7, 0.6, "Check the validity of the method.", "检验方法的有效性。", "question the validity"),
  v("reliability-test", "/可靠性", "/rɪˌlaɪəˈbɪləti/", "n.", 5, 0.5, "Reliability matters more than speed.", "可靠性比速度更重要。", "test reliability"),
  v("conclusion-section", "/结论；结尾", "/kənˈkluːʒn/", "n.", 3, 0.3, "State your conclusion in one sentence.", "用一句话陈述你的结论。", "draw a conclusion"),
  v("abstract-paper", "/摘要；抽象的", "/ˈæbstrækt/", "n./adj.", 6, 0.5, "Read the abstract before the whole paper.", "读全文前先读摘要。", "the paper's abstract"),
  v("citation-format", "/引用；引文", "/saɪˈteɪʃn/", "n.", 6, 0.55, "Every claim needs a citation.", "每个论断都要有引用。", "add proper citations"),
  v("plagiarism-rules", "/剽窃；抄袭", "/ˈpleɪdʒərɪzəm/", "n.", 7, 0.6, "Plagiarism ends academic careers.", "剽窃会终结学术生涯。", "avoid plagiarism"),
  v("dissertation-defense", "/学位论文", "/ˌdɪsərˈteɪʃn/", "n.", 7, 0.6, "Her dissertation took three years.", "她的博士论文花了三年。", "write a dissertation"),
  v("research-findings", "/研究发现", "/rɪˈsɜːrtʃ ˈfaɪndɪŋz/", "n.", 5, 0.5, "The findings contradicted earlier expectations.", "研究结果与早先的预期相矛盾。", "publish the findings"),
];
