import { v } from "@/content/vocab/builder";
import type { VocabRow } from "@/content/vocab/types";

/** Astronomy & space exploration - Phase 10 chunk-g. */
export const astronomySpaceRows: VocabRow[] = [
  v("galaxy-cluster", "/星系；银河", "/ˈɡæləksi/", "n.", 5, 0.4, "Our galaxy holds billions of stars.", "我们的星系容纳数千亿颗恒星。", "the Milky Way galaxy"),
  v("cosmos", "/宇宙", "/ˈkɑːzmoʊs/", "n.", 6, 0.5, "The cosmos keeps expanding outward.", "宇宙不断向外膨胀。", "the vastness of the cosmos"),
  v("orbit-n2", "/轨道；绕行", "/ˈɔːrbɪt/", "n./v.", 4, 0.35, "The moon orbits Earth once a month.", "月球每月绕地球一周。", "enter Earth's orbit"),
  v("comet-tail", "/彗星", "/ˈkɑːmət/", "n.", 6, 0.5, "A bright comet crossed the night sky.", "一颗明亮的彗星划过夜空。", "a passing comet"),
  v("asteroid-belt", "/小行星", "/ˈæstərɔɪd/", "n.", 6, 0.55, "Asteroids circle between Mars and Jupiter.", "小行星在火星与木星之间环绕。", "the asteroid belt"),
  v("meteor-shower", "/流星", "/ˈmiːtiər/", "n.", 6, 0.5, "We watched meteors streak overhead.", "我们看流星划过头顶。", "a meteor shower"),
  v("meteorite-impact", "/陨石", "/ˈmiːtiəraɪt/", "n.", 7, 0.65, "The meteorite left a huge crater.", "陨石留下巨大坑洞。", "a meteorite impact"),
  v("impact-crater", "/陨石坑；火山口", "/ˈkreɪtər/", "n.", 6, 0.5, "Moon craters never fade away.", "月面环形山永不消失。", "an impact crater"),
  v("solar-eclipse", "/食；日食月食", "/ɪˈklɪps/", "n./v.", 6, 0.5, "A solar eclipse darkened the noon sky.", "日食使正午的天空变暗。", "watch a solar eclipse"),
  v("constellation-map", "/星座", "/ˌkɑːnstəˈleɪʃn/", "n.", 7, 0.6, "Orion is a winter constellation.", "猎户座是冬季星座。", "name the constellations"),
  v("distant-nebula", "/星云", "/ˈnebjələ/", "n.", 7, 0.7, "The nebula glows faintly pink.", "星云发出淡淡的粉色光。", "a distant nebula"),
  v("black-hole-physics", "/黑洞", "/blæk hoʊl/", "n.", 5, 0.5, "Nothing escapes a black hole.", "没有什么能逃出黑洞。", "fall into a black hole"),
  v("supernova-explosion", "/超新星", "/ˌsuːpərˈnoʊvə/", "n.", 7, 0.75, "A supernova can outshine its galaxy.", "超新星可以比它所在的星系还亮。", "observe a supernova"),
  v("gravitation-law", "/引力；万有引力", "/ˌɡrævɪˈteɪʃn/", "n.", 7, 0.6, "Gravitation bends passing starlight.", "引力使经过的星光弯曲。", "the law of gravitation"),
  v("spacecraft-launch", "/航天器；宇宙飞船", "/ˈspeɪskræft/", "n.", 5, 0.45, "The spacecraft passed the far side of the moon.", "航天器掠过月球背面。", "launch a spacecraft"),
  v("space-station-dock", "/空间站", "/ˈspeɪs ˌsteɪʃn/", "n.", 5, 0.45, "Astronauts exercise daily on the space station.", "宇航员在空间站每天锻炼。", "board the space station"),
  v("astronaut-training", "/宇航员", "/ˈæstrənɔːt/", "n.", 4, 0.3, "Astronauts train for years before launch.", "宇航员发射前要训练多年。", "become an astronaut"),
  v("rocket-launch-pad", "/发射台", "/ˈlɔːntʃ pæd/", "n.", 6, 0.5, "Rockets lift off from the launch pad.", "火箭从发射台升空。", "clear the launch pad"),
  v("countdown-clock", "/倒计时", "/ˈkaʊntdaʊn/", "n.", 4, 0.35, "The countdown stopped at ten seconds.", "倒计时在十秒时暂停。", "begin the countdown"),
  v("rocket-engine", "/火箭", "/ˈrɑːkɪt/", "n.", 4, 0.35, "The rocket climbed through the clouds.", "火箭穿云而上。", "launch a rocket"),
  v("lunar-module", "/舱；模块", "/ˈmɑːdʒuːl/", "n.", 7, 0.6, "The lunar module separated cleanly.", "登月舱顺利分离。", "a service module"),
  v("return-capsule", "/返回舱；胶囊", "/ˈkæpsuːl/", "n.", 6, 0.55, "The capsule splashed down safely.", "返回舱安全溅落海面。", "a reentry capsule"),
  v("safe-touchdown", "/着陆；降落", "/ˈtʌtʃdaʊn/", "n.", 6, 0.55, "Touchdown was confirmed at three o'clock.", "下午三点确认着陆。", "confirm touchdown"),
  v("mars-rover", "/火星车；漫游车", "/ˈroʊvər/", "n.", 7, 0.6, "The rover drilled into Martian rock.", "火星车钻取火星岩石。", "a robotic rover"),
  v("Martian-planet", "/火星的；火星人", "/ˈmɑːrʃn/", "adj./n.", 7, 0.6, "Martian soil contains rusty iron dust.", "火星土壤含铁锈色尘埃。", "a Martian landscape"),
  v("cosmic-rays", "/宇宙的", "/ˈkɑːzmɪk/", "adj.", 6, 0.55, "Cosmic rays pierce almost everything.", "宇宙射线几乎穿透一切。", "cosmic radiation"),
  v("interstellar-travel", "/星际的", "/ˌɪntərˈstelər/", "adj.", 7, 0.7, "Interstellar travel remains theoretical.", "星际旅行仍停留在理论阶段。", "interstellar space"),
  v("astronomical-costs", "/天文的；天文数字般庞大的", "/ˌæstrəˈnɑːmɪkl/", "adj.", 7, 0.6, "Ticket prices were astronomical.", "票价高得离谱。", "an astronomical sum"),
  v("space-observatory", "/天文台", "/əbˈzɜːrvətɔːri/", "n.", 7, 0.6, "The observatory opens its dome at dusk.", "天文台黄昏开启圆顶。", "visit an observatory"),
  v("professional-astronomer", "/天文学家", "/əˈstrɑːnəmər/", "n.", 6, 0.5, "Astronomers track near-Earth objects.", "天文学家追踪近地天体。", "a professional astronomer"),
  v("stargazing-night", "/观星", "/ˈstɑːrɡeɪzɪŋ/", "n.", 5, 0.4, "Stargazing calms a busy mind.", "观星让忙碌的心平静下来。", "go stargazing"),
  v("light-year-distance", "/光年", "/ˈlaɪt jɪr/", "n.", 6, 0.5, "That star lies forty light-years away.", "那颗恒星距我们四十光年。", "thousands of light-years away"),
  v("solar-system-tour", "/太阳系", "/ˈsoʊlər ˈsɪstəm/", "n.", 4, 0.35, "Eight planets form our solar system.", "八大行星构成我们的太阳系。", "explore the solar system"),
  v("helium-balloon", "/氦", "/ˈhiːliəm/", "n.", 6, 0.5, "Helium lifts party balloons.", "氦气托起派对气球。", "a tank of helium"),
  v("hydrogen-fuel", "/氢", "/ˈhaɪdrədʒən/", "n.", 6, 0.5, "Hydrogen burns without smoke.", "氢燃烧无烟。", "hydrogen fuel"),
  v("radiation-levels", "/辐射", "/ˌreɪdiˈeɪʃn/", "n.", 6, 0.5, "Radiation levels spiked after the leak.", "泄漏后辐射水平飙升。", "exposure to radiation"),
  v("zero-gravity-flight", "/零重力；失重", "/ˌzɪroʊ ˈɡrævəti/", "n.", 6, 0.5, "Bones weaken in zero gravity.", "失重环境下骨骼会变弱。", "float in zero gravity"),
  v("spacesuit-design", "/宇航服", "/ˈspeɪssuːt/", "n.", 6, 0.5, "The spacesuit weighs 250 pounds on Earth.", "宇航服在地球上重二百五十磅。", "wear a spacesuit"),
  v("lunar-surface", "/月球的；农历的", "/ˈluːnər/", "adj.", 6, 0.55, "Lunar dust ruined the camera lens.", "月尘毁了相机镜头。", "a lunar landing"),
  v("mission-control-room", "/任务控制中心", "/ˈmɪʃn kənˌtroʊl/", "n.", 6, 0.55, "Mission Control held its breath.", "任务控制中心屏住了呼吸。", "report to Mission Control"),
  v("space-probe", "/探测器；探查", "/proʊb/", "n./v.", 7, 0.6, "The probe sent back close-up images.", "探测器传回特写图像。", "launch a space probe"),
  v("celestial-bodies", "/天的；天体的", "/səˈlestʃl/", "adj.", 7, 0.65, "Ancient maps charted celestial bodies.", "古地图上标绘着天体。", "celestial navigation"),
  v("zodiac-sign", "/黄道带；十二宫", "/ˈzoʊdiæk/", "n.", 7, 0.65, "She reads her zodiac sign every morning.", "她每天早上看自己的星座运势。", "the signs of the zodiac"),
  v("daily-horoscope", "/占星；星运", "/ˈhɔːrəskoʊp/", "n.", 6, 0.55, "His horoscope promised good luck this week.", "他的本周星运预示好运。", "read your horoscope"),
  v("alien-life-form", "/外星人；外星的", "/ˈeɪliən/", "n./adj.", 4, 0.35, "No alien signal has ever been verified.", "从未有确证的外星信号。", "signs of alien life"),
  v("extraterrestrial-being", "/地球外的", "/ˌekstrətəˈrestriəl/", "adj.", 7, 0.75, "Extraterrestrial life remains hypothetical.", "地外生命仍是假设。", "extraterrestrial intelligence"),
  v("science-fiction-novel", "/科幻小说", "/ˈsaɪəns ˈfɪkʃn/", "n.", 4, 0.35, "Science-fiction predicts tomorrow's gadgets.", "科幻预言明日的科技产品。", "a science-fiction novel"),
  v("planetarium-show", "/天文馆", "/ˌplænɪˈteriəm/", "n.", 7, 0.65, "Kids love the planetarium dome show.", "孩子们喜欢天文馆的穹顶影片。", "visit the planetarium"),
  v("astrophysics-degree", "/天体物理学", "/ˌæstroʊˈfɪzɪks/", "n.", 7, 0.75, "Astrophysics explains stellar lifecycles.", "天体物理学解释恒星生命周期。", "study astrophysics"),
  v("big-bang-theory", "/宇宙大爆炸", "/ˌbɪɡ ˈbæŋ/", "n.", 6, 0.6, "The Big Bang theory explains cosmic origins.", "大爆炸理论解释宇宙起源。", "since the Big Bang"),
  v("dark-matter-clue", "/暗物质", "/dɑːrk ˈmætər/", "n.", 7, 0.75, "Dark matter outweighs visible stars.", "暗物质的质量超过可见恒星。", "clues about dark matter"),
  v("weightlessness-effect", "/失重状态", "/ˈweɪtləsnəs/", "n.", 7, 0.6, "Weightlessness disorients newcomers.", "失重让新手失去方向感。", "experience weightlessness"),
  v("blast-off-moment", "/点火升空", "/ˈblæst ɔːf/", "n.", 6, 0.55, "Blast-off went flawlessly.", "点火升空完美无误。", "moments before blast-off"),
  v("atmospheric-reentry", "/再入大气层", "/riˈentri/", "n.", 7, 0.65, "Reentry heats the hull to thousands of degrees.", "再入大气层使船体升温数千度。", "survive reentry"),
  v("automatic-docking", "/对接", "/ˈdɑːkɪŋ/", "n.", 7, 0.6, "Docking demands millimeter precision.", "对接需要毫米级精度。", "automatic docking"),
  v("rocket-payload", "/有效载荷", "/ˈpeɪloʊd/", "n.", 7, 0.65, "The rocket carried a secret payload.", "火箭运载着秘密载荷。", "a scientific payload"),
  v("rocket-booster", "/助推器；加强针", "/ˈbuːstər/", "n.", 6, 0.55, "Boosters detach two minutes after lift-off.", "助推器在升空两分钟后分离。", "a rocket booster"),
  v("flight-trajectory", "/轨迹；弹道", "/trəˈdʒektəri/", "n.", 7, 0.6, "The trajectory narrowly missed the station.", "轨迹与空间站擦肩而过。", "adjust the trajectory"),
  v("veteran-cosmonaut", "/苏联/俄罗斯宇航员", "/ˈkɑːzmənɔːt/", "n.", 7, 0.65, "Cosmonauts pioneered long-duration missions.", "苏联宇航员开创了长期太空任务。", "a veteran cosmonaut"),
];
