import { v } from "@/content/vocab/builder";
import type { VocabRow } from "@/content/vocab/types";

/** Geography & terrain - Phase 10 chunk-g. */
export const geographyTerrainRows: VocabRow[] = [
  v("continent-n2", "/大陆；洲", "/ˈkɑːntɪnənt/", "n.", 2, 0.2, "Asia is the largest continent.", "亚洲是最大的洲。", "across the continent"),
  v("peninsula", "/半岛", "/pəˈnɪnsələ/", "n.", 6, 0.5, "Florida is a famous peninsula.", "佛罗里达是著名的半岛。", "a rocky peninsula"),
  v("plateau", "/高原；停滞期", "/plæˈtoʊ/", "n./v.", 6, 0.5, "The plateau sits three thousand meters high.", "这片高原海拔三千米。", "a vast plateau"),
  v("plain-n2", "/平原；朴素的", "/pleɪn/", "n./adj.", 3, 0.3, "Buffalo once roamed the Great Plains.", "野牛曾漫步于大平原。", "wide open plains"),
  v("valley-n2", "/山谷；流域", "/ˈvæli/", "n.", 2, 0.25, "Vineyards cover the whole valley.", "葡萄园铺满整个山谷。", "a fertile river valley"),
  v("steep-gorge", "/峡谷；深谷", "/ɡɔːrdʒ/", "n.", 6, 0.55, "Rafting through the steep gorge thrilled us.", "在陡峭的峡谷中漂流令我们兴奋不已。", "a narrow gorge"),
  v("cliff-edge", "/悬崖；峭壁", "/klɪf/", "n.", 4, 0.3, "The cottage perched on the cliff edge.", "小屋悬立于崖边。", "a sheer cliff"),
  v("mountain-ridge", "/山脊", "/rɪdʒ/", "n.", 6, 0.5, "We hiked along the foggy ridge.", "我们沿着雾蒙蒙的山脊徒步。", "a mountain ridge"),
  v("peak-n2", "/山峰；顶峰", "/piːk/", "n.", 3, 0.3, "Snow caps the highest peak year-round.", "最高峰顶终年积雪。", "reach the peak"),
  v("summit-mountain", "/山顶；峰会", "/ˈsʌmɪt/", "n.", 5, 0.45, "They reached the summit at dawn.", "他们在黎明时分登顶。", "the summit of the mountain"),
  v("foothills", "/山麓丘陵", "/ˈfʊthɪlz/", "n.", 6, 0.5, "Deer graze quietly in the foothills.", "鹿在山麓安静地吃草。", "the foothills of the Alps"),
  v("river-basin", "/流域；盆地", "/ˈbeɪsn/", "n.", 6, 0.5, "The Amazon Basin drains half a continent.", "亚马逊流域排水半个大陆。", "the river basin"),
  v("delta-region", "/三角洲", "/ˈdeltə/", "n.", 6, 0.55, "The delta fans out into the sea.", "三角洲呈扇形伸入大海。", "the Nile Delta"),
  v("estuary", "/河口湾", "/ˈestʃueri/", "n.", 7, 0.65, "Birds crowd the muddy estuary each winter.", "每年冬天鸟群聚集泥泞的河口。", "a busy shipping estuary"),
  v("bay-area", "/海湾", "/beɪ/", "n.", 2, 0.2, "Boats bobbed gently in the calm bay.", "小船在平静的海湾里轻轻摇晃。", "a sheltered bay"),
  v("lagoon", "/潟湖；环礁湖", "/ləˈɡuːn/", "n.", 7, 0.6, "Flamingos waded through the shallow lagoon.", "火烈鸟涉过浅浅的潟湖。", "a blue lagoon"),
  v("strait-crossing", "/海峡", "/streɪt/", "n.", 7, 0.6, "Ships queue up at the narrow strait.", "船只排队通过狭窄的海峡。", "cross the strait"),
  v("archipelago", "/群岛", "/ˌɑːrkɪˈpeləɡoʊ/", "n.", 7, 0.7, "Indonesia is a vast archipelago.", "印度尼西亚是一片广袤的群岛。", "a tropical archipelago"),
  v("atoll", "/环礁", "/ˈætɔːl/", "n.", 7, 0.75, "The atoll rings a turquoise lagoon.", "环礁环抱着一泓碧绿的潟湖。", "a remote atoll"),
  v("terrain-type", "/地形；地势", "/təˈreɪn/", "n.", 5, 0.45, "Mountain bikes handle rough terrain best.", "山地车最擅长应对崎岖地形。", "rough terrain"),
  v("topography", "/地形学；地势", "/təˈpɑːɡrəfi/", "n.", 7, 0.7, "The map shows surprisingly rugged topography.", "地图显示出惊人的崎岖地势。", "study the topography"),
  v("elevation-level", "/海拔；高度", "/ˌelɪˈveɪʃn/", "n.", 5, 0.45, "Denver sits at a high elevation.", "丹佛海拔很高。", "an elevation of 1,600 meters"),
  v("altitude-sickness", "/海拔；高处", "/ˈæltɪtuːd/", "n.", 5, 0.4, "Altitude sickness hit us on day two.", "第二天我们就出现了高原反应。", "adjust to high altitude"),
  v("latitude-line", "/纬度", "/ˈlætɪtuːd/", "n.", 6, 0.55, "Latitude largely shapes climate zones.", "纬度在很大程度上决定气候带。", "at high latitudes"),
  v("longitude-line", "/经度", "/ˈlɑːndʒɪtuːd/", "n.", 6, 0.55, "Longitude baffled sailors for centuries.", "经度困扰了航海者几个世纪。", "lines of longitude"),
  v("equator-line", "/赤道", "/ɪˈkweɪtər/", "n.", 5, 0.45, "Days and nights are equal at the equator.", "赤道上昼夜等长。", "near the equator"),
  v("tropics-zone", "/热带地区", "/ˈtrɑːpɪks/", "n.", 5, 0.45, "Mangoes thrive in the tropics.", "芒果盛产于热带地区。", "life in the tropics"),
  v("arctic-region", "/北极的；北极圈", "/ˈɑːrktɪk/", "adj./n.", 5, 0.45, "Arctic sea ice shrinks every year.", "北极海冰逐年缩减。", "the Arctic Circle"),
  v("hemisphere-half", "/半球", "/ˈhemɪsfɪr/", "n.", 5, 0.45, "Winter flips between the two hemispheres.", "南北半球的冬季正好相反。", "the Southern Hemisphere"),
  v("horizon-view", "/地平线；眼界", "/həˈraɪzn/", "n.", 3, 0.3, "The sun sank below the horizon.", "太阳沉入地平线下。", "on the horizon"),
  v("city-landmark", "/地标", "/ˈlændmɑːrk/", "n.", 3, 0.3, "The tower is the city's most famous landmark.", "这座塔是该市最著名的地标。", "a historic landmark"),
  v("border-checkpoint", "/边境检查站", "/ˈtʃekpɔɪnt/", "n.", 5, 0.45, "Guards waved us through the checkpoint.", "卫兵挥手让我们通过检查站。", "a military checkpoint"),
  v("province-region", "/省份", "/ˈprɑːvɪns/", "n.", 4, 0.3, "Guangdong is a wealthy southern province.", "广东是一个富裕的南方省份。", "a coastal province"),
  v("municipality-city", "/市政当局；自治市", "/mjuːˌnɪsɪˈpæləti/", "n.", 7, 0.65, "The municipality repaired the old bridge.", "市政部门修缮了老桥。", "the local municipality"),
  v("suburb-town", "/郊区", "/ˈsʌbɜːrb/", "n.", 3, 0.25, "They moved to a quiet suburb.", "他们搬到了安静的郊区。", "a leafy suburb"),
  v("outskirts-of-town", "/市郊；外围", "/ˈaʊtskɜːrts/", "n.", 5, 0.45, "Factories cluster on the outskirts of town.", "工厂聚集在市郊。", "live on the outskirts"),
  v("rural-area", "/乡村的", "/ˈrʊrəl/", "adj.", 4, 0.3, "Rural buses run only twice a day.", "乡间巴士一天只开两班。", "rural communities"),
  v("urbanization-trend", "/城市化", "/ˌɜːrbənəˈzeɪʃn/", "n.", 7, 0.6, "Urbanization has emptied many villages.", "城市化使许多村庄空心化。", "rapid urbanization"),
  v("metropolitan-area", "/大都市的", "/ˌmetrəˈpɑːlɪtən/", "adj.", 6, 0.5, "The metropolitan area holds nine million people.", "都会区有九百万人口。", "the metropolitan area"),
  v("scenic-vista", "/景色；远景", "/ˈvɪstə/", "n.", 7, 0.6, "The balcony frames a stunning mountain vista.", "阳台框住一幅绝美的山景。", "a breathtaking vista"),
  v("panorama-view", "/全景", "/ˌpænəˈræmə/", "n.", 7, 0.6, "The summit offers a full panorama of the coast.", "山顶可尽览海岸全景。", "a sweeping panorama"),
  v("waterfall-hike", "/瀑布", "/ˈwɔːtərfɔːl/", "n.", 3, 0.3, "Cool mist rose from the waterfall.", "瀑布腾起清凉的水雾。", "a towering waterfall"),
  v("hot-spring", "/温泉", "/ˈhɑːt sprɪŋ/", "n.", 5, 0.4, "We soaked in a steaming hot spring.", "我们泡了热气腾腾的温泉。", "a natural hot spring"),
  v("limestone-cave", "/洞穴", "/keɪv/", "n.", 3, 0.3, "Stalactites hung from the cave ceiling.", "钟乳石悬在洞顶。", "explore a limestone cave"),
  v("underground-cavern", "/大山洞", "/ˈkævərn/", "n.", 6, 0.55, "Echoes filled the enormous cavern.", "巨大的洞穴中回声荡漾。", "an underground cavern"),
  v("sand-dune", "/沙丘", "/duːn/", "n.", 6, 0.5, "Camels crossed the singing sand dunes.", "骆驼穿越鸣沙丘。", "climb the sand dunes"),
  v("desert-oasis", "/绿洲", "/oʊˈeɪsɪs/", "n.", 7, 0.65, "Palm shade marked a rare oasis.", "棕榈树荫处是一片难得的绿洲。", "a desert oasis"),
  v("frozen-tundra", "/苔原；冻原", "/ˈtʌndrə/", "n.", 7, 0.7, "Caribou migrate across the tundra.", "驯鹿迁徙穿越苔原。", "the frozen tundra"),
  v("african-savanna", "/稀树草原", "/səˈvænə/", "n.", 7, 0.65, "Lions rule the open savanna.", "狮子统治着辽阔的稀树草原。", "the African savanna"),
  v("amazon-rainforest", "/雨林", "/ˈreɪnfɔːrɪst/", "n.", 5, 0.45, "Rainforests store immense amounts of carbon.", "雨林储存着巨量的碳。", "the Amazon rainforest"),
  v("swamp-land", "/沼泽", "/swɑːmp/", "n.", 5, 0.45, "Alligators glide silently through the swamp.", "鳄鱼悄无声息地在沼泽滑行。", "a mosquito-filled swamp"),
  v("salt-marsh", "/盐沼；湿地", "/mɑːrʃ/", "n.", 7, 0.6, "Herons nest deep in the marsh.", "苍鹭在沼泽深处筑巢。", "salt marshes"),
  v("alpine-meadow", "/草地；草甸", "/ˈmedoʊ/", "n.", 6, 0.5, "Picnickers spread across the wildflower meadow.", "野餐者散布在开满野花的草甸上。", "an alpine meadow"),
  v("mountain-stream", "/小溪；溪流", "/striːm/", "n.", 3, 0.25, "Trout darted about the cold stream.", "鳟鱼在冰冷溪流中穿梭。", "a mountain stream"),
  v("river-tributary", "/支流", "/ˈtrɪbjəteri/", "n.", 7, 0.65, "That tributary doubles the river's flow.", "那条支流使河水流量翻倍。", "a major tributary"),
  v("water-reservoir", "/水库；蓄水池", "/ˈrezərwɑːr/", "n.", 6, 0.5, "The reservoir supplies the entire city.", "水库供应全市用水。", "a drinking-water reservoir"),
  v("shipping-canal", "/运河；水道", "/kəˈnæl/", "n.", 5, 0.4, "Barges glide slowly along the canal.", "驳船沿运河缓缓滑行。", "the Panama Canal"),
  v("hydroelectric-dam", "/水坝；堤坝", "/dæm/", "n.", 4, 0.3, "The dam generates cheap clean power.", "大坝生产廉价的清洁电力。", "a hydroelectric dam"),
];
