import { v } from "@/content/vocab/builder";
import type { VocabRow } from "@/content/vocab/types";

/** Environment, climate & natural disasters - Phase 10 chunk-g. */
export const environmentClimateRows: VocabRow[] = [
  v("climate-change-effect", "/气候变化", "/ˈklaɪmət tʃeɪndʒ/", "n.", 4, 0.35, "Climate change is reshaping coastlines.", "气候变化正在重塑海岸线。", "fight climate change"),
  v("global-warming-trend", "/全球变暖", "/ˈɡloʊbl ˈwɔːrmɪŋ/", "n.", 4, 0.35, "Global warming melts mountain glaciers.", "全球变暖融化高山冰川。", "slow global warming"),
  v("carbon-emission-cut", "/排放；排放物", "/ɪˈmɪʃn/", "n.", 5, 0.45, "New rules cut car emissions sharply.", "新规大幅削减汽车尾气排放。", "cut carbon emissions"),
  v("greenhouse-gas-levels", "/温室气体", "/ˈɡriːnhaʊs ɡæs/", "n.", 5, 0.45, "Methane is a potent greenhouse gas.", "甲烷是一种强效温室气体。", "reduce greenhouse gases"),
  v("fossil-fuel-use", "/化石燃料", "/ˈfɑːsl ˈfjuːəl/", "n.", 4, 0.4, "Fossil fuels still power most big cities.", "化石燃料仍为大多数城市供能。", "phase out fossil fuels"),
  v("renewable-energy-source", "/可再生能源", "/rɪˈnuːəbl ˈenərdʒi/", "n.", 4, 0.4, "Renewable energy prices keep falling.", "可再生能源价格持续下降。", "invest in renewable energy"),
  v("rooftop-solar-panel", "/太阳能板", "/ˈsoʊlər pænl/", "n.", 4, 0.4, "Solar panels now cover the whole roof.", "太阳能板现在铺满了整个屋顶。", "install solar panels"),
  v("wind-turbine-farm", "/风力涡轮机", "/wɪnd ˈtɜːrbaɪn/", "n.", 5, 0.45, "Wind turbines dot the coastal hills.", "风力发电机点缀着沿海丘陵。", "a field of wind turbines"),
  v("sustainability-goal", "/可持续性", "/səˌsteɪnəˈbɪləti/", "n.", 6, 0.5, "Sustainability now guides city planning.", "可持续性如今指导城市规划。", "a commitment to sustainability"),
  v("fragile-ecosystem", "/生态系统", "/ˈiːkoʊsɪstəm/", "n.", 4, 0.4, "A garden pond is a small ecosystem.", "花园池塘就是一个小生态系统。", "protect fragile ecosystems"),
  v("biodiversity-loss", "/生物多样性", "/ˌbaɪoʊdaɪˈvɜːrsəti/", "n.", 7, 0.65, "Biodiversity keeps forests resilient.", "生物多样性让森林更有韧性。", "protect biodiversity"),
  v("deforestation-rate", "/滥伐森林；毁林", "/diːˌfɔːrɪˈsteɪʃn/", "n.", 7, 0.6, "Deforestation speeds up flooding downstream.", "滥伐森林加剧下游洪灾。", "halt deforestation"),
  v("desertification-risk", "/荒漠化", "/dɪˌzɜːrtɪfɪˈkeɪʃn/", "n.", 7, 0.75, "Desertification threatens northern farmland.", "荒漠化威胁着北方农田。", "combat desertification"),
  v("soil-erosion-control", "/侵蚀；腐蚀", "/ɪˈroʊʒn/", "n.", 6, 0.5, "Erosion slowly carved the grand canyon walls.", "侵蚀缓缓凿出了峡谷岩壁。", "prevent soil erosion"),
  v("thick-smog-layer", "/雾霾", "/smɑːɡ/", "n.", 5, 0.45, "Smog hid the skyline all week.", "雾霾整周遮住了天际线。", "blanketed in smog"),
  v("water-contaminant", "/污染物", "/kənˈtæmɪnənt/", "n.", 7, 0.65, "Tests found lead contaminants in the water.", "检测在水里发现了铅污染物。", "remove contaminants"),
  v("toxic-waste-site", "/有毒废料", "/ˈtɑːksɪk weɪst/", "n.", 6, 0.55, "Toxic waste poisoned the river fish.", "有毒废料毒害了河里的鱼。", "dump toxic waste"),
  v("landfill-space", "/垃圾填埋场", "/ˈlændfɪl/", "n.", 5, 0.45, "Most plastic trash ends up in landfills.", "大多数塑料垃圾最后进了填埋场。", "reduce landfill waste"),
  v("composting-bin", "/堆肥", "/ˈkɑːmpoʊstɪŋ/", "n.", 6, 0.5, "Composting turns kitchen scraps into soil.", "堆肥把厨余变成沃土。", "start composting at home"),
  v("biodegradable-plastic", "/可生物降解的", "/ˌbaɪoʊdɪˈɡreɪdəbl/", "adj.", 7, 0.65, "Choose biodegradable packaging when possible.", "尽量选择可降解包装。", "fully biodegradable materials"),
  v("carbon-footprint-reduction", "/碳足迹", "/ˈkɑːrbən ˈfʊtprɪnt/", "n.", 5, 0.5, "Flying triples your carbon footprint.", "坐飞机会使你的碳足迹翻三倍。", "shrink your carbon footprint"),
  v("offset-carbon", "/抵消；弥补", "/ˈɔːfset/", "v./n.", 6, 0.5, "Planting trees can offset some emissions.", "种树可以抵消部分排放。", "offset your carbon use"),
  v("wildlife-conservation", "/保护；保存", "/ˌkɑːnsərˈveɪʃn/", "n.", 5, 0.45, "Wildlife conservation needs steady funding.", "野生动物保护需要稳定的资金。", "a conservation project"),
  v("natural-habitat-loss", "/栖息地", "/ˈhæbɪtæt/", "n.", 5, 0.4, "Logging destroys panda habitat.", "伐木破坏了大熊猫的栖息地。", "lose its natural habitat"),
  v("endangered-species-list", "/濒危物种", "/ɪnˈdeɪndʒərd ˈspiːʃiːz/", "n.", 4, 0.4, "Tigers remain on the endangered species list.", "老虎仍在濒危物种名单上。", "protect endangered species"),
  v("extinct-species", "/灭绝的", "/ɪkˈstɪŋkt/", "adj.", 5, 0.45, "Dinosaurs went extinct 66 million years ago.", "恐龙在六千六百万年前灭绝了。", "go extinct"),
  v("anti-poaching-patrol", "/偷猎；非法捕猎", "/ˈpoʊtʃɪŋ/", "n.", 7, 0.6, "Poaching nearly wiped out the rhinos.", "偷猎几乎使犀牛绝迹。", "an anti-poaching unit"),
  v("wildlife-reserve-zone", "/自然保护区", "/ˈwaɪldlaɪf rɪˈzɜːrv/", "n.", 5, 0.45, "The wildlife reserve spans four hundred square miles.", "保护区绵延四百平方英里。", "a national wildlife reserve"),
  v("coastal-wetland-restoration", "/湿地", "/ˈwetlənd/", "n.", 6, 0.5, "Wetlands filter water naturally.", "湿地能自然过滤水质。", "restore coastal wetlands"),
  v("coral-reef-bleaching", "/珊瑚礁", "/ˈkɔːrəl riːf/", "n.", 6, 0.5, "Coral reefs shelter a quarter of marine species.", "珊瑚礁庇护着四分之一的海洋物种。", "a dying coral reef"),
  v("acid-rain-damage", "/酸雨", "/ˈæsɪd reɪn/", "n.", 6, 0.5, "Acid rain slowly damages stone statues.", "酸雨慢慢损坏石雕。", "damage caused by acid rain"),
  v("ozone-layer-recovery", "/臭氧层", "/ˈoʊzoʊn ˈleɪər/", "n.", 6, 0.5, "The ozone layer blocks harmful UV rays.", "臭氧层阻挡有害紫外线。", "heal the ozone layer"),
  v("ultraviolet-protection", "/紫外线的", "/ˌʌltrəˈvaɪələt/", "adj.", 6, 0.55, "Ultraviolet light fades curtains fast.", "紫外线很快使窗帘褪色。", "ultraviolet protection factor"),
  v("prolonged-drought-period", "/干旱；旱灾", "/draʊt/", "n.", 5, 0.4, "A prolonged drought dried up the wells.", "长期干旱使水井干涸。", "survive a prolonged drought"),
  v("flash-flood-warning", "/山洪暴发", "/flæʃ flʌd/", "n.", 6, 0.5, "Flash floods swept parked cars away.", "山洪冲走了停放的汽车。", "a flash flood warning"),
  v("deadly-landslide", "/山体滑坡", "/ˈlændslaɪd/", "n.", 5, 0.45, "Heavy rains triggered landslides overnight.", "暴雨一夜之间引发多处山体滑坡。", "trigger a landslide"),
  v("raging-wildfire", "/野火；山火", "/ˈwaɪldfaɪər/", "n.", 5, 0.4, "Wildfires rage across California each summer.", "加州每年夏天山火肆虐。", "contain a wildfire"),
  v("hurricane-season", "/飓风", "/ˈhɜːrɪkən/", "n.", 4, 0.35, "The hurricane flattened coastal towns.", "飓风夷平了沿海城镇。", "brace for a hurricane"),
  v("tornado-alley", "/龙卷风", "/tɔːrˈneɪdoʊ/", "n.", 5, 0.4, "The tornado lifted roofs right off houses.", "龙卷风把屋顶整个掀翻。", "a tornado warning siren"),
  v("tsunami-warning-system", "/海啸", "/tsuːˈnɑːmi/", "n.", 6, 0.5, "The tsunami reached three countries within hours.", "海啸数小时内波及三国。", "a tsunami warning system"),
  v("aftershock-series", "/余震", "/ˈæftərʃɑːk/", "n.", 7, 0.6, "Aftershocks rattled survivors for days.", "余震惊扰幸存者多日。", "a series of aftershocks"),
  v("earthquake-magnitude-scale", "/震级；重要性", "/ˈmæɡnɪtuːd/", "n.", 6, 0.5, "The quake measured magnitude seven point two.", "这次地震震级为七点二级。", "a quake of great magnitude"),
  v("mass-evacuation-order", "/撤离；疏散", "/ɪˌvækjuˈeɪʃn/", "n.", 6, 0.5, "The evacuation saved thousands of lives.", "大撤离挽救了数千人的生命。", "order an evacuation"),
  v("disaster-relief-effort", "/救援；救济", "/rɪˈliːf/", "n.", 5, 0.4, "International relief teams poured into the region.", "国际救援队涌入该地区。", "lead relief efforts"),
  v("rising-sea-levels", "/海平面", "/ˈsiː ˌlevl/", "n.", 5, 0.45, "Sea levels rose eight inches last century.", "上个世纪海平面上升了八英寸。", "rising sea levels"),
  v("melting-ice-sheet", "/冰盖", "/aɪs ʃiːt/", "n.", 7, 0.6, "The Antarctic ice sheet keeps thinning.", "南极冰盖不断变薄。", "a melting ice sheet"),
  v("retreating-glacier", "/冰川", "/ˈɡleɪʃər/", "n.", 6, 0.5, "Glaciers feed Asia's major rivers.", "冰川滋养着亚洲的大河。", "a retreating glacier"),
  v("thawing-permafrost", "/永久冻土", "/ˈpɜːrməfrɔːst/", "n.", 7, 0.75, "Melting permafrost releases trapped methane.", "冻土融化释放出被困住的甲烷。", "thawing permafrost"),
  v("shifting-weather-pattern", "/天气模式", "/ˈweðər ˈpætərn/", "n.", 5, 0.45, "Weather patterns have shifted northward.", "天气模式已经北移。", "changing weather patterns"),
  v("monsoon-rainy-season", "/季风；雨季", "/mɑːnˈsuːn/", "n.", 7, 0.6, "Monsoon rains flooded the old city streets.", "季风雨淹没了老城街道。", "monsoon season arrives"),
  v("arid-desert-climate", "/干旱的；干燥的", "/ˈærɪd/", "adj.", 6, 0.5, "Arizona's arid air cracks your lips.", "亚利桑那干燥的空气会让嘴唇干裂。", "an arid climate zone"),
  v("barren-hillside", "/贫瘠的；荒芜的", "/ˈbærən/", "adj.", 6, 0.5, "The barren hillside held no trees at all.", "贫瘠的山坡上一棵树都没有。", "barren wasteland"),
  v("fertile-farmland", "/肥沃的；富饶的", "/ˈfɜːrtl/", "adj.", 5, 0.4, "Fertile soil along the river feeds millions.", "河流沿岸肥沃的土壤养活千百万人。", "deep fertile soil"),
  v("dense-vegetation-cover", "/植被", "/ˌvedʒəˈteɪʃn/", "n.", 6, 0.5, "Dense vegetation hides the old trail.", "茂密的植被遮住了古道。", "dense tropical vegetation"),
  v("rainforest-canopy-walk", "/林冠；顶篷", "/ˈkænopi/", "n.", 6, 0.55, "Monkeys moved noisily through the canopy.", "猴子在林冠间闹腾穿行。", "the forest canopy"),
  v("reforestation-program", "/重新造林", "/ˌriːfɔːrɪˈsteɪʃn/", "n.", 7, 0.7, "Reforestation began on the bare slopes.", "裸坡上开始了重新造林。", "a large-scale reforestation program"),
  v("environmentalist-group", "/环保主义者", "/ɪnˌvaɪrənˈmentəlɪst/", "n.", 6, 0.5, "Environmentalists sued the polluting factory.", "环保人士起诉了那家污染工厂。", "a leading environmentalist"),
  v("eco-friendly-product", "/环保的；生态友好的", "/ˈiːkoʊ ˈfrendli/", "adj.", 4, 0.35, "Swap to eco-friendly cleaning products.", "换用环保清洁产品。", "certified eco-friendly products"),
];
