import { v } from "@/content/vocab/builder";
import type { VocabRow } from "@/content/vocab/types";

/** Physics & energy - Phase 10 chunk-g. */
export const physicsEnergyRows: VocabRow[] = [
  v("kinetic-energy", "/动能", "/kɪˈnetɪk ˈenərdʒi/", "n.", 7, 0.65, "Speed doubles kinetic energy.", "速度使动能加倍。", "convert kinetic energy into heat"),
  v("potential-energy-store", "/势能", "/pəˈtenʃl ˈenərdʒi/", "n.", 7, 0.65, "Water behind the dam stores potential energy.", "坝后的水储存着势能。", "gravitational potential energy"),
  v("momentum-shift", "/动量；势头", "/moʊˈmentəm/", "n.", 5, 0.45, "The truck's momentum crushed the fence.", "卡车的动量撞毁了围栏。", "gain momentum quickly"),
  v("inertia-principle", "/惯性", "/ɪˈnɜːrʃə/", "n.", 7, 0.6, "Inertia pins you to the seat during takeoff.", "起飞时惯性把你压在座椅上。", "overcome inertia"),
  v("acceleration-rate", "/加速度；加速", "/əkˌseləˈreɪʃn/", "n.", 5, 0.45, "The sports car's acceleration stunned everyone.", "跑车的加速度惊呆了众人。", "rapid acceleration"),
  v("velocity-change", "/速度", "/vəˈlɑːsəti/", "n.", 6, 0.5, "Escape velocity exceeds eleven kilometers per second.", "逃逸速度超过每秒十一公里。", "constant velocity"),
  v("electric-current-flow", "/电流", "/ɪˈlektrɪk ˈkɜːrənt/", "n.", 4, 0.35, "Current flows only through closed circuits.", "电流只在闭合电路中流动。", "a direct current supply"),
  v("circuit-board-design", "/电路；回路", "/ˈsɜːrkɪt/", "n.", 4, 0.35, "One loose wire broke the whole circuit.", "一根松线断掉了整个电路。", "complete the circuit"),
  v("battery-voltage", "/电压", "/ˈvoʊltɪdʒ/", "n.", 6, 0.5, "High voltage lines hum overhead.", "头顶的高压线嗡嗡作响。", "check the voltage first"),
  v("resistance-training-physics", "/电阻；抵抗", "/rɪˈzɪstəns/", "n.", 5, 0.4, "Thicker wires offer less resistance.", "更粗的导线电阻更小。", "lower the resistance"),
  v("magnetic-field-lines", "/磁场", "/mæɡˈnetɪk fiːld/", "n.", 5, 0.45, "Compass needles align with magnetic fields.", "指南针与磁场方向一致。", "a strong magnetic field"),
  v("electromagnetic-spectrum", "/电磁的", "/ɪˌlektrɒmæɡˈnetɪk/", "adj.", 7, 0.7, "Electromagnetic waves carry radio signals.", "电磁波承载无线电信号。", "the electromagnetic spectrum"),
  v("wavelength-frequency", "/波长", "/ˈweɪvleŋθ/", "n.", 6, 0.55, "Red light has the longest wavelength.", "红光波长最长。", "a short wavelength signal"),
  v("frequency-range", "/频率", "/ˈfriːkwənsi/", "n.", 4, 0.35, "Bats call at ultrasonic frequencies.", "蝙蝠以超声波频率鸣叫。", "adjust the frequency"),
  v("sound-wave-travel", "/声波", "/saʊnd weɪv/", "n.", 4, 0.3, "Sound waves bend around open doors.", "声波会绕过敞开的门。", "high-frequency sound waves"),
  v("echo-location", "/回声；回响", "/ˈekoʊ/", "n./v.", 4, 0.3, "Our voices echoed through the empty hall.", "我们的声音在大厅里回荡。", "hear an echo return"),
  v("reflection-angle", "/反射；映像", "/rɪˈflekʃn/", "n.", 4, 0.3, "The lake gave a perfect reflection of the peak.", "湖面倒映出完美的山峰。", "see your reflection clearly"),
  v("light-refraction", "/折射", "/rɪˈfrækʃn/", "n.", 7, 0.65, "Refraction bends light entering water.", "折射使进入水中的光线弯曲。", "light refraction in glass"),
  v("transparent-material", "/透明的", "/trænsˈperənt/", "adj.", 4, 0.3, "Glass is transparent to visible light.", "玻璃对可见光是透明的。", "a transparent plastic sheet"),
  v("opaque-screen", "/不透明的", "/oʊˈpeɪk/", "adj.", 7, 0.6, "Fog turned the windows almost opaque.", "雾气使窗户几乎不透明。", "an opaque curtain"),
  v("radiant-heat-transfer", "/辐射的；光芒四射的", "/ˈreɪdiənt/", "adj.", 6, 0.55, "The fire sent radiant heat across the room.", "炉火的热辐射散满房间。", "a radiant heating panel"),
  v("conduction-of-heat", "/传导", "/kənˈdʌkʃn/", "n.", 7, 0.6, "Metal handles conduct heat by conduction.", "金属手柄通过传导传热。", "heat conduction through metal"),
  v("convection-current", "/对流", "/kənˈvekʃn/", "n.", 7, 0.65, "Convection stirs the boiling soup.", "对流搅动着沸腾的汤。", "a convection oven"),
  v("insulation-layer", "/绝缘；隔热", "/ˌɪnsəˈleɪʃn/", "n.", 6, 0.5, "Thick insulation cut our heating bill in half.", "厚隔热层使供暖账单减半。", "add attic insulation"),
  v("thermometer-reading", "/温度计", "/θərˈmɑːmɪtər/", "n.", 3, 0.25, "The thermometer hit forty degrees today.", "今天温度计升到四十度。", "read the thermometer carefully"),
  v("barometric-pressure-drop", "/气压计", "/bəˈrɑːmɪtər/", "n.", 7, 0.65, "A falling barometer warns of storms.", "气压下降预示风暴来临。", "watch the barometer closely"),
  v("nuclear-reactor-core", "/核反应堆", "/ˈnuːkliər ˈriːæktər/", "n.", 7, 0.7, "Engineers shut down the reactor within minutes.", "工程师们几分钟内关闭了反应堆。", "shut down the reactor"),
  v("nuclear-fission-process", "/核裂变", "/ˈfɪʒn/", "n.", 7, 0.75, "Fission splits heavy atomic nuclei.", "核裂变分裂重原子核。", "controlled nuclear fission"),
  v("fusion-power-research", "/核聚变；融合", "/ˈfjuːʒn/", "n.", 7, 0.75, "Fusion powers the sun itself.", "聚变为太阳本身提供能量。", "a fusion reactor prototype"),
  v("radioactive-waste-storage", "/放射性的", "/ˌreɪdioʊˈæktɪv/", "adj.", 7, 0.65, "Radioactive material needs thick shielding.", "放射性材料需要厚重屏蔽层。", "radioactive contamination"),
  v("power-grid-stability", "/电网", "/ˈpaʊər ɡrɪd/", "n.", 6, 0.5, "Storms overloaded the regional power grid.", "风暴使区域电网超载。", "connect to the power grid"),
  v("blackout-prevention", "/停电；断电", "/ˈblækdaʊt/", "n.", 5, 0.45, "A blackout plunged the stadium into darkness.", "停电使体育场陷入黑暗。", "a citywide blackout"),
  v("energy-efficiency-rating", "/效率", "/ɪˈfɪʃnsi/", "n.", 4, 0.3, "Insulation improves energy efficiency dramatically.", "隔热措施显著提高能源效率。", "boost energy efficiency"),
  v("horsepower-rating", "/马力", "/ˈhɔːrspaʊər/", "n.", 5, 0.4, "The engine delivers three hundred horsepower.", "这台发动机输出三百马力。", "a high-horsepower engine"),
  v("fuel-consumption-rate", "/消耗；消费", "/kənˈsʌmpʃn/", "n.", 5, 0.4, "City driving increases fuel consumption.", "城市驾驶增加油耗。", "reduce fuel consumption"),
  v("generator-backup-unit", "/发电机", "/ˈdʒenəreɪtər/", "n.", 5, 0.4, "The backup generator kicked in immediately.", "备用发电机立即启动。", "start the emergency generator"),
  v("turbine-blade-inspection", "/涡轮机；叶轮", "/ˈtɜːrbɪn/", "n.", 7, 0.65, "Steam spins the turbine at incredible speed.", "蒸汽以惊人速度驱动涡轮机。", "inspect the turbine blades"),
  v("photovoltaic-cell", "/光电伏打电池", "/ˌfoʊtoʊvɑːlˈteɪɪk sel/", "n.", 7, 0.8, "Photovoltaic cells turn sunlight into electricity.", "光伏电池把阳光变成电。", "install photovoltaic cells"),
  v("hydrogen-fuel-cell", "/燃料电池", "/ˈfjuːəl sel/", "n.", 7, 0.7, "Fuel cells power some city buses quietly.", "燃料电池安静地驱动一些城市公交。", "a hydrogen fuel cell vehicle"),
  v("energy-storage-battery", "/储能", "/ˈenərdʒi ˈstɔːrɪdʒ/", "n.", 6, 0.55, "Better storage solves renewable energy's biggest problem.", "更好的储能解决可再生能源最大难题。", "grid-scale energy storage"),
  v("motion-detector-sensor", "/运动；动作", "/ˈmoʊʃn/", "n.", 3, 0.25, "The security light responds to motion.", "安防灯对移动有感应。", "detect sudden motion"),
  v("wind-vector-plot", "/矢量", "/ˈvektər/", "n.", 7, 0.7, "Wind velocity has both speed and direction.", "风速既有大小又有方向（是矢量）。", "plot the wind vector"),
  v("equilibrium-state", "/平衡；均衡", "/ˌiːkwɪˈlɪbriəm/", "n.", 7, 0.65, "The seesaw found perfect equilibrium.", "跷跷板达到了完美平衡。", "reach thermal equilibrium"),
  v("pendulum-swing-motion", "/钟摆", "/ˈpendʒələm/", "n.", 7, 0.6, "The pendulum swung in steady rhythm.", "钟摆稳定地摆动。", "the pendulum swings wide"),
  v("lever-arm-length", "/杠杆", "/ˈlevər/", "n.", 6, 0.5, "A long lever lifts heavy stones easily.", "长杠杆轻松撬起巨石。", "pull the lever down"),
  v("pulley-system-load", "/滑轮", "/ˈpʊli/", "n.", 6, 0.5, "Sailors hoisted sails with pulleys.", "水手用滑轮升起船帆。", "a block-and-tackle pulley system"),
  v("coil-spring-mechanism", "/弹簧", "/kɔɪl sprɪŋ/", "n.", 6, 0.5, "The spring snapped back violently.", "弹簧猛烈弹回。", "compress the coil spring"),
  v("torque-specification", "/扭矩；转矩", "/tɔːrk/", "n.", 7, 0.7, "Diesel engines produce huge torque at low revs.", "柴油机低转速时产生巨大扭矩。", "apply maximum torque"),
  v("air-resistance-force", "/空气阻力", "/er rɪˈzɪstəns/", "n.", 6, 0.5, "Air resistance slows falling leaves gently.", "空气阻力使落叶缓缓飘落。", "reduce air resistance"),
  v("terminal-velocity-physics", "/终端速度", "/ˈtɜːrmɪnl vəˈlɑːsəti/", "n.", 7, 0.75, "Skydivers fall at terminal velocity after ten seconds.", "跳伞者十秒后达到终端速度。", "reach terminal velocity"),
  v("sonic-boom-test", "/音爆；音速的", "/ˈsɑːnɪk/", "adj.", 7, 0.65, "Concorde flew faster than sonic speed.", "协和客机以超音速飞行。", "break the sonic barrier"),
  v("ultrasound-imaging-scan", "/超声波", "/ˈʌltrəsaʊnd/", "n.", 6, 0.55, "Ultrasound revealed a healthy baby.", "超声波显示胎儿健康。", "an ultrasound scan appointment"),
  v("x-ray-machine-operator", "/X光；X射线", "/ˈeks reɪ/", "n.", 5, 0.4, "X-rays showed a hairline fracture.", "X光片显示一处细微骨裂。", "take an X-ray image"),
  v("laser-beam-pointer", "/激光", "/ˈleɪzər/", "n.", 5, 0.4, "Laser surgery heals eyes overnight.", "激光手术一夜修复视力。", "a laser cutting beam"),
  v("fiber-optic-cable-network", "/光纤", "/ˈfaɪbər ˈɑːptɪk/", "adj./n.", 6, 0.55, "Fiber-optic lines carry the internet under oceans.", "光纤线路横跨海底传输互联网。", "a fiber-optic backbone"),
  v("semiconductor-chip-plant", "/半导体", "/ˌsemiənˈdʌktər/", "n.", 7, 0.7, "Semiconductors run every modern device.", "半导体驱动所有现代设备。", "a semiconductor fabrication plant"),
  v("superconductor-research-lab", "/超导体", "/ˌsuːpərkənˈdʌktər/", "n.", 7, 0.8, "Superconductors carry current without any loss.", "超导体输电毫无损耗。", "cryogenic superconductors"),
  v("quantum-computing-lab", "/量子的", "/ˈkwɑːntəm/", "adj./n.", 7, 0.75, "Quantum computers may crack today's encryption.", "量子计算机可能破解现有加密。", "quantum computing power"),
];
