import { v } from "@/content/vocab/builder";
import type { VocabRow } from "@/content/vocab/types";

/** Chemistry & materials - Phase 10 chunk-g. */
export const chemistryMaterialsRows: VocabRow[] = [
  v("periodic-table-chart", "/元素周期表", "/ˌpɪriˈɑːdɪk ˈteɪbl/", "n.", 6, 0.5, "Hydrogen tops the periodic table.", "氢排在元素周期表首位。", "memorize the periodic table"),
  v("element-symbol-memorize", "/元素；要素", "/ˈelɪmənt/", "n.", 3, 0.3, "Gold is a precious element.", "黄金是一种贵重元素。", "a chemical element"),
  v("noble-gas-family", "/惰性气体", "/ˈnoʊbl ɡæs/", "n.", 7, 0.7, "Helium belongs to the noble gases.", "氦属于惰性气体。", "an inert noble gas"),
  v("alkali-metal-reaction", "/碱金属", "/ˈælkəlaɪ ˈmetl/", "n.", 7, 0.75, "Alkali metals explode in water.", "碱金属遇水爆炸。", "a reactive alkali metal"),
  v("acid-base-reaction", "/酸；酸的", "/ˈæsɪd/", "n./adj.", 5, 0.4, "Lemon juice tastes sharp because it is acid.", "柠檬汁味道尖酸因为它是酸性的。", "a mild household acid"),
  v("alkaline-soil-treatment", "/碱性的", "/ˈælkəlaɪn/", "adj.", 7, 0.65, "Alkaline water tastes slightly soapy.", "碱性水喝起来有点像肥皂水。", "slightly alkaline soil"),
  v("ph-balance-strip", "/pH值；酸碱度", "/ˌpiː ˈeɪtʃ/", "n.", 6, 0.55, "Test the pool's pH weekly.", "每周检测泳池的pH值。", "check the pH level"),
  v("ion-charge-transfer", "/离子", "/ˈaɪən/", "n.", 7, 0.65, "Salt dissolves into charged ions.", "盐溶解成带电离子。", "positively charged ions"),
  v("isotope-dating-method", "/同位素", "/ˈaɪsətoʊp/", "n.", 7, 0.75, "Carbon isotopes date ancient bones.", "碳同位素可测定古骨年代。", "a radioactive isotope"),
  v("electron-shell-diagram", "/电子", "/ɪˈlektrɑːn/", "n.", 5, 0.45, "Electrons orbit the atomic nucleus.", "电子绕原子核运转。", "free electrons flow"),
  v("neutron-particle-beam", "/中子", "/ˈnuːtrɑːn/", "n.", 7, 0.7, "Neutrons carry no electric charge.", "中子不带电荷。", "a neutron star core"),
  v("proton-beam-therapy", "/质子", "/ˈproʊtɑːn/", "n.", 7, 0.7, "Protons sit at the atom's heart.", "质子位于原子中心。", "proton beam therapy"),
  v("organic-compound-list", "/有机化合物", "/ɔːrˈɡænɪk ˈkɑːmpaʊnd/", "n.", 7, 0.65, "Petroleum is a mix of organic compounds.", "石油是多种有机化合物的混合物。", "volatile organic compounds"),
  v("synthetic-material-lab", "/合成的；人造的", "/sɪnˈθetɪk/", "adj.", 5, 0.45, "Synthetic fabrics dry twice as fast.", "合成面料干得快一倍。", "synthetic rubber seals"),
  v("polymer-chain-science", "/聚合物", "/ˈpɑːlɪmər/", "n.", 7, 0.75, "Plastics are long polymer chains.", "塑料是长长的聚合物链。", "a durable polymer coating"),
  v("alloy-metal-blend", "/合金", "/ˈælɔɪ/", "n.", 6, 0.55, "Bronze is a copper-tin alloy.", "青铜是铜锡合金。", "a lightweight aluminum alloy"),
  v("stainless-steel-sink", "/不锈钢", "/ˈsteɪnləs stiːl/", "n.", 4, 0.35, "Stainless steel resists rust for decades.", "不锈钢数十年不生锈。", "brushed stainless steel finish"),
  v("carbon-fiber-frame", "/碳纤维", "/ˈkɑːrbən ˈfaɪbər/", "n.", 6, 0.6, "Carbon fiber makes bikes feather-light.", "碳纤维让自行车轻如鸿毛。", "a carbon fiber bicycle frame"),
  v("ceramic-tile-floor", "/陶瓷的", "/səˈræmɪk/", "adj./n.", 5, 0.45, "Ceramic tiles keep floors cool in summer.", "夏季瓷砖地面保持凉爽。", "glazed ceramic tiles"),
  v("porcelain-teacup-set", "/瓷器", "/ˈpɔːrsəlɪn/", "n.", 6, 0.55, "Delicate porcelain chips easily.", "精致的瓷器容易磕碰缺口。", "fine white porcelain"),
  v("glass-recycling-bin", "/玻璃", "/ɡlæs/", "n.", 1, 0.1, "Recycle every glass bottle you use.", "把用过的每个玻璃瓶都回收。", "frosted glass panels"),
  v("rubber-gasket-seal", "/橡胶", "/ˈrʌbər/", "n.", 3, 0.25, "Rubber boots survived the muddy field.", "橡胶靴在泥地里完好无损。", "hardened rubber soles"),
  v("concrete-pouring-truck", "/混凝土", "/ˈkɑːŋkriːt/", "n./adj.", 5, 0.4, "Concrete needs days to fully cure.", "混凝土需要数天完全凝固。", "reinforced concrete pillars"),
  v("asphalt-road-repair", "/沥青", "/ˈæsfɔːlt/", "n.", 6, 0.6, "Fresh asphalt softened in the heat.", "新铺的沥青在高温下变软。", "an asphalt parking lot"),
  v("timber-frame-house", "/木材；木料", "/ˈtɪmbər/", "n.", 5, 0.4, "Old barns were built from local timber.", "旧谷仓用当地木料建成。", "sustainable timber supplies"),
  v("plywood-sheet-price", "/胶合板", "/ˈplaɪwʊd/", "n.", 6, 0.6, "Plywood sheets lined the truck bed.", "胶合板垫在卡车车斗里。", "waterproof plywood sheets"),
  v("fiberglass-insulation-roll", "/玻璃纤维", "/ˈfaɪbərɡlæs/", "n.", 7, 0.7, "Fiberglass insulation keeps attics warm.", "玻璃纤维保温层为阁楼保暖。", "fiberglass insulation rolls"),
  v("silicone-sealant-gun", "/硅胶；硅酮", "/ˈsɪlɪkoʊn/", "n.", 7, 0.65, "Silicone caulk sealed the leaky tub edge.", "硅胶密封剂堵住了浴缸渗漏边缘。", "food-grade silicone rings"),
  v("lubricant-oil-change", "/润滑剂", "/ˈluːbrɪkənt/", "n.", 7, 0.65, "A good lubricant silences squeaky hinges.", "好的润滑剂消除铰链吱吱声。", "apply a silicone lubricant"),
  v("adhesive-tape-strength", "/粘合剂；带黏性的", "/ədˈhiːsɪv/", "n./adj.", 7, 0.6, "Strong adhesive holds the mirror firmly.", "强力粘合剂牢牢固定镜子。", "industrial adhesive strips"),
  v("dissolve-fully", "/溶解；解散", "/dɪˈzɑːlv/", "v.", 5, 0.5, "Sugar dissolves faster in hot tea.", "糖在热茶里溶解得更快。", "dissolve completely in water"),
  v("crystalline-structure-model", "/结晶的；水晶般的", "/ˈkrɪstəlɪn/", "adj.", 7, 0.7, "Snowflakes show perfect crystalline patterns.", "雪花呈现完美的晶体图案。", "a crystalline mountain lake"),
  v("corrosion-resistant-coating", "/腐蚀", "/kəˈroʊʒn/", "n.", 7, 0.65, "Salt spray accelerates corrosion on cars.", "盐雾加速汽车腐蚀。", "protect against corrosion"),
  v("rust-proof-treatment", "/锈；铁锈", "/rʌst/", "n./v.", 4, 0.35, "Rust crept across the old gate.", "铁锈爬满旧大门。", "cover the chain in rust"),
  v("toxic-chemical-spill", "/有毒的", "/ˈtɑːksɪk/", "adj.", 4, 0.35, "Never mix toxic cleaning agents together.", "切勿混合使用有毒清洁剂。", "highly toxic fumes"),
  v("flammable-label-warning", "/易燃的", "/ˈflæməbl/", "adj.", 6, 0.55, "Gasoline is highly flammable.", "汽油极易燃。", "keep away from flammable materials"),
  v("explosive-device-disposal", "/爆炸性的；炸药", "/ɪkˈsploʊsɪv/", "adj./n.", 6, 0.55, "Miners handle explosive charges carefully.", "矿工小心处理炸药。", "an explosive atmosphere"),
  v("laboratory-glassware-set", "/玻璃器皿", "/ˈɡlæswer/", "n.", 7, 0.65, "Rinse all glassware after each experiment.", "每次实验后冲洗所有玻璃器皿。", "clean laboratory glassware"),
  v("test-tube-rack", "/试管", "/ˈtest tuːb/", "n.", 5, 0.4, "The liquid changed color in the test tube.", "试管里的液体变了颜色。", "a rack of test tubes"),
  v("bunsen-burner-flame", "/本生灯；煤气喷灯", "/ˈbʌnsən ˈbɜːrnər/", "n.", 7, 0.7, "Adjust the Bunsen burner to a blue flame.", "把本生灯调成蓝色火焰。", "light the Bunsen burner"),
  v("safety-goggles-required", "/安全护目镜", "/ˈsæfti ˈɡɑːɡlz/", "n.", 5, 0.4, "Safety goggles are required near acids.", "接触酸类必须戴安全护目镜。", "wear safety goggles"),
  v("chemical-reaction-rate", "/化学反应", "/ˈkemɪkl riˈækʃn/", "n.", 5, 0.45, "Heat speeds up any chemical reaction.", "加热会加速任何化学反应。", "trigger a chemical reaction"),
  v("combustible-material-storage", "/可燃的", "/kəmˈbʌstəbl/", "adj.", 7, 0.7, "Sawdust is surprisingly combustible.", "锯末竟然是可燃的。", "store combustibles safely"),
  v("gas-leak-detector-alarm", "/气体泄漏", "/ɡæs liːk/", "n.", 5, 0.45, "The detector caught a gas leak early.", "探测器及早发现了燃气泄漏。", "report a gas leak immediately"),
  v("oxygen-tank-refill", "/氧气", "/ˈɑːksɪdʒən/", "n.", 3, 0.3, "Divers check their oxygen twice.", "潜水员两次检查氧气。", "run low on oxygen"),
  v("nitrogen-fertilizer-use", "/氮", "/ˈnaɪtrədʒən/", "n.", 6, 0.6, "Nitrogen makes up most of the air.", "氮占空气的大部分。", "nitrogen-rich fertilizer"),
  v("methane-gas-emission", "/甲烷；沼气", "/ˈmeθeɪn/", "n.", 7, 0.65, "Cows release methane when digesting.", "牛消化时会释放甲烷。", "capture methane emissions"),
  v("chlorine-pool-treatment", "/氯", "/ˈklɔːriːn/", "n.", 6, 0.6, "Chlorine keeps pool water germ-free.", "氯保持泳池水质无菌。", "add chlorine tablets"),
  v("bleach-stain-removal", "/漂白剂；漂白", "/bliːtʃ/", "n./v.", 5, 0.45, "Bleach whitens grout lines quickly.", "漂白剂迅速使填缝剂变白。", "dilute the bleach first"),
  v("rust-remover-solution", "/溶液；解决方案", "/səˈluːʃn/", "n.", 3, 0.3, "Try this simple solution tonight.", "今晚试试这个简单的办法。", "an effective temporary solution"),
  v("detergent-laundry-powder", "/洗涤剂", "/dɪˈtɜːrdʒənt/", "n.", 5, 0.45, "Use less detergent for smaller loads.", "小件衣物少用洗涤剂。", "a gentle laundry detergent"),
  v("pesticide-spray-drift", "/杀虫剂", "/ˈpestɪsaɪd/", "n.", 7, 0.65, "Organic farms avoid synthetic pesticides.", "有机农场不用合成杀虫剂。", "spray pesticide at dusk"),
  v("herbicide-weed-control", "/除草剂", "/ˈhɜːrbɪsaɪd/", "n.", 7, 0.7, "Herbicides killed every weed overnight.", "除草剂一夜之间除尽杂草。", "apply herbicide sparingly"),
  v("preservative-food-additive", "/防腐剂", "/prɪˈzɜːrvətɪv/", "n.", 7, 0.65, "This bread contains no preservatives.", "这种面包不含防腐剂。", "free of artificial preservatives"),
  v("antibiotic-course-complete", "/抗生素", "/ˌæntibaɪˈɑːtɪk/", "n.", 5, 0.5, "Finish the whole antibiotic course.", "服完整个抗生素疗程。", "prescribe antibiotics"),
  v("vaccine-booster-shot", "/疫苗", "/vækˈsiːn/", "n.", 4, 0.35, "Flu vaccines change every year.", "流感疫苗每年都更新。", "get vaccinated early"),
  v("insulin-injection-site", "/胰岛素", "/ˈɪnsəlɪn/", "n.", 6, 0.6, "Diabetics inject insulin daily.", "糖尿病患者每天注射胰岛素。", "regulate insulin levels"),
  v("caffeine-intake-limit", "/咖啡因", "/kæˈfiːn/", "n.", 4, 0.35, "Cut caffeine after noon for better sleep.", "中午后戒咖啡因有助睡眠。", "limit daily caffeine intake"),
];
