import { v } from "@/content/vocab/builder";
import type { VocabRow } from "@/content/vocab/types";

/** Biology, genetics & evolution - Phase 10 chunk-g. */
export const biologyGeneticsRows: VocabRow[] = [
  v("cell-division-process", "/细胞", "/sel/", "n.", 4, 0.3, "Every organ starts as a single cell.", "每个器官都始于一个细胞。", "cell division and growth"),
  v("nucleus-control-center", "/细胞核；核心", "/ˈnuːkliəs/", "n.", 7, 0.6, "The nucleus stores genetic instructions.", "细胞核储存遗传指令。", "the cell's nucleus"),
  v("membrane-bound-organelle", "/膜；薄膜", "/ˈmembreɪn/", "n.", 7, 0.65, "A thin membrane surrounds each cell.", "一层薄膜包裹着每个细胞。", "the cell membrane"),
  v("enzyme-digestion-aid", "/酶", "/ˈenzaɪm/", "n.", 7, 0.7, "Enzymes break food into nutrients.", "酶把食物分解成养分。", "digestive enzymes"),
  v("hormone-level-balance", "/激素；荷尔蒙", "/ˈhɔːrmoʊn/", "n.", 5, 0.5, "Stress hormones spike before exams.", "考前压力激素飙升。", "a hormonal imbalance"),
  v("chromosome-pair-count", "/染色体", "/ˈkroʊməsoʊm/", "n.", 7, 0.7, "Humans carry twenty-three chromosome pairs.", "人类有二十三对染色体。", "an extra chromosome"),
  v("gene-editing-technology", "/基因", "/dʒiːn/", "n.", 5, 0.5, "One gene can change flower color completely.", "一个基因就能完全改变花的颜色。", "edit a single gene"),
  v("genome-mapping-project", "/基因组", "/ˈdʒiːnoʊm/", "n.", 7, 0.75, "Scientists mapped the rice genome.", "科学家绘制了水稻基因组图谱。", "sequence the whole genome"),
  v("dna-sequence-data", "/DNA；脱氧核糖核酸", "/ˌdiː en ˈeɪ/", "n.", 5, 0.45, "DNA carries the blueprint of life.", "DNA携带生命的蓝图。", "analyze DNA samples"),
  v("rna-vaccine-platform", "/RNA；核糖核酸", "/ˌɑːr en ˈeɪ/", "n.", 7, 0.75, "Messenger RNA teaches cells to build proteins.", "信使RNA教细胞制造蛋白质。", "an RNA-based therapy"),
  v("protein-synthesis-step", "/蛋白质", "/ˈproʊtiːn/", "n.", 4, 0.35, "Eggs supply cheap high-quality protein.", "鸡蛋提供廉价优质蛋白。", "a protein-rich diet"),
  v("amino-acid-chain", "/氨基酸", "/əˌmiːnoʊ ˈæsɪd/", "n.", 7, 0.75, "Twenty amino acids build human proteins.", "二十种氨基酸构成人体蛋白质。", "essential amino acids"),
  v("mutation-rate-study", "/突变；变异", "/mjuːˈteɪʃn/", "n.", 7, 0.7, "Radiation raises the mutation rate.", "辐射会提高突变率。", "a harmful genetic mutation"),
  v("heredity-family-tree", "/遗传；世袭", "/həˈredəti/", "n.", 7, 0.65, "Heredity explains family resemblances.", "遗传解释了家族相似性。", "the laws of heredity"),
  v("dominant-trait-inheritance", "/显性的；占优势的", "/ˈdɑːmɪnənt/", "adj.", 5, 0.5, "Brown eyes are a dominant trait.", "棕色眼睛是显性性状。", "a dominant gene version"),
  v("recessive-gene-carrier", "/隐性的", "/rɪˈsesɪv/", "adj.", 7, 0.7, "Blue eyes need two recessive copies.", "蓝眼睛需要两个隐性拷贝。", "carry a recessive disorder"),
  v("natural-selection-theory", "/自然选择", "/ˈnætʃrəl sɪˈlekʃn/", "n.", 6, 0.55, "Natural selection favors helpful traits.", "自然选择青睐有利性状。", "drive natural selection"),
  v("evolutionary-biology-class", "/进化的；演变的", "/ˌevəˈluːʃəneri/", "adj.", 6, 0.6, "Whales show clear evolutionary leftovers.", "鲸鱼身上有明显进化残留。", "an evolutionary advantage"),
  v("adaptation-survival-strategy", "/适应；改编", "/ˌædæpˈteɪʃn/", "n.", 4, 0.35, "Camels' humps are a desert adaptation.", "驼峰是沙漠适应性进化的产物。", "a remarkable adaptation"),
  v("species-diversity-survey", "/物种", "/ˈspiːʃiːz/", "n.", 4, 0.35, "This valley hosts over forty bird species.", "这条山谷栖息四十多种鸟类。", "an endangered species survey"),
  v("organism-microscope-view", "/生物体；有机体", "/ˈɔːrɡənɪzəm/", "n.", 6, 0.55, "Soil teems with tiny organisms.", "土壤里满是微小生物。", "a living organism"),
  v("photosynthesis-light-reaction", "/光合作用", "/ˌfoʊtoʊˈsɪnθəsɪs/", "n.", 7, 0.7, "Photosynthesis turns light into sugar.", "光合作用把光变成糖。", "the process of photosynthesis"),
  v("respiration-breathing-cycle", "/呼吸", "/ˌrespəˈreɪʃn/", "n.", 5, 0.45, "Deep respiration calms the nerves.", "深呼吸能安抚神经。", "control your respiration rate"),
  v("circulation-blood-flow", "/循环；流通", "/ˌsɜːrkjəˈleɪʃn/", "n.", 5, 0.45, "Exercise improves blood circulation fast.", "运动快速改善血液循环。", "boost blood circulation"),
  v("metabolism-boosting-foods", "/新陈代谢", "/məˈtæbəlɪzəm/", "n.", 6, 0.6, "Muscle raises your resting metabolism.", "肌肉提高静息代谢率。", "a slow metabolism complaint"),
  v("immune-system-defense", "/免疫系统", "/ɪˈmjuːn ˈsɪstəm/", "n.", 5, 0.45, "Sleep strengthens your immune system.", "睡眠增强免疫系统。", "a weak immune system"),
  v("antibody-response-test", "/抗体", "/ˈæntibɑːdi/", "n.", 7, 0.7, "Antibodies remember old invaders.", "抗体会记住旧的入侵者。", "produce antibodies naturally"),
  v("tissue-sample-analysis", "/组织", "/ˈtɪʃuː/", "n.", 5, 0.45, "Doctors examined the tissue under magnification.", "医生在放大镜下检查组织。", "scar tissue removal"),
  v("nerve-signal-transmission", "/神经", "/nɜːrv/", "n.", 3, 0.3, "A pinched nerve caused the tingling.", "神经受压导致刺痛感。", "calm irritated nerves"),
  v("neuron-brain-cell-network", "/神经元", "/ˈnʊrɑːn/", "n.", 7, 0.7, "The brain wires billions of neurons together.", "大脑把数十亿神经元连接起来。", "activate dormant neurons"),
  v("synapse-connection-point", "/突触", "/ˈsɪnæps/", "n.", 7, 0.8, "Learning strengthens synaptic connections.", "学习会强化突触连接。", "form new synapses"),
  v("reflex-action-test", "/反射；本能反应", "/ˈriːfleks/", "n.", 5, 0.45, "Knee reflexes test nerve health.", "膝跳反射检测神经健康。", "a lightning-fast reflex"),
  v("stem-cell-research-lab", "/干细胞", "/stem sel/", "n.", 7, 0.7, "Stem cells may repair damaged hearts.", "干细胞或许能修复受损心脏。", "embryonic stem cell lines"),
  v("clone-identical-copy", "/克隆；复制", "/kloʊn/", "n./v.", 6, 0.6, "Dolly was history's first cloned sheep.", "多莉是史上第一只克隆羊。", "clone an endangered animal"),
  v("fertilization-success-rate", "/受精", "/ˌfɜːrtələˈzeɪʃn/", "n.", 7, 0.65, "Cold weather reduced fertilization success.", "寒冷天气降低了受精成功率。", "in vitro fertilization treatment"),
  v("embryo-development-stage", "/胚胎", "/ˈembrioʊ/", "n.", 7, 0.7, "The embryo doubles in size weekly.", "胚胎每周体积翻倍。", "an early-stage embryo"),
  v("pregnancy-trimester-guide", "/怀孕；妊娠", "/ˈpreɡnənsi/", "n.", 4, 0.35, "Pregnancy lasts about forty weeks.", "孕期约四十周。", "a healthy pregnancy diet"),
  v("offspring-generation-gap", "/后代；幼崽", "/ˈɔːfsprɪŋ/", "n.", 6, 0.55, "Birds feed their offspring tirelessly.", "鸟不知疲倦地喂养后代。", "raise healthy offspring"),
  v("predator-prey-relationship", "/捕食者", "/ˈpredətər/", "n.", 6, 0.55, "Owls are silent night predators.", "猫头鹰是无声的夜间猎手。", "escape from predators"),
  v("camouflage-nature-mastery", "/伪装", "/ˈkæməflɑːʒ/", "n./v.", 7, 0.6, "Cuttlefish camouflage beats any costume.", "乌贼的伪装胜过任何戏服。", "blend in using camouflage"),
  v("hibernation-winter-sleep", "/冬眠", "/ˌhaɪbərˈneɪʃn/", "n.", 7, 0.65, "Bears wake briefly during hibernation.", "熊在冬眠中短暂苏醒。", "enter deep hibernation"),
  v("migration-route-tracking", "/迁徙；移居", "/maɪˈɡreɪʃn/", "n.", 5, 0.45, "Geese follow ancient migration routes.", "雁群沿古老迁徙路线飞行。", "track bird migration"),
  v("habitat-restoration-plan", "/栖息地恢复计划", "/ˈhæbɪtæt ˌrestəˈreɪʃn/", "n.", 7, 0.65, "Wetland restoration brought herons back.", "湿地恢复让鹭鸟回归。", "fund habitat restoration projects"),
  v("pollination-bee-service", "/授粉", "/ˌpɑːləˈneɪʃn/", "n.", 7, 0.7, "Bees handle most crop pollination.", "蜜蜂承担大部分作物授粉。", "support pollinator populations"),
  v("germination-seed-sprouting", "/发芽", "/ˌdʒɜːrmɪˈneɪʃn/", "n.", 7, 0.7, "Warm soil speeds seed germination.", "温暖的土壤加快种子发芽。", "watch germination begin"),
  v("botany-plant-science-course", "/植物学", "/ˈbɑːtəni/", "n.", 7, 0.7, "Botany reveals hidden plant intelligence.", "植物学揭示植物隐秘的智能。", "study botany outdoors"),
  v("entomology-insect-study", "/昆虫学", "/ˌentəˈmɑːlədʒi/", "n.", 7, 0.8, "Entomology catalogs millions of beetle species.", "昆虫学编目了数百万种甲虫。", "a career in entomology"),
  v("zoology-animal-department", "/动物学", "/zoʊˈɑːlədʒi/", "n.", 7, 0.75, "Zoology students dissect squid on Fridays.", "动物学学生周五解剖鱿鱼。", "a zoology field trip"),
  v("ecology-field-station", "/生态学", "/iˈkɑːlədʒi/", "n.", 6, 0.6, "Ecology links wolves to river health.", "生态学把狼与河流健康联系起来。", "population ecology research"),
  v("microbiology-lab-course", "/微生物学", "/ˌmaɪkroʊbaɪˈɑːlədʒi/", "n.", 7, 0.75, "Microbiology uncovered the gut's second brain.", "微生物学发现了肠道这个第二大脑。", "a microbiology degree program"),
];
