import { v } from "@/content/vocab/builder";
import type { VocabRow } from "@/content/vocab/types";

/** Math & quantitative concepts - Phase 10 chunk-g. */
export const mathConceptRows: VocabRow[] = [
  v("algebra-equation-solve", "/代数", "/ˈældʒɪbrə/", "n.", 6, 0.6, "Algebra turns word problems into symbols.", "代数把文字题变成符号。", "an algebra homework assignment"),
  v("geometry-angle-rules", "/几何；几何学", "/dʒiˈɑːmətri/", "n.", 6, 0.6, "Geometry explains why bridges stand.", "几何学解释桥梁为何屹立。", "a plane geometry proof"),
  v("calculus-course-load", "/微积分", "/ˈkælkjələs/", "n.", 7, 0.7, "Calculus tracks changing quantities.", "微积分研究变化的量。", "pass the calculus exam"),
  v("statistics-report-data", "/统计学；统计数字", "/stəˈtɪstɪks/", "n.", 5, 0.5, "Statistics turn guesses into decisions.", "统计学把猜测变成决策。", "reliable crime statistics"),
  v("probability-odds-calculate", "/概率；可能性", "/ˌprɑːbəˈbɪləti/", "n.", 5, 0.5, "The probability of rain is eighty percent.", "降雨概率为百分之八十。", "calculate the probability exactly"),
  v("percentage-point-difference", "/百分比", "/pərˈsentɪdʒ/", "n.", 3, 0.25, "Prices rose by a small percentage.", "价格小幅上涨了几个百分点。", "a percentage of the profits"),
  v("average-mean-value", "/平均的；平均数", "/ˈævərɪdʒ/", "adj./n.", 2, 0.15, "The average family owns two cars.", "普通家庭平均有两辆车。", "above average performance"),
  v("median-household-income", "/中位数", "/ˈmiːdiən/", "n.", 6, 0.55, "The median price hides luxury outliers.", "中位数价格掩盖了豪宅离群值。", "the median income level"),
  v("ratio-proportion-formula", "/比率", "/ˈreɪʃioʊ/", "n.", 4, 0.4, "Mix concrete at a three-to-one ratio.", "混凝土按三比一的比率混合。", "in a fixed ratio"),
  v("fraction-bar-compare", "/分数；部分", "/ˈfrækʃn/", "n.", 3, 0.35, "Only a fraction of applicants got interviews.", "只有一小部分申请者获得面试。", "a tiny fraction of sales"),
  v("decimal-point-placement", "/小数；十进制的", "/ˈdesɪml/", "n./adj.", 4, 0.35, "One misplaced decimal ruined the invoice.", "一个错位的小数点毁掉了发票。", "round to two decimal places"),
  v("integer-whole-number", "/整数", "/ˈɪntɪdʒər/", "n.", 7, 0.65, "Integers exclude fractions entirely.", "整数完全排除分数。", "positive integers only"),
  v("negative-number-rule", "/负数；消极的", "/ˈneɡətɪv/", "adj./n.", 2, 0.2, "Negative numbers sit left of zero.", "负数位于零的左侧。", "test negative for the virus"),
  v("prime-number-list", "/质数；素数", "/praɪm/", "adj./n.", 6, 0.55, "Seven is the fourth prime number.", "七是第四个质数。", "a prime factor check"),
  v("square-root-estimate", "/平方根", "/skwer ruːt/", "n.", 5, 0.5, "The square root of sixteen is four.", "十六的平方根是四。", "take the square root"),
  v("exponential-growth-curve", "/指数的", "/ˌekspəˈnenʃl/", "adj.", 7, 0.65, "Compound interest creates exponential growth.", "复利带来指数级增长。", "exponential growth in users"),
  v("logarithm-scale-chart", "/对数", "/ˈlɔːɡərɪðəm/", "n.", 7, 0.8, "Earthquake scales use logarithms.", "地震震级用对数标度。", "plot on a logarithmic scale"),
  v("graph-axis-label", "/图表；曲线图", "/ɡræf/", "n.", 3, 0.25, "The graph peaks every summer.", "曲线每年夏天达到峰值。", "plot data on a graph"),
  v("chart-pie-diagram", "/图表", "/tʃɑːrt/", "n.", 2, 0.2, "The pie chart shows spending by category.", "饼状图按类别展示支出。", "read the chart carefully"),
  v("axis-coordinate-plane", "/坐标轴", "/ˈæksɪs/", "n.", 6, 0.55, "Label both axes before plotting.", "绘图前先标注两个坐标轴。", "the horizontal axis line"),
  v("coordinate-grid-map", "/坐标", "/koʊˈɔːrdɪnət/", "n.", 6, 0.55, "Give me the exact GPS coordinates.", "给我精确的GPS坐标。", "report your coordinates"),
  v("angle-degree-measure", "/角度；度", "/ˈæŋɡl/", "n.", 3, 0.3, "A right angle measures ninety degrees.", "直角是九十度。", "measure the angle precisely"),
  v("triangle-shape-type", "/三角形", "/ˈtraɪæŋɡl/", "n.", 3, 0.3, "Roof trusses form strong triangles.", "屋架构成稳固的三角形。", "an equilateral triangle"),
  v("circle-radius-line", "/圆；圈子", "/ˈsɜːrkl/", "n.", 2, 0.2, "The kids sat in a circle.", "孩子们围坐成一圈。", "draw a perfect circle"),
  v("circumference-formula-use", "/周长", "/sərˈkʌmfərəns/", "n.", 7, 0.7, "Circumference equals pi times diameter.", "周长等于圆周率乘直径。", "measure the circumference"),
  v("perimeter-fence-length", "/周长；周边", "/pəˈrɪmɪtər/", "n.", 6, 0.6, "Guards patrol the prison perimeter.", "警卫沿监狱围墙巡逻。", "secure the building perimeter"),
  v("area-surface-measure", "/面积；地区", "/ˈeriə/", "n.", 1, 0.1, "The room's area is twenty square meters.", "房间面积是二十平方米。", "calculate the floor area"),
  v("tank-volume-capacity", "/体积；容积", "/ˈvɑːljəm/", "n.", 4, 0.35, "The tank holds fifty liters by volume.", "水箱容积五十升。", "double the container volume"),
  v("symmetry-butterfly-wing", "/对称", "/ˈsɪmətri/", "n.", 6, 0.6, "Butterfly wings show near-perfect symmetry.", "蝴蝶翅膀近乎完美对称。", "broken symmetry patterns"),
  v("sequence-pattern-find", "/序列；顺序", "/ˈsiːkwəns/", "n.", 4, 0.35, "Follow the number sequence carefully.", "仔细跟着这组数列走。", "continue the sequence"),
  v("pattern-recognition-skill", "/模式；图案", "/ˈpætərn/", "n.", 3, 0.3, "Traders hunt repeating chart patterns.", "交易者寻找重复出现的图表形态。", "spot the emerging pattern"),
  v("estimate-guess-close", "/估计；估算", "/ˈestɪmeɪt/", "v./n.", 3, 0.3, "Estimate the bill before ordering.", "点单前先估算账单。", "a rough cost estimate"),
  v("calculate-exact-total", "/计算", "/ˈkælkjuleɪt/", "v.", 3, 0.3, "Calculate the tip mentally.", "心算小费。", "calculate quickly and accurately"),
  v("measurement-unit-convert", "/测量；度量", "/ˈmeʒərmənt/", "n.", 4, 0.35, "Convert measurements before baking.", "烘焙前先转换计量单位。", "take precise measurements"),
  v("conversion-rate-table", "/换算；转变", "/kənˈvɜːrʒn/", "n.", 5, 0.45, "Check the conversion rate before exchanging money.", "换钱前先看汇率。", "a smooth metric conversion"),
  v("multiply-times-table", "/乘", "/ˈmʌltɪplaɪ/", "v.", 2, 0.15, "Multiply six by seven to get forty-two.", "六乘七等于四十二。", "multiply quickly in your head"),
  v("divide-share-equally", "/除；分开", "/dɪˈvaɪd/", "v.", 2, 0.15, "Divide the pizza into eight slices.", "把比萨分成八块。", "divide the profits equally"),
  v("subtract-minus-sign", "/减去", "/səbˈtrækt/", "v.", 3, 0.25, "Subtract expenses from gross income.", "从总收入中减去开支。", "subtract the discount first"),
  v("addition-sum-total", "/加法；附加物", "/əˈdɪʃn/", "n.", 2, 0.15, "In addition, we offer free delivery.", "此外，我们还提供免费配送。", "in addition to the fee"),
  v("infinity-symbol-meaning", "/无穷；无限", "/ɪnˈfɪnəti/", "n.", 7, 0.6, "Space feels close to infinity.", "空间近乎无限。", "stretch on to infinity"),
];
