import { v } from "@/content/vocab/builder";
import type { VocabRow } from "@/content/vocab/types";

/** Medicine & healthcare treatment - Phase 10 chunk-g. */
export const medicineTreatmentRows: VocabRow[] = [
  v("diagnosis-early-stage", "/诊断", "/ˌdaɪəɡˈnoʊsɪs/", "n.", 6, 0.55, "Early diagnosis saves lives.", "早期诊断挽救生命。", "reach an accurate diagnosis"),
  v("symptom-checker-app", "/症状", "/ˈsɪmptəm/", "n.", 4, 0.35, "Fever is the first symptom.", "发烧是第一个症状。", "relieve flu symptoms"),
  v("chronic-condition-care", "/慢性的；长期的", "/ˈkrɑːnɪk/", "adj.", 6, 0.5, "Chronic back pain limits his work.", "慢性背痛限制了他的工作。", "a chronic illness diagnosis"),
  v("acute-pain-relief", "/急性的；剧烈的", "/əˈkjuːt/", "adj.", 6, 0.55, "Acute appendicitis needs immediate surgery.", "急性阑尾炎需要立即手术。", "acute abdominal pain"),
  v("prescription-drug-cost", "/处方；处方药", "/prɪˈskrɪpʃn/", "n.", 5, 0.45, "Pick up your prescription before five.", "五点前来取你的处方药。", "fill a prescription"),
  v("dosage-instructions-follow", "/剂量", "/ˈdoʊsɪdʒ/", "n.", 7, 0.65, "Never exceed the recommended dosage.", "切勿超过建议剂量。", "adjust the dosage carefully"),
  v("side-effect-warning-list", "/副作用", "/saɪd ɪˈfekt/", "n.", 4, 0.35, "Drowsiness is a common side effect.", "嗜睡是常见的副作用。", "report any side effects"),
  v("surgery-operation-room", "/手术；外科", "/ˈsɜːrdʒəri/", "n.", 4, 0.35, "The surgery lasted three hours.", "手术持续了三小时。", "undergo minor surgery"),
  v("surgeon-skill-level", "/外科医生", "/ˈsɜːrdʒən/", "n.", 5, 0.45, "The surgeon explained every step calmly.", "外科医生平静地讲解每一步。", "a highly skilled surgeon"),
  v("anesthesia-wear-off-time", "/麻醉", "/ˌænəsˈθiːʒə/", "n.", 7, 0.7, "Anesthesia numbed my whole leg.", "麻醉使我整条腿失去知觉。", "under general anesthesia"),
  v("transplant-organ-donation", "/移植；移植器官", "/trænsˈplænt/", "n./v.", 6, 0.6, "A heart transplant gave him ten more years.", "心脏移植让他多活了十年。", "await a kidney transplant"),
  v("donor-registry-match", "/捐赠者", "/ˈdoʊnər/", "n.", 5, 0.5, "Blood donors saved countless patients.", "献血者拯救了无数病人。", "a matching bone-marrow donor"),
  v("therapy-session-schedule", "/治疗；疗法", "/ˈθerəpi/", "n.", 4, 0.35, "Physical therapy restored her knee strength.", "物理治疗恢复了她的膝盖力量。", "attend weekly therapy sessions"),
  v("rehabilitation-program-length", "/康复", "/ˌriːhəˌbɪlɪˈteɪʃn/", "n.", 7, 0.65, "Rehabilitation took six hard months.", "康复花了艰苦的六个月。", "a stroke rehabilitation program"),
  v("chemotherapy-cycle-plan", "/化疗", "/ˌkiːmoʊˈθerəpi/", "n.", 7, 0.7, "Chemotherapy drained her energy for days.", "化疗让她好几天没有力气。", "begin chemotherapy treatment"),
  v("radiation-therapy-dose", "/放疗；放射治疗", "/ˈreɪdieɪʃn ˈθerəpi/", "n.", 7, 0.7, "Radiation therapy targets the tumor precisely.", "放射治疗精确瞄准肿瘤。", "complete radiation therapy sessions"),
  v("tumor-benign-or-not", "/肿瘤", "/ˈtuːmər/", "n.", 6, 0.6, "Doctors removed the benign tumor easily.", "医生轻松切除了良性肿瘤。", "shrink the tumor"),
  v("cancer-screening-test", "/癌症", "/ˈkænsər/", "n.", 3, 0.35, "Screening catches cancer early.", "筛查能早期发现癌症。", "fight cancer bravely"),
  v("diabetes-blood-sugar-log", "/糖尿病", "/ˌdaɪəˈbiːtiːz/", "n.", 5, 0.5, "Diabetes runs in his family.", "糖尿病在他家族中遗传。", "manage type-two diabetes"),
  v("hypertension-high-blood-pressure", "/高血压", "/ˌhaɪpərˈtenʃn/", "n.", 7, 0.7, "Hypertension silently damages arteries.", "高血压悄悄损害动脉。", "control hypertension through diet"),
  v("asthma-inhaler-use", "/哮喘", "/ˈæzmə/", "n.", 5, 0.5, "Cold air triggers his asthma.", "冷空气诱发他的哮喘。", "an asthma attack plan"),
  v("allergy-seasonal-triggers", "/过敏", "/ˈælərdʒi/", "n.", 4, 0.35, "Pollen allergies flare every spring.", "花粉过敏每年春天发作。", "develop a nut allergy"),
  v("infection-wound-clean", "/感染；传染", "/ɪnˈfekʃn/", "n.", 4, 0.35, "Clean cuts to prevent infection.", "清洗伤口以防感染。", "fight off an infection"),
  v("inflammation-swelling-reduce", "/炎症；发炎", "/ˌɪnləˈmeɪʃn/", "n.", 7, 0.65, "Ice reduces inflammation after sprains.", "冰敷减轻扭伤后的炎症。", "ease chronic inflammation"),
  v("fracture-bone-healing", "/骨折；断裂", "/ˈfræktʃər/", "n./v.", 6, 0.55, "The X-ray revealed a hairline fracture.", "X光片显示一处细微骨折。", "a stress fracture in the shin"),
  v("sprained-ankle-recovery", "/扭伤", "/spreɪn/", "v./n.", 5, 0.45, "She sprained her ankle on the trail.", "她在小径上扭伤了脚踝。", "a badly sprained wrist"),
  v("bandage-wrap-tight", "/绷带", "/ˈbændɪdʒ/", "n.", 3, 0.25, "Wrap the bandage snugly but not tightly.", "绷带缠得服帖但不要太紧。", "change the bandage daily"),
  v("stitches-remove-week", "/缝针；缝合线", "/ˈstɪtʃɪz/", "n.", 5, 0.5, "Stitches come out after ten days.", "缝线十天后拆除。", "dissolvable stitches inside"),
  v("cast-broken-arm-itch", "/石膏；铸模", "/kæst/", "n.", 4, 0.35, "The cast stayed on for six weeks.", "石膏打了六周。", "get the cast removed today"),
  v("crutches-walking-aid", "/拐杖", "/ˈkrʌtʃɪz/", "n.", 5, 0.5, "He hopped around on crutches proudly.", "他拄着拐杖骄傲地跳来跳去。", "move around on crutches"),
  v("wheelchair-accessible-ramp", "/轮椅", "/ˈwiːltʃer/", "n.", 4, 0.35, "Ramps make buildings wheelchair friendly.", "坡道让建筑方便轮椅通行。", "a lightweight folding wheelchair"),
  v("ambulance-emergency-call", "/救护车", "/ˈæmbjələns/", "n.", 2, 0.2, "Call an ambulance right now!", "马上叫救护车！", "arrive by ambulance"),
  v("emergency-room-visit", "/急诊室", "/ɪˈmɜːrdʒənsi ruːm/", "n.", 3, 0.3, "The ER visit cost a small fortune.", "那次急诊花费不菲。", "rush someone to the ER"),
  v("intensive-care-unit-stay", "/重症监护室", "/ɪnˈtensɪv ker ˈjuːnɪt/", "n.", 6, 0.6, "Grandpa spent two nights in intensive care.", "爷爷在重症监护室住了两晚。", "transfer to intensive care"),
  v("checkup-annual-exam", "/体检；检查", "/ˈtʃekʌp/", "n.", 3, 0.3, "Book your annual checkup online.", "在网上预约年度体检。", "a routine dental checkup"),
  v("vaccination-record-card", "/接种疫苗", "/ˌvæksɪˈneɪʃn/", "n.", 5, 0.45, "Keep your vaccination record handy.", "保管好疫苗接种记录。", "update vaccination records"),
  v("screening-test-results", "/筛查；筛选", "/ˈskriːnɪŋ/", "n.", 5, 0.45, "Free screening starts next Monday.", "免费筛查下周一启动。", "routine cancer screening"),
  v("referral-specialist-letter", "/转诊；推荐", "/rɪˈfɜːrəl/", "n.", 6, 0.6, "Get a referral before seeing the specialist.", "看专科前先拿到转诊单。", "need a doctor's referral"),
  v("insurance-claim-medical-bill", "/保险索赔", "/ɪnˈʃʊrəns kleɪm/", "n.", 5, 0.45, "Submit the insurance claim this week.", "本周提交保险索赔。", "file an insurance claim"),
  v("premium-monthly-payment", "/保费；溢价", "/ˈpriːmiəm/", "n./adj.", 6, 0.55, "Premiums rise every single year.", "保费逐年上涨。", "pay higher monthly premiums"),
  v("deductible-plan-details", "/免赔额", "/dɪˈdʌktəbl/", "n.", 7, 0.7, "Our deductible resets each January.", "免赔额每年一月重置。", "meet the annual deductible"),
  v("pharmacy-counter-pickup", "/药房", "/ˈfɑːrməsi/", "n.", 4, 0.35, "The pharmacy closes at nine tonight.", "药房今晚九点关门。", "wait at the pharmacy counter"),
  v("over-the-counter-medicine-shelf", "/非处方的", "/ˌoʊvər ðə ˈkaʊntər/", "adj.", 6, 0.55, "Aspirin is sold over the counter.", "阿司匹林是非处方出售的。", "an over-the-counter remedy"),
  v("painkiller-strongest-type", "/止痛药", "/ˈpeɪnkɪlər/", "n.", 5, 0.45, "Avoid strong painkillers during pregnancy.", "孕期避免强效止痛药。", "take a mild painkiller"),
  v("first-aid-kit-items", "/急救", "/fɜːrst eɪd/", "n.", 4, 0.35, "Every car should hold a first-aid kit.", "每辆车都应有急救箱。", "learn basic first aid"),
  v("cardiopulmonary-resuscitation-training", "/心肺复苏", "/ˌkɑːrdioʊˈpʊlməneri rɪˌsʌsɪˈteɪʃn/", "n.", 7, 0.75, "CPR training takes just one afternoon.", "心肺复苏培训只需一个下午。", "perform CPR immediately"),
  v("defibrillator-public-device", "/除颤器", "/diˈfɪbrɪleɪtər/", "n.", 7, 0.75, "Airports hang defibrillators everywhere.", "机场到处挂着除颤器。", "grab the nearest defibrillator"),
  v("blood-pressure-cuff-read", "/血压", "/blʌd ˈpreʃər/", "n.", 4, 0.35, "High blood pressure has no symptoms at first.", "高血压起初毫无症状。", "monitor blood pressure daily"),
  v("heart-rate-resting-average", "/心率", "/hɑːrt reɪt/", "n.", 4, 0.3, "Resting heart rate drops with fitness.", "静息心率随体能提升而下降。", "track your heart rate"),
  v("cholesterol-level-check", "/胆固醇", "/kəˈlestərɔːl/", "n.", 6, 0.55, "Oatmeal lowers cholesterol naturally.", "燕麦能天然降低胆固醇。", "high cholesterol readings"),
  v("calorie-count-menu-label", "/卡路里", "/ˈkæləri/", "n.", 3, 0.3, "Menus now list calories openly.", "菜单现在公开标注卡路里。", "cut empty calories"),
  v("nutrition-label-facts", "/营养", "/nuˈtrɪʃn/", "n.", 4, 0.35, "Read nutrition labels while shopping.", "购物时阅读营养成分表。", "poor nutrition habits"),
  v("dietitian-meal-plan", "/营养师", "/ˌdaɪəˈtɪʃn/", "n.", 7, 0.65, "The dietitian redesigned her meals.", "营养师重新设计了她的餐单。", "consult a registered dietitian"),
  v("wellness-program-workplace", "/健康；身心健康", "/ˈwelnəs/", "n.", 5, 0.45, "The company launched a wellness program.", "公司推出了健康计划。", "a corporate wellness retreat"),
  v("mental-health-support-line", "/心理健康", "/ˈmentl helθ/", "n.", 3, 0.3, "Mental health matters as much as physical health.", "心理健康和身体健康同等重要。", "improve mental health support"),
];
