import { v } from "@/content/vocab/builder";
import type { VocabRow } from "@/content/vocab/types";

/** Ocean & maritime world - Phase 10 chunk-g. */
export const oceanMarineRows: VocabRow[] = [
  v("deep-ocean-trench", "/海沟；深沟", "/trentʃ/", "n.", 7, 0.7, "The Mariana Trench dwarfs Mount Everest.", "马里亚纳海沟比珠峰还深。", "explore the ocean trench"),
  v("abyss-dark-depths", "/深渊", "/əˈbɪs/", "n.", 7, 0.75, "Submarines vanish into the abyss.", "潜艇消失在深渊之中。", "the lightless ocean abyss"),
  v("sea-floor-sediment", "/海底", "/ˈsiː flɔːr/", "n.", 5, 0.45, "Robot crawlers map the sea floor.", "机器人爬行器绘制海底地图。", "the volcanic sea floor"),
  v("high-tide-schedule", "/潮汐；潮流", "/taɪd/", "n.", 4, 0.3, "The tide retreats every six hours.", "潮水每六小时退去一次。", "swim at low tide"),
  v("wave-crest-height", "/波浪；波峰", "/krest/", "n.", 6, 0.55, "Surfers chase the perfect crest.", "冲浪者追逐完美浪峰。", "ride the wave crest"),
  v("rip-current-danger", "/激流；离岸流", "/rɪp ˈkɜːrənt/", "n.", 7, 0.65, "Rip currents pull swimmers seaward fast.", "离岸流把游泳者快速拖向深海。", "escape a rip current sideways"),
  v("undertow-beach-warning", "/暗流；下层逆流", "/ˈʌndərtoʊ/", "n.", 7, 0.7, "The undertow surprised the wading kids.", "暗流让蹚水的孩子们吃了一惊。", "a strong undertow near the pier"),
  v("saltwater-fish-tank", "/盐水；海水", "/ˈsɔːltwɔːtər/", "n./adj.", 4, 0.35, "Saltwater corrodes cheap metal fittings.", "盐水腐蚀廉价金属配件。", "a saltwater aquarium setup"),
  v("freshwater-lake-fishing", "/淡水的；内陆的", "/ˈfreʃwɔːtər/", "adj.", 5, 0.4, "Freshwater fish dislike salty water.", "淡水鱼不适应咸水。", "a freshwater spring source"),
  v("seaweed-sushi-wrap", "/海藻；海草", "/ˈsiːwiːd/", "n.", 4, 0.35, "Seaweed farms absorb excess nutrients.", "海藻养殖场吸收过剩养分。", "dried seaweed snacks"),
  v("plankton-food-chain-base", "/浮游生物", "/ˈplæŋktən/", "n.", 7, 0.7, "Whale sharks filter plankton all day.", "鲸鲨整天滤食浮游生物。", "tiny drifting plankton"),
  v("coral-polyp-colony", "/珊瑚", "/ˈkɔːrəl/", "n.", 6, 0.5, "Coral needs warm clear water.", "珊瑚需要温暖清澈的海水。", "bleached coral skeletons"),
  v("jellyfish-sting-treatment", "/水母", "/ˈdʒelifɪʃ/", "n.", 5, 0.45, "Jellyfish drift with the current.", "水母随波逐流。", "a painful jellyfish sting"),
  v("octopus-intelligence-test", "/章鱼", "/ˈɑːktəpəs/", "n.", 4, 0.4, "An octopus squeezed through a coin-sized hole.", "一只章鱼挤过了硬币大小的洞。", "an octopus hiding in rocks"),
  v("dolphin-pod-play", "/海豚", "/ˈdɑːlfɪn/", "n.", 3, 0.25, "Dolphins surf bow waves for fun.", "海豚在船首浪里嬉戏冲浪。", "watch dolphins offshore"),
  v("shark-cage-diving-trip", "/鲨鱼", "/ʃɑːrk/", "n.", 3, 0.3, "Sharks patrol the reef edge at dusk.", "鲨鱼黄昏时在礁缘巡游。", "spot reef sharks while diving"),
  v("whale-watching-season", "/鲸", "/weɪl/", "n.", 3, 0.25, "Gray whales pass here each March.", "灰鲸每年三月经过这里。", "book a whale-watching cruise"),
  v("seal-rocks-basking", "/海豹", "/siːl/", "n.", 3, 0.3, "Seals nap loudly on warm rocks.", "海豹在暖石上大声打盹。", "harbor seals resting ashore"),
  v("sea-turtle-nesting-site", "/海龟", "/siː ˈtɜːrtl/", "n.", 4, 0.35, "Sea turtles return to their birth beach.", "海龟会回到出生的海滩产卵。", "protect sea turtle nests"),
  v("penguin-colony-antarctica", "/企鹅", "/ˈpeŋɡwɪn/", "n.", 3, 0.3, "Penguins huddle through polar storms.", "企鹅在极地风暴中挤成一团。", "an emperor penguin colony"),
  v("lighthouse-guiding-beam", "/灯塔", "/ˈlaʊthaʊs/", "n.", 4, 0.35, "The lighthouse blinked every twelve seconds.", "灯塔每十二秒闪一次。", "climb the old lighthouse steps"),
  v("harbor-master-office", "/港口；港湾", "/ˈhɑːrbər/", "n.", 4, 0.35, "Fishing boats crowd the harbor at dawn.", "黎明时渔船挤满港口。", "a safe natural harbor"),
  v("dock-worker-unload", "/码头；船坞", "/dɑːk/", "n./v.", 4, 0.35, "We docked just before sunset.", "我们在日落前靠岸停泊。", "tie up at the dock"),
  v("pier-fishing-spot", "/栈桥；突堤", "/pɪr/", "n.", 4, 0.35, "Kids fished off the wooden pier.", "孩子们在木栈桥上钓鱼。", "stroll along the pleasure pier"),
  v("buoy-marker-floating", "/浮标", "/ˈbuːi/", "n.", 6, 0.6, "Red buoys mark the safe channel.", "红色浮标标出安全航道。", "steer between the buoys"),
  v("anchor-drop-deep", "/锚；抛锚", "/ˈæŋkər/", "n./v.", 4, 0.35, "Drop anchor in the sheltered cove.", "在有遮蔽的小海湾抛锚。", "weigh anchor at dawn"),
  v("sailboat-rigging-check", "/帆船", "/ˈseɪlboʊt/", "n.", 4, 0.35, "Their sailboat heeled in the gusts.", "他们的帆船在阵风中倾斜。", "race small sailboats on weekends"),
  v("yacht-charter-expensive", "/游艇", "/jɑːt/", "n.", 5, 0.45, "A luxury yacht anchored offshore.", "一艘豪华游艇停在近海。", "charter a yacht for the day"),
  v("canoe-paddle-stroke", "/独木舟", "/kəˈnuː/", "n.", 4, 0.35, "We canoed across the glassy lake.", "我们划独木舟穿过平静如镜的湖面。", "paddle a canoe upstream"),
  v("kayak-white-water-run", "/皮划艇", "/ˈkaɪæk/", "n.", 5, 0.4, "Kayak rentals fill up fast in summer.", "夏季皮划艇租赁很快订满。", "paddle the kayak through rapids"),
  v("ferry-crossing-ticket", "/渡轮", "/ˈferi/", "n.", 4, 0.35, "The ferry crosses hourly in summer.", "渡轮夏季每小时一班。", "take the early ferry crossing"),
  v("cargo-ship-container-load", "/货船", "/ˈkɑːrɡoʊ ʃɪp/", "n.", 5, 0.45, "Cargo ships queue outside every big port.", "货船在各大港口外排队。", "load the cargo ship at berth four"),
  v("submarine-deep-dive", "/潜水艇", "/ˌsʌbməˈriːn/", "n.", 5, 0.45, "The submarine surfaced near dawn.", "潜艇黎明前浮出水面。", "tour a retired submarine"),
  v("snorkeling-mask-clear", "/浮潜", "/ˈsnɔːrkəlɪŋ/", "n.", 5, 0.4, "Snorkeling revealed neon-colored fish.", "浮潜让我们看到了霓虹色的鱼群。", "go snorkeling over the reef"),
  v("scuba-certification-course", "/水肺潜水", "/ˈskuːbə/", "n.", 6, 0.55, "Scuba divers check air twice before descending.", "水肺潜水员下潜前两次检查气量。", "earn an open-water scuba certification"),
  v("wetsuit-thickness-guide", "/潜水服；防寒泳衣", "/ˈwetsuːt/", "n.", 6, 0.55, "A thicker wetsuit beats winter swells.", "更厚的湿式潜水服能抵御冬季涌浪。", "zip up the wetsuit fully"),
  v("surfboard-wax-layer", "/冲浪板", "/ˈsɜːrfbɔːrd/", "n.", 5, 0.45, "Wax your surfboard before paddling out.", "划出去之前给冲浪板打蜡。", "carry two spare surfboards"),
  v("lifeguard-tower-watch", "/救生员", "/ˈlaɪfɡɑːrd/", "n.", 4, 0.35, "Lifeguards whistle at risky swimmers.", "救生员向冒险的游泳者吹哨警告。", "swim between lifeguard flags"),
  v("coastline-erosion-map", "/海岸线", "/ˈkoʊstlaɪn/", "n.", 5, 0.4, "Cliffs reshape this coastline every storm.", "每场风暴都重塑这段悬崖海岸线。", "hike the wild coastline path"),
  v("beachcombing-treasure-hunt", "/海滩拾荒", "/ˈbiːtʃkoʊmɪŋ/", "n.", 7, 0.65, "Beachcombing turns up sea glass and stories.", "海滩拾贝总能捡到玻璃石和故事。", "spend the morning beachcombing"),
  v("driftwood-campfire-seat", "/浮木；漂流木", "/ˈdrɪftwʊd/", "n.", 6, 0.6, "Driftwood fed our bonfire all night.", "浮木让篝火烧了一整夜。", "collect smooth driftwood pieces"),
  v("seashell-collection-jar", "/贝壳", "/ˈsiːʃel/", "n.", 3, 0.3, "Her jar overflows with tiny seashells.", "她的罐子里装满了小贝壳。", "gather spiral seashells at low tide"),
  v("starfish-five-arm-regrow", "/海星", "/ˈstɑːrfɪʃ/", "n.", 4, 0.4, "Starfish regrow lost arms slowly.", "海星能慢慢再生断掉的腕足。", "find an orange starfish under rocks"),
  v("seahorse-male-pregnancy", "/海马", "/ˈsiːhɔːrs/", "n.", 5, 0.5, "Male seahorses carry the babies.", "雄性海马负责孕育宝宝。", "spot camouflaged seahorses"),
  v("maritime-trade-history", "/海事的；海运的", "/ˈmerɪtaɪm/", "adj.", 7, 0.65, "Maritime law governs international waters.", "海商法管辖国际水域。", "a rich maritime heritage"),
  v("navigation-chart-plotting", "/航海；导航", "/ˌnævɪˈɡeɪʃn/", "n.", 5, 0.5, "Old sailors trusted stars for navigation.", "老水手靠星星导航。", "master coastal navigation basics"),
  v("captain-ship-commander", "/船长；机长", "/ˈkæptɪn/", "n.", 2, 0.2, "The captain announced rough seas ahead.", "船长广播前方风浪较大。", "obey the captain's orders"),
  v("sailor-knot-skills", "/水手", "/ˈseɪlər/", "n.", 3, 0.3, "Sailors tie knots blindfolded.", "水手蒙眼也能打绳结。", "an experienced deep-sea sailor"),
  v("shipwreck-diving-site", "/沉船；海难", "/ˈʃɪprek/", "n.", 7, 0.65, "The shipwreck shelters colorful fish now.", "那艘沉船如今成了彩色鱼群的家园。", "dive a famous shipwreck"),
  v("tsunami-drill-coastal-town", "/海啸演习", "/ˈsuːnɑːmi drɪl/", "n.", 7, 0.7, "Coastal towns run tsunami drills yearly.", "沿海城镇每年举行海啸演练。", "practice the tsunami drill route"),
];
