import { v } from "@/content/vocab/builder";
import type { VocabRow } from "@/content/vocab/types";

/** History & civilizations - Phase 10 chunk-g. */
export const historyCivilizationRows: VocabRow[] = [
  v("ancient-civilization-ruins", "/文明", "/ˌsɪvələˈzeɪʃn/", "n.", 4, 0.35, "Ancient civilizations rose along rivers.", "古代文明沿河而起。", "the fall of a civilization"),
  v("dynasty-family-rule", "/朝代；王朝", "/ˈdaɪnəsti/", "n.", 6, 0.55, "The Tang dynasty shaped Chinese poetry.", "唐朝塑造了中国诗歌。", "found a new dynasty"),
  v("empire-expansion-map", "/帝国", "/ˈempaɪər/", "n.", 5, 0.45, "The Roman empire spanned three continents.", "罗马帝国横跨三大洲。", "the collapse of the empire"),
  v("monarchy-royal-lineage", "/君主制；君主国", "/ˈmɑːnərki/", "n.", 7, 0.65, "Britain kept its monarchy into modern times.", "英国将君主制延续到现代。", "abolish the monarchy"),
  v("republic-government-form", "/共和国；共和政体", "/rɪˈpʌblɪk/", "n.", 5, 0.45, "Rome was a republic before the emperors.", "罗马在帝制之前是共和国。", "a constitutional republic"),
  v("medieval-castle-tour", "/中世纪的", "/ˌmiːdiˈiːvl/", "adj.", 6, 0.55, "Medieval walls still ring the old city.", "中世纪城墙仍环绕老城。", "a medieval marketplace reenactment"),
  v("renaissance-art-patron", "/文艺复兴", "/ˌrenəˈsɑːns/", "n.", 6, 0.6, "The Renaissance rediscovered classical ideas.", "文艺复兴重新发现了古典思想。", "a Renaissance masterpiece"),
  v("revolution-uprising-success", "/革命；巨变", "/ˌrevəˈluːʃn/", "n.", 4, 0.4, "The industrial revolution changed everything.", "工业革命改变了一切。", "spark a peaceful revolution"),
  v("colonial-trade-routes", "/殖民的；殖民地的", "/kəˈloʊniəl/", "adj.", 7, 0.6, "Colonial ports grew rich on spice trade.", "殖民港口靠香料贸易致富。", "colonial-era architecture"),
  v("independence-declaration-day", "/独立；自主", "/ˌɪndɪˈpendəns/", "n.", 4, 0.35, "The nation celebrates independence each July.", "这个国家每年七月庆祝独立。", "win independence peacefully"),
  v("treaty-peace-signing", "/条约；协议", "/ˈtriːti/", "n.", 6, 0.55, "The treaty ended thirty years of war.", "条约结束了三十年战争。", "sign a landmark treaty"),
  v("alliance-military-partnership", "/联盟；结盟", "/əˈlaɪəns/", "n.", 5, 0.5, "The alliance deterred further invasions.", "联盟遏制了进一步入侵。", "form a strategic alliance"),
  v("conquest-battle-victory", "/征服；攻占", "/ˈkɑːŋkwest/", "n.", 7, 0.65, "Norman conquest reshaped English itself.", "诺曼征服重塑了英语本身。", "complete the conquest of the region"),
  v("archaeology-dig-site", "/考古学", "/ˌɑːrkiˈɑːlədʒi/", "n.", 7, 0.7, "Archaeology resurrects forgotten cities.", "考古学让被遗忘的城市重见天日。", "join an archaeology field school"),
  v("excavation-careful-brushing", "/挖掘；出土", "/ˌekskəˈveɪʃn/", "n.", 7, 0.7, "Excavation uncovered a Roman mosaic.", "发掘出土了一幅罗马马赛克。", "begin the excavation season"),
  v("artifact-museum-piece", "/人工制品；手工艺品", "/ˈɑːrtɪfækt/", "n.", 7, 0.65, "Every artifact tells a human story.", "每件文物都讲述着人类的故事。", "handle ancient artifacts with gloves"),
  v("hieroglyphic-wall-carving", "/象形文字", "/ˌhaɪərəˈɡlɪfɪk/", "adj./n.", 7, 0.75, "Hieroglyphic carvings recorded pharaohs' deeds.", "象形文字刻录了法老的功绩。", "decipher hieroglyphic inscriptions"),
  v("manuscript-ancient-scroll", "/手稿；抄本", "/ˈmænjuskrɪpt/", "n.", 7, 0.65, "The medieval manuscript survived centuries intact.", "这份中世纪手稿完好保存了数百年。", "donate a rare manuscript"),
  v("oracle-prophecy-stone", "/神谕；先知", "/ˈɔːrəkl/", "n.", 7, 0.75, "Ancient Greeks consulted the oracle at Delphi.", "古希腊人到德尔斐求取神谕。", "speak like an oracle"),
  v("pharaoh-pyramid-builder", "/法老", "/ˈferoʊ/", "n.", 6, 0.6, "Tutankhamun became pharaoh at nine.", "图坦卡蒙九岁成为法老。", "a boy pharaoh's golden mask"),
  v("gladiator-arena-fight", "/角斗士", "/ˈɡlædieɪtər/", "n.", 7, 0.7, "Gladiators fought under the Colosseum sun.", "角斗士们在斗兽场的烈日下搏斗。", "train as a gladiator"),
  v("samurai-honor-code", "/武士；武士阶层", "/ˈsæmuraɪ/", "n.", 6, 0.6, "Samurai served their lords absolutely.", "武士绝对效忠主君。", "a samurai sword collection"),
  v("viking-longship-raiders", "/维京人；北欧海盗", "/ˈvaɪkɪŋ/", "n.", 5, 0.5, "Vikings raided coasts and traded furs.", "维京人劫掠海岸并交易毛皮。", "trace Viking settlements"),
  v("nomad-desert-crossing", "/游牧民；流浪者", "/ˈnoʊmæd/", "n.", 6, 0.6, "Nomads followed rain across the steppe.", "游牧民追随雨水穿越草原。", "live like digital nomads"),
  v("pilgrim-sacred-journey", "/朝圣者；旅人", "/ˈpɪlɡrɪm/", "n.", 6, 0.6, "Pilgrims walked barefoot to the shrine.", "朝圣者赤脚走向圣地。", "join pilgrims on the trail"),
  v("plague-black-death", "/瘟疫；灾害", "/pleɪɡ/", "n.", 7, 0.6, "The plague emptied whole cities.", "瘟疫让整座城市空无一人。", "survive the bubonic plague"),
  v("famine-food-shortage-year", "/饥荒", "/ˈfæmɪn/", "n.", 7, 0.65, "Famine followed three failed harvests.", "三季歉收之后爆发饥荒。", "relieve famine victims"),
  v("uprising-peasant-revolt", "/起义；暴动", "/ˈʌpraɪzɪŋ/", "n.", 7, 0.65, "The uprising toppled the corrupt governor.", "起义推翻了腐败的总督。", "crush an armed uprising"),
  v("assassination-political-murder", "/暗杀；行刺", "/əˌsæsɪˈneɪʃn/", "n.", 7, 0.7, "An assassination plunged Rome into chaos.", "一次暗杀使罗马陷入混乱。", "attempt an assassination plot"),
  v("abdicate-the-throne", "/退位；放弃", "/ˈæbdɪkeɪt/", "v.", 7, 0.8, "The king abdicated after the scandal.", "国王在丑闻后退位。", "abdicate in favor of his son"),
  v("succession-throne-dispute", "/继任；继承", "/səkˈseʃn/", "n.", 7, 0.7, "Succession disputes tore the court apart.", "继承之争撕碎了宫廷。", "settle the succession peacefully"),
  v("feudal-system-lords", "/封建的；封建制度", "/ˈfjuːdl/", "adj.", 7, 0.75, "Feudal lords owned land and loyalty alike.", "封建领主同时拥有土地与忠诚。", "the feudal hierarchy pyramid"),
  v("serf-bound-to-land", "/农奴", "/sɜːrf/", "n.", 7, 0.8, "Serfs farmed land they could never own.", "农奴耕种永远无法拥有的土地。", "free the serfs by decree"),
  v("guild-medieval-craftsmen", "/行会；公会", "/ɡɪld/", "n.", 7, 0.8, "Weaver guilds set prices for centuries.", "织工行会数百年来掌控定价。", "join the merchants' guild"),
  v("industrialization-factory-age", "/工业化", "/ɪnˌdʌstriələˈzeɪʃn/", "n.", 7, 0.7, "Industrialization pulled farmers into cities.", "工业化把农民吸进城市。", "rapid industrialization costs"),
  v("immigration-wave-history", "/移民入境", "/ˌɪmɪˈɡreɪʃn/", "n.", 5, 0.45, "Immigration built this port city twice over.", "移民潮两度造就了这座港城。", "ease immigration restrictions"),
  v("emigration-overseas-leaving", "/移居国外", "/ˌemɪˈɡreɪʃn/", "n.", 7, 0.7, "Emigration emptied entire villages.", "向外移民让整个村庄空了。", "wave of rural emigration"),
  v("ancestor-worship-tradition", "/祖先；先辈", "/ˈænsestər/", "n.", 5, 0.45, "Our ancestors crossed oceans for hope.", "我们的祖先为希望跨越大洋。", "honor one's ancestors"),
  v("descendant-family-lineage", "/后代；子孙", "/dɪˈsendənt/", "n.", 6, 0.55, "Descendants still farm the same valley.", "后代仍在同一山谷耕作。", "a direct descendant of the founder"),
  v("heritage-cultural-pride", "/遗产；传统", "/ˈherɪtɪdʒ/", "n.", 5, 0.45, "UNESCO lists it as world heritage.", "联合国教科文组织将其列为世界遗产。", "protect our cultural heritage"),
  v("timeline-milestone-events", "/时间线；年表", "/ˈtaɪmlaɪn/", "n.", 4, 0.35, "Build a timeline before writing history essays.", "写历史论文前先做时间线。", "follow the project timeline"),
  v("century-turning-points", "/世纪；百年", "/ˈsentʃəri/", "n.", 2, 0.15, "The printing press defined its century.", "印刷机定义了它所在的世纪。", "span several turbulent centuries"),
  v("decade-by-decade-review", "/十年", "/ˈdekeɪd/", "n.", 3, 0.2, "Technology leaped every decade since.", "此后科技每十年一跃。", "over the past decade alone"),
  v("era-defining-style", "/时代；年代", "/ˈerə/", "n.", 4, 0.3, "That song captures the era perfectly.", "那首歌完美捕捉了那个时代。", "usher in a new era"),
  v("historian-primary-sources", "/历史学家", "/hɪˈstɔːriən/", "n.", 5, 0.45, "Historians argue about causes endlessly.", "历史学家无休止地争论原因。", "consult respected historians"),
];
