import { v } from "@/content/vocab/builder";
import type { VocabRow } from "@/content/vocab/types";

/** Government & politics - Phase 10 chunk-g. */
export const governmentPoliticsRows: VocabRow[] = [
  v("democracy-voting-rights", "/民主；民主制度", "/dɪˈmɑːkrəsi/", "n.", 5, 0.45, "Democracy depends on informed voters.", "民主要靠知情的选民。", "defend democracy at the ballot box"),
  v("government-policy-shift", "/政府；治理", "/ˈɡʌvərnmənt/", "n.", 2, 0.2, "The government announced new housing rules.", "政府宣布了新的住房规定。", "a coalition government deal"),
  v("constitution-amendment-process", "/宪法", "/ˌkɑːnstɪˈtuːʃn/", "n.", 7, 0.6, "Amendments require supermajority votes.", "修宪需要绝对多数票。", "amend the state constitution"),
  v("parliament-debate-session", "/议会；国会", "/ˈpɑːrləmənt/", "n.", 6, 0.55, "Parliament debated the bill all night.", "议会通宵辩论法案。", "address parliament directly"),
  v("congress-bill-passing", "/国会；代表大会", "/ˈkɑːŋɡrəs/", "n.", 5, 0.5, "Congress passed the emergency funding bill.", "国会通过了紧急拨款案。", "lobby Congress for support"),
  v("senate-majority-vote", "/参议院", "/ˈsenət/", "n.", 6, 0.6, "The Senate approved three judges today.", "参议院今天批准了三名法官。", "win the Senate seat"),
  v("president-executive-order", "/总统；总裁", "/ˈprezɪdənt/", "n.", 2, 0.15, "The president signed the order this morning.", "总统今早签署了行政令。", "meet with the president"),
  v("prime-minister-office-term", "/首相；总理", "/ˌpraɪm ˈmɪnɪstər/", "n.", 4, 0.35, "The prime minister called an early election.", "首相宣布提前选举。", "the prime minister's resignation speech"),
  v("election-campaign-strategy", "/选举", "/ɪˈlekʃn/", "n.", 3, 0.3, "Local elections happen every two years here.", "本地每两年举行一次地方选举。", "run a clean election campaign"),
  v("ballot-box-security", "/选票；投票", "/ˈbælət/", "n.", 6, 0.6, "Seal every ballot box before transport.", "运输前封好每个投票箱。", "count the ballots by hand"),
  v("voter-turnout-rate", "/选民；投票者", "/ˈvoʊtər/", "n.", 5, 0.5, "Voter turnout hit a twenty-year high.", "选民投票率创二十年新高。", "register as a voter early"),
  v("campaign-promise-list", "/竞选活动", "/kæmˈpeɪn/", "n./v.", 4, 0.35, "Their campaign focused on jobs alone.", "他们的竞选只聚焦就业。", "kick off the campaign tour"),
  v("candidate-interview-night", "/候选人；应试者", "/ˈkændɪdət/", "n.", 4, 0.35, "Each candidate got ninety seconds.", "每位候选人有九十秒发言。", "shortlist three candidates"),
  v("political-party-platform", "/政党", "/ˈpɑːlɪtɪkl pɑːrti/", "n.", 3, 0.3, "Third parties rarely win national races.", "第三党很少赢得全国大选。", "join a local political party"),
  v("diplomat-embassy-posting", "/外交官", "/ˈdɪpləmæt/", "n.", 6, 0.6, "Diplomats negotiated behind closed doors.", "外交官在幕后谈判。", "send senior diplomats to talks"),
  v("embassy-visa-section", "/大使馆", "/ˈembəsi/", "n.", 5, 0.5, "Apply at the embassy before March.", "三月份前到大使馆申请。", "contact your embassy abroad"),
  v("ambassador-state-visit", "/大使；使节", "/æmˈbæsədər/", "n.", 6, 0.6, "The ambassador hosted a culture night.", "大使举办了文化之夜活动。", "appoint a new ambassador"),
  v("diplomacy-channel-open", "/外交；外交手段", "/dɪˈploʊməsi/", "n.", 6, 0.6, "Quiet diplomacy defused the border crisis.", "低调外交化解了边境危机。", "practice quiet diplomacy"),
  v("sanction-economic-pressure", "/制裁；批准", "/ˈsæŋkʃn/", "n./v.", 7, 0.65, "Sanctions froze billions in assets.", "制裁冻结了数十亿资产。", "lift economic sanctions"),
  v("referendum-public-vote", "/公民投票", "/ˌrefəˈrendəm/", "n.", 7, 0.7, "The referendum passed by one point.", "公投以一个百分点之差通过。", "call a national referendum"),
  v("legislation-new-law-passed", "/立法；法规", "/ˌledʒɪsˈleɪʃn/", "n.", 6, 0.6, "New legislation protects gig workers.", "新立法保护零工劳动者。", "push legislation through committee"),
  v("bureaucracy-red-tape-complaints", "/官僚机构；官僚主义", "/bjʊˈrɑːkrəsi/", "n.", 7, 0.65, "Bureaucracy delayed permits for months.", "官僚流程让许可拖了几个月。", "cut through the bureaucracy"),
  v("policy-maker-roundtable", "/政策", "/ˈpɑːləsi/", "n.", 4, 0.35, "Rate policy affects mortgages directly.", "利率政策直接影响房贷。", "shape long-term policy"),
  v("minister-cabinet-role", "/部长；大臣", "/ˈmɪnɪstər/", "n.", 5, 0.5, "The finance minister resigned abruptly.", "财政部长突然辞职。", "swear in the new minister"),
  v("cabinet-meeting-agenda", "/内阁；橱柜", "/ˈkæbɪnət/", "n.", 5, 0.5, "The cabinet met behind locked doors.", "内阁闭门开会。", "reshuffle the cabinet"),
  v("governor-state-election", "/州长；省长", "/ˈɡʌvərnər/", "n.", 5, 0.5, "The governor declared a state of emergency.", "州长宣布进入紧急状态。", "elect a new governor"),
  v("mayor-city-hall-office", "/市长", "/ˈmeɪər/", "n.", 3, 0.25, "Our mayor rides the subway to work.", "我们市长坐地铁上班。", "the mayor's budget proposal"),
  v("immigration-policy-debate", "/移民；移居", "/ˈɪmɪɡrənt/", "n.", 4, 0.35, "Immigrants rebuilt the neighborhood after the fire.", "火灾后移民们重建了社区。", "welcome skilled immigrants"),
  v("citizenship-naturalization-test", "/公民身份", "/ˈsɪtɪzənʃɪp/", "n.", 5, 0.5, "Citizenship took her eight years.", "她花了八年获得公民身份。", "apply for dual citizenship"),
  v("passport-renewal-line", "/护照", "/ˈpæspɔːrt/", "n.", 2, 0.2, "Renew your passport six months early.", "提前六个月换发护照。", "stamp the passport at entry"),
  v("visa-application-status", "/签证", "/ˈviːzə/", "n.", 3, 0.3, "Her student visa arrived just in time.", "她的学生签证及时办下来了。", "extend a tourist visa"),
  v("protest-march-permit", "/抗议；反对", "/ˈproʊtest/", "n./v.", 4, 0.35, "Thousands joined the climate protest.", "数千人参加了气候抗议。", "stage a peaceful protest"),
  v("petition-signature-drive", "/请愿；请愿书", "/pəˈtɪʃn/", "n./v.", 6, 0.55, "The petition gathered fifty thousand names.", "请愿征集到五万个签名。", "launch an online petition"),
  v("lobbying-interest-groups", "/游说", "/ˈlɑːbiɪŋ/", "n.", 7, 0.65, "Lobbying shapes farm subsidies quietly.", "游说悄然左右农业补贴。", "ban corporate lobbying gifts"),
  v("corruption-scandal-exposed", "/腐败；贪污", "/kəˈrʌpʃn/", "n.", 6, 0.6, "Corruption scandals toppled two ministers.", "腐败丑闻掀翻了两名部长。", "fight corruption at every level"),
  v("transparency-report-publishing", "/透明度", "/trænsˈperənsi/", "n.", 7, 0.6, "Transparency builds public trust slowly.", "透明度慢慢建立公众信任。", "demand full transparency"),
  v("surveillance-camera-network", "/监控；监视", "/sɜːrˈveɪləns/", "n.", 7, 0.65, "Facial surveillance sparks fierce debate.", "人脸监控引发激烈争论。", "mass surveillance concerns"),
  v("national-security-briefing", "/国家安全", "/ˈnæʃnəl sɪˈkjʊrəti/", "n.", 5, 0.5, "Cyber threats now top national security lists.", "网络威胁如今位居国家安全清单之首。", "a national security clearance"),
  v("border-patrol-station", "/边境；边界", "/ˈbɔːrdər/", "n.", 3, 0.3, "Guards patrol the mountainous border nightly.", "卫兵每晚巡查多山边境。", "cross the border legally"),
  v("federal-court-system", "/联邦的", "/ˈfedərəl/", "adj.", 6, 0.55, "Federal agents joined the investigation.", "联邦探员加入调查。", "a federal minimum wage"),
  v("state-affairs-summary", "/国家；州的", "/steɪt/", "n./adj./v.", 1, 0.1, "Water safety is a state responsibility.", "水质安全是州级责任。", "affairs of state"),
];
