import { v } from "@/content/vocab/builder";
import type { VocabRow } from "@/content/vocab/types";

/** Law, crime & justice - Phase 10 chunk-g. */
export const lawCrimeRows: VocabRow[] = [
  v("attorney-defense-team", "/律师；代理人", "/əˈtɜːrni/", "n.", 6, 0.6, "Her attorney requested a delay.", "她的律师申请延期。", "consult an attorney first"),
  v("defendant-plead-innocent", "/被告", "/dɪˈfendənt/", "n.", 7, 0.65, "The defendant pleaded not guilty.", "被告作无罪抗辩。", "the defendant's legal team"),
  v("plaintiff-file-suit", "/原告", "/ˈpleɪntɪf/", "n.", 7, 0.7, "The plaintiff demanded full compensation.", "原告要求全额赔偿。", "settle with the plaintiff"),
  v("witness-stand-testimony", "/证人；目击者", "/ˈwɪtnəs/", "n./v.", 4, 0.4, "One witness changed the whole trial.", "一名证人改变了整个庭审。", "call a key witness"),
  v("testimony-sworn-statement", "/证词；证据", "/ˈtestɪmoʊni/", "n.", 7, 0.7, "His testimony contradicted the video.", "他的证词与视频矛盾。", "give sworn testimony"),
  v("evidence-chain-custody", "/证据", "/ˈevɪdəns/", "n.", 4, 0.35, "DNA evidence sealed the verdict.", "DNA证据锁定了判决。", "gather forensic evidence"),
  v("verdict-jury-decision", "/裁决；判决", "/ˈvɜːrdɪkt/", "n.", 6, 0.55, "The verdict took eleven hours.", "陪审团花了十一小时才做出裁决。", "await the final verdict"),
  v("jury-duty-selection", "/陪审团", "/ˈdʒʊri/", "n.", 5, 0.5, "Twelve citizens served on the jury.", "十二位公民担任陪审员。", "serve on a jury for a week"),
  v("judge-courtroom-ruling", "/法官；判断", "/dʒʌdʒ/", "n./v.", 2, 0.2, "Don't judge people by their shoes.", "别以鞋取人。", "judge each case on its merits"),
  v("trial-court-date-set", "/审判；试验", "/ˈtraɪəl/", "n.", 3, 0.3, "The trial begins next Tuesday.", "审判下周二开始。", "face a lengthy trial"),
  v("appeal-higher-court", "/上诉；呼吁", "/əˈpiːl/", "v./n.", 6, 0.6, "They plan to appeal the ruling.", "他们计划对判决提起上诉。", "file an appeal within thirty days"),
  v("sentence-prison-term", "/判刑；句子", "/ˈsentəns-n2/", "n./v.", 4, 0.4, "He received a five-year sentence.", "他被判处五年徒刑。", "reduce the sentence for good behavior"),
  v("parole-hearing-date", "/假释", "/pəˈroʊl/", "n.", 7, 0.7, "Parole was denied a third time.", "假释第三次被驳回。", "qualify for early parole"),
  v("probation-officer-visits", "/缓刑；试用期", "/proʊˈbeɪʃn/", "n.", 7, 0.7, "She completed probation without incidents.", "她平安度过缓刑期。", "violate probation terms"),
  v("bail-hearing-amount", "/保释；保释金", "/beɪl/", "n.", 6, 0.6, "Bail was set at fifty thousand dollars.", "保释金定为五万美元。", "post bail that same night"),
  v("arrest-warrant-signed", "/逮捕；拘留", "/əˈrest/", "v./n.", 4, 0.4, "Police arrested two suspects at dawn.", "警方黎明逮捕了两名嫌疑人。", "make a lawful arrest"),
  v("suspect-interrogation-room", "/嫌疑人；怀疑", "/ˈsʌspekt/", "n./v.", 4, 0.4, "Detectives questioned the suspect for hours.", "警探审问了嫌疑人数小时。", "rule out the main suspect"),
  v("investigation-case-file", "/调查；研究", "/ɪnˌvestɪˈɡeɪʃn/", "n.", 4, 0.35, "The investigation lasted eighteen months.", "调查历时十八个月。", "open a formal investigation"),
  v("forensics-lab-results", "/法庭科学；取证", "/fəˈrenzɪks/", "n.", 7, 0.7, "Forensics matched the fibers exactly.", "法医物证精确匹配了纤维。", "send samples to forensics"),
  v("fraud-insurance-claim", "/欺诈；骗子", "/frɔːd/", "n.", 6, 0.6, "Insurance fraud costs everyone money.", "保险欺诈让所有人买单。", "uncover a wire fraud scheme"),
  v("theft-shoplifting-charge", "/盗窃；偷窃", "/θeft/", "n.", 4, 0.35, "Theft reports dropped after new lighting.", "新装路灯后盗窃报案下降。", "report the theft immediately"),
  v("robbery-armed-bank", "/抢劫；劫案", "/ˈrɑːbəri/", "n.", 4, 0.35, "An armed robbery shut the block down.", "一起持械抢劫封闭了整个街区。", "witness a daylight robbery"),
  v("burglary-home-break-in", "/入室盗窃", "/ˈbɜːrɡləri/", "n.", 6, 0.55, "Burglary attempts rose during the holidays.", "假期入室盗窃未遂案上升。", "prevent burglary with smart locks"),
  v("vandalism-graffiti-cleanup", "/故意破坏；破坏公物", "/ˈvændəlɪzəm/", "n.", 6, 0.6, "Vandalism cost the school thousands.", "故意破坏让学校损失数千元。", "charge them with vandalism"),
  v("assault-charge-filed", "/攻击；袭击", "/əˈsɔːlt/", "n./v.", 6, 0.6, "He faces an assault charge.", "他面临袭击指控。", "a serious assault case"),
  v("murder-mystery-novel", "/谋杀", "/ˈmɜːrdər/", "n./v.", 4, 0.35, "The murder remains unsolved after decades.", "这起谋杀数十年悬而未破。", "solve a decades-old murder"),
  v("kidnapping-ransom-note", "/绑架", "/ˈkɪdnæpɪŋ/", "n.", 6, 0.6, "The kidnapping ended with a safe rescue.", "绑架案以安全获救告终。", "demand a ransom payment"),
  v("smuggling-border-crossing", "/走私；偷运", "/ˈsmʌɡlɪŋ/", "n.", 7, 0.65, "Smuggling rings move rare animals.", "走私团伙贩卖珍稀动物。","break up a smuggling ring"),
  v("counterfeit-money-detection", "/伪造的；假冒的", "/ˈkaʊntərfɪt/", "adj./n.", 7, 0.7, "Counterfeit bills flooded the market.", "伪钞充斥市场。", "spot counterfeit products online"),
  v("cybercrime-unit-specialists", "/网络犯罪", "/ˈsaɪbərkraɪm/", "n.", 7, 0.65, "Cybercrime now outpaces street theft.", "网络犯罪已超过街头盗窃。", "combat cross-border cybercrime"),
  v("hacking-unauthorized-access", "/黑客行为；非法侵入", "/ˈhækɪŋ/", "n.", 6, 0.6, "Hacking exposed millions of passwords.", "黑客攻击泄露了数百万密码。", "prevent hacking with two-factor login"),
  v("identity-theft-protection", "/身份盗用", "/aɪˈdentəti θeft/", "n.", 7, 0.6, "Identity theft ruined his credit score.", "身份盗用毁了他的信用评分。", "guard against identity theft"),
  v("stalking-restraining-order", "/跟踪骚扰", "/ˈstɔːkɪŋ/", "n.", 7, 0.65, "Stalking laws finally covered online abuse.", "跟踪骚扰法终于涵盖网络侵害。", "file a stalking complaint"),
  v("harassment-policy-workplace", "/骚扰；侵扰", "/həˈræsmənt/", "n.", 6, 0.55, "Zero-tolerance harassment policies protect everyone.", "零容忍骚扰政策保护所有人。", "report harassment to HR promptly"),
  v("discrimination-lawsuit-risk", "/歧视", "/dɪˌskrɪmɪˈneɪʃn/", "n.", 6, 0.55, "Age discrimination hides behind polite words.", "年龄歧视藏在客气话背后。", "fight workplace discrimination"),
  v("lawsuit-class-action-filing", "/诉讼", "/ˈlɔːsuːt/", "n.", 6, 0.6, "A class-action lawsuit named twelve companies.", "一桩集体诉讼点名十二家公司。", "settle the lawsuit out of court"),
  v("litigation-costs-mounting", "/诉讼；打官司", "/ˌlɪtɪˈɡeɪʃn/", "n.", 7, 0.75, "Litigation drained their savings fast.", "官司很快耗尽了积蓄。", "avoid costly litigation"),
  v("settlement-out-of-court-agreement", "/和解；定居点", "/ˈsetlmənt/", "n.", 6, 0.6, "Both sides signed a quiet settlement.", "双方签署了保密和解协议。", "reach a fair settlement"),
  v("contract-breach-clause", "/合同；契约", "/ˈkɑːntrækt/", "n.", 4, 0.35, "Read every contract clause before signing.", "签字前读遍合同条款。", "sign a binding contract"),
  v("copyright-intellectual-property", "/版权", "/ˈkɑːpiraɪt/", "n.", 6, 0.6, "Copyright protects photos automatically.", "版权自动保护照片。", "register your copyright officially"),
  v("trademark-registration-office", "/商标", "/ˈtreɪdmɑːrk/", "n.", 7, 0.65, "Register the trademark before launch.", "发布前先注册商标。", "infringe a registered trademark"),
  v("patent-application-process", "/专利", "/ˈpætnt/", "n.", 7, 0.65, "The patent took three years to approve.", "专利花了三年才获批。", "file a patent application"),
  v("regulation-compliance-audit", "/规章；条例", "/ˌreɡjuˈleɪʃn/", "n.", 5, 0.45, "New regulations ban single-use plastics here.", "新规禁止一次性塑料制品。", "meet strict safety regulations"),
  v("lawyer-client-meeting", "/律师", "/ˈlɔːjər/", "n.", 3, 0.3, "Call your lawyer before answering questions.", "回答问题前先联系律师。", "hire a good lawyer"),
  v("justice-system-reform", "/正义；司法", "/ˈdʒʌstɪs/", "n.", 3, 0.3, "Justice delayed is justice denied.", "迟到的正义非正义。", "seek justice for victims"),
];
