import { v } from "@/content/vocab/builder";
import type { VocabRow } from "@/content/vocab/types";

/** Economics & trade - Phase 10 chunk-h. */
export const economicsTradeRows: VocabRow[] = [
  v("economy-growth-rate", "/经济", "/ɪˈkɑːnəmi/", "n.", 3, 0.25, "The economy added two million jobs.", "经济新增两百万岗位。", "boost the local economy"),
  v("inflation-rate-spike", "/通货膨胀", "/ɪnˈfleɪʃn/", "n.", 6, 0.55, "Inflation squeezed family budgets hard.", "通胀严重挤压家庭预算。", "curb rising inflation"),
  v("deflation-price-fall-risk", "/通货紧缩", "/dɪˈfleɪʃn/", "n.", 7, 0.7, "Deflation makes debts heavier over time.", "通缩会让债务越背越重。", "avoid a deflation spiral"),
  v("recession-two-quarters-decline", "/衰退；经济衰退", "/rɪˈseʃn/", "n.", 6, 0.6, "The recession lasted eighteen months.", "这次衰退持续了十八个月。", "brace for a deep recession"),
  v("depression-era-economics", "/萧条；抑郁", "/dɪˈpreʃn/", "n.", 5, 0.5, "The Great Depression reshaped banking law.", "大萧条重塑了银行法规。", "an economic depression cycle"),
  v("gdp-per-capita-figure", "/国内生产总值", "/ˌdʒiː diː ˈpiː/", "n.", 7, 0.65, "GDP grew three percent last quarter.", "上季度GDP增长百分之三。", "measure GDP per capita"),
  v("tariff-import-tax-hike", "/关税", "/ˈtærɪf/", "n.", 7, 0.65, "New tariffs raised steel prices overnight.", "新关税一夜推高钢价。", "impose tariffs on imports"),
  v("import-export-balance-sheet", "/进口；输入", "/ˈɪmpɔːrt/", "n./v.", 4, 0.35, "Imports fell while exports surged.", "进口下降而出口激增。", "rely on cheap imports"),
  v("export-market-expansion", "/出口；输出", "/ˈekspɔːrt/", "n./v.", 4, 0.4, "Exports of EVs doubled this year.", "今年电动车出口翻倍。", "expand export markets abroad"),
  v("trade-deficit-widening-gap", "/贸易逆差", "/treɪd ˈdefəsɪt/", "n.", 7, 0.65, "The trade deficit narrowed slightly.", "贸易逆差略有收窄。", "shrink the trade deficit"),
  v("free-trade-agreement-terms", "/自由贸易", "/friː treɪd/", "n.", 6, 0.6, "Free trade lowered consumer prices.", "自由贸易降低了消费品价格。", "sign a free trade deal"),
  v("supply-demand-equilibrium-price", "/供给；供应量", "/səˈplaɪ/", "n./v.", 3, 0.25, "Supply chains recovered slowly after the storm.", "风暴后供应链恢复缓慢。", "balance supply and demand"),
  v("demand-curve-shift-left", "/需求；要求", "/dɪˈmænd/", "n./v.", 3, 0.25, "Demand for rentals outpaces new builds.", "租赁需求超过新建速度。", "stimulate consumer demand"),
  v("monopoly-market-dominance", "/垄断；专利", "/məˈnɑːpəli/", "n.", 7, 0.65, "Regulators broke up the telecom monopoly.", "监管机构拆分了电信垄断企业。", "challenge the monopoly in court"),
  v("competition-market-rivalry", "/竞争；比赛", "/ˌkɑːmpəˈtɪʃn/", "n.", 3, 0.3, "Competition keeps prices honest.", "竞争让价格保持诚实。", "face fierce competition daily"),
  v("capital-investment-inflow", "/资本；首都", "/ˈkæpɪtl/", "n.", 4, 0.35, "Startup capital dried up last winter.", "去年冬天创业资本枯竭。", "raise capital from investors"),
  v("interest-rate-hike-cycle", "/利息；兴趣", "/ˈɪntrəst/", "n.", 2, 0.15, "Interest rates climbed again this month.", "本月利率再度上调。", "pay interest on the loan"),
  v("mortgage-refinance-options", "/抵押贷款", "/ˈmɔːrɡɪdʒ/", "n.", 5, 0.5, "Refinancing the mortgage saved us $300 monthly.", "再融资房贷每月省三百美元。", "apply for a fixed mortgage"),
  v("stock-market-index-fund", "/股票市场", "/stɑːk ˈmɑːrkɪt/", "n.", 4, 0.4, "The stock market rallied all spring.", "股市整个春天持续上涨。", "watch the stock market closely"),
  v("shareholder-annual-meeting", "/股东", "/ˈʃerhoʊldər/", "n.", 7, 0.6, "Shareholders demanded clearer disclosures.", "股东要求更清晰的信息披露。", "reward long-term shareholders"),
  v("dividend-quarterly-payment", "/股息；红利", "/ˈdɪvɪdend/", "n.", 7, 0.65, "Dividends arrived every March and September.", "股息每年三月和九月到账。", "declare a special dividend"),
  v("portfolio-diversification-strategy", "/投资组合", "/pɔːrtˈfoʊlioʊ/", "n.", 7, 0.65, "Diversify your portfolio across regions.", "跨区域分散你的投资组合。", "rebalance your portfolio yearly"),
  v("bond-yield-curve-chart", "/债券；纽带", "/bɑːnd/", "n.", 6, 0.6, "Government bonds feel safe but yield little.", "国债安全但收益微薄。", "buy ten-year treasury bonds"),
  v("commodity-price-swings", "/商品；日用品", "/kəˈmɑːdəti/", "n.", 7, 0.65, "Coffee is the second most traded commodity.", "咖啡是第二大交易大宗商品。", "track commodity prices weekly"),
  v("currency-exchange-booth", "/货币", "/ˈkɜːrənsi/", "n.", 5, 0.45, "Which currency should I carry in Japan?", "在日本该带哪种货币？", "exchange currency at fair rates"),
  v("fiscal-policy-spending-bill", "/财政的", "/ˈfɪskl/", "adj.", 7, 0.7, "Fiscal stimulus revived small businesses.", "财政刺激救活了小企业。", "the fiscal year ends in June"),
  v("monetary-policy-central-bank", "/货币的；金钱的", "/ˈmɑːnɪteri/", "adj.", 7, 0.7, "Monetary policy moves markets within minutes.", "货币政策几分钟内就能撼动市场。", "tighten monetary policy again"),
  v("central-bank-rate-decision", "/中央银行", "/ˈsentrəl bæŋk/", "n.", 6, 0.6, "The central bank cut rates unexpectedly.", "央行意外降息。", "the central bank governor speaks Friday"),
  v("budget-deficit-spending-plan", "/预算", "/ˈbʌdʒɪt/", "n.", 3, 0.3, "Our travel budget barely covered trains.", "我们的旅行预算勉强够火车票。", "stick to a tight budget"),
  v("subsidy-farm-support-payment", "/补贴；津贴", "/ˈsʌbsədi/", "n.", 7, 0.7, "EV subsidies boosted showroom traffic.", "电动车补贴提升了展厅客流。", "phase out fossil fuel subsidies"),
  v("wage-stagnation-debate", "/工资；报酬", "/weɪdʒ/", "n.", 3, 0.3, "Wages finally beat inflation this year.", "今年工资终于跑赢通胀。", "negotiate a higher starting wage"),
  v("minimum-wage-increase-law", "/最低工资", "/ˈmɪnɪməm weɪdʒ/", "n.", 4, 0.35, "The minimum wage rose to fifteen dollars.", "最低工资涨到十五美元。", "raise the minimum wage gradually"),
  v("unemployment-insurance-claim", "/失业", "/ˌʌnɪmˈplɔɪmənt/", "n.", 5, 0.45, "Unemployment fell to a record low.", "失业率降至历史低点。", "file an unemployment claim online"),
  v("labor-force-participation-rate", "/劳动力", "/ˈleɪbər fɔːrs/", "n.", 6, 0.6, "Automation is reshaping the labor force.", "自动化正在重塑劳动力结构。", "enter the labor force earlier"),
  v("outsourcing-overseas-call-centers", "/外包", "/ˈaʊtsɔːrsɪŋ/", "n.", 7, 0.65, "Outsourcing cut costs but hurt quality.", "外包降低了成本却伤害了质量。", "move outsourcing closer to home"),
  v("productivity-output-per-hour", "/生产率", "/ˌprɑːdʌkˈtɪvəti/", "n.", 6, 0.6, "Better tools lifted productivity twenty percent.", "更好的工具使生产率提升两成。", "improve team productivity steadily"),
  v("infrastructure-spending-bill", "/基础设施", "/ˈɪnfrəstrʌktʃər/", "n.", 6, 0.55, "Infrastructure spending fixes bridges first.", "基建支出优先修桥。", "invest heavily in infrastructure"),
  v("privatization-state-assets-sale", "/私有化", "/ˌpraɪvətəˈzeɪʃn/", "n.", 7, 0.75, "Privatization of railways remains contested.", "铁路私有化仍存争议。", "oppose the privatization plan"),
  v("nationalization-industry-takeover", "/国有化", "/ˌnæʃnələˈzeɪʃn/", "n.", 7, 0.8, "Nationalization debates returned during the crisis.", "危机期间国有化争论重现。", "consider nationalizing the grid"),
  v("globalization-supply-chain-effects", "/全球化", "/ˌɡloʊbələˈzeɪʃn/", "n.", 6, 0.6, "Globalization spread both jobs and ideas.", "全球化传播了就业也传播了思想。", "study globalization's uneven effects"),
  v("protectionism-tariff-wall", "/保护主义", "/prəˈtekʃənɪzəm/", "n.", 7, 0.75, "Protectionism raises prices at home.", "保护主义抬高本国物价。", "slide back into protectionism"),
  v("entrepreneur-small-business-owner", "/企业家", "/ˌɑːntrəprəˈnɜːr/", "n.", 6, 0.55, "Every entrepreneur starts with zero customers.", "每位企业家都从零客户起步。", "think like an entrepreneur"),
  v("consumer-confidence-index-drop", "/消费者", "/kənˈsuːmər/", "n.", 4, 0.3, "Consumers kept spending despite warnings.", "尽管有警告，消费者仍在消费。", "protect consumer rights firmly"),
  v("retail-store-foot-traffic", "/零售", "/ˈriːteɪl/", "n./adj.", 4, 0.35, "Retail sales dipped before the holidays.", "节前零售额小幅下滑。", "a career in retail management"),
  v("wholesale-bulk-discount-tier", "/批发", "/ˈhoʊlseɪl/", "n./adv.", 6, 0.6, "Wholesale buyers get thirty percent off.", "批发买家享七折优惠。", "buy wholesale in bulk lots"),
  v("e-commerce-platform-growth", "/电子商务", "/ˈiː kɑːmɜːrs/", "n.", 5, 0.45, "E-commerce keeps eating mall traffic.", "电商不断蚕食商场客流。", "launch an e-commerce storefront"),
  v("bankruptcy-chapter-eleven-filing", "/破产", "/ˈbæŋkrʌptsi/", "n.", 7, 0.65, "Three chains slid into bankruptcy.", "三家连锁滑向破产。", "file for bankruptcy protection"),
  v("insolvent-company-restructuring", "/资不抵债的", "/ɪnˈsɑːlvənt/", "adj.", 7, 0.8, "Insolvent firms need court protection fast.", "资不抵债的公司急需法院保护。", "declare itself insolvent legally"),
  v("prosperity-shared-growth-era", "/繁荣；兴旺", "/prɑːˈsperəti/", "n.", 6, 0.55, "Prosperity never reached the outer districts.", "繁荣从未惠及外围城区。", "bring lasting prosperity to rural areas"),
  v("poverty-line-threshold-income", "/贫困；贫穷", "/ˈpɑːvərti/", "n.", 4, 0.35, "One in eight children lives near poverty.", "每八个孩子就有一个生活在贫困边缘。", "escape generational poverty"),
];
