import { v } from "@/content/vocab/builder";
import type { VocabRow } from "@/content/vocab/types";

/** Media & journalism - Phase 10 chunk-h. */
export const mediaJournalismRows: VocabRow[] = [
  v("journalism-ethics-code", "/新闻业；新闻工作", "/ˈdʒɜːrnəlɪzəm/", "n.", 6, 0.6, "Good journalism checks every source twice.", "好的新闻业会把每个信源核查两遍。", "a career in investigative journalism"),
  v("journalist-field-reporter", "/新闻记者", "/ˈdʒɜːrnəlɪst/", "n.", 4, 0.35, "The journalist embedded with rescue teams.", "记者随救援队深入现场。", "interview journalists after the match"),
  v("reporter-breaking-news-desk", "/记者；报告员", "/rɪˈpɔːrtər/", "n.", 3, 0.3, "A reporter chased us for a comment.", "一名记者追着我们要评论。", "brief the reporters outside"),
  v("headline-grabbing-title", "/标题；头条", "/ˈhedlaɪn/", "n.", 4, 0.35, "That headline oversold the study.", "那个标题夸大了这项研究。", "make national headlines overnight"),
  v("newsroom-deadline-pressure", "/新闻编辑室", "/ˈnuːzruːm/", "n.", 7, 0.65, "The newsroom hums before every broadcast.", "每次播出前编辑室一片忙碌。", "pace the busy newsroom floor"),
  v("broadcast-live-transmission", "/广播；播放", "/ˈbrɔːdkæst/", "n./v.", 4, 0.35, "The interview broadcasts live at nine.", "采访九点现场直播。", "broadcast the game nationwide"),
  v("coverage-full-report-range", "/报道；覆盖范围", "/ˈkʌvərɪdʒ/", "n.", 5, 0.45, "Live coverage followed the storm north.", "直播报道追踪风暴北上。", "receive round-the-clock coverage"),
  v("press-conference-question-time", "/新闻发布会；媒体", "/pres ˈkɑːnfərəns/", "n.", 5, 0.5, "The coach faced a tense press conference.", "教练面对一场气氛紧张的发布会。", "hold a press conference at noon"),
  v("editorial-board-opinion-page", "/社论", "/ˌedɪˈtɔːriəl/", "n./adj.", 7, 0.7, "Their editorial demanded police reform.", "他们的社论要求警队改革。", "write the paper's lead editorial"),
  v("columnist-weekly-opinion-piece", "/专栏作家", "/ˈkɑːləmnɪst/", "n.", 7, 0.7, "Our columnist predicts elections eerily well.", "我们的专栏作家预言选举准得可怕。", "read her Saturday columnist take"),
  v("byline-credit-line", "/署名行", "/ˈbaɪlaɪn/", "n.", 7, 0.75, "Her byline appeared in three magazines.", "她的署名出现在三本杂志上。", "see your first byline printed"),
  v("scoop-exclusive-story-first", "/独家新闻；抢先报道", "/skuːp/", "n.", 7, 0.7, "The rookie landed the scoop of the year.", "新人拿到了年度独家新闻。", "beat rivals to the scoop"),
  v("exclusive-story-rights-deal", "/独有的；独家的", "/ɪkˈskluːsɪv/", "adj.", 5, 0.5, "We signed an exclusive interview deal.", "我们签了独家专访协议。", "an exclusive behind-the-scenes look"),
  v("fact-checking-team-verifies", "/事实核查", "/fækt ˈtʃekɪŋ/", "n.", 7, 0.65, "Fact-checking killed the viral rumor fast.", "事实核查迅速击破网络谣言。", "run every quote through fact-checking"),
  v("misinformation-false-content-spread", "/错误信息", "/ˌmɪsɪnfərˈmeɪʃn/", "n.", 7, 0.65, "Misinformation spreads six times faster than facts.", "错误信息传播速度是事实的六倍。", "flag health misinformation quickly"),
  v("disinformation-deliberate-campaign", "/虚假信息", "/ˌdɪsɪnfərˈmeɪʃn/", "n.", 7, 0.75, "Disinformation campaigns target swing voters.", "虚假信息运动瞄准摇摆选民。","trace the disinformation campaign's origin") ,
  v("censorship-government-control", "/审查；审查制度", "/ˈsensərʃɪp/", "n.", 7, 0.65, "Censorship silenced the documentary at home.", "审查让这部纪录片无法在国内上映。", "fight internet censorship openly"),
  v("propaganda-war-of-narratives", "/宣传；鼓吹", "/ˌprɑːpəˈɡændə/", "n.", 7, 0.65, "Wartime propaganda painted enemies as monsters.", "战时宣传把敌人描绘成怪物。", "detect state propaganda techniques"),
  v("tabloid-celebrity-gossip-paper", "/小报", "/ˈtæblɔɪd/", "n.", 7, 0.65, "Tabloids invented half that romance.", "小报编造了那段恋情的一半情节。", "sell millions of tabloid copies"),
  v("documentary-feature-length-film", "/纪录片", "/ˌdɑːkjuˈmentri/", "n.", 5, 0.45, "Her documentary won the audience award.", "她的纪录片赢得观众选择奖。", "stream an award-winning documentary"),
  v("podcast-episode-download", "/播客", "/ˈpɑːdkæst/", "n.", 4, 0.35, "Their podcast tops the history charts.", "他们的播客登顶历史类榜单。", "launch a weekly podcast show"),
  v("influencer-brand-partnership-post", "/网红；影响者", "/ˈɪnfluənsər/", "n.", 5, 0.45, "One influencer sold out the whole product line.", "一位网红卖空了整条产品线。", "hire a niche influencer campaign"),
  v("viral-video-million-views", "/病毒式传播的；走红的", "/ˈvaɪrəl/", "adj.", 5, 0.45, "Their wedding video went viral instantly.", "他们的婚礼视频瞬间走红。", "go viral on short-video platforms"),
  v("clickbait-headline-regret", "/标题党；诱饵标题", "/ˈklɪkbeɪt/", "n.", 7, 0.65, "Clickbait promises what articles never deliver.", "标题党承诺文章从不兑现的东西。", "resist obvious clickbait traps"),
  v("algorithm-feed-personalization", "/算法", "/ˈælɡərɪðəm/", "n.", 6, 0.55, "The algorithm decides what you watch next.", "算法决定你接下来看什么。", "outsmart the recommendation algorithm"),
  v("subscriber-paywall-model", "/订户；订阅者", "/səbˈskraɪbər/", "n.", 6, 0.55, "Subscribers fund real reporting now.", "如今订户支撑着真正的新闻报道。", "convert readers into subscribers"),
  v("circulation-print-run-numbers", "/发行量；流通", "/ˌsɜːrkjəˈleɪʃn/", "n.", 7, 0.7, "Print circulation keeps shrinking yearly.", "纸质发行量逐年萎缩。", "boost newspaper circulation figures"),
  v("archive-old-issues-search", "/档案馆；档案", "/ˈɑːrkaɪv/", "n./v.", 6, 0.6, "The archive holds every edition since 1923.", "档案馆收藏着1923年以来的每一期。", "dig through the photo archive"),
  v("press-pass-event-access", "/记者证", "/pres pæs/", "n.", 7, 0.65, "A press pass got us backstage legally.", "记者证让我们合法进入后台。", "renew your press pass annually"),
  v("paparazzi-celebrity-chasers", "/狗仔队", "/ˌpɑːpəˈrɑːtsi/", "n.", 7, 0.7, "Paparazzi camped outside her apartment for days.", "狗仔队在她公寓外蹲守数日。", "escape the paparazzi through side doors"),
  v("anonymous-source-protection", "/匿名的；无名的", "/əˈnɑːnɪməs/", "adj.", 6, 0.6, "An anonymous source leaked the memo.", "匿名人士泄露了备忘录。", "quote an anonymous whistleblower"),
  v("leak-classified-document-scandal", "/泄露；漏洞", "/liːk/", "v./n.", 5, 0.5, "Someone leaked the merger plans early.", "有人提前泄露了并购计划。", "plug the data leak immediately"),
  v("expose-investigative-revelation", "/揭露；曝光", "/ɪkˈspoʊz/", "v.", 4, 0.4, "The series exposed unsafe factories.", "该系列报道曝光了不安全工厂。", "expose corruption at the top"),
  v("bias-media-slant-criticism", "/媒体偏向性报道", "/ˈbaɪəs/", "n.", 5, 0.45, "Readers accuse every outlet of bias.", "读者指责每家媒体都有偏见。", "check stories for hidden bias"),
  v("objectivity-journalistic-standard", "/客观性", "/ˌɑːbdʒekˈtɪvəti/", "n.", 7, 0.7, "Perfect objectivity is a moving target.", "完美的客观性是个移动靶。", "strive for strict objectivity"),
  v("interview-tough-question-round", "/面试；访谈", "/ˈɪntərvjuː/", "n./v.", 2, 0.2, "She nailed every interview question calmly.", "她沉着答好每个面试问题。", "prepare for the panel interview"),
  v("press-release-official-statement", "/新闻稿", "/pres rɪˈliːs/", "n.", 6, 0.6, "The startup sent a press release at dawn.", "初创公司清晨发出新闻稿。", "draft a crisp press release"),
  v("statement-official-response-text", "/声明；陈述", "/ˈsteɪtmənt/", "n.", 3, 0.25, "The bank issued a short statement.", "银行发布了一份简短声明。", "release a formal statement today"),
  v("media-outlet-news-platform", "/媒体机构；途径", "/ˈmiːdiə ˈaʊtlet/", "n.", 6, 0.6, "Every major outlet covered the verdict.", "各大媒体都报道了判决。", "pitch the story to multiple outlets"),
  v("audience-engagement-metrics", "/观众；听众", "/ˈɔːdiəns/", "n.", 3, 0.25, "The audience laughed at line three.", "观众在第三句笑了起来。", "know your target audience deeply"),
  v("viewer-ratings-sweep-week", "/观众；收看者", "/ˈvjuːər/", "n.", 5, 0.45, "Viewership doubled after the finale twist.", "大结局反转后观众数翻倍。", "lose viewers to streaming rivals"),
  v("ratings-sweep-period-results", "/收视率；评级", "/ˈreɪtɪŋz/", "n.", 6, 0.55, "Ratings dipped after the host left.", "主持人离开后收视率下滑。", "chase higher prime-time ratings"),
  v("airtime-commercial-slot-cost", "/播放时间；空中时间", "/ˈertaɪm/", "n.", 7, 0.7, "Paid airtime during finals costs a fortune.", "决赛时段的广告位价格不菲。", "buy airtime before launch day"),
  v("soundbite-quotable-clip-length", "/（广播、电视中的）简短引语", "/ˈsaʊndbaɪt/", "n.", 7, 0.75, "Politicians live on ten-second soundbites.", "政客靠十秒钟的金句过活。", "craft a memorable soundbite"),
  v("off-the-record-background-briefing", "/不供发表的；私下的", "/ˈrekərd/", "n./v./adj.", 3, 0.3, "The chat was strictly off the record.", "那次谈话绝对不可公开引用。", "keep it off the record please"),
  v("correspondent-foreign-bureau-chief", "/驻外记者；通讯员", "/ˌkɔːrəˈspɑːndənt/", "n.", 7, 0.7, "Our correspondent filed from the border tonight.", "我们的驻外记者今晚从边境发回报道。", "our Beijing correspondent reports"),
];
