import { v } from "@/content/vocab/builder";
import type { VocabRow } from "@/content/vocab/types";

/** Literature & books - Phase 10 chunk-h. */
export const literatureBooksRows: VocabRow[] = [
  v("literature-classic-novels-list", "/文学；文学作品", "/ˈlɪtərətʃər/", "n.", 4, 0.35, "Russian literature rewards patient readers.", "俄罗斯文学回报耐心的读者。", "a degree in comparative literature"),
  v("fiction-short-story-collection", "/小说；虚构", "/ˈfɪkʃn/", "n.", 3, 0.3, "Science fiction asks what if endlessly.", "科幻小说无穷尽地追问如果怎样。", "a shelf of quality fiction"),
  v("nonfiction-true-story-section", "/非虚构；纪实文学", "/nɑːnˈfɪkʃn/", "n.", 5, 0.45, "Nonfiction sells better in December.", "十二月非虚构类更好卖。", "write narrative nonfiction instead"),
  v("novel-plot-twist-ending", "/小说；新奇的", "/ˈnɑːvl/", "n./adj.", 2, 0.2, "Her debut novel surprised everyone.", "她的处女作惊到了所有人。", "publish a bestselling novel"),
  v("poetry-rhyme-and-meter", "/诗歌", "/ˈpoʊətri/", "n.", 4, 0.35, "Poetry hides whole storms in eight words.", "诗歌用八个字藏下整场风暴。", "read poetry aloud nightly"),
  v("biography-famous-life-story", "/传记", "/baɪˈɑːɡrəfi/", "n.", 5, 0.5, "The biography took seven years of research.", "这本传记花了七年研究。", "an authorized biography deal"),
  v("autobiography-first-person-account", "/自传", "/ˌɔːtəbaɪˈɑːɡrəfi/", "n.", 7, 0.7, "His autobiography spares nobody, including himself.", "他的自传不放过任何人，包括自己。", "ghostwrite a CEO's autobiography"),
  v("memoir-childhood-recollection", "/回忆录", "/ˈmemwɑːr/", "n.", 7, 0.65, "Her memoir reads like a road trip.", "她的回忆录读起来像一场公路旅行。", "pitch the memoir to publishers"),
  v("protagonist-hero-journey", "/主人公；主角", "/proʊˈtæɡənɪst/", "n.", 7, 0.6, "The protagonist never leaves her village.", "主人公从未离开村庄。", "root for the flawed protagonist"),
  v("antagonist-villain-motive", "/反派；对手", "/ænˈtæɡənɪst/", "n.", 7, 0.65, "A great antagonist believes he is right.", "出色的反派坚信自己是对的。", "flesh out the antagonist's past"),
  v("narrator-unreliable-voice", "/叙述者；旁白", "/ˈnæreɪtər/", "n.", 7, 0.65, "The narrator admits lying twice.", "叙述者两次承认撒谎。", "an unreliable narrator trick"),
  v("plot-line-summary-chart", "/情节", "/plɑːt/", "n.", 3, 0.25, "The plot thickens at chapter nine.", "第九章情节变得扑朔迷离。", "lose the plot halfway through"),
  v("subplot-secondary-thread", "/次要情节", "/ˈsʌbplɑːt/", "n.", 7, 0.7, "The romance subplot steals every scene.", "爱情副线抢尽风头。", "trim the unnecessary subplot"),
  v("chapter-opening-hook-line", "/章节", "/ˈtʃæptər/", "n.", 2, 0.15, "Read one chapter before bed.", "睡前读一章。", "end the chapter on a cliffhanger"),
  v("cliffhanger-episode-ending", "/悬念；扣人心弦的结尾", "/ˈklɪfhæŋər/", "n.", 7, 0.65, "Every episode ends on a cliffhanger.", "每集都以悬念收尾。", "a brutal cliffhanger finale"),
  v("setting-time-place-frame", "/背景；设定", "/ˈsetɪŋ/", "n.", 4, 0.35, "The setting shifts from Kyoto to Oslo.", "故事背景从京都转到奥斯陆。", "describe the setting vividly"),
  v("theme-recurring-motif-idea", "/主题", "/θiːm/", "n.", 4, 0.35, "Loneliness anchors the whole theme.", "孤独是贯穿全书的主题。", "explore the theme of exile"),
  v("metaphor-comparison-image", "/隐喻；暗喻", "/ˈmetəfɔːr/", "n.", 6, 0.6, "Time is a thief — a tired metaphor.", "时间是贼——一个老套的隐喻。", "extend the central metaphor"),
  v("simile-like-or-as", "/明喻；直喻", "/ˈsɪməli/", "n.", 7, 0.65, "Brave as a lion is a classic simile.", "勇猛如狮是经典明喻。", "sprinkle in fresh similes"),
  v("symbolism-deeper-meaning-layer", "/象征主义；象征手法", "/ˈsɪmbəlɪzəm/", "n.", 7, 0.7, "Green light symbolism haunts that novel.", "那部小说中绿灯的象征意味挥之不去。", "analyze the heavy symbolism"),
  v("irony-verbal-situational-difference", "/讽刺；反讽", "/ˈaɪrəni/", "n.", 5, 0.5, "The irony: the fire station burned down.", "讽刺的是：消防站烧毁了。", "appreciate dry irony"),
  v("satire-sharp-social-mockery", "/讽刺作品；讥讽", "/ˈsætaɪər/", "n.", 7, 0.7, "The show's satire skewers office life.", "这部剧的讽刺直戳职场生态。", "master gentle political satire"),
  v("allegory-hidden-political-story", "/寓言；讽喻", "/ˈæləɡɔːri/", "n.", 7, 0.75, "Animal Farm works as political allegory.", "《动物农场》是一部政治寓言。", "read it as cold-war allegory"),
  v("foreshadowing-early-hints-planted", "/伏笔；预示", "/fɔːrˈʃædoʊɪŋ/", "n.", 7, 0.7, "Smart foreshadowing rewards second reads.", "巧妙的伏笔值得重读。", "plant subtle foreshadowing early"),
  v("flashback-scene-memory-cut", "/闪回；倒叙", "/ˈflæʃbæk/", "n.", 6, 0.55, "A flashback explains his scar.", "一段闪回解释了他的伤疤。", "open with a brief flashback"),
  v("climax-tension-peak-scene", "/高潮；顶点", "/ˈklaɪmæks/", "n.", 5, 0.5, "The courtroom scene is the climax.", "法庭戏是全书高潮。", "build toward the climax slowly"),
  v("denouement-final-resolution", "/结局；收场", "/ˌdeɪnuːˈmɑːŋ/", "n.", 7, 0.8, "The denouement ties three threads neatly.", "结局把三条线干净利落地收拢。", "a satisfying denouement at last"),
  v("epilogue-after-the-ending", "/尾声；后记", "/ˈepɪlɔːɡ/", "n.", 7, 0.7, "The epilogue jumps twenty years ahead.", "尾声直接跳到二十年后。", "read the sweet epilogue aloud"),
  v("prologue-before-chapter-one", "/序言；序幕", "/ˈproʊlɔːɡ/", "n.", 7, 0.7, "Skip nothing — even the prologue matters.", "什么都别跳过——连序言都重要。", "rewrite the prologue again"),
  v("manuscript-submission-envelope", "/手稿；底稿", "/ˈmænjuskrɪpt/", "n.", 7, 0.7, "Agents reject ninety manuscripts weekly.", "经纪人每周退稿九十份。", "polish your manuscript before submitting"),
  v("publisher-printing-house-deal", "/出版商；出版社", "/ˈpʌblɪʃər/", "n.", 5, 0.5, "Three publishers bid for the rights.", "三家出版社竞标版权。", "sign with a major publisher"),
  v("bestseller-top-ten-list", "/畅销书", "/ˌbestˈselər/", "n.", 5, 0.45, "Her third book became an instant bestseller.", "她的第三本书一上市就成了畅销书。", "top the bestseller lists worldwide"),
  v("bookworm-library-regular", "/书虫；书迷", "/ˈbʊkwɜːrm/", "n.", 5, 0.4, "Bookworms smell rain and old paper alike.", "书虫对雨味和旧纸味一视同仁。", "a certified bookworm since childhood"),
  v("bookshelf-alphabetical-order", "/书架", "/ˈbʊkʃelf/", "n.", 3, 0.25, "Sagging bookshelves mean a good home.", "压弯的书架说明这是个有故事的家。", "reorganize the overflowing bookshelf"),
  v("bookmark-last-page-marker", "/书签", "/ˈbʊkmɑːrk/", "n./v.", 4, 0.3, "Use the receipt as a bookmark.", "拿小票当书签吧。", "bookmark the recipe page"),
  v("library-card-signup-desk", "/图书馆", "/ˈlaɪbreri/", "n.", 1, 0.1, "Libraries lend more than books now.", "如今图书馆外借的不只是书。", "renew library loans online"),
  v("librarian-helpful-desk-person", "/图书管理员", "/laɪˈbreriən/", "n.", 4, 0.3, "Ask the librarian; they know everything.", "问图书管理员，他们无所不知。", "thank the school librarian warmly"),
  v("hardcover-collectors-edition", "/精装本", "/ˈhɑːrdkʌvər/", "n./adj.", 6, 0.55, "Hardcovers drop months before paperbacks.", "精装版比平装早几个月上市。", "pre-order the signed hardcover"),
  v("paperback-travel-edition", "/平装本", "/ˈpeɪpərbæk/", "n.", 5, 0.45, "Beat-up paperbacks travel best.", "翻旧的平装书最适合旅行。", "swap dog-eared paperbacks with friends"),
  v("e-reader-screen-adjustment", "/电子阅读器", "/ˈiː riːdər/", "n.", 5, 0.4, "An e-reader holds a thousand trips.", "一台电子阅读器装得下一千次旅程。", "load the e-reader before flying"),
  v("audiobook-commute-companion", "/有声书", "/ˈɔːdioʊbʊk/", "n.", 5, 0.4, "Audiobooks tame traffic jams.", "有声书驯服了堵车时光。", "finish two audiobooks monthly"),
  v("translator-language-bridge-work", "/译者；翻译者", "/trænzˈleɪtər/", "n.", 6, 0.6, "Great translators are invisible artists.", "伟大的译者是隐形的艺术家。", "hire a sworn legal translator"),
  v("anthology-selected-poems-volume", "/选集；文选", "/ænˈθɑːlədʒi/", "n.", 7, 0.75, "This anthology spans four poetic centuries.", "这部选集横跨四个诗歌世纪。", "assign the poetry anthology"),
  v("installment-series-next-part", "/连载的一集；分期", "/ɪnˈstɔːlmənt/", "n.", 7, 0.7, "Fans queued for installment number twelve.", "粉丝们排队等第十二部。", "pay in easy monthly installments"),
  v("serial-weekly-publishing-format", "/连载的；连续的", "/ˈsɪriəl/", "adj./n.", 7, 0.7, "Dickens published novels as serials first.", "狄更斯的小说最初以连载形式发表。", "follow the gripping serial weekly"),
  v("critique-balanced-review-essay", "/评论；批评", "/krɪˈtiːk/", "n./v.", 7, 0.7, "Fair critique helps writers grow.", "公允的批评助作家成长。", "offer constructive critique kindly"),
  v("plagiarized-content-scandal-copy", "/剽窃的；抄袭的", "/ˈpleɪdʒəraɪzd/", "adj.", 7, 0.7, "Two chapters were quietly plagiarized.", "有两章被悄悄抄袭了。", "pull the plagiarized edition immediately"),
  v("censorship-banned-books-week", "/查禁；删改", "/ˈsensər/", "v./n.", 7, 0.7, "Schools shouldn't censor classic novels.", "学校不应查禁经典小说。", "censor violent scenes heavily"),
  v("literary-prize-ceremony-night", "/文学的；文学上的", "/ˈlɪtəreri/", "adj.", 7, 0.65, "Literary fame rarely pays rent.", "文学名声很少付得起房租。", "win a major literary award"),
];
