import { v } from "@/content/vocab/builder";
import type { VocabRow } from "@/content/vocab/types";

/** Music & performance - Phase 10 chunk-h. */
export const musicPerformanceRows: VocabRow[] = [
  v("melody-humming-tune-line", "/旋律；曲调", "/ˈmelədi/", "n.", 4, 0.35, "That melody lives rent-free in my head.", "那段旋律一直在我脑内循环。", "carry the main melody confidently"),
  v("harmony-vocal-blend-parts", "/和声；融洽", "/ˈhɑːrməni/", "n.", 5, 0.5, "Three-part harmony gave me goosebumps.", "三声部和声让我起鸡皮疙瘩。", "sing in perfect harmony"),
  v("rhythm-clap-along-pattern", "/节奏；韵律", "/ˈrɪðəm/", "n.", 4, 0.35, "Clap the rhythm before you play it.", "演奏前先拍出节奏。", "lock into the rhythm section"),
  v("tempo-speed-marking-change", "/速度；拍子", "/ˈtempoʊ/", "n.", 6, 0.55, "Nerves pushed the tempo too fast.", "紧张让速度弹得过快。", "slow the tempo down slightly"),
  v("lyrics-meaningful-words-sheet", "/歌词", "/ˈlɪrɪks/", "n.", 4, 0.35, "Simple lyrics often hit hardest.", "简单的歌词往往最戳心。", "memorize the lyrics by heart"),
  v("chorus-everyone-sings-part", "/副歌；合唱团", "/ˈkɔːrəs/", "n.", 5, 0.5, "The chorus lifts twice, then explodes.", "副歌推两次然后爆发。", "join the community chorus tonight"),
  v("verse-story-first-section", "/诗句；韵文", "/vɜːrs/", "n.", 4, 0.4, "The second verse tells the backstory.", "第二段主歌交代了背景故事。", "rhyme the closing verse neatly"),
  v("bridge-song-transition-section", "/桥段；桥梁", "/brɪdʒ/", "n.", 2, 0.15, "A key change saves the bridge.", "一次转调救活了桥段。", "build tension through the bridge"),
  v("acoustic-unplugged-guitar-set", "/原声的；声学的", "/əˈkuːstɪk/", "adj.", 5, 0.45, "The acoustic version exposes every flaw.", "不插电版本暴露所有瑕疵。", "record an acoustic session live"),
  v("amplifier-stack-loud-stage", "/放大器；扩音器", "/ˈæmplɪfaɪər/", "n.", 7, 0.65, "Crank the amplifier gently at first.", "先把放大器音量慢慢开大。", "haul the heavy amplifier upstairs"),
  v("microphone-feedback-screech-fix", "/麦克风；话筒", "/ˈmaɪkrəfoʊn/", "n.", 4, 0.35, "Tap the microphone twice before speaking.", "发言前轻敲两下麦克风。", "hand the roaming microphone around"),
  v("concert-tour-opening-night", "/音乐会；演唱会", "/ˈkɑːnsərt/", "n.", 3, 0.3, "The concert sold out in nine minutes.", "演唱会九分钟售罄。", "attend an open-air concert"),
  v("gig-small-venue-show", "/（流行音乐或爵士乐）现场演出", "/ɡɪɡ/", "n.", 6, 0.6, "Their first gig drew eleven people.", "他们首演只来了十一个人。", "book three summer gigs locally"),
  v("encore-shout-one-more-song", "/返场；加演", "/ˈɑːŋkɔːr/", "n.", 7, 0.7, "The encore lasted twenty glorious minutes.", "返场持续了精彩的二十分钟。", "demand an encore loudly"),
  v("backstage-pass-crew-area-only", "/后台", "/ˌbækˈsteɪdʒ/", "adv./adj.", 6, 0.55, "Backstage smells of hairspray and nerves.", "后台弥漫发胶和紧张的气味。", "wait nervously backstage together"),
  v("rehearsal-run-through-schedule", "/排练", "/rɪˈhɜːrsəl/", "n.", 5, 0.5, "Rehearsal runs every Tuesday night.", "每周二晚排练。", "run a full dress rehearsal"),
  v("audition-nervous-two-minutes", "/试镜；试唱", "/ɔːˈdɪʃn/", "n./v.", 6, 0.6, "She nailed the audition cold.", "她毫无准备却拿下试镜。", "prepare thoroughly for the audition"),
  v("orchestra-symphony-hall-seating", "/管弦乐队", "/ˈɔːrkɪstrə/", "n.", 5, 0.5, "The orchestra tuned as one instrument.", "整个乐团像一件乐器般校音。", "sit in with the youth orchestra"),
  v("conductor-baton-wave-tempo", "/指挥；（公交车）售票员", "/kənˈdʌktər/", "n.", 5, 0.5, "The conductor silenced us with one glance.", "指挥一个眼神就让大家安静。", "follow the conductor's cutoff precisely"),
  v("violin-solo-bow-control", "/小提琴", "/ˌvaɪəˈlɪn/", "n.", 4, 0.4, "Rosin dust covered her violin case.", "松香粉落满她的小提琴盒。", "tune the violin before class"),
  v("cello-deep-string-instrument", "/大提琴", "/ˈtʃeloʊ/", "n.", 6, 0.6, "A cello hums like a warm engine.", "大提琴哼鸣像温暖的引擎。", "carry the cello on the subway"),
  v("trumpet-brass-fanfare-note", "/小号；喇叭", "/ˈtrʌmpɪt/", "n.", 4, 0.4, "His trumpet cut through the parade.", "他的小号穿透游行队伍。", "hit the high trumpet note clean"),
  v("drum-kit-rhythm-backbone", "/架子鼓", "/drʌm kɪt/", "n.", 4, 0.4, "Neighbors tolerate the drum kit until ten.", "邻居容忍架子鼓到十点。", "mic the drum kit properly"),
  v("piano-keyboard-practice-scale", "/钢琴", "/piˈænoʊ/", "n.", 1, 0.1, "Grandma taught piano for forty years.", "奶奶教了四十年钢琴。", "practice piano scales daily"),
  v("saxophone-jazz-smooth-reed", "/萨克斯管", "/ˈsæksəfoʊn/", "n.", 6, 0.6, "A distant saxophone owned the midnight street.", "远处的萨克斯占领午夜街头。", "wail on the saxophone all night"),
  v("flute-breath-light-melody", "/长笛", "/fluːt/", "n.", 4, 0.4, "Birds answered her flute practice.", "鸟儿应和她练习长笛。", "clean the flute swab nightly"),
  v("band-members-rehearse-together", "/乐队；一群", "/bænd/", "n.", 2, 0.2, "Our band argues about setlists weekly.", "我们乐队每周为歌单吵架。", "start a garage band together"),
  v("album-twelve-track-release", "/专辑；相册", "/ˈælbəm/", "n.", 3, 0.25, "Their third album finally clicked.", "他们的第三张专辑终于成了。", "drop a surprise album at midnight"),
  v("single-radio-edit-version", "/单曲；单个的", "/ˈsɪŋɡl/", "n./adj.", 3, 0.25, "The lead single leaked a week early.", "主打单曲提前一周泄露。", "release the debut single Friday"),
  v("playlist-workout-focus-mix", "/播放列表", "/ˈpleɪlɪst/", "n.", 4, 0.3, "My running playlist is ninety percent drums.", "我的跑步歌单九成是鼓点。", "share your road-trip playlist"),
  v("streaming-platform-music-library", "/流媒体", "/ˈstriːmɪŋ/", "n.", 4, 0.35, "Streaming pays fractions of a cent per play.", "流媒体每次播放只付几分之一美分。", "switch streaming services again"),
  v("busker-street-performer-hat", "/街头艺人", "/ˈbʌskər/", "n.", 7, 0.7, "The busker earned applause, not coins.", "街头艺人赢得掌声而非硬币。", "tip your favorite busker generously"),
  v("karaoke-night-brave-microphone", "/卡拉OK", "/ˌkæriˈoʊki/", "n.", 5, 0.4, "Karaoke revealed his hidden falsetto.", "K歌暴露了他的隐藏假音。", "own the karaoke stage fearlessly"),
  v("fanbase-loyal-followers-count", "/粉丝群", "/ˈfænbeɪs/", "n.", 6, 0.55, "A tiny fanbase kept them touring.", "小小的粉丝群支撑他们巡演至今。", "grow a devoted fanbase slowly"),
  v("tour-manager-logistics-nightmare", "/巡演；巡回", "/tʊr/", "n./v.", 3, 0.25, "The world tour emptied their savings.", "世界巡演掏空了积蓄。", "kick off the comeback tour"),
  v("soundcheck-line-check-before-doors", "/试音；音响检查", "/ˈsaʊndtʃek/", "n.", 7, 0.65, "Soundcheck caught the dead cable just in time.", "试音及时发现了断线。", "skip soundcheck at your peril"),
  v("stage-fright-cold-hands-cure", "/怯场", "/steɪdʒ fraɪt/", "n.", 6, 0.55, "Stage fright shrinks after ten shows.", "演过十场后怯场会缩小。", "battle stage fright with breathing drills"),
  v("spotlight-blind-bright-circle", "/聚光灯；众人瞩目焦点", "/ˈspɑːtlaɪt/", "n.", 5, 0.5, "The spotlight found her mid-note.", "聚光灯在她唱到一半时找到她。", "step out of the spotlight briefly"),
  v("applause-thunderous-house-reaction", "/掌声；喝彩", "/əˈplɔːz/", "n.", 4, 0.35, "Applause rolled like weather through the hall.", "掌声如天气般在大厅里滚动。", "burst into spontaneous applause"),
  v("standingovation-feet-long-cheer", "/起立鼓掌", "/ˈstændɪŋ oʊˈveɪʃn/", "n.", 7, 0.65, "The standing ovation refused to stop.", "起立鼓掌经久不息。", "earn a rare standing ovation"),
];
