import { v } from "@/content/vocab/builder";
import type { VocabRow } from "@/content/vocab/types";

/** Philosophy, religion & ideas - Phase 10 chunk-h. */
export const philosophyIdeasRows: VocabRow[] = [
  v("philosophy-big-questions-course", "/哲学", "/fəˈlɑːsəfi/", "n.", 5, 0.45, "Philosophy teaches questions, not answers.", "哲学教的是提问而非答案。", "study ancient Greek philosophy"),
  v("logic-premise-conclusion-chain", "/逻辑；逻辑学", "/ˈlɑːdʒɪk/", "n.", 4, 0.35, "Emotion broke the logic chain mid-step.", "情绪在半途打断了逻辑链。", "follow the cold hard logic"),
  v("reason-rational-thought-process", "/理性；理由", "/ˈriːzn/", "n./v.", 2, 0.15, "Reason lost to hunger that day.", "那天理性输给了饥饿。", "argue from reason alone"),
  v("rational-well-reasoned-choice", "/理性的；合理的", "/ˈræʃnəl/", "adj.", 6, 0.55, "Panic beats rational planning every time.", "恐慌总是击败理性规划。", "make a purely rational decision"),
  v("wisdom-earned-over-years", "/智慧；才智", "/ˈwɪzdəm/", "n.", 3, 0.3, "Grandma's wisdom fits on one index card.", "奶奶的智慧写在一张卡片上。", "share hard-won wisdom freely"),
  v("truth-absolute-or-relative", "/真理；事实", "/truːθ/", "n.", 3, 0.25, "Truth survived the courtroom barely.", "真理在法庭上勉强幸存。", "seek the plain truth first"),
  v("belief-core-conviction-held", "/信念；信仰", "/bɪˈliːf/", "n.", 3, 0.25, "Beliefs bend slowly under new evidence.", "信念在新证据下缓缓弯曲。", "challenge your deepest beliefs"),
  v("faith-doubt-companion-cycle", "/信任；信心", "/feɪθ/", "n.", 3, 0.3, "Faith carried the village through famine.", "信念支撑村庄度过饥荒。", "keep faith with old friends"),
  v("doubt-healthy-questioning-mind", "/怀疑；疑问", "/daʊt/", "n./v.", 3, 0.25, "Doubt is curiosity wearing a coat.", "怀疑是穿上外套的好奇心。", "cast doubt on shaky claims"),
  v("skeptic-question-everything-first", "/怀疑者；持怀疑态度的人", "/ˈskeptɪk/", "n.", 7, 0.65, "A healthy skeptic checks receipts twice.", "健康的怀疑者会两次核对收据。", "convert even the fiercest skeptic"),
  v("ethics-right-and-wrong-study", "/伦理学；道德准则", "/ˈeθɪks/", "n.", 6, 0.6, "Business ethics class changed my hiring habits.", "商业伦理课改变了我的招聘习惯。", "a strict personal ethics code"),
  v("morality-shared-values-system", "/道德；品行", "/məˈræləti/", "n.", 7, 0.65, "Morality predates written law by millennia.", "道德比成文法早了几千年。", "question inherited morality quietly"),
  v("virtue-practiced-good-habit", "/美德；优点", "/ˈvɜːrtʃuː/", "n.", 7, 0.65, "Patience is a boring but mighty virtue.", "耐心是无聊却强大的美德。", "prize quiet everyday virtues"),
  v("vice-bad-habit-shadow", "/恶习；缺点", "/vaɪs/", "n.", 6, 0.6, "Gossip was his one admitted vice.", "八卦是他唯一承认的恶习。", "trade one vice for a better habit"),
  v("justice-fair-treatment-ideal", "/正义；公正", "/ˈdʒʌstɪs/", "n.", 3, 0.3, "Poets define justice better than courts.", "诗人对正义的定义胜过法庭。", "demand social justice reforms"),
  v("equality-equal-standing-principle", "/平等；相等", "/iˈkwɑːləti/", "n.", 4, 0.35, "Equality sounds simple and costs everything.", "平等听起来简单，代价高昂。", "champion gender equality openly"),
  v("liberty-personal-freedom-idea", "/自由；自由权", "/ˈlɪbərti/", "n.", 6, 0.55, "Liberty ends where panic begins.", "自由止于恐慌开始处。", "defend individual liberty fiercely"),
  v("free-will-versus-fate-debate", "/自由意志", "/friː wɪl/", "n.", 7, 0.7, "Free will feels real from inside.", "自由意志从内部感受无比真实。", "debate free will after dinner"),
  v("destiny-written-in-stars-claim", "/命运；天命", "/ˈdestəni/", "n.", 5, 0.5, "She refused to accept destiny as an excuse.", "她拒绝拿命运当借口。", "shape your own destiny daily"),
  v("consciousness-hard-problem-field", "/意识；知觉", "/ˈkɑːnʃəsnəs/", "n.", 7, 0.75, "Consciousness still embarrasses science.", "意识仍让科学难堪。", "theories of consciousness multiply yearly"),
  v("perception-is-not-reality-gap", "/感知；看法", "/pərˈsepʃn/", "n.", 6, 0.6, "Marketing sells perception, not products.", "营销卖的是认知而非产品。", "shift public perception gradually"),
  v("reality-check-brutal-honesty", "/现实；实际", "/riˈæləti/", "n.", 3, 0.25, "Rent checks are reality's favorite teacher.", "房租账单是现实最好的老师。", "face the harsh reality early"),
  v("illusion-magic-trick-mind", "/错觉；幻觉", "/ɪˈluːʒn/", "n.", 5, 0.5, "Control is mostly a comforting illusion.", "掌控感多半是种安慰性错觉。", "shatter the illusion completely"),
  v("paradox-self-contradictory-truth", "/悖论；自相矛盾", "/ˈpærədɑːks/", "n.", 7, 0.7, "Less choice creating less joy is a modern paradox.", "选择越多快乐越少是现代悖论。", "embrace the productive paradox"),
  v("dilemma-two-bad-options-pick", "/困境；两难", "/dɪˈlemə/", "n.", 5, 0.5, "The classic dilemma: loyalty versus honesty.", "经典两难：忠诚还是诚实。", "face a genuine moral dilemma"),
  v("existential-meaning-crisis-hour", "/存在的；关于存在的", "/ˌegzɪˈstenʃl/", "adj.", 7, 0.75, "Sunday nights bring mild existential dread.", "周日夜晚带来轻微的存在焦虑。", "an existential threat to the company"),
  v("nihilism-nothing-matters-phase", "/虚无主义", "/ˈnaɪɪlɪzəm/", "n.", 7, 0.8, "Nihilism is boredom with a diploma.", "虚无主义是拿了文凭的无聊。", "slip briefly into nihilism"),
  v("stoicism-calm-under-storms", "/斯多葛主义；坚忍", "/ˈstoʊɪsɪzəm/", "n.", 7, 0.75, "Stoicism went viral as morning routines.", "斯多葛主义以晨间流程的形式走红。", "practice daily stoicism deliberately"),
  v("utopia-perfect-society-blueprint", "/乌托邦；理想社会", "/juːˈtoʊpiə/", "n.", 7, 0.7, "Every utopia needs someone to sweep.", "每个乌托邦都需要扫地的。", "sketch your personal utopia"),
  v("dystopia-dark-future-warning", "/反乌托邦；反面乌托邦", "/dɪˈstoʊpiə/", "n.", 7, 0.7, "Dystopias warn better than they predict.", "反乌托邦作品长于警示短于预言。", "a chilling corporate dystopia novel"),
  v("ideology-belief-package-deal", "/意识形态；思想体系", "/ˌaɪdiˈɑːlədʒi/", "n.", 7, 0.7, "No ideology survives contact with rent day.", "没有哪种意识形态扛得过交租日。", "reject rigid ideology altogether"),
  v("doctrine-official-teaching-set", "/教义；主义", "/ˈdɑːktrɪn/", "n.", 7, 0.7, "The doctrine evolved quietly over centuries.", "教义数百年来悄然演变。", "quote party doctrine verbatim"),
  v("dogma-unquestionable-rule-list", "/教条；独断论", "/ˈdɔːɡmə/", "n.", 7, 0.7, "Science dies when it turns dogma.", "科学一旦变成教条就会死去。", "question the central dogma boldly"),
  v("ritual-comfort-of-repetition", "/仪式；例行公事", "/ˈrɪtʃuəl/", "n.", 4, 0.4, "Morning coffee became our little ritual.", "早晨的咖啡成了我们的小仪式。", "follow the tea ceremony ritual exactly"),
  v("tradition-passed-down-generations", "/传统；惯例", "/trəˈdɪʃn/", "n.", 3, 0.25, "Tradition tastes best around crowded tables.", "传统在拥挤的餐桌旁最有味道。", "uphold family traditions proudly"),
  v("custom-local-way-doing", "/习俗；风俗", "/ˈkʌstəm/", "n.", 3, 0.3, "Follow local custom when gift-giving abroad.", "在国外送礼要遵循当地习俗。", "respect unfamiliar local customs"),
  v("heritage-site-world-list", "/遗产；继承物", "/ˈherɪtɪdʒ-n2/", "n.", 5, 0.45, "Heritage recipes carry migration maps inside.", "传家菜谱里藏着移民路线图。", "celebrate your mixed heritage proudly"),
  v("spiritual-not-necessarily-religious", "/精神的；心灵的", "/ˈspɪrɪtʃuəl/", "adj.", 5, 0.5, "Long walks are her spiritual practice.", "长途散步是她的心灵修行。", "feel deeply spiritual in nature"),
  v("meditation-daily-ten-minutes-habit", "/冥想；沉思", "/ˌmedɪˈteɪʃn/", "n.", 4, 0.35, "Ten-minute meditation tamed his temper.", "十分钟冥想驯服了他的坏脾气。", "build a morning meditation habit"),
  v("monastery-quiet-hill-retreat", "/修道院；寺院", "/ˈmɑːnəsteri/", "n.", 7, 0.7, "Monks copied books in cold monasteries.", "僧侣们在冰冷的寺院里抄书。", "visit a mountain monastery retreat"),
  v("temple-incense-morning-visit", "/庙；寺院", "/ˈtempl/", "n.", 3, 0.3, "Incense drifted through the temple gates.", "香烟飘过寺庙大门。", "tour the golden temple at dawn"),
  v("church-bells-sunday-morning", "/教堂；教会", "/tʃɜːrtʃ/", "n.", 2, 0.2, "Church bells argued with traffic noise.", "教堂钟声与车流声较劲。", "attend the village church fete"),
  v("mosque-call-to-prayer-evening", "/清真寺", "/mɑːsk/", "n.", 5, 0.45, "The mosque glowed at sunset.", "清真寺在日落时发光。", "admire the mosque's blue tiles"),
  v("pilgrimage-long-sacred-walk", "/朝圣之旅", "/ˈpɪlɡrɪmɪdʒ/", "n.", 7, 0.7, "Fans make annual pilgrimages to Abbey Road.", "歌迷每年到艾比路朝圣。", "complete a walking pilgrimage route"),
  v("afterlife-what-comes-next-question", "/来世；死后生命", "/ˈæftərlaɪf/", "n.", 7, 0.65, "Egyptians packed for the afterlife carefully.", "埃及人为来世精心打点行李。","debate the afterlife over tea"),
  v("karma-what-goes-around-idea", "/因果报应；业", "/ˈkɑːrmə/", "n.", 5, 0.5, "Parking karma finally smiled on me.", "停车运气终于眷顾我了。", "believe in instant parking karma"),
  v("zen-minimalist-calm-aesthetic", "/禅；禅宗", "/zen/", "n./adj.", 6, 0.6, "Her tiny apartment has real zen energy.", "她的小公寓有真正的禅意。", "achieve total zen before deadlines"),
];
