import { v } from "@/content/vocab/builder";
import type { VocabRow } from "@/content/vocab/types";

/** Psychology & the mind - Phase 10 chunk-h. */
export const psychologyMindRows: VocabRow[] = [
  v("psychology-intro-course-basics", "/心理学", "/saɪˈkɑːlədʒi/", "n.", 5, 0.45, "Psychology explains why lists calm us.", "心理学解释清单为何让人安心。", "take an evening psychology class"),
  v("cognitive-mental-processing-power", "/认知的", "/ˈkɑːɡnətɪv/", "adj.", 7, 0.65, "Sleep debt drains cognitive performance fast.", "睡眠负债迅速拖垮认知表现。", "sharp cognitive skills training"),
  v("perception-senses-filter-reality", "/感知觉；知觉", "/pərˈsepʃn/", "n.", 6, 0.6, "Hunger warps perception of portion sizes.", "饥饿会扭曲对食物份量的感知。", "test visual perception in the lab"),
  v("attention-span-shrinking-worry", "/注意力；专注", "/əˈtenʃn/", "n.", 2, 0.15, "My attention span died by notification #40.", "我的注意力死于第40条通知。", "stretch your attention span gradually"),
  v("focus-deep-work-block", "/焦点；聚焦", "/ˈfoʊkəs/", "n./v.", 3, 0.25, "Ninety minutes of focus beats four distracted hours.", "九十分钟专注胜过四小时分心。", "protect your morning focus fiercely"),
  v("memory-short-term-vs-long-term", "/记忆；记忆力", "/ˈmeməri/", "n.", 1, 0.1, "Smells unlock memory faster than photos.", "气味解锁记忆比照片更快。", "jog someone's memory gently"),
  v("recall-active-memory-pull", "/回忆起；召回", "/rɪˈkɔːl/", "v.", 4, 0.35, "I can't recall locking the door today.", "我想不起来今天锁门没有。", "recall details under pressure"),
  v("forgetting-curve-review-timing", "/忘记；遗忘", "/fərˈɡetɪŋ/", "n.", 4, 0.3, "Forgetting starts within one hour.", "遗忘在一小时内就开始了。", "beat the forgetting curve with reviews"),
  v("motivation-internal-fire-source", "/动机；动力", "/ˌmoʊtɪˈveɪʃn/", "n.", 4, 0.35, "Motivation follows action more often than it leads.", "动力常常跟随行动而非引领行动。", "boost team motivation weekly"),
  v("discipline-systems-over-willpower", "/自律；纪律", "/ˈdɪsəplɪn/", "n.", 4, 0.35, "Discipline is remembering what you want.", "自律是记住自己真正想要什么。", "build discipline through tiny routines"),
  v("habit-loop-cue-routine-reward", "/习惯", "/ˈhæbɪt/", "n.", 2, 0.15, "Swap the habit; keep the cue and reward.", "替换习惯，保留提示和奖励。", "stack a new habit onto an old one"),
  v("addiction-brain-reward-trap", "/成瘾；上瘾", "/əˈdɪkʃn/", "n.", 6, 0.6, "Phone addiction wears everyone's face now.", "如今手机成瘾写在每个人脸上。", "fight addiction with support networks"),
  v("anxiety-disorder-generalized-type", "/焦虑；担忧", "/æŋˈzaɪəti/", "n.", 5, 0.5, "Anxiety shrink-wraps your whole chest.", "焦虑把整个胸腔裹紧。", "manage anxiety with box breathing"),
  v("depression-clinical-support-needed", "/抑郁症；沮丧", "/dɪˈpreʃn-n2/", "n.", 5, 0.5, "Depression lies convincingly to its host.", "抑郁会说服力十足地欺骗宿主。", "seek help for depression early"),
  v("stress-hormone-cortisol-spike", "/压力", "/stres/", "n.", 2, 0.15, "Deadline stress peaks at 2 a.m. ideas.", "截止日压力在凌晨两点达到峰值。", "reduce stress with short walks"),
  v("trauma-body-keeps-the-score", "/创伤；精神创伤", "/ˈtrɔːmə/", "n.", 7, 0.65, "Trauma echoes in ordinary kitchens.", "创伤在寻常厨房里回响。", "process childhood trauma safely"),
  v("therapy-talk-session-weekly", "/心理治疗；谈话治疗", "/ˈθerəpi-n2/", "n.", 5, 0.5, "Talk therapy rewires stubborn thought loops.", "谈话治疗能改写顽固思维循环。", "commit to twelve therapy sessions"),
  v("mindfulness-present-moment-practice", "/正念；专注当下", "/ˈmaɪndfəlnəs/", "n.", 6, 0.55, "Mindfulness turns washing dishes into a spa.", "正念把洗碗变成水疗。", "practice mindfulness while commuting"),
  v("empathy-feel-with-others-skill", "/同理心；共情", "/ˈempəθi/", "n.", 6, 0.5, "Empathy reads the room before words do.", "同理心先于语言读懂房间气氛。", "teach empathy through stories"),
  v("sympathy-card-kindness-note", "/同情；同情心", "/ˈsɪmpəθi/", "n.", 4, 0.35, "Sympathy says sorry; empathy says me too.", "同情说遗憾，共情说我懂。", "express genuine sympathy promptly"),
  v("compassion-action-behind-empathy", "/怜悯；慈悲", "/kəmˈpæʃn/", "n.", 6, 0.55, "Compassion budgets time for strangers.", "慈悲为陌生人在日程里留出时间。", "act with compassion under pressure"),
  v("ego-defense-mechanism-guard", "/自我；自负", "/ˈiːɡoʊ/", "n.", 6, 0.6, "His fragile ego vetoed three good ideas.", "他脆弱的自否决了三个好点子。", "set aside your ego in negotiations"),
  v("confidence-earned-through-reps", "/信心；自信", "/ˈkɑːnfɪdəns/", "n.", 3, 0.25, "Confidence compounds like interest.", "自信像利息一样复利增长。", "build speaking confidence with drills"),
  v("self-esteem-inner-worth-meter", "/自尊（心）", "/ˌself ɪˈstiːm/", "n.", 6, 0.55, "Social media taxes teenage self-esteem daily.", "社交媒体每天向青少年自尊征税。", "rebuild self-esteem after failure"),
  v("introvert-energy-from-solitude", "/内向者", "/ˈɪntrəvɜːrt/", "n.", 6, 0.55, "Introverts recharge in empty rooms.", "内向者在空房间里充电。", "design meetings introverts can win"),
  v("extrovert-people-charger-type", "/外向者", "/ˈekstrəvɜːrt/", "n.", 6, 0.55, "Extroverts think out loud on purpose.", "外向者故意边说边想。", "pair extroverts with quiet analysts"),
  v("personality-big-five-traits-test", "/性格；个性", "/ˌpɜːrsəˈnæləti/", "n.", 4, 0.35, "Personality shifts slowly after thirty.", "三十岁后性格仍会缓慢变化。", "assess personality before teaming up"),
  v("temperament-inborn-mood-style", "/气质；性情", "/ˈtemprəmənt/", "n.", 7, 0.65, "A sunny temperament survives bad weather.", "好脾气能扛过坏天气。", "a naturally cheerful temperament"),
  v("mood-ring-color-swing-hour", "/情绪；心情", "/muːd/", "n.", 2, 0.15, "The office mood lifted after lunch.", "午饭办公室情绪回升了。", "lift the team mood instantly"),
  v("emotion-naming-tames-it-effect", "/情绪；强烈情感", "/ɪˈmoʊʃn/", "n.", 3, 0.25, "Name the emotion to shrink it.", "说出情绪的名字它就会缩小。", "regulate strong emotions calmly"),
  v("instinct-gut-first-response", "/本能；直觉", "/ˈɪnstɪŋkt/", "n.", 5, 0.45, "His instinct said take the exit early.", "他的直觉说提前下高速。", "trust your survival instinct sometimes"),
  v("intuition-fast-pattern-brain", "/直觉", "/ˌɪntuˈɪʃn/", "n.", 6, 0.55, "Intuition is experience moving at speed.", "直觉是经验的高速运转。", "hone intuition through deliberate practice"),
  v("subconscious-under-the-surface-mind", "/潜意识", "/ˌsʌbˈkɑːnʃəs/", "adj./n.", 7, 0.7, "Subconscious biases steer hiring quietly.", "潜意识偏见悄悄左右招聘。", "surfacing subconscious assumptions takes work"),
  v("dream-interpretation-night-stories", "/梦；梦想", "/driːm/", "n./v.", 1, 0.1, "Chase the dream, not the applause.", "追梦想，别追掌声。", "keep a dream journal bedside"),
  v("nightmare-3am-heart-race", "/噩梦", "/ˈnaɪtmer/", "n.", 3, 0.3, "Public-speaking nightmares visit us all.", "当众讲话的噩梦人人都做过。", "wake from a nightmare sweating"),
  v("insomnia-counting-sheep-fails", "/失眠", "/ɪnˈsɑːmniə/", "n.", 7, 0.65, "Insomnia loves unfinished arguments.", "失眠偏爱没吵完的架。", "battle insomnia with fixed wake times"),
  v("fatigue-chronic-tiredness-warning", "/疲劳；疲乏", "/fəˈtiːɡ/", "n.", 6, 0.55, "Decision fatigue hits by late afternoon.", "决策疲劳在下午晚些时候来袭。", "combat mental fatigue with breaks"),
  v("burnout-work-exhaustion-red-flag", "/倦怠；燃尽", "/ˈbɜːrnaʊt/", "n.", 7, 0.6, "Burnout arrives dressed as productivity.", "倦怠穿着效率的外衣到来。", "recover from burnout without guilt"),
  v("resilience-bounce-back-capacity", "/韧性；复原力", "/rɪˈzɪliəns/", "n.", 7, 0.65, "Resilience grows only under load.", "韧性只在负荷下生长。", "train resilience like a muscle"),
  v("grit-long-term-perseverance-trait", "/毅力；坚毅", "/ɡrɪt/", "n.", 7, 0.6, "Grit outlasts talent on rainy Tuesdays.", "在下雨的周二，毅力比天赋更持久。", "praise grit over raw talent"),
  v("willpower-limited-daily-supply", "/意志力", "/ˈwɪlpaʊər/", "n.", 6, 0.55, "Willpower dips hardest before dinner.", "意志力在晚饭前最低迷。", "spend willpower on big rocks only"),
  v("procrastination-due-tomorrow-syndrome", "/拖延；拖延症", "/proʊˌkræstɪˈneɪʃn/", "n.", 7, 0.6, "Procrastination feeds on vague tasks.", "模糊的任务喂养拖延。", "defeat procrastination with two-minute starts"),
  v("distraction-notification-red-badge", "/分心；干扰", "/dɪˈstrækʃn/", "n.", 4, 0.35, "Distraction costs eleven minutes per ping.", "每次提醒消耗十一分钟专注。", "remove digital distraction ruthlessly"),
  v("multitasking-myth-productivity-tax", "/多任务处理", "/ˌmʌltiˈtæskɪŋ/", "n.", 7, 0.6, "Multitasking just means doing two things badly.", "多任务不过是两件事都做糟。", "quit multitasking during deep work"),
  v("neuroscience-brain-imaging-lab", "/神经科学", "/ˌnʊroʊˈsaɪəns/", "n.", 7, 0.75, "Neuroscience maps habits onto circuits.", "神经科学把习惯映射到回路。", "follow popular neuroscience books"),
  v("behaviorism-reward-training-school", "/行为主义", "/bɪˈheɪvjərɪzəm/", "n.", 7, 0.8, "Behaviorism trained pigeons and toddlers alike.", "行为主义同样训练了鸽子与幼儿。", "apply behaviorism to habit design"),
  v("nature-versus-nurture-debate", "/后天养育；培养", "/ˈnɜːrtʃər/", "n./v.", 7, 0.7, "Talent is nature polished by nurture.", "天资是天性经后天打磨的结果。", "argue nature versus nurture forever"),
];
