import { v } from "@/content/vocab/builder";
import type { VocabRow } from "@/content/vocab/types";

/** Academic research & university life - Phase 10 chunk-h. */
export const academicResearchRows: VocabRow[] = [
  v("academic-calendar-semester-dates", "/学术的；学业的", "/ˌækəˈdemɪk/", "adj.", 4, 0.35, "The academic year starts in September here.", "这里的学年九月开始。", "maintain strong academic standing"),
  v("semester-course-load-heavy", "/学期", "/sɪˈmestər/", "n.", 4, 0.3, "This semester stacks five hard courses.", "这学期五门硬课叠加。", "survive the busiest semester yet"),
  v("credit-hour-transfer-rules", "/学分", "/ˈkredɪt/", "n.", 5, 0.45, "Night classes still earn full credits.", "夜课同样修满学分。", "transfer credits between universities"),
  v("tuition-fees-rise-yearly", "/学费", "/ˈtuːɪʃn/", "n.", 6, 0.55, "Tuition doubled since her parents studied.", "学费比她父母上学时翻了一倍。", "cover tuition with scholarships"),
  v("scholarship-merit-based-award", "/奖学金", "/ˈskɑːlərʃɪp/", "n.", 4, 0.35, "A robotics scholarship paid his way.", "机器人奖学金为他付了学费。", "win a full scholarship abroad"),
  v("undergraduate-four-year-degree-track", "/本科生", "/ˌʌndərˈɡrædʒuət/", "n./adj.", 6, 0.6, "Undergraduates packed the front rows.", "本科生们坐满前排。", "an undergraduate research assistant"),
  v("graduate-school-application-season", "/研究生；毕业生", "/ˈɡrædʒuət/", "n./adj./v.", 3, 0.3, "She graduated top of her class.", "她以全班第一名毕业。", "attend graduate school overseas"),
  v("professor-office-hours-visits", "/教授", "/prəˈfesər/", "n.", 3, 0.25, "The professor keeps candy for nervous visitors.", "教授为紧张的来访者备着糖果。", "email the professor directly first"),
  v("lecture-hall-back-row-seats", "/讲座；讲课", "/ˈlektʃər/", "n./v.", 4, 0.35, "His lectures sell out like concerts.", "他的讲座像演唱会一样满座。", "record the lecture for review"),
  v("seminar-small-group-discussion-class", "/研讨会；研讨课", "/ˈsemɪnɑːr/", "n.", 6, 0.6, "The Thursday seminar argues about ethics cases.", "周四研讨课辩论伦理案例。", "lead this week's seminar reading"),
  v("syllabus-week-by-week-plan", "/教学大纲", "/ˈsɪləbəs/", "n.", 7, 0.65, "Read the syllabus before buying textbooks.", "买教材前先读教学大纲。", "revise the course syllabus annually"),
  v("curriculum-redesign-committee-vote", "/课程；全部课程", "/kəˈrɪkjələm/", "n.", 6, 0.6, "Coding entered the core curriculum finally.", "编程终于进入核心课程体系。", "modernize the national curriculum"),
  v("assignment-deadline-extension-request", "/作业；任务", "/əˈsaɪnmənt/", "n.", 3, 0.3, "One assignment ate the entire weekend.", "一份作业吃掉整个周末。", "submit every assignment early"),
  v("exam-final-week-schedule", "/考试", "/ɪɡˈzæm/", "n.", 1, 0.15, "The final exam covers chapters one to twelve.", "期末考试覆盖第一到十二章。", "pass the entrance exam on the first try"),
  v("quiz-surprise-five-minute-test", "/小测验", "/kwɪz/", "n./v.", 3, 0.25, "Friday quizzes keep readings honest.", "周五小测让大家认真读材料。", "ace the pop quiz again"),
  v("grade-point-average-gpa-matters", "/分数；成绩", "/ɡreɪd/", "n.", 1, 0.1, "Grades matter less than portfolio work.", "成绩不如作品集重要。", "pull your grades up steadily"),
  v("transcript-official-record-copy", "/成绩单；抄本", "/ˈtrænskrɪpt/", "n.", 7, 0.65, "Employers asked for sealed transcripts.", "雇主索要密封的成绩单。", "request an official transcript"),
  v("campus-tour-guide-job", "/校园；校区", "/ˈkæmpəs/", "n.", 3, 0.25, "Bikes rule this leafy campus.", "自行车统治着这座绿树成荫的校园。", "live on campus freshman year"),
  v("dormitory-shared-room-life", "/宿舍", "/ˈdɔːrmətɔːri/", "n.", 6, 0.55, "Dormitory walls are famously thin.", "宿舍墙薄是出了名的。", "move into the dormitory early"),
  v("cafeteria-tray-lunch-line", "/自助食堂", "/ˌkæfəˈtɪriə/", "n.", 4, 0.35, "Cafeteria coffee tastes like ambition and regret.", "食堂咖啡喝出野心与悔意。", "grab lunch at the cafeteria"),
  v("library-all-nighter-finals-week", "/通宵；熬夜", "/ˈɔːl naɪtər/", "n.", 7, 0.65, "One all-nighter cost three recovery days.", "一次通宵换来三天恢复期。", "avoid all-nighters during finals"),
  v("research-assistant-paid-position", "/研究；调查", "/rɪˈsɜːrtʃ/", "n./v.", 3, 0.3, "Research rewards boring patience most.", "研究最奖励无聊的耐心。", "present original research findings"),
  v("survey-questionnaire-sample-group", "/调查；测量", "/ˈsɜːrveɪ/", "n./v.", 4, 0.4, "Our survey reached two thousand readers.", "我们的调查覆盖两千名读者。", "design an unbiased survey carefully"),
  v("interview-transcribe-hours-of-tape", "/逐字记录；转录", "/trænˈskraɪb/", "v.", 7, 0.7, "Transcribing interviews takes triple the time.", "转录访谈要花三倍时间。", "transcribe field notes same day"),
  v("literature-review-background-section", "/文献综述", "/ˈlɪtərətʃə rɪˈvjuː/", "n.", 7, 0.75, "The literature review exposed a research gap.", "文献综述暴露了研究空白。", "update the literature review monthly"),
  v("methodology-chapter-defense-prep", "/方法论；方法体系", "/ˌmeθəˈdɑːlədʒi/", "n.", 7, 0.8, "Her methodology survived every examiner's jab.", "她的方法论扛住了考官每次发难。", "justify your methodology clearly"),
  v("case-study-deep-dive-format", "/案例研究", "/keɪs ˈstʌdi/", "n.", 6, 0.55, "One case study beats ten hunches.", "一个案例胜过十次瞎猜。", "build the course around case studies"),
  v("fieldwork-muddy-boots-science", "/实地调查；田野工作", "/ˈfiːldwɜːrk/", "n.", 7, 0.7, "Fieldwork ruined three pairs of shoes.", "田野调查毁掉了三双鞋。", "plan the fieldwork logistics early"),
  v("experiment-controlled-variable-setup", "/实验；尝试", "/ɪkˈsperɪmənt/", "n./v.", 3, 0.3, "The experiment failed beautifully twice.", "实验漂亮地失败了两次。", "repeat the experiment independently"),
  v("hypothesis-driven-research-design", "/假设驱动的", "/haɪˈpɑːθəsɪs ˈdrɪvn/", "adj.", 7, 0.8, "Hypothesis-first design saves months.", "假设先行的研究设计省下数月。", "run a hypothesis-driven pilot study"),
  v("statistical-significance-p-value-talk", "/统计显著性", "/stəˈtɪstɪkl sɪɡˈnɪfɪkəns/", "n.", 7, 0.8, "Significance without size means little.", "只有显著性没有效应量意义有限。", "report statistical significance honestly"),
  v("sample-representative-group-check", "/样本；样品", "/ˈsæmpl/", "n./v.", 4, 0.4, "Free samples built the brand.", "免费试用装成就了这个品牌。", "test a free sample first"),
  v("data-collection-cleanup-phase", "/数据收集", "/ˈdeɪtə kəˈlekʃn/", "n.", 6, 0.6, "Data collection filled two muddy notebooks.", "数据收集写满了两本泥迹笔记本。", "automate boring data collection steps"),
  v("analysis-pattern-finding-session", "/分析；解析", "/əˈnæləsɪs/", "n.", 4, 0.35, "Deep analysis killed our favorite theory.", "深入分析杀死了我们最爱的理论。", "run the numbers analysis tonight"),
  v("interpretation-meaning-making-step", "/解释；口译", "/ɪnˌtɜːrprɪˈteɪʃn/", "n.", 6, 0.6, "Interpretation is where bias sneaks in.", "解释是偏见潜入之处。", "offer a cautious interpretation instead"),
  v("conclusion-limitations-section-last", "/结论段", "/kənˈkluːʒn-n2/", "n.", 4, 0.35, "Admit limitations; reviewers respect honesty.", "承认局限，审稿人尊重诚实。", "state the conclusion in plain words"),
  v("reference-list-alphabetical-order", "/参考书目", "/ˈrefrəns/", "n./v.", 4, 0.4, "She cited forty references without padding.", "她引用四十条文献毫无注水。", "format every reference correctly"),
  v("citation-manager-tool-save-time", "/引文管理器", "/ˈsaɪteɪʃn/", "n.", 6, 0.65, "A citation manager saved my sanity.", "引文管理工具保住了我的理智。", "export citations automatically now"),
  v("journal-impact-factor-ranking", "/期刊；日志", "/ˈdʒɜːrnl/", "n.", 5, 0.5, "Top journals reject ninety percent blindly.", "顶级期刊盲拒九成投稿。", "submit to a peer-reviewed journal"),
  v("conference-poster-session-networking", "/会议；大会", "/ˈkɑːnfərəns/", "n.", 4, 0.35, "Conferences run on coffee and courage.", "学术会议靠咖啡和勇气运转。", "present at an international conference"),
  v("presentation-slide-deck-practice-run", "/演示；报告", "/ˌpriːzenˈteɪʃn/", "n.", 4, 0.35, "Rehearse the presentation out loud twice.", "把演示大声排练两遍。", "nail the client presentation tomorrow"),
  v("thesis-advisor-weekly-meetings", "/导师；顾问", "/ədˈvaɪzər/", "n.", 6, 0.6, "My advisor red inked everything gently.", "我的导师温柔地用红笔改遍全文。", "choose an advisor who replies fast"),
  v("defense-q-a-brutal-round", "/答辩；防御", "/dɪˈfens/", "n.", 2, 0.2, "The thesis defense lasted three hours.", "论文答辩持续三小时。", "survive the defense with humor"),
  v("degree-bachelor-or-master-type", "/学位；程度", "/dɪˈɡriː/", "n.", 2, 0.15, "The degree opens doors; skills keep them open.", "学位开门，技能守门。", "earn a degree part-time"),
  v("diploma-frame-wall-office", "/文凭；毕业证书", "/dɪˈploʊmə/", "n.", 4, 0.35, "Grandpa framed his night-school diploma proudly.", "爷爷骄傲地把夜校文凭装框。", "collect the diploma in person"),
  v("dropout-rate-improvement-plan", "/退学者", "/drɑːpˈaʊt/", "n.", 6, 0.55, "College dropouts founded half these startups.", "这些初创公司一半由大学辍学者创办。", "a high school dropout success story"),
  v("mentor-guidance-career-ladder", "/导师；指导者", "/ˈmentɔːr/", "n./v.", 5, 0.45, "A good mentor shortens every detour.", "好导师能缩短每一次弯路。", "find a mentor outside your team"),
  v("internship-summer-program-slot", "/实习；实习期", "/ˈɪntɜːrnʃɪp/", "n.", 5, 0.45, "The internship turned into a job offer.", "实习变成了正式录用。", "land a competitive internship early"),
];
