import { v } from "@/content/vocab/builder";
import type { VocabRow } from "@/content/vocab/types";

/** Business strategy & workplace skills - Phase 10 chunk-h. */
export const businessStrategyRows: VocabRow[] = [
  v("strategy-quarterly-roadmap-review", "/战略；策略", "/ˈstrætədʒi/", "n.", 4, 0.35, "Our strategy bets on boring reliability.", "我们的战略押注于无聊的可靠性。", "align the team behind one strategy"),
  v("vision-statement-wall-poster", "/愿景；视力", "/ˈvɪʒn/", "n.", 4, 0.35, "A vision without payroll is a daydream.", "没有工资单支撑的愿景只是白日梦。", "articulate the company vision clearly"),
  v("mission-one-sentence-purpose", "/使命；任务", "/ˈmɪʃn/", "n.", 4, 0.3, "Cut the mission to one verb.", "把使命压缩成一个动词。", "live the mission every sprint"),
  v("objective-measurable-target-set", "/目标；客观的", "/əbˈdʒektɪv/", "n./adj.", 4, 0.35, "Three objectives beat thirty wishes.", "三个明确目标胜过三十个愿望。", "set quarterly objectives together"),
  v("kpi-dashboard-metric-tracking", "/关键绩效指标", "/ˌkeɪ piː ˈaɪ/", "n.", 7, 0.65, "Vanity KPIs flatter; real ones warn.", "虚荣指标讨好人，真指标会报警。", "review the core KPIs weekly"),
  v("benchmark-industry-standard-compare", "/基准；标杆", "/ˈbentʃmɑːrk/", "n./v.", 6, 0.6, "Benchmark against the best, not the loudest.", "对标最强者而非嗓门最大者。", "beat last year's benchmark easily"),
  v("competitive-advantage-moat-building", "/竞争优势", "/kəmˈpetətɪv ədˈvæntɪdʒ/", "n.", 7, 0.65, "Distribution became their real competitive advantage.", "渠道才是他们真正的竞争优势。", "defend your competitive advantage fiercely"),
  v("stakeholder-map-interest-grid", "/利益相关者", "/ˈsteɪkhoʊldər/", "n.", 7, 0.65, "Stakeholders disagree on purpose sometimes.", "利益相关者有时故意意见相左。", "manage stakeholders with early previews"),
  v("executive-team-corner-office", "/高管；行政人员", "/ɪɡˈzekjətɪv/", "n./adj.", 5, 0.5, "Executives read one page, not forty.", "高管只读一页，不读四十页。", "brief executives in three bullets"),
  v("board-of-directors-meeting-minutes", "/董事会", "/bɔːrd əv ˈdɪrektərz/", "n.", 7, 0.65, "The board meets quarterly, panics rarely.", "董事会每季度开会，极少恐慌。", "present to the board confidently"),
  v("ceo-chief-executive-officer-role", "/首席执行官", "/ˌsiː iː ˈoʊ/", "n.", 4, 0.4, "The CEO answers support tickets monthly.", "CEO每月亲自回复客服工单。", "the CEO's all-hands address"),
  v("manager-one-on-one-notes", "/经理；管理者", "/ˈmænɪdʒər/", "n.", 2, 0.2, "My manager shields us from chaos.", "我的经理为我们挡住混乱。", "sync weekly with your manager"),
  v("employee-engagement-survey-score", "/雇员；员工", "/ɪmˈplɔɪiː/", "n.", 4, 0.3, "Employees forgive pay gaps, not disrespect.", "员工能原谅薪酬差距，不能原谅不被尊重。", "recognize employees publicly and often"),
  v("workplace-culture-fit-debate", "/职场；工作场所", "/ˈwɜːrkpleɪs/", "n.", 4, 0.3, "Culture is what the boss does at 6 p.m.", "文化就是老板傍晚六点的行为。", "improve workplace safety standards"),
  v("remote-work-policy-update", "/远程办公", "/rɪˈmoʊt wɜːrk/", "n.", 5, 0.4, "Remote work erased two hours of commuting.", "远程办公省掉两小时通勤。", "hire remote workers across time zones"),
  v("hybrid-schedule-office-days-mix", "/混合的；杂种的", "/ˈhaɪbrɪd/", "adj./n.", 5, 0.45, "Hybrid schedules need calendar discipline.", "混合办公制需要日程自律。", "adopt a hybrid model gradually"),
  v("freelance-contract-gig-client", "/自由职业", "/ˈfriːlæns/", "adj./v.", 5, 0.45, "Freelance life means chasing invoices too.", "自由职业也意味着追讨发票。", "go freelance after saving six months"),
  v("consultant-slide-deck-billing-rate", "/顾问", "/kənˈsʌltənt/", "n.", 6, 0.55, "Consultants borrow your watch to tell the time.", "顾问借你的表告诉你时间。", "hire a pricing consultant briefly"),
  v("vendor-supplier-contract-renewal", "/供应商；卖主", "/ˈvendər/", "n.", 6, 0.55, "Vendor delays stalled the launch twice.", "供应商延误两次拖累发布。", "audit key vendors yearly"),
  v("client-relationship-long-term-care", "/客户；委托人", "/ˈklaɪənt/", "n.", 3, 0.25, "Clients remember how you handle mistakes.", "客户记住的是你如何处理错误。", "win back a lost client gracefully"),
  v("invoice-net-thirty-payment-terms", "/发票；账单", "/ˈɪnvɔɪs/", "n./v.", 7, 0.6, "Send the invoice the same day.", "当天就开发票。", "chase overdue invoices politely"),
  v("payroll-direct-deposit-run", "/工资名单；发薪", "/ˈpeɪroʊl/", "n.", 7, 0.6, "Payroll never misses the 25th here.", "这里发薪从不晚于25号。", "run payroll accurately twice monthly"),
  v("revenue-recurring-vs-one-time", "/收入；营收", "/ˈrevənuː/", "n.", 5, 0.45, "Recurring revenue sleeps well at night.", "经常性收入夜里睡得香。", "grow recurring revenue steadily"),
  v("profit-margin-thin-or-fat", "/利润；盈利", "/ˈprɑːfɪt/", "n.", 4, 0.35, "Revenue is vanity; profit is sanity.", "收入是面子，利润是里子。", "protect profit margins during discounts"),
  v("cash-flow-monthly-gap-warning", "/现金流", "/kæʃ floʊ/", "n.", 6, 0.55, "Cash flow kills faster than competition.", "现金流失血比竞争更致命。", "smooth cash flow with deposits"),
  v("overhead-fixed-cost-reduction", "/日常开支；一般管理费用", "/ˈoʊvərhed/", "n.", 7, 0.65, "Overhead creeps up one subscription at a time.", "管理费一个个订阅悄悄涨起来。", "slash needless overhead ruthlessly"),
  v("expenditure-capital-vs-operating-type", "/支出；花费", "/ɪkˈspendɪtʃər/", "n.", 7, 0.7, "Cap expenditure before growth sprints.", "增长冲刺前先管住支出。", "approve major capital expenditure"),
  v("forecast-sales-pipeline-projection", "/预测；预报", "/ˈfɔːrkæst/", "n./v.", 5, 0.45, "Forecasts are stories with spreadsheets.", "预测就是用表格讲的故事。", "update the sales forecast weekly"),
  v("quarterly-report-earnings-call", "/季度报告", "/ˈkwɔːrtərli rɪˈpɔːrt/", "n.", 6, 0.6, "Quarterly reports reward boring consistency.", "季报奖励乏味的一致性。", "draft the quarterly report early"),
  v("merger-equal-partners-union", "/合并；归并", "/ˈmɜːrdʒər/", "n.", 7, 0.65, "Half of mergers quietly fail within five years.", "一半并购五年内悄然失败。", "announce the merger internally first"),
  v("acquisition-buyout-deal-closed", "/收购；获得", "/ˌækwɪˈzɪʃn/", "n.", 7, 0.65, "Acquisitions buy users faster than ads do.", "收购比广告更快买到用户。", "close the acquisition by Friday"),
  v("partnership-joint-venture-agreement", "/合伙关系；伙伴关系", "/ˈpɑːrtnərʃɪp/", "n.", 4, 0.35, "Good partnerships survive bad quarters.", "好的伙伴关系能挺过糟糕的季度。", "negotiate partnership terms fairly"),
  v("negotiation-win-win-outcome-craft", "/谈判；协商", "/nɪˌɡoʊʃiˈeɪʃn/", "n.", 6, 0.55, "Silence is negotiation's sharpest tool.", "沉默是谈判最锋利的工具。", "prepare negotiation walk-away points"),
  v("proposal-rfp-response-document", "/提案；求婚", "/prəˈpoʊzl/", "n.", 4, 0.35, "Win proposals answer fears, not specs.", "赢下的提案回应恐惧而非参数。", "polish the proposal one more pass"),
  v("contract-negotiation-red-lines", "/合同谈判", "/ˈkɑːntrækt ˌniːɡoʊʃiˈeɪʃn/", "n.", 6, 0.65, "Contract talks stall over liability caps.", "合同谈判常卡在责任上限上。", "flag contract risks to legal early"),
  v("deadline-extension-request-email", "/截止日期；期限", "/ˈdedlaɪn/", "n.", 4, 0.3, "Deadlines are promises wearing suits.", "截止日期是穿西装的承诺。", "hit every internal deadline comfortably"),
  v("prioritization-urgent-vs-important-sort", "/优先级排序", "/praɪˌɔːrətəˈzeɪʃn/", "n.", 7, 0.65, "Prioritization is polite refusal in bulk.", "排序就是批量地礼貌说不。", "practice ruthless prioritization daily"),
  v("delegation-trust-but-verify-loop", "/授权；委派", "/ˌdelɪˈɡeɪʃn/", "n.", 7, 0.65, "Delegation multiplies you or drowns you.", "授权要么放大你，要么淹死你。", "master delegation through small tasks"),
  v("feedback-sandwich-vs-direct-style", "/反馈；回授", "/ˈfiːdbæk/", "n.", 3, 0.25, "Fast feedback beats perfect feedback.", "快速反馈胜过完美反馈。", "ask for specific feedback always"),
  v("performance-review-anxiety-season", "/绩效考核", "/ˈpɜːrfərməns rɪˈvjuː/", "n.", 6, 0.6, "Keep receipts all year for performance reviews.", "全年留存证据应对绩效评估。", "prepare examples before the performance review"),
  v("promotion-cycle-wait-time", "/晋升；提升", "/prəˈmoʊʃn/", "n.", 4, 0.4, "Promotion follows solved problems, not hours.", "晋升跟着解决的问题走，不是工时。", "earn the promotion visibly"),
  v("resignation-two-weeks-notice-letter", "/辞职；辞职信", "/ˌrezɪɡˈneɪʃn/", "n.", 7, 0.6, "Resignations travel faster than announcements.", "辞职消息传得比公告还快。", "submit a gracious resignation letter"),
  v("retirement-savings-plan-enrollment", "/退休", "/rɪˈtaɪərmənt/", "n.", 4, 0.35, "Retirement math scares thirty-year-olds awake.", "退休数学把三十岁的人吓醒。", "plan retirement contributions automatically"),
  v("layoff-restructuring-round-survivor", "/裁员", "/ˈleɪɔːf/", "n.", 7, 0.65, "Layoffs broke the team's trust for years.", "裁员让团队信任多年难愈。", "survive a layoff round with grace"),
  v("recruitment-talent-pipeline-funnel", "/招聘", "/rɪˈkruːtmənt/", "n.", 6, 0.6, "Recruitment starts before the job posting.", "招聘始于发布职位之前。", "streamline recruitment with referrals"),
  v("orientation-first-week-checklist", "/入职培训；定向", "/ˌɔːriənˈteɪʃn/", "n.", 6, 0.6, "Orientation decides whether people stay.", "入职培训决定去留。", "redesign the new-hire orientation week"),
  v("onboarding-buddy-system-setup", "/入职引导", "/ˈɑːnbɔːrdɪŋ/", "n.", 7, 0.6, "Great onboarding pays for itself monthly.", "好的入职引导每月都能回本。", "assign each new hire an onboarding buddy"),
];
