import { v } from "@/content/vocab/builder";
import type { VocabRow } from "@/content/vocab/types";

/** Marketing, sales & startups - Phase 10 chunk-h. */
export const marketingSalesRows: VocabRow[] = [
  v("marketing-mix-four-ps-model", "/市场营销", "/ˈmɑːrkɪtɪŋ/", "n.", 4, 0.35, "Marketing is promises kept at scale.", "营销是规模化兑现承诺。", "align sales and marketing weekly"),
  v("brand-identity-guidelines-book", "/品牌", "/brænd/", "n.", 3, 0.3, "A brand is a promise repeated daily.", "品牌是每天重复的承诺。", "protect the brand during crises"),
  v("logo-redesign-public-backlash", "/标识；商标图案", "/ˈloʊɡoʊ/", "n.", 5, 0.45, "The new logo cost six figures and one apology.", "新标志花了六位数外加一次道歉。", "refresh the logo subtly"),
  v("slogan-catchy-three-words-max", "/标语；口号", "/ˈsloʊɡən/", "n.", 6, 0.55, "Great slogans fit on a matchbox.", "好口号能写进火柴盒。", "test three slogan options internally"),
  v("target-audience-persona-profile", "/目标受众", "/ˈtɑːrɡɪt ˈɔːdiəns/", "n.", 5, 0.45, "Target everyone and you sell to nobody.", "面向所有人等于谁也没卖到。", "define your target audience narrowly"),
  v("campaign-launch-date-countdown", "/广告活动；运动", "/kæmˈpeɪn/", "n.", 3, 0.25, "The launch campaign ran for six weeks.", "发布活动持续了六周。", "measure each campaign against one goal"),
  v("advertisement-billboard-vs-banner-format", "/广告", "/ˌædvərˈtaɪzmənt/", "n.", 3, 0.25, "Honest advertisements age the best.", "诚实的广告最耐老。", "skip the annoying advertisement entirely"),
  v("commercial-tv-slot-thirty-seconds", "/商业广告", "/kəˈmɜːrʃl/", "adj./n.", 4, 0.35, "Their Super Bowl commercial outshone the game.", "他们的超级碗广告抢了比赛风头。", "shoot a low-budget commercial locally"),
  v("copywriting-headline-conversion-tricks", "/文案写作", "/ˈkɑːpiraɪtɪŋ/", "n.", 7, 0.65, "Copywriting sells the click before the product.", "文案先卖出点击再卖出产品。", "study classic copywriting swipe files"),
  v("seo-search-ranking-factors-list", "/搜索引擎优化", "/ˌes iː ˈoʊ/", "n.", 7, 0.7, "SEO rewards patience over tricks now.", "如今SEO奖励耐心而非花招。", "audit your site's SEO quarterly"),
  v("social-media-content-calendar-plan", "/社交媒体", "/ˈsoʊʃl ˈmiːdiə/", "n.", 4, 0.35, "Social media amplifies whatever you already are.", "社交媒体只会放大你本来的样子。", "batch your social media posts Sundays"),
  v("influencer-marketing-roi-debate", "/网红营销", "/ˌɪnfluˈensər ˈmɑːrkɪtɪŋ/", "n.", 7, 0.7, "Influencer deals need tracked discount codes.", "网红合作需要可追踪的折扣码。", "vet influencer audiences for bots"),
  v("newsletter-subscriber-welcome-email", "/时事通讯；业务通讯", "/ˈnuːzletər/", "n.", 6, 0.6, "Newsletters survive algorithm changes happily.", "邮件通讯不怕算法改版。", "launch a paid newsletter this year"),
  v("lead-generation-pipeline-top-stage", "/获客；线索生成", "/liːd dʒenəˈreɪʃn/", "n.", 7, 0.7, "Lead generation dies without follow-up speed.", "线索生成毁于跟进迟缓。", "automate lead generation with webinars"),
  v("conversion-rate-landing-page-test", "/转化率", "/kənˈvɜːrʒn reɪt/", "n.", 7, 0.65, "Doubling conversion beats doubling traffic.", "转化率翻倍胜过流量翻倍。", "lift conversion rate with clearer buttons"),
  v("funnel-awareness-to-purchase-stages", "/漏斗", "/ˈfʌnl/", "n.", 7, 0.65, "Leaky funnels waste great products.", "漏水的漏斗浪费好产品。", "patch the leaky funnel stage by stage"),
  v("a-b-testing-split-url-experiment", "/A/B测试", "/eɪ biː ˈtestɪŋ/", "n.", 7, 0.7, "A/B testing ends loud opinions quietly.", "A/B测试让大声的意见安静下来。", "run an A/B test on pricing pages"),
  v("customer-acquisition-cost-formula", "/客户获取成本", "/ˈkʌstəmər ækwɪˈzɪʃn kɔːst/", "n.", 7, 0.75, "Acquisition cost must beat lifetime value.", "获客成本必须低于终身价值。", "cut customer acquisition cost with referrals"),
  v("retention-churn-prevention-focus", "/保留；留存", "/rɪˈtenʃn/", "n.", 7, 0.65, "Retention is growth hiding in plain sight.", "留存就是藏在眼皮底下的增长。", "improve employee retention with career paths"),
  v("loyalty-program-points-expiry-rules", "/忠诚度计划", "/ˈlɔɪəlti ˈproʊɡræm/", "n.", 6, 0.6, "Loyalty points expire exactly when needed.", "积分总在你需要时过期。", "join the coffee loyalty program finally"),
  v("upsell-checkout-counter-offer", "/追加销售；向上销售", "/ˈʌpsel/", "v./n.", 7, 0.7, "Smart upsells feel like helpful tips.", "聪明的追加销售像善意提醒。", "train cashiers to upsell politely"),
  v("cross-sell-related-items-widget", "/交叉销售", "/ˈkrɔːssel/", "v./n.", 7, 0.7, "Cross-selling batteries with toys just works.", "玩具搭售电池就是管用。", "cross-sell accessories on product pages"),
  v("discount-code-limited-time-offer", "/折扣；打折", "/ˈdɪskaʊnt/", "n.", 3, 0.3, "Permanent discounts train patient buyers.", "永久折扣培养出耐心买家。", "apply the member discount automatically"),
  v("promotion-seasonal-sale-event", "/促销；推广", "/prəˈmoʊʃn/", "n.", 3, 0.3, "Promotions work best with real stories.", "有真实故事的促销最有效。", "plan promotions around paydays"),
  v("cold-call-rejection-recovery-drill", "/陌生电话推销", "/koʊld kɔːl/", "n./v.", 7, 0.7, "Cold calls warm up after fifty tries.", "陌生电话打到第五十个就热了。","make ten cold calls before lunch"),
  v("sales-pipeline-stage-review-meeting", "/销售管道；管线", "/ˈseɪlz ˈpaɪplaɪn/", "n.", 7, 0.7, "Pipeline reviews kill wishful thinking.", "管道复盘杀死一厢情愿。", "clean the sales pipeline every Monday"),
  v("quota-monthly-target-pressure-cooker", "/定额；配额", "/ˈkwoʊtə/", "n.", 7, 0.65, "Quotas measure activity more than skill.", "配额更多衡量活动量而非技巧。", "hit quota two weeks early"),
  v("commission-based-pay-structure", "/佣金；回扣", "/kəˈmɪʃn/", "n.", 5, 0.5, "Commission plans shape behavior silently.", "提成方案悄悄塑造行为。", "earn commission on renewals too"),
  v("pitch-investor-three-minute-story", "/推销；投球", "/pɪtʃ/", "n./v.", 5, 0.45, "Every pitch needs one number to remember.", "每个路演都需要一个让人记住的数字。", "sharpen your pitch until it stings"),
  v("startup-runway-months-left-chart", "/初创公司", "/ˈstɑːrtʌp/", "n.", 6, 0.55, "Startups die of thirst, not hunger.", "初创公司渴死的比饿死的多。", "extend the startup's runway first"),
  v("venture-capital-term-sheet-talks", "/风险资本", "/ˈventʃər ˈkæpɪtl/", "n.", 7, 0.7, "Venture capital funds momentum, not logic.", "风投为势头买单，不为逻辑买单。", "raise venture capital only when rocketing"),
  v("angel-investor-first-check-writing", "/天使投资人", "/ˈeɪndʒəl ɪnˈvestər/", "n.", 7, 0.7, "Angel investors bet on founders' grit.", "天使投资人赌创始人的韧性。", "thank angel investors monthly updates"),
  v("seed-round-early-money-close", "/种子轮", "/siːd raʊnd/", "n.", 7, 0.75, "Seed rounds fund experiments, not offices.", "种子轮资助实验，不是办公室。", "close the seed round by June"),
  v("valuation-negotiated-paper-number", "/估值", "/ˌvæljuˈeɪʃn/", "n.", 7, 0.7, "Valuation is opinion wearing a suit.", "估值是穿西装的观点。", "defend the valuation with comparables"),
  v("equity-share-options-vesting-schedule", "/股权；公平", "/ˈekwəti/", "n.", 7, 0.65, "Equity motivates only when it might be worth something.", "股权只有在可能值钱时才有激励性。", "grant equity with clear vesting terms"),
  v("ipo-going-public-milestone-day", "/首次公开募股", "/ˌaɪ piː ˈoʊ/", "n.", 7, 0.8, "IPO day makes paper millionaires briefly.", "上市日短暂制造纸面百万富翁。", "file for an IPO next spring"),
  v("unicorn-billion-startup-club", "/独角兽（十亿美元公司）", "/ˈjuːnɪkɔːrn/", "n.", 7, 0.7, "Most unicorns still can't spell profit.", "多数独角兽仍不会拼写“利润”。", "chase unicorn status less than cash flow"),
  v("pivot-strategy-change-direction-fast", "/转向；支点", "/ˈpɪvət/", "n./v.", 7, 0.65, "Pivots fail when they skip customer calls.", "不打客户电话的转型注定失败。", "pivot toward paying users quickly"),
  v("mvp-minimum-viable-product-version", "/最简可行产品", "/ˌem viː ˈpiː/", "n.", 7, 0.75, "An MVP answers one question cheaply.", "MVP廉价地回答一个问题。", "ship the mvp in six weeks"),
  v("prototype-3d-printed-first-draft", "/原型；样机", "/ˈproʊtətaɪp/", "n.", 6, 0.6, "Prototypes earn honest feedback instantly.", "原型立刻换来诚实反馈。", "print a rough prototype overnight"),
  v("product-market-fit-elusive-alignment", "/产品市场契合", "/ˈprɑːdʌkt ˈmɑːrkɪt fɪt/", "n.", 7, 0.8, "Product-market fit feels like tailwinds.", "产品市场契合的感觉像顺风骑行。", "search for product-market fit relentlessly"),
  v("growth-hacking-loophole-experiments", "/增长黑客", "/ɡroʊθ ˈhækɪŋ/", "n.", 7, 0.75, "Growth hacking is marketing with lab goggles.", "增长黑客就是戴护目镜做营销。", "run one growth experiment weekly"),
  v("scale-up-operational-growing-pains", "/规模扩大；规模", "/skeɪl/", "n./v.", 4, 0.4, "Scale breaks processes you never noticed.", "规模化会压垮你没注意到的流程。", "prepare support docs before you scale"),
  v("bootstrapping-self-funded-growth-path", "/自力更生创业", "/ˈbuːtstræpɪŋ/", "n.", 7, 0.75, "Bootstrapping keeps founders stubbornly free.", "自筹资金让创始人顽固地自由。", "bootstrap until customers pull you forward"),
  v("burn-rate-monthly-cash-speedometer", "/烧钱率", "/bɜːrn reɪt/", "n.", 7, 0.75, "Burn rate reads like a horror novel.", "烧钱率读起来像恐怖小说。", "halve burn rate before winter"),
  v("exit-strategy-acquisition-or-ipo-endgame", "/退出策略", "/ˈeksɪt ˈstrætədʒi/", "n.", 7, 0.75, "Build the company; the exit builds itself.", "把公司做好，退出自然水到渠成。", "discuss exit strategy with cofounders early"),
];
