import { v } from "@/content/vocab/builder";
import type { VocabRow } from "@/content/vocab/types";

/** Industry, manufacturing & logistics - Phase 10 chunk-h. */
export const industryLogisticsRows: VocabRow[] = [
  v("manufacturing-plant-floor-tour", "/制造业；制造", "/ˌmænjəˈfæktʃərɪŋ/", "n.", 6, 0.55, "Manufacturing returned to the region quietly.", "制造业悄悄回到了该地区。", "modernize aging manufacturing lines"),
  v("factory-shift-three-eight-hour", "/工厂", "/ˈfæktəri/", "n.", 2, 0.2, "The factory hums three shifts a day.", "工厂每天三班运转。", "tour the widget factory Friday"),
  v("assembly-line-speed-balance", "/装配线", "/əˈsembli laɪn/", "n.", 6, 0.55, "Assembly lines punish one slow station.", "流水线最恨一个慢工位。", "rebalance the assembly line stations"),
  v("warehouse-inventory-shelving-aisles", "/仓库", "/ˈwerhaʊs/", "n.", 5, 0.45, "Robots now roam the warehouse at night.", "如今机器人在夜里巡行仓库。", "label every warehouse shelf clearly"),
  v("inventory-count-cycle-stock-check", "/库存；清单", "/ˈɪnvəntɔːri/", "n.", 6, 0.6, "Inventory hides in three spreadsheets.", "库存藏在三张表格里。", "cut dead inventory before year end"),
  v("supply-chain-disruption-contingency-plan", "/供应链", "/səˈplaɪ tʃeɪn/", "n.", 5, 0.5, "One port closure froze whole supply chains.", "一个港口关闭冻结整条供应链。", "map your supply chain single points"),
  v("procurement-sourcing-team-vendor-vetting", "/采购", "/prəˈkjʊrmənt/", "n.", 7, 0.7, "Procurement negotiates like chess masters.", "采购像棋手一样谈判。", "centralize procurement for better pricing"),
  v("logistics-last-mile-delivery-cost", "/物流", "/ləˈdʒɪstɪks/", "n.", 7, 0.65, "Last-mile logistics eats half the shipping cost.", "末端物流吃掉一半运费。", "optimize logistics with route software"),
  v("shipment-tracking-number-update", "/装运；货物", "/ˈʃɪpmənt/", "n.", 4, 0.4, "The shipment clears customs on Tuesday.", "货物周二清关。", "expedite the delayed shipment today"),
  v("freight-heavy-cargo-rates-quote", "/货运；运费", "/freɪt/", "n.", 7, 0.65, "Air freight triples costs overnight.", "空运让成本一夜翻三倍。", "compare freight quotes seasonally"),
  v("container-port-crane-operators", "/集装箱", "/kənˈteɪnər/", "n.", 5, 0.45, "Containers stacked like steel Lego bricks.", "集装箱像钢铁乐高一样堆叠。", "inspect each container seal carefully"),
  v("pallet-forklift-stack-height", "/托盘；货板", "/ˈpælɪt/", "n.", 7, 0.7, "Pallets move twice; count them once more.", "托盘移动两次，再多点一次数。", "shrink-wrap pallets before shipping"),
  v("forklift-certification-training-course", "/叉车", "/ˈfɔːrklɪft/", "n.", 7, 0.65, "Forklift beeps compose factory music.", "叉车蜂鸣是工厂的音乐。", "renew your forklift certification annually"),
  v("quality-control-inspection-gate-process", "/质量控制", "/ˈkwɑːləti kənˈtroʊl/", "n.", 6, 0.6, "Quality control catches what marketing forgives.", "质检抓住营销原谅不了的问题。", "add a final quality control checkpoint"),
  v("defect-rate-six-sigma-target", "/缺陷；缺点", "/dɪˈfekt/", "n./v.", 7, 0.7, "Zero defects sounds noble and bankrupts slowly.", "零缺陷听着高尚，慢慢拖垮钱包。", "trace every defect to its root cause"),
  v("automation-repetitive-task-replacement", "/自动化", "/ˌɔːtəˈmeɪʃn/", "n.", 5, 0.5, "Automation frees humans for judgment calls.", "自动化把人解放出来做判断。", "start automation with boring tasks first"),
  v("robotics-arm-welding-cell", "/机器人技术", "/roʊˈbætɪks/", "n.", 6, 0.6, "Robotics arms never call in sick.", "机械臂从不请病假。", "calibrate robotics arms monthly"),
  v("lean-manufacturing-waste-elimination-method", "/精益生产", "/liːn/", "adj.", 7, 0.7, "Lean thinking hunts seven kinds of waste.", "精益思维追杀七种浪费。", "run lean kaizen workshops quarterly"),
  v("output-capacity-utilization-percent", "/产量；输出", "/ˈaʊtpʊt/", "n.", 5, 0.45, "Night shifts doubled plant output.", "夜班使工厂产量翻倍。", "raise output without new hires"),
  v("downtime-unplanned-machine-stoppage", "/停机时间；故障时间", "/ˈdaʊntaɪm/", "n.", 7, 0.65, "Downtime bills arrive when machines rest.", "设备一歇，账单就到。", "predict downtime with sensor data"),
  v("maintenance-preventive-schedule-calendar", "/维护；保养", "/ˈmeɪntənəns/", "n.", 5, 0.45, "Preventive maintenance is cheap insurance.", "预防性维护是便宜的保险。", "schedule elevator maintenance quarterly"),
  v("machinery-heavy-equipment-leasing", "/机械；机器", "/məˈʃiːnəri/", "n.", 6, 0.55, "Old machinery sings before it fails.", "老机器罢工前会唱歌。", "lubricate all machinery on schedule"),
  v("blueprint-engineering-drawing-set", "/蓝图；蓝图般的计划", "/ˈbluːprɪnt/", "n.", 6, 0.6, "Every renovation starts with blueprints.", "每次翻新从蓝图开始。", "redraw the blueprints after changes"),
  v("welding-sparks-safety-mask", "/焊接；焊缝", "/ˈweldɪŋ/", "n.", 7, 0.65, "Welding sparks write short bright stories.", "焊花写下短暂明亮的故事。", "certify welders before shipyard work"),
  v("drill-press-hole-precision", "/钻头；钻孔", "/drɪl/", "n./v.", 3, 0.3, "Drill pilot holes to spare the wood.", "先打导孔以保护木材。", "drill slowly through tile"),
  v("lathe-spinning-wood-craft", "/车床", "/leɪð/", "n.", 7, 0.75, "The lathe turns blocks into banisters.", "车床把木块变成栏杆。", "mount the blank on the lathe securely"),
  v("sawdust-workshop-cleanup-duty", "/锯末", "/ˈsɔːdʌst/", "n.", 7, 0.7, "Sawdust seasons every workshop sandwich.", "锯末给车间三明治调味。", "vacuum sawdust before it settles"),
  v("conveyor-belt-speed-adjustment", "/传送带", "/kənˈveɪər belt/", "n.", 7, 0.65, "Conveyor belts set the factory's heartbeat.", "传送带定下工厂的心跳。", "stop the conveyor belt before clearing jams"),
  v("packaging-recyclable-material-switch", "/包装", "/ˈpækɪdʒɪŋ/", "n.", 5, 0.45, "Packaging is advertising you throw away.", "包装是被你扔掉的广告。", "reduce packaging without breaking products"),
  v("distribution-network-regional-hubs-map", "/分销；分发", "/ˌdɪstrɪˈbjuːʃn/", "n.", 6, 0.6, "Distribution decides who tastes your product.", "分销决定谁能尝到你的产品。", "expand distribution into second-tier cities"),
  v("wholesale-vs-retail-pricing-tiers", "/批发价", "/ˈhoʊlseɪl/", "adv./adj./n.", 6, 0.6, "Wholesale prices need ten-times volume.", "批发价需要十倍的量。", "buy hardware wholesale with the crew"),
  v("export-license-paperwork-checklist", "/出口许可证", "/ˈekspɔːrt ˈlaɪsns/", "n.", 7, 0.75, "Export licenses take longer than prototypes.", "出口许可证比原型机还慢。", "apply for the export license early"),
  v("customs-declaration-form-line", "/海关", "/ˈkʌstəmz/", "n.", 5, 0.5, "Customs held our samples hostage.", "海关扣下了我们的样品。", "clear customs with complete paperwork"),
  v("tariff-code-classification-lookup", "/税则编码", "/ˈtærɪf koʊd/", "n.", 7, 0.8, "Wrong tariff codes cost real money.", "错的税则编码真金白银地亏钱。", "verify tariff codes before quoting prices"),
  v("fleet-delivery-van-routing-software", "/车队；舰队", "/fliːt/", "n.", 7, 0.65, "Our delivery fleet runs on coffee and algorithms.", "我们的配送车队靠咖啡和算法运转。", "electrify the company fleet gradually"),
  v("route-optimization-algorithm-savings", "/路线；路径", "/ruːt/", "n.", 4, 0.35, "Optimized routes saved nine hundred miles weekly.", "优化路线每周省九百英里。", "recalculate routes around rush hour"),
  v("carbon-neutral-shipping-pledge", "/碳中性的", "/ˈkɑːrbən ˈnuːtrəl/", "adj.", 7, 0.7, "Carbon-neutral pledges need receipts too.", "碳中和承诺也需要凭据。", "offer carbon-neutral shipping at checkout"),
];
