import { v } from "@/content/vocab/builder";
import type { VocabRow } from "@/content/vocab/types";

/** City infrastructure & public services - Phase 10 chunk-h. */
export const cityInfrastructureRows: VocabRow[] = [
  v("infrastructure-investment-decade-plan", "/基础设施投资", "/ˈɪnfrəˌstrʌktʃər/", "n.", 7, 0.65, "Infrastructure ages one budget cycle at a time.", "基础设施随一个又一个预算周期老化。", "prioritize infrastructure repairs transparently"),
  v("metro-subway-rush-hour-crush", "/地铁", "/ˈmetroʊ/", "n.", 4, 0.35, "The metro swallows thirty thousand mornings daily.", "地铁每天吞下三万个清晨。", "take the metro to the museum"),
  v("bus-route-night-service-map", "/公交线路", "/bʌs ruːt/", "n.", 4, 0.35, "The night bus route saved my internship.", "夜班公交救了我的实习。","memorize the airport bus route"),
  v("commute-train-seat-luck-factor", "/通勤；上下班路程", "/kəˈmjuːt/", "n./v.", 4, 0.35, "A podcast redeems any commute under an hour.", "一小时的通勤有播客就能救赎。", "shorten your commute by moving closer"),
  v("traffic-congestion-pricing-zone-debate", "/拥堵；塞车", "/kənˈdʒestʃən/", "n.", 7, 0.65, "Congestion charges changed downtown driving fast.", "拥堵费迅速改变市中心驾车习惯。", "ease congestion with staggered hours"),
  v("roundabout-yield-circle-driving-rule", "/环岛；迂回路线", "/ˈraʊndəbaʊt/", "n.", 6, 0.6, "Roundabouts confuse tourists beautifully.", "环岛把游客绕得晕头转向。", "signal before exiting the roundabout"),
  v("pedestrian-crossing-button-wait-time", "/行人", "/pəˈdestriən/", "n./adj.", 6, 0.6, "Pedestrians rule this street on Sundays.", "周日这条街由行人做主。", "respect pedestrian right of way"),
  v("sidewalk-cafe-seating-permit", "/人行道", "/ˈsaɪdwɔːk/", "n.", 5, 0.45, "Sidewalk chalk masterpieces wash away nightly.", "人行道粉笔画每晚被冲刷殆尽。", "clear the icy sidewalk responsibly"),
  v("crosswalk-striped-painting-fresh", "/人行横道；斑马线", "/ˈkrɔːswɔːk/", "n.", 5, 0.5, "Paint the faded crosswalk before winter.", "入冬前重画褪色的斑马线。", "stop well before the crosswalk line"),
  v("streetlight-led-retrofit-project", "/路灯", "/ˈstriːtlaɪt/", "n.", 7, 0.65, "Streetlights flicker like nervous fireflies here.", "这里的路灯像紧张的萤火虫般闪烁。", "report a broken streetlight promptly"),
  v("sewer-system-century-old-pipes", "/下水道；污水管", "/ˈsuːər/", "n.", 7, 0.75, "Century-old sewers groan beneath parades.", "百年下水道在游行队伍下呻吟。", "inspect aging sewer lines proactively"),
  v("drainage-flooding-basement-risk", "/排水；排水系统", "/ˈdreɪnɪdʒ/", "n.", 7, 0.7, "Bad drainage drowned three parking lots.", "糟糕的排水淹了三个停车场。", "improve yard drainage before monsoon season"),
  v("water-treatment-plant-tour-day", "/水处理", "/ˈwɔːtər ˈtriːtmənt/", "n.", 7, 0.7, "Water treatment turns rivers into tap water.", "水处理把河水变成自来水。", "upgrade the city's water treatment capacity"),
  v("tap-water-filter-jug-habit", "/自来水", "/tæp ˈwɔːtər/", "n.", 3, 0.25, "Tap water here beats bottled brands blind.", "这里的自来水盲测胜过瓶装品牌。", "drink more tap water safely"),
  v("power-outage-candle-dinner-memory", "/停电（同 outage）；中断", "/ˈaʊtteɪdʒ/", "n.", 7, 0.7, "The outage lasted exactly one barbecue.", "停电恰好持续了一次烧烤的时间。", "report the power outage within minutes"),
  v("utility-bill-autopay-discount", "/公用事业；效用", "/juːˈtɪləti/", "n.", 5, 0.5, "Utility bills spike in both extremes.", "水电煤气账单在两个极端月份飙升。", "compare utility providers annually"),
  v("gas-station-full-tank-math", "/加油站", "/ɡæs ˈsteɪʃn/", "n.", 3, 0.25, "Every road trip starts at a gas station.", "每段公路旅行始于加油站。", "fill up at the last gas station first"),
  v("charging-station-ev-plug-anxiety", "/充电站", "/ˈtʃɑːrdʒɪŋ ˈsteɪʃn/", "n.", 6, 0.55, "Charging stations host quiet business deals now.", "如今充电站里谈着安静的生意。", "map charging stations before road trips"),
  v("recycling-center-sorting-rules-poster", "/回收中心", "/riːˈsaɪklɪŋ ˈsentər/", "n.", 6, 0.6, "The recycling center rejects greasy pizza boxes.", "回收中心拒绝油腻的披萨盒。", "sort recyclables before the center run"),
  v("landfill-diversion-rate-target-goal", "/垃圾填埋转移率", "/ˈlændfɪl-n2/", "n.", 7, 0.75, "Divert waste; landfills outlive us all.", "分流垃圾，填埋场比我们都长寿。", "raise the landfill diversion rate yearly"),
  v("park-playground-swing-set-repair", "/公园；停车场", "/pɑːrk/", "n./v.", 1, 0.1, "Park near the entrance, not the cart return.", "停在入口附近，别停到还车处。", "jog the park loop each morning"),
  v("public-library-free-tutoring-hours", "/公共图书馆", "/ˈpʌblɪk ˈlaɪbreri/", "n.", 5, 0.4, "Public libraries air-condition dreams for free.", "公共图书馆免费为梦想降温。", "study at the public library weekly"),
  v("community-center-gym-membership-deal", "/社区中心", "/kəˈmjuːnəti ˈsentər/", "n.", 5, 0.45, "Community centers teach grandma TikTok now.", "社区中心现在教奶奶玩短视频。", "book the community center hall early"),
  v("hospital-emergency-wing-expansion", "/医院", "/ˈhɑːspɪtl/", "n.", 1, 0.15, "Hospital waiting rooms test everyone's patience.", "医院候诊室考验所有人的耐心。", "visit grandpa at the hospital Sunday"),
  v("fire-station-open-house-day", "/消防站", "/ˈfaɪər ˌsteɪʃn/", "n.", 5, 0.45, "Fire station dogs greet school tours proudly.", "消防站的狗骄傲地迎接学生参观团。", "tour the neighborhood fire station once"),
  v("police-precinct-community-meeting-night", "/警察分局；管辖区", "/ˈpriːsɪŋkt/", "n.", 7, 0.75, "Precinct meetings start awkward and end hopeful.", "警民会议开场尴尬收尾充满希望。", "attend the precinct safety forum"),
  v("postal-service-mail-carrier-route", "/邮政服务", "/ˈpoʊstl ˈsɜːrvɪs/", "n.", 5, 0.45, "Postal services deliver ballots and birthdays alike.", "邮递既送选票也送生日祝福。", "complain to the postal service politely"),
  v("mailbox-cluster-number-key-copy", "/邮箱；信箱", "/ˈmeɪlbɑːks/", "n.", 5, 0.45, "Mailbox keys vanish exactly when tax forms arrive.", "税表寄到时邮箱钥匙准时失踪。", "check the mailbox before the storm"),
  v("courier-signature-required-package", "/快递员；信使", "/ˈkʊriər/", "n.", 6, 0.6, "Couriers learn your doorbell's personality.", "快递员熟悉你家门铃的脾气。", "tip holiday couriers generously"),
  v("construction-site-hardhat-zone-rules", "/建筑工地", "/kənˈstrʌkʃn saɪt/", "n.", 5, 0.5, "Construction sites wake before alarm clocks.", "建筑工地比闹钟醒得早。","walk around the construction site detour"),
  v("crane-operator-high-altitude-license", "/起重机；吊车", "/kreɪn/", "n.", 6, 0.6, "Cranes dance with steel at sunrise.", "吊车在日出时与钢铁共舞。", "watch the harbor cranes load container ships"),
  v("scaffolding-street-shed-canopy", "/脚手架", "/ˈskæfoʊldɪŋ/", "n.", 7, 0.7, "Scaffolding becomes the building's winter coat.", "脚手架是建筑的冬衣。", "walk under the scaffolding carefully"),
  v("demolition-permit-neighbor-notice", "/拆除；摧毁", "/ˌdeməˈlɪʃn/", "n.", 7, 0.7, "Demolition day draws lawn-chair spectators.", "拆迁日引来搬躺椅围观的观众。", "delay demolition until permits clear"),
  v("renovation-budget-overrun-surprise-cost", "/翻新；整修", "/ˌrenəˈveɪʃn/", "n.", 7, 0.65, "Renovation budgets double behind your back.", "装修预算总在你背后翻倍。", "finish the kitchen renovation before hosting holidays"),
  v("housing-development-subdivision-names", "/住宅开发；住房", "/ˈhaʊzɪŋ dɪˈveləpmənt/", "n.", 6, 0.6, "Housing developments swallow orchards overnight.", "住宅开发一夜吞掉果园。", "oppose the housing development rezoning plan"),
  v("affordable-housing-lottery-application", "/经济适用房", "/əˈfɔːrdəbl ˈhaʊzɪŋ/", "n.", 7, 0.65, "Affordable housing waits list longer than blockbusters.", "经适房排队名单比大片还长。", "expand affordable housing near transit lines"),
  v("gentrification-coffee-shop-index-joke", "/士绅化；中产阶级化", "/ˌdʒentrɪfɪˈkeɪʃn/", "n.", 7, 0.8, "Gentrification arrives one oat-milk latte at a time.", "士绅化随着一杯杯燕麦拿铁到来。", "debate gentrification with long-time residents"),
  v("zoning-law-residential-commercial-map", "/分区规划法规", "/ˈzoʊnɪŋ lɔː/", "n.", 7, 0.8, "Zoning laws decide cities before voters do.", "分区法规比选民更早决定城市样貌。", "challenge outdated zoning laws publicly"),
];
