import { v } from "@/content/vocab/builder";
import type { VocabRow } from "@/content/vocab/types";

/** Food, cuisine & dining culture - Phase 10 chunk-h. */
export const foodCuisineRows: VocabRow[] = [
  v("cuisine-regional-style-cooking", "/菜肴；烹饪风格", "/kwɪˈziːn/", "n.", 6, 0.55, "Sichuan cuisine argues with timid tongues.", "川菜与胆小的舌头争辩。", "explore regional Chinese cuisines deeply"),
  v("gourmet-food-hall-stand", "/美食家；讲究饮食的", "/ɡʊrˈmeɪ/", "adj./n.", 7, 0.65, "Gourmet labels double prices magically.", "贴上“精品”标签价格自动翻倍。", "host a gourmet dinner at home"),
  v("appetizer-starter-small-plate-first", "/开胃菜", "/ˈæpɪtaɪzər/", "n.", 5, 0.45, "Great appetizers set the evening's tempo.", "好的前菜定下整晚的节奏。", "share three appetizers instead of one"),
  v("entree-main-course-us-menu-word", "/主菜（美式）；入场", "/ˈɑːntreɪ/", "n.", 7, 0.65, "The entree arrives; phones go dark.", "主菜上桌，手机熄屏。", "pick the chef's recommended entree"),
  v("dessert-menu-browse-strategy", "/甜点；餐后甜食", "/dɪˈzɜːrt/", "n.", 4, 0.35, "Save stomach space for dessert diplomacy.", "为甜点外交留出胃容量。", "split the chocolate dessert two ways"),
  v("appetite-sharpened-by-walks", "/食欲；胃口", "/ˈæpɪtaɪt/", "n.", 4, 0.35, "Hiking builds an honest appetite.", "远足锻造诚实的食欲。", "lose your appetite from bad news"),
  v("flavor-profile-smoky-citrus-notes", "/味道；风味", "/ˈfleɪvər/", "n.", 4, 0.35, "Smoke is a flavor you remember by coat.", "烟熏味是沾在外套上的记忆。", "layer flavor with fresh herbs"),
  v("seasoning-salt-fat-acid-heat-balance", "/调味；佐料", "/ˈsiːzənɪŋ/", "n.", 5, 0.5, "Seasoning decides dinner's fate early.", "调味早早决定晚餐命运。", "taste and adjust seasoning last"),
  v("marinade-overnight-flavor-soak", "/腌泡汁；腌泡", "/ˌmærɪˈneɪd/", "n./v.", 7, 0.7, "A yogurt marinade tenderizes everything.", "酸奶腌料让一切变嫩。", "marinade overnight in the fridge"),
  v("braise-low-slow-meat-method", "/炖；焖", "/breɪz/", "v.", 7, 0.75, "Braise cheap cuts into luxury.", "把便宜肉块炖成奢华美味。", "braise short ribs all afternoon"),
  v("simmer-gentle-bubble-watch", "/煨；文火慢煮", "/ˈsɪmər/", "v./n.", 5, 0.5, "Let the sauce simmer while you set the table.", "摆桌时让酱汁小火咕嘟着。", "simmer uncovered to thicken"),
  v("steam-vegetable-basket-method", "/蒸；蒸汽", "/stiːm/", "v./n.", 3, 0.3, "Steam dumplings until the skins turn glassy.", "把饺子蒸到皮呈玻璃感。", "steam broccoli for four minutes exactly"),
  v("stew-one-pot-winter-comfort", "/炖菜；焖", "/stuː/", "n./v.", 4, 0.35, "Stews taste better the second day.", "炖菜第二天更好吃。", "freeze half the stew for later"),
  v("roast-vegetable-caramelized-edges-trick", "/烤；烘焙", "/roʊst/", "v./n.", 4, 0.35, "Roast carrots until their edges candy.", "把胡萝卜烤到边缘焦糖化。", "roast the chicken breast-side up"),
  v("grill-char-mark-seasoning-debate", "/烧烤架；烤", "/ɡrɪl/", "n./v.", 3, 0.3, "Grill marks are summer's signature.", "烤痕是夏天的签名。", "grill peaches for surprising dessert"),
  v("deep-fry-once-a-year-treat", "/油炸", "/diːp fraɪ/", "v.", 5, 0.5, "Deep-fry nothing you must carry upstairs.", "别油炸任何要端上楼的东西。", "deep-fry spring rolls outside if possible"),
  v("knead-dough-eight-minute-workout", "/揉（面团）", "/niːd/", "v.", 7, 0.65, "Knead bread dough like stress relief.", "像减压一样揉面团。", "knead until the dough springs back"),
  v("yeast-bread-rising-science", "/酵母", "/jiːst/", "n.", 7, 0.65, "Yeast sleeps in cold fridges patiently.", "酵母在冰箱里耐心沉睡。", "proof yeast in warm water first"),
  v("dough-rest-covered-hour-rule", "/生面团", "/doʊ/", "n.", 6, 0.6, "Rest the dough; it earned it.", "让面团歇会儿，它应得的。", "roll the chilled dough thinly"),
  v("batter-lumpy-is-fine-rule", "/面糊", "/ˈbætər/", "n.", 6, 0.6, "Lumpy batter forgives impatient bakers never.", "结块的面糊从不原谅心急的烘焙者。", "rest the pancake batter ten minutes"),
  v("whisk-stiff-peaks-arm-day", "/搅拌器；搅打", "/wɪsk/", "n./v.", 5, 0.5, "Whisk cream only as far as it needs.", "奶油打发到需要的程度就停。", "whisk the vinaigrette until cloudy"),
  v("grate-cheese-room-temperature-tip", "/磨碎；擦丝", "/ɡreɪt/", "v.", 5, 0.5, "Grate cheese straight onto steaming pasta.", "把奶酪直接刨到热气腾腾的面上。", "grate frozen butter for flaky biscuits"),
  v("chop-even-sized-miracle-expectations", "/切碎；砍", "/tʃɑːp/", "v.", 3, 0.3, "Chop onions near running water, they said.", "他们说在水流边切洋葱就不流泪。", "chop herbs gently with a sharp knife"),
  v("slice-paper-thin-dedication-test", "/切片；薄片", "/slaɪs/", "v./n.", 2, 0.2, "Slice the loaf while it barely cools.", "趁面包刚凉就切片吧。","skip a slice of birthday cake tonight"),
  v("dice-uniform-cube-perfectionism", "/切丁；骰子", "/daɪs/", "v./n.", 5, 0.5, "Dice onions finer than your patience allows.", "把洋葱切成比耐心更细的丁。", "dice mangoes with the pit trick"),
  v("peel-one-strip-challenge-game", "/削皮；剥皮", "/piːl/", "v./n.", 3, 0.25, "Peel apples in one unbroken ribbon.", "把苹果皮削成不断的一条。", "peel ginger with a spoon edge"),
  v("boil-water-first-always-advice", "/煮沸；沸腾", "/bɔɪl/", "v./n.", 1, 0.1, "Boil water before adding noodles, always.", "下面之前先把水烧开，永远如此。", "bring the pot to a rolling boil"),
  v("microwave-reheat-leftover-etiquette", "/微波炉", "/ˈmaɪkroʊweɪv/", "n./v.", 2, 0.15, "Microwave leftovers in short bursts.", "剩菜用微波炉短时多次加热。", "reheat rice thoroughly before eating"),
  v("leftovers-next-day-lunch-plan", "/剩饭剩菜", "/ˈleftoʊvərz/", "n.", 4, 0.35, "Leftovers are yesterday cooking for you twice.", "剩菜是昨天的你替今天做饭。", "transform leftovers into fried rice"),
  v("takeout-friday-night-tradition", "/外卖食物", "/ˈteɪkaʊt/", "n.", 4, 0.3, "Friday takeout funds small joys weekly.", "周五外卖每周资助小确幸。", "order takeout from the new noodle shop"),
  v("delivery-driver-apartment-hunt-game", "/送货；递送", "/dɪˈlɪvəri/", "n.", 3, 0.25, "Delivery apps know my comfort foods too well.", "外卖应用太懂我的安慰食物。", "track your delivery in real time"),
  v("buffet-all-you-can-eat-strategy-talk", "/自助餐", "/bʌˈfeɪ/", "n.", 5, 0.45, "Buffet strategy: survey before loading.", "自助餐策略：先侦察再装盘。", "pace yourself at Sunday buffet brunches"),
  v("picnic-blanket-real-estate-negotiation", "/野餐", "/ˈpɪknɪk/", "n.", 4, 0.35, "Picnic menus travel badly but taste better anyway.", "野餐菜单经不起颠簸却格外好吃。", "pack the picnic basket the night before"),
  v("barbecue-regional-sauce-holy-war", "/烧烤聚会；烤肉", "/ˈbɑːrbɪkjuː/", "n./v.", 4, 0.35, "Barbecue debates end friendships politely.", "烧烤酱之争礼貌地终结友谊。", "host a backyard barbecue this weekend"),
  v("brunch-eggs-benedict-weekend-ritual", "/早午餐", "/brʌntʃ/", "n.", 4, 0.35, "Brunch is breakfast wearing sunglasses.", "早午餐是戴着墨镜的早餐。", "reserve brunch tables two weeks ahead"),
  v("street-vendor-night-market-row", "/街头摊贩", "/striːt ˈvendər/", "n.", 6, 0.55, "Street vendors feed cities better than malls do.", "街头摊贩比商场更好地喂养城市。", "follow the locals to trusted street vendors"),
  v("food-truck-lunch-line-strategy", "/餐车", "/fuːd trʌk/", "n.", 6, 0.6, "Food trucks post today's location at dawn.", "餐车清晨发布今日位置。", "chase the taco truck across town"),
  v("farmers-market-saturday-morning-ritual", "/农贸市场", "/ˈfɑːrmərz ˈmɑːrkɪt/", "n.", 6, 0.55, "Farmers markets sell seasons, not just vegetables.", "农夫市场卖的是季节而非蔬菜。", "arrive early at the farmers market"),
  v("organic-produce-price-premium-debate", "/有机的", "/ɔːrˈɡænɪk/", "adj.", 5, 0.45, "Organic strawberries taste like actual weather.", "有机草莓尝得出真实的天气。", "prioritize organic for thin-skinned fruits"),
  v("free-range-egg-yolk-color-myth", "/散养的；自由放养的", "/friː reɪndʒ/", "adj.", 7, 0.65, "Free-range yolks stand taller in the bowl.", "散养蛋黄在碗里站得更挺。", "buy free-range eggs from local farms"),
  v("gluten-free-menu-substitution-tax", "/无麸质的", "/ˈɡluːtn friː/", "adj.", 6, 0.6, "Gluten-free bread improved dramatically lately.", "无麸质面包近来进步神速。", "offer gluten-free options without sighing"),
  v("vegan-restaurant-menu-expansion-wave", "/纯素食的；严格素食者", "/ˈviːɡən/", "adj./n.", 5, 0.45, "Vegan bakeries fooled every skeptic present.", "纯素面包店骗过了在场每位怀疑论者。", "try vegan versions before judging them"),
  v("vegetarian-since-college-badge", "/素食者；素的", "/ˌvedʒəˈteriən/", "n./adj.", 4, 0.35, "Vegetarians memorize protein charts involuntarily.", "素食者不由自主背下蛋白质表。", "cook one vegetarian dinner weekly"),
  v("allergy-menu-separate-fryer-request", "/过敏原；过敏反应", "/ˈælərdʒi/", "n.", 5, 0.45, "Allergy questions save lives at restaurants.", "在餐厅询问过敏原是在救命。", "flag your nut allergy clearly when booking"),
  v("nutritionist-approved-meal-prep-sunday", "/营养师（同 dietitian 变体）", "/nuˈtrɪʃənɪst/", "n.", 6, 0.6, "Sunday meal prep silences weekday vending machines.", "周日备餐让工作日的售货机闭嘴。", "start simple meal prep Sundays"),
  v("calorie-counting-app-streak-psychology", "/卡路里计数", "/ˈkæləri ˈkaʊntɪŋ/", "n.", 6, 0.6, "Calorie counting works until dinner parties.", "卡路里计数在晚宴面前失效。", "quit obsessive calorie counting gently"),
  v("portion-size-restaurant-inflation-joke", "/一份的量；部分", "/ˈpɔːrʃn/", "n.", 4, 0.35, "Portion sizes grew faster than wages.", "餐品份量涨得比工资快。", "halve restaurant portions and box the rest"),
];
