import { v } from "@/content/vocab/builder";
import type { VocabRow } from "@/content/vocab/types";

/** Sports, competition & outdoor adventure - Phase 10 chunk-h. */
export const sportsAdventureRows: VocabRow[] = [
  v("championship-title-defense-season", "/锦标赛；冠军赛", "/ˈtʃæmpiənʃɪp/", "n.", 4, 0.35, "The championship hangs on one penalty kick.", "冠军归属悬于一次点球。", "reach the national championship finals"),
  v("tournament-bracket-prediction-sheet", "/联赛；锦标赛", "/ˈtʊrnəmənt/", "n.", 4, 0.35, "Office tournament pools ruin friendships by noon.", "办公室竞猜到中午就毁掉友谊。", "advance through the tournament bracket"),
  v("league-standings-weekly-update", "/联盟；同盟", "/liːɡ/", "n.", 3, 0.3, "Our rec league values snacks over scorelines.", "我们的业余联盟看重零食胜过比分。", "top the local league standings"),
  v("coach-timeout-drawing-board-moment", "/教练；辅导", "/koʊtʃ/", "n./v.", 2, 0.2, "A good coach benches egos without apology.", "好教练毫不犹豫让自尊坐板凳。", "trust the coach's game plan"),
  v("referee-whistle-blind-spot-jokes", "/裁判员", "/ˌrefəˈriː/", "n.", 5, 0.5, "Referees see everything except what matters.", "裁判什么都看得见，除了关键处。", "argue with the referee politely"),
  v("umpire-strike-zone-debate-eternal", "/裁判（板球、棒球等）；仲裁", "/ˈʌmpaɪər/", "n.", 7, 0.7, "Umpires age slower than their critics claim.", "裁判老得比批评者说的慢。", "respect the umpire's final call"),
  v("stadium-sea-of-color-wave-starts", "/体育场；运动场", "/ˈsteɪdiəm/", "n.", 3, 0.3, "The stadium roared before kickoff even came.", "开球前体育场已沸腾。", "tailgate outside the stadium first"),
  v("scoreboard-clock-zero-heartbreak-formula", "/记分牌", "/ˈskɔːrbɔːrd/", "n.", 6, 0.6, "Scoreboards lie until the final whistle.", "终场哨响前记分牌都在说谎。", "glance at the scoreboard nervously"),
  v("playoff-seeding-math-nightmare", "/季后赛；加时赛", "/ˈpleɪɔːf/", "n.", 7, 0.65, "Playoff basketball doubles every heartbeat.", "季后赛篮球让心跳翻倍。", "clinch a playoff spot in week ten"),
  v("overtime-sudden-death-rules-confusion", "/加班时间；超时", "/ˈoʊvərtaɪm/", "n./adj.", 5, 0.45, "Overtime punishes whoever wants it less.", "加时惩罚更不想要它的一方。", "win in overtime against the rivals"),
  v("penalty-shootout-nerves-of-steel-test", "/点球大战", "/ˈpenəlti ˈʃuːtaʊt/", "n.", 7, 0.65, "Shootouts turn grown men into poets and philosophers.", "点球大战把成年人变成诗人和哲学家。", "survive the penalty shootout heroically"),
  v("marathon-training-plan-sixteen-weeks", "/马拉松", "/ˈmærəθɑːn/", "n.", 5, 0.5, "Marathons are eating contests with scenery.", "马拉松是带风景的大胃王比赛。", "finish your first marathon upright"),
  v("triathlon-three-sports-one-morning", "/铁人三项", "/traɪˈæθlən/", "n.", 7, 0.75, "Triathlon transitions are their own sport.", "铁人三项的换项本身就是一项运动。", "train for a sprint triathlon first"),
  v("relay-baton-pass-perfection-drill", "/接力赛；中继", "/ˈriːleɪ/", "n./v.", 6, 0.6, "Relay races forgive everything but the baton.", "接力赛原谅一切，除了交接棒。", "anchor the relay team's final leg"),
  v("gym-membership-guilt-vs-gains-cycle", "/健身房；体育馆", "/dʒɪm/", "n.", 3, 0.25, "January gyms empty out by March.", "一月的健身房三月就空了。", "cancel the unused gym membership honestly"),
  v("personal-record-beat-last-self-only", "/个人纪录", "/ˈpɜːrsənəl ˈrekərd/", "n.", 7, 0.65, "Beat your personal record; ignore strangers' timelines.", "只跟自己的最好成绩较劲。", "set a new deadlift personal record"),
  v("warmup-injury-prevention-non-negotiable", "/热身；准备活动", "/ˈwɔːrmʌp/", "n./adj.", 5, 0.45, "Warmups are boring insurance policies.", "热身是无聊的保险单。", "never skip the warmup rounds again"),
  v("cooldown-stretch-five-minute-rule", "/放松整理运动", "/ˈkuːldaʊn/", "n.", 6, 0.55, "Cooldown walks carry the best conversations.", "放松慢走承载最好的对话。", "end sessions with a proper cooldown"),
  v("stretch-desk-worker-lifesaver-move", "/伸展；拉伸", "/stretʃ/", "v./n.", 3, 0.25, "Stretch hips hourly if you sit all day.", "久坐者每小时拉伸髋部。", "hold each stretch for thirty seconds"),
  v("hydration-water-bottle-companion-object", "/补水；水合作用", "/haɪˈdreɪʃn/", "n.", 7, 0.65, "Hydration fixes half of all headaches.", "补水能治一半的头痛。", "monitor hydration on long hikes"),
  v("endurance-built-not-born-truth", "/耐力；持久力", "/ɪnˈdʊrəns/", "n.", 6, 0.6, "Endurance is stubbornness wearing sneakers.", "耐力是穿运动鞋的固执。", "build endurance through slow miles"),
  v("stamina-final-quarter-fuel-reserve", "/体力；毅力", "/ˈstæmɪnə/", "n.", 6, 0.6, "Stamina decides who finishes strong.", "体力决定谁能强势收尾。", "boost stamina with interval training"),
  v("flexibility-yoga-class-side-effect", "/灵活性；柔韧性", "/ˌfleksəˈbɪləti/", "n.", 5, 0.45, "Flexibility negotiates better than muscles do.", "柔韧性比肌肉更会谈判。", "improve flexibility with evening yoga"),
  v("hiking-trail-snack-pack-ethics", "/远足；徒步旅行", "/ˈhaɪkɪŋ/", "n.", 4, 0.3, "Hiking conversations climb better than feet do.", "徒步时的聊天比脚步爬得更high。", "pack layers for autumn hiking trips"),
  v("camping-tent-pitch-in-the-dark-story", "/露营", "/ˈkæmpɪŋ/", "n.", 4, 0.3, "Camping resets sleep better than vacations do.", "露营比度假更能重置睡眠。", "book the lakeside camping spot early"),
  v("backpacking-light-gear-religion-debate", "/背包旅行", "/ˈbækpækɪŋ/", "n.", 7, 0.65, "Backpacking weighs grams like diamonds.", "背包客把克数当钻石计较。", "trim backpacking weight ruthlessly"),
  v("rock-climbing-chalk-bag-rituals", "/攀岩", "/rɑːk ˈklaɪmɪŋ/", "n.", 6, 0.6, "Rock climbing is puzzle-solving with consequences.", "攀岩是有后果的解谜。", "trust the rope while rock climbing"),
  v("skiing-black-diamond-confidence-check", "/滑雪（运动）", "/ˈskiːɪŋ/", "n.", 5, 0.45, "Skiing lessons cost less than knee surgery.", "滑雪课比膝盖手术便宜。", "graduate to blue-square skiing runs"),
  v("snowboarding-heal-side-learning-curve", "/单板滑雪", "/ˈsnoʊbɔːrdɪŋ/", "n.", 6, 0.6, "Snowboarding bruises teach physics viscerally.", "单板的淤青用身体教物理。", "link turns while snowboarding downhill"),
  v("surfing-wipeout-story-collection", "/冲浪（运动）", "/ˈsɜːrfɪŋ/", "n.", 5, 0.5, "Surfing is mostly paddling with moments of flying.", "冲浪大多是划水，偶尔飞翔。", "read the waves before surfing them"),
  v("kayaking-portage-port-arm-workout", "/皮划艇运动", "/ˈkaɪækɪŋ/", "n.", 7, 0.65, "Kayaking mirrors teach herons patience.", "皮划艇的水面倒影教会苍鹭耐心。", "rent kayaks for the river afternoon"),
  v("fishing-patience-with-a-rod-license", "/钓鱼", "/ˈfɪʃɪŋ/", "n.", 3, 0.3, "Fishing licenses fishing stories legally.", "钓鱼执照合法化吹牛素材。", "cast at dawn for the best fishing"),
  v("hunting-season-regulations-book-thick", "/打猎；狩猎", "/ˈhʌntɪŋ/", "n.", 5, 0.45, "Hunting season orange saves lives literally.", "狩猎季的橙色衣服字面意义上救命。", "review hunting regulations every fall"),
  v("cycling-commute-vs-weekend-warrior-split", "/骑行；自行车运动", "/ˈsaɪklɪŋ/", "n.", 4, 0.35, "Cycling commutes double as therapy sessions.", "骑车通勤自带理疗效果。", "join a weekend cycling group ride"),
  v("swimming-laps-meditation-with-water", "/游泳", "/ˈswɪmɪŋ/", "n.", 2, 0.2, "Swimming clears mental tabs faster than sleep.", "游泳清空大脑标签页快过睡眠。", "swim laps twice a week minimum"),
  v("boxing-footwork-poetry-round-two", "/拳击（运动）", "/ˈbɑːksɪŋ/", "n.", 6, 0.6, "Boxing footwork hides years of bruised toes.", "拳击步法下藏着多年的淤青脚趾。", "learn boxing footwork before punching hard"),
  v("martial-arts-belt-ranking-systems", "/武术", "/ˈmɑːrʃl ɑːrts/", "n.", 6, 0.55, "Martial arts bow before they spar.", "武术先鞠躬再切磋。", "enroll kids in martial arts for discipline"),
  v("gymnastics-flexibility-meets-courage-test", "/体操；体操训练", "/dʒɪmˈnæstɪks/", "n.", 6, 0.6, "Gymnastics parents age decades per routine.", "体操家长一套动作老十岁。", "watch rhythmic gymnastics finals together"),
  v("tennis-serve-speed-gun-numbers", "/网球（运动）", "/ˈtenɪs/", "n.", 3, 0.3, "Tennis scores confuse newcomers delightfully.", "网球的计分愉快地迷惑新人。", "practice tennis serves against the garage door"),
  v("basketball-pickup-game-court-etiquette", "/篮球（运动）", "/ˈbæskɪtbɔːl/", "n.", 3, 0.3, "Pickup basketball drafts strangers into brothers.", "野球场把陌生人变成兄弟。", "call next game at the basketball court"),
  v("soccer-youth-league-saturday-mornings", "/足球（美式说法）", "/ˈsɑːkər/", "n.", 3, 0.3, "Youth soccer Saturdays smell of orange slices.", "少年足球的周六有橙子瓣的味道。", "coach the neighborhood soccer clinic"),
  v("baseball-scorecard-pencil-tradition", "/棒球（运动）", "/ˈbeɪsbɔːl/", "n.", 3, 0.3, "Baseball games fit whole summers inside nine innings.", "棒球把整个夏天装进九局。", "keep score with a pencil at baseball games"),
  v("volleyball-sand-between-toes-version", "/排球（运动）", "/ˈvɑːlibɔːl/", "n.", 4, 0.35, "Beach volleyball sand gets everywhere permanently.", "沙滩排球的沙子永远无处不在。", "spike the volleyball at the company picnic"),
  v("badminton-backyard-fastest-racquet-sport", "/羽毛球（运动）", "/ˈbædmɪntən/", "n.", 5, 0.4, "Backyard badminton humbles athletes fast.", "后院羽毛球快速羞辱运动员。", "string the badminton net between trees"),
  v("ping-pong-office-champion-politics", "/乒乓球（口语）；乒乓", "/ˈpɪŋ pɑːŋ/", "n.", 5, 0.4, "Office ping-pong titles matter more than KPIs.", "办公室乒乓冠军头衔比KPI重要。", "defend your ping-pong title at lunch"),
  v("golf-handicap-honesty-commitment", "/高尔夫球运动", "/ɡɑːlf/", "n.", 5, 0.4, "Golf handicaps are confessions with numbers.", "高尔夫差点是带数字的自白。", "book the dawn golf tee time"),
  v("esports-team-sponsorship-mainstream-era", "/电子竞技", "/ˈiː spɔːrts/", "n.", 7, 0.65, "Esports arenas sell out like rock concerts.", "电竞馆像摇滚现场一样满座。", "follow the collegiate esports league"),
];
