import { v } from "@/content/vocab/builder";
import type { VocabRow } from "@/content/vocab/types";

/** Fashion, beauty & style - Phase 10 chunk-h. */
export const fashionBeautyRows: VocabRow[] = [
  v("fashion-week-front-row-chaos", "/时尚；时装业", "/ˈfæʃn/", "n.", 3, 0.25, "Fashion recycles decades on a twenty-year loop.", "时尚以二十年为周期回收年代。", "follow fashion week coverage casually"),
  v("style-personal-signature-outfit-formula", "/风格；款式", "/staɪl/", "n.", 2, 0.2, "Style is consistency with occasional surprises.", "风格是一致性加偶尔的惊喜。", "develop a signature personal style"),
  v("wardrobe-capsule-twelve-piece-theory", "/衣柜；全部衣物", "/ˈwɔːrdroʊb/", "n.", 5, 0.45, "Capsule wardrobes end morning negotiations early.", "胶囊衣橱终结清晨的穿搭谈判。", "declutter your wardrobe seasonally"),
  v("closet-purge-marie-kondo-hour", "/壁橱；衣橱", "/ˈklɔːzɪt/", "n./adj.", 4, 0.35, "Closet skeletons escape at reunions.", "同学会上衣橱里的秘密会溜出来。", "organize the hall closet this weekend"),
  v("outfit-planned-night-before-miracle", "/全套服装；装备", "/ˈaʊtfɪt/", "n.", 3, 0.25, "One good outfit survives three occasions.", "一套好衣服能应付三种场合。", "coordinate outfits for the family photo"),
  v("accessory-scarf-elevator-trick", "/配饰；附件", "/əkˈsesəri/", "n.", 5, 0.45, "Accessories rescue boring basics weekly.", "配饰每周拯救无聊的基础款。", "elevate basics with one bold accessory"),
  v("handbag-what-fits-inside-philosophy", "/手提包；手袋", "/ˈhændbæɡ/", "n.", 6, 0.6, "Handbags hold emergency lives inside.", "手袋里装着应急的人生。", "switch handbags without losing keys"),
  v("high-heels-comfort-versus-silhouette-war", "/高跟鞋", "/haɪ hiːlz/", "n.", 5, 0.45, "High heels negotiate with gravity hourly.", "高跟鞋每小时与地心引力谈判。", "pack foldable flats after high heels events"),
  v("sneaker-drop-limited-edition-hype-cycle", "/运动鞋；球鞋", "/ˈsniːkər/", "n.", 4, 0.35, "Sneaker drops sell out before breakfast.", "球鞋发售在早餐前售罄。","rotate two pairs of sneakers max"),
  v("tailor-alterations-perfect-fit-secret", "/裁缝；裁剪", "/ˈteɪlər/", "n./v.", 6, 0.55, "A tailor turns clearance into couture.", "裁缝把清仓货改成高级定制。", "take blazers to the tailor once"),
  v("fabric-content-label-reader-habit", "/织物；布料", "/ˈfæbrɪk/", "n.", 5, 0.45, "Fabric content predicts laundry regrets.", "面料成分预示洗衣悔恨。", "check fabric labels before buying online"),
  v("cotton-breathable-summer-standard", "/棉；棉布", "/ˈkɑːtn/", "n./adj.", 2, 0.15, "Cotton wrinkles honestly.", "棉布诚实地起皱。", "choose soft cotton sheets deliberately"),
  v("wool-winter-sweater-itch-tolerance", "/羊毛；毛线", "/wʊl/", "n.", 4, 0.3, "Wool forgives cold shoulders figuratively only.", "羊毛只在比喻上容忍冷遇。", "store wool sweaters with cedar blocks"),
  v("silk-delicate-handwash-only-warning", "/丝绸；丝线", "/sɪlk/", "n./adj.", 5, 0.45, "Silk whispers where cotton shouts.", "丝绸低语，棉布喊叫。", "iron silk inside a towel sandwich"),
  v("linen-wrinkle-as-aesthetic-choice", "/亚麻布；亚麻的", "/ˈlɪnɪn/", "n.", 7, 0.65, "Linen wrinkles are proof of vacation.", "亚麻的褶皱是度假的证明。", "embrace linen's natural crumple"),
  v("denim-jacket-break-in-period", "/牛仔布", "/ˈdenɪm/", "n.", 6, 0.55, "Denim improves exactly as it frays.", "牛仔布越磨越有味道。", "style one denim jacket five ways"),
  v("vintage-thrift-store-treasure-hunt-rules", "/古董的；复古的", "/ˈvɪntɪdʒ/", "adj./n.", 6, 0.55, "Vintage finds carry previous adventures.", "复古旧物带着前主人的冒险。", "dig through vintage racks patiently"),
  v("secondhand-benefits-double-discount-logic", "/二手的", "/ˈsekəndhænd/", "adj.", 5, 0.45, "Secondhand books come pre-annotated free.", "二手书附赠免费批注。", "shop secondhand before buying new"),
  v("makeup-everyday-five-minute-routine", "/化妆；化妆品", "/ˈmeɪkʌp/", "n.", 4, 0.35, "Makeup should survive hugs and rain.", "妆容要经得住拥抱和雨。", "keep makeup simple for workdays"),
  v("skincare-routine-consistency-over-products", "/护肤", "/ˈskɪnker/", "n.", 6, 0.55, "Skincare rewards patience over price tags.", "护肤奖励耐心而非价格标签。", "simplify skincare to three steps"),
  v("moisturizer-spf-daytime-non-negotiable", "/润肤霜；保湿霜", "/ˈmɔɪstʃəraɪzər/", "n.", 7, 0.65, "Moisturizer with SPF is time travel prevention.", "带防晒的保湿霜是抗时光机。", "apply moisturizer on damp skin"),
  v("sunscreen-reapplication-hour-two-forgetting", "/防晒霜", "/ˈsʌnskriːn/", "n.", 6, 0.55, "Sunscreen expires faster than you reapply it.", "防晒霜过期比你补涂还快。", "pack travel sunscreen in every bag"),
  v("shampoo-sulfate-free-switch-experience", "/洗发水", "/ʃæmˈpuː/", "n.", 4, 0.35, "Shampoo marketing outpaces chemistry.", "洗发水营销跑赢了化学。", "rotate shampoo brands occasionally"),
  v("conditioner-three-minute-shower-timer", "/护发素", "/kənˈdɪʃənər/", "n.", 6, 0.6, "Conditioner needs minutes, not promises.", "护发素需要时间而非许诺。", "rinse conditioner with cool water finally"),
  v("perfume-signature-scent-memory-trigger", "/香水；香味", "/pərˈfjuːm/", "n.", 7, 0.65, "Perfume writes memories into strangers' minds.", "香水把记忆写进陌生人脑海。", "test perfume on skin, not paper"),
  v("deodorant-gym-bag-staple-item", "/除臭剂；止汗剂", "/diˈoʊdərənt/", "n.", 5, 0.45, "Deodorant belongs in every glovebox.", "每辆车的储物格都该有除臭剂。", "reapply deodorant after lunch meetings"),
  v("razor-blade-subscription-model-jokes", "/剃刀；剃须刀", "/ˈreɪzər/", "n.", 5, 0.45, "Razor companies invented subscription boxes first.", "剃须刀公司最早发明订阅盒。", "replace razor blades monthly for comfort"),
  v("barbershop-quarterly-tradition-conversation-tax", "/理发店（男式）", "/ˈbɑːrbərʃɑːp/", "n.", 6, 0.55, "Barbershops dispense haircuts and life advice equally.", "理发店平等供应发型与人生建议。", "book the same barbershop chair forever"),
  v("salon-color-appointment-book-in-advance", "/美发厅；沙龙", "/səˈlɑːn/", "n.", 5, 0.5, "Salon small talk follows predictable scripts.", "美发厅闲聊都有固定剧本。", "schedule salon visits before big interviews"),
  v("haircut-regret-grow-out-phase-diary", "/发型；理发", "/ˈherkʌt/", "n.", 4, 0.35, "Every haircut is negotiable with time.", "每个发型都能靠时间翻篇。", "show the barber photos of the haircut"),
  v("manicure-self-done-versus-salon-cost-math", "/修甲；美甲", "/ˈmænɪkjʊr/", "n./v.", 7, 0.65, "Manicures chip exactly before interviews.", "美甲总在面试前剥落。", "treat yourself to a manicure quarterly"),
  v("beauty-standard-cultural-shift-debates", "/美；美丽", "/ˈbjuːti/", "n.", 2, 0.15, "Beauty standards change; sunscreen advice doesn't.", "审美在变，防晒建议不变。", "find beauty in ordinary routines"),
  v("appearance-first-impression-statistics-debate", "/外貌；外观", "/əˈpɪrəns/", "n.", 4, 0.3, "Appearances open doors; competence keeps them open.", "外貌开门，实力守门。", "polish your professional appearance slightly"),
  v("trend-chasing-fatigue-fast-fashion-critique", "/趋势；潮流", "/trend/", "n.", 4, 0.3, "Trends charge rent in your closet.", "潮流在你的衣柜里收租。", "ignore trends that don't fit your life"),
  v("minimalist-one-in-one-out-policy", "/极简主义者", "/ˈmɪnɪməlɪst/", "adj./n.", 7, 0.65, "Minimalist closets start with honest mirrors.", "极简衣橱始于诚实的镜子。", "adopt minimalist rules for new purchases"),
];
