import { v } from "@/content/vocab/builder";
import type { VocabRow } from "@/content/vocab/types";

/** Emotions & character traits - Phase 10 chunk-h. */
export const emotionsCharacterRows: VocabRow[] = [
  v("courage-fear-walking-anyway-definition", "/勇气；胆量", "/ˈkɜːrɪdʒ/", "n.", 4, 0.3, "Courage texts fear back: coming anyway.", "勇气回复恐惧：照来不误。", "summon courage before hard conversations"),
  v("bravery-everyday-quiet-versions", "/勇敢；勇气", "/ˈbreɪvəri/", "n.", 5, 0.45, "Bravery rarely looks like the movies.", "勇敢很少长得像电影里那样。", "praise quiet bravery in others"),
  v("cowardice-regret-in-advance-feeling", "/懦弱；胆怯", "/ˈkaʊərdɪs/", "n.", 7, 0.7, "Cowardice always sends apologies later.", "怯懦总在事后寄来道歉。", "accuse nobody of cowardice lightly"),
  v("kindness-free-yet-priceless-currency", "/仁慈；善良", "/ˈkaɪndnəs/", "n.", 2, 0.15, "Kindness compounds faster than interest.", "善意比利息复利更快。", "practice random kindness daily"),
  v("generosity-giving-without-calculator", "/慷慨；大方", "/ˌdʒenəˈrɑːsəti/", "n.", 6, 0.55, "Generosity tips like the meal mattered.", "慷慨的小费说明这顿饭很重要。", "model generosity for your kids"),
  v("greed-never-enough-engine", "/贪婪；贪心", "/ɡriːd/", "n.", 5, 0.5, "Greed mistakes having for being.", "贪婪把拥有错当存在。", "guard against quiet greed"),
  v("envy-comparison-machine-fuel-type", "/嫉妒；羡慕", "/ˈenvi/", "n./v.", 6, 0.55, "Envy reads everyone's highlight reels.", "嫉妒专读别人的高光集锦。","admit envy before it curdles"),
  v("jealousy-relationship-green-eyed-guard", "/妒忌；吃醋", "/ˈdʒeləsi/", "n.", 6, 0.6, "Jealousy guards what trust already lost.", "妒忌看守信任早已丢失之物。", "talk through jealousy without accusations"),
  v("pride-healthy-vs-hubris-line-thin", "/自豪；骄傲", "/praɪd/", "n.", 3, 0.25, "Pride lifts; hubris parachutes without checks.", "自豪使人振作，狂妄使人跳伞不带备用伞。", "balance pride with humility carefully"),
  v("humility-strength-without-spotlight-need", "/谦逊；谦逊品质", "/hjuːˈmɪləti/", "n.", 7, 0.65, "Humility keeps learning after winning.", "谦逊在获胜后继续学习。", "lead with visible humility instead"),
  v("patience-waiting-without-grinding-teeth", "/耐心；忍耐", "/ˈpeɪʃns/", "n.", 3, 0.25, "Patience is speed wearing a disguise.", "耐心是化了妆的速度。", "test your patience on purpose sometimes"),
  v("impatience-two-day-shipping-spoiled-us", "/不耐烦；急躁", "/ɪmˈpeɪʃns/", "adj./n.", 4, 0.35, "Impatience ships fast and lands wrong.", "急躁发货快但落点偏。", "catch impatience before hitting send"),
  v("anger-hot-useful-brief-fuel-warning", "/愤怒；怒火", "/ˈæŋɡər/", "n.", 3, 0.25, "Anger is brief fuel; read the label.", "愤怒是短效燃料，看清标签。", "cool anger before drafting replies"),
  v("rage-road-edition-horn-language", "/狂怒；暴怒", "/reɪdʒ/", "n./v.", 6, 0.6, "Rage writes checks the relationship cashes later.", "暴怒开出的支票由感情买单。", "walk away from rising rage early"),
  v("fury-silent-cold-varieties-too", "/狂怒；激怒", "/ˈfjʊri/", "n.", 7, 0.65, "Fury can whisper and still burn.", "狂怒可以低语却照样灼人。", "vent fury at the gym instead"),
  v("joy-unreasonable-small-moments-collector", "/欢乐；喜悦", "/dʒɔɪ/", "n.", 3, 0.25, "Joy hides in ordinary Tuesdays mostly.", "喜悦多半藏在普通的周二里。", "collect small joys deliberately each day"),
  v("delight-surprise-and-pleasure-twins", "/高兴；乐事", "/dɪˈlaɪt/", "n./v.", 5, 0.45, "Delight needs surprise as co-signer.", "欣喜需要惊喜共同签署。", "delight customers with unexpected notes"),
  v("grief-love-with-nowhere-to-go-definition", "/悲痛；悲伤", "/ɡriːf/", "n.", 6, 0.55, "Grief arrives unannounced in parking lots.", "悲伤不打招呼就在停车场袭来。", "sit with grief instead of fixing it"),
  v("sorrow-deep-quiet-long-river", "/悲哀；懊悔", "/ˈsɑːroʊ/", "n.", 7, 0.6, "Sorrow moves slower than sadness.", "悲恸比忧伤流得更慢。", "share sorrow to halve its weight"),
  v("misery-company-joke-has-truth-inside", "/痛苦；悲惨", "/ˈmɪzəri/", "n.", 6, 0.6, "Misery loves company but company deserves better.", "痛苦爱找伴，但伴值得更好的。", "escape misery with tiny routine changes"),
  v("despair-tunnel-no-light-yet-phase", "/绝望", "/dɪˈsper/", "n.", 7, 0.65, "Despair lies about tomorrow specifically.", "绝望专门谎报明天。", "reach out when despair whispers lies"),
  v("hope-realistic-optimist-toolkit-item", "/希望；期望", "/hoʊp/", "n./v.", 1, 0.1, "Hope is a plan still under construction.", "希望是仍在施工的计划。", "offer hope with concrete next steps"),
  v("optimism-practice-not-personality-type", "/乐观；乐观主义", "/ˈɑːptɪmɪzəm/", "n.", 6, 0.55, "Optimism trains like a muscle group.", "乐观像肌群一样可以训练。", "choose grounded optimism over denial"),
  v("pessimism-risk-manager-gone-rogue", "/悲观；悲观主义", "/ˈpesɪmɪzəm/", "n.", 7, 0.65, "Pessimism protects nothing from rain.", "悲观挡不住任何雨。", "question reflexive pessimism kindly"),
  v("contentment-enough-is-a-number-you-set", "/满足；知足", "/kənˈtentmənt/", "n.", 7, 0.6, "Contentment is budgeting happiness wisely.", "知足是聪明地分配幸福。", "find contentment in finished days"),
  v("gratitude-three-things-before-bed-habit", "/感激；感恩", "/ˈɡrætɪtuːd/", "n.", 5, 0.45, "Gratitude rewrites scarcity into inventory.", "感恩把匮乏改写成库存清单。", "text gratitude before you forget"),
  v("loneliness-crowded-rooms-count-too", "/孤独；寂寞", "/ˈloʊnlinəs/", "n.", 5, 0.45, "Loneliness lies about who would answer.", "孤独谎称没人会接你电话。", "interrupt loneliness with one small message"),
  v("solitude-chosen-alone-versus-lonely", "/独处；独居", "/ˈsɑːlətuːd/", "n.", 7, 0.6, "Solitude recharges what loneliness drains.", "独处充电，孤独耗电。", "schedule weekly solitude without guilt"),
  v("boredom-creativity-uncomfortable-front-door", "/无聊；厌倦", "/ˈbɔːrdəm/", "n.", 4, 0.3, "Boredom is creativity knocking rudely.", "无聊是创造力的粗鲁敲门。", "let boredom sit without feeding it screens"),
  v("curiosity-question-everything-license-plate", "/好奇心；求知欲", "/ˌkjʊriˈɑːsəti/", "n.", 5, 0.4, "Curiosity ages slower than birthdays.", "好奇心比生日老得慢。", "follow curiosity down useful rabbit holes"),
  v("enthusiasm-contagious-energy-budget-item", "/热情；积极性", "/ɪnˈθuːziæzəm/", "n.", 5, 0.45, "Enthusiasm recruits allies cheaper than money.", "热情比金钱更便宜地招募盟友。", "fake enthusiasm until the work hooks you"),
  v("passion-sustainable-fire-check-annually", "/激情；热情", "/ˈpæʃn/", "n.", 4, 0.35, "Passion burns bright; purpose burns long.", "激情烧得亮，使命烧得久。", "pair passion with systems that sustain it"),
  v("apathy-vote-by-not-showing-up-cost", "/冷漠；无动于衷", "/ˈæpəθi/", "n.", 7, 0.65, "Apathy is exhaustion wearing sunglasses indoors.", "冷漠是戴着墨镜的疲惫。", "fight apathy with one tiny action"),
  v("sympathy-n2-card-aisle-greeting-section", "/同情（变体）", "/ˈsɪmpəθi/", "n.", 5, 0.45, "Sympathy cards say what hugs struggle to.", "慰问卡说出拥抱说不出的安慰。", "sign sympathy cards personally always"),
  v("empathetic-listening-without-fixing-reflex", "/有同理心的", "/ˌempəˈθetɪk/", "adj.", 7, 0.65, "Empathetic ears beat quick fixes every time.", "共情的倾听胜过速效方案。", "train empathetic listening in one-on-ones"),
  v("resilient-bend-don't-break-material-test", "/有韧性的；能快速恢复的", "/rɪˈzɪliənt/", "adj.", 7, 0.65, "Resilient people keep spare tomorrows handy.", "坚韧的人随身备着明天。", "raise resilient kids through manageable failures"),
  v("persistent-polite-knock-twenty-times-strategy", "/坚持不懈的；执着的", "/pərˈsɪstənt/", "adj.", 6, 0.55, "Persistent beats talented by showing up daily.", "坚持者靠天天到场击败天才。", "stay persistent through three noes minimum"),
  v("ambitious-five-year-plan-holder-type", "/有雄心的；野心勃勃的", "/æmˈbɪʃəs/", "adj.", 5, 0.45, "Ambitious without rest is just tired.", "没有休息的雄心只是疲惫。", "channel ambitious energy into weekly wins"),
  v("humble-success-doesn't-change-address", "/谦逊的；谦虚的", "/ˈhʌmbl/", "adj.", 5, 0.45, "Humble winners thank the bench players.", "谦逊的赢家感谢替补队员。", "stay humble right after the win"),
  v("arrogant-confidence-minus-competence-formula", "/傲慢的；自大的", "/ˈærəɡənt/", "adj.", 6, 0.55, "Arrogant experts skip the reading.", "傲慢的专家跳过阅读环节。", "avoid arrogant tones in client emails"),
  v("reliable-promises-kept-quietly-track-record", "/可靠的；可信赖的", "/rɪˈlaɪəbl/", "adj.", 4, 0.3, "Reliable people are boring miracles.", "可靠的人是无聊的奇迹。", "hire reliable over brilliant when stakes rise"),
  v("dependable-rain-or-shine-guarantee-type", "/可靠的；靠得住的", "/dɪˈpendəbl/", "adj.", 5, 0.5, "Dependable friends answer before sunrise.", "靠谱的朋友天亮前就会回音。", "be dependable in small things first"),
  v("authentic-no-filter-required-presence", "/真诚的；正宗的", "/ɔːˈθentɪk/", "adj.", 6, 0.55, "Authentic voices crack occasionally on purpose.", "真实的声音偶尔故意沙哑。", "sound authentic by dropping the script"),
  v("sincere-apology-without-but-clause-art", "/诚挚的；真诚的", "/sɪnˈsɪr/", "adj.", 6, 0.5, "Sincere apologies delete the word 'but'.", "真诚的道歉会删掉“但是”。", "keep apologies sincere short and specific"),
];
