import { v } from "@/content/vocab/builder";
import type { VocabRow } from "@/content/vocab/types";

/** Language, discourse & communication skills - Phase 10 chunk-h. */
export const languageDiscourseRows: VocabRow[] = [
  v("vocabulary-size-reading-correlation", "/词汇量；词汇", "/vəˈkæbjəleri/", "n.", 4, 0.3, "Vocabulary grows one conversation at a time.", "词汇量一次长一点对话。", "expand your active vocabulary weekly"),
  v("grammar-rules-made-to-bend-later", "/语法；文法", "/ˈɡræmər/", "n.", 2, 0.2, "Grammar is scaffolding, not the building.", "语法是脚手架，不是大楼。", "review grammar basics before exams"),
  v("pronunciation-drill-minimal-pair-practice", "/发音；读法", "/prəˌnʌnsiˈeɪʃn/", "n.", 5, 0.45, "Pronunciation opens doors spelling never will.", "发音能打开拼写打不开的门。", "shadow native audio for pronunciation gains"),
  v("accent-regional-melody-of-words", "/口音；重音", "/ˈæksent/", "n.", 5, 0.45, "Accents are maps your mouth carries.", "口音是嘴巴随身携带的地图。", "keep your accent; polish your clarity"),
  v("fluency-speed-with-control-balance", "/流利；流畅", "/ˈfluːənsi/", "n.", 6, 0.55, "Fluency is comfort at speed, not just speed.", "流利是带控制的快，不只是快。", "build fluency with timed retellings"),
  v("idiom-literal-trap-for-learners", "/习语；成语", "/ˈɪdiəm/", "n.", 5, 0.5, "Idioms betray dictionaries constantly.", "习语天天背叛词典。", "learn idioms in full conversations only"),
  v("slang-generation-password-refresh-cycle", "/俚语；行话", "/slæŋ/", "n.", 5, 0.5, "Slang expires faster than milk.", "俚语比牛奶过期还快。", "test slang on friends before meetings"),
  v("collocation-natural-word-partnerships", "/词语搭配", "/ˌkɑːləkeɪʃn/", "n.", 7, 0.65, "Collocations make English sound earned.", "地道搭配让英语听起来像母语。", "memorize verbs with their natural collocations"),
  v("synonym-shade-differences-matter-chart", "/同义词", "/ˈsɪnənɪm/", "n.", 6, 0.55, "Synonyms differ by temperature, not just meaning.", "同义词差在温度而非仅字义。", "swap three synonyms in every draft"),
  v("antonym-opposite-pairs-memory-hooks", "/反义词", "/ˈæntənɪm/", "n.", 6, 0.5, "Antonyms anchor words in pairs.", "反义词成对锚定单词。", "quiz antonyms before the vocabulary test"),
  v("literal-exact-word-meaning-mode", "/字面的；逐字的", "/ˈlɪtərəl/", "adj.", 5, 0.45, "Literal translation ships hilarious accidents.", "直译会运来爆笑事故。", "avoid literal renderings of idioms"),
  v("figurative-meaning-between-the-lines-layer", "/比喻的；修辞性的", "/ˈfɪɡjərətɪv/", "adj.", 7, 0.65, "Figurative speech paints what facts can't.", "比喻性语言画出事实画不出的东西。", "read figurative language slowly aloud"),
  v("context-clue-guessing-skill-training", "/上下文；语境", "/ˈkɑːntekst/", "n.", 4, 0.35, "Context rescues half your unknown words.", "语境拯救你一半的生词。", "infer meanings from context before checking"),
  v("nuance-fine-distinction-expert-ear-test", "/细微差别；微妙之处", "/ˈnuːɑːns/", "n.", 7, 0.65, "Nuance separates fluent from native.", "细微差别区分流利与母语。", "appreciate nuance before translating jokes"),
  v("tone-message-emotion-channel-check", "/语气；音调", "/toʊn/", "n.", 4, 0.35, "Email tone dies between keyboards.", "邮件语气死在键盘之间。", "soften tone before sending complaints"),
  v("register-formal-versus-casual-switching", "/语域；语体", "/ˈredʒɪstər/", "n.", 7, 0.75, "Register switching is social judo.", "语体切换是社交柔道。", "match register to every audience"),
  v("formal-written-contract-language-style", "/正式的；礼仪性的", "/ˈfɔːrml/", "adj.", 3, 0.25, "Formal emails still need one warm sentence.", "正式邮件也需要一句暖场。", "keep formal letters under one page"),
  v("casual-friday-language-relaxation-zone", "/随意的；非正式的", "/ˈkæʒuəl/", "adj.", 2, 0.15, "Casual chat builds serious trust.", "随意的闲聊建立认真的信任。", "open meetings with casual check-ins briefly"),
  v("polite-request-vs-demand-phrasing-art", "/有礼貌的；客气的", "/pəˈlaɪt/", "adj.", 2, 0.15, "Polite asks travel farther than demands.", "礼貌的请求走得比命令远。", "phrase polite requests with could-would frames"),
  v("persuasion-ethos-pathos-logos-triangle", "/说服；说服力", "/pərˈsweɪʒn/", "n.", 6, 0.6, "Persuasion starts from their reasons, not yours.", "说服从对方的理由出发。", "study persuasion without becoming sneaky"),
  v("argument-premises-not-shouting-contest", "/论点；争论", "/ˈɑːrɡjumənt/", "n.", 3, 0.3, "Win arguments by losing heat first.", "赢下争论先降温。", "steelman the argument before rebutting it"),
  v("debate-team-rebuttal-timer-discipline", "/辩论；辩论赛", "/dɪˈbeɪt/", "n./v.", 4, 0.35, "Debate rewards preparation over volume.", "辩论奖励准备，不奖励音量。", "join a debate club for quick thinking"),
  v("negotiate-terms-win-win-drafting", "/谈判；协商", "/nɪˈɡoʊʃieɪt/", "v.", 5, 0.5, "Negotiate salaries before enthusiasm expires.", "趁热情未退先谈薪资。","negotiate lease terms every renewal"),
  v("articulate-thoughts-into-clean-sentences-skill", "/清晰表达；发音清楚的", "/ɑːrˈtɪkjuleɪt/", "v./adj.", 7, 0.65, "Articulate ideas in one breath first.", "先用一口气把想法说清。", "practice articulating decisions in writing"),
  v("concise-cut-adjectives-payroll-halving", "/简洁的；简明的", "/kənˈsaɪs/", "adj.", 6, 0.55, "Concise writing respects busy readers.", "简洁的文字尊重忙碌的读者。", "revise drafts until they turn concise"),
  v("eloquent-speeches-quote-worthy-sentences", "/雄辩的；有说服力的", "/ˈeləkwənt/", "adj.", 7, 0.7, "Eloquent speakers edit ruthlessly beforehand.", "雄辩者事先狠心删改。", "borrow structures from eloquent speeches"),
  v("fluent-four-skills-balanced-checklist", "/流利的；流畅的", "/ˈfluːənt/", "adj.", 4, 0.35, "Fluent speakers forgive their own mistakes fast.", "流利者迅速原谅自己的错误。", "become fluent in meeting small talk first"),
  v("bilingual-brain-switching-cost-studies", "/双语的；会说两种语言的", "/ˌbaɪˈlɪŋɡwəl/", "adj./n.", 7, 0.6, "Bilingual brains run two operating systems.", "双语大脑运行两套操作系统。", "raise bilingual kids with one-parent-one-language"),
  v("interpreter-live-translation-pressure-cooker-job", "/口译员", "/ɪnˈtɜːrprɪtər/", "n.", 7, 0.7, "Interpreters translate jokes at their own risk.", "口译员自担风险翻译笑话。", "brief the interpreter on jargon beforehand"),
  v("translator-written-text-specialist-role", "/翻译（笔译）；译者", "/trænzˈleɪtər-n2/", "n.", 6, 0.65, "Translators choose sides: fidelity or flow.", "译者要选边：忠实还是流畅。", "hire translators who live in both cultures"),
  v("paraphrase-same-meaning-new-clothes-skill", "/释义；意译", "/ˈpærəfreɪz/", "v./n.", 7, 0.65, "Paraphrasing proves real understanding.", "会转述才算真懂。", "paraphrase instructions back to confirm"),
  v("summarize-three-sentences-maximum-rule", "/总结；概述", "/ˈsʌməraɪz/", "v.", 4, 0.35, "Summarize meetings while memories steam.", "趁记忆还热着就写会议纪要。", "summarize each chapter in two lines"),
  v("clarify-before-assuming-disaster-prevention", "/澄清；阐明", "/ˈklærəfaɪ/", "v.", 4, 0.3, "Clarify now or renegotiate later.", "现在澄清，免得日后返工。", "clarify ambiguous deadlines in writing"),
  v("emphasize-bold-the-one-number-that-matters", "/强调；着重", "/ˈemfəsaɪz/", "v.", 4, 0.35, "Emphasize one point, bury the rest politely.", "只强调一个重点，其余礼貌收起。", "emphasize benefits over features always"),
  v("rephrase-say-it-three-slower-ways-technique", "/改述；换种说法", "/riːˈfreɪz/", "v.", 6, 0.6, "Rephrasing rescues misunderstood instructions.", "换个说法能救回被误解的指令。", "rephrase questions when faces look puzzled"),
  v("interrupt-politely-bridge-phrases-toolkit", "/插话；打断", "/ˌɪntəˈrʌpt/", "v.", 4, 0.3, "Interrupt with bridges, not bulldozers.", "插话用桥梁，别用推土机。", "interrupt politely with quick acknowledgments"),
  v("hesitate-two-second-buy-time-move", "/犹豫；迟疑", "/ˈhezɪteɪt/", "v.", 4, 0.35, "Hesitate strategically; fillers are fine sometimes.", "战略性停顿，填充词偶尔也无妨。", "hesitate less by preparing openings cold"),
  v("small-talk-weather-elevator-scripts-unlock-doors", "/寒暄；闲聊", "/smɔːl tɔːk/", "n.", 4, 0.3, "Small talk is the handshake before trust.", "寒暄是信任之前的握手。", "prepare three small talk openers daily"),
  v("body-language-crossed-arms-myth-decoded", "/肢体语言", "/ˈbɑːdi ˈlæŋɡwɪdʒ/", "n.", 5, 0.45, "Body language whispers what slides hide.", "肢体语言泄露幻灯片藏不住的事。", "record yourself to review body language"),
  v("eye-contact-confidence-calibration-by-culture-map", "/眼神交流", "/aɪ ˈkɑːntækt/", "n.", 5, 0.4, "Eye contact rules rewrite across borders.", "对视规则跨越国界就要重写。", "practice eye contact in low-stakes chats"),
  v("gesture-hand-talk-free-upgrade-pack", "/手势；姿态", "/ˈdʒestʃər/", "n./v.", 4, 0.35, "Gestures draw pictures words forget to.", "手势画出语言忘记画的图。", "add gestures when presenting numbers"),
  v("silence-strategic-pause-negotiation-weapon", "/沉默；寂静", "/ˈsaɪləns/", "n.", 3, 0.25, "Silence negotiates better than adjectives.", "沉默比形容词更会谈条件。", "hold silence after stating your price"),
  v("feedback-loop-fast-course-correction-culture", "/反馈回路", "/ˈfiːdbæk luːp/", "n.", 6, 0.6, "Fast feedback loops beat annual surprises.", "快速反馈胜过年度惊吓。", "shorten feedback loops within teams"),
];
