import { v } from "@/content/vocab/builder";
import type { VocabRow } from "@/content/vocab/types";

/** Travel abroad & cross-cultural experience - Phase 10 chunk-h. */
export const travelAbroadRows: VocabRow[] = [
  v("itinerary-printed-copy-saves-batteries", "/行程表；旅行计划", "/aɪˈtɪnəreri/", "n.", 6, 0.6, "Loose itineraries find the best alleys.", "松散的行程才能发现最好的小巷。", "share your itinerary with family first"),
  v("layover-city-mini-tour-window", "/中转停留；中途下车", "/ˈleɪoʊvər/", "n.", 7, 0.65, "Ten-hour layovers hide free city tours.", "十小时中转藏着免费城市游。", "book long layovers on purpose"),
  v("jet-lag-eastward-worse-rule-thumb", "/时差反应", "/ˈdʒæt læɡ/", "n.", 6, 0.55, "Jet lag eastward charges double interest.", "向东飞的时差利息翻倍。", "beat jet lag with morning sunlight"),
  v("hostel-dorm-curtain-best-invention", "/青年旅舍", "/ˈhɑːstl/", "n.", 6, 0.6, "Hostels trade privacy for stories.", "青旅用隐私换故事。", "book hostels with private rooms when tired"),
  v("airbnb-host-recommendation-goldmine", "/民宿短租", "/ˌer aɪ en biː diː/", "abbr.", 6, 0.6, "Great Airbnb hosts annotate neighborhood maps by hand.", "好房东会手绘街区地图标注。", "message the airbnb host about early bags"),
  v("souvenir-fridge-magnet-economics-explained", "/纪念品", "/ˌsuːvəˈnɪr/", "n.", 5, 0.45, "Souvenirs shrink memories into carry-ons.", "纪念品把回忆压缩进行李箱。","buy souvenirs after photos, never before"),
  v("currency-conversion-mental-math-market-trick", "/货币兑换；汇兑", "/ˈkɜːrənsi kənˈvɜːrʒn/", "n.", 5, 0.5, "Currency conversion apps beat airport kiosks.", "货币换算应用完胜机场柜台。", "check currency conversion before haggling"),
  v("travel-insurance-read-the-fine-print-lesson", "/旅行保险", "/ˈtrævl ɪnˈʃʊrəns/", "n.", 6, 0.6, "Travel insurance pays for the trip you didn't take.", "旅行保险为没成行的旅程买单。", "compare travel insurance deductibles carefully"),
  v("passport-photo-rules-change-yearly-myths", "/护照照片", "/ˈpæspɔːrt ˈfoʊtoʊ/", "n.", 5, 0.5, "Passport photos forbid smiles officially.", "护照照片官方规定禁止微笑。", "renew passport photos before expiry year"),
  v("boarding-pass-screenshot-backup-strategy", "/登机牌", "/ˈbɔːrdɪŋ pæs/", "n.", 4, 0.4, "Screenshot boarding passes; airport wifi lies.", "截图登机牌，机场WiFi会骗人。", "print backup boarding passes for international legs"),
  v("customs-officer-small-talk-or-silence-choice", "/海关官员；报关", "/ˈkʌstəmz ˈɔːfɪsər/", "n.", 7, 0.7, "Customs officers appreciate honest boring answers.", "海关官员欣赏诚实的无聊回答。", "answer customs officers briefly and truthfully"),
  v("visa-run-border-town-adventures", "/签证续签往返", "/ˈviːzə rʌn/", "n.", 7, 0.75, "Visa runs turn borders into day trips.", "签证跑让边境变成一日游。", "plan visa runs with buffer days"),
  v("expat-community-facebook-group-wisdom", "/旅居海外者", "/eksˈpæt/", "n.", 7, 0.7, "Expats know which doctor speaks English.", "旅居者知道哪位医生会说英语。", "join expat groups before moving abroad"),
  v("culture-shock-week-three-dip-pattern", "/文化冲击", "/ˈkʌltʃər ʃɑːk/", "n.", 7, 0.6, "Culture shock peaks when the novelty invoice arrives.", "文化冲击在新鲜感账单寄到时达到顶峰。", "expect culture shock around week three"),
  v("homesickness-care-package-smell-memory-science", "/思乡；乡愁", "/ˈhoʊmsɪknəs/", "n.", 6, 0.55, "Homesickness smells like grandma's kitchen.", "乡愁闻起来像外婆的厨房。", "schedule calls to soften homesickness evenings"),
  v("language-barrier-charades-championship-level-skills", "/语言障碍", "/ˈlæŋɡwɪdʒ ˈbæriər/", "n.", 5, 0.5, "Language barriers unlock world-class charades.", "语言障碍解锁世界级比划猜词。", "bridge language barriers with translation apps"),
  v("haggle-market-price-negotiation-theater", "/讨价还价；砍价", "/ˈhæɡl/", "v./n.", 7, 0.6, "Haggling is theater where everyone applauds.", "砍价是人人鼓掌的剧场。", "haggle with smiles in bazaar markets"),
  v("tip-etiquette-country-chart-confusion", "/小费礼仪", "/tɪp ˈetɪket/", "n.", 5, 0.5, "Tipping etiquette rewrites at every border.", "小费规矩在每个边境重写。", "research tipping etiquette before arriving"),
  v("street-food-safety-line-length-indicator-theory", "/街头小吃", "/striːt fuːd/", "n.", 5, 0.45, "Street food lines measure trust better than reviews.", "街头小吃排队长度比点评更可信。", "follow students to the best street food"),
  v("landmark-meeting-point-getting-lost-together", "/地标；标志性建筑", "/ˈlændmɑːrk/", "n.", 4, 0.35, "Landmarks anchor every lost wanderer home.", "地标指引每个迷路的漫游者回家。", "meet under the famous landmark clock"),
  v("off-the-beaten-path-tourist-free-zones", "/人迹罕至的；偏僻的", "/ɔːf ðə ˈbiːtn pæθ/", "adj.", 7, 0.65, "Off-path trails reward early buses.", "冷门路线奖励早班车乘客。", "venture off the beaten path with locals"),
  v("tourist-trap-menu-with-photos-warning-sign", "/游客陷阱", "/ˈtʊrɪst træp/", "n.", 7, 0.6, "Photo menus mark tourist traps precisely.", "带照片的菜单精准标记游客陷阱。", "escape tourist traps by walking two streets over"),
  v("day-trip-packed-morning-itinerary-art", "/一日游", "/deɪ trɪp/", "n.", 5, 0.45, "Day trips fit whole vacations into weekends.", "一日游把整个假期塞进周末。", "plan a coastal day trip this month"),
  v("road-trip-playlist-democracy-principles", "/公路旅行", "/roʊd trɪp/", "n.", 3, 0.3, "Road trips test friendships at mile two hundred.", "公路旅行在第二百英里考验友谊。", "rotate road trip DJs hourly fairly"),
  v("backpack-packing-list-editing-discipline", "/背包；打包", "/ˈbækpæk/", "n./v.", 4, 0.35, "Backpack lighter; regret less at stairs.", "背包轻一点，爬楼少后悔。", "weigh your backpack before budget flights"),
  v("suitcase-overweight-checkin-counter-negotiation", "/行李箱", "/ˈsuːtkeɪs/", "n.", 4, 0.35, "Suitcases gain souvenirs and lose wheels.", "行李箱收获纪念品，牺牲轮子。", "buy expandable suitcases for market days"),
  v("carry-on-liquids-rule-three-one-one-formula", "/随身行李", "/ˈkæri ɑːn/", "n./adj.", 5, 0.45, "Carry-on packing is tetris with consequences.", "随身行李装箱是有后果的俄罗斯方块。", "master carry-on-only travel techniques"),
  v("lost-luggage-tracking-tag-technology-era", "/丢失的行李", "/lɔːst ˈlʌɡɪdʒ/", "n.", 7, 0.7, "Lost luggage reunions deserve confetti.", "失而复得的行李值得撒花庆祝。", "photograph luggage contents against lost luggage odds"),
  v("delay-compensation-eu261-know-your-rights", "/延误；推迟", "/dɪˈleɪ/", "n./v.", 4, 0.35, "Delays pay out if you keep receipts.", "留好票据，延误也能索赔。", "claim delay compensation within deadlines"),
  v("cancellation-policy-free-window-deadlines", "/取消；撤销", "/ˌkænsəˈleɪʃn/", "n.", 6, 0.6, "Cancellation windows close while you deliberate.", "你犹豫时取消窗口正在关闭。", "note cancellation policies at booking time"),
  v("reservation-name-mismatch-middle-initial-chaos", "/预订；预约", "/ˌrezərˈveɪʃn/", "n.", 5, 0.45, "Reservations under nicknames meet strict hosts.", "用昵称订位会遇到严格的主人家。", "confirm reservations twenty-four hours ahead"),
  v("check-out-noon-sharp-housekeeping-schedule", "/退房；结账离开", "/tʃek aʊt/", "phr.", 2, 0.2, "Checkout at noon; adventures until midnight.", "中午退房，玩到半夜。", "request late checkout politely at breakfast"),
  v("exchange-student-semester-abroad-life-changing", "/交换生", "/ɪksˈtʃeɪndʒ ˈstuːdnt/", "n.", 6, 0.6, "Exchange students age one year per semester, emotionally.", "交换生一学期情感上老一岁。", "host an exchange student for a semester"),
  v("study-abroad-application-essay-all-nighters", "/留学；海外学习", "/ˈstʌdi əˈbrɔːd/", "phr.", 5, 0.5, "Study abroad semesters compress decades into months.", "留学一学期浓缩十年人生。", "apply for study abroad funding early"),
  v("gap-year-volunteer-teaching-stories", "/间隔年", "/ɡæp jɪr/", "n.", 6, 0.6, "Gap years teach more than gap semesters admit.", "间隔年教的比成绩单承认的多。", "plan a purposeful gap year itinerary"),
  v("work-visa-sponsorship-job-hunt-reality", "/工作签证", "/wɜːrk ˈviːzə/", "n.", 7, 0.7, "Work visas gate careers more than résumés do.", "工作签证比简历更能决定职业走向。", "target employers offering work visa sponsorship"),
  v("green-card-permanent-resident-status-journey", "/绿卡", "/ˈɡriːn kɑːrd/", "n.", 6, 0.65, "Green card timelines test marriages and patience equally.", "绿卡时间线同等考验婚姻与耐心。", "track green card processing times monthly"),
  v("dual-citizenship-passport-two-advantages", "/双重国籍", "/ˌduːəl ˈsɪtɪzənʃɪp/", "n.", 7, 0.75, "Dual citizenship doubles holiday dinners.", "双重国籍让节日晚餐翻倍热闹。", "research dual citizenship rules by country"),
  v("remittance-money-home-transfer-fees-comparison", "/汇款；汇款额", "/rɪˈmɪtns/", "n.", 7, 0.8, "Remittances fund villages better than aid does.", "侨汇对乡村的贡献超过援助。", "compare remittance fees across providers yearly"),
];
