import { v } from "@/content/vocab/builder";
import type { VocabRow } from "@/content/vocab/types";

/** Modern daily life & digital living - Phase 10 chunk-h. */
export const modernLifeRows: VocabRow[] = [
  v("notification-badge-red-dot-anxiety-source", "/通知；提示", "/ˌnoʊtɪfɪˈkeɪʃn/", "n.", 5, 0.4, "Notifications schedule your day if you let them.", "放任不管的话，通知会替你安排一天。", "mute nonessential notifications during work"),
  v("screen-time-weekly-report-guilt-math", "/屏幕使用时间", "/ˈskriːn taɪm/", "n.", 6, 0.55, "Screen time reports read like horror novels.", "屏幕时间报告像恐怖小说。", "cap evening screen time at one hour"),
  v("do-not-disturb-mode-sacred-evening-hours", "/勿扰模式", "/duː nɑːt dɪˈstɜːrb/", "phr.", 6, 0.6, "Do-not-disturb is the new velvet rope.", "勿扰模式是新时代的天鹅绒围绳。", "schedule do-not-disturb windows nightly"),
  v("password-manager-one-master-memory-test", "/密码管理器", "/ˈpæswɜːrd ˈmænɪdʒər/", "n.", 7, 0.65, "Password managers end sticky-note archaeology.", "密码管理器终结便利贴考古学。", "migrate logins into a password manager"),
  v("two-factor-authentication-extra-step-peace", "/双因素认证", "/ˌtuː ˈfæktər ɔːˌθentɪˈkeɪʃn/", "n.", 7, 0.7, "Two-factor login blocks most takeover attempts.", "双重验证挡住大多数盗号。", "enable two-factor on email accounts first"),
  v("software-update-restart-later-forever-button", "/软件更新", "/ˈsɔːftwer ʌpˈdeɪt/", "n.", 5, 0.45, "Software updates always arrive mid-presentation.", "软件更新总在演讲中途弹出。","schedule software updates for lunch breaks"),
  v("backup-cloud-vs-external-drive-debate", "/备份", "/ˈbækʌp/", "n./v.", 5, 0.5, "Backups turn disasters into inconveniences.", "备份把灾难降级为麻烦。", "test backups by restoring one file monthly"),
  v("cloud-storage-free-tier-limits-explained", "/云存储；云端", "/klaʊd ˈstɔːrɪdʒ/", "n.", 6, 0.6, "Cloud storage rents you your own photos.", "云存储把你的照片租回给你。", "organize cloud storage folders quarterly"),
  v("wifi-password-cafe-small-talk-starter", "/无线网络", "/ˈwaɪfaɪ/", "n.", 3, 0.25, "Wifi passwords are modern housewarming gifts.", "WiFi密码是现代的乔迁礼。", "ask for the wifi password upon sitting down"),
  v("hotspot-phone-tethering-battery-tax", "/热点；（经济、政治）热点", "/ˈhɑːtspɑːt/", "n.", 7, 0.65, "Phone hotspots rescue deadlines in taxis.", "手机热点在出租车里抢救截止日期。", "tether the laptop to your phone hotspot"),
  v("stream-buffer-spinning-wheel-rage-cycle", "/缓冲；缓冲存储", "/ˈbʌfər/", "n./v.", 7, 0.65, "Buffering ruins climaxes in films and meetings alike.", "缓冲毁了电影和会议的高潮。", "download shows before buffering country roads"),
  v("download-offline-playlist-commute-strategy", "/下载", "/ˈdaʊnloʊd/", "v./n.", 3, 0.25, "Download podcasts before mountain drives.", "进山之前先下载播客。", "limit app downloads to trusted stores"),
  v("upload-speed-vs-download-asymmetry-explained", "/上传", "/ˌʌpˈloʊd/", "v./n.", 3, 0.3, "Upload speeds betray video calls first.", "上传速度最先出卖视频通话。", "pause cloud uploads before client calls"),
  v("attachment-forgot-to-attach-classic-email-crime", "/附件", "/əˈtætʃmənt/", "n.", 5, 0.5, "Forgotten attachments define email comedy.", "忘了附件是邮件喜剧的经典桥段。", "compress attachments before sending to clients"),
  v("spam-folder-legitimate-email-graveyard", "/垃圾邮件", "/spæm/", "n.", 5, 0.45, "Spam filters eat job offers weekly.", "垃圾邮件过滤器每周吞掉录用通知。", "whitelist important senders past spam filters"),
  v("unsubscribe-newsletter-purge-sunday-ritual", "/退订；取消订阅", "/ˌʌnsəbˈskraɪb/", "v.", 6, 0.55, "Unsubscribe ruthlessly; inbox peace compounds.", "狠心退订，收件箱清净复利增长。", "unsubscribe from five lists every Sunday"),
  v("inbox-zero-myth-or-method-debate", "/收件箱", "/ˈɪnbɑːks/", "n.", 5, 0.45, "Inbox zero lasts exactly forty-five minutes.", "收件箱清零只能维持四十五分钟。", "process inbox twice daily maximum"),
  v("emoji-tone-rescue-mission-in-texts", "/表情符号；表情包", "/ɪˈmoʊdʒi/", "n.", 5, 0.45, "Emoji rescue flat sentences from sounding cold.", "表情符号拯救干瘪句子免于冷漠。", "add emoji sparingly in professional chats"),
  v("meme-culture-inside-joke-globalization", "/梗图；模因", "/miːm/", "n.", 6, 0.55, "Memes translate faster than embassies.", "梗图的传播比大使馆还快。", "explain the meme to grandma gently"),
  v("viral-trend-participation-window-48-hours-max", "/疯传；走红", "/ˈvaɪrəl/", "adj.", 6, 0.55, "Viral moments expire faster than milk.", "爆红保质期比牛奶还短。", "ride viral trends while they're warm"),
  v("influencer-fatigue-authenticity-premium-era", "/网红（同 influencer 变体）", "/ˈɪnfluənsər/", "n.", 7, 0.6, "Influencer ads work until they smell like ads.", "网红广告一露出广告味就失效。", "trust peer reviews over influencer hype"),
  v("dating-app-profile-photo-selection-science", "/交友应用", "/ˈdeɪtɪŋ æp/", "n.", 6, 0.6, "Dating apps turned chemistry into keywords.", "交友应用把化学反应变成关键词。", "rewrite dating app bios every season"),
  v("ghost-read-no-reply-message-etiquette-debate", "/已读不回（网络用语）", "/ɡoʊst/", "n./v.", 6, 0.55, "Ghosting saves minutes and costs friendships.", "玩消失省几分钟，赔上交情。", "avoid ghosting; send one honest sentence instead"),
  v("zoom-fatigue-camera-on-meetings-backlash", "/视频会议疲劳", "/zuːm ˈfætiːɡ/", "n.", 7, 0.65, "Video-call fatigue peaked with pants-optional policies.", "视频会议疲劳在不强制穿裤时代达到顶峰。", "schedule camera-off meetings between heavy ones"),
  v("remote-team-time-zone-empathy-rotation", "/远程团队", "/rɪˈmoʊt tiːm/", "n.", 7, 0.65, "Remote teams rotate meeting pain fairly.", "远程团队轮流承担开会痛苦。", "document decisions for remote teammates daily"),
  v("freelance-platform-gig-economy-rating-pressure", "/自由职业平台", "/ˈfriːlæns plætfɔːrm/", "n.", 7, 0.7, "Freelance platforms rate humans like restaurants.", "自由职业平台像评餐厅一样给人打分。", "diversify freelance platforms beyond one marketplace"),
  v("smart-home-speaker-listening-conspiracy-jokes", "/智能家居", "/smɑːrt hoʊm/", "n.", 6, 0.6, "Smart homes obey voices and ignore accents equally.", "智能语音对所有口音一视同仁地装傻。", "rename smart home devices clearly for guests"),
  v("electric-car-range-anxiety-cure-map-apps", "/电动汽车", "/ɪˈlektrɪk kɑːr/", "n.", 5, 0.45, "Electric cars silence gas station small talk.", "电动车终结了加油站的闲聊。", "charge electric cars overnight like phones"),
  v("drone-delivery-future-arrived-early-package", "/无人机", "/droʊn/", "n.", 6, 0.55, "Drones deliver burritos and invade privacy simultaneously.", "无人机同时送来卷饼和隐私焦虑。", "register drone flights before takeoff legally"),
  v("e-signature-document-workflow-paperless-milestone", "/电子签名", "/ˈiː ˌsɪɡnətʃər/", "n.", 7, 0.65, "E-signatures ended printer-divorce statistics forever.", "电子签名终结了打印机引发的婚姻危机。", "collect e-signatures before lease deadlines"),
  v("paperless-office-promise-vs-printer-reality", "/无纸化的", "/ˈpeɪpərləs/", "adj.", 7, 0.6, "Paperless offices still own three printers each.", "无纸办公室人均仍有三台打印机。", "go paperless with statements this quarter"),
  v("digital-detox-weekend-cabin-challenge", "/数字排毒", "/ˈdɪdʒɪtl ˈdiːtɑːks/", "n.", 7, 0.65, "Digital detoxes reveal how loud silence isn't.", "数字排毒让人发现寂静其实不吵。", "try a Sunday digital detox monthly"),
  v("focus-mode-app-blocker-willpower-outsourcing", "/专注模式", "/ˈfoʊkəs moʊd/", "n.", 7, 0.65, "Focus modes beat willpower nine days out of ten.", "专注模式十次里赢九次意志力。", "activate focus mode before writing sessions"),
  v("algorithmic-feed-curated-reality-bubble-warning", "/算法推荐流", "/ˌælɡəˈrɪðmɪk fiːd/", "n.", 7, 0.75, "Algorithmic feeds serve comfort, not truth.", "算法投喂舒适，不投喂真相。", "reset algorithmic feeds by following new topics"),
  v("privacy-policy-scroll-past-reflex-critique", "/隐私政策", "/ˈpraɪvəsi ˈpɑːləsi/", "n.", 7, 0.7, "Privacy policies count on your scrolling thumb.", "隐私政策赌你的拇指不停下滑。", "skim privacy policies for data-sharing clauses"),
  v("terms-of-service-nobody-reads-legally-binding", "/服务条款", "/ˈtɜːrmz əv ˈsɜːrvɪs/", "n.", 7, 0.75, "Terms of service hide arbitration in paragraph forty.", "服务条款把仲裁条款藏在第四十段。", "review terms of service for auto-renewal traps"),
  v("subscription-economy-monthly-death-by-a-thousand-cuts", "/订阅制经济", "/səbˈskrɪpʃn ɪˈkɑːnəmi/", "n.", 7, 0.7, "Subscriptions leak money one trial at a time.", "订阅费一次一次试用地漏水。", "audit subscriptions quarterly and cancel ruthlessly"),
  v("cashless-society-card-only-restaurant-debates", "/无现金社会", "/ˈkæʃləs səˈsaɪəti/", "n.", 7, 0.7, "Cashless cafes strand grandpa's five-dollar bill.", "无现金咖啡馆难住爷爷的五美元纸币。", "carry backup cash for cashless surprises"),
  v("qr-code-menu-flashlight-restaurant-adventures", "/二维码", "/ˌkjuː ɑːr koʊd/", "n.", 5, 0.5, "QR menus die precisely under dim restaurant lights.", "二维码菜单专挑昏暗灯光下罢工。", "save QR codes as screenshots when possible"),
  v("contactless-payment-tap-limit-awkward-second-tap", "/非接触支付", "/ˈkɑːntæktləs ˈpeɪmənt/", "n.", 7, 0.65, "Contactless taps fail loudest behind long lines.", "非接触支付专在长队前失灵出声。", "set contactless payment limits deliberately"),
  v("buy-now-pay-later-installment-app-traps", "/先买后付", "/baɪ naʊ peɪ ˈleɪtər/", "phr.", 7, 0.7, "Buy-now-pay-later splits wallets and futures.", "先买后付劈开钱包也劈开未来。", "skip buy-now-pay-later for wants entirely"),
  v("side-hustle-evening-second-shift-economy", "/副业；兼职", "/saɪd ˈhʌsl/", "n.", 7, 0.65, "Side hustles moonlight until they don't have to.", "副业打工打到不必打工为止。", "grow side hustles without burning evenings completely"),
  v("passive-income-dream-vs-dividend-reality-check", "/被动收入", "/ˈpæsɪv ˈɪnkʌm/", "n.", 7, 0.7, "Passive income starts painfully active.", "被动收入起步时极其主动。", "build passive income streams slowly and honestly"),
];
