import { v } from "@/content/vocab/builder";
import type { VocabRow } from "@/content/vocab/types";

/** Idioms, expressions & natural phrases - Phase 10 chunk-h. */
export const idiomsExpressionsRows: VocabRow[] = [
  v("piece-of-cake-easy-task-idiom", "/小菜一碟（习语）", "/piːs əv keɪk/", "idi.", 3, 0.2, "The interview was a piece of cake.", "那场面试就是小菜一碟。", "call it a piece of cake afterwards"),
  v("under-the-weather-slightly-ill-idiom", "/有点不舒服（习语）", "/ˈʌndər ðə ˈweðər/", "idi.", 4, 0.25, "She's under the weather, so we rescheduled.", "她有点不舒服，所以我们改期了。", "feel under the weather since Monday"),
  v("break-the-ice-first-conversation-idiom", "/打破僵局（习语）", "/breɪk ði aɪs/", "idi.", 4, 0.25, "Bad jokes break the ice efficiently.", "冷笑话高效破冰。", "break the ice with a quick poll"),
  v("hit-the-nail-on-the-head-exactly-right-idiom", "/一针见血（习语）", "/hɪt ðə neɪl ɑːn ðə hed/", "idi.", 5, 0.35, "Your critique hit the nail on the head.", "你的点评一针见血。", "admit someone hit the nail on the head"),
  v("cost-an-arm-and-a-leg-expensive-idiom", "/贵得要命（习语）", "/kɔːst ən ɑːrm ənd ə leɡ/", "idi.", 4, 0.3, "Downtown parking costs an arm and a leg.", "市中心停车贵得要命。", "avoid repairs that cost an arm and a leg"),
  v("once-in-a-blue-moon-rarely-idiom", "/千载难逢；极少（习语）", "/wʌns ɪn ə bluː muːn/", "idi.", 4, 0.3, "We see each other once in a blue moon now.", "我们如今难得见一次面。", "clean the garage once in a blue moon"),
  v("spill-the-beans-reveal-secret-idiom", "/说漏嘴；泄密（习语）", "/spɪl ðə biːnz/", "idi.", 5, 0.3, "Grandma spilled the beans about the party.", "外婆把派对的事说漏了嘴。", "promise not to spill the beans early"),
  v("bite-the-bullet-face-it-idiom", "/硬着头皮上（习语）", "/baɪt ðə ˈbʊlɪt/", "idi.", 5, 0.35, "Bite the bullet and call the dentist.", "咬紧牙关给牙医打电话吧。", "bite the bullet before tax season"),
  v("cut-corners-skip-steps-warning-idiom", "/偷工减料（习语）", "/kʌt ˈkɔːrnərz/", "idi.", 6, 0.35, "Cut corners on paint and pay twice.", "油漆上偷工减料就得花两次钱。", "never cut corners on safety checks"),
  v("on-the-fence-undecided-idiom", "/犹豫不决（习语）", "/ɑːn ðə fens/", "idi.", 4, 0.25, "I'm still on the fence about relocating.", "搬不搬家我还在犹豫。", "sit on the fence until Friday's demo"),
  v("beat-around-the-bush-avoid-topic-idiom", "/拐弯抹角（习语）", "/biːt əˈraʊnd ðə bʊʃ/", "idi.", 5, 0.3, "Stop beating around the bush and ask her.", "别拐弯抹角了，直接问她。", "quit beating around the bush in reviews"),
  v("barking-up-the-wrong-tree-wrong-target-idiom", "/找错对象（习语）", "/ˈbɑːrkɪŋ ʌp ðə rɔːŋ triː/", "idi.", 6, 0.35, "Blaming IT is barking up the wrong tree.", "怪IT部门是怪错了人。", "realize you're barking up the wrong tree quickly"),
  v("burn-the-midnight-oil-work-late-idiom", "/开夜车；熬夜苦干（习语）", "/bɜːrn ðə ˈmɪdnaɪt ɔɪl/", "idi.", 5, 0.3, "Students burn the midnight oil before finals.", "学生期末前挑灯夜战。", "burn less midnight oil with better planning"),
  v("throw-in-the-towel-give-up-idiom", "/认输；放弃（习语）", "/θroʊ ɪn ðə ˈtaʊəl/", "idi.", 5, 0.3, "Don't throw in the towel at chapter three.", "别在第三章就放弃。", "refuse to throw in the towel yet"),
  v("back-to-square-one-start-over-idiom", "/回到原点（习语）", "/bæk tə skwer wʌn/", "idi.", 5, 0.3, "The appeal sent us back to square one.", "上诉把我们打回原点。", "land back at square one after the redesign"),
  v("read-between-the-lines-hidden-meaning-idiom", "/读出言外之意（习语）", "/riːd bɪˈtwiːn ðə laɪnz/", "idi.", 5, 0.35, "Read between the lines of polite rejections.", "读懂礼貌拒绝背后的意思。", "learn to read between the lines diplomatically"),
  v("the-ball-is-in-your-court-decision-yours-idiom", "/该你决定了（习语）", "/ðə bɔːl ɪz ɪn jʊr kɔːrt/", "idi.", 6, 0.35, "The ball is in your court now, boss.", "老板，现在该您拍板了。", "leave the ball in their court politely"),
  v("get-the-ball-rolling-start-momentum-idiom", "/让事情运转起来（习语）", "/ɡet ðə bɔːl ˈroʊlɪŋ/", "idi.", 5, 0.3, "Coffee got the meeting ball rolling.", "咖啡让会议滚动起来。", "get the ball rolling with introductions"),
  v("let-sleeping-dogs-lie-dont-revisit-idiom", "/别惹是生非（习语）", "/let ˈspiːpɪŋ dɔːgz laɪ/", "idi.", 7, 0.4, "Let sleeping dogs lie about last year's audit.", "去年的审计就别再提了。", "advise letting sleeping dogs lie carefully"),
  v("add-insult-to-injury-make-it-worse-idiom", "/雪上加霜（习语）", "/æd ɪnˈsʌlt tu ˈɪndʒəri/", "idi.", 6, 0.35, "To add insult to injury, they billed shipping.", "雪上加霜的是他们还收运费。", "avoid adding insult to injury publicly"),
  v("against-all-odds-unexpected-success-phrase", "/尽管困难重重", "/əˈɡenst ɔːl ɑːdz/", "phr.", 6, 0.4, "Against all odds, the bakery survived year one.", "尽管困难重重，面包店熬过了第一年。", "win against all odds together"),
  v("better-late-than-never-consolation-phrase", "/迟做总比不做好", "/ˈbetər leɪ ðæn ˈnevər/", "phr.", 3, 0.2, "Your apology arrived—better late than never.", "你的道歉来了——迟到总比不到好。", "mutter better late than never while waiting"),
  v("easier-said-than-done-practical-gap-phrase", "/说来容易做来难", "/ˈiːziər sed ðæn dʌn/", "phr.", 4, 0.25, "Sleep more? Easier said than done.", "多睡觉？说来容易做来难。", "concede it's easier said than done honestly"),
  v("so-far-so-good-progress-check-phrase", "/到目前为止一切顺利", "/soʊ fɑːr soʊ ɡʊd/", "phr.", 4, 0.2, "Day two of the diet: so far so good.", "节食第二天：目前为止还好。", "report so far so good during check-ins"),
  v("no-pain-no-gain-effort-motto-phrase", "/一分耕耘一分收获", "/noʊ peɪn noʊ ɡeɪn/", "phr.", 4, 0.25, "No pain no gain applies to coding too.", "编码同样是不劳无获。", "joke no pain no gain at the gym"),
  v("practice-makes-perfect-drill-encouragement-phrase", "/熟能生巧", "/ˈpræktɪs meɪks ˈpɜːrfɪkt/", "phr.", 3, 0.2, "Practice makes perfect, said every piano teacher ever.", "每位钢琴老师都说熟能生巧。", "chant practice makes perfect through drills"),
  v("time-flies-enjoy-it-observation", "/时光飞逝", "/taɪm flaɪz/", "phr.", 3, 0.15, "Time flies when spreadsheets fight back.", "表格反击时时间飞逝。", "sigh time flies at every reunion"),
  v("money-doesnt-grow-on-trees-budget-lecture-phrase", "/钱不是大风刮来的", "/ˈmʌni doʊznt ɡroʊ ɑːn triːz/", "phr.", 4, 0.25, "Money doesn't grow on trees, said dad about heating.", "关于暖气，爸爸说钱不是大风刮来的。", "quote money doesn't grow on trees gently"),
  v("actions-speak-louder-than-words-trust-phrase", "/行动胜于言辞", "/ˈækʃənz spiːk ˈlaʊdər ðæn wɜːrdz/", "phr.", 5, 0.3, "Actions speak louder than words; show up weekly.", "行动胜于言辞，每周都到场吧。", "believe actions speak louder than words finally"),
  v("two-heads-are-better-than-one-teamwork-phrase", "/三个臭皮匠顶个诸葛亮", "/tuː hedz ɑːr ˈbetər ðən wʌn/", "phr.", 5, 0.3, "Two heads are better than one on bug hunts.", "抓虫子时人多智广。", "pair up because two heads beat one"),
  v("when-in-rome-local-custom-advice", "/入乡随俗", "/wen ɪn roʊm/", "phr.", 5, 0.3, "When in Rome, eat dinner at nine like locals.", "入乡随俗，像当地人一样九点吃晚饭。", "follow when-in-rome logic abroad"),
  v("the-last-straw-final-breaking-point-idiom", "/压垮骆驼的最后一根稻草", "/ðə læst strɔː/", "idi.", 6, 0.35, "Cold coffee was the last straw that Monday.", "那个周一，凉咖啡成了最后一根稻草。", "name the last straw calmly in meetings"),
  v("rain-check-postpone-politely-idiom", "/改天再约", "/ˈreɪn tʃek/", "idi.", 5, 0.3, "Take a rain check on Friday's dinner?", "周五的晚餐改天行吗？", "offer a rain check without guilt"),
  v("under-the-table-officially-unofficial-payments", "/私下的；偷偷摸摸的", "/ˈʌndər ðə ˈteɪbl/", "idi.", 7, 0.45, "Some deals happen under the table; ours won't.", "有的交易私下进行，我们不搞这套。", "refuse payments under the table firmly"),
  v("by-the-way-conversation-detour-marker", "/顺便说一句", "/baɪ ðə weɪ/", "phr.", 2, 0.1, "By the way, the deadline moved to Tuesday.", "对了，截止日期挪到周二了。", "drop by-the-way updates casually"),
  v("as-a-matter-of-fact-correction-opener", "/事实上；其实", "/æz ə ˈmætər əv fækt/", "phr.", 4, 0.25, "As a matter of fact, I finished it yesterday.", "其实我昨天就做完了。", "open corrections with as-a-matter-of-fact softly"),
  v("to-be-honest-confession-framing-phrase", "/说实话", "/tə bi ˈɑːnɪst/", "phr.", 3, 0.15, "To be honest, I skipped the appendix too.", "说实话，附录我也跳过了。", "start feedback with to-be-honest sparingly"),
  v("in-the-long-run-perspective-shifter-phrase", "/从长远来看", "/ɪn ðə lɔːŋ rʌn/", "phr.", 4, 0.25, "In the long run, sleep beats caffeine.", "长远看，睡眠胜过咖啡因。", "justify costs by the long run savings"),
  v("at-the-end-of-the-day-summary-phrase", "/说到底；归根结底", "/æt ði end əv ðə deɪ/", "phr.", 5, 0.25, "At the end of the day, users just want speed.", "说到底用户只想要快。", "overuse at-the-end-of-the-day in meetings famously"),
  v("on-the-same-page-alignment-confirmation-idiom", "/达成一致；想法相同", "/ɑːn ðə seɪm peɪdʒ/", "idi.", 5, 0.3, "Let's confirm everyone is on the same page.", "确认一下大家想法一致。", "check the team stays on the same page weekly"),
  v("think-outside-the-box-creativity-cliche", "/跳出固有思维", "/θɪŋk ˌaʊtsaɪd ðə bɑːks/", "idi.", 6, 0.35, "Think outside the box, then check the box budget.", "先跳出框框想，再看看预算框框。", "brainstorm outside the box quarterly anyway"),
  v("raise-the-bar-set-higher-standard-idiom", "/提高标准", "/reɪz ðə bɑːr/", "idi.", 5, 0.3, "Her exit raised the bar for everyone left.", "她的离开提高了留下的每个人的标准。", "raise the bar without burning people out"),
  v("back-to-the-drawing-board-redesign-time", "/重新开始设计", "/bæk tə ðə ˈdrɔːɪŋ bɔːrd/", "idi.", 6, 0.35, "Prototype failed; back to the drawing board.", "原型失败，从头再来。", "head back to the drawing board without drama"),
  v("light-at-the-end-of-the-tunnel-hope-idiom", "/隧道尽头的光亮；曙光", "/laɪt æt ði end əv ðə ˈtʌnl/", "idi.", 6, 0.35, "Finals end Friday—there's light at the end of the tunnel.", "周五期末结束——隧道尽头有光了。", "spot light at the end of the tunnel eventually"),
];
