import { v } from "@/content/vocab/builder";
import type { VocabRow } from "@/content/vocab/types";

/** Technology, AI & digital tools - Phase 10 chunk-h. */
export const techDigitalRows: VocabRow[] = [
  v("artificial-intelligence-everyday-definition-shift", "/人工智能", "/ˌɑːrtɪˈfɪʃl ɪnˈtelɪdʒəns/", "n.", 5, 0.45, "Artificial intelligence drafts emails and still miscounts r's.", "人工智能起草邮件却还是数不清r。", "adopt artificial intelligence tools thoughtfully"),
  v("machine-learning-patterns-without-rules-explained", "/机器学习", "/məˈʃiːn ˈlɜːrnɪŋ/", "n.", 7, 0.65, "Machine learning finds patterns humans never labeled.", "机器学习发现人类从未标注的模式。", "train machine learning models on clean data"),
  v("neural-network-brain-inspired-layers-metaphor", "/神经网络", "/ˈnʊrəl ˈnetwɜːrk/", "n.", 7, 0.75, "Neural networks learn by adjusting weights quietly.", "神经网络靠悄悄调权重来学习。", "visualize neural network layers for beginners"),
  v("chatbot-support-first-line-frustration-or-delight", "/聊天机器人", "/ˈtʃæt bɑːt/", "n.", 6, 0.6, "Chatbots answer at 3 a.m. without sighing audibly.", "聊天机器人凌晨三点回答且听不见叹气。", "escalate chatbot conversations to humans quickly"),
  v("algorithm-bias-training-data-inheritance-problem", "/算法偏见", "/ˈælɡərɪðəm ˈbaɪəs/", "n.", 7, 0.75, "Algorithmic bias inherits history's paperwork.", "算法偏见继承了历史的旧账。", "audit algorithm bias before deployment publicly"),
  v("data-privacy-consent-checkbox-fatigue-studies", "/数据隐私", "/ˈdeɪtə ˈpraɪvəsi/", "n.", 7, 0.65, "Data privacy dies one checkbox at a time.", "数据隐私死于一个又一个勾选框。", "minimize data collection to protect privacy"),
  v("encryption-end-to-end-meaning-demystified-simply", "/加密", "/ɪnˈkrɪpʃn/", "n.", 7, 0.7, "Encryption scrambles letters until only keys unscramble them.", "加密把字母打乱，只有钥匙能复原。", "enable encryption on every backup drive"),
  v("hacker-white-hat-vs-black-hat-taxonomy", "/黑客；热心改造者", "/ˈhækər/", "n.", 6, 0.6, "White-hat hackers break in so others can't.", "白帽黑客先行闯入，坏人就进不来。", "hire ethical hackers for annual testing"),
  v("phishing-email-red-flags-checklist-training", "/网络钓鱼", "/ˈfɪʃɪŋ/", "n.", 7, 0.6, "Phishing emails flatter you before robbing you.", "钓鱼邮件先恭维后抢劫。", "report phishing attempts to IT immediately"),
  v("ransomware-hospital-nightmare-headlines-explained", "/勒索软件", "/ˈrænsəmwer/", "n.", 7, 0.75, "Ransomware locks hospitals and hearts alike.", "勒索软件同时锁住医院与人心。", "back up offline against ransomware waves"),
  v("firewall-network-bouncer-job-description", "/防火墙", "/ˈfaɪərwɔːl/", "n.", 6, 0.6, "Firewalls bounce troublemakers politely but firmly.", "防火墙礼貌而坚定地挡下捣乱者。", "configure firewall rules least-privilege style"),
  v("malware-symptoms-computer-coughing-analogies", "/恶意软件", "/ˈmælmwer/", "n.", 7, 0.65, "Malware spreads like rumors through shared drives.", "恶意软件像流言一样在共享盘传播。", "scan downloads for malware automatically"),
  v("software-bug-first-moth-literal-history-fact", "/程序错误；虫子", "/bʌɡ/", "n.", 3, 0.25, "The first computer bug was literally a moth.", "第一个程序错误真的是一只飞蛾。", "reproduce the bug before reporting it"),
  v("debugging-print-statement-to-breakpoint-evolution", "/调试", "/diːˈbʌɡɪŋ/", "n./v.", 7, 0.65, "Debugging is detective work with worse lighting.", "调试是灯光更差的侦探工作。", "log variables early while debugging late nights"),
  v("open-source-community-governance-gift-economy", "/开源（软件）", "/ˌoʊpən ˈsɔːrs/", "adj./n.", 7, 0.65, "Open source runs the internet unpaid and proud.", "开源软件无偿而骄傲地驱动互联网。", "contribute open source docs as a start"),
  v("user-interface-design-affordances-subtle-art", "/用户界面", "/ˈjuːzər ˈɪntərfeɪs/", "n.", 7, 0.65, "Good user interfaces whisper where buttons are.", "好的界面轻声告诉你按钮在哪。", "test user interfaces with five real users"),
  v("user-experience-frustration-metrics-map-journeys", "/用户体验", "/ˌjuːzər ɪkˈspɪriəns/", "n.", 7, 0.65, "User experience lives or dies at checkout.", "用户体验在结账环节定生死。", "map user experience journeys quarterly"),
  v("wireframe-lorem-ipsum-sketch-stage-honesty", "/线框图", "/ˈwaɪerfreɪm/", "n.", 7, 0.75, "Wireframes keep debates about fonts out early.", "线框图让字体之争晚点进场。", "approve wireframes before visual polish begins"),
  v("prototype-testing-five-user-rule-usability-classic", "/原型测试", "/ˈproʊtətaɪp ˈtestɪŋ/", "n.", 7, 0.7, "Prototype tests humbled our favorite features fast.", "原型测试迅速羞辱了我们最爱的功能。", "run prototype tests before writing production code"),
  v("beta-version-brave-early-adopter-thanks-program", "/测试版", "/ˈbeɪtə ˈvɜːrʒn/", "n.", 6, 0.6, "Beta users find crashes developers never dreamed of.", "测试用户能找到开发者做梦都想不到的崩溃。", "reward beta testers with early access perks"),
  v("release-notes-changelog-human-translation-attempt", "/发布说明", "/rɪˈliːs noʊts/", "n.", 7, 0.65, "Release notes say 'improvements' when they mean 'fewer fires'.", "发布说明里的“优化”意思是“火情更少”。", "write release notes in human language finally"),
  v("cloud-computing-renting-servers-like-utilities-model", "/云计算", "/klaʊd kəmˈpjuːtɪŋ/", "n.", 6, 0.6, "Cloud computing bills surprise like gym memberships.", "云账单像健身年卡一样给人惊喜。", "set cloud spending alerts before month two"),
  v("server-room-cold-air-humming-lullaby-memory", "/服务器", "/ˈsɜːrvər/", "n.", 5, 0.45, "Servers nap lightly and wake cranky.", "服务器浅眠，醒来闹脾气。", "restart the stubborn server during maintenance windows"),
  v("database-query-language-structured-curiosity-tool", "/数据库", "/ˈdeɪtəbeɪs/", "n.", 6, 0.6, "Databases remember everything except why you asked.", "数据库记得一切，除了你为什么问。", "index database columns that filters actually use"),
  v("api-integration-digital-handshake-contracts-explained", "/应用程序接口", "/ˌeɪ piː ˈaɪ/", "abbr.", 7, 0.7, "APIs shake hands so apps don't fight in public.", "API负责握手，应用就不在公开场合打架。", "read API changelogs before version upgrades"),
  v("version-control-git-commit-message-regrets-archive", "/版本控制", "/ˈvɜːrʒn kənˈtroʊl/", "n.", 7, 0.7, "Version control forgives what Fridays shouldn't have deployed.", "版本控制原谅周五本不该上线的冲动。", "commit early and often with clear messages"),
  v("backup-disaster-recovery-drill-fire-alarm-for-data", "/灾难恢复", "/dɪˈzæstər rɪˈkʌvəri/", "n.", 7, 0.75, "Disaster recovery plans read great until Tuesday's outage.", "灾备计划在周二的断电前一直很完美。", "schedule disaster recovery drills twice yearly"),
  v("digital-footprint-permanent-marker-internet-lesson", "/数字足迹", "/ˈdɪdʒɪtl ˈfʊtprɪnt/", "n.", 7, 0.65, "Digital footprints outlive hairstyles and opinions.", "数字足迹比发型和观点都长寿。", "search your digital footprint once a year"),
  v("deepfake-detection-eye-blink-tell-research", "/深度伪造", "/ˈdiːpfake/", "n.", 7, 0.8, "Deepfakes blink wrong; trust calls over clips.", "深度伪造眨眼不对，重要事打电话别信片段。", "verify deepfake suspicions through second channels"),
  v("quantum-leap-tech-marketing-vs-physics-meaning-gap", "/量子跃迁；巨大飞跃", "/ˈkwɑːntəm liːp/", "idi.", 7, 0.7, "Every keynote promises a quantum leap annually.", "每场发布会都许诺年度量子飞跃。", "distrust quantum leap claims without benchmarks"),
  v("automation-script-weekly-report-magic-tricks", "/自动化脚本", "/ˌɔːtəˈmeɪʃn skrɪpt/", "n.", 7, 0.65, "Automation scripts retire boring Tuesdays quietly.", "自动化脚本悄悄让无聊的周二退休。", "version control your automation scripts too"),
  v("no-code-platform-citizen-developer-movement-wave", "/无代码平台", "/noʊ koʊd/", "adj.", 7, 0.7, "No-code tools turn accountants into app builders.", "无代码工具把会计变成应用工程师。", "prototype internal tools with no-code first"),
  v("cybersecurity-hygiene-password-and-patch-daily-vitamins", "/网络安全", "/ˌsaɪbərsɪˈkjʊrəti/", "n.", 7, 0.65, "Cybersecurity is brushing teeth for computers.", "网络安全就是给电脑刷牙。", "practice cybersecurity hygiene like dental care"),
  v("tech-support-turn-it-off-and-on-legendary-fix", "/技术支持", "/tek səˈpɔːrt/", "n.", 5, 0.4, "Tech support's sacred spell: restart it twice.", "技术支持的神咒：重启两次。","try turning it off and on before calling support"),
];
