import { v } from "@/content/vocab/builder";
import type { VocabRow } from "@/content/vocab/types";

/** Descriptive precision & nuanced adjectives - Phase 10 chunk-h. */
export const descriptivePrecisionRows: VocabRow[] = [
  v("vivid-description-sensory-detail-craft", "/生动的；鲜明的", "/ˈvɪvɪd/", "adj.", 6, 0.5, "Vivid details make readers smell the rain.", "生动的细节让读者闻到雨味。", "paint a vivid picture with words"),
  v("vague-foggy-commitments-warning-label", "/模糊的；含糊的", "/veɪɡ/", "adj.", 6, 0.45, "Vague promises collect interest in resentment.", "模糊的承诺以怨恨计息。", "avoid vague deadlines entirely please"),
  v("ambiguous-two-reads-one-sentence-trap", "/模棱两可的；歧义的", "/æmˈbɪɡjuəs/", "adj.", 7, 0.55, "Ambiguous road signs test faith in maps.", "歧义路标考验对地图的信仰。", "flag ambiguous requirements before coding"),
  v("precise-exact-to-the-millimeter-standard", "/精确的；明确的", "/prɪˈsaɪs/", "adj.", 5, 0.4, "Precise instructions spare everyone follow-ups.", "精确的指令省去所有追问。", "give precise times not vague windows"),
  v("accurate-fact-check-approved-adjective", "/准确的；精准的", "/ˈækjərət/", "adj.", 4, 0.3, "Accurate beats fast in medical charts.", "在病历里，准确胜过快速。", "keep records accurate and current"),
  v("specific-nail-down-the-details-skill", "/具体的；特定的", "/spəˈsɪfɪk/", "adj.", 3, 0.25, "Specific praise teaches; generic praise flatters.", "具体的赞美教人，空泛的赞美哄人。", "request specific feedback on one section"),
  v("subtle-understated-expertise-signature", "/微妙的；不易察觉的", "/ˈsʌtl/", "adj.", 6, 0.5, "Subtle flavors argue quietly and win.", "微妙的风味安静争辩然后获胜。", "notice subtle shifts in tone early"),
  v("obvious-elephant-in-room-acknowledgment", "/明显的；显然的", "/ˈɑːbviəs/", "adj.", 2, 0.15, "The obvious answer arrived after three coffees.", "显而易见的答案在第三杯咖啡后到来。", "state the obvious once then move on"),
  v("drastic-measures-extreme-cures-warning", "/极端的；激烈的", "/ˈdræstɪk/", "adj.", 7, 0.55, "Drastic haircuts demand three days of privacy.", "激动的发型需要三天不出门。", "take drastic measures only as last resorts"),
  v("moderate-middle-path-underrated-setting", "/适度的；温和的", "/ˈmɑːdərət/", "adj.", 5, 0.4, "Moderate exercise outlives January heroics.", "适度运动比一月热血更长寿。", "recommend moderate portions over bans"),
  v("significant-not-just-statistics-word", "/显著的；重要的", "/sɪɡˈnɪfɪkənt/", "adj.", 4, 0.3, "Significant others outrank significant metrics.", "重要的另一半胜过重要指标。", "report significant changes with context attached"),
  v("marginal-edge-case-small-but-real-gains-word", "/边际的；微小的", "/ˈmɑːrdʒɪnl/", "adj.", 7, 0.6, "Marginal gains compound into championships.", "边际收益复利成冠军。", "collect marginal gains systematically weekly"),
  v("substantial-size-that-pays-rent-adjective", "/大量的；实质的", "/səbˈstænʃl/", "adj.", 6, 0.5, "A substantial breakfast defeats vending machines.", "丰盛早餐击败售货机。", "raise substantial funding before hiring sprees"),
  v("negligible-rounding-error-honesty-word", "/可忽略不计的；微不足道的", "/ˈneɡlɪdʒəbl/", "adj.", 7, 0.65, "The delay was negligible; the apology wasn't.", "延误可以忽略，道歉不能。", "dismiss negligible risks without drama"),
  v("abundant-overwhelming-plenty-visual-word", "/丰富的；充裕的", "/əˈbʌndənt/", "adj.", 6, 0.5, "Abundant sunshine ruins no plans ever.", "充沛的阳光从不毁掉计划。", "enjoy abundant options without hoarding them"),
  v("scarce-desert-rain-economics-of-things", "/稀缺的；不足的", "/skers/", "adj.", 6, 0.5, "Scarce parking writes its own etiquette.", "稀缺的车位自创礼仪。", "stock up when essentials turn scarce"),
  v("ample-roomy-generous-measurement-compliment", "/充足的；宽敞的", "/ˈæmpl/", "adj.", 6, 0.5, "Ample legroom buys lifelong airline loyalty.", "宽敞的腿部空间买断航空忠诚。", "leave ample time between connections"),
  v("cramped-city-apartment-character-building-joke", "/狭窄的；拥挤的", "/kræmpt/", "adj.", 6, 0.5, "Cramped kitchens invent efficient chefs.", "狭小的厨房造就高效厨师。", "survive cramped flights with aisle strategy"),
  v("spacious-suburb-dream-square-footage-flex", "/宽敞的；广阔的", "/ˈspeɪʃəs/", "adj.", 6, 0.5, "Spacious garages become storage rooms instantly.", "宽敞车库秒变杂物间。", "tour spacious venues before signing contracts"),
  v("fragile-handle-with-care-sticker-origin", "/易碎的；脆弱的", "/ˈfrædʒəl/", "adj.", 4, 0.35, "Fragile packages and egos ship poorly.", "易碎品和玻璃心都不好寄。", "mark fragile boxes in two languages"),
  v("sturdy-ikea-furniture-aspirations-benchmark", "/结实的；坚固的", "/ˈstɜːrdi/", "adj.", 5, 0.4, "Sturdy shoes forgive mountain mistakes.", "结实的鞋原谅登山的失误。", "invest in sturdy luggage handles first"),
  v("durable-decade-warranty-confident-products", "/耐用的；持久的", "/dʊrəbl/", "adj.", 6, 0.5, "Durable friendships survive moving trucks.", "耐用的友谊扛得住搬家卡车。", "choose durable over trendy for daily items"),
  v("flimsy-one-star-review-predictor-adjective", "/劣质的；不结实的", "/ˈflɪmzi/", "adj.", 7, 0.55, "Flimsy umbrellas surrender at first gust.", "单薄的雨伞一阵风就投降。", "return flimsy products within warranty windows"),
  v("glossy-magazine-shine-vs-screen-glare-double-life", "/光滑的；光面的", "/ˈɡlɑːsi/", "adj.", 6, 0.5, "Glossy brochures promise weatherproof marriages.", "光面宣传册承诺防风雨的婚姻。", "avoid glossy screens under office skylights"),
  v("matte-fingerprint-resistant-practical-choice-badge", "/哑光的；无光泽的", "/mæt/", "adj.", 7, 0.6, "Matte finishes hide fingerprints and regrets.", "哑光表面藏住指纹与悔恨。", "pick matte laptop lids for open offices"),
  v("transparent-honesty-and-clear-plastic-double-meaning", "/透明的；坦率的", "/trænsˈperənt/", "adj.", 5, 0.45, "Transparent pricing ends checkout regret.", "透明定价终结结算后悔。", "stay transparent about delays proactively"),
  v("opaque-deliberately-unclear-contracts-warning", "/不透明的；难懂的", "/oʊˈpeɪk/", "adj.", 7, 0.6, "Opaque fees fund surprise invoices.", "不透明费用养肥意外账单。", "question opaque pricing models directly"),
  v("flexible-yoga-and-schedules-shared-virtue", "/灵活的；柔韧的", "/ˈfleksəbl/", "adj.", 4, 0.3, "Flexible plans survive contact with Mondays.", "灵活的计划经得起周一检验。", "build flexible buffers into travel days"),
  v("rigid-steel-beam-management-style-warning", "/僵硬的；死板的", "/ˈrɪdʒɪd/", "adj.", 6, 0.5, "Rigid routines crack under newborn schedules.", "死板的日程在新宝宝面前碎裂。", "loosen rigid processes before they snap"),
  v("steady-heartbeat-and-progress-shared-adjective", "/稳定的；持续的", "/ˈstedi/", "adj.", 3, 0.25, "Steady progress embarrasses dramatic comebacks.", "稳步前进让戏剧性逆袭难堪。", "value steady contributors during loud launches"),
  v("erratic-weather-app-mood-swings-described", "/反复无常的；飘忽不定的", "/ɪˈrætɪk/", "adj.", 7, 0.6, "Erratic wifi tests meditation training daily.", "飘忽的WiFi天天考验冥想功力。", "document erratic behavior before support calls"),
  v("relentless-positive-or-exhausting-context-decides", "/不懈的；不留情的", "/rɪˈlentləs/", "adj.", 7, 0.6, "Relentless curiosity beats occasional genius.", "不懈的好奇胜过偶尔的天才。", "praise relentless effort over lucky outcomes"),
  v("meticulous-tiny-details-organized-love-language", "/一丝不苟的；细致的", "/məˈtɪkjələs/", "adj.", 7, 0.6, "Meticulous notes rescue future-you monthly.", "细致的笔记每月拯救未来的你。", "keep meticulous logs during experiments"),
  v("careless-autocorrect-blamed-unfairly-adjective", "/粗心的；疏忽的", "/ˈkerləs/", "adj.", 4, 0.3, "Careless typos draft apology emails for you.", "粗心的错字替你起草道歉邮件。", "proofread careless drafts twice before sending"),
  v("thorough-full-checkout-before-returning-library-books", "/彻底的；全面的", "/ˈθɜːroʊ/", "adj.", 5, 0.35, "Thorough checks find what hope overlooked.", "彻底检查能找到希望漏掉的问题。", "run thorough audits before board meetings"),
  v("superficial-first-impression-only-depth-settings", "/肤浅的；表面的", "/ˌsuːpərˈfɪʃl/", "adj.", 7, 0.55, "Superficial small talk hides deep strangers.", "肤浅闲聊背后藏着深刻的陌生人。", "move beyond superficial small talk gradually"),
  v("profound-three-am-thoughts-adjective", "/深刻的；意义深远的", "/prəˈfaʊnd/", "adj.", 6, 0.55, "Profound insights sound obvious by morning.", "深刻的洞见到早上显得理所当然。", "capture profound ideas before sunrise steals them"),
  v("shallow-end-pool-and-arguments-double-duty", "/浅的；浅薄的", "/ˈʃæloʊ/", "adj.", 4, 0.3, "Shallow rivers cross fastest, mostly.", "浅河多半先被渡过。", "wade shallow waters before deep commitments"),
  v("dense-information-packed-or-thick-crusted-double-life", "/密集的；稠密的", "/dens/", "adj.", 5, 0.45, "Dense textbooks read slower than traffic moves.", "晦涩的教材读得比堵车还慢。", "summarize dense reports into three bullets"),
  v("sparse-minimalist-fields-and-fonts-aesthetic", "/稀疏的；稀少的", "/spɑːrs/", "adj.", 7, 0.6, "Sparse slides respect sleepy audiences.", "留白的幻灯片尊重打瞌睡的观众。", "keep sparse notes when trails fork often"),
];
