import { v } from "@/content/vocab/builder";
import type { VocabRow } from "@/content/vocab/types";

/** Nuanced verbs & everyday actions - Phase 10 chunk-h. */
export const verbsNuanceRows: VocabRow[] = [
  v("glance-quick-look-two-second-version", "/瞥视；匆匆一看", "/ɡlæns/", "v./n.", 4, 0.3, "She glanced at the clock and sighed.", "她瞥了一眼时钟叹了口气。", "glance at your notes briefly"),
  v("stare-too-long-social-alarm-version", "/凝视；盯着看", "/ster/", "v./n.", 3, 0.25, "Don't stare at the eclipse without glasses.", "看日食别不戴眼镜直视。", "stare out the window daydreaming"),
  v("gaze-long-soft-romantic-look", "/凝望；注视", "/ɡeɪz/", "v./n.", 5, 0.35, "They gazed at city lights in silence.", "他们默默凝望城市灯火。", "gaze into the campfire thoughtfully"),
  v("peek-sneaky-small-look-permission-question", "/偷看；瞥一眼", "/piːk/", "v./n.", 4, 0.25, "Can I peek at the menu early?", "我能先瞄一眼菜单吗？", "take a quick peek inside the box"),
  v("peer-look-closely-through-glasses-version", "/仔细看；窥视", "/pɪr/", "v./n.", 6, 0.4, "He peered through the foggy windshield.", "他透过起雾的挡风玻璃仔细看。", "peer over the crowd for a better view"),
  v("whisper-library-volume-secret-sharing", "/低语；耳语", "/ˈwɪspər/", "v./n.", 3, 0.25, "Libraries turn gossip into whispering practice.", "图书馆把八卦变成耳语练习。", "whisper the answer during exams never"),
  v("mumble-mouth-full-excuse-generator", "/咕哝；含糊地说", "/ˈmʌmbl/", "v./n.", 6, 0.45, "He mumbled an apology and left quickly.", "他咕哝着道歉然后快步离开。", "stop mumbling during presentations please"),
  v("shout-outdoor-voice-maximum-setting", "/大喊；高声喊叫", "/ʃaʊt/", "v./n.", 2, 0.2, "Fans shouted the chorus louder than speakers.", "粉丝的合唱比音响还大声。", "shout directions across the field"),
  v("yell-anger-or-kids-at-play-version", "/大叫；吼叫", "/jel/", "v./n.", 3, 0.25, "Mom yelled upstairs; dinner was ready twice.", "妈妈朝楼上喊了两遍饭好了。", "yell a warning before the wave hits"),
  v("scream-horror-movie-or-roller-coaster-audio", "/尖叫；惊呼", "/skriːm/", "v./n.", 3, 0.25, "Roller coasters rent screams by the drop.", "过山车按俯冲出租尖叫。", "scream into pillows when deadlines stack"),
  v("chat-light-casual-conversation-default-mode", "/闲聊；聊天", "/tʃæt/", "v./n.", 2, 0.15, "Neighbors chat over fences like antennas.", "邻居隔着栅栏像天线一样聊天。", "chat with strangers at dog parks easily"),
  v("gossip-information-currency-exchange-program", "/八卦；说三道四", "/ˈɡɑːsɪp/", "n./v.", 4, 0.3, "Office gossip travels faster than email ever will.", "办公室八卦永远跑得比邮件快。", "skip gossip during lunch invitations politely"),
  v("complain-ticket-booth-frequent-flyer-behavior", "/抱怨；投诉", "/kəmˈpleɪn/", "v.", 3, 0.25, "Complain once to fix; twice to entertain.", "投诉一次能修好，两次成表演。", "complain constructively with proposed solutions"),
  v("grumble-low-level-complaint-background-music", "/嘟囔；发牢骚", "/ˈɡrʌmbl/", "v./n.", 6, 0.45, "Dads grumble happily while assembling furniture.", "爸爸们边装家具边幸福地嘟囔。", "grumble about weather as small talk"),
  v("praise-specific-recognition-that-teaches", "/表扬；称赞", "/preɪz/", "v./n.", 4, 0.3, "Praise the process, not just the trophy.", "夸过程，不只夸奖杯。", "earn praise by lifting teammates quietly"),
  v("compliment-free-gift-with-no-return-policy-needed", "/赞美；恭维", "/ˈkɑːmplɪmənt/", "n./v.", 4, 0.3, "Compliment shoes; it starts friendships randomly.", "夸夸鞋子，友谊随机开始。", "accept compliments with plain thank-yous"),
  v("flatter-obvious-agenda-detector-triggering", "/奉承；讨好", "/ˈflætər/", "v.", 7, 0.55, "Flattery works exactly once per person.", "奉承对每人只生效一次。", "distinguish flattery from genuine praise carefully"),
  v("apologize-sincere-repair-kit-for-mistakes", "/道歉", "/əˈpɑːlədʒaɪz/", "v.", 4, 0.3, "Apologize fast; interest accrues on pride.", "快点道歉，自尊也会计息。", "apologize without excuses in one sentence"),
  v("forgive-release-yourself-from-the-resentment-tax", "/原谅；宽恕", "/fərˈɡɪv/", "v.", 4, 0.35, "Forgive quietly; grudges charge storage fees.", "悄悄原谅，怨恨收保管费。", "forgive small things before they fossilize"),
  v("promise-commitment-with-interest-calculator", "/承诺；答应", "/ˈprɑːmɪs/", "n./v.", 2, 0.15, "Promise less; deliver slightly more.", "少承诺，多交付一点点。", "keep promises smaller than your calendar"),
  v("refuse-polite-no-without-paragraph-defense", "/拒绝；回绝", "/rɪˈfjuːz/", "v.", 4, 0.3, "Refuse extra projects with warm firmness.", "用温暖而坚定拒绝额外项目。", "refuse gracefully and recommend someone else"),
  v("deny-formal-disagreement-with-allegations-style", "/否认；否定", "/dɪˈnaɪ/", "v.", 5, 0.4, "The cat denied everything about the vase.", "猫对花瓶事件一概否认。", "deny rumors with facts not volume"),
  v("admit-truth-costs-less-than-cover-stories", "/承认；招认", "/ədˈmɪt/", "v.", 3, 0.3, "Admit mistakes before they grow roommates.", "趁错误还没搬来合租先承认。", "admit gaps then show learning plans"),
  v("confess-weight-off-chest-relief-verb", "/坦白；忏悔", "/kənˈfes/", "v.", 6, 0.5, "Confess you ate the leftovers; heal the household.", "坦白你吃了剩菜，拯救家庭和谐。", "confess mistakes before audits find them"),
  v("suggest-options-not-orders-leadership-verb", "/建议；暗示", "/səˈdʒest/", "v.", 3, 0.25, "Suggest three options and let teams choose.", "给出三个选项让团队选。", "suggest improvements with working prototypes attached"),
  v("recommend-personal-stamp-of-approval-verb", "/推荐；建议", "/ˌrekəˈmend/", "v.", 3, 0.25, "Recommend only restaurants you'd defend in court.", "只推荐你愿意在法庭上辩护的餐厅。", "recommend books that changed your thinking"),
  v("insist-boundary-with-smile-repeat-technique", "/坚持认为；坚决要求", "/ɪnˈsɪst/", "v.", 5, 0.4, "Grandma insists; resistance only delays dessert.", "外婆坚持己见，抵抗只会推迟甜点。", "insist politely twice then let it go"),
  v("persuade-change-minds-without-force-fields", "/说服；劝服", "/pərˈsweɪd/", "v.", 5, 0.4, "Persuade with their reasons, not your volume.", "用对方的理由说服对方。", "persuade stakeholders with pilot results first"),
  v("convince-beyond-doubt-threshold-crossing", "/使确信；使信服", "/kənˈvɪns/", "v.", 4, 0.3, "Convince yourself before convincing investors.", "先说服自己再说服投资人。", "convince skeptics with boring solid evidence"),
  v("remind-love-notes-for-memory-leaks", "/提醒；使想起", "/rɪˈmaɪnd/", "v.", 2, 0.15, "Remind me why we chose the early flight.", "提醒我当初为啥选红眼航班。", "set reminders two days before deadlines"),
  v("memorize-flashcards-vs-understanding-debate-entry", "/记住；背诵", "/ˈmeməraɪz/", "v.", 4, 0.3, "Memorize lines; understand characters deeper still.", "背下台词，更要理解角色。", "memorize key numbers for confident talks"),
  v("review-second-pass-before-submitting-discipline", "/复习；审查", "/rɪˈvjuː-n2/", "v./n.", 3, 0.25, "Review tomorrow's slides tonight; future-you says thanks.", "今晚就复习明天的幻灯片，未来的你会感谢你。", "review budgets line by line monthly"),
  v("revise-edit-without-mercy-pass", "/修改；修订", "/rɪˈvaɪz/", "v.", 5, 0.4, "Revise drafts until they sound spoken.", "反复修改直到文字像说话。", "revise resumes for every application individually"),
  v("proofread-typo-assassin-final-gate-duty", "/校对", "/ˈpruːfriːd/", "v.", 7, 0.55, "Proofread backwards to catch sneaky typos.", "倒着校对抓狡猾错字。", "ask fresh eyes to proofread big emails"),
  v("translate-between-languages-and-jargon-systems", "/翻译；转化", "/trænzˈleɪt/", "v.", 4, 0.35, "Translate engineer to human weekly.", "每周把工程师语言译成人话。", "translate feedback into concrete next steps"),
  v("interpret-flexibly-when-rules-meet-reality", "/口译；解读", "/ɪnˈtɜːrprət/", "v.", 6, 0.45, "Interpret silence generously during negotiations.", "谈判中对沉默要善意解读。", "interpret data cautiously before headlines write themselves"),
  v("calculate-versus-estimate-precision-spectrum-pair", "/计算；估算", "/ˈkælkjuleɪt/", "v.", 3, 0.25, "Calculate tips mentally; calculate taxes with software.", "小费心算，报税交给软件。", "calculate runway before celebrating funding"),
  v("measure-twice-cut-once-grandpa-law", "/测量；衡量", "/ˈmeʒər/", "v./n.", 2, 0.2, "Measure twice; buy returns labels zero times.", "量两次，退货标签零次。", "measure progress against last quarter honestly"),
  v("compare-apples-to-apples-only-fair-method", "/比较；对比", "/kəmˈper/", "v.", 2, 0.2, "Compare prices per unit, not per package drama.", "按单位比价，别被包装戏法骗了。", "compare vendors using identical requirements lists"),
  v("organize-chaos-into-labeled-victory", "/组织；整理", "/ˈɔːrɡənaɪz/", "v.", 3, 0.25, "Organize cables today; thank yourself at midnight.", "今天理好线缆，午夜自会感谢。", "organize files by project not by panic"),
  v("arrange-flowers-and-meetings-share-verbs", "/安排；整理", "/əˈreɪndʒ/", "v.", 3, 0.25, "Arrange meetings shorter; arrange flowers however.", "会议越短越好，花随性插。", "arrange carpools for the conference week"),
  v("prepare-plan-B-because-Monday-exists", "/准备；预备", "/prɪˈper/", "v.", 2, 0.15, "Prepare answers before interviews ask questions.", "在面试提问前先备好答案。", "prepare talking points before difficult reviews"),
  v("plan-realistic-timelines-builders-anonymous", "/计划；打算", "/plæn/", "v./n.", 1, 0.1, "Plan loosely; hold priorities tightly.", "计划放宽，优先级握紧。", "plan buffer days after long trips"),
  v("schedule-calendar-blocks-defended-like-fortresses", "/安排时间；预定", "/ˈskedʒuːl/", "v./n.", 3, 0.25, "Schedule thinking time or meetings will eat it.", "不给思考留档期，会议就会吃掉它。", "schedule deep work before checking messages"),
  v("postpone-guilt-free-rescheduling-art", "/推迟；延期", "/poʊstpˈoʊn/", "v.", 5, 0.35, "Postpone vacations rarely; postpone meetings freely.", "假期尽量别推迟，会议随便延。", "postpone launches rather than quality always"),
  v("cancel-subscriptions-and-plans-equal-rights-policy", "/取消；撤销", "/ˈkænsl/", "v.", 3, 0.25, "Cancel plans kindly and promptly when needed.", "需要取消时尽早并友善地告知。", "cancel unused subscriptions every quarter"),
  v("celebrate-small-wins-confetti-budget-friendly", "/庆祝；庆贺", "/ˈselɪbreɪt/", "v.", 3, 0.25, "Celebrate shipped work, not just launched dreams.", "庆祝交付的工作，不只是发布的梦想。", "celebrate milestones with the whole crew"),
  v("congratulate-others-first-networking-kindness", "/祝贺；道贺", "/kənˈɡrætʃuleɪt/", "v.", 5, 0.35, "Congratulate rivals sincerely; watch what returns.", "真诚祝贺对手，看看会回来什么。", "congratulate new parents with food not questions"),
  v("appreciate-notice-then-say-it-aloud-rule", "/感激；欣赏", "/əˈpriːʃieɪt/", "v.", 3, 0.25, "Appreciate effort loudly; correct privately later.", "公开欣赏努力，私下再来纠正。", "appreciate teachers with specific stories instead"),
  v("volunteer-hand-raising-before-being-voluntold", "/自愿做；志愿者", "/ˌvɑːlənˈtɪr/", "v./n.", 4, 0.3, "Volunteer for demos; confidence compounds there.", "主动请缨做演示，自信在那里复利。", "volunteer skills where they multiply fastest"),
  v("donate-clutter-exit-strategy-with-purpose", "/捐赠；捐献", "/doʊˈneɪt/", "v.", 4, 0.3, "Donate books while they still smell loved.", "趁书还有爱的味道赶紧捐出去。", "donate monthly even in tiny amounts"),
  v("recycle-bin-sorting-civic-reflex-training", "/回收利用；再利用", "/ˌriːˈsaɪkl/", "v.", 4, 0.3, "Recycle batteries separately; landfills vote no.", "电池单独回收，垃圾填埋场投反对票。", "recycle electronics at certified centers only"),
  v("reuse-jars-containers-second-career-program", "/重复使用；再使用", "/ˌriːˈjuːz/", "v.", 4, 0.3, "Reuse glass jars; pasta sauce deserves retirement plans.", "重复用玻璃罐，意面酱瓶值得再就业。", "reuse gift bags until they disintegrate proudly"),
];
