import { v } from "@/content/vocab/builder";
import type { VocabRow } from "@/content/vocab/types";

/** Everyday essentials & mixed high-frequency support - Phase 10 chunk-h. */
export const essentialsMixedRows: VocabRow[] = [
  v("errand-lunch-break-task-chaining", "/差事；跑腿", "/ˈerənd/", "n.", 4, 0.25, "Saturday errands swallow entire mornings.", "周六的杂事吞掉整个上午。", "run errands before noon crowds"),
  v("chore-weekend-negotiation-marathon", "/家务活；杂务", "/tʃɔːr/", "n.", 3, 0.2, "Chore charts ended household diplomacy crises.", "家务分工表终结了家庭外交危机。", "rotate chores fairly every week"),
  v("appointment-calendar-slot-defended-fiercely", "/预约；约定", "/əˈpɔɪntmənt/", "n.", 3, 0.25, "Dentist appointments book months out here.", "这里的牙医预约要排几个月。", "confirm appointments the day before"),
  v("deadline-extension-request-politely-crafted-emails", "/最后期限；交稿日期", "/ˈdedlaɪn/", "n.", 4, 0.3, "Deadlines move; quality expectations don't.", "截止日可以移，质量标准不能降。", "negotiate deadlines before agreeing to them"),
  v("budget-app-category-spiral-analysis-paralysis", "/预算（同 budget 变体）", "/ˈbʌdʒɪt/", "n.", 3, 0.3, "Budget apps reveal your true favorite restaurant.", "记账应用暴露你最爱哪家馆子。", "review budget categories monthly together"),
  v("receipt-shoebox-accounting-system-classic", "/收据；小票", "/rɪˈsiːt/", "n.", 4, 0.3, "Receipts multiply inside coat pockets mysteriously.", "收据在外套口袋里神秘增殖。", "photograph receipts immediately for expenses"),
  v("refund-return-window-deadline-drama", "/退款", "/ˈriːfʌnd/", "n./v.", 4, 0.3, "Refunds arrive slower than regret sets in.", "退款到账总比后悔来得慢。", "request refunds within policy windows politely"),
  v("warranty-registration-card-throwaway-tradition", "/保修单；保证", "/ˈwɔːrənti/", "n.", 6, 0.5, "Warranties expire exactly one week before failure.", "保修期恰好在故障前一周到期。", "register warranties digitally on purchase day"),
  v("delivery-window-two-hour-promise-mythology", "/配送时段", "/dɪˈlɪvəri ˈwɪndoʊ/", "n.", 5, 0.45, "Delivery windows stretch like warm taffy.", "配送时段像热太妃糖一样拉长。", "narrow delivery windows with morning calls"),
  v("neighbor-package-holding-kindness-economy", "/邻居（同 neighbor 拼写变体）", "/ˈneɪbər/", "n.", 1, 0.1, "Neighbors who hold packages deserve thank-you bread.", "帮忙代收包裹的邻居值得送面包。", "thank neighbors with small baked gifts"),
  v("houseplant-watering-schedule-guilt-ecosystem", "/室内植物", "/ˈhaʊsplænt/", "n.", 6, 0.5, "Houseplants forgive missed waterings twice yearly.", "室内植物每年原谅两次忘记浇水。","name houseplants so you'll water them"),
  v("pet-sitter-trust-transfer-protocol-keys", "/宠物保姆", "/pet ˈsɪtər/", "n.", 6, 0.55, "Great pet sitters send daily photo reports.", "好的宠物保姆每天发照片汇报。", "book pet sitters three weeks early minimum"),
  v("babysitter-friday-night-limited-resource-economics", "/临时保姆", "/ˈbeɪbisɪtər/", "n.", 6, 0.5, "Friday babysitters are rarer than eclipse glasses.", "周五的临时保姆比日食镜还稀有。", "line up backup babysitters before summer"),
  v("commute-podcast-library-curated-carefully", "/通勤（变体）", "/ˈkɑːmjuːt/", "v./n.", 4, 0.3, "Commute time is found reading money.", "通勤时间是白捡的阅读时间。", "stack podcasts for long commutes ahead"),
  v("carpool-HOV-lane-speed-pass-privileges", "/拼车；合用车", "/ˈkɑːrpuːl/", "n./v.", 6, 0.5, "Carpools run on snacks and strict playlists.", "拼车靠零食和严格的歌单运转。", "organize carpools through the group chat"),
  v("gas-mileage-hybrid-pride-conversations", "/油耗；每加仑里程", "/ɡæs ˈmaɪlɪdʒ/", "n.", 7, 0.65, "Gas mileage bragging peaks at family dinners.", "吹嘘油耗的高峰在家庭晚宴。", "improve gas mileage by easing off pedals"),
  v("oil-change-sticker-windshield-reminder-archaeology", "/换机油", "/ˈɔɪl tʃeɪndʒ/", "n.", 7, 0.6, "Oil change stickers outlive most new year resolutions.", "换机油贴纸比多数新年决心长寿。", "schedule oil changes every five thousand miles"),
  v("tire-pressure-monthly-check-preaching-season", "/胎压", "/ˈtaɪər ˈpreʃər/", "n.", 7, 0.6, "Tire pressure checks save winter mornings silently.", "检查胎压默默拯救冬日清晨。", "check tire pressure monthly like vitamins"),
  v("windshield-wiper-streak-blade-replacement-rain-test", "/雨刷", "/ˈwɪndʃiːld ˈwaɪpər/", "n.", 7, 0.65, "Squeaky wipers announce autumn officially.", "吱吱响的雨刷正式宣告秋天来了。", "replace wipers before the first storm"),
  v("parking-meter-quarter-hunting-expedition-sport", "/停车计时器", "/ˈpɑːrkɪŋ ˈmiːtər/", "n.", 6, 0.55, "Parking meters accept cards and still prefer quarters.", "停车计费器收卡但更爱硬币。", "feed parking meters before coffee runs"),
  v("jaywalking-ticket-tourist-surprise-tax", "/乱穿马路", "/ˈdʒeɪwɔːkɪŋ/", "n.", 7, 0.7, "Jaywalking fines surprise visitors with luggage.", "乱穿马路的罚单专惊带行李的游客。", "avoid jaywalking near busy intersections completely"),
  v("crosswalk-button-placebo-effect-studies-jokes", "/行人按钮（变体）", "/ˈkrɔːswɔːk ˈbʌtn/", "n.", 7, 0.7, "Crosswalk buttons comfort fingers more than signals.", "行人按钮安慰手指多过改变信号灯。", "press crosswalk buttons once then wait patiently"),
  v("laundry-day-sorting-ritual-colors-versus-whites", "/洗衣日", "/ˈlɔːndri deɪ/", "n.", 4, 0.3, "Laundry day reveals your real weekly uniform.", "洗衣日暴露你真实的一周制服。", "batch laundry days to save quarters"),
  v("dry-clean-only-tag-ignored-at-your-peril", "/干洗", "/draɪ kliːn/", "v./adj.", 6, 0.5, "Dry-clean tags are gentle warnings, not suggestions.", "干洗标签是温柔的警告不是建议。", "budget dry cleaning for interview suits only"),
  v("iron-shirt-collar-discipline-inherited-from-parents", "/熨烫；熨斗", "/ˈaɪərn/", "v./n.", 3, 0.3, "Iron skills skip generations randomly.", "熨衣手艺随机跳代遗传。", "iron shirts while slightly damp instead"),
  v("vacuum-cleaner-robot-vs-upright-household-debate", "/吸尘器（变体）", "/ˈvækjuːm ˌkliːnər/", "n.", 5, 0.4, "Robot vacuums map homes better than owners do.", "扫地机器人比主人还懂户型。", "run robot vacuums during office hours quietly"),
  v("dishwasher-loading-philosophy-household-summit-topic", "/洗碗机", "/ˈdɪʃwɑːʃər/", "n.", 5, 0.4, "Dishwasher loading sparks diplomatic incidents worldwide.", "洗碗机装载法在全球引发外交事件。", "rinse dishes lightly before dishwasher runs"),
  v("grocery-list-phone-notes-checkout-forgetting-curve", "/购物清单", "/ˈɡroʊsəri lɪst/", "n.", 4, 0.3, "Grocery lists left home guarantee two extra trips.", "购物清单忘在家必换来两趟返程。", "share grocery lists with household members live"),
  v("coupon-clipping-digital-era-evolution-story", "/优惠券", "/ˈkuːpɑːn/", "n.", 5, 0.35, "Coupons expire faster than enthusiasm does.", "优惠券过期比热情消退还快。", "clip coupons only for items already listed"),
  v("sale-rack-bottom-shelf-hidden-treasure-archaeology", "/打折区", "/seɪl ræk/", "n.", 5, 0.4, "Sale racks reward patience and punish impulse equally.", "打折货架平等奖励耐心惩罚冲动。", "browse sale racks last not first deliberately"),
  v("fitting-room-lighting-cruelty-awareness-movement", "/试衣间", "/ˈfɪtɪŋ ruːm/", "n.", 6, 0.5, "Fitting room lighting should require consent.", "试衣间的灯光应该先征得同意。", "photograph fitting room mirrors for honest angles"),
  v("alterations-ticket-number-callout-memory-test", "/修改衣服（服务）", "/ˌɔːltəˈreɪʃnz/", "n.", 7, 0.65, "Alterations transform clearance sales into couture.", "改衣把清仓货变成高级定制。", "keep alterations receipts pinned inside hems"),
  v("haircut-tip-standard-local-etiquette-research", "/理发小费", "/ˈherkʌt tɪp/", "n.", 7, 0.65, "Haircut tips vary more than haircut prices locally.", "本地理发小费比理发价差异还大。", "ask friends about haircut tipping norms first"),
  v("dentist-twice-yearly-preaching-consistency-champions", "/牙医（变体）", "/ˈdentɪst/", "n.", 3, 0.25, "Dentists always know; flossing lies detect instantly.", "牙医什么都知道，牙线谎话秒被识破。", "book dentist visits six months apart exactly"),
  v("optometrist-prescription-update-headache-detective-work", "/验光师", "/ɑːpˈtɑːmətrɪst/", "n.", 7, 0.7, "Old prescriptions cause mystery headaches silently.", "过期眼镜处方悄悄制造神秘头痛。", "update optometrist prescriptions every two years"),
  v("pharmacy-refill-auto-renewal-setup-relief", "/药房续药", "/ˈfɑːrməsi riːˈfɪl/", "n.", 6, 0.55, "Auto refills end pharmacy line small talk forever.", "自动续药永久终结药房排队闲聊。", "sync pharmacy refills into one monthly trip"),
  v("insurance-open-enrollment-deadline-calendar-alarm-worthy", "/保险登记期", "/ɪnˈʃʊrəns ˌoʊpən ɪnˈroʊlmənt/", "n.", 7, 0.75, "Open enrollment rewards spreadsheet people annually.", "保险登记期每年奖励表格控。", "diarize insurance enrollment windows each fall"),
  v("tax-season-document-scavenger-hunt-annual-tradition", "/报税季", "/ˈtæks ˈsiːzn/", "n.", 6, 0.6, "Tax season turns shoeboxes into treasure maps.", "报税季让鞋盒变身藏宝图。", "start tax folders in January not April"),
  v("payday-celebration-shrinking-as-autopay-expands", "/发薪日", "/ˈpeɪdeɪ/", "n.", 4, 0.25, "Payday joy lasts until autopay wakes up.", "发薪日的快乐持续到自动扣款醒来。", "schedule transfers on payday morning automatically"),
  v("direct-deposit-payroll-modernization-default-option-now", "/直接存款；工资直入", "/dəˈrekt dɪˈpɑːzɪt/", "n.", 6, 0.5, "Direct deposit ended lunchtime bank runs forever.", "工资直入永久终结午休跑银行。", "split direct deposits into savings automatically first"),
  v("credit-score-three-digit-adulthood-report-card", "/信用分数", "/ˈkredɪt skɔːr/", "n.", 6, 0.6, "Credit scores judge you more kindly than landlords do.", "信用分数比房东仁慈一点。", "monitor credit scores quarterly through free reports"),
  v("loan-application-paperwork-mountains-before-approval-mountains", "/贷款申请", "/loʊn ˌæplɪˈkeɪʃn/", "n.", 6, 0.6, "Loan applications ask where you were born twice differently.", "贷款申请会换着花样两次问你出生地。", "gather loan documents before pre-appointment stress"),
  v("mortgage-rate-shopping-weekend-warrior-spreadsheets", "/房贷利率比较", "/ˈmɔːrɡɪdʒ reɪt/", "n.", 7, 0.7, "Mortgage rate shopping saves more than coupon years combined.", "比价房贷利率省下的钱超过多年优惠券总和。", "shop mortgage rates across three lenders minimum"),
  v("down-payment-savings-goal-birthday-money-gravity", "/首付款", "/daʊn ˈpeɪmənt/", "n.", 7, 0.7, "Down payment funds attract birthday cash magically.", "首付基金神奇吸引生日礼金。", "automate down payment savings invisibly every payday"),
  v("renters-insurance-cheapest-peace-of-math-subscription", "/租客保险", "/ˈrentərz ɪnˈʃʊrəns/", "n.", 7, 0.7, "Renters insurance costs less than one pizza monthly.", "租客保险每月不到一张披萨钱。", "bundle renters insurance with car policies cheaply"),
  v("utility-usage-comparison-neighbor-email-guilt-programs", "/水电账单（复数）", "/juːˈtɪlətiz/", "n.", 6, 0.55, "Utility comparisons shame thermostat rebels publicly.", "公用事业对比公开羞辱恒温器叛逆者。", "trim utility usage during peak hours gently"),
  v("internet-plan-speed-tier-upselling-counter-scripts", "/网络套餐", "/ˈɪntərnət plæn/", "n.", 6, 0.6, "Internet plans upsell speed your devices can't chew.", "网络套餐推销设备啃不动的带宽。", "test internet plans against evening streaming honestly"),
  v("phone-plan-family-share-data-negotiation-summits", "/手机套餐", "/foʊn plæn/", "n.", 5, 0.5, "Family phone plans fund group chat diplomacy.", "家庭套餐资助群聊外交。", "audit phone plans when promotions expire silently"),
  v("streaming-service-rotation-strategy-subscription-churn-art", "/流媒体订阅轮换策略", "/ˈstriːmɪŋ ˈsɜːrvɪs/", "n.", 6, 0.6, "Streaming rotation beats paying four platforms to nap.", "轮换订阅胜过给四个平台付睡觉钱。", "rotate streaming services seasonally and cancel ruthlessly"),
];
