import { v } from "@/content/vocab/builder";
import type { VocabRow } from "@/content/vocab/types";

/** Hobbies, crafts & creative pastimes - Phase 10 chunk-h. */
export const hobbiesCraftsRows: VocabRow[] = [
  v("hobby-rotation-quarterly-commitment-cycles", "/爱好；消遣", "/ˈhɑːbi/", "n.", 2, 0.15, "Hobbies collect more dust than trophies.", "爱好的灰尘比奖杯多。", "rotate hobbies without guilt annually"),
  v("knitting-yarn-stash-growth-outpacing-output", "/编织；针织", "/ˈnɪtɪŋ/", "n.", 6, 0.5, "Knitting calms hands and worries equally.", "编织同时安抚双手和忧愁。", "join knitting circles for winter evenings"),
  v("crochet-hook-versus-needles-friendly-rivalry", "/钩针编织", "/kroʊˈʃeɪ/", "v./n.", 7, 0.6, "Crochet hooks travel in every purse pocket.", "钩针在每个手包口袋里旅行。", "learn crochet stitches from video loops"),
  v("embroidery-hoop-hope-and-french-knots", "/刺绣；绣花", "/ɪmˈbrɔɪdəri/", "n.", 7, 0.65, "Embroidery turns mistakes into design features.", "刺绣把失误变成设计特色。", "frame your first embroidery attempt proudly"),
  v("sewing-machine-pedal-speed-confidence-curve", "/缝纫机", "/ˈsoʊɪŋ məˈʃiːn/", "n.", 7, 0.6, "Sewing machines hum louder during deadlines.", "缝纫机在赶工时哼得更响。", "thread sewing machines before buying fabric"),
  v("woodworking-sawdust-perfume-workshop-pride", "/木工；木工活", "/ˈwʊdwɜːrkɪŋ/", "n.", 7, 0.6, "Woodworking measures twice and brags forever.", "木工量两次，吹嘘一辈子。", "start woodworking with simple shelf projects"),
  v("pottery-wheel-centering-meditation-class-analogy", "/陶艺；制陶", "/ˈpɑːtəri/", "n.", 7, 0.6, "Pottery wheels wobble until egos center too.", "转盘先晃，等你的心也稳了就正了。", "book pottery wheel classes for date nights"),
  v("painting-watercolor-unpredictability-appreciation-training", "/绘画；画作", "/ˈpeɪntɪŋ/", "n.", 3, 0.25, "Watercolor teaches planning humility quickly.", "水彩迅速教会人谦逊地做计划。", "gift family paintings for birthdays always"),
  v("sketchbook-daily-page-streaks-vs-quality-debates", "/素描本；速写本", "/ˈsketʃbʊk/", "n.", 6, 0.5, "Sketchbooks forgive worse than diaries do.", "素描本比日记更宽容。", "carry small sketchbooks to waiting rooms everywhere"),
  v("photography-composition-rules-before-breaking-them-order", "/摄影", "/fəˈtɑːɡrəfi/", "n.", 4, 0.3, "Photography is noticing with commitment.", "摄影是有承诺的观察。", "study photography composition before gear upgrades"),
  v("calligraphy-pen-angle-discipline-handwriting-upgrade-path", "/书法（英文书写艺术）", "/kəˈlɪɡrəfi/", "n.", 7, 0.65, "Calligraphy slows thoughts into beauty.", "书法把思绪放慢成美。", "practice calligraphy strokes before words daily"),
  v("scrapbooking-memory-archaeology-with-washi-tape", "/剪贴簿；拼贴纪念册", "/ˈskræpbʊkɪŋ/", "n.", 7, 0.65, "Scrapbooking archives love in glued layers.", "剪贴簿用胶层归档爱。", "start scrapbooking trips within the same year"),
  v("board-game-night-house-rules-legislation-session", "/桌游之夜", "/bɔːrd ɡeɪm naɪt/", "n.", 5, 0.4, "Board game nights legislate house rules passionately.", "桌游之夜热烈立法家规。", "host board game nights monthly for friendships"),
  v("jigsaw-puzzle-border-first-strategy-school", "/拼图", "/ˈdʒɪɡsɔː ˈpʌzl/", "n.", 4, 0.35, "Jigsaw borders first; chaos later anyway.", "拼图先拼边框，混乱随后照来。","sort jigsaw pieces by color under good lamps"),
  v("chess-openings-memorized-blitz-forgotten-instantly", "/国际象棋", "/tʃes/", "n.", 4, 0.35, "Chess punishes impatience within six moves.", "国际象棋六步内惩罚急躁。", "learn chess endgames before fancy openings"),
  v("go-board-game-ancient-strategy-still-winning", "/围棋", "/ɡoʊ/", "n.", 6, 0.6, "Go rewards patience computers respect eventually.", "围棋奖励耐心，连电脑最终也服气。", "study go shapes through beginner books slowly"),
  v("birdwatching-life-list-notebook-bragging-rights", "/观鸟", "/ˈbɜːrdwɑːtʃɪŋ/", "n.", 7, 0.6, "Birdwatching trains patience binoculars can't teach alone.", "观鸟训练耐心，望远镜独自教不会。", "log birdwatching sightings every Saturday morning"),
  v("gardening-tomato-pride-seasonal-emotional-investment", "/园艺", "/ˈɡɑːrdənɪŋ/", "n.", 4, 0.3, "Gardening converts patience into tomatoes eventually.", "园艺最终把耐心变成番茄。", "start gardening herbs on sunny windowsills"),
  v("baking-sourdough-starter-name-registration-ceremony", "/烘焙（名词）", "/ˈbeɪkɪŋ/", "n.", 4, 0.3, "Baking measures feelings in grams now.", "如今烘焙用克来计量心情。", "share baking failures as funny stories freely"),
  v("homebrewing-patient-bottles-labeled-with-hope", "/家庭自酿（啤酒）", "/ˈhoʊmbruːɪŋ/", "n.", 7, 0.7, "Homebrewing bottles hope and waits six weeks.", "自酿把希望装瓶再等六周。", "sanitize homebrewing equipment twice for safety"),
  v("astronomy-backyard-telescope-cold-nights-worth-it", "/业余天文观测", "/əˈstrɑːnəmi/", "n.", 6, 0.55, "Backyard astronomy freezes fingers and expands minds.", "后院天文冻僵手指却扩展心灵。", "check astronomy forecasts before telescope nights"),
  v("stargazing-app-augmented-reality-sky-maps-helpful", "/观星（变体）", "/ˈstɑːrɡeɪzɪŋ/", "n.", 5, 0.4, "Stargazing apps name stars faster than memory does.", "观星应用报星名比记忆快多了。", "combine stargazing apps with real star charts"),
  v("rock-collecting-pocket-weight-vs-knowledge-tradeoffs", "/收集岩石", "/rɑːk kəˈlektɪŋ/", "n.", 7, 0.65, "Rock collecting weighs pockets down and spirits up.", "捡石头压沉口袋，托起心情。", "label rock collecting finds by region carefully"),
  v("stamp-collecting-grandfather-album-inherited-curiosity", "/集邮", "/stæmp kəˈlektɪŋ/", "n.", 7, 0.65, "Stamp collecting travels history one corner postmark at a time.", "集邮沿着角落邮戳走遍历史。", "store stamp collecting albums away from sunlight"),
  v("coin-collecting-change-jar-archaeology-every-evening", "/硬币收藏", "/kɔɪn kəˈlektɪŋ/", "n.", 7, 0.65, "Coin collecting makes cashiers your research assistants.", "硬币收藏让收银员变成研究助理。", "inspect coin collecting change rolls weekly"),
  v("origami-crane-folding-patience-certification-program", "/折纸", "/ˌɔːrɪˈɡɑːmi/", "n.", 6, 0.55, "Origami folds patience into paper birds.", "折纸把耐心折进纸鸟。", "master origami cranes before dragon challenges"),
  v("magic-tricks-card-palm-practice-invisible-audiences", "/魔术戏法", "/ˈmædʒɪk trɪks/", "n.", 6, 0.55, "Magic tricks perform best after two hundred invisible shows.", "魔术在两百场隐形演出后才最精彩。", "perform magic tricks for kids who never blink"),
  v("juggling-three-ball-ceiling-lamp-casualty-statistics", "/杂耍；抛接杂技", "/ˈdʒʌɡlɪŋ/", "n./v.", 7, 0.6, "Juggling claims ceiling lamps as tuition.", "杂耍拿吊灯当学费。", "practice juggling over beds not lamps"),
  v("karate-kid-discipline-through-belt-testing-years", "/空手道", "/kəˈrɑːti/", "n.", 5, 0.45, "Karate belts measure persistence better than resumes do.", "空手道腰带比简历更能衡量坚持。", "stretch before karate classes every single time"),
  v("taekwondo-kicking-flexibility-progress-photo-albums", "/跆拳道", "/taɪˈkwɑːndoʊ/", "n.", 6, 0.55, "Taekwondo kicks start at hip height, allegedly.", "跆拳道的踢腿据说从髋部高度开始。", "film taekwondo forms to track progress monthly"),
  v("pilates-core-truth-serum-for-desks-workers", "/普拉提", "/pɪˈlɑːtiz/", "n.", 7, 0.65, "Pilates exposes desk posture honestly.", "普拉提诚实揭露久坐体态。", "try pilates classes twice weekly for posture"),
  v("meditation-app-streaks-versus-real-stillness-debate", "/冥想（变体）", "/ˌmedɪˈteɪʃn/", "n.", 5, 0.4, "Meditation streaks matter less than single honest breaths.", "冥想连续打卡不如一次真正的静心呼吸。", "restart meditation habits gently without judgment"),
  v("journaling-morning-pages-brain-drain-method-fans", "/写日记；日志", "/ˈdʒɜːrnəlɪŋ/", "n.", 6, 0.5, "Journaling deletes mental browser tabs nightly.", "写日志每晚清空大脑标签页。", "keep journaling prompts short on busy days"),
  v("blogging-niche-passion-monetization-eventual-conversations", "/写博客", "/ˈblɔːɡɪŋ/", "n.", 6, 0.55, "Blogging pays in readers before it pays rent.", "写博客先收获读者，再谈收入。", "post blogging schedules consistently over perfection"),
  v("podcasting-two-microphones-one-garage-dream-origin-story", "/播客制作", "/ˈpɑːdkæstɪŋ/", "n.", 7, 0.6, "Podcasting starts with opinions and ends with editing.", "播客始于观点，终于剪辑。", "outline podcasting episodes before pressing record"),
  v("genealogy-family-tree-brick-wall-breakthrough-celebrations", "/家谱学；系谱学", "/ˌdʒiːniˈælədʒi/", "n.", 7, 0.75, "Genealogy turns dusty courthouses into treasure maps.", "家谱学让积灰的法院档案室变藏宝图。", "interview genealogy relatives before stories fade"),
  v("language-learning-app-streaks-versus-real-conversations-gap", "/语言学习", "/ˈlæŋɡwɪdʒ ˈlɜːrnɪŋ/", "n.", 4, 0.3, "Language learning lives or dies in real conversations.", "语言学习成败在真实对话里。", "pair language learning apps with weekly meetups"),
];
