import { cv, type C2VocabRow } from "@/content/vocab/c2-types";

/** Phase 15-A · g151 C1 Academic — research & argument core. */
export const c1AcademicRows: C2VocabRow[] = [
  cv("nuanced", "/ˈnjuːɑːnst/", "adj.", "细微差别的；精细的", "C1", "academic", "both", "指区分微妙差异的观点或表达，比 detailed 更强调层次", "Her nuanced reading of the data impressed the panel.", "她对数据的细致解读令评审团印象深刻。", "a nuanced argument", ["subtle", "fine-grained"], ["crude", "simplistic"]),
  cv("empirical", "/ɪmˈpɪrɪkl/", "adj.", "实证的；经验的", "C1", "academic", "written", "基于观察实验而非理论推演，学术写作高频", "The claim lacks empirical support.", "该主张缺乏实证支持。", "empirical evidence", ["observable", "data-driven"], ["theoretical", "speculative"]),
  cv("corroborate", "/kəˈrɒbəreɪt/", "v.", "佐证；印证", "C1", "formal", "written", "用独立来源支持某说法，比 confirm 更正式", "Two witnesses corroborated her account.", "两名证人印证了她的说法。", "corroborate a claim", ["confirm", "substantiate"], ["contradict", "refute"]),
  cv("juxtapose", "/ˌdʒʌkstəˈpoʊz/", "v.", "并置对比", "C2", "academic", "written", "把不同事物并列以凸显反差", "The essay juxtaposes wealth and poverty.", "文章将贫富并置对比。", "juxtapose X with Y", ["contrast"], ["separate"]),
  cv("paradigm", "/ˈpærədaɪm/", "n.", "范式；典范", "C1", "academic", "both", "一套主导性的理论框架或模式", "The discovery shifted the dominant paradigm.", "这一发现改变了主流范式。", "a new paradigm", ["model", "framework"], []),
  cv("rigorous", "/ˈrɪɡərəs/", "adj.", "严谨的；严格的", "C1", "academic", "both", "强调过程彻底、标准高", "The study followed rigorous methods.", "研究采用了严谨的方法。", "rigorous testing", ["thorough", "strict"], ["loose", "careless"]),
  cv("tentative", "/ˈtentətɪv/", "adj.", "试探性的；暂定的", "C1", "academic", "both", "结论留有余地，不武断", "We drew a tentative conclusion.", "我们得出了初步结论。", "tentative conclusions", ["provisional", "preliminary"], ["definitive"]),
  cv("underpin", "/ˌʌndərˈpɪn/", "v.", "支撑；构成基础", "C1", "formal", "written", "作为底层依据支持上层结构", "Trust underpins every contract.", "信任是一切契约的基础。", "underpin the theory", ["support", "sustain"], ["undermine"]),
  cv("salient", "/ˈseɪliənt/", "adj.", "显著的；突出的", "C1", "formal", "written", "在诸多细节中最值得注意的", "The most salient point is cost.", "最突出的一点是成本。", "a salient feature", ["prominent", "noticeable"], ["minor"]),
  cv("anomaly", "/əˈnɒməli/", "n.", "异常；反常现象", "C1", "academic", "both", "偏离预期模式的数据点", "The anomaly prompted further study.", "这一异常促使进一步研究。", "a statistical anomaly", ["outlier", "irregularity"], ["norm"]),
  cv("construe", "/kənˈstruː/", "v.", "解读；理解为", "C2", "formal", "written", "强调按某种方式诠释，常有争议空间", "His silence was construed as consent.", "他的沉默被解读为同意。", "construe X as Y", ["interpret"], ["misread"]),
  cv("epitomize", "/ɪˈpɪtəmaɪz/", "v.", "是…的典型化身", "C2", "formal", "written", "集中体现某类事物的本质", "The case epitomizes urban decline.", "该案例是城市衰退的典型。", "epitomize an era", ["exemplify"], []),
  cv("ostensibly", "/ɒˈstensəbli/", "adv.", "表面上地", "C2", "formal", "written", "暗示表象之下另有真相", "Ostensibly, the meeting was about budgets.", "表面上看，会议讨论的是预算。", "ostensibly for safety", ["apparently"], ["genuinely"]),
  cv("substantiate", "/səbˈstænʃieɪt/", "v.", "证实；使有根据", "C1", "formal", "written", "提供具体证据使主张成立", "Documents substantiated the allegations.", "文件证实了这些指控。", "substantiate a claim", ["verify"], ["disprove"]),
  cv("tenuous", "/ˈtenjuəs/", "adj.", "牵强的；脆弱的", "C2", "formal", "written", "论据薄弱、联系勉强", "The link remains tenuous.", "这一关联仍然牵强。", "a tenuous link", ["flimsy", "weak"], ["solid"]),
  cv("ubiquitous", "/juːˈbɪkwɪtəs/", "adj.", "无处不在的", "C1", "formal", "both", "强调普遍到几乎注意不到", "Smartphones are ubiquitous now.", "如今智能手机无处不在。", "ubiquitous technology", ["pervasive", "omnipresent"], ["scarce", "rare"]),
  cv("vindicate", "/ˈvɪndɪkeɪt/", "v.", "为…正名；证实无辜", "C2", "formal", "written", "事后证明某人/做法正确", "Time vindicated her decision.", "时间证明她的决定是对的。", "vindicate sb's choice", ["justify", "exonerate"], ["condemn"]),
  cv("caveat", "/ˈkæviæt/", "n.", "警告性附注；限制条件", "C1", "formal", "both", "正式声明前的重要保留意见", "One caveat applies here.", "这里有一个前提需要注意。", "with one caveat", ["qualification"], []),
  cv("delineate", "/dɪˈlɪnieɪt/", "v.", "清晰勾勒；划定", "C2", "formal", "written", "精确描述边界或要素", "The report delineates three options.", "报告清晰地列出三个选项。", "delineate boundaries", ["outline", "demarcate"], ["blur"]),
  cv("extrapolate", "/ɪkˈstræpəleɪt/", "v.", "外推；推断延伸", "C1", "academic", "both", "由已知趋势推测未知区间", "We extrapolated costs to 2030.", "我们将成本外推至2030年。", "extrapolate from data", ["project"], ["interpolate"]),
  cv("fallacy", "/ˈfæləsi/", "n.", "谬误", "C1", "academic", "written", "逻辑上站不住的论证", "That argument rests on a fallacy.", "那个论证建立在一个谬误之上。", "a logical fallacy", ["misconception"], ["validity"]),
  cv("impetus", "/ˈɪmpɪtəs/", "n.", "推动力；动因", "C1", "formal", "written", "触发并维持发展的力量", "The crisis gave impetus to reform.", "危机推动了改革。", "give impetus to", ["momentum", "stimulus"], ["hindrance"]),
  cv("innocuous", "/ɪˈnɒkjuəs/", "adj.", "无害的；无关痛痒的", "C2", "formal", "written", "看似毫无威胁（常与实际后果对照）", "An innocuous comment sparked outrage.", "一句无心之言引发众怒。", "an innocuous remark", ["harmless", "benign"], ["noxious"]),
  cv("mitigate", "/ˈmɪtɪɡeɪt/", "v.", "缓解；减轻", "C1", "formal", "both", "降低严重程度而非根除", "Trees mitigate urban heat.", "树木能缓解城市高温。", "mitigate risks", ["alleviate", "reduce"], ["aggravate"]),
  cv("prudent", "/ˈpruːdnt/", "adj.", "审慎的；明智的", "C1", "formal", "both", "强调权衡风险后的克制", "Prudent investors diversify.", "审慎的投资者会分散投资。", "a prudent decision", ["cautious", "judicious"], ["reckless"]),
  cv("rebut", "/rɪˈbʌt/", "v.", "反驳；驳斥", "C1", "formal", "written", "以论证正面击破对方观点", "She rebutted each charge in turn.", "她逐条反驳了各项指控。", "rebut an allegation", ["refute", "counter"], ["endorse"]),
  cv("scrutinize", "/ˈskruːtənaɪz/", "v.", "细察；审视", "C1", "formal", "both", "带批判性地仔细检查", "Regulators scrutinized the merger.", "监管机构审查了这次并购。", "scrutinize closely", ["examine", "inspect"], ["ignore"]),
  cv("tacit", "/ˈtæsɪt/", "adj.", "心照不宣的；默示的", "C2", "formal", "written", "未明说但被理解的共识", "There was tacit agreement to postpone.", "大家心照不宣地同意延期。", "tacit approval", ["implicit", "unspoken"], ["explicit"]),
  cv("underscore", "/ˌʌndərˈskɔːr/", "v.", "强调；凸显", "C1", "formal", "written", "用事实强化某一论点的重要性", "The delay underscores the risk.", "延误凸显了风险。", "underscore the need", ["emphasize", "highlight"], ["downplay"]),
  cv("wield", "/wiːld/", "v.", "行使；掌握（权力/影响）", "C2", "formal", "written", "对抽象权力/工具的实际运用", "Ministers wield enormous power.", "部长们手握大权。", "wield influence", ["exercise"], ["surrender"]),
];
