import { v } from "@/content/vocab/builder";
import type { VocabRow } from "@/content/vocab/types";

export const timeAdverbsRows: VocabRow[] = [
  v("always", "/总是", "/ˈɔːlweɪz/", "adv.", 1, 0.15, "I always eat breakfast.", "我总是吃早餐。", "not alwaysalways late"),
  v("usually", "/通常", "/ˈjuːʒuəli/", "adv.", 1, 0.2, "We usually walk.", "我们通常走路去。", "as usual"),
  v("often", "/经常", "/ˈɔːfn/", "adv.", 1, 0.2, "She often smiles.", "她常微笑。", "more often"),
  v("sometimes", "/有时", "/ˈsʌmtaɪmz/", "adv.", 1, 0.2, "Sometimes I forget.", "有时我会忘。", "at timessometimes busy"),
  v("rarely", "/很少", "/ˈrerli/", "adv.", 2, 0.25, "He rarely complains.", "他很少抱怨。", "rarely seenrarely"),
  v("never", "/从不", "/ˈnevər/", "adv.", 1, 0.15, "Never give up!", "永不放弃！", "never mind"),
  v("soon", "/很快；不久", "/suːn/", "adv.", 1, 0.15, "See you soon!", "回头见！", "as soon as possible"),
  v("already", "/已经", "/ɔːlˈredi/", "adv.", 1, 0.25, "Already done?", "已经完成了？", "yet alreadyalready finished"),
  v("yet", "/还（没）；已经", "/jet/", "adv./conj.", 1, 0.3, "Not yet.", "还没有。", "not yet"),
  v("still", "/仍然", "/stɪl/", "adv./adj.", 1, 0.2, "Still here.", "还在这儿。", "stay still"),
  v("just", "/刚刚；只是", "/dʒʌst/", "adv.", 1, 0.2, "Just five minutes.", "只要五分钟。", "just now"),
  v("almost", "/几乎", "/ˈɔːlmoʊst/", "adv.", 1, 0.2, "Almost done!", "快好了！", "almost neveralmost ready"),
  v("enough", "/足够", "/ɪˈnʌf/", "adj./adv.", 1, 0.2, "Enough talk.", "说够了。", "good enough"),
  v("maybe", "/也许", "/ˈmeɪbi/", "adv.", 1, 0.2, "Maybe tomorrow.", "也许明天吧。", "maybe yesmaybe later"),
  v("probably", "/大概", "/ˈprɑːbəbli/", "adv.", 1, 0.2, "Probably right.", "大概是对的。", "most probablyprobably"),
  v("suddenly", "/突然", "/ˈsʌdnli/", "adv.", 1, 0.25, "Suddenly it rained.", "天突然下雨了。", "all of a suddensuddenly"),
  v("finally", "/终于", "/ˈfaɪnəli/", "adv.", 1, 0.2, "Finally home!", "终于到家了！", "finally donefinally"),
  v("immediately", "/立即", "/ɪˈmiːdiətli/", "adv.", 1, 0.3, "Call immediately.", "立刻打电话。", "right awayimmediately"),
  v("recently", "/最近", "/ˈriːsntli/", "adv.", 1, 0.25, "Recently very busy.", "最近很忙。", "until recentlyrecently"),
  v("twice", "/两次；两倍", "/twaɪs/", "adv.", 1, 0.2, "Twice a week.", "每周两次。", "think twice"),
  v("once", "/一次；曾经", "/wʌns/", "adv.", 1, 0.2, "Once a month.", "每月一次。", "at once"),
  v("daily", "/每日的", "/ˈdeɪli/", "adj./adv.", 1, 0.2, "Daily practice wins.", "每天练习才是王道。", "daily life"),
  v("weekly", "/每周的", "/ˈwiːkli/", "adj./adv.", 1, 0.2, "Weekly meetings help.", "周会有用。", "a weekly planweekly"),
  v("forever", "/永远", "/fərˈevər/", "adv.", 1, 0.2, "Forever grateful.", "永远感激。", "takes forever"),
  v("quickly", "/快速地", "/ˈkwɪkli/", "adv.", 1, 0.2, "Answer quickly.", "快点回答。", "so quicklyquickly"),
  v("slowly", "/慢慢地", "/ˈsloʊli/", "adv.", 1, 0.2, "Speak slowly, please.", "请慢点说。", "slowly but surely"),
  v("really", "/真正地；很", "/ˈriːəli/", "adv.", 1, 0.2, "Really good!", "真的好！", "really good"),
  v("quite", "/相当", "/kwaɪt/", "adv.", 1, 0.25, "Quite easy.", "挺容易的。", "quite a lot"),
  v("rather", "/宁愿；相当", "/ˈræðər/", "adv.", 2, 0.3, "Rather stay home.", "更想待在家。", "or ratherrather than"),
  v("during", "/在……期间", "/ˈdʊrɪŋ/", "prep.", 1, 0.2, "During class, listen.", "课上要听讲。", "during the day"),
  v("while", "/当……时；然而", "/waɪl/", "conj./n.", 1, 0.25, "Wait while I check.", "等我查一下。", "in a while"),
  v("before", "/在……之前", "/bɪˈfɔːr/", "prep./conj.", 1, 0.2, "Before you go,", "你走之前，", "before long"),
  v("after", "/在……之后", "/ˈæftər/", "prep./conj.", 1, 0.15, "After dinner, walk.", "晚饭后散步。", "day after day"),
  v("until", "/直到", "/ənˈtɪl/", "prep./conj.", 1, 0.2, "Wait until six.", "等到六点。", "up until nowuntil now"),
  v("since", "/自从；既然", "/sɪns/", "prep./conj.", 1, 0.25, "Since Monday, rain.", "从周一就下雨。", "ever since"),
  v("together", "/一起", "/təˈɡeðər/", "adv.", 1, 0.2, "Study together.", "一起学习。", "work togethertogether"),
  v("alone", "/独自的", "/əˈloʊn/", "adj./adv.", 1, 0.2, "Eat alone today.", "今天一个人吃。", "leave me alonealone at home"),
];