import { v } from "@/content/vocab/builder";
import type { VocabRow } from "@/content/vocab/types";

export const kitchenCookingRows: VocabRow[] = [
  v("stove", "/炉灶", "/stoʊv/", "n.", 1, 0.2, "Hot stove!", "灶台烫！", "on the stove"),
  v("oven", "/烤箱", "/ˈʌvn/", "n.", 1, 0.2, "Preheat the oven.", "预热烤箱。", "in the oven"),
  v("microwave", "/微波炉", "/ˈmaɪkroʊweɪv/", "n./v.", 1, 0.2, "Microwave it for one minute.", "微波一分钟。", "the microwave"),
  v("fridge", "/冰箱", "/frɪdʒ/", "n.", 1, 0.15, "Milk in the fridge.", "冰箱里有牛奶。", "in the fridge"),
  v("freezer", "/冰柜", "/ˈfriːzər/", "n.", 2, 0.2, "Ice in the freezer.", "冰柜里有冰。", "the freezer"),
  v("counter", "/柜台；台面", "/ˈkaʊntər/", "n.", 1, 0.2, "On the counter.", "在台面上。", "kitchen counter"),
  v("pan", "/平底锅", "/pæn/", "n.", 1, 0.15, "A hot pan.", "热锅。", "frying pan"),
  v("pot", "/锅；壶", "/pɑːt/", "n.", 1, 0.15, "A big pot of soup.", "一大锅汤。", "a pot of teapots and pans"),
  v("bowl", "/碗", "/boʊl/", "n.", 1, 0.1, "A bowl of rice.", "一碗米饭。", "a bowl of soup"),
  v("tray", "/托盘", "/treɪ/", "n.", 1, 0.2, "Food tray here.", "餐盘在这。", "a tray of"),
  v("napkin", "/餐巾", "/ˈnæpkɪn/", "n.", 2, 0.2, "Need a napkin.", "需要餐巾纸。", "paper napkinsa napkin"),
  v("apron", "/围裙", "/ˈeɪprən/", "n.", 3, 0.3, "Dad wears an apron.", "爸爸系着围裙。", "an apron"),
  v("recipe", "/食谱", "/ˈresəpi/", "n.", 1, 0.25, "Grandma's recipe.", "奶奶的食谱。", "follow a recipea recipe"),
  v("ingredient", "/食材；成分", "/ɪnˈɡriːdiənt/", "n.", 2, 0.35, "Fresh ingredients only.", "只用新鲜食材。", "ingredients"),
  v("steam", "/蒸汽；蒸", "/stiːm/", "n./v.", 1, 0.25, "Steam the vegetables.", "蒸蔬菜。", "steamed ricesteam"),
  v("roast", "/烤(肉)", "/roʊst/", "v./n.", 2, 0.3, "Roast a chicken.", "烤只鸡。", "roast chicken"),
  v("grill", "/烧烤；烤架", "/ɡrɪl/", "v./n.", 1, 0.2, "Grill outside today?", "今天外面烤肉？", "grill itthe grill"),
  v("chop", "/切；砍", "/tʃɑːp/", "v.", 1, 0.2, "Chop onions fast.", "快速切洋葱。", "chop woodchop finelychop"),
  v("slice", "/切片", "/slaɪs/", "v./n.", 1, 0.2, "Slice the bread.", "把面包切片。", "a slice of bread"),
  v("peel", "/削皮", "/piːl/", "v./n.", 2, 0.25, "Peel the apple.", "给苹果削皮。", "apple peelpeel it"),
  v("stir", "/搅拌", "/stɜːr/", "v.", 1, 0.2, "Stir the soup.", "搅一下汤。", "give it a stirstir well"),
  v("pour", "/倒", "/pɔːr/", "v.", 1, 0.2, "Pour the milk.", "倒牛奶。", "pour out"),
  v("mix", "/混合", "/mɪks/", "v./n.", 1, 0.2, "Mix it well.", "拌匀。", "mixed feelingsmix well"),
  v("dish", "/菜肴；盘子", "/dɪʃ/", "n.", 1, 0.2, "My favorite dish.", "我最爱的菜。", "wash the dishes"),
  v("dishwasher", "/洗碗机", "/ˈdɪʃwɑːʃər/", "n.", 1, 0.2, "Load the dishwasher.", "把碗放进洗碗机。", "a dishwasher"),
  v("toaster", "/烤面包机", "/ˈtoʊstər/", "n.", 1, 0.2, "Bread in the toaster.", "面包进烤机。", "a toaster"),
  v("spice", "/香料", "/spaɪs/", "n.", 2, 0.3, "Add spices slowly.", "香料慢慢加。", "spicy foodspices"),
  v("ginger", "/姜", "/ˈdʒɪndʒər/", "n.", 3, 0.25, "Ginger tea warms you.", "姜茶暖身。", "ginger tea"),
  v("vinegar", "/醋", "/ˈvɪnɪɡər/", "n.", 3, 0.3, "A little vinegar.", "一点醋。", "rice vinegarvinegar"),
];