import { v } from "@/content/vocab/builder";
import type { VocabRow } from "@/content/vocab/types";

export const opinionQualityRows: VocabRow[] = [
  v("wonderful", "/精彩的", "/ˈwʌndərfl/", "adj.", 1, 0.2, "Wonderful news!", "好消息！", "a wonderful daywonderful"),
  v("terrible", "/糟糕的", "/ˈterəbl/", "adj.", 1, 0.2, "Terrible traffic.", "堵得要命。", "feel terribleterrible"),
  v("awful", "/很糟的", "/ˈɔːfl/", "adj.", 1, 0.2, "Awful weather.", "鬼天气。", "an awful dayawful"),
  v("excellent", "/优秀的", "/ˈeksələnt/", "adj.", 1, 0.25, "Excellent work!", "干得漂亮！", "excellent qualityexcellent"),
  v("perfect", "/完美的", "/ˈpɜːrfɪkt/", "adj.", 1, 0.2, "Perfect timing.", "时机完美。", "practice makes perfectperfect"),
  v("normal", "/正常的", "/ˈnɔːrml/", "adj.", 1, 0.2, "Normal day today.", "平常的一天。", "back to normalnormal"),
  v("strange", "/奇怪的", "/streɪndʒ/", "adj.", 1, 0.2, "Strange noise outside.", "外面有怪声。", "a strange ideahow strange"),
  v("weird", "/怪异的", "/wɪrd/", "adj.", 1, 0.2, "Weird dream last night.", "昨晚的梦很怪。", "kind of weirdweird"),
  v("common", "/常见的；共同的", "/ˈkɑːmən/", "adj.", 1, 0.2, "A common mistake.", "常见错误。", "common groundcommon"),
  v("usual", "/通常的", "/ˈjuːʒuəl/", "adj.", 1, 0.2, "Same as usual.", "老样子。", "as usualmy usual table"),
  v("unusual", "/不寻常的", "/ʌnˈjuːʒuəl/", "adj.", 2, 0.3, "An unusual color.", "少见的颜色。", "unusual weatherunusual"),
  v("special", "/特别的", "/ˈspeʃl/", "adj.", 1, 0.2, "Nothing special.", "没什么特别。", "special offerspecial"),
  v("general", "/总体的；大致的", "/ˈdʒenərl/", "adj.", 1, 0.25, "General idea first.", "先说大概。", "in general"),
  v("main", "/主要的", "/meɪn/", "adj.", 1, 0.2, "The main road.", "主干道。", "the main thingmain streetthe main"),
  v("basic", "/基础的", "/ˈbeɪsɪk/", "adj.", 1, 0.2, "Basic English first.", "先学基础英语。", "basic needsbasic"),
  v("simple", "/简单的", "/ˈsɪmpl/", "adj.", 1, 0.15, "Keep it simple.", "简单点。", "simple foodsimple"),
  v("double", "/两倍；双", "/ˈdʌbl/", "adj./v.", 1, 0.25, "Double check it.", "再检查一遍。", "double roomdouble-checkdouble"),
  v("single", "/单个的；单身的", "/ˈsɪŋɡl/", "adj.", 1, 0.2, "A single ticket.", "单程票。", "single rooma single"),
  v("male", "/男性的", "/meɪl/", "adj./n.", 1, 0.25, "Male or female?", "男性还是女性？", "male and femalemale"),
  v("female", "/女性的", "/ˈfiːmeɪl/", "adj./n.", 1, 0.25, "Female voices sing hereFemale students lead.", "女生领唱。", "a female doctorfemale"),
  v("local", "/当地的", "/ˈloʊkl/", "adj./n.", 1, 0.2, "Local honey is best.", "本地蜂蜜最好。", "local foodlocal"),
  v("foreign", "/外国的", "/ˈfɔːrən/", "adj.", 1, 0.25, "Foreign languages help.", "外语有用。", "foreign countriesforeign"),
  v("national", "/国家的", "/ˈnæʃnəl/", "adj.", 1, 0.25, "National holiday soon.", "国庆快到。", "national parknational"),
  v("official", "/官方的", "/əˈfɪʃl/", "adj./n.", 1, 0.25, "Official news only.", "只信官方消息。", "an official statementofficial"),
  v("personal", "/个人的", "/ˈpɜːrsənl/", "adj.", 1, 0.2, "My personal opinion.", "我的个人看法。", "personal informationpersonal"),
  v("natural", "/自然的", "/ˈnætʃrəl/", "adj.", 1, 0.2, "Natural light helps.", "自然光有益。", "natural foodnatural"),
  v("international", "/国际的", "/ˌɪntərˈnæʃnəl/", "adj.", 1, 0.25, "International calls cost more.", "国际长途贵些。", "an international flightinternational"),
  v("central", "/中心的", "/ˈsentrəl/", "adj.", 1, 0.25, "Central heating on.", "暖气开了。", "central parkcentral"),
  v("western", "/西方的；西部的", "/ˈwestərn/", "adj.", 1, 0.25, "Western food tonight.", "今晚吃西餐。", "western movieswestern"),
  v("southern", "/南方的", "/ˈsʌðərn/", "adj.", 1, 0.25, "Southern cooking.", "南方菜。", "the southern sidesouthern"),
  v("northern", "/北方的", "/ˈnɜːrðərn/", "adj.", 1, 0.25, "Northern cities are cold.", "北方城市冷。", "northern lightsnorthern"),
  v("ideal", "/理想的", "/aɪˈdiːəl/", "adj./n.", 3, 0.35, "Ideal weather for a walk.", "散步的理想天气。", "ideal conditionsideal"),
  v("necessary", "/必要的", "/ˈnesəseri/", "adj.", 1, 0.3, "Sleep is necessary.", "睡眠是必需的。", "if necessary"),
  v("important", "/重要的", "/ɪmˈpɔːrtnt/", "adj.", 1, 0.15, "Important call coming.", "重要来电。", "very importantimportant"),
  v("huge", "/巨大的", "/hjuːdʒ/", "adj.", 1, 0.2, "A huge success!", "巨大成功！", "a huge differencehuge"),
  v("tiny", "/极小的", "/ˈtaɪni/", "adj.", 1, 0.2, "A tiny kitchen.", "小厨房。", "a tiny bittiny"),
  v("giant", "/巨大的；巨人", "/ˈdʒaɪənt/", "adj./n.", 1, 0.2, "Giant panda cubs sleep a lotGiant pandas eat bamboo.", "大熊猫吃竹子。", "a giant stepgiant"),
  v("major", "/主要的；专业", "/ˈmeɪdʒər/", "adj./n.", 1, 0.25, "Major changes coming.", "重大变化将至。", "a major citymajor"),
  v("minor", "/较小的", "/ˈmaɪnər/", "adj.", 1, 0.3, "Minor problem only.", "只是小问题。", "a minor detailminor"),
  v("ordinary", "/普通的", "/ˈɔːrdəneri/", "adj.", 2, 0.3, "Ordinary people win too.", "普通人也能赢。", "out of the ordinaryordinary"),
  v("typical", "/典型的", "/ˈtɪpɪkl/", "adj.", 1, 0.3, "Typical Monday.", "典型周一。", "a typical daytypical"),
  v("whole", "/整个的", "/hoʊl/", "adj./n.", 1, 0.2, "The whole story.", "完整的故事。", "on the wholethe whole day"),
  v("entire", "/全部的", "/ɪnˈtaɪər/", "adj.", 1, 0.25, "The entire team agrees.", "全队同意。", "the entire time"),
  v("extra", "/额外的", "/ˈekstrə/", "adj./adv.", 1, 0.2, "Extra time today.", "今天有富余时间。", "extra workextra"),
  v("spare", "/备用的；空闲的", "/sper/", "adj./v.", 1, 0.25, "Spare key inside.", "备用钥匙在里面。", "spare time"),
];