import { v } from "@/content/vocab/builder";
import type { VocabRow } from "@/content/vocab/types";

export const verbsSocial3Rows: VocabRow[] = [
  v("greet", "/问候", "/ɡriːt/", "v.", 2, 0.25, "Greet guests warmly.", "热情迎客。", "greet someone"),
  v("welcome-v", "/欢迎", "/ˈwelkəm/", "v./adj.", 1, 0.15, "Welcome them in.", "请他们进来。", "you are welcome"),
  v("respect-v", "/尊重", "/rɪˈspekt/", "v./n.", 1, 0.25, "Respect different views.", "尊重不同看法。", "mutual respectrespect"),
  v("admire", "/钦佩", "/ədˈmaɪər/", "v.", 2, 0.3, "I admire teachers.", "我敬佩老师。", "admire someoneadmire"),
  v("appreciate", "/感激；欣赏", "/əˈpriːʃieɪt/", "v.", 1, 0.3, "I appreciate it.", "我很感激。", "appreciate your helpappreciate"),
  v("congratulate", "/祝贺", "/kənˈɡrætʃuleɪt/", "v.", 3, 0.4, "Congratulate the winnersCongratulate her!", "祝贺她！", "congratulations"),
  v("encourage", "/鼓励", "/ɪnˈkɜːrɪdʒ/", "v.", 1, 0.25, "Encourage beginners.", "鼓励初学者。", "encourage someone to"),
  v("convince", "/说服", "/kənˈvɪns/", "v.", 2, 0.35, "Convince me first.", "先说服我。", "convince someone thatconvince"),
  v("attract", "/吸引", "/əˈtrækt/", "v.", 1, 0.3, "Opposites attract?", "异性相吸？", "attract attentionattract"),
  v("impress", "/留下印象", "/ɪmˈpres/", "v.", 1, 0.3, "Impress the judges.", "打动评委。", "impress the bossimpress"),
  v("express", "/表达", "/ɪkˈspres/", "v.", 1, 0.25, "Express yourself clearly.", "清晰表达自己。", "express feelingsexpress"),
  v("share", "/分享", "/ʃer/", "v.", 1, 0.15, "Share your notes.", "分享笔记。", "share with friendsshare"),
  v("send", "/发送", "/send/", "v.", 1, 0.15, "Send it tonight.", "今晚发出去。", "send a message"),
  v("receive", "/收到", "/rɪˈsiːv/", "v.", 1, 0.25, "Receive an email.", "收到邮件。", "receive a giftreceive"),
  v("reply", "/回复", "/rɪˈplaɪ/", "v./n.", 1, 0.2, "Reply quickly.", "快点回复。", "reply to"),
  v("forward-v", "/转发；向前", "/ˈfɔːrwərd/", "v./adv.", 1, 0.25, "Forward the email.", "转发邮件。", "look forward toforward"),
  v("upload", "/上传", "/ˌʌpˈloʊd/", "v./n.", 1, 0.25, "Upload the video.", "上传视频。", "upload photosupload"),
  v("download", "/下载", "/ˈdaʊnloʊd/", "v./n.", 1, 0.2, "Download the app.", "下载应用。", "download speeddownload"),
  v("print", "/打印", "/prɪnt/", "v./n.", 1, 0.2, "Print two copies.", "打印两份。", "print outprint"),
  v("sign-v", "/签名", "/saɪn/", "v.", 1, 0.2, "Sign your name here.", "在这里签名。", "sign upsign"),
  v("submit", "/提交", "/səbˈmɪt/", "v.", 1, 0.25, "Submit before Friday.", "周五前提交。", "submit a formsubmit"),
  v("register", "/注册", "/ˈredʒɪstər/", "v./n.", 1, 0.25, "Register online first.", "先网上注册。", "register for classregister"),
  v("book-v", "/预订", "/bʊk/", "v.", 1, 0.2, "Book early to save.", "早订省钱。", "book a roombook"),
  v("cancel", "/取消", "/ˈkænsl/", "v.", 1, 0.2, "Cancel my order.", "取消订单。", "call offcancel"),
  v("confirm", "/确认", "/kənˈfɜːrm/", "v.", 1, 0.2, "Confirm the time, please.", "请确认时间。", "confirm bookingconfirm"),
  v("deliver", "/递送", "/dɪˈlɪvər/", "v.", 1, 0.2, "They deliver fast.", "他们送货快。", "deliver fooddeliverydeliver"),
  v("pack", "/打包", "/pæk/", "v./n.", 1, 0.2, "Pack lightly.", "轻装出行。", "pack uppack"),
  v("wrap", "/包裹；缠绕", "/ræp/", "v./n.", 1, 0.2, "Wrap the gift nicely.", "把礼物包漂亮点。", "wrap giftswrap"),
  v("tie", "/系；领带", "/taɪ/", "v./n.", 1, 0.2, "Tie your shoes.", "系鞋带。", "tie a knotties"),
  v("untie", "/解开", "/ʌnˈtaɪ/", "v.", 4, 0.35, "Untie the rope.", "解开绳子。", "untie"),
  v("bend", "/弯曲", "/bend/", "v./n.", 2, 0.3, "Bend your knees.", "屈膝。", "bend down"),
  v("stretch", "/伸展", "/stretʃ/", "v./n.", 1, 0.25, "Stretch before running.", "跑步前拉伸。", "stretch out"),
];