import { v } from "@/content/vocab/builder";
import type { VocabRow } from "@/content/vocab/types";

/** Shopping & customer service - Day 31+ shopping theme. */
export const shoppingServiceRows: VocabRow[] = [
  v("aisle", "/(货架间的)过道", "/aɪl/", "n.", 4, 0.3, "The cereal is in aisle five.", "麦片在第五过道。", "in aisle five"),
  v("barcode", "/条形码", "/ˈbɑːrkoʊd/", "n.", 5, 0.35, "Scan the barcode at checkout.", "结账时扫描条形码。", "scan a barcode"),
  v("carton", "/纸盒；纸箱", "/ˈkɑːrtn/", "n.", 4, 0.3, "Buy a carton of milk.", "买一盒牛奶。", "a carton of milk"),
  v("coupon", "/优惠券", "/ˈkuːpɑːn/", "n.", 4, 0.3, "She clipped coupons before shopping.", "她购物前剪了优惠券。", "use a coupon"),
  v("checkout", "/收银台；结账", "/ˈtʃekaʊt/", "n.", 3, 0.3, "The line at checkout is long.", "收银台的队伍很长。", "at the checkout"),
  v("self-checkout", "/自助结账机", "/ˌself ˈtʃekaʊt/", "n.", 4, 0.35, "Use the self-checkout to skip the line.", "用自助结账机免排队。", "a self-checkout machine"),
  v("membership", "/会员资格", "/ˈmembərʃɪp/", "n.", 4, 0.35, "A membership saves ten percent.", "会员能省百分之十。", "renew a membership"),
  v("warehouse", "/仓库；仓储式商店", "/ˈwerhaʊs/", "n.", 4, 0.35, "Warehouse stores sell in bulk.", "仓储商店按批量卖货。", "a warehouse store"),
  v("bargain", "/便宜货；讨价还价", "/ˈbɑːrɡən/", "n./v.", 3, 0.35, "These shoes were a real bargain.", "这双鞋真便宜。", "get a bargain"),
  v("trolley", "/购物车(英)", "/ˈtrɑːli/", "n.", 4, 0.3, "Grab a trolley near the entrance.", "在入口处拿辆购物车。", "push a trolley"),
  v("voucher", "/代金券", "/ˈvaʊtʃər/", "n.", 5, 0.45, "This voucher gives you a free drink.", "这张券可以换一杯免费饮料。", "redeem a voucher"),
  v("installment", "/分期付款", "/ɪnˈstɔːlmənt/", "n.", 5, 0.5, "We pay for the sofa in installments.", "沙发我们是分期付款的。", "pay in installments"),
  v("warranty", "/保修单", "/ˈwɔːrənti/", "n.", 5, 0.45, "The laptop is still under warranty.", "这台笔记本还在保修期内。", "under warranty"),
  v("boutique", "/精品店", "/buːˈtiːk/", "n.", 5, 0.45, "She opened a small clothing boutique.", "她开了一家小服装精品店。", "a local boutique"),
  v("outlet", "/折扣店；插座", "/ˈaʊtlet/", "n.", 4, 0.35, "Outlet malls sell brand items cheaply.", "奥特莱斯卖的品牌商品很便宜。", "an outlet mall"),
  v("secondhand", "/二手的", "/ˌsekənd ˈhænd/", "adj.", 4, 0.3, "He bought a secondhand bike.", "他买了一辆二手自行车。", "secondhand books"),
  v("fitting-room", "/试衣间", "/ˈfɪtɪŋ ruːm/", "n.", 3, 0.3, "The fitting-room is over there.", "试衣间在那边。", "try it on in the fitting-room"),
  v("gift-card", "/礼品卡", "/ˈɡɪft kɑːrd/", "n.", 3, 0.25, "I gave her a fifty-dollar gift-card.", "我给了她一张五十美元的礼品卡。", "a gift-card for a store"),
  v("grocery", "/食品杂货", "/ˈɡroʊsəri/", "n.", 2, 0.25, "We do the grocery shopping on Sundays.", "我们每周日买食品杂货。", "a grocery run"),
  v("department-store", "/百货商店", "/dɪˈpɑːrtmənt stɔːr/", "n.", 3, 0.3, "The department-store opens at nine.", "百货商店九点开门。", "work at a department-store"),
  v("purchase", "/购买", "/ˈpɜːrtʃəs/", "v./n.", 4, 0.4, "Keep your purchase receipt safe.", "保管好你的购物小票。", "make a purchase"),
  v("browse", "/浏览；随便看看", "/braʊz/", "v.", 3, 0.3, "I'm just browsing, thanks.", "我只是随便看看，谢谢。", "browse online stores"),
  v("queue", "/排队", "/kjuː/", "n./v.", 3, 0.35, "The queue moves slowly.", "队伍移动得很慢。", "wait in the queue"),
  v("stock", "/存货；库存", "/stɑːk/", "n./v.", 4, 0.35, "That size is out of stock.", "那个尺码断货了。", "out of stock"),
  v("courier", "/快递员", "/ˈkʊriər/", "n.", 4, 0.35, "The courier left the box at the door.", "快递员把箱子放在门口。", "a courier service"),
  v("parcel", "/包裹", "/ˈpɑːrsl/", "n.", 3, 0.3, "A parcel arrived this morning.", "今天早上到了一个包裹。", "wrap a parcel"),
  v("shipping", "/运送；(运)费", "/ˈʃɪpɪŋ/", "n.", 3, 0.3, "Shipping is free over fifty dollars.", "满五十美元免运费。", "free shipping"),
  v("order", "/订购；点单", "/ˈɔːrdər/", "v./n.", 1, 0.25, "Let's order pizza tonight.", "今晚我们点披萨吧。", "place an order"),
  v("deal", "/交易；划算的买卖", "/diːl/", "n.", 2, 0.25, "Half price? What a deal!", "半价？太划算了！", "a great deal"),
  v("clearance", "/清仓甩卖", "/ˈklɪrəns/", "n.", 5, 0.45, "Everything on the clearance rack is half off.", "清货架上的东西全部五折。", "a clearance sale"),
  v("retail", "/零售", "/ˈriːteɪl/", "n.", 4, 0.45, "Retail prices are higher online now.", "现在线上零售价更高。", "the retail price"),
  v("wholesale", "/批发", "/ˈhoʊlseɪl/", "n.", 5, 0.5, "We buy vegetables wholesale.", "我们批发蔬菜。", "buy wholesale"),
  v("affordable", "/价格可承受的", "/əˈfɔːrdəbl/", "adj.", 3, 0.3, "They sell affordable furniture.", "他们卖价格实惠的家具。", "affordable housing"),
  v("price-tag", "/价签", "/ˈpraɪs tæɡ/", "n.", 3, 0.25, "Check the price-tag first.", "先看价签。", "read the price-tag"),
  v("rack", "/架子；挂架", "/ræk/", "n.", 3, 0.25, "New arrivals hang on that rack.", "新品挂在那个架子上。", "on the sale rack"),
  v("display", "/陈列；展示", "/dɪˈspleɪ/", "v./n.", 3, 0.3, "The window display changes weekly.", "橱窗陈列每周更换。", "on display"),
  v("loyalty", "/忠诚(度)", "/ˈlɔɪəlti/", "n.", 4, 0.4, "Their loyalty program gives points back.", "他们的会员积分计划有返点。", "a loyalty program", { fam: ["loyal"] }),
  v("client", "/客户", "/ˈklaɪənt/", "n.", 3, 0.3, "She met an important client today.", "她今天见了一位重要客户。", "a regular client"),
  v("sales-tax", "/销售税", "/ˈseɪlz tæks/", "n.", 4, 0.4, "Sales-tax adds eight percent here.", "这里销售税加百分之八。", "include sales-tax"),
  v("return", "/退(货)；归还", "/rɪˈtɜːrn/", "v.", 2, 0.3, "Can I return these shoes?", "我能退这双鞋吗？", "return an item"),
];
