import { v } from "@/content/vocab/builder";
import type { VocabRow } from "@/content/vocab/types";

/** Travel & going abroad - Day 31+ travel theme. */
export const travelAbroad2Rows: VocabRow[] = [
  v("boarding-pass", "/登机牌", "/ˈbɔːrdɪŋ pæs/", "n.", 4, 0.35, "Show your boarding-pass at the gate.", "在登机口出示登机牌。", "show your boarding-pass"),
  v("customs", "/海关", "/ˈkʌstəmz/", "n.", 4, 0.4, "We waited thirty minutes at customs.", "我们在海关等了三十分钟。", "go through customs"),
  v("immigration", "/入境检查；移民局", "/ˌɪmɪˈɡreɪʃn/", "n.", 5, 0.5, "Immigration asked about my trip.", "入境检查员问了我的行程。", "clear immigration"),
  v("layover", "/中转停留", "/ˈleɪoʊvər/", "n.", 5, 0.5, "We have a two-hour layover in Tokyo.", "我们在东京有两个小时的中转。", "a long layover"),
  v("jet-lag", "/时差反应", "/ˈdʒet læɡ/", "n.", 5, 0.45, "Jet-lag kept me awake all night.", "时差让我整晚睡不着。", "have jet-lag"),
  v("round-trip", "/往返票；来回", "/ˌraʊnd ˈtrɪp/", "n.", 4, 0.35, "A round-trip ticket costs less than two one-way fares.", "往返票比两张单程票便宜。", "a round-trip ticket"),
  v("one-way", "/单程的", "/ˌwʌn ˈweɪ/", "adj.", 4, 0.35, "This street is one-way.", "这条街是单行的。", "a one-way street"),
  v("carry-on", "/随身行李", "/ˈkæri ɑːn/", "n.", 4, 0.35, "Keep your passport in your carry-on.", "把护照放在随身行李里。", "a carry-on bag"),
  v("baggage", "/行李", "/ˈbæɡɪdʒ/", "n.", 3, 0.3, "Collect your baggage at carousel three.", "在三号转盘取行李。", "baggage claim"),
  v("terminal", "/航站楼；终点站", "/ˈtɜːrmɪnl/", "n.", 4, 0.4, "International flights leave from terminal two.", "国际航班从二号航站楼出发。", "airport terminal"),
  v("domestic", "/国内的", "/dəˈmestɪk/", "adj.", 4, 0.45, "Domestic flights are cheaper.", "国内航班更便宜。", "a domestic flight"),
  v("overseas", "/海外的；在国外", "/ˌoʊvərˈsiːz/", "adj./adv.", 4, 0.4, "Her parents live overseas.", "她的父母住在国外。", "study overseas"),
  v("itinerary", "/行程表", "/aɪˈtɪnəreri/", "n.", 6, 0.55, "Our itinerary includes three cities.", "我们的行程包括三个城市。", "plan an itinerary"),
  v("landmark", "/地标", "/ˈlændmɑːrk/", "n.", 4, 0.4, "The tower is the city's most famous landmark.", "这座塔是这个城市最著名的地标。", "a famous landmark"),
  v("sightseeing", "/观光", "/ˈsaɪtsiːɪŋ/", "n.", 4, 0.35, "We went sightseeing all afternoon.", "我们整个下午都在观光。", "go sightseeing"),
  v("souvenir", "/纪念品", "/ˌsuːvəˈnɪr/", "n.", 4, 0.35, "I bought a keychain as a souvenir.", "我买了一个钥匙扣当纪念品。", "buy souvenirs"),
  v("guidebook", "/旅游指南", "/ˈɡaɪdbʊk/", "n.", 5, 0.4, "The guidebook lists cheap hotels.", "这本旅游指南列了便宜的酒店。", "a travel guidebook"),
  v("hostel", "/青年旅舍", "/ˈhɑːstel/", "n.", 4, 0.4, "Hostels are great for budget travelers.", "青旅对预算少的旅行者很友好。", "stay in a hostel"),
  v("resort", "/度假村", "/rɪˈzɔːrt/", "n.", 4, 0.4, "The resort has a pool and a private beach.", "度假村有泳池和私人海滩。", "a beach resort"),
  v("cruise", "/游轮航行", "/kruːz/", "n./v.", 4, 0.4, "They took a cruise to Alaska.", "他们坐游轮去了阿拉斯加。", "go on a cruise"),
  v("abroad", "/在国外", "/əˈbrɔːd/", "adv.", 3, 0.35, "She has never been abroad before.", "她以前从未出过国。", "travel abroad"),
  v("foreigner", "/外国人", "/ˈfɔːrənər/", "n.", 3, 0.3, "As a foreigner, he often asks for directions.", "作为外国人，他经常问路。", "a foreign tourist"),
  v("currency", "/货币", "/ˈkɜːrənsi/", "n.", 4, 0.45, "What's the local currency in Japan?", "日本的当地货币是什么？", "foreign currency"),
  v("adventure", "/冒险；奇遇", "/ædˈventʃər/", "n.", 3, 0.35, "Traveling alone was a big adventure.", "独自旅行是一次大冒险。", "an exciting adventure"),
  v("destination", "/目的地", "/ˌdestɪˈneɪʃn/", "n.", 4, 0.4, "Hawaii is a popular destination.", "夏威夷是个热门目的地。", "a popular destination"),
  v("gps", "/卫星定位系统", "/ˌdʒiː piː ˈes/", "n.", 3, 0.25, "Use GPS to find the hotel.", "用GPS找酒店。", "turn on GPS"),
  v("shuttle", "/班车；摆渡车", "/ˈʃʌtl/", "n.", 4, 0.4, "A free shuttle runs between the airport and the hotel.", "机场和酒店之间有免费班车。", "take the shuttle"),
  v("cab", "/出租车", "/kæb/", "n.", 3, 0.25, "Let's take a cab to the station.", "我们打车去车站吧。", "hail a cab"),
  v("toll", "/通行费", "/toʊl/", "n.", 4, 0.4, "The highway toll is five dollars.", "高速通行费是五美元。", "pay the toll"),
  v("traffic-jam", "/堵车", "/ˈtræfɪk dʒæm/", "n.", 3, 0.3, "We were stuck in a traffic-jam for an hour.", "我们被堵了一个小时。", "be stuck in a traffic-jam"),
  v("rush-hour", "/高峰时段", "/ˈrʌʃ ˌaʊər/", "n.", 3, 0.3, "Avoid driving during rush-hour.", "避免在高峰时段开车。", "during rush-hour"),
  v("pedestrian", "/行人", "/pəˈdestriən/", "n.", 4, 0.4, "Pedestrians should use the crosswalk.", "行人应该走人行横道。", "a pedestrian crossing"),
  v("embassy", "/大使馆", "/ˈembəsi/", "n.", 4, 0.45, "Lose your passport? Call your embassy.", "护照丢了？联系你的大使馆。", "contact the embassy"),
  v("transit", "/运输；中转", "/ˈtrænzɪt/", "n.", 5, 0.5, "The city improved its public transit last year.", "这座城市去年改善了公共交通。", "public transit"),
  v("runway", "/跑道", "/ˈrʌnweɪ/", "n.", 4, 0.4, "The plane waited on the runway.", "飞机在跑道上等待。", "on the runway"),
  v("check-in", "/值机；入住登记", "/ˈtʃek ɪn/", "n.", 3, 0.3, "Online check-in opens 24 hours early.", "网上值机提前24小时开放。", "hotel check-in"),
  v("tour-guide", "/导游", "/ˈtʊr ɡaɪd/", "n.", 3, 0.3, "Our tour-guide speaks three languages.", "我们的导游会说三种语言。", "a local tour-guide"),
  v("traveler", "/旅行者", "/ˈtrævələr/", "n.", 3, 0.25, "Experienced travelers pack light.", "有经验的旅行者轻装出行。", "a frequent traveler"),
  v("backpacker", "/背包客", "/ˈbækpækər/", "n.", 5, 0.4, "Backpackers often stay in hostels.", "背包客经常住青旅。", "a young backpacker"),
  v("excursion", "/短途旅行", "/ɪkˈskɜːrʒn/", "n.", 6, 0.55, "The hotel offers day excursions to the islands.", "酒店提供去群岛的一日游。", "a day excursion"),
  v("security", "/安检；安全", "/sɪˈkjʊrəti/", "n.", 2, 0.25, "Arrive early — security takes time.", "早点到——安检费时间。", "go through security"),
];
