import { v } from "@/content/vocab/builder";
import type { VocabRow } from "@/content/vocab/types";

/** Workplace & office life - Day 31+ work theme. */
export const workOffice3Rows: VocabRow[] = [
  v("coworker", "/同事", "/ˈkoʊwɜːrkər/", "n.", 2, 0.25, "My coworkers are friendly.", "我的同事们很友好。", "a close coworker"),
  v("employer", "/雇主；用人单位", "/ɪmˈplɔɪər/", "n.", 4, 0.4, "Ask your employer about vacation days.", "问你的雇主关于假期的事。", "a fair employer", { fam: ["employ", "employee"] }),
  v("promotion", "/升职；晋升", "/prəˈmoʊʃn/", "n.", 4, 0.4, "She got a promotion after one year.", "她一年后就升职了。", "get a promotion"),
  v("raise", "/加薪；提高", "/reɪz/", "n./v.", 2, 0.3, "He asked his boss for a raise.", "他向老板请求加薪。", "ask for a raise"),
  v("resign", "/辞职", "/rɪˈzaɪn/", "v.", 5, 0.5, "She resigned to start her own company.", "她辞职创办了自己的公司。", "resign from a job"),
  v("retire", "/退休", "/rɪˈtaɪər/", "v.", 3, 0.35, "My dad will retire next year.", "我爸爸明年退休。", "retire at sixty-five"),
  v("recruit", "/招聘；招募", "/rɪˈkruːt/", "v.", 5, 0.5, "The company is recruiting new engineers.", "公司正在招聘新工程师。", "recruit new staff"),
  v("applicant", "/申请人", "/ˈæplɪkənt/", "n.", 5, 0.45, "We have fifty applicants for one job.", "一个职位有五十名申请者。", "a strong applicant"),
  v("resume", "/简历", "/ˈrezəmeɪ/", "n.", 3, 0.3, "Update your resume before applying.", "申请前先更新简历。", "send a resume"),
  v("fire-v", "/解雇", "/faɪər/", "v.", 3, 0.35, "He got fired for being late every day.", "他因为天天迟到被解雇了。", "get fired"),
  v("layoff", "/裁员", "/ˈleɪɔːf/", "n.", 5, 0.45, "The factory announced layoffs last month.", "工厂上个月宣布了裁员。", "face layoffs"),
  v("overtime", "/加班", "/ˈoʊvərtaɪm/", "n./adv.", 3, 0.3, "I worked overtime on Friday.", "我周五加了班。", "work overtime"),
  v("schedule", "/日程表；安排时间", "/ˈskedʒuːl/", "n./v.", 2, 0.3, "Check the schedule for meeting times.", "查一下日程表上的会议时间。", "a busy schedule"),
  v("workload", "/工作量", "/ˈwɜːrkloʊd/", "n.", 4, 0.4, "My workload doubles before holidays.", "假期前我的工作量翻倍。", "a heavy workload"),
  v("assignment", "/任务；作业", "/əˈsaɪnmənt/", "n.", 3, 0.3, "This assignment is due Monday.", "这个任务周一截止。", "finish an assignment"),
  v("conference", "/会议；研讨会", "/ˈkɑːnfərəns/", "n.", 3, 0.3, "The conference lasts three days.", "会议持续三天。", "attend a conference"),
  v("agenda", "/议程", "/əˈdʒendə/", "n.", 4, 0.4, "The first item on the agenda is sales.", "议程第一项是销售。", "on the agenda"),
  v("memo", "/备忘录", "/ˈmiːmoʊ/", "n.", 5, 0.45, "Read the memo about parking.", "读一下关于停车的备忘录。", "send a memo"),
  v("presentation", "/演讲；展示", "/ˌpriːzenˈteɪʃn/", "n.", 3, 0.35, "Her presentation was clear and short.", "她的演讲清晰简短。", "give a presentation"),
  v("spreadsheet", "/电子表格", "/ˈspredʃiːt/", "n.", 4, 0.4, "Track expenses in a spreadsheet.", "用电子表格记录开支。", "a shared spreadsheet"),
  v("printer", "/打印机", "/ˈprɪntər/", "n.", 2, 0.2, "The printer is out of paper again.", "打印机又没纸了。", "connect the printer"),
  v("scanner", "/扫描仪", "/ˈskænər/", "n.", 3, 0.25, "Put the form in the scanner.", "把表格放进扫描仪。", "use a scanner"),
  v("cubicle", "/(办公)隔间", "/ˈkjuːbɪkl/", "n.", 6, 0.5, "He decorated his cubicle with plants.", "他用植物装饰了自己的隔间。", "an office cubicle"),
  v("cafeteria", "/自助餐厅；食堂", "/ˌkæfəˈtɪriə/", "n.", 3, 0.3, "Lunch in the cafeteria costs eight dollars.", "在食堂吃午饭要八美元。", "the office cafeteria"),
  v("commute", "/通勤", "/kəˈmjuːt/", "v./n.", 4, 0.35, "My commute takes forty minutes by train.", "我坐火车通勤要四十分钟。", "a daily commute"),
  v("full-time", "/全职的", "/ˌfʊl ˈtaɪm/", "adj.", 2, 0.25, "She found a full-time job downtown.", "她在市中心找了份全职工作。", "a full-time job"),
  v("part-time", "/兼职的", "/ˌpɑːrt ˈtaɪm/", "adj.", 2, 0.25, "Students often work part-time.", "学生经常做兼职。", "a part-time job"),
  v("intern", "/实习生", "/ˈɪntɜːrn/", "n.", 4, 0.35, "Interns learn fast here.", "实习生在这里进步很快。", "hire an intern"),
  v("training", "/培训", "/ˈtreɪnɪŋ/", "n.", 2, 0.25, "New staff receive two weeks of training.", "新员工接受两周培训。", "on-the-job training"),
  v("qualification", "/资格；资历", "/ˌkwɑːlɪfɪˈkeɪʃn/", "n.", 5, 0.5, "Do you have the right qualifications?", "你有相应的资格证书吗？", "job qualifications"),
  v("expertise", "/专业知识；专长", "/ˌekspɜːrˈtiːz/", "n.", 6, 0.55, "We need someone with marketing expertise.", "我们需要有营销专长的人。", "technical expertise"),
  v("performance", "/表现；绩效", "/pərˈfɔːrməns/", "n.", 3, 0.35, "His performance this quarter was excellent.", "他这季度的表现出色。", "a performance review"),
  v("review", "/评估；复习；评论", "/rɪˈvjuː/", "n./v.", 1, 0.15, "Write a short review after your stay.", "入住后写一条简短评价。", "a five-star review"),
  v("feedback", "/反馈", "/ˈfiːdbæk/", "n.", 3, 0.3, "My boss gives useful feedback.", "我的老板会给出有用的反馈。", "give feedback"),
  v("brainstorm", "/头脑风暴", "/ˈbreɪnstɔːrm/", "v./n.", 4, 0.4, "Let's brainstorm ideas for the logo.", "我们来给标志集思广益吧。", "a brainstorm session"),
  v("collaborate", "/合作", "/kəˈlæbəreɪt/", "v.", 5, 0.5, "Two teams collaborated on the app.", "两个团队合作开发了这个应用。", "collaborate with a team"),
  v("negotiate", "/谈判；协商", "/nɪˈɡoʊʃieɪt/", "v.", 5, 0.5, "He negotiated a better price.", "他谈到了更好的价格。", "negotiate a contract"),
  v("position", "/职位；位置", "/pəˈzɪʃn/", "n.", 2, 0.3, "They filled the manager position.", "他们招到了经理职位的人选。", "apply for a position"),
  v("apply", "/申请", "/əˈplaɪ/", "v.", 1, 0.25, "I applied for three jobs today.", "我今天申请了三份工作。", "apply for a job"),
  v("quit", "/辞职；戒掉", "/kwɪt/", "v.", 2, 0.3, "She quit her job to travel.", "她辞职去旅行了。", "quit smoking"),
  v("benefit", "/福利；好处", "/ˈbenɪfɪt/", "n.", 2, 0.3, "Health benefits matter to workers.", "医疗保险福利对员工很重要。", "company benefits"),
];
