import { v } from "@/content/vocab/builder";
import type { VocabRow } from "@/content/vocab/types";

/** Social life & relationships - Day 31+ social theme. */
export const socialPeople2Rows: VocabRow[] = [
  v("acquaintance", "/熟人", "/əˈkweɪntəns/", "n.", 5, 0.45, "He's an acquaintance from work.", "他是我在工作场合认识的一个熟人。", "a business acquaintance"),
  v("roommate", "/室友", "/ˈruːmmeɪt/", "n.", 2, 0.25, "My roommate cooks dinner on Fridays.", "我室友每周五做晚饭。", "a college roommate"),
  v("neighborhood", "/街区；邻近地区", "/ˈneɪbərhʊd/", "n.", 3, 0.3, "This neighborhood is quiet at night.", "这个街区晚上很安静。", "a safe neighborhood"),
  v("gathering", "/聚会；聚集", "/ˈɡæðərɪŋ/", "n.", 4, 0.35, "It was a small family gathering.", "那是一次小型的家庭聚会。", "a family gathering"),
  v("housewarming", "/乔迁聚会", "/ˈhaʊswɔːrmɪŋ/", "n.", 6, 0.5, "We're throwing a housewarming this Saturday.", "这周六我们办乔迁聚会。", "a housewarming party"),
  v("potluck", "/百乐餐(各带一菜)", "/ˈpɑːtlʌk/", "n.", 6, 0.5, "Bring a dish to the office potluck.", "办公室百乐餐请带一道菜。", "a potluck dinner"),
  v("small-talk", "/寒暄；闲聊", "/ˈsmɔːl tɔːk/", "n.", 4, 0.35, "Weather is classic small-talk.", "天气是经典的寒暄话题。", "make small-talk"),
  v("gossip", "/八卦；说闲话", "/ˈɡɑːsɪp/", "n./v.", 4, 0.4, "Office gossip spreads fast.", "办公室八卦传得快。", "office gossip"),
  v("privacy", "/隐私", "/ˈpraɪvəsi/", "n.", 3, 0.35, "Please respect my privacy.", "请尊重我的隐私。", "invade someone's privacy"),
  v("relationship", "/关系；恋爱关系", "/rɪˈleɪʃnʃɪp/", "n.", 1, 0.25, "They have a good working relationship.", "他们的工作关系很好。", "a long-term relationship"),
  v("dating", "/约会；恋爱", "/ˈdeɪtɪŋ/", "n.", 3, 0.3, "Dating apps are popular now.", "交友软件现在很流行。", "online dating"),
  v("boyfriend", "/男朋友", "/ˈbɔɪfrend/", "n.", 1, 0.2, "Her boyfriend studies medicine.", "她男朋友学医。", "meet her boyfriend"),
  v("girlfriend", "/女朋友", "/ˈɡɜːrlfrend/", "n.", 1, 0.2, "He introduced his girlfriend to us.", "他把女朋友介绍给我们。", "have a girlfriend"),
  v("engaged", "/已订婚的", "/ɪnˈɡeɪdʒd/", "adj.", 3, 0.3, "They got engaged last month.", "他们上个月订婚了。", "get engaged"),
  v("married", "/已婚的", "/ˈmærid/", "adj.", 1, 0.2, "Are you married?", "你结婚了吗？", "get married"),
  v("marry", "/结婚；娶/嫁", "/ˈmæri/", "v.", 2, 0.25, "They plan to marry in June.", "他们计划六月结婚。", "marry your best friend"),
  v("divorce", "/离婚", "/dɪˈvɔːrs/", "n./v.", 4, 0.4, "His parents divorced when he was ten.", "他十岁时父母离异。", "file for divorce"),
  v("breakup", "/分手", "/ˈbreɪkʌp/", "n.", 3, 0.3, "The breakup was hard on both of them.", "分手对两个人都很难。", "a painful breakup"),
  v("quarrel", "/争吵", "/ˈkwɔːrəl/", "n./v.", 5, 0.45, "They had a quarrel over money.", "他们为钱吵了一架。", "a family quarrel"),
  v("bond", "/纽带；情感联结", "/bɑːnd/", "n.", 4, 0.4, "Traveling together created a strong bond.", "一起旅行建立了深厚的感情。", "a close bond"),
  v("loyal", "/忠诚的", "/ˈlɔɪəl/", "adj.", 3, 0.35, "Dogs are loyal animals.", "狗是忠诚的动物。", "a loyal friend", { fam: ["loyalty"] }),
  v("reliable", "/可靠的", "/rɪˈlaɪəbl/", "adj.", 3, 0.35, "She's a reliable teammate.", "她是个可靠的队友。", "reliable information"),
  v("generous", "/大方的；慷慨的", "/ˈdʒenərəs/", "adj.", 3, 0.35, "It was a generous gift.", "那是一份大方的礼物。", "generous with money"),
  v("selfish", "/自私的", "/ˈselfɪʃ/", "adj.", 3, 0.35, "Don't be selfish — share the cake.", "别自私，把蛋糕分一分。", "a selfish decision"),
  v("outgoing", "/外向的", "/ˈaʊtɡoʊɪŋ/", "adj.", 3, 0.3, "Outgoing people make friends easily.", "外向的人容易交朋友。", "an outgoing personality"),
  v("talkative", "/健谈的", "/ˈtɔːkətɪv/", "adj.", 4, 0.4, "Grandpa gets talkative after dinner.", "爷爷晚饭后话就多起来。", "a talkative child"),
  v("etiquette", "/礼节", "/ˈetɪket/", "n.", 6, 0.55, "Table etiquette differs across cultures.", "餐桌礼节因文化而异。", "social etiquette"),
  v("taboo", "/禁忌", "/təˈbuː/", "n./adj.", 6, 0.55, "Asking salary is a taboo here.", "在这里问工资是禁忌。", "a cultural taboo"),
  v("compliment", "/赞美；恭维", "/ˈkɑːmplɪmənt/", "n./v.", 4, 0.4, "Give a sincere compliment.", "给出真诚的赞美。", "pay someone a compliment"),
  v("criticize", "/批评", "/ˈkrɪtɪsaɪz/", "v.", 4, 0.4, "Bosses shouldn't criticize in public.", "老板不应该当众批评人。", "criticize openly"),
  v("apology", "/道歉", "/əˈpɑːlədʒi/", "n.", 3, 0.3, "A sincere apology fixes a lot.", "真诚的道歉能解决很多问题。", "accept an apology"),
  v("forgive", "/原谅", "/fərˈɡɪv/", "v.", 3, 0.35, "I forgive you — let's move on.", "我原谅你，翻篇吧。", "forgive and forget"),
  v("gratitude", "/感激之情", "/ˈɡrætɪtuːd/", "n.", 5, 0.45, "She expressed gratitude for our help.", "她对我们的帮助表达了感激。", "express gratitude"),
  v("sympathy", "/同情", "/ˈsɪmpəθi/", "n.", 4, 0.4, "We sent sympathy cards after the funeral.", "葬礼后我们寄了慰问卡。", "express sympathy"),
  v("empathy", "/共情；同理心", "/ˈempəθi/", "n.", 6, 0.55, "Good nurses show real empathy.", "好的护士有真正的同理心。", "show empathy"),
  v("get-together", "/(小型)聚会", "/ˈɡet təˌɡeðər/", "n.", 4, 0.35, "Let's have a get-together this weekend.", "这周末我们小聚一下吧。", "a casual get-together"),
  v("reunion", "/重聚；同学会", "/ˌriːˈjuːniən/", "n.", 4, 0.4, "My college reunion is in October.", "我的大学同学会在十月。", "a class reunion"),
  v("farewell", "/告别", "/ˌferˈwel/", "n.", 4, 0.35, "We said our farewells at the station.", "我们在车站道了别。", "say farewell"),
  v("handshake", "/握手", "/ˈhændʃeɪk/", "n.", 4, 0.3, "A firm handshake shows confidence.", "有力的握手显得自信。", "a firm handshake"),
  v("hug", "/拥抱", "/hʌɡ/", "n./v.", 2, 0.2, "She gave her mom a big hug.", "她给了妈妈一个大大的拥抱。", "give someone a hug"),
  v("personality", "/性格；个性", "/ˌpɜːrsəˈnæləti/", "n.", 3, 0.3, "Her personality lights up the room.", "她的性格照亮了整个房间。", "a bubbly personality"),
];
