import { v } from "@/content/vocab/builder";
import type { VocabRow } from "@/content/vocab/types";

/** Health & medical care - Day 31+ health theme. */
export const healthMedical2Rows: VocabRow[] = [
  v("appointment", "/预约；约见", "/əˈpɔɪntmənt/", "n.", 2, 0.25, "I have a dentist appointment at three.", "我三点有个牙医预约。", "make an appointment"),
  v("checkup", "/体检", "/ˈtʃekʌp/", "n.", 3, 0.3, "Get a yearly checkup.", "每年做一次体检。", "a routine checkup"),
  v("symptom", "/症状", "/ˈsɪmptəm/", "n.", 4, 0.4, "A fever is a common symptom.", "发烧是常见症状。", "flu symptoms"),
  v("prescription", "/处方", "/prɪˈskrɪpʃn/", "n.", 5, 0.45, "Take this prescription to the drugstore.", "拿这张处方去药房。", "a prescription for pills"),
  v("drugstore", "/药房(兼卖日用品)", "/ˈdrʌɡstɔːr/", "n.", 3, 0.25, "Buy bandages at the drugstore.", "在药店买绷带。", "run to the drugstore"),
  v("bandage", "/绷带", "/ˈbændɪdʒ/", "n./v.", 4, 0.3, "She put a bandage on the cut.", "她在伤口上贴了绷带。", "wrap a bandage around"),
  v("ambulance", "/救护车", "/ˈæmbjələns/", "n.", 3, 0.25, "Call an ambulance right now!", "马上叫救护车！", "call an ambulance"),
  v("surgeon", "/外科医生", "/ˈsɜːrdʒən/", "n.", 5, 0.45, "The surgeon explained the operation.", "外科医生解释了手术。", "a skilled surgeon"),
  v("surgery", "/外科手术", "/ˈsɜːrdʒəri/", "n.", 4, 0.45, "The surgery took two hours.", "手术进行了两个小时。", "have surgery on a knee"),
  v("operation", "/手术", "/ˌɑːpəˈreɪʃn/", "n.", 4, 0.4, "The operation went well.", "手术很顺利。", "an emergency operation"),
  v("injection", "/注射；打针", "/ɪnˈdʒekʃn/", "n.", 4, 0.35, "The nurse gave him an injection.", "护士给他打了一针。", "get an injection"),
  v("vaccine", "/疫苗", "/vækˈsiːn/", "n.", 4, 0.4, "Flu vaccines are free here.", "这里流感疫苗免费。", "get a vaccine"),
  v("virus", "/病毒", "/ˈvaɪrəs/", "n.", 3, 0.35, "The virus spreads in winter.", "这种病毒在冬天传播。", "catch a virus"),
  v("bacteria", "/细菌", "/bækˈtɪriə/", "n.", 5, 0.5, "Wash hands to kill bacteria.", "洗手可以杀灭细菌。", "harmful bacteria"),
  v("infection", "/感染", "/ɪnˈfekʃn/", "n.", 4, 0.45, "The wound got an infection.", "伤口感染了。", "a skin infection"),
  v("contagious", "/传染性的", "/kənˈteɪdʒəs/", "adj.", 5, 0.5, "Chickenpox is very contagious.", "水痘的传染性很强。", "highly contagious"),
  v("chronic", "/慢性的；长期的", "/ˈkrɑːnɪk/", "adj.", 6, 0.55, "He suffers from chronic back pain.", "他长期背痛。", "chronic pain"),
  v("recovery", "/康复；恢复", "/rɪˈkʌvəri/", "n.", 4, 0.4, "Recovery takes about six weeks.", "康复大约需要六周。", "a full recovery"),
  v("treatment", "/治疗", "/ˈtriːtmənt/", "n.", 3, 0.35, "This treatment works slowly.", "这种治疗见效慢。", "receive treatment"),
  v("therapy", "/治疗；理疗", "/ˈθerəpi/", "n.", 4, 0.4, "Physical therapy helped her walk again.", "物理治疗帮她重新走路。", "physical therapy"),
  v("therapist", "/治疗师", "/ˈθerəpɪst/", "n.", 5, 0.45, "His therapist suggested daily walks.", "他的治疗师建议每天散步。", "see a therapist"),
  v("mental-health", "/心理健康", "/ˈmentl helθ/", "n.", 3, 0.35, "Sleep matters for mental-health.", "睡眠对心理健康很重要。", "mental-health support"),
  v("anxiety", "/焦虑", "/æŋˈzaɪəti/", "n.", 4, 0.4, "Deep breathing reduces anxiety.", "深呼吸能缓解焦虑。", "feelings of anxiety", { fam: ["anxious"] }),
  v("depression", "/抑郁(症)", "/dɪˈpreʃn/", "n.", 5, 0.5, "Talk to someone if depression lasts.", "如果抑郁持续，找人聊聊。", "fight depression"),
  v("insomnia", "/失眠", "/ɪnˈsɑːmniə/", "n.", 6, 0.55, "Coffee after noon causes insomnia for me.", "中午后喝咖啡会让我失眠。", "suffer from insomnia"),
  v("dizzy", "/头晕的", "/ˈdɪzi/", "adj.", 4, 0.35, "I feel dizzy when I stand up fast.", "我猛地站起来会头晕。", "feel dizzy"),
  v("sore-throat", "/嗓子疼", "/ˈsɔːr θroʊt/", "n.", 3, 0.25, "Hot tea soothes a sore-throat.", "热茶能缓解嗓子疼。", "have a sore-throat"),
  v("x-ray", "/X光检查", "/ˈeks reɪ/", "n.", 3, 0.25, "The x-ray shows no broken bones.", "X光显示没有骨折。", "take an x-ray"),
  v("blood-pressure", "/血压", "/ˈblʌd ˌpreʃər/", "n.", 4, 0.35, "Salt raises blood-pressure.", "盐会让血压升高。", "check your blood-pressure"),
  v("pulse", "/脉搏", "/pʌls/", "n.", 5, 0.4, "The nurse checked my pulse.", "护士量了我的脉搏。", "take someone's pulse"),
  v("painkiller", "/止痛药", "/ˈpeɪnkɪlər/", "n.", 5, 0.4, "Take one painkiller before bed.", "睡前吃一粒止痛药。", "strong painkillers"),
  v("antibiotic", "/抗生素", "/ˌæntibaɪˈɑːtɪk/", "n.", 5, 0.5, "Finish all the antibiotics.", "把抗生素疗程吃完。", "a course of antibiotics"),
  v("aspirin", "/阿司匹林", "/ˈæsprɪn/", "n.", 4, 0.3, "Aspirin helps headaches.", "阿司匹林能缓解头疼。", "two aspirins"),
  v("first-aid", "/急救", "/ˈfɜːrst eɪd/", "n.", 3, 0.3, "Every kitchen needs a first-aid kit.", "每个厨房都需要急救箱。", "a first-aid kit"),
  v("insurance", "/保险", "/ɪnˈʃʊrəns/", "n.", 3, 0.35, "Health insurance covers the visit.", "健康保险覆盖这次就诊。", "health insurance"),
  v("wellness", "/身心健康", "/ˈwelnəs/", "n.", 6, 0.5, "The company has a wellness program.", "公司有一个健康计划。", "a wellness program"),
  v("fitness", "/健身；体能", "/ˈfɪtnəs/", "n.", 2, 0.25, "Swimming builds fitness.", "游泳增强体能。", "a fitness center"),
  v("fit", "/健康的；合身的；适合", "/fɪt/", "adj./v.", 1, 0.25, "Exercise keeps you fit.", "锻炼让你保持健康。", "stay fit"),
  v("wheelchair", "/轮椅", "/ˈwiːltʃer/", "n.", 4, 0.3, "The hospital lends wheelchairs at the door.", "医院门口可借用轮椅。", "use a wheelchair"),
  v("allergic", "/过敏的", "/əˈlɜːrdʒɪk/", "adj.", 4, 0.35, "I'm allergic to peanuts.", "我对花生过敏。", "allergic to seafood"),
  v("dentist", "/牙医", "/ˈdentɪst/", "n.", 2, 0.2, "Visit the dentist twice a year.", "一年看两次牙医。", "go to the dentist"),
  v("emergency-room", "/急诊室", "/ɪˈmɜːrdʒənsi ruːm/", "n.", 4, 0.3, "They rushed him to the emergency room.", "他们把他紧急送往急诊室。", "wait in the emergency-room"),
  v("nutrition-label", "/营养", "/nuːˈtrɪʃn/", "n.", 5, 0.45, "Good nutrition starts with real food.", "好的营养从真正的食物开始。", "a nutrition facts label"),
];
