import { v } from "@/content/vocab/builder";
import type { VocabRow } from "@/content/vocab/types";

/** Hobbies & leisure - Day 31+ interests theme. */
export const hobbiesLeisure2Rows: VocabRow[] = [
  v("photography", "/摄影", "/fəˈtɑːɡrəfi/", "n.", 3, 0.3, "Photography is her weekend hobby.", "摄影是她周末的爱好。", "a photography class", { fam: ["photo", "photographer"] }),
  v("drawing", "/素描；绘画(作品)", "/ˈdrɔːɪŋ/", "n.", 2, 0.25, "Her drawing of the cat is funny.", "她画的猫很搞笑。", "a pencil drawing"),
  v("sculpture", "/雕塑", "/ˈskʌlptʃər/", "n.", 6, 0.5, "The park has a steel sculpture.", "公园里有一座钢铁雕塑。", "a public sculpture"),
  v("pottery", "/陶艺", "/ˈpɑːtəri/", "n.", 6, 0.5, "We tried pottery on vacation.", "我们假期体验了陶艺。", "a pottery class"),
  v("calligraphy", "/书法", "/kəˈlɪɡrəfi/", "n.", 6, 0.55, "Chinese calligraphy needs patience.", "中国书法需要耐心。", "practice calligraphy"),
  v("board-game", "/桌游", "/ˈbɔːrd ɡeɪm/", "n.", 3, 0.25, "Monopoly is a classic board-game.", "大富翁是经典桌游。", "play a board-game"),
  v("crossword", "/填字游戏", "/ˈkrɔːswɜːrd/", "n.", 5, 0.4, "Grandma does the Sunday crossword.", "奶奶会做周日的填字游戏。", "do a crossword"),
  v("riddle", "/谜语", "/ˈrɪdl/", "n.", 5, 0.35, "Tell us another riddle!", "再给我们出个谜语吧！", "solve a riddle"),
  v("karaoke", "/卡拉OK", "/ˌkæriˈoʊki/", "n.", 4, 0.25, "Karaoke night is every Thursday.", "每周四是卡拉OK之夜。", "go to karaoke"),
  v("hunting", "/打猎；搜寻", "/ˈhʌntɪŋ/", "n.", 4, 0.35, "Deer hunting season starts in fall.", "猎鹿季从秋天开始。", "a hunting license"),
  v("cycling", "/骑行", "/ˈsaɪklɪŋ/", "n.", 3, 0.25, "Cycling keeps my legs strong.", "骑行让我的腿有力。", "go cycling"),
  v("skating", "/滑冰", "/ˈskeɪtɪŋ/", "n.", 3, 0.25, "Ice skating is fun in winter.", "冬天滑冰很有趣。", "go ice skating"),
  v("skiing", "/滑雪", "/ˈskiːɪŋ/", "n.", 3, 0.3, "They drove to Colorado for skiing.", "他们开车去科罗拉多滑雪。", "go skiing in the mountains"),
  v("surfing", "/冲浪", "/ˈsɜːrfɪŋ/", "n.", 4, 0.3, "Surfing looks harder than it is.", "冲浪看起来比实际难。", "learn surfing"),
  v("diving", "/潜水；跳水", "/ˈdaɪvɪŋ/", "n.", 4, 0.3, "Scuba diving shows you coral reefs.", "水肺潜水能看到珊瑚礁。", "go scuba diving"),
  v("workout", "/(健身)锻炼", "/ˈwɜːrkaʊt/", "n.", 2, 0.2, "A short workout beats no workout.", "短时间锻炼也比不练强。", "a morning workout"),
  v("jogging", "/慢跑", "/ˈdʒɑːɡɪŋ/", "n.", 2, 0.2, "Jogging clears my head.", "慢跑让我头脑清醒。", "go jogging"),
  v("marathon", "/马拉松", "/ˈmærəθɑːn/", "n.", 4, 0.35, "She trained six months for the marathon.", "她为马拉松训练了六个月。", "run a marathon"),
  v("referee", "/裁判", "/ˌrefəˈriː/", "n.", 4, 0.35, "The referee blew the whistle.", "裁判吹响了哨子。", "the referee's whistle"),
  v("championship", "/锦标赛；冠军赛", "/ˈtʃæmpiənʃɪp/", "n.", 4, 0.4, "They won the championship last year.", "他们去年拿了冠军。", "win the championship"),
  v("tournament", "/联赛；淘汰赛", "/ˈtʊrnəmənt/", "n.", 4, 0.4, "A chess tournament starts Friday.", "国际象棋比赛周五开始。", "enter a tournament"),
  v("opponent", "/对手", "/əˈpoʊnənt/", "n.", 5, 0.45, "Respect your opponent.", "尊重你的对手。", "a tough opponent"),
  v("teammate", "/队友", "/ˈtiːmeɪt/", "n.", 2, 0.2, "My teammates cheered loudly.", "我的队友们大声欢呼。", "support your teammates"),
  v("athlete", "/运动员", "/ˈæθliːt/", "n.", 3, 0.3, "Professional athletes train daily.", "职业运动员每天训练。", "a professional athlete"),
  v("amateur", "/业余爱好者", "/ˈæmətʃər/", "adj./n.", 5, 0.5, "He's an amateur photographer.", "他是个业余摄影师。", "an amateur player"),
  v("leisure", "/休闲", "/ˈliːʒər/", "n.", 4, 0.4, "What do you do in your leisure time?", "你闲暇时做什么？", "leisure time"),
  v("entertainment", "/娱乐", "/ˌentərˈteɪnmənt/", "n.", 3, 0.35, "Streaming changed entertainment.", "流媒体改变了娱乐方式。", "the entertainment industry"),
  v("amusement-park", "/游乐园", "/əˈmjuːzmənt pɑːrk/", "n.", 3, 0.25, "Kids love amusement-parks.", "孩子们爱游乐园。", "spend a day at an amusement-park"),
  v("roller-coaster", "/过山车", "/ˈroʊlər ˌkoʊstər/", "n.", 4, 0.25, "That roller-coaster goes upside down!", "那台过山车会翻圈！", "ride a roller-coaster"),
  v("video-game", "/电子游戏", "/ˈvɪdioʊ ɡeɪm/", "n.", 1, 0.15, "He plays video-games after homework.", "他写完作业后玩电子游戏。", "play video-games"),
  v("podcast", "/播客", "/ˈpɑːdkæst/", "n.", 3, 0.2, "I listen to podcasts on the subway.", "我在地铁上听播客。", "subscribe to a podcast"),
  v("streaming", "/流媒体播放", "/ˈstriːmɪŋ/", "n.", 3, 0.25, "Streaming replaced cable TV for many people.", "对很多人来说流媒体取代了有线电视。", "a streaming service"),
  v("subscribe", "/订阅", "/səbˈskraɪb/", "v.", 3, 0.3, "Subscribe to their channel for free.", "免费订阅他们的频道。", "subscribe to a channel"),
  v("channel", "/频道；电视台", "/ˈtʃænl/", "n.", 2, 0.25, "Which channel is the game on?", "比赛在哪个频道？", "switch channels"),
  v("episode", "/一集", "/ˈepɪsoʊd/", "n.", 3, 0.25, "We watched two episodes last night.", "我们昨晚看了两集。", "the latest episode"),
  v("documentary", "/纪录片", "/ˌdɑːkjuˈmentri/", "n.", 4, 0.35, "This documentary is about deep-sea fish.", "这部纪录片讲深海鱼类。", "watch a documentary"),
  v("genre", "/体裁；类型", "/ˈʒɑːnrə/", "n.", 6, 0.5, "Sci-fi is my favorite genre.", "科幻是我最喜欢的类型。", "a movie genre"),
  v("sitcom", "/情景喜剧", "/ˈsɪtkɑːm/", "n.", 6, 0.5, "Friends is a famous sitcom.", "《老友记》是有名的情景喜剧。", "a classic sitcom"),
  v("thriller", "/惊悚片/小说", "/ˈθrɪlər/", "n.", 6, 0.5, "The new thriller kept me up all night.", "新出的惊悚片让我一夜没睡。", "a psychological thriller"),
  v("collection", "/收藏品", "/kəˈlekʃn/", "n.", 3, 0.3, "His coin collection fills two boxes.", "他的硬币收藏装满两个盒子。", "a stamp collection"),
  v("collector", "/收藏家", "/kəˈlektər/", "n.", 4, 0.35, "Serious collectors read auction lists.", "认真的收藏家会看拍卖目录。", "an art collector"),
  v("gardening", "/园艺", "/ˈɡɑːrdnɪŋ/", "n.", 3, 0.25, "Gardening relaxes me after work.", "园艺让我下班后放松。", "do some gardening"),
];
