import { v } from "@/content/vocab/builder";
import type { VocabRow } from "@/content/vocab/types";

/** Food & dining out - Day 31+ daily-life theme. */
export const foodDining3Rows: VocabRow[] = [
  v("appetizer", "/开胃菜", "/ˈæpɪtaɪzər/", "n.", 4, 0.35, "Spring rolls are a great appetizer.", "春卷是很好的开胃菜。", "order an appetizer"),
  v("main-course", "/主菜", "/ˌmeɪn ˈkɔːrs/", "n.", 3, 0.25, "For the main-course I'll have steak.", "主菜我要牛排。", "choose a main-course"),
  v("side-dish", "/配菜", "/ˈsaɪd dɪʃ/", "n.", 3, 0.25, "Fries come as a side-dish.", "薯条作为配菜。", "add a side-dish"),
  v("portion", "/一份；分量", "/ˈpɔːrʃn/", "n.", 4, 0.35, "American portions are huge.", "美国的菜量很大。", "a generous portion"),
  v("leftover", "/剩饭剩菜", "/ˈleftoʊvər/", "n./adj.", 3, 0.3, "Leftovers make easy lunches.", "剩菜做午餐很方便。", "heat up leftovers"),
  v("waiter", "/服务员(男)", "/ˈweɪtər/", "n.", 2, 0.15, "The waiter brought water first.", "服务员先端来了水。", "call the waiter"),
  v("waitress", "/服务员(女)", "/ˈweɪtrəs/", "n.", 2, 0.15, "Our waitress recommended the special.", "我们女服务员推荐了特色菜。", "tip the waitress"),
  v("check", "/(餐厅)账单", "/tʃek/", "n.", 2, 0.2, "Can we get the check, please?", "能给我们账单吗？", "ask for the check"),
  v("meal", "/一餐；饭", "/miːl/", "n.", 1, 0.15, "Breakfast is my favorite meal.", "早餐是我最喜欢的一餐。", "a home-cooked meal"),
  v("brunch", "/早午餐", "/brʌntʃ/", "n.", 3, 0.2, "Sunday brunch starts at ten.", "周日早午餐十点开始。", "go out for brunch"),
  v("food-court", "/美食广场", "/ˈfuːd kɔːrt/", "n.", 3, 0.2, "Meet me at the mall food-court.", "商场美食广场见。", "eat at a food-court"),
  v("fast-food", "/快餐", "/ˌfæst ˈfuːd/", "n.", 1, 0.15, "Too much fast-food is unhealthy.", "快餐吃太多不健康。", "a fast-food restaurant"),
  v("junk-food", "/垃圾食品", "/ˈdʒʌŋk fuːd/", "n.", 3, 0.2, "Chips and soda are junk-food.", "薯片和汽水是垃圾食品。", "cut down on junk-food"),
  v("organic", "/有机的", "/ɔːrˈɡænɪk/", "adj.", 4, 0.35, "Organic vegetables cost more.", "有机蔬菜更贵。", "organic food"),
  v("vegetarian", "/素食者；素的", "/ˌvedʒəˈteriən/", "n./adj.", 3, 0.3, "She's been vegetarian for years.", "她吃素好几年了。", "a vegetarian dish"),
  v("vegan", "/纯素食者", "/ˈviːɡən/", "n./adj.", 5, 0.4, "Vegans don't eat any animal products.", "纯素食者不吃任何动物制品。", "vegan options"),
  v("dairy", "/乳制品", "/ˈderi/", "n./adj.", 4, 0.35, "Milk, cheese, and yogurt are dairy.", "牛奶、奶酪和酸奶都是乳制品。", "a dairy farm"),
  v("seafood", "/海鲜", "/ˈsiːfuːd/", "n.", 2, 0.2, "Coastal cities serve fresh seafood.", "沿海城市有新鲜海鲜。", "a seafood platter"),
  v("ham", "/火腿", "/hæm/", "n.", 2, 0.15, "Ham and eggs is a classic breakfast.", "火腿蛋是经典早餐。", "a ham sandwich"),
  v("lobster", "/龙虾", "/ˈlɑːbstər/", "n.", 5, 0.4, "Maine lobster is famous.", "缅因州龙虾很有名。", "boiled lobster"),
  v("squid", "/鱿鱼", "/skwɪd/", "n.", 5, 0.4, "Grilled squid tastes great with lemon.", "烤鱿鱼配柠檬很好吃。", "fried squid"),
  v("octopus", "/章鱼", "/ˈɑːktəpʊs/", "n.", 5, 0.4, "An octopus has eight arms.", "章鱼有八条腕。", "grilled octopus"),
  v("tofu", "/豆腐", "/ˈtoʊfuː/", "n.", 3, 0.2, "Tofu absorbs flavor well.", "豆腐很吸味。", "mapo tofu"),
  v("soy-sauce", "/酱油", "/ˈsɔɪ sɔːs/", "n.", 2, 0.15, "Add a little soy-sauce.", "加一点酱油。", "a dash of soy-sauce"),
  v("ketchup", "/番茄酱", "/ˈketʃəp/", "n.", 1, 0.1, "Fries need ketchup.", "薯条要蘸番茄酱。", "a bottle of ketchup"),
  v("mustard", "/芥末酱", "/ˈmʌstərd/", "n.", 4, 0.25, "Hot dogs with mustard, please.", "热狗加芥末酱，谢谢。", "mustard on a pretzel"),
  v("mayonnaise", "/蛋黄酱", "/ˈmeɪəneɪz/", "n.", 5, 0.35, "Light mayonnaise has fewer calories.", "淡蛋黄酱热量更低。", "a spoonful of mayonnaise"),
  v("cinnamon", "/肉桂", "/ˈsɪnəmən/", "n.", 6, 0.45, "Cinnamon smells like holidays.", "肉桂闻起来像过节。", "cinnamon rolls"),
  v("curry", "/咖喱", "/ˈkɜːri/", "n.", 4, 0.25, "Japanese curry is mild and sweet.", "日式咖喱温和偏甜。", "chicken curry"),
  v("green-onion", "/小葱", "/ˈɡriːn ˌʌnjən/", "n.", 4, 0.25, "Top the soup with green-onions.", "汤上撒点葱花。", "chop green-onions"),
  v("mushroom", "/蘑菇", "/ˈmʌʃruːm/", "n.", 2, 0.15, "Mushroom soup is comfort food.", "蘑菇汤是治愈系食物。", "mushroom pizza"),
  v("oatmeal", "/燕麦粥", "/ˈoʊtmiːl/", "n.", 3, 0.25, "Oatmeal with berries is healthy.", "燕麦粥加浆果很健康。", "a bowl of oatmeal"),
  v("cereal", "/麦片", "/ˈsɪriəl/", "n.", 2, 0.15, "Cold cereal is a quick breakfast.", "冷麦片是快手早餐。", "a box of cereal"),
  v("pancake", "/煎饼；薄烤饼", "/ˈpænkeɪk/", "n.", 2, 0.15, "Pancakes with maple syrup — yes please!", "煎饼配枫糖浆——来一份！", "a stack of pancakes"),
  v("waffle", "/华夫饼", "/ˈwɑːfl/", "n.", 3, 0.2, "Belgian waffles are thick and fluffy.", "比利时华夫饼又厚又松软。", "waffles and ice cream"),
  v("syrup", "/糖浆", "/ˈsɜːrəp/", "n.", 3, 0.2, "Maple syrup comes from Canada.", "枫糖浆产自加拿大。", "pour syrup on pancakes"),
  v("muffin", "/玛芬蛋糕", "/ˈmʌfɪn/", "n.", 3, 0.15, "A blueberry muffin with coffee?", "蓝莓玛芬配咖啡怎么样？", "bake muffins"),
  v("donut", "/甜甜圈", "/ˈdoʊnʌt/", "n.", 2, 0.1, "One glazed donut, please.", "一个糖霜甜甜圈，谢谢。", "a dozen donuts"),
  v("croissant", "/可颂/牛角包", "/krwɑːˈsɑːn/", "n.", 5, 0.3, "Warm croissants sell out early.", "热的可颂很早就卖光。", "a butter croissant"),
  v("bagel", "/贝果", "/ˈbeɪɡl/", "n.", 4, 0.25, "Toast the bagel and add cream cheese.", "贝果烤一下抹奶油奶酪。", "a sesame bagel"),
];
