import { v } from "@/content/vocab/builder";
import type { VocabRow } from "@/content/vocab/types";

/** City & neighborhood places - Day 31+ daily-life theme. */
export const cityPlaces3Rows: VocabRow[] = [
  v("intersection", "/十字路口", "/ˌɪntərˈsekʃn/", "n.", 4, 0.35, "Turn left at the next intersection.", "在下一个十字路口左转。", "a busy intersection"),
  v("crosswalk", "/人行横道", "/ˈkrɔːswɔːk/", "n.", 3, 0.25, "Wait for the crosswalk signal.", "等人行横道信号灯。", "use the crosswalk"),
  v("lane", "/小巷；车道", "/leɪn/", "n.", 3, 0.3, "We live on a quiet lane.", "我们住在一条安静的小巷。", "the fast lane"),
  v("alley", "/小巷；后巷", "/ˈæli/", "n.", 5, 0.4, "Cats sleep in the sunny alley.", "猫睡在阳光明媚的小巷里。", "a back alley"),
  v("plaza", "/广场；商业广场", "/ˈplæzə/", "n.", 3, 0.25, "Families picnic at the plaza.", "家庭们在广场野餐。", "a shopping plaza"),
  v("fountain", "/喷泉", "/ˈfaʊntn/", "n.", 3, 0.25, "Kids play around the fountain.", "孩子们绕着喷泉玩。", "a marble fountain"),
  v("statue", "/雕像", "/ˈstætʃuː/", "n.", 3, 0.25, "The statue honors a local hero.", "这座雕像纪念当地英雄。", "a bronze statue"),
  v("monument", "/纪念碑", "/ˈmɑːnjumənt/", "n.", 5, 0.45, "The monument lists every soldier's name.", "纪念碑上刻着每位士兵的名字。", "a war monument"),
  v("courthouse", "/法院大楼", "/ˈkɔːrthaʊs/", "n.", 5, 0.45, "The trial is at the downtown courthouse.", "审判在市中心法院进行。", "appear at the courthouse"),
  v("city-hall", "/市政厅", "/ˌsɪti ˈhɔːl/", "n.", 4, 0.35, "Permits come from city-hall.", "许可证要去市政厅办。", "register at city-hall"),
  v("post-office", "/邮局", "/ˈpoʊst ˌɔːfɪs/", "n.", 1, 0.15, "The post-office closes at five.", "邮局五点关门。", "mail it at the post-office"),
  v("police-station", "/警察局", "/pəˈliːs ˌsteɪʃn/", "n.", 2, 0.15, "Report the theft at the police-station.", "去警察局报案。", "go to the police-station"),
  v("gas-station", "/加油站", "/ˈɡæs ˌsteɪʃn/", "n.", 1, 0.1, "Fill up at the gas-station ahead.", "在前面的加油站加油。", "stop at a gas-station"),
  v("laundromat", "/自助洗衣店", "/ˈlɔːndrəmæt/", "n.", 5, 0.4, "The laundromat is open all night.", "自助洗衣店通宵营业。", "do laundry at the laundromat"),
  v("salon", "/美容美发沙龙", "/səˈlɑːn/", "n.", 4, 0.3, "I booked a haircut at the salon.", "我在沙龙预约了剪发。", "a hair salon"),
  v("convenience-store", "/便利店", "/kənˈviːniəns stɔːr/", "n.", 1, 0.15, "Grab milk at the convenience-store.", "在便利店买牛奶。", "a corner convenience-store"),
  v("parking-lot", "/停车场", "/ˈpɑːrkɪŋ lɑːt/", "n.", 1, 0.15, "The parking-lot fills before nine.", "停车场九点前就满了。", "a crowded parking-lot"),
  v("driveway", "/(私宅)车道", "/ˈdraɪvweɪ/", "n.", 3, 0.25, "Park in the driveway, not the street.", "停在车道上，别停街上。", "pull into the driveway"),
  v("lawn", "/草坪", "/lɔːn/", "n.", 3, 0.25, "He mows the lawn every Saturday.", "他每周六修剪草坪。", "mow the lawn"),
  v("porch", "/门廊", "/pɔːrtʃ/", "n.", 4, 0.3, "Grandma reads on the porch.", "奶奶在门廊上看书。", "sit on the porch"),
  v("balcony", "/阳台", "/ˈbælkəni/", "n.", 2, 0.2, "Our balcony faces the park.", "我们的阳台朝向公园。", "grow herbs on the balcony"),
  v("rooftop", "/屋顶", "/ˈruːftɑːp/", "n.", 3, 0.25, "The rooftop bar has a great view.", "屋顶酒吧视野很好。", "a rooftop garden"),
  v("skyscraper", "/摩天大楼", "/ˈskaɪskreɪpər/", "n.", 4, 0.3, "Chicago built the first skyscrapers.", "芝加哥建了最早的摩天大楼。", "a glass skyscraper"),
  v("district", "/区；行政区", "/ˈdɪstrɪkt/", "n.", 3, 0.3, "This district is known for art galleries.", "这个区以画廊闻名。", "a business district"),
  v("aquarium", "/水族馆", "/əˈkweriəm/", "n.", 4, 0.3, "The aquarium has a shark tunnel.", "水族馆有鲨鱼隧道。", "visit the aquarium"),
  v("harbor", "/港口；海港", "/ˈhɑːrbər/", "n.", 3, 0.3, "Fishing boats fill the harbor.", "渔船停满了港口。", "a natural harbor"),
  v("pier", "/码头；(海边)栈桥", "/pɪr/", "n.", 4, 0.3, "Walk to the end of the pier.", "走到栈桥尽头。", "fish off the pier"),
  v("lighthouse", "/灯塔", "/ˈlaɪthaʊs/", "n.", 5, 0.3, "The old lighthouse still guides ships.", "老灯塔仍为船只引航。", "tour the lighthouse"),
  v("metro", "/地铁", "/ˈmetroʊ/", "n.", 2, 0.2, "The metro runs until midnight.", "地铁运营到午夜。", "take the metro"),
  v("streetcar", "/有轨电车", "/ˈstriːtkɑːr/", "n.", 6, 0.45, "San Francisco kept its historic streetcars.", "旧金山保留了历史有轨电车。", "ride the streetcar"),
  v("commuter", "/通勤者", "/kəˈmjuːtər/", "n.", 4, 0.3, "Morning trains are full of commuters.", "早班火车挤满通勤者。", "a daily commuter"),
  v("residential", "/住宅的", "/ˌrezɪˈdenʃl/", "adj.", 5, 0.45, "Keep noise low in residential areas.", "住宅区要保持安静。", "a residential neighborhood"),
  v("noise", "/噪音；响声", "/nɔɪz/", "n.", 1, 0.2, "What's that noise outside?", "外面是什么声音？", "make a loud noise"),
  v("pollution", "/污染", "/pəˈluːʃn/", "n.", 3, 0.3, "Air pollution drops when people bike.", "骑车的人多了空气污染就减少。", "air pollution"),
  v("farmers-market", "/农贸市场", "/ˈfɑːrmərz ˌmɑːrkɪt/", "n.", 4, 0.25, "Buy peaches at the farmers-market.", "在农贸市场买桃子。", "shop at the farmers-market"),
  v("yard-sale", "/庭院旧货出售", "/ˈjɑːrd seɪl/", "n.", 5, 0.3, "We found cheap books at a yard-sale.", "我们在庭院拍卖上淘到了便宜书。", "hold a yard-sale"),
];
