import { v } from "@/content/vocab/builder";
import type { VocabRow } from "@/content/vocab/types";

/** Home & household items - Day 31+ daily-life theme. */
export const houseDaily2Rows: VocabRow[] = [
  v("hallway", "/走廊", "/ˈhɔːlweɪ/", "n.", 2, 0.2, "Hang your coat in the hallway.", "把外套挂在走廊。", "a long hallway"),
  v("closet", "/壁橱；衣柜", "/ˈklɑːzɪt/", "n.", 2, 0.2, "Winter clothes go in the top closet shelf.", "冬装放衣柜顶层。", "a walk-in closet"),
  v("attic", "/阁楼", "/ˈætɪk/", "n.", 5, 0.4, "Holiday decorations live in the attic.", "节日装饰放在阁楼。", "an attic full of boxes"),
  v("chimney", "/烟囱", "/ˈtʃɪmni/", "n.", 4, 0.3, "Smoke rose from the chimney.", "烟从烟囱升起。", "clean the chimney"),
  v("thermostat", "/恒温器", "/ˈθɜːrməstæt/", "n.", 6, 0.5, "Set the thermostat to seventy degrees.", "把恒温器调到七十华氏度。", "adjust the thermostat"),
  v("air-conditioner", "/空调", "/ˈer kəndɪʃənər/", "n.", 1, 0.15, "The air-conditioner broke in July.", "空调七月份坏了。", "fix the air-conditioner"),
  v("heater", "/取暖器；热水器", "/ˈhiːtər/", "n.", 2, 0.2, "Turn on the heater before the guests come.", "客人来之前打开取暖器。", "turn up the heater"),
  v("faucet", "/水龙头(美)", "/ˈfɔːsɪt/", "n.", 3, 0.25, "The faucet drips at night.", "水龙头夜里滴水。", "turn off the faucet"),
  v("drain", "/下水口；排水管", "/dreɪn/", "n./v.", 3, 0.3, "Hair clogged the shower drain.", "头发堵住了淋浴下水口。", "unclog the drain"),
  v("pipe", "/管子；管道", "/paɪp/", "n.", 3, 0.3, "A frozen pipe burst last winter.", "去年冬天冻裂了一根水管。", "burst pipes"),
  v("leak", "/漏；漏水", "/liːk/", "v./n.", 3, 0.3, "The ceiling leaks when it rains.", "下雨时天花板漏水。", "a leak in the roof"),
  v("toilet", "/马桶", "/ˈtɔɪlət/", "n.", 1, 0.15, "The toilet won't flush.", "马桶冲不了水。", "flush the toilet"),
  v("flush", "/冲洗", "/flʌʃ/", "v.", 2, 0.2, "Flush twice if needed.", "需要就冲两次。", "flush the toilet"),
  v("bathtub", "/浴缸", "/ˈbæθtʌb/", "n.", 2, 0.15, "She reads in the bathtub on Sundays.", "她周日泡在浴缸里看书。", "fill the bathtub"),
  v("bathrobe", "/浴袍", "/ˈbæθroʊb/", "n.", 5, 0.35, "Hotel bathrobes are so soft.", "酒店的浴袍特别软。", "put on a bathrobe"),
  v("hanger", "/衣架", "/ˈhæŋər/", "n.", 2, 0.15, "Buy ten wooden hangers.", "买十个木衣架。", "a clothes hanger"),
  v("dresser", "/五斗柜；梳妆台", "/ˈdresər/", "n.", 4, 0.3, "Socks are in the top dresser drawer.", "袜子在五斗柜最上层抽屉。", "dresser drawers"),
  v("nightstand", "/床头柜", "/ˈnaɪtstænd/", "n.", 5, 0.35, "Put your phone on the nightstand.", "把手机放床头柜上。", "a wooden nightstand"),
  v("bookshelf", "/书架", "/ˈbʊkʃelf/", "n.", 2, 0.15, "The bookshelf holds three hundred books.", "书架上放了三百本书。", "a packed bookshelf"),
  v("cabinet", "/橱柜", "/ˈkæbɪnət/", "n.", 2, 0.2, "Plates are in the kitchen cabinet.", "盘子在厨房橱柜里。", "a medicine cabinet"),
  v("mattress", "/床垫", "/ˈmætrəs/", "n.", 3, 0.25, "A good mattress improves sleep.", "好床垫改善睡眠。", "a firm mattress"),
  v("quilt", "/被子", "/kwɪlt/", "n.", 4, 0.3, "Grandma sewed this quilt by hand.", "奶奶手工缝了这床被子。", "a warm quilt"),
  v("blinds", "/百叶窗", "/blaɪndz/", "n.", 4, 0.3, "Close the blinds against the sun.", "拉上百叶窗挡太阳。", "open the blinds"),
  v("rug", "/小地毯", "/rʌɡ/", "n.", 2, 0.2, "The rug ties the room together.", "这块地毯让房间更完整。", "a round rug"),
  v("sponge", "/海绵", "/spʌndʒ/", "n.", 2, 0.15, "Wipe the counter with a sponge.", "用海绵擦台面。", "a kitchen sponge"),
  v("detergent", "/洗衣液/洗涤剂", "/dɪˈtɜːrdʒənt/", "n.", 4, 0.35, "This detergent smells like lavender.", "这款洗衣液是薰衣草味。", "laundry detergent"),
  v("dustpan", "/簸箕", "/ˈdʌstpæn/", "n.", 5, 0.35, "Grab the dustpan for the crumbs.", "拿簸箕来扫面包屑。", "broom and dustpan"),
  v("clothespin", "/晾衣夹", "/ˈkloʊðzpɪn/", "n.", 6, 0.45, "Clip towels with clothespins.", "用晾衣夹夹毛巾。", "a bag of clothespins"),
  v("smoke-detector", "/烟雾报警器", "/ˈsmoʊk dɪˌtektər/", "n.", 5, 0.4, "Test the smoke-detector monthly.", "每月测试烟雾报警器。", "install a smoke-detector"),
  v("doormat", "/门口擦鞋垫", "/ˈdɔːrmæt/", "n.", 5, 0.35, "Wipe your feet on the doormat.", "在门垫上蹭蹭脚。", "welcome doormat"),
  v("lightbulb", "/灯泡", "/ˈlaɪtbʌlb/", "n.", 2, 0.15, "The lightbulb burned out again.", "灯泡又烧了。", "replace a lightbulb"),
  v("hamper", "/(脏衣)篮", "/ˈhæmpər/", "n.", 6, 0.45, "Toss dirty shirts in the hamper.", "脏衬衫扔进脏衣篮。", "a laundry hamper"),
  v("furniture", "/家具", "/ˈfɜːrnɪtʃər/", "n.", 1, 0.15, "New furniture brightens a room.", "新家具让房间亮起来。", "move heavy furniture"),
  v("couch", "/沙发(美)", "/kaʊtʃ/", "n.", 1, 0.15, "The cat sleeps on the couch all day.", "猫整天睡在沙发上。", "crash on the couch"),
  v("wallpaper", "/壁纸", "/ˈwɔːlpeɪpər/", "n./v.", 5, 0.4, "They chose blue wallpaper for the nursery.", "他们为婴儿房选了蓝色壁纸。", "hang wallpaper"),
  v("houseplant", "/室内植物", "/ˈhaʊsplænt/", "n.", 4, 0.25, "Water the houseplants once a week.", "每周给室内植物浇一次水。", "care for houseplants"),
];
