import { v } from "@/content/vocab/builder";
import type { VocabRow } from "@/content/vocab/types";

/** Core verbs batch 4 - everyday actions (B1). */
export const verbsAction4Rows: VocabRow[] = [
  v("achieve", "/实现；达到", "/əˈtʃiːv/", "v.", 2, 0.3, "She achieved her goal of running 5k.", "她实现了跑五公里的目标。", "achieve a goal"),
  v("adjust", "/调整；适应", "/əˈdʒʌst/", "v.", 2, 0.25, "Adjust the mirror before driving.", "开车前先调后视镜。", "adjust to a new schedule"),
  v("arrange", "/安排；整理", "/əˈreɪndʒ/", "v.", 2, 0.3, "Let me arrange a meeting time.", "我来安排会议时间。", "arrange a meeting"),
  v("arrest", "/逮捕", "/əˈrest/", "v./n.", 4, 0.35, "Police arrested the thief quickly.", "警察很快逮捕了小偷。", "be arrested by police"),
  v("assume", "/假定；想当然", "/əˈsuːm/", "v.", 3, 0.4, "Don't assume everyone speaks English.", "不要想当然认为人人都会英语。", "assume the worst"),
  v("attach", "/附上；系上", "/əˈtætʃ/", "v.", 3, 0.3, "Attach the file to your email.", "把文件附加到邮件里。", "attach a photo"),
  v("attempt", "/尝试", "/əˈtempt/", "v./n.", 3, 0.35, "He attempted the recipe for the first time.", "他第一次尝试这个菜谱。", "an attempt at something"),
  v("attend", "/出席；参加", "/əˈtend/", "v.", 2, 0.25, "Will you attend the wedding?", "你会参加婚礼吗？", "attend a class"),
  v("behave", "/表现；守规矩", "/bɪˈheɪv/", "v.", 3, 0.3, "The kids behaved well at dinner.", "孩子们吃饭时表现很好。", "behave yourself"),
  v("blame", "/责怪", "/bleɪm/", "v./n.", 3, 0.35, "Don't blame the weather.", "别怪天气。", "blame someone for something"),
  v("calculate", "/计算；估算", "/ˈkælkjuleɪt/", "v.", 4, 0.4, "Calculate the total before paying.", "付款前算一下总额。", "calculate the cost"),
  v("chase", "/追逐", "/tʃeɪs/", "v.", 2, 0.2, "The dog chased the ball.", "狗追着球跑。", "chase after a dream"),
  v("cheat", "/作弊；欺骗", "/tʃiːt/", "v./n.", 3, 0.3, "Never cheat on an exam.", "考试千万别作弊。", "cheat on a test"),
  v("claim", "/声称；认领", "/kleɪm/", "v./n.", 3, 0.35, "He claims he finished early.", "他声称自己提前完成了。", "claim your luggage"),
  v("compete", "/竞争；比赛", "/kəmˈpiːt/", "v.", 3, 0.35, "Ten teams will compete on Sunday.", "十支队伍周日比赛。", "compete in a race"),
  v("complete", "/完成", "/kəmˈpliːt/", "v./adj.", 2, 0.25, "Complete the form and sign here.", "填完表格在这里签字。", "complete a task"),
  v("concentrate", "/集中注意力", "/ˈkɑːnsntreɪt/", "v.", 2, 0.3, "I can't concentrate with music on.", "开着音乐我没法专心。", "concentrate on your homework"),
  v("confess", "/坦白；承认", "/kənˈfes/", "v.", 5, 0.45, "He confessed to breaking the vase.", "他承认打碎了花瓶。", "confess to a mistake"),
  v("confuse", "/使困惑", "/kənˈfjuːz/", "v.", 2, 0.25, "Long directions confuse me.", "太长的说明会让我糊涂。", "confuse A with B"),
  v("consider", "/考虑；认为", "/kənˈsɪdər/", "v.", 1, 0.2, "Consider taking the earlier train.", "考虑坐早一点的火车。", "consider an offer"),
  v("consist", "/由…组成(与of连用)", "/kənˈsɪst/", "v.", 4, 0.4, "Breakfast consists of eggs and toast.", "早餐包括鸡蛋和吐司。", "consist of three parts"),
  v("consult", "/咨询；请教", "/kənˈsʌlt/", "v.", 4, 0.4, "Consult a lawyer before signing.", "签字前咨询律师。", "consult a doctor"),
  v("continue", "/继续", "/kənˈtɪnjuː/", "v.", 1, 0.15, "Continue straight for two blocks.", "直走两个街区。", "continue reading"),
  v("contribute", "/贡献；捐助", "/kənˈtrɪbjuːt/", "v.", 3, 0.4, "Everyone contributed ideas to the plan.", "每个人都为计划贡献了想法。", "contribute to a project"),
  v("cooperate", "/配合；合作", "/koʊˈɑːpəreɪt/", "v.", 4, 0.4, "The kids cooperated during cleanup.", "孩子们打扫时很配合。", "cooperate with the team"),
  v("cope", "/应对；处理", "/koʊp/", "v.", 4, 0.4, "How do you cope with stress?", "你怎么应对压力？", "cope with pressure"),
  v("cover", "/覆盖；涵盖", "/ˈkʌvər/", "v./n.", 1, 0.2, "Snow covered the whole yard.", "雪覆盖了整个院子。", "cover the costs"),
  v("crash", "/撞车；崩溃", "/kræʃ/", "v./n.", 2, 0.2, "No one was hurt in the crash.", "撞车中无人受伤。", "a car crash"),
  v("crawl", "/爬行", "/krɔːl/", "v.", 3, 0.25, "Babies crawl before they walk.", "婴儿先会爬后会走。", "crawl under the table"),
  v("cure", "/治愈；疗法", "/kjʊr/", "n./v.", 3, 0.3, "Rest is the best cure for a cold.", "休息是感冒最好的药。", "find a cure"),
  v("defend", "/防守；为…辩护", "/dɪˈfend/", "v.", 3, 0.35, "He defended his friend from rumors.", "他为朋友辟谣。", "defend your opinion"),
  v("demand", "/要求；需求", "/dɪˈmænd/", "v./n.", 2, 0.3, "Workers demanded higher pay.", "工人要求加薪。", "meet the demand"),
  v("deny", "/否认", "/dɪˈnaɪ/", "v.", 4, 0.4, "She denied moving the papers.", "她否认动过文件。", "deny an accusation"),
  v("detect", "/察觉；检测到", "/dɪˈtekt/", "v.", 4, 0.4, "The app detects faces automatically.", "这款应用自动检测人脸。", "detect a problem early"),
  v("determine", "/确定；下决心", "/dɪˈtɜːrmɪn/", "v.", 3, 0.4, "We must determine the cause first.", "我们必须先确定原因。", "determine the best route"),
  v("dig", "/挖", "/dɪɡ/", "v.", 2, 0.2, "Dig a hole two feet deep.", "挖一个两英尺深的坑。", "dig a hole"),
  v("discover", "/发现", "/dɪˈskʌvər/", "v.", 1, 0.2, "Scientists discovered a new species.", "科学家发现了一个新物种。", "discover a hidden talent"),
  v("dismiss", "/解散；不予理会", "/dɪsˈmɪs/", "v.", 5, 0.5, "Don't dismiss her idea too fast.", "别太快否定她的想法。", "dismiss the class"),
  v("disturb", "/打扰；扰乱", "/dɪˈstɜːrb/", "v.", 3, 0.3, "Sorry to disturb you so late.", "这么晚打扰你真抱歉。", "do not disturb"),
  v("drag", "/拖；拽", "/dræɡ/", "v.", 2, 0.2, "Drag the icon to the trash.", "把图标拖到垃圾桶。", "drag the box outside"),
  v("earn", "/挣得；获得", "/ɜːrn/", "v.", 1, 0.2, "She earns extra money tutoring.", "她靠家教挣外快。", "earn a good salary"),
  v("escape", "/逃跑；逃离", "/ɪˈskeɪp/", "v./n.", 2, 0.25, "The rabbit escaped from its cage.", "兔子从笼子里逃了出来。", "escape from danger"),
];
