import { v } from "@/content/vocab/builder";
import type { VocabRow } from "@/content/vocab/types";

/** Core verbs batch 5 - everyday actions (B1). */
export const verbsAction5Rows: VocabRow[] = [
  v("expand", "/扩大；扩展", "/ɪkˈspænd/", "v.", 3, 0.35, "The cafe plans to expand next year.", "咖啡馆计划明年扩店。", "expand a business"),
  v("expect", "/预期；期待", "/ɪkˈspekt/", "v.", 1, 0.2, "We expect guests at six.", "我们预计客人六点到。", "expect good news"),
  v("explode", "/爆炸；爆发", "/ɪkˈsploʊd/", "v.", 3, 0.3, "Fireworks exploded over the river.", "烟花在河上空绽放。", "burst into laughter"),
  v("extend", "/延长；延伸", "/ɪkˈstend/", "v.", 3, 0.35, "Can we extend the deadline by a week?", "截止日期能延一周吗？", "extend your stay"),
  v("fill", "/装满；填满", "/fɪl/", "v.", 1, 0.15, "Fill the pot with water.", "把锅装满水。", "fill in a form"),
  v("float", "/漂浮", "/floʊt/", "v.", 3, 0.25, "Wood floats; metal sinks.", "木头浮，金属沉。", "float on your back"),
  v("flow", "/流动", "/floʊ/", "v.", 3, 0.25, "The river flows into the sea.", "这条河流入大海。", "traffic flows smoothly"),
  v("forbid", "/禁止", "/fərˈbɪd/", "v.", 5, 0.45, "The rules forbid smoking indoors.", "规定禁止室内吸烟。", "forbid something completely"),
  v("force", "/强迫；用力推", "/fɔːrs/", "v./n.", 2, 0.3, "Don't force the door — it's stuck.", "别硬推门——卡住了。", "force a smile"),
  v("grab", "/抓取；赶紧拿", "/ɡræb/", "v.", 1, 0.15, "Grab your coat, we're late!", "抓上外套，我们要迟到了！", "grab a bite"),
  v("grasp", "/抓住；领会", "/ɡræsp/", "v.", 4, 0.4, "She grasped the rope tightly.", "她紧紧抓住绳子。", "grasp the main idea"),
  v("guess", "/猜测", "/ɡes/", "v./n.", 1, 0.15, "Guess how old the house is.", "猜猜这房子多少年了。", "take a guess"),
  v("identify", "/识别；确认", "/aɪˈdentɪfaɪ/", "v.", 3, 0.35, "Can you identify this bird?", "你能认出这只鸟吗？", "identify the problem"),
  v("ignore", "/忽视；不理", "/ɪɡˈnɔːr/", "v.", 2, 0.25, "Ignore the spam emails.", "无视垃圾邮件。", "ignore rude comments"),
  v("indicate", "/表明；指示", "/ˈɪndɪkeɪt/", "v.", 4, 0.4, "The sign indicates the exit.", "标志指示出口。", "indicate a change"),
  v("inspire", "/鼓舞；启发", "/ɪnˈspaɪər/", "v.", 3, 0.35, "Her story inspired thousands.", "她的故事鼓舞了数千人。", "inspire confidence"),
  v("intend", "/打算", "/ɪnˈtend/", "v.", 3, 0.35, "I intend to arrive early.", "我打算早点到。", "intend to do something"),
  v("interrupt", "/打断", "/ˌɪntəˈrʌpt/", "v.", 3, 0.3, "Sorry to interrupt your meeting.", "抱歉打断你们的会议。", "interrupt someone mid-sentence"),
  v("involve", "/涉及；包含", "/ɪnˈvɑːlv/", "v.", 2, 0.3, "The job involves some travel.", "这份工作需要出差。", "be involved in a project"),
  v("kick", "/踢", "/kɪk/", "v./n.", 1, 0.1, "Kick the ball to me!", "把球踢给我！", "kick a ball around"),
  v("launch", "/发起；发射；推出", "/lɔːntʃ/", "v./n.", 3, 0.35, "They launch the app next month.", "他们下个月发布应用。", "launch a product"),
  v("lean", "/倾斜；倚靠", "/liːn/", "v.", 3, 0.3, "Lean the ladder against the wall.", "把梯子靠在墙上。", "lean on the fence"),
  v("limit", "/限制", "/ˈlɪmɪt/", "v./n.", 2, 0.25, "Limit screen time after dinner.", "晚饭后限制屏幕时间。", "set a limit"),
  v("march", "/行军；齐步走", "/mɑːrtʃ/", "v./n.", 4, 0.3, "The band marched down the street.", "乐队沿街行进。", "march in a parade"),
  v("melt", "/融化", "/melt/", "v.", 2, 0.2, "Ice melts quickly in the sun.", "冰在阳光下化得快。", "melt the butter first"),
  v("miss", "/错过；思念", "/mɪs/", "v.", 1, 0.15, "I miss my hometown food.", "我想念家乡菜。", "miss the bus"),
  v("notice", "/注意到", "/ˈnoʊtɪs/", "v./n.", 1, 0.15, "Did you notice her new haircut?", "你注意到她的新发型了吗？", "take notice of details"),
  v("observe", "/观察；遵守", "/əbˈzɜːrv/", "v.", 3, 0.35, "Observe how the machine works first.", "先观察机器怎么运转。", "observe the rules"),
  v("occur", "/发生；出现", "/əˈkɜːr/", "v.", 3, 0.35, "Accidents occur most often at night.", "事故最常发生在夜里。", "when did it occur?"),
  v("overcome", "/克服", "/ˌoʊvərˈkʌm/", "v.", 4, 0.4, "She overcame her fear of speaking.", "她克服了说话的恐惧。", "overcome a difficulty"),
  v("owe", "/欠(钱/人情)", "/oʊ/", "v.", 3, 0.3, "I owe you ten dollars.", "我欠你十美元。", "owe money to a friend"),
  v("perform", "/表演；执行", "/pərˈfɔːrm/", "v.", 2, 0.25, "The band performs every Friday.", "乐队每周五演出。", "perform on stage"),
  v("persuade", "/说服", "/pərˈsweɪd/", "v.", 4, 0.4, "He persuaded me to join the team.", "他说服我加入团队。", "persuade someone to help"),
  v("pick", "/挑选；采摘", "/pɪk/", "v.", 1, 0.1, "Pick the ripest apples.", "挑最熟的苹果。", "pick fresh berries"),
  v("plant", "/种植；工厂", "/plænt/", "v./n.", 2, 0.15, "Plant tomatoes in late spring.", "晚春种西红柿。", "plant flowers in pots"),
  v("point", "/指；指向", "/pɔɪnt/", "v./n.", 1, 0.15, "Point at the map where you live.", "在地图上指一下你住哪儿。", "point at the board"),
  v("predict", "/预测", "/prɪˈdɪkt/", "v.", 4, 0.4, "Weather apps predict rain tomorrow.", "天气应用预测明天有雨。", "predict the future"),
  v("prevent", "/阻止；预防", "/prɪˈvent/", "v.", 2, 0.3, "Washing hands prevents illness.", "洗手预防疾病。", "prevent an accident"),
  v("pronounce", "/发音；宣布", "/prəˈnaʊns/", "v.", 2, 0.2, "How do you pronounce this word?", "这个词怎么读？", "pronounce a word clearly"),
  v("prove", "/证明", "/pruːv/", "v.", 3, 0.35, "The receipt proves I paid.", "收据证明我付过钱。", "prove a point"),
  v("punish", "/惩罚", "/ˈpʌnɪʃ/", "v.", 3, 0.3, "Speeding is punished heavily here.", "这里超速处罚很重。", "punish bad behavior"),
  v("quit-v", "/停止；戒除", "/kwɪt/", "v.", 2, 0.25, "Quit tapping your pen!", "别再敲笔了！", "quit cold turkey"),
  v("reach", "/到达；伸手够到", "/riːtʃ/", "v.", 1, 0.15, "Reach the shelf on your toes.", "踮脚够那个架子。", "reach an agreement"),
  v("realize", "/意识到；实现", "/ˈriːəlaɪz/", "v.", 1, 0.2, "I didn't realize the time!", "我没意识到都这个点了！", "realize a mistake"),
];
