import { v } from "@/content/vocab/builder";
import type { VocabRow } from "@/content/vocab/types";

/** Core verbs batch 6 - everyday actions (B1-B2). */
export const verbsAction6Rows: VocabRow[] = [
  v("recognize", "/认出；认可", "/ˈrekəɡnaɪz/", "v.", 1, 0.2, "I recognized her voice right away.", "我立刻听出了她的声音。", "recognize a face"),
  v("recover", "/恢复；痊愈", "/rɪˈkʌvər/", "v.", 2, 0.3, "He recovered quickly from the flu.", "他流感好得很快。", "recover from an illness"),
  v("reflect", "/反射；反思", "/rɪˈflekt/", "v.", 3, 0.35, "The lake reflects the mountains.", "湖面倒映着群山。", "reflect on your day"),
  v("refresh", "/使清爽；刷新", "/rɪˈfreʃ/", "v.", 3, 0.3, "Cold water refreshes tired feet.", "冷水让疲惫的双脚恢复精神。", "refresh the page"),
  v("regret", "/后悔；遗憾", "/rɪˈɡret/", "v./n.", 2, 0.3, "You'll regret staying up late.", "你会后悔熬夜的。", "regret a decision"),
  v("release", "/释放；发布", "/rɪˈliːs/", "v./n.", 3, 0.35, "They released the bird back into the wild.", "他们把鸟放归自然。", "release a new song"),
  v("remove", "/移除；去掉", "/rɪˈmuːv/", "v.", 1, 0.2, "Remove your shoes at the door.", "进门请脱鞋。", "remove a stain"),
  v("rescue", "/营救", "/ˈreskjuː/", "v./n.", 3, 0.3, "Firefighters rescued the cat from the tree.", "消防员把猫从树上救了下来。", "rescue a drowning swimmer"),
  v("resist", "/抵抗；忍住", "/rɪˈzɪst/", "v.", 4, 0.4, "I can't resist chocolate cake.", "我无法抗拒巧克力蛋糕。", "resist the temptation"),
  v("resolve", "/解决；下决心", "/rɪˈzɑːlv/", "v.", 4, 0.4, "We resolved the problem together.", "我们一起解决了问题。", "resolve a conflict"),
  v("respond", "/回应；回答", "/rɪˈspɑːnd/", "v.", 2, 0.25, "She responded to my email within an hour.", "她一小时内回复了我的邮件。", "respond to a question"),
  v("reveal", "/揭示；透露", "/rɪˈviːl/", "v.", 4, 0.4, "The x-ray revealed a small crack.", "X光显示有一道小裂缝。", "reveal a surprise"),
  v("risk", "/风险；冒险", "/rɪsk/", "n./v.", 2, 0.25, "Don't risk your health for work.", "别拿健康冒险去工作。", "take a risk"),
  v("rob", "/抢劫；盗取", "/rɑːb/", "v.", 3, 0.3, "Thieves robbed the store last night.", "昨晚小偷抢了那家店。", "rob a bank"),
  v("ruin", "/毁坏；糟蹋", "/ˈruːɪn/", "v./n.", 3, 0.3, "Rain ruined our picnic.", "雨毁了我们的野餐。", "ruin the moment"),
  v("rush", "/冲；赶紧", "/rʌʃ/", "v./n.", 1, 0.2, "Don't rush — we have time.", "别急，我们有时间。", "in a rush"),
  v("satisfy", "/使满意；满足", "/ˈsætɪsfaɪ/", "v.", 3, 0.35, "A quick snack satisfied my hunger.", "一份快零食填饱了肚子。", "satisfy a customer"),
  v("scratch", "/抓；刮", "/skrætʃ/", "v./n.", 2, 0.2, "The cat scratched the sofa again.", "猫又抓沙发了。", "scratch an itch"),
  v("scream", "/尖叫", "/skriːm/", "v./n.", 2, 0.2, "Fans screamed when the singer appeared.", "歌手出现时粉丝们尖叫起来。", "scream for help"),
  v("seek", "/寻找；寻求", "/siːk/", "v.", 3, 0.35, "She sought advice from her teacher.", "她向老师寻求建议。", "seek help"),
  v("select", "/挑选", "/sɪˈlekt/", "v.", 2, 0.25, "Select your language on the screen.", "在屏幕上选择你的语言。", "select a gift carefully"),
  v("shave", "/剃须；刮脸", "/ʃeɪv/", "v.", 2, 0.15, "He shaves every morning.", "他每天早上刮胡子。", "shave your beard off"),
  v("shine", "/照耀；擦亮", "/ʃaɪn/", "v.", 2, 0.15, "The sun shines brightly today.", "今天阳光灿烂。", "shine your shoes"),
  v("shoot", "/射击；拍摄", "/ʃuːt/", "v.", 2, 0.25, "We shot the video in one afternoon.", "我们一个下午就拍完了视频。", "shoot a movie"),
  v("shrink", "/缩小；收缩", "/ʃrɪŋk/", "v.", 3, 0.3, "Wool shrinks in hot water.", "羊毛在热水里会缩水。", "shrink in the wash"),
  v("shut", "/关上", "/ʃʌt/", "v.", 1, 0.15, "Shut the window — it's cold.", "关上窗户——外面冷。", "shut the door quietly"),
  v("sink", "/下沉；水槽", "/sɪŋk/", "v./n.", 2, 0.2, "Wash the dishes in the sink.", "在水槽里洗碗。", "kitchen sink"),
  v("slip", "/滑倒；溜走", "/slɪp/", "v./n.", 2, 0.2, "Watch your step — you might slip.", "小心脚下——你可能会滑倒。", "slip on the ice"),
  v("spread", "/传播；摊开", "/spred/", "v.", 2, 0.25, "News spreads fast in small towns.", "消息在小城镇传得快。", "spread butter on toast"),
  v("squeeze", "/挤压；榨", "/skwiːz/", "v.", 3, 0.25, "Squeeze some lemon over the fish.", "往鱼上挤点柠檬汁。", "squeeze an orange"),
  v("stain", "/污渍；染色", "/steɪn/", "n./v.", 3, 0.25, "Coffee left a stain on the shirt.", "咖啡在衬衫上留下了污渍。", "a coffee stain"),
  v("steal", "/偷", "/stiːl/", "v.", 2, 0.2, "Someone stole my bike yesterday.", "昨天有人偷了我的自行车。", "steal money from a purse"),
  v("stick", "/粘；卡住", "/stɪk/", "v./n.", 1, 0.2, "Stick the note on the fridge.", "把便条贴在冰箱上。", "stick to the plan"),
  v("strike", "/击打；罢工", "/straɪk/", "v./n.", 3, 0.3, "Lightning struck the old oak tree.", "闪电击中了那棵老橡树。", "go on strike"),
  v("succeed", "/成功", "/səkˈsiːd/", "v.", 2, 0.25, "Work hard and you will succeed.", "努力你就会成功。", "succeed in passing the exam"),
  v("suffer", "/遭受；受苦", "/ˈsʌfər/", "v.", 2, 0.3, "Many people suffer from allergies in spring.", "很多人春天受过敏之苦。", "suffer from a cold"),
  v("supply", "/供应", "/səˈplaɪ/", "v./n.", 3, 0.3, "Local farms supply fresh vegetables.", "当地农场供应新鲜蔬菜。", "water supply"),
  v("suppose", "/假设；料想", "/səˈpoʊz/", "v.", 2, 0.25, "I suppose you're right.", "我想你是对的。", "be supposed to do something"),
  v("surround", "/包围；环绕", "/səˈraʊnd/", "v.", 3, 0.3, "Trees surround the little house.", "小房子四周绿树环绕。", "be surrounded by friends"),
  v("survive", "/生存；幸存", "/sərˈvaɪv/", "v.", 2, 0.3, "Camels survive without water for weeks.", "骆驼几周不喝水也能活。", "survive a disaster"),
  v("swing", "/摇摆；秋千", "/swɪŋ/", "v./n.", 3, 0.2, "Kids lined up for the swings.", "孩子们排队玩秋千。", "play on the swings"),
  v("tear", "/撕裂；眼泪", "/ter/", "v./n.", 2, 0.2, "Be careful not to tear the paper.", "小心别把纸撕破。", "tear a page out"),
  v("toss", "/扔；抛", "/tɔːs/", "v.", 2, 0.15, "Toss the salad with olive oil.", "用橄榄油拌沙拉。", "toss a coin"),
  v("track", "/跟踪；轨道", "/træk/", "v./n.", 2, 0.25, "Track your package online.", "在网上追踪包裹。", "keep track of expenses"),
];
