import { v } from "@/content/vocab/builder";
import type { VocabRow } from "@/content/vocab/types";

/** Core verbs batch 7 - everyday actions (B1). */
export const verbsAction7Rows: VocabRow[] = [
  v("trade", "/交易；交换", "/treɪd/", "v./n.", 2, 0.25, "Let's trade sandwiches — mine for yours.", "我们换三明治吧——我的换你的。", "trade goods"),
  v("transfer", "/转移；转账", "/trænsˈfɜːr/", "v./n.", 3, 0.3, "Transfer the money before Friday.", "周五之前把钱转过去。", "transfer to another school"),
  v("transform", "/彻底改变", "/trænsˈfɔːrm/", "v.", 4, 0.4, "Paint transformed the old room.", "刷漆让旧房间焕然一新。", "transform a space"),
  v("transport", "/运输；交通", "/ˈtrænspɔːrt/", "v./n.", 3, 0.3, "Trucks transport goods across the country.", "卡车把货物运往全国各地。", "public transport"),
  v("trap", "/陷阱；困住", "/træp/", "n./v.", 3, 0.25, "The raccoon was caught in a trap.", "浣熊被困在陷阱里。", "fall into a trap"),
  v("treat", "/对待；治疗；请客", "/triːt/", "v./n.", 1, 0.2, "Doctors treat patients with care here.", "这里的医生悉心治疗病人。", "treat someone to dinner"),
  v("trick", "/戏法；欺骗", "/trɪk/", "n./v.", 2, 0.2, "The magician's trick surprised everyone.", "魔术师的戏法让大家惊讶。", "play a trick on someone"),
  v("twist", "/拧；扭转", "/twɪst/", "v./n.", 2, 0.2, "Twist the cap to open the bottle.", "拧开瓶盖。", "twist off the lid"),
  v("unlock", "/开锁；解锁", "/ˌʌnˈlɑːk/", "v.", 2, 0.15, "Unlock your phone with your face.", "用面部解锁手机。", "unlock the front door"),
  v("update", "/更新", "/ˌʌpˈdeɪt/", "v./n.", 2, 0.2, "Update the app for new features.", "更新应用以获得新功能。", "a software update"),
  v("vary", "/变化；不同", "/ˈveri/", "v.", 4, 0.4, "Prices vary from store to store.", "价格因店而异。", "vary from day to day"),
  v("verify", "/核实", "/ˈverɪfaɪ/", "v.", 5, 0.45, "Verify your email address.", "验证你的电子邮箱。", "verify the facts"),
  v("view", "/看法；景色；观看", "/vjuː/", "n./v.", 1, 0.2, "The view from the bridge is amazing.", "桥上的景色美极了。", "a room with a view"),
  v("vote", "/投票", "/voʊt/", "v./n.", 2, 0.2, "Americans vote every four years.", "美国人每四年投一次票。", "vote in an election"),
  v("wander", "/漫步；闲逛", "/ˈwɑːndər/", "v.", 3, 0.25, "We wandered around the old town all afternoon.", "我们整个下午都在老城闲逛。", "wander around a market"),
  v("whistle", "/吹口哨", "/ˈwɪsl/", "v./n.", 3, 0.2, "He whistled while washing dishes.", "他边洗碗边吹口哨。", "whistle a happy tune"),
  v("wonder", "/想知道；纳闷", "/ˈwʌndər/", "v.", 1, 0.15, "I wonder what's for dinner.", "我想知道晚饭吃什么。", "no wonder!"),
  v("worry", "/担心", "/ˈwɜːri/", "v.", 1, 0.1, "Don't worry about small mistakes.", "别为小错误担心。", "worry about exams"),
  v("yell", "/大喊；吼叫", "/jel/", "v./n.", 2, 0.15, "Mom yelled from downstairs: dinner!", "妈妈在楼下喊：吃饭了！", "yell for help"),
  v("blow", "/吹；刮", "/bloʊ/", "v.", 1, 0.15, "Wind blew the papers off the desk.", "风把纸吹下了桌。", "blow out the candles"),
  v("bow", "/鞠躬；弓", "/baʊ/", "v./n.", 4, 0.25, "Japanese people bow when greeting.", "日本人见面时鞠躬。", "take a bow"),
  v("bury", "/埋；埋葬", "/ˈberi/", "v.", 4, 0.3, "The dog buried its bone in the yard.", "狗把骨头埋在了院子里。", "bury the treasure"),
  v("clap", "/拍手；鼓掌", "/klæp/", "v./n.", 1, 0.1, "Everyone clapped after her speech.", "她演讲结束后大家鼓掌。", "clap your hands"),
  v("cross", "/穿过；交叉", "/krɔːs/", "v./n.", 1, 0.15, "Cross the street at the light.", "等绿灯再过马路。", "cross the bridge"),
  v("dive", "/跳水；潜水", "/daɪv/", "v.", 3, 0.25, "She dove into the pool gracefully.", "她优雅地跳入泳池。", "dive into water"),
  v("enter", "/进入；输入", "/ˈentər/", "v.", 1, 0.15, "Enter the code on this screen.", "在这个屏幕上输入代码。", "enter a room"),
  v("follow", "/跟随；遵循", "/ˈfɑːloʊ/", "v.", 1, 0.15, "Follow me — I know a shortcut.", "跟我来——我知道近路。", "follow the recipe"),
  v("freeze", "/结冰；冷冻", "/friːz/", "v.", 2, 0.2, "The lake freezes every January.", "湖每年一月结冰。", "freeze leftover soup"),
  v("hide", "/藏；躲", "/haɪd/", "v.", 1, 0.15, "The cat likes to hide under the bed.", "这只猫喜欢藏在床底下。", "hide behind the door"),
  v("join", "/加入；连接", "/dʒɔɪn/", "v.", 1, 0.15, "Join us for coffee after class.", "下课后和我们一起喝咖啡。", "join a club"),
  v("kill", "/杀死", "/kɪl/", "v.", 1, 0.15, "Smoking kills thousands every year.", "吸烟每年害死成千上万的人。", "kill time at the airport"),
  v("kiss", "/吻", "/kɪs/", "v./n.", 1, 0.1, "Grandma kissed my forehead goodnight.", "奶奶睡前亲了我的额头。", "kiss someone goodbye"),
  v("land", "/着陆；登陆", "/lænd/", "v./n.", 2, 0.2, "The plane lands in Denver at six.", "飞机六点在丹佛着陆。", "land safely"),
  v("lead", "/带领；导致", "/liːd/", "v./n.", 1, 0.2, "This road leads to the beach.", "这条路通向海滩。", "lead a team"),
  v("lie", "/躺；平躺；说谎", "/laɪ/", "v.", 1, 0.2, "Lie down if your head hurts.", "头疼就躺一会儿。", "tell a lie"),
  v("pat", "/轻拍", "/pæt/", "v./n.", 3, 0.15, "He patted the dog gently.", "他轻轻拍了拍狗。", "pat someone on the back"),
  v("pause", "/暂停", "/pɔːz/", "v./n.", 2, 0.15, "Pause the video and take notes.", "暂停视频做笔记。", "pause for breath"),
  v("press", "/按；压；新闻界", "/pres/", "v./n.", 1, 0.15, "Press the green button twice.", "按两下绿色按钮。", "press the button firmly"),
  v("pretend", "/假装", "/prɪˈtend/", "v.", 2, 0.2, "He pretended not to hear me.", "他假装没听见我说话。", "pretend to sleep"),
  v("punch", "/用拳打；打孔", "/pʌntʃ/", "v./n.", 4, 0.25, "Boxers punch with padded gloves.", "拳击手戴着垫手套出拳。", "punch a ticket"),
  v("quote", "/引用；报价", "/kwoʊt/", "v./n.", 4, 0.35, "She quoted a line from her favorite book.", "她引用了最爱的一本书里的句子。", "quote an expert"),
  v("burn", "/燃烧；烧焦", "/bɜːrn/", "v./n.", 1, 0.15, "Toast burns quickly — watch it!", "吐司烤得快——盯着点！", "burn the candles"),
];
