import { v } from "@/content/vocab/builder";
import type { VocabRow } from "@/content/vocab/types";

/** Descriptive adjectives batch 3 (B1). */
export const adjectivesDescribe3Rows: VocabRow[] = [
  v("accurate", "/准确的", "/ˈækjərət/", "adj.", 4, 0.35, "The map is accurate up to the small streets.", "这张地图连小街道都很准确。", "an accurate answer"),
  v("active", "/活跃的；积极的", "/ˈæktɪv/", "adj.", 1, 0.15, "Grandpa stays active with daily walks.", "爷爷每天散步保持活力。", "lead an active life"),
  v("attractive", "/有吸引力的", "/əˈtræktɪv/", "adj.", 2, 0.25, "The cafe has a warm, attractive design.", "这家咖啡馆设计温馨好看。", "an attractive offer"),
  v("automatic", "/自动的", "/ˌɔːtəˈmætɪk/", "adj.", 3, 0.3, "The doors are automatic.", "门是自动的。", "an automatic response"),
  v("balanced", "/均衡的；平衡的", "/ˈbælənst/", "adj.", 3, 0.3, "A balanced diet includes vegetables and protein.", "均衡饮食包括蔬菜和蛋白质。", "a balanced diet"),
  v("brief", "/简短的", "/briːf/", "adj.", 3, 0.25, "Keep your speech brief — five minutes max.", "演讲要简短——最多五分钟。", "a brief meeting"),
  v("brilliant", "/极好的；才华出众的", "/ˈbrɪljənt/", "adj.", 4, 0.3, "That's a brilliant idea!", "这个主意太棒了！", "a brilliant student"),
  v("careful", "/小心的；仔细的", "/ˈkerfl/", "adj.", 1, 0.1, "Be careful with hot soup.", "小心热汤。", "be careful on the stairs"),
  v("careless", "/粗心的", "/ˈkerləs/", "adj.", 2, 0.2, "Careless mistakes cost him the game.", "粗心的失误让他输掉了比赛。", "a careless mistake"),
  v("cautious", "/谨慎的", "/ˈkɔːʃəs/", "adj.", 5, 0.4, "Investors stay cautious in uncertain times.", "不确定时期投资者保持谨慎。", "cautious about spending"),
  v("clever", "/聪明的；机灵的", "/ˈklevər/", "adj.", 2, 0.15, "What a clever way to fold a shirt!", "叠衣服的方法真聪明！", "a clever solution"),
  v("clumsy", "/笨拙的", "/ˈklʌmzi/", "adj.", 5, 0.4, "I feel clumsy in new shoes.", "穿新鞋我觉得笨手笨脚的。", "clumsy with chopsticks"),
  v("complex", "/复杂的", "/kəmˈpleks/", "adj.", 4, 0.35, "The subway map looks complex at first.", "地铁图乍一看很复杂。", "a complex problem"),
  v("convenient", "/方便的", "/kənˈviːniənt/", "adj.", 2, 0.2, "Is eight o'clock convenient for you?", "八点对你方便吗？", "a convenient location"),
  v("crazy", "/疯狂的", "/ˈkreɪzi/", "adj.", 1, 0.1, "Traffic here is crazy during rush hour.", "高峰期这里的交通疯了一样。", "drive someone crazy"),
  v("creative", "/有创造力的", "/kriˈeɪtɪv/", "adj.", 2, 0.2, "Creative cooks invent new dishes.", "有创意的厨师会发明新菜。", "a creative solution"),
  v("crowded", "/拥挤的", "/ˈkraʊdɪd/", "adj.", 1, 0.15, "The train is crowded this morning.", "今天早上火车很挤。", "a crowded market"),
  v("current", "/当前的；通用的", "/ˈkɜːrənt/", "adj.", 2, 0.25, "Check the current weather before hiking.", "徒步前查看当前天气。", "the current situation"),
  v("cute", "/可爱的", "/kjuːt/", "adj.", 1, 0.05, "Your puppy is so cute!", "你的小狗真可爱！", "a cute outfit"),
  v("delicate", "/精致易碎的；纤细的", "/ˈdelɪkət/", "adj.", 5, 0.45, "Handle the delicate teacup gently.", "拿精致的茶杯要轻。", "delicate china"),
  v("desperate", "/绝望的；拼命的", "/ˈdespərət/", "adj.", 4, 0.4, "He was desperate for a cold drink.", "他特别想喝杯冷饮。", "a desperate attempt"),
  v("difficult", "/困难的", "/ˈdɪfɪkəlt/", "adj.", 1, 0.15, "Chinese tones are difficult for beginners.", "声调对初学者来说很难。", "a difficult decision"),
  v("dull", "/乏味的；钝的", "/dʌl/", "adj.", 4, 0.3, "The movie was dull and slow.", "电影又闷又慢。", "a dull knife"),
  v("eager", "/热切的；渴望的", "/ˈiːɡər/", "adj.", 4, 0.3, "Students were eager to start the trip.", "学生们迫不及待想出发。", "eager to learn"),
  v("elegant", "/优雅的", "/ˈelɪɡənt/", "adj.", 5, 0.4, "She wore an elegant black dress.", "她穿着一条优雅的黑裙。", "an elegant solution"),
  v("enormous", "/巨大的", "/ɪˈnɔːrməs/", "adj.", 3, 0.25, "Whales are enormous creatures.", "鲸鱼是巨大的生物。", "an enormous amount of work"),
  v("exhausted", "/精疲力尽的", "/ɪɡˈzɔːstɪd/", "adj.", 2, 0.2, "After the marathon I was exhausted.", "马拉松后我筋疲力尽。", "feel completely exhausted"),
  v("fancy", "/花哨的；高档的", "/ˈfænsi/", "adj./n.", 2, 0.2, "We don't need anything fancy for dinner.", "晚饭不用搞得太花哨。", "a fancy restaurant"),
  v("fat", "/胖的；肥的", "/fæt/", "adj.", 1, 0.1, "The neighbor's cat is getting fat.", "邻居家的猫越来越胖了。", "a fat cat"),
  v("fierce", "/凶猛的；激烈的", "/fɪrs/", "adj.", 5, 0.45, "Competition between the two shops is fierce.", "两家店竞争激烈。", "fierce competition"),
  v("fond", "/喜爱的", "/fɑːnd/", "adj.", 4, 0.3, "I'm fond of early morning walks.", "我喜欢清晨散步。", "be fond of sweets"),
  v("fragile", "/易碎的", "/ˈfrædʒl/", "adj.", 3, 0.25, "This box is labeled fragile.", "这个箱子标着易碎品。", "fragile glassware"),
  v("frequent", "/频繁的", "/ˈfriːkwənt/", "adj.", 3, 0.3, "Frequent practice builds fluency.", "经常练习能培养流利度。", "a frequent visitor"),
  v("frightened", "/害怕的", "/ˈfraɪtnd/", "adj.", 2, 0.2, "The loud thunder frightened the baby.", "响雷吓到了婴儿。", "be frightened of spiders"),
  v("glad", "/高兴的", "/ɡlæd/", "adj.", 1, 0.1, "I'm glad you could come.", "很高兴你能来。", "glad to help"),
  v("gorgeous", "/极其漂亮的", "/ˈɡɔːrdʒəs/", "adj.", 4, 0.25, "The sunset was absolutely gorgeous.", "日落美极了。", "a gorgeous day"),
  v("grateful", "/感激的", "/ˈɡreɪtfl/", "adj.", 2, 0.2, "I'm grateful for your support.", "我很感激你的支持。", "deeply grateful"),
  v("guilty", "/内疚的；有罪的", "/ˈɡɪlti/", "adj.", 3, 0.25, "He felt guilty about lying.", "他为撒谎感到内疚。", "feel guilty about something"),
  v("handy", "/方便好用的；手巧的", "/ˈhændi/", "adj.", 4, 0.25, "This little flashlight is handy.", "这个小手电很好用。", "come in handy"),
  v("harsh", "/严厉的；刺耳的", "/hɑːrʃ/", "adj.", 5, 0.4, "Harsh winter winds hit the coast.", "凛冽的冬风袭击了海岸。", "harsh criticism"),
  v("hollow", "/空心的", "/ˈhɑːloʊ/", "adj.", 6, 0.45, "The tree trunk is hollow inside.", "树干里面是空的。", "hollow cheeks"),
  v("humid", "/潮湿的", "/ˈhjuːmɪd/", "adj.", 4, 0.3, "Summers here are hot and humid.", "这里夏天又热又潮。", "hot and humid weather"),
];
