import { v } from "@/content/vocab/builder";
import type { VocabRow } from "@/content/vocab/types";

/** Descriptive adjectives batch 4 (B1). */
export const adjectivesDescribe4Rows: VocabRow[] = [
  v("alive", "/活着的；有活力的", "/əˈlaɪv/", "adj.", 1, 0.15, "The old tradition is still alive here.", "这个老传统在这里仍然鲜活。", "stay alive"),
  v("ancient", "/古老的", "/ˈeɪnʃənt/", "adj.", 3, 0.25, "We toured the ancient city walls.", "我们参观了古老的城墙。", "an ancient temple"),
  v("bold", "/大胆的", "/boʊld/", "adj.", 4, 0.3, "It was a bold move to quit and travel.", "辞职去旅行是个大胆的决定。", "a bold decision"),
  v("broad", "/宽的；广泛的", "/brɔːd/", "adj.", 3, 0.25, "The broad avenue holds six lanes.", "宽阔的大道有六条车道。", "a broad range of topics"),
  v("charming", "/迷人的", "/ˈtʃɑːrmɪŋ/", "adj.", 4, 0.25, "What a charming little bookshop!", "多迷人的一家小书店！", "a charming village"),
  v("chilly", "/微寒的", "/ˈtʃɪli/", "adj.", 3, 0.2, "It's a bit chilly — bring a jacket.", "有点凉——带件外套。", "a chilly morning"),
  v("cozy", "/温馨舒适的", "/ˈkoʊzi/", "adj.", 3, 0.15, "This cafe feels cozy on rainy days.", "雨天这家咖啡馆格外温馨。", "a cozy blanket"),
  v("crisp", "/脆的；(天气)清爽的", "/krɪsp/", "adj.", 3, 0.2, "Fresh apples are crisp and sweet.", "新鲜苹果又脆又甜。", "crisp autumn air"),
  v("dim", "/昏暗的", "/dɪm/", "adj.", 4, 0.2, "The dim lamp made reading hard.", "昏暗的灯让人难以阅读。", "dim lighting"),
  v("dusty", "/积灰的", "/ˈdʌsti/", "adj.", 3, 0.2, "The old books on the shelf were dusty.", "书架上的旧书落满了灰。", "a dusty road"),
  v("faint", "/微弱的；模糊的", "/feɪnt/", "adj./v.", 4, 0.35, "I heard a faint knock at the door.", "我听到轻轻的敲门声。", "a faint smell of coffee"),
  v("gloomy", "/阴暗的；令人沮丧的", "/ˈɡluːmi/", "adj.", 5, 0.4, "Rainy skies look gloomy today.", "今天的雨天阴沉沉的。", "a gloomy forecast"),
  v("greedy", "/贪婪的", "/ˈɡriːdi/", "adj.", 4, 0.3, "Don't be greedy — save some cake for others.", "别贪心，给别人留点蛋糕。", "greedy for attention"),
  v("icy", "/结冰的；冰冷的", "/ˈaɪsi/", "adj.", 3, 0.2, "Icy roads are dangerous to drive on.", "结冰的路面开车危险。", "icy conditions"),
  v("ill", "/生病的", "/ɪl/", "adj.", 1, 0.15, "She stayed home because she felt ill.", "她觉得不舒服就待在家里。", "fall ill suddenly"),
  v("innocent", "/无辜的；天真的", "/ˈɪnəsnt/", "adj.", 3, 0.25, "The jury found him innocent.", "陪审团判他无罪。", "an innocent mistake"),
  v("jealous", "/嫉妒的", "/ˈdʒeləs/", "adj.", 3, 0.25, "The cat gets jealous of the new puppy.", "这只猫嫉妒新来的小狗。", "jealous of a friend's success"),
  v("lovely", "/美好的；可爱的", "/ˈlʌvli/", "adj.", 1, 0.1, "We had a lovely evening together.", "我们一起度过了美好的夜晚。", "a lovely view"),
  v("mad", "/生气的；疯狂的", "/mæd/", "adj.", 1, 0.1, "Dad was mad about the broken window.", "爸爸为打破的窗户生气。", "mad at someone"),
  v("neat", "/整洁的", "/niːt/", "adj.", 2, 0.15, "Her handwriting is small and neat.", "她的字小而工整。", "keep your room neat"),
  v("odd", "/奇怪的；奇数的", "/ɑːd/", "adj.", 2, 0.2, "What an odd question to ask!", "这个问题问得真怪！", "an odd number"),
  v("painful", "/疼痛的；痛苦的", "/ˈpeɪnfl/", "adj.", 1, 0.15, "The injection was quick but painful.", "打针很快但疼。", "a painful memory"),
  v("pale", "/苍白的；浅色的", "/peɪl/", "adj.", 3, 0.2, "You look pale — did you sleep well?", "你脸色苍白——睡好了吗？", "pale blue walls"),
  v("plain", "/朴素的；简单的", "/pleɪn/", "adj.", 2, 0.2, "A plain white shirt goes with everything.", "纯白衬衫百搭。", "plain yogurt"),
  v("plump", "/丰满的；圆鼓鼓的", "/plʌmp/", "adj.", 6, 0.4, "The plump pillows feel soft.", "饱满的枕头摸起来很软。", "a plump turkey"),
  v("powerful", "/强大的；有力的", "/ˈpaʊərfl/", "adj.", 1, 0.15, "That is a powerful speech.", "那是一场有力的演讲。", "a powerful engine"),
  v("pretty", "/漂亮的；相当", "/ˈprɪti/", "adv./adj.", 1, 0.1, "The garden looks pretty in spring.", "春天的花园很好看。", "pretty good news"),
  v("pure", "/纯的；纯洁的", "/pjʊr/", "adj.", 3, 0.25, "Mountain air feels pure and clean.", "山里的空气纯净清新。", "pure water"),
  v("shaky", "/颤抖的；不稳的", "/ˈʃeɪki/", "adj.", 4, 0.3, "My voice was shaky before the interview.", "面试前我的声音发抖。", "shaky hands"),
  v("shiny", "/闪亮的", "/ˈʃaɪni/", "adj.", 2, 0.15, "The shiny red bike caught my eye.", "亮闪闪的红色自行车吸引了我。", "shiny black shoes"),
  v("silent", "/寂静的；沉默的", "/ˈsaɪlənt/", "adj.", 2, 0.15, "The library stays silent after eight.", "八点后图书馆一片安静。", "keep silent during the movie"),
  v("sore", "/酸痛的；疼痛的", "/sɔːr/", "adj.", 2, 0.2, "My legs are sore after hiking.", "远足后我腿酸。", "sore muscles"),
  v("steady", "/稳定的", "/ˈstedi/", "adj.", 3, 0.25, "Keep a steady pace up the hill.", "上山保持稳定节奏。", "a steady income"),
  v("sticky", "/黏的", "/ˈstɪki/", "adj.", 2, 0.15, "Rice dough is sticky.", "米面团很黏。", "sticky fingers"),
  v("stiff", "/硬的；僵硬的", "/stɪf/", "adj.", 3, 0.25, "New leather shoes feel stiff at first.", "新皮鞋一开始发硬。", "a stiff neck"),
  v("stubborn", "/固执的", "/ˈstʌbərn/", "adj.", 4, 0.3, "Grandma is stubborn about her morning routine.", "奶奶对晨间习惯非常执着。", "stubborn as a mule"),
  v("tender", "/温柔的；嫩的", "/ˈtendər/", "adj./n.", 4, 0.3, "Slow cooking makes the meat tender.", "慢炖让肉变嫩。", "tender loving care"),
  v("tough", "/艰难的；坚韧的", "/tʌf/", "adj.", 1, 0.15, "Learning a language is tough but worth it.", "学语言很难但值得。", "a tough decision"),
  v("vain", "/自负的；徒劳的", "/veɪn/", "adj.", 6, 0.45, "He's vain about his hair.", "他对自己的头发很自负。", "in vain"),
  v("wealthy", "/富有的", "/ˈwelθi/", "adj.", 4, 0.3, "The wealthy family donated the library.", "那个富裕家庭捐赠了图书馆。", "a wealthy neighborhood"),
];
