import { v } from "@/content/vocab/builder";
import type { VocabRow } from "@/content/vocab/types";

/** Nature, space & basic world nouns - surprising gaps in the A1-B1 core. */
export const coreWorldNounsRows: VocabRow[] = [
  v("death", "/死亡", "/deθ/", "n.", 2, 0.25, "The news of his death shocked the whole town.", "他去世的消息震惊了全镇。", "the death of a loved one"),
  v("die", "/死；枯萎", "/daɪ/", "v.", 1, 0.15, "Plants die without water.", "没有水植物会枯死。", "die of old age"),
  v("dead", "/死的；没电的", "/ded/", "adj.", 1, 0.15, "My phone battery is dead again.", "我手机又没电了。", "a dead battery"),
  v("beauty", "/美；美丽", "/ˈbjuːti/", "n.", 2, 0.2, "The beauty of the lake amazed us.", "湖的美景让我们惊叹。", "natural beauty"),
  v("space", "/空间；太空", "/speɪs/", "n.", 1, 0.15, "There's no space for another chair.", "没地方再放一把椅子了。", "outer space"),
  v("earth", "/地球；泥土", "/ɜːrθ/", "n.", 1, 0.1, "The earth moves around the sun.", "地球绕着太阳转。", "the earth's surface"),
  v("sea", "/海", "/siː/", "n.", 1, 0.1, "The sea was calm this morning.", "今天早上海面很平静。", "by the sea"),
  v("ocean", "/海洋", "/ˈoʊʃn/", "n.", 1, 0.1, "The Pacific is the largest ocean.", "太平洋是最大的洋。", "across the ocean"),
  v("river", "/河；江", "/ˈrɪvər/", "n.", 1, 0.05, "We kayaked down the river.", "我们划皮划艇顺流而下。", "cross the river"),
  v("lake", "/湖", "/leɪk/", "n.", 1, 0.05, "The lake freezes in winter.", "这个湖冬天结冰。", "a cabin by the lake"),
  v("mountain", "/山", "/ˈmaʊntn/", "n.", 1, 0.1, "They climbed the mountain in two days.", "他们用两天登上了那座山。", "mountain climbing"),
  v("forest", "/森林", "/ˈfɔːrɪst/", "n.", 1, 0.1, "Birds sing loudly in the forest.", "鸟儿在森林里大声歌唱。", "a thick forest"),
  v("wood", "/木头；树林", "/wʊd/", "n.", 1, 0.1, "The table is made of solid wood.", "这张桌子是实木的。", "a piece of wood"),
  v("field", "/田地；领域", "/fiːld/", "n.", 1, 0.1, "Farmers work in the fields at dawn.", "农民黎明时分在田里劳作。", "in the field of medicine"),
  v("stone", "/石头", "/stoʊn/", "n.", 1, 0.1, "Skip a stone across the water.", "打水漂——让石头掠过水面。", "a heart of stone"),
  v("rock", "/岩石；摇滚", "/rɑːk/", "n.", 1, 0.1, "Sit on that big rock and rest.", "坐在那块大石头上休息。", "rock music"),
  v("sand", "/沙；沙子", "/sænd/", "n.", 1, 0.05, "Hot sand burns bare feet.", "滚烫的沙子烫脚。", "a sand castle"),
  v("mud", "/泥", "/mʌd/", "n.", 3, 0.15, "Our shoes were covered in mud.", "我们的鞋上全是泥。", "stuck in the mud"),
  v("shore", "/岸；滨", "/ʃɔːr/", "n.", 4, 0.3, "Waves crash on the rocky shore.", "海浪拍打着岩石海岸。", "off shore"),
  v("cave", "/洞穴", "/keɪv/", "n.", 3, 0.2, "Bats sleep in the cave by day.", "蝙蝠白天在洞里睡觉。", "explore a cave"),
  v("desert", "/沙漠", "/ˈdezərt/", "n.", 3, 0.2, "Camels cross the desert slowly.", "骆驼慢慢地穿越沙漠。", "the Sahara desert"),
  v("jungle", "/丛林", "/ˈdʒʌŋɡl/", "n.", 4, 0.3, "Monkeys swung through the jungle.", "猴子们在丛林间荡来荡去。", "the jungle floor"),
  v("waterfall", "/瀑布", "/ˈwɔːtərfɔːl/", "n.", 4, 0.25, "The waterfall roared below us.", "瀑布在我们下方轰鸣。", "a famous waterfall"),
  v("planet", "/行星", "/ˈplænɪt/", "n.", 2, 0.2, "Mars is the fourth planet from the sun.", "火星是离太阳第四近的行星。", "save the planet"),
  v("universe", "/宇宙", "/ˈjuːnɪvɜːrs/", "n.", 4, 0.35, "Scientists study how the universe began.", "科学家研究宇宙如何开始。", "the known universe"),
  v("gravity", "/重力；引力", "/ˈɡrævəti/", "n.", 5, 0.45, "Gravity keeps us on the ground.", "重力让我们留在地面。", "the force of gravity"),
  v("shadow", "/影子", "/ˈʃædoʊ/", "n.", 2, 0.15, "My shadow grows long at sunset.", "日落时我的影子变长。", "afraid of shadows"),
  v("silence", "/寂静；沉默", "/ˈsaɪləns/", "n.", 2, 0.2, "Silence filled the room after the news.", "消息传来后房间一片寂静。", "break the silence"),
  v("sound", "/声音", "/saʊnd/", "n./v.", 1, 0.1, "I heard a strange sound outside.", "我听到外面有个奇怪的声音。", "a sound sleep"),
  v("sight", "/视力；景象", "/saɪt/", "n.", 2, 0.2, "The sight of snow made the kids cheer.", "看到雪孩子们欢呼起来。", "lose sight of something"),
  v("hearing", "/听力", "/ˈhɪrɪŋ/", "n.", 3, 0.25, "Loud music can damage your hearing.", "吵闹的音乐会损害听力。", "a hearing test"),
  v("nature", "/大自然；本性", "/ˈneɪtʃər/", "n.", 1, 0.15, "We love spending weekends in nature.", "我们喜欢周末亲近大自然。", "human nature"),
  v("environment", "/环境", "/ɪnˈvaɪrənmənt/", "n.", 2, 0.2, "Recycling helps the environment.", "回收利用有助于保护环境。", "protect the environment"),
  v("horizon", "/地平线", "/həˈraɪzn/", "n.", 6, 0.45, "The sun sank below the horizon.", "太阳沉到地平线下。", "on the horizon"),
  v("surface", "/表面", "/ˈsɜːrfɪs/", "n.", 3, 0.3, "Wipe the surface with a damp cloth.", "用湿布擦表面。", "scratch the surface"),
  v("depth", "/深度", "/depθ/", "n.", 5, 0.45, "The pool has a depth of two meters.", "泳池深两米。", "in the depths of winter"),
  v("smoke", "/烟", "/smoʊk/", "n./v.", 1, 0.15, "Smoke rose from the campfire.", "营火升起了烟。", "secondhand smoke"),
  v("flame", "/火焰", "/fleɪm/", "n.", 3, 0.25, "The candle flame flickered in the wind.", "烛火在风中摇曳。", "burst into flames"),
  v("ash", "/灰；灰烬", "/æʃ/", "n.", 5, 0.4, "Ash covered everything after the fire.", "火灾后到处都是灰。", "cigarette ash"),
  v("mist", "/薄雾", "/mɪst/", "n.", 5, 0.4, "Morning mist hung over the rice fields.", "清晨薄雾笼罩着稻田。", "a light mist"),
  v("sunset", "/日落", "/ˈsʌnset/", "n.", 1, 0.1, "We watched the sunset from the pier.", "我们在栈桥上看日落。", "at sunset"),
  v("sunrise", "/日出", "/ˈsʌnraɪz/", "n.", 1, 0.1, "The sunrise was worth waking up early.", "这场日出值得早起。", "watch the sunrise"),
];
