import { v } from "@/content/vocab/builder";
import type { VocabRow } from "@/content/vocab/types";

/** Opinions & discussion - Day 61+ opinion theme. */
export const opinionDiscussRows: VocabRow[] = [
  v("disagree", "/不同意", "/ˌdɪsəˈɡriː/", "v.", 2, 0.25, "I respect you, but I disagree.", "我尊重你，但我不同意。", "agree to disagree"),
  v("debate", "/辩论；争论", "/dɪˈbeɪt/", "n./v.", 3, 0.3, "The class debated homework policies.", "班里就作业政策展开了辩论。", "a heated debate"),
  v("discussion", "/讨论", "/dɪˈskʌʃn/", "n.", 1, 0.15, "Let's have a short discussion after the video.", "看完视频我们简短讨论一下。", "a group discussion"),
  v("viewpoint", "/观点；视角", "/ˈvjuːpɔɪnt/", "n.", 4, 0.35, "Try to see it from her viewpoint.", "试着从她的角度看这件事。", "an opposing viewpoint"),
  v("perspective", "/视角；角度", "/pərˈspektɪv/", "n.", 4, 0.4, "Travel gives you a new perspective.", "旅行给你新的视角。", "from a different perspective"),
  v("attitude", "/态度", "/ˈætɪtuːd/", "n.", 2, 0.25, "A positive attitude helps at work.", "积极的态度对工作有帮助。", "a positive attitude"),
  v("doubt", "/怀疑；疑惑", "/daʊt/", "n./v.", 2, 0.25, "I have no doubt you'll pass.", "我毫不怀疑你会通过。", "without a doubt"),
  v("certain", "/确定的；某个", "/ˈsɜːrtn/", "adj.", 1, 0.15, "Are you certain about the time?", "你确定时间吗？", "for certain"),
  v("certainly", "/当然；肯定", "/ˈsɜːrtnli/", "adv.", 1, 0.15, "That will certainly help.", "那肯定会有帮助。", "most certainly"),
  v("perhaps", "/也许", "/pərˈhæps/", "adv.", 1, 0.15, "Perhaps we should leave early.", "也许我们应该早点出发。", "perhaps tomorrow"),
  v("definitely", "/肯定地；绝对", "/ˈdefɪnətli/", "adv.", 1, 0.15, "I'll definitely be there by nine.", "我九点前肯定到。", "definitely not"),
  v("absolutely", "/绝对地；完全地", "/ˈæbsəluːtli/", "adv.", 1, 0.15, "Absolutely — count me in!", "当然——算我一个！", "absolutely right"),
  v("exactly", "/确切地；正是", "/ɪɡˈzæktli/", "adv.", 1, 0.1, "That's exactly what I meant.", "那正是我的意思。", "not exactly"),
  v("actually", "/实际上；其实", "/ˈæktʃuəli/", "adv.", 1, 0.1, "Actually, I changed my mind.", "其实我改变主意了。", "did you actually see it?"),
  v("personally", "/就个人而言", "/ˈpɜːrsənəli/", "adv.", 2, 0.2, "Personally, I prefer tea.", "就我个人而言，我更喜欢茶。", "personally speaking"),
  v("honestly", "/老实说", "/ˈɑːnɪstli/", "adv.", 1, 0.15, "Honestly, the movie wasn't that good.", "说实话，电影没那么好。", "honestly speaking"),
  v("frankly", "/坦率地说", "/ˈfræŋkli/", "adv.", 5, 0.35, "Frankly, I don't trust the ad.", "坦白说，我不信这广告。", "frankly speaking"),
  v("obviously", "/显然", "/ˈɑːbviəsli/", "adv.", 2, 0.2, "Obviously, practice makes perfect.", "显然熟能生巧。", "quite obviously"),
  v("apparently", "/据说；看来", "/əˈpærəntli/", "adv.", 4, 0.35, "Apparently, the store closes early on Mondays.", "看来这家店周一关门早。", "apparently so"),
  v("generally", "/通常；总体上", "/ˈdʒenrəli/", "adv.", 2, 0.2, "Generally, buses run every ten minutes.", "公交车通常每十分钟一班。", "generally speaking"),
  v("suggest", "/建议；暗示", "/səˈdʒest/", "v.", 1, 0.15, "I suggest taking the earlier train.", "我建议坐早一点的火车。", "strongly suggest"),
  v("recommendation", "/推荐；建议书", "/ˌrekəmenˈdeɪʃn/", "n.", 3, 0.3, "Follow the doctor's recommendation.", "遵从医生的建议。", "a letter of recommendation"),
  v("oppose", "/反对", "/əˈpoʊz/", "v.", 4, 0.35, "Parents opposed the new school rules.", "家长反对新的校规。", "strongly oppose"),
  v("favor", "/赞同；恩惠", "/ˈfeɪvər/", "n./v.", 1, 0.2, "Are you in favor of the plan?", "你赞成这个计划吗？", "in favor of"),
  v("approve", "/赞成；批准", "/əˈpruːv/", "v.", 3, 0.3, "Her parents approved of her new job.", "她父母赞成她的新工作。", "approve of the plan"),
  v("reject", "/拒绝；否决", "/rɪˈdʒekt/", "v.", 3, 0.3, "The editor rejected my first draft.", "编辑退了我的初稿。", "reject an offer"),
  v("insist", "/坚持(要求)", "/ɪnˈsɪst/", "v.", 3, 0.3, "He insisted on paying for lunch.", "他坚持要付午饭钱。", "insist on the truth"),
  v("point-of-view", "/观点；立场", "/ˌpɔɪnt əv ˈvjuː/", "n.", 3, 0.3, "From my point of view, the price is too high.", "依我看，价格太高了。", "from my point of view"),
  v("on-the-other-hand", "/另一方面", "/ˈʌðər hænd/", "phr.", 3, 0.25, "On the other hand, winter days are cozy.", "另一方面，冬日很温馨。", "on the one hand, on the other hand"),
  v("after-all", "/毕竟；终究", "/ˈæftər ɔːl/", "phr.", 2, 0.2, "After all, he is only five years old.", "毕竟他才五岁。", "after all this time"),
  v("at-least", "/至少", "/æt liːst/", "phr.", 1, 0.1, "Call me at least once a week.", "每周至少给我打一次电话。", "at least once"),
  v("by-the-way", "/顺便说一句", "/baɪ ðə weɪ/", "phr.", 1, 0.1, "By the way, your zipper is down.", "顺便说一句，你拉链开了。", "oh, by the way"),
  v("for-example", "/例如", "/fɔːr ɪɡˈzæmpl/", "phr.", 1, 0.1, "Many jobs are flexible; for example, remote work.", "有些工作允许带宠物，例如一些咖啡馆。", "for example, this app"),
  v("in-fact", "/事实上", "/ɪn fækt/", "phr.", 2, 0.15, "In fact, I finished early.", "事实上我提前完成了。", "in fact, most people agree"),
  v("of-course", "/当然", "/əv kɔːrs/", "phr.", 1, 0.05, "Of course you can borrow it.", "当然可以借你。", "of course not"),
  v("it-depends", "/视情况而定", "/ɪt dɪˈpendz/", "phr.", 2, 0.15, "It depends on the weather.", "这取决于天气。", "it depends on the day"),
  v("however", "/然而；不过", "/haʊˈevər/", "adv.", 1, 0.15, "The plan sounds good; however, it costs too much.", "计划听起来不错；然而成本太高。", "however small it is"),
  v("therefore", "/因此；所以", "/ˈðerfɔːr/", "adv.", 2, 0.2, "The road was icy; therefore, we drove slowly.", "路面结冰，所以我们开得很慢。", "and therefore"),
  v("although", "/虽然；尽管", "/ɔːlˈðoʊ/", "conj.", 1, 0.15, "Although it rained, we had fun.", "虽然下雨，我们还是玩得开心。", "although small, it works"),
  v("moreover", "/此外；而且", "/mɔːrˈoʊvər/", "adv.", 6, 0.45, "The hotel is cheap; moreover, breakfast is free.", "酒店便宜，而且早餐免费。", "moreover, it saves time"),
  v("besides", "/除…之外；况且", "/bɪˈsaɪdz/", "prep./adv.", 2, 0.2, "Besides English, she speaks Japanese.", "除了英语她还会日语。", "besides the point"),
  v("anyway", "/无论如何；反正", "/ˈeniweɪ/", "adv.", 1, 0.1, "Anyway, let's get back to work.", "不管怎样，继续干活吧。", "thanks anyway"),
];
