import { v } from "@/content/vocab/builder";
import type { VocabRow } from "@/content/vocab/types";

/** Experiences, stories & memory - Day 61+ describing experiences. */
export const experienceMemoryRows: VocabRow[] = [
  v("childhood", "/童年", "/ˈtʃaɪldhʊd/", "n.", 2, 0.2, "I spent my childhood by the sea.", "我的童年在海边度过。", "childhood memories"),
  v("youth", "/青春；年轻人", "/juːθ/", "n.", 4, 0.35, "In his youth, he raced bicycles.", "年轻时他参加自行车赛。", "the youth of today"),
  v("milestone", "/里程碑；转折点", "/ˈmaɪlstoʊn/", "n.", 5, 0.45, "Graduating was a huge milestone.", "毕业是一个巨大的里程碑。", "reach a milestone"),
  v("achievement", "/成就", "/əˈtʃiːvmənt/", "n.", 2, 0.25, "Speaking a second language is a real achievement.", "会说第二语言是真正的成就。", "a proud achievement"),
  v("occasion", "/场合；时刻", "/əˈkeɪʒn/", "n.", 3, 0.3, "Wear whatever suits the occasion.", "穿适合场合的衣服。", "on this special occasion"),
  v("incident", "/事件；小事故", "/ˈɪnsɪdənt/", "n.", 5, 0.45, "The manager apologized for the incident.", "经理为那起事故道了歉。", "a strange incident"),
  v("chapter", "/章节；人生篇章", "/ˈtʃæptər/", "n.", 3, 0.2, "Starting college opens a new chapter.", "上大学开启了新篇章。", "the first chapter"),
  v("scene", "/场景；(戏)一场", "/siːn/", "n.", 3, 0.25, "The market scene smelled of spices.", "集市场景弥漫着香料味。", "the opening scene"),
  v("plot", "/情节；密谋", "/plɑːt/", "n.", 4, 0.35, "The plot twists twice in the last hour.", "剧情在最后一小时反转两次。", "follow the plot"),
  v("background", "/背景；出身", "/ˈbækɡraʊnd/", "n.", 2, 0.25, "Her background is in finance.", "她的背景是金融。", "a quiet background"),
  v("highlight", "/亮点；最精彩部分", "/ˈhaɪlaɪt/", "n./v.", 3, 0.25, "The concert highlight was the final song.", "演唱会的高潮是最后一首歌。", "the highlight of the trip"),
  v("turning-point", "/转折点", "/ˈtɜːrnɪŋ pɔɪnt/", "n.", 5, 0.45, "Meeting her was a turning point in my life.", "遇见她是我人生的转折点。", "a major turning point"),
  v("lesson", "/课；教训", "/ˈlesn/", "n.", 1, 0.1, "Every failure teaches a lesson.", "每次失败都给人教训。", "learn your lesson"),
  v("mistake", "/错误", "/mɪˈsteɪk/", "n.", 1, 0.15, "Everyone makes mistakes sometimes.", "人人都会犯错。", "make a mistake"),
  v("fault", "/过错；故障", "/fɔːlt/", "n.", 2, 0.2, "The accident wasn't my fault.", "事故不是我的错。", "it's your fault"),
  v("pride", "/自豪；骄傲", "/praɪd/", "n.", 2, 0.25, "She spoke with pride about her team.", "她自豪地谈起自己的团队。", "take pride in your work"),
  v("shame", "/羞耻；遗憾", "/ʃeɪm/", "n.", 2, 0.2, "What a shame — the show sold out.", "真遗憾——票卖光了。", "what a shame!"),
  v("honor", "/荣誉；尊敬", "/ˈɑːnər/", "n./v.", 4, 0.35, "It's an honor to meet you.", "见到您很荣幸。", "a great honor"),
  v("unforgettable", "/难忘的", "/ˌʌnfərˈɡetəbl/", "adj.", 3, 0.3, "The trip was unforgettable.", "那次旅行令人难忘。", "an unforgettable night"),
  v("meaningful", "/有意义的", "/ˈmiːnɪŋfl/", "adj.", 3, 0.25, "Volunteering feels meaningful.", "做志愿者很有意义。", "a meaningful conversation"),
  v("memorable", "/值得纪念的", "/ˈmemərəbl/", "adj.", 4, 0.3, "It was the most memorable day of the summer.", "那是今夏最难忘的一天。", "a memorable trip"),
  v("vivid", "/生动的；鲜明的", "/ˈvɪvɪd/", "adj.", 6, 0.45, "I still have vivid memories of that night.", "我对那晚仍记忆犹新。", "a vivid description"),
  v("vague", "/模糊的", "/veɪɡ/", "adj.", 5, 0.4, "I only have a vague idea of the plan.", "我对这个计划只有一个模糊的概念。", "a vague answer"),
  v("recent", "/最近的", "/ˈriːsnt/", "adj.", 1, 0.15, "Recent rain made the trail muddy.", "近来的雨把小路弄得泥泞。", "in recent years"),
  v("journal", "/日记本；期刊", "/ˈdʒɜːrnl/", "n.", 4, 0.35, "She keeps a travel journal.", "她记旅行日志。", "keep a journal"),
  v("blog", "/博客", "/blɑːɡ/", "n./v.", 3, 0.2, "He writes a food blog.", "他写美食博客。", "start a blog"),
  v("post", "/帖子；邮件；张贴", "/poʊst/", "n./v.", 1, 0.1, "Her post got a hundred likes.", "她的帖子获得一百个赞。", "share a post"),
  v("comment", "/评论", "/ˈkɑːment/", "n./v.", 2, 0.2, "Leave a comment below the video.", "在视频下方留言。", "post a comment"),
  v("follower", "/粉丝；追随者", "/ˈfɑːloʊər/", "n.", 3, 0.25, "The chef has a million followers.", "这位厨师有一百万粉丝。", "gain followers fast"),
  v("influencer", "/网红；博主", "/ˈɪnfluənsər/", "n.", 5, 0.35, "The influencer reviewed our cafe.", "那位博主测评了我们的咖啡馆。", "a fashion influencer"),
  v("emoji", "/表情符号", "/ɪˈmoʊdʒi/", "n.", 3, 0.15, "Add an emoji to soften the message.", "加个表情让语气柔和些。", "send a smiley emoji"),
  v("meme", "/梗图；网络迷因", "/miːm/", "n.", 5, 0.25, "That cat meme made my day.", "那张猫梗图让我开心了一整天。", "a viral meme"),
  v("viral", "/疯传的", "/ˈvaɪrəl/", "adj.", 5, 0.35, "The dance video went viral overnight.", "舞蹈视频一夜爆红。", "go viral online"),
  v("tale", "/故事；传说", "/teɪl/", "n.", 4, 0.3, "Grandpa told tales of his sailor days.", "爷爷讲他当水手时的故事。", "an old tale"),
  v("legend", "/传说；传奇人物", "/ˈledʒənd/", "n.", 4, 0.35, "Local legend says the lake is bottomless.", "当地传说这个湖深不见底。", "a basketball legend"),
  v("fairy-tale", "/童话", "/ˈferi teɪl/", "n.", 3, 0.2, "Cinderella is a classic fairy tale.", "《灰姑娘》是经典童话。", "a fairy-tale ending"),
  v("myth", "/神话；误解", "/mɪθ/", "n.", 5, 0.4, "It's a myth that goldfish forget everything quickly.", "金鱼很快忘事是个误解。", "an ancient myth"),
  v("rumor", "/谣言", "/ˈruːmər/", "n.", 3, 0.3, "Don't spread rumors about coworkers.", "不要散播同事的谣言。", "hear a rumor"),
];
