import { v } from "@/content/vocab/builder";
import type { VocabRow } from "@/content/vocab/types";

/** News & media - Day 61+ news basics theme. */
export const newsMedia2Rows: VocabRow[] = [
  v("headline", "/标题；头条", "/ˈhedlaɪn/", "n.", 3, 0.25, "The headline caught my eye.", "这个标题吸引了我的目光。", "make the headlines"),
  v("article", "/文章", "/ˈɑːrtɪkl/", "n.", 2, 0.2, "She wrote an article about remote work.", "她写了一篇关于远程工作的文章。", "read a news article"),
  v("editor", "/编辑", "/ˈedɪtər/", "n.", 3, 0.3, "The editor shortened my story.", "编辑缩短了我的稿子。", "a magazine editor"),
  v("breaking-news", "/突发新闻", "/ˈbreɪkɪŋ nuːz/", "n.", 3, 0.2, "Breaking news interrupted the show.", "突发新闻打断了节目。", "a breaking-news alert"),
  v("front-page", "/头版的", "/ˌfrʌnt ˈpeɪdʒ/", "adj./n.", 4, 0.3, "The storm made front-page news.", "风暴上了头版新闻。", "a front-page story"),
  v("broadcast", "/广播；播出", "/ˈbrɔːdkæst/", "v./n.", 4, 0.35, "The game broadcasts live at seven.", "比赛七点直播。", "a live broadcast"),
  v("coverage", "/报道覆盖面", "/ˈkʌvərɪdʒ/", "n.", 6, 0.5, "Local coverage of the flood was excellent.", "当地对洪水的报道非常到位。", "news coverage"),
  v("media", "/媒体", "/ˈmiːdiə/", "n.", 2, 0.2, "Social media spreads rumors fast.", "社交媒体传谣很快。", "social media"),
  v("source", "/来源；消息源", "/sɔːrs/", "n.", 2, 0.25, "Check the source before sharing.", "转发前先查来源。", "a reliable source"),
  v("fake-news", "/假新闻", "/ˌfeɪk ˈnuːz/", "n.", 3, 0.25, "Fake-news spreads faster than facts.", "假新闻比事实传播更快。", "spot fake-news"),
  v("bias", "/偏见；偏向", "/ˈbaɪəs/", "n.", 5, 0.45, "Every reporter has some bias.", "每个记者都有些偏向。", "political bias"),
  v("survey", "/调查；问卷", "/ˈsɜːrveɪ/", "n./v.", 3, 0.3, "A recent survey asked about sleep habits.", "最近一项调查询问了睡眠习惯。", "take part in a survey"),
  v("poll", "/民意调查", "/poʊl/", "n.", 5, 0.45, "Opinion polls predict a close race.", "民调显示选情胶着。", "an opinion poll"),
  v("statistics", "/统计数据", "/stəˈtɪstɪks/", "n.", 5, 0.45, "Statistics show fewer smokers now.", "统计显示烟民减少了。", "according to statistics"),
  v("chart", "/图表", "/tʃɑːrt/", "n.", 2, 0.2, "The pie chart shows monthly costs.", "饼图显示了每月开销。", "draw a chart"),
  v("graph", "/曲线图；坐标图", "/ɡræf/", "n.", 3, 0.25, "The graph rises sharply in June.", "曲线在六月陡然上升。", "plot a graph"),
  v("figure", "/数字；人物；身材", "/ˈfɪɡjər/", "n.", 3, 0.3, "Sales figures doubled this year.", "今年销售数字翻倍。", "official figures"),
  v("percent", "/百分比", "/pərˈsent/", "n.", 1, 0.15, "Twenty percent agreed with the change.", "百分之二十的人同意这一改变。", "fifty percent off"),
  v("majority", "/多数；大多数", "/məˈdʒɔːrəti/", "n.", 3, 0.3, "The majority voted yes.", "大多数人投了赞成票。", "the vast majority"),
  v("minority", "/少数；少数群体", "/maɪˈnɔːrəti/", "n.", 4, 0.35, "A small minority disagreed.", "少数人不同意。", "protect minority rights"),
  v("candidate", "/候选人", "/ˈkændɪdət/", "n.", 4, 0.35, "Three candidates joined the debate.", "三位候选人参加了辩论。", "a strong candidate"),
  v("policy", "/政策；方针", "/ˈpɑːləsi/", "n.", 3, 0.3, "The city changed its recycling policy.", "城市修改了回收政策。", "a new policy on housing"),
  v("president", "/总统；总裁", "/ˈprezɪdənt/", "n.", 1, 0.15, "The president gave a short speech.", "总统发表了简短讲话。", "the company president"),
  v("trial", "/审判；试验", "/ˈtraɪəl/", "n.", 5, 0.45, "The trial lasted three weeks.", "审判持续了三周。", "a fair trial"),
  v("jury", "/陪审团", "/ˈdʒʊri/", "n.", 6, 0.5, "The jury reached a decision by noon.", "陪审团中午前做出了裁定。", "sit on a jury"),
  v("witness", "/目击者；见证", "/ˈwɪtnəs/", "n./v.", 4, 0.4, "One witness recorded everything.", "一名目击者录下了一切。", "call a witness"),
  v("evidence", "/证据", "/ˈevɪdəns/", "n.", 3, 0.3, "There isn't enough evidence yet.", "目前证据不足。", "gather evidence"),
  v("criminal", "/罪犯；犯罪的", "/ˈkrɪmɪnl/", "n./adj.", 3, 0.3, "Police caught the criminals within hours.", "警察几小时内抓到罪犯。", "a criminal record"),
  v("victim", "/受害者", "/ˈvɪktɪm/", "n.", 4, 0.35, "The scam targeted elderly victims.", "骗局专门针对老年受害者。", "help victims of fraud"),
  v("prison", "/监狱", "/ˈprɪzn/", "n.", 2, 0.25, "He spent five years in prison.", "他坐了五年牢。", "be sent to prison"),
  v("prisoner", "/囚犯", "/ˈprɪznər/", "n.", 4, 0.35, "The prisoner read law books daily.", "囚犯每天读法律书。", "release a prisoner"),
  v("officer", "/官员；警官", "/ˈɔːfɪsər/", "n.", 2, 0.2, "Officer Lee took our statement.", "李警官做了笔录。", "report it to an officer"),
  v("press-conference", "/新闻发布会", "/ˈpres ˌkɑːnfərəns/", "n.", 5, 0.4, "The mayor held a press-conference.", "市长召开了新闻发布会。", "hold a press-conference"),
  v("statement", "/声明；陈述", "/ˈsteɪtmənt/", "n.", 3, 0.3, "The company released a short statement.", "公司发布了一份简短声明。", "issue a statement"),
  v("announcement", "/公告；宣布", "/əˈnaʊnsmənt/", "n.", 2, 0.2, "The announcement surprised everyone.", "公告让所有人意外。", "make an announcement"),
  v("announce", "/宣布", "/əˈnaʊns/", "v.", 2, 0.2, "They announced the winner at midnight.", "他们在午夜宣布了获胜者。", "announce the results"),
  v("issue", "/问题；(杂志)期", "/ˈɪʃuː/", "n./v.", 1, 0.2, "Pollution is a serious issue here.", "污染是这里的严重问题。", "a key issue in the debate"),
  v("topic", "/话题；主题", "/ˈtɑːpɪk/", "n.", 2, 0.15, "Climate is today's main topic.", "气候是今天的主要话题。", "change the topic"),
  v("protest", "/抗议", "/ˈproʊtest/", "n./v.", 4, 0.4, "Workers protested outside the factory.", "工人们在工厂外抗议。", "join a peaceful protest"),
  v("reform", "/改革", "/rɪˈfɔːrm/", "n./v.", 6, 0.55, "Tax reform takes effect next year.", "税改明年生效。", "push for reform"),
  v("rights", "/权利", "/raɪts/", "n.", 2, 0.25, "Know your rights as a tenant.", "了解你作为租客的权利。", "equal rights for everyone"),
];
