import { v } from "@/content/vocab/builder";
import type { VocabRow } from "@/content/vocab/types";

/** Money & banking - Day 31+ shopping/work support vocabulary. */
export const moneyBanking2Rows: VocabRow[] = [
  v("expense", "/花费；开支", "/ɪkˈspens/", "n.", 3, 0.3, "Coffee is my biggest daily expense.", "咖啡是我每天最大的开销。", "cut expenses"),
  v("savings", "/积蓄；储蓄", "/ˈseɪvɪŋz/", "n.", 2, 0.2, "We keep savings for emergencies.", "我们存钱以备急用。", "dip into savings"),
  v("deposit", "/存款；押金", "/dɪˈpɑːzɪt/", "n./v.", 4, 0.35, "The landlord asked for one month's deposit.", "房东要求一个月的押金。", "make a deposit"),
  v("withdraw", "/取款；撤回", "/wɪðˈdrɔː/", "v.", 4, 0.4, "Withdraw cash before the trip.", "旅行前先取些现金。", "withdraw money from an atm"),
  v("atm", "/自动取款机", "/ˌeɪ tiː ˈem/", "n.", 1, 0.1, "There's an atm near the entrance.", "入口附近有一台取款机。", "find the nearest atm"),
  v("credit-card", "/信用卡", "/ˈkredɪt kɑːrd/", "n.", 1, 0.15, "Do you take credit cards?", "这里收信用卡吗？", "pay by credit-card"),
  v("debit-card", "/借记卡", "/ˈdebɪt kɑːrd/", "n.", 2, 0.2, "Use your debit-card to avoid debt.", "用借记卡避免负债。", "a debit-card payment"),
  v("rate", "/比率；费率", "/reɪt/", "n.", 2, 0.25, "The interest rate rose this month.", "这个月利率上升了。", "a special rate for students"),
  v("mortgage", "/房贷；抵押贷款", "/ˈmɔːrɡɪdʒ/", "n.", 6, 0.55, "They finally paid off the mortgage.", "他们终于还清了房贷。", "apply for a mortgage"),
  v("invoice", "/发票；账单", "/ˈɪnvɔɪs/", "n.", 5, 0.45, "Send the invoice by Friday.", "周五前把发票发来。", "pay the invoice"),
  v("paycheck", "/工资支票；薪水", "/ˈpeɪtʃek/", "n.", 4, 0.3, "Rent eats half my paycheck.", "房租吃掉我一半工资。", "live paycheck to paycheck"),
  v("profit", "/利润", "/ˈprɑːfɪt/", "n./v.", 3, 0.3, "The bakery turned a profit in June.", "面包店六月实现了盈利。", "make a profit"),
  v("loss", "/亏损；损失", "/lɔːs/", "n.", 2, 0.25, "The store reported a small loss.", "商店报告了小幅亏损。", "at a loss"),
  v("revenue", "/收入；营收", "/ˈrevənuː/", "n.", 6, 0.5, "Ad revenue pays for the free app.", "广告收入支撑着免费应用。", "annual revenue"),
  v("investment", "/投资", "/ɪnˈvestmənt/", "n.", 4, 0.4, "Education is the best investment.", "教育是最好的投资。", "a smart investment"),
  v("investor", "/投资者", "/ɪnˈvestər/", "n.", 5, 0.45, "Investors loved the pitch.", "投资者很喜欢这个路演。", "attract investors"),
  v("fund", "/基金；资金", "/fʌnd/", "n./v.", 3, 0.35, "The school started a repair fund.", "学校设立了维修基金。", "raise funds for charity"),
  v("scholarship", "/奖学金", "/ˈskɑːlərʃɪp/", "n.", 4, 0.35, "She won a full scholarship.", "她获得了全额奖学金。", "apply for a scholarship"),
  v("tuition", "/学费", "/tuːˈɪʃn/", "n.", 5, 0.45, "Tuition rises every year.", "学费年年上涨。", "college tuition"),
  v("fee", "/费用", "/fiː/", "n.", 2, 0.2, "There's no fee for kids under five.", "五岁以下儿童免费。", "an annual fee"),
  v("costly", "/代价高的；昂贵的", "/ˈkɔːstli/", "adj.", 4, 0.3, "Car repairs can be costly.", "汽车修理可能很贵。", "a costly mistake"),
  v("pricey", "/偏贵的", "/ˈpraɪsi/", "adj.", 4, 0.25, "That restaurant is tasty but pricey.", "那家餐厅好吃但贵。", "a bit pricey"),
  v("broke", "/身无分文的", "/broʊk/", "adj.", 3, 0.2, "I'm broke until payday.", "发工资前我一分钱都没有。", "go broke"),
  v("wealth", "/财富", "/welθ/", "n.", 4, 0.35, "Health matters more than wealth.", "健康比财富更重要。", "a wealth of experience"),
  v("poverty", "/贫困", "/ˈpɑːvərti/", "n.", 4, 0.4, "The program fights child poverty.", "该项目致力于消除儿童贫困。", "live in poverty"),
  v("fortune", "/财产；运气", "/ˈfɔːrtʃən/", "n.", 3, 0.3, "That car must have cost a fortune.", "那辆车一定花了一大笔钱。", "make a fortune"),
  v("charity", "/慈善机构；施舍", "/ˈtʃærəti/", "n.", 3, 0.3, "She donates monthly to an animal charity.", "她每月向一家动物慈善机构捐款。", "donate to charity"),
  v("donate", "/捐赠", "/ˈdoʊneɪt/", "v.", 2, 0.2, "Donate old clothes instead of tossing them.", "旧衣服捐掉而不是扔掉。", "donate blood"),
  v("donation", "/捐款；捐赠物", "/doʊˈneɪʃn/", "n.", 3, 0.25, "Every small donation helps.", "每一笔小额捐款都有帮助。", "make a donation"),
  v("sponsor", "/赞助商；赞助", "/ˈspɑːnsər/", "n./v.", 5, 0.4, "A local bank sponsors the team.", "当地一家银行赞助这支队伍。", "find a sponsor"),
  v("cost", "/成本；费用", "/kɔːst/", "n./v.", 1, 0.15, "Shipping costs are included.", "运费已包含在内。", "at no extra cost"),
  v("payment", "/付款；款项", "/ˈpeɪmənt/", "n.", 1, 0.15, "Your payment went through.", "你的付款成功了。", "accept online payments"),
  v("down-payment", "/首付", "/ˈdaʊn ˌpeɪmənt/", "n.", 6, 0.5, "We saved for years for the down-payment.", "我们为攒首付存了好几年。", "a twenty-percent down-payment"),
  v("dollar", "/美元", "/ˈdɑːlər/", "n.", 1, 0.05, "It costs just one dollar.", "它只要一美元。", "a five-dollar bill"),
  v("cent", "/美分", "/sent/", "n.", 1, 0.1, "It costs ninety-nine cents.", "它卖九毛九。", "not one cent more"),
  v("penny", "/一分硬币", "/ˈpeni/", "n.", 2, 0.1, "I found a lucky penny on the sidewalk.", "我在人行道上捡到一枚幸运便士。", "a penny for your thoughts"),
  v("quarter", "/二十五美分硬币；四分之一", "/ˈkwɔːrtər/", "n.", 1, 0.15, "Feed the meter with two quarters.", "投两个两毛五喂停车计时器。", "a quarter past nine"),
  v("nickel", "/五美分镍币", "/ˈnɪkl/", "n.", 6, 0.35, "A nickel is worth five cents.", "一枚镍币值五美分。", "a shiny nickel"),
  v("dime", "/十美分硬币", "/daɪm/", "n.", 6, 0.35, "A dime is the smallest coin here.", "一角硬币是这里最小的硬币。", "stop on a dime"),
  v("cashless", "/无现金的", "/ˈkæʃləs/", "adj.", 6, 0.4, "Many cafes are going cashless.", "许多咖啡馆正在转向无现金支付。", "a cashless society"),
];
