import { v } from "@/content/vocab/builder";
import type { VocabRow } from "@/content/vocab/types";

/** Education & study - supports Day 61+ discussion topics. */
export const educationStudy2Rows: VocabRow[] = [
  v("college", "/学院；大学", "/ˈkɑːlɪdʒ/", "n.", 1, 0.1, "My sister starts college in fall.", "我妹妹秋天上大学。", "go to college"),
  v("university", "/大学(综合性)", "/ˌjuːnɪˈvɜːrsəti/", "n.", 1, 0.1, "Which university did you attend?", "你上的是哪所大学？", "a top university"),
  v("campus", "/校园", "/ˈkæmpəs/", "n.", 2, 0.15, "The dorms are on the north campus.", "宿舍在北校区。", "live on campus"),
  v("freshman", "/(大学/高中)一年级学生", "/ˈfreʃmən/", "n.", 4, 0.3, "Freshmen move in a week early.", "大一新生提前一周入住。", "a college freshman"),
  v("sophomore", "/二年级学生", "/ˈsɑːfmɔːr/", "n.", 6, 0.45, "As a sophomore, she picked harder courses.", "大二时她选了课程。", "a sophomore year project"),
  v("junior", "/三年级学生；较年幼者", "/ˈdʒuːniər/", "n./adj.", 3, 0.25, "Juniors take the practice exam in spring.", "高三学生在春天参加模拟考试。", "a junior developer"),
  v("senior", "/毕业班学生；年长者", "/ˈsiːnjər/", "n./adj.", 2, 0.2, "Seniors graduate in May.", "毕业班五月离校。", "respect your seniors"),
  v("semester", "/学期", "/sɪˈmestər/", "n.", 2, 0.2, "The semester ends in December.", "学期十二月结束。", "this semester's schedule"),
  v("lecture", "/讲座；讲课", "/ˈlektʃər/", "n./v.", 2, 0.2, "The biology lecture starts at ten sharp.", "生物课十点整开始。", "attend a lecture"),
  v("professor", "/教授", "/prəˈfesər/", "n.", 2, 0.2, "Professor Chen teaches linguistics.", "陈教授教语言学。", "a visiting professor"),
  v("tutor", "/家教；导师", "/ˈtuːtər/", "n./v.", 3, 0.25, "Her math tutor explains things clearly.", "她的数学家教讲解清晰。", "hire a tutor"),
  v("course", "/课程", "/kɔːrs/", "n.", 1, 0.1, "I signed up for an online course.", "我报名了一门网课。", "take a course in coding"),
  v("curriculum", "/课程体系", "/kəˈrɪkjələm/", "n.", 6, 0.55, "The school updated its curriculum.", "学校更新了课程体系。", "the national curriculum"),
  v("syllabus", "/教学大纲", "/ˈsɪləbəs/", "n.", 7, 0.6, "Read the syllabus before week one.", "第一周前先读教学大纲。", "follow the syllabus"),
  v("quiz", "/小测验", "/kwɪz/", "n./v.", 1, 0.1, "There's a vocab quiz every Friday.", "每周五有词汇小测。", "pop quiz!"),
  v("test", "/测试；考试", "/test/", "n./v.", 1, 0.1, "The driving test has two parts.", "驾照考试分两部分。", "pass the test"),
  v("classmate", "/同学", "/ˈklæsmeɪt/", "n.", 1, 0.1, "My classmates organized a study group.", "同学们组了学习小组。", "an old classmate"),
  v("graduate", "/毕业；毕业生", "/ˈɡrædʒueɪt/", "v./n.", 1, 0.15, "He graduates from high school this June.", "他今年六月高中毕业。", "graduate with honors"),
  v("graduation", "/毕业典礼", "/ˌɡrædʒuˈeɪʃn/", "n.", 2, 0.2, "Graduation is on the twentieth.", "毕业典礼在二十号。", "a graduation ceremony"),
  v("diploma", "/文凭；毕业证书", "/dɪˈploʊmə/", "n.", 5, 0.45, "She framed her diploma.", "她把毕业证书装了框。", "a high school diploma"),
  v("certificate", "/证书", "/sərˈtɪfɪkət/", "n.", 3, 0.35, "Get a certificate in first aid.", "考一个急救证书。", "a teaching certificate"),
  v("research", "/研究", "/rɪˈsɜːrtʃ/", "n./v.", 2, 0.2, "Their research focuses on sleep.", "他们的研究聚焦睡眠。", "do research on pandas"),
  v("researcher", "/研究员", "/rɪˈsɜːrtʃər/", "n.", 4, 0.35, "Researchers interviewed fifty families.", "研究人员访谈了五十个家庭。", "a field researcher"),
  v("thesis", "/论文；论点", "/ˈθiːsɪs/", "n.", 7, 0.6, "Her thesis took eight months.", "她的论文花了八个月。", "write a thesis"),
  v("draft", "/草稿", "/dræft/", "n./v.", 4, 0.35, "Send me your first draft tonight.", "今晚把你初稿发我。", "a rough draft"),
  v("revise", "/修改；温习", "/rɪˈvaɪz/", "v.", 4, 0.35, "Revise your essay after feedback.", "根据反馈修改文章。", "revise for finals"),
  v("memorize", "/记住；背诵", "/ˈmeməraɪz/", "v.", 2, 0.2, "Memorize these twenty verbs.", "记住这二十个动词。", "memorize a poem"),
  v("distract", "/使分心", "/dɪˈstrækt/", "v.", 3, 0.3, "Phones distract students in class.", "手机让课堂上的人分心。", "don't distract the driver"),
  v("focus", "/焦点；专注", "/ˈfoʊkəs/", "n./v.", 1, 0.15, "Focus on one task at a time.", "一次专注一件事。", "lose focus easily"),
  v("elective", "/选修课", "/ˈelektɪv/", "n./adj.", 6, 0.5, "Photography is my favorite elective.", "摄影是我最喜欢的选修课。", "an elective course"),
  v("report-card", "/成绩单", "/rɪˈpɔːrt kɑːrd/", "n.", 4, 0.3, "Report cards come out Friday.", "成绩单周五发放。", "bring home a good report-card"),
  v("recess", "/课间休息", "/ˈriːses/", "n.", 6, 0.4, "Kids play tag at recess.", "孩子们课间玩捉人游戏。", "outdoor recess"),
  v("principal", "/校长", "/ˈprɪnsɪpl/", "n./adj.", 4, 0.3, "Our principal greets us at the gate.", "我们校长在大门口迎接大家。", "the school principal"),
  v("counselor", "/辅导员；顾问", "/ˈkaʊnsələr/", "n.", 5, 0.4, "See the counselor about course options.", "关于选课去找辅导员。", "talk to a counselor"),
  v("peer-pressure", "/同伴压力", "/pɪr/", "n.", 5, 0.4, "Peer pressure affects teens strongly.", "同伴压力对青少年影响很大。", "resist peer pressure"),
  v("bullying", "/霸凌", "/ˈbʊliɪŋ/", "n.", 4, 0.3, "Schools must stop bullying early.", "学校必须尽早制止霸凌。", "stand up to bullying"),
  v("literacy", "/读写能力", "/ˈlɪtərəsi/", "n.", 6, 0.5, "Reading aloud builds literacy.", "朗读能培养读写能力。", "improve digital literacy"),
  v("fluency", "/流利度", "/ˈfluːənsi/", "n.", 4, 0.35, "Daily speaking improves fluency.", "每天开口提升流利度。", "gain fluency fast"),
];
