import { v } from "@/content/vocab/builder";
import type { VocabRow } from "@/content/vocab/types";

/** Technology & digital life - modern daily vocabulary. */
export const techDigital2Rows: VocabRow[] = [
  v("laptop", "/笔记本电脑", "/ˈlæptɑːp/", "n.", 1, 0.1, "My laptop needs a new battery.", "我的笔记本需要换电池。", "shut the laptop"),
  v("tablet", "/平板电脑；药片", "/ˈtæblət/", "n.", 2, 0.15, "Kids watch cartoons on the tablet.", "孩子们在平板上看动画片。", "a drawing tablet"),
  v("smartphone", "/智能手机", "/ˈsmɑːrtfoʊn/", "n.", 1, 0.1, "Smartphones replaced alarm clocks for many people.", "对很多人来说手机取代了闹钟。", "unlock your smartphone"),
  v("wifi", "/无线网络", "/ˈwaɪfaɪ/", "n.", 1, 0.1, "What's the wifi password?", "Wi-Fi 密码是多少？", "connect to the wifi"),
  v("login", "/登录；登录信息", "/ˈlɔːɡɪn/", "n./v.", 3, 0.25, "Your login works on any device.", "你的账号在任何设备上都能用。", "save your login details"),
  v("install", "/安装", "/ɪnˈstɔːl/", "v.", 2, 0.2, "Install the update tonight.", "今晚安装更新。", "install a new app"),
  v("hardware", "/硬件", "/ˈhɑːrdwer/", "n.", 4, 0.35, "Old hardware slows everything down.", "旧硬件会拖慢一切。", "upgrade your hardware"),
  v("bug", "/程序错误；虫子", "/bʌɡ/", "n.", 2, 0.2, "The update fixed that annoying bug.", "更新修复了那个烦人的错误。", "fix a bug"),
  v("browser", "/浏览器", "/ˈbraʊzər/", "n.", 2, 0.2, "Open the link in another browser.", "用另一个浏览器打开链接。", "clear the browser cache"),
  v("search-engine", "/搜索引擎", "/ˈsɜːrtʃ ˌendʒɪn/", "n.", 3, 0.3, "The search engine suggested similar shops.", "搜索引擎推荐了类似的店。", "use a search engine"),
  v("click", "/点击", "/klɪk/", "v./n.", 1, 0.05, "Click the blue button to continue.", "点击蓝色按钮继续。", "click on the link"),
  v("scroll", "/滚动；滑动屏幕", "/skroʊl/", "v.", 2, 0.15, "Scroll down to see the comments.", "往下滚动看评论。", "scroll through photos"),
  v("swipe", "/滑动；刷(卡)", "/swaɪp/", "v.", 2, 0.15, "Swipe left to dismiss the photo.", "左滑关闭照片。", "swipe your card here"),
  v("tap", "/轻点；轻拍", "/tæp/", "v./n.", 1, 0.1, "Tap the icon twice.", "双击那个图标。", "tap to pay at checkout"),
  v("folder", "/文件夹", "/ˈfoʊldər/", "n.", 1, 0.1, "Create a folder for receipts.", "建一个收据文件夹。", "drag it into a folder"),
  v("attachment", "/附件", "/əˈtætʃmənt/", "n.", 3, 0.3, "I attached the photos as attachments.", "我把照片作为附件发过去了。", "open the attachment"),
  v("notification", "/通知", "/ˌnoʊtɪfɪˈkeɪʃn/", "n.", 3, 0.3, "Turn off notifications after nine.", "九点后关掉通知。", "mute app notifications"),
  v("mute", "/静音；消音", "/mjuːt/", "v./adj.", 2, 0.2, "Mute yourself during the meeting.", "开会时把自己静音。", "keep the phone on mute"),
  v("volume", "/音量；体积", "/ˈvɑːljum/", "n.", 1, 0.1, "Turn the volume down, please.", "请把音量调低。", "raise the volume"),
  v("headphones", "/耳机(头戴)", "/ˈhedfoʊnz/", "n.", 1, 0.1, "I study with headphones on.", "我戴着耳机学习。", "noise-canceling headphones"),
  v("earbuds", "/入耳式耳机", "/ˈɪrbʌdz/", "n.", 4, 0.25, "Wireless earbuds are everywhere now.", "无线耳机现在到处都是。", "pair your earbuds"),
  v("microphone", "/麦克风", "/ˈmaɪkrəfoʊn/", "n.", 2, 0.2, "Speak into the microphone clearly.", "对着麦克风清晰讲话。", "test the microphone"),
  v("selfie", "/自拍", "/ˈselfi/", "n.", 1, 0.1, "Let's take a selfie by the gate.", "我们在门口自拍一张吧。", "take a group selfie"),
  v("filter", "/滤镜；过滤器", "/ˈfɪltər/", "n./v.", 3, 0.3, "This photo filter hides messy desks.", "这个滤镜能遮住乱桌子。", "apply a warm filter"),
  v("offline", "/离线的", "/ˌɔːfˈlaɪn/", "adj./adv.", 2, 0.2, "The maps work offline too.", "地图离线也能用。", "go offline for a day"),
  v("gadget", "/小玩意儿；设备", "/ˈɡædʒɪt/", "n.", 5, 0.35, "Kitchen gadgets save time.", "厨房小工具省时间。", "the latest gadgets"),
  v("artificial-intelligence", "/人工智能", "/ˌɑːrtɪˈfɪʃl ɪnˈtelɪdʒəns/", "n.", 4, 0.35, "Artificial intelligence writes drafts now.", "人工智能现在能写初稿了。", "powered by artificial intelligence"),
  v("chatbot", "/聊天机器人", "/ˈtʃætbɑːt/", "n.", 4, 0.3, "The chatbot answered instantly.", "聊天机器人秒回。", "talk to a chatbot"),
  v("algorithm", "/算法", "/ˈælɡərɪðəm/", "n.", 6, 0.55, "The algorithm picks what you watch next.", "算法决定你下一个看什么。", "how the algorithm works"),
  v("coding", "/编程", "/ˈkoʊdɪŋ/", "n.", 3, 0.25, "Coding classes start in April.", "编程课四月开班。", "learn basic coding"),
  v("hacker", "/黑客", "/ˈhækər/", "n.", 4, 0.35, "A hacker tried to steal user accounts.", "一名黑客试图窃取用户账号。", "beware of hackers"),
  v("backup", "/备份", "/ˈbækʌp/", "n./v.", 4, 0.35, "Keep a backup of your photos.", "给照片留个备份。", "make a weekly backup"),
  v("sync", "/同步", "/sɪŋk/", "v.", 4, 0.35, "Sync your notes across devices.", "在设备间同步笔记。", "sync your calendar"),
  v("delete", "/删除", "/dɪˈliːt/", "v.", 1, 0.15, "Delete the duplicate file.", "删除重复文件。", "delete old emails"),
  v("paste", "/粘贴", "/peɪst/", "v.", 1, 0.1, "Paste the link into the chat.", "把链接粘贴到聊天里。", "copy and paste"),
  v("touchscreen", "/触摸屏", "/ˈtʌtʃskriːn/", "n.", 3, 0.2, "The touchscreen responds quickly.", "触摸屏反应很快。", "a cracked touchscreen"),
  v("drone", "/无人机；嗡嗡声", "/droʊn/", "n.", 5, 0.35, "A drone filmed the whole race.", "一架无人机拍下了整场比赛。", "fly a drone legally"),
  v("livestream", "/直播", "/ˈlaɪvstriːm/", "n./v.", 4, 0.3, "They livestream every match.", "他们直播每场比赛。", "watch the livestream"),
  v("screenshot", "/截屏；截图", "/ˈskriːnʃɑːt/", "n./v.", 2, 0.2, "Send me a screenshot of the error.", "把报错截图发我。", "take a screenshot"),
  v("usb", "/USB 接口", "/ˌjuː es ˈbiː/", "n.", 2, 0.15, "Plug the fan into a USB port.", "把风扇插到 USB 口上。", "a spare USB port"),
];
