import { v } from "@/content/vocab/builder";
import type { VocabRow } from "@/content/vocab/types";

/** High-frequency phrasal verbs as lexical chunks (B1). */
export const phrasalCoreRows: VocabRow[] = [
  v("give-up", "/放弃", "/ˌɡɪv ˈʌp/", "v.", 1, 0.15, "Never give up after one bad grade.", "一次考砸别放弃。", "give up smoking"),
  v("look-for", "/寻找", "/ˌlʊk ˈfɔːr/", "v.", 1, 0.1, "I'm looking for my keys.", "我在找钥匙。", "look for a job"),
  v("find-out", "/查明；发现", "/ˌfaɪnd ˈaʊt/", "v.", 1, 0.15, "Find out what time it opens.", "查一下几点开门。", "find out the truth"),
  v("pick-up", "/接(人)；拿起；学会", "/ˈpɪk ʌp/", "v./n.", 1, 0.1, "Pick up the kids at three.", "三点去接孩子。", "pick up a new language"),
  v("turn-on", "/打开", "/ˌtɜːrn ˈɑːn/", "v.", 1, 0.05, "Turn on the lights, please.", "请开灯。", "turn on the tv"),
  v("turn-off", "/关掉", "/ˌtɜːrn ˈɔːf/", "v.", 1, 0.05, "Turn off your phone in class.", "上课把手机关掉。", "turn off the tap"),
  v("put-on", "/穿上；增加", "/ˌpʊt ˈɑːn/", "v.", 1, 0.05, "Put on a coat — it's cold.", "穿件外套——外面冷。", "put on some weight"),
  v("take-off", "/脱下；(飞机)起飞", "/ˌteɪk ˈɔːf/", "v.", 1, 0.1, "Take off wet shoes at the door.", "进门脱掉湿鞋。", "the plane takes off at noon"),
  v("get-up", "/起床；站起来", "/ˌɡet ˈʌp/", "v.", 1, 0.05, "I get up at six on weekdays.", "工作日我六点起床。", "get up early"),
  v("wake-up", "/醒来；叫醒", "/ˌweɪk ˈʌp/", "v.", 1, 0.05, "Wake me up before you leave.", "你走之前叫醒我。", "wake up suddenly"),
  v("sit-down", "/坐下", "/ˌsɪt ˈdaʊn/", "v.", 1, 0.05, "Sit down and make yourself comfortable.", "坐下别拘束。", "sit down for dinner"),
  v("stand-up", "/起立；站起身", "/ˌstænd ˈʌp/", "v.", 1, 0.05, "Everyone stood up when she entered.", "她进来时大家都站了起来。", "stand up straight"),
  v("come-back", "/回来；重返", "/kəm ˈbæk/", "v.", 1, 0.1, "Come back soon!", "早点回来！", "come back later"),
  v("go-out", "/外出；出门", "/ˌɡoʊ ˈaʊt/", "v.", 1, 0.05, "Let's go out tonight.", "今晚我们出去吧。", "go out for dinner"),
  v("grow-up", "/长大", "/ˌɡroʊ ˈʌp/", "v.", 1, 0.1, "Where did you grow up?", "你在哪儿长大的？", "when I grow up"),
  v("hurry-up", "/赶快", "/ˌhɜːri ˈʌp/", "v.", 1, 0.1, "Hurry up or we'll miss the bus!", "快点，不然赶不上公交了！", "hurry up, please"),
  v("calm-down", "/冷静下来", "/ˌkɑːm ˈdaʊn/", "v.", 1, 0.1, "Calm down and take a deep breath.", "冷静下来深呼吸。", "calm down first"),
  v("cheer-up", "/振作起来；开心起来", "/ˌtʃɪr ˈʌp/", "v.", 2, 0.15, "Cheer up — tomorrow is another day.", "振作点——明天又是新的一天。", "cheer someone up"),
  v("hang-up", "/挂断电话", "/ˌhæŋ ˈʌp/", "v.", 2, 0.2, "Don't hang up — wait one second.", "别挂——等一秒。", "hang up the phone"),
  v("call-back", "/回电话", "/ˌkɔːl ˈbæk/", "v.", 1, 0.15, "Can he call back after lunch?", "他午饭后再打回来行吗？", "call back in an hour"),
  v("drop-off", "/送(人)；下降", "/drɑːp ˈɔːf/", "v.", 2, 0.2, "I'll drop you off at school.", "我送你到学校。", "a drop-off point"),
  v("run-out-of", "/用完；耗尽", "/rʊn aʊt/", "v.", 1, 0.15, "We ran out of milk again.", "牛奶又喝完了。", "run out of time"),
  v("look-after", "/照顾", "/lʊk ˈæftər/", "v.", 1, 0.15, "Who looks after your dog on trips?", "旅行时谁照看你的狗？", "look after grandma"),
  v("look-forward-to", "/期待", "/ˌlʊk ˈfɔːrwərd tu/", "v.", 1, 0.15, "I look forward to seeing you.", "期待见到你。", "look forward to the weekend"),
  v("get-along-with", "/相处融洽", "/ɡət əˈlɔːŋ/", "v.", 2, 0.2, "Do you get along with your roommate?", "你和室友处得好吗？", "get along with everyone"),
  v("get-rid-of", "/摆脱；处理掉", "/ɡet rɪd/", "v.", 2, 0.2, "Get rid of old magazines.", "把旧杂志处理掉。", "get rid of junk"),
  v("pay-back", "/偿还；报复", "/peɪ ˈbæk/", "v.", 2, 0.2, "I'll pay you back on Friday.", "我周五还你钱。", "pay back the loan"),
  v("pay-attention-to", "/注意；专心", "/əˈtenʃn/", "v.", 1, 0.1, "Pay attention to the signs.", "注意看标识。", "pay close attention"),
  v("try-on", "/试穿", "/traɪ ˈɑːn/", "v.", 1, 0.1, "Try on both colors.", "两个颜色都试试。", "try it on first"),
  v("write-down", "/写下；记下", "/raɪt ˈdaʊn/", "v.", 1, 0.1, "Write down her number.", "把她的号码记下来。", "write it down quickly"),
  v("cross-out", "/划掉", "/krɔːs aʊt/", "v.", 3, 0.2, "Cross out the wrong answer.", "划掉错误答案。", "cross out mistakes"),
  v("hand-in", "/上交", "/hænd ˈɪn/", "v.", 2, 0.2, "Hand in your homework by Friday.", "周五前交作业。", "hand in the report"),
  v("hand-out", "/分发", "/hænd ˈaʊt/", "v.", 2, 0.2, "Volunteers handed out water.", "志愿者分发了水。", "hand out flyers"),
  v("put-away", "/收好；放好", "/pʊt əˈweɪ/", "v.", 2, 0.15, "Put away your toys after playing.", "玩完把玩具收好。", "put away the dishes"),
  v("take-out", "/取出；外卖带走", "/teɪk ˈaʊt/", "v.", 1, 0.1, "Take out the trash before eight.", "八点前把垃圾拿出去。", "take the trash out"),
  v("throw-away", "/扔掉", "/θroʊ əˈweɪ/", "v.", 1, 0.15, "Don't throw away that box yet.", "先别扔那个盒子。", "throw away old shoes"),
  v("show-up", "/露面；出现", "/ʃoʊ ʌp/", "v.", 2, 0.2, "He showed up twenty minutes late.", "他迟到二十分钟才出现。", "show up on time"),
  v("end-up-doing", "/最终成为/落到", "/end ʌp/", "v.", 2, 0.25, "We ended up staying till midnight.", "我们最后待到了午夜。", "end up somewhere unexpected"),
  v("eat-out", "/下馆子；出去吃", "/iːt aʊt/", "v.", 1, 0.1, "Let's eat out this Friday.", "这周五出去吃吧。", "eat out twice a month"),
  v("dress-up", "/盛装打扮", "/ˌdres ˈʌp/", "v.", 2, 0.15, "Kids dressed up as pirates.", "孩子们打扮成了海盗。", "dress up for Halloween"),
  v("warm-up", "/热身", "/wɔːrm ʌp/", "v./n.", 2, 0.15, "Warm up before running.", "跑步前要热身。", "a five-minute warm-up"),
  v("cool-down", "/冷却；平静下来", "/kuːl daʊn/", "v./n.", 2, 0.15, "Cool down with slow walking.", "慢走放松降温。", "a cool-down stretch"),
  v("figure-out", "/想明白；弄清楚", "/ˈfɪɡjər aʊt/", "v.", 1, 0.15, "I can't figure out this map.", "我看不懂这张地图。", "figure out the problem"),
  v("point-out", "/指出", "/pɔɪnt aʊt/", "v.", 2, 0.2, "She pointed out two spelling errors.", "她指出了两处拼写错误。", "point out a mistake"),
];
