import { v } from "@/content/vocab/builder";
import type { VocabRow } from "@/content/vocab/types";

/** Describing people & appearance. */
export const describingPeopleRows: VocabRow[] = [
  v("appearance", "/外貌；外观", "/əˈpɪrəns/", "n.", 3, 0.3, "Never judge by appearance.", "不要以貌取人。", "judge by appearance"),
  v("slim", "/苗条的；变瘦", "/slɪm/", "adj./v.", 2, 0.2, "She got slim by walking daily.", "她每天走路变苗条了。", "a slim figure"),
  v("muscular", "/肌肉发达的", "/ˈmʌskjələr/", "adj.", 5, 0.4, "Swimmers have muscular shoulders.", "游泳运动员肩部肌肉发达。", "a muscular build"),
  v("freckles", "/雀斑", "/ˈfreklz/", "n.", 6, 0.45, "Sun freckles appear on her nose.", "她的鼻子上晒出了雀斑。", "covered in freckles"),
  v("dimples", "/酒窝", "/ˈdɪmplz/", "n.", 6, 0.4, "He smiles with two deep dimples.", "他笑起来有两个深深的酒窝。", "cute dimples"),
  v("ponytail", "/马尾辫", "/ˈpoʊniteɪl/", "n.", 5, 0.35, "Tie your hair in a ponytail for gym.", "上体育课把头发扎成马尾。", "wear a ponytail"),
  v("braid", "/辫子", "/breɪd/", "n./v.", 6, 0.5, "Grandma braided the girl's hair.", "奶奶给女孩编了辫子。", "two braids"),
  v("outfit", "/一套衣服", "/ˈaʊtfɪt/", "n.", 3, 0.25, "Nice outfit! Is it new?", "这身衣服真好看！是新买的吗？", "pick an outfit"),
  v("uniform", "/制服", "/ˈjuːnɪfɔːrm/", "n.", 1, 0.15, "Nurses wear blue uniforms here.", "这里的护士穿蓝色制服。", "wear a school uniform"),
  v("hoodie", "/连帽衫", "/ˈhʊdi/", "n.", 3, 0.2, "He wears a gray hoodie every day.", "他每天都穿灰色连帽衫。", "an oversized hoodie"),
  v("sandals", "/凉鞋", "/ˈsændlz/", "n.", 2, 0.15, "Sandals are perfect for the beach.", "凉鞋最适合沙滩。", "leather sandals"),
  v("sneakers", "/运动鞋", "/ˈsniːkərz/", "n.", 1, 0.1, "New sneakers squeak on the floor.", "新运动鞋在地板上吱吱响。", "white sneakers"),
  v("high-heels", "/高跟鞋", "/ˌhaɪ ˈhiːlz/", "n.", 4, 0.25, "High-heels hurt after an hour.", "高跟鞋穿一小时脚就疼。", "a pair of high-heels"),
  v("jewelry", "/珠宝首饰", "/ˈdʒuːəlri/", "n.", 4, 0.3, "Real jewelry costs a lot.", "真正的首饰很贵。", "fine jewelry"),
  v("bracelet", "/手链", "/ˈbreɪslət/", "n.", 3, 0.25, "She made friendship bracelets.", "她编了友谊手链。", "a beaded bracelet"),
  v("earring", "/耳环", "/ˈɪrrɪŋ/", "n.", 3, 0.25, "One earring is missing!", "一只耳环不见了！", "gold earrings"),
  v("tattoo", "/纹身", "/tæˈtuː/", "n./v.", 4, 0.3, "His tattoo shows a small wave.", "他的纹身是一道小浪花。", "get a tattoo"),
  v("glasses", "/眼镜", "/ˈɡlæsɪz/", "n.", 1, 0.05, "I can't read without glasses.", "不戴眼镜我没法看书。", "wear reading glasses"),
  v("contacts", "/隐形眼镜", "/ˈkɑːntækts/", "n.", 4, 0.3, "Contacts dry out my eyes.", "隐形眼镜让眼睛发干。", "switch to contacts"),
  v("expression", "/表情；表达", "/ɪkˈspreʃn/", "n.", 2, 0.2, "Her expression turned serious.", "她的表情变得严肃。", "a worried expression"),
  v("frown", "/皱眉", "/fraʊn/", "v./n.", 5, 0.35, "Why are you frowning at the bill?", "你为什么对着账单皱眉？", "frown with confusion"),
  v("posture", "/姿势；体态", "/ˈpɑːstʃər/", "n.", 6, 0.5, "Good posture protects your back.", "好体态保护腰背。", "improve your posture"),
  v("gesture", "/手势；姿态", "/ˈdʒestʃər/", "n./v.", 4, 0.35, "A thumbs-up gesture means ok.", "竖大拇指的手势表示可以。", "make a friendly gesture"),
  v("body-language", "/肢体语言", "/ˈbɑːdi ˌlæŋɡwɪdʒ/", "n.", 4, 0.35, "Body-language often speaks louder than words.", "肢体语言常比言语更有力。", "read body-language"),
  v("first-impression", "/第一印象", "/fɜːrst ɪmˈpreʃn/", "n.", 3, 0.3, "You get one chance for a first-impression.", "第一印象只有一次机会。", "make a good first-impression"),
  v("age", "/年龄；时代", "/eɪdʒ/", "n./v.", 1, 0.1, "Guess my age — most people guess wrong.", "猜猜我的年龄——大多数人猜错。", "look young for your age"),
  v("height", "/身高；高度", "/haɪt/", "n.", 2, 0.15, "What's the height requirement for the ride?", "这个游乐设施有身高要求吗？", "average height"),
  v("weight", "/体重；重量", "/weɪt/", "n.", 2, 0.15, "Watch the weight limit on the bridge.", "注意桥上的限重。", "gain weight over holidays"),
  v("gender", "/性别", "/ˈdʒendər/", "n.", 4, 0.35, "The form asks for name and gender.", "表格要求填写姓名和性别。", "gender equality"),
  v("generation", "/一代人；世代", "/ˌdʒenəˈreɪʃn/", "n.", 3, 0.3, "My generation grew up online.", "我这代人是上网长大的。", "the younger generation"),
  v("tan", "/晒黑的皮肤", "/tæn/", "n./v.", 4, 0.3, "Beach trips give Dad a tan.", "去海边让爸爸晒黑了。", "get a summer tan"),
  v("hairstyle", "/发型", "/ˈherstaɪl/", "n.", 3, 0.2, "Try a shorter hairstyle this summer.", "今夏试试更短的发型。", "change your hairstyle"),
  v("makeup", "/化妆；化妆品", "/ˈmeɪkʌp/", "n.", 2, 0.2, "Light makeup looks natural.", "淡妆显得自然。", "put on makeup"),
  v("elderly", "/年长的", "/ˈeldərli/", "adj.", 3, 0.25, "Offer your seat to elderly riders.", "给年长的乘客让座。", "care for the elderly"),
  v("middle-aged", "/中年的", "/ˌmɪdl ˈeɪdʒd/", "adj.", 5, 0.35, "A middle-aged man asked for directions.", "一位中年男子问了路。", "a middle-aged couple"),
  v("perfume", "/香水", "/pərˈfjuːm/", "n.", 4, 0.25, "Her perfume smells like flowers.", "她的香水闻起来像花香。", "a light perfume"),
];
