import { v } from "@/content/vocab/builder";
import type { VocabRow } from "@/content/vocab/types";

/** Emotions & inner states (nouns) - deep feeling words. */
export const emotionsStates3Rows: VocabRow[] = [
  v("delight", "/高兴；乐趣", "/dɪˈlaɪt/", "n./v.", 4, 0.35, "The kids screamed with delight.", "孩子们高兴得大叫。", "to your delight"),
  v("sorrow", "/悲伤", "/ˈsɑːroʊ/", "n.", 6, 0.5, "His eyes showed quiet sorrow.", "他眼中流露出淡淡的哀伤。", "deep sorrow"),
  v("grief", "/悲痛", "/ɡriːf/", "n.", 6, 0.55, "Grief takes time to soften.", "悲痛需要时间慢慢抚平。", "in deep grief"),
  v("relief", "/宽慰；缓解", "/rɪˈliːf/", "n.", 2, 0.25, "What a relief — the test was easy.", "太轻松了——考试很简单。", "breathe a sigh of relief"),
  v("satisfaction", "/满足；满意", "/ˌsætɪsˈfækʃn/", "n.", 3, 0.3, "Fixing it myself gave me satisfaction.", "自己修好很有成就感。", "job satisfaction"),
  v("disappointment", "/失望", "/ˌdɪsəˈpɔɪntmənt/", "n.", 2, 0.25, "The rainy weekend was a big disappointment.", "下雨的周末真让人失望。", "a huge disappointment"),
  v("frustration", "/沮丧；挫折", "/frʌˈstreɪʃn/", "n.", 3, 0.3, "He slammed the door in frustration.", "他懊恼地摔上了门。", "shout in frustration"),
  v("rage", "/狂怒", "/reɪdʒ/", "n.", 5, 0.45, "She left the room to hide her rage.", "她离开房间掩饰怒火。", "fly into a rage"),
  v("terror", "/恐怖；惊恐", "/ˈterər/", "n.", 4, 0.4, "The horror movie gave her nightmares.", "恐怖片让她做了噩梦。", "a look of terror"),
  v("panic", "/恐慌", "/ˈpænɪk/", "v./n.", 3, 0.3, "Don't panic — we have a map.", "别慌——我们有地图。", "panic buying"),
  v("horror", "/恐惧；惊悚", "/ˈhɔːrər/", "n.", 4, 0.35, "She loves horror movies.", "她爱看恐怖片。", "a horror film"),
  v("disgust", "/厌恶", "/dɪsˈɡʌst/", "n.", 5, 0.45, "Moldy bread disgusts him.", "发霉的面包让他恶心。", "a look of disgust"),
  v("envy", "/羡慕；嫉妒", "/ˈenvi/", "n./v.", 4, 0.4, "I feel no envy for celebrities.", "我一点也不羡慕名人。", "green with envy"),
  v("jealousy", "/妒忌", "/ˈdʒeləsi/", "n.", 4, 0.4, "Jealousy can ruin friendships.", "妒忌会毁掉友谊。", "fight jealousy"),
  v("guilt", "/内疚", "/ɡɪlt/", "n.", 3, 0.3, "Guilt kept him awake that night.", "那晚内疚让他睡不着。", "feel a pang of guilt"),
  v("embarrassment", "/尴尬", "/ɪmˈbærəsmənt/", "n.", 4, 0.35, "To my embarrassment, I forgot her name.", "尴尬的是，我忘了她的名字。", "hide your embarrassment"),
  v("loneliness", "/孤独感", "/ˈloʊnlinəs/", "n.", 4, 0.35, "Big cities can bring loneliness.", "大城市也会带来孤独。", "battle loneliness"),
  v("boredom", "/无聊", "/ˈbɔːrdəm/", "n.", 3, 0.25, "Long flights mean boredom for kids.", "长途飞行让孩子觉得无聊。", "relieve boredom with music"),
  v("excitement", "/兴奋", "/ɪkˈsaɪtmənt/", "n.", 1, 0.15, "The puppy wiggled with excitement.", "小狗兴奋地扭来扭去。", "full of excitement"),
  v("despair", "/绝望", "/dɪˈsper/", "n.", 6, 0.55, "One kind word eased her despair.", "一句暖心话减轻了她的绝望。", "drive someone to despair"),
  v("optimism", "/乐观(主义)", "/ˈɑːptɪmɪzəm/", "n.", 5, 0.5, "Her optimism lifts the whole team.", "她的乐观鼓舞了整个团队。", "a sense of optimism"),
  v("pessimism", "/悲观(主义)", "/ˈpesɪmɪzəm/", "n.", 7, 0.6, "Constant pessimism wears people out.", "持续的悲观让人疲惫。", "guard against pessimism"),
  v("insecurity", "/不安全感", "/ˌɪnsɪˈkjʊrəti/", "n.", 5, 0.5, "New jobs often bring insecurity.", "新工作常带来不安感。", "deep insecurities"),
  v("determination", "/决心；毅力", "/dɪˌtɜːrmɪˈneɪʃn/", "n.", 4, 0.4, "Determination beats talent sometimes.", "毅力有时胜过天赋。", "sheer determination"),
  v("cruelty", "/残忍", "/ˈkruːəlti/", "n.", 5, 0.45, "Cruelty to animals is a crime.", "虐待动物是犯罪。", "an act of cruelty"),
  v("affection", "/喜爱；慈爱", "/əˈfekʃn/", "n.", 4, 0.4, "Grandma shows affection through food.", "奶奶用食物表达关爱。", "show deep affection"),
  v("passion", "/激情；热爱", "/ˈpæʃn/", "n.", 2, 0.25, "Teaching is his true passion.", "教学是他真正的热爱。", "a passion for music"),
  v("enthusiasm", "/热情", "/ɪnˈθuːziæzəm/", "n.", 3, 0.3, "Her enthusiasm is contagious.", "她的热情很有感染力。", "bursting with enthusiasm"),
  v("curiosity", "/好奇心", "/ˌkjʊriˈɑːsəti/", "n.", 3, 0.3, "Curiosity drives good science.", "好奇心推动好的科学。", "out of curiosity"),
  v("unease", "/不安", "/ʌnˈiːz/", "n.", 7, 0.6, "A strange silence created unease.", "奇怪的安静让人不安。", "a feeling of unease"),
  v("dread", "/畏惧；担忧", "/dred/", "n./v.", 6, 0.55, "Sunday nights fill him with dread.", "周日晚上总让他心生畏惧。", "dread doing something"),
  v("awe", "/敬畏", "/ɔː/", "n.", 6, 0.5, "We stared at the canyon in awe.", "我们敬畏地凝视着峡谷。", "stand in awe of nature"),
  v("homesickness", "/想家", "/ˈhoʊmsɪknəs/", "n.", 5, 0.4, "Homesickness hits hardest at festivals.", "过节时最想家。", "cure homesickness with calls home"),
  v("fatigue", "/疲劳", "/fəˈtiːɡ/", "n.", 6, 0.5, "Driver fatigue causes many crashes.", "驾驶疲劳导致许多事故。", "chronic fatigue"),
  v("hunger", "/饥饿", "/ˈhʌŋɡər/", "n.", 1, 0.15, "Hunger makes everything smell better.", "饿的时候什么都更香。", "a hunger for knowledge"),
  v("thirst", "/口渴", "/θɜːrst/", "n.", 1, 0.15, "Cold water satisfies thirst fast.", "凉水最能解渴。", "quench your thirst"),
  v("comfort", "/舒适；安慰", "/ˈkʌmfərt/", "n./v.", 1, 0.15, "Hot soup brings comfort on cold days.", "冷天喝热汤很舒服。", "comfort food"),
  v("amusement", "/娱乐；消遣", "/əˈmjuːzmənt/", "n.", 6, 0.5, "She watched the puppies with amusement.", "她饶有兴致地看着小狗们。", "to your amusement"),
];
