import { v } from "@/content/vocab/builder";
import type { VocabRow } from "@/content/vocab/types";

/** Thinking, reasoning & learning nouns - supports discussion topics. */
export const thinkingLearningRows: VocabRow[] = [
  v("imagination", "/想象力", "/ɪˌmædʒɪˈneɪʃn/", "n.", 3, 0.3, "A good story feeds the imagination.", "好故事滋养想象力。", "use your imagination"),
  v("intelligence", "/智力；才智", "/ɪnˈtelɪdʒəns/", "n.", 3, 0.3, "Emotional intelligence matters at work.", "情商在工作中很重要。", "artificial intelligence research"),
  v("intelligent", "/聪明的；智能的", "/ɪnˈtelɪdʒənt/", "adj.", 2, 0.25, "Dolphins are highly intelligent animals.", "海豚是非常聪明的动物。", "an intelligent answer"),
  v("wisdom", "/智慧", "/ˈwɪzdəm/", "n.", 4, 0.35, "Grandma shares wisdom without lecturing.", "奶奶分享智慧从不说教。", "words of wisdom"),
  v("logic", "/逻辑", "/ˈlɑːdʒɪk/", "n.", 5, 0.45, "Chess teaches logic and patience.", "国际象棋教人逻辑与耐心。", "follow the logic"),
  v("logical", "/合乎逻辑的", "/ˈlɑːdʒɪkl/", "adj.", 3, 0.35, "There's a logical explanation for everything.", "万事都有合理的解释。", "a logical choice"),
  v("reasonable", "/合理的；公道的", "/ˈriːznəbl/", "adj.", 2, 0.25, "Ten dollars is a reasonable price.", "十美元价格合理。", "a reasonable request"),
  v("nonsense", "/胡说八道", "/ˈnɑːnsens/", "n.", 3, 0.3, "Stop talking nonsense and focus.", "别胡说了，专心点。", "pure nonsense"),
  v("common-sense", "/常识", "/ˌkɑːmən ˈsens/", "n.", 3, 0.3, "Common-sense beats fancy tools sometimes.", "有时常识胜过花哨的工具。", "use common sense"),
  v("judgment", "/判断；判断力", "/ˈdʒʌdʒmənt/", "n.", 3, 0.3, "Trust your own judgment.", "相信你自己的判断。", "pass judgment on others"),
  v("option", "/选项；选择", "/ˈɑːpʃn/", "n.", 1, 0.15, "We have three options left.", "我们还剩三个选择。", "keep your options open"),
  v("mystery", "/谜；神秘事物", "/ˈmɪstəri/", "n.", 3, 0.3, "The missing sock remains a mystery.", "失踪的袜子仍是个谜。", "solve a mystery"),
  v("clue", "/线索；提示", "/kluː/", "n.", 3, 0.3, "One clue cracked the whole case.", "一条线索破了整个案子。", "a vital clue"),
  v("hint", "/暗示；提示", "/hɪnt/", "n./v.", 2, 0.2, "Give me a hint — I'm stuck.", "给个提示——我卡住了。", "take a hint"),
  v("suggestion", "/建议", "/səˈdʒestʃən/", "n.", 1, 0.15, "Thanks for the suggestion!", "谢谢你的建议！", "make a helpful suggestion"),
  v("strategy", "/策略", "/ˈstrætədʒi/", "n.", 3, 0.3, "Our strategy is simple: practice daily.", "我们的策略很简单：每天练。", "a long-term strategy"),
  v("effect", "/效果；影响", "/ɪˈfekt/", "n.", 1, 0.15, "The medicine takes effect quickly.", "这药见效很快。", "side effects of medicine"),
  v("consequence", "/后果", "/ˈkɑːnsɪkwens/", "n.", 4, 0.4, "Every choice has consequences.", "每个选择都有后果。", "face the consequences"),
  v("conclusion", "/结论；结尾", "/kənˈkluːʒn/", "n.", 2, 0.25, "What conclusion did you draw?", "你得出了什么结论？", "jump to conclusions"),
  v("proof", "/证据；证明", "/pruːf/", "n.", 3, 0.3, "Photos are proof we visited.", "照片是我们去过的证据。", "demand solid proof"),
  v("argument", "/论点；争吵", "/ˈɑːrɡjumənt/", "n.", 2, 0.25, "Her argument convinced the judges.", "她的论证说服了评委。", "win an argument fairly"),
  v("analysis", "/分析", "/əˈnæləsɪs/", "n.", 4, 0.4, "Careful analysis found the error.", "仔细分析找到了错误。", "a detailed analysis"),
  v("contrast", "/对比；反差", "/ˈkɑːntræst/", "n./v.", 4, 0.4, "In contrast, winter feels quiet.", "相比之下，冬天很安静。", "by contrast"),
  v("similarity", "/相似之处", "/ˌsɪməˈlærəti/", "n.", 4, 0.4, "The two languages share many similarities.", "两种语言有很多相似之处。", "spot the similarity"),
  v("category", "/类别", "/ˈkætəɡɔːri/", "n.", 3, 0.35, "Sort the words by category.", "按类别整理单词。", "fall into a category"),
  v("exception", "/例外", "/ɪkˈsepʃn/", "n.", 3, 0.35, "Every rule has an exception.", "每条规则都有例外。", "without exception"),
  v("priority", "/优先事项", "/praɪˈɔːrəti/", "n.", 3, 0.3, "Sleep is my top priority this month.", "睡眠是我这个月的头等大事。", "set clear priorities"),
  v("assumption", "/假设", "/əˈsʌmpʃn/", "n.", 5, 0.45, "Your assumption may be wrong.", "你的假设可能是错的。", "challenge an assumption"),
  v("prediction", "/预测", "/prɪˈdɪkʃn/", "n.", 3, 0.35, "His prediction came true.", "他的预测成真了。", "make a bold prediction"),
  v("impression", "/印象", "/ɪmˈpreʃn/", "n.", 2, 0.2, "First impressions matter in interviews.", "面试中第一印象很重要。", "get the wrong impression"),
  v("concentration", "/专注力", "/ˌkɑːnsnˈtreɪʃn/", "n.", 3, 0.3, "Noise kills concentration.", "噪音毁掉专注力。", "deep concentration"),
  v("creativity", "/创造力", "/ˌkriːeɪˈtɪvəti/", "n.", 3, 0.3, "Art class boosts creativity.", "美术课提升创造力。", "spark creativity"),
  v("genius", "/天才；天才创意", "/ˈdʒiːniəs/", "n./adj.", 4, 0.35, "That shortcut is pure genius!", "那个捷径真是天才想法！", "a marketing genius"),
];
