import { v } from "@/content/vocab/builder";
import type { VocabRow } from "@/content/vocab/types";

/** Body, movement & physical reactions - verbs of motion and body gaps. */
export const bodyMovement2Rows: VocabRow[] = [
  v("grip", "/紧握；握力", "/ɡrɪp/", "v./n.", 4, 0.3, "Grip the bar firmly before lifting.", "举之前握紧杠铃。", "a firm grip"),
  v("pinch", "/捏；一撮", "/pɪntʃ/", "v./n.", 5, 0.35, "Pinch the dough to seal it.", "捏住面团边缘封口。", "a pinch of salt"),
  v("slap", "/拍；掌击", "/slæp/", "v./n.", 4, 0.3, "He slapped the table laughing.", "他笑得直拍桌子。", "slap someone on the back"),
  v("rub", "/摩擦；揉", "/rʌb/", "v.", 2, 0.15, "Rub your hands to warm them up.", "搓搓手暖和一下。", "rub sore shoulders"),
  v("stroke", "/轻抚；抚摸", "/stroʊk/", "v./n.", 5, 0.35, "She stroked the cat's back gently.", "她轻轻抚摸猫背。", "stroke your chin thoughtfully"),
  v("blink", "/眨眼", "/blɪŋk/", "v./n.", 3, 0.25, "We blink thousands of times a day.", "我们每天眨眼几千次。", "blink twice quickly"),
  v("wink", "/眨眼示意", "/wɪŋk/", "v./n.", 5, 0.35, "Dad winked to show he was joking.", "爸爸眨眼表示在开玩笑。", "give me a wink"),
  v("glance", "/瞥一眼", "/ɡlæns/", "v./n.", 4, 0.35, "She glanced at her watch nervously.", "她紧张地看了眼手表。", "glance at the menu"),
  v("peek", "/偷看；窥视", "/piːk/", "v./n.", 5, 0.35, "Take a peek at the gifts under the tree.", "偷偷看一眼树下的礼物。", "sneak a peek"),
  v("sigh", "/叹气", "/saɪ/", "v./n.", 3, 0.25, "He sighed with relief and sat down.", "他松了口气坐下。", "heave a deep sigh"),
  v("gasp", "/倒吸一口气；喘气", "/ɡæsp/", "v./n.", 4, 0.35, "The audience gasped in surprise.", "观众惊得倒吸一口气。", "gasp for air"),
  v("tremble", "/颤抖", "/ˈtrembl/", "v.", 5, 0.4, "Her hands trembled with cold.", "她的手冻得发抖。", "tremble with fear"),
  v("shiver", "/哆嗦；发抖", "/ˈʃɪvər/", "v./n.", 4, 0.35, "A cold wind made us shiver.", "冷风吹得我们直哆嗦。", "shiver in the wind"),
  v("sweat", "/汗水；出汗", "/swet/", "n./v.", 2, 0.2, "Sweat dripped down his forehead.", "汗珠从他额头滚落。", "break into a sweat"),
  v("blush", "/脸红", "/blʌʃ/", "v./n.", 5, 0.4, "She blushed at the compliment.", "听到赞美她脸红了。", "blush bright red"),
  v("swell-up", "/肿胀；膨胀", "/swel/", "v.", 5, 0.45, "His ankle swelled after the fall.", "摔倒后他的脚踝肿了。", "swell up overnight"),
  v("stumble", "/绊倒；偶然发现", "/ˈstʌmbl/", "v.", 5, 0.45, "I stumbled on a hidden trail.", "我无意中发现了一条小路。", "stumble across an old letter"),
  v("tiptoe", "/踮脚走", "/ˈtɪptoʊ/", "v./n.", 6, 0.45, "Tiptoe past the sleeping baby.", "踮脚走过熟睡的宝宝。", "walk on tiptoe"),
  v("kneel", "/跪下", "/niːl/", "v.", 5, 0.4, "Kneel down to tie the shoe.", "跪下来系鞋带。", "kneel in the grass"),
  v("stroll", "/散步；闲逛", "/stroʊl/", "v./n.", 4, 0.3, "They strolled through the night market.", "他们漫步穿过夜市。", "an evening stroll"),
  v("leap", "/跳跃；跃过", "/liːp/", "v./n.", 4, 0.35, "The goat leaped over the fence.", "山羊跃过了栅栏。", "a giant leap forward"),
  v("hop", "/单脚跳；跳上", "/hɑːp/", "v.", 3, 0.25, "Hop on the bus at the corner.", "在街角跳上公交。", "hop on one foot"),
  v("slide", "/滑动；滑入", "/slaɪd/", "v./n.", 2, 0.2, "Slide the tray into the oven.", "把烤盘滑进烤箱。", "slide down the hill"),
  v("fall", "/落下；跌倒", "/fɔːl/", "v./n.", 1, 0.1, "Leaves fall down in October.", "十月树叶纷纷落下。", "fall asleep fast"),
  v("rise", "/上升；起身", "/raɪz/", "v./n.", 1, 0.2, "Bread dough rises in a warm spot.", "面团在温暖处发酵膨胀。", "the sun rises early here"),
  v("descend", "/下降；下坡", "/dɪˈsend/", "v.", 6, 0.55, "We descended from the ridge before dark.", "天黑前我们从山脊下来。", "descend the stairs slowly"),
  v("grin", "/咧嘴笑", "/ɡrɪn/", "v./n.", 4, 0.3, "He grinned at his own joke.", "他被自己的笑话逗得咧嘴笑。", "a wide grin"),
  v("giggle", "/咯咯笑", "/ˈɡɪɡl/", "v./n.", 4, 0.3, "The girls giggled at the puppy's tricks.", "女孩们被小狗的把戏逗得咯咯笑。", "burst into giggles"),
  v("snore", "/打鼾", "/snɔːr/", "v./n.", 5, 0.35, "Grandpa snores loudly on the couch.", "爷爷在沙发上鼾声如雷。", "stop snoring naturally"),
  v("hiccup", "/打嗝", "/ˈhɪkʌp/", "n./v.", 6, 0.45, "A hiccup interrupted her speech.", "一个嗝打断了她的演讲。", "get the hiccups"),
  v("tug", "/用力拉", "/tʌɡ/", "v./n.", 6, 0.45, "Tug the rope twice to signal.", "拉两下绳子作为信号。", "give it a gentle tug"),
  v("clutch", "/紧抓", "/klʌtʃ/", "v./n.", 7, 0.55, "She clutched the railing tightly.", "她紧紧抓住栏杆。", "clutch a bag tightly"),
  v("spit", "/吐出", "/spɪt/", "v./n.", 4, 0.3, "Spit out the toothpaste — don't swallow.", "吐掉牙膏——别吞下去。", "spit out water"),
  v("lick", "/舔", "/lɪk/", "v.", 2, 0.15, "The dog licked the plate clean.", "狗把盘子舔得干干净净。", "lick ice cream off a spoon"),
];
