import { v } from "@/content/vocab/builder";
import type { VocabRow } from "@/content/vocab/types";

/** Law, society & civics - supports news and discussion topics. */
export const lawSociety2Rows: VocabRow[] = [
  v("legal", "/合法的；法律的", "/ˈliːɡl/", "adj.", 3, 0.35, "Get legal advice before signing anything.", "签字前先咨询法律意见。", "legal advice"),
  v("illegal", "/非法的", "/ɪˈliːɡl/", "adj.", 3, 0.3, "Parking here is illegal.", "在这里停车是违法的。", "an illegal download"),
  v("justice", "/正义；司法", "/ˈdʒʌstɪs/", "n.", 4, 0.4, "They waited years for justice.", "他们为讨回公道等了多年。", "a justice system"),
  v("freedom", "/自由", "/ˈfriːdəm/", "n.", 1, 0.2, "Freedom of speech protects opinions.", "言论自由保护观点表达。", "the freedom to choose"),
  v("equality", "/平等", "/ɪˈkwɑːləti/", "n.", 3, 0.3, "The law promises equal treatment for everyone.", "法律承诺人人平等待遇。", "fight for equality"),
  v("fairness", "/公平", "/ˈfernəs/", "n.", 4, 0.35, "Players questioned the fairness of the call.", "球员质疑判罚是否公正。", "basic fairness"),
  v("discrimination", "/歧视", "/dɪˌskrɪmɪˈneɪʃn/", "n.", 5, 0.5, "Discrimination at work is against the law.", "职场歧视是违法的。", "fight discrimination"),
  v("racism", "/种族主义；种族歧视", "/ˈreɪsɪzəm/", "n.", 4, 0.4, "Racism has no place in sports.", "体育界不容种族主义。", "confront racism openly"),
  v("sexism", "/性别歧视", "/ˈseksɪzəm/", "n.", 6, 0.55, "Sexism still exists in some workplaces.", "某些职场仍存在性别歧视。", "call out sexism"),
  v("unemployment", "/失业", "/ˌʌnɪmˈplɔɪmənt/", "n.", 4, 0.4, "Unemployment fell this quarter.", "本季度失业率下降。", "the unemployment rate"),
  v("economy", "/经济", "/ɪˈkɑːnəmi/", "n.", 2, 0.3, "Tourism drives the local economy.", "旅游业拉动当地经济。", "the global economy"),
  v("economic", "/经济的；经济学的", "/ˌiːkəˈnɑːmɪk/", "adj.", 3, 0.35, "Economic growth slowed last year.", "去年经济增长放缓。", "an economic crisis"),
  v("inflation", "/通货膨胀", "/ɪnˈfleɪʃn/", "n.", 6, 0.55, "Inflation raised food prices everywhere.", "通胀推高了各地的食品价格。", "control inflation"),
  v("recession", "/经济衰退", "/rɪˈseʃn/", "n.", 7, 0.65, "The recession hit small shops hard.", "衰退重创了小店。", "survive a recession"),
  v("immigrant", "/移民", "/ˈɪmɪɡrənt/", "n./adj.", 4, 0.4, "Her grandparents were immigrants from Italy.", "她的祖父母是意大利移民。", "support immigrant families"),
  v("refugee", "/难民", "/ˌrefjuˈdʒiː/", "n.", 6, 0.55, "Volunteers welcomed the refugee families.", "志愿者迎接了难民家庭。", "help refugees settle"),
  v("union", "/工会；联盟", "/ˈjuːniən/", "n.", 5, 0.45, "The union negotiated better schedules.", "工会谈成了更好的排班。", "join a union"),
  v("welfare", "/福利；福祉", "/ˈwelfer/", "n.", 6, 0.55, "Animal welfare laws keep getting stricter.", "动物福利法越来越严格。", "welfare programs"),
  v("constitution", "/宪法", "/ˌkɑːnstɪˈtuːʃn/", "n.", 7, 0.65, "The constitution lists our basic rights.", "宪法列明了基本权利。", "study the constitution"),
  v("congress", "/国会；代表大会", "/ˈkɑːŋɡrəs/", "n.", 6, 0.55, "Congress debates the budget each fall.", "国会每年秋天讨论预算。", "a bill in congress"),
  v("campaign", "/运动；竞选活动", "/kæmˈpeɪn/", "n./v.", 4, 0.4, "The city launched a recycling campaign.", "市里发起了回收运动。", "run an ad campaign"),
  v("politician", "/政治家；政客", "/ˌpɑːləˈtɪʃn/", "n.", 4, 0.4, "Voters trust few politicians now.", "如今选民信任的政客很少。", "a local politician"),
  v("corruption", "/腐败", "/kəˈrʌpʃn/", "n.", 6, 0.6, "Investigators exposed corruption at the agency.", "调查人员揭露了该机构的腐败。", "fight corruption"),
  v("penalty", "/处罚；罚金", "/ˈpenəlti/", "n.", 3, 0.35, "Late returns carry a small penalty.", "逾期归还有小额罚款。", "face a heavy penalty"),
  v("punishment", "/惩罚", "/ˈpʌnɪʃmənt/", "n.", 3, 0.35, "The punishment must fit the offense.", "惩罚应与过错相称。", "escape punishment"),
  v("jail", "/看守所；监狱", "/dʒeɪl/", "n./v.", 4, 0.4, "He spent a night in jail for street racing.", "他因街头飙车蹲了一夜监狱。", "release someone from jail"),
  v("lawsuit", "/诉讼", "/ˈlɔːsuːt/", "n.", 6, 0.6, "The company faced a lawsuit over safety.", "公司因安全问题被起诉。", "settle a lawsuit"),
  v("sue", "/起诉", "/suː/", "v.", 6, 0.6, "They sued the builder over delays.", "他们因工期延误起诉了建筑商。", "sue for damages"),
  v("contract", "/合同", "/ˈkɑːntrækt/", "n.", 2, 0.25, "Read the contract before you sign.", "签字前读一遍合同。", "sign a two-year contract"),
  v("signature", "/签名", "/ˈsɪɡnətʃər/", "n.", 2, 0.25, "Your signature goes on the last page.", "你的签名签在最后一页。", "collect signatures"),
  v("regulation", "/规章；条例", "/ˌreɡjuˈleɪʃn/", "n.", 5, 0.5, "New regulations limit scooter speeds downtown.", "新规限制了市区滑板车速度。", "follow safety regulations"),
  v("ban", "/禁令；禁止", "/bæn/", "n./v.", 2, 0.25, "The city banned smoking in parks.", "该市禁止在公园吸烟。", "lift the ban"),
  v("permit", "/许可证", "/ˈpɜːrmɪt/", "n./v.", 4, 0.4, "You need a permit to fish here.", "在这里钓鱼需要许可证。", "apply for a work permit"),
  v("ballot", "/选票；投票", "/ˈbælət/", "n.", 7, 0.6, "Fill out your ballot carefully.", "认真填写选票。", "cast a ballot early"),
  v("democracy", "/民主", "/dɪˈmɑːkrəsi/", "n.", 5, 0.5, "Democracy needs informed voters.", "民主需要知情的选民。", "defend democracy"),
];
