import { v } from "@/content/vocab/builder";
import type { VocabRow } from "@/content/vocab/types";

/** Verbal communication - speaking, tone & language chunks. */
export const communicationVerbal2Rows: VocabRow[] = [
  v("dialogue", "/对话", "/ˈdaɪəlɔːɡ/", "n.", 3, 0.25, "The movie's dialogue feels natural.", "这部电影的对白很自然。", "practice a dialogue"),
  v("murmur", "/低声说；咕哝", "/ˈmɜːrmər/", "v./n.", 6, 0.5, "He murmured an apology and left.", "他小声道歉后就走了。", "a murmur of agreement"),
  v("mumble", "/咕哝；含糊地说", "/ˈmʌmbl/", "v./n.", 6, 0.5, "Don't mumble — speak clearly.", "别含糊不清——大声清楚地说。", "mumble an answer"),
  v("stutter", "/结巴；口吃", "/ˈstʌtər/", "v./n.", 7, 0.6, "He stuttered but finished the sentence.", "他结巴了一下但把句子说完了。", "speak without stuttering"),
  v("convey", "/传达；表达", "/kənˈveɪ/", "v.", 6, 0.55, "A simple chart conveys the idea faster.", "简单的图表更快传达想法。", "convey your meaning clearly"),
  v("imply", "/暗示；意味着", "/ɪmˈplaɪ/", "v.", 6, 0.55, "Silence can imply agreement.", "沉默可能表示默许。", "what does that imply?"),
  v("insult", "/侮辱；冒犯", "/ɪnˈsʌlt/", "v./n.", 4, 0.4, "Jokes that insult people aren't funny.", "侮辱人的笑话不好笑。", "an insult disguised as a joke"),
  v("tease", "/取笑；揶揄", "/tiːz/", "v.", 3, 0.3, "Siblings tease each other all the time.", "兄弟姐妹之间总互相打趣。", "tease someone about their accent"),
  v("praise", "/表扬；赞美", "/preɪz/", "v./n.", 3, 0.25, "Teachers praise effort, not just results.", "老师表扬努力，而不只看结果。", "deserve high praise"),
  v("scold", "/责骂", "/skoʊld/", "v.", 6, 0.5, "Dad scolded me for tracking mud inside.", "爸爸因为我把泥带进屋骂了我。", "scold gently"),
  v("nag", "/唠叨；不断催促", "/næɡ/", "v.", 5, 0.45, "Stop nagging me about the dishes.", "别再为洗碗唠叨我了。", "quit nagging"),
  v("brag", "/吹牛；自夸", "/bræɡ/", "v.", 5, 0.45, "He brags about his cooking constantly.", "他不停地吹嘘自己的厨艺。", "bragging rights"),
  v("reassure", "/使安心；打消疑虑", "/ˌriːəˈʃʊr/", "v.", 5, 0.5, "The nurse reassured me before the injection.", "护士在打针前安抚了我。", "reassure a nervous customer"),
  v("discourage", "/使泄气；劝阻", "/dɪsˈkɜːrɪdʒ/", "v.", 4, 0.4, "Harsh feedback discourages beginners.", "苛刻的反馈让初学者泄气。", "feel discouraged after one loss"),
  v("motivate", "/激励；激发动力", "/ˈmoʊtɪveɪt/", "v.", 3, 0.3, "Deadlines motivate some people.", "截止日期对有些人有激励作用。", "stay motivated daily"),
  v("threaten", "/威胁", "/ˈθretn/", "v.", 3, 0.3, "Dark clouds threatened rain all afternoon.", "乌云一下午都像要下雨。", "threaten legal action"),
  v("beg", "/恳求", "/beɡ/", "v.", 3, 0.3, "The puppy begged for scraps at dinner.", "小狗吃饭时讨要剩菜。", "beg for one more chance"),
  v("request", "/请求；要求", "/rɪˈkwest/", "n./v.", 2, 0.25, "Please submit requests before Friday.", "请周五前提交申请。", "a polite request"),
  v("address", "/称呼；向…讲话；处理", "/əˈdres/", "v./n.", 3, 0.3, "Address her as Doctor Lee.", "称她为李博士。", "address the whole team"),
  v("text", "/发短信；短信", "/tekst/", "v./n.", 1, 0.1, "Text me when you land.", "落地给我发消息。", "send a quick text"),
  v("texting", "/发短信(行为)", "/ˈtekstɪŋ/", "n.", 2, 0.15, "Texting during meetings looks rude.", "开会时发信息显得无礼。", "constant texting"),
  v("voicemail", "/语音留言", "/ˈvɔɪsmeɪl/", "n.", 4, 0.3, "My voicemail box is full again.", "我的语音信箱又满了。", "leave a short voicemail"),
  v("hold-on", "/稍等；坚持住", "/hoʊld ɑːn/", "phr.", 1, 0.1, "Hold on — I'll check for you.", "稍等——我帮你查查。", "hold on one second"),
  v("heart-to-heart", "/交心的谈话", "/ˌhɑːrt tu ˈhɑːrt/", "n.", 5, 0.4, "We had a heart-to-heart last night.", "我们昨晚敞开心扉聊了聊。", "a real heart-to-heart"),
  v("pep-talk", "/鼓舞士气的讲话", "/ˈpep tɔːk/", "n.", 6, 0.5, "Coach gave us a pep talk at halftime.", "教练中场给我们打了气。", "give someone a pep talk"),
  v("advice", "/建议；忠告", "/ædˈvaɪs/", "n.", 1, 0.15, "Take my advice: start early.", "听我的建议：早点开始。", "ask for advice"),
  v("advise", "/劝告；建议", "/ədˈvaɪz/", "v.", 4, 0.35, "Doctors advise rest and fluids.", "医生建议休息多喝水。", "strongly advise against it"),
  v("warning", "/警告；预告", "/ˈwɔːrnɪŋ/", "n.", 1, 0.15, "Read the warning label first.", "先读警告标签。", "a fair warning"),
  v("permission", "/许可；批准", "/pərˈmɪʃn/", "n.", 2, 0.25, "You need permission to film here.", "在这里拍摄需要许可。", "ask permission first"),
  v("allow", "/允许", "/əˈlaʊ/", "v.", 1, 0.1, "This building doesn't allow pets.", "这栋楼不允许养宠物。", "allow enough time"),
  v("tone", "/语气；音调", "/toʊn/", "n.", 2, 0.2, "Watch your tone with customers.", "对顾客注意语气。", "a friendly tone of voice"),
  v("idiom", "/习语；成语", "/ˈɪdiəm/", "n.", 5, 0.45, "\"Break a leg\" is a theater idiom.", "\"Break a leg\" 是戏剧界习语。", "learn common idioms"),
  v("proverb", "/谚语；格言", "/ˈprɑːvɜːrb/", "n.", 6, 0.5, "An old proverb says practice makes perfect.", "一句老话说熟能生巧。", "as the proverb goes"),
];
