import { v } from "@/content/vocab/builder";
import type { VocabRow } from "@/content/vocab/types";

/** Jobs & careers - supports workplace topics (Day 31+). */
export const jobsCareer3Rows: VocabRow[] = [
  v("accountant", "/会计师", "/əˈkaʊntənt/", "n.", 4, 0.35, "Our accountant files taxes every spring.", "我们的会计师每年春天报税。", "a certified accountant"),
  v("architect", "/建筑师", "/ˈɑːrkɪtekt/", "n.", 5, 0.4, "The architect sketched the new library.", "建筑师画了新图书馆的草图。", "hire an architect"),
  v("vet", "/兽医", "/vet/", "n./v.", 4, 0.3, "The vet calmed our nervous cat.", "兽医安抚了我们紧张的猫。", "take the puppy to the vet"),
  v("nurse", "/护士", "/nɜːrs/", "n./v.", 1, 0.15, "The nurse checked my blood pressure twice.", "护士量了两次我的血压。", "a night-shift nurse"),
  v("driver", "/司机；驾驶员", "/ˈdraɪvər/", "n.", 1, 0.1, "Every driver must wear a seat belt.", "每位司机都要系安全带。", "a delivery driver"),
  v("conductor", "/(乐队)指挥；(火车)列车员", "/kənˈdʌktər/", "n.", 6, 0.5, "The conductor checked our tickets politely.", "列车员礼貌地查票。", "an orchestra conductor"),
  v("flight-attendant", "/空乘人员", "/ˈflaɪt əˌtendənt/", "n.", 5, 0.35, "The flight attendant demonstrated the seatbelt.", "空乘演示了安全带系法。", "a friendly flight attendant"),
  v("receptionist", "/前台接待员", "/rɪˈsepʃənɪst/", "n.", 4, 0.3, "The receptionist booked me in quickly.", "接待员很快帮我登记了。", "the hotel receptionist"),
  v("secretary", "/秘书", "/ˈsekrəteri/", "n.", 3, 0.25, "His secretary screens all calls first.", "他的秘书先过滤所有来电。", "an executive secretary"),
  v("clerk", "/职员；店员", "/klɜːrk/", "n.", 3, 0.3, "The clerk counted the change twice.", "店员数了两遍找零。", "a bank clerk"),
  v("marketing", "/市场营销", "/ˈmɑːrkɪtɪŋ/", "n.", 3, 0.3, "Marketing drives traffic to the site.", "营销为网站带来流量。", "a marketing campaign"),
  v("author", "/作者", "/ˈɔːθər/", "n./v.", 2, 0.2, "The author signed my copy.", "作者在我的书上签了名。", "a bestselling author"),
  v("poet", "/诗人", "/ˈpoʊət/", "n.", 5, 0.4, "The poet read three short verses.", "诗人朗读了三节短诗。", "a local poet"),
  v("novelist", "/小说家", "/ˈnɑːvəlɪst/", "n.", 6, 0.5, "The novelist writes one page a day.", "这位小说家每天写一页。", "a famous novelist"),
  v("librarian", "/图书管理员", "/laɪˈbreriən/", "n.", 4, 0.3, "The librarian recommended five novels.", "图书管理员推荐了五本小说。", "ask the librarian for help"),
  v("lifeguard", "/救生员", "/ˈlaɪfɡɑːrd/", "n.", 5, 0.35, "The lifeguard whistled at the deep end.", "救生员在深水区吹哨提醒。", "work as a lifeguard"),
  v("guard", "/警卫；看守", "/ɡɑːrd/", "n./v.", 2, 0.2, "A guard patrols the parking lot at night.", "保安夜间在停车场巡逻。", "a museum guard"),
  v("sailor", "/水手；海员", "/ˈseɪlər/", "n.", 5, 0.35, "Old sailors read clouds like maps.", "老水手能像看地图一样读懂云。", "a retired sailor"),
  v("fisherman", "/渔夫", "/ˈfɪʃərmən/", "n.", 4, 0.3, "The fisherman mends his nets at dawn.", "渔夫黎明时补网。", "a local fisherman"),
  v("miner", "/矿工", "/ˈmaɪnər/", "n.", 7, 0.55, "Coal miners wear helmets with lamps.", "煤矿工人戴带灯的安全帽。", "a coal miner"),
  v("butcher", "/屠夫；肉贩", "/ˈbʊtʃər/", "n./v.", 5, 0.4, "The butcher tied the roast with twine.", "屠夫用细绳捆好烤肉。", "visit the butcher"),
  v("barista", "/咖啡师", "/bəˈriːstə/", "n.", 5, 0.35, "Our barista remembers everyone's order.", "我们的咖啡师记得每个人的点单。", "chat with the barista"),
  v("bartender", "/酒保；调酒师", "/ˈbɑːrtendər/", "n.", 5, 0.35, "The bartender shook the cocktail well.", "调酒师把鸡尾酒摇匀。", "tip your bartender"),
  v("janitor", "/大楼管理员；清洁工", "/ˈdʒænɪtər/", "n.", 6, 0.5, "The janitor unlocked the gym early.", "管理员一早就开了体育馆的门。", "the school janitor"),
  v("gardener", "/园丁；花匠", "/ˈɡɑːrdnər/", "n.", 5, 0.35, "The gardener trims the hedge every Friday.", "园丁每周五修剪树篱。", "a part-time gardener"),
  v("technician", "/技术员；技师", "/tekˈnɪʃn/", "n.", 4, 0.35, "A technician fixed the projector in ten minutes.", "技师十分钟修好了投影仪。", "call an IT technician"),
  v("analyst", "/分析师", "/ˈænəlɪst/", "n.", 5, 0.45, "The analyst predicted slower growth.", "分析师预测增长放缓。", "a data analyst"),
  v("consultant", "/顾问", "/kənˈsʌltənt/", "n.", 5, 0.45, "We hired a consultant for the rebranding.", "我们为品牌重塑请了顾问。", "a management consultant"),
  v("entrepreneur", "/创业者", "/ˌɑːntrəprəˈnɜːr/", "n.", 6, 0.55, "The entrepreneur opened her third shop this year.", "这位创业者开了第三家店。", "a serial entrepreneur"),
  v("freelancer", "/自由职业者", "/ˈfriːlænsər/", "n.", 5, 0.4, "Freelancers juggle several clients at once.", "自由职业者同时应付多个客户。", "hire a freelancer online"),
  v("director", "/董事；导演；主管", "/dəˈrektər/", "n.", 3, 0.3, "The director approved the final cut.", "导演批准了最终剪辑版。", "a board director"),
  v("ceo", "/首席执行官", "/ˌsiː iː ˈoʊ/", "n.", 4, 0.35, "The CEO joined the all-hands meeting.", "首席执行官参加了全员大会。", "meet the CEO"),
  v("owner", "/物主；所有人", "/ˈoʊnər/", "n.", 1, 0.15, "The owner greets every customer herself.", "店主亲自迎接每位顾客。", "the proud owner of a bakery"),
  v("attorney", "/律师(美)", "/əˈtɜːrni/", "n.", 5, 0.45, "Her attorney reviewed the lease carefully.", "她的律师仔细审阅了租约。", "consult an attorney"),
];
