import { v } from "@/content/vocab/builder";
import type { VocabRow } from "@/content/vocab/types";

/** Body parts & health actions - fills surprising gaps in the body map. */
export const healthBody3Rows: VocabRow[] = [
  v("neck", "/脖子", "/nek/", "n.", 1, 0.1, "My neck aches after computer work.", "用电脑久了脖子疼。", "a stiff neck"),
  v("lips", "/嘴唇", "/lɪps/", "n.", 1, 0.05, "Her lips turned blue in the cold.", "天冷时她的嘴唇冻得发紫。", "lick your dry lips"),
  v("eyebrow", "/眉毛", "/ˈaɪbraʊ/", "n.", 3, 0.2, "One eyebrow went up in surprise.", "一只眉毛惊讶地扬起。", "raise an eyebrow at that idea"),
  v("jaw", "/下巴；颌", "/dʒɔː/", "n.", 4, 0.3, "His jaw dropped when he saw the bill.", "看到账单他惊得下巴都掉了。", "your jaw drops"),
  v("fist", "/拳头", "/fɪst/", "n.", 2, 0.15, "He clenched his fist before the interview.", "面试前他握紧了拳头。", "clench your fist tightly"),
  v("palm", "/手掌", "/pɑːm/", "n.", 5, 0.35, "She held the coin in her palm.", "她把硬币握在掌心。", "read someone's palm for fun"),
  v("rib", "/肋骨", "/rɪb/", "n.", 5, 0.4, "A rib protects the lungsRibs protect the lungs.", "肋骨保护肺部。", "crack a rib skiing"),
  v("spine", "/脊柱；脊梁", "/spaɪn/", "n.", 6, 0.5, "Sit with a straight spine when typingKeep your spine straight when typing.", "打字时保持脊背挺直。", "the spine of a book"),
  v("kidney", "/肾脏", "/ˈkɪdni/", "n.", 6, 0.55, "Kidneys filter waste from the blood.", "肾脏过滤血液中的废物。", "healthy kidneys"),
  v("liver", "/肝脏", "/ˈlɪvər/", "n.", 6, 0.55, "Alcohol damages the liver over time.", "长期饮酒损害肝脏。", "liver damage risks"),
  v("vein", "/静脉；纹理", "/veɪn/", "n.", 7, 0.6, "Blue veins show under pale skin.", "青色的静脉在苍白皮肤下显现。", "visible veins"),
  v("skull", "/头骨", "/skʌl/", "n.", 6, 0.55, "The helmet protects the skull in fallsThe helmet protects your skull.", "头盔保护你的头骨。", "protect your skull"),
  v("calf", "/小腿；牛犊", "/kæf/", "n.", 6, 0.5, "Calf stretches help after runningStretch your calves after running.", "跑步后拉伸小腿。", "pull a calf muscle"),
  v("sole", "/脚底；唯一的", "/soʊl/", "adj./n.", 6, 0.5, "The soles of my feet acheThe soles of my feet ache.", "我的脚底酸痛。", "the sole survivor of the crash"),
  v("scar", "/伤疤", "/skɑːr/", "n.", 5, 0.4, "A small scar marks his eyebrowA small scar marks his eyebrow.", "他的眉骨上有道小疤。", "a scar from surgery"),
  v("nerve", "/神经", "/nɜːrv/", "n.", 4, 0.4, "Steady hands calm the nervesDeep breaths steady the nerves.", "深呼吸让神经平静下来。", "lose your nerve at the last second"),
  v("joint", "/关节；接合处", "/dʒɔɪnt/", "n./adj.", 4, 0.4, "Knees are joints that bend both waysKnees are joints that only bend one way.", "膝盖是只能朝一个方向弯的关节。", "a joint bank account"),
  v("skeleton", "/骨架；骨骼", "/ˈskelɪtn/", "n.", 6, 0.5, "The museum has a model skeletonThe museum has a model skeleton.", "博物馆有一个骨骼模型。", "the bare skeleton of an essay outline"),
  v("balance", "/平衡；余额", "/ˈbæləns/", "n./v.", 2, 0.25, "Yoga improves balance and focusYoga improves balance and focus.", "瑜伽改善平衡与专注。", "check your bank balance weekly"),
  v("diagnose", "/诊断(疾病/问题)", "/ˌdaɪəɡˈnoʊs/", "v.", 7, 0.65, "Doctors diagnosed the rash quicklyDoctors quickly diagnosed the rash.", "医生很快诊断出皮疹的原因。", "correctly diagnose a problem"),
  v("examine", "/检查；细看", "/ɪɡˈzæmɪn/", "v.", 2, 0.25, "Customs officers examined the suitcase twiceCustoms examined the suitcase twice.", "海关把行李箱查了两遍。", "examine all options first"),
  v("operate", "/做手术；操作", "/ˈɑːpəreɪt/", "v.", 3, 0.3, "Surgeons operated for three hoursSurgeons operated for three hours.", "外科医生手术了三小时。", "operate heavy machinery safely"),
  v("heal", "/愈合；治愈", "/hiːl/", "v.", 2, 0.25, "Small cuts heal within days.", "小伤口几天就能愈合。", "time heals most wounds"),
  v("ache", "/隐隐作痛", "/eɪk/", "v./n.", 2, 0.2, "My legs ache after climbing stairsMy legs ache after the long climb.", "爬完山腿隐隐作痛。", "an ache in your heart"),
  v("toothache", "/牙疼", "/ˈtuːθeɪk/", "n.", 2, 0.2, "Cold drinks make my toothache worseCold drinks make my toothache worse.", "冷饮让我牙疼加重。", "a terrible toothache at night"),
  v("cramp", "/抽筋；痉挛", "/kræmp/", "n./v.", 5, 0.4, "Swimmers get leg cramps in cold water.", "游泳者在冷水里容易腿部抽筋。", "stomach cramps before exams"),
  v("rash", "/皮疹；一时冲动", "/ræʃ/", "n./adj.", 5, 0.45, "Heat often causes a skin rashHeat often causes a heat rash.", "暑热常引起痱子。", "a rash decision to quit"),
  v("itch", "/痒；发痒", "/ɪtʃ/", "v./n.", 3, 0.25, "Mosquito bites itch terribly at nightMosquito bites itch terribly.", "蚊子咬的包特别痒。", "scratch an itch gently"),
  v("blister", "/水泡；起泡", "/ˈblɪstər/", "n.", 5, 0.4, "New shoes gave him heel blistersNew shoes gave him blisters on his heels.", "新鞋磨得他脚后跟起泡。", "pop a blister? better: cover the blister"),
  v("bump", "/碰撞；肿块；偶遇", "/bʌmp/", "v./n.", 2, 0.2, "I bumped into my old teacher downtownI bumped into my old teacher downtown.", "我在市区偶遇了老师。", "a bump on the head"),
  v("nausea", "/恶心", "/ˈnɔːziə/", "n.", 7, 0.65, "Motion sickness brings waves of nauseaMotion sickness brings nausea.", "晕车带来阵阵恶心。", "nausea during pregnancy"),
  v("vomit", "/呕吐", "/ˈvɑːmɪt/", "v./n.", 6, 0.6, "The toddler vomited after too much candyThe child vomited after eating too much candy.", "孩子糖吃多了吐了。", "feel like vomiting"),
  v("diarrhea", "/腹泻", "/ˌdaɪəˈriːə/", "n.", 7, 0.7, "Traveler's diarrhea ruins tripsTraveler's diarrhea can ruin trips.", "旅行者腹泻会毁掉行程。", "treat mild diarrhea at home"),
  v("asthma", "/哮喘", "/ˈæzmə/", "n.", 6, 0.55, "Cold air triggers her asthmaCold air triggers her asthma.", "冷空气会诱发她的哮喘。", "an asthma inhaler"),
  v("diabetes", "/糖尿病", "/ˌdaɪəˈbiːtiːz/", "n.", 7, 0.65, "Diabetes rates rise with sugary dietsDiabetes rates rise with sugary diets.", "高糖饮食使糖尿病率上升。", "manage diabetes with diet"),
  v("cancer", "/癌；癌症", "/ˈkænsər/", "n.", 3, 0.35, "Early screening catches many cancersEarly screening catches many cancers early.", "早期筛查能发现许多癌症。", "skin cancer prevention"),
  v("tumor", "/肿瘤", "/ˈtuːmər/", "n.", 7, 0.7, "Scans found a small benign tumorScans found a small benign tumor.", "扫描发现一个良性小肿瘤。", "a benign tumor"),
  v("heart-attack", "/心脏病发作", "/hɑːrt əˈtæk/", "n.", 5, 0.45, "Know the signs of a heart attackLearn the warning signs of a heart attack.", "了解心脏病发作的征兆。", "survive a heart attack"),
  v("sprain-an-ankle", "/扭伤", "/spreɪn/", "v./n.", 6, 0.5, "She sprained her wrist at volleyballShe sprained her wrist playing volleyball.", "她打排球时扭伤了手腕。", "a mild ankle sprain"),
];
