import { v } from "@/content/vocab/builder";
import type { VocabRow } from "@/content/vocab/types";

/** Abstract nouns batch 3 - success, freedom & quality of life (B1-B2). */
export const abstractNouns3Rows: VocabRow[] = [
  v("success", "/成功", "/səkˈses/", "n.", 1, 0.15, "Success takes patience and luckSuccess takes patience.", "成功需要耐心。", "the key to success"),
  v("failure", "/失败", "/ˈfeɪljər/", "n.", 2, 0.2, "Treat failure as feedbackTreat failure as useful feedback.", "把失败当作有用的反馈。", "a fear of failure"),
  v("victory", "/胜利", "/ˈvɪktəri/", "n.", 2, 0.2, "The team celebrated its victory quietlyThe team celebrated its victory.", "球队庆祝了胜利。", "a narrow victory"),
  v("defeat", "/失败；击败", "/dɪˈfiːt/", "n./v.", 3, 0.3, "They accepted defeat with dignityThey accepted defeat gracefully.", "他们有风度地接受了失利。", "suffer a heavy defeat"),
  v("fame", "/名声", "/feɪm/", "n.", 3, 0.3, "Fame changed him littleFame changed him very little.", "名气几乎没改变他。", "rise to fame overnight"),
  v("opportunity", "/机会", "/ˌɑːpərˈtuːnəti/", "n.", 1, 0.15, "Every mistake hides an opportunityEvery problem hides an opportunity.", "每个问题都藏着机会。", "seize the opportunity"),
  v("possibility", "/可能性", "/ˌpɑːsəˈbɪləti/", "n.", 2, 0.25, "There's a real possibility of snow tonightThere's a real possibility of snow.", "今晚真的可能下雪。", "rule out the possibility"),
  v("probability", "/概率；可能性", "/ˌprɑːbəˈbɪləti/", "n.", 6, 0.55, "Rain probability stays high all weekThe probability of rain stays high.", "下雨的概率一直很高。", "in all probability"),
  v("reality", "/现实；实际", "/riˈæləti/", "n.", 2, 0.25, "The plan met reality quicklyThe plan collided with reality quickly.", "计划很快撞上现实。", "face harsh reality"),
  v("honesty", "/诚实", "/ˈɑːnəsti/", "n.", 3, 0.25, "Honesty saves time in the long run.", "诚实从长远看省时间。", "value honesty above all"),
  v("integrity", "/正直；完整", "/ɪnˈteɡrəti/", "n.", 7, 0.65, "She leads with integrity and calmShe leads with integrity.", "她以正直的方式领导。", "a person of integrity"),
  v("dignity", "/尊严", "/ˈdɪɡnəti/", "n.", 6, 0.55, "Treat every patient with dignity.", "尊重每位患者的尊严。", "stand with dignity"),
  v("modesty", "/谦逊", "/ˈmɑːdəsti/", "n.", 7, 0.65, "His modesty surprises new teammatesHis modesty surprises people.", "他的谦逊让人意外。", "with typical modesty"),
  v("threat", "/威胁", "/θret/", "n.", 3, 0.3, "Job loss is the biggest financial threatJob loss is their biggest financial threat.", "失业是他们最大的财务威胁。", "pose a serious threat"),
  v("suffering", "/苦难；痛苦", "/ˈsʌfərɪŋ/", "n.", 3, 0.3, "Medicine eases suffering at the end of lifeMedicine can ease suffering.", "药物可以减轻痛苦。", "relieve human suffering"),
  v("pleasure", "/愉快；乐事", "/ˈpleʒər/", "n.", 2, 0.2, "It's a pleasure to work with youIt's a pleasure working with you.", "和你共事很愉快。", "with great pleasure"),
  v("harm", "/伤害；损害", "/hɑːrm/", "n./v.", 2, 0.2, "Secondhand smoke causes real harmSecondhand smoke causes harm.", "二手烟确实有害。", "do more harm than good"),
  v("advantage", "/优势；好处", "/ædˈvæntɪdʒ/", "n.", 1, 0.15, "Height is an advantage in basketball.", "身高在篮球中是优势。", "take advantage of sales"),
  v("disadvantage", "/劣势；不利", "/ˌdɪsædˈvæntɪdʒ/", "n.", 3, 0.25, "The main disadvantage is the priceThe main disadvantage is the cost.", "主要缺点是价格。", "weigh the disadvantages first"),
  v("restriction", "/限制；约束", "/rɪˈstrɪkʃn/", "n.", 5, 0.45, "Speed restrictions apply near schools.", "学校附近限速。", "lift travel restrictions"),
  v("chaos", "/混乱；无序", "/ˈkeɪɑːs/", "n.", 5, 0.45, "Morning traffic descends into chaosMorning traffic often descends into chaos.", "早高峰常常一片混乱。", "total chaos after the storm"),
  v("conflict", "/冲突；矛盾", "/ˈkɑːnflɪkt/", "n./v.", 3, 0.35, "Schedule conflicts delayed the meetingSchedule conflicts delayed the meeting.", "日程冲突使会议延期。", "resolve conflicts peacefully"),
  v("harmony", "/和谐；融洽", "/ˈhɑːrməni/", "n.", 5, 0.5, "The choir sang in perfect harmonyThe choir sang in harmony.", "合唱团唱得十分和谐。", "live together in harmony"),
  v("tension", "/紧张；张力", "/ˈtenʃn/", "n.", 2, 0.25, "Neck tension builds during long callsNeck tension builds during long phone calls.", "长时间通话会让颈部紧绷。", "ease political tension"),
  v("aid", "/帮助；援助", "/eɪd/", "n./v.", 2, 0.2, "Neighbors offered aid after the stormNeighbors offered aid after the flood.", "洪水后邻居们伸出援手。", "come to someone's aid"),
  v("assistance", "/帮助；协助", "/əˈsɪstəns/", "n.", 3, 0.25, "Technical assistance is available by chatTechnical assistance is available online.", "可在线获取技术支持。", "ask for assistance politely"),
  v("goods", "/商品；货物", "/ɡʊdz/", "n.", 3, 0.3, "Sporting goods sell well before summerSporting goods sell well in early summer.", "体育用品在初夏畅销。", "deliver goods on time"),
  v("quantity", "/量；数量", "/ˈkwɑːntəti/", "n.", 4, 0.35, "Order in quantity for a discountBulk orders get a quantity discount.", "批量下单有折扣。", "a small quantity of salt"),
  v("amount", "/总额；数量(不可数)", "/əˈmaʊnt/", "n.", 1, 0.15, "Reduce the amount of sugar slowlyReduce the amount of sugar gradually.", "逐步减少糖的用量。", "a large amount of data"),
  v("size", "/大小；尺码", "/saɪz/", "n.", 1, 0.05, "What size do you wear?", "你穿多大码？", "one size fits all"),
  v("shape", "/形状；状态", "/ʃeɪp/", "n./v.", 1, 0.1, "Clouds shaped like animals drifted byAnimal-shaped clouds drifted by.", "动物形状的云飘过。", "get back into shape"),
  v("design", "/设计；图样", "/dɪˈzaɪn/", "n./v.", 1, 0.15, "Good design feels effortlessGood design feels effortless.", "好的设计浑然天成。", "by design, not accident"),
  v("variety", "/多样性；种类", "/vəˈraɪəti/", "n.", 2, 0.2, "A variety of food keeps meals funA variety of foods keeps meals interesting.", "食物多样让吃饭更有趣。", "a wide variety of options"),
  v("range", "/范围；山脉；射程", "/reɪndʒ/", "n.", 2, 0.2, "Prices range from five to twenty dollarsPrices range from $5 to $20.", "价格从五美元到二十美元不等。", "a wide price range"),
  v("selection", "/选择；精选品", "/sɪˈlekʃn/", "n.", 3, 0.3, "The cheese selection here is impressiveThe cheese selection is impressive.", "这里的奶酪选择很丰富。", "make your selection"),
  v("version", "/版本", "/ˈvɜːrʒn/", "n.", 2, 0.2, "The free version shows adsThe free version shows ads.", "免费版带广告。", "the latest version available"),
];
