import { v } from "@/content/vocab/builder";
import type { VocabRow } from "@/content/vocab/types";

/** Measurement & geography - practical numbers and places vocabulary. */
export const measurePlace2Rows: VocabRow[] = [
  v("site", "/地点；场所；网站", "/saɪt/", "n.", 2, 0.2, "Hard hats are required on siteHard hats are required on the construction site?", "在工地必须戴安全帽。", "an official website"),
  v("side", "/边；侧面；一方", "/saɪd/", "n./adj./v.", 1, 0.05, "Which side of the bed do you sleep on?", "你睡床的哪一边？", "from side to side"),
  v("boundary", "/边界；界限", "/ˈbaʊndri/", "n.", 5, 0.45, "The fence marks our property boundaryThe fence marks the property boundary.", "栅栏标出地产边界。", "push the boundaries of design"),
  v("interior", "/内部；内饰", "/ɪnˈtɪriər/", "n./adj.", 6, 0.55, "The car's interior feels premiumThe car's interior feels premium.", "这辆车的内饰很高级。", "ministry of the interior"),
  v("path", "/小路；路径", "/pæθ/", "n.", 1, 0.1, "Follow the stone path to the beach.", "沿着石径走到海滩。", "cross someone's path"),
  v("trail", "/小径；踪迹", "/treɪl/", "n./v.", 3, 0.25, "Deer left tracks on the trailDeer tracks crossed the trail.", "鹿的足迹横穿小道。", "trail running shoes"),
  v("freeway", "/(美)高速公路", "/ˈfriːweɪ/", "n.", 3, 0.25, "Take the freeway to avoid downtown lightsTake the freeway to skip downtown lights.", "走高速避开市区的红绿灯。", "the freeway exit"),
  v("mile", "/英里", "/maɪl/", "n.", 1, 0.1, "The next gas station is ten miles aheadThe next station is ten miles ahead.", "下一个加油站在前方十英里。", "miles per hour"),
  v("kilometer", "/公里；千米", "/ˈkɪləmiːtər/", "n.", 2, 0.15, "Run two more kilometers, then rest.", "再跑两公里就休息。", "square kilometers of forest"),
  v("inch", "/英寸", "/ɪntʃ/", "n.", 1, 0.1, "Give him an inch and he takes a mile.", "他得寸进尺。", "a 65-inch tv"),
  v("meter", "/米；计量表", "/ˈmiːtər/", "n.", 2, 0.15, "The pool is twenty-five meters longThe pool is 25 meters long.", "泳池长25米。", "a parking meter"),
  v("liter", "/升", "/ˈliːtər/", "n.", 2, 0.1, "Drink two liters of water dailyDrink two liters of water a day.", "每天喝两升水。", "a liter of milk"),
  v("gallon", "/加仑", "/ˈɡælən/", "n.", 4, 0.25, "Gas costs five dollars a gallon here.", "这里汽油五美元一加仑。", "miles per gallon rating"),
  v("pound", "/磅；英镑", "/paʊnd/", "n./v.", 1, 0.1, "Buy a pound of strawberries.", "买一磅草莓。", "lose ten pounds"),
  v("gram", "/克", "/ɡræm/", "n.", 3, 0.15, "This recipe measures flour in grams.", "这个菜谱用克称面粉。", "500 grams of chicken"),
  v("speed", "/速度", "/spiːd/", "n./v.", 1, 0.1, "The train reaches top speed outside town.", "火车在城外达到最高速。", "at full speed ahead"),
  v("width", "/宽度", "/wɪdθ/", "n.", 5, 0.4, "Measure the width of the doorway firstMeasure the doorway's width first.", "先量门洞宽度。", "arm-width apart"),
  v("length", "/长度；时长", "/leŋθ/", "n.", 2, 0.2, "What's the length of the flight?", "航程时长是多少？", "knee-length skirt"),
  v("northeast", "/东北(方)", "/ˌnɔːrθˈiːst/", "n./adj./adv.", 4, 0.35, "A northeast wind cooled the cityA northeast wind cooled the city.", "东北风给城市降温。", "travel northeast by train"),
  v("southwest", "/西南(方)", "/ˌsaʊθˈwest/", "n./adj./adv.", 4, 0.35, "The southwest corner gets afternoon sun.", "西南角晒得到午后的太阳。", "a southwest-facing balcony"),
  v("globe", "/地球仪；球体", "/ɡloʊb/", "n.", 3, 0.25, "Spin the globe and pick a country.", "转动地球仪随便选个国家。", "offices around the globe"),
  v("landscape", "/风景；景观", "/ˈlændskeɪp/", "n./v.", 4, 0.4, "The desert landscape glows at duskThe desert landscape glows at sunset.", "沙漠景观在日落时发光。", "paint landscapes outdoors"),
  v("scenery", "/景色；风景", "/ˈsiːnəri/", "n.", 3, 0.25, "Mountain scenery flew past the train window.", "山景从车窗外掠过。", "stop and enjoy the scenery"),
  v("countryside", "/乡下；农村", "/ˈkʌntrisaɪd/", "n.", 3, 0.25, "Weekends in the countryside recharge me.", "乡下的周末让我恢复精力。", "walks through the countryside"),
  v("rural", "/乡村的", "/ˈrʊrəl/", "adj.", 5, 0.45, "Rural clinics often lack specialists.", "乡村诊所常缺专科医生。", "rural broadband access"),
  v("urban", "/城市的", "/ˈɜːrbən/", "adj.", 4, 0.4, "Urban parks cool whole neighborhoods.", "城市公园能给街区降温。", "an urban apartment"),
  v("suburban", "/郊区的", "/səˈbɜːrbən/", "adj.", 6, 0.5, "Suburban streets stay quiet at noon.", "郊区街道中午很安静。", "a suburban backyard"),
  v("wilderness", "/荒野；荒原", "/ˈwɪldərnəs/", "n.", 6, 0.55, "Hikers got lost in the wilderness overnight.", "徒步者在荒野迷路一夜。", "a wilderness survival course"),
  v("meadow", "/草地；牧场", "/ˈmedoʊ/", "n.", 7, 0.6, "Wildflowers covered the meadow in JuneWildflowers covered the meadow in June.", "六月野花铺满草甸。", "picnic in a meadow"),
  v("canyon", "/峡谷", "/ˈkænjən/", "n.", 6, 0.5, "The canyon walls echoed every shout.", "峡谷岩壁回荡着每一声喊叫。", "raft through the canyon"),
  v("cliff", "/悬崖；峭壁", "/klɪf/", "n.", 5, 0.45, "Seabirds nest on the cliff edgeSeabirds nest on the cliff edges.", "海鸟在悬崖边缘筑巢。", "stand at the cliff edge carefully"),
  v("glacier", "/冰川", "/ˈɡleɪʃər/", "n.", 7, 0.65, "Glaciers shrink as summers warmGlaciers shrink as summers get warmer.", "夏天变热冰川缩小。", "a glacier hiking tour"),
  v("volcano", "/火山", "/vɑːlˈkeɪnoʊ/", "n.", 5, 0.5, "The volcano last erupted in 1944.", "这座火山上次喷发是1944年。", "an active volcano"),
];
