import { v } from "@/content/vocab/builder";
import type { VocabRow } from "@/content/vocab/types";

/** Core verb gap-fill batch A - shockingly common verbs missing from the base list. */
export const verbsCoreGapRows: VocabRow[] = [
  v("bring", "/带来；拿来", "/brɪŋ/", "v.", 1, 0.1, "Bring your umbrella — it looks rainy.", "带上伞——看着要下雨。", "bring snacks to the party"),
  v("build", "/建造；建立", "/bɪld/", "v.", 1, 0.15, "They built a treehouse last summer.", "去年夏天他们建了个树屋。", "build trust slowly"),
  v("enjoy", "/享受；喜爱", "/ɪnˈdʒɔɪ/", "v.", 1, 0.1, "I enjoy long walks after dinner.", "我喜欢晚饭后散步。", "enjoy every minute"),
  v("end", "/结束；终止", "/end/", "n./v.", 1, 0.1, "The concert ended with fireworks.", "音乐会在烟花中落幕。", "in the end"),
  v("develop", "/发展；开发；冲洗", "/dɪˈveləp/", "v.", 2, 0.25, "Apps develop fast with good feedback.", "有好的反馈应用就进步快。", "develop a new skill"),
  v("fail", "/失败；不及格", "/feɪl/", "v./n.", 1, 0.15, "Engines fail without oil changesEngines fail without regular oil changes.", "不换机油发动机会坏。", "without fail, every week"),
  v("fight", "/打架；斗争；对抗", "/faɪt/", "v./n.", 1, 0.15, "The brothers fight over the remote dailyThe brothers fight over the remote.", "兄弟俩天天为遥控器吵架。", "fight for what is right"),
  v("mean", "/意思是；意味着", "/miːn/", "v./adj.", 1, 0.15, "What does this sign mean?", "这个标志是什么意思？", "mean a lot to me"),
  v("solve", "/解决；解答", "/sɑːlv/", "v.", 2, 0.25, "We solved the mystery before dinnerWe solved the mystery by dinner.", "晚饭前我们解开了谜团。", "solve problems together"),
  v("collect", "/收集；接(人)", "/kəˈlekt/", "v.", 1, 0.1, "Collect tickets in a shoebox.", "把票根收在鞋盒里。", "collect data for research"),
  v("communicate", "/交流；沟通", "/kəˈmjuːnɪkeɪt/", "v.", 2, 0.2, "Good leaders communicate clearly.", "好的领导者沟通清晰。", "communicate across cultures"),
  v("challenge", "/挑战；质疑", "/ˈtʃælɪndʒ/", "n./v.", 2, 0.25, "Try a challenge: no phone after nine.", "试试挑战：九点后不碰手机。", "face a challenge bravely"),
  v("roll", "/滚动；卷起", "/roʊl/", "v./n.", 2, 0.15, "Roll the dough into a ball.", "把面团揉成球。", "rock and roll music"),
  v("split", "/分开；劈开", "/splɪt/", "v./n.", 2, 0.2, "Let's split the bill three ways.", "我们三人分摊账单吧。", "a split-second decision"),
  v("struggle", "/挣扎；奋斗", "/ˈstrʌɡl/", "v./n.", 2, 0.25, "Many learners struggle with spelling.", "很多学习者拼写吃力。", "the struggle is real"),
  v("influence", "/影响", "/ˈɪnfluəns/", "n./v.", 2, 0.25, "Teachers influence students for decades.", "老师对学生的影响持续几十年。", "a positive influence"),
  v("contact", "/联系；联络", "/ˈkɑːntækt/", "n./v.", 1, 0.1, "Contact me anytime by email.", "随时邮件联系我。", "keep in contact with old friends"),
  v("care", "/在意；关心；照料", "/ker/", "n./v.", 1, 0.1, "Careful drivers care about pedestriansGood drivers care about pedestrians.", "好司机会顾及行人。", "take care of yourself"),
  v("heat", "/热；加热；高温", "/hiːt/", "n./v.", 1, 0.1, "Heat the pan before adding eggsHeat the pan before adding the eggs.", "先热锅再打蛋。", "the heat of midsummer"),
  v("last", "/持续；维持", "/læst/", "v./adj.", 1, 0.1, "The meeting lasted two hours.", "会议开了两小时。", "at long last, home!"),
  v("lay", "/放；铺设；产卵", "/leɪ/", "v.", 3, 0.3, "Lay the baby down gently.", "轻轻放下宝宝。", "lay the cards on the table"),
  v("match", "/相配；比赛；火柴", "/mætʃ/", "n./v.", 1, 0.1, "Does this tie match the shirt?", "这条领带配衬衫吗？", "win the tennis match"),
  v("note", "/注意；记录；便条", "/noʊt/", "n./v.", 1, 0.1, "Note the exit number as you driveNote the exit number while driving.", "开车时留意出口编号。", "take notes during class"),
  v("pass", "/通过；传递；经过", "/pæs/", "v./n.", 1, 0.1, "Pass the salt, please.", "请把盐递给我。", "pass with flying colors"),
  v("record", "/录制；纪录", "/ˈrekərd/", "n./v.", 1, 0.15, "Record your voice to check pronunciation.", "录下自己的声音检查发音。", "break a world record"),
  v("reward", "/奖励；回报", "/rɪˈwɔːrd/", "n./v.", 3, 0.25, "Small rewards keep habits alive.", "小奖励让习惯保持活力。", "reap the rewards of practice"),
  v("spell", "/拼写；咒语；一段时间", "/spel/", "v./n.", 1, 0.1, "How do you spell your name?", "你的名字怎么拼？", "spell words correctly"),
  v("spill", "/溢出；洒出", "/spɪl/", "v./n.", 2, 0.15, "Oops — I spilled coffee on the reportI spilled coffee on the report.", "我把咖啡洒在报告上了。", "don't cry over spilled milk"),
  v("spin", "/旋转；纺纱；疾驰", "/spɪn/", "v./n.", 3, 0.2, "Wheels spin faster downhillWheels spin faster going downhill.", "下坡时车轮转得更快。", "take it for a spin"),
  v("state", "/陈述；州；状态", "/steɪt/", "v./n.", 1, 0.15, "State your name for the record.", "请报上姓名以便记录。", "a state of confusion"),
  v("trouble", "/麻烦；困难", "/ˈtrʌbl/", "n./v.", 1, 0.15, "No trouble at all — happy to help.", "一点也不麻烦——乐意帮忙。", "stay out of trouble"),
  v("tend", "/倾向于；照料", "/tend/", "v.", 3, 0.35, "I tend to skip breakfast on busy days.", "忙的日子我常常不吃早饭。", "tend to get nervous"),
  v("upgrade", "/升级；提升", "/ˌʌpˈɡreɪd/", "v./n.", 4, 0.35, "Upgrade the app to unlock featuresUpgrade the app to unlock extra features.", "升级应用解锁更多功能。", "a free seat upgrade"),
  v("unpack", "/打开包裹；取出", "/ˌʌnˈpæk/", "v.", 4, 0.3, "Unpack first, then explore the cityUnpack first, then explore the city.", "先拆行李再出去逛。", "unpack the boxes later"),
  v("dare", "/敢；挑战", "/der/", "v./n.", 5, 0.45, "I wouldn't dare ask for a raise todayI daren't ask for a raise today.", "今天我可不敢提加薪。", "how dare you!"),
  v("decorate", "/装饰；布置", "/ˈdekəreɪt/", "v.", 2, 0.25, "Decorate the room with paper starsDecorate the room with paper stars.", "用纸星星布置房间。", "decorate for the holidays"),
  v("decrease", "/减少；降低", "/dɪˈkriːs/", "v./n.", 3, 0.3, "Sales decreased slightly in winter.", "冬天销量略降。", "a sharp decrease in price"),
  v("disappoint", "/使失望", "/ˌdɪsəˈpɔɪnt/", "v.", 3, 0.3, "Canceling again will disappoint themCanceling again would disappoint them.", "再取消会让他们失望的。", "sorry to disappoint you"),
  v("elect", "/选举；选择", "/ɪˈlekt/", "v.", 4, 0.4, "Members elect officers each yearMembers elect new officers yearly.", "会员每年选出新干部。", "get elected to the council"),
  v("equal", "/相等的；等于", "/ˈiːkwəl/", "adj./v./n.", 2, 0.2, "All opinions are equal here? better: All voices are equal here.", "这里人人话语权平等。", "equal pay for equal work"),
  v("excuse", "/原谅；借口", "/ɪkˈskjuːs/", "n./v.", 1, 0.1, "There's no excuse for being rude.", "粗鲁没有任何借口。", "excuse my messy desk"),
  v("flash", "/闪光；闪现", "/flæʃ/", "n./v.", 3, 0.2, "Cameras flashed at the red carpetCameras flashed on the red carpet.", "红毯上相机闪光不断。", "in a flash, dinner was gone"),
  v("glow", "/发光；容光焕发", "/ɡloʊ/", "v./n.", 4, 0.25, "Embers glow long after the fire diesEmbers glow after the fire dies down.", "火灭后余烬仍发光。", "a healthy glow"),
];
