import { v } from "@/content/vocab/builder";
import type { VocabRow } from "@/content/vocab/types";

/** Core verb gap-fill batch B - completing the high-frequency verb core. */
export const verbsCoreGap2Rows: VocabRow[] = [
  v("participate", "/参加；参与", "/pɑːrˈtɪsɪpeɪt/", "v.", 3, 0.3, "Everyone participates in cleanup dayEveryone takes part in cleanup day.", "大家都参与大扫除日。", "actively participate in class"),
  v("preserve", "/保存；保护", "/prɪˈzɜːrv/", "v./n.", 5, 0.5, "Freezing preserves berries for monthsFreezing keeps berries good for months.", "冷冻能让浆果保存数月。", "preserve family recipes"),
  v("promote", "/促进；提拔；推销", "/prəˈmoʊt/", "v.", 3, 0.3, "Reading promotes empathyReading builds empathy.", "阅读培养同理心。", "get promoted to manager"),
  v("publish", "/出版；发表", "/ˈpʌblɪʃ/", "v.", 4, 0.35, "She publishes one article a month.", "她每月发表一篇文章。", "publish research findings"),
  v("qualify", "/使合格；取得资格", "/ˈkwɑːlɪfaɪ/", "v.", 4, 0.4, "Do you qualify for the student discount?", "你符合学生折扣条件吗？", "qualify for the finals"),
  v("react", "/反应；起化学反应", "/riˈækt/", "v.", 2, 0.25, "Dogs react to thunder instantly.", "狗对雷声立刻有反应。", "react calmly under pressure"),
  v("refer", "/提及；参考", "/rɪˈfɜːr/", "v.", 4, 0.4, "Refer to page twelve for detailsSee page twelve for details.", "详情见第十二页。", "refer a friend to the clinic"),
  v("relate", "/与…相关；使联系", "/rɪˈleɪt/", "v.", 3, 0.35, "Kids relate to brave charactersKids relate to brave characters.", "孩子会与勇敢的角色共情。", "related by marriage"),
  v("reserve", "/预订；保留", "/rɪˈzɜːrv/", "v./n.", 3, 0.3, "Reserve a table for six at sevenReserve a table for six at 7 pm.", "预订晚七点六人桌。", "reserve seats online"),
  v("settle", "/安顿；解决；定居", "/ˈsetl/", "v.", 3, 0.3, "The baby finally settled down to sleepThe baby finally settled down.", "宝宝终于安静下来睡着了。", "settle an argument fairly"),
  v("shelter", "/庇护；住所", "/ˈʃeltər/", "n./v.", 4, 0.35, "Caves shelter hikers from stormsCaves can shelter hikers during storms.", "山洞能为徒步者挡风雨。", "an animal shelter volunteer"),
  v("sketch", "/速写；概述", "/sketʃ/", "n./v.", 5, 0.4, "She sketched the harbor in ten minutesShe sketched the harbor quickly.", "她很快画了港口速写。", "a rough sketch of the plan"),
  v("strengthen", "/加强；增强", "/ˈstreŋθn/", "v.", 3, 0.35, "Swimming strengthens shoulders and backSwimming strengthens shoulders and back muscles.", "游泳强健肩背肌肉。", "strengthen ties between teams"),
  v("swap", "/交换", "/swɑːp/", "v./n.", 5, 0.4, "Swap seats with me for the view?", "和我换座位看风景好吗？", "swap phone numbers quickly"),
  v("bathe", "/洗澡；游泳(英)", "/beɪð/", "v.", 5, 0.4, "Bathe the dog before guests arrive? better: Wash the dog before guests arrive.", "客人到之前给狗洗个澡。", "bathe a newborn safely"),
  v("hesitate", "/犹豫", "/ˈhezɪteɪt/", "v.", 4, 0.35, "Don't hesitate to ask questionsDon't hesitate to ask questions.", "别犹豫，尽管提问。", "hesitate for only a second"),
  v("imitate", "/模仿", "/ˈɪmɪteɪt/", "v.", 4, 0.4, "Parrots imitate doorbells perfectly.", "鹦鹉学门铃声学得惟妙惟肖。", "imitate a native speaker's rhythm"),
  v("impact", "/影响；冲击", "/ˈɪmpækt/", "n./v.", 3, 0.3, "Sleep impacts memory stronglySleep strongly affects memory.", "睡眠对记忆力影响很大。", "make a big impact at work"),
  v("import", "/进口；输入", "/ɪmˈpɔːrt/", "v./n.", 5, 0.45, "They import olive oil from SpainThey import olive oil from Greece.", "他们从希腊进口橄榄油。", "import raw materials"),
  v("inform", "/通知；告知", "/ɪnˈfɔːrm/", "v.", 3, 0.3, "Please inform us of any delaysPlease inform us about delays.", "如有延误请告知我们。", "keep everyone well informed"),
  v("injure", "/伤害；使受伤", "/ˈɪndʒər/", "v.", 3, 0.3, "Lift properly so you don't injure your back.", "正确搬举以免伤腰。", "injure a shoulder"),
  v("instruct", "/指示；教授", "/ɪnˈstrʌkt/", "v.", 4, 0.4, "The coach instructs beginners every SaturdayShe instructs beginners on Saturdays.", "她每周六教初学者。", "follow instructions carefully"),
  v("govern", "/统治；管理", "/ˈɡʌvərn/", "v.", 6, 0.55, "Good rules govern fair playClear rules keep games fair.", "清晰的规则保证公平比赛。", "the governing board meets monthly"),
  v("guarantee", "/保证；担保", "/ˌɡærənˈtiː/", "n./v.", 4, 0.4, "We guarantee delivery within two daysWe guarantee two-day delivery.", "我们保证两日送达。", "no money-back guarantee offered"),
  v("list", "/列出；清单", "/lɪst/", "n./v.", 1, 0.1, "List three goals for this month.", "列出本月三个目标。", "top of the waiting list"),
  v("load", "/装载；负荷；加载", "/loʊd/", "n./v.", 2, 0.2, "Load the dishes after dinnerLoad the dishwasher after dinner.", "晚饭后把碗碟放进洗碗机。", "a heavy load of laundry"),
  v("obey", "/服从；遵守", "/oʊˈbeɪ/", "v.", 4, 0.35, "Everyone obeys the pool rulesEveryone must obey the pool rules.", "人人必须遵守泳池规则。", "obey traffic laws strictly"),
  v("obtain", "/获得；得到", "/əbˈteɪn/", "v.", 6, 0.55, "Obtain a permit before buildingGet a permit before you build.", "建房前先取得许可。", "obtain written consent first"),
  v("pray", "/祈祷", "/preɪ/", "v.", 5, 0.4, "Farmers prayed for rain all springFarmers prayed for rain all month.", "农民整月祈雨。", "pray for someone's recovery"),
  v("tighten", "/拧紧；收紧", "/ˈtaɪtn/", "v.", 3, 0.25, "Tighten the jar lid firmlyTighten the lid until it's snug.", "拧紧瓶盖直到贴合。", "tighten your budget this month"),
  v("tolerate", "/容忍；耐受", "/ˈtɑːləreɪt/", "v.", 5, 0.45, "I can't tolerate spicy food anymoreI can't tolerate very spicy food anymore.", "我受不了太辣的食物了。", "zero tolerance for bullying"),
  v("trace", "/追踪；描摹", "/treɪs/", "v./n.", 4, 0.35, "Trace the design onto new paperTrace the pattern onto fresh paper.", "把图案拓画到新纸上。", "trace your family tree"),
  v("urge", "/敦促；强烈愿望", "/ɜːrdʒ/", "v./n.", 5, 0.45, "Doctors urge daily walks for patientsDoctors urge patients to walk daily.", "医生督促病人每天散步。", "resist the urge to check messages"),
  v("zip", "/拉链；拉开速度", "/zɪp/", "n./v.", 1, 0.1, "Zip up your jacket — it's windyZip up your jacket; it's windy outside.", "把外套拉上——外面风大。", "zip through homework fast"),
  v("fade", "/褪色；逐渐消失", "/feɪd/", "v.", 4, 0.3, "Jeans fade after many washes.", "牛仔裤洗多了会褪色。", "memories slowly fade away"),
  v("command", "/命令；指挥；掌握", "/kəˈmænd/", "v./n.", 4, 0.4, "The general commands great respectThe general is greatly respected.", "这位将军深受敬重。", "command of the english language"),
  v("construct", "/建造；构筑", "/kənˈstrʌkt/", "v.", 6, 0.55, "Workers constructed the bridge in winterWorkers built the bridge last winter.", "工人去年冬天建了桥。", "construct a logical argument"),
  v("consume", "/消耗；消费", "/kənˈsuːm/", "v.", 5, 0.5, "Old fridges consume more powerOld fridges consume more electricity.", "旧冰箱更耗电。", "consume news in small doses"),
  v("define", "/下定义；明确", "/dɪˈfaɪn/", "v.", 4, 0.4, "Define success on your own terms.", "按自己的标准定义成功。", "clearly defined rules help"),
];
