import { v } from "@/content/vocab/builder";
import type { VocabRow } from "@/content/vocab/types";

export const homeObjectsRows: VocabRow[] = [
  v("house", "/房子", "/haʊs/", "n.", 1, 0.25, "Their house is small.", "他们的房子小。", "big house"),
  v("home", "/家", "/hoʊm/", "n./adv.", 1, 0.15, "I go home at six.", "我六点回家。", "go home"),
  v("room", "/房间；空间", "/ruːm/", "n.", 1, 0.2, "A clean room.", "干净的房间。", "living room"),
  v("door", "/门", "/dɔːr/", "n.", 1, 0.2, "Open the door.", "开门。", "front door"),
  v("window", "/窗户", "/ˈwɪndoʊ/", "n.", 1, 0.25, "Close the window.", "关窗。", "by the window"),
  v("table", "/桌子", "/ˈteɪbl/", "n.", 1, 0.2, "On the table.", "在桌上。", "kitchen table"),
  v("chair", "/椅子", "/tʃer/", "n.", 1, 0.2, "Sit on this chair.", "坐这把椅子。", "a soft chair"),
  v("bed", "/床", "/bed/", "n.", 1, 0.2, "The bed is big.", "床很大。", "go to bed"),
  v("sofa", "/沙发", "/ˈsoʊfə/", "n.", 3, 0.3, "Sleep on the sofa.", "睡在沙发上。", "on the sofa"),
  v("kitchen", "/厨房", "/ˈkɪtʃɪn/", "n.", 1, 0.3, "Mom is in the kitchen.", "妈妈在厨房。", "kitchen table"),
  v("bathroom", "/浴室；卫生间", "/ˈbæθruːm/", "n.", 1, 0.3, "Where is the bathroom?", "卫生间在哪？", "go to the bathroom"),
  v("key", "/钥匙", "/kiː/", "n.", 1, 0.25, "Where are my keys?", "我的钥匙呢？", "car keys"),
  v("bag", "/包；袋子", "/bæɡ/", "n.", 1, 0.2, "My bag is heavy.", "我的包很重。", "shopping bag"),
  v("phone", "/电话；手机", "/foʊn/", "n.", 1, 0.15, "My phone is dead.", "我手机没电了。", "answer the phone"),
  v("computer", "/电脑", "/kəmˈpjuːtər/", "n.", 1, 0.3, "Turn on the computer.", "打开电脑。", "use a computer"),
  v("television", "/电视", "/ˈtelɪvɪʒn/", "n.", 1, 0.35, "They watch television.", "他们看电视。", "watch television"),
  v("light", "/灯；轻的", "/laɪt/", "n./adj.", 1, 0.3, "Turn off the light.", "关灯。", "green light"),
  v("box", "/盒子", "/bɑːks/", "n.", 1, 0.2, "A small box.", "一个小盒子。", "a box of books"),
  v("cup", "/杯子", "/kʌp/", "n.", 1, 0.2, "A cup of tea.", "一杯茶。", "a cup of coffee"),
  v("plate", "/盘子", "/pleɪt/", "n.", 2, 0.25, "Wash the plates.", "洗盘子。", "a plate of"),
  v("knife", "/刀", "/naɪf/", "n.", 2, 0.35, "Use a sharp knife.", "用锋利的刀。", "knife and fork"),
  v("fork", "/叉子", "/fɔːrk/", "n.", 2, 0.3, "Fork on the left.", "叉子放左边。", "knife and fork"),
  v("spoon", "/勺子", "/spuːn/", "n.", 2, 0.3, "A two spoons of sugar", "两勺糖。", "a spoon of soup"),
  v("clock", "/时钟", "/klɑːk/", "n.", 2, 0.3, "Look at the clock.", "看钟。", "wall clock"),
  v("book", "/书", "/bʊk/", "n.", 1, 0.15, "This book is good.", "这本书不错。", "read a book"),
  v("pen", "/钢笔；笔", "/pen/", "n.", 1, 0.15, "Sign with this pen.", "用这支笔签名。", "pen and paper"),
  v("paper", "/纸；论文", "/ˈpeɪpər/", "n.", 1, 0.25, "A piece of paper.", "一张纸。", "on paper"),
  v("money", "/钱", "/ˈmʌni/", "n.", 1, 0.25, "Save your money.", "存好你的钱。", "spend money"),
  v("card", "/卡片；银行卡", "/kɑːrd/", "n.", 1, 0.25, "Pay by card.", "刷卡支付。", "credit card"),
  v("seat", "/座位", "/siːt/", "n.", 2, 0.3, "Take a seat, please.", "请坐。", "take a seat"),
];
