import { v } from "@/content/vocab/builder";
import type { VocabRow } from "@/content/vocab/types";

export const pronounsFunctionRows: VocabRow[] = [
  v("I", "/我", "/aɪ/", "pron.", 1, 0.05, "I am a student.", "我是学生。", "you and I"),
  v("me", "/我（宾格）", "/miː/", "pron.", 1, 0.1, "Call me tomorrow.", "明天给我打电话。", "tell me"),
  v("we", "/我们", "/wiː/", "pron.", 1, 0.15, "We are friends.", "我们是朋友。", "we two"),
  v("us", "/我们（宾格）", "/ʌs/", "pron.", 2, 0.2, "Come with us.", "跟我们一起来。", "join us"),
  v("they", "/他们；她们；它们", "/ðeɪ/", "pron.", 1, 0.15, "They are teachers.", "他们是老师。", "they say"),
  v("them", "/他们（宾格）", "/ðem/", "pron.", 1, 0.2, "I know them well.", "我很了解他们。", "one of them"),
  v("him", "/他（宾格）", "/hɪm/", "pron.", 1, 0.2, "Give him the book.", "把书给他。", "tell him"),
  v("it", "/它；这；那", "/ɪt/", "pron.", 1, 0.1, "It is big.", "它很大。", "it is"),
  v("his", "/他的", "/hɪz/", "det.", 2, 0.25, "This is his car.", "这是他的车。", "his name"),
  v("our", "/我们的", "/ˈaʊər/", "det.", 2, 0.3, "Our team won.", "我们队赢了。", "our home"),
  v("their", "/他们的", "/ðer/", "det.", 2, 0.3, "Their house is big.", "他们的房子很大。", "their family"),
  v("this", "/这；这个", "/ðɪs/", "pron./det.", 1, 0.15, "This is my dad.", "这是我爸爸。", "this way"),
  v("that", "/那；那个", "/ðæt/", "pron./det.", 1, 0.15, "That is OK.", "那没关系。", "like that"),
  v("these", "/这些", "/ðiːz/", "det.", 2, 0.3, "These are apples.", "这些是苹果。", "these days"),
  v("those", "/那些", "/ðoʊz/", "det.", 2, 0.35, "Those are my books.", "那些是我的书。", "those people"),
  v("who", "/谁", "/huː/", "pron.", 1, 0.25, "Who is she?", "她是谁？", "who knows"),
  v("what", "/什么", "/wɑːt/", "pron.", 1, 0.15, "What is this?", "这是什么？", "what time"),
  v("when", "/什么时候", "/wen/", "adv.", 1, 0.25, "When do we start?", "我们什么时候开始？", "when ready"),
  v("where", "/在哪里", "/wer/", "adv.", 1, 0.25, "Where do you live?", "你住哪里？", "where to"),
  v("why", "/为什么", "/waɪ/", "adv.", 1, 0.3, "Why not?", "为什么不呢？", "why so"),
  v("how", "/怎样；如何", "/haʊ/", "adv.", 1, 0.2, "How are you?", "你好吗？", "how much"),
  v("which", "/哪一个", "/wɪtʃ/", "pron.", 3, 0.4, "Which one do you want?", "你想要哪个？", "which way"),
  v("yes", "/是；对", "/jes/", "adv.", 1, 0.1, "Yes, please.", "是的，麻烦了。", "yes and no"),
  v("no", "/不；没有", "/noʊ/", "adv.", 1, 0.1, "No problem.", "没问题。", "no way"),
  v("not", "/不；没", "/nɑːt/", "adv.", 1, 0.15, "I am not tired.", "我不累。", "or not"),
  v("and", "/和；而且", "/ænd/", "conj.", 1, 0.1, "Tea and coffee.", "茶和咖啡。", "and so on"),
  v("but", "/但是", "/bʌt/", "conj.", 1, 0.2, "Sorry, but I can't.", "抱歉，但我不能。", "but then"),
  v("or", "/或者", "/ɔːr/", "conj.", 1, 0.2, "Tea or coffee?", "茶还是咖啡？", "either or"),
  v("if", "/如果", "/ɪf/", "conj.", 2, 0.4, "If you like.", "如果你愿意的话。", "as if"),
  v("very", "/很；非常", "/ˈveri/", "adv.", 1, 0.15, "Very good!", "非常好！", "very much"),
  v("also", "/也", "/ˈɔːlsoʊ/", "adv.", 2, 0.35, "Me also!", "我也是！", "also known as"),
  v("again", "/再；又", "/əˈɡen/", "adv.", 1, 0.3, "Say it again, please.", "请再说一遍。", "once again"),
  v("all", "/全部；所有", "/ɔːl/", "det.", 1, 0.25, "All the best!", "祝一切顺利！", "all right"),
  v("some", "/一些", "/sʌm/", "det.", 1, 0.2, "Some water, please.", "请给一些水。", "some more"),
  v("many", "/许多", "/ˈmeni/", "det.", 1, 0.25, "How many people?", "多少人？", "so many"),
  v("more", "/更多", "/mɔːr/", "adj./adv.", 1, 0.3, "One more, please.", "再来一个。", "more or less"),
];
