import { v } from "@/content/vocab/builder";
import type { VocabRow } from "@/content/vocab/types";

export const verbsCoreRows: VocabRow[] = [
  v("do", "/做；干", "/duː/", "v.", 1, 0.15, "Do it now.", "现在就做。", "do homework"),
  v("have", "/有；吃；喝", "/hæv/", "v.", 1, 0.2, "I have two kids.", "我有两个孩子。", "have lunch"),
  v("go", "/去", "/ɡoʊ/", "v.", 1, 0.15, "Let's go!", "我们走吧！", "go home"),
  v("come", "/来", "/kʌm/", "v.", 1, 0.2, "Come here, please.", "请过来。", "come back"),
  v("get", "/得到；拿到", "/ɡet/", "v.", 1, 0.3, "Get some rest.", "休息一下。", "get up"),
  v("make", "/做；制作", "/meɪk/", "v.", 1, 0.3, "Make a plan.", "做个计划。", "make friends"),
  v("say", "/说", "/seɪ/", "v.", 1, 0.25, "Say it again.", "再说一遍。", "say hello"),
  v("tell", "/告诉", "/tel/", "v.", 1, 0.3, "Tell me the truth.", "告诉我实话。", "tell me"),
  v("ask", "/问；请求", "/æsk/", "v.", 1, 0.3, "Ask the teacher.", "问老师。", "ask a question"),
  v("know", "/知道；认识", "/noʊ/", "v.", 1, 0.25, "I don't know.", "我不知道。", "you know"),
  v("think", "/想；认为", "/θɪŋk/", "v.", 1, 0.35, "I think so.", "我认为是。", "think about"),
  v("see", "/看见；明白", "/siː/", "v.", 1, 0.2, "See you tomorrow.", "明天见。", "see you"),
  v("look", "/看", "/lʊk/", "v.", 1, 0.25, "Look at this!", "看这个！", "look at"),
  v("watch", "/观看", "/wɑːtʃ/", "v.", 2, 0.3, "Watch TV together.", "一起看电视。", "watch a movie"),
  v("hear", "/听见", "/hɪr/", "v.", 2, 0.35, "I can't hear you.", "我听不见你说话。", "hear from"),
  v("listen", "/听", "/ˈlɪsn/", "v.", 1, 0.3, "Listen to me.", "听我说。", "listen to"),
  v("eat", "/吃", "/iːt/", "v.", 1, 0.2, "Eat more vegetables.", "多吃蔬菜。", "eat out"),
  v("like", "/喜欢", "/laɪk/", "v./prep.", 1, 0.2, "I like blue.", "我喜欢蓝色。", "would like"),
  v("love", "/爱", "/lʌv/", "v./n.", 1, 0.25, "I love my family.", "我爱我的家人。", "fall in love"),
  v("need", "/需要", "/niːd/", "v.", 1, 0.3, "I need help.", "我需要帮助。", "need help"),
  v("help", "/帮助", "/help/", "v./n.", 1, 0.25, "Can you help me?", "你能帮我吗？", "help with"),
  v("talk", "/交谈", "/tɔːk/", "v.", 1, 0.3, "Talk to him.", "和他谈谈。", "talk about"),
  v("speak", "/说（语言）", "/spiːk/", "v.", 1, 0.3, "Speak English, please.", "请说英语。", "speak English"),
  v("read", "/读；阅读", "/riːd/", "v.", 1, 0.3, "Read this book.", "读这本书。", "read a book"),
  v("write", "/写", "/raɪt/", "v.", 1, 0.3, "Write your name here.", "把名字写这里。", "write down"),
  v("work", "/工作；起作用", "/wɜːrk/", "v./n.", 1, 0.3, "I work in a bank.", "我在银行工作。", "go to work"),
  v("play", "/玩；播放", "/pleɪ/", "v.", 1, 0.25, "Play with the kids.", "陪孩子们玩。", "play games"),
  v("open", "/打开", "/ˈoʊpən/", "v./adj.", 1, 0.3, "Open the door.", "开门。", "open the door"),
  v("close", "/关闭", "/kloʊz/", "v.", 1, 0.3, "Close the window.", "关窗。", "close the door"),
  v("start", "/开始", "/stɑːrt/", "v./n.", 1, 0.3, "Start now.", "现在开始。", "start over"),
  v("stop", "/停止", "/stɑːp/", "v./n.", 1, 0.25, "Stop the car!", "停车！", "stop it"),
  v("finish", "/完成", "/ˈfɪnɪʃ/", "v.", 2, 0.4, "Finish your food.", "把饭吃完。", "finish line"),
  v("buy", "/买", "/baɪ/", "v.", 1, 0.3, "Buy some milk.", "买点牛奶。", "buy online"),
  v("sell", "/卖", "/sel/", "v.", 2, 0.4, "They sell fruit.", "他们卖水果。", "sell well"),
  v("pay", "/付钱", "/peɪ/", "v.", 1, 0.35, "I'll pay today.", "我今天付款。", "pay for"),
  v("use", "/使用", "/juːz/", "v.", 1, 0.3, "Use this key.", "用这把钥匙。", "use up"),
  v("try", "/尝试", "/traɪ/", "v.", 1, 0.3, "Try again!", "再试一次！", "try on"),
  v("put", "/放", "/pʊt/", "v.", 1, 0.3, "Put it here.", "放这儿。", "put on"),
  v("find", "/找到", "/faɪnd/", "v.", 1, 0.3, "Find your seat.", "找到你的座位。", "find out"),
  v("keep", "/保持；保存", "/kiːp/", "v.", 2, 0.4, "Keep it safe.", "保管好它。", "keep going"),
  v("turn", "/转动；转向", "/tɜːrn/", "v.", 2, 0.4, "Turn left.", "左转。", "turn on"),
  v("learn", "/学习", "/lɜːrn/", "v.", 1, 0.3, "Learn English every day.", "每天学英语。", "learn from"),
  v("teach", "/教", "/tiːtʃ/", "v.", 2, 0.35, "She teaches math.", "她教数学。", "teach English"),
  v("sit", "/坐", "/sɪt/", "v.", 1, 0.25, "Sit down, please.", "请坐。", "sit down"),
  v("stand", "/站", "/stænd/", "v.", 2, 0.3, "Stand up.", "站起来。", "stand up"),
  v("walk", "/走路", "/wɔːk/", "v./n.", 1, 0.3, "Walk with me.", "陪我走走。", "take a walk"),
  v("run", "/跑；经营", "/rʌn/", "v.", 1, 0.3, "Run every morning.", "每天早上跑步。", "run fast"),
  v("sleep", "/睡觉", "/sliːp/", "v./n.", 1, 0.3, "Sleep eight hours.", "睡八小时。", "go to sleep"),
  v("wash", "/洗", "/wɑːʃ/", "v.", 2, 0.3, "Wash your hands.", "洗手。", "wash hands"),
  v("wait", "/等", "/weɪt/", "v.", 1, 0.3, "Wait for me!", "等等我！", "wait for"),
  v("live", "/住；活着", "/lɪv/", "v.", 1, 0.3, "Where do you live?", "你住哪儿？", "live in"),
  v("leave", "/离开；留下", "/liːv/", "v.", 1, 0.35, "Leave at six.", "六点出发。", "leave home"),
  v("call", "/打电话；称呼", "/kɔːl/", "v.", 1, 0.3, "Call me later.", "晚点打给我。", "call back"),
  v("remember", "/记得", "/rɪˈmembər/", "v.", 2, 0.45, "Remember this word.", "记住这个词。", "remember me"),
  v("forget", "/忘记", "/fərˈɡet/", "v.", 2, 0.4, "Don't forget it.", "别忘了。", "forget about"),
  v("understand", "/理解；懂", "/ˌʌndərˈstænd/", "v.", 1, 0.4, "I understand now.", "我现在懂了。", "I understand"),
  v("sing", "/唱歌", "/sɪŋ/", "v.", 3, 0.35, "Sing a song.", "唱首歌。", "sing along"),
  v("cut", "/切；剪", "/kʌt/", "v.", 2, 0.35, "Cut the apple.", "切苹果。", "cut it"),
];
