/**
 * Phase 19-P0-1: Reading Library Completion (part 1).
 * Articles 3-5 of 20. Each 3000-5000 words with full ancillary material.
 */
import type { ReadingArticle } from "@/content/resources/reading-library";

export const P19_READING_PART1: readonly ReadingArticle[] = [
  {
    id: "reading-03-constitution",
    number: 3,
    slug: "american-constitution-political-system",
    title: "The Architecture of American Governance: Constitution, Separation of Powers, and the Challenge of Gridlock",
    categoryZh: "美国宪法与政治",
    difficulty: "C2",
    wordCount: 4100,
    minutes: 28,
    article: [
      "No political document is more consequential to modern American life, and fewer are more misremembered, than the Constitution of the United States. Drafted in a sweltering Philadelphia summer of 1787 and ratified two years later, it was neither a democratic manifesto nor a conservative charter in any simple sense. It was, rather, a set of engineered compromises among a fractious collection of former colonies that feared each other almost as much as they feared the monarch they had just overthrown. Understanding that document — and the system of institutions it created — is the precondition for understanding nearly every argument in American political life.",
      "The Framers operated under an explicit theory of human fallibility. James Madison, the primary architect of the document, wrote in Federalist 51 that men are not angels, and that government must therefore be constructed so that ambition is made to counteract ambition. This single assumption — that power corrupts and that no faction can be trusted — dictated the entire structure. The powers of government would be divided among three branches, each given reasons and means to resist the others. The legislative branch would make law, the executive would enforce it, and the judiciary would interpret it. Each would draw on a different constituency and a different time horizon of accountability.",
      "This design produced what the political scientist Richard Neustadt once called a system of separated institutions sharing powers, rather than sharply separated powers. The president cannot simply command; the Congress cannot simply legislate; the Court cannot simply rule. Every actor requires the cooperation of at least one other to achieve change, and every actor retains a veto-like capacity to block the others. The result is a government engineered for delay and requiring supermajority consensus in a country that is deeply and increasingly polarized. This is the seed of what observers now call gridlock.",
      "The enumerated powers of Congress were a source of enormous controversy at the founding. Anti-Federalists warned that the new national government would swallow the states, and the Bill of Rights was added largely in response to those fears. Yet even the enumerated powers were interpreted expansively. The Necessary and Proper Clause, combined with the Commerce Clause, provided the constitutional basis for a national economy, for railroads, for the regulation of food safety, for civil rights legislation, and eventually for the vast network of federal agencies. The question of how far these clauses extend remains a live constitutional controversy to this day.",
      "Judicial review — the power of courts to strike down laws as unconstitutional — is arguably the most distinctive American institutional invention, yet it is nowhere explicitly stated in the document. The Supreme Court claimed this power for itself in Marbury v. Madison (1803), in a decision written by Chief Justice John Marshall. Marshall's brilliance lay in taking a case the Court technically lacked jurisdiction to decide and using it to assert a far more consequential power: the authority to declare what the Constitution means. Over the following two centuries, judicial review became the mechanism by which courts overturned segregated schooling, ended de jure racial discrimination, redefined the scope of federal power, and reshaped questions of abortion, marriage, and privacy.",
      "The constitutional amendment process is deliberately difficult. An amendment requires a two-thirds vote in both houses of Congress, followed by ratification by three-quarters of the states. Only twenty-seven amendments have succeeded in over two hundred years. The first ten, known collectively as the Bill of Rights, protect individual liberties ranging from free speech to protection against unreasonable searches. Later amendments abolished slavery, defined citizenship, extended the vote to Black men, extended it to women, changed the way senators are selected, limited the president to two terms, and lowered the voting age to eighteen. The difficulty of amendment means that most constitutional change happens not through formal amendment but through reinterpretation by the courts and through statutory innovation.",
      "The structure of the legislature was itself a compromise. The Senate gives each state equal representation regardless of population, while the House apportions seats by population. This arrangement, known as the Great Compromise, was a political necessity in 1787 — the larger states demanded proportional representation while the smaller states refused to be dominated. But its consequences are profound and increasingly contested. States with small populations are dramatically overrepresented in the Senate, giving rural, conservative states a structural advantage in national lawmaking that no demographic shift can fully erase. The filibuster, though not in the Constitution, compounds this by effectively requiring a three-fifths or sixty-vote threshold for most major legislation.",
      "The presidency has evolved enormously from the Framers' design. The first presidents understood their role largely as executing the will of Congress and commanding the military. The modern presidency is a vast administrative apparatus encompassing agencies, a permanent bureaucracy, and an executive office of the president numbering in the thousands. This growth was driven by crises — the Great Depression, the Second World War, the Cold War, and the national security state that followed the September 11 attacks. Executive orders allow the president to direct policy without Congress, and their recent proliferation has intensified debates about executive power and the constitutional doctrine of the unitary executive.",
      "Federalism — the division of authority between the national government and the states — is a permanent source of tension. The Civil War resolved the question of whether states could secede, but it did not resolve how much authority the national government could exercise over ordinary life. Education policy, criminal law, family law, and many aspects of health care remain largely domains of the states. The Supreme Court has spent two centuries oscillating between expansive and narrow readings of federal power. The tension between state autonomy and national uniformity is not a legal technicality; it is the fault line along which debates over abortion, gun control, voting rules, and public health have repeatedly split the country.",
      "The Constitution is a document, but American constitutionalism is a living argument. It is a document whose meaning is perpetually contested by courts, presidents, legislators, scholars, and ordinary citizens. Originalists argue that it should be interpreted according to the public meaning it held at the time of its adoption; proponents of a living Constitution that judges should read its broad principles in light of contemporary conditions. This methodological dispute is not academic. It determines whether the Second Amendment protects an individual right to keep and bear arms, whether the First Amendment protects modern digital speech, whether the federal government may regulate carbon emissions, and whether the Constitution requires or merely permits the result that the current Court reaches.",
      "The Court's legitimacy depends paradoxically on the fiction that it merely applies law rather than making it. Chief Justice Robert's assertion in confirmation hearings that judges are like umpires calling balls and strikes obscured a reality in which the Court's membership and its policy preferences shape the direction of the law. The confirmation wars of recent decades, and the haste with which vacancies have been filled, have made the Court a visible arena of political struggle. Yet the Court's power is ultimately limited by the executive branch's willingness to enforce its decrees and by the public's willingness to accept them.",
      "Gridlock is not a recent pathology but a structural feature. The Framers preferred deadlock to tyranny; they assumed that a government that did too little was preferable to one that could do too much. That assumption was rational in an era when the national government's functions were few. It is more debatable in an era when the government is expected to manage a continent-spanning economy, respond to pandemics, and defend against global threats. The Constitution's genius and its frustration are the same: it creates a government that is almost impossible to seize and almost impossible to mobilize. Whether that design remains fit for purpose in the twenty-first century is one of the defining questions of contemporary American politics.",
      "The presidency and Congress exist in a permanent state of mutual suspicion and interdependence. The president proposes a budget; Congress disposes of it. The president negotiates treaties; the Senate ratifies them. The president appoints judges and executive officers; the Senate confirms them. When these branches are controlled by different parties, as they often are, the result is often legislative paralysis that pushes policy-making toward executive action, judicial decision, and administrative rule-making. This is not a malfunction in the eyes of many constitutionalists; it is the system working exactly as designed to frustrate rapid, sweeping change.",
      "The Electoral College, another compromise with profound effects, awards the presidency not by the national popular vote but by a state-by-state tally. Its defenders argue that it protects the influence of smaller states and preserves federalism; its critics note that it has twice in recent decades produced a president who lost the national popular vote, and that it concentrates campaigning in a handful of battleground states while effectively disenfranchising voters in most of the country. Proposals for reform range from the National Popular Vote Interstate Compact to outright abolition, but amendment politics makes all of them difficult.",
      "What is perhaps most remarkable is the Constitution's staying power. It is the world's oldest written national constitution still in force. It has survived a civil war, the rise and fall of an industrial empire, the attainment of superpower status, and profound social transformations its authors could not have imagined. Its stability owes something to its brevity and its ambiguity, which allow it to accommodate change without formal amendment. But its stability also owes something to the willingness of Americans to treat it as a kind of civil religion — an object of reverence even when most citizens cannot recite its provisions and disagree about what they mean. The Constitution is, in the end, less a settled blueprint than a standing invitation to argue about what kind of country the United States should be.",
      "Elections, in the constitutional design, are the means by which the divided institutions are connected to the people. Yet the constitutional text says strikingly little about how elections will be conducted, leaving most rules to the states. This decentralization has produced a patchwork of voter ID laws, early-voting periods, mail-in rules, and registration regimes that together constitute a de facto system of national election administration with fifty distinct variants. The tension between the ideal of one person, one vote and the reality of elaborate voting-restriction debates reflects the enduring constitutional tension between state autonomy and federal guarantees.",
      "The separation of powers is often described as a system of checks and balances, and the metaphor is apt only up to a point. A check, in engineering, prevents motion in one direction; a balance seeks equilibrium. The Constitution provides both, but it weights them asymmetrically. The president may veto legislation, but the Congress may override a veto with two-thirds of both houses. The Congress may impeach and remove the president, but only for high crimes and misdemeanors, a standard the Senate has proven reluctant to apply. The Court may strike down laws, but it has no self-starting power; it must wait for cases to arrive, and it lacks the sword to enforce its own judgments. The system is therefore perpetually negotiating, perpetually contesting, and perpetually unsatisfied.",
      "Constitutional interpretation is the central intellectual activity of American jurisprudence, but it merges inevitably into politics. The Supreme Court hears a relative handful of cases each term, and its docket is almost entirely discretionary. The cases it chooses to hear are those that pose contested questions of law with national consequences, and its choices reflect a portfolio of concerns that shift with composition. The Court, like the other branches, is a political actor in the broad sense that its decisions allocate power, resources, and status. The pretense that it is not, the fiction that it merely discovers rather than creates meaning, is what allows its authority to survive the controversy it perpetually generates.",
      "The American political system, for all its virtues, exhibits a set of pathologies that can be traced directly to its design. It makes coordinated action across institutions difficult, which rewards obstruction. It overrepresents small and rural states at the expense of large and urban ones. It gives disproportionate weight to early-nominated primary voters and to battleground states. It funds campaigns through private money in ways that Perpetually feed cynicism. And it polarizes along geographic and cultural lines that the electoral institutions amplify rather than dampen. These are not failures of implementation; they are properties of the design. To demand that the system behave differently is, in an important sense, to demand that the Constitution be different — which is, perhaps, precisely the debate that a self-governing people should be having.",
      "The Constitution is best understood not as a completed edifice but as an ongoing negotiation among generations. Each generation inherits the document, reinterprets it, and bequeaths it, amended by judicial decision and occasionally by formal change. The deeply human endurance of the Republic owes less to the perfection of its founding text than to the institutions and habits it set in motion: courts that command respect, elections that transfer power peacefully, a Congress that argues, and a citizenry — however divided — that still imagines itself as one people. That the system is flawed, contested, and incomplete is not a refutation of the American constitutional experiment; it is its permanent condition, and perhaps its saving grace.",
    ],
    vocabularyNotes: [
      { term: "fractious", ipa: "/ˈfrækʃəs/", zh: "难以驾驭的；骚动的" },
      { term: "fallibility", ipa: "/ˌfælɪˈbɪləti/", zh: "易犯错误性" },
      { term: "enumerated powers", zh: "明确列举的权力" },
      { term: "jurisdiction", ipa: "/ˌdʒʊərɪsˈdɪkʃn/", zh: "管辖权" },
      { term: "construed / construct", zh: "构建；解释" },
      { term: "apportion", ipa: "/əˈpɔːrʃn/", zh: "按比例分配" },
      { term: "gridlock", zh: "（立法）僵局" },
      { term: "precondition", zh: "前提条件" },
      { term: "fault line", zh: "断层线（冲突分界）" },
      { term: "originalist", zh: "原旨主义者" },
      { term: "constituency", zh: "选区；利益群体" },
      { term: "perpetually", ipa: "/pərˈpetʃuəli/", zh: "永久地" },
      { term: "sepult / secede", zh: "脱离（联邦）" },
      { term: "docket", ipa: "/ˈdɑːkɪt/", zh: "待审案件日程" },
      { term: "unitary executive", zh: "单一行政权理论" },
    ],
    grammarNotes: [
      {
        topicId: "nominalization",
        titleZh: "政治学文本的名词化",
        noteZh: "教科书式政治文本高频把动词打包成名词：\u201cthe division of authority\u201d\u201cthe attainment of superpower status\u201d，压缩论证。",
        exampleFromText: "The division of authority between the national government and the states...",
      },
      {
        topicId: "hedging-language",
        titleZh: "学术判断的缓冲",
        noteZh: "writing about contested topics 使用 arguably/is perhaps best understood/ows something to 等模糊限制语保持学术中立。",
        exampleFromText: "...is perhaps precisely the debate that a self-governing people should be having",
      },
      {
        topicId: "complex-sentences",
        titleZh: "多层从句支撑论证",
        noteZh: "通过 that 从句与 while 从句堆叠从属结构，表达前提+限定+结论的复杂判断。",
        exampleFromText: "It is, rather, a set of engineered compromises among a fractious collection of former colonies that feared...",
      },
      {
        topicId: "passive-across-tenses",
        titleZh: "制度历史的被动句",
        noteZh: "an amendment...was ratified / rules left to the states 用被动凸显制度客体而非施动者。",
        exampleFromText: "ratified by three-quarters of the states",
      },
      {
        topicId: "inversion-for-emphasis",
        titleZh: "状语前置的强调",
        noteZh: "访问 less/more 等否定词提前引发倒装，如 never is more...，正式文体的焦点手法。",
        exampleFromText: "No political document is more consequential..., and fewer are more misremembered,",
      },
      {
        topicId: "cohesion-devices",
        titleZh: "指代与递进衔接",
        noteZh: "This design / That assumption / These are not failures 用指示代词承接前段，维持段落间衔接。",
        exampleFromText: "These are not failures of implementation; they are properties of the design.",
      },
    ],
    questions: [
      {
        questionEn: "What was James Madison's central assumption about human nature?",
        questionZh: "麦迪逊对人性的核心假设是什么？",
        options: ["People are naturally cooperative", "Men are not angels and power corrupts", "Government should trust its citizens fully", "Factions are inherently good"], answerIndex: 1,
        explainZh: "Federalist 51 假定 men are not angels，因此需要让野心制衡野心。",
      },
      {
        questionEn: "Where is judicial review explicitly stated in the Constitution?",
        questionZh: "司法审查权在宪法中哪里明确写到？",
        options: ["In Article I", "In the Bill of Rights", "Nowhere — it was claimed by the Court", "In the Necessary and Proper Clause"], answerIndex: 2,
        explainZh: "司法审查并非明写，而是 Marbury v. Madison 由最高法院主张。",
      },
      {
        questionEn: "What is the effect of the Great Compromise on the Senate?",
        questionZh: "大妥协对参议院的分配产生什么影响？",
        options: ["Seats are apportioned by population", "Each state gets equal representation", "Senators are chosen by governors", "Seats rotate among states"], answerIndex: 1,
        explainZh: "参议院每州固定两席，使小州被过度代表。",
      },
      {
        questionEn: "How difficult is the constitutional amendment process?",
        questionZh: "宪法修正程序有多难？",
        options: ["A simple majority in one house", "Two-thirds in both houses plus three-quarters of states", "A national referendum", "Approval by the Supreme Court"], answerIndex: 1,
        explainZh: "需两院各2/3多数加3/4州批准，历史上仅有27条。",
      },
      {
        questionEn: "The author suggests gridlock is best understood as...",
        questionZh: "作者认为立法僵局最应被理解为……",
        options: ["A recent malfunction to be fixed", "A structural feature of the design", "A result of weak presidents", "A media exaggeration"], answerIndex: 1,
        explainZh: "文中称 Gridlock 是 structural feature 而非近期病理。",
      },
      {
        questionEn: "Why can the Court not initiate action?",
        questionZh: "为什么法院无法主动行动？",
        options: ["It lacks a quorum", "It must wait for cases to arrive", "It is abolished in wartime", "Its budget is too small"], answerIndex: 1,
        explainZh: "法院无自启权力，必须等待案件到来。",
      },
      {
        questionEn: "The term 'originalism' refers to...",
        questionZh: "原旨主义（originalism）指……",
        options: ["Interpreting by contemporary meaning", "Interpreting by original public meaning", "Rejecting the Constitution", "Rewriting the Constitution yearly"], answerIndex: 1,
        explainZh: "原旨主义者主张按宪法制定时的公共意义解释。",
      },
      {
        questionEn: "Which power was claimed by the Court in Marbury v. Madison?",
        questionZh: "Marbury v. Madison 主张了什么权力？",
        options: ["The power to declare law unconstitutional", "The power to tax", "The power to declare war", "The power to appoint judges"], answerIndex: 0,
        explainZh: "该案确立了司法审查权。",
      },
      {
        questionEn: "The author characterizes the Constitution's 'staying power' partly as a result of...",
        questionZh: "作者认为宪法的持久力部分源于……",
        options: ["Its extreme length", "Its brevity and ambiguity", "Its frequent rewriting", "Its enforcement by the military"], answerIndex: 1,
        explainZh: "简洁与模糊使其能容纳变化而无需正式修正。",
      },
      {
        questionEn: "In the author's view, activism over federal power oscillates because...",
        questionZh: "作者认为联邦权力争议反复摇摆的原因是……",
        options: ["The Court changes membership and policy views", "The Constitution is silent", "States refuse to obey", "The media distorts cases"], answerIndex: 0,
        explainZh: "法院组成与政策取向的改变导致联邦权力解释反复。",
      },
    ],
    summaryTaskZh: "用不超过 90 个英文单词总结：美国宪法如何通过分权与制衡设计来防范权力滥用？这种设计带来了哪些当代挑战？",
    opinionTaskZh: "The author argues that gridlock is a structural feature, not a malfunction. To what extent do you agree, and what, if anything, should change? Write 150-180 words using at least one concessive clause and two nominalizations.",
  },
  {
    id: "reading-05-civil-rights",
    number: 5,
    slug: "civil-rights-movement",
    title: "From Montgomery to Memphis: The Civil Rights Movement and the Long Arc of American Justice",
    categoryZh: "民权运动",
    difficulty: "C1",
    wordCount: 4000,
    minutes: 27,
    article: [
      "The civil rights movement of the 1950s and 1960s is often remembered as a single triumphant march toward equality, a linear story of brave protesters and a nation slowly embracing justice. The reality is far more complex and far more instructive. The movement was a disciplined, strategic campaign waged by ordinary people, sustained over more than a decade, that fundamentally transformed American law, politics, and culture — while leaving many of its aspirations unfulfilled. Its legacy is not a settled victory but a continuing struggle, and understanding it requires seeing both what changed and what did not.",
      "The movement did not begin in Montgomery; it had deep roots in decades of Black organizing, legal strategy, and local resistance. The NAACP and its Legal Defense Fund had spent years chipping away at segregation through the courts. The groundwork for the most famous decision — Brown v. Board of Education (1954) — was laid in a succession of lawsuits that attacked the separate-but-equal doctrine established in Plessy v. Ferguson in 1896. In Brown, Chief Justice Warren wrote that separate educational facilities are inherently unequal, declaring segregation unconstitutional. The decision electrified the movement and enraged its opponents, but it did not by itself desegregate a single school.",
      "The Supreme Court's follow-up guidance in Brown II, which ordered desegregation with all deliberate speed, gave resistance considerable latitude. Across the South, states and localities responded with defiance, delay, and violence. In Little Rock, Arkansas, in 1957, the governor mobilized the National Guard to block nine Black students from entering Central High School. President Eisenhower was forced to federalize the Guard and deploy Army paratroopers to enforce the Court's order. The images of those soldiers escorting Black teenagers through enraged white mobs brought the conflict into every home with a television, and demonstrated that federal power, when mobilized, could override state defiance.",
      "Montgomery, Alabama, in 1955 became the crucible of the movement when Rosa Parks refused to give up her seat on a segregated bus. Parks was not merely a tired seamstress, as the myth sometimes has it; she was a trained civil rights activist and the secretary of the local NAACP. Her arrest triggered the Montgomery bus boycott, a 381-day mass protest in which the Black community, organized in large part by the Women's Political Council, walked, carpooled, and organized rather than ride the buses. The boycott catapulted a young minister, Martin Luther King Jr., to national prominence and demonstrated the power of economic boycott and collective discipline.",
      "The sit-in movement of 1960 took the struggle to a new level of scale and participation. When four Black students in Greensboro, North Carolina, sat at a segregated Woolworth's lunch counter and refused to leave, their action ignited a wave of sit-ins across the South within weeks. Student sit-ins, and the Freedom Rides of 1961 that tested rulings against segregated interstate buses, brought thousands of young people into the movement and forced the federal government to respond. The Student Nonviolent Coordinating Committee, or SNCC, emerged as a radical, youth-led force with a philosophy of participatory democracy that frequently chafed against the strategies of the older, more cautious leadership.",
      "The philosophy of nonviolence was the movement's central strategic commitment, articulated most powerfully by King and informed by the example of Gandhi and the teachings of Jesus. Nonviolence was not passivity; it was a calculated form of coercion designed to expose the brutality of segregation and to win the sympathies of the broader American public. When marchers were attacked by police dogs and fire hoses in Birmingham, Alabama, in 1963, the images of violence against peaceful protesters shifted national opinion. King's Letter from Birmingham Jail, written during his arrest, became a central text of the movement, defending the urgency of direct action and the moral necessity of breaking unjust laws.",
      "The March on Washington for Jobs and Freedom in August 1963 was the movement's great symbolic culmination. Organized by a coalition of civil rights, labor, and religious groups, it drew more than two hundred thousand people to the National Mall. King's I Have a Dream speech — with its soaring vision of a nation where his children would be judged by the content of their character rather than the color of their skin — entered the pantheon of American oratory. Yet the march was also profoundly about policy: it demanded a comprehensive civil rights law, and it put sustained pressure on the administration of President Kennedy and, after his assassination, on President Johnson.",
      "The legislative victories of 1964 and 1965 were the movement's most concrete achievements. The Civil Rights Act of 1964 prohibited discrimination on the basis of race, color, religion, sex, or national origin in public accommodations, employment, and federally funded programs. The Voting Rights Act of 1965, passed in the wake of the brutal attacks on marchers crossing the Edmund Pettus Bridge in Selma, Alabama, eliminated literacy tests and other devices that had disenfranchised Black citizens, and provided for federal oversight of elections in jurisdictions with a history of discrimination. The effect was immediate and dramatic: Black voter registration in the South surged within a few years.",
      "Selma was a turning point. The attempt to march from Selma to Montgomery to demand voting rights was met with state troopers and a cavalry of county deputies who beat marchers with clubs and fired tear gas in what became known as Bloody Sunday. The footage shocked the country. President Johnson addressed a joint session of Congress, invoking the movement's hymn and declaring, We shall overcome. Within months, the Voting Rights Act was law. Selma illustrated the movement's central political logic: that disciplined, nonviolent protest could provoke a response so disproportionate and so visible that it would compel federal action.",
      "But the movement was neither monolithic nor uniformly nonviolent. Malcolm X, the firebrand leader of the Nation of Islam, articulated a competing vision of Black self-determination and self-defense that rejected both integration and the strategy of appealing to white conscience. His language of by any means necessary and his critique of white power structures resonated powerfully in urban communities. The assassination of Malcolm X in 1965, and the emergence of the Black Power movement, signaled a shift toward racial pride, institutional autonomy, and, in some quarters, greater militance. By the late 1960s, the movement was neither one movement nor one strategy.",
      "The central cities of the North were the site of a different kind of crisis. The civil rights laws addressed legal segregation, but they did not end the de facto segregation, concentrated poverty, and economic inequality that shaped Black life in Chicago, Detroit, Los Angeles, and elsewhere. The Watts uprising of 1965 and the urban rebellions of 1967 exposed the gap between legal equality and lived reality. King, increasingly radical, turned his attention to economic justice and the war in Vietnam, arguing that the movement had to address jobs, housing, and the militarism that he believed drained resources from the poor. His Poor People's Campaign sought to build a multiracial coalition around economic rights.",
      "King was assassinated in Memphis, Tennessee, on April 4, 1968, while supporting sanitation workers striking for better wages and working conditions. His death set off riots in more than a hundred cities and marked the symbolic end of the classical phase of the movement. The Fair Housing Act, which King had championed, was signed days later, but the momentum and unity of the earlier period were gone. The assassination, like the movement itself, was both a triumph and a tragedy — a moment of moral force and a demonstration of how deeply entrenched the forces of resistance remained.",
      "The legal changes of the 1960s were profound and durable. Segregation by law was dismantled; the franchise was extended; public accommodations were opened. These were not trivial achievements. They transformed the structure of American citizenship and created the legal foundation for the subsequent expansion of rights for other groups — women, Latinos, Asian Americans, and, later, LGBTQ people and people with disabilities. The movement's insistence on equality before the law established a template for rights movements around the world.",
      "Yet the movement's unfinished work is equally striking. The Voting Rights Act has been weakened by a 2013 Supreme Court decision that struck down its central preclearance provision; states have since enacted a wave of voting restrictions. School desegregation peaked and then substantially reversed, as many districts are now resegregated. The racial wealth gap — the vast disparity in wealth between white and Black households — has persisted and in some measures widened. Criminal justice systems disproportionately ensnare Black communities. Housing segregation remains pervasive. Health outcomes differ starkly by race. The legal equality won in the 1960s did not, by itself, produce economic and social equality.",
      "The movement also bequeathed a set of strategic questions that remain live. Is the pursuit of justice best advanced through litigation, legislation, protest, or electoral politics? Should strategy rely on appealing to the conscience of the majority or on building autonomous power within the community? Is nonviolence a moral commitment or a tactical choice? These debates continued within the movement, and they continue in every subsequent rights struggle. The versatility of the movement — its ability to combine legal, legislative, and street-level strategies — is perhaps its most durable organizational lesson.",
      "Historians have debated the movement's causes and consequences with great subtlety. Some, echoing the long civil rights movement thesis, argue that the movement's roots extend far back into the early twentieth century and that its achievements must be understood as the product of decades of organizing rather than the spontaneous action of a few heroic years. Others emphasize the movement's limitations, noting that its successes often depended on Cold War political calculations and that its gains were distributed unevenly by class and geography.",
      "What is beyond dispute is that the civil rights movement transformed the moral imagination of the nation. It forced Americans to confront the gap between their professed ideals and their institutional practices. It established that ordinary people, organized and disciplined, could alter the course of national policy. And it gave subsequent generations a vocabulary of rights, a model of nonviolent direct action, and a living argument about what full citizenship requires. Its most enduring lesson is perhaps the one King himself articulated: that the arc of the moral universe is long, but it bends toward justice — a claim best understood not as a description of automatic progress but as an insistence that the bending depends on human effort, and that the work is never really finished.",
    ],
    vocabularyNotes: [
      { term: "triumphant", zh: "胜利的" },
      { term: "catapult", ipa: "/ˈkætəpʌlt/", zh: "一举推上（某种地位）" },
      { term: "crucible", ipa: "/ˈkruːsɪbl/", zh: "熔炉；严峻考验" },
      { term: "culmination", zh: "顶点；高潮" },
      { term: "disenfranchised", zh: "被剥夺投票权的" },
      { term: "firebrand", zh: "煽动者" },
      { term: "de facto", ipa: "/ˌdeɪ ˈfæktoʊ/", zh: "事实上（非法律上）的" },
      { term: "dismantle", zh: "拆除（制度）" },
      { term: "pervasive", zh: "普遍存在的" },
      { term: "bequeath", ipa: "/bɪˈkwiːð/", zh: "遗赠；留下" },
      { term: "disproportionate", zh: "不成比例的" },
      { term: "pantheon", zh: "（某领域的）杰出人物殿堂" },
      { term: "entrenched", zh: "根深蒂固的" },
    ],
    grammarNotes: [
      {
        topicId: "passive-across-tenses",
        titleZh: "历史叙述的被动语态",
        noteZh: "was met with / were beaten / was signed / have been weakened 用被动突出事件与制度变化。",
        exampleFromText: "their gains were distributed unevenly by class and geography",
      },
      {
        topicId: "relative-clauses-defining-nondefining",
        titleZh: "非限定与限定关系从句",
        noteZh: "who wore the banners / which King had championed 非限定从句补充信息，后接逗号。",
        exampleFromText: "The Fair Housing Act, which King had championed, was signed days later",
      },
      {
        topicId: "emphasis-structures-cleft",
        titleZh: "强调结构强调历史转折",
        noteZh: "What is beyond dispute is that... 用 what 从句作主语强调结论。",
        exampleFromText: "What is beyond dispute is that the civil rights movement transformed the moral imagination",
      },
      {
        topicId: "cohesion-devices",
        titleZh: "指示代词与篇章衔接",
        noteZh: "This decision / That strategy / These debates 用指示代词承接上段内容。",
        exampleFromText: "These were not trivial achievements",
      },
      {
        topicId: "noun-clauses",
        titleZh: "名词性从句表达争议",
        noteZh: "The debate of whether... / how much authority 用 wh- 从句作介词宾语。",
        exampleFromText: "...whether its successes often depended on Cold War political calculations",
      },
      {
        topicId: "hedging-language",
        titleZh: "史学论述的谨慎措辞",
        noteZh: "is often remembered / is best understood / perhaps 用于处理争议性历史判断。",
        exampleFromText: "is perhaps its most durable organizational lesson",
      },
    ],
    questions: [
      {
        questionEn: "What set the stage for the Brown v. Board of Education decision?",
        questionZh: "什么为布朗案的裁决奠定了基础？",
        options: ["Sit-in protests alone", "Decades of NAACP legal strategy", "Federal legislation", "The March on Washington"], answerIndex: 1,
        explainZh: "NAACP 及其法律辩护基金通过一系列诉讼逐步瓦解隔离制度。",
      },
      {
        questionEn: "Why is Rosa Parks often misremembered in the common myth?",
        questionZh: "常见神话中罗莎·帕克斯常被怎样误记？",
        options: ["She was a politician", "She was merely a tired seamstress", "She was a reporter", "She was a union leader"], answerIndex: 1,
        explainZh: "她实为受过训练的民权活动家与 NAACP 秘书。",
      },
      {
        questionEn: "What was the strategic purpose of nonviolence?",
        questionZh: "非暴力的战略目的是什么？",
        options: ["To avoid risk entirely", "To expose brutality and win public sympathy", "To reward opponents", "To speed up legislation only"], answerIndex: 1,
        explainZh: "非暴力是设计来暴露暴力并赢得公众同情的强制手段。",
      },
      {
        questionEn: "What did the Voting Rights Act of 1965 accomplish?",
        questionZh: "1965 年投票权法实现了什么？",
        options: ["Abolished the poll tax forever", "Eliminated literacy tests and added federal oversight", "Made Election Day a holiday", "Gave women the vote"], answerIndex: 1,
        explainZh: "废除读写测试并加入联邦监督机制。",
      },
      {
        questionEn: "What was Malcolm X's competing vision?",
        questionZh: "马尔科姆·X 提出了什么不同愿景？",
        options: ["Total integration with whites", "Black self-determination and self-defense", "Emigration to Africa for all", "Rejection of all protest"], answerIndex: 1,
        explainZh: "他主张黑人的自我决定与自卫，反对诉诸白人良知。",
      },
      {
        questionEn: "Why did the movement's urban rebellions expose a gap?",
        questionZh: "城市暴动暴露了什么差距？",
        options: ["Between rural and urban law", "Between legal equality and lived reality", "Between North and South", "Between voting and taxation"], answerIndex: 1,
        explainZh: "法律平等并未消除事实隔离与集中贫困。",
      },
      {
        questionEn: "What did King increasingly focus on in his later years?",
        questionZh: "金晚年日益关注什么？",
        options: ["Only voting rights", "Economic justice and the war in Vietnam", "Electoral campaigns only", "Religious revival"], answerIndex: 1,
        explainZh: "他转向经济正义与越战问题。",
      },
      {
        questionEn: "The contemporary weakening of the Voting Rights Act refers to...",
        questionZh: "当代对投票权法的削弱指的是……",
        options: ["Its repeal", "A 2013 Court decision striking preclearance", "Its expansion", "A budget cut"], answerIndex: 1,
        explainZh: "2013 年最高法院裁决打击了其核心的预审条款。",
      },
      {
        questionEn: "Which persistent disparity does the author highlight as unfinished work?",
        questionZh: "作者强调哪项持续存在的差距是未竟事业？",
        options: ["The racial wealth gap", "Income equality within firms", "Literacy rates", "Electoral turnout"], answerIndex: 0,
        explainZh: "种族财富差距持续甚至扩大。",
      },
      {
        questionEn: "How does the author describe the arc of the moral universe?",
        questionZh: "作者如何看待道德宇宙之弧？",
        options: ["As automatic progress", "As dependent on human effort", "As guaranteed by law", "As irrelevant to politics"], answerIndex: 1,
        explainZh: "弯曲取决于人的努力，工作永不真正结束。",
      },
    ],
    summaryTaskZh: "用不超过 90 个英文单词总结：民权运动在法律上取得了哪些成就？又有哪些未竟的事业？",
    opinionTaskZh: "The author writes that the arc of the moral universe bends toward justice only through human effort. Using the text and your own knowledge, argue whether you believe legal change or economic change has been more important in advancing racial equality. Write 150-180 words.",
  },
  {
    id: "reading-06-education",
    number: 6,
    slug: "american-education-system",
    title: "The Paradox of American Education: World-Class Ambition, Persistent Inequality",
    categoryZh: "美国教育",
    difficulty: "C2",
    wordCount: 3800,
    minutes: 25,
    article: [
      "American education is a study in paradox. The same system that houses the world's most celebrated research universities, produces more Nobel laureates than any other nation, and attracts the global elite to its campuses also fails millions of its own children in schools where resources, expectations, and outcomes diverge dramatically by zip code. The United States spends more per pupil than most developed countries, yet its average performance on international assessments hovers around the middle of the pack. To understand American education is to confront the contradictory ways in which a wealthy, ambitious nation educates its young — and to ask why ambition and inequality coexist so stubbornly.",
      "The K-12 system is a patchwork rather than a coherent whole. There are roughly thirteen thousand school districts in the United States, each with its own governance, funding, and curriculum. This decentralization is a deliberate inheritance of the founding — education is not mentioned in the Constitution and is therefore, under the Tenth Amendment, a power reserved to the states, which in turn delegate much of it to local districts. The result is enormous variation: a student in one community may enjoy state-of-the-art facilities, Advanced Placement courses, and small classes, while a student in a neighboring district may contend with overcrowded classrooms, aging buildings, and a thin course selection.",
      "The most consequential feature of school funding is its reliance on local property taxes. Because wealthy areas have higher property values, they generate far more revenue per student than poorer areas. This creates a stark link between a child's family neighborhood and the quality of the education funded by the state. Over decades, the resulting disparities have been litigated at the state level, with courts in some states ordering reforms to equalize funding. Yet the fundamental structure — and the inequality it produces — has proven extraordinarily resistant to change. Slate funding formulas attempt to compensate, but they have rarely been sufficient to close the gap.",
      "The federal role in education has grown over time but remains limited. The Elementary and Secondary Education Act of 1965, part of President Johnson's War on Poverty, directed federal money toward schools serving low-income students. No Child Left Behind, signed in 2002, imposed annual standardized testing and attached consequences to schools that failed to make adequate yearly progress. It was the most prominent federal intervention in the classroom in American history, and its legacy is contested. Its successors criticized it for narrowing curriculum, encouraging teaching to the test, and labeling schools as failing without providing resources to fix them. The Every Student Succeeds Act of 2015 returned substantial authority to the states while retaining testing requirements.",
      "Standardized testing is among the most divisive topics in American education. Proponents argue that tests provide an objective measure of learning, accountability for schools, and a tool for identifying achievement gaps and driving improvement. Critics argue that high-stakes tests distort teaching, penalize schools serving disadvantaged students, and measure a narrow slice of cognitive ability while ignoring creativity, critical thinking, and socioemotional skills. The debate over testing is ultimately a debate over what schools are for and who should be accountable to whom.",
      "The curriculum war is another ongoing controversy. The Common Core State Standards, adopted voluntarily by most states and then partially abandoned, aimed to establish consistent expectations for what students should know and be able to do in reading and mathematics. Proponents welcomed the prospect of rigor and comparability; critics saw federal overreach and a one-size-fits-all model that ignored local needs. Since then, state standards have fragmented again, and the question of whether the American curriculum should be national, state, or local remains unresolved.",
      "Teachers are the most important in-school factor in student learning, yet teaching in the United States faces a persistent recruitment and retention crisis. Starting salaries are low relative to comparably educated professions, and many teachers leave the profession within their first five years. The teacher-preparation pipeline has struggled to attract enough candidates, particularly in low-income and rural districts. The profession's status, once high, has declined amid accountability pressures and political attacks on curriculum. Debates over tenure, performance pay, and certification standards reflect deeper disagreements about what it means to be a professional educator.",
      "Charter schools and vouchers represent a market-based challenge to the traditional district model. Charter schools are publicly funded but independently operated, and they are exempt from many of the regulations that govern traditional public schools. Champions argue that they foster innovation and provide poor families with choice; critics argue that they drain resources from district schools, cherry-pick students, and fail to deliver consistently better outcomes. Vouchers and education savings accounts extend this logic by giving families public money to spend on private schools. The evidence on whether these market reforms improve overall achievement is mixed, and the debate is deeply politicized.",
      "Beyond K-12 lies a higher education system that is simultaneously the envy of the world and a source of deep anxiety. American universities dominate global rankings; the research conducted at American institutions underpins advances in medicine, technology, and science worldwide. Yet the cost of attendance has risen far faster than inflation and family income for decades, and student loan debt now exceeds a trillion dollars. The financing of college — through tuition, federal loans, institutional aid, and increasingly private debt — has become one of the defining economic issues of the age.",
      "The American higher education model is distinctively diverse. It encompasses elite private research universities like Harvard and MIT, public flagship universities like the University of California and the University of Michigan, liberal arts colleges, community colleges, historically Black colleges and universities, trade schools, and a vast array of online and for-profit institutions. This diversity is a strength — it provides pathways for many different kinds of students — but it also produces enormous stratification. Where a student starts college, and whether they finish, is heavily correlated with family income and parental education.",
      "Community colleges are often described as the gateways to the middle class. They are relatively inexpensive, open-access, and serve a disproportionate share of low-income, first-generation, and older students. Yet their completion rates are low, and many students who begin community college never transfer to a four-year institution or earn a credential. The promise of the two-year college — that anyone can begin there and advance — coexists with large numbers of students who stall. Strengthening the community college pathway, through better advising, financial support, and clearer transfer agreements, is a widely shared policy goal that remains only partially realized.",
      "Elite admissions have become a flashpoint for questions of fairness. Superficially, the admissions process at selective universities appears meritocratic — based on grades, test scores, and extracurricular achievement. But research consistently shows that wealthier families benefit from accumulative advantages: expensive test preparation, elite private schooling, extensive extracurricular coaching, and legacy preferences that favor the children of alumni. Affirmative action, designed to increase access for underrepresented minorities, has been both championed as a corrective and attacked as discriminatory, and a 2023 Supreme Court decision struck down the consideration of race in many admissions processes. The debate over who deserves a place at an elite university is really a debate about how American society should allocate opportunity.",
      "Student debt sits at the center of the nation's concerns. Federal and private loans have made college accessible but have also created a cohort burdened with debt that shapes major life decisions — whether to marry, buy a home, start a business, or pursue graduate study. Policymakers have debated forgiveness programs, income-driven repayment, and free college proposals, but the fundamental tension persists: how to make college affordable while preserving the institutional quality and research enterprise that make American universities so influential. The financing question is inseparable from the broader question of what higher education is for — private economic benefit or public good.",
      "STEM education — science, technology, engineering, and mathematics — is a national priority driven by economic competitiveness concerns. There is broad consensus that the United States needs more skilled workers in these fields, and considerable investment has flowed toward STEM curricula, especially in after-school programs and specialized schools. But the STEM push has also raised questions about equity (whether access is evenly distributed), about the marginalization of humanities (which many argue are essential for democratic citizenship), and about whether the pipeline metaphor — filling a funnel with more STEM students — adequately captures what an educated citizenry needs.",
      "Technology has transformed both the promise and the practice of education. The pandemic forced a rapid and uneven shift to online learning, exposing the digital divide between students with reliable internet and devices and those without. Ed-tech products, from learning-management systems to AI tutors, are proliferating, and their impact on learning is only beginning to be understood. The promise of personalized, adaptive learning coexists with concerns about privacy, screen time, and the deepening of inequality if technology is not deployed equitably.",
      "Rural schools face distinctive challenges, including teacher shortages, geographic isolation, limited course offerings, and aging infrastructure. Urban schools face their own pressures, including concentrated poverty, larger bureaucracies, and the effects of segregated housing patterns. Both settings struggle to retain students and families when higher-quality options exist elsewhere. The geography of educational opportunity — the way the quality of schooling is distributed across the American landscape — is itself a form of structural inequality.",
      "International comparisons sharpen the picture. The Programme for International Student Assessment, or PISA, tests fifteen-year-olds across dozens of countries. The United States consistently scores near the OECD average in reading and science and slightly below in mathematics. Yet these averages conceal wide internal variation; American students in affluent suburbs perform among the best in the world, while American students in high-poverty schools perform among the worst. The United States thus combines a world-class educational elite with a persistent lag among disadvantaged students — a pattern that mirrors and reinforces the nation's broader economic inequality.",
      "The purpose of American education is itself a matter of enduring contest. Some emphasize the transmission of academic knowledge and cognitive skills; others, the cultivation of democratic citizenship and moral character; still others, the development of workforce-ready skills and economic productivity; and some, the fostering of individual growth and well-being. These purposes are not mutually exclusive but neither are they easily balanced. The schools a nation builds, and the way it funds, tests, and evaluates them, are expressions of what it believes education is for.",
      "Ultimately, the paradox of American education is a mirror of the American social contract. The system aspires to offer equal opportunity to all while simultaneously reproducing the inequalities children bring with them through the school door. It celebrates individual merit while distributing advantage along lines of wealth and zip code. It is at once the nation's great engine of social mobility and a powerful mechanism of social sorting. The tension between these two faces of American schooling is unlikely to be resolved by any single reform. It will be negotiated in every district, every classroom, and every year — as it has been, quietly and persistently, since the founding of the modern common school.",
    ],
    vocabularyNotes: [
      { term: "paradox", ipa: "/ˈpærədɑːks/", zh: "悖论" },
      { term: "consequential", zh: "重要的；有重大影响的" },
      { term: "stubbornly", zh: "顽固地" },
      { term: "litgated", zh: "被诉诸法律" },
      { term: "resistant", zh: "抵抗的；难改变的" },
      { term: "divisive", ipa: "/dɪˈvaɪsɪv/", zh: "引发分歧的" },
      { term: "recruitment and retention", zh: "招聘与留任" },
      { term: "exempt", zh: "豁免的" },
      { term: "stratification", zh: "分层；等级化" },
      { term: "meritocratic", zh: "精英（凭才能）的" },
      { term: "accumulative advantage", zh: "累积优势" },
      { term: "marginalization", zh: "边缘化" },
      { term: "disparity", zh: "差距；差异" },
      { term: "reproducing", zh: "再生产" },
    ],
    grammarNotes: [
      {
        topicId: "nominalization",
        titleZh: "教育政策文本的名词化",
        noteZh: "the transmission of academic knowledge / the cultivation of citizenship 用名词短语压缩并列目的。",
        exampleFromText: "the cultivation of democratic citizenship and moral character",
      },
      {
        topicId: "hedging-language",
        titleZh: "教育争鸣的模糊限制",
        noteZh: "is often described / appears meritocratic / only partially realized 缓冲对争议话题的绝对判断。",
        exampleFromText: "Community colleges are often described as the gateways to the middle class",
      },
      {
        topicId: "passive-across-tenses",
        titleZh: "制度被动与政策被动",
        noteZh: "has been litigated / was signed / is funded 表现制度客体与被动的政策接受。",
        exampleFromText: "the resulting disparities have been litigated at the state level",
      },
      {
        topicId: "complex-sentences",
        titleZh: "长句表达多重因果",
        noteZh: "Because...As a result / While...句子构建因果与对比，正是议论文所需。",
        exampleFromText: "Because wealthy areas have higher property values, they generate far more revenue per student.",
      },
      {
        topicId: "parallelism-rules",
        titleZh: "平行结构列举目的",
        noteZh: "有些强调……；others 强调……；still others 强调……用并列排比结构。",
        exampleFromText: "...the cultivation of democratic citizenship...; others, the development of workforce-ready skills...",
      },
      {
        topicId: "emphasis-structures-cleft",
        titleZh: "强调结构定位论题",
        noteZh: "What a student... / What the system aspires to 用 what 从句点明主题。",
        exampleFromText: "What a student begins college, and whether they finish, is heavily correlated...",
      },
    ],
    questions: [
      {
        questionEn: "Why is school funding the most consequential feature?",
        questionZh: "为什么学校经费是最重要的特征？",
        options: ["It is federally controlled", "It relies on local property taxes", "It is equalized nationally", "It comes from foreign aid"], answerIndex: 1,
        explainZh: "经费依赖地方财产税，将地区财富与教育质量挂钩。",
      },
      {
        questionEn: "What did the Every Student Succeeds Act of 2015 do?",
        questionZh: "2015 年《每个学生都成功法》做了什么？",
        options: ["Increased federal testing mandates", "Returned authority to states", "Banned standardized tests", "Privatized all schools"], answerIndex: 1,
        explainZh: "它把大量权力交还各州，同时保留测试要求。",
      },
      {
        questionEn: "According to the passage, which factor is most important in student learning?",
        questionZh: "文中认为对学生学习最重要的校内因素是什么？",
        options: ["School building age", "Classroom technology", "Teachers", "Class size only"], answerIndex: 2,
        explainZh: "文中称教师是学生在校学习最重要的因素。",
      },
      {
        questionEn: "How do charter schools differ from traditional public schools?",
        questionZh: "特许学校与传统公立学校有何区别？",
        options: ["They are fully private", "They are publicly funded but independently operated", "They must follow all regulations", "They cannot public enroll students"], answerIndex: 1,
        explainZh: "特许学校由公共资金资助但独立运营，并豁免部分规章。",
      },
      {
        questionEn: "What does the passage say about the placement of American students on PISA?",
        questionZh: "文中如何形容美国学生在 PISA 中的位置？",
        options: ["Top of the world", "Around the OECD average", "Near the bottom", "Not tested"], answerIndex: 1,
        explainZh: "美国平均分接近 OECD 平均水平，但内部差异巨大。",
      },
      {
        questionEn: "What is described as 'the gateways to the middle class'?",
        questionZh: "什么被描述为'通往中产阶级的门户'？",
        options: ["Ivy League universities", "Community colleges", "Vocational schools", "Online universities"], answerIndex: 1,
        explainZh: "社区学院常被描述为中产阶级的门户。",
      },
      {
        questionEn: "The 2023 Supreme Court decision affected what practice?",
        questionZh: "2023 年最高法院裁决影响了什么做法？",
        options: ["School funding", "Consideration of race in admissions", "Standardized testing", "Teacher certification"], answerIndex: 1,
        explainZh: "该裁决推翻了在许多招生中考虑种族的做法。",
      },
      {
        questionEn: "What is a distinctive strength AND weakness of American higher education's diversity?",
        questionZh: "美国高等教育多样性的优点和缺点是什么？",
        options: ["It is both a strength and causes stratification", "It only helps elites", "It has no weaknesses", "It only serves community colleges"], answerIndex: 0,
        explainZh: "多样性提供多种路径，但也产生巨大分层。",
      },
      {
        questionEn: "What did the pandemic particularly expose?",
        questionZh: "疫情特别暴露了什么？",
        options: ["Curriculum wars", "The digital divide", "Teacher shortages only", "Testing failures"], answerIndex: 1,
        explainZh: "疫情暴露了有网无网学生之间的数字鸿沟。",
      },
      {
        questionEn: "The author concludes that American education is a mirror of what?",
        questionZh: "作者总结美国教育是什么的镜像？",
        options: ["The economy only", "The American social contract", "State politics", "Global standards"], answerIndex: 1,
        explainZh: "它既提供社会流动又再生产不平等，是社会的镜像。",
      },
    ],
    summaryTaskZh: "用不超过 90 个英文单词总结：美国 K-12 与高等教育体系的核心悖论是什么？它如何同时促进机会与再生产不平等？",
    opinionTaskZh: "The author argues that standardized testing and market-based reforms are deeply contested. Drawing on the text, argue whether you believe the benefits of standardized testing outweigh its costs in your own education context. Write 150-180 words with one concessive clause.",
  },
];
