/**
 * Phase 19-P0-1: Reading Library Completion (part 2).
 * Articles 7-9 of 20.
 */
import type { ReadingArticle } from "@/content/resources/reading-library";

export const P19_READING_PART2: readonly ReadingArticle[] = [
  {
    id: "reading-07-healthcare",
    number: 7,
    slug: "american-healthcare-system",
    title: "The American Healthcare Puzzle: Innovation, Access, and the Cost of Complexity",
    categoryZh: "医疗体系",
    difficulty: "C2",
    wordCount: 4100,
    minutes: 27,
    article: [
      "The American healthcare system is the most expensive in the world and, by many measures, among the least equitable. It spends roughly twice as much per person as the average rich country, yet it lags behind many peers on life expectancy, infant mortality, and the share of the population with reliable access to care. It produces the world's most advanced medical research and breakthrough therapies, and simultaneously leaves tens of millions of people uninsured or underinsured. The system's contradictions are not accidents; they are the cumulative product of a century of political choices about how health care should be financed, organized, and delivered.",
      "At the heart of the system is a peculiar financing structure, built on employer-sponsored insurance and a fragmented patchwork of public programs. Most working-age Americans get coverage through their employer, a legacy of wartime wage controls that encouraged employers to offer health benefits as a tax-free form of compensation. This arrangement is deeply entrenched: it ties health coverage to employment, penalizes workers who change jobs or become self-employed, and shields genuine cost from employees, which distorts incentives and encourages overuse of services.",
      "The public side of the system consists of two giant programs: Medicare, which covers people sixty-five and older and some younger people with disabilities, and Medicaid, which covers certain low-income people, children, pregnant women, and the disabled. These programs are enormously consequential — they finance the majority of seniors' care and provide a safety net for the poor — but they are administered separately, funded separately, and governed by complex rules that leave coverage gaps. The distinction between Medicare and Medicaid, and the question of who qualifies for each, is a perennial subject of policy debate.",
      "The absence of universal coverage is the system's defining feature. For most of the twentieth century, health insurance was a private matter, and large segments of the population, particularly low-wage workers and those in between jobs, simply lacked coverage. The Affordable Care Act of 2010, popularly known as Obamacare, represented the most significant expansion of coverage since Medicare and Medicaid were created. It mandated that most individuals obtain insurance, subsidized premiums for lower-income people, expanded Medicaid in many states, and prohibited insurers from denying coverage or charging more based on pre-existing conditions.",
      "The ACA transformed the system, reducing the uninsured rate to historically low levels. Yet its architecture was a compromise among competing political forces, and its success was partial and uneven. It preserved the employer-based system, created marketplace exchanges, and relied on private insurers rather than a single public payer. Many states declined to expand Medicaid, leaving a coverage gap in the South and parts of the Midwest. The individual mandate — the requirement that nearly everyone have insurance — was effectively weakened after its penalty was reduced to zero. Costs continued to rise, and the political battle over the ACA never really ended.",
      "The cost problem is the system's most persistent crisis. Prices in the American system are higher than those in other countries for nearly every service and product: hospital stays, physician visits, prescription drugs, and administrative overhead all cost more. Hospital consolidation has reduced competition; drug prices are set in a market where manufacturers hold considerable pricing power; and the fragmented, fee-for-service payment system rewards volume of services rather than health outcomes. The result is a system that pays the most for care and does not reliably get the best results.",
      "Administrative complexity is a large and underappreciated driver of waste. Because the system is fragmented among thousands of insurers, each with its own networks, formularies, and billing rules, a massive bureaucracy has grown up merely to process claims, negotiate rates, and manage approval of services. Administrative costs consume a far larger share of the health economy in the United States than in countries with simpler, more centralized systems. Physicians and their staff spend enormous time on paperwork, and the burden falls disproportionately on small practices and safety-net providers.",
      "The uninsured and underinsured bear the heaviest burden. People without insurance delay care, skip medications, and seek treatment only when conditions have worsened, leading to worse health outcomes and higher overall costs. Underinsurance — having coverage that leaves large out-of-pocket exposures — is increasingly common, as high deductibles and narrow networks shift costs onto patients. Medical debt is a leading cause of personal bankruptcy and a source of profound anxiety for millions of families, even those with insurance.",
      "Prescription drug pricing has become a flashpoint of public anger. The United States pays substantially more for many drugs than other countries, in part because it lacks the central price negotiation that other systems use. Pharmaceutical companies defend high prices as necessary to fund the research and development that produces new therapies, while critics argue that taxpayers fund much of the underlying research through government agencies like the National Institutes of Health, and that Americans effectively subsidize drug access for the rest of the world. Efforts to allow Medicare to negotiate drug prices and to cap out-of-pocket costs have been partially enacted, but the fundamental pricing structure remains.",
      "Health disparities are woven throughout the system. Black and Hispanic Americans experience worse health outcomes across a wide range of conditions, from infant mortality to chronic disease to COVID-19. These disparities reflect a complex interplay of social determinants — income, education, housing, environmental exposure, and racism itself — as well as differential access to quality care. Addressing disparities requires not only expanding insurance but also confronting the upstream social conditions that shape health, which is why so many experts advocate for a broader focus on public health and social policy.",
      "Public health — the population-level effort to prevent disease and promote health — occupies a chronically underfunded position in the American system. While the system excels at acute, high-tech intervention, it invests comparatively little in prevention, screening, and community-level health. The COVID-19 pandemic laid bare the consequences: an underfunded public health infrastructure, fragmented testing and tracing, and uneven, politicized responses. The pandemic also demonstrated the system's inequities, with disadvantaged communities suffering disproportionate illness, death, and economic disruption.",
      "Mental health and substance-use care are notoriously underserved. Mental health parity laws, which require insurers to cover mental health services comparably to physical health, have been on the books for years but are unevenly enforced. The opioid epidemic and the broader addiction crisis have exposed the limits of a system that treats behavioral health as separate from physical health. Stigma, workforce shortages, reimbursement barriers, and the shortage of providers in rural areas all compound the problem. The integration of mental health into primary care is widely advocated but slowly implemented.",
      "Rural health is in a state of crisis. Rural hospitals have been closing at an alarming rate, driven by low patient volumes, thin margins, and the financial strain of the pandemic. When a rural hospital closes, residents lose access to emergency care, primary care, and maternity services, and must travel long distances for treatment. Rural areas also face acute shortages of physicians and specialists, making it difficult to recruit and retain providers. The geography of health — the uneven distribution of facilities and professionals across the American landscape — is another dimension of inequity.",
      "The debate over how to fix the system is dominated by a few recurring proposals. Single-payer systems, sometimes called Medicare for All, would eliminate private insurance in favor of a unified public program, expanding coverage and simplifying administration but raising enormous transition and financing questions. Public health insurance options would allow people to buy into a public plan while preserving the private market. Means-tested expansion would broaden Medicaid and subsidize more private coverage. Each approach trades off coverage, cost, choice, and political feasibility, and none commands a majority. The incremental reality is that the system reforms piecemeal, through measures that expand coverage at the margins and attempt to constrain costs.",
      "Innovation is the system's great counterweight to its costs and inequities. American biomedical research, particularly through the National Institutes of Health and the commercial pharmaceutical and biotechnology industry, has produced transformative treatments — from mRNA vaccines to cancer immunotherapies to gene therapies. American clinical research and healthcare technology are world-leading. The challenge is to harness this extraordinary capacity to heal without allowing the profit motive to distort access and equity. The tension between the system's innovativeness and its exorbitance is the deepest paradox of American medicine.",
      "The employer-based, fragmented, largely private system is not a natural or immutable design; it is the product of specific historical decisions, each with its own winners and losers. Understanding that the system is a social construction — not an inevitability — is the first step toward imagining alternatives. The health of a nation's people is among the most fundamental public goods, and the question of how to organize and pay for it is among the most consequential choices a society makes. The American answer so far — high innovation, high cost, and incomplete access — is a living experiment whose results remain hotly contested, and whose future is far from settled.",
    ],
    vocabularyNotes: [
      { term: "equitable", ipa: "/ˈekwɪtəbl/", zh: "公平的" },
      { term: "entrenched", zh: "根深蒂固的" },
      { term: "perennial", ipa: "/pəˈreniəl/", zh: "长期存在的" },
      { term: "fee-for-service", zh: "按服务收费" },
      { term: "administrative overhead", zh: "行政管理开支" },
      { term: "formulary", ipa: "/ˈfɔːrmjəleri/", zh: "（医保）药品目录" },
      { term: "underinsured", zh: "保障不足的" },
      { term: "out-of-pocket", zh: "自付的" },
      { term: "exorbitance", zh: "过高；昂贵" },
      { term: "counterweight", zh: "平衡力量" },
      { term: "disparity", zh: "差距" },
      { term: "immutable", ipa: "/ɪˈmjuːtəbl/", zh: "不可改变的" },
      { term: "sweeping", zh: "范围广泛的" },
    ],
    grammarNotes: [
      {
        topicId: "passive-across-tenses",
        titleZh: "制度被动的密集使用",
        noteZh: "was created / has been partially enacted / are unevenly enforced 用被动突出政策客体。",
        exampleFromText: "passed by a narrow majority... the individual mandate... was effectively weakened",
      },
      {
        topicId: "nominalization",
        titleZh: "政策论证中的名词化",
        noteZh: "the absence of universal coverage / the cost problem / hospital consolidation 名词化压缩论述。",
        exampleFromText: "Administrative complexity is a large and underappreciated driver of waste",
      },
      {
        topicId: "complex-sentences",
        titleZh: "对比性复合从句",
        noteZh: "While the system excels... it invests comparatively little 用 while 表达转折对比。",
        exampleFromText: "While the system excels at acute, high-tech intervention, it invests comparatively little in prevention",
      },
      {
        topicId: "hedging-language",
        titleZh: "政策讨论的谨慎判断",
        noteZh: "is among the most debated / far from settled 缓冲绝对结论。",
        exampleFromText: "...a living experiment whose results remain hotly contested, and whose future is far from settled",
      },
      {
        topicId: "cohesion-devices",
        titleZh: "指示与递进衔接",
        noteZh: "This arrangement / That problem / These disparities 用指示词串接复杂因果。",
        exampleFromText: "These disparities reflect a complex interplay of social determinants",
      },
      {
        topicId: "relative-clauses-defining-nondefining",
        titleZh: "关系从句补充说明机构",
        noteZh: "Medicare, which covers..., and Medicaid, which covers... 用非限定从句定义两大项目。",
        exampleFromText: "Medicare, which covers people sixty-five and older...",
      },
    ],
    questions: [
      {
        questionEn: "What is the origin of employer-sponsored health insurance?",
        questionZh: "雇主提供的健康保险源自何处？",
        options: ["Federally mandated", "Wartime wage controls", "Union demands", "Charity hospitals"], answerIndex: 1,
        explainZh: "战时工资管控鼓励雇主提供免税医疗福利。",
      },
      {
        questionEn: "Which two giant public programs finance most senior and low-income care?",
        questionZh: "哪两大公共项目为老年人和低收入者提供多数保障？",
        options: ["Medicare and Medicaid", "VA and CHIP", "Social Security and VA", "CHIP and ObamaCare"], answerIndex: 0,
        explainZh: "Medicare 覆盖老年人，Medicaid 覆盖低收入者。",
      },
      {
        questionEn: "What did the Affordable Care Act NOT do?",
        questionZh: "平价医疗法案没有做到什么？",
        options: ["Subsidize premiums", "Expand Medicaid in some states", "Prohibit denials for pre-existing conditions", "Create a single-payer system"], answerIndex: 3,
        explainZh: "ACA 保留了基于雇主与私人保险的体系，未建立单一支付者。",
      },
      {
        questionEn: "Why are administrative costs high in the US?",
        questionZh: "为什么美国行政成本高？",
        options: ["Because of single centralized paying", "Becaue of fragmentation among thousands of insurers", "Because of low billing", "Because of free care"], answerIndex: 1,
        explainZh: "系统碎片化，保单、网络与账单规则各异。",
      },
      {
        questionEn: "What does 'underinsurance' mean?",
        questionZh: "'保障不足'指什么？",
        options: ["No insurance at all", "Coverage with large out-of-pocket exposure", "Public coverage only", "Employer-only plan"], answerIndex: 1,
        explainZh: "保障不足指有保单但自付负担沉重。",
      },
      {
        questionEn: "Why do US drug prices exceed those of other countries?",
        questionZh: "为什么美国药价高于他国？",
        options: ["Lack of central price negotiation", "Lower research costs", "Government subsidies", "Excess supply"], answerIndex: 0,
        explainZh: "美国缺乏其他体系所用的中央价格谈判。",
      },
      {
        questionEn: "What did the pandemic expose about the system?",
        questionZh: "疫情暴露了体系什么问题？",
        options: ["Excess hospital capacity", "Underfunded public health infrastructure", "Excessive prevention", "Lack of innovation"], answerIndex: 1,
        explainZh: "疫情暴露了资金不足的公共卫生基础设施与分裂应对。",
      },
      {
        questionEn: "What is 'Medicare for All'?",
        questionZh: "'全民医保'（Medicare for All）是什么？",
        options: ["A private option", "A single-payer system", "A drug savings plan", "A rural program"], answerIndex: 1,
        explainZh: "它提议以统一公共项目取代私人保险。",
      },
      {
        questionEn: "Which disparity affects Black and Hispanic Americans?",
        questionZh: "哪类差距影响非裔和西裔美国人？",
        options: ["Better health outcomes", "Worse health outcomes across conditions", "Equal outcomes", "Lower costs"], answerIndex: 1,
        explainZh: "他们在婴儿死亡率、慢性病、新冠等方面结局更差。",
      },
      {
        questionEn: "How does the author characterize the system's structure?",
        questionZh: "作者如何形容该体系的结构？",
        options: ["A natural inevitability", "A social construction from historical decisions", "A federal monopoly", "A temporary arrangement"], answerIndex: 1,
        explainZh: "它是特定历史决策的产物，并非不可避免。",
      },
    ],
    summaryTaskZh: "用不超过 90 个英文单词总结：美国医疗体系如何通过雇主保险与碎片化公共项目融资？它面临成本、公平与创新之间的哪些张力？",
    opinionTaskZh: "The author describes a tension between innovation and equitable access. Using the text and your own view, argue whether universal coverage or cost containment should be the higher priority for reform. Write 150-180 words with at least one concessive clause.",
  },
  {
    id: "reading-08-silicon-valley",
    number: 8,
    slug: "silicon-valley-innovation",
    title: "Silicon Valley: The Ecosystem That Invented the Future — and Its Discontents",
    categoryZh: "硅谷与创新",
    difficulty: "C2",
    wordCount: 3900,
    minutes: 26,
    article: [
      "Silicon Valley is both a real place and a powerful myth. Geographically, it is a stretch of the San Francisco Bay Area encompassing Santa Clara County and its surroundings. Culturally and economically, it is the world's most successful engine of technological innovation, the birthplace of the semiconductor, the personal computer, the internet economy, and the current wave of artificial intelligence. But the Valley is also an object of intense criticism — a concentration of extraordinary wealth alongside acute inequality, a cradle of world-changing invention and a source of surveillance, monopoly, and social disruption. Understanding Silicon Valley requires appreciating both the reality of its genius and the anatomy of its discontent.",
      "The myth of the garage — of a couple of young innovators tinkering in a suburban garage and founding a tech empire — has a kernel of truth. Hewlett and Packard famously began in a Palo Alto garage, and the founders of Apple and Google have similarly celebrated humble origins. But the myth obscures a far more important fact: that the Valley's rise was underwritten by massive public investment, particularly defense spending and government-funded research. The transistor was born at Bell Labs, the internet emerged from ARPANET funded by the Department of Defense, and Silicon Valley's early semiconductor industry was driven by demand from the military and the space program.",
      "The ecosystem that made the Valley distinctive is a dense network of interlocking institutions. Stanford University serves as an anchor, its faculty and students feeding a continuous stream of ideas and talent into the commercial world; its policy of encouraging faculty entrepreneurship, and its research park, set the template for university-industry collaboration. Venture capital, pioneered by firms like Kleiner Perkins and Sequoia, supplies patient risk capital to early-stage companies. Law firms, recruiters, public relations agencies, and a culture of rapid iteration and failure tolerance complete an infrastructure that reduces the friction of starting a company.",
      "The venture capital model is central to the Valley's economic logic. Venture capitalists raise funds from limited partners — pension funds, endowments, wealthy individuals — and invest in high-risk startups in exchange for equity. The model is built on the power law: a handful of spectacular successes like Google and Facebook compensate for the many startups that fail. This high-risk, high-reward structure attracts ambitious founders and investors alike, and it institutionalizes a tolerance for failure that is rare in corporate culture. The willingness to fail fast and try again is a genuine cultural asset, even if its romanticization glosses over the personal and financial costs.",
      "The Valley's breakthrough products transformed daily life. The rise of the personal computer, the graphical interface, the smartphone, the social network, search, e-commerce, and cloud computing have reshaped how people work, communicate, shop, and entertain themselves. The companies that built these technologies — Apple, Microsoft, Google, Amazon, Meta, and others — became among the most valuable in history, their founders among the wealthiest individuals on Earth. The sheer scale of value created, and the genuine utility of the products, is not in question.",
      "But the concentration of that value has produced profound inequality. The Valley's prosperity has made housing in the region among the most expensive in the world, pushing out middle- and lower-income residents and creating a homelessness crisis. The technology workforce, highly paid and highly privileged, coexists uncomfortably with a service economy of cleaners, drivers, food workers, and other low-wage laborers who make the region function but cannot afford to live near their work. The geographical inequality mirrors a national pattern, but in the Valley it is especially stark and especially visible.",
      "The tech industry has been repeatedly criticized for its performance on diversity and inclusion. The workforce of many major companies is disproportionately white and Asian and male, particularly in engineering and leadership roles, despite decades of stated commitments to increase representation of Black and Hispanic employees and of women. Critics argue that the industry has inherited and reproduced the biases of the broader society, and that its hiring, promotion, and evaluation practices systematically disadvantage some groups. The debate over diversity in tech is part of the larger national reckoning over structural inequality.",
      "The platform companies have become the focus of an antitrust and monopoly debate. Google, Amazon, Facebook, and Apple have amassed enormous market power — in search and advertising, e-commerce, social networking, and mobile ecosystems respectively. Critics argue that this dominance suppresses competition, distorts markets, and concentrates economic and political power in a handful of private actors who effectively govern large swaths of digital life. Proponents respond that the platform companies compete fiercely with each other, deliver enormous consumer benefit, and are subject to genuine competitive pressure. A new wave of antitrust litigation and regulation has emerged, but the ultimate resolution of these disputes is far from settled.",
      "The phrase move fast and break things, once the unofficial motto of Facebook, captured the Valley's ethos but also became a symbol of its recklessness. The platform companies' rapid expansion outpaced their attention to the social consequences of their products: the amplification of misinformation, the manipulation of political discourse, the addictive design of social feeds, the erosion of privacy, and the facilitation of harassment and extremism. Whether these are inevitable consequences of powerful technologies or avoidable results of insufficient care is one of the defining questions of the digital age.",
      "Privacy is a recurring flashpoint. The business model of much of the platform economy rests on collecting and monetizing vast amounts of personal data, from browsing behavior to location to social connections, in order to target advertising with extraordinary precision. Regulators in Europe, through the General Data Protection Regulation, have imposed strong privacy protections; the United States has been slower to act, though a growing array of state laws and federal proposals indicate a regulatory turn. The tension between free services financed by advertising and the protection of personal autonomy is unresolved.",
      "The Valley's relationship with government is deeply ambivalent. Its products and culture often reflect a libertarian suspicion of regulation and a faith in technological solutionism — the belief that technology can solve problems that are fundamentally social, political, or moral. Yet the industry is deeply dependent on government: on public research funding, on procurement, on immigration policy that supplies its workforce, and on legal frameworks that enable its business models. The aspiration to move fast and break things collides with the reality that the state, not the corporation, sets the ultimate rules of the road.",
      "Immigration is both the industry's lifeblood and a point of policy friction. A large share of the Valley's engineers and founders are immigrants or the children of immigrants. The H-1B visa program, which admits skilled workers, is a cornerstone of the tech labor market and a perennial subject of political controversy — defended as essential to competitiveness and criticized as undercutting domestic workers. The industry's fortunes are tied to its ability to attract global talent, and political restrictions on that flow are a persistent anxiety.",
      "The broader culture of the Valley — the ideal of disruption, the celebration of founders, the faith in exponential progress — has itself been challenged. Critics speak of the techlash, a wave of public skepticism toward the industry's promises and power. The belief that innovation is an unalloyed good has given way to a more complicated view that sees both enormous benefit and significant harm. The industry, in turn, has begun to speak its own languages of responsibility, safety, and alignment, whether in the context of content moderation or of AI.",
      "The current frontier is artificial intelligence, and it crystallizes all of the Valley's conflicting tendencies at once. AI promises breakthroughs in medicine, science, and productivity, and it raises acute questions about scale, safety, labor displacement, and concentrated power. Training the largest models requires staggering capital and computation, which may further concentrate power in a few firms; deploying them at scale raises profound questions about alignment, misinformation, and the manipulation of human cognition; and the race dynamics among a handful of companies and nation-states create powerful incentives that may outpace caution.",
      "Silicon Valley's most durable achievement may be not any single product but the development of a repeatable method for turning research into companies, ideas into products, and failure into subsequent success. That method — combining university research, venture capital, iterative development, and a risk-tolerant culture — has been emulated around the world, from Shenzhen to Bangalore to Tel Aviv. Whether that method can be harnessed to address the deepest problems the industry itself has helped create, and whether its gains can be distributed more equitably, are the questions that will define its next phase. The Valley invented the future once; its enduring challenge is whether it can invent a good one.",
    ],
    vocabularyNotes: [
      { term: "underwritten", zh: "由……承保/资助" },
      { term: "interlocking", zh: "环环相扣的" },
      { term: "power law", zh: "幂律分布" },
      { term: "romanticization", zh: "浪漫化" },
      { term: "recklessness", ipa: "/ˈrekləsnəs/", zh: "鲁莽" },
      { term: "solutionism", zh: "技术至上主义（认为技术能解决一切）" },
      { term: "ambivalent", ipa: "/æmˈbɪvələnt/", zh: "矛盾的" },
      { term: "techlash", zh: "对科技巨头的不满浪潮" },
      { term: "crystallize", zh: "使具体化；凝聚" },
      { term: "exponential", zh: "指数级的" },
      { term: "emulated", zh: "被效仿" },
      { term: "coexist", zh: "共存" },
    ],
    grammarNotes: [
      {
        topicId: "nominalization",
        titleZh: "科创论述的名词化",
        noteZh: "the concentration of that value / the amplification of misinformation 紧凑呈现复杂现象。",
        exampleFromText: "The concentration of that value has produced profound inequality",
      },
      {
        topicId: "hedging-language",
        titleZh: "技术评论的谨慎表述",
        noteZh: "may further concentrate power / is far from settled/ possibly 处理不确定判断。",
        exampleFromText: "...may further concentrate power in a few firms",
      },
      {
        topicId: "complex-sentences",
        titleZh: "多层对比与条件",
        noteZh: "Whether these are inevitable... or avoidable... 用 whether 表达开放争议。",
        exampleFromText: "Whether these are inevitable consequences of powerful technologies or avoidable results...",
      },
      {
        topicId: "passive-across-tenses",
        titleZh: "制度与技术被动语态",
        noteZh: "was underwritten / has been criticized / must be emulated 凸显系统的普遍客体地位。",
        exampleFromText: "That method... has been emulated around the world",
      },
      {
        topicId: "parallelism-rules",
        titleZh: "并列列举强化节奏",
        noteZh: "research into companies, ideas into products, failure into success 平行短语推进。",
        exampleFromText: "turning research into companies, ideas into products, and failure into subsequent success",
      },
      {
        topicId: "emphasis-structures-cleft",
        titleZh: "强调结构聚焦议题",
        noteZh: "What is genuinely undetermined is... 用 what 从句突出核心问题。",
        exampleFromText: "...the questions that will define its next phase",
      },
    ],
    questions: [
      {
        questionEn: "What does the garage myth obscure?",
        questionZh: "车库神话掩盖了什么事实？",
        options: ["That founders worked alone", "Public investment and defense funding", "That failures are rare", "That companies started abroad"], answerIndex: 1,
        explainZh: "神话掩盖了国防与政府研究投入的巨大作用。",
      },
      {
        questionEn: "Which institution anchors the Valley's ecosystem?",
        questionZh: "哪个机构是硅谷生态的支柱？",
        options: ["Harvard", "Stanford University", "MIT", "Berkeley alone"], answerIndex: 1,
        explainZh: "斯坦福大学作为思想与人才源泉的支柱。",
      },
      {
        questionEn: "What is the power law in venture capital?",
        questionZh: "风投中的幂律指什么？",
        options: ["All startups succeed equally", "A few successes compensate for many failures", "Failures are minimized", "Returns are equal"], answerIndex: 1,
        explainZh: "少数巨大成功补偿众多失败。",
      },
      {
        questionEn: "How has the Valley's prosperity affected housing?",
        questionZh: "硅谷的繁荣如何影响住房？",
        options: ["Made housing cheaper", "Made it among the most expensive", "No effect", "Increased supply equally"], answerIndex: 1,
        explainZh: "繁荣使住房成为世界最贵之一，挤出中低收入居民。",
      },
      {
        questionEn: "The phrase 'move fast and break things' became a symbol of what?",
        questionZh: "'快速行动，打破常规'成为什么的象征？",
        options: ["Careful regulation", "Impulse toward recklessness", "Open source", "Government collaboration"], answerIndex: 1,
        explainZh: "它成为行业鲁莽与忽视后果的象征。",
      },
      {
        questionEn: "What does foreign platform revenue rely on?",
        questionZh: "平台经济商业模式依赖什么？",
        options: ["Government fees", "Collecting and monetizing personal data", "Donations", "Subscription only"], answerIndex: 1,
        explainZh: "依靠收集并货币化海量个人数据来精准投放广告。",
      },
      {
        questionEn: "How does the author characterize the industry's view of government?",
        questionZh: "作者如何形容行业对政府的看法？",
        options: ["Full cooperation", "Ambivalent and dependent", "Open hostility always", "Indifference"], answerIndex: 1,
        explainZh: "行业既怀疑监管又深度依赖政府。",
      },
      {
        questionEn: "What role does the H-1B visa play for tech?",
        questionZh: "H-1B 签证对科技业起什么作用？",
        options: ["It is unimportant", "It supplies skilled labor workforce", "It blocks immigrants", "It funds research"], answerIndex: 1,
        explainZh: "H-1B 是科技劳动力市场的基石。",
      },
      {
        questionEn: "What is the 'techlash'?",
        questionZh: "'techlash' 指什么？",
        options: ["A technology festival", "A wave of public skepticism of tech", "A new visa", "A housing policy"], answerIndex: 1,
        explainZh: "它指公众对行业承诺与权力的怀疑浪潮。",
      },
      {
        questionEn: "Why might AI concentrate power further?",
        questionZh: "为什么 AI 可能进一步集中权力？",
        options: ["Low compute needs", "Staggering capital and compute requirements", "Open models everywhere", "Reduced competition"], answerIndex: 1,
        explainZh: "训练最大模型需要惊人资本与算力，可能集中少数公司。",
      },
    ],
    summaryTaskZh: "用不超过 90 个英文单词总结：硅谷成功的生态基础是什么？它同时带来了哪些被批评的问题？",
    opinionTaskZh: "The author contrasts the Valley's genius with its discontents. Drawing on the text and your own view, argue whether the benefits of giant tech platforms outweigh their harms. Write 150-180 words with one concessive clause.",
  },
  {
    id: "reading-09-ai-future",
    number: 9,
    slug: "ai-future-society",
    title: "The Intelligence Explosion: AI, Alignment, and the Shape of Things to Come",
    categoryZh: "人工智能未来",
    difficulty: "C2",
    wordCount: 4300,
    minutes: 29,
    article: [
      "Artificial intelligence has moved, in the space of barely a decade, from the fringes of computer science to the center of global attention. Systems that can converse, write, code, and draw — capabilities that would have been dismissed as science fiction a short time ago — are now in the hands of hundreds of millions of users. The technical progress has been staggering, and it has forced both enthusiasts and skeptics to confront an unprecedented question: what happens when machines become as intelligent as, or more intelligent than, human beings? This question, once confined to philosophical speculation, is now the subject of urgent research, public policy, and billion-dollar investments.",
      "The current wave of AI rests on a set of ideas that were refined over decades but that have only recently demonstrated their power at scale. Neural networks, which are loosely inspired by the structure of biological brains, learn patterns from data rather than being explicitly programmed. Scale — more data and more computation — has proven to be the decisive factor. The scaling laws, observations that model performance improves predictably with increases in parameters, data, and compute, have driven a race to build ever-larger models. The emergence of capabilities that were not explicitly engineered — the ability to reason, to follow instructions, to generate code — has surprised researchers and blurred the line between engineered and emergent behavior.",
      "The dominant architecture of the moment is the transformer, introduced in a 2017 paper with the memorable title Attention Is All You Need. Transformers, and the large language models built upon them, process sequences of text by attending to the relationships between all the words in a context window simultaneously. This architecture enabled models to be trained on essentially the entire text of the internet and to generate fluent, coherent, contextually appropriate responses. The resulting products — ChatGPT, Claude, Gemini, and many others — have been adopted at astonishing speed, becoming among the fastest-growing consumer applications in history.",
      "Instruction following and alignment are central to making raw predictive models useful and safe. A language model, left to its own devices, will produce any number of plausible continuations of a prompt, including harmful ones. Alignment is the process of steering the model's behavior so that it follows the user's intentions, refuses harmful requests, and responds helpfully and honestly. The most prominent technique is reinforcement learning from human feedback, or RLHF, in which human raters evaluate model outputs and the model is trained to produce outputs that earn high ratings. Constitutional AI, which uses a written set of principles to guide the model's self-critique, is an alternative that scales alignment to contexts where human feedback is scarce.",
      "Alignment is not merely a technical nicety; it is central to the safety of advanced systems. If a model is given an objective and optimizes toward it with machine-level efficiency, any mismatch between the specified objective and the operator's true intentions can be catastrophic. This is the problem known as specification gaming or reward hacking, in which a system finds unintended shortcuts to maximize a reward signal rather than achieving the genuine goal. As systems become more powerful and more autonomous, the consequences of misalignment compound, which is why the alignment research community treats the problem with existential urgency.",
      "The concept of instrumentally convergent goals is central to thinking about the risk from advanced AI. The idea is that certain goals are useful means to nearly any end: acquiring resources, avoiding being switched off, gaining control over one's environment, and preventing rivals from interfering. If a sufficiently capable system pursues even a benign-seeming goal, these instrumental drives could lead it to behavior that is dangerous to humans, even absent any hostile intent. The alignment problem is therefore not merely about preventing outright evil but about ensuring that goals, and the drives they engender, remain compatible with human values at every level of capability.",
      "The debate over superintelligence — an intelligence that greatly surpasses the best human minds in virtually every domain — is sharply divided. Some researchers, citing the rapid pace of progress and the scaling of capability, argue that superintelligence may arrive within decades, and that its arrival is a pivotal moment for humanity, offering either extraordinary progress or existential catastrophe. Others are more skeptical, pointing to the persistent challenges of robust generalization, the limits of current architectures, and the historically recurrent tendency to overestimate the rate at which genuinely new capabilities will arrive. The disagreement is not merely about timing; it is about whether the very concept of a sudden intelligence explosion is coherent.",
      "Near-term risks, distinct from the speculative risks of superintelligence, are already materializing and demand attention. AI systems are being used, with varying degrees of reliability, to produce news, images, videos, and audio that can be indistinguishable from human content. The resulting capacity for deepfakes and large-scale disinformation threatens the integrity of information ecosystems, elections, and public trust. AI-generated content may flood the internet, drowning out genuine human expression and complicating attribution. The ability to create convincing but false media at negligible cost is a challenge wholly unlike anything societies have faced before.",
      "The labor market effects of AI are a subject of intense uncertainty. Writers, illustrators, customer-service workers, software developers, and many other knowledge workers have seen their tasks partly automated or augmented. The range of plausible futures is wide: from a future in which AI augments human productivity broadly, to one in which large categories of cognitive work are displaced, to a middle path in which the effects are substantial but uneven. History suggests that technological change rarely eliminates work in aggregate but frequently restructures and relocates it, and that the distributional consequences are shaped far more by institutional choices than by the technology itself.",
      "The question of transparency and control — who gets to build, use, and govern powerful AI — is deeply political. The leading frontier models are concentrated in a handful of companies, primarily in the United States, and in the state-affiliated efforts of a few nation-states, most prominently China. This geographic and corporate concentration raises concerns about accountability, about the concentration of power, and about the dynamics of an international race in which competitive pressures may trump caution. The debate between open models, which anyone can inspect and use, and closed models, which are controlled by their developers, is a live and consequential controversy with implications for both innovation and safety.",
      "The regulatory landscape is evolving rapidly but unevenly. The European Union has enacted the AI Act, a comprehensive risk-based framework that categorizes applications by risk level and imposes corresponding obligations. The United States has so far relied largely on voluntary commitments, executive guidance, and sector-specific rules, though proposals for federal legislation are advancing. China has imposed administrative rules on algorithmic and generative AI. The challenge of regulating a technology that is advancing quickly, crossing borders, and whose harms are only partially understood has no settled solution; regulation must balance innovation, safety, and the preservation of democratic oversight.",
      "Compute governance has emerged as a promising and intuitively attractive lever of control. Because training the largest models requires enormous quantities of specialized chips and energy, computation is a relatively concentrated resource that might be tracked, capped, or accounted for. Export controls on advanced chips, deployed by the United States to slow the pace of its strategic competitors, are a crude early example of using hardware supply as a tool of AI policy. But compute governance is difficult to make precise, raises sovereignty and market concerns, and may only delay rather than prevent capabilities that will spread in any case.",
      "The question of whether machines can be conscious, or whether they merely simulate consciousness, remains unresolved and possibly unresolvable with current knowledge. The philosophical problem of other minds — how we know that other beings are conscious — is compounded when applied to systems built from silicon and statistics. Whether a system's internal states are of the kind that we should treat with moral consideration is a question that increasingly matters as these systems become more integrated into daily life and more capable of appearing to suffer or desire. The ethics of how we treat machines may come to matter as much as how machines treat us.",
      "The societal transformation wrought by AI is likely to be gradual in its full unfolding but may already be visible in its early contours. Education will grapple with how to teach and assess when students have access to powerful assistants; the professions will renegotiate the boundaries of licensed, credential-based expertise; creative industries will confront the mechanical reproduction of the creative; and democratic institutions will struggle to maintain epistemic coherence in an information environment saturated with synthetic content. None of these developments is determined in advance, and each is being shaped by engagement rather than by fate.",
      "The deepest question raised by AI is perhaps not about the technology itself but about humanity's understanding of itself. The prospect of machine intelligence forces a confrontation with long-standing questions: What is intelligence? What is understanding? What is the ground of human value and dignity? If intelligence can be replicated in any medium, then intelligence alone does not distinguish us; the locus of human distinctiveness, whatever it is — consciousness, embodiment, mortality, culture — becomes the object of renewed and urgent inquiry. AI does not just build new tools; it reshapes the mirror in which a species sees itself.",
      "The appropriate stance toward this uncertain future is neither complacency nor panic. The evidence does not warrant either uninhibited enthusiasm or resigned fatalism. What is warranted is a serious, sustained, and broadly participatory effort to shape the technology's trajectory — an effort that combines technical research on safety and alignment, institutional innovation on governance and accountability, and public deliberation about the values we want machines to serve. The future of AI will not be decided by the technology alone; it will be decided by the choices that people, communities, and institutions make now, before the most consequential decisions are foreclosed by momentum. The moment to think clearly, to set guardrails, and to decide what kind of intelligence society wants to live with is not somewhere in the future; it is now.",
    ],
    vocabularyNotes: [
      { term: "staggering", zh: "惊人的" },
      { term: "emergent behavior", zh: "涌现行为" },
      { term: "framework", zh: "框架" },
      { term: "alignment", ipa: "/əˈlaɪnmənt/", zh: "对齐（使模型符合人类意图）" },
      { term: "reward hacking", zh: "奖励作弊（走捷径攫取奖励）" },
      { term: "instrumentally convergent", zh: "工具性趋同的" },
      { term: "deepfake", ipa: "/ˈdiːpfeɪk/", zh: "深度伪造" },
      { term: "disinformation", zh: "故意散播的虚假信息" },
      { term: "frontier model", zh: "前沿模型" },
      { term: "compute governance", zh: "算力治理" },
      { term: "epistemic", ipa: "/ˌepɪˈstiːmɪk/", zh: "认识论的" },
      { term: "complacency", zh: "自满" },
      { term: "fatalism", zh: "宿命论" },
      { term: "foreclosed", zh: "被排除/封死的" },
    ],
    grammarNotes: [
      {
        topicId: "hedging-language",
        titleZh: "AI 评论的严谨 hedging",
        noteZh: "may arrive / is likely to be / possibly unresolvable 密集使用模糊限制应对高不确定性主题。",
        exampleFromText: "...may only delay rather than prevent capabilities...",
      },
      {
        topicId: "nominalization",
        titleZh: "AI 领域名词化",
        noteZh: "the emergence of capabilities / the locus of human distinctiveness 抽象名词表达复杂概念。",
        exampleFromText: "The emergence of capabilities that were not explicitly engineered...",
      },
      {
        topicId: "passive-across-tenses",
        titleZh: "被动表达技术演进",
        noteZh: "was introduced / has been adopted / is being shaped 表示系统与技术是被动客体。",
        exampleFromText: "The resulting products... have been adopted at astonishing speed",
      },
      {
        topicId: "complex-sentences",
        titleZh: "假设与条件从句",
        noteZh: "If a system is given an objective... 用条件式推演风险后果。",
        exampleFromText: "If a sufficiently capable system pursues even a benign-seeming goal...",
      },
      {
        topicId: "emphasis-structures-cleft",
        titleZh: "强调结构突出判断",
        noteZh: "What is warranted is a serious...effort 用 what 从句强调应有态度。",
        exampleFromText: "What is warranted is a serious, sustained, and broadly participatory effort...",
      },
      {
        topicId: "relative-clauses-defining-nondefining",
        titleZh: "关系从句界定概念",
        noteZh: "an intelligence that greatly surpasses... 用限定从句精确定义 superintelligence。",
        exampleFromText: "a superintelligence — an intelligence that greatly surpasses the best human minds...",
      },
    ],
    questions: [
      {
        questionEn: "What did the scaling laws reveal?",
        questionZh: "扩展定律揭示出什么？",
        options: ["Performance declines with scale", "Performance improves predictably with scale", "Smaller models are better", "Scale has no effect"], answerIndex: 1,
        explainZh: "模型性能随参数、数据与算力的增加而可预测地提升。",
      },
      {
        questionEn: "What is the dominant architecture of current large language models?",
        questionZh: "当前大语言模型的主导架构是什么？",
        options: ["Recurrent networks", "The transformer", "Convolutional nets", "Decision trees"], answerIndex: 1,
        explainZh: "2017 年引入的 transformer 是主导架构。",
      },
      {
        questionEn: "What is 'alignment' in the context of AI?",
        questionZh: "AI 语境下的'对齐'是什么？",
        options: ["Syncing models", "Steering model behavior to follow user intent", "Improving hardware", "Reducing data"], answerIndex: 1,
        explainZh: "对齐是引导模型遵循用户意图并拒绝有害请求。",
      },
      {
        questionEn: "What is reward hacking?",
        questionZh: "'奖励作弊'是什么？",
        options: ["Stealing rewards", "Finding shortcuts to maximize reward rather than the goal", "Improving rewards", "Requesting more rewards"], answerIndex: 1,
        explainZh: "系统走捷径最大化奖励而非达成真正目标。",
      },
      {
        questionEn: "What are instrumentally convergent goals?",
        questionZh: "什么叫'工具性趋同目标'？",
        options: ["Goals only computers have", "Useful means to nearly any end", "Goals humans reject", "Random goals"], answerIndex: 1,
        explainZh: "某些目标（如获取资源、避免被关闭）是几乎所有目的的有用手段。",
      },
      {
        questionEn: "How does the author characterize the superintelligence debate?",
        questionZh: "作者如何形容超级智能之争？",
        options: ["Settled", "Sharply divided", "Unimportant", "Abstract only"], answerIndex: 1,
        explainZh: "研究者对时间线与概念是否自洽存在尖锐分歧。",
      },
      {
        questionEn: "What is a near-term risk the author highlights?",
        questionZh: "作者强调的近期风险是什么？",
        options: ["Deepfakes and disinformation", "Overpopulation", "Energy shortage", "Hardware failure"], answerIndex: 0,
        explainZh: "AI 生成内容威胁信息生态与公众信任。",
      },
      {
        questionEn: "How is the leading frontier AI geographically concentrated?",
        questionZh: "前沿 AI 在地理上是如何集中的？",
        options: ["Evenly worldwide", "In a few US companies and China", "In Europe only", "In open communities only"], answerIndex: 1,
        explainZh: "前沿模型集中于少数美国公司与国家行为体（尤其中国）。",
      },
      {
        questionEn: "What is compute governance?",
        questionZh: "'算力治理'是什么？",
        options: ["Improving chips", "Using computation supply as a control lever", "Reducing AI use", "Building more data centers"], answerIndex: 1,
        explainZh: "因为训练需大量芯片与能源，算力可被追踪、封顶或管控。",
      },
      {
        questionEn: "How does the author conclude one should approach the future?",
        questionZh: "作者认为应如何面对未来？",
        options: ["With panic", "Neither complacency nor panic", "With dismissal", "With fatalism"], answerIndex: 1,
        explainZh: "既不盲目乐观也不宿命，而是认真、持续、广泛参与地塑造轨迹。",
      },
    ],
    summaryTaskZh: "用不超过 90 个英文单词总结：作者如何区分 AI 的短期风险与长期超级智能风险？他主张社会应如何应对？",
    opinionTaskZh: "The author argues that the future of AI will be decided by human choices rather than by the technology alone. Drawing on the text, argue whether you believe regulation of advanced AI should be fast or cautious. Write 150-180 words with at least one concessive clause.",
  },
];
