/**
 * Phase 19-P0-1: Reading Library Completion (part 5).
 * Articles 16-18 of 20.
 */
import type { ReadingArticle } from "@/content/resources/reading-library";

export const P19_READING_PART5: readonly ReadingArticle[] = [
  {
    id: "reading-16-media-literacy",
    number: 16,
    slug: "media-information-literacy",
    title: "Skepticism in the Age of Noise: Media and Information Literacy",
    categoryZh: "媒介与信息素养",
    difficulty: "C2",
    wordCount: 3900,
    minutes: 26,
    article: [
      "We live, by any historical measure, in an age of unprecedented information abundance. The average person now has access, through a screen in their pocket, to more data than any library in history once held — news from every corner of the world, the accumulated knowledge of centuries, and the real-time expression of billions of other people. Yet this abundance has not produced a corresponding clarity. On the contrary, the same technology that connects us to the world also delivers misinformation, propaganda, and manipulation at scale, and the capacity to distinguish the true from the false, the reliable from the spurious, has become one of the most essential and most difficult skills of modern life. This capacity is called media and information literacy, and its cultivation is a defining challenge of the digital age.",
      "The nature of information problems has changed dramatically with the technology. In an earlier media era, the limitation was scarcity: relatively few outlets controlled the production of news, and the challenge was one of access and of the bias that inevitably accompanied concentrated control. The digital revolution eliminated scarcity at a stroke, but it created new pathologies. Anyone can now publish anything, to a global audience, at essentially no cost and with essentially no accountability. The barriers to entry that once constrained falsehood have fallen, and the result is an information environment in which false and misleading content competes on equal terms, and often more effectively, with the true.",
      "The concept of misinformation — false or inaccurate information spread without deliberate intent to deceive — is central to understanding the problem. Much of what circulates is simply wrong: rumors, half-truths, and errors that travel quickly through the network of distribution. Distinct from this is disinformation, which is false information created and spread deliberately, with the intent to deceive or to cause harm. The distinction matters because the remedies differ: correcting simple error requires better fact-checking and education, while countering deliberate disinformation requires recognizing its origins, its motives, and its techniques. Both forms coexist and often reinforce each other, and both are amplified by the mechanics of the platforms on which they circulate.",
      "The psychology of belief makes us vulnerable to false information in ways that are now well documented. The confirmation bias leads people to accept information that confirms their existing beliefs and to discount information that challenges them; the illusion of explanatory depth makes people overestimate how well they understand complex issues; and the mere-exposure effect means that repetition alone increases believability. These tendencies, hard-wired into human cognition, are exploited by the design of engagement-optimized platforms, which amplify content that provokes emotion, outrage, and confirmation. The result is an environment in which the most viral content is often the most misleading, and in which human cognitive vulnerabilities are systematically exploited for attention, profit, and influence.",
      "The economics of attention are at the heart of the crisis. The dominant business model of much of the digital world rests on capturing and monetizing attention through advertising. Platforms are engineered to maximize engagement, and content that is emotionally charged, surprising, or divisive tends to generate the most engagement. Algorithms, optimized for this objective, amplify such content without regard to its truth. Misinformation is, in a real sense, a business: it earns attention, and attention earns money. Understanding the incentives that drive the spread of false content is essential to addressing it, because the problem is not merely one of bad actors but of a structural alignment between falsehood and profit.",
      "Echo chambers and filter bubbles compound the problem. Algorithms that feed people content similar to what they have engaged with before can create self-reinforcing loops, in which users are exposed mainly to views they already hold and are insulated from contradicting information. The term echo chamber describes the social phenomenon in which people's networks are dominated by like-minded others; the filter bubble describes the algorithmic phenomenon in which feeds exclude disconfirming content. Both reduce the diversity of information to which people are exposed, and both make people more susceptible to within-group misinformation and more resistant to correction from outside. The debate over how much the algorithms create these effects, and how much people seek them out, is ongoing, but the consequence is clear: a more fragmented and more manipulable public.",
      "Misinformation has real-world consequences that extend far beyond the digital realm. It has been implicated in public-health disasters, as false claims about vaccines and treatments undermined effective responses to disease. It has fueled political polarization and undermined trust in democratic institutions and elections. It has incited violence, promoted fraud, and spread harmful prejudice. The stakes of information integrity are therefore not merely epistemic — a matter of having true beliefs — but practical, because beliefs guide action and action shapes the lives of individuals and communities. When large numbers of people act on false information, the results can be catastrophic.",
      "The response to the crisis has taken many forms, each with its own promise and its own difficulties. Fact-checking — the systematic verification of claims by dedicated organizations — has grown into a substantial industry and provides an important corrective, though it struggles to match the scale and speed of misinformation and to reach those who most need it. Media literacy education aims to equip people with the critical skills to evaluate sources, detect manipulation, and understand the mechanics of the media; it is widely advocated but unevenly implemented, and its effects are difficult to measure. Platform regulation seeks to hold the technology companies accountable for the content they amplify, but it raises hard questions of censorship, free speech, and the proper role of private platforms in governing public discourse.",
      "The role of the technology platforms is uniquely fraught. On the one hand, they are private companies that have created enormously valuable products and that enjoy broad legal protection from liability for user content; on the other, they have become the de facto public squares of the modern world, where a very large share of public discourse occurs. The governments of the world have struggled to balance accountability with the protection of free expression, and the platforms themselves have vacillated between minimal intervention and aggressive content moderation. There is no settled answer to the question of how to govern the speech that happens on private platforms, and the contending positions reflect deep divisions about the meaning of free speech, the dangers of censorship, and the proper limits of corporate and state power.",
      "The question of trust in institutions is inseparable from the problem of misinformation. A public that trusts its institutions — journalism, science, government, medicine — is better able to distinguish reliable from unreliable information, because it knows whose claims to credit and whose to doubt. But that trust has diminished, and the decline feeds a vicious circle: diminished trust makes people more susceptible to alternative and false sources, and the proliferation of false content further erodes trust in credible sources. Restoring the credibility of reliable institutions is therefore a central, if difficult, element of any response, and it depends as much on the behavior of those institutions as on the education of the public.",
      "The evolution of the technology continues to outpace the response. The rise of generative artificial intelligence, capable of producing text, images, audio, and video that are increasingly difficult to distinguish from genuine content, threatens to make the problem dramatically worse. The capacity to fabricate convincing media at scale — deepfakes, synthetic news, forged recordings — raises the prospect of an environment in which nothing can be taken at face value, in which the evidentiary basis of public life is itself called into question. The tools for authenticating content, and the norms and laws for assigning responsibility, are far from adequate to the challenge, and the race between fabrication and detection is likely to be a defining feature of the coming era.",
      "The widespread failure of trust raises the possibility of what has been called an epistemic crisis — a state in which a society loses the shared basis for distinguishing truth from falsehood. Such a condition is profoundly threatening to democracy, which depends on a citizenry capable of informed deliberation, and to the entire edifice of modern life, which depends on the ability to verify claims about medicine, finance, science, and governance. When the foundations of shared reality erode, everything else is destabilized. Preventing that outcome is not a niche concern of media scholars; it is a matter of sustaining the conditions of a functioning society.",
      "The cultivation of information literacy is urgent, and it is best understood not merely as acquiring a set of skeptical techniques but as developing a disposition — a habit of mind that is curious, critical, and humble. It involves knowing how to evaluate the credibility of a source by examining its origin, its evidence, its corrections, and its funding; it involves understanding one's own cognitive biases and emotional responses; and it involves a willingness to revise one's beliefs in the face of good evidence. Crucially, it is not the same as cynicism: the goal is not to distrust everything but to trust discerningly, to be open to genuine evidence while remaining resistant to manipulation. In an age of noise, the ability to see clearly is a form of power, and its cultivation is among the most valuable things an education can confer.",
      "There is no single solution to the crisis of information integrity, and the problem will not be finally solved. It is a systemic condition of the technologically saturated world we have built, and it will require a sustained, multi-pronged, and continuous effort — combining education, journalism norms, platform design and regulation, technological authentication, and the rebuilding of institutional trust. The task is not to return to some imagined golden age of pure information, which never existed, but to build, deliberately and continually, the institutions, skills, and norms that allow a society to navigate abundance without losing its grip on truth. That project is democratic at its core: it rests on the conviction that a society of citizens who can think for themselves is the precondition for a society that is free. And it begins with the individual act of refusing to take information on faith — and learning, instead, to follow the evidence wherever it leads.",
    ],
    vocabularyNotes: [
      { term: "spurious", zh: "伪的；虚假的" },
      { term: "misinformation", zh: "（无意散布的）错误信息" },
      { term: "disinformation", zh: "（故意散布的）虚假信息" },
      { term: "confirmation bias", zh: "确认偏误" },
      { term: "mere-exposure effect", zh: "单纯曝光效应" },
      { term: "echo chamber", zh: "回音室" },
      { term: "filter bubble", zh: "过滤气泡" },
      { term: "epistemic", ipa: "/ˌepɪˈstiːmɪk/", zh: "认识论的" },
      { term: "fact-checking", zh: "事实核查" },
      { term: "de facto", zh: "事实上的" },
      { term: "content moderation", zh: "内容审核" },
      { term: "vicious circle", zh: "恶性循环" },
      { term: "deepfake", zh: "深度伪造" },
    ],
    grammarNotes: [
      {
        topicId: "hedging-language",
        titleZh: "媒介论述的审慎判断",
        noteZh: "may be complicated by / is likely to / arguably 对复杂因果保持分寸。",
        exampleFromText: "...the confirmation bias leads people to accept information that confirms their beliefs",
      },
      {
        topicId: "nominalization",
        titleZh: "媒介批评名词化",
        noteZh: "the amplification of content / the decline of trust 抽象名词压缩现象因果。",
        exampleFromText: "the proliferation of false content further erodes trust",
      },
      {
        topicId: "passive-across-tenses",
        titleZh: "被操纵受众的被动",
        noteZh: "are amplified / are exploited / is undermined 强调用户作为被动客体。",
        exampleFromText: "human cognitive vulnerabilities are systematically exploited",
      },
      {
        topicId: "parallelism-rules",
        titleZh: "并列结构界定概念",
        noteZh: "curious, critical, and humble 三连形容词刻画素养。",
        exampleFromText: "a habit of mind that is curious, critical, and humble",
      },
      {
        topicId: "emphasis-structures-cleft",
        titleZh: "强调结构突出结论",
        noteZh: "It is not the same as cynicism... 用 not...but 结构区分近义概念。",
        exampleFromText: "it is not the same as cynicism: the goal is not to distrust everything but to trust discerningly",
      },
      {
        topicId: "complex-sentences",
        titleZh: "因果与让步复合",
        noteZh: "Although the mechanism is complex... 用让步状语限定反驳难度。",
        exampleFromText: "While online media exaggerate effective correction, they also...",
      },
    ],
    questions: [
      {
        questionEn: "What is misinformation?",
        questionZh: "'misinformation' 是什么？",
        options: ["Deliberate lies", "False info spread without intent to deceive", "True rumors", "Only advertising"], answerIndex: 1,
        explainZh: "指无意欺骗传播的虚假或失准信息。",
      },
      {
        questionEn: "How does disinformation differ?",
        questionZh: "'disinformation' 与之有何不同？",
        options: ["It is always true", "It is deliberate, created with intent to deceive", "It is accidental", "It is opinion"], answerIndex: 1,
        explainZh: "它是故意制造并散布以欺骗或造成伤害的虚假信息。",
      },
      {
        questionEn: "What does the mere-exposure effect do?",
        questionZh: "'单纯曝光效应'起什么作用？",
        options: ["Makes familiar false", "Repetition alone increases believability", "Reduces memory", "Stops learning"], answerIndex: 1,
        explainZh: "仅凭重复就足以提高可信度。",
      },
      {
        questionEn: "Why does attention economics amplify misinformation?",
        questionZh: "为何注意力经济学放大虚假信息？",
        options: ["Platforms profit from engagement", "Advertising is truthful", "Algorithms prefer facts", "No incentives"], answerIndex: 0,
        explainZh: "平台追求最大参与度，而煽动性内容参与度最高。",
      },
      {
        questionEn: "What does a filter bubble do?",
        questionZh: "'过滤气泡'做什么？",
        options: ["Adds diverse views", "Excludes disconfirming content", "Removes ads", "Verifies facts"], answerIndex: 1,
        explainZh: "算法把关排除与用户观点相悖的内容。",
      },
      {
        questionEn: "Why do the real-world consequences of misinformation matter?",
        questionZh: "为何虚假信息的现实后果重要？",
        options: ["Only online", "Beliefs guide action affecting lives", "No impact", "Purely academic"], answerIndex: 1,
        explainZh: "信念指导行动，危害公共卫生、民主与生命。",
      },
      {
        questionEn: "Why is the platform role 'fraught'?",
        questionZh: "为何平台角色'棘手'？",
        options: ["They are simple", "They are private companies but de facto public squares", "They have no power", "They are public"], answerIndex: 1,
        explainZh: "平台既是私营公司又在事实上成为公共广场。",
      },
      {
        questionEn: "What threatens to make the problem worse?",
        questionZh: "什么可能使问题更严重？",
        options: ["More newspapers", "Generative AI producing convincing media", "More journalists", "Better printing"], answerIndex: 1,
        explainZh: "生成式 AI 能以规模制造几乎无法辨别的内容。",
      },
      {
        questionEn: "What is an 'epistemic crisis'?",
        questionZh: "'认识论危机'指什么？",
        options: ["Economic collapse", "Losing a shared basis for judging truth", "Too many facts", "Better education"], answerIndex: 1,
        explainZh: "社会失去区分真假共享基础的状态，威胁民主。",
      },
      {
        questionEn: "How is information literacy best understood?",
        questionZh: "信息素养最好被理解为？",
        options: ["A set of tricks", "A disposition that is curious, critical, humble", "Pure cynicism", "Censorship"], answerIndex: 1,
        explainZh: "它是好奇、批判、谦逊的心智习性，而非怀疑一切。",
      },
    ],
    summaryTaskZh: "用不超过 90 个英文单词总结：作者如何区分 misinformation 与 disinformation？为什么注意力经济与算法会放大虚假信息？",
    opinionTaskZh: "The author argues that the goal of information literacy is to trust discerningly rather than cynically. Drawing on the text, argue whether individuals or platforms bear greater responsibility for stopping the spread of misinformation. Write 150-180 words with one concessive clause.",
  },
  {
    id: "reading-17-law-justice",
    number: 17,
    slug: "law-justice",
    title: "The Rule of Law: Justice, Legitimacy, and the Delicate Architecture of Legal Order",
    categoryZh: "法律与正义",
    difficulty: "C2",
    wordCount: 4100,
    minutes: 27,
    article: [
      "Law is one of humanity's oldest and most consequential inventions. It is the framework through which societies regulate conduct, resolve disputes, and reconcile the claims of individuals with the demands of the community. But law is not merely a set of rules; it is an institution built on a distinctive kind of authority — the authority of legitimate order — and it claims obedience not principally through force but through the recognition that its commands are binding. The question of what makes law legitimate, of how justice can be achieved through legal means, and of how the rule of law relates to power is among the deepest subjects of political and legal philosophy, and it is the foundation on which the entire edifice of modern legal order rests.",
      "The concept of the rule of law is central to this inquiry. It is the idea that law should govern — that no one, including those who wield power, is above the law, and that legal rules should be general, public, prospective, and consistently applied. The rule of law stands in contrast to the rule of men, in which decisions are made arbitrarily and power is exercised at the whim of the powerful. In its full form, the rule of law requires not only that rulers obey the law but that the law itself possess certain qualities — clarity, stability, and generality — that enable people to plan their lives around it. It is, in the celebrated phrase, a government of laws and not of men, and it is widely regarded as a precondition for liberty and for the legitimacy of political authority.",
      "The sources of law are diverse, and their arrangement defines the character of a legal system. In common-law systems, which trace their lineage to England, much of the law is made by judges through the doctrine of precedent — the principle that like cases should be decided alike, so that decisions accumulate into a body of law over time. In civil-law systems, which descend from Roman law, the law is codified in comprehensive statutes and codes, and the role of the judge is primarily to apply the code rather than to make law. Beyond these, there is statute law, enacted by legislatures, constitutional law, which sets the fundamental framework and limits of government power, and international law, which governs relations between states. The blend of these sources varies from country to country, and their interaction generates much of the complexity of legal practice.",
      "The idea that law derives its authority from legitimacy rather than mere coercion is central to its character. A legal system that relies solely on force is not properly a legal system at all but a regime of domination, and its commands are obeyed from fear rather than obligation. The authority of law depends on its claim to obligation being recognized as morally binding, and this recognition rests, in turn, on legitimacy. Theories of legitimacy differ: some locate it in consent, some in the beneficial function of law, some in the fairness of the procedures by which law is made and applied. Whatever the theory, the practical point is that a law is authoritative not simply because it is powerful but because it is accepted as something that ought to be obeyed.",
      "Justice is the end toward which law aspires, and the analysis of justice has occupied the greatest minds of political philosophy. A central distinction runs between commutative and distributive justice, and between procedural and substantive justice. Procedural justice concerns the fairness of the processes by which decisions are made — that like cases are treated alike, that parties are heard, that decisions are made by impartial adjudicators. Substantive justice concerns the content of the outcomes, the fairness of the rules themselves. A system can be procedurally fair and still substantively unjust if the rules it applies are themselves skewed against some. The two are inseparable in practice: procedural fairness is a necessary but not a sufficient condition of a just legal order.",
      "The theory of punishment raises the most contested questions in the philosophy of law. Why do we punish, and what justifies it? The retributive theory holds that punishment is justified because wrongdoers deserve it, that it restores a moral balance disturbed by the crime. The utilitarian or deterrent theory holds that punishment is justified not because it is deserved but because it deters crime and protects society. These theories pull in different directions: retribution looks backward to desert, deterrence looks forward to consequences. Modern criminal justice systems are a hybrid, and the debate between rehabilitation, deterrence, and retribution animates every reform of sentencing, imprisonment, and the treatment of offenders.",
      "The criminal justice system is, in practice, profoundly influenced by its social context, and its ideal of equal justice is only imperfectly realized. The distribution of who is arrested, prosecuted, convicted, and imprisoned reflects not only the commission of crime but a host of social factors — income, race, and the resources available to defendants. The aspiration of equal treatment before the law collides with the reality of unequal resources and unequal protection. The recognition of these disparities has generated widespread concern about mass incarceration, over-policing of poor communities, and the differential treatment of offenders by race and class. Reforming the criminal justice system is among the most emotionally charged and politically consequential projects of contemporary societies.",
      "The law's relationship to morality is another deep theme. Some legal theorists insist that law and morality are, or should be, connected — that an unjust law is not truly law, or that law must be interpreted in the light of moral principle. Others argue that law is a distinct domain, defined by its formal sources and procedures rather than by its moral content, and that confusing law with morality invites the danger of pretending that might makes right. The debate matters enormously in practice, because it bears on how judges interpret statutes, how rights are understood, and how the bounds of legitimate state power are drawn. The tension between a legal order that aims at justice and a legal order that is simply orderly is one that no system entirely resolves.",
      "Constitutionalism — the idea that even government is bound by a higher law — is the foundation of modern political freedom. A constitution sets out the basic structure of government, the distribution of powers, and the fundamental rights that government may not infringe. Constitutional design is among the most delicate arts of statecraft: it must create a government strong enough to govern effectively but constrained enough to be safe; it must balance the powers of different branches, guard against tyranny, and provide mechanisms for peaceful change. The separation of powers, federalism, and an independent judiciary are among the devices by which constitutional orders seek to achieve these ends. The legitimacy of a constitutional order rests on its claim to embody the will and secure the rights of the people it governs.",
      "The role of an independent judiciary is central to the rule of law. If judges are to adjudicate disputes fairly, they must be free from the influence of the parties before them and from the pressure of the political branches. Judicial independence is not a matter of juridical vanity; it is a practical condition for the trust that the public must place in courts if they are to resolve disputes peacefully and to hold government within the bounds of law. Yet independence raises its own difficulties, above all the question of how a body that is not democratically accountable is itself to be held in check. The balance between judicial independence and democratic accountability is a permanent and productive tension in constitutional design.",
      "The law evolves, and its responsiveness to change is a measure of its health. The common law grows through decisions that adapt old principles to new circumstances. Statutes are amended and replaced as societies' values and circumstances change. And on questions of fundamental right, the law sometimes undergoes profound transformation — as with the abolition of slavery, the extension of the franchise, and the recognition of civil rights — usually after long and contentious struggle. The fact that law changes demonstrates that it is not a frozen code but a living institution, responsive to the moral development of the society that makes and obeys it; but the pace and direction of that change are themselves the subject of perpetual contestation.",
      "International law occupies a distinctive and contested position. It governs relations between sovereign states, and its authority rests not on a world government but on the consent, expressed through treaties and the development of customary norms, of the states it binds. International law has achieved real and consequential results — in the laws of war, human rights, trade, and the environment — yet it is frequently violated, and it is enforced unevenly and often weakly. The tension between state sovereignty and international obligation, and between the ideal of a rule-governed international order and the reality of power politics, is one of the most difficult and consequential questions of the contemporary world.",
      "The expansion of law into ever more areas of life is a mark of modernization and a source of concern. As societies have grown more complex, law has come to regulate areas — employment, environment, data, health — that were once left to private arrangement or social convention. The juridification of social life brings the benefits of clear rights and protections, but it also risks excessive formalism, the crowding-out of non-legal modes of resolving conflict, and the constant need to make policy through adjudication. The question of how much and what kind of law a society needs, and of the proper boundary between legal regulation and other forms of social ordering, is a perennial one.",
      "Ultimately, the law is a human institution that embodies the central tension of political life: the need for order and the demand for justice. A legal order that is merely orderly but unjust is a regime of oppression; a justice that is sought without order descends into conflict. The rule of law is the attempt to reconcile these poles — to bind power by general, public rules while directing those rules toward the ends of fairness and freedom. It is an institution of extraordinary subtlety and fragility, always under construction and never complete. Its preservation is the collective responsibility of every citizen, because the law is not self-sustaining: it depends, in the end, on the willingness of people to obey it as legitimate, to defend it against arbitrary power, and to keep pressing it toward the justice it promises but has never fully delivered.",
    ],
    vocabularyNotes: [
      { term: "legitimacy", zh: "合法性；正当性" },
      { term: "rule of law", zh: "法治" },
      { term: "prospective", zh: "面向未来的" },
      { term: "common law", zh: "普通法（判例法）" },
      { term: "precedent", ipa: "/ˈpresɪdənt/", zh: "先例" },
      { term: "civil law", zh: "大陆法（成文法）" },
      { term: "statute law", zh: "成文法" },
      { term: "retributive", zh: "报应（论）的" },
      { term: "utilitarian", zh: "功利主义的" },
      { term: "deterrence", zh: "威慑" },
      { term: "rehabilitation", zh: "改造；矫治" },
      { term: "constitutionalism", zh: "宪政主义" },
      { term: "juridification", zh: "法律化" },
      { term: "adjudication", zh: "裁判；裁决" },
    ],
    grammarNotes: [
      {
        topicId: "nominalization",
        titleZh: "法理论述的名词化",
        noteZh: "the recognition of civil rights / the extension of the franchise 抽象名词呈现法律演进。",
        exampleFromText: "the abolition of slavery, the extension of the franchise, and the recognition of civil rights",
      },
      {
        topicId: "hedging-language",
        titleZh: "法哲学判断的审慎",
        noteZh: "is not a matter of...; it is a matter of / preeminently 措辞严谨界定范围。",
        exampleFromText: "The rule of law stands in contrast to the rule of men",
      },
      {
        topicId: "passive-across-tenses",
        titleZh: "司法制度的被动",
        noteZh: "are interpreted / is applied / are obeyed 强调规则与司法为客体。",
        exampleFromText: "decisions are made by impartial adjudicators",
      },
      {
        topicId: "complex-sentences",
        titleZh: "条件与让步逻辑",
        noteZh: "If judges are to adjudicate fairly, they must be free... 用条件式论证司法独立。",
        exampleFromText: "If judges are to adjudicate disputes fairly, they must be free from the influence of the parties before them",
      },
      {
        topicId: "relative-clauses-defining-nondefining",
        titleZh: "关系从句界定制度",
        noteZh: "a government of laws and not of men, which is widely regarded... 界定法治理想。",
        exampleFromText: "It is... a government of laws and not of men",
      },
      {
        topicId: "parallelism-rules",
        titleZh: "对比并列结构",
        noteZh: "retribution looks backward, deterrence looks forward 对举两种惩罚理论。",
        exampleFromText: "retribution looks backward to desert, deterrence looks forward to consequences",
      },
    ],
    questions: [
      {
        questionEn: "What does the rule of law require?",
        questionZh: "法治要求什么？",
        options: ["Rule by whim", "That no one, including rulers, is above the law", "Only subjects obey", "Arbitrary power"], answerIndex: 1,
        explainZh: "法治要求无人能凌驾于法律之上，规则一般、公开、前瞻且一致适用。",
      },
      {
        questionEn: "What creates law in common-law systems?",
        questionZh: "普通法系如何创制法律？",
        options: ["Only parliaments", "Judges through precedent", "Priests", "No law"], answerIndex: 1,
        explainZh: "普通法通过法官遵循先例累积而成。",
      },
      {
        questionEn: "Why is legitimate authority central to law?",
        questionZh: "为何正当性对法律至关重要？",
        options: ["Force alone is not proper law", "Legitimacy is irrelevant", "Fear is enough", "Power defines law"], answerIndex: 0,
        explainZh: "仅靠强制的不是真正的法律而是支配，需被承认为有约束力。",
      },
      {
        questionEn: "What does retributive theory of punishment hold?",
        questionZh: "报应论认为惩罚为何正当？",
        options: ["To deter crime", "Because wrongdoers deserve it", "To save money", "To profit"], answerIndex: 1,
        explainZh: "报应论认为恶者应得惩罚，恢复道德平衡。",
      },
      {
        questionEn: "What distinguishes utilitarian punishment?",
        questionZh: "功利主义惩罚有何不同？",
        options: ["Looks backward", "Justified by deterrence and protection", "No purpose", "Retribution only"], answerIndex: 1,
        explainZh: "功利主义看未来后果——威慑与保护社会。",
      },
      {
        questionEn: "Why is justice only imperfectly realized?",
        questionZh: "为何正义只能不完美实现？",
        options: ["Laws are perfect", "Social factors skew who is punished", "No crime occurs", "Courts are unnecessary"], answerIndex: 1,
        explainZh: "逮捕、起诉与监禁受收入、种族与资源影响。",
      },
      {
        questionEn: "What does constitutionalism hold?",
        questionZh: "宪政主义主张什么？",
        options: ["Unlimited government", "Even government is bound by higher law", "No rights", "Monarchy"], answerIndex: 1,
        explainZh: "连政府也受更高法律的约束，是政治自由的基础。",
      },
      {
        questionEn: "Why is judicial independence central?",
        questionZh: "为何司法独立至关重要？",
        options: ["Judges are above law", "It enables fair adjudication free from influence", "It removes checks", "For vanity"], answerIndex: 1,
        explainZh: "独立使法官免受影响，是公众信任的实际条件。",
      },
      {
        questionEn: "On what does international law's authority rest?",
        questionZh: "国际法的权威倚仗什么？",
        options: ["A world government", "Consent of states through treaties", "Armies", "One country's power"], answerIndex: 1,
        explainZh: "倚仗国家通过条约与习惯法的同意。",
      },
      {
        questionEn: "How does the author characterize law's preservation?",
        questionZh: "作者如何形容法律的维护？",
        options: ["Automatic", "A collective responsibility of citizens", "The courts' alone", "Impossible"], answerIndex: 1,
        explainZh: "法律的维系依赖人民恪守、捍卫并推动其正义的集体责任。",
      },
    ],
    summaryTaskZh: "用不超过 90 个英文单词总结：作者如何定义法治与法律权威的正当性来源？为什么程序正义不足以保证实体正义？",
    opinionTaskZh: "The author notes the tension between retribution and deterrence in punishment. Drawing on the text and your own view, argue whether the criminal justice system should emphasize punishment or rehabilitation. Write 150-180 words with one concessive clause.",
  },
  {
    id: "reading-18-philosophy-ethics",
    number: 18,
    slug: "philosophy-ethics",
    title: "How Should We Live? Philosophy, Ethics, and the Search for the Good Life",
    categoryZh: "哲学与伦理",
    difficulty: "C2",
    wordCount: 4100,
    minutes: 27,
    article: [
      "Philosophy is the love of wisdom, and its central questions are among the most enduring that human beings have asked. What is real? What can we know? What is good? And how should we live? These questions, apparently abstract and remote, are in fact inescapable, because every human being, whether or not they reflect on it, lives according to some answer to them. The branch of philosophy that confronts the question of how we should live, and of what makes an action right or a life good, is ethics, and it is to the enduring and inconclusive conversation of ethics that this inquiry turns. Ethics does not promise final answers; its value lies in the clarity and rigour it brings to questions we cannot avoid.",
      "The ancient Greeks set the terms of the conversation. At its center stands Socrates, who insisted that the unexamined life is not worth living and that the pursuit of moral knowledge is the first duty of a human being. His student Plato developed a comprehensive philosophy in which the good is an objective reality — the form of the good — that grounds all value and toward which knowledge and virtue aspire. Aristotle, Plato's student, took a more empirical and practical turn. For Aristotle, the central ethical question was not what abstract rule we should follow but what it is to live a good life, and his answer was framed in terms of eudaimonia — a Greek word often rendered as happiness or flourishing. The good life, for Aristotle, consists in the actualization of our distinctively human capacities through the cultivation of virtue and practical wisdom.",
      "Aristotle's virtue ethics exercised an enormous influence, and it has enjoyed a powerful revival in recent decades. Its core idea is that the good life is achieved not primarily by following rules or calculating consequences but by becoming a certain kind of person — by cultivating character-traits, the virtues, that dispose one to feel and act well. The virtues are not innate but habitual: we become just by doing just acts, courageous by acting courageously. Practical wisdom, or phronesis, is the capacity to discern, in the particular circumstances of a life, what the right course of action is. Virtue ethics is often contrasted with theories that define right action in terms of rules or outcomes, and its appeal lies in its realism about the moral life being a matter of character as much as of decision.",
      "The modern period produced the two great rival theories that still dominate ethical discussion. Deontology, associated above all with Immanuel Kant, holds that the rightness of an action is determined not by its consequences but by its conformity to duty — to the moral law. Kant's supreme moral principle, the categorical imperative, commands that one act only on maxims one could will to be universal law, and that one treat humanity, whether in oneself or others, always as an end and never merely as a means. Kantian ethics elevates respect for persons, and its insistence on the dignity of rational beings has become a cornerstone of modern thought about human rights. Its difficulty lies in its rigidity and in the contestable nature of its formulation of duty.",
      "Consequentialism, in its most influential form utilitarianism, associated with Jeremy Bentham and John Stuart Mill, takes a diametrically opposed starting point. For the utilitarian, the right action is the one that produces the greatest good — classically, the greatest happiness — for the greatest number. Consequentialism is forward-looking and impartial, holding outcomes, and the sum of well-being across all affected, to be decisive. Its appeal lies in its clarity and its insistence that the moral point of view is impartial. Its difficulties are notorious: the problem of measuring and comparing goods, the danger that a strict focus on aggregate happiness might license injustice to individuals, and the demandingness of a view that holds us responsible for all the consequences of our alternatives. The debate between deontology and consequentialism — between respect for persons and the promotion of good outcomes — is far from settled and remains the fault-line of much ethical thought.",
      "Applied ethics extends these theoretical debates to the concrete moral problems of contemporary life. Bioethics confronts the questions raised by medicine and biotechnology: the beginning and end of life, the allocation of scarce medical resources, the limits of enhancement and genetic intervention. Business ethics examines the responsibilities of corporations and the moral limits of profit-seeking. Environmental ethics asks about our obligations to the natural world and to future generations. And the ethics of technology, a fast-growing field, confronts the systematically underestimated consequences of AI, surveillance, and digital manipulation. Applied ethics demonstrates that philosophy is not a purely abstract discipline but an indispensable resource for a society attempting to orient itself amid rapid and disorienting change.",
      "The domain of justice and political philosophy addresses the question of how society should be organized. If ethics concerns the good life of individuals, political philosophy asks what a just society is, and how the claims of liberty, equality, and community are to be balanced. The most important modern statement is John Rawls's theory of justice as fairness, which asks what principles of social cooperation free and equal persons would choose behind a veil of ignorance — that is, without knowing their own place in society. Rawls argues that they would choose principles guaranteeing equal basic liberties and arranging inequalities so that they work to the benefit of the least advantaged. His work renewed political philosophy and continues to shape debate over distributive justice, though it has been challenged from both libertarian and more radical directions.",
      "The nature of the good life has been a central question since antiquity, and it has acquired new urgency in the modern world. Is the good life a matter of pleasure, of virtue, of the exercise of reason, of meaningful work and relationships, of the satisfaction of desire? The ancient schools offered rival answers, and the contemporary science of well-being has added empirical evidence to the ancient debates, finding that beyond a certain point income brings diminishing happiness, and that relationships, meaning, and purpose matter more than consumption. The philosophical question of what happiness is, and whether it is the same as flourishing, remains open, but the increased attention to well-being reflects a growing recognition that a good life is more than a successful career or the accumulation of goods.",
      "The question of free will and moral responsibility is threaded throughout ethics. If our actions are determined by causes we did not choose, in what sense are we responsible for them? Determinists argue that all our choices are the product of prior causes and that this threatens the notion of moral responsibility; libertarians insist that genuine free choice exists; and compatibilists argue that freedom and responsibility are compatible with determinism, properly understood. The question is not merely theoretical, because it bears on the practices of praising, blaming, and punishing on which social life depends. Advances in neuroscience have given the question a new empirical edge, without resolving the philosophical puzzles it raises.",
      "The diversity of moral norms across cultures raises the question of moral relativism. If different societies hold different moral codes, is there any objective standard by which to judge them, or is morality merely a matter of cultural convention? Few serious philosophers embrace a crude relativism, but the recognition of cultural diversity requires humility about one's own moral certainties and attention to the danger of assuming that one's own code is universal. The challenge is to recognize genuine differences while retaining the ground to criticize practices — slavery, oppression, cruelty — that warrant universal condemnation. The debate between universalism and particularism is among the most contested and consequential in the contemporary philosophical conversation.",
      "The life of the mind and the question of what philosophy is for are themselves subjects of philosophical reflection. Is philosophy a science, a form of therapy for a troubled mind, a propaedeutic to other disciplines, or an activity valuable in itself? The advocates of each view bring out different dimensions of the enterprise. What is clear is that philosophy is not a body of settled doctrine but an activity — a mode of disciplined inquiry, of questioning assumptions, of attending to the grounds of belief. Its value lies less in the conclusions it secures than in the clarity of thought it cultivates and the rigor with which it examines what we otherwise take for granted.",
      "The relationship between ethics and religion has been a perennial tension. For many, moral obligation has its foundation in the will or nature of God, and religious traditions have been among the most powerful bearers of moral teaching. Others argue that morality can and must be grounded in reason and in facts about human well-being, and that a mature ethics can stand without theological support. The questions of whether morality requires religion, whether religious morality is a genuine alternative to secular ethics, and how a pluralistic society should treat competing moral and religious claims are as urgent in the present as at any time in history.",
      "The rise of artificial intelligence has lent a new and acute urgency to philosophical questions. What does it mean for a machine to make decisions that affect human lives, and how are responsibility and accountability to be assigned when those decisions go wrong? What values should be embedded in autonomous systems, and who is to decide? Do increasingly capable systems raise genuine moral questions, of rights, of obligations to them, or are they merely tools to be judged by their effects on human beings? And the question of the meaning and value of human life takes on new sharpness in an age in which the distinctiveness of human intelligence can no longer be taken for granted. These are not merely engineering problems; they are philosophical questions of the first order, and the discipline that has long asked how we should live is now also called upon to ask how the machines we build should live among us.",
      "Philosophy offers no final answers, and its history is a conversation that has continued for more than two millennia without being concluded. But that is not a failure; it is the nature of the enterprise. The questions philosophy asks are not the kind that admit of conclusive resolution, because they concern the most fundamental orientations of human life, about which reasonable people will continue to differ. What philosophy does offer is something perhaps more valuable: the discipline of thinking clearly about the questions we cannot avoid, the courage to examine our assumptions, and the humility to recognize the limits of our knowledge. In an age of unprecedented change and uncertainty, these are capacities of which humanity stands in acute need. To learn to think well about how we should live — that, Socrates insisted, is the first of arts; and that, the long conversation of ethics and philosophy continues to teach us.",
    ],
    vocabularyNotes: [
      { term: "eudaimonia", ipa: "/juːdaɪˈmoʊniə/", zh: "幸福/繁盛（亚里士多德式的最高善）" },
      { term: "virtue ethics", zh: "德性伦理学" },
      { term: "phronesis", zh: "实践智慧" },
      { term: "deontology", ipa: "/ˌdiːɒnˈtɒlədʒi/", zh: "义务论" },
      { term: "categorical imperative", zh: "绝对命令" },
      { term: "consequentialism", zh: "后果论" },
      { term: "utilitarianism", zh: "功利主义" },
      { term: "veil of ignorance", zh: "无知之幕" },
      { term: "compatibilist", zh: "相容论者" },
      { term: "moral relativism", zh: "道德相对主义" },
      { term: "universalism", zh: "普遍主义" },
      { term: "particularism", zh: "特殊主义" },
      { term: "propaedeutic", zh: "预备性的（导论）" },
    ],
    grammarNotes: [
      {
        topicId: "nominalization",
        titleZh: "伦理论述的名词化",
        noteZh: "the cultivation of virtue / the actualization of capacities 抽象名词表达哲学概念。",
        exampleFromText: "the actualization of our distinctively human capacities through the cultivation of virtue",
      },
      {
        topicId: "hedging-language",
        titleZh: "哲学判断的审慎",
        noteZh: "is not a matter of...; it is a matter of / arguably 界定范围、缓冲断言。",
        exampleFromText: "Its value lies less in the conclusions it secures than in the clarity of thought it cultivates",
      },
      {
        topicId: "passive-across-tenses",
        titleZh: "被研究对象的被动",
        noteZh: "are determined / are characterized / is embedded 强调人被塑造与系统被设计。",
        exampleFromText: "we become just by doing just acts",
      },
      {
        topicId: "parallelism-rules",
        titleZh: "设问式并列推进",
        noteZh: "What is good? How should we live? 用连续设问铺陈哲学核心。",
        exampleFromText: "What is real? What can we know? What is good? And how should we live?",
      },
      {
        topicId: "relative-clauses-defining-nondefining",
        titleZh: "关系从句界定概念",
        noteZh: "a Greek word that is often rendered as happiness 用从句注解外文术语。",
        exampleFromText: "eudaimonia — a Greek word often rendered as happiness or flourishing",
      },
      {
        topicId: "emphasis-structures-cleft",
        titleZh: "强调结构突出观点",
        noteZh: "It is not...; it is the nature of... 用 not...but 澄清误解。",
        exampleFromText: "But that is not a failure; it is the nature of the enterprise",
      },
    ],
    questions: [
      {
        questionEn: "What did Aristotle claim the good life consists in?",
        questionZh: "亚里士多德认为好生活在于什么？",
        options: ["Pleasure", "Actualizing distinctively human capacities through virtue", "Wealth", "Power"], answerIndex: 1,
        explainZh: "好生活在于通过培养德性实现人之独特能力。",
      },
      {
        questionEn: "What is eudaimonia often translated as?",
        questionZh: "'eudaimonia' 常被译为什么？",
        options: ["Duty", "Happiness or flourishing", "Justice", "Wisdom alone"], answerIndex: 1,
        explainZh: "常译为幸福或繁盛。",
      },
      {
        questionEn: "What does deontology (Kant) hold?",
        questionZh: "义务论（康德）主张什么？",
        options: ["Judging by consequences", "Rightness by conformity to duty", "No rules", "Maximizing pleasure"], answerIndex: 1,
        explainZh: "行为正当性由其与义务的契合决定，而非后果。",
      },
      {
        questionEn: "What is the categorical imperative's command about persons?",
        questionZh: "绝对命令对人提出什么要求？",
        options: ["Use as means", "Treat humanity always as an end, never merely a means", "Ignore dignity", "Obey rulers"], answerIndex: 1,
        explainZh: "总把人当作目的，绝不只当作手段。",
      },
      {
        questionEn: "What does utilitarianism hold?",
        questionZh: "功利主义主张什么？",
        options: ["Respect persons only", "Produce greatest good for greatest number", "Follow universal law", "Cultivate virtue"], answerIndex: 1,
        explainZh: "正当行为产生最大多数人的最大幸福。",
      },
      {
        questionEn: "What does Rawls's veil of ignorance ask?",
        questionZh: "罗尔斯的'无知之幕'询问什么？",
        options: ["What rules self-interested choosers would select without knowing their place", "What maxims are universal", "What maximizes pleasure", "What ancient customs"], answerIndex: 0,
        explainZh: "设想人们在不知道自己社会地位时选择公正原则。",
      },
      {
        questionEn: "What do compatibilists argue?",
        questionZh: "相容论者主张什么？",
        options: ["Freedom is impossible", "Freedom and responsibility are compatible with determinism", "Only libertarianism", "No responsibility"], answerIndex: 1,
        explainZh: "自由与责任可与决定论相容，若恰当理解。",
      },
      {
        questionEn: "Why does cultural diversity raise the relativism question?",
        questionZh: "为何文化多样性引发相对主义问题？",
        options: ["No cultures differ", "If codes differ, is there objective standard", "All share one code", "It ends debate"], answerIndex: 1,
        explainZh: "若各文化准则不同，是否还有客观判断标准。",
      },
      {
        questionEn: "Why does philosophy offer no final answers?",
        questionZh: "为何哲学不提供最终答案？",
        options: ["It is useless", "Its questions concern fundamental orientations admitting no conclusive resolution", "It ends soon", "It is dogmatic"], answerIndex: 1,
        explainZh: "其问题关乎人类生活根本取向，理性者可持续分歧。",
      },
      {
        questionEn: "What value does the author say philosophy offers?",
        questionZh: "作者说哲学提供什么价值？",
        options: ["Settled doctrine", "Discipline of clear thinking and humility", "Final truths", "Pleasure"], answerIndex: 1,
        explainZh: "提供清晰思考的纪律、审视假设的勇气与认识限度的谦逊。",
      },
    ],
    summaryTaskZh: "用不超过 90 个英文单词总结：作者如何对比德性伦理学、义务论与后果论？他认为哲学的价值何在？",
    opinionTaskZh: "The author presents rival theories of right action. Drawing on the text and your own reasoning, argue whether the rightness of an action should be judged by its consequences or by its conformity to duty. Write 150-180 words with one concessive clause.",
  },
];
