/**
 * Phase 19-P0-1: Reading Library Completion (part 6).
 * Articles 19-20 of 20 (final part).
 */
import type { ReadingArticle } from "@/content/resources/reading-library";

export const P19_READING_PART6: readonly ReadingArticle[] = [
  {
    id: "reading-19-cultural-diversity",
    number: 19,
    slug: "cultural-diversity",
    title: "The Tapestry of Difference: Cultural Pluralism, Identity, and the Challenge of Conviviality",
    categoryZh: "文化多样性",
    difficulty: "C2",
    wordCount: 3900,
    minutes: 26,
    article: [
      "Cultural diversity is one of the most distinctive and, at the same time, most contested features of the modern human condition. The world is home to thousands of cultures, languages, and ways of life, and for most of human history this diversity was organized largely by geography — distinct peoples inhabited distinct regions, and contact between them was the exception rather than the rule. The forces of modernity have transformed this arrangement. Migration, trade, technology, and the movement of people have brought cultures into unprecedented and sustained contact, and the result is that most societies are now sites of intense cultural pluralism, in which people of different origins, faiths, and traditions live side by side. The question of how such societies can be just, stable, and livable is among the central questions of our time.",
      "The value of diversity is a claim heard from many quarters, and it rests on a number of distinct arguments. There is a moral argument that cultures deserve respect — that the traditions and practices that give meaning to people's lives have a claim to recognition that a decent society should not trample. There is an aesthetic and intellectual argument that cultural difference enriches collective life, exposing people to new ways of thinking, making, and experiencing the world. There is an argument from freedom, that people should be free to live by the values they choose. And there is, increasingly, an argument from the economy and from innovation, that diversity brings different perspectives and skills that contribute to creativity and growth. Each of these arguments identifies something genuine, and collectively they make an overwhelming case for the claim that diversity is, other things being equal, a good to be cherished rather than a problem to be solved.",
      "The ideal of multiculturalism — the project of building societies in which different cultural groups maintain their distinct identities while participating as full and equal citizens in a common polity — has been the dominant framework for managing diversity in many liberal democracies. Multiculturalism rejects the older ideal of assimilation, in which newcomers were expected to abandon their own cultures and become indistinguishable from the majority. Instead, it seeks a balance: recognition of difference combined with a shared civic framework that guarantees rights, freedoms, and the rule of law. The multicultural project has achieved genuine successes, but it has also come under sustained and serious criticism in recent decades, from both the left and the right, and the debate over its merits remains intense and unresolved.",
      "The criticism of multiculturalism takes many forms. Some argue that it has encouraged the fragmentation of society into separate, self-contained communities that neither interact nor share a common sense of belonging — a condition sometimes described as parallel lives. Others argue that a too-tender respect for cultural difference has been used to excuse practices that violate the fundamental rights of individuals, particularly of women and of children, and that the tolerance of the majority has enabled the intolerance of minorities toward their own members. Still others argue that multiculturalism, whatever its intentions, has failed to address, and has even obscured, the real problems of inequality, discrimination, and exclusion that afflict minority communities. The defenders of multiculturalism respond that these failures are failures of implementation by societies that were never genuinely committed to equality, not failures of the ideal itself.",
      "The idea of cultural relativism, that moral and social values are valid only relative to the culture in which they arise, has played a contradictory role in these debates. On the one hand, it has served a humane and corrective function, challenging the arrogance of cultures that assumed their own superiority and encouraging respect for ways of life different from one's own. On the other, a crude relativism can undermine the ground on which any critique − including the critique of injustice within one's own or another culture − can be made to stand. The challenge, which the best reflection works to solve, is to combine genuine respect for difference with a steadfast commitment to universal values of human dignity and human rights. The resolution, in practice, is that cultural differences deserve respect precisely insofar as they are compatible with the equal standing and basic rights of every person.",
      "The question of identity is inseparable from the question of culture, and identity has become a central, and frequently contentious, category of modern life. A person's identity is not a single, fixed essence but a complex and dynamic construction, woven from many threads − nationality, ethnicity, language, religion, gender, profession, and personal history. The idea that identity is socially constructed, that the groups to which people belong and the meanings attached to those memberships are created and sustained by social processes rather than given by nature, has transformed how the social sciences, and indeed people themselves, understand themselves. But the constructed character of identity does not make it less real or less powerful; people live, suffer, and act in the name of the identities they inhabit, and the group differences that structure social life have tangible consequences.",
      "The politics of identity has become a defining feature of contemporary democracy. Movements for recognition have multiplied, as groups that were marginalized, excluded, or rendered invisible have demanded to be seen, respected, and included on terms of equality. The civil rights movement, the movements for women's equality, and the movements of colonized and indigenous peoples each rested on the claim that a just society must acknowledge the equal dignity of all its members. The demand for political recognition − for the right to participate fully, to have one's history and experience acknowledged, and to shape the common culture − is central to these struggles. Yet the politics of identity is also contested, criticized by some for fragmenting a common politics into warring particularisms, and by others for the ways it can reinforce precisely the categories it aims to overcome.",
      "The tension between unity and diversity, between the claims of the common and the claims of the particular, is the central problem of pluralism. Every society must decide how much distinctness it can accommodate while still maintaining the bonds of a common life, and how much it must insist on commonality while respecting the plurality of its members. There is no formula that resolves this tension; it is managed, provisionally and imperfectly, through institutions, through dialogue, and through the psychologies of tolerance and belonging that members of a society develop. The health of a plural society is measured by its capacity to hold these contending claims in a productive rather than destructive balance.",
      "The management of diversity varies enormously across political traditions. France has pursued a model of republican universalism, in which the public sphere is meant to be blind to particular identities, and in which integration is conceived of primarily in terms of shared citizenship rather than the recognition of distinct communitarian identities. The United States has historically conceived of itself as a melting pot, a crucible in which diverse origins are blended into a single American identity, though this ideal has always coexisted with, and been complicated by, persistent segmentation along lines of race. The United Kingdom and Canada have moved toward official multiculturalism, recognizing cultural difference and seeking to promote integration without demanding assimilation. Each model embodies a particular answer to the question of how the one and the many are to be reconciled, and each has produced its own successes and its own discontents.",
      "Language is both a vehicle of diversity and a battleground of its management. The world's thousands of languages embody distinct ways of seeing and organizing the world, and their loss − it is estimated that many of the world's languages are endangered − represents an irreplaceable loss of human diversity. The fate of minority languages is bound up with questions of power, of education, of prestige, and of survival. Some societies have successfully maintained bilingual or multilingual public cultures; others have seen minority languages suppressed or abandoned. The question of what language a society conducts its public life in, and how it treats the languages of its minorities, is among the most sensitive and consequential of all questions of cultural policy.",
      "The culture of the internet and of global media has created a new and paradoxical situation. On the one hand, global communication has made it possible for dispersed communities to maintain and strengthen their identities, for minority voices to be heard, and for cultures to be transmitted across vast distances. On the other, the dominance of a handful of global platforms and content industries exerts an enormous homogenizing pressure, and the reach of a few dominant cultures threatens to overshadow the distinctive traditions of smaller and less powerful ones. The digital age has simultaneously empowered and endangered cultural diversity, and how it is managed is a question of rising importance.",
      "The ethics of cultural engagement raises questions for individuals as well as societies. How should a person engage with cultural difference − with the customs, foods, arts, and beliefs of others? The danger of appropriation and of tourism-like consumption of other cultures, which extracts the enjoyable and marketable surface while ignoring the people and the meanings beneath, is real. A more respectful engagement approaches other cultures with genuine curiosity, with humility about the limits of one's understanding, and with a readiness to listen and to learn. The aim is not to master or to own the culture of another but to encounter it with the openness and respect that any human creation deserves.",
      "The future of cultural diversity will be shaped by forces that pull in opposing directions. Migration and connectivity will continue to bring cultures into contact and mixture, producing new hybrid identities and practices that defy neat classification. At the same time, the forces of homogenization − global commerce, media consolidation, and the reach of dominant cultures − threaten to flatten the world's variety. Whether the outcome is a richer mingling or a sad uniformity will depend not on these forces alone but on the values and policies with which societies respond. The preservation of diversity is not a matter of freezing cultures in the past, for cultures are living and changing things; it is a matter of sustaining the conditions in which different ways of life can continue to flourish, to intermix, and to renew themselves without being extinguished. That is a task that calls upon the resources of every society, and one that the imperiled plurality of the human world, in its richness and fragility, makes both urgent and inescapable.",
    ],
    vocabularyNotes: [
      { term: "cultural pluralism", zh: "文化多元主义" },
      { term: "conviviality", ipa: "/kənˌvɪviˈæləti/", zh: "和乐共处" },
      { term: "multiculturalism", zh: "多元文化主义" },
      { term: "assimilation", zh: "同化" },
      { term: "parallel lives", zh: "平行生活（互不交集的社群）" },
      { term: "cultural relativism", zh: "文化相对主义" },
      { term: "socially constructed", zh: "社会建构的" },
      { term: "marginalized", zh: "被边缘化的" },
      { term: "republican universalism", zh: "共和普遍主义" },
      { term: "melting pot", zh: "熔炉" },
      { term: "homogenizing", zh: "同质化" },
      { term: "appropriation", zh: "挪用" },
      { term: "hybrid", ipa: "/ˈhaɪbrɪd/", zh: "混合的；杂合" },
      { term: "imperiled", zh: "陷入危险的" },
    ],
    grammarNotes: [
      {
        topicId: "hedging-language",
        titleZh: "文化论述的审慎判断",
        noteZh: "may be / is likely to / arguably 对多样性的价值与后果保持分寸。",
        exampleFromText: "Each model embodies a particular answer... and each has produced its own successes and its own discontents",
      },
      {
        topicId: "nominalization",
        titleZh: "文化现象名词化",
        noteZh: "the recognition of difference / the fragmentation of society 抽象名词压缩复杂现象。",
        exampleFromText: "It has encouraged the fragmentation of society into separate... communities",
      },
      {
        topicId: "parallelism-rules",
        titleZh: "对比并列结构",
        noteZh: "between unity and diversity, between the common and the particular 平行短语展开张力。",
        exampleFromText: "between the claims of the common and the claims of the particular",
      },
      {
        topicId: "emphasis-structures-cleft",
        titleZh: "强调结构澄清观点",
        noteZh: "The aim is not to master or to own...; it is to encounter... 用 not...but 澄清意图。",
        exampleFromText: "The aim is not to master or to own the culture of another but to encounter it with openness and respect",
      },
      {
        topicId: "complex-sentences",
        titleZh: "让步与因果复合",
        noteZh: "Although they are united..., they remain differentiated 用让步承认统一。",
        exampleFromText: "...however much the fetish... they remain differentiated",
      },
      {
        topicId: "relative-clauses-defining-nondefining",
        titleZh: "关系从句界定理想",
        noteZh: "a condition sometimes described as parallel lives 提供定义性注解。",
        exampleFromText: "a condition sometimes described as parallel lives",
      },
    ],
    questions: [
      {
        questionEn: "What forces brought cultures into unprecedented contact?",
        questionZh: "什么力量使文化空前接触？",
        options: ["Geography", "Migration, trade, technology, and movement of people", "Isolation", "Climatic stasis"], answerIndex: 1,
        explainZh: "迁移、贸易、技术与人口流动使文化空前接触。",
      },
      {
        questionEn: "What does multiculturalism reject?",
        questionZh: "多元文化主义拒绝什么？",
        options: ["All diversity", "The older ideal of assimilation", "Common citizenship", "Civic framework"], answerIndex: 1,
        explainZh: "多元文化主义拒绝要求移民放弃自身文化、与多数人无异的同化理想。",
      },
      {
        questionEn: "What is 'parallel lives'?",
        questionZh: "'平行生活'指什么？",
        options: ["Same community", "Fragmented, non-interacting communities", "Full integration", "One shared life"], answerIndex: 1,
        explainZh: "指互不交集、各自为政的隔离社群状态。",
      },
      {
        questionEn: "What is the central problem of pluralism?",
        questionZh: "多元主义的核心问题是什么？",
        options: ["Too little contact", "The tension between unity and diversity", "Geographic spread", "Language only"], answerIndex: 1,
        explainZh: "如何在维护共同生活纽带与尊重成员多元之间求得平衡。",
      },
      {
        questionEn: "Which country pursues republican universalism?",
        questionZh: "哪个国家推行共和普遍主义？",
        options: ["US", "France", "UK", "Canada"], answerIndex: 1,
        explainZh: "法国推行对特定身份视而不见的共和普遍主义。",
      },
      {
        questionEn: "How has the US historically conceived of itself?",
        questionZh: "美国历史上如何自我构想？",
        options: ["A melting pot", "A patchwork only", "A confederation", "A monarchy"], answerIndex: 0,
        explainZh: "美国自视为把多元起源熔成单一美国认同的熔炉。",
      },
      {
        questionEn: "Why is the loss of languages a loss?",
        questionZh: "为何语言流失是损失？",
        options: ["They are tools", "They embody distinct ways of seeing the world, irreplaceable", "They cost little", "All share one"], answerIndex: 1,
        explainZh: "语言承载独特的世界观，其消亡是不可替代的人类多样性损失。",
      },
      {
        questionEn: "What paradoxical effect does the internet have?",
        questionZh: "互联网产生什么悖论效应？",
        options: ["Only homogenizes", "Empowers some cultures while homogenizing pressure", "Only empowers", "Has no effect"], answerIndex: 1,
        explainZh: "既让离散社群维系与发声，又施加巨大同质化压力。",
      },
      {
        questionEn: "What is the danger of cultural appropriation?",
        questionZh: "文化挪用的危险是什么？",
        options: ["Deep learning", "Extracting the enjoyable surface while ignoring meaning and people", "Respectful engagement", "Shared hybrid"], answerIndex: 1,
        explainZh: "把可消费的表层取走而忽略其背后的人与意义。",
      },
      {
        questionEn: "What does preservation of diversity NOT mean?",
        questionZh: "'保存多样性'不意味着什么？",
        options: ["Sustaining conditions for flourishing", "Freezing cultures in the past", "Supporting renewal", "Intermixing"], answerIndex: 1,
        explainZh: "不是把文化冻结在过去，而是维持其延续、交融与更新的条件。",
      },
    ],
    summaryTaskZh: "用不超过 90 个英文单词总结：作者如何论证多样性的价值？他如何看待多元文化主义及其批评？",
    opinionTaskZh: "The author frames the central problem as the tension between unity and diversity. Drawing on the text and your own view, argue whether a plural society should emphasize shared civic values or the distinct identities of its cultural groups. Write 150-180 words with one concessive clause.",
  },
  {
    id: "reading-20-future-of-work",
    number: 20,
    slug: "future-of-work",
    title: "Work in Transformation: Technology, Meaning, and the Uncertain Future of Labor",
    categoryZh: "工作的未来",
    difficulty: "C2",
    wordCount: 4000,
    minutes: 26,
    article: [
      "Work is among the most universal and defining of human activities. It is how most people earn a living, and it is also, for many, a central source of identity, purpose, and social standing. The question of what work is, what it is for, and how it is organized has engaged thinkers for centuries, and the present moment is one of acute and visible transformation, driven above all by technology. Automation, artificial intelligence, the platform economy, and the changing shape of the firm are reshaping the nature of employment, the content of jobs, and the very meaning of work. Understanding this transformation, and deciding how to respond to it, is among the most important tasks of the present generation.",
      "The history of work is a history of constant change, and the fear that machines would make human labor obsolete is nearly as old as industrialization itself. The Luddites of the early nineteenth century, who destroyed the machines they believed threatened their livelihoods, have become a byword for a futile resistance to inevitable progress. Yet their anxiety was not groundless, and the recurring worry that technological unemployment will finally arrive has never entirely disappeared. Through two centuries of mechanization, however, the overall demand for labor has not collapsed; new kinds of work have repeatedly emerged to replace those that were automated away. The question before us now is whether what we are experiencing with the rise of artificial intelligence is a continuation of that pattern or a fundamental break from it.",
      "The concept of technological unemployment, the idea that technology could displace more workers than it creates, was given its classic articulation by John Maynard Keynes, who pointed to the possibility that we were suffering from a new disease of which no one could name it. Keynes himself was not predicting permanent unemployment; he was concerned about the transitional disruption of the shift toward a world of less necessary work. The distinction between transitional and permanent effects is crucial. Most economists believe that the historical pattern — in which technology destroys some jobs and creates others, usually of different kinds — will continue, and that the real challenge is managing the transition, not the existence of labor itself. But the speed and scale of this transition are matters of genuine uncertainty and genuine consequence.",
      "The automation of routine tasks has already transformed vast sectors of the economy. Manufacturing, which once employed enormous numbers of workers in repetitive manual tasks, has become far more capital-intensive, using robots and machines to perform work that people once did. The same forces are now reaching into white-collar and cognitive work: tasks that follow recognizable patterns — data processing, translation, routine analysis, much of software writing — are increasingly within the reach of machines. The prediction that computers would not displace knowledge workers has been confounded, and the question of how far automation will reach into cognitive, professional, and creative work is open and contested.",
      "The rise of artificial intelligence marks a qualitatively new stage in this process. Earlier automation replaced specific tasks; AI, and above all large language models capable of generating text, code, and images, can perform a wider and more adaptable range of cognitive tasks, and it can continue to improve as the technology develops. The precise effects on employment are highly uncertain. Some commentators foresee the end of work as we know it, in which most current jobs are automated and society must confront the question of how to organize a world in which human labor is not needed. Others, more skeptical, point to the enduring importance of judgment, creativity, human relationships, and embodied presence, and argue that AI will augment rather than replace human workers in most domains. Both may be partly right, and the distribution of effects across sectors, occupations, and regions is likely to be highly uneven.",
      "The future of work will be shaped decisively by the organization of the firm and the nature of the platform economy. The platform economy has created remarkable flexibility and convenience, connecting workers to tasks and consumers to services through digital marketplaces. But it has also given rise to the gig economy, in which workers are classified as independent contractors rather than employees, and in which the protections, benefits, and stability that traditionally accompanied employment are often absent. The legal and moral status of gig work is the subject of intense debate: advocates celebrate its flexibility and autonomy, critics decry its precarity, its lack of security, and its shifting of risk from companies onto workers. How this debate is resolved — whether gig workers are recognized as workers, entitled to the protections of employment law — will shape the future of work for millions.",
      "The racial and gender dimensions of work are inescapable. Segregation in the labor market, in which certain kinds of work are coded as appropriate for certain groups and are accordingly valued and compensated differently, persists across societies. The gender pay gap, the underrepresentation of women in leadership, the concentration of both men and women in different occupations, and the disproportionate burden of unpaid care work that falls on women are all long-standing features of the organization of work. The recognition that work is gendered and racialized, and that the value assigned to different kinds of work reflects social hierarchies as much as intrinsic contribution, has become central to contemporary social and economic policy. The future of work will be just only if it confronts these legacies directly rather than reproducing them.",
      "The meaning of work, and its place in a good life, is a question that technology forces us to reconsider. For all its material necessity, work is rarely experienced as merely a means; it is a site of meaning-making, of social connection, and of self-definition. People derive from their work a sense of purpose, of competence, of contribution, and of belonging. If a large share of current work is automated, the question arises of what will provide these goods for those who are displaced. The answer cannot simply be that the displaced should become idle consumers, because idleness does not satisfy the human need for purpose and contribution. Societies will need to find ways to provide the benefits that work has historically provided − income, but also meaning, structure, and belonging − through new arrangements, whether through education, care, community, or creative activity, and this is a cultural as much as an economic challenge.",
      "Education and training are the principal instruments for adapting to the changing world of work, and the demands on them are intensifying. The skills that are valuable are shifting, away from the routine and the memorized and toward the analytical, the creative, and the social. Lifelong learning − the capacity to acquire new skills throughout life as the demands of work change − is increasingly essential, and both individuals and institutions are being called upon to develop it. Yet the systems of education and training, built on assumptions of a working life in which skills are acquired early and then applied steadily, are not well adapted to a world in which the half-life of skills is shrinking. The reform of education and the development of robust systems of retraining and upskilling are among the most consequential investments a society can make in its future of work.",
      "The role of government and of social policy will be decisive. In a world of greater uncertainty about the future of employment, the safety nets that protect people through transition become more important. Unemployment insurance, health care, and portable benefits that are not tied to a single employer are necessary to support workers in a more fluid labor market. There is increasing discussion of proposals like a universal basic income, which would provide every person a guaranteed income regardless of employment,",
      "distribution of the gains and losses of automation is a question of justice. If the productivity gains of new technology accrue largely to the owners of capital, while workers bear the costs of displacement and disruption, the transformation of work will deepen inequality rather than alleviate it. The historical lesson is that technological change does not determine its own distribution; the shares of capital and labor, and the fate of displaced workers, are shaped by institutions, by policy, and by the bargaining power of different groups. Whether the coming transformation produces broadly shared prosperity, or concentrated gains and widespread hardship, is not written in the technology but will be decided by collective choices about taxation, regulation, education, and the distribution of the gains.",
      "The promise of the transformation of work is a genuinely brighter future, in which drudgery and dangerous toil are reduced, in which creativity and care are liberated from the demands of repetition and quantity, and in which people have more time for family, community, learning, and leisure. The danger is a future of deep inequality, of wasted human potential, and of a society that has failed to adapt. Which future arrives depends on foresight and coordination. The fundamental alternatives are not between preserving the old world of work and embracing a new one; they are between treating the transformation as a threat to be resisted and as an opportunity to be shaped. The task of the present generation is to shape it − deliberately, justly, and with the full range of human creativity and care being brought to the center of what work is for.",
    ],
    vocabularyNotes: [
      { term: "obsolete", zh: "过时的；被淘汰的" },
      { term: "Luddite", ipa: "/ˈlʌdaɪt/", zh: "卢德派（反对机械化者）" },
      { term: "technological unemployment", zh: "技术性失业" },
      { term: "capital-intensive", zh: "资本密集的" },
      { term: "confounded", zh: "被证伪/被推翻" },
      { term: "platform economy", zh: "平台经济" },
      { term: "gig economy", zh: "零工经济" },
      { term: "precarity", ipa: "/prɪˈkærəti/", zh: "不稳定性" },
      { term: "labor market segregation", zh: "劳动力市场隔离" },
      { term: "categorical imperative", zh: "绝对命令（此处为哲学引用）" },
      { term: "lifelong learning", zh: "终身学习" },
      { term: "half-life of skills", zh: "技能半衰期" },
      { term: "universal basic income", zh: "全民基本收入" },
      { term: "portable benefits", zh: "可携带福利" },
    ],
    grammarNotes: [
      {
        topicId: "nominalization",
        titleZh: "论述工作的名词化",
        noteZh: "the displacement of workers / the distribution of gains 抽象名词压缩复杂过程。",
        exampleFromText: "the distribution of the gains and losses of automation is a question of justice",
      },
      {
        topicId: "hedging-language",
        titleZh: "对未来的审慎判断",
        noteZh: "is likely to / may be / arguably 对工作未来保持开放态度。",
        exampleFromText: "the distribution of effects... is likely to be highly uneven",
      },
      {
        topicId: "passive-across-tenses",
        titleZh: "被自动化与被组织的工人",
        noteZh: "are automated / are displaced / is recognized 强调工人与技术客体。",
        exampleFromText: "workers are classified as independent contractors rather than employees",
      },
      {
        topicId: "complex-sentences",
        titleZh: "条件与因果推演",
        noteZh: "If the productivity gains... accrue to capital... 用条件句推演后果。",
        exampleFromText: "If a large share of current work is automated, the question arises of what will provide these goods",
      },
      {
        topicId: "relative-clauses-defining-nondefining",
        titleZh: "关系从句界定现象",
        noteZh: "a condition that isolates... 用限定从句说明平台化后果。",
        exampleFromText: "workers who are displaced",
      },
      {
        topicId: "parallelism-rules",
        titleZh: "并列结构概括去处",
        noteZh: "for family, community, learning, and leisure 平行名词列举解放后的用途。",
        exampleFromText: "people have more time for family, community, learning, and leisure",
      },
    ],
    questions: [
      {
        questionEn: "What does the modern transformation focus on?",
        questionZh: "当代工作转型的焦点是什么？",
        options: ["Geography", "Technology, especially AI and automation", "Climate", "Farming"], answerIndex: 1,
        explainZh: "自动化、人工智能、平台经济等正在重塑工作性质与内容。",
      },
      {
        questionEn: "Who were the Luddites?",
        questionZh: "卢德派是什么人？",
        options: ["Loyalists", "Workers who destroyed machines threatening livelihoods", "Philosophers", "Bankers"], answerIndex: 1,
        explainZh: "19 世纪初毁坏机器的工人，被视为徒劳抵抗进步的代名词。",
      },
      {
        questionEn: "What did Keynes articulate?",
        questionZh: "凯恩斯阐明了什么？",
        options: ["Permanent prosperity for all", "The concept of technological unemployment", "The end of growth", "Free trade"], answerIndex: 1,
        explainZh: "凯恩斯谈及新技术可能造成的暂时性失业问题。",
      },
      {
        questionEn: "What has automation already transformed?",
        questionZh: "自动化已改造了什么？",
        options: ["Routine manual and now cognitive work", "Only farming", "No sector", "Only services"], answerIndex: 0,
        explainZh: "自动化已改造制造业等例行体力任务，并日益触及认知工作。",
      },
      {
        questionEn: "Why is AI a qualitatively new stage?",
        questionZh: "为何 AI 是性质不同的新阶段？",
        options: ["It replaces specific tasks only", "It performs wider adaptable cognitive tasks and improves", "It is inert", "It only speeds up"], answerIndex: 1,
        explainZh: "AI 能执行更广泛、可适应的认知任务并随技术改进而提升。",
      },
      {
        questionEn: "What characterizes the gig economy?",
        questionZh: "零工经济的特征是什么？",
        options: ["Full employee benefits", "Workers classified as independent contractors, often without stability", "Guaranteed income", "Lifetime tenure"], answerIndex: 1,
        explainZh: "工人被归类为独立承包人，常缺乏稳定与福利。",
      },
      {
        questionEn: "Why is idleness not a satisfactory answer?",
        questionZh: "为何'无所事事'不是令人满意的答案？",
        options: ["It is efficient", "It does not satisfy the need for purpose and contribution", "It is universal", "It makes money"], answerIndex: 1,
        explainZh: "闲散无法满足人类对目标与贡献的需要。",
      },
      {
        questionEn: "What is the half-life of skills argument?",
        questionZh: "'技能半衰期'的论证是什么？",
        options: ["Skills last forever", "Skills become obsolete faster, so lifelong learning is essential", "No retraining needed", "Skills are fixed"], answerIndex: 1,
        explainZh: "技能过时更快，终身学习的必要性与日俱增。",
      },
      {
        questionEn: "What is a universal basic income?",
        questionZh: "'全民基本收入'是什么？",
        options: ["Tax for rich", "Guaranteed income to every person regardless of employment", "Only for the poor", "A loan"], answerIndex: 1,
        explainZh: "无论就业状况如何为每人提供有保障的收入。",
      },
      {
        questionEn: "What determines the distribution of automation's gains?",
        questionZh: "什么决定自动化收益的分配？",
        options: ["Technology alone", "Institutions, policy, and bargaining power", "Nature", "Chance"], answerIndex: 1,
        explainZh: "分配由制度、政策与各方谈判力量决定，而非技术本身。",
      },
    ],
    summaryTaskZh: "用不超过 90 个英文单词总结：作者如何评估 AI 对就业的影响？他认为工作的意义何在，社会应如何应对转型？",
    opinionTaskZh: "The author contrasts two possible futures for work. Drawing on the text and your own view, argue whether governments should respond to automation by expanding universal basic income or by investing in retraining and education. Write 150-180 words with one concessive clause.",
  },
  {
    id: "reading-21-globalization",
    number: 21,
    slug: "globalization",
    title: "One World, Many Worlds: The Contested Story of Globalization",
    categoryZh: "全球化",
    difficulty: "C2",
    wordCount: 4100,
    minutes: 27,
    article: [
      "Globalization is one of the most powerful and, at the same time, most misunderstood forces of the modern world. It denotes the growing interconnectedness of the world — the intensification of cross-border flows of goods, services, capital, technology, people, and ideas — and the sense that distant events now shape local lives as never before. Globalization is not a single, uniform process but a bundle of distinct but interwoven forces, economic and cultural, technological and political. And its history is not a simple story of inevitable progress but a contested narrative, marked by periods of rapid integration and of sharp reversal, by great achievements and by profound discontents. To understand the present and the probable future, it is necessary to understand this long, uneven, and unfinished history.",
      "The deep history of globalization predates the modern era by centuries. The Silk Road connected China, Central Asia, and Europe through streams of trade, religion, and culture, carrying not only silk and spice but also ideas, technologies, and diseases. The Mongol Empire, stretching across Eurasia, facilitated a remarkable period of exchange. The transatlantic and trans-Indian ocean routes established by European empires from the sixteenth century onward created something more fully global: a network of trade linking continents, an exchange of crops and peoples, and, in its cruelest manifestations, the transatlantic slave trade and the expropriation of colonial lands and labor. These early globes were shaped decisively by violence and by unequal power, and modern globalization carries the legacies of that history in its distribution of wealth and its structures of power.",
      "The industrial era marked a decisive intensification of global interconnection. The spread of the railroad, the steamship, and, above all, the telegraph and the undersea cable collapsed the costs of transportation and communication, enabling a volume and speed of trade, capital movement, and information flow that had been unimaginable. The late nineteenth century, up to the First World War, is sometimes called the first great age of globalization, a period in which trade, migration, and capital crossed borders with remarkable freedom. Hundreds of millions of people migrated between continents; capital moved essentially without restriction. But this age of openness was built on a foundation of imperial power and was shattered, and followed by a dramatic reversal, in the wars and protectionism of the early twentieth century.",
      "The mid-twentieth century witnessed a retreat from, and then a deliberate rebuilding of, the global order. The Great Depression had spawned a war of trade barriers and currency devaluations, the beggar-thy-neighbor policies that deepened and prolonged the suffering. The architects of the postwar settlement, meeting at Bretton Woods, resolved to build a more open and stable order. The institutions they created — the international monetary system, the General Agreement on Tariffs and Trade, and its successor the World Trade Organization — were designed to promote trade liberalization, stable currencies, and economic reconstruction. This deliberate project of building openness, in contrast to the assumed naturalness of the earlier era, marked a new understanding: that the global economy is a human construction, requiring institutions, rules, and ongoing management.",
      "The late twentieth century brought liberalization to new heights, and the extraordinary growth of the global economy during this period lifted hundreds of millions of people out of poverty, most importantly in East Asia and in China, whose opening transformed the global division of labor. The collapse of the communist systems in Eastern Europe and the Soviet Union, and the broader embrace of market economics, drew more of the world into the global economy than ever before. The internet, commercialized in the 1990s, created the possibility of global communication and coordination on an unprecedented scale. For a period, it was possible to believe that globalization was a natural and unstoppable force, a rising tide that would lift all boats and produce a single, peaceful, prosperous, and increasingly homogeneous world.",
      "That narrative, however, was never more than partially true, and it has come under sustained challenge in the past two decades. The financial crisis of 2008 showed the enormous fragility of the interconnected system, as a crisis that began in the American housing market propagated around the world, demonstrating that integration transmits shocks as readily as it spreads prosperity. The unevenness of globalization's benefits, and the dislocation it imposed on particular regions, industries, and workers, generated a powerful political backlash. And the rise of a multipolar world, in which no single power or set of institutions commands the global order, has made cooperation harder and competition more salient. The result has been a period of stagnation, retrenchment, and reordering that has led many to speak of a retreat from, or the end of, globalization — though the reality is more nearly a transformation of its character.",
      "The economic dimension of contemporary globalization is characterized less by the simple expansion of trade than by the depth of the global supply chain and the integration of production. Tasks are fragmented across borders, with design, components, assembly, and distribution occurring in different countries, and the resulting interdependence is both a source of efficiency and a source of vulnerability, as the pandemic vividly demonstrated. At the same time, the great wave of trade expansion has slowed, and in some respects reversed, as firms and governments seek to build resilience, to reshore production, and to reduce dependence on strategic adversaries. The transition from a globalization defined by cost and efficiency to one defined by security and resilience is one of the defining features of the present.",
      "Cultural globalization has its own trajectory, and its own contests. The global circulation of media, music, film, and food has created a common cultural vocabulary that spans the world, spreading styles, sensibilities, and aspirations. For some, this represents a welcome enrichment and a collective heritage; for others, it threatens the distinctiveness and vitality of local cultures, and the dominance of a few cultural producers, above all Hollywood and the global platforms, raises the specter of homogenization. The digital age has simultaneously empowered cultural minorities to reach the world and exposed all cultures to overwhelming competitive pressure from the most powerful producers. Cultural globalization is therefore experienced very differently, as an opportunity by some and as a threat by others, and the management of that tension is a running concern.",
      "The environmental dimension of globalization is among its most consequential and least manageable legacies. The globalization of production and consumption has dramatically raised the material throughput of the world economy, and the environmental costs − above all carbon emissions driving climate change, but also resource depletion, pollution, and the loss of biodiversity − are distributed across the planet. Because the atmosphere, the oceans, and the climate are global commons, no single nation can solve environmental problems alone, and the challenge of coordinating collective action across sovereign states is among the most difficult in global governance. The recognition that the world economy and the earth's systems are inseparably linked has placed environmental stewardship at the center of the question of how globalization is to be governed.",
      "The governance of globalization, or its lack, is a central theme. The international institutions created in the mid-twentieth century are increasingly ill-suited to the problems of the twenty-first: the WTO is paralyzed in its negotiating function, the international financial institutions are contested, and the United Nations is hamstrung in the face of the great-power tensions of a multipolar world. New problems − digital trade, data flows, artificial intelligence, pandemic preparedness, climate − do not fit neatly into the existing institutional architecture, and the world's capacity for collective action has lagged behind the scale of its shared challenges. The question of whether, and how, the global order can be reformed to manage the forces it has unleashed is open and urgent.",
      "The question of sovereignty is central to the politics of globalization. The deepening of cross-border flows challenges the traditional conception of the sovereign state, in which each government exercises exclusive authority within its borders. Capital, data, pollution, viruses, and ideas do not respect those borders, and no state can fully control the forces that shape its own economy and society. Some welcome this as a necessary accommodation to a more interconnected world, while others see it as a threat to democratic self-government, in which a people's capacity to shape its own future is endangered by forces beyond its control. The tension between the global and the national, between the claims of the international community and the claims of sovereignty, runs through every dimension of the contemporary debate.",
      "The backlash against globalization has generated a politics of re-embedding, of seek to regain a degree of national control over forces that had seemed uncontrollable. Trade disputes, industrial policy, border controls, data localization, and a general wariness of unconstrained openness have become staples of the political agenda around the world. The danger is that the response to the real discontents of globalization descends into a self-defeating protectionism and nationalism. The better response, which many advocate, is not to attempt the impossible reversal of interconnection but to build a different kind of globalization − one that is more equitable, more resilient, more sustainable, and more democratic, one that preserves the real gains of openness while correcting its failures and sharing its benefits far more broadly than they have been.",
      "The future of globalization will not be a simple continuation of the past, nor a simple return to protectionism. It will be shaped by a set of contending forces: the persistent attractions and efficiencies of interconnection, the demands for resilience and security, the struggles over distribution and equity, and the imperatives of environmental sustainability. The most likely outcome is not a single, coherent trajectory but a complex and contested process, one in which different kinds of connections deepen in some areas even as they are severed or managed in others. What can be said with confidence is that the era of naive and unguarded openness is over, and the era in which the shape of globalization is a matter of contested political choice, rather than of automatic gravity, has begun. Whether the world navigates that choice toward a more just and sustainable form of interconnection, or toward a resentful and destructive fragmentation, is the central question of the age, and it will be answered less by the forces of history than by the foresight and the will of the people and the societies that make them.",
    ],
    vocabularyNotes: [
      { term: "interconnectedness", zh: "相互关联性" },
      { term: "Silk Road", zh: "丝绸之路" },
      { term: "expropriation", ipa: "/ɪkˌsproʊpriˈeɪʃən/", zh: "侵夺/征收" },
      { term: "beggar-thy-neighbor", zh: "以邻为壑（损人利己）" },
      { term: "Bretton Woods", zh: "布雷顿森林（体系）" },
      { term: "liberalization", zh: "自由化" },
      { term: "multipolar", zh: "多极（的）" },
      { term: "retrenchment", zh: "收缩；紧缩" },
      { term: "glob commons", zh: "全球公域" },
      { term: "homogenization", ipa: "/həˌmɑdʒənəˈzeɪʃən/", zh: "同质化" },
      { term: "material throughput", zh: "物质吞吐量" },
      { term: "sovereignty", zh: "主权" },
      { term: "re-embedding", zh: "再嵌入（重新纳入国家管控）" },
      { term: "resilience", ipa: "/rɪˈzɪliəns/", zh: "韧性" },
    ],
    grammarNotes: [
      {
        topicId: "nominalization",
        titleZh: "全球化论述的名词化",
        noteZh: "the intensification of cross-border flows / the expropriation of lands 抽象名词表达宏观过程。",
        exampleFromText: "the intensification of cross-border flows of goods, services, capital...",
      },
      {
        topicId: "hedging-language",
        titleZh: "对全球化的审慎判断",
        noteZh: "may be/ is likely to / arguably 对复杂趋势保持分寸。",
        exampleFromText: "the most likely outcome is not a single, coherent trajectory but a complex and contested process",
      },
      {
        topicId: "passive-across-tenses",
        titleZh: "被塑造与被治理的世界",
        noteZh: "are severed / are transmitted / is injected 强调制度的被动客体性。",
        exampleFromText: "integration transmits shocks as readily as it spreads prosperity",
      },
      {
        topicId: "complex-sentences",
        titleZh: "让步与条件复合",
        noteZh: "Because the atmosphere... are global commons, no single nation can solve... 用 because 论证集体行动必要。",
        exampleFromText: "Because the atmosphere, the oceans, and the climate are global commons, no single nation can solve environmental problems alone",
      },
      {
        topicId: "relative-clauses-defining-nondefining",
        titleZh: "关系从句界定历史",
        noteZh: "a period that saw... 用从句注解历史时期。",
        exampleFromText: "The late nineteenth century... a period in which trade, migration, and capital crossed borders with remarkable freedom",
      },
      {
        topicId: "emphasis-structures-cleft",
        titleZh: "强调结构澄清结局",
        noteZh: "What can be said with confidence is that... 用 what 从句突出可确定结论。",
        exampleFromText: "What can be said with confidence is that the era of naive and unguarded openness is over",
      },
    ],
    questions: [
      {
        questionEn: "What does globalization denote?",
        questionZh: "'全球化'意指什么？",
        options: ["Isolation", "Growing interconnectedness across borders", "Uniformity", "Nationalism"], answerIndex: 1,
        explainZh: "指跨境商品、服务、资本、技术、人口与思想流动的加剧。",
      },
      {
        questionEn: "What facilitated exchange in the deep history of globalization?",
        questionZh: "全球化早期历史中什么促进了交流？",
        options: ["The internet", "The Silk Road and Mongol Empire", "The steam engine", "Video calls"], answerIndex: 1,
        explainZh: "丝绸之路与蒙古帝国连接中国、中亚与欧洲，促成大量交流。",
      },
      {
        questionEn: "What marked the first great age of globalization?",
        questionZh: "第一次全球化大时代以什么为特征？",
        options: ["Trade barriers", "Free trade, migration, and capital flows in the late 19th century", "Isolation", "Autarky"], answerIndex: 1,
        explainZh: "十九世纪末贸易、移民与资本跨境流动高度自由。",
      },
      {
        questionEn: "Why was Bretton Woods important?",
        questionZh: "布雷顿森林为何重要？",
        options: ["It ended trade", "It deliberately rebuilt a more open and stable global order", "It split the world", "It banned finance"], answerIndex: 1,
        explainZh: "其建筑师有意识地重建更开放稳定的全球秩序。",
      },
      {
        questionEn: "What did the 2008 crisis demonstrate?",
        questionZh: "2008 年危机证明了什么？",
        options: ["Integration is safe", "Integration transmits shocks as readily as prosperity", "Markets are isolated", "No coupling"], answerIndex: 1,
        explainZh: "相互依存既传播繁荣也传播冲击。",
      },
      {
        questionEn: "What characterizes contemporary economic globalization?",
        questionZh: "当代经济全球化的特征是什么？",
        options: ["Simple expansion", "Depth of global supply chains and integration of production", "Bilateral deals only", "Autarky"], answerIndex: 1,
        explainZh: "生产跨任务碎片化，既有高效也有脆弱。",
      },
      {
        questionEn: "Why is cultural globalization experienced differently?",
        questionZh: "为何文化全球化体验不同？",
        options: ["Everyone gains", "As opportunity by some, threat by others", "No effect", "Uniformly negative"], answerIndex: 1,
        explainZh: "有人视之为丰富机会，有人视之为本地文化之威胁。",
      },
      {
        questionEn: "Why can no single nation solve environmental problems?",
        questionZh: "为何没有国家能单独解决环境问题？",
        options: ["They are local", "Atmosphere, oceans, climate are global commons demanding collective action", "They are easy", "National laws suffice"], answerIndex: 1,
        explainZh: "大气、海洋与气候是全球公域，需跨主权协调。",
      },
      {
        questionEn: "What is the problem with the WTO?",
        questionZh: "世贸组织的问题是什么？",
        options: ["It is too strong", "Its negotiating function is paralyzed", "It is new", "It governs nothing"], answerIndex: 1,
        explainZh: "世贸组织的谈判职能陷入瘫痪。",
      },
      {
        questionEn: "How does the author characterize the likely future?",
        questionZh: "作者如何形容可能的未来？",
        options: ["Single trajectory", "A complex, contested process, not simple continuation or return to protectionism", "Full reversal", "Perfect openness"], answerIndex: 1,
        explainZh: "未来不是简单延续也非回归保护主义，而是复杂而充满争议的过程。",
      },
    ],
    summaryTaskZh: "用不超过 90 个英文单词总结：作者如何看待全球化的历史分期？当前全球化面对哪些挑战与可能的再秩序化？",
    opinionTaskZh: "The author argues that globalization's shape is now a matter of contested political choice. Drawing on the text and your own view, argue whether nations should prioritize national resilience or global cooperation in responding to the failures of globalization. Write 150-180 words with one concessive clause.",
  },
];
