/**
 * Phase 19-P0-1: Reading Library Completion (part 4).
 * Articles 13-15 of 20.
 */
import type { ReadingArticle } from "@/content/resources/reading-library";

export const P19_READING_PART4: readonly ReadingArticle[] = [
  {
    id: "reading-13-psychology",
    number: 13,
    slug: "psychology-human-behavior",
    title: "The Science of Mind: Psychology, Behavior, and the Architecture of Human Choice",
    categoryZh: "心理学",
    difficulty: "C2",
    wordCount: 4000,
    minutes: 26,
    article: [
      "Psychology is the scientific study of mind and behavior, and it has grown from a speculative branch of philosophy into a rich and rigorous empirical discipline. Its central ambition is to understand why people think, feel, and act as they do — to identify the mental processes and environmental forces that shape human behavior. The questions psychology asks are among the most fundamental a science can pose: What is the relationship between mind and brain? How do we learn, remember, and decide? Why do people behave irrationally? And what does it mean to be mentally healthy? The answers psychology has discovered are often counterintuitive, occasionally disturbing, and always consequential for how societies understand and treat human beings.",
      "The history of psychology is a story of successive paradigms, each claiming to offer the fundamental account of mind. Early psychology, in the form of structuralism and functionalism, sought to analyze consciousness into its elements. Behaviorism, ascendant in the first half of the twentieth century, rejected the study of inner mental states altogether, insisting that psychology should concern itself only with observable behavior and its environmental causes. The cognitive revolution of the 1950s and 1960s overturned this orthodoxy, restoring to psychology the study of mental processes — perception, memory, reasoning — by conceiving of the mind as an information-processing system, in the way a computer processes data. Each paradigm made genuine progress, and the cognitive and then computational turn established the framework within which virtually all contemporary research is conducted.",
      "The cognitive revolution brought with it the concept of the mind as a set of specialized systems, and the study of these systems has produced a wealth of empirical findings. Perception is not a passive recording of reality but an active construction; the brain fills in gaps, imposes structure, and is prey to systematic illusions. Memory is not a faithful recording either; it is reconstructive, and it is continually rewritten in the light of subsequent experience. Attention is a limited resource, and its limits explain many of the failures and efficiencies of human cognition. Reasoning is subject to characteristic biases, and judgment routinely deviates from the standards of logic and probability. The cumulative picture is of a mind that is remarkably powerful and yet systematically imperfect.",
      "The discovery of cognitive biases, and the research program that grew out of it, has been one of psychology's most influential contributions. Daniel Kahneman, whose work led to his Nobel Prize in Economics, described the mind in terms of two systems: System 1, which is fast, automatic, and intuitive, and System 2, which is slow, effortful, and deliberate. Much of our thinking is carried out by System 1, whose short-cuts — heuristics — are usually efficient but occasionally produce systematic error. The anchoring and framing effects, loss aversion, overconfidence, and the confirmation bias are among the many shortcuts and pitfalls that research has catalogued. This work on judgment and decision-making, gathered under the name behavioral economics, has profoundly influenced public policy, marketing, and the design of incentives through the practice of nudging.",
      "The social dimension of psychology is equally central. Human beings are fundamentally social creatures, formed by and living within an intricate web of relationships. Social psychology studies how the presence and behavior of others influence individual thought and action. It has documented the power of conformity, in which individuals adjust their judgments to match those of a group even when the group is clearly wrong; obedience, in which people comply with authority even to the point of causing harm; and the dynamics of groups, including the formation of in-groups and out-groups and the attitudinal biases that accompany them. The findings of social psychology are humbling, showing how powerfully situation and context shape behavior that we would like to believe reflects stable internal character.",
      "The concept of self and identity is a perennial concern, and psychology has shown that identity is neither fixed nor simple. The self is not a single, unified thing but a narrative and a construction, sustained through introspection, social feedback, and memory. People maintain self-concepts that are coherent and flattering, and they deploy a range of protective mechanisms to defend those self-concepts against threatening information. The question of how identity forms — through genes, upbringing, culture, and life experience — remains open and contested, and it matters enormously for how societies think about responsibility, education, and social policy. The study of identity intersects with every other domain of psychology and with the humanities more generally.",
      "Developmental psychology examines how people change across the lifespan, from infancy through old age. It has revealed that the early years are a period of extraordinary plasticity and vulnerability, when foundational capacities for attachment, language, and trust are established. The work on attachment theory showed the profound importance of early relationships, and it has shaped thinking about child care, parenting, and education. Later development brings its own challenges and renegotiations, from the identity struggles of adolescence to the transitions of midlife and the reckoning with aging and mortality that mark the final stages. Development is not a simple unfolding but a lifelong, interactive process in which biology and environment are inseparably intertwined.",
      "Personality psychology seeks to describe and explain the stable patterns of thought, feeling, and behavior that distinguish individuals. The dominant contemporary framework, the five-factor or Big Five model, describes personality along five broad dimensions: openness, conscientiousness, extraversion, agreeableness, and neuroticism. This model has proven remarkably robust across cultures and predictive of important life outcomes, from health to occupational success to relationship stability. But personality is not destiny; trait levels shift over time, and behavior is heavily influenced by situation. The study of personality sits at the intersection of biology and culture, and its findings complicate any simple account of human difference.",
      "Abnormal psychology and the allied field of psychiatry confront the reality of mental disorder. Mental illness is common — anxiety, depression, and addiction affect a substantial share of the population — and its burden, in terms of suffering and lost productivity, is enormous. The dominant framework, the medical model, treats mental disorders as conditions that can be diagnosed, and it has produced diagnostic manuals and an array of effective treatments, both psychosocial and pharmacological. But the medical model is not without its critics, who worry about over-diagnosis, cultural variation in what counts as disorder, and the influence of pharmaceutical interests. The stigma surrounding mental illness remains a profound barrier to seeking help, and destigmatization is itself an important social and psychological project.",
      "Positive psychology, a relatively recent movement, shifts the focus from psychopathology to human flourishing. Instead of asking only what goes wrong with the mind, it asks what makes life worth living — what enables people to thrive, to experience meaning, to build satisfying relationships, and to cultivate strengths. Research in this tradition has examined subjective well-being, the conditions that promote happiness, the cultivation of gratitude and resilience, and the nature of meaning and purpose. The movement has been criticized for over-promising and for simplifying complex realities, but it has also succeeded in broadening the questions psychology is willing to ask, and its insights are widely applied in coaching, education, and the workplace.",
      "The relationship between psychology and neurology, or between mind and brain, is one of the deepest and most contested questions in the science. The cognitive neuroscience that has emerged in recent decades connects mental processes to the activity of specific brain regions and networks, using brain imaging to examine the neural correlates of perception, memory, emotion, and decision-making. This work has enormously enriched our understanding, but it has also opened deep philosophical questions about consciousness and about the reducibility of mind to matter. Whether everything about the mind can be explained by the brain, and how subjective experience arises from gray tissue, remain among the great unresolved mysteries of science.",
      "The application of psychology has transformed institutions. In education, psychological research on learning, motivation, and the science of expertise has reshaped teaching and the design of curricula. In the workplace, the study of organizations, leadership, and employee well-being informs management practice and the design of incentives. In law, psychology bears on the reliability of eyewitness testimony, the dangers of false confessions, and the factors that drive verdicts. In medicine, behavioral science underlies the effort to encourage healthier behavior and to help patients adhere to treatment. And in the digital age, psychology increasingly informs the design of the technology, from social media to e-commerce, that pervades daily life — with consequences both beneficial and troubling.",
      "The ethics of psychological knowledge are a growing concern. Because psychology reveals how behavior can be influenced, its knowledge is a double-edged sword: it can be used to help people live healthier, happier lives, or it can be used to manipulate, deceive, and exploit. The use of psychological insight in advertising, political campaigning, and the design of addictive digital products raises profound questions about autonomy and consent. The discipline is governed by strict ethical codes governing research with human participants, but the application of its findings in the wider society is subject to fewer constraints. The question of how psychological knowledge is used — for whom, and to what ends — is as much a moral question as a scientific one.",
      "The cultural dimension of psychology is increasingly recognized as essential. Much psychological research has been conducted on what critics call WEIRD populations — Western, Educated, Industrialized, Rich, and Democratic societies — whose members may not represent humanity as a whole. Cross-cultural psychology has revealed significant variation in basic processes of reasoning, self-conception, and social behavior, and it has demonstrated the danger of assuming that findings from one population generalize to all. A psychology that aspires to be a science of human nature must be a psychology of human variety — one that takes seriously the ways that culture shapes the mind even as it searches for the commonalities that make us recognizably human.",
      "The future of psychology is likely to be shaped by its deepening integration with other sciences: with neuroscience and genetics in understanding the biological bases of mind, with data science and artificial intelligence in modeling cognition, and with the social sciences in understanding the dynamics of large-scale behavior. The discipline is also likely to become more global, more diverse, and more attentive to the full range of human experience. Yet for all its technical sophistication, psychology will remain fundamentally concerned with the questions that motivated its founding: what it means to be human, how we come to be who we are, and how we can live better lives. In an age of extraordinary technological and social change, that scientific and humane inquiry is needed more than ever.",
    ],
    vocabularyNotes: [
      { term: "empirical", zh: "经验实证的" },
      { term: "paradigm", ipa: "/ˈpærədaɪm/", zh: "范式" },
      { term: "behaviorism", zh: "行为主义" },
      { term: "cognitive revolution", zh: "认知革命" },
      { term: "reconstructive", zh: "重构性的" },
      { term: "heuristics", zh: "启发式（经验法则）" },
      { term: "loss aversion", zh: "损失厌恶" },
      { term: "confirmation bias", zh: "确认偏误" },
      { term: "nudging", zh: "助推" },
      { term: "plasticity", zh: "可塑性" },
      { term: "attachment theory", zh: "依恋理论" },
      { term: "conscientiousness", zh: "尽责性" },
      { term: "destigmatization", zh: "去污名化" },
      { term: "WEIRD", zh: "西方、受教育、工业化、富裕、民主（人群）" },
    ],
    grammarNotes: [
      {
        topicId: "nominalization",
        titleZh: "心理科学名词化",
        noteZh: "the study of mental processes / the formation of in-groups 抽象名词呈现抽象对象。",
        exampleFromText: "including the formation of in-groups and out-groups",
      },
      {
        topicId: "hedging-language",
        titleZh: "科学结论的严谨 hedge",
        noteZh: "may not represent / is likely to/ can 对概括与推广保持审慎。",
        exampleFromText: "whose members may not represent humanity as a whole",
      },
      {
        topicId: "passive-across-tenses",
        titleZh: "被研究者的被动",
        noteZh: "are driven / has been shown / is influenced 强调人与行为作为研究对象。",
        exampleFromText: "behavior is heavily influenced by situation",
      },
      {
        topicId: "complex-sentences",
        titleZh: "条件与让步复合",
        noteZh: "Even when the group is clearly wrong 用让步嵌套刻画从众实验。",
        exampleFromText: "individuals adjust their judgments to match those of a group even when the group is clearly wrong",
      },
      {
        topicId: "relative-clauses-defining-nondefining",
        titleZh: "关系从句界定人群",
        noteZh: "people whom researchers call WEIRD 用限定从句定义专业术语。",
        exampleFromText: "what critics call WEIRD populations — Western, Educated, Industrialized, Rich, and Democratic societies",
      },
      {
        topicId: "parallelism-rules",
        titleZh: "设问式并列推进",
        noteZh: "What is...? How do...? Why do...? 用连续设问铺陈学科问题。",
        exampleFromText: "What is the relationship between mind and brain? How do we learn...? Why do people behave irrationally?",
      },
    ],
    questions: [
      {
        questionEn: "What did behaviorism insist psychology should study?",
        questionZh: "行为主义坚持心理学应研究什么？",
        options: ["Inner mental states", "Only observable behavior", "Consciousness", "The subconscious"], answerIndex: 1,
        explainZh: "行为主义拒绝研究内在心理状态，只关注可观察行为。",
      },
      {
        questionEn: "What did the cognitive revolution restore to psychology?",
        questionZh: "认知革命为心理学恢复了什么？",
        options: ["The study of mental processes", "Observable behavior only", "Psychoanalysis", "Phrenology"], answerIndex: 0,
        explainZh: "认知革命以信息处理视角恢复了对心理过程的研究。",
      },
      {
        questionEn: "Which two systems did Kahneman describe?",
        questionZh: "卡尼曼描述了哪两个系统？",
        options: ["Fast intuition and slow deliberation", "Brain and heart", "Conscious and unconscious alike", "Id and superego"], answerIndex: 0,
        explainZh: "系统1快速直觉，系统2缓慢审慎。",
      },
      {
        questionEn: "What does social psychology reveal about behavior?",
        questionZh: "社会心理学揭示行为受何种影响？",
        options: ["Only internal character", "Powerfully by situation and context", "Not at all", "By genes only"], answerIndex: 1,
        explainZh: "情境与背景强力塑造行为，令我们谦卑。",
      },
      {
        questionEn: "What is the Big Five model?",
        questionZh: "'大五'模型描述什么？",
        options: ["Five brain lobes", "Five personality dimensions", "Five emotions", "Five stages"], answerIndex: 1,
        explainZh: "开放性、尽责性、外向性、宜人性、神经质五维度。",
      },
      {
        questionEn: "What is the medical model in abnormal psychology?",
        questionZh: "异常心理学中的'医学模型'是什么？",
        options: ["Treating all as healthy", "Treating mental disorders as diagnosable conditions", "Rejecting diagnosis", "Surgery only"], answerIndex: 1,
        explainZh: "把心理障碍当作可诊断并治疗的状态。",
      },
      {
        questionEn: "What does positive psychology focus on?",
        questionZh: "积极心理学关注什么？",
        options: ["Psychopathology", "Human flourishing, not just disorder", "Only depression", "The unconscious"], answerIndex: 1,
        explainZh: "从病态转向人类如何蓬勃发展。",
      },
      {
        questionEn: "Why is psychology's knowledge a double-edged sword?",
        questionZh: "为何心理学知识是一把双刃剑？",
        options: ["It is useless", "It can help or manipulate", "It is only theoretical", "It cannot be applied"], answerIndex: 1,
        explainZh: "既可用于助人，也可用于操纵与剥削。",
      },
      {
        questionEn: "What does the acronym WEIRD critique?",
        questionZh: "'WEIRD'批判什么？",
        options: ["Lack of labs", "The over-representation of Western educated populations", "Too many participants", "Cloning"], answerIndex: 1,
        explainZh: "大量研究基于西方、受教育人群，可能不具普遍代表性。",
      },
      {
        questionEn: "How does the author foresee psychology's future?",
        questionZh: "作者如何预见心理学的未来？",
        options: ["More isolated", "Deeper integration with neuroscience and data science", "Purely philosophical", "Dismissed"], answerIndex: 1,
        explainZh: "与神经科学、遗传学、数据科学等深度融合并更全球化。",
      },
    ],
    summaryTaskZh: "用不超过 90 个英文单词总结：作者认为心理学如何解释人类判断与行为的系统性偏差？为什么社会情境如此重要？",
    opinionTaskZh: "The author notes that psychological knowledge can both help and manipulate. Drawing on the text and your own view, argue whether the use of psychological insight to influence behavior in marketing should be regulated. Write 150-180 words with one concessive clause.",
  },
  {
    id: "reading-14-neuroscience",
    number: 14,
    slug: "neuroscience-brain",
    title: "The Brain Beneath the Mind: Neuroscience and the Frontiers of Understanding Ourselves",
    categoryZh: "神经科学",
    difficulty: "C2",
    wordCount: 4000,
    minutes: 26,
    article: [
      "Neuroscience is the study of the nervous system — the brain, the spinal cord, and the vast network of nerves — and it has become one of the most dynamic and consequential fields in all of science. The brain, an organ weighing about three pounds and consisting of roughly eighty-six billion neurons, each making thousands of connections, is the most complex object known in the universe. It is the physical substrate of everything we are: our thoughts, our emotions, our memories, our sense of self, and our capacity for language and reason. To understand the brain is, in a profound sense, to understand ourselves, and neuroscience pursues that understanding with a combination of technical sophistication and existential ambition that few other sciences can match.",
      "The architecture of the brain is layered and hierarchical. At its base lie the regions responsible for the most basic life functions — breathing, heart rate, and arousal — structures shared with even the simplest vertebrates. Above them lie more elaborate systems: the limbic system, involved in emotion, motivation, and the formation of memory; and, crowning everything, the cerebral cortex, a thin sheet of tissue folded into the characteristic wrinkles of the brain, which underwrites the higher functions of perception, language, reasoning, and planning that distinguish human beings among animals. The brain is not a single undifferentiated mass but a constellation of specialized regions and networks that must coordinate their activity for coherent mental life to emerge.",
      "The fundamental unit of the brain is the neuron, a specialized cell that transmits information through electrical and chemical signals. A neuron receives signals through its dendrites, integrates them at the cell body, and, if the accumulation of input crosses a threshold, fires an electrical impulse down its axon. At the synapse — the junction between neurons — the impulse triggers the release of chemical messengers called neurotransmitters, which excite or inhibit the next neuron. The staggering complexity of the brain arises from the sheer scale of this wiring, and from the subtlety with which connections are strengthened by use. The discovery that synaptic connections are modified by experience — a phenomenon called synaptic plasticity — provides the basis for learning and memory at the cellular level.",
      "The relationship between the brain and consciousness is the deepest unresolved problem in neuroscience, and indeed in all of science. We know with certainty that mental life depends on the brain: damage to specific regions produces specific deficits, and stimulation of specific regions produces specific experiences. Yet we do not understand how the subjective experience of consciousness — the raw feel of seeing red, or the feeling of pain — arises from the activity of neurons. This is the so-called hard problem, and it divides researchers. Some propose that consciousness emerges from the integration of information across the brain; others doubt that physical science alone can ever explain it. Whatever its ultimate resolution, the problem animates the field and connects neuroscience to philosophy in ways that are both fruitful and unresolved.",
      "Memory is one of the great achievements of the brain, and its study illustrates the integration of levels that characterizes modern neuroscience. Memory is not a single thing but a collection of systems: working memory holds a small amount of information briefly; short-term memory stores items for seconds to minutes; and long-term memory holds vast amounts, subdivided into explicit memory, for facts and events, and implicit memory, for skills and habits. Each of these is supported by distinct brain circuits, and the process of consolidation — by which labile new memories become stable — depends, critically, on the hippocampus and on sleep. The study of memory has also revealed its fallibility, showing that memories are reconstructed on retrieval and can be distorted, and that even confidence is no guarantee of accuracy.",
      "The biological basis of emotion and motivation has been a central theme. Emotions, once dismissed as mere disruptions of rational thought, are now understood as adaptive systems that guide behavior, signal value, and organize social interaction. The limbic system, the amygdala in particular, plays a central role in emotion and fear. Motivation is governed by a complex interplay of brain circuits, particularly those involving the neurotransmitter dopamine, which is central to reward, desire, and reinforcement. The understanding of these systems has profound implications — for understanding addiction, for the treatment of mood disorders, and for the design of technologies and environments that powerfully engage the brain's reward circuits.",
      "The study of brain development has revealed that the brain is not fixed at birth but continues to change dramatically throughout life. Early development is a period of exuberant growth and pruning, in which the brain's circuitry is shaped by experience, making infancy and childhood periods of extraordinary plasticity. Adolescence brings a second wave of change, particularly in the prefrontal cortex, the region responsible for impulse control and planning, which matures last into early adulthood. And throughout adulthood, the brain retains a capacity for change — neuroplasticity — that underlies learning and recovery. The recognition that the brain is plastic throughout life has transformed thinking about education, rehabilitation, and mental health.",
      "Language provides one of the clearest windows into brain function. The ability to speak and understand language depends on a set of specialized regions, classically localized in the left hemisphere, and damage to these regions produces characteristic forms of aphasia — the loss of language. Yet language is not simply a separate module; it interacts with the broader systems of thought, memory, and social cognition. The study of the brain and language has demonstrated that our capacity for symbolic communication is deeply rooted in the biology of the brain, and it has illuminated the relations between the structure of thought and the structure of grammar and expression.",
      "Brain imaging has been a revolutionary tool. Techniques like functional magnetic resonance imaging allow researchers to watch the brain in action, observing which regions become active during specific tasks. This has transformed our understanding of perception, decision-making, emotion, and many disorders, and it has enabled the connection of mental processes to their neural substrates in unprecedented detail. But the power of brain imaging has also created temptations to over-interpret: colorful images of brain activity can seem more compelling than the modest evidence they often represent, and the field has struggled with issues of reliability and replication. The interpretative rigor of neuroscience must match its technical sophistication.",
      "The clinical applications of neuroscience are among its most important yields. Neurological disorders — Alzheimer's disease, Parkinson's disease, stroke, epilepsy, and the many forms of dementia — impose a staggering burden of suffering, and they are becoming more common as populations age. Psychiatric disorders — depression, anxiety, schizophrenia, bipolar disorder — are, at root, disorders of the brain, and understanding their neural basis is essential to treating them. Advances in neuropharmacology, in brain stimulation techniques like deep brain stimulation, and in the development of targeted therapies offer genuine hope. But the pace of progress is uneven, many brain disorders remain elusive, and the gap between scientific understanding and effective treatment is wide.",
      "The growth of neuroscience has raised a distinctive set of ethical questions, gathered under the name neuroethics. Brain-based biomarkers raise questions of privacy: what does a society do with the ability to discern information about a person's mind from their brain signals? Techniques of neuroenhancement, which aim to improve cognitive function beyond healthy levels, raise questions about fairness and the nature of normal human capacity. The possibility of using neuroscience to influence or coerce behavior raises profound concerns about autonomy. And the very attempt to reduce human experience to brain activity forces confrontation with long-standing questions of free will, responsibility, and the nature of moral agency. These are not peripheral concerns; they go to the heart of what it means to treat human beings with dignity.",
      "The relationship between neuroscience and our ideas about free will and responsibility is among the most philosophically charged. If all our decisions are, in some sense, determined by the activity of neurons, what room is left for freedom? Some neuroscientists argue that this threatens the commonsense notion of free will; others insist that freedom, properly understood, is compatible with neural determination, and that the responsible approach is to refine rather than abandon our concepts. The stakes are practical as well as philosophical, because the legal and moral systems of society rest on the assumption that people are sometimes responsible for their actions. Whatever the resolution, neuroscience challenges us to bring our concepts of mind, freedom, and responsibility into alignment with what science is learning about the brain.",
      "The comparison between brains and computers has been fruitful but also misleading. Early cognitive science modeled the mind on the sequential processing of a classical computer. Contemporary neuroscience increasingly views the brain as a parallel, distributed, and deeply embodied system, one that learns from statistics, runs on energy-efficient biology, and is shaped by evolution and development rather than by a programmer's design. The recent rise of artificial neural networks — originally inspired by the brain — has renewed interest in the comparison, and many researchers hope that insights from the brain will continue to guide the development of more capable and more energy-efficient intelligent systems.",
      "The horizon of neuroscience is expansive and its trajectory uncertain. Projects to map the complete connectivity of the brain — the connectome — promise a more comprehensive understanding of its wiring. The integration of neuroscience with genetics, with artificial intelligence, and with the behavioral sciences is accelerating. And the ambition to understand consciousness itself, while it may not be realized soon, continues to motivate the field. Yet for all its power, neuroscience is likely to remain a science of organic humility: the brain we study is the very organ through which we study, and every conclusion we reach is a product of the thing we are trying to understand. That reflexive fact, at once humbling and accelerating, is one of the distinctive and defining features of the endeavor to know the brain beneath the mind.",
    ],
    vocabularyNotes: [
      { term: "substrate", zh: "基质；载体" },
      { term: "hierarchical", zh: "分层的" },
      { term: "limbic system", zh: "边缘系统" },
      { term: "cerebral cortex", zh: "大脑皮层" },
      { term: "neuron", ipa: "/ˈnjʊərɒn/", zh: "神经元" },
      { term: "dendrite", zh: "树突" },
      { term: "axon", ipa: "/ˈæksɒn/", zh: "轴突" },
      { term: "synapse", ipa: "/ˈsaɪnæps/", zh: "突触" },
      { term: "neurotransmitter", zh: "神经递质" },
      { term: "synaptic plasticity", zh: "突触可塑性" },
      { term: "consolidation", zh: "（记忆）巩固" },
      { term: "hippocampus", zh: "海马体" },
      { term: "aphasia", ipa: "/əˈfeɪʒə/", zh: "失语症" },
      { term: "neuroplasticity", zh: "神经可塑性" },
      { term: "connectome", zh: "连接组" },
    ],
    grammarNotes: [
      {
        topicId: "hedging-language",
        titleZh: "神经科学结论的严谨限定",
        noteZh: "may or may not / is likely to / arguably 对未解问题保持审慎判断。",
        exampleFromText: "...may only produce an approximation of what the brain does",
      },
      {
        topicId: "nominalization",
        titleZh: "神经科学名词化",
        noteZh: "the integration of information / the loss of language 抽象名词表达复杂机制。",
        exampleFromText: "the subjective experience of consciousness... arises from the activity of neurons",
      },
      {
        topicId: "passive-across-tenses",
        titleZh: "脑机制被动表达",
        noteZh: "is strengthened / are reconstructed / is coordinated 强调神经过程为客体。",
        exampleFromText: "memories are reconstructed on retrieval and can be distorted",
      },
      {
        topicId: "complex-sentences",
        titleZh: "假设与条件推演",
        noteZh: "If all our decisions... are determined... 用条件式展开自由意志难题。",
        exampleFromText: "If all our decisions are, in some sense, determined by the activity of neurons, what room is left for freedom?",
      },
      {
        topicId: "relative-clauses-defining-nondefining",
        titleZh: "关系从句界定结构",
        noteZh: "a thin sheet of tissue that underwrites... 用限定从句说明皮层功能。",
        exampleFromText: "the cerebral cortex, a thin sheet of tissue... that underwrites the higher functions",
      },
      {
        topicId: "emphasis-structures-cleft",
        titleZh: "设问强调核心命题",
        noteZh: "It is the brain we study... 用强调结构突出元层面困境。",
        exampleFromText: "the brain we study is the very organ through which we study",
      },
    ],
    questions: [
      {
        questionEn: "How many neurons does the brain contain?",
        questionZh: "人脑含多少神经元？",
        options: ["About 86 million", "About 86 billion", "About 86 trillion", "About 86 thousand"], answerIndex: 1,
        explainZh: "大约八百六十亿个神经元，每个又作数千个连接。",
      },
      {
        questionEn: "What is the fundamental unit of the brain?",
        questionZh: "大脑的基本单位是什么？",
        options: ["The cell body only", "The neuron", "The cortex", "The synapse only"], answerIndex: 1,
        explainZh: "神经元是传递电化学信号的专用细胞。",
      },
      {
        questionEn: "What is the 'hard problem'?",
        questionZh: "'困难问题'指什么？",
        options: ["Baking", "Explaining subjective consciousness from neuron activity", "Disease cure", "Brain size"], answerIndex: 1,
        explainZh: "即如何从神经元活动解释主观体验的问题。",
      },
      {
        questionEn: "Where does consolidation of memory critically depend?",
        questionZh: "记忆巩固关键依赖于哪里？",
        options: ["The cerebellum", "The hippocampus and sleep", "The spinal cord", "The optic nerve"], answerIndex: 1,
        explainZh: "巩固依赖海马体与睡眠。",
      },
      {
        questionEn: "Which neurotransmitter governs reward and desire?",
        questionZh: "哪种神经递质掌管奖赏与欲望？",
        options: ["Serotonin", "Dopamine", "Adrenaline", "Melatonin"], answerIndex: 1,
        explainZh: "多巴胺对奖赏、欲望与强化至关重要。",
      },
      {
        questionEn: "Why is infancy a period of extraordinary plasticity?",
        questionZh: "为何婴儿期是极强可塑性时期？",
        options: ["The brain is fixed", "Growth and pruning shape circuitry", "No change occurs", "Only adults relearn"], answerIndex: 1,
        explainZh: "早期发育是快速增长与修剪时期，经验塑造回路。",
      },
      {
        questionEn: "What did studies of language reveal?",
        questionZh: "语言研究揭示了什么？",
        options: ["Language has no basis", "Language capacity is rooted in brain biology", "Only right side", "No specialized regions"], answerIndex: 1,
        explainZh: "语言能力深深植根于大脑的生物学。",
      },
      {
        questionEn: "What risk does brain imaging create?",
        questionZh: "脑成像带来什么风险？",
        options: ["It is infallible", "Over-interpretation of colorful images", "It is useless", "It replaces all tests"], answerIndex: 1,
        explainZh: "彩色图像易被过度解读，超出证据支持范围。",
      },
      {
        questionEn: "What does neuroethics examine?",
        questionZh: "'神经伦理学'研究什么？",
        options: ["Neuroanatomy", "Privacy, enhancement, and autonomy questions", "Only drugs", "Surgery techniques"], answerIndex: 1,
        explainZh: "探讨脑标记隐私、认知增强与自主性等伦理问题。",
      },
      {
        questionEn: "Why is the brain comparison with computers misleading?",
        questionZh: "为何将大脑比作计算机会误导？",
        options: ["Brains are simple", "The brain is parallel, distributed, embodied", "Computers are alive", "No difference"], answerIndex: 1,
        explainZh: "大脑是并行、分布式、具身系统论。",
      },
    ],
    summaryTaskZh: "用不超过 90 个英文单词总结：作者如何描述大脑的层次结构？为什么对意识的解释被称为'困难问题'？",
    opinionTaskZh: "The author raises the tension between neural determinism and free will. Drawing on the text and your own view, argue whether the findings of neuroscience undermine the idea of moral responsibility. Write 150-180 words with one concessive clause.",
  },
  {
    id: "reading-15-modern-medicine",
    number: 15,
    slug: "modern-medicine",
    title: "The Healing Arts Transformed: Modern Medicine, Its Triumphs, and Its Unfinished Business",
    categoryZh: "现代医学",
    difficulty: "C2",
    wordCount: 4100,
    minutes: 27,
    article: [
      "Modern medicine is one of the greatest success stories in the history of civilization. In little more than a century, it has transformed the human condition: life expectancy has roughly doubled in developed countries, millions of deaths from infectious disease have been prevented, and once-fatal conditions now yield to routine treatment. The achievement rests on a foundation of scientific understanding — the germ theory of disease, the discovery of antibiotics and vaccines, the control of chronic disease, and the extraordinary expansion of diagnostic and surgical capability. Yet modern medicine also carries an unfinished business and a set of deepening tensions, between its power and its cost, between its technological sophistication and its failures of equity, and between its successes in curing and its more limited capacity to care.",
      "The intellectual foundation of modern medicine is the understanding that disease has biological causes that can be identified and addressed. The germ theory, established in the nineteenth century by figures like Louis Pasteur and Robert Koch, showed that many diseases are caused by microorganisms, and it transformed medicine from a largely helpless art of prognosis into a science of intervention. From this insight flowed the development of vaccines, which prevent disease by training the immune system, and of antibiotics, which cure bacterial infections. These interventions, together with improvements in sanitation, nutrition, and living standards, produced the dramatic reductions in mortality from infectious disease that define the modern biomedical era.",
      "The twentieth century saw the consolidation of medicine's power. The discovery of penicillin and the sulfa drugs inaugurated the antibiotic age, which made previously fatal infections treatable. The development of vaccines — against polio, measles, and eventually many other diseases — prevented enormous suffering. Advances in anesthesia and antisepsis transformed surgery from a desperate last resort into a routine and largely safe undertaking. And the control of chronic disease, through the management of high blood pressure, diabetes, and heart disease, began to change the pattern of mortality from acute infection toward chronic, managed conditions. The result was a medicine that could not only diagnose and treat but, in many cases, genuinely cure.",
      "The imaging revolution transformed diagnosis. The X-ray, discovered at the end of the nineteenth century, gave physicians a way to see inside the living body. The subsequent development of ultrasound, computed tomography, magnetic resonance imaging, and positron emission tomography provided ever more detailed views of anatomy and physiology. These technologies allow disease to be detected earlier, localized precisely, and monitored over time, and they have become indispensable to almost every field of medicine. Yet the sophistication of imaging also raises questions of cost, of the overuse of tests, and of the interpretation of incidental findings that may not matter — a reminder that technological capability must be paired with clinical judgment.",
      "The genomics revolution has opened a new frontier. The sequencing of the human genome, completed early in the twenty-first century, promised a deeper understanding of the genetic basis of disease and the possibility of personalized medicine — the tailoring of prevention and treatment to the individual's genetic and molecular profile. Oncology has begun to realize this promise: many cancers are now characterized by their molecular drivers, and targeted therapies attack these drivers with remarkable specificity. Pharmacogenomics, which uses genetic information to guide drug choice and dosing, is entering clinical use. The promise of precision medicine is enormous, but it is also unevenly realized, and it raises difficult questions about cost, about the interpretation of genetic information, and about equity in access.",
      "The randomized controlled trial is the methodological cornerstone of modern evidence-based medicine. The recognition that clinical claims must be tested rigorously, with treatments compared against placebos or established alternatives in controlled and blinded protocols, transformed medicine from a field governed by authority and anecdote into one governed by evidence. The evolution of clinical research, from the failures and ethical disasters that necessitated modern research ethics to the sophisticated trials of today, is a central thread in the history of medicine. The randomized trial, together with systematic reviews and meta-analyses, provides the basis for the confidence that treatments work, and its discipline remains a model of rigorous empiricism.",
      "The management of chronic and noncommunicable disease is now the central challenge of the world's health systems. As infectious disease receded, chronic conditions — cardiovascular disease, cancer, diabetes, respiratory disease, and mental illness — emerged as the leading causes of death and disability. These conditions are complex, long-lasting, and shaped powerfully by lifestyle, environment, and social conditions. Their management is rarely a simple matter of cure; it is a matter of ongoing care, of controlling risk factors, of behavior change, and of the coordination of care across providers and over many years. The health systems built to treat acute, episodic illness are ill-suited to the demands of chronic care, and their redesign is a defining task of the era.",
      "The aging of populations, an extraordinary triumph of modern medicine, has become one of its great challenges. People are living far longer, often with multiple chronic conditions, and the care of older adults — with its mix of medical, functional, and social dimensions — demands a different kind of medicine. The field of geriatrics, the specialty devoted to the care of older people, emphasizes the complexity of their needs and the importance of preserving function and quality of life rather than merely treating disease. The societal and financial implications of aging are profound, as health systems and families shoulder the challenge of providing appropriate and humane care to a growing population of older people.",
      "The relationship between medicine and public health has been a source of both partnership and strain. The dramatic improvements in life expectancy that began before the advent of effective medicine were largely the result of public health measures — sanitation, clean water, vaccination, and safer food — and these population-level approaches remain essential. Yet public health has often been undervalued relative to the glamour of technological medicine, and its institutions have been chronically underfunded. The COVID-19 pandemic demonstrated both the enormous value of public health and the consequences of its neglect, as the world struggled to mount a coordinated response to a global infectious threat for which much of the infrastructure of public health was unprepared.",
      "The economics of health care dominate policy debate in every country, and they are the arena in which the successes of medicine collide with its limits. The cost of care has grown far faster than national income, driven by the rising price of drugs, devices, and procedures, and by the treatment of chronic disease and the extension of life. Societies must decide how much to spend, what to cover, and who bears the cost, and those decisions are shot through with values and politics as much as with economics. The tension between the extraordinary promise of new treatments and their mounting cost, and between the imperative to make care available and the finite resources available, is unlikely to be resolved; it can only be managed through difficult collective choices.",
      "The ethical landscape of medicine, once relatively settled, is being reshaped by the expansion of its powers. The questions of when life begins and ends, of the limits of intervention, and of the meaning of a good death are being reopened by technology. Palliative care and the movement for humane end-of-life care have sought to ensure that the desire to prolong life does not overshadow the imperative to relieve suffering and to respect patients' wishes. Questions of autonomy, informed consent, and shared decision-making have moved to the center of clinical practice. And the biomedical possibilities of the future — from gene editing to enhancement technologies — promise to generate ethical questions of still greater moral depth, as the power to alter what human beings are begins to come within our grasp.",
      "Global health has become a defining concern, revealing both the interconnectedness of humanity and its profound inequities. Infectious diseases do not respect borders, and the pandemic made vivid the fact that the health of any one nation depends on the health of all. The burden of disease remains hugely unequal: the poor bear the overwhelming share of avoidable suffering, and the capacity to prevent and treat disease is distributed with striking unevenness across countries and within them. Global health efforts have made real progress — in vaccination, in the control of disease, in the reduction of child mortality — but they are persistently underfunded and face the challenge of building durable health systems in the places that need them most.",
      "The rise of artificial intelligence and digital health is the newest frontier. Machine-learning systems are being developed to interpret medical images, to predict disease, to assist diagnosis, and to personalize treatment. Digital tools are being used to monitor patients, to support remote care, and to engage people in managing their own health. The potential of these technologies is considerable, but so are the challenges: ensuring their safety and reliability, protecting privacy, avoiding bias, and integrating them into care without undermining the human relationship that remains central to healing. Technology holds the promise of a more precise, more efficient, more accessible medicine, but technology alone will not resolve the deeper human and social challenges of health and care.",
      "The unfinished business of modern medicine is equity. For all its triumphs, the benefits of medical progress are not shared equally: across and within countries, the poor, the marginalized, and the disadvantaged continue to bear a disproportionate burden of disease and to enjoy inferior access to the care that could prevent, treat, and cure it. Social determinants of health — income, education, housing, and environment — shape health outcomes more powerfully than the health system itself, and no purely medical advance can close the gaps they create. The aspiration of medicine, declared in its ancient codes and renewed in every generation, is to heal — but true healing requires attending not only to the biology of disease but to the social conditions of the people who suffer it. That is the task that remains, and it is as much a moral and political task as a scientific and technical one.",
    ],
    vocabularyNotes: [
      { term: "germ theory", zh: "细菌（致病）学说" },
      { term: "prognosis", zh: "预后；预后判断" },
      { term: "antisepsis", zh: "无菌法；消毒" },
      { term: "computed tomography", zh: "计算机断层扫描" },
      { term: "incidental findings", zh: "偶然发现" },
      { term: "personalized medicine", zh: "个体化医疗" },
      { term: "pharmacogenomics", zh: "药物基因组学" },
      { term: "randomized controlled trial", zh: "随机对照试验" },
      { term: "meta-analysis", zh: "荟萃分析" },
      { term: "noncommunicable disease", zh: "非传染性疾病" },
      { term: "geriatrics", zh: "老年医学" },
      { term: "palliative care", zh: "姑息/安宁疗护" },
      { term: "social determinants of health", zh: "健康的社会决定因素" },
    ],
    grammarNotes: [
      {
        topicId: "nominalization",
        titleZh: "医学术语名词化",
        noteZh: "the sequencing of the human genome / the control of disease 抽象名词表达科学过程。",
        exampleFromText: "the sequencing of the human genome, completed early in the twenty-first century",
      },
      {
        topicId: "hedging-language",
        titleZh: "临床判断的审慎",
        noteZh: "may or may not / is likely to / arguably 对技术后果给出分寸判断。",
        exampleFromText: "technology alone will not resolve the deeper human and social challenges",
      },
      {
        topicId: "passive-across-tenses",
        titleZh: "医学发明的被动陈述",
        noteZh: "was established / are used / is appraised 强调药物与技术客体。",
        exampleFromText: "antibiotics, which cure bacterial infections... have been developed",
      },
      {
        topicId: "relative-clauses-defining-nondefining",
        titleZh: "关系从句定义机制",
        noteZh: "man-made by-products... that had never before been met 用限定从句界定新型危害。",
        exampleFromText: "conditions... that had never before been encountered in human society",
      },
      {
        topicId: "complex-sentences",
        titleZh: "因果与转折复合",
        noteZh: "Although the mechanism is not fully known... 用让步状语限定结论。",
        exampleFromText: "Although modern medicine has achieved much, its benefits are not shared equally",
      },
      {
        topicId: "parallelism-rules",
        titleZh: "并列动词概括时代",
        noteZh: "to prevent, to treat, and to cure 平行口号式推进。",
        exampleFromText: "the care that could prevent, treat, and cure it",
      },
    ],
    questions: [
      {
        questionEn: "What established the germ theory?",
        questionZh: "谁确立了细菌学说？",
        options: ["Hippocrates", "Pasteur and Koch", "Harvey", "Pavlov"], answerIndex: 1,
        explainZh: "巴斯德与科赫十九世纪确立细菌（致病）学说。",
      },
      {
        questionEn: "What did the antibiotic age make possible?",
        questionZh: "抗生素时代使什么成为可能？",
        options: ["More infections", "Treating previously fatal infections", "Only surgery", "No cure"], answerIndex: 1,
        explainZh: "青霉素等使以往致命的感染可治。",
      },
      {
        questionEn: "What did the imaging revolution do for diagnosis?",
        questionZh: "影像革命为诊断带来什么？",
        options: ["Made diagnosis slower", "Provided views inside the living body", "Replaced doctors", "Ended X-rays"], answerIndex: 1,
        explainZh: "超声、CT、MRI 等提供体内详细视图，早期发现疾病。",
      },
      {
        questionEn: "What does pharmacogenomics use genetic info for?",
        questionZh: "药物基因组学用基因信息做什么？",
        options: ["Making diagnoses", "Guiding drug choice and dosing", "Running labs", "Surgery"], answerIndex: 1,
        explainZh: "用基因信息指导药物选择与剂量。",
      },
      {
        questionEn: "What is the methodological cornerstone of evidence-based medicine?",
        questionZh: "循证医学的方法论基石是什么？",
        options: ["Anecdote", "The randomized controlled trial", "Authority", "Trial and error"], answerIndex: 1,
        explainZh: "随机对照试验以严格、设盲方案检验疗效。",
      },
      {
        questionEn: "What is now the central challenge of health systems?",
        questionZh: "当前卫生体系的核心挑战是什么？",
        options: ["Infectious disease only", "Chronic noncommunicable disease", "Only cancer", "Trauma"], answerIndex: 1,
        explainZh: "慢性非传染性疾病成为死亡与残疾主因。",
      },
      {
        questionEn: "Why has aging become a challenge?",
        questionZh: "为何老龄化成为挑战？",
        options: ["Shorter lives", "Longer lives with multiple chronic conditions", "Fewer patients", "No need for care"], answerIndex: 1,
        explainZh: "人活更久且常伴多种慢病，需有别于急性护理的照护。",
      },
      {
        questionEn: "What did the pandemic demonstrate?",
        questionZh: "疫情证明了什么？",
        options: ["Public health is useless", "Both the value and the neglect of public health", "Only medicine matters", "No response needed"], answerIndex: 1,
        explainZh: "既显示公共卫生的价值，又显示其资金不足与忽视的后果。",
      },
      {
        questionEn: "What has the expansion of medicine's powers reopened?",
        questionZh: "医学力量扩展重新开启了什么？",
        options: ["Only surgical questions", "Questions of life, death, and good death", "No questions", "Only billing"], answerIndex: 1,
        explainZh: "生命起止、干预限度与善终等问题被技术重新讨论。",
      },
      {
        questionEn: "What is medicine's unfinished business?",
        questionZh: "医学未竟的事业是什么？",
        options: ["More cures", "Equity - unequal sharing of benefits", "More drugs", "Faster recovery"], answerIndex: 1,
        explainZh: "医学进步的好处分配不均，需关注健康的社会决定因素。",
      },
    ],
    summaryTaskZh: "用不超过 90 个英文单词总结：作者列举了现代医学的哪些重大成就？它面临哪些尚未解决的内在张力？",
    opinionTaskZh: "The author argues that medicine's unfinished business is equity, not merely more technology. Drawing on the text and your own view, argue whether spending on advanced medical technology or on social determinants should be prioritized. Write 150-180 words with one concessive clause.",
  },
];
