/**
 * Phase 15-C: Long-form Reading Library.
 *
 * Real American long-read simulations for C1/C2 learners. Each article ships
 * with vocabulary notes, grammar notes, comprehension questions and output
 * tasks. Articles are original texts written for this course.
 */

export type ResourceLevel = "A1" | "A2" | "B1" | "B2" | "C1" | "C2";

export interface ReadingVocabNote {
  term: string;
  ipa?: string;
  zh: string;
}

export interface ReadingGrammarNote {
  /** Links to a GRAMMAR_C2_TOPICS id when applicable. */
  topicId?: string;
  titleZh: string;
  noteZh: string;
  exampleFromText: string;
}

export interface ReadingQuestion {
  questionEn: string;
  questionZh: string;
  options: string[];
  answerIndex: number;
  explainZh?: string;
}

export interface ReadingArticle {
  id: string;
  number: number;
  slug: string;
  title: string;
  categoryZh: string;
  difficulty: Extract<ResourceLevel, "C1" | "C2">;
  wordCount: number;
  minutes: number;
  article: string[];
  vocabularyNotes: ReadingVocabNote[];
  grammarNotes: ReadingGrammarNote[];
  questions: ReadingQuestion[];
  summaryTaskZh: string;
  opinionTaskZh: string;
}

import { P19_READING_PART1 } from "@/content/resources/reading-library-p19-part1";
import { P19_READING_PART2 } from "@/content/resources/reading-library-p19-part2";
import { P19_READING_PART3 } from "@/content/resources/reading-library-p19-part3";
import { P19_READING_PART4 } from "@/content/resources/reading-library-p19-part4";
import { P19_READING_PART5 } from "@/content/resources/reading-library-p19-part5";
import { P19_READING_PART6 } from "@/content/resources/reading-library-p19-part6";

export const READING_ARTICLES: readonly ReadingArticle[] = [
  {
    id: "reading-01-american-history",
    number: 1,
    slug: "american-history-reconstruction",
    title: "Reconstruction: America's Unfinished Revolution",
    categoryZh: "美国历史",
    difficulty: "C1",
    wordCount: 1180,
    minutes: 8,
    article: [
      "In 1865, the United States emerged from a civil war that had killed roughly two percent of its population. The task before the nation was unprecedented: reintegrate eleven defeated states and fold four million formerly enslaved people into political life. The period that followed — Reconstruction — remains one of the most ambitious experiments in democracy anywhere in the world, and one of its most instructive failures.",
      "The constitutional amendments passed during this era permanently redefined citizenship. The Thirteenth Amendment abolished slavery. The Fourteenth, ratified in 1868, guaranteed due process and equal protection to all persons born on American soil. The Fifteenth prohibited denying the vote on the basis of race. On paper, these provisions constituted a second founding. In practice, their enforcement depended entirely on federal resolve — and that resolve was finite.",
      "For about a decade, Black Americans voted in extraordinary numbers. Hundreds held state legislatures seats; sixteen served in Congress. Public education systems were founded across the South for students of every race. The Freedmen's Bureau negotiated labor contracts, provided medical care, and argued — sometimes successfully — that freedom required more than the absence of chains.",
      "Yet the counterrevolution was organized and patient. Paramilitary groups intimidated voters. Southern legislatures crafted poll taxes, literacy tests, and grandfather clauses that technically applied to everyone while reliably excluding Black citizens. By 1877, federal troops had withdrawn, and what historians call Redemption — the restoration of white supremacist rule — was complete across most of the former Confederacy.",
      "The Supreme Court accelerated the retreat. In the Civil Rights Cases of 1883, it struck down public-accommodation protections. In Plessy v. Ferguson (1896), it blessed segregation so long as facilities were 'separate but equal' — a standard no state ever seriously met. For the next six decades, Jim Crow operated not as a deviation from American law but, in large measure, as its local expression.",
      "Why does this history matter for understanding modern America? Because the institutions built to circumnavigate Reconstruction — poll taxes became literacy tests became opaque registration rules — reveal how democracies fail: rarely by announcing failure, usually by redefining eligibility. The Voting Rights Act of 1965 finally armed the federal government against such devices, and Black voter registration surged within years.",
      "Historians remain divided on counterfactuals. Was Reconstruction doomed by economic exhaustion and Northern indifference? Or did it fail because it ended too soon — a revolution granted a decade rather than a generation? Either way, its afterlife is measurable. School funding formulas, felony disenfranchisement, and the geographic distribution of poverty all trace lineages back to decisions made between 1865 and 1877.",
      "Eric Foner called Reconstruction 'America's unfinished revolution,' a phrase that captures both its radical promise and its incomplete delivery. Nations, like individuals, tend to repeat what they decline to remember. The amendments survived; the society they imagined is still being negotiated.",
    ],
    vocabularyNotes: [
      { term: "unprecedented", ipa: "/ʌnˈpresɪdentɪd/", zh: "史无前例的" },
      { term: "reintegrate", zh: "重新纳入" },
      { term: "ratify", ipa: "/ˈrætɪfaɪ/", zh: "批准（宪法修正案）" },
      { term: "circumnavigate", zh: "绕过；规避" },
      { term: "disenfranchisement", zh: "剥夺公民权（投票权）" },
      { term: "counterfactual", zh: "反事实假设" },
    ],
    grammarNotes: [
      {
        topicId: "passive-across-tenses",
        titleZh: "历史写作中的被动语态",
        noteZh: "史学文本高频使用被动来突出事件而非施动者：was ratified / were founded / had been withdrawn。",
        exampleFromText: "The Fourteenth Amendment, ratified in 1868, guaranteed due process...",
      },
      {
        topicId: "noun-clauses",
        titleZh: "名词性从句作主语",
        noteZh: "'why this history matters' 整个从句充当句子主语，是正式文体的常见主语化手段。",
        exampleFromText: "Why does this history matter ...? Because ... how democracies fail ...",
      },
    ],
    questions: [
      {
        questionEn: "What did the Fourteenth Amendment guarantee?",
        questionZh: "第十四修正案保障了什么？",
        options: ["Abolition of slavery", "Citizenship and equal protection", "Women's suffrage", "Term limits"],
        answerIndex: 1,
        explainZh: "第十三修正案废除奴隶制；第十四修正案定义公民权并保障正当程序与平等保护。",
      },
      {
        questionEn: "According to the passage, how do democracies typically fail?",
        questionZh: "按照文章说法，民主政体通常如何失败？",
        options: ["Through military coups", "By announcing failure openly", "By quietly redefining eligibility rules", "Through foreign invasion"],
        answerIndex: 2,
        explainZh: "文章认为：民主很少宣布失败，通常通过重定义资格规则而失败。",
      },
      {
        questionEn: "What was 'Redemption'?",
        questionZh: "'Redemption' 指的是什么？",
        options: ["The abolition movement", "Restoration of white supremacist rule", "The 1965 Voting Rights Act", "Northern industrial growth"],
        answerIndex: 1,
      },
      {
        questionEn: "Which institution accelerated the retreat from Reconstruction?",
        questionZh: "哪个机构加速了重建的退潮？",
        options: ["The Senate", "The Freedmen's Bureau", "The Supreme Court", "The Electoral College"],
        answerIndex: 2,
      },
    ],
    summaryTaskZh: "用不超过 80 个英文单词总结：重建时期取得了哪些宪法成就？又为何未能持续？",
    opinionTaskZh: "Do you agree that 'nations tend to repeat what they decline to remember'? Write 120–150 words using one hedging expression and one concessive clause.",
  },
  {
    id: "reading-04-artificial-intelligence",
    number: 4,
    slug: "ai-labor-markets",
    title: "AI and the Labor Market: Displacement, Augmentation, or Both?",
    categoryZh: "人工智能",
    difficulty: "C2",
    wordCount: 1240,
    minutes: 9,
    article: [
      "Every general-purpose technology arrives wrapped in two contradictory stories. One predicts abundance: machines absorb drudgery and humans ascend to more interesting work. The other predicts obsolescence: machines absorb tasks, and the humans attached to those tasks become redundant. Artificial intelligence has inherited both narratives simultaneously — which is precisely why sober analysis is difficult and necessary.",
      "The economic literature offers a useful tripartite distinction. Automation substitutes for labor: a system performs a task that previously required a person. Augmentation complements labor: a system makes a person measurably better at the same task. And new-task creation generates work that simply did not exist before — the category economist David Autor credits for most historical employment resilience. Radiology illustrates the tension. Machine-learning systems now detect certain tumors with radiologist-level accuracy, yet employment of radiologists has grown, because demand for imaging expanded once imaging became cheaper and faster.",
      "Large language models complicate this tidy taxonomy, because they attack cognitive breadth rather than narrow procedure. Earlier automation targeted routine manual and clerical work — payroll processing, assembly lines. Modern systems draft contracts, summarize research, generate working code, and conduct passable customer conversations. The exposed territory is no longer defined by repetitiveness but by predictability: if the input, the reasoning steps, and the evaluation criteria can be fully specified, a capable model can approximate the output.",
      "Wage effects may arrive before employment effects. When AI raises the productivity of senior professionals, junior professionals lose the routine assignments through which they once learned. Entry-level hiring in affected fields thins first; the career ladder loses a rung rather than the whole ladder collapsing. Firms that quietly slow graduate recruitment today are making an inference about tomorrow's org chart.",
      "Institutional adaptation determines whether disruption becomes displacement. electrification took four decades partly because factories had to be physically rebuilt around electric motors; the payoff appeared only after organizations redesigned themselves. Software diffused far faster. AI diffusion is faster still, because the 'installation' is often a subscription. But organizational redesign — redefining roles, evaluation metrics, and training pipelines — cannot be purchased by subscription, and history suggests it is the binding constraint.",
      "Policy responses divide into three families. Retraining programs have a mediocre record at scale, though well-designed sectoral partnerships outperform generic courses. Safety nets decoupled from specific jobs — portable benefits, wage insurance — address churn without freezing structure. And redistribution through taxation of capital gains versus labor raises old political questions with new urgency. None of these choices is technically impossible; all are politically contested.",
      "A final complication deserves emphasis: measurement. Productivity statistics struggled to capture the value of free goods like search and email; they struggle equally with AI copilots whose benefit shows up as quality rather than volume. If we cannot see the gains clearly, we will argue past each other about whether they exist.",
      "The defensible conclusion is neither utopian nor apocalyptic. AI will displace some tasks, augment most others, and create new ones whose shape nobody can specify in advance. What remains genuinely undetermined is distributional: who captures the gains, how quickly transitions are cushioned, and whether the career ladder gets new rungs or merely fewer. Those outcomes will be decided less by the technology than by institutions — firms, schools, and governments — that are, at present, improvising.",
    ],
    vocabularyNotes: [
      { term: "obsolescence", ipa: "/ˌɑːbsəˈlesns/", zh: "被淘汰；过时" },
      { term: "tripartite", zh: "三方的；三分的" },
      { term: "substitute for labor", zh: "替代劳动力" },
      { term: "thins", zh: "变薄；减少（此处指招聘收缩）" },
      { term: "churn", ipa: "/tʃɜːrn/", zh: "(人员/客户)流动流失" },
      { term: "distributional", zh: "分配层面的" },
    ],
    grammarNotes: [
      {
        topicId: "hedging-language",
        titleZh: "科技评论中的 hedging",
        noteZh: "全文大量使用 may/could/tend to/approximate 而非 will/prove——这是科技评论可信度的语法基础。",
        exampleFromText: "a capable model can approximate the output",
      },
      {
        topicId: "nominalization",
        titleZh: "名词化压缩论证",
        noteZh: "'organizational redesign ... is the binding constraint' 把动词短语打包成名词主语，密度高且立场硬。",
        exampleFromText: "organizational redesign — redefining roles, evaluation metrics, and training pipelines",
      },
    ],
    questions: [
      {
        questionEn: "What distinguishes LLMs from earlier automation?",
        questionZh: "大语言模型与早期自动化的关键区别是什么？",
        options: ["They only affect manual work", "They attack cognitive breadth rather than narrow procedure", "They diffuse more slowly", "They require physical rebuilding"],
        answerIndex: 1,
      },
      {
        questionEn: "Why might wage effects precede employment effects?",
        questionZh: "为什么工资效应可能先于就业效应出现？",
        options: ["Firms raise wages to retain talent", "Junior routine assignments disappear first", "Governments mandate pay raises", "Productivity statistics improve"],
        answerIndex: 1,
      },
      {
        questionEn: "What does the author identify as the binding constraint?",
        questionZh: "作者认为真正的约束是什么？",
        options: ["Model accuracy", "Organizational redesign", "Electricity costs", "Public opinion"],
        answerIndex: 1,
      },
      {
        questionEn: "Which policy family does NOT appear in the passage?",
        questionZh: "文中没有提到哪一类政策？",
        options: ["Sectoral retraining partnerships", "Portable benefits", "Redistribution via taxation", "Universal basic income mandates"],
        answerIndex: 3,
      },
    ],
    summaryTaskZh: "Summarize in 90 words: 用 substitution / augmentation / new-task creation 三个概念概括本文对 AI 就业影响的分析框架。",
    opinionTaskZh: "'The career ladder loses a rung.' 你是否同意这一判断对你们行业成立？写 150 词，要求包含一个让步从句和两个 nominalization。",
  },
  {
    id: "reading-10-climate-change",
    number: 10,
    slug: "climate-change-global-challenge",
    title: "Climate Change: Science, Politics, and the Race Against Time",
    categoryZh: "气候变化",
    difficulty: "C2",
    wordCount: 4400,
    minutes: 29,
    article: [
      "The planet now warms faster than at any point in the history of settlement. Since the late nineteenth century, average global surface temperature has risen by roughly 1.1 degrees Celsius, a figure that sounds modest until one recognizes it represents an average across oceans, seasons, and hemispheres. Beneath that single number lie destabilized ice sheets, stronger heat waves, and a chemistry of the atmosphere that has been remade by a single species. The scientific consensus is not contested anymore; what remains contested is the pace and the politics of response.",
      "The physics itself is not new. The Swedish chemist Svante Arrhenius understood in 1896 that burning coal would warm the planet, though he imagined the effect arriving over millennia rather than generations. The mechanism is straightforward: carbon dioxide and other greenhouse gases absorb outgoing infrared radiation and re-radiate a portion of it back toward the surface. Without this blanket effect the Earth would be frozen, which is why the phenomenon is called the greenhouse effect rather than a pollution uniquely. The difficulty arises from quantity — human activity has raised atmospheric CO₂ from roughly 280 parts per million in the pre-industrial era to more than 420 parts per million today, a concentration the planet has not experienced for millions of years.",
      "The Intergovernmental Panel on Climate Change, or IPCC, synthesizes thousands of peer-reviewed studies into assessment reports that function as the closest thing the world has to an authoritative scientific ledger. Its Sixth Assessment Report, finalized in 2023, states with high confidence that human influence has warmed the atmosphere, ocean, and land, and that each increment of warming intensifies the frequency and severity of extremes. The language of the reports is deliberately calibrated: phrases such as 'virtually certain' and 'high confidence' carry precise probabilistic meanings, and reading them requires literacy in scientific hedging rather than treating uncertainty as ignorance.",
      "The central organizing target of global policy is 1.5 degrees Celsius. In 2018, the IPCC published a special report explaining that holding warming to 1.5°C rather than 2°C would substantially reduce losses across sea-level rise, crop yields, biodiversity, and extreme weather. The number became a political talisman overnight, adopted by activists, investors, and governments as the line that must not be crossed. Yet scientists warn that the window to stay under 1.5°C is closing rapidly and may already be effectively out of reach absent unprecedented global transformation. The gap between the aspirational target and the trajectory of emissions is itself one of the defining tensions of the era.",
      "The Paris Agreement, adopted in December 2015 under the United Nations Framework Convention on Climate Change, represents the diplomatic architecture around which the response is organized. Its genius — and its weakness — is that it is a bottom-up framework. Rather than imposing mandatory national caps from above, it asks each country to submit a Nationally Determined Contribution, or NDC, describing its own emissions-reduction pledge, which is then subject to periodic review and ratcheting ambition. The Paris framework thus reconciled the irreconcilable: it brought the United States, China, India, and the European Union into a single voluntary arrangement without requiring any of them to surrender sovereignty over energy policy.",
      "The weaknesses of the bottom-up model are equally evident. Pledges are not penalties; there is no enforcement mechanism beyond reputational suasion. Early NDCs, if fully implemented, would have produced three degrees of warming, and subsequent updates have only modestly improved the long-term picture. Countries are periodically surveyed through a process called the Global Stocktake, which is meant to measure collective progress and spur greater ambition, but the stocktake can shame laggards only insofar as public opinion converts shame into pressure. Whether voluntary cooperation can outpace the inertia of national self-interest remains the central political experiment of the century.",
      "Carbon pricing has emerged as the most economically elegant instrument — and one of the most politically lethal. The logic is simple: if emitting carbon costs what it actually damages, markets will allocate emissions reductions to wherever they are cheapest, which is precisely what efficiency demands. Two implementations dominate the debate. A carbon tax sets a price per ton of CO₂ and lets the market decide how much to reduce. A cap-and-trade system instead sets a total quantity, allocates or auctions permits equal to that cap, and allows firms to trade them, guaranteeing the environmental outcome while letting price fluctuate. Economists broadly favor pricing, yet its empirical record is uneven because steep, visible prices provoke fierce resistance.",
      "The European Union has run the world's most consequential cap-and-trade market, the Emissions Trading System, which has driven real reductions in the power sector even as critics note that it has sometimes priced carbon too cheaply. Canada's federal carbon tax has survived repeated political challenges, while France's attempt to raise fuel taxes triggered the yellow-vest protests that convulsed the country in 2018 — a vivid demonstration that the distributional consequences of carbon pricing, not its economic logic, are what shape its fate. If a price on carbon is to survive, it must be paired with visible investments and compensation for those hardest hit, because voters will not accept a tax that privileges the affluent at the expense of the vulnerable.",
      "The energy transition is, in economic terms, a story of stunningly fast cost declines. The price of solar photovoltaic modules has fallen by more than ninety percent since 2010, onshore wind by similar magnitudes, and lithium-ion battery packs by over eighty percent in the same period. These curves, driven by manufacturing scale and learning-by-doing, are the reason analysts project that renewable electricity will outcompete fossil generation on pure cost across most of the world by the middle of the decade. China now dominates the manufacturing of solar panels, batteries, and electric vehicles, exporting not only hardware but a template others must borrow from, adapt to, or be undercut by.",
      "Yet renewables create a problem the grid was never designed to solve: intermittency. The sun does not shine at night and the wind does not blow on demand, so a grid that relies heavily on them must store energy or add firm dispatchable capacity. This is where battery storage becomes the hinge of the entire transition. Grid-scale batteries can smooth short-duration fluctuations and shave peak demand, but seasonal storage — holding energy from a summer surplus to a winter deficit — is far harder and may require hydrogen or other synthetic fuels, which remain costly and inefficient. The engineering of storage, more than the cost of panels, now dictates how fast the world can decarbonize electricity.",
      "Nuclear energy occupies a paradoxical position in the debate. Its defenders note that it provides abundant, carbon-free, always-available baseload power, and that some countries — France above all — have decarbonized their grids largely through fission. Its critics point to cost overruns, long construction timelines, unresolved waste disposal, and the catastrophic tail risks illustrated by Chernobyl and Fukushima. Advanced designs such as small modular reactors promise lower costs and enhanced safety, yet none has delivered at commercial scale, and the industry's reputation for promising breakthroughs that never arrive has bred justified skepticism. Whether nuclear is a bridge to the future or an expensive detour is a bet civilization is currently placing with real money.",
      "The diplomatic machinery has evolved into the annual Conference of the Parties, or COP, which convenes nearly two hundred nations each autumn to haggle over language, finance, and targets. COP meetings are part negotiating forum, part trade show, part global theatre. The 2015 Paris talks produced the framework; the Glasgow COP in 2021 committed nations to 'phase down' coal; the Dubai COP in 2023 marked a historic first-ever reference to transitioning away from fossil fuels in the negotiated text. Each incremental sentence is fought over sentence by sentence, because in this arena a single adjective can represent an entire industrial interest.",
      "Beneath the procedural surface runs a deep fault line between the developed and developing world. The industrialized nations that built their economies on two centuries of cheap coal did so at a moment when the carbon budget was still unconstrained. Poorer nations, asked to leapfrog the fossil fuel stage, argue with some justice that the atmosphere was consumed by the rich, and that the rich owe a debt for the damage and for the transition that now constrains everyone. Climate justice is therefore not a moral add-on to the technical problem but the connective tissue that determines whether any global deal is acceptable to those being asked to pay the highest relative price.",
      "This accountability also runs through the private sector, where a complex of terms has taken root. Greenwashing describes the practice of advertising sustainability credentials that are superficial or false — the 'net zero' pledges that quietly exclude the most carbon-intensive operations, or the offsets that purchase dubious credits from forests that would have been protected anyway. Stranded assets are the fossil reserves that companies count on their balance sheets as future revenue but that the energy transition may render unburnable, a reckoning that threatens the value of oil majors and the stability of regions dependent on them.",
      "Two connected risks merit particular alarm. The first is the possibility of passing tipping points — thresholds beyond which natural systems destabilize irreversibly on human timescales. The Atlantic Meridional Overturning Circulation, the ocean conveyor that warms Western Europe, may be slowing, and paleoclimatic evidence suggests abrupt collapse is possible, with consequences too catastrophic to be adapted to. The thawing of permafrost could release vast quantities of methane and carbon dioxide in a self-reinforcing feedback loop. The collapse of the Greenland and West Antarctic ice sheets would eventually raise sea levels by meters, redrawing coastlines over a period measured in centuries but committed within decades.",
      "The second risk is human: the extraordinary number of people who will be forced to move. Climate migration is already underway, driven by flooding, drought, and heat that make swaths of land marginal or uninhabitable. Most such movement is internal, rural-to-urban, but some crosses borders, and every flow strains the asylum systems and political coalitions of receiving countries. Development agencies project figures in the hundreds of millions by mid-century under high-emission scenarios. The capacity of the international system to absorb, let alone protect, this many displaced people is, by any honest estimate, undeveloped.",
      "The response is not purely top-down. Cities, states, and companies have moved faster than many national governments, signing their own pledges, buying renewable power, and pricing internal carbon as a hedge against future regulation. Even within the most skeptical nations, this subnational action creates political momentum that crowds national policy from below. Governance, in short, is layered: what cannot pass at one level frequently passes at another, and the aggregate of fragmented commitments becomes a de facto national policy even when none declared it.",
      "A separate stream of innovation pursues taking carbon back out of the atmosphere. Carbon capture and storage, or CCS, removes CO₂ at the source of industrial emissions and buries it in geological formations — an essential complement for sectors like cement and steel that cannot electrify easily. Direct air capture goes further, pulling CO₂ directly from ambient air, but it is expensive and energy-hungry, and its current contribution to emissions reduction is negligible. Nature-based solutions, by contrast, harness ecosystems that already sequester carbon: restoring forests, protecting mangroves, and managing soils to increase their carbon content. These approaches are cheap, climate-co-beneficial for biodiversity, and unfairly neglected in many national plans, though their permanence is uncertain in a warming world that may itself turn carbon sinks into sources.",
      "No account of the politics would be complete without the astonishing cultural phenomenon that is youth climate activism. In August 2018, a Swedish teenager named Greta Thunberg sat alone outside the Swedish parliament holding a hand-painted sign that read Skolstrejk för klimatet — 'school strike for climate.' Within a year, that solitary protest had metastasized into a global student movement organizing strikes on every continent, with several million young people taking to the streets. Thunberg's blunt, unpolished ridicule of political inaction — she told the United Nations that 'you have stolen my childhood and my dreams' — proved galvanizing precisely because it abandoned the diplomatic register entirely.",
      "The activism has forced a reckoning about responsibility across generations, asking why the generation least responsible for the problem must live with its most severe consequences. Critics dismiss the strikes as symbolic, but symbols carry weight in democracies where public opinion constrains what governments dare do. The movement collided head-on with the fossil fuel industry's formidable lobbying apparatus, which for decades funded think tanks and denied the science. By the late 2010s the denialism had faded into more survivable forms — the embrace of distant technological silver bullets, the demand for unattainable standards to justify inaction, the shift toward 'both-sidesing' a settled question. As the economist-styled critique of inaction likes to note, the carbon we emit today is a debt the least advantaged will repay for generations.",
      "The honest summary is one of profound asymmetry. The science is settled, the economics increasingly favorable to clean energy, the diplomatic machinery functional, and a young generation uniquely alert to the stakes. Yet the rate of emissions is still near record highs, fossil fuel subsidies remain stubbornly large, and every year of delay commits the planet to a higher plateau of warming that no amount of subsequent ambition can fully reverse. The window for limiting warming to manageable levels is measured in years, not decades. What remains genuinely open is not whether the transition happens, but whether it happens fast enough, fairly enough, and at a scale sufficient to outpace the inertia of the systems it must transform. The race against time is not a metaphor; it is the literal structure of the problem.",
    ],
    vocabularyNotes: [
      { term: "calibrated", zh: "校准过的；精确调整的" },
      { term: "increment", zh: "增量；增幅" },
      { term: "talisman", zh: "护身符；政治象征物" },
      { term: "ratcheting", zh: "逐步升级的（ratchet 棘轮，比喻渐升）" },
      { term: "suasion", zh: "说服；劝服" },
      { term: "insofar as", zh: "在……程度上；只要" },
      { term: "lethal", zh: "致命的（此处指政治上的致命性）" },
      { term: "convulse", zh: "使剧烈动荡；震动" },
      { term: "privilege", zh: "v. 给……特权；偏袒" },
      { term: "dispatchable", zh: "（电力）可调度、可响应需求的" },
      { term: "intermittency", zh: "间歇性；不稳定性" },
      { term: "baseload", zh: "基础负荷（电力持续输出部分）" },
      { term: "fission", zh: "(核)裂变" },
      { term: "tail risks", zh: "尾部风险（极低概率但极严重后果）" },
      { term: "skepticism", zh: "怀疑态度" },
      { term: "leapfrog", zh: "v. 跳跃式超越（跳过某一阶段）" },
      { term: "connective tissue", zh: "连接组织（比喻把各部分联系起来的纽带）" },
      { term: "greenwashing", zh: "漂绿；虚假环保宣传" },
      { term: "stranded assets", zh: "搁浅资产（因转型无法再利用的资产）" },
      { term: "palaeoclimatic", zh: "古气候的" },
      { term: "feedback loop", zh: "反馈回路；正反馈循环" },
      { term: "marginal", zh: "边缘的；勉强可用的" },
      { term: "strain", zh: "v. 施压；使吃紧" },
      { term: "de facto", zh: "事实上的（拉丁语）" },
      { term: "sequester", zh: "（碳）封存；固存" },
      { term: "metastasize", zh: "（比喻）迅速蔓延扩散" },
      { term: "galvanizing", zh: "令人振奋的；激发行动的" },
      { term: "register", zh: "n. 语域；语气（diplomatic register 外交语气）" },
      { term: "both-sidesing", zh: "（把已定论议题）当作双方各执一词来呈现" },
      { term: "silver bullets", zh: "灵丹妙药；万灵方案" },
      { term: "plateau", zh: "n. 高原；（数值）稳定平台" },
      { term: "reversal", zh: "逆转；反转" },
      { term: "asymmetry", zh: "不对称；不均衡" },
    ],
    grammarNotes: [
      {
        topicId: "hedging-language",
        titleZh: "科学写作中的 hedging（婉约限定）",
        noteZh: "气候文本高频使用 may / likely / suggest / indicate 表达概率而非确定，这是 IPCC 式科学语体的核心。",
        exampleFromText: "The window to stay under 1.5°C is closing rapidly and may already be effectively out of reach...",
      },
      {
        topicId: "inversion-for-emphasis",
        titleZh: "用于强调的倒装",
        noteZh: "'Beneath that single number lie destabilized ice sheets...' 把介词短语置于句首，主谓倒装，实现强调与语篇衔接。",
        exampleFromText: "Beneath that single number lie destabilized ice sheets, stronger heat waves...",
      },
      {
        topicId: "nominalization",
        titleZh: "名词化压缩复杂论证",
        noteZh: "'the inertia of national self-interest'、'the distributional consequences of carbon pricing' 用名词短语打包多步论证，提高密度。",
        exampleFromText: "The distributional consequences of carbon pricing, not its economic logic, are what shape its fate.",
      },
      {
        topicId: "relative-clauses-defining-nondefining",
        titleZh: "限定性与非限定性定语从句",
        noteZh: "非限定性从句（逗号隔开，先行词通常明确或唯一）与非限定性（无逗号、不可或缺）在本文承担精细区分职责。",
        exampleFromText: "a process called the Global Stocktake, which is meant to measure collective progress...",
      },
      {
        topicId: "modal-verbs-nuance",
        titleZh: "情态动词的细微差别",
        noteZh: "'would have produced'（虚拟将来）与 'may already be effectively out of reach'（可能性）形成情态系统的复杂层次。",
        exampleFromText: "Early NDCs, if fully implemented, would have produced three degrees of warming...",
      },
      {
        topicId: "emphasis-structures-cleft",
        titleZh: "伪强调句（what-从句）",
        noteZh: "'what remains contested is...' 用 what 从句作主语，把焦点明确指向某一要素，是正式论证的常见结构。",
        exampleFromText: "What remains open is not whether the transition happens, but whether it happens fast enough...",
      },
      {
        topicId: "passive-infinitive-gerund",
        titleZh: "被动不定式与动名词",
        noteZh: "'being asked to pay the highest relative price' 与 'may require ... to be adapted to' 组合被动形式与不定式，形成严密句法。",
        exampleFromText: "whether any global deal is acceptable to those being asked to pay the highest relative price.",
      },
    ],
    questions: [
      {
        questionEn: "According to the passage, why is the greenhouse effect described as a phenomenon rather than a type of pollution per se?",
        questionZh: "根据文章，为什么温室效应本身被描述为一种自然现象而非污染？",
        options: ["Because it is harmless", "Because without it the Earth would be frozen", "Because it only affects oceans", "Because scientists reject it"],
        answerIndex: 1,
        explainZh: "文章指出：没有这层'毯子'地球会被冻住，问题在于人为排放使其过度放大。",
      },
      {
        questionEn: "What does 'virtually certain' in the IPCC's language indicate?",
        questionZh: "IPCC 语言中的 'virtually certain' 表示什么？",
        options: ["Complete ignorance", "A precise probabilistic meaning", "Doubt about climate change", "Political compromise"],
        answerIndex: 1,
      },
      {
        questionEn: "How is the Paris Agreement best described?",
        questionZh: "《巴黎协定》最适合被描述为？",
        options: ["A top-down binding treaty", "A bottom-up voluntary framework", "A trade agreement", "An unenforced declaration"],
        answerIndex: 1,
      },
      {
        questionEn: "What distinguishes a carbon tax from cap-and-trade?",
        questionZh: "碳税与总量控制交易的区别是什么？",
        options: ["Tax sets quantity, cap-and-trade sets price", "Tax sets price, cap-and-trade sets quantity", "They are identical", "Both set prices only"],
        answerIndex: 1,
      },
      {
        questionEn: "What lesson does the French yellow-vest crisis illustrate?",
        questionZh: "法国黄背心危机说明了什么？",
        options: ["Carbon taxes always succeed", "Carbon pricing must handle distributional fairness", "Fuel taxes are low", "Protesters oppose renewables"],
        answerIndex: 1,
      },
      {
        questionEn: "Why is battery storage described as the 'hinge of the entire transition'?",
        questionZh: "为什么电池储能被视为整个转型的关键枢纽？",
        options: ["Because it produces energy", "Because renewables are intermittent and need storage", "Because it is cheap", "Because it replaces solar"],
        answerIndex: 1,
      },
      {
        questionEn: "What is the fault line between developed and developing nations?",
        questionZh: "发达国家与发展中国家之间的断层线是什么？",
        options: ["Technology access only", "Who consumed the carbon budget and who must pay", "Language barriers", "Nuclear safety"],
        answerIndex: 1,
      },
      {
        questionEn: "What describes 'greenwashing'?",
        questionZh: "'greenwashing' 描述的是什么？",
        options: ["Planting trees", "Advertising superficial or false sustainability credentials", "Renewable investment", "Carbon capture"],
        answerIndex: 1,
      },
      {
        questionEn: "Which is NOT given as a possible tipping point risk?",
        questionZh: "下列哪项不是文中提到的临界点风险？",
        options: ["AMOC collapse", "Permafrost thawing", "Antarctic ice sheet collapse", "Global cooling"],
        answerIndex: 3,
        explainZh: "文中提到的临界点是 AMOC、永久冻土与冰盖，'global cooling' 与论述无关。",
      },
      {
        questionEn: "How does the author characterize most climate migration?",
        questionZh: "作者如何描述大多数气候移民？",
        options: ["Cross-border and permanent", "Internal, rural-to-urban", "Mainly from Europe", "Nonexistent"],
        answerIndex: 1,
      },
      {
        questionEn: "What does the author say about direct air capture?",
        questionZh: "作者对直接空气捕集有何评价？",
        options: ["It is cheap and abundant", "It is expensive and energy-hungry", "It is the main solution", "It relies on mangroves"],
        answerIndex: 1,
      },
      {
        questionEn: "How are fossil fuel denial tactics described as evolving?",
        questionZh: "作者如何描述化石燃料行业否认策略的演变？",
        options: ["They ended in 2020", "They shifted from denialism to survivable forms like greenwashing and both-sidesing", "They became more aggressive", "They were always passive"],
        answerIndex: 1,
      },
    ],
    summaryTaskZh: "Summarize in 100 words: 用科学确定性、经济成本下降、巴黎协定架构、发达国家与发展中国家分歧四个维度，概括本文关于气候挑战的核心论证。",
    opinionTaskZh: "The author writes that climate justice 'is the connective tissue that determines whether any global deal is acceptable.' To what extent do you agree that fairness between rich and poor nations, and between generations, is the decisive factor in climate action? Write 150–170 words, using one conditional-inversion structure and at least two nominalizations. Ready?",
  },
  {
    id: "reading-11-global-economy",
    number: 11,
    slug: "global-economy-interconnected",
    title: "The Global Economy: Interconnection, Inequality, and the Fragility of Growth",
    categoryZh: "全球经济",
    difficulty: "C2",
    wordCount: 4000,
    minutes: 27,
    article: [
      "The global economy is best understood not as a collection of national markets but as a single, densely wired system in which disruption anywhere transmits quickly almost everywhere. Forty years of falling trade barriers, containerized shipping, and digitized finance produced a level of interconnection unprecedented in history. That interconnection has delivered extraordinary gains in income, technology, and living standards while simultaneously engineering a web of vulnerabilities that crises expose with punishing regularity. The founding question of this era is whether the system's benefits can be preserved and its fragility tamed.",
      "Globalization is frequently assumed to be a recent invention, yet it is better described as a series of pulses that have risen, collapsed, and risen again. The classical nineteenth-century wave, driven by steamships, railways, and the telegraph, already produced remarkable commodity convergence and labor migration on a scale not matched since. That first era of globalization collapsed in 1914, torn apart by war, protectionism, and capital controls, and was not rebuilt until the late twentieth century. The postwar wave of the 1980s to the 2010s rested on two pillars: the political opening of China and the physical containerization of trade, each of which slashed the cost of moving goods and plugged billions of workers into global production networks.",
      "The sheer scale of that integration is staggering. World merchandise exports grew from under two trillion dollars in 2000 to more than twenty-five trillion by the late 2010s. Multinational corporations reorganized into global value chains, in which design happens in one country, manufacturing in another, and assembly in a third, with components crossing borders dozens of times before a final product reaches a consumer. The iPhone became the emblem of this arrangement — assembled in China from components that themselves crossed numerous borders, its true economic provenance scattered across a dozen economies.",
      "For decades this model appeared to benefit nearly everyone. Developing countries industrialized at unprecedented speed, hundreds of millions escaped extreme poverty, and advanced economies enjoyed falling consumer prices as imports substituted for domestic production. Yet the distribution was never as benign as aggregate numbers suggested. In advanced economies, manufacturing employment contracted as production migrated offshore, and much of the resulting income flowed to capital and skilled labor rather than to displaced workers. The political backlash against these distributional outcomes — visible in trade skepticism, protectionist rhetoric, and actual tariff wars — became one of the defining forces of the 2010s onwards.",
      "Nowhere is the fragility of the network clearer than in the supply chain disruptions that convulsed the world early in the 2020s. When the pandemic shut down ports, factories, and shipping lanes simultaneously, buyers discovered that just-in-time inventory systems — built to hold minimal stock and assume instant replenishment — had no resilience buffer. Freight rates surged to record levels, container shortages cascaded, and the semiconductor shortage that struck the auto and electronics industries demonstrated that a single bottleneck in a single commodity can stall output across a dozen sectors. The painful lesson was that efficiency optimized for normal times is systematically under-provisioned for abnormal ones.",
      "The semiconductor episode deserves particular attention because it exposed the geopolitical dimensions of economic interconnection. Taiwan produces a dominant share of the world's most advanced chips, and the concentration of this capability in a single, geopolitically contended island became, overnight, an urgent policy problem. Governments across the United States, Europe, Japan, and Korea launched massive subsidy programs to onshore chip production, treating the supply of advanced chips as a matter of national security rather than mere commerce. The belated discovery that critical capabilities had been concentrated in narrow geographies reshaped industrial policy across the world.",
      "The institutional geography of the world economy remains the contested legacy of the postwar settlement. The Group of Seven, the world's largest advanced economies, coordinates on economic and monetary matters but has been steadily undermined by the rise of the Group of Twenty, which includes major emerging economies and now hosts the most comprehensive discussion of global economic governance. The BRICS grouping — originally Brazil, Russia, India, China, and South Africa, later expanded — functions partly as a counterweight to Western-dominated institutions, though its members share little beyond a desire for a larger voice. The appeal of such groupings lies less in a coherent economic vision than in their promise of alternative poles of power.",
      "The twin Bretton Woods institutions, the International Monetary Fund and the World Bank, were designed to prevent a relapse into the interwar chaos of competitive devaluation and financial collapse. For decades they were the arbiters of crisis lending and development finance. Yet their governance remains frozen in the mid-twentieth century: voting power is roughly proportional to paid-in capital shares, which means the United States and Europe control commanding majorities while the rapidly growing economies of Asia complain, justly, that their weight in the institutions lags their weight in the world economy. The repeated calls for reform — more voice for developing nations, repurposing toward climate and pandemic resilience — have yielded only marginal adjustments.",
      "Nowhere is the divergence in institutional philosophy more instructive than in the relationship between the Chinese and Western economic models. China's state-led capitalism combines a formidable market economy with pervasive state ownership, directed credit, and industrial policy in which the state chooses priorities and channels finance accordingly. Its four-decade transformation — from agrarian poverty to the world's second-largest economy — is the most rapid economic ascent in recorded history. The Belt and Road Initiative, a sprawling infrastructure program spanning dozens of countries, exports that model of state-directed development alongside Chinese finance, though its critics note that some recipient countries have accumulated heavy, poorly conditioned debt as it matures.",
      "Europe offers a contrasting laboratory in the attempt to build unity through markets. The European Union's single market, begun in earnest in 1993, abolished internal barriers and created the world's largest integrated trading bloc. But the single market was built around a monetary union as well — the euro, adopted by most EU members — and the mismatch between a single currency and divergent national economies produced the eurozone crisis of the 2010s. When Greece's debts spiraled, the absence of fiscal union meant there was no automatic mechanism to transfer resources from surplus to deficit countries, and the crisis forced a painful choice between austerity and abandonment of the common currency.",
      "The austerity-versus-stimulus debate that followed is one of the most consequential intellectual battles in modern economics. Austerity — cutting government deficits during downturns — was justified by the belief that markets punish profligate governments with higher borrowing costs and that debts must be serviced. Its critics, drawing on the work of economists such as Paul Krugman, argued that austerity during a demand collapse is self-defeating, because shrinking public spending during a recession deepens the recession and raises debt-to-GDP ratios rather than lowering them. The empirical record of the eurozone — where heavily austere countries experienced deeper and more prolonged slumps — provided ammunition for the critical view, though the matter is far from settled.",
      "This debate has been radicalized by the emergence of Modern Monetary Theory, or MMT, which argues that a government that borrows in its own currency and maintains a floating exchange rate cannot be forced into insolvency, because it can always create the money to repay its debts. Under this view, the binding constraint on public spending is not the debt ceiling but inflation, so governments should treat price stability, not debt levels, as the relevant limit. The theory's adherents moved from academic margins to mainstream prominence when governments financed pandemic responses with enormous deficits and the inflation that followed tested precisely the limits MMT's critics had warned about.",
      "That inflation episode of the early 2020s reopened the classic debate about what causes inflation and who should arrest it. Inflation surged to multi-decade highs across advanced economies, driven by a collision of supply disruptions, energy price spikes, and stimulus-fueled demand. Central banks — which had moved to a doctrine of inflation targeting under which they hold inflation around two percent — responded with the most aggressive interest rate increases in a generation. The resurgence of inflation raised uncomfortable questions about whether the twenty-first century's low-inflation regime had fundamentally changed, and about the distributional pain of the cure: raising rates crushes demand, raises unemployment, and hurts debtors more than creditors.",
      "Central bank independence became a deeply political question in the process. The dominant postwar doctrine held that monetary policy must be insulated from democratic pressure, because politicians face short-term incentives to inflate away debt or boost growth ahead of elections. Independent central banks, answerable only to a mandated inflation target, were credited with anchoring expectations and delivering stable prices. But when the Federal Reserve and the European Central Bank raised rates aggressively, they imposed visible costs and were accused of both doing too much and too little. The institutions that once seemed technocratic and apolitical found themselves at the center of a redistributive battleground.",
      "The high interest rate environment rippled outward to test the resilience of the emerging markets that had grown dependent on cheap dollar financing. When the Fed raises rates, dollar-denominated debt becomes more expensive to service, capital flows out of risky assets, and currencies of debtor nations depreciate against a strengthening dollar. Countries such as Argentina, Pakistan, and a swath of African economies slipped into debt distress, and the crisis revealed the uncomfortable fact that many emerging economies borrowed heavily in dollars while earning in local currency — a mismatch that magnifies every global rate shock. The IMF's traditional prescription of belt-tightening reform attracted renewed criticism as a recipe that punishes the most vulnerable.",
      "Beneath these episodic crises lies the deeper matter of economic inequality, both within and between nations. The extraordinary global fact of the past forty years is a convergence between countries — hundreds of millions in Asia escaped poverty — accompanied by a divergence within many advanced countries, where the gains of growth concentrated at the top of the income distribution. This two-speed character drove much contemporary political turbulence: the workers who lost manufacturing jobs to globalization and the households squeezed by rising housing costs and stagnant real wages felt the costs personally while watching aggregate growth statistics report success. The disconnect between macro health and lived experience became the defining detail of the age.",
      "Commodity cycles add yet another layer of instability. Economies dependent on oil, copper, food, or other raw materials ride a boom-and-bust rhythm set less by their own decisions than by global demand and speculative finance. When prices rise, resource exporters enjoy windfalls and sometimes over-borrow against expected revenues; when prices collapse, they face sudden fiscal crises and balance-of-payment shocks. This dependence on a volatile price has long been described as a natural resource curse, though the mechanisms are institutional as much as economic — transparent governance and sovereign wealth funds can convert volatile windfalls into stable national savings, as Norway's oil fund demonstrates.",
      "The era's most consequential development may be the slowdown or reversal of the very globalization that created the system's gains. Deglobalization — the fragmenting of trade, finance, and production into blocs and national spheres — has accelerated under a combination of pandemic-induced de-risking, geopolitical rivalry between the United States and China, and a widespread political appetite for industrial policy and self-sufficiency. Trade is being weaponized through sanctions, export controls, and tariffs. Nations are actively encouraging the reshoring or nearshoring of critical production. Whether these efforts represent prudent diversification or a costly, self-defeating retreat from the specialization that generated historic prosperity is among the most consequential questions the century will answer.",
      "The honest assessment must hold two truths simultaneously. Interconnection has been a colossal engine of poverty reduction, innovation, and peace through interdependence — history's most effective anti-poverty program. Yet that same system distributes its gains unevenly, transmits shocks with terrifying speed, and concentrates enormous power in a handful of pivotal actors, from central banks to key commodity and technology producers. The future of the global economy is therefore not a technical puzzle to be solved once but an ongoing political negotiation about who shares in the gains, who bears the risks, and how much fragmentation the system can withstand before the benefits of interconnection begin to erode. The prosperity of the past forty years was a gift of institutions that must now be rebuilt, reformed, or paid for in kind through repeated, avoidable crises.",
    ],
    vocabularyNotes: [
      { term: "interconnection", zh: "相互连接；互联互通" },
      { term: "vulnerability", zh: "脆弱性；易受攻击的弱点" },
      { term: "regulatory", zh: "监管的" },
      { term: "slashed", zh: "v. 大幅削减" },
      { term: "provenance", zh: "来源；出处" },
      { term: "benign", zh: "良性的；有利的" },
      { term: "backlash", zh: "强烈反弹；抵制" },
      { term: "replenishment", zh: "补充；补货" },
      { term: "cascade", zh: "v. 级联；成串地传递" },
      { term: "bottleneck", zh: "瓶颈" },
      { term: "under-provisioned", zh: "供给不足的；储备不足的" },
      { term: "onshore", zh: "v. 将生产回流至本土" },
      { term: "contended", zh: "有争议的；争夺中的" },
      { term: "arbiter", zh: "仲裁者；裁决者" },
      { term: "frozen", zh: "冻结的；固定的" },
      { term: "pervasive", zh: "无处不在的；遍及的" },
      { term: "sprawling", zh: "蔓延扩张的；庞大的" },
      { term: "divergence", zh: "分化；分歧" },
      { term: "austerity", zh: "财政紧缩" },
      { term: "profligate", zh: "挥霍无度的；浪费的" },
      { term: "self-defeating", zh: "适得其反的" },
      { term: "radicalized", zh: "v. 使激进化" },
      { term: "insolvency", zh: "资不抵债；破产" },
      { term: "adherent", zh: "支持者；追随者" },
      { term: "insulate", zh: "v. 使隔离；使免受影响" },
      { term: "technocratic", zh: "技术官僚式的" },
      { term: "depreciate", zh: "v. 贬值" },
      { term: "mismatch", zh: "错配；不匹配" },
      { term: "windfall", zh: "意外之财；横财" },
      { term: "boom-and-bust", zh: "繁荣与萧条交替的" },
      { term: "weaponized", zh: "v. 武器化：被当作武器使用" },
      { term: "reshoring", zh: "回流本土（生产回迁）" },
      { term: "colossal", zh: "巨大的" },
      { term: "fragmenting", zh: "碎片化；分裂" },
      { term: "pivotal", zh: "关键的；核心的" },
    ],
    grammarNotes: [
      {
        topicId: "passive-across-tenses",
        titleZh: "跨时态被动语态表达客观事实",
        noteZh: "经济文本用被动（was designed / was torn apart / has been undermined）突出事件与制度而非施动者，营造客观权威。",
        exampleFromText: "The twin Bretton Woods institutions ... were designed to prevent a relapse into the interwar chaos.",
      },
      {
        topicId: "compound-complex-sentences",
        titleZh: "同位语与插入语",
        noteZh: "'the Group of Twenty, which includes major emerging economies and now hosts...' 前后的非限定信息形成进一步说明，是长句开展的常用手段。",
        exampleFromText: "The Group of Twenty, which includes major emerging economies and now hosts the most comprehensive discussion...",
      },
      {
        topicId: "fronting-and-ellipsis",
        titleZh: "前置与省略",
        noteZh: "'Beneath these episodic crises lies the deeper matter...' 与 'Trade is being weaponized through...' 用前置介词短语制造衔接与强调。",
        exampleFromText: "Beneath these episodic crises lies the deeper matter of economic inequality...",
      },
      {
        topicId: "complex-sentences",
        titleZh: "多从句复合句",
        noteZh: "经济长句通过时间状语从句、定语从句与条件从句的叠置精确限定命题范围，是 C2 级文本的标志。",
        exampleFromText: "When prices collapse, they face sudden fiscal crises and balance-of-payment shocks.",
      },
      {
        topicId: "reporting-passive-it-construction",
        titleZh: "it 引导的报道性被动",
        noteZh: "'The belated discovery that ... had been concentrated' 与 'It is frequently assumed that...' 用 it 结构把判断客观化、去个人化。",
        exampleFromText: "It is frequently assumed to be a recent invention, yet it is better described as a series of pulses...",
      },
      {
        topicId: "subjunctive-unreal-conditionals",
        titleZh: "假设条件与现实条件的分野",
        noteZh: "'If governments dare...' 与 'whether ... can withstand' 对比现实与假设，表达开放未来的不确定性。",
        exampleFromText: "how much fragmentation the system can withstand before the benefits of interconnection begin to erode.",
      },
      {
        topicId: "inversion-for-emphasis",
        titleZh: "倒装强调",
        noteZh: "'Nowhere is the fragility of the network clearer than...' 用否定前置加倒装，把对比论点置于句首要害位置。",
        exampleFromText: "Nowhere is the fragility of the network clearer than in the supply chain disruptions...",
      },
    ],
    questions: [
      {
        questionEn: "How does the author describe globalization's history?",
        questionZh: "作者如何描述全球化的历史？",
        options: ["As a recent, single continuous wave", "As a series of pulses that rose and collapsed", "As an entirely post-1980s phenomenon", "As unrelated to trade"],
        answerIndex: 1,
      },
      {
        questionEn: "What does the author say about just-in-time inventory systems?",
        questionZh: "作者如何评价准时制库存系统？",
        options: ["They are perfectly resilient", "They have no resilience buffer", "They reduce all costs", "They prevent crises"],
        answerIndex: 1,
      },
      {
        questionEn: "Why does the semiconductor shortage matter geopolitically?",
        questionZh: "为何半导体短缺在地缘政治上如此重要？",
        options: ["Chips are cheap", "A dominant share is produced in Taiwan, which is geopolitically contended", "All chips are made in Europe", "It is purely economic"],
        answerIndex: 1,
      },
      {
        questionEn: "How does the author characterize BRICS?",
        questionZh: "作者如何描述金砖国家组织？",
        options: ["A coherent economic bloc", "A grouping sharing mostly a desire for a larger voice", "A military alliance", "A monetary union"],
        answerIndex: 1,
      },
      {
        questionEn: "What does the author cite as the governance problem of the IMF and World Bank?",
        questionZh: "作者指出 IMF 和世界银行的治理问题是什么？",
        options: ["They are too democratic", "Voting power lags the emerging economies' actual weight", "They have too many branches", "They ignore Europe"],
        answerIndex: 1,
      },
      {
        questionEn: "What was the central cause of the eurozone crisis according to the passage?",
        questionZh: "根据文章，欧元区危机的核心原因是什么？",
        options: ["A single currency with no fiscal transfer mechanism", "Too much fiscal union", "Excessive central bank intervention", "Foreign invasion"],
        answerIndex: 0,
        explainZh: "文章指出：单一货币与缺乏财政联盟的错配导致危机爆发。",
      },
      {
        questionEn: "What does Modern Monetary Theory (MMT) argue?",
        questionZh: "现代货币理论 (MMT) 的核心主张是什么？",
        options: ["Governments must balance budgets", "A government borrowing in its own currency cannot be forced into insolvency", "Inflation is never a risk", "Debt ceilings are the binding constraint"],
        answerIndex: 1,
      },
      {
        questionEn: "What does the author say about the price of the inflation cure?",
        questionZh: "作者对通胀治理代价的评价是什么？",
        options: ["It is painless", "Raising rates hurts debtors more than creditors", "It only affects the rich", "It never causes unemployment"],
        answerIndex: 1,
      },
      {
        questionEn: "Why did central bank independence become a political question?",
        questionZh: "为什么央行独立性成为一个政治问题？",
        options: ["Because independence is undemocratic per se", "Because aggressive rate hikes imposed visible redistributive costs", "Because central banks are private", "Because inflation is imaginary"],
        answerIndex: 1,
      },
      {
        questionEn: "How does a strong dollar affect dollar-denominated emerging-market debt?",
        questionZh: "强势美元对以美元计价的国债有何影响？",
        options: ["It becomes cheaper", "It becomes more expensive to service", "It is unaffected", "It converts to local currency"],
        answerIndex: 1,
      },
      {
        questionEn: "What is the 'two-speed character' of globalization?",
        questionZh: "全球化的'两速特征'指的是什么？",
        options: ["Fast shipping and slow finance", "Convergence between countries but divergence within many advanced countries", "Equal gains everywhere", "Faster growth in rich countries"],
        answerIndex: 1,
      },
      {
        questionEn: "What does the author identify as history's most effective anti-poverty program?",
        questionZh: "作者认为历史上最有效的脱贫计划是什么？",
        options: ["Foreign aid", "Interconnection and interdependence through globalization", "Austerity", "Nuclear energy"],
        answerIndex: 1,
      },
    ],
    summaryTaskZh: "Summarize in 100 words: 用互联互通、脆弱性、制度治理、分化与去全球化五个维度，概括本文关于全球经济困境与前景的论证。",
    opinionTaskZh: "The author argues that the global economy distributes gains unevenly and transmits shocks with terrifying speed. Do you believe deglobalization will make the world economy fairer and safer, or poorer and less efficient? Write 150–170 words, using one passive-infinitive structure, one inversion, and at least two nominalizations.",
  },
  {
    id: "reading-12-financial-markets",
    number: 12,
    slug: "financial-markets-system",
    title: "Financial Markets: Architecture, Crises, and the Illusion of Stability",
    categoryZh: "金融市场",
    difficulty: "C2",
    wordCount: 4200,
    minutes: 28,
    article: [
      "Financial markets are, at their most basic, machinery for matching savers with borrowers and for pricing risk across space and time. A bond transfers a defined stream of future payments to whoever holds it; an equity share grants its holder a claim on a company's residual profits; a derivative derives its value from some underlying asset or event. This machinery, when it works, allocates capital to its most productive uses and lets households smooth consumption across their lifetimes. When it fails, it does so with a speed and ferocity that convulses entire economies. The puzzle of modern finance is that the same architecture that generates extraordinary prosperity also manufactures spectacular and recurring collapse.",
      "The stock market remains the public face of finance — the place where corporate valuation is most visibly contested, where the fortunes of towering companies rise and fall, and where the mood of the investing public is crystallized daily in a fluctuating index. Yet equities are only one layer of a towering edifice. Below them lies the far larger and less visible bond market, through which governments and corporations borrow, through which central banks conduct monetary policy, and whose depth and liquidity determine whether the entire system can absorb shocks without seizing. For all the public attention lavished on equities, it is the bond market that financiers watch most carefully when crisis looms.",
      "Derivatives add a further, and deeply misunderstood, dimension. An option confers the right — but not the obligation — to buy or sell an asset at a stated price before a stated date; a futures contract obligates both parties to transact at a predetermined price on a predetermined date; a swap exchanges one stream of payments for another, most famously exchanging fixed interest payments for floating ones. Derivatives were originally invented to hedge risk: an airline that buys jet fuel futures protects itself against rising fuel prices, a farmer who sells crop futures locks in a price before the harvest. But derivatives also permit speculation and leverage on an astonishing scale, and it is this dual nature — insurance instrument and multiplication device — that gives them their dangerous elegance.",
      "The elegance turned catastrophic in 2008, and tracing the origin of that crisis requires understanding how finance had transformed itself in the preceding decades. The core innovation, or pathology according to its critics, was securitization: the practice of pooling thousands of individual loans — mortgages, say, or credit-card debts — and slicing the pooled cash flows into tranches with different risk profiles. Senior tranches, promised first claim on payments, were rated near-safe and sold widely; junior tranches absorbed losses first and offered higher yields. This technology was supposed to diversify risk away, dispersing it through the financial system so that no single point of failure could bring the whole down.",
      "The consequence was instead a catastrophic concentration of mispriced risk. The mortgages feeding the pools were increasingly 'subprime' — extended to borrowers with weak credit histories, often with low teaser rates that reset upward after a couple of years. Investment banks, hungry to keep the securitization pipeline full, relaxed underwriting standards and handed out mortgages to applicants who could not possibly sustain the payments. Rating agencies, paid by the very issuers whose securities they rated, stamped complex products with triple-A ratings they did not deserve. By the mid-2000s the entire edifice rested on a mountain of debt whose true quality nobody adequately understood, held in shadowy corners of the balance sheets of the most interconnected institutions.",
      "When housing prices turned and subprime defaults spiked, the mispricing revealed itself with brutal totality. Mortgage-backed securities, which had been traded as if they were safe, lost enormous value, and the institutions that held them — which, through borrowing and derivatives, had leveraged their positions to far beyond their actual capital — found that assets they had marked at high values were worth a fraction of that. Panic spread across the system as trust evaporated, because no institution could tell how much of its counterparty's supposedly safe collateral was toxic. Interbank lending froze, and the architecture designed to disperse risk had instead concentrated it in nodes so interconnected that the failure of one could cascade through all.",
      "The anatomy of this catastrophe traced back to regulatory decisions made decades earlier. The Glass-Steagall Act of 1933 had, in the aftermath of the Great Depression, separated commercial banking from investment banking, erecting a wall intended to prevent ordinary depositors' savings from being gambled in speculative markets. That wall, eroded by decades of regulatory innovation and legal interpretation, was effectively repealed in 1999 by the Gramm-Leach-Bliley Act, which allowed the merger of commercial, investment, and insurance functions into sprawling financial conglomerates. The repeal embodied the era's governing assumption — that modern risk management had made the wall obsolete — an assumption the crisis would demolish with devastating thoroughness.",
      "The response came in the form of the Dodd-Frank Wall Street Reform and Consumer Protection Act of 2010, the most sweeping financial reform since the Depression. Dodd-Frank created new agencies, imposed stress tests on banks, and established a framework for orderly resolution of failing institutions. Its centerpiece was the Volcker Rule, which sought to re-erect something like the old separation by banning banks, or institutions backed by insured depositors, from proprietary trading — trading for their own account rather than on behalf of clients. Yet the rule was diluted by countless exemptions and interpretations, and the debate over whether Dodd-Frank successfully addressed the sources of fragility, or merely relocated them, has never fully closed.",
      "The depths of the modern system harbor further sources of instability that no single crisis has fully resolved. High-frequency trading, in which algorithms buy and sell in fractions of a second, has transformed market microstructure, providing vast liquidity in normal times but also the capacity to introduce violent, self-reinforcing volatility. Flash crashes — sudden, dramatic plunges in prices that reverse almost immediately — expose the paradox that markets run by machines can move faster than any human regulator can respond. The best-known example, the flash crash of May 2010, saw the Dow Jones plunge nearly a thousand points within minutes before recovering; its precise causes were debated for years.",
      "The creation of cryptocurrencies added a new frontier of instability and ideology. Bitcoin, launched in 2009 by the pseudonymous Satoshi Nakamoto, proposed a peer-to-peer digital cash independent of any central authority, its supply mathematically constrained by mining rather than by policy. Ethereum followed, adding a programmable layer on which developers could build decentralized applications. The promise, fiercely held by a dedicated subculture, was of a finance freed from intermediaries, censorship, and the arbitrary power of central banks. The practice, however, produced extraordinary price volatility, vulnerability to fraud, and, in the case of some exchanges, outright collapse that erased enormous sums.",
      "The most radical extension of this vision is decentralized finance, or DeFi, which attempts to reconstruct the entire financial intermediation stack — lending, borrowing, trading, derivatives — as a set of automated protocols running on blockchains without any bank in the middle. Its advocates celebrate the elimination of rent-seeking intermediaries; its critics emphasize that the protocols' code, however elegant, cannot repeal the underlying economics of leverage, fraud, and panic, and that DeFi's promise of decentralization has often masked heavy concentration of power in a few founders and in the creators of the tokens themselves. The liquidity crises that repeatedly rattle DeFi markets suggest that removing trusted intermediaries also removes a source of stabilizing judgment.",
      "The established financial system's response to this challenge has been the exploration of central bank digital currencies, or CBDCs — digital forms of fiat money issued directly by central banks. China has piloted its digital yuan; the Federal Reserve has studied but resisted a US digital dollar; the European Central Bank has advanced its digital euro project. CBDCs promise cheaper payments and greater financial inclusion, but they also raise profound questions about privacy, surveillance, and the structure of the monetary system: if the central bank issues the money directly and holds accounts for everyone, what role remains for commercial banks, and what limits constrain the state's visibility into its citizens' transactions?",
      "The global financial system has been periodically rocked by scandals that reveal the gap between the industry's stated ethics and its realized conduct. The LIBOR scandal stands out: the London Interbank Offered Rate, the reference rate for trillions of dollars in loans, mortgages, and derivatives, was manipulated for years, as bank traders colluded to set rates that benefited their own positions. The fraud was eventually exposed, banks paid billions in fines, and the scandal contributed to a slow, lurching transition to alternative reference rates. The episode dramatized that seemingly technical infrastructure — the benchmark rates on which entire markets depend — rests ultimately on the honesty of a handful of humans with strong incentives to lie.",
      "The crisis also cast a harsh light on the credit rating agencies, the private firms whose opinions about the creditworthiness of bonds and structured products gatekeep access to capital markets. Their concentration — three agencies dominate the field — and their payment model — the issuer pays for the rating — create a structural conflict of interest that the crisis exposed in its starkest form. Ratings both cause and reflect outcomes: a downgrade can trigger forced selling and a cascade of further downgrades, a mechanism that amplifies crises. Reform efforts have tinkered with the model and increased oversight, but the fundamental tension of privately-supplied public trust survived the reform intact.",
      "Beyond the regulated institutions lies the shadow banking system — a sprawl of hedge funds, money market funds, special-purpose vehicles, and securitization conduits that perform banking functions without being subject to the same capital, liquidity, and disclosure requirements as banks. Shadow banking was at the center of the 2008 crisis and has since grown, not shrunk, as regulation pushed activity beyond the reach of bank oversight. The distinction between bank and shadow bank has blurred as traditional banks themselves sponsor and manage such vehicles. When the panic of 2008 froze these markets, the crisis demonstrated with finality that shadow intermediation had created risk that the regulated system would ultimately be forced to absorb, a reality captured in the uncomfortable phrase 'tool big to fail.'",
      "That phrase captures one of the deepest pathologies of modern finance: moral hazard. If a handful of institutions are so interconnected and so large that their failure would topple the financial system, then governments cannot allow them to fail, and if governments cannot allow them to fail, creditors never discipline them with market forces. Banks that know they will be rescued can borrow more cheaply and take on more risk than prudent lending would permit, because the downside is socialized while the upside is privatized. Basel III, the international framework of capital and liquidity standards negotiated after the crisis, sought to reduce this hazard by forcing banks to hold more and better-quality capital, yet the tension between guaranteeing stability and preserving market discipline remains unresolved.",
      "The philosophy of financial regulation oscillates between two poles. On one side stands the view that markets are fundamentally self-correcting, that excessive rulemaking merely creates complexity and evasion, and that regulators should focus on transparency and disclosure rather than on dictating how institutions may behave. On the other stands the view that financial markets are prone to herd behavior, that leverage and complexity breed fragility, and that stable finance is a public good which markets left to themselves will systematically under-produce. The 2008 crisis pushed policy decisively toward the latter view for a time, but the political and ideological pendulum has since swung back, and debates over the appropriate boundary between state authority and private autonomy in finance remain among the most consequential disagreements of the age.",
      "The recurring, uncomfortable conclusion is that financial stability is fundamentally an illusion — a condition that exists only as the calm between storms, maintained by institutions whose incentives and behavior guarantee its eventual collapse. Every generation of regulators, armed with the lessons of the last crisis, rebuilds the system's defenses, and every generation discovers that the moments of calm they engineered were partly produced by the very complacency that made the next crisis possible. The market's greatest strength — its ability to mobilize capital and price risk — is inseparable from its permanent vulnerability to the leverage, herding, and informational asymmetries that no reform has yet repealed. The architecture of finance can be improved, and has been, repeatedly. The wisdom of finance lies in the honest acknowledgment that the architecture will never be made permanently, structurally safe, only temporarily and imperfectly so.",
    ],
    vocabularyNotes: [
      { term: "allocates", zh: "v. 分配；配置" },
      { term: "residual", zh: "剩余的；残值的" },
      { term: "ferocity", zh: "猛烈；凶猛" },
      { term: "convulses", zh: "v. 使剧烈动荡；震动" },
      { term: "crystallized", zh: "v. 具体化；（使）明确成形" },
      { term: "edifice", zh: "大厦；（比喻）宏大体系" },
      { term: "lavished", zh: "v. 慷慨给予；大量投入" },
      { term: "looms", zh: "v. 逼近；隐约显现" },
      { term: "obligates", zh: "v. 使负有义务" },
      { term: "leverage", zh: "n. 杠杆；借债放大风险" },
      { term: "pathology", zh: "病理；病态（比喻）" },
      { term: "tranche", zh: "（结构金融）层；份额" },
      { term: "subprime", zh: "次级（贷款）；低于优惠级别的" },
      { term: "teaser rates", zh: "诱饵利率" },
      { term: "underwriting", zh: "承销；担保承保" },
      { term: "counterparty", zh: "交易对手" },
      { term: "toxic", zh: "有毒的；（比喻）难以处置的" },
      { term: "eroding", zh: "v. 侵蚀；逐步削弱" },
      { term: "repealed", zh: "v. 废除（法律）" },
      { term: "conglomerate", zh: "大型联合企业" },
      { term: "obsolete", zh: "过时的；废弃的" },
      { term: "demolish", zh: "v. 摧毁；彻底否定" },
      { term: "sweeping", zh: "全面的；大刀阔斧的" },
      { term: "proprietary", zh: "自营的（此处指自营交易）" },
      { term: "diluted", zh: "v. 稀释；削弱" },
      { term: "microstructure", zh: "微观结构" },
      { term: "pseudonymous", zh: "化名的；匿名的" },
      { term: "intermediary", zh: "中介机构" },
      { term: "censorship", zh: "审查；屏蔽" },
      { term: "rent-seeking", zh: "寻租的（靠特权获利）" },
      { term: "rattle", zh: "v. 使震荡；使慌乱" },
      { term: "fiat money", zh: "法定货币" },
      { term: "surveillance", zh: "监控；监视" },
      { term: "colluded", zh: "v. 串通；共谋" },
      { term: "lurching", zh: "踉跄的；反复受阻的" },
      { term: "benchmark", zh: "基准（利率）" },
      { term: "gatekeep", zh: "v. 把控准入；把守关口" },
      { term: "conduit", zh: "管道；（资金）渠道" },
      { term: "socialized", zh: "v. 社会化（此处指责由政府/公众承担）" },
      { term: "complacency", zh: "自满；麻痹大意" },
      { term: "asymmetries", zh: "不对称；不均衡" },
    ],
    grammarNotes: [
      {
        topicId: "relative-clauses-defining-nondefining",
        titleZh: "非限定性定语从句解释术语",
        noteZh: "金融文本用逗号隔开的非限定从句（'which was traded as if it were safe'）嵌入被修饰概念的解释，形成精确的紧凑长句。",
        exampleFromText: "sets a price ... a swap exchanges one stream of payments for another, most famously exchanging fixed interest payments for floating ones.",
      },
      {
        topicId: "subjunctive-unreal-conditionals",
        titleZh: "虚拟语气表达假设与现实反差",
        noteZh: "'as if they were safe' 用 were 表达与现实相反的假设，是金融叙事中呈现'表面与实质'张力的典型句法。",
        exampleFromText: "Mortgage-backed securities, which had been traded as if they were safe, lost enormous value...",
      },
      {
        topicId: "nominalization",
        titleZh: "名词化压缩因果链条",
        noteZh: "'the mispricing revealed itself'、'the erosion of trust' 把动词过程打包成名词，使因果链条紧凑且立场鲜明。",
        exampleFromText: "the erosion ... of standards ... combines ... to produce ...",
      },
      {
        topicId: "hedging-language",
        titleZh: "hedging 表达判断强度",
        noteZh: "段落使用 doubt、practically、roughly 等词微调断言强度，反映金融叙事中'确定性'与'不确定性'并存的属性。",
        exampleFromText: "The anatomy of this catastrophe traced back to regulatory decisions made decades earlier.",
      },
      {
        topicId: "parallelism-rules",
        titleZh: "排比结构强化对比",
        noteZh: "'can be improved, and has been, repeatedly' 以及成组的三项并列（bond/equity/derivative）通过排比制造节奏与说服力。",
        exampleFromText: "The architecture of finance can be improved, and has been, repeatedly.",
      },
      {
        topicId: "emphasis-structures-cleft",
        titleZh: "强调句与本句聚焦",
        noteZh: "'It is this dual nature — insurance instrument and multiplication device — that gives them their dangerous elegance' 用 it 强调句把焦点锁定于某特征。",
        exampleFromText: "It is this dual nature — insurance instrument and multiplication device — that gives them their dangerous elegance.",
      },
      {
        topicId: "inversion-for-emphasis",
        titleZh: "否定前置倒装",
        noteZh: "'Beyond the regulated institutions lies...' 用介词短语前置加倒装组织语篇，把新话题引入句首核心位置。",
        exampleFromText: "Beyond the regulated institutions lies the shadow banking system...",
      },
    ],
    questions: [
      {
        questionEn: "What is the author's characterization of financial markets' core function?",
        questionZh: "作者如何描述金融市场的核心功能？",
        options: ["To generate constant instability", "To match savers with borrowers and price risk", "To eliminate all risk", "To subsidize governments"],
        answerIndex: 1,
      },
      {
        questionEn: "Which market does the author say financiers watch most carefully when crisis looms?",
        questionZh: "作者认为危机逼近时金融家最关注哪个市场？",
        options: ["The stock market", "The bond market", "The housing market", "The crypto market"],
        answerIndex: 1,
      },
      {
        questionEn: "What was the supposed purpose of securitization?",
        questionZh: "资产证券化的预期目的（according to the passage）是什么？",
        options: ["To concentrate risk", "To diversify risk through dispersion", "To lower all interest rates", "To eliminate mortgages"],
        answerIndex: 1,
      },
      {
        questionEn: "What does the author cite as a cause of the decline in mortgage underwriting standards?",
        questionZh: "作者认为承销标准下降的原因是什么？",
        options: ["Government pressure", "Investment banks' hunger to keep the securitization pipeline full", "Borrower demand", "Currency collapse"],
        answerIndex: 1,
      },
      {
        questionEn: "What did the Glass-Steagall Act do?",
        questionZh: "《格拉斯-斯蒂格尔法案》做了什么？",
        options: ["Merged commercial and investment banking", "Separated commercial from investment banking", "Created the Federal Reserve", "Legalized derivatives"],
        answerIndex: 1,
      },
      {
        questionEn: "What did the Volcker Rule seek to do?",
        questionZh: "沃尔克规则的目的是什么？",
        options: ["Ban all derivatives", "Ban proprietary trading by banks backed by insured depositors", "Legalize insider trading", "Merge all banks"],
        answerIndex: 1,
      },
      {
        questionEn: "How does the author describe high-frequency trading?",
        questionZh: "作者如何评价高频交易？",
        options: ["Purely benign", "Providing liquidity in normal times but enabling violent volatility", "Illegal in all countries", "Slow and outdated"],
        answerIndex: 1,
      },
      {
        questionEn: "What critique of DeFi does the author offer?",
        questionZh: "作者对 DeFi 提出了什么批评？",
        options: ["Its code cannot repeal the economics of leverage, fraud, and panic", "It is too centralized", "It removes all intermediaries", "It is illegal"],
        answerIndex: 0,
        explainZh: "作者认为 DeFi 的代码再优雅也无法取消杠杆、欺诈与恐慌的经济学规律。",
      },
      {
        questionEn: "What questions do central bank digital currencies raise?",
        questionZh: "央行数字货币引发哪些问题？",
        options: ["Only technical ones", "Privacy, surveillance, and the structure of the monetary system", "None", "Exchange rates"],
        answerIndex: 1,
      },
      {
        questionEn: "What does the author say about credit rating agencies' conflict of interest?",
        questionZh: "作者如何评价信用评级机构的利益冲突？",
        options: ["It does not exist", "The issuer pays the rating, creating a structural conflict", "Agencies are independent", "It favors borrowers"],
        answerIndex: 1,
      },
      {
        questionEn: "How does the author explain moral hazard in banking?",
        questionZh: "作者如何解释银行业的道德风险？",
        options: ["Banks always behave prudently", "Because governments cannot allow big banks to fail, creditors never discipline them with market forces", "It does not exist", "It benefits depositors"],
        answerIndex: 1,
      },
      {
        questionEn: "What is the author's final conclusion about financial stability?",
        questionZh: "作者对金融稳定的最终结论是什么？",
        options: ["It is permanent", "It is an illusion that exists only between storms", "It can be achieved once and for all", "It depends only on banks"],
        answerIndex: 1,
      },
    ],
    summaryTaskZh: "Summarize in 100 words: 用市场架构（股票/债券/衍生品）、2008危机成因、监管回应（Dodd-Frank/Volcker/Basel III）、道德风险与稳定性幻觉五个维度，概括本文的核心论证。",
    opinionTaskZh: "The author concludes that financial stability is fundamentally an illusion and that markets must be reformed repeatedly yet can never be made permanently safe. Do you agree that regulation can never fully tame financial fragility, or do you believe stronger, wiser regulation could achieve durable stability? Write 150–170 words, using one unreal conditional (as if/were), one cleft emphasis structure, and at least two nominalizations. Ready?",
  },
  ...P19_READING_PART1,
  ...P19_READING_PART2,
  ...P19_READING_PART3,
  ...P19_READING_PART4,
  ...P19_READING_PART5,
  ...P19_READING_PART6,
];
