import type { VideoResource } from "@/content/resources/video-library";

/** Phase 17-D: +20 additional video resources (total 30). */
export const ADDITIONAL_VIDEO: readonly VideoResource[] = [
  { id: "video-11-mit-intro-ai", number: 11, title: "MIT 6.S191 — Introduction to Deep Learning", source: "MIT OpenCourseWare", url: "https://introtodeeplearning.com/", level: "C2", durationMinutes: 50, skillFocus: "listening", categoryZh: "AI深度学习导论", tasksZh: ["跟读模型架构描述段", "记录五个技术术语", "写100词总结"] },
  { id: "video-12-yale-psychology", number: 12, title: "Yale PSYC 110 — Introduction to Psychology (video)", source: "Yale Open Courses", url: "https://oyc.yale.edu/psychology/psyc-110", level: "C1", durationMinutes: 60, skillFocus: "listening", categoryZh: "心理学大学课", tasksZh: ["使用官方文字稿二遍法", "整理核心概念表", "写100词课程摘要"] },
  { id: "video-13-ted-climate-science", number: 13, title: "TED Climate Change playlist — curated talks", source: "TED Climate playlist", url: "https://www.ted.com/topics/climate+change", level: "C1", durationMinutes: 45, skillFocus: "listening", categoryZh: "气候科学演讲集", tasksZh: ["任选三讲：记录数据引用方式", "比较讲者的解决方案框架", "写一段对比分析"] },
  { id: "video-14-stanford-startup", number: 14, title: "Stanford eCorner — entrepreneurship lecture series", source: "Stanford eCorner", url: "https://ecorner.stanford.edu/", level: "C1", durationMinutes: 50, skillFocus: "speaking", categoryZh: "斯坦福创业课", tasksZh: ["选一讲：记录商业模式画布要素", "模仿创始人 pitch 的开场 60 秒", "用英语写一句你的创业想法"] },
  { id: "video-15-pbs-frontline-ai", number: 15, title: "PBS Frontline — AI documentary episode", source: "PBS Frontline", url: "https://www.pbs.org/wgbh/frontline/", level: "C2", durationMinutes: 55, skillFocus: "reading", categoryZh: "AI调查纪录片", tasksZh: ["观看前阅读官网调查报告提纲", "记录证据呈现顺序", "写120词编辑立场分析"] },
  { id: "video-16-ted-brain-science", number: 16, title: "TED Brain Science playlist — neuroscience talks", source: "TED Brain playlist", url: "https://www.ted.com/topics/neuroscience", level: "C1", durationMinutes: 40, skillFocus: "vocabulary", categoryZh: "脑科学演讲", tasksZh: ["收集十个神经科学术语", "跟读定义句并录音", "写一段科普转述"] },
  { id: "video-17-crashcourse-literature", number: 17, title: "CrashCourse Literature — analysis episodes", source: "CrashCourse Literature", url: "https://www.youtube.com/@crashcourse", level: "B2", durationMinutes: 12, skillFocus: "reading", categoryZh: "文学分析速览", tasksZh: ["选一集：记下三个批评术语", "阅读对应原著节选", "写一段主题分析"] },
  { id: "video-18-ted-business-strategy", number: 18, title: "TED Business Strategy playlist", source: "TED Business playlist", url: "https://www.ted.com/topics/business", level: "C1", durationMinutes: 35, skillFocus: "listening", categoryZh: "商业策略演讲", tasksZh: ["选一讲：提取核心商业模型", "分析讲者的说服技巧", "写80词英文回应"] },
  { id: "video-19-khan-academy-statistics", number: 19, title: "Khan Academy — Statistics & Probability course videos", source: "Khan Academy", url: "https://www.khanacademy.org/math/statistics-probability", level: "B2", durationMinutes: 20, skillFocus: "vocabulary", categoryZh: "统计学教程", tasksZh: ["看完一个单元：建术语表", "练习口述统计概念", "写一段方法说明"] },
  { id: "video-20-yale-environmental-humanities", number: 20, title: "Yale Environment 360 — video interviews", source: "Yale Environment 360", url: "https://e360.yale.edu/", level: "C2", durationMinutes: 15, skillFocus: "listening", categoryZh: "环境人文访谈", tasksZh: ["看两段访谈：记录科学家vs活动家的语言差异", "写一段立场分析"] },
];
