import type { CourseDayPlan } from "@/content/pipeline/generate-days";

/** Day 111-130 工作沟通深化 - compact real plans. */
export const PLAN_111_130: readonly CourseDayPlan[] = [
  { day: 111, titleEn: "Project Kickoff Alignment", titleZh: "第 111 天 · 项目启动对齐", goalZh: "用对齐语言确认目标与范围。",
    vocabIds: ["w:goal", "w:agenda", "w:collaborate", "w:assignment", "w:deadline"], grammarTopicId: "basic-clauses", phonicsRuleIds: ["ai", "oa"],
    pattern: { titleZh: "句型：Let's make sure we're aligned on ___.", explainZh: "复习已学内容并识别需要进一步练习的领域，确保知识巩固。",
      examples: [["Let's make sure we're aligned on the goal.", "我们先对齐目标。"], ["w:feedback", "范围到底包括什么？"], ["I'll own the timeline.", "时间表由我负责。"]],
      sentences: [["w:feedback", "谁是对接人？"], ["Deliverables go out every Friday.", "交付物每周五提交。"], ["Flag risks early, please.", "风险请尽早提出。"]] },
    reading: [["The kickoff took thirty minutes, not sixty.", "启动会只用了三十分钟而非一小时。"], ["Roles were written on one slide.", "分工只用一页幻灯片写清。"], ["Nobody asked whose job it was again.", "再没人问那是谁的活。"]],
    writing: { zh: "写一句项目目标对齐的话。", hintEn: "We're aligned on ___ by ___." } },
  { day: 112, titleEn: "Status Update: Progress", titleZh: "第 112 天 · 汇报进展", goalZh: "三句话讲清进展：完成/进行/下一步。",
    vocabIds: ["w:progress-n", "w:complete", "w:deadline", "w:performance", "w:feedback"], grammarTopicId: "present-progressive", phonicsRuleIds: ["pl", "ee"],
    pattern: { titleZh: "句型：___ is done. ___ is in progress. Next up: ___.", explainZh: "汇报节奏 done → in progress → next；百分比说 % complete。",
      examples: [["The design is done.", "设计已完成。"], ["Testing is in progress.", "测试正在进行。"], ["Next up: user interviews.", "接下来是用户访谈。"]],
      sentences: [["We're about seventy percent complete.", "完成了大约七成。"], ["No blockers on my side.", "我这边没有阻塞。"], ["More details in the doc.", "详情见文档。"]] },
    reading: [["Ben's updates follow a template.", "本的汇报有模板。"], ["Green means done, yellow means risky.", "绿代表完成，黄代表有风险。"], ["His manager reads them in ten seconds.", "经理十秒读完。"]],
    writing: { zh: "用三句话汇报手头的事。", hintEn: "___ is done. ___ is in progress. Next: ___." } },
  { day: 113, titleEn: "Reporting Problems", titleZh: "第 113 天 · 汇报问题", goalZh: "报告坏消息并附上方案。",
    vocabIds: ["w:solve", "w:respond", "w:detect", "w:escalate-issue", "w:request"], grammarTopicId: "negation", phonicsRuleIds: ["bl", "e-short"],
    pattern: { titleZh: "句型：We've hit a problem with ___. I suggest ___.", explainZh: "坏消息+方案一起说：hit a problem with… I suggest…。",
      examples: [["We've hit a problem with the API.", "API 出了问题。"], ["The data didn't sync overnight.", "数据夜里没同步。"], ["I suggest rolling back to v1.", "我建议回滚到第一版。"]],
      sentences: [["I need input from security.", "我需要安全团队的输入。"], ["w:feedback", "今天能抽十五分钟吗？"], ["Here's what I've tried so far.", "这是我目前的尝试。"]] },
    reading: [["Nina found a bug at four on Friday.", "妮娜周五四点发现漏洞。"], ["She reported steps and a screenshot.", "她带复现步骤和截图上报。"], ["Fix shipped before Monday standup.", "周一站会前修复上线。"]],
    writing: { zh: "写一句带方案的坏消息汇报。", hintEn: "We hit a problem with ___. I suggest ___." } },
  { day: 114, titleEn: "Dividing the Work", titleZh: "第 114 天 · 项目分工", goalZh: "主动认领任务、礼貌分配。",
    vocabIds: ["w:divide", "w:teammate", "w:fairness", "w:workload", "w:collaborate"], grammarTopicId: "questions", phonicsRuleIds: ["ai", "pl"],
    pattern: { titleZh: "句型：I can take ___, if you handle ___.", explainZh: "分工句式 take/own/cover + 任务；交换条件用 if。",
      examples: [["I can take the slides.", "我来做幻灯片。"], ["w:feedback", "你能负责数据部分吗？"], ["w:feedback", "这样分公平吗？"]],
      sentences: [["Let's list everything first.", "先列清所有事。"], ["Two tasks each sounds right.", "每人两件比较合理。"], ["Ping me when your part ships.", "你的部分好了叫我。"]] },
    reading: [["Sticky notes covered the whiteboard.", "白板贴满便利贴。"], ["Each name got two colors of dots.", "每个名字旁两种颜色的点。"], ["Ownership was clear before lunch.", "午饭前分工明确。"]],
    writing: { zh: "写一句认领任务的话。", hintEn: "I'll take ___ if you can handle ___." } },
  { day: 115, titleEn: "Negotiating Timelines", titleZh: "第 115 天 · 协商时间表", goalZh: "为时间表讨价还价并给出依据。",
    vocabIds: ["w:negotiate", "w:extend", "w:milestone", "w:agenda", "w:feedback"], grammarTopicId: "future-simple", phonicsRuleIds: ["oa", "st"],
    pattern: { titleZh: "句型：If we move ___, we can ship by ___.", explainZh: "谈判公式 If we X, then Y by DATE；buffer 表示缓冲。",
      examples: [["w:feedback", "发布能推一周吗？"], ["If we cut scope, we ship on time.", "减范围就能按时上线。"], ["Let's add a two-day buffer.", "留两天缓冲吧。"]],
      sentences: [["w:feedback", "截止日的由来是什么？"], ["Quality drops when we rush QA.", "赶测试会掉质量。"], ["I'd rather under-promise.", "我宁可少承诺。"]] },
    reading: [["Marketing wanted March; engineering said May.", "市场要三月，工程说五月。"], ["They mapped dependencies on one page.", "依赖关系铺在一页上。"], ["The compromise: beta in April.", "折中：四月出测试版。"]],
    writing: { zh: "写一句延期申请及补偿条件。", hintEn: "If we ___, we can still deliver ___ by ___." } },
  { day: 116, titleEn: "Disagreeing in Meetings", titleZh: "第 116 天 · 会上表达不同意见", goalZh: "有依据地反对，不攻击人。",
    vocabIds: ["w:disagree", "w:however", "w:evidence", "w:defend", "w:on-the-other-hand"], grammarTopicId: "basic-clauses", phonicsRuleIds: ["ai", "th-vd"],
    pattern: { titleZh: "句型：I see it differently, because ___.", explainZh: "反对三段：认可部分 → however → 数据/理由。",
      examples: [["I see it differently, based on the data.", "基于数据我看发不同。"], ["However, users asked for the opposite.", "不过用户要求正相反。"], ["w:feedback", "我能提供另一个角度吗？"]],
      sentences: [["Strong disagreement needs strong evidence.", "强反对需要强证据。"], ["Let's separate facts from guesses.", "把事实和猜测分开。"], ["Disagree with ideas, not people.", "对事不对人。"]] },
    reading: [["The pricing debate got heated twice.", "定价辩论两次升温。"], ["A junior cited last quarter's survey.", "一位新人引用了上季度调研。"], ["Numbers cooled the room down.", "数据让会议室冷静下来。"]],
    writing: { zh: "写一句有理由的反对意见。", hintEn: "I see it differently because ___." } },
  { day: 117, titleEn: "Standing Firm & Compromising", titleZh: "第 117 天 · 坚持与妥协", goalZh: "知道何时坚持、何时让步。",
    vocabIds: ["w:insist", "w:reject", "w:accept", "w:quarrel", "w:resolve"], grammarTopicId: "basic-clauses", phonicsRuleIds: ["ai", "or"],
    pattern: { titleZh: "句型：I stand by ___, but I can flex on ___.", explainZh: "坚持底线 stand by；可让步处 flex on——各让一步推进合作。",
      examples: [["I stand by the budget, but I can flex on timing.", "预算不让，时间可谈。"], ["Meet me halfway on features.", "功能上我们各退一步。"], ["That's a dealbreaker for us.", "这对我们是底线。"]],
      sentences: [["w:feedback", "哪条不可谈？"], ["Small concessions build trust.", "小让步建立信任。"], ["Shake hands and move forward.", "握手言和向前看。"]] },
    reading: [["Vendor talks stalled over seats.", "供应商谈判卡在席位数。"], ["One side offered training for free.", "一方免费提供培训。"], ["Signed by Thursday, both smiling.", "周四签约，双方都满意。"]],
    writing: { zh: "写一句立场+让步的组合表达。", hintEn: "I stand by ___, but I can flex on ___." } },
];
