import type { CourseDayPlan } from "@/content/pipeline/generate-days";

/**
 * Phase 23 · Day 241-270 — Block C 批判性思维与辩论（Critical Thinking & Debate）。
 * B2→C2 思辨产出：识别认知偏差、区分相关与因果、论证形式、谬误狩猎、
 * 伦理框架、证据与可重复性、结构化辩论动作。全部引用真实 C1/C2 词汇。
 */
export const PLAN_241_270: readonly CourseDayPlan[] = [
  {
    day: 241,
    titleEn: "Spotting Your Own Biases",
    titleZh: "第 241 天 · 自查偏见",
    goalZh: "识别自己最常犯的三种认知偏差并给它们命名。",
    vocabIds: [
      "w:confirmation-bias",
      "w:availability-heuristic",
      "w:cognitive-bias",
      "w:metacognition",
      "w:anchoring-availability-heuristic",
    ],
    grammarTopicId: "present-simple",
    phonicsRuleIds: ["ee", "st", "oi"],
    pattern: {
      titleZh: "句型：I tend to notice evidence that ___. / My bias here is ___.",
      explainZh: "自查句式：坦白收集面 I tend to notice evidence that…；给偏差命名 My bias here is…;记下触发点 it shows up when…。给偏见命名是驯服它的第一步。",
      examples: [
        ["I tend to notice evidence that supports my routine.", "我总注意到支持我习惯的证据。"],
        ["My bias here is confirmation bias.", "我这里的偏见是确认偏误。"],
        ["Name the bias, and it shrinks.", "说出偏差的名字，它就变小。"],
      ],
      sentences: [
        ["Named biases lose their invisibility.", "被命名的偏差失去隐身术。"],
        ["Check-in before you check-argue.", "先自查，再开怼。"],
        ["A bias log is a cheap mirror.", "一本偏见日志就是一面廉价镜子。"],
      ],
    },
    reading: [
      ["Learners logged one bias a week for a month.", "学员每周记一条偏差，记了一个月。"],
      ["Realizing bias beat debating it.", "意识到偏差胜过辩论它。"],
      ["Metacognition gave them a second self to consult.", "元认知给了他们一个可咨询的第二个自己。"],
    ],
    writing: { zh: "写下你最近一次被哪种偏差左右的时刻。", hintEn: "I tend to notice evidence that ___. My bias is ___." },
  },
  {
    day: 242,
    titleEn: "Availability & Anchors",
    titleZh: "第 242 天 · 可得性与锚定",
    goalZh: "识破鲜活案例与初始数字对判断的操纵。",
    vocabIds: [
      "w:availability-heuristic",
      "w:anchoring-availability-heuristic",
      "w:affect-heuristic",
      "w:cognitive-bias-systematic-error",
      "w:heuristics-and-biases",
    ],
    grammarTopicId: "past-simple",
    phonicsRuleIds: ["th-vl", "ee", "er"],
    pattern: {
      titleZh: "句型：The vivid example made me think ___. / That first number anchored the estimate.",
      explainZh: "两把锁：可得性 vivid example 让人高估重现率；锚定 the first number stuck。数字谈判第一口价就是锚，先说明再比较。",
      examples: [
        ["The vivid plane-crash story made me overestimate risk.", "坠机的鲜活故事让我高估了风险概率。"],
        ["That first number anchored every bid that followed.", "第一个数字给后续每个出价当了锚。"],
        ["News feeds sell availability, not probability.", "信息流卖的是可得性，不是概率。"],
      ],
      sentences: [
        ["Dramatic cases shout; quiet data whispers.", "戏剧性案例在大喊，安静的数据在低语。"],
        ["Anchors work even when you know they work.", "锚定在你明知其存在时依然起效。"],
        ["Compare against a second independent reference point.", "拿第二个独立参照点来对照。"],
      ],
    },
    reading: [
      ["A single vivid example swung a hundred estimates.", "一个鲜活例子带偏了一百个估计。"],
      ["Buyers who named the anchor paid closer to market.", "点破锚点的买家出价更贴近市场。"],
      ["News rotation made rare events feel weekly.", "新闻轮播让罕见事件显得每周发生。"],
    ],
    writing: { zh: "回忆一个被鲜活案例或第一数字带偏的判断。", hintEn: "The ___ example made me think ___. The anchor was ___." },
  },
  {
    day: 243,
    titleEn: "Confidence Calibration",
    titleZh: "第 243 天 · 自信校准",
    goalZh: "对照真实命中率校准自己的过度自信。",
    vocabIds: [
      "w:overconfidence-bias",
      "w:optimism-bias",
      "w:present-bias",
      "w:metacognition-awareness",
      "w:heuristics",
    ],
    grammarTopicId: "future-simple",
    phonicsRuleIds: ["fl", "ee", "st"],
    pattern: {
      titleZh: "句型：I was sure it would ___, yet ___. / Let me bet on it.",
      explainZh: "校准两招：回顾 I was sure it would…, yet…;下注 Let me bet on it 用真金换命中率。自信要配记分牌。",
      examples: [
        ["I was sure the train would be late, yet it left early.", "我本来笃定火车会晚点，结果它早发了。"],
        ["Let me bet on it and see how often I win.", "让我下注一试，看看我赢几次。"],
        ["Calibration beats confidence as a life skill.", "校准比自信更是人生技能。"],
      ],
      sentences: [
        ["Confidence is a feeling; calibration is a score.", "自信是感觉，校准是分数。"],
        ["Optimism bias plans sunny, pays stormy.", "乐观偏差按晴天计划，按暴风雨付账。"],
        ["Score every forecast; the scroll keeps you honest.", "给每个预测打分，记分板让你诚实。"],
      ],
    },
    reading: [
      ["Teen drivers rated themselves skilled; the data disagreed.", "少年司机自评车技高超，数据不同意。"],
      ["Teams that bet on estimates hit twice as many deadlines.", "敢对估计下注的团队命中两倍期限。"],
      ["Prediction journals became calibration gyms.", "预测日记变成了校准健身房。"],
    ],
    writing: { zh: "写下你上周的一个预测并诚实记下结果。", hintEn: "I was sure ___ would happen. It did/didn't. Score: ___." },
  },
  {
    day: 244,
    titleEn: "Correlation vs Causation",
    titleZh: "第 244 天 · 相关与因果",
    goalZh: "用因果链检查每个相关关系，拦截第三变量。",
    vocabIds: [
      "w:correlation-causation",
      "w:confounding-variable",
      "w:omitted-variable-bias",
      "w:instrumental-variable",
      "w:correlation",
    ],
    grammarTopicId: "past-simple",
    phonicsRuleIds: ["gr", "ai", "st"],
    pattern: {
      titleZh: "句型：They move together, but ___ may explain both. / What drives both is ___.",
      explainZh: "拦截句式：承认同向 They move together;给第三解释 but the weather may drive both;要我证据 what drives both is…。冰淇淋与溺水同涨，真凶是夏天。",
      examples: [
        ["They move together, but income may explain both.", "它俩同向而动，但收入可能解释两者。"],
        ["What drives both is the summer heat.", "推动两者的都是夏天的热浪。"],
        ["A mechanism is the password to causality.", "机制是通往因果的通行证。"],
      ],
      sentences: [
        ["Correlation introduces; mechanism introduces itself.", "相关只负责介绍，机制才自我介绍。"],
        ["Hidden variables crash the party uninvited.", "隐藏变量会不请自来砸场。"],
        ["Before claiming X caused Y, hunt for Z.", "断言 X 导致 Y 之前，先去找 Z。"],
      ],
    },
    reading: [
      ["The ice-cream study taught a generation the trap.", "冰淇淋研究上了一代人的课。"],
      ["Controlled trials outranked matched observations.", "对照试验胜过配对观察。"],
      ["A missing variable turned a cure into a curse claim.", "一个漏掉的变量把疗效说成了祸害。"],
    ],
    writing: { zh: "举一个真实相关的例子并给出可能的第三变量。", hintEn: "A rises with B, but ___ may drive both." },
  },
  {
    day: 245,
    titleEn: "The Replication Question",
    titleZh: "第 245 天 · 可重复性拷问",
    goalZh: "用可重复性判断一项研究可信度。",
    vocabIds: [
      "w:replication-crisis",
      "w:replication-validity",
      "w:publication-bias",
      "w:peer-replication-crisis",
      "w:bias-audit",
    ],
    grammarTopicId: "questions",
    phonicsRuleIds: ["ee", "oi", "st"],
    pattern: {
      titleZh: "句型：Has this been replicated? / One study suggests ___, but replication is pending.",
      explainZh: "可信度两问：有没有复现 Has this been replicated？样本多大 How many people？头条标题常说 one study，正文要问 replication is pending。",
      examples: [
        ["Has this effect been replicated outside the lab?", "这个效应在实验室之外被复现过吗？"],
        ["One study suggests a benefit, but replication is pending.", "一项研究提示有效，但复现还在路上。"],
        ["Publication bias hides the studies that failed.", "发表偏误藏起了失败的实验。"],
      ],
      sentences: [
        ["Single studies are singles, not championships.", "单项研究是单打，不是总冠军。"],
        ["Replication is the peer review of peer review.", "复现是对同行评议的同行评议。"],
        ["Ask the question before you share the headline.", "转发行头之前先问一句复现问题。"],
      ],
    },
    reading: [
      ["Replication runs changed how teams read abstracts.", "复现行动改变了团队读摘要的方式。"],
      ["Half the classic effects shrank under retesting.", "一半的经典效应在复测下缩水。"],
      ["Preregistered studies became the gold standard.", "预注册研究成了黄金标准。"],
    ],
    writing: { zh: "就你关注的任一说法提出可重复性问题。", hintEn: "Has ___ been replicated? The pending question is ___." },
  },
  {
    day: 246,
    titleEn: "Deductive Validity",
    titleZh: "第 246 天 · 演绎有效性",
    goalZh: "判断演绎论证是否有效，前提是否可信。",
    vocabIds: [
      "w:deduction-logic",
      "w:premise-n2",
      "w:fallacy",
      "w:fallacious",
      "w:soundness-of-argument",
    ],
    grammarTopicId: "basic-clauses",
    phonicsRuleIds: ["st", "ee", "oi"],
    pattern: {
      titleZh: "句型：If P, then Q. / P, therefore Q — but is P true?",
      explainZh: "演绎两问：形式有效 If P, then Q;前提真实 is P true？形式对但前提假，论证就不可靠。",
      examples: [
        ["If it rains, the ground is wet; it rains, so it is wet.", "若下雨则地湿；下了雨，所以地湿。"],
        ["All change is risk, therefore all risk is change — that's invalid.", "所有变化都有风险，所以所有风险都是变化——这推理无效。"],
        ["Sound reasoning needs true premises and valid moves.", "可靠论证需要真前提加有效步骤。"],
      ],
      sentences: [
        ["Validity is about moves, truth about starting points.", "有效性看步法，真理性看起点。"],
        ["A valid form with a false premise is a corpse with manners.", "假前提加有效形式，是有礼貌的尸体。"],
        ["When the conclusion surprises you, audit the premises.", "结论吓到你时，去审计前提。"],
      ],
    },
    reading: [
      ["Learners separated form from truth in twenty syllogisms.", "学员在二十个三段论里区分了形式与真值。"],
      ["Fallacious moves slipped in through emotional wording.", "谬误步法借情绪措辞溜进来。"],
      ["Premise checks caught the slippery generalization.", "前提检查拦住了滑坡概括。"],
    ],
    writing: { zh: "写一个有效但前提可疑的论证并标出问题。", hintEn: "If P then Q; P; so Q. Is P actually true?" },
  },
  {
    day: 247,
    titleEn: "Induction & Inference",
    titleZh: "第 247 天 · 归纳与推断",
    goalZh: "用归纳与溯因推理描述结论的强度与不确定性。",
    vocabIds: [
      "w:induction",
      "w:abduction-inference",
      "w:induction-problem",
      "w:hume-problem-induction",
      "w:assumptions",
    ],
    grammarTopicId: "present-simple",
    phonicsRuleIds: ["ee", "oi", "th-vd"],
    pattern: {
      titleZh: "句型：From these cases, we infer ___. / The best explanation, so far, is ___.",
      explainZh: "推断两型：归纳 from these cases we infer…（从样本到全体）；溯因 the best explanation is…（从现象到解释）。两个都只给强度，不给保障。",
      examples: [
        ["From these cases, we infer the pattern generalizes.", "从这些案例我们推断模式可以推广。"],
        ["The best explanation, so far, is a seasonal effect.", "目前最好的解释是季节性效应。"],
        ["Inductive odds are provisional by nature.", "归纳出的概率本质上是临时的。"],
      ],
      sentences: [
        ["Induction bets on tomorrow repeating the past.", "归纳押注明天重复昨天。"],
        ["Abduction picks the best story, not the true one.", "溯因挑最好的故事，不保证真。"],
        ["Label your inference type and honesty follows.", "标明推断类型，诚实时就跟着来了。"],
      ],
    },
    reading: [
      ["The turkey who liked Thanksgiving was an inductive casualty.", "那只喜欢感恩节的火鸡是归纳的牺牲品。"],
      ["Abduction saved the diagnostic in a day of symptoms.", "溯因救活了一整天的症状诊断。"],
      ["Teams that typed their inferences reduced disputes.", "给推断分类的团队减少了争执。"],
    ],
    writing: { zh: "写下你最近的一个人际推断，并标注归纳或溯因。", hintEn: "From ___, I inferred ___. Type: induction/abduction." },
  },
  {
    day: 248,
    titleEn: "Probability as a Language",
    titleZh: "第 248 天 · 概率语言",
    goalZh: "用概率而非两极词表达不确定，避免非黑即白。",
    vocabIds: [
      "w:probability",
      "w:probability-theory",
      "w:bayesian-diagnostic-reasoning",
      "w:probability-space",
      "w:pre-test-probability",
    ],
    grammarTopicId: "future-simple",
    phonicsRuleIds: ["ee", "sp", "oi"],
    pattern: {
      titleZh: "句型：There is a 70 percent chance that ___. / Rather than certain, it is likely.",
      explainZh: "概率表达：给数字 a 70 percent chance；给换代 rather than certain, it is likely。把一定/绝对换成概率，是语言的革命。",
      examples: [
        ["There is a 70 percent chance the train is late.", "火车晚点的概率是七成。"],
        ["Rather than certain, the claim is merely likely.", "这说法不是确定，只是可能。"],
        ["Bayesian thinking updates beliefs with new evidence.", "贝叶斯思维用新证据更新信念。"],
      ],
      sentences: [
        ["Probability is the grammar of uncertainty.", "概率是不确定性的语法。"],
        ["Certain is a claim; 80 percent is a share.", "一定是个主张，80% 是一份份额。"],
        ["Say the number, then the story feels small.", "说出数字，故事就变小了。"],
      ],
    },
    reading: [
      ["Weather apps beat pundits by speaking in percents.", "天气应用用百分比打败了专家。"],
      ["Doctors who used odds shared decisions better.", "会用概率的医生共享决策更顺畅。"],
      ["Two-word weather reports misled half the users.", "两个词的天播误导了一半用户。"],
    ],
    writing: { zh: "把一个日常判断改写为带百分比的句子。", hintEn: "There is a ___ percent chance that ___." },
  },
  {
    day: 249,
    titleEn: "Counterfactual Scenarios",
    titleZh: "第 249 天 · 反事实推演",
    goalZh: "用 if-not 想象检验结论的稳健性。",
    vocabIds: [
      "w:counterfactual-reasoning-method",
      "w:conjecture-speculation",
      "w:hypothesis-driven",
      "w:proxy-variable",
      "w:random-variable",
    ],
    grammarTopicId: "past-simple",
    phonicsRuleIds: ["th-vd", "ai", "st"],
    pattern: {
      titleZh: "句型：If we had not ___, then ___. / Would the result hold without ___?",
      explainZh: "反事实两问：改条件 If we had not…, then…；去变量 Would it hold without…？结论经不起 if-not 就还没站稳。",
      examples: [
        ["If we had not raised fees, churn would have soared.", "如果我们没涨价，流失会飙升。"],
        ["Would the result hold without the holiday effect?", "去掉节日效应结果还成立吗？"],
        ["Counterfactuals stress-test every confident conclusion.", "反事实给每个自信的结论做压力测试。"],
      ],
      sentences: [
        ["What if-not is the gym of conclusions.", "if-not 是结论的健身房。"],
        ["Remove the variable; watch the claim sweat.", "去掉变量，看主张出汗。"],
        ["Scenarios are cheap policy rehearsals.", "情景是廉价的政策彩排。"],
      ],
    },
    reading: [
      ["The team ran three if-nots before declaring victory.", "团队宣布胜利前跑了三个 if-not。"],
      ["The crashing hypothesis survived without the outlier.", "去掉离群值后崩溃假说依然成立。"],
      ["Counterfactual drills improved forecast honesty.", "反事实演练改善了预测的诚实度。"],
    ],
    writing: { zh: "对任一结论做一次反事实检验。", hintEn: "If we had not ___, then ___. Would it hold without ___?" },
  },
  {
    day: 250,
    titleEn: "Argument Mapping",
    titleZh: "第 250 天 · 论证地图",
    goalZh: "把长论证画成主张-理由-支持的结构图。",
    vocabIds: [
      "w:argument-structure",
      "w:premise-n2",
      "w:deduction-logic",
      "w:argument-from-example",
      "w:argument-from-authority",
    ],
    grammarTopicId: "basic-clauses",
    phonicsRuleIds: ["oi", "ee", "gr"],
    pattern: {
      titleZh: "句型：The main claim is ___, supported by ___. / Support 1 says ___.",
      explainZh: "画图三行：主主张 the main claim is…;支持理由 supported by…;标注类型 support 1 says…。画成图，漏洞自己浮上来。",
      examples: [
        ["The main claim is cheap transit, supported by ridership data.", "主主张是廉价交通，由客流数据支撑。"],
        ["Support 1 says commute time dropped by 12 percent.", "支持一说道路时间下降百分之十二。"],
        ["Map the argument before you attack it.", "攻击前先画图。"],
      ],
      sentences: [
        ["Every node without a path is a hole.", "没有路径的节点就是漏洞。"],
        ["Authority claims need named experts and dates.", "权威主张需要署名专家和日期。"],
        ["A visible map beats an invisible chain.", "看得见的地图胜过看不见的链条。"],
      ],
    },
    reading: [
      ["The mapped argument lost its mystique instantly.", "被画成图的论证立刻失去神秘感。"],
      ["Missing supports surfaced as floating claims.", "缺失的支持露出水面变成悬空主张。"],
      ["Students argued from maps, not notes.", "学生看着地图争论，不再看笔记。"],
    ],
    writing: { zh: "把任一主张画成三行论证地图。", hintEn: "Claim: ___. Support 1: ___. Support 2: ___." },
  },
  {
    day: 251,
    titleEn: "Fallacy Hunt",
    titleZh: "第 251 天 · 谬误狩猎",
    goalZh: "给常见谬误命名并礼貌地指出它。",
    vocabIds: [
      "w:fallacy",
      "w:fallacious",
      "w:straw-man-fallacy-examples",
      "w:both-sides-fallacy-critique",
      "w:gamblers-fallacy-belief",
    ],
    grammarTopicId: "past-simple",
    phonicsRuleIds: ["ee", "oi", "st"],
    pattern: {
      titleZh: "句型：That sounds like a straw man. / Could you restore the full argument?",
      explainZh: "点破句式：给名字 That sounds like a straw man；请还原 Could you restore the full argument?。指出谬误要有礼貌，谬误名字才像体检报告。",
      examples: [
        ["That sounds like a straw man of my position.", "那听起来像对我立场的稻草人。"],
        ["Could you restore the full argument we started with?", "能把我们最初完整的论证还回来吗？"],
        ["Naming the fallacy is half the refutation.", "给谬误命名完成了反驳的一半。"],
      ],
      sentences: [
        ["Fallacies are noise; a name turns down the volume.", "谬误是噪音，名字把音量调小。"],
        ["The bandwagon subtle, the straw man loud.", "从众很含蓄，稻草人很喧哗。"],
        ["Point at the move, not at the person.", "指动作，不指人。"],
      ],
    },
    reading: [
      ["Comment threads became a fallacy museum.", "评论区成了谬误博物馆。"],
      ["Learners collected ten named fallacies in a week.", "学员一周收集十个有名谬误。"],
      ["The straw man fell when the full quote returned.", "完整引语回归，稻草人倒下。"],
    ],
    writing: { zh: "记录你见到或亲历的一条谬误并命名。", hintEn: "The move was ___. Name: ___." },
  },
  {
    day: 252,
    titleEn: "Slanted Sources",
    titleZh: "第 252 天 · 媒体偏向识读",
    goalZh: "识别报道角度、省略与框架对事实的塑造。",
    vocabIds: [
      "w:media-bias",
      "w:publication-bias",
      "w:implicit-bias-unconscious",
      "w:bias-audit",
      "w:algorithm-bias-training-data-inheritance-problem",
    ],
    grammarTopicId: "articles",
    phonicsRuleIds: ["ee", "oi", "st"],
    pattern: {
      titleZh: "句型：The headline frames it as ___. / What is left out of this story?",
      explainZh: "识读三问：框架 The headline frames it as…;省略 What is left out?;来源谁出钱 Who funds the outlet？偏见常在没写进来的部分。",
      examples: [
        ["The headline frames it as a tax win.", "标题把它框成一次税收胜利。"],
        ["What is left out of this story about fees?", "这篇费用报道里漏掉了什么？"],
        ["Every story has a camera angle and a crop.", "每条新闻都有机位和裁剪。"],
      ],
      sentences: [
        ["What is omitted is often the argument.", "被省略的往往是论点本身。"],
        ["Source follow the money, then the facts.", "先跟钱走，再跟事实。"],
        ["Algorithms inherit the biases of their training.", "算法继承训练数据的偏见。"],
      ],
    },
    reading: [
      ["Two outlets covered the same event with different verbs.", "两家媒体用不同动词报道同一事件。"],
      ["The omitted paragraph was the whole story.", "被省略的一段就是整个故事。"],
      ["Implicit bias shaped which victims made page one.", "内隐偏见决定了谁上头条。"],
    ],
    writing: { zh: "对任一新闻做三问识读。", hintEn: "Frame: ___. Omitted: ___. Funded by: ___." },
  },
  {
    day: 253,
    titleEn: "Moral Reasoning Starter",
    titleZh: "第 253 天 · 道德推理入门",
    goalZh: "区分事实问题与价值问题，展开道德对话。",
    vocabIds: [
      "w:moral-reasoning",
      "w:moral-dilemmas",
      "w:moral-foundations",
      "w:moral-intuition",
      "w:ethics-normative-moral",
    ],
    grammarTopicId: "questions",
    phonicsRuleIds: ["oi", "ee", "st"],
    pattern: {
      titleZh: "句型：Is this a fact question or a value question? / My intuition says ___, but my reasoning asks ___.",
      explainZh: "道德对话两步：分型 Is this fact or value？；对质 My intuition says…, but my reasoning asks…。把直觉和推理分开谈，说服才有戏。",
      examples: [
        ["Is this a fact question or a value question?", "这是事实问题还是价值问题？"],
        ["My intuition says it is unfair, but my reasoning asks why.", "我的直觉说不公平，但推理要问为什么。"],
        ["Moral foundations differ; respect opens the floor.", "道德基础各异，尊重才能开场。"],
      ],
      sentences: [
        ["Facts settle some debates; values settle others.", "事实了结一部分争论，价值了结另一部分。"],
        ["Naming the foundation explains the shouting.", "说出道德基础，喊叫就有了解释。"],
        ["Talk to the person, not to the caricature.", "跟人说话，别跟漫画说话。"],
      ],
    },
    reading: [
      ["Class debates rose in quality once facts left the stage.", "事实退出舞台后课堂争论质量上升。"],
      ["Lay intuition led the trolley car through class.", "朴素的直觉开着电车穿过课堂。"],
      ["Moral foundation language cooled two hot teams.", "道德基础语言让两支火气十足的队伍降温。"],
    ],
    writing: { zh: "把一个分歧标注为事实问题或价值问题。", hintEn: "The dispute is a ___ question. My intuition says ___, my reasoning asks ___." },
  },
  {
    day: 254,
    titleEn: "Ethics Toolbox",
    titleZh: "第 254 天 · 伦理工具箱",
    goalZh: "用三套框架分析道德困境并给出理由。",
    vocabIds: [
      "w:utilitarian-consequentialist",
      "w:deontology",
      "w:virtue-ethics",
      "w:code-of-ethics",
      "w:moral-hazard",
    ],
    grammarTopicId: "present-simple",
    phonicsRuleIds: ["ee", "oi", "st"],
    pattern: {
      titleZh: "句型：Utilitarian logic says ___. / Duty says ___ regardless of outcome.",
      explainZh: "三框架：结果论 utilitarian logic says…（看结果）；义务论 duty says… regardless（看规则）；德性论 a good colleague would…（看品格）。",
      examples: [
        ["Utilitarian logic says the smaller lie buys the greater good.", "结果论说小谎换更大的善。"],
        ["Duty says honest reporting, regardless of outcome.", "义务论说不论结果如何都要如实报道。"],
        ["A virtue lens asks how a wise senior would decide.", "德性视角问智者前辈会怎么决策。"],
      ],
      sentences: [
        ["Frameworks disagree; that is their service.", "框架彼此分歧，这正是它的用处。"],
        ["Code of ethics is the floor, not the ceiling.", "守则是地板不是天花板。"],
        ["Moral hazard rewards the risk you do not feel.", "道德风险奖励你感觉不到的风险。"],
      ],
    },
    reading: [
      ["The ethics case split the room three ways.", "伦理案例把教室切成三派。"],
      ["Duty-based teams refused; outcome-based teams shipped.", "义务派拒绝，结果派交付。"],
      ["Virtue talk brought elders back into the debate.", "德性话语把长辈请回辩论席。"],
    ],
    writing: { zh: "用两套框架分析一个你面对的困境。", hintEn: "Utilitarian: ___. Duty: ___." },
  },
  {
    day: 255,
    titleEn: "Claims Worth Defending",
    titleZh: "第 255 天 · 值得守护的主张",
    goalZh: "筛选值得争辩的主张，放弃不值得的战役。",
    vocabIds: [
      "w:thesis-argumentation",
      "w:soundness-of-argument",
      "w:counterclaim-integration",
      "w:knowledge-claims",
      "w:assert",
    ],
    grammarTopicId: "future-simple",
    phonicsRuleIds: ["ee", "oi", "st"],
    pattern: {
      titleZh: "句型：This claim is worth defending because ___. / The stakes here are ___.",
      explainZh: "筛选两问：为什么值得争 the stakes here are…;能不能赢 it is defensible。值得不是喜欢，是你愿意为它付证据。",
      examples: [
        ["This claim is worth defending because it changes policy.", "这主张值得守护，因为它改变政策。"],
        ["The stakes here are school scheduling, not life.", "这里的赌注是排课，不是性命。"],
        ["Assert the claim, arm it with evidence, walk away untouched.", "主张说出口，证据配上，动过手也不受伤。"],
      ],
      sentences: [
        ["Not every battle deserves your ammunition.", "不是每场仗都值得你的弹药。"],
        ["Worth stems from stakes and defensibility.", "值得源自分量与可辩护性。"],
        ["Strong claims invite challenge; that is the point.", "强主张招来挑战，这正是意义所在。"],
      ],
    },
    reading: [
      ["Learners listed ten opinions and kept two.", "学员列出十个观点只留两个。"],
      ["The defensible claim attracted the best counter-evidence.", "可辩护的主张吸引了最好的反证。"],
      ["Stakes clarified who should speak.", "分量决定了谁该开口。"],
    ],
    writing: { zh: "写下你愿意为其付证据的一个主张。", hintEn: "I'll defend that ___. The stakes are ___." },
  },
  {
    day: 256,
    titleEn: "Debate Engine: Claim-Reason-Evidence",
    titleZh: "第 256 天 · 辩论引擎",
    goalZh: "每一轮发言都带主张-理由-证据的完整结构。",
    vocabIds: [
      "w:premise-n2",
      "w:argument-structure",
      "w:concession-rebuttal-structure",
      "w:point-of-information-raised",
      "w:argument-from-example",
    ],
    grammarTopicId: "questions",
    phonicsRuleIds: ["ee", "oi", "st"],
    pattern: {
      titleZh: "句型：Here is my claim. / The reason is ___. / The evidence is ___.",
      explainZh: "三轮结构：主张 here is my claim；理由 the reason is…（因果链条）；证据 the evidence is…（数字或例子）。缺一个环节当场补。",
      examples: [
        ["Here is my claim: remote equals productive.", "我的主张：远程等于高效。"],
        ["The reason is commute time followed the meeting count.", "理由是通勤时长跟着会议数变动。"],
        ["The evidence is a six-month attendance log.", "证据是六个月的出勤日志。"],
      ],
      sentences: [
        ["Structure makes the loudest of the loud audible.", "结构让最大嗓门变得可听。"],
        ["A claim without a reason is a chant.", "没有理由的主张是口号。"],
        ["Raise a point of information to check facts live.", "现场举插问核实事实。"],
      ],
    },
    reading: [
      ["Judges counted claim-reason-evidence per speech.", "评委统计每场发言的三段完整度。"],
      ["Debaters with structure survived hostile rooms.", "有结构的辩手熬得过刁难场。"],
      ["The evidence log outlasted the tallest speaker.", "证据日志比最大的嗓门活得久。"],
    ],
    writing: { zh: "写一轮标准发言：主张+理由+证据。", hintEn: "Claim… Reason… Evidence…" },
  },
  {
    day: 257,
    titleEn: "Rebuttal Ladder",
    titleZh: "第 257 天 · 反驳之梯",
    goalZh: "从最弱反驳爬到最强反驳，逐级击穿。",
    vocabIds: [
      "w:counterclaim-integration",
      "w:strawman-fallacy-label-misrepresentation",
      "w:soundness-of-argument",
      "w:deduction-logic",
      "w:fallacy",
    ],
    grammarTopicId: "past-simple",
    phonicsRuleIds: ["ee", "oi", "st"],
    pattern: {
      titleZh: "句型：Level one: the example is atypical. / Level three: the logic distorts the evidence.",
      explainZh: "反驳四级：例子不典型 atypical；证据不足 insufficient;逻辑扭曲 distortion；前提有假 premise false。越抽越高，最后攻地基。",
      examples: [
        ["Level one: the example is atypical, not the rule.", "第一级：这是非典型例子，不是规律。"],
        ["Level two: the evidence covers one city only.", "第二级：证据只覆盖一座城市。"],
        ["Level three: the conclusion distorts the correlation.", "第三级：结论扭曲了相关关系。"],
      ],
      sentences: [
        ["Climb the ladder; do not skip for the cheap kick.", "逐级爬梯，别为廉价一脚跳级。"],
        ["Attacking the strongest form of the argument earns respect.", "攻击最强版本的论证才赢得尊重。"],
        ["A fallacious rebuttal undoes your own point.", "谬误式反驳会反噬你自己的论点。"],
      ],
    },
    reading: [
      ["The ladder turned shouting into scoring.", "反驳之梯把喊叫变成得分。"],
      ["Level-three rebuttals forced concessions.", "第三级反驳逼出让步。"],
      ["Cases were won on the fourth rung.", "胜负常定在第四级。"],
    ],
    writing: { zh: "对任一主张写两到三级反驳。", hintEn: "Level 1 (atypical): ___. Level 3 (distortion): ___." },
  },
  {
    day: 258,
    titleEn: "Stand Your Ground",
    titleZh: "第 258 天 · 稳住立场",
    goalZh: "被连环质疑时不慌乱、不跑偏、不情绪化。",
    vocabIds: [
      "w:stance",
      "w:assertion",
      "w:assertiveness-training",
      "w:concede-point",
      "w:rogerian-argument",
    ],
    grammarTopicId: "negation",
    phonicsRuleIds: ["ee", "oi", "st"],
    pattern: {
      titleZh: "句型：That is a fair question; here is what holds. / I concede the limit, not the claim.",
      explainZh: "稳住三式：接招 That is a fair question; what holds is…;划界 I concede the limit, not the claim;重复核心 my core point remains。",
      examples: [
        ["That is a fair question; here is what still holds.", "问得好；这里仍成立的东西如下。"],
        ["I concede the edge case, not the main claim.", "我让掉边缘情况，不让掉主主张。"],
        ["My core point remains: timing beats volume.", "我的核心点不变：时机胜过数量。"],
      ],
      sentences: [
        ["Grace under questioning is a trained behavior.", "质疑下的优雅是可训练的行为。"],
        ["Restate, reframe, and re-anchor your core point.", "重述、重构、重新锚定核心。"],
        ["Empathy first, then the argument sails.", "共情先行，论证才好扬帆。"],
      ],
    },
    reading: [
      ["The candidate stayed calm through six stacked questions.", "那位候选人顶着六个连发问题保持冷静。"],
      ["Concessions bought the space to reassert.", "让步换来了重新主张的空间。"],
      ["Restating the core ended the drift every time.", "重申核心每次都止住跑偏。"],
    ],
    writing: { zh: "写三句稳住立场的回应台词。", hintEn: "Fair question… I concede X… My core remains ___." },
  },
  {
    day: 259,
    titleEn: "Clear Under Load",
    titleZh: "第 259 天 · 认知负荷与清晰",
    goalZh: "在自己疲惫时仍能把复杂想法说简单的技巧。",
    vocabIds: [
      "w:cognitive-load-theory",
      "w:concise-cut-adjectives-payroll-halving",
      "w:coherent",
      "w:cohesion",
      "w:narrow-framing-bias",
    ],
    grammarTopicId: "basic-clauses",
    phonicsRuleIds: ["ee", "oi", "st"],
    pattern: {
      titleZh: "句型：The short version is ___. / One idea at a time: ___.",
      explainZh: "减载两招：一句版 the short version is…；切块 one idea at a time。认知负荷超载时就砍成长句，别砍掉重点。",
      examples: [
        ["The short version is: cheaper fixes come first.", "简短版是：便宜的修法优先。"],
        ["One idea at a time: the map changed, then the route.", "一次一个想法：先改地图，再改路线。"],
        ["Wide frames hide the real constraint.", "宽框架会藏起真正的约束。"],
      ],
      sentences: [
        ["Short sentences are oxygen under deadline.", "短句是截止日期的氧气。"],
        ["Chunk the thought and the room can hold it.", "把想法切块，全场才接得住。"],
        ["Clarity is a kindness when minds are full.", "脑子装满时，清晰是一种体贴。"],
      ],
    },
    reading: [
      ["Tired teams listened better to one-idea sentences.", "疲惫团队更听得进一次一个想法的句子。"],
      ["The 15-word rule rescued the crisis call.", "十五词法则救活危机通话。"],
      ["Narrow frames made the huge problem list their size.", "窄框架让问题列表量出自己的尺寸。"],
    ],
    writing: { zh: "把一个复杂想法压缩成一句 15 词以内的版。", hintEn: "Short version: ___ (≤15 words)." },
  },
  {
    day: 260,
    titleEn: "Bias Audits at Work",
    titleZh: "第 260 天 · 职场偏见审计",
    goalZh: "在决策流程里给偏差布下检查点。",
    vocabIds: [
      "w:bias-audit",
      "w:cognitive-bias",
      "w:confirmation-bias",
      "w:implicit-bias-unconscious",
      "w:moral-hazard-risk",
    ],
    grammarTopicId: "present-simple",
    phonicsRuleIds: ["ee", "oi", "st"],
    pattern: {
      titleZh: "句型：Before we approve, what bias check applies? / Who is missing from this table?",
      explainZh: "流程审计：前置检查 before we approve…;补座位 who is missing from this table？给流程加检查点，别给个人贴标签。",
      examples: [
        ["Before we approve, what bias check applies here?", "批准之前，这里该做什么偏差检查？"],
        ["Who is missing from this table when we decide?", "决策时这张桌上缺了谁？"],
        ["A structured checklist outranks a confident gut.", "结构化清单胜过自信的直觉。"],
      ],
      sentences: [
        ["Bias audits belong in the process, not the person.", "偏差审计该进流程，不该钉在人身上。"],
        ["Same list every time defeats the hot-take reflex.", "每次同一张清单，可击败热评反射。"],
        ["Missing voices are the loudest hidden variable.", "缺席的声音是最响的隐藏变量。"],
      ],
    },
    reading: [
      ["A pre-decision checklist cut hiring surprises.", "决策前清单减少了招聘意外。"],
      ["Rotation seats fixed who chaired the decisive meetings.", "轮席制修好了关键会议的椅子归属。"],
      ["Anonymous scoring beat panel chatter on bias tests.", "匿名打分在偏见测试上胜过小组闲聊。"],
    ],
    writing: { zh: "给你最常做的决策写一条偏差检查点。", hintEn: "Before I approve ___, I check ___." },
  },
  {
    day: 261,
    titleEn: "Probabilistic Forecasts",
    titleZh: "第 261 天 · 概率化预测",
    goalZh: "把预测变成可打分的概率而非宿命断言。",
    vocabIds: [
      "w:default-probability",
      "w:post-test-probability",
      "w:pre-test-probability",
      "w:extrapolate-trends",
      "w:optimism-bias",
    ],
    grammarTopicId: "future-simple",
    phonicsRuleIds: ["ee", "oi", "st"],
    pattern: {
      titleZh: "句型：My forecast is 60 percent / with 30 percent upside. / I will score my own call.",
      explainZh: "预测句式：给概率 my forecast is 60 percent;给区间 with 30 percent upside;认账 I will score my own call。预测不记分，等于没预测。",
      examples: [
        ["My forecast is 60 percent next quarter improves.", "我预测下季度改善的概率六成。"],
        ["With 30 percent upside and 20 percent tail risk.", "有百分之三十的上行空间和百分之二十的尾部风险。"],
        ["I will score my own call in writing next month.", "下个月我会用白纸黑字给自己的预测打分。"],
      ],
      sentences: [
        ["A number on the forecast is a number on the loop.", "预测上的数字就是学习回路上的数字。"],
        ["Confidence without a score is a cosmetic claim.", "没有分数的自信是化妆主张。"],
        ["Update the base rate before you move the forecast.", "先更新基础率再动预测。"],
      ],
    },
    reading: [
      ["Scored forecasts turned pundits into learners.", "打分的预测把评论家变成学员。"],
      ["Teams who logged odds beat teams who logged opinions.", "记录概率的团队击败记录观点的团队。"],
      ["The base rate quietly corrected loud gut calls.", "基础率悄悄纠正了大声的直觉判断。"],
    ],
    writing: { zh: "为一个月度目标写下三成到八成区间的预测。", hintEn: "I forecast __% chance X happens within Y. Upside __%." },
  },
  {
    day: 262,
    titleEn: "Interrogating Numbers",
    titleZh: "第 262 天 · 审问数字",
    goalZh: "问清样本、口径与单位之后再信任何数字。",
    vocabIds: [
      "w:correlation-causation",
      "w:confounding-variable",
      "w:media-bias",
      "w:probability",
      "w:replicate",
    ],
    grammarTopicId: "questions",
    phonicsRuleIds: ["ee", "oi", "st"],
    pattern: {
      titleZh: "句型：Who exactly was measured? / What does this number exclude?",
      explainZh: "审数四问：谁被测量 who was measured?；口径 how is the unit defined?；样本 how many?；可复现 can it be replicated？数字张嘴之前先验明正身。",
      examples: [
        ["Who exactly was measured in this 88 percent?", "这百分之八十八里究竟测量了谁？"],
        ["What does this average exclude?", "这个平均数排除了什么？"],
        ["Ask which denominator before trust the ratio.", "相信比率前先问分母。"],
      ],
      sentences: [
        ["Numbers are sentences; ask them who they describe.", "数字是句子，问它在描述谁。"],
        ["Averages hide the distribution entirely.", "平均数把整个分布藏起来。"],
        ["Replicated numbers survive; one-off headlines do not.", "可复现的数字活下来，一次性头条不能。"],
      ],
    },
    reading: [
      ["The 88 percent shrank to 22 when the sample surfaced.", "样本曝光后百分之八十八缩成百分之二十二。"],
      ["Averages outvoted medians in every misleading chart.", "在每张误导性图表里平均数都赢了中位数。"],
      ["Pupils who asked denominators read charts like detectives.", "会问分母的学生读图像侦探。"],
    ],
    writing: { zh: "抽查一个你刚听到的数字并列出三个问题。", hintEn: "Number: ___. Q1 who… Q2 how many… Q3 replicated?" },
  },
  {
    day: 263,
    titleEn: "Ethics of Data",
    titleZh: "第 263 天 · 数据伦理",
    goalZh: "评估数据使用的同意、用途与后果。",
    vocabIds: [
      "w:data-ethics",
      "w:code-of-ethics",
      "w:ethics-review-board-approval",
      "w:algorithmic-bias",
      "w:moral-responsibility",
    ],
    grammarTopicId: "present-simple",
    phonicsRuleIds: ["ee", "oi", "st"],
    pattern: {
      titleZh: "句型：The data was collected for ___, used for ___. / Whose approval covers this?",
      explainZh: "数据伦理三问：用途匹配 was collected for…, used for…；许可 whose approval covers this？；影响 who carries the consequence？诚实回答了才算合规。",
      examples: [
        ["The data was collected for routing, used for scoring.", "数据为路由而采集，却用于打分。"],
        ["Whose approval covers repurposing this dataset?", "哪份批准允许这套数据改作他用？"],
        ["Designers who ship bias audits sleep cleaner.", "把偏见审计带进发布的设计师睡得更安稳。"],
      ],
      sentences: [
        ["Purpose drift is where trust leaks.", "用途漂移是信任泄漏之处。"],
        ["Consent is a verb, re-issued at every reuse.", "同意是动词，每次复用都要再签。"],
        ["Algorithms inherit the room that made them.", "算法继承造就它的那个房间。"],
      ],
    },
    reading: [
      ["The repurposing clause changed a decade of policy.", "改用途条款改写十年政策。"],
      ["Ethics boards slowed shipping and saved reputations.", "伦理委员会拖慢发布，却救了声誉。"],
      ["Learners rewrote a data policy in plain English.", "学员用大白话重写了一份数据政策。"],
    ],
    writing: { zh: "评估你手机上一个数据使用的例子。", hintEn: "Collected for ___, used for ___. Approval: ___." },
  },
  {
    day: 264,
    titleEn: "Preparing to Debate",
    titleZh: "第 264 天 · 辩论备战",
    goalZh: "赛前写出立场卡、证据包与预判反方名单。",
    vocabIds: [
      "w:thesis-statement",
      "w:point-of-information-raised",
      "w:argument-structure",
      "w:counterclaim-integration",
      "w:argument-from-authority",
    ],
    grammarTopicId: "future-simple",
    phonicsRuleIds: ["ee", "oi", "st"],
    pattern: {
      titleZh: "句型：My position card says ___. / The five objections I expect are ___.",
      explainZh: "备战三卡：立场卡 my position card;证据包 my evidence pack;反方名单 the five objections I expect。每张卡一句话，上场就有弹药。",
      examples: [
        ["My position card says speed over scope this quarter.", "我的立场卡写着本季度速度优先于范围。"],
        ["The five objections I expect include cost and trust.", "我预判的五条反对里有成本和信任。"],
        ["Prepare the rival's best move before the round.", "开赛前先备好对手最强的一手。"],
      ],
      sentences: [
        ["Debates are won in the night before.", "辩论在前一夜赢得。"],
        ["A pre-scouted rebuttal lands before the attack.", "预侦查过的反驳总在攻击前落地。"],
        ["Names and dates stiffen every authority claim.", "署名和日期撑硬每条权威主张。"],
      ],
    },
    reading: [
      ["Prepared teams opened with their rival's strongest case.", "备战充分的队伍先摆对方的强论。"],
      ["Position cards kept speakers inside the lane.", "立场卡让发言人不越线。"],
      ["Scouted objections got answered before being asked.", "被预见的反对在提问前就得到了回答。"],
    ],
    writing: { zh: "为下一场交锋写立场卡与三个预期反对。", hintEn: "Position: ___. Objections: 1… 2… 3…" },
  },
  {
    day: 265,
    titleEn: "Heuristic Watch",
    titleZh: "第 265 天 · 看好启发式",
    goalZh: "在快思考与慢思考之间给自己加一个暂停键。",
    vocabIds: [
      "w:heuristics",
      "w:affect-heuristic",
      "w:availability-heuristic-judge",
      "w:heuristics-biases-decision",
      "w:metacognition-thinking",
    ],
    grammarTopicId: "present-simple",
    phonicsRuleIds: ["ee", "oi", "st"],
    pattern: {
      titleZh: "句型：That was my fast answer; slow mode says ___. / Let me add a pause before deciding.",
      explainZh: "暂停句式：区分快慢 that was my fast answer;这是慢版 slow mode says…;给自我设一个暂停 let me add a pause。快思考省电，慢思考保命。",
      examples: [
        ["That was my fast answer; slow mode takes a second look.", "那是我的快答；慢模式让我再瞟一眼。"],
        ["Let me add a pause before I click approve.", "让我在点批准前加一次停顿。"],
        ["Affect colored the whole estimate before data arrived.", "数据到达前情绪已给整个估计上了色。"],
      ],
      sentences: [
        ["A pause is the cheapest debias tool on the desk.", "停顿是桌上最便宜的防偏工具。"],
        ["Fast thinking serves the routine; slow thinking serves the stakes.", "快思考服侍日常，慢思考服侍赌注。"],
        ["Ask one metacognition question before you commit.", "动手前先问自己一个元认知问题。"],
      ],
    },
    reading: [
      ["Pre-decision pauses reduced impulsive renewals.", "决策前停顿减少了冲动续约。"],
      ["The affect heuristic sold extended warranties twice.", "情感启发式把延保卖出去两次。"],
      ["Slow keyboards beat fast thumbs on judgment tasks.", "慢键盘在判断任务上赢过快拇指。"],
    ],
    writing: { zh: "写一个提醒自己暂停的检查句。", hintEn: "Before I decide ___, I pause and ask ___." },
  },
  {
    day: 266,
    titleEn: "Trust & Replication",
    titleZh: "第 266 天 · 信任与复现",
    goalZh: "建立自己的信息信任清单并持续更新。",
    vocabIds: [
      "w:replication",
      "w:replicate",
      "w:replication-validity",
      "w:peer-replication-crisis",
      "w:bias-audit",
    ],
    grammarTopicId: "present-simple",
    phonicsRuleIds: ["ee", "oi", "st"],
    pattern: {
      titleZh: "句型：I trust this source because ___. / My checklist includes replication and funding.",
      explainZh: "信任清单：作者 who wrote it?；复现 has it been replicated?；钱袋 who funds it?；机制 does it name a mechanism？信任是清单，不是感觉。",
      examples: [
        ["I trust this source because it names its method.", "我信任它因为它交代了方法。"],
        ["My checklist includes replication and funding.", "我的清单包括复现与资金来源。"],
        ["Trust without mechanism is a fragile habit.", "没有机制的信任是脆弱的习惯。"],
      ],
      sentences: [
        ["A trust list you update beats a gut you never question.", "会更新的信任清单胜过从不被质疑的直觉。"],
        ["The strongest sources survive adversarial review.", "最强的来源经得起对抗式审查。"],
        ["Replication is cheaper than repentance.", "复现比后悔便宜。"],
      ],
    },
    reading: [
      ["The funding line explained the framing instantly.", "资金行瞬间解释了框架。"],
      ["One replicated result outlasted a week of viral takes.", "一个被复现的结果比一周的爆款更长寿。"],
      ["Teams audited their sources every quarter.", "团队每季度审计一遍自己的消息源。"],
    ],
    writing: { zh: "为你最信任的一个消息源写四行理由。", hintEn: "I trust it because: method… replication… funding… mechanism…" },
  },
  {
    day: 267,
    titleEn: "Argument Hygiene",
    titleZh: "第 267 天 · 论证卫生",
    goalZh: "给论证做体检：清理谬误、补齐证据、校准措辞。",
    vocabIds: [
      "w:soundness-of-argument",
      "w:fallacy",
      "w:fallacious",
      "w:corroborate-evidence",
      "w:substantiate-claims",
    ],
    grammarTopicId: "past-simple",
    phonicsRuleIds: ["ee", "oi", "st"],
    pattern: {
      titleZh: "句型：Clean this claim: remove the ad hominem x. / The claim now rests on ___.",
      explainZh: "体检三步：扫谬误 remove the ad hominem;验证据 the claim rests on…;调措辞 match verb to evidence。论证卫生是每天的小保养。",
      examples: [
        ["Clean this claim: remove the ad hominem, keep the point.", "清洗这句：去掉人身攻击，留下观点。"],
        ["The claim now rests on two corroborated studies.", "该主张现在立在两项相互证实的研宄上。"],
        ["A big claim with small proof dresses up a myth.", "大主张配小证明是在给神话穿衣。"],
      ],
      sentences: [
        ["Hygiene beats heroics on the argument floor.", "卫生胜过英雄主义于论证现场。"],
        ["Every cleaned claim makes the next round shorter.", "每条清洗过的主张让下一轮更短。"],
        ["Sturdy claims survive a walk in the wind.", "结实的论证经得起走一遭风口。"],
      ],
    },
    reading: [
      ["Argument hygiene clinics cut dispute length in half.", "论证卫生诊所把争执时长砍半。"],
      ["Teams cleaned their claims before cross-exam.", "队伍在交叉质询前清洗主张。"],
      ["Verified claims held the floor without shouting.", "被核实的主张不靠喊也占得住场。"],
    ],
    writing: { zh: "挑你昨天一条主张做一次清洗。", hintEn: "Before: ___. Cleaned: rests on ___; fallacy removed: ___." },
  },
  {
    day: 268,
    titleEn: "Disagreeing Well",
    titleZh: "第 268 天 · 高质量分歧",
    goalZh: "把分歧变成学习机会而非战场。",
    vocabIds: [
      "w:rogerian-argument",
      "w:nuance-argument",
      "w:stance",
      "w:concession-rebuttal-structure",
      "w:assertiveness-training",
    ],
    grammarTopicId: "negation",
    phonicsRuleIds: ["ee", "oi", "st"],
    pattern: {
      titleZh: "句型：Tell me what evidence could change your mind. / I will share what changed mine once.",
      explainZh: "高质量分歧协议：交换证据 what evidence could change your mind?；交代自己 I will share what changed mine;约定共同立场 where we agree。分歧是证据交易所。",
      examples: [
        ["Tell me what evidence could change your mind.", "告诉我什么证据能改变你的想法。"],
        ["I will share the one study that changed mine.", "我分享一下曾改变我的一项研究。"],
        ["Where we agree is further than where we fight.", "我们的一致比我们的争执走得更远。"],
      ],
      sentences: [
        ["Ask the evidence question before the verdict question.", "先问证据问题，再问判决问题。"],
        ["Listening for what moves someone is research.", "听出什么能打动对方就是做研究。"],
        ["A good disagreement leaves both sides better armed.", "好的分歧让双方更全副武装。"],
      ],
    },
    reading: [
      ["The evidence question melted a year of tension.", "证据之问融化了一年的紧绷。"],
      ["Learners tested divergence as an information noise.", "学员把分歧当作信息信号来测试。"],
      ["Teams who shared change-evidence moved faster.", "会交换改变证据的团队走得更快。"],
    ],
    writing: { zh: "写两个能启动高质量分歧的问题。", hintEn: "Q1 what evidence could change… Q2 where do we agree…" },
  },
  {
    day: 269,
    titleEn: "Critical News Reading",
    titleZh: "第 269 天 · 批判读新闻",
    goalZh: "用一套流程快速评估任何突发报道。",
    vocabIds: [
      "w:media-bias",
      "w:clickbait-headline-regret",
      "w:confirmation-bias",
      "w:extrapolate-trends",
      "w:evidence-based-practice",
    ],
    grammarTopicId: "questions",
    phonicsRuleIds: ["ee", "oi", "st"],
    pattern: {
      titleZh: "句型：Check should include the outlet, the source, and the date. / Headlines sell; bodies tell.",
      explainZh: "五分钟流程：机构 the outlet?;信源 the source?;日期 the date?;样本 how many measured? 。头条卖点击，正文才给证据。",
      examples: [
        ["Check the outlet, the source, and the date first.", "先查机构、信源和日期。"],
        ["Headlines sell attention; bodies deliver evidence.", "头条卖注意力，正文交付证据。"],
        ["Confirmation bias clicks the comfortable story twice.", "确认偏误把舒服的故事点两遍。"],
      ],
      sentences: [
        ["The five-minute check costs less than the embarrassment.", "五分钟检查比尴尬便宜。"],
        ["Trend headlines mint noise; studies mint probabilities.", "趋势头条铸造噪音，研究铸造概率。"],
        ["Read the correction page like a health chart.", "把更正页当作健康状况图来读。"],
      ],
    },
    reading: [
      ["Students ran the five-minute check on ten headlines.", "学生对十条头条跑了五分钟检查。"],
      ["Date-checked stories survived the recycle bin.", "查过日期的报道逃过了回收站。"],
      ["Source names outed the weakest claims fastest.", "信源名字最快揭穿最弱的主张。"],
    ],
    writing: { zh: "对一条报道跑一次五分钟检查并写结论。", hintEn: "Outlet… Source… Date… Verdict…" },
  },
  {
    day: 270,
    titleEn: "Block C Review & Assessment",
    titleZh: "第 270 天 · 批判思维总结与测评",
    goalZh: "复盘 241-269 天思辨技能并完成一次自评与规划。",
    vocabIds: [
      "w:metacognition",
      "w:confirmation-bias",
      "w:soundness-of-argument",
      "w:correlation-causation",
      "w:replication-validity",
    ],
    grammarTopicId: "basic-clauses",
    phonicsRuleIds: ["ee", "oi", "st"],
    pattern: {
      titleZh: "句型：My thinking win this block was ___. / The question I now ask before believing is ___.",
      explainZh: "思辨终测：对照 241-269 的电环（偏差自查、相关因果、逻辑形式、谬误命名、伦理框架、概率化预测）逐环自评 1-5 分，写下最实用的一问。",
      examples: [
        ["My thinking win this block was naming biases on sight.", "这一块我最大的进步是能一眼命名偏差。"],
        ["The question I now ask before believing is who benefited?", "我现在相信前必问的问题是：谁受益？"],
        ["I rated my correlation radar 4 out of 5.", "我的相关-因果雷达我给 4 分。"],
      ],
      sentences: [
        ["Review is where thinking skills become habits.", "复盘是思辨技能变成习惯的地方。"],
        ["Carry one question into Block D, not a textbook.", "带一个问题进 D 块，别带课本。"],
        ["The next block applies this engine to work and money.", "下一块要把这套引擎用到职场与金钱。"],
      ],
    },
    reading: [
      ["Block C built bias checks, logic, ethics, and forecasts.", "本块搭建偏差检查、逻辑、伦理与预测。"],
      ["The final task bundled reading a news item and a rebuttal.", "终测捆绑读新闻与写反驳。"],
      ["Learners recorded a two-minute defense of one belief.", "学员录下两分钟为一种信念的辩护。"],
    ],
    writing: { zh: "写一封信：本块最好的习惯、最大差距、要带的那个问题。", hintEn: "This block, I ___ . I'm asking ___ in Block D." },
  },
];