import type { CourseDayPlan } from "@/content/pipeline/generate-days";

/** Phase 10-B · Day 171-180 Final Assessment（阶段一结业测评）. */
export const PLAN_171_180: readonly CourseDayPlan[] = [
  {
    day: 171,
    titleEn: "Listening Final",
    titleZh: "第 171 天 · 听力终测",
    goalZh: "在多口音多场景音频中抓取关键信息。",
    vocabIds: [
      "w:fluency-speed-with-control-balance",
      "w:context-clue-guessing-skill-training",
      "w:pronunciation-drill-minimal-pair-practice",
      "w:accent-regional-melody-of-words",
      "w:nuance-fine-distinction-expert-ear-test",
    ],
    grammarTopicId: "questions",
    phonicsRuleIds: ["th-vl", "th-vd"],
    pattern: {
      titleZh: "句型：Sorry, could you repeat the part about ___? / Did you say ___ or ___?",
      explainZh: "听力终测策略：没听清就定位复听 Could you repeat the part about…；近音词用 A or B 确认。",
      examples: [
        ["Sorry, could you repeat the part about the deadline?", "抱歉，能重复一下关于截止日期的部分吗？"],
        ["Did you say fifteen or fifty?", "您说的是十五还是五十？"],
        ["Let me play that back one more time.", "我再放一遍那段。"],
      ],
      sentences: [
        ["Listen for numbers, dates, and names first.", "先抓数字、日期和人名。"],
        ["Guess from context, then verify.", "先猜后验，双保险。"],
        ["Fast speech hides small words; train for it.", "快语速会吞小词，要专门训练。"],
      ],
    },
    reading: [
      ["The final mixed five real-world audios.", "听力终测混合了五段真实音频。"],
      ["Airport announcements tripped half the class.", "机场广播难倒了半数学员。"],
      ["Everyone passed after the second listen.", "第二遍之后全员过关。"],
    ],
    writing: { zh: "写一句你在听力中最常听混的一对词。", hintEn: "I often confuse ___ with ___." },
  },
  {
    day: 172,
    titleEn: "Speaking Final",
    titleZh: "第 172 天 · 口语终测",
    goalZh: "完成两分钟即兴陈述与追问应答。",
    vocabIds: [
      "w:articulate-thoughts-into-clean-sentences-skill",
      "w:eye-contact-confidence-calibration-by-culture-map",
      "w:gesture-hand-talk-free-upgrade-pack",
      "w:hesitate-two-second-buy-time-move",
      "w:eloquent-speeches-quote-worthy-sentences",
    ],
    grammarTopicId: "basic-clauses",
    phonicsRuleIds: ["er", "l"],
    pattern: {
      titleZh: "句型：Today I'd like to talk about ___. / To sum up, ___.",
      explainZh: "即兴陈述骨架：开场 Today I'd like to talk about…；收尾 To sum up…；中间三点各配一个例子。",
      examples: [
        ["Today I'd like to talk about my first year here.", "今天我想谈谈我在这里的第一年。"],
        ["There are three reasons behind this.", "这背后有三个原因。"],
        ["To sum up, persistence beat talent this year.", "总而言之，今年坚持胜过了天赋。"],
      ],
      sentences: [
        ["Structure buys you seconds under pressure.", "结构能在压力下为你赢得时间。"],
        ["Two-second pauses sound thoughtful.", "停顿两秒反而显得沉稳。"],
        ["Gestures add confidence you can hear.", "手势能带来听得出的自信。"],
      ],
    },
    reading: [
      ["Each speaker drew a random topic card.", "每位讲者抽一张随机话题卡。"],
      ["Ninety seconds to prepare, two to deliver.", "九十秒准备，两分钟输出。"],
      ["The panel scored clarity over speed.", "评委更看重清晰而非语速。"],
    ],
    writing: { zh: "为话题 My proudest moment 写三句提纲。", hintEn: "First… Second… Finally…" },
  },
  {
    day: 173,
    titleEn: "Writing Final",
    titleZh: "第 173 天 · 写作终测",
    goalZh: "限时完成一篇结构完整的邮件或短文。",
    vocabIds: [
      "w:concise-cut-adjectives-payroll-halving",
      "w:revise-edit-without-mercy-pass",
      "w:proofread-typo-assassin-final-gate-duty",
      "w:vivid-description-sensory-detail-craft",
      "w:formal-written-contract-language-style",
    ],
    grammarTopicId: "articles",
    phonicsRuleIds: ["r", "ai"],
    pattern: {
      titleZh: "句型：Purpose → Facts → Request. / I am writing to ___.",
      explainZh: "写作终测公式：第一句目的 I am writing to…；中段事实；末段明确请求或结论。",
      examples: [
        ["I am writing to confirm next week's schedule.", "我写信是为确认下周的安排。"],
        ["Three facts support this request.", "三项事实支撑这个请求。"],
        ["Please reply by Friday with your decision.", "请在周五前回复您的决定。"],
      ],
      sentences: [
        ["One paragraph, one job.", "一段只做一件事。"],
        ["Delete every word that earns no keep.", "删掉每个不挣饭吃的词。"],
        ["Read it aloud before sending.", "发送前大声读一遍。"],
      ],
    },
    reading: [
      ["The prompt asked for a complaint email.", "题目要求写一封投诉邮件。"],
      ["Top scores followed purpose-fact-request.", "高分答案都遵循目的-事实-请求结构。"],
      ["Typos cost more than grammar slips.", "错别字扣分多于语法小错。"],
    ],
    writing: { zh: "二十五分钟内写一封五句的正式邮件并自查一遍。", hintEn: "I am writing to ___; please reply by ___." },
  },
  {
    day: 174,
    titleEn: "Reading Final",
    titleZh: "第 174 天 · 阅读终测",
    goalZh: "限时阅读实用文本并回答细节与推断题。",
    vocabIds: [
      "w:read-between-the-lines-hidden-meaning-idiom",
      "w:context-clue-guessing-skill-training",
      "w:vocabulary-size-reading-correlation",
      "w:literal-exact-word-meaning-mode",
      "w:figurative-meaning-between-the-lines-layer",
    ],
    grammarTopicId: "basic-clauses",
    phonicsRuleIds: ["ee", "oa"],
    pattern: {
      titleZh: "句型：The main idea is ___. / The writer implies that ___.",
      explainZh: "阅读答题双句：主旨 The main idea is…；推断 The writer implies that…（imply = 暗示）。",
      examples: [
        ["The main idea is hidden in paragraph one.", "主旨藏在第一段。"],
        ["The writer implies that costs will rise.", "作者暗示成本将上升。"],
        ["This word here means its opposite in context.", "这个词在上下文里是反义用法。"],
      ],
      sentences: [
        ["Skim once, scan twice, answer third.", "先略读，再扫读，最后作答。"],
        ["Questions hint where answers live.", "问题会暗示答案的位置。"],
        ["Don't import outside knowledge into tests.", "别把外部知识带进考题。"],
      ],
    },
    reading: [
      ["Passages came from leases and notices.", "文章选自租约和通知。"],
      ["Numbers in questions matched numbers in text.", "题干数字对应文中数字。"],
      ["Slow readers finished by trusting structure.", "慢读者靠结构照样做完。"],
    ],
    writing: { zh: "用一句话概括你今天读到的短文主旨。", hintEn: "The main idea is ___." },
  },
  {
    day: 175,
    titleEn: "Daily Life Simulation Final",
    titleZh: "第 175 天 · 生活模拟终测",
    goalZh: "连续完成四个真实生活任务情景。",
    vocabIds: [
      "w:appointment-calendar-slot-defended-fiercely",
      "w:insurance-claim-medical-bill",
      "w:security-deposit-refund",
      "w:citizenship-naturalization-test",
      "w:errand-lunch-break-task-chaining",
    ],
    grammarTopicId: "future-simple",
    phonicsRuleIds: ["st", "or"],
    pattern: {
      titleZh: "句型：Could I schedule ___? / I'm here about ___. / What's the next step?",
      explainZh: "生活任务链：预约 Could I schedule…；说明来意 I'm here about…；推进流程 What's the next step?",
      examples: [
        ["Could I schedule a checkup for Thursday morning?", "能约周四上午的体检吗？"],
        ["I'm here about my billing dispute.", "我来是为了我的账单争议。"],
        ["What's the next step after this form?", "交了这张表之后下一步是什么？"],
      ],
      sentences: [
        ["Four desks, forty minutes, zero panic.", "四个柜台、四十分钟、零慌张。"],
        ["Keep every receipt; they chain tasks together.", "留好每张收据，它们能把任务串起来。"],
        ["Ask for the next step before leaving any desk.", "离开任何柜台前都问清下一步。"],
      ],
    },
    reading: [
      ["Stations included clinic, bank, DMV, and post office.", "站点包括诊所、银行、车管所和邮局。"],
      ["Role players added realistic complications.", "扮演者设置了现实的障碍。"],
      ["Scores rewarded calm transitions.", "评分奖励从容的任务切换。"],
    ],
    writing: { zh: "写下四个生活任务站里你最紧张的一个及应对句。", hintEn: "At the ___ desk, I said: ___." },
  },
  {
    day: 176,
    titleEn: "Workplace Simulation Final",
    titleZh: "第 176 天 · 职场模拟终测",
    goalZh: "主持一场含分歧与决策的项目会议。",
    vocabIds: [
      "w:board-of-directors-meeting-minutes",
      "w:objective-measurable-target-set",
      "w:deadline-extension-request-email",
      "w:prioritization-urgent-vs-important-sort",
      "w:negotiation-win-win-outcome-craft",
    ],
    grammarTopicId: "past-simple",
    phonicsRuleIds: ["pl", "dr"],
    pattern: {
      titleZh: "句型：Let's align on ___. / Can we commit to ___ by ___?",
      explainZh: "会议主持三件套：对齐 Let's align on…；承诺 Can we commit to… by…；收尾总结行动项。",
      examples: [
        ["Let's align on the launch date first.", "我们先对齐上线日期。"],
        ["Can we commit to the demo by Friday?", "我们能承诺周五前出演示吗？"],
        ["To close: three actions, three owners.", "收尾：三项行动，三个负责人。"],
      ],
      sentences: [
        ["Disagreement on data beats agreement on vibes.", "数据上的分歧胜过氛围上的一致。"],
        ["Every decision needs an owner and a date.", "每个决定都要有负责人和日期。"],
        ["Minutes turn meetings into progress.", "会议纪要把开会变成进展。"],
      ],
    },
    reading: [
      ["The simulated client pushed for scope creep.", "模拟客户试图不断扩大需求。"],
      ["Priya anchored on the original roadmap.", "普里雅锚定原始路线图。"],
      ["They logged a win-win change order.", "最终记录了一笔双赢的变更单。"],
    ],
    writing: { zh: "为一场会议写三条包含负责人和日期的行动项。", hintEn: "___ will ___ by ___." },
  },
  {
    day: 177,
    titleEn: "Free Conversation Final",
    titleZh: "第 177 天 · 自由对话终测",
    goalZh: "就陌生话题进行十分钟自然对话。",
    vocabIds: [
      "w:small-talk-weather-elevator-scripts-unlock-doors",
      "w:body-language-crossed-arms-myth-decoded",
      "w:curiosity-question-everything-license-plate",
      "w:interrupt-politely-bridge-phrases-toolkit",
      "w:authentic-no-filter-required-presence",
    ],
    grammarTopicId: "present-progressive",
    phonicsRuleIds: ["w", "y-cons"],
    pattern: {
      titleZh: "句型：That reminds me of ___. / What's your take on ___?",
      explainZh: "自由对话引擎：话题跳转 That reminds me of…；邀请观点 What's your take on…？让对话自己呼吸。",
      examples: [
        ["That reminds me of my first winter here.", "这让我想起在这里的第一个冬天。"],
        ["What's your take on working four days?", "你怎么看一周工作四天？"],
        ["Say more about that — I'm curious.", "再多说说，我很好奇。"],
      ],
      sentences: [
        ["Follow-up questions are conversation oxygen.", "追问是对话的氧气。"],
        ["Silence for two seconds is thinking, not failing.", "沉默两秒是在思考不是失败。"],
        ["Topics wander; connection is the destination.", "话题会漂移，连接才是终点。"],
      ],
    },
    reading: [
      ["Pairs talked ten minutes without scripts.", "两人组无稿对话十分钟。"],
      ["Random cards forced new topics mid-flow.", "随机卡片迫使中途换话题。"],
      ["Listeners scored engagement, not vocabulary size.", "听众打分看投入度不看词量。"],
    ],
    writing: { zh: "记下对话里你最想改进的一个瞬间。", hintEn: "Next time someone says ___, I will ___." },
  },
  {
    day: 178,
    titleEn: "Error Bank Review",
    titleZh: "第 178 天 · 错误库复盘",
    goalZh: "系统回顾个人高频错误并制定修复计划。",
    vocabIds: [
      "w:practice-makes-perfect-drill-encouragement-phrase",
      "w:grammar-rules-made-to-bend-later",
      "w:meticulous-tiny-details-organized-love-language",
      "w:careless-autocorrect-blamed-unfairly-adjective",
      "w:back-to-the-drawing-board-redesign-time",
    ],
    grammarTopicId: "negation",
    phonicsRuleIds: ["er", "sh"],
    pattern: {
      titleZh: "句型：My top error is ___. / From now on, I will ___.",
      explainZh: "错误复盘：命名错误 My top error is…；给出对策 From now on, I will…。错误被命名后就跑不掉了。",
      examples: [
        ["My top error is dropping articles before nouns.", "我最常见的错误是名词前丢冠词。"],
        ["From now on, I will read emails aloud once.", "从今往后，邮件发出前我要读一遍。"],
        ["That mistake again? It goes on the fix list.", "又犯这个错？记进修复清单。"],
      ],
      sentences: [
        ["Errors repeat until they're named.", "错误在被点名前会一直重演。"],
        ["Fix one pattern per week, not ten.", "一周修一个模式，别贪十 个。"],
        ["Your error log is your private textbook.", "你的错误日志就是私人教材。"],
      ],
    },
    reading: [
      ["Everyone exported their six-month error stats.", "每人导出了六个月的错误统计。"],
      ["Articles and prepositions led the charts.", "冠词和介词高居榜首。"],
      ["Small habits erased recurring bugs fastest.", "小习惯最快消灭惯犯错误。"],
    ],
    writing: { zh: "写出你的头号错误与本周对策各一句。", hintEn: "My top error is ___; from now on, I will ___." },
  },
  {
    day: 179,
    titleEn: "Comprehensive Assessment",
    titleZh: "第 179 天 · 综合测评",
    goalZh: "完成听说读写四项综合能力测评。",
    vocabIds: [
      "w:exam-final-week-schedule",
      "w:objective-measurable-target-set",
      "w:benchmark-industry-standard-compare",
      "w:significant-not-just-statistics-word",
      "w:celebrate-small-wins-confetti-budget-friendly",
    ],
    grammarTopicId: "questions",
    phonicsRuleIds: ["ai", "igh"],
    pattern: {
      titleZh: "句型：I can now ___ confidently. / I still need work on ___.",
      explainZh: "测评自评双句：能力声明 I can now… confidently；诚实缺口 I still need work on…。",
      examples: [
        ["I can now handle a doctor's call unaided.", "我现在能独立应对医生的电话了。"],
        ["I still need work on fast group chats.", "多人快速群聊我还需练习。"],
        ["My benchmark: last January versus today.", "我的对照基准：去年一月对比现在。"],
      ],
      sentences: [
        ["Assessment is measurement, not judgment.", "测评是度量，不是审判。"],
        ["Scores guide the next ninety days.", "分数指引下一个九十天。"],
        ["Confidence grows where evidence lives.", "自信长在有证据的地方。"],
      ],
    },
    reading: [
      ["Four sections ran back to back.", "四个科目连续进行。"],
      ["Breaks were earned between modules.", "模块之间的休息是挣来的。"],
      ["Results arrived with skill-level maps.", "成绩附带技能等级图谱。"],
    ],
    writing: { zh: "写一句你最有把握的能力与一句待加强的能力。", hintEn: "I can now ___ confidently; I still need work on ___." },
  },
  {
    day: 180,
    titleEn: "Final Growth Report & Graduation",
    titleZh: "第 180 天 · 增长报告与毕业课",
    goalZh: "生成个人增长报告并规划下一阶段学习。",
    vocabIds: [
      "w:milestone",
      "w:progress-n",
      "w:gratitude-three-things-before-bed-habit",
      "w:passion-sustainable-fire-check-annually",
      "w:light-at-the-end-of-the-tunnel-hope-idiom",
    ],
    grammarTopicId: "present-simple",
    phonicsRuleIds: ["gr", "ow-2"],
    pattern: {
      titleZh: "句型：Six months ago, I couldn't ___; now I can. / Next quarter, I will ___.",
      explainZh: "毕业叙事：对比句 Six months ago… now I can；展望句 Next quarter, I will…。用证据为自己颁奖。",
      examples: [
        ["Six months ago, I couldn't order coffee without rehearsing; now I host meetings.", "六个月前我点咖啡都要打腹稿，现在我主持会议。"],
        ["My streak survived two colds and one move.", "我的打卡挺过了两场感冒和一次搬家。"],
        ["Next quarter, I will coach a newer learner.", "下个季度，我会去带一位新学员。"],
      ],
      sentences: [
        ["Graduation is a milestone, not a finish line.", "毕业是里程碑，不是终点线。"],
        ["Growth compounds quietly, then suddenly.", "成长悄悄复利，然后突然可见。"],
        ["Keep the habit; the language follows.", "留住习惯，语言自然跟随。"],
      ],
    },
    reading: [
      ["Each learner presented a growth story.", "每位学员讲述了自己的成长故事。"],
      ["Charts showed vocabulary tripling since Day 1.", "图表显示词汇量较第一天翻了三倍。"],
      ["Certificates came with next-phase roadmaps.", "证书附带下一阶段路线图。"],
    ],
    writing: { zh: "写两句毕业陈述：最大的变化 + 下季度的一个目标。", hintEn: "Six months ago I couldn't ___; next quarter, I will ___." },
  },
];
