import type { CourseDayPlan } from "@/content/pipeline/generate-days";

/** Day 131-150 真实美国生活 - compact real plans. */
export const PLAN_131_150: readonly CourseDayPlan[] = [
  { day: 131, titleEn: "Opening a Bank Account", titleZh: "第 131 天 · 银行开户", goalZh: "比较账户类型并完成开户。",
    vocabIds: ["w:savings-account-n2", "w:direct-deposit-form", "w:bank-statement", "w:atm", "w:deposit"], grammarTopicId: "questions", phonicsRuleIds: ["a-short", "ng"],
    pattern: { titleZh: "句型：Review and practice.", explainZh: "开户问三件：月费、最低存款、ATM 网络。",
      examples: [["I'd like to open a checking account.", "我想开个支票账户。"], ["w:practice", "有月费吗？"], ["w:review", "能用哪些ATM网络？"]],
      sentences: [["Two forms of ID, please.", "请带两种证件。"], ["The app handles most things.", "大部分业务在应用里办。"], ["Statements go paperless.", "对账单无纸化。"]] },
    reading: [["Ana compared three banks in one table.", "安娜用一张表比三家银行。"], ["Fees mattered more than free toasters.", "手续费比赠品重要。"], ["Her paycheck landed digitally on day one.", "工资首月就电子到账。"]],
    writing: { zh: "写一句你在银行要办的业务。", hintEn: "I'd like to open ___ without a monthly fee." } },
  { day: 132, titleEn: "Using Credit Wisely", titleZh: "第 132 天 · 信用使用", goalZh: "谈论信用分与负责任用卡。",
    vocabIds: ["w:credit-history", "w:rate", "w:minimum-wage", "w:credit-score-three-digit-adulthood-report-card", "w:debt-free-goal"], grammarTopicId: "basic-clauses", phonicsRuleIds: ["ai", "dr"],
    pattern: { titleZh: "句型：Paying on time builds ___. / Keep ___ below thirty percent.", explainZh: "信用三原则：按时还款、控制额度使用率、保留老账户历史。",
      examples: [["Paying on time builds your score.", "按时还款涨信用分。"], ["Keep balances below thirty percent.", "欠款保持在额度三成以下。"], ["Old cards help your history.", "老卡有助于信用历史。"]],
      sentences: [["Rewards are useless with interest.", "有利息的话奖励没意义。"], ["Set up auto-pay for the minimum.", "设自动还款至少还最低额。"], ["Check reports once a year.", "每年查一次征信报告。"]] },
    reading: [["Sam's first card had a $500 limit.", "山姆第一张卡额度500美元。"], ["He charged gas and paid in full.", "他只刷油钱并全额还清。"], ["Two years later: excellent credit.", "两年后信用优秀。"]],
    writing: { zh: "写一句你的用卡习惯。", hintEn: "I pay ___ on time and keep ___ low." } },
  { day: 133, titleEn: "Tax Season Basics", titleZh: "第 133 天 · 报税季节", goalZh: "理解报税基本词汇与时间线。",
    vocabIds: ["w:tax", "w:refund", "w:receipt", "w:deadline", "w:accountant"], grammarTopicId: "past-simple", phonicsRuleIds: ["ai", "st"],
    pattern: { titleZh: "句型：I filed my taxes ___. / My refund was ___.", explainZh: "报税动词 file；退税 refund；截止 April 15。",
      examples: [["I filed my taxes early this year.", "今年我早早报了税。"], ["My refund was eight hundred dollars.", "我的退税是八百美元。"], ["Keep receipts for donations.", "捐赠收据要保留。"]],
      sentences: [["W-2s arrive by end of January.", "一月底会收到W-2表。"], ["Free filing tools exist online.", "网上有免费报税工具。"], ["April fifteenth is the deadline.", "四月十五日截止。"]] },
    reading: [["First tax season felt scary.", "第一个报税季令人害怕。"], ["A checklist tamed the paperwork.", "一张清单驯服了文件堆。"], ["The refund funded new tires.", "退税款换了新轮胎。"]],
    writing: { zh: "写一句你的报税准备情况。", hintEn: "I filed/haven't filed yet because ___." } },
  { day: 134, titleEn: "Apartment Hunting", titleZh: "第 134 天 · 租房看房", goalZh: "看房时提出关键问题。",
    vocabIds: ["w:lease-agreement", "w:utility-bills-online", "w:parking-lot", "w:dryer", "w:neighborhood"], grammarTopicId: "questions", phonicsRuleIds: ["a-short", "oa"],
    pattern: { titleZh: "句型：Review and practice.", explainZh: "看房必问：水电网是否包含、停车、洗衣、周边噪音。",
      examples: [["w:practice", "房租含水费吗？"], ["w:review", "附近停车怎么样？"], ["w:progress-n", "什么时候能入住？"]],
      sentences: [["Test the water pressure.", "试试水压。"], ["Check phone signal in rooms.", "在房间看手机信号。"], ["Visit at night too.", "晚上也来看一次。"]] },
    reading: [["The photos lied about the kitchen.", "照片里的厨房照骗。"], ["Second viewing caught street noise.", "第二次看房发现街道很吵。"], ["She chose the boring, solid one.", "她选了朴素但扎实的那个。"]],
    writing: { zh: "写一句看房时要问的问题。", hintEn: "Practice makes perfect." } },
  { day: 135, titleEn: "Signing the Lease", titleZh: "第 135 天 · 签约与押金", goalZh: "读懂租约条款与押金规则。",
    vocabIds: ["w:lease-agreement", "w:security-deposit-refund", "w:owner", "w:repair", "w:inform"], grammarTopicId: "basic-clauses", phonicsRuleIds: ["ee", "i-short"],
    pattern: { titleZh: "句型：Review and practice.", explainZh: "关键条款：提前通知期 notice period；转租 sublet 是否允许。",
      examples: [["w:feedback", "搬走要提前多久告知？"], ["w:practice", "租约允许室友吗？"], ["w:review", "押金何时退还？"]],
      sentences: [["Photograph everything before moving in.", "入住前拍照留档。"], ["Repairs go through the portal.", "维修通过系统提交。"], ["Late fees start on the fourth.", "四号开始计滞纳金。"]] },
    reading: [["Ben asked for clauses in plain words.", "本要求用大白话解释条款。"], ["The landlord added a pet rider.", "房东加了宠物附加条款。"], ["Both initialed every page.", "双方每页都签了缩写。"]],
    writing: { zh: "写一句签约前要确认的条款。", hintEn: "Practice makes perfect." } },
  { day: 136, titleEn: "Talking to Your Landlord", titleZh: "第 136 天 · 与房东沟通", goalZh: "报告维修问题并跟进处理。",
    vocabIds: ["w:owner", "w:leak", "w:repair", "w:appointment", "w:politely"], grammarTopicId: "present-progressive", phonicsRuleIds: ["ai", "sh"],
    pattern: { titleZh: "句型：Review and practice.", explainZh: "维修请求：问题+紧急度+方便时段；书面留痕。",
      examples: [["The heater stopped working overnight.", "暖气一夜之间坏了。"], ["This needs fixing soon — pipes may burst.", "得尽快修——水管可能冻裂。"], ["Mornings work best for access.", "上午最方便开门。"]],
      sentences: [["Texting counts as written notice.", "短信也算书面通知。"], ["Small issues grow without reports.", "不报修小问题变大。"], ["Say thanks when it's fixed.", "修好了记得道谢。"]] },
    reading: [["A slow drip became a ceiling stain.", "慢漏水滴变成天花板渍。"], ["One email with a video sped things up.", "带视频的一封邮件加快了处理。"], ["Plumber arrived within two days.", "水管工两天内上门。"]],
    writing: { zh: "写一条报修短信。", hintEn: "Practice makes perfect." } },
  { day: 137, titleEn: "Buying a Used Car", titleZh: "第 137 天 · 买二手车", goalZh: "试驾提问与车况检查。",
    vocabIds: ["w:gps", "w:driver-license", "w:mechanic", "w:report", "w:negotiate"], grammarTopicId: "questions", phonicsRuleIds: ["dr", "ai"],
    pattern: { titleZh: "句型：Review and practice.", explainZh: "二手车三问：事故史/保养记录/第三方检测。",
      examples: [["w:practice", "出过事故吗？"], ["w:review", "能看保养记录吗？"], ["w:progress-n", "可以先让师傅检测吗？"]],
      sentences: [["Cold start reveals hidden issues.", "冷启动暴露隐患。"], ["Tires tell how it was driven.", "轮胎会说话。"], ["Walk away if they rush you.", "催你成交就走人。"]] },
    reading: [["Leo test-drove three sedans.", "利奥试驾了三辆轿车。"], ["One smelled like burnt toast.", "有一辆有糊味。"], ["His mechanic found a leak in the winner.", "师傅在心仪那辆发现了漏液。"]],
    writing: { zh: "写一句买二手车时的关键问题。", hintEn: "Practice makes perfect." } },
];
