import type { CourseDayPlan } from "@/content/pipeline/generate-days";

/**
 * Phase 23 · Day 271-300 — Block D 职场与商务英语（Workplace & Business English）。
 * B2→C2 职场产出：干系人、会议、授权、反馈、谈判、销售、定价、
 * 指标、风险、合同、面试、远程、艰难对话与职业叙事。全部引用真实 C1/C2 词汇。
 */
export const PLAN_271_300: readonly CourseDayPlan[] = [
  {
    day: 271,
    titleEn: "Stakeholder Maps",
    titleZh: "第 271 天 · 干系人地图",
    goalZh: "绘制决策人、影响者与执行者，找准汇报线。",
    vocabIds: ["w:stakeholder", "w:stakeholder-map", "w:stakeholder-interview", "w:stakeholder-theory", "w:stakeholder-alignment"],
    grammarTopicId: "present-simple",
    phonicsRuleIds: ["st", "ee", "oi"],
    pattern: {
      titleZh: "句型：The decision-maker is ___. / This stakeholder only cares about ___.",
      explainZh: "画图三路：谁是拍板人 the decision-maker is…;每格怎么写 this stakeholder only cares about…;谁是否决者 the blocker is…。干系人地图先于动工。",
      examples: [
        ["The decision-maker is the finance lead, not the intern.", "拍板的是财务负责人，不是实习生。"],
        ["This stakeholder only cares about cost per seat.", "这位干系人只在乎每座位成本。"],
        ["The blocker sits two layers above the project.", "反对者坐在项目上方两层。"],
      ],
      sentences: [
        ["Map who gains and who loses before you start.", "动工前画清谁受益谁受损。"],
        ["Interviews beat guesses about silent stakeholders.", "访谈胜过对沉默干系人的猜测。"],
        ["Alignment is an active verb, not a slide.", "对齐是动词，不是一张幻灯片。"],
      ],
    },
    reading: [
      ["The map showed the veto power we had missed.", "地图显示出我们漏掉的一票否决权。"],
      ["Two interviews changed the whole launch sequence.", "两场访谈改写了整个发布顺序。"],
      ["Quiet sponsors fund more than loud critics block.", "安静的支持者比大声的反对者更能成事。"],
    ],
    writing: { zh: "为你正在推进的一件事画一张干系人小地图。", hintEn: "Decision-maker: ___. Influence: ___. Blocker: ___." },
  },
  {
    day: 272,
    titleEn: "Managing Up",
    titleZh: "第 272 天 · 向上管理",
    goalZh: "主动给领导制定预期并请求决策。",
    vocabIds: ["w:accountability", "w:agenda-setting-influence", "w:escalate-issue-appropriately", "w:empower-decision-making", "w:prioritization-matrix"],
    grammarTopicId: "past-simple",
    phonicsRuleIds: ["oi", "ee", "st"],
    pattern: {
      titleZh: "句型：Here is what I need from you: ___. / I will report back by ___.",
      explainZh: "向上管理三件套：要什么 what I need from you;进度点 report back by…;兜底句 I will handle the rest。把领导从执行里请出去，请他决定。",
      examples: [
        ["Here is what I need from you: one yes or no.", "我需要你的就一句话：行或不行。"],
        ["I will report back by Friday with data.", "周五我带着数据向你汇报。"],
        ["I will handle the rest if you clear the blocker.", "你清掉障碍，其余我来。"],
      ],
      sentences: [
        ["Manage expectations before they harden.", "在期望硬化前管理它。"],
        ["Upward clarity saves everyone a meeting.", "向上的清晰省掉所有人一场会。"],
        ["Take accountability for the ask and the follow-through.", "对请求和后续一并负责。"],
      ],
    },
    reading: [
      ["The weekly note kept the leader from guessing.", "每周简报让领导不必靠猜。"],
      ["Escalating with options changed the check-in tone.", "带选项升级改变了进度会的气氛。"],
      ["Clear asks tripled the speed of approval.", "清晰请求把批准速度翻了倍。"],
    ],
    writing: { zh: "写下你本周需要领导做的一个决定。", hintEn: "I need a decision on ___. I will report by ___." },
  },
  {
    day: 273,
    titleEn: "Agenda Power",
    titleZh: "第 273 天 · 议程设置权",
    goalZh: "用一页议程掌控会议走向与时间分配。",
    vocabIds: ["w:agenda-building", "w:agenda-setting", "w:agenda-setting-influence", "w:decision-tree", "w:empower-decision-making"],
    grammarTopicId: "present-progressive",
    phonicsRuleIds: ["ee", "oi", "st"],
    pattern: {
      titleZh: "句型：Each item needs one exit: decide, defer, or drop. / Item two is about the budget.",
      explainZh: "议程公式：每项配出口 decide/defer/drop;每项标主题 item two is about…;留出决策位。议程不设出口，会议就变漫谈。",
      examples: [
        ["Each item needs one exit: decide, defer, or drop.", "每项议程都配一个出口：决定、推迟还是砍掉。"],
        ["Item two is about the budget, not the tooling.", "第二项讲预算，不是工具选型。"],
        ["Setting the agenda is setting the outcome.", "设定议程就是设定结果。"],
      ],
      sentences: [
        ["No exit on the agenda means no decision in the room.", "议程没有出口，会议室就没有决定。"],
        ["Name the item owner before the invite goes out.", "邀请发出前排好每项的负责人。"],
        ["Ten minutes well framed beats one hour wandered.", "框好框架的十分钟胜过漫游的一小时。"],
      ],
    },
    reading: [
      ["The one-page agenda cut the meeting by half.", "一页议程把会议砍到一半。"],
      ["Decide-differ-drop exits closed thirty open loops.", "决定-推迟-砍掉的出口关掉了三十个悬空项。"],
      ["Item owners showed up ready once the exits existed.", "有出口后，负责人开始带着答案到场。"],
    ],
    writing: { zh: "为你下一场会写一页议程：三项，各带出口。", hintEn: "Item 1: ___, exit ___. Item 2: ___, exit ___. Item 3: ___, exit ___." },
  },
  {
    day: 274,
    titleEn: "Delegation That Sticks",
    titleZh: "第 274 天 · 授权不甩锅",
    goalZh: "明确授权边界、所需支持与回查点。",
    vocabIds: ["w:delegate-authority-not-tasks", "w:delegate-tasks-wisely", "w:empower-decision-making", "w:accountability", "w:feedback-loop"],
    grammarTopicId: "future-simple",
    phonicsRuleIds: ["oi", "ee", "st"],
    pattern: {
      titleZh: "句型：You own this until ___. / Check in when you hit ___.",
      explainZh: "授权四要素：所有权 you own this until…;回查点 check in when…;升级线 escalate if…;兜底 I have your back。授权给的是决定权，不是锅。",
      examples: [
        ["You own this until the launch recap.", "这件事到发布复盘为止归你。"],
        ["Check in when you hit the spending cap.", "触及预算上限时来同步一次。"],
        ["Escalate if the blocker blocks twice in a row.", "障碍连挡两次就升级。"],
      ],
      sentences: [
        ["Delegation of authority is not abdication.", "授的是权，不是放弃责任。"],
        ["Clear boundaries make brave juniors.", "清晰边界造出勇敢的新人。"],
        ["A feedback loop converts follow-ups into habits.", "反馈回路把跟进变成习惯。"],
      ],
    },
    reading: [
      ["When the intern owned the decision, the pace doubled.", "实习生握有决定权时，节奏翻倍。"],
      ["Two named check-ins replaced weekly surveillance.", "两个点名回查点取代了每周盯梢。"],
      ["Blame fades when authority is explicit.", "权责写明时，甩锅自然消失。"],
    ],
    writing: { zh: "把你准备授权的一件事写满四要素。", hintEn: "Owner: ___. Until: ___. Check in when: ___. Escalate if: ___." },
  },
  {
    day: 275,
    titleEn: "Feedback Loops",
    titleZh: "第 275 天 · 反馈回路",
    goalZh: "把反馈做成双向定期流程而非一次性事件。",
    vocabIds: ["w:360-feedback", "w:peer-feedback-incorporation", "w:feedback-loop", "w:corrective-feedback", "w:positive-feedback"],
    grammarTopicId: "negation",
    phonicsRuleIds: ["ee", "oi", "st"],
    pattern: {
      titleZh: "句型：One thing to keep, one thing to change. / I saw ___, and the impact was ___.",
      explainZh: "反馈句式：保留项 keep…;改变项 change…;具体化 I saw…, and the impact was…。反馈要可复现、可核查，不要滚烫的形容词。",
      examples: [
        ["One thing to keep, one thing to change this sprint.", "这个迭代保留一件、改变一件。"],
        ["I saw the demo run smoothly, and the impact was trust.", "我看到演示顺利跑通，影响是信任。"],
        ["Feedback is data directed at a person's growth.", "反馈是指向个人成长的数据。"],
      ],
      sentences: [
        ["Specific beats sincere in feedback.", "在反馈里，具体比真诚更管用。"],
        ["A loop repeats; an event was.", "回路反复运转，事件一次了结。"],
        ["Say what you saw, not what you guessed.", "说你看见的，别说你猜的。"],
      ],
    },
    reading: [
      ["Quarterly 360 loops outperformed annual surprises.", "季度 360 反馈胜过年度惊吓。"],
      ["Peers modeled the keep-change format and it stuck.", "同事把保留-改变格式用了起来并留住了。"],
      ["Corrective notes landed when tied to a live demo.", "纠正附在真实演示上才落地。"],
    ],
    writing: { zh: "给一位同事写一个 keep-change 反馈。", hintEn: "Keep: ___. Change: ___. Because: ___." },
  },
  {
    day: 276,
    titleEn: "Negotiation Anchors",
    titleZh: "第 276 天 · 谈判锚点",
    goalZh: "识别首价锚点并用保留底价守卫结果。",
    vocabIds: ["w:anchoring", "w:anchoring-offer-tactic", "w:reservation-price-floor", "w:prospect-theory-loss-aversion", "w:jockey-for-position-leverage"],
    grammarTopicId: "questions",
    phonicsRuleIds: ["oi", "ee", "st"],
    pattern: {
      titleZh: "句型：Before we discuss numbers, set the frame. / My floor is ___, and here is why.",
      explainZh: "防锚两招：先设框架 before we discuss numbers, set the frame;亮底线 my floor is…, and here is why。首价是锚不是答案，先问口径再谈价。",
      examples: [
        ["Before we discuss numbers, set the frame: value, not discount.", "谈数前先设框架：谈价值，不谈折扣。"],
        ["My floor is the direct cost, and here is why.", "我的底线是直接成本，理由如下。"],
        ["Their anchor lowers your ceiling unless you name yours.", "对方的锚定压低你的上限，除非你先提名自己。"],
      ],
      sentences: [
        ["An anchor only works inside your silence.", "锚只在你沉默时起作用。"],
        ["Loss aversion makes the first offer feel like theft.", "损失厌恶让首价显得像抢劫。"],
        ["Name the frame and the number loses weight.", "说出框架，数字就减重。"],
      ],
    },
    reading: [
      ["Candidates who named a range earned more than anchors allowed.", "说出区间的候选人比任锚定支配的人赚得更多。"],
      ["The floor price turned a soft stand into a firm line.", "底线价把软立场变成硬战线。"],
      ["Framing value first changed every breakthrough call.", "先谈价值的电话每次都能破冰。"],
    ],
    writing: { zh: "写下你下一次谈判的三行：框架、底线、理由。", hintEn: "Frame: ___. Floor: ___. Because: ___." },
  },
  {
    day: 277,
    titleEn: "Win-Win Bargaining",
    titleZh: "第 277 天 · 整合式谈判",
    goalZh: "把零和谈判改成可用交换点取胜的整合谈判。",
    vocabIds: ["w:win-win-integrative-bargaining", "w:logrolling-trade-offs-swap", "w:concession-rebuttal-structure", "w:leverage-v", "w:negotiation-win-win-outcome-craft"],
    grammarTopicId: "articles",
    phonicsRuleIds: ["ee", "oi", "st"],
    pattern: {
      titleZh: "句型：What matters more to you: X or Y? / I can trade Z for a longer window.",
      explainZh: "整合三招：问权重 what matters more…;造交换 I can trade Z for…;寻找一致点 we both need…。利益排序不同才谈得成，价值要互换不要对撞。",
      examples: [
        ["What matters more to you: speed or price?", "你更在乎哪个：速度还是价格？"],
        ["I can trade a shorter warranty for a longer window.", "我可以用更短保修换更长账期。"],
        ["We both need a deadline that survives the summer.", "我们都需要一个扛得住夏天的期限。"],
      ],
      sentences: [
        ["Scores differ, and that is the deal's engine.", "双方排序不同，正是交易的引擎。"],
        ["Trade the cheap card for the expensive need.", "用你的便宜牌换对方的硬需求。"],
        ["Expand the pie before you split what exists.", "先做大饼，再分现有的饼。"],
      ],
    },
    reading: [
      ["The warranty-for-time swap closed a stalled deal.", "保修换账期的交换关上了一单僵局。"],
      ["Asking priorities exposed a silent third need.", "询问优先级暴露了潜伏的第三需求。"],
      ["Both-sides scoring turned opposition into design.", "双方打分把对立变成设计。"],
    ],
    writing: { zh: "写一个你可以做的等价交换。", hintEn: "I trade ___ for ___. It costs me ___, it buys them ___." },
  },
  {
    day: 278,
    titleEn: "Concessions & Red Lines",
    titleZh: "第 278 天 · 让步与红线",
    goalZh: "让步要有回报，红线要提前写明。",
    vocabIds: ["w:contract-negotiation-red-lines", "w:good-cop-bad-cop-routine", "w:anchoring-adjustment-effect", "w:risk-aversion", "w:leverage-term"],
    grammarTopicId: "prepositions-basic",
    phonicsRuleIds: ["oi", "ee", "st"],
    pattern: {
      titleZh: "句型：I can give ground on ___, but not on ___. / Every concession returns something.",
      explainZh: "红线句式：给地 I can give ground on…, but not on…;交换法则 every concession returns something。让步要换回来，白给的让步是负债。",
      examples: [
        ["I can give ground on delivery dates, but not on scope.", "交付日期可以让，范围不能让。"],
        ["Every concession returns something in writing.", "每次让步都要换回白纸黑字。"],
        ["Named red lines stop the good-cop-bad-cop theatre.", "写明红线就可戳穿红白脸表演。"],
      ],
      sentences: [
        ["Red lines written early stay standing late.", "提前写下的红线站到最后。"],
        ["A concession without a return is a gift, not a trade.", "没有回报的让步是送礼不是交易。"],
        ["Risk aversion leans on anchors; name yours to resist.", "风险厌恶爱靠锚，说出你的锚才好抵抗。"],
      ],
    },
    reading: [
      ["The seeded anchor moved the midpoint before discussion began.", "埋好的锚在讨论前就移动了中位线。"],
      ["Three written red lines survived four rounds of pressure.", "三行写好的红线顶过了四轮施压。"],
      ["Every give came back as a get in the final draft.", "每个给出去的都回到最终稿里。"],
    ],
    writing: { zh: "写两份清单：可让步的与不可让步的。", hintEn: "I give on ___. I never give on ___." },
  },
  {
    day: 279,
    titleEn: "Pipeline Talk",
    titleZh: "第 279 天 · 销售管道语言",
    goalZh: "把每一条线索用阶段语言讲清楚。",
    vocabIds: ["w:sales-pipeline-stage-review-meeting", "w:lead-generation-pipeline-top-stage", "w:quota-monthly-target-pressure-cooker", "w:customer-segment", "w:upsell-checkout-counter-offer"],
    grammarTopicId: "countable-uncountable",
    phonicsRuleIds: ["ee", "oi", "st"],
    pattern: {
      titleZh: "句型：This lead is at the proposal stage. / The booking risk here is ___.",
      explainZh: "管道语言：阶段 this lead is at…;风险 the booking risk here is…;手数 the deal is weighted at X percent。讲阶段、讲权重，别只讲感觉。",
      examples: [
        ["This lead is at the proposal stage, not closed.", "这条线索在提案阶段，还没成单。"],
        ["The booking risk here is legal review timing.", "这里成单风险是法务复核的时间。"],
        ["Weight the deal, or the pipeline lies to you.", "给交易加权，否则管道会骗你。"],
      ],
      sentences: [
        ["Won deals pay; pipeline tells the story honestly.", "成交的付钱，管道只负责讲真话。"],
        ["A weighted stage is a forecast with a pulse.", "加权阶段就是带脉搏的预测。"],
        ["Upsell talks begin at the table, not after invoicing.", "增销从桌边开始，不是开票之后。"],
      ],
    },
    reading: [
      ["Stage discipline lowered the forecast error rate.", "阶段纪律降低了预测误差率。"],
      ["The heavyweight deal hid a legal time bomb.", "那个大单藏着一颗法务定时炸弹。"],
      ["Segment-level talk replaced general enthusiasm.", "细分客户的语言取代了笼统热情。"],
    ],
    writing: { zh: "给一条真实或模拟线索写阶段描述。", hintEn: "Stage: ___. Risk: ___. Weight: ___%." },
  },
  {
    day: 280,
    titleEn: "Pricing Logic",
    titleZh: "第 280 天 · 定价逻辑",
    goalZh: "用价值定价而非比价定价说明理由。",
    vocabIds: ["w:pricing-strategy", "w:value-based-pricing", "w:hedonic-pricing", "w:gross-margin-per-unit", "w:gross-margin-optimization"],
    grammarTopicId: "pronouns-basic",
    phonicsRuleIds: ["ee", "oi", "st"],
    pattern: {
      titleZh: "句型：We price against the value the buyer keeps. / The margin per unit is ___.",
      explainZh: "定价三原理：锚定价值 we price against the value the buyer keeps;看边际 the margin per unit is…;比心理代价 hedonic price reflects perceived gain。价格是价值的话，不是成本的话。",
      examples: [
        ["We price against the value the buyer keeps, not our cost.", "我们按买家保住的价值定价，不是按成本。"],
        ["The margin per unit is forty percent at list.", "挂牌价下单位毛利四成。"],
        ["A hedonic price names the status the buyer feels.", "享乐定价点破买家感受到的身份。"],
      ],
      sentences: [
        ["Price whispers what you trust about your value.", "价格在低语你对自己价值有多大信心。"],
        ["Margin per unit tells the business its breathing room.", "单位毛利告诉生意它的喘息空间。"],
        ["Cutting price to chase share turns flows into leaks.", "砍价追份额是把现金流转成漏水。"],
      ],
    },
    reading: [
      ["Value-based tiers beat cost-plus on the bottom line.", "按价值的档位在利润线上赢了成本加成。"],
      ["The unit margin review saved a struggling line.", "单位毛利审查救活一条亏损产品线。"],
      ["Perceived gains, not real costs, drove the anchor price.", "感知价值而非真实成本推动了锚价。"],
    ],
    writing: { zh: "为你的服务写一句价值定价主张。", hintEn: "Buyers keep ___; we price at ___. Margin per unit: ___%." },
  },
  {
    day: 281,
    titleEn: "Customer Discovery",
    titleZh: "第 281 天 · 客户探索",
    goalZh: "用访谈验证痛点而非用断言推销方案。",
    vocabIds: ["w:customer-discovery-interviews", "w:customer-acquisition-cost-formula", "w:customer-segment", "w:lead-generation-pipeline-top-stage", "w:recurring-revenue-model"],
    grammarTopicId: "basic-clauses",
    phonicsRuleIds: ["ee", "oi", "st"],
    pattern: {
      titleZh: "句型：What did the last attempt cost you? / That pain repeats at what frequency?",
      explainZh: "探索三问：成本 what did the last attempt cost you?;频率 that pain repeats at what frequency?;得失 who wins and who loses if it is solved。痛点要量化才可信。",
      examples: [
        ["What did the last attempt at fixing this cost you?", "上次修这个花了你多少代价？"],
        ["That pain repeats at what frequency per month?", "这个痛点每月以什么频率重演？"],
        ["Who loses if this problem gets solved cheaply?", "这问题被便宜解决时谁会受损？"],
      ],
      sentences: [
        ["Fact first, pitch second, always.", "事实在前，推销永远在后。"],
        ["Interviews sample the market; guesses sample the room.", "访谈抽样市场，猜测只抽样会议室。"],
        ["Acquisition cost earns its keep when churn is low.", "获客成本在低流失时才算赚到。"],
      ],
    },
    reading: [
      ["Thirty interviews replaced one confident assumption.", "三十场访谈替换掉一个自信假设。"],
      ["The recurring pain surfaced a subscription-shaped fix.", "反复痛点暴露了一个订阅式的解法。"],
      ["Discovery changed the roadmap before a single build.", "探索在写一行代码前就改了路线图。"],
    ],
    writing: { zh: "为你关心的用户写三个探索问题。", hintEn: "Q1 cost: ___. Q2 frequency: ___. Q3 loser: ___." },
  },
  {
    day: 282,
    titleEn: "Rhythm of the Team",
    titleZh: "第 282 天 · 团队节奏",
    goalZh: "用站会、燃尽与短迭代稳住团队节拍。",
    vocabIds: ["w:daily-standup", "w:burn-down-chart", "w:retrospective", "w:sales-and-operations-planning", "w:kpis-performance-metrics"],
    grammarTopicId: "be-verb",
    phonicsRuleIds: ["ee", "oi", "st"],
    pattern: {
      titleZh: "句型：Yesterday I finished ___, today I am on ___, blocked by ___.",
      explainZh: "站会三句：完成 yesterday I finished…;进行今天 today I am on…;障碍 blocked by…。三句站会造节奏，燃尽图让节奏可见。",
      examples: [
        ["Yesterday I finished the payment flow, today I am on the invoice.", "昨天做完支付流，今天做发票。"],
        ["I am blocked by the legal template for two days now.", "我被法务模板卡了两天。"],
        ["The burn-down shows the curve bending right this sprint.", "燃尽图显示本迭代曲线在正确下弯。"],
      ],
      sentences: [
        ["Rhythm beats goodwill when the work is invisible.", "工作不可见时，节奏胜过人情。"],
        ["A blocked day reported is a blocking day owned.", "报出受阻的一天，是担起阻碍的一天。"],
        ["Short loops make every failure cheap to inspect.", "短循环让每次失败都便宜到可以细看。"],
      ],
    },
    reading: [
      ["Three-sentence standups shortened the morning meeting.", "三句站会缩短了晨会。"],
      ["The burn-down chart made the hidden slip visible.", "燃尽图让隐藏的滑坡显形。"],
      ["Weekly planning loops tightened the sales-ops link.", "周计划循环收紧销售与运营的衔接。"],
    ],
    writing: { zh: "写你今天的站会三句。", hintEn: "Done: ___. Doing: ___. Blocked by: ___." },
  },
  {
    day: 283,
    titleEn: "Retrospectives That Learn",
    titleZh: "第 283 天 · 会学习的复盘",
    goalZh: "从每一轮工作里提出可复用的改进行动。",
    vocabIds: ["w:retrospective", "w:lessons-learned", "w:feedback-loop-fast-course-correction-culture", "w:peer-feedback-incorporation", "w:accountability"],
    grammarTopicId: "past-simple",
    phonicsRuleIds: ["ee", "oi", "st"],
    pattern: {
      titleZh: "句型：Keep: ___. / Change: ___. / The fix lands if someone owns it.",
      explainZh: "复盘三列：保留 keep…;改变 change…;试一个 the trial this sprint is…。复盘没有行动项就是叙事会。",
      examples: [
        ["Keep the demo-first habit; it prevented surprises.", "保留先演示的习惯，它挡住了意外。"],
        ["Change the two-day test window; it hid the bug.", "改变两天的测试窗口，它藏住了 bug。"],
        ["The trial this sprint is a one-page handoff note.", "本迭代的试验是交接一页纸。"],
      ],
      sentences: [
        ["A retrospective without owners is a story hour.", "没有责任人的复盘是故事会。"],
        ["Course corrections beat course apologies.", "中途纠偏胜过事后道歉。"],
        ["Name the lesson and give it a price.", "说出教训并给它标价。"],
      ],
    },
    reading: [
      ["The demo-first rule came straight out of a retrospective.", "先演示的规则直接出自一次复盘。"],
      ["Owned action items doubled the follow-through rate.", "有主人的行动项把落地率翻倍。"],
      ["Lessons written down survived the hiring churn.", "写下的教训挺过了人员流动。"],
    ],
    writing: { zh: "为上一轮你参与的工作写一条保留与一条改变。", hintEn: "Keep: ___. Change: ___. Trial: ___." },
  },
  {
    day: 284,
    titleEn: "Metrics That Matter",
    titleZh: "第 284 天 · 有用的指标",
    goalZh: "区分虚荣指标与因果指标并守住北极星。",
    vocabIds: ["w:kpis-performance-metrics", "w:net-revenue-retention", "w:ebitda-metric", "w:revenue-recognition", "w:gain-margin"],
    grammarTopicId: "present-simple",
    phonicsRuleIds: ["ee", "oi", "st"],
    pattern: {
      titleZh: "句型：This KPI drives that outcome. / Net retention fell because ___.",
      explainZh: "指标两问：因果 this KPI drives that outcome?;反例 net retention fell because…。虚荣指标会报喜，因果指标才告诉你开车没。",
      examples: [
        ["This KPI drives renewal, not just visits.", "这项指标驱动续费，不只是访问量。"],
        ["Net retention fell because onboarding dropped a step.", "净留存下滑因入职引导少了一环。"],
        ["EBITDA tells owners the truth at close.", "EBITDA 在结算时对老板讲真话。"],
      ],
      sentences: [
        ["Vanity metrics glitter; causal metrics steer.", "虚荣指标闪光，因果指标掌舵。"],
        ["Pick one north star and fight for its orbit.", "只选一颗北极星并守住它的轨道。"],
        ["Recognition timing changes the number without changing health.", "确认时点能改数字而不改健康。"],
      ],
    },
    reading: [
      ["The dashboards showed gold coins and hid the leak.", "仪表盘展示金币，却藏起漏水。"],
      ["Chasing engagement tripled a metric and tanked value.", "追互动让一个指标翻三倍而价值崩盘。"],
      ["Net retention became the complaint we learned from.", "净留存成了我们反刍的指标。"],
    ],
    writing: { zh: "为你的一项工作写下因果指标与成交信号。", hintEn: "KPI: ___. It drives ___. Cause of change: ___." },
  },
  {
    day: 285,
    titleEn: "Risk Communication",
    titleZh: "第 285 天 · 风险沟通",
    goalZh: "把风险讲成概率与预案，而不是恐吓或掩盖。",
    vocabIds: ["w:risk-communication", "w:risk-based-approach", "w:risk-aversion", "w:risk-sharing", "w:liability-exposure-risk"],
    grammarTopicId: "future-simple",
    phonicsRuleIds: ["ee", "oi", "st"],
    pattern: {
      titleZh: "句型：The risk is X percent for Y impact. / Our mitigation is ___.",
      explainZh: "风险句式：量化 the risk is X percent for Y impact;预案 our mitigation is…;谁担 risk sharing means ___ carries it。风险没有概率就是新闻标题。",
      examples: [
        ["The risk is twenty percent for a two-week slip.", "风险是百分之二十，后果是两周延宕。"],
        ["Our mitigation is a parallel review path.", "我们的预案是一条并行复核通道。"],
        ["Risk sharing means the vendor carries the testing load.", "共担风险意味着供应商扛检测这头。"],
      ],
      sentences: [
        ["Probability plus plan is communication; the rest is theater.", "概率加对策才是沟通，其余是表演。"],
        ["A risk you cannot name is a liability you carry.", "说不上名字的风险就是你背着的负债。"],
        ["Fear without a number lets the loudest guess win.", "没有数字的恐惧让最大声的猜测获胜。"],
      ],
    },
    reading: [
      ["The one-page risk sheet replaced a week of rumors.", "一页风险表取代了一周的传言。"],
      ["Percent and plan turned the storm into a schedule.", "概率加计划把风暴变成进度表。"],
      ["Named liability exposure sharpened the signing debate.", "点明责任敞口让签署争论变锋利。"],
    ],
    writing: { zh: "为一个你担心的风险写概率与预案。", hintEn: "Risk: ___ @ __% for __ impact. Mitigation: ___." },
  },
  {
    day: 286,
    titleEn: "Decision Design",
    titleZh: "第 286 天 · 决策设计",
    goalZh: "用决策树把复杂选择拆成可算的分支。",
    vocabIds: ["w:decision-theory-framework", "w:decision-tree", "w:bayesian-decision", "w:influence-diagram", "w:prioritization-matrix"],
    grammarTopicId: "questions",
    phonicsRuleIds: ["ee", "oi", "st"],
    pattern: {
      titleZh: "句型：Branch one: if A, then ___. / Which branch is the no-regret move?",
      explainZh: "画树两步：分支 if A, then…;找无憾支 the no-regret move is…。决策树让情绪无处藏身，让后悔可以预算。",
      examples: [
        ["Branch one: if we delay, the license cost doubles.", "分支一：若推迟，许可成本翻倍。"],
        ["Branch two: if we ship, we fix the edge case hot.", "分支二：若发布，我们热修边界情况。"],
        ["The no-regret move is negotiating a rolling start.", "无憾的走法是谈判一个滚动启动。"],
      ],
      sentences: [
        ["A drawn tree reveals the branch you were protecting.", "画出的树会揭穿你在护着哪一支。"],
        ["Priorities live in the matrix; excuses live in the chat.", "优先级活在矩阵里，借口活在群里。"],
        ["Update the branch when the update is cheaper than regret.", "当更新比后悔便宜时就更新分支。"],
      ],
    },
    reading: [
      ["The tree turned a shouting match into a spreadsheet.", "决策树把争吵变成一张表格。"],
      ["Influence diagrams showed who fed the false branch.", "影响图指出谁在喂养错误的分支。"],
      ["The no-regret move they chose survives hindsight.", "他们选的无憾走法经得起后见之明。"],
    ],
    writing: { zh: "把一个选择画成两分支树。", hintEn: "If ___, then ___. If ___, then ___. No-regret: ___." },
  },
  {
    day: 287,
    titleEn: "Priority Under Fire",
    titleZh: "第 287 天 · 火力下排序",
    goalZh: "在被迫做多做少时仍保住最重要的一两件事。",
    vocabIds: ["w:prioritization-matrix", "w:prioritization-urgent-vs-important-sort", "w:empower-decision-making", "w:burn-down-chart", "w:quota-monthly-target-pressure-cooker"],
    grammarTopicId: "negation",
    phonicsRuleIds: ["ee", "oi", "st"],
    pattern: {
      titleZh: "句型：Urgent is not the same as important. / Today I protect ___ above all.",
      explainZh: "排序两句：区分 urgent vs important;宣告 today I protect… above all。紧急总是大嗓门，重要需要你点名。",
      examples: [
        ["Urgent is not the same as important under a deadline.", "火线下，紧急不等于重要。"],
        ["Today I protect the renewal fix above all else.", "今天我最护住续费修复这件事。"],
        ["The matrix moved three loud tasks to next week.", "矩阵把三件大嗓门的事移到了下周。"],
      ],
      sentences: [
        ["Loud things talk; important things whisper.", "紧急的大声喊，重要的悄悄说。"],
        ["Protect one thing, and the quarter keeps a spine.", "守住一件事，季度就还有脊梁。"],
        ["A queue is a promise; sort it on purpose.", "队列是一串承诺，要有意排序。"],
      ],
    },
    reading: [
      ["The protected renewal added more than ten fires charged.", "被护住的续费修复比赶十场火更值钱。"],
      ["Sorting by importance twice a day kept the week sane.", "一天两次按重要性排序让这周没疯。"],
      ["What got deferred exposed the hidden real priority.", "被推迟的东西暴露了隐藏的真心头号。"],
    ],
    writing: { zh: "写下你今天要重点保护的唯一一件事。", hintEn: "Today I protect ___. Deferred: ___. Reason: ___." },
  },
  {
    day: 288,
    titleEn: "Money Health",
    titleZh: "第 288 天 · 现金健康",
    goalZh: "读懂烧钱率、现金流与毛利三根健康线。",
    vocabIds: ["w:burn-rate-cash-consumption", "w:burn-multiple", "w:cash-flow", "w:budget-impact-analysis", "w:recurring-revenue-model"],
    grammarTopicId: "articles",
    phonicsRuleIds: ["ee", "oi", "st"],
    pattern: {
      titleZh: "句型：Cash covers us for ___ months. / Recurring revenue grew by ___.",
      explainZh: "现金三线：跑道 cash covers us for X months;烧钱 burn rate is…;毛利 unit margin…。故事讲盒数，健康看现金。",
      examples: [
        ["Cash covers us for eleven months at this burn.", "照此烧钱速度，现金可撑十一个月。"],
        ["Recurring revenue grew by nine percent last quarter.", "上季度经常性收入增长百分之九。"],
        ["Budget impact analysis preceded the hire, not followed it.", "预算影响分析走在了招聘前面，而不是跟上。"],
      ],
      sentences: [
        ["Burn is a number; runway is a countdown.", "烧钱是数字，跑道是倒计时。"],
        ["Recurring flows smooth the reliable month.", "经常性流入夯平可靠的月份。"],
        ["Cash tells the truth the deck postpones.", "现金说出那页幻灯片推迟的话。"],
      ],
    },
    reading: [
      ["Eleven months of runway changed the whole hiring talk.", "十一个月的跑道改变了整场招聘对话。"],
      ["The burn multiple at the meeting scared the board.", "会上那个烧钱倍数吓到了董事会。"],
      ["Renewals beat new logos in the cash column.", "续费在现金栏里胜过新客户。"],
    ],
    writing: { zh: "为你的业务写一句现金健康说明。", hintEn: "Runway: ___ months. Burn/mo: ___. Recurring growth: ___%." },
  },
  {
    day: 289,
    titleEn: "Equity & Motives",
    titleZh: "第 289 天 · 股权与动机",
    goalZh: "讨论激励结构时把归属期与风险讲明白。",
    vocabIds: ["w:equity-share-options-vesting-schedule", "w:sweat-equity-stake", "w:co-founder-equity-split-talk", "w:brand-equity", "w:equity"],
    grammarTopicId: "prepositions-basic",
    phonicsRuleIds: ["ee", "oi", "st"],
    pattern: {
      titleZh: "句型：Equity aligns long-term work with long-term reward. / The vesting cliff is ___.",
      explainZh: "激励句式：目的 equity aligns work with reward;结构 the vesting cliff is…, the schedule is…;风险 note the dilution risk。谈股权先谈归属期和稀释。",
      examples: [
        ["Equity aligns long-term work with long-term reward.", "股权让长期工作与长期回报对齐。"],
        ["The vesting cliff is one year; the schedule is four.", "归属悬崖一年，分期四年。"],
        ["Sweat equity names the work as the first currency.", "血汗股权把付出设为首要货币。"],
      ],
      sentences: [
        ["Shares talk louder when the cliff is on the table.", "悬崖条款摆上台后，股份说话更响。"],
        ["Motives follow structure; do not guess the motive.", "动机跟着结构走，别去猜动机。"],
        ["Brand equity pays when the deal roughens.", "交易变硬时品牌资产开始付款。"],
      ],
    },
    reading: [
      ["The vesting cliff ended a summer of ambiguity.", "归属悬崖终结了一整个夏天的含糊。"],
      ["Sweat equity fell apart when the vesting was not written.", "归属未写时，血汗股权当场散架。"],
      ["Dilution talk kept the co-founder room candid.", "谈稀释让联合创始人会议保持坦诚。"],
    ],
    writing: { zh: "写下一段你在激励结构中关心的归属安排。", hintEn: "Schedule: ___, cliff: ___. Concern: ___." },
  },
  {
    day: 290,
    titleEn: "Contracts in Plain English",
    titleZh: "第 290 天 · 合同大白话",
    goalZh: "把合同条款翻译成责任与风险的日常语言。",
    vocabIds: ["w:contract-law-agreement", "w:contract-law-enforcement", "w:liability", "w:warrant", "w:e-signature-document-workflow-paperless-milestone"],
    grammarTopicId: "countable-uncountable",
    phonicsRuleIds: ["ee", "oi", "st"],
    pattern: {
      titleZh: "句型：This clause means you owe me ___. / The liability cap is ___.",
      explainZh: "合同三读：义务 this clause means you owe me…;风险 the liability cap is…;后手 if X, then the remedy is…。看不懂的条款就是别人写的规则。",
      examples: [
        ["This clause means you owe me the fixes within ten days.", "这条意味着十天内你给我补好。"],
        ["The liability cap is one year of fees.", "责任上限是一年服务费。"],
        ["If data risk bites, the remedy is a named pool.", "数据风险咬人时，补救是一个指定资金池。"],
      ],
      sentences: [
        ["Plain English turns clauses into choices.", "大白话把条款变成选择。"],
        ["The cap is where the contract finally confesses.", "上限是合同最终坦白之处。"],
        ["A warranty gap is a wage you pay at the end.", "保修空洞是最后结算的工资。"],
      ],
    },
    reading: [
      ["Two clauses hid a year of liability the signer missed.", "两条款藏起签署人漏看的一年责任。"],
      ["The paperless milestone cut the signature cycle in half.", "无纸化里程碑把签署周期减半。"],
      ["Translated into plain English, the contract chose sides.", "译成大白话，合同马上亮明立场。"],
    ],
    writing: { zh: "把一条你看过的条款翻译成大白话。", hintEn: "Clause: ___. In plain words: ___. Risk to me: ___." },
  },
  {
    day: 291,
    titleEn: "Interview English That Hires",
    titleZh: "第 291 天 · 面试英语",
    goalZh: "用行为叙事代替形容词式自我介绍。",
    vocabIds: ["w:interview-transcribe-hours-of-tape", "w:screening", "w:referral", "w:recruitment-talent-pipeline-funnel", "w:peer-feedback-incorporation"],
    grammarTopicId: "pronouns-basic",
    phonicsRuleIds: ["ee", "oi", "st"],
    pattern: {
      titleZh: "句型：In that project, I owned ___, and I changed ___.",
      explainZh: "行为叙事：情景 in that project…;我的角色 I owned…;影响 the result was…。形容自己的形容词会钻进回收站，事件会留下。",
      examples: [
        ["In that project, I owned the launch plan, and I changed the order.", "那个项目我负责发布计划，我改动了顺序。"],
        ["The result was a forty percent faster review cycle.", "结果是复核周期加快四成。"],
        ["Referral culture outperforms cold funnels on quality.", "推荐文化在质量上胜过陌生漏斗。"],
      ],
      sentences: [
        ["Tell the situation; the traited adjective will follow.", "讲情景，特质形容词自然跟上。"],
        ["Numbers put the story on a measuring tape.", "数字把故事放上卷尺。"],
        ["Screening questions predict; interviews probe.", "筛选问预判，面试负责深挖。"],
      ],
    },
    reading: [
      ["Behavior stories outperformed self-praise ten to one.", "行为叙事以十比一胜过自夸。"],
      ["The referral line shortened weeks of sourcing.", "推荐渠道把几周的搜人缩成几天。"],
      ["Hours of transcribed practice made answers sound native.", "数小时的转写练习让答案听上去像母语。"],
    ],
    writing: { zh: "改写一段自我介绍：去掉形容词，加入事件与数字。", hintEn: "In ___, I owned ___. Result: ___." },
  },
  {
    day: 292,
    titleEn: "First Ninety Days",
    titleZh: "第 292 天 · 头九十天",
    goalZh: "把入职期设计成快速建信与学业务的窗口。",
    vocabIds: ["w:onboarding-buddy-system-setup", "w:customer-discovery-interviews", "w:stakeholder-interview", "w:feedback-loop", "w:recruitment-talent-pipeline-funnel"],
    grammarTopicId: "basic-clauses",
    phonicsRuleIds: ["ee", "oi", "st"],
    pattern: {
      titleZh: "句型：Week one: listen. / Week four: ask the second question.",
      explainZh: "九十天节奏：先听 week one: listen;再设计 week four: ask the second question;后交付 week eight: deliver a named win。头仨月先借耳朵再借手。",
      examples: [
        ["Week one: listen, do not decorate the roadmap.", "第一周：倾听，别去装饰路线图。"],
        ["Week four: ask the second question everyone skips.", "第四周：问那个大家都会跳过的第二个问题。"],
        ["Week eight: deliver one named win live.", "第八周：交付一个点名的实打实胜利。"],
      ],
      sentences: [
        ["The buddy system trades the org chart's blind spots.", "伙伴制补上组织图的盲区。"],
        ["Trust is drafted in the first ninety days.", "信任在头九十天里起草。"],
        ["Interviews beat onboarding decks for real context.", "访谈在真实语境上胜过入职幻灯片。"],
      ],
    },
    reading: [
      ["The ninety-day plan gave the newcomer a spine.", "九十天计划给新人一根主心骨。"],
      ["A named week-eight win opened every office door.", "第八周的点名胜利打开了每扇门。"],
      ["Buddies made the org chart speak human.", "伙伴让组织图说人话。"],
    ],
    writing: { zh: "为你的一次入职写四行计划：四个时间点。", hintEn: "W1: ___. W4: ___. W8: ___. W12: ___." },
  },
  {
    day: 293,
    titleEn: "Remote & Async",
    titleZh: "第 293 天 · 远程与异步",
    goalZh: "把书面英语变成跨时区团队的主引擎。",
    vocabIds: ["w:remote-work-term", "w:remote-team-time-zone-empathy-rotation", "w:boundaryless-organization", "w:expat-community-facebook-group-wisdom", "w:work-life-balance"],
    grammarTopicId: "be-verb",
    phonicsRuleIds: ["ee", "oi", "st"],
    pattern: {
      titleZh: "句型：Because we are async, write the decision twice. / The handoff doc is the meeting.",
      explainZh: "异步三律：多写一遍 because we are async, write the decision twice;交接即会议 the handoff doc is the meeting;转时区 timezone empathy: rotate the late slot. 书面就是你的现场。",
      examples: [
        ["Because we are async, write the decision twice.", "因为异步，把决定写两遍。"],
        ["The handoff doc is the meeting we never need.", "交接文档就是那场我们不必要开的会。"],
        ["Timezone empathy means rotating the late slot.", "时区共情意味着轮流扛深夜时段。"],
      ],
      sentences: [
        ["Overcommunicate in writing; underdrift in person.", "书面要过度沟通，人前少跑偏。"],
        ["Boundaryless teams exist on documented decisions.", "无边界团队活在文档化的决定上。"],
        ["Balance is a contract you write with your calendar.", "平衡是你和日历签的合同。"],
      ],
    },
    reading: [
      ["The written decision outlived the video call.", "写下来的决定比视频通话长寿。"],
      ["Rotating late shifts kept three continents fair.", "轮换深夜班让三大洲都公平。"],
      ["Async documentation halved the workday interruptions.", "异步文档把工作日的打扰减半。"],
    ],
    writing: { zh: "写一封异步通知对方下一步的简报。", hintEn: "Decision: ___. Reason: ___. Next step by ___." },
  },
  {
    day: 294,
    titleEn: "Hard Conversations",
    titleZh: "第 294 天 · 艰难对话",
    goalZh: "直说、就事、给下一步并守住尊重。",
    vocabIds: ["w:assertiveness-training", "w:concession-rebuttal-structure", "w:escalate-issue-appropriately", "w:accountability", "w:risk-communication"],
    grammarTopicId: "past-simple",
    phonicsRuleIds: ["ee", "oi", "st"],
    pattern: {
      titleZh: "句型：I need to talk about ___, and I want us to fix it. / What we will do next is ___.",
      explainZh: "艰难对话三步：开机 I need to talk about…, and I want us to fix it;就事 I saw X, it meant Y;下一步 what we will do next is…。直说不等于刻薄。",
      examples: [
        ["I need to talk about the coverage gap, and I want us to fix it.", "我想谈覆盖面缺口，而且想一起修。"],
        ["I saw three missed handoffs; it meant redoing the data.", "我看到三次漏交接，意味着数据返工。"],
        ["What we will do next is a named check twice a week.", "下一步是一周两次点名核对。"],
      ],
      sentences: [
        ["Facts carry the room; tone decides the ceiling.", "事实托住房间，语气决定天花板。"],
        ["Name the behavior, spare the identity.", "点名行为，放过身份。"],
        ["Escalation with options stays a team sport.", "带选项的升级仍是团队运动。"],
      ],
    },
    reading: [
      ["The named gap opened a repair that silence delayed.", "点名缺口开启了被沉默拖延的修补。"],
      ["One hard sentence saved four passive-aggressive months.", "一句硬话省去四个月的被动攻击。"],
      ["Escalated with a plan, the issue met owners, not shrugs.", "带方案升级时，问题遇到的是负责人不是耸肩。"],
    ],
    writing: { zh: "为你需要谈的一件难事写三句开场。", hintEn: "Topic: ___. Facts: ___. Next: ___." },
  },
  {
    day: 295,
    titleEn: "Saying No Professionally",
    titleZh: "第 295 天 · 职场拒绝",
    goalZh: "用一个可替代方案拒绝，让拒绝长成谈判。",
    vocabIds: ["w:assertiveness-training", "w:empower-decision-making", "w:prioritization-matrix", "w:work-life-balance", "w:boundaryless-organization"],
    grammarTopicId: "negation",
    phonicsRuleIds: ["ee", "oi", "st"],
    pattern: {
      titleZh: "句型：I cannot take X, and here is the trade: ___. / No, but yes to ___.",
      explainZh: "拒绝句式：说明我 can't take X;给出替代 here is the trade;弱化伤害 no, but yes to…。每次都先说不，再说能干什么。",
      examples: [
        ["I cannot take the extra project this week, and here is the trade.", "这周我接不了额外项目，交换如下。"],
        ["No, but yes to reviewing the plan twice instead.", "不，但我可以改成两次审计划。"],
        ["A clear no costs an afternoon; a blurry yes costs a month.", "干脆的拒绝花一下午，模糊的答应花一个月。"],
      ],
      sentences: [
        ["No with a trade is a yes in a different costume.", "带交换的拒绝是另一件衣服的答应。"],
        ["Boundaries are the salary of long-term loyalty.", "边界是长期忠诚的薪水。"],
        ["Refusal makes your yes heavier on the scale.", "拒绝让你的同意在秤上更重。"],
      ],
    },
    reading: [
      ["The trade version of no kept the relationship whole.", "交换版拒绝保住了关系完整。"],
      ["One hard boundary saved four weeks of midnight emails.", "一条硬边界拯救了四周的深夜邮件。"],
      ["Saying no to scope said yes to the launch.", "对范围说不就是对发布说是。"],
    ],
    writing: { zh: "写一句带交换的拒绝。", hintEn: "No to ___. Trade: yes to ___ instead." },
  },
  {
    day: 296,
    titleEn: "Fair Weather, Harsh Seasons",
    titleZh: "第 296 天 · 顺境之外",
    goalZh: "在裁员与转向中用词精确且不失体面。",
    vocabIds: ["w:layoff-restructuring-round-survivor", "w:redundancy", "w:resignation-two-weeks-notice-letter", "w:risk-communication", "w:liability-exposure-risk"],
    grammarTopicId: "future-simple",
    phonicsRuleIds: ["ee", "oi", "st"],
    pattern: {
      titleZh: "句型：The restructuring affects these roles, and here is the timeline. / Survivor guilt is not a flaw; it is a signal.",
      explainZh: "难季用语：直面 the restructuring affects these roles;给时间线 here is the timeline;关心人 the support available is…。裁员是数字，也是人。",
      examples: [
        ["The restructuring affects three roles, and here is the timeline.", "重组影响三个岗位，时间线如下。"],
        ["The support available is four months of outplacement.", "可用支持是四个月的再就业服务。"],
        ["Survivor guilt is not a flaw; it is a signal.", "幸存者愧疚不是缺陷，是信号。"],
      ],
      sentences: [
        ["Precision in hard news is a kindness.", "硬新闻上的精准是一种善意。"],
        ["Redundancy talks measure words, not just costs.", "谈论精简要量词句，不只量成本。"],
        ["A two-week notice letter is a bridge, not a bomb.", "两星期辞职信是桥，不是炸弹。"],
      ],
    },
    reading: [
      ["The named timeline quieted a corridor of rumors.", "点名时间线抚平了一条过道的谣言。"],
      ["Outplacement support changed the exit interview's tone.", "再就业支持改变了离职面谈的语气。"],
      ["Honest survivors talked less but understood more.", "诚实的幸存者谈得少却懂得多。"],
    ],
    writing: { zh: "写一句直面难事但保持尊重的公务表述。", hintEn: "The change affects ___. Timeline: ___. Support: ___." },
  },
  {
    day: 297,
    titleEn: "The Promotion Argument",
    titleZh: "第 297 天 · 晋升申请",
    goalZh: "把晋升陈述写成成果证据而非好人卡。",
    vocabIds: ["w:promotion-party-office-cake-politics-simplified", "w:net-revenue-retention", "w:ebitda-metric", "w:accountability", "w:kpis-performance-metrics"],
    grammarTopicId: "present-simple",
    phonicsRuleIds: ["ee", "oi", "st"],
    pattern: {
      titleZh: "句型：Over the year, I moved X to Y. / The skill I grew most is ___.",
      explainZh: "晋升三段：起跑 over the year, I moved X to Y;指标 the metric that moved with me is…;成长 the skill I grew most is…。成果说话，好人卡不出办公室。",
      examples: [
        ["Over the year, I moved onboarding time down by a third.", "这一年我把上手时间缩短三分之一。"],
        ["The metric that moved with me is net retention.", "跟着我走的指标是净留存。"],
        ["The skill I grew most is strategic sequencing.", "我成长最大的是策略性排序。"],
      ],
      sentences: [
        ["The promotion argues with evidence, not with attendance.", "晋升用证据辩论，不用考勤辩论。"],
        ["Accountability is the skeleton of the ask.", "问责感是这次请求的骨架。"],
        ["KPI trends are your reference letters in numbers.", "指标趋势是你的数字推荐信。"],
      ],
    },
    reading: [
      ["The evidence memo outran the office cake chatter.", "证据备忘录跑赢了蛋糕闲聊。"],
      ["Net retention went up; so did the title, in time.", "净留存上升，头衔随后也升了。"],
      ["Asked with numbers, ownership became uncanny.", "带着数字提问时，责任心显得出奇。"],
    ],
    writing: { zh: "为一次晋升写证据三行。", hintEn: "From X to Y: ___. Metric: ___. Skill grown: ___." },
  },
  {
    day: 298,
    titleEn: "Career Trajectory Talk",
    titleZh: "第 298 天 · 职业叙事",
    goalZh: "讲清从哪儿来、为什么在这、要往哪去。",
    vocabIds: ["w:work-life-balance", "w:promotion-party-office-cake-politics-simplified", "w:networking-event-name-forgettery-support-group-vibes", "w:referral", "w:accountability"],
    grammarTopicId: "present-simple",
    phonicsRuleIds: ["ee", "oi", "st"],
    pattern: {
      titleZh: "句型：My path went through ___ to here, and the reason is ___. / Next I want ___.",
      explainZh: "叙事三问：起点 my path went through…;动机 the reason is…;方向 next I want…。职业叙事讲动机，不讲名头列表。",
      examples: [
        ["My path went through support roles to here, and the reason is craft.", "我的路径经支持岗走到这里，原因是手艺。"],
        ["Next I want a year where delivery teaches design.", "下一步我想要一年让交付教授设计。"],
        ["Balance is a calendar choice, not a company policy.", "平衡是日历的选择，不是公司的政策。"],
      ],
      sentences: [
        ["The why in your story outshouts the who.", "故事里的为什么压过是谁。"],
        ["A trajectory is a plot, not a timeline.", "轨迹是情节，不是时间轴。"],
        ["Networking that counts connections counts names, twice.", "数人脉的在数两次名单。"],
      ],
    },
    reading: [
      ["The why made the resume portable across industries.", "那个为什么让简历跨行业通用。"],
      ["A clear next chapter opened doors for the rarest ask.", "清晰的下一章为最稀有的请求开门。"],
      ["Balance conversations started with calendar honesty.", "平衡对话从日历诚实开始。"],
    ],
    writing: { zh: "写三句职业叙事：路径、动机、方向。", hintEn: "I came through ___. Because ___. Next: ___." },
  },
  {
    day: 299,
    titleEn: "Beyond Borders",
    titleZh: "第 299 天 · 全球化团队",
    goalZh: "用文化敏感与清晰结构搭起跨国协作。",
    vocabIds: ["w:remote-team-time-zone-empathy-rotation", "w:expat-community-facebook-group-wisdom", "w:boundaryless-organization", "w:work-life-balance", "w:stakeholder-alignment"],
    grammarTopicId: "questions",
    phonicsRuleIds: ["ee", "oi", "st"],
    pattern: {
      titleZh: "句型：In their context, this request reads as ___. / Let us name the cultural default we are assuming.",
      explainZh: "跨国默契：换视角 in their context, this reads as…;点默认 let us name the default we are assuming;留缓冲 give the buffer the meeting needs。文化默认值要被点名才可被检查。",
      examples: [
        ["In their context, this request reads as a demand.", "在他们的语境里，这个请求读起来像命令。"],
        ["Let us name the cultural default we are assuming here.", "让我们点名这里默认的文化假设。"],
        ["Budget the extra round for tone, not for politeness.", "为语气多留一轮，不是为客套。"],
      ],
      sentences: [
        ["The map of one culture is not a passport to another.", "一种文化的地图不是别处的护照。"],
        ["Named defaults stop silent misunderstandings.", "点名的默认假设拦住无声的误会。"],
        ["Expat ears catch the meeting the transcript missed.", "异乡人的耳朵听出纪要漏掉的那层。"],
      ],
    },
    reading: [
      ["The sampled tone in three time zones changed the memo.", "三个时区的语气采样改写了备忘录。"],
      ["One named default saved a handshake deal.", "一个点名的默认假设救下一笔握手交易。"],
      ["Rotating late slots made three continents feel staffed.", "轮换深夜时段让三大洲都觉得有人在岗。"],
    ],
    writing: { zh: "写一段跨文化协作的高风险线上文案。", hintEn: "In their context, ___. We assume ___. The ask: ___." },
  },
  {
    day: 300,
    titleEn: "Block D Review & Assessment",
    titleZh: "第 300 天 · 职场英语总结与测评",
    goalZh: "复盘 271-299 天职场技能并完成汇报演练与规划。",
    vocabIds: ["w:stakeholder-alignment", "w:lessons-learned", "w:accountability", "w:360-feedback", "w:decision-theory-framework"],
    grammarTopicId: "be-verb",
    phonicsRuleIds: ["ee", "oi", "st"],
    pattern: {
      titleZh: "句型：My workplace win this block was ___. / The next review asks ___.",
      explainZh: "职场终测：对照 271-299 的电环（干系人、会议、授权、反馈、谈判、销售、定价、指标、风险、合同、面试、远程、难话、晋升）逐环自评 1-5 分，写一段三分钟工作汇报。",
      examples: [
        ["My workplace win this block was running a real negotiation.", "这一块我最大的进步是主持了一场真实谈判。"],
        ["I rated my risk communication at four out of five.", "我给风险沟通打四分。"],
        ["The next review asks for one named accountable item.", "下一次复盘只要一个点名的责任项。"],
      ],
      sentences: [
        ["Lessons owned become management; lessons shelved become nostalgia.", "被认领的教训成为管理，被搁置的教训成为怀旧。"],
        ["Alignment is re-earned every quarter, not filed.", "对齐每季度重新挣得，不是归档。"],
        ["Block E applies this engine to media and technology.", "E 块要把这套引擎用于媒体与科技。"],
      ],
    },
    reading: [
      ["Block D built stakeholder maps, negotiations, metrics, and careers.", "本块搭建干系人地图、谈判、指标与职业。"],
      ["The final task bundled a review memo and a two-minute speech.", "终测捆绑复盘备忘录与两分钟发言。"],
      ["Learners recorded a weekly report in their own voice.", "学员用自己声音录下了一周汇报。"],
    ],
    writing: { zh: "写一份三分钟工作汇报草稿：成果、差距、下季承诺。", hintEn: "This quarter, ___. I am working on ___. Next: ___." },
  },
];