import type { CourseDayPlan } from "@/content/pipeline/generate-days";

/** Day 91-120 生活高级表达 - compact real plans compiled by generate-days(). */
export const PLAN_91_120: readonly CourseDayPlan[] = [
  { day: 91, titleEn: "Softening Opinions", titleZh: "第 91 天 · 委婉表达", goalZh: "用 maybe/could/perhaps 委婉表态。",
    vocabIds: ["w:personally", "w:perhaps", "w:viewpoint", "w:attitude", "w:certain"], grammarTopicId: "basic-clauses",
    phonicsRuleIds: ["er", "ai"], pattern: { titleZh: "句型：Review and practice.", explainZh: "委婉=留余地：might/maybe/perhaps 让语气更客气，适合职场与陌生人。",
      examples: [["w:feedback", "也许我们可以换个方法？"], ["It might rain later.", "待会儿可能会下雨。"], ["Perhaps ten is too early.", "十点也许太早了。"]],
      sentences: [["I would say it depends.", "我觉得要看情况。"], ["It seems a bit pricey.", "好像有点贵。"], ["w:feedback", "明天再谈行吗？"]] },
    reading: [["Emails soften requests with could and perhaps.", "邮件用 could 和 perhaps 让请求更柔和。"], ["Direct words can sound rude in writing.", "直白的词在书面上显得生硬。"], ["Politeness buys patience.", "礼貌换来耐心。"]],
    writing: { zh: "把“这方案不行”改写成委婉句。", hintEn: "Maybe we could ___ instead." } },
  { day: 92, titleEn: "Small Complaints", titleZh: "第 92 天 · 得体投诉", goalZh: "礼貌报告问题并要求解决。",
    vocabIds: ["w:issue", "w:fix", "w:apologize", "w:repair", "w:schedule"], grammarTopicId: "questions",
    phonicsRuleIds: ["st", "o-short"], pattern: { titleZh: "句型：Sorry to bother you, but ___", explainZh: "投诉三步：致歉开场→说明事实→提出期望。不吼不闹更有效。",
      examples: [["Sorry to bother you, but the heater is broken.", "抱歉打扰，暖气坏了。"], ["There seems to be a problem with my order.", "我的订单似乎有问题。"], ["w:feedback", "今天能有人来看一下吗？"]],
      sentences: [["I'd appreciate a quick fix.", "希望尽快修好。"], ["w:feedback", "这事该找谁？"], ["Thanks for handling it.", "谢谢处理。"]] },
    reading: [["Maya's faucet dripped all night.", "玛雅家的水龙头滴了一夜。"], ["She emailed the landlord with photos.", "她带照片给房东发了邮件。"], ["A plumber came by noon.", "中午水管工就来了。"]],
    writing: { zh: "写一句礼貌报修的话。", hintEn: "Sorry to bother you, but ___ isn't working." } },
  { day: 93, titleEn: "Making Suggestions", titleZh: "第 93 天 · 提出建议", goalZh: "区分建议强度并恰当使用。",
    vocabIds: ["w:suggest", "w:recommendation", "w:advice", "w:option", "w:insist"], grammarTopicId: "basic-clauses",
    phonicsRuleIds: ["j", "st"], pattern: { titleZh: "句型：Review and practice.", explainZh: "强建议 should；弱建议 could/might；被拒后用 We could always… 留后路。",
      examples: [["w:feedback", "我们分摊费用如何？"], ["We could always order pizza.", "我们大可以点披萨。"], ["You might like the sequel better.", "你也许更喜欢续集。"]],
      sentences: [["w:feedback", "午餐有什么建议？"], ["That's worth considering.", "值得考虑。"], ["Let's sleep on it tonight.", "今晚先想想。"]] },
    reading: [["The team was stuck on a name.", "团队卡在取名上。"], ["Someone suggested a book title style.", "有人建议用书名风格。"], ["Everyone built on that idea.", "大家在这个点子上发散。"]],
    writing: { zh: "给朋友提一条周末计划建议。", hintEn: "Practice makes perfect." } },
  { day: 94, titleEn: "Talking About Habits", titleZh: "第 94 天 · 谈论习惯", goalZh: "用频率副词准确描述习惯。",
    vocabIds: ["w:routine", "w:habit", "w:rarely", "w:occasionally", "w:constantly"], grammarTopicId: "present-simple",
    phonicsRuleIds: ["ch", "ee"], pattern: { titleZh: "句型：I hardly ever ___. / Once in a while, ___.", explainZh: "频率阶梯：always>usually>often>sometimes>occasionally>hardly ever>never。",
      examples: [["I occasionally skip breakfast.", "我偶尔不吃早饭。"], ["He constantly checks his phone.", "他不停地看手机。"], ["Hardly ever do we eat out now.", "我们现在很少外出吃饭。"]],
      sentences: [["w:feedback", "你多久写一次日记？"], ["Usually I walk at noon.", "我通常中午散步。"], ["Never on an empty stomach!", "绝不空腹做！"]] },
    reading: [["Rita tracks her habits in a notebook.", "丽塔用本子记录习惯。"], ["Reading nightly stuck; running didn't.", "每晚阅读坚持了，跑步没有。"], ["She adjusted the plan instead of quitting.", "她调整计划而不是放弃。"]],
    writing: { zh: "用两个不同频率副词描述你的习惯。", hintEn: "I usually ___, but I rarely ___." } },
  { day: 95, titleEn: "Describing Changes", titleZh: "第 95 天 · 描述变化", goalZh: "比较过去与现在的社区变化。",
    vocabIds: ["w:gradually", "w:transform", "w:decade", "w:nowadays", "w:housing-market"], grammarTopicId: "past-simple",
    phonicsRuleIds: ["oa", "gr"], pattern: { titleZh: "句型：Used to be ___; now it's ___.", explainZh: "used to + 动词原形 表示过去的常态，现在不再如此。",
      examples: [["This used to be a farm.", "这里曾经是农场。"], ["Downtown used to close at six.", "以前市中心六点关门。"], ["Now it's busy till midnight.", "现在忙到午夜。"]],
      sentences: [["Things changed gradually after the subway opened.", "地铁开通后一切渐渐变了。"], ["Old neighbors moved away.", "老邻居们搬走了。"], ["Some things never change though.", "不过有些事从没变。"]] },
    reading: [["Grandpa maps his old town from memory.", "爷爷凭记忆画老城地图。"], ["The theater is a coffee bar now.", "老剧院现在是咖啡馆。"], ["His school still stands, painted blue.", "母校还在，刷成了蓝色。"]],
    writing: { zh: "写一句你家附近最大的变化。", hintEn: "___ used to ___. Now ___." } },
  { day: 96, titleEn: "Plans vs Predictions", titleZh: "第 96 天 · 计划与预测", goalZh: "区分 going to 与 will 的语感。",
    vocabIds: ["w:eventually", "w:definitely", "w:expect", "w:predict", "w:probably"], grammarTopicId: "future-simple",
    phonicsRuleIds: ["oa", "ai"], pattern: { titleZh: "句型：I'm going to ___ / It will ___.", explainZh: "有计划用 be going to；临场判断/预测用 will。",
      examples: [["I'm going to start yoga next week.", "我下周要开始瑜伽（已报名）。"], ["It will probably snow tonight.", "今晚大概会下雪。"], ["We'll see what happens.", "走一步看一步。"]],
      sentences: [["She's going to study nursing.", "她打算读护理。"], ["Prices will drop after the holidays.", "假期后价格会降。"], ["I won't be late this time.", "这次我不会迟到。"]] },
    reading: [["Leo planned his year in January.", "利奥一月就做了全年计划。"], ["Half went as scheduled.", "一半按计划完成。"], ["The rest taught him flexibility.", "另一半教会了他灵活应变。"]],
    writing: { zh: "各写一句计划与预测。", hintEn: "I'm going to ___. I think ___ will ___." } },
  { day: 97, titleEn: "Borrowing & Lending", titleZh: "第 97 天 · 借与还", goalZh: "谈论借钱借物，设定边界。",
    vocabIds: ["w:borrow", "w:lend", "w:owe", "w:return", "w:loan"], grammarTopicId: "pronouns-basic",
    phonicsRuleIds: ["or", "ow-2"], pattern: { titleZh: "句型：Review and practice.", explainZh: "borrow 借入，lend 借出。钱往来最好写明时间：by Friday。",
      examples: [["w:feedback", "能借用你的充电器吗？"], ["w:feedback", "能借我二十块吗？"], ["I'll return it tomorrow morning.", "我明早还你。"]],
      sentences: [["I owe you one.", "我欠你个人情。"], ["Lending money strains friendships.", "借钱伤感情。"], ["Write it down if it's serious.", "金额大就立字据。"]] },
    reading: [["Dan lent his truck to a neighbor.", "丹把卡车借给了邻居。"], ["It came back with a full tank and a thank-you card.", "车还回来油箱满、还有感谢卡。"], ["Now they trade tools often.", "如今他们常互通工具。"]],
    writing: { zh: "写一句借东西的请求和归还承诺。", hintEn: "Practice makes perfect." } },
  { day: 98, titleEn: "At the Doctor's Office", titleZh: "第 98 天 · 复诊沟通", goalZh: "描述疗效与复诊安排。",
    vocabIds: ["w:treatment", "w:recovery", "w:symptom", "w:prescription", "w:checkup"], grammarTopicId: "present-progressive",
    phonicsRuleIds: ["th-vl", "sh"], pattern: { titleZh: "句型：Review and practice.", explainZh: "复习已学内容并识别需要进一步练习的领域，确保知识巩固。",
      examples: [["The cough is getting better.", "咳嗽在好转。"], ["w:feedback", "我需要复诊吗？"], ["The new prescription works faster.", "新处方见效更快。"]],
      sentences: [["Symptoms returned last night.", "昨晚症状又出现了。"], ["Avoid coffee while on this medicine.", "服此药期间避免咖啡。"], ["Book a follow-up in two weeks.", "两周后约复诊。"]] },
    reading: [["After surgery, Ken walked daily.", "术后肯每天散步。"], ["Progress felt slow, then steady.", "进展先是缓慢，然后稳定。"], ["His doctor called it textbook recovery.", "医生说这是教科书式康复。"]],
    writing: { zh: "写一句向医生描述近期状况的话。", hintEn: "The pain is ___, but I still feel ___." } },
  { day: 99, titleEn: "Fixing Misunderstandings", titleZh: "第 99 天 · 澄清误会", goalZh: "澄清误会、确认信息的常用句。",
    vocabIds: ["w:actually", "w:apology", "w:confuse", "w:message", "w:respond"], grammarTopicId: "negation",
    phonicsRuleIds: ["th-vd", "r"], pattern: { titleZh: "句型：Just to clarify, ___. / That's not quite what I meant.", explainZh: "澄清开头 Just to clarify / What I meant was…；认领误会说 My fault.",
      examples: [["Just to clarify, the meeting is at two.", "澄清一下，会议两点。"], ["That's not quite what I meant.", "我不完全是那个意思。"], ["Oh, my fault — thanks for catching that.", "哦我的错——谢谢你指出。"]],
      sentences: [["Let me put it another way.", "换个说法。"], ["w:feedback", "那我们现在达成一致了？"], ["No worries — easy mix-up.", "没事——很容易搞混。"]] },
    reading: [["Ana thought the party was Saturday.", "安娜以为聚会是周六。"], ["The group chat said Sunday.", "群消息写的周日。"], ["One clarifying text saved her a trip.", "一条澄清短信免了她白跑一趟。"]],
    writing: { zh: "写一句澄清时间的消息。", hintEn: "Just to clarify, ___ starts at ___." } },
  { day: 100, titleEn: "Review: Advanced Daily Life", titleZh: "第 100 天 · 阶段复习(百天)",
    goalZh: "综合复习 91-99 天内容，庆祝一百天坚持。",
    vocabIds: ["w:milestone", "w:determination", "w:habit", "w:proud", "w:progress-n"], grammarTopicId: "basic-clauses",
    phonicsRuleIds: ["ai", "igh"], pattern: { titleZh: "句型：Day by day, ___.", explainZh: "百日复盘：用 Day by day 句型总结渐进变化，并列出下一步。",
      examples: [["Day by day, my ears got used to English.", "一天天下来耳朵习惯了英语。"], ["I can handle complaints politely now.", "我现在能得体处理投诉。"], ["Small wins stack up.", "小胜利会累积。"]],
      sentences: [["One hundred days of showing up matters.", "坚持打卡一百天本身就重要。"], ["Next: longer conversations.", "下一步：更长的对话。"], ["Proud, not perfect.", "求进步不求完美。"]] },
    reading: [["Jia marked Day 100 with dumplings.", "佳在第100天用饺子庆祝。"], ["Her phone log showed 100 green dots.", "手机记录里有一百个绿点。"], ["Each dot was a promise kept.", "每个绿点都是一次守约。"]],
    writing: { zh: "写两句百日总结。", hintEn: "In 100 days, I ___. Next, I will ___." } },
];
