import type { CourseDayPlan } from "@/content/pipeline/generate-days";

/** Day 126-130 工作沟通深化(收尾). */
export const PLAN_126_130: readonly CourseDayPlan[] = [
  { day: 126, titleEn: "Writing Status Emails", titleZh: "第 126 天 · 状态邮件", goalZh: "三段式状态邮件：进展/风险/需求。",
    vocabIds: ["w:progress-n", "w:feedback", "w:request", "w:deadline", "w:attachment"], grammarTopicId: "basic-clauses", phonicsRuleIds: ["ee", "st"],
    pattern: { titleZh: "句型：Quick update on ___: ___.", explainZh: "状态邮件开头 Quick update on X；风险用 Risk:；需求用 Ask:。",
      examples: [["Quick update on the launch: on track.", "发布简报：一切按计划。"], ["Risk: vendor reply is slow.", "风险：供应商回复慢。"], ["Ask: confirm budget by Friday.", "请求：周五前确认预算。"]],
      sentences: [["Two wins, one risk today.", "今天两个进展一个风险。"], ["Details live in the doc.", "细节在文档里。"], ["Ping me with questions.", "有问题随时问。"]] },
    reading: [["Subject lines carry the verdict.", "主题行直接给结论。"], ["\x27Green/Yellow/Red\x27 saves reading time.", "红黄绿标记省阅读时间。"], ["Short emails get short replies.", "短邮件收短回复。"]],
    writing: { zh: "写一封三段式状态邮件。", hintEn: "Update on ___: done ___, in progress ___, ask ___." } },
  { day: 127, titleEn: "Phone: Scheduling", titleZh: "第 127 天 · 电话约时间", goalZh: "电话协调多人时间。",
    vocabIds: ["w:schedule", "w:agenda", "w:confirm", "w:call-back", "w:feedback"], grammarTopicId: "questions", phonicsRuleIds: ["ai", "ee"],
    pattern: { titleZh: "句型：Review and practice.", explainZh: "复习已学内容并识别需要进一步练习的领域，确保知识巩固。",
      examples: [["w:feedback", "周四两点可以吗？"], ["Let's lock in ten a.m.", "就定上午十点。"], ["I'll send a calendar invite.", "我发个日历邀请。"]],
      sentences: [["Mornings are tight for me.", "我上午时间紧。"], ["w:feedback", "能安排半小时吗？"], ["If anything changes, tell me early.", "有变化早点说。"]] },
    reading: [["Group scheduling dies without a deadline.", "没有截止时间的群约必死。"], ["One person proposes two options.", "一人提两个选项。"], ["Others vote with one word.", "其他人一词表决。"]],
    writing: { zh: "写一句电话里确认时间的话。", hintEn: "So we're set for ___ at ___." } },
  { day: 128, titleEn: "Time Audit", titleZh: "第 128 天 · 时间盘点", goalZh: "描述时间去向并调整。",
    vocabIds: ["w:track", "w:waste", "w:habit", "w:focus", "w:routine"], grammarTopicId: "past-simple", phonicsRuleIds: ["ow-2", "ai"],
    pattern: { titleZh: "句型：I spent ___ on ___ last week.", explainZh: "盘点句 spend + 时间 + on；减少 cut down on。",
      examples: [["I spent six hours on email.", "我花了六小时处理邮件。"], ["Meetings ate my deep-work time.", "会议吃掉了专注时间。"], ["I cut down on evening scrolling.", "我减少了晚间刷手机。"]],
      sentences: [["Track one honest day first.", "先诚实记录一天。"], ["Small leaks sink schedules.", "小漏洞沉大船。"], ["Protect one focus block daily.", "每天保护一个专注时段。"]] },
    reading: [["Ken logged his Tuesday honestly.", "肯诚实记录了周二。"], ["Ninety minutes vanished into news feeds.", "九十分钟消失在信息流里。"], ["He moved that time to the gym.", "他把这段时间挪给了健身房。"]],
    writing: { zh: "写一句上周时间花销盘点。", hintEn: "Last week I spent ___ hours on ___." } },
  { day: 129, titleEn: "Deadline Pressure", titleZh: "第 129 天 · 截止日压力", goalZh: "高压周的表达与求援时机。",
    vocabIds: ["w:overtime", "w:fatigue", "w:cope", "w:limit", "w:complete"], grammarTopicId: "basic-clauses", phonicsRuleIds: ["ai", "sh"],
    pattern: { titleZh: "句型：Review and practice.", explainZh: "压力来源用 because 指向具体；求援要具体到任务和时间。",
      examples: [["We're under pressure because of the audit.", "审计让我们压力很大。"], ["w:feedback", "今晚你能接手幻灯片吗？"], ["I'd rather deliver less, done well.", "我宁愿少交但交好。"]],
      sentences: [["Coffee isn't a strategy.", "咖啡不是策略。"], ["Split the list, swap tasks.", "拆清单，换任务。"], ["Sleep protects tomorrow's speed.", "睡眠保护明天的速度。"]] },
    reading: [["Launch week tested the whole team.", "发布周考验全队。"], ["They cut two features, not corners.", "他们砍功能，不砍质量。"], ["Friday's demo went clean.", "周五演示顺利通过。"]],
    writing: { zh: "写一句高压下的求助表达。", hintEn: "Practice makes perfect." } },
  { day: 130, titleEn: "Review: Workplace Voice", titleZh: "第 130 天 · 复习：职场之声", goalZh: "综合复习汇报/分歧/邮件/电话/优先级。",
    vocabIds: ["w:confidence", "w:feedback", "w:review", "w:negotiate", "w:practice-n"], grammarTopicId: "basic-clauses", phonicsRuleIds: ["ai", "er"],
    pattern: { titleZh: "句型：At work, I can now ___ confidently.", explainZh: "职场能力盘点：At work, I can now + 动作。",
      examples: [["I can disagree with data, calmly.", "我能用数据冷静反对。"], ["I can write a clear ask.", "我能写出清晰的请求。"], ["I can protect my focus time.", "我能保护专注时间。"]],
      sentences: [["Clear beats clever at work.", "职场上清晰胜过聪明。"], ["Your calendar is your real plan.", "日历才是真正的计划。"], ["Kind + direct wins long-term.", "友善且直接才能长久。"]] },
    reading: [["Twenty days ago, meetings drained Ana.", "二十天前会议耗尽了安娜。"], ["Now she speaks first in standups.", "现在她站会第一个发言。"], ["Same ideas, sharper words.", "同样的想法，更锋利的表达。"]],
    writing: { zh: "写两句你的职场能力变化。", hintEn: "At work, I can now ___ and ___." } },
];
