import type { CourseDayPlan } from "@/content/pipeline/generate-days";

/** Day 101-110 生活高级表达(收尾) - compact real plans. */
export const PLAN_101_110: readonly CourseDayPlan[] = [
  { day: 101, titleEn: "At the Bank", titleZh: "第 101 天 · 银行办事", goalZh: "办理开户与咨询业务。",
    vocabIds: ["w:savings-account-n2", "w:direct-deposit-form", "w:bank-statement", "w:atm", "w:deposit"], grammarTopicId: "questions",
    phonicsRuleIds: ["a-short", "ng"], pattern: { titleZh: "句型：Review and practice.", explainZh: "w:feedback Please practice this pattern daily with real examples.",
      examples: [["I'd like to open a savings account.", "我想开一个储蓄账户。"], ["w:feedback", "电汇收费吗？"], ["w:feedback", "能帮我查下余额吗？"]],
      sentences: [["Bring two IDs and proof of address.", "带两件证件和地址证明。"], ["The statement comes monthly.", "对账单每月寄送。"], ["Sign here and here.", "请在这里和这里签字。"]] },
    reading: [["Wei switched banks last spring.", "小魏去年春天换了银行。"], ["Direct deposit took one paycheck to kick in.", "直接存款一个发薪周期才生效。"], ["Now everything is in one app.", "现在一切都在一个应用里。"]],
    writing: { zh: "写一句你要在银行办的业务。", hintEn: "I'd like to ___ today." } },
  { day: 102, titleEn: "Car Trouble", titleZh: "第 102 天 · 车辆问题", goalZh: "描述车辆故障并预约维修。",
    vocabIds: ["w:mechanic", "w:battery", "w:repair", "w:insurance", "w:schedule"], grammarTopicId: "present-progressive",
    phonicsRuleIds: ["ar", "ai"], pattern: { titleZh: "句型：My car won't start. / It's making a strange noise.", explainZh: "won't start 打不着火；异响 making a noise；拖车 say tow truck。",
      examples: [["My car won't start this morning.", "我车今天早上打不着火。"], ["It's making a strange noise when braking.", "刹车时有怪声。"], ["w:feedback", "修理要多久？"]],
      sentences: [["The battery might be dead.", "可能是电池没电了。"], ["w:feedback", "能拖到店里吗？"], ["Please text me the estimate first.", "先发报价给我。"]] },
    reading: [["Priya's van sputtered on the freeway.", "普莉娅的货车在高速上突突作响。"], ["Roadside assistance towed it quickly.", "道路救援很快拖了车。"], ["A worn belt was the whole problem.", "问题只是一根老化皮带。"]],
    writing: { zh: "写一句向修车行描述故障的话。", hintEn: "Practice makes perfect." } },
  { day: 103, titleEn: "Neighborhood Watch", titleZh: "第 103 天 · 社区安全", goalZh: "报告可疑情况、参与社区事务。",
    vocabIds: ["w:neighborhood", "w:police-station", "w:report", "w:witness", "w:officer"], grammarTopicId: "past-simple",
    phonicsRuleIds: ["r", "or"], pattern: { titleZh: "句型：Someone was ___ing near ___. / I'd like to report ___.", explainZh: "描述可疑行为用过去进行时 was/were + doing。",
      examples: [["I'd like to report a stolen bike.", "我要报失一辆自行车。"], ["Someone was checking car doors last night.", "昨晚有人挨个拉车门。"], ["The officer took notes politely.", "警官礼貌地做了记录。"]],
      sentences: [["Here's my camera footage.", "这是我的监控录像。"], ["Stay safe and lock up.", "注意安全，锁好门窗。"], ["Neighbors shared updates in the group.", "邻居们在群里互通消息。"]] },
    reading: [["Maple Street started a watch group.", "枫树街成立了守望小组。"], ["Members rotate evening walks.", "成员轮流傍晚巡视。"], ["Package thefts dropped that month.", "当月包裹盗窃就少了。"]],
    writing: { zh: "写一句向警方描述情况的报告。", hintEn: "Yesterday around ___, I saw ___." } },
  { day: 104, titleEn: "Ordering Repairs", titleZh: "第 104 天 · 家政维修", goalZh: "比较报价并安排上门服务。",
    vocabIds: ["w:plumber", "w:electrician", "w:repair", "w:appointment", "w:feedback"], grammarTopicId: "future-simple",
    phonicsRuleIds: ["pl", "er"], pattern: { titleZh: "句型：Review and practice.", explainZh: "w:feedback Please practice this pattern daily with real examples.",
      examples: [["w:feedback", "多快能上门？"], ["w:feedback", "报价含配件和人工吗？"], ["Mornings work best for us.", "上午最方便。"]],
      sentences: [["Get two estimates before deciding.", "决定前拿两份报价。"], ["The plumber charged by the hour.", "水管工按小时收费。"], ["Fixed it in under an hour.", "不到一小时修好了。"]] },
    reading: [["The sink backed up on Sunday.", "周日水槽堵了。"], ["Two plumbers quoted different prices.", "两位水管工报价不同。"], ["She chose experience over the cheapest bid.", "她选了经验而非最低价。"]],
    writing: { zh: "写一句预约维修的话。", hintEn: "Practice makes perfect." } },
  { day: 105, titleEn: "Talking About News", titleZh: "第 105 天 · 聊新闻", goalZh: "转述新闻并与朋友讨论。",
    vocabIds: ["w:headline", "w:article", "w:source", "w:bias", "w:evidence"], grammarTopicId: "basic-clauses",
    phonicsRuleIds: ["ee", "st"], pattern: { titleZh: "句型：Review and practice.", explainZh: "w:feedback Please practice this pattern daily with real examples.",
      examples: [["w:feedback", "听说新公园的事了吗？"], ["It says here that prices dropped.", "报上说价格降了。"], ["That source seems reliable.", "这个来源挺可靠。"]],
      sentences: [["I read two articles about it.", "我读了两篇相关报道。"], ["Some outlets spin the same facts.", "有些媒体会加工事实。"], ["Let's check the official statement.", "我们看看官方声明。"]] },
    reading: [["News club meets Tuesdays at lunch.", "新闻社周二午间活动。"], ["Members bring one story each.", "每人带一条新闻分享。"], ["They rate sources before opinions.", "先评来源再谈观点。"]],
    writing: { zh: "转述一条你最近看到的新闻。", hintEn: "I read that ___, because ___.", } },
  { day: 106, titleEn: "Weather Small Talk", titleZh: "第 106 天 · 天气寒暄进阶", goalZh: "用天气开启并延展对话。",
    vocabIds: ["w:freezing", "w:humid", "w:chilly", "w:drizzle", "w:forecast"], grammarTopicId: "future-simple",
    phonicsRuleIds: ["fl", "ee"], pattern: { titleZh: "句型：Review and practice.", explainZh: "附加疑问 isn't it 拉近关系；预报用 be supposed to / supposed to rain。",
      examples: [["w:feedback", "今天真冷，是吧？"], ["Supposed to drizzle tomorrow.", "明天可能有小雨。"], ["Perfect beach weather, finally!", "终于到海滩好天气了！"]],
      sentences: [["This humidity frizzed my hair.", "这湿度把我头发弄毛躁了。"], ["Forecast says clear skies all week.", "预报说整周晴天。"], ["Good day for indoor plans.", "适合安排室内活动。"]] },
    reading: [["Elevator weather talk gets a bad rap.", "电梯里聊天气常被调侃。"], ["But it works: low stakes, shared truth.", "但它有效：低风险且有共识。"], ["Then pivot to the weekend.", "然后顺势聊周末。"]],
    writing: { zh: "写两句以天气开场的对话。", hintEn: "Practice makes perfect." } },
  { day: 107, titleEn: "Describing People Kindly", titleZh: "第 107 天 · 得体描述他人", goalZh: "中性/褒义描述外貌性格，避免刻板。",
    vocabIds: ["w:outfit", "w:personality", "w:generous", "w:reliable", "w:talkative"], grammarTopicId: "pronouns-basic",
    phonicsRuleIds: ["pl", "sh"], pattern: { titleZh: "句型：He's the kind of person who ___.", explainZh: "评价人用 who 从句更具体：the kind of person who always helps.",
      examples: [["She's the kind of person who remembers birthdays.", "她是记得朋友生日的那种人。"], ["He dresses sharp but stays humble.", "他穿着讲究却谦逊。"], ["They're generous with their time.", "他们乐于花时间帮人。"]],
      sentences: [["Describe skills, not looks, at work.", "职场评价看能力不看外貌。"], ["Talkative isn't a flaw in sales.", "销售岗位健谈不是缺点。"], ["Kind words travel far.", "好话传得远。"]] },
    reading: [["Yearbook notes described classmates warmly.", "毕业留言温暖地描述同学。"], ["One line kept returning: always helped.", "一句话反复出现：总是帮忙。"], ["Character outlasts yearbook photos.", "品格比照片更长久。"]],
    writing: { zh: "用 who 从句写一句夸同事的话。", hintEn: "She's the kind of person who ___." } },
  { day: 108, titleEn: "Planning a Trip Together", titleZh: "第 108 天 · 结伴旅行规划", goalZh: "协商行程、分工与预算。",
    vocabIds: ["w:itinerary", "w:destination", "w:split", "w:book-v", "w:souvenir"], grammarTopicId: "questions",
    phonicsRuleIds: ["sp", "ai"], pattern: { titleZh: "句型：Review and practice.", explainZh: "w:feedback Please practice this pattern daily with real examples.",
      examples: [["w:feedback", "今晚订机票好吗？"], ["Let's split hotels and food evenly.", "住宿餐饮平摊吧。"], ["Decide by Friday or prices jump.", "周五前定，否则涨价。"]],
      sentences: [["w:feedback", "谁负责行程表？"], ["One museum day, one beach day.", "一天博物馆，一天海滩。"], ["Leave room for surprises.", "留点意外空间。"]] },
    reading: [["Three friends planned a desert trip.", "三个朋友计划沙漠之旅。"], ["A shared note held every decision.", "共享笔记记录每个决定。"], ["No group-chat chaos this time.", "这次群聊不再混乱。"]],
    writing: { zh: "写一句提议并附截止时间。", hintEn: "Practice makes perfect." } },
  { day: 109, titleEn: "Handling Delays", titleZh: "第 109 天 · 延误应对", goalZh: "延误时改签、沟通与安抚。",
    vocabIds: ["w:delay", "w:cancel", "w:refund", "w:voucher", "w:compensate-for"], grammarTopicId: "negation",
    phonicsRuleIds: ["ng", "ai"], pattern: { titleZh: "句型：Review and practice.", explainZh: "关键句 What are my options（有哪些选择）？语气稳，信息全。",
      examples: [["Our flight got delayed three hours.", "航班延误三小时。"], ["w:feedback", "今晚还有别的航班吗？"], ["w:feedback", "有餐券吗？"]],
      sentences: [["Don't cancel — rebook instead.", "别取消——改签吧。"], ["Keep the delay receipt.", "保留延误凭证。"], ["Breathe; airlines handle this daily.", "深呼吸，航空公司天天处理这种事。"]] },
    reading: [["Storms grounded every departure.", "暴风雨使所有航班停飞。"], ["The gate agent offered two options calmly.", "地勤冷静给出两个方案。"], ["Passengers who asked questions flew sooner.", "主动询问的乘客更早成行。"]],
    writing: { zh: "写一句延误时询问补偿的礼貌用语。", hintEn: "Practice makes perfect." } },
  { day: 110, titleEn: "Review: Real-Life Ready", titleZh: "第 110 天 · 阶段复习",
    goalZh: "复习 91-109 天，检验真实生活场景应对力。",
    vocabIds: ["w:confidence", "w:progress-n", "w:practice-n", "w:feedback", "w:review"], grammarTopicId: "basic-clauses",
    phonicsRuleIds: ["ai", "er"], pattern: { titleZh: "句型：If ___, I know how to ___ now.", explainZh: "能力盘点句：If X happens, I know how to respond.",
      examples: [["If the sink leaks, I know how to book a plumber.", "水管漏水我知道怎么约师傅。"], ["If flights delay, I know what to ask.", "航班延误我知道问什么。"], ["If plans change, I renegotiate kindly.", "计划变了我会好好重谈。"]],
      sentences: [["Real life rewards preparation.", "现实奖励有准备的人。"], ["Review beats cramming.", "复习胜过突击。"], ["Next stop: workplace English.", "下一站：职场英语。"]] },
    reading: [["Lin replayed her hardest moment this month.", "小林回顾本月最难的一刻。"], ["It was a phone call about a delay.", "是一通关于延误的电话。"], ["She handled it in English — calmly.", "她用英语从容处理了。"]],
    writing: { zh: "写两句你的能力盘点。", hintEn: "If ___, I know how to ___." } },
];
