import type { CourseDayPlan } from "@/content/pipeline/generate-days";

/** Phase 10-B · Day 151-160 Advanced Communication I（高级表达 I）. */
export const PLAN_151_160: readonly CourseDayPlan[] = [
  {
    day: 151,
    titleEn: "Stating Your Opinion",
    titleZh: "第 151 天 · 表达个人观点",
    goalZh: "用清晰的框架陈述并支撑个人观点。",
    vocabIds: [
      "w:argument-premises-not-shouting-contest",
      "w:persuasion-ethos-pathos-logos-triangle",
      "w:articulate-thoughts-into-clean-sentences-skill",
      "w:tone-message-emotion-channel-check",
      "w:specific-nail-down-the-details-skill",
    ],
    grammarTopicId: "basic-clauses",
    phonicsRuleIds: ["th-vl", "er"],
    pattern: {
      titleZh: "句型：In my opinion, ___ because ___. / The way I see it, ___.",
      explainZh: "观点两件套：亮观点 In my opinion / The way I see it；接 because 给出理由，一句话完成“观点+依据”。",
      examples: [
        ["In my opinion, remote work saves everyone time.", "在我看来，远程办公为每个人省了时间。"],
        ["The way I see it, the plan needs one more test.", "依我看，这个方案还需要再测一次。"],
        ["From where I stand, quality comes first.", "站在我的角度，质量优先。"],
      ],
      sentences: [
        ["State the claim, then earn it.", "先亮主张，再证明它。"],
        ["One opinion per sentence keeps you clear.", "一句一个观点才清楚。"],
        ["Calm tone makes opinions land.", "语气平稳，观点才站得住。"],
      ],
    },
    reading: [
      ["The team debated two designs on Tuesday.", "周二团队就两个设计展开辩论。"],
      ["Maya opened with her opinion and one reason.", "玛雅先亮观点再给一条理由。"],
      ["Nobody interrupted; everyone took notes.", "没人插话，大家都在记录。"],
    ],
    writing: { zh: "用 In my opinion… because… 写一句你对远程办公的看法。", hintEn: "In my opinion, ___ because ___." },
  },
  {
    day: 152,
    titleEn: "Reasons & Evidence",
    titleZh: "第 152 天 · 提供理由和证据",
    goalZh: "为观点补充可核查的理由与证据。",
    vocabIds: [
      "w:evidence-chain-custody",
      "w:accurate-fact-check-approved-adjective",
      "w:vague-foggy-commitments-warning-label",
      "w:significant-not-just-statistics-word",
      "w:marginal-edge-case-small-but-real-gains-word",
    ],
    grammarTopicId: "questions",
    phonicsRuleIds: ["ai", "r"],
    pattern: {
      titleZh: "句型：For example, ___. / According to ___, ___. / That's why ___.",
      explainZh: "证据三连：举例 For example；引来源 According to；收束因果 That's why。让理由落地成证据链。",
      examples: [
        ["For example, our pilot saved ten hours a week.", "例如，我们的试点每周节省十小时。"],
        ["According to the survey, seventy percent agree.", "根据调查，百分之七十的人同意。"],
        ["That's why we recommend phase two.", "这就是我们建议进入第二阶段的原因。"],
      ],
      sentences: [
        ["Numbers persuade; adjectives decorate.", "数字说服人，形容词只是装饰。"],
        ["Name the source or lose the point.", "说不出来源，论点就立不住。"],
        ["Small gains still count as evidence.", "小改善也算证据。"],
      ],
    },
    reading: [
      ["Wei's report cited three sources.", "小魏的报告引用了三个来源。"],
      ["Each claim carried one number.", "每个论点都带一个数字。"],
      ["The manager approved it without edits.", "经理未经修改直接批准。"],
    ],
    writing: { zh: "用 For example… That's why… 为昨天的观点补两条证据。", hintEn: "For example, ___; that's why ___." },
  },
  {
    day: 153,
    titleEn: "Agreeing & Disagreeing",
    titleZh: "第 153 天 · 同意与不同意",
    goalZh: "礼貌地表达同意与有理有据的反对。",
    vocabIds: [
      "w:on-the-same-page-alignment-confirmation-idiom",
      "w:insist-boundary-with-smile-repeat-technique",
      "w:refuse-polite-no-without-paragraph-defense",
      "w:negotiate-terms-win-win-drafting",
      "w:silence-strategic-pause-negotiation-weapon",
    ],
    grammarTopicId: "negation",
    phonicsRuleIds: ["ng", "oi"],
    pattern: {
      titleZh: "句型：I see your point, but ___. / I'm afraid I disagree about ___.",
      explainZh: "先接后转：I see your point, but… 承认对方再转折；I'm afraid 让否定听起来体面。",
      examples: [
        ["I see your point, but the budget won't stretch.", "我明白你的意思，但预算撑不住。"],
        ["I'm afraid I disagree about the timeline.", "恐怕在时间表上我不敢苟同。"],
        ["Partly agreed — let's split the difference.", "部分同意——我们各退一步吧。"],
      ],
      sentences: [
        ["Disagree with ideas, never with people.", "反对的是想法，不是人。"],
        ["A pause beats a pushback.", "停顿胜过硬顶。"],
        ["Write down where you truly differ.", "把真正的分歧写下来。"],
      ],
    },
    reading: [
      ["The meeting hit a friendly stalemate.", "会议陷入友好的僵局。"],
      ["Ana restated Sam's idea before objecting.", "安娜反驳前先复述了山姆的想法。"],
      ["They left with two action items each.", "散会时各自领了两项行动。"],
    ],
    writing: { zh: "用 I see your point, but… 写一句委婉的反对。", hintEn: "I see your point, but ___." },
  },
  {
    day: 154,
    titleEn: "Clearing Up Misunderstandings",
    titleZh: "第 154 天 · 澄清误解",
    goalZh: "发现误会后快速澄清并修复对话。",
    vocabIds: [
      "w:clarify-before-assuming-disaster-prevention",
      "w:ambiguous-two-reads-one-sentence-trap",
      "w:rephrase-say-it-three-slower-ways-technique",
      "w:paraphrase-same-meaning-new-clothes-skill",
      "w:hesitate-two-second-buy-time-move",
    ],
    grammarTopicId: "present-simple",
    phonicsRuleIds: ["fl", "er"],
    pattern: {
      titleZh: "句型：Just to clarify, ___. / What I meant was ___.",
      explainZh: "澄清双句：Just to clarify 请求确认；What I meant was 重述本意。误会越早摊开越好修。",
      examples: [
        ["Just to clarify, the deadline is Thursday, not Tuesday.", "澄清一下，截止日是周四不是周二。"],
        ["What I meant was fewer meetings, not none.", "我的意思是少开会，不是不开会。"],
        ["So if I understand you right, we ship Friday?", "所以我理解得对的话，我们周五上线？"],
      ],
      sentences: [
        ["Repeat the ask back in your own words.", "用自己的话复述需求。"],
        ["Assume confusion before bad faith.", "先怀疑误会，别怀疑人品。"],
        ["One clear sentence beats five fast ones.", "一句清楚胜过五句飞快。"],
      ],
    },
    reading: [
      ["The client heard 'demo' as 'delivery'.", "客户把 demo 听成了 delivery。"],
      ["Sam caught it in one email.", "山姆一封邮件就发现了。"],
      ["Both sides laughed and reset the date.", "双方一笑，重新定了日期。"],
    ],
    writing: { zh: "用 Just to clarify… 写一句工作里的关键确认。", hintEn: "Just to clarify, ___." },
  },
  {
    day: 155,
    titleEn: "Explaining Complex Things Simply",
    titleZh: "第 155 天 · 把复杂的事讲简单",
    goalZh: "用类比和分步法解释复杂概念。",
    vocabIds: [
      "w:concise-cut-adjectives-payroll-halving",
      "w:dense-information-packed-or-thick-crusted-double-life",
      "w:summarize-three-sentences-maximum-rule",
      "w:emphasize-bold-the-one-number-that-matters",
      "w:profound-three-am-thoughts-adjective",
    ],
    grammarTopicId: "countable-uncountable",
    phonicsRuleIds: ["pl", "ai"],
    pattern: {
      titleZh: "句型：Think of it like ___. / It works in three steps.",
      explainZh: "化繁为简：Think of it like 用类比开路；It works in three steps 给出结构感。",
      examples: [
        ["Think of the cloud as a storage unit you rent.", "把云端想成你租的储物间。"],
        ["It works in three steps: collect, clean, chart.", "它分三步：收集、清洗、制图。"],
        ["Long story short, the fix takes one line.", "长话短说，修复只需一行。"],
      ],
      sentences: [
        ["Analogies carry heavy ideas far.", "类比能驮着重概念走远路。"],
        ["Cut every adjective; keep one number.", "砍掉形容词，留一个数字。"],
        ["If grandma gets it, it's ready.", "奶奶能听懂，才算讲明白。"],
      ],
    },
    reading: [
      ["Maya explained APIs using mailboxes.", "玛雅用邮箱解释 API。"],
      ["Three steps, one whiteboard, zero jargon.", "三步、一块白板、零术语。"],
      ["Even sales could repeat it back.", "连销售都能复述出来。"],
    ],
    writing: { zh: "用 Think of it like ___ 解释一个你行业的术语。", hintEn: "Think of it like ___." },
  },
  {
    day: 156,
    titleEn: "Describing Trends",
    titleZh: "第 156 天 · 描述变化趋势",
    goalZh: "描述数据与趋势的上升下降与波动。",
    vocabIds: [
      "w:steady-heartbeat-and-progress-shared-adjective",
      "w:erratic-weather-app-mood-swings-described",
      "w:substantial-size-that-pays-rent-adjective",
      "w:negligible-rounding-error-honesty-word",
      "w:forecast-sales-pipeline-projection",
    ],
    grammarTopicId: "past-simple",
    phonicsRuleIds: ["tr", "ee"],
    pattern: {
      titleZh: "句型：Sales rose steadily. / It dipped slightly, then recovered.",
      explainZh: "趋势公式：方向动词 rise/drop/dip/stay + 程度副词 steadily/sharply/slightly。",
      examples: [
        ["Costs dropped sharply last quarter.", "上季度成本急剧下降。"],
        ["Traffic stayed steady through the holidays.", "假期流量保持平稳。"],
        ["Signups fluctuated, then trended upward.", "注册量波动后整体向上。"],
      ],
      sentences: [
        ["Pair every verb with an honest degree.", "动词配副词，程度要诚实。"],
        ["Trends tell stories; pick the headline one.", "趋势会讲故事，挑主线讲。"],
        ["Compare against last year, not memory.", "和去年比，别凭记忆比。"],
      ],
    },
    reading: [
      ["The chart told a two-year story.", "这张图讲了两年故事。"],
      ["Revenue climbed steadily after March.", "三月之后收入稳步攀升。"],
      ["One dip matched the server outage.", "唯一一次下滑正好对应服务器故障。"],
    ],
    writing: { zh: "用两个趋势动词描述你行业今年的变化。", hintEn: "___ rose/dropped/stayed ___." },
  },
  {
    day: 157,
    titleEn: "Emotions & Attitudes",
    titleZh: "第 157 天 · 表达情绪和态度",
    goalZh: "准确命名情绪并以专业态度表达。",
    vocabIds: [
      "w:anger-hot-useful-brief-fuel-warning",
      "w:enthusiasm-contagious-energy-budget-item",
      "w:gratitude-three-things-before-bed-habit",
      "w:joy-unreasonable-small-moments-collector",
      "w:apologize-sincere-repair-kit-for-mistakes",
    ],
    grammarTopicId: "present-progressive",
    phonicsRuleIds: ["sh", "ai"],
    pattern: {
      titleZh: "句型：I'm feeling ___. / To be honest, this is ___.",
      explainZh: "情绪表达：I'm feeling + 情绪词 命名感受；To be honest 引出真实态度但不失礼。",
      examples: [
        ["I'm feeling optimistic about the pilot.", "我对试点感到乐观。"],
        ["To be honest, the delay frustrated me.", "说实话，这次延误让我沮丧。"],
        ["I appreciate your patience more than you know.", "你的耐心比你以为的更珍贵。"],
      ],
      sentences: [
        ["Name the feeling to tame the feeling.", "说出情绪，才能安放情绪。"],
        ["Gratitude costs nothing and pays daily.", "感激不花钱，却天天有回报。"],
        ["Frustration stated politely still counts.", "礼貌说出的沮丧同样有效。"],
      ],
    },
    reading: [
      ["The rollout hit another snag.", "上线又遇到一个坎。"],
      ["Priya named her frustration in one sentence.", "普里雅用一句话说出了沮丧。"],
      ["Then she proposed the next step calmly.", "接着她平静地提出下一步。"],
    ],
    writing: { zh: "用 I'm feeling… 写一句本周真实的情绪及其原因。", hintEn: "I'm feeling ___ because ___." },
  },
  {
    day: 158,
    titleEn: "Formal vs Casual Registers",
    titleZh: "第 158 天 · 正式与非正式表达转换",
    goalZh: "同一意思在正式与非正式场合间自由切换。",
    vocabIds: [
      "w:register-formal-versus-casual-switching",
      "w:formal-written-contract-language-style",
      "w:casual-friday-language-relaxation-zone",
      "w:slang-generation-password-refresh-cycle",
      "w:polite-request-vs-demand-phrasing-art",
    ],
    grammarTopicId: "articles",
    phonicsRuleIds: ["st", "fl"],
    pattern: {
      titleZh: "句型：Formal: Could you please ___? / Casual: Can you ___?",
      explainZh: "语域切换：正式加 Could you please / would；口语直接 Can you / gonna。对象决定说法。",
      examples: [
        ["Formal: Could you please send the contract today?", "正式：能否请您今天发来合同？"],
        ["Casual: Can you shoot me the contract today?", "口语：今天能甩给我合同吗？"],
        ["Formal: I would appreciate a quick reply.", "正式：如蒙速复，不胜感激。"],
      ],
      sentences: [
        ["Match the channel before the words.", "先看渠道再选措辞。"],
        ["When unsure, go one notch formal.", "拿不准时，正式半档。"],
        ["Slang expires; courtesy doesn't.", "俚语会过期，客气不会。"],
      ],
    },
    reading: [
      ["Wei rewrote his email twice.", "小魏把邮件改了两遍。"],
      ["Version one sounded like a text message.", "第一版读起来像短信。"],
      ["Version three got a reply within the hour.", "第三版一小时内就收到回复。"],
    ],
    writing: { zh: "把 Can you send it? 改写成一句正式请求。", hintEn: "Could you please ___?" },
  },
  {
    day: 159,
    titleEn: "Discussing Social Topics",
    titleZh: "第 159 天 · 社会话题讨论",
    goalZh: "就社会议题进行平衡、尊重的讨论。",
    vocabIds: [
      "w:debate-team-rebuttal-timer-discipline",
      "w:nuance-fine-distinction-expert-ear-test",
      "w:superficial-first-impression-only-depth-settings",
      "w:context-clue-guessing-skill-training",
      "w:humility-strength-without-spotlight-need",
    ],
    grammarTopicId: "future-simple",
    phonicsRuleIds: ["th-vd", "r"],
    pattern: {
      titleZh: "句型：Some argue that ___; others believe ___. / It depends on ___.",
      explainZh: "平衡讨论：Some argue… others believe… 呈现两面；It depends on 承认复杂性。",
      examples: [
        ["Some argue cities should add bike lanes; others worry about parking.", "有人主张增设自行车道，也有人担心停车。"],
        ["It depends on local traffic data.", "这取决于当地交通数据。"],
        ["There's truth on both sides here.", "两边各有道理。"],
      ],
      sentences: [
        ["Steel-man the other side first.", "先把对方观点讲到最强。"],
        ["Data before anecdotes.", "先摆数据再讲故事。"],
        ["Curiosity closes fewer doors than certainty.", "好奇比武断少关门。"],
      ],
    },
    reading: [
      ["The town hall discussed remote work.", "市政厅讨论远程办公。"],
      ["Speakers traded studies, not insults.", "发言者交换的是研究而非攻击。"],
      ["The council scheduled a follow-up forum.", "议会安排了后续论坛。"],
    ],
    writing: { zh: "用 Some argue… others believe… 写一句你对某社会议题的两面总结。", hintEn: "Some argue ___; others believe ___." },
  },
  {
    day: 160,
    titleEn: "Review: Communication Toolkit",
    titleZh: "第 160 天 · 综合复习：沟通工具箱",
    goalZh: "综合复习 151-159 天的高级沟通技能。",
    vocabIds: [
      "w:feedback-loop-fast-course-correction-culture",
      "w:summarize-three-sentences-maximum-rule",
      "w:on-the-same-page-alignment-confirmation-idiom",
      "w:review-second-pass-before-submitting-discipline",
      "w:confidence-earned-through-reps",
    ],
    grammarTopicId: "questions",
    phonicsRuleIds: ["er", "ai"],
    pattern: {
      titleZh: "句型：Looking back, I learned to ___. / Next, I want to master ___.",
      explainZh: "复盘句式：Looking back 盘点收获；Next, I want to master 指向下一程。",
      examples: [
        ["Looking back, I learned to disagree gracefully.", "回头看，我学会了体面地反对。"],
        ["Evidence changed how I argue.", "证据改变了我争论的方式。"],
        ["Next, I want to master formal registers.", "接下来我想掌握正式语域。"],
      ],
      sentences: [
        ["Review turns lessons into instincts.", "复习把课程变成本能。"],
        ["Keep the toolkit where you can see it.", "把工具箱放在看得见的地方。"],
        ["Ten days ago, some phrases felt impossible.", "十天前有些短语还觉得不可能学会。"],
      ],
    },
    reading: [
      ["The cohort ran a practice panel discussion.", "学员们做了一场模拟座谈。"],
      ["Everyone used one habit from Day 151-159.", "每个人都用了后十天的一个习惯。"],
      ["Feedback focused on clarity, not accents.", "反馈聚焦清晰度而非口音。"],
    ],
    writing: { zh: "写两句：这十天最有用的一个表达 + 下一步想掌握的技能。", hintEn: "Looking back, I learned ___; next, I want to master ___." },
  },
];
