import type { CourseDayPlan } from "@/content/pipeline/generate-days";

/** Day 144-150 真实美国生活深化(下). */
export const PLAN_144_150_CLEAN: readonly CourseDayPlan[] = [
  { day: 144, titleEn: "School & Parents", titleZh: "第 144 天 · 学校与家长", goalZh: "参加家长会并与老师沟通。",
    vocabIds: ["w:report-card", "w:teacher", "w:principal", "w:parents", "w:feedback"], grammarTopicId: "questions", phonicsRuleIds: ["r", "ee"],
    pattern: { titleZh: "句型：How is ___ doing in ___? / What can we do at home?", explainZh: "家长会两句核心：问表现 How is X doing…?；问配合 What can we do…?",
      examples: [["How is Maya doing in reading?", "玛雅阅读方面怎么样？"], ["What can we practice at home?", "在家能练什么？"], ["Is she turning in homework on time?", "她按时交作业吗？"]],
      sentences: [["Strengths first, then gaps.", "先说优势再谈差距。"], ["Teachers appreciate specific questions.", "老师喜欢具体问题。"], ["Fifteen minutes go fast — prioritize.", "十五分钟很快——抓重点。"]] },
    reading: [["Parent night ran four minutes per family.", "家长之夜每家四分钟。"], ["Mr. Lee showed two writing samples.", "李老师展示了两份写作样本。"], ["The plan: library card plus bedtime stories.", "计划：办借书卡加睡前故事。"]],
    writing: { zh: "写一句你在家长会要问的问题。", hintEn: "How is ___ doing in ___?" } },
  { day: 145, titleEn: "Recycling Rules", titleZh: "第 145 天 · 垃圾分类规则", goalZh: "描述本地回收规则并纠正错误投放。",
    vocabIds: ["w:recycle", "w:environment", "w:noise", "w:feedback", "w:list"], grammarTopicId: "countable-uncountable", phonicsRuleIds: ["ai", "bl"],
    pattern: { titleZh: "句型：___ goes in the ___ bin. / ___ can't be recycled.", explainZh: "垃圾分类句：X goes in Y bin；不能回收 X can't be recycled。",
      examples: [["Cardboard goes in the blue bin.", "纸板放蓝色桶。"], ["Plastic bags can't be recycled curbside.", "塑料袋路边不可回收。"], ["Rinse cans before recycling.", "回收前冲净罐子。"]],
      sentences: [["Check the city website for rules.", "上市政府网站查规则。"], ["Greasy pizza boxes ruin batches.", "油腻披萨盒毁掉整批。"], ["One wrong item costs the truck a trip.", "一件错投让整车白跑。"]] },
    reading: [["The HOA left flyers about bins.", "业主协会发了分类传单。"], ["Ana laminated one for the kitchen.", "安娜塑封一张贴厨房。"], ["Guests now ask before tossing.", "客人扔前先问了。"]],
    writing: { zh: "写一句你家的分类规则。", hintEn: "In our home, ___ goes in ___." } },
  { day: 146, titleEn: "Noise & Neighbors", titleZh: "第 146 天 · 邻里噪音", goalZh: "礼貌处理噪音投诉。",
    vocabIds: ["w:noise", "w:politely", "w:quietly", "w:feedback", "w:water"], grammarTopicId: "negation", phonicsRuleIds: ["oi", "ng"],
    pattern: { titleZh: "句型：Would you mind keeping it down after ten?", explainZh: "请求降噪 Would you mind + doing；升级前先友好沟通两次。",
      examples: [["Would you mind keeping music down after ten?", "十点后音乐小声点好吗？"], ["The walls are thinner than they look.", "墙比看起来薄。"], ["We didn't realize it carried so much.", "没想到声音传这么远。"]],
      sentences: [["A note works better than a bang.", "字条比敲门砸墙有效。"], ["Offer your number for future issues.", "留号码方便日后沟通。"], ["Quiet hours start at ten here.", "这里安静时间从十点开始。"]] },
    reading: [["Upstairs practiced drums at midnight.", "楼上半夜练鼓。"], ["Sam brought cookies and asked nicely.", "山姆带着饼干礼貌开口。"], ["Drum pads appeared by the weekend.", "周末楼上就换上了哑鼓垫。"]],
    writing: { zh: "写一句给邻居的友好提示。", hintEn: "Hi! Would you mind ___ after ___?" } },
  { day: 147, titleEn: "Public Library Gold", titleZh: "第 147 天 · 公共资源", goalZh: "介绍图书馆等免费公共资源。",
    vocabIds: ["w:borrow", "w:free", "w:book", "w:read", "w:learn"], grammarTopicId: "present-simple", phonicsRuleIds: ["bl", "ee"],
    pattern: { titleZh: "句型：The library offers free ___. / You can borrow ___.", explainZh: "公共资源句：offers free + 名词；借阅 borrow + 数量/期限。",
      examples: [["The library offers free English classes.", "图书馆提供免费英语课。"], ["You can borrow up to twenty books.", "最多可借二十本。"], ["Museum passes are loanable too.", "博物馆通票也能外借。"]],
      sentences: [["Librarians answer everything patiently.", "馆员耐心解答一切。"], ["Printing costs ten cents a page.", "打印一页十美分。"], ["Story hour fills up fast.", "故事会名额很快抢光。"]] },
    reading: [["The card took five minutes and zero dollars.", "办卡五分钟零美元。"], ["Wei borrowed test-prep books and a hotspot.", "小魏借了备考书和随身WiFi。"], ["His tax questions got a free workshop slot.", "税务问题还约到免费讲座。"]],
    writing: { zh: "写一句推荐别人用图书馆的话。", hintEn: "The library offers free ___ for ___." } },
  { day: 148, titleEn: "Emergency Drills", titleZh: "第 148 天 · 应急演练", goalZh: "描述应急流程与集合点。",
    vocabIds: ["w:first-aid", "w:emergency-room", "w:gathering", "w:book", "w:water"], grammarTopicId: "negation", phonicsRuleIds: ["ai", "st"],
    pattern: { titleZh: "句型：If the alarm sounds, we meet at ___. / Don't use the elevator.", explainZh: "应急句：If 火警响起, 集合点 meet at…；禁止乘电梯 Don't take the elevator。",
      examples: [["If the alarm sounds, meet at the flagpole.", "警报响起到旗杆集合。"], ["Don't take the elevator during a fire.", "火灾时别乘电梯。"], ["Know two exits from every room.", "每个房间记两条出口。"]],
      sentences: [["Practice makes evacuation calm.", "演练让撤离不慌。"], ["Keep shoes by the door at night.", "夜里在门口备鞋。"], ["Text your meeting point to family.", "把集合点发给家人。"]] },
    reading: [["The office drill finished in six minutes.", "公司演练六分钟完成。"], ["Everyone knew the two exits.", "每个人都知道两个出口。"], ["The marshal counted heads twice.", "安全员清点了两遍人数。"]],
    writing: { zh: "写一条你家的应急约定。", hintEn: "If ___, our family meets at ___." } },
  { day: 149, titleEn: "Holiday Plans", titleZh: "第 149 天 · 节假日安排", goalZh: "协商假期安排与家庭传统。",
    vocabIds: ["w:holiday", "w:tradition", "w:gathering", "w:thanksgiving-dinner", "w:friend"], grammarTopicId: "future-simple", phonicsRuleIds: ["ai", "ng"],
    pattern: { titleZh: "句型：Every year, we ___. / This year, let's ___.", explainZh: "传统用 Every year + 一般现在时；今年新意 This year, let's。",
      examples: [["Every year, we roast one giant turkey.", "每年我们烤一只大火鸡。"], ["This year, let's add a gratitude jar.", "今年加个感恩罐吧。"], ["Who's hosting this time?", "这次谁做东？"]],
      sentences: [["Travel peaks three days before.", "出行高峰提前三天。"], ["Potluck beats one exhausted cook.", "各带一道胜过一人累瘫。"], ["Traditions can evolve.", "传统也可以进化。"]] },
    reading: [["Thanksgiving rotated houses yearly.", "感恩节每年轮换东家。"], ["Cousins claimed the kids' table forever.", "表兄妹们永远占小孩桌。"], ["The gravy recipe stayed secret.", "肉汁秘方始终保密。"]],
    writing: { zh: "写一句你家节日传统或新提议。", hintEn: "Every year we ___; this year let's ___." } },
  { day: 150, titleEn: "Review: American Life", titleZh: "第 150 天 · 复习：美国生活", goalZh: "综合复习 131-149 天生活场景。",
    vocabIds: ["w:milestone", "w:confidence", "w:review", "w:practice-n", "w:progress-n"], grammarTopicId: "basic-clauses", phonicsRuleIds: ["ai", "er"],
    pattern: { titleZh: "句型：Living here taught me to ___.", explainZh: "生活复盘句 Living here taught me to + 动作。",
      examples: [["Living here taught me to read leases twice.", "在这里生活教会我租约读两遍。"], ["I learned to question every bill.", "我学会了核对每张账单。"], ["Neighbors became my best translators.", "邻居成了最好的翻译。"]],
      sentences: [["From bank accounts to boiler repairs,", "从银行开户到锅炉维修，"], ["each task started confusing,", "每件事起初都令人困惑，"], ["then turned into a story worth telling.", "后来都变成值得讲的故事。"]] },
    reading: [["From bank accounts to boiler repairs,", "从银行开户到锅炉维修，"], ["each task started confusing,", "每件事起初都令人困惑，"], ["then turned into a story worth telling.", "后来都变成值得讲的故事。"]],
    writing: { zh: "写两句这五十天最实用的一项生存技能。", hintEn: "I learned to ___, and it helped when ___." } },
];
