import type { CourseDayPlan } from "@/content/pipeline/generate-days";

/** Day 138-150 真实美国生活深化. */
export const PLAN_138_150: readonly CourseDayPlan[] = [
  { day: 138, titleEn: "Rental Disputes", titleZh: "第 138 天 · 租房纠纷处理", goalZh: "就押金/维修分歧据理力争。",
    vocabIds: ["w:security-deposit-refund", "w:owner", "w:evidence", "w:lawsuit", "w:inform"], grammarTopicId: "basic-clauses", phonicsRuleIds: ["ee", "sh"],
    pattern: { titleZh: "句型：According to the lease, ___. / I'd like this in writing.", explainZh: "引用条款 According to the lease…；关键承诺要求书面 in writing。",
      examples: [["According to the lease, you have thirty days.", "按租约，您有三十天。"], ["I'd like your answer in writing, please.", "请书面答复。"], ["The mold was here before I moved in.", "霉斑在我入住前就有。"]],
      sentences: [["Small claims court is the last step.", "小额法庭是最后一步。"], ["Keep every email and photo.", "保留所有邮件与照片。"], ["Stay calm; facts win.", "保持冷静，事实说话。"]] },
    reading: [["Ana's deposit was withheld for stains.", "安娜的押金被以污渍为由扣下。"], ["Her move-in photos proved otherwise.", "入住照片证明事实相反。"], ["Full refund arrived in nine days.", "九天后全额退款到账。"]],
    writing: { zh: "写一句援引租约的交涉用语。", hintEn: "According to the lease, ___. Please respond in writing." } },
  { day: 139, titleEn: "Work-Life Balance", titleZh: "第 139 天 · 工作生活平衡", goalZh: "谈论边界与恢复时间。",
    vocabIds: ["w:overtime", "w:hobby", "w:routine", "w:relax", "w:weekend"], grammarTopicId: "basic-clauses", phonicsRuleIds: ["ai", "ng"],
    pattern: { titleZh: "句型：I stop working at ___. / ___ helps me recharge.", explainZh: "设边界句 I stop X at TIME；恢复说 recharge。",
      examples: [["I stop working at six, mostly.", "我基本六点停工。"], ["Weekends help me recharge.", "周末帮我充电。"], ["No email after dinner — my rule.", "晚饭后不看邮件——我的规矩。"]],
      sentences: [["Balance looks different for everyone.", "平衡因人而异。"], ["Burnout costs more than rest.", "倦怠的代价比休息高。"], ["Protect one full day off.", "保护一整个休息日。"]] },
    reading: [["Ravi turned off work chat at seven.", "拉维七点关掉工作群。"], ["His first week felt anxious.", "第一周他很不适应。"], ["By week three, sleep improved.", "第三周睡眠明显变好。"]],
    writing: { zh: "写一句你的下班边界规则。", hintEn: "After ___, I ___. It helps me ___." } },
  { day: 140, titleEn: "Banking Deep Dive", titleZh: "第 140 天 · 银行金融深入", goalZh: "咨询理财产品与风险表达。",
    vocabIds: ["w:investment", "w:risk", "w:vary", "w:savings-account-n2", "w:consultant"], grammarTopicId: "questions", phonicsRuleIds: ["ai", "st"],
    pattern: { titleZh: "句型：What are the risks of ___? / I'd like low-risk options.", explainZh: "问风险 What are the risks of…？低风险产品说 low-risk options。",
      examples: [["What are the risks of this fund?", "这只基金有什么风险？"], ["I'd like lower-risk options, please.", "请给我低风险的选项。"], ["How liquid is this account?", "这个账户流动性如何？"]],
      sentences: [["Never invest money you need soon.", "近期要用的钱不要投资。"], ["Spread money across accounts.", "把钱分散存放。"], ["Ask about fees before returns.", "先问费用再谈收益。"]] },
    reading: [["Grandma split savings three ways.", "奶奶把储蓄分成三份。"], ["Emergency fund, vacation jar, quiet index fund.", "应急金、旅行罐、安静的指数基金。"], ["Boring worked for forty years.", "这套无聊办法用了四十年。"]],
    writing: { zh: "写一句向银行经理的提问。", hintEn: "What are the fees and risks of ___?" } },
  { day: 141, titleEn: "Health Insurance Basics", titleZh: "第 141 天 · 医保入门", goalZh: "看懂保险术语并选择计划。",
    vocabIds: ["w:insurance", "w:cover", "w:health-plan", "w:fee", "w:doctor"], grammarTopicId: "countable-uncountable", phonicsRuleIds: ["ai", "th-vl"],
    pattern: { titleZh: "句型：Does this plan cover ___? / What's my copay?", explainZh: "三词定医保：月费、起付线、每次自付 copay。",
      examples: [["Does this plan cover dental?", "这个计划含牙科吗？"], ["What's my copay for specialists?", "专科自付是多少？"], ["The deductible resets in January.", "起付线一月重置。"]],
      sentences: [["In-network doctors cost less.", "网络内医生更便宜。"], ["Ask for the drug formulary list.", "索要药品目录。"], ["Open enrollment ends in December.", "开放注册十二月截止。"]] },
    reading: [["Two plans, one question: how often do you go?", "两个计划一个问题：就医频率？"], ["Frequent visits favor higher monthly fees.", "常看病适合高月费计划。"], ["Healthy years favor high deductibles.", "健康年份适合高起付线。"]],
    writing: { zh: "写一句比较两个医保计划的问句。", hintEn: "Does plan A cover ___ with a lower copay?" } },
  { day: 142, titleEn: "Medical Bills", titleZh: "第 142 天 · 医疗账单", goalZh: "核对账单、申诉错误收费。",
    vocabIds: ["w:bill", "w:fee", "w:detail", "w:insurance", "w:phone"], grammarTopicId: "negation", phonicsRuleIds: ["ai", "sh"],
    pattern: { titleZh: "句型：I was billed twice for ___. / Please send an itemized bill.", explainZh: "对账单异议：被重复计费 billed twice；索要明细 itemized bill。",
      examples: [["I was billed twice for the X-ray.", "X光我被收了两次费。"], ["Please send an itemized bill.", "请寄送账单明细。"], ["My insurance should cover this visit.", "这次就诊保险应覆盖。"]],
      sentences: [["Dispute in writing, always.", "申诉务必书面。"], ["Billing errors are common.", "账单错误很常见。"], ["Politely persistent wins.", "礼貌而坚持者赢。"]] },
    reading: [["Ken's bill tripled the estimate.", "肯的账单是估价的三倍。"], ["One phone call found a coding error.", "一个电话发现录入编码错误。"], ["Corrected bill: zero dollars owed.", "修正后应付：零元。"]],
    writing: { zh: "写一句账单异议的开头。", hintEn: "I'm disputing a charge for ___ on ___." } },
  { day: 143, titleEn: "Community Volunteering", titleZh: "第 143 天 · 社区志愿", goalZh: "报名志愿活动并描述职责。",
    vocabIds: ["w:volunteer", "w:donate", "w:shift", "w:neighborhood", "w:join"], grammarTopicId: "future-simple", phonicsRuleIds: ["v", "sh"],
    pattern: { titleZh: "句型：I signed up for ___. / Can I take the ___ shift?", explainZh: "报名 sign up for；认领班次 take the morning shift。",
      examples: [["I signed up for Saturday cleanup.", "我报了周六清扫。"], ["Can I take the morning shift?", "我能上早班吗？"], ["We sort donations at ten.", "我们十点分拣捐赠品。"]],
      sentences: [["Volunteering builds real friendships.", "志愿服务结下真友谊。"], ["Bring gloves and water.", "带手套和水。"], ["Every hour counts.", "每一小时都算数。"]] },
    reading: [["The food bank needed two drivers.", "食物银行缺两名司机。"], ["Mina recruited her carpool group.", "米娜拉上了拼车小组。"], ["Saturday routes doubled capacity.", "周六运力翻倍。"]],
    writing: { zh: "写一句报名志愿活动的话。", hintEn: "I signed up for ___ on ___." } },
];
