import type { CourseDayPlan } from "@/content/pipeline/generate-days";

/** Phase 10-B · Day 161-170 Real American Life Advanced（真实美国生活·进阶）. */
export const PLAN_161_170: readonly CourseDayPlan[] = [
  {
    day: 161,
    titleEn: "Health Insurance Calls",
    titleZh: "第 161 天 · 医疗保险沟通",
    goalZh: "就保险覆盖范围与客服有效沟通。",
    vocabIds: [
      "w:premium-monthly-payment",
      "w:deductible-plan-details",
      "w:insurance-claim-medical-bill",
      "w:prescription-drug-cost",
      "w:referral-specialist-letter",
    ],
    grammarTopicId: "questions",
    phonicsRuleIds: ["ai", "sh"],
    pattern: {
      titleZh: "句型：Does my plan cover ___? / What's my deductible for ___?",
      explainZh: "保险电话三问：问覆盖 Does my plan cover…；问免赔 What's my deductible；要书面确认 Could you email that in writing?",
      examples: [
        ["Does my plan cover physical therapy?", "我的计划包含物理治疗吗？"],
        ["What's my deductible for specialist visits?", "专科门诊的免赔额是多少？"],
        ["Could you email me the coverage details in writing?", "能把保障细节用邮件发我吗？"],
      ],
      sentences: [
        ["Get names and reference numbers.", "记下姓名和案件号。"],
        ["Denials can be appealed in thirty days.", "拒赔可在三十天内申诉。"],
        ["Read the summary of benefits twice.", "福利摘要要读两遍。"],
      ],
    },
    reading: [
      ["Lena's claim was denied by mistake.", "莉娜的理赔被错误拒绝了。"],
      ["She called with her member ID ready.", "她备好会员号致电。"],
      ["The rep reversed it within one call.", "客服一通电话就撤销了拒赔。"],
    ],
    writing: { zh: "写一句你要问保险公司的关键问题。", hintEn: "Does my plan cover ___? / What's my deductible for ___?" },
  },
  {
    day: 162,
    titleEn: "Hospital Bill Problems",
    titleZh: "第 162 天 · 医院账单问题",
    goalZh: "核对医院账单并协商费用。",
    vocabIds: [
      "w:emergency-room-visit",
      "w:bill-pay-deadline",
      "w:monthly-payment-plan",
      "w:late-fee-waiver",
      "w:bank-statement",
    ],
    grammarTopicId: "past-simple",
    phonicsRuleIds: ["sh", "ch"],
    pattern: {
      titleZh: "句型：I'd like an itemized bill, please. / This charge looks incorrect.",
      explainZh: "账单维权：先要明细 itemized bill；再指出错误 This charge looks incorrect；最后谈方案 payment plan。",
      examples: [
        ["I'd like an itemized bill for my visit.", "请给我这次就诊的账单明细。"],
        ["This charge looks incorrect — I never saw that specialist.", "这笔收费有问题，我没看过那个专科。"],
        ["Can we set up a zero-interest payment plan?", "我们能定一个无息分期付款计划吗？"],
      ],
      sentences: [
        ["Billing errors are common; disputes work.", "账单错误很常见，申诉有用。"],
        ["Ask about financial assistance early.", "尽早询问财务援助。"],
        ["Never ignore a bill you dispute.", "有争议的账单千万别不理。"],
      ],
    },
    reading: [
      ["Omar's bill doubled overnight.", "奥马尔的账单一夜翻倍。"],
      ["The itemized version showed a double charge.", "明细单显示一笔重复收费。"],
      ["The hospital corrected it and apologized.", "医院更正并致歉。"],
    ],
    writing: { zh: "写一句你就争议收费的开场白。", hintEn: "I'm calling about a charge on my bill from ___." },
  },
  {
    day: 163,
    titleEn: "Government Services",
    titleZh: "第 163 天 · 政府服务沟通",
    goalZh: "办理证件与咨询政府服务流程。",
    vocabIds: [
      "w:bureaucracy-red-tape-complaints",
      "w:passport-renewal-line",
      "w:citizenship-naturalization-test",
      "w:municipality-city",
      "w:immigration-policy-debate",
    ],
    grammarTopicId: "present-progressive",
    phonicsRuleIds: ["gr", "st"],
    pattern: {
      titleZh: "句型：What documents do I need for ___? / Where do I submit ___?",
      explainZh: "政务办事两问：材料 What documents do I need for…；地点/流程 Where/How do I submit…。",
      examples: [
        ["What documents do I need for license renewal?", "换驾照需要哪些材料？"],
        ["Where do I submit the application form?", "申请表交到哪里？"],
        ["How long does processing usually take?", "一般处理要多久？"],
      ],
      sentences: [
        ["Bring copies; originals stay home safe.", "带复印件，原件留在家。"],
        ["Fees vary by county and service.", "费用因县和服务而异。"],
        ["Book morning appointments to skip lines.", "约早上的号少排队。"],
      ],
    },
    reading: [
      ["The DMV line moved slowly but surely.", "车管所的队伍慢而稳地前进。"],
      ["Mei had every document in one folder.", "小梅把所有材料放在一个文件夹。"],
      ["Her new license arrived within two weeks.", "两周内新驾照寄到。"],
    ],
    writing: { zh: "列出你最近一次办证需要的三份材料（英文）。", hintEn: "For ___, I need ___, ___, and ___." },
  },
  {
    day: 164,
    titleEn: "Tax Basics",
    titleZh: "第 164 天 · 税务基础问题",
    goalZh: "理解报税关键词并寻求帮助。",
    vocabIds: [
      "w:tax-season-document-scavenger-hunt-annual-tradition",
      "w:refund",
      "w:budget-deficit-spending-plan",
      "w:wage-stagnation-debate",
      "w:net-income-calc",
    ],
    grammarTopicId: "present-simple",
    phonicsRuleIds: ["ai", "st"],
    pattern: {
      titleZh: "句型：Am I eligible for ___? / When will I get my refund?",
      explainZh: "报税两句：问资格 Am I eligible for…；问进度 When will I get my refund。听不懂就请对方换个说法。",
      examples: [
        ["Am I eligible for the child tax credit?", "我有资格享受儿童税收抵免吗？"],
        ["When will I get my refund this year?", "今年退款什么时候到？"],
        ["Could you explain that in simpler terms?", "能说得简单点吗？"],
      ],
      sentences: [
        ["Free filing help exists at libraries.", "图书馆有免费报税协助。"],
        ["Keep every form until next spring.", "所有表单留到明年春天。"],
        ["Deadlines in April sneak up fast.", "四月截止日来得飞快。"],
      ],
    },
    reading: [
      ["Tomas filed early this year.", "托马斯今年早早报了税。"],
      ["A library volunteer checked his deductions.", "图书馆志愿者帮他核对了抵扣项。"],
      ["His refund landed in nine days.", "退款九天到账。"],
    ],
    writing: { zh: "写一句你今年报税最想搞懂的问题。", hintEn: "Am I eligible for ___? / When will I get my refund?" },
  },
  {
    day: 165,
    titleEn: "Banking Issues Solved",
    titleZh: "第 165 天 · 银行账户问题解决",
    goalZh: "处理银行账户异常与费用争议。",
    vocabIds: [
      "w:charge",
      "w:credit-card",
      "w:wire-transfer-fee",
      "w:online-banking-app",
      "w:identity-theft-protection",
    ],
    grammarTopicId: "negation",
    phonicsRuleIds: ["fl", "oi"],
    pattern: {
      titleZh: "句型：I see a charge I didn't make. / Could you waive this fee?",
      explainZh: "银行维权：欺诈 I see a charge I didn't make；减免费用 Could you waive this fee；语气坚定但礼貌。",
      examples: [
        ["I see a charge I didn't make on Saturday.", "我看到一笔周六不是本人消费的扣款。"],
        ["Could you waive the overdraft fee this once?", "这次透支费能免掉吗？"],
        ["Please freeze the card and send a new one.", "请冻结这张卡并补寄新卡。"],
      ],
      sentences: [
        ["Report fraud within two business days.", "欺诈要在两个工作日内上报。"],
        ["Polite firmness gets fees waived.", "礼貌的坚持能让费用被免除。"],
        ["Check statements monthly, minimum.", "对账单至少每月查一次。"],
      ],
    },
    reading: [
      ["A $900 charge appeared at 3 a.m.", "凌晨三点出现一笔九百美元消费。"],
      ["Nina froze her card from the app.", "妮娜在应用里一键冻结。"],
      ["The bank refunded everything by Friday.", "银行周五前全额退回。"],
    ],
    writing: { zh: "写一句向银行报告可疑扣款的话。", hintEn: "I see a charge I didn't make on ___." },
  },
  {
    day: 166,
    titleEn: "Rental Disputes",
    titleZh: "第 166 天 · 租房纠纷处理",
    goalZh: "依法沟通租房维修押金纠纷。",
    vocabIds: [
      "w:security-deposit-refund",
      "w:renters-insurance-policy",
      "w:contract-breach-clause",
      "w:utility-bills-online",
      "w:rent",
    ],
    grammarTopicId: "future-simple",
    phonicsRuleIds: ["l", "ar"],
    pattern: {
      titleZh: "句型：My lease says ___. / Could you repair ___ by ___?",
      explainZh: "租房沟通：拿租约说话 My lease says…；维修请求给出期限 Could you repair… by…；一切留书面。",
      examples: [
        ["My lease says the deposit returns within thirty days.", "我的租约写着押金三十天内退还。"],
        ["Could you repair the heater by Friday?", "周五前能修好暖气吗？"],
        ["I'll send this request in writing as well.", "我也会把请求以书面形式发送。"],
      ],
      sentences: [
        ["Written notices protect both sides.", "书面通知保护双方。"],
        ["Document problems with dated photos.", "给问题拍照并标注日期。"],
        ["Courts favor tenants with paper trails.", "法庭偏爱有证据链的租客。"],
      ],
    },
    reading: [
      ["The heater died during a cold snap.", "寒潮里暖气罢工。"],
      ["Leo texted, then mailed a formal notice.", "利奥先发短信，再寄正式通知。"],
      ["A contractor came within three days.", "三天内承包商上门。"],
    ],
    writing: { zh: "写一句关于维修请求的书面通知。", hintEn: "Could you repair ___ by ___? Please reply in writing." },
  },
  {
    day: 167,
    titleEn: "Feedback Meetings",
    titleZh: "第 167 天 · 工作反馈会议",
    goalZh: "在绩效面谈中接收与给予反馈。",
    vocabIds: [
      "w:performance-review-anxiety-season",
      "w:feedback-sandwich-vs-direct-style",
      "w:promotion-cycle-wait-time",
      "w:manager-one-on-one-notes",
      "w:kpi-dashboard-metric-tracking",
    ],
    grammarTopicId: "basic-clauses",
    phonicsRuleIds: ["ee", "l"],
    pattern: {
      titleZh: "句型：Could you give me an example? / Going forward, I will ___.",
      explainZh: "反馈会议：听不懂例子就问 Could you give me an example；收尾承诺 Going forward, I will…。",
      examples: [
        ["Could you give me a specific example?", "能给我一个具体例子吗？"],
        ["Going forward, I will share drafts earlier.", "今后我会更早分享草稿。"],
        ["What would success look like next quarter?", "下季度的成功标准是什么？"],
      ],
      sentences: [
        ["Take notes; feelings fade, notes don't.", "做笔记，情绪会淡，笔记不会。"],
        ["Ask for metrics behind adjectives.", "追问形容词背后的指标。"],
        ["One commitment beats ten apologies.", "一个承诺胜过十次道歉。"],
      ],
    },
    reading: [
      ["Ravi's review started tense.", "拉维的评估开局紧张。"],
      ["He asked for examples instead of labels.", "他要例子而不是贴标签。"],
      ["They left with a clear growth plan.", "结束时两人有了清晰的成长计划。"],
    ],
    writing: { zh: "写下你在下次一对一里想问的一个问题。", hintEn: "Could you give me an example of ___?" },
  },
  {
    day: 168,
    titleEn: "Career Growth Talks",
    titleZh: "第 168 天 · 职业发展讨论",
    goalZh: "与上级规划晋升路径与学习目标。",
    vocabIds: [
      "w:strategy-quarterly-roadmap-review",
      "w:mentor-guidance-career-ladder",
      "w:internship-summer-program-slot",
      "w:orientation-first-week-checklist",
      "w:resignation-two-weeks-notice-letter",
    ],
    grammarTopicId: "future-simple",
    phonicsRuleIds: ["gr", "ee"],
    pattern: {
      titleZh: "句型：I'd like to grow toward ___. / What skills should I build?",
      explainZh: "职业对话：表达方向 I'd like to grow toward…；请教路径 What skills should I build…。",
      examples: [
        ["I'd like to grow toward a team lead role.", "我想朝团队负责人方向发展。"],
        ["What skills should I build this year?", "今年我该修炼哪些技能？"],
        ["Who should I shadow to learn faster?", "我可以跟谁学习来加速成长？"],
      ],
      sentences: [
        ["Ambition lands better with a plan.", "有计划的野心更容易被接受。"],
        ["Ask for projects, not just titles.", "要项目机会，而不只是头衔。"],
        ["Mentors shorten every detour.", "导师缩短每一次弯路。"],
      ],
    },
    reading: [
      ["Dana mapped her five-year path.", "丹娜画出五年路线图。"],
      ["Her manager suggested two internal projects.", "经理推荐了两个内部项目。"],
      ["A mentor signup opened that week.", "那周导师报名恰好开放。"],
    ],
    writing: { zh: "用 I'd like to grow toward ___ 写一句你的职业方向。", hintEn: "I'd like to grow toward ___." },
  },
  {
    day: 169,
    titleEn: "Formal Complaints & Resolutions",
    titleZh: "第 169 天 · 正式投诉和解决方案",
    goalZh: "撰写正式投诉并提出解决方案。",
    vocabIds: [
      "w:settlement-out-of-court-agreement",
      "w:regulation-compliance-audit",
      "w:consumer-confidence-index-drop",
      "w:lawsuit-class-action-filing",
      "w:attorney-defense-team",
    ],
    grammarTopicId: "countable-uncountable",
    phonicsRuleIds: ["pl", "ai"],
    pattern: {
      titleZh: "句型：I am writing to file a complaint about ___. / A fair resolution would be ___.",
      explainZh: "投诉信公式：开头 I am writing to file a complaint about…；中间事实按时间排；结尾提出公平解法 A fair resolution would be…。",
      examples: [
        ["I am writing to file a complaint about order #4512.", "我写信是为了投诉订单 4512。"],
        ["Despite three calls, the issue remains unresolved.", "尽管打了三次电话，问题仍未解决。"],
        ["A fair resolution would be a full refund.", "合理的解决方式是全额退款。"],
      ],
      sentences: [
        ["State facts; skip fury.", "陈述事实，省略怒火。"],
        ["Attach receipts and dates.", "附上收据与日期。"],
        ["Set a reply deadline politely.", "礼貌设定期限。"],
      ],
    },
    reading: [
      ["Grace's router died within warranty.", "格蕾丝的路由器在保修期内坏了。"],
      ["Her letter listed dates, not emotions.", "她的信列的是日期而非情绪。"],
      ["A replacement arrived before the deadline she set.", "在她设定期限前新机已寄到。"],
    ],
    writing: { zh: "写一句投诉信的开头与一句期望的解决方案。", hintEn: "I am writing to file a complaint about ___; a fair resolution would be ___." },
  },
  {
    day: 170,
    titleEn: "Review: American Life Simulation",
    titleZh: "第 170 天 · 综合模拟：美国生活",
    goalZh: "综合模拟 161-169 天的真实生活场景。",
    vocabIds: [
      "w:insurance-claim-medical-bill",
      "w:bureaucracy-red-tape-complaints",
      "w:online-banking-app",
      "w:security-deposit-refund",
      "w:settlement-out-of-court-agreement",
    ],
    grammarTopicId: "basic-clauses",
    phonicsRuleIds: ["er", "ai"],
    pattern: {
      titleZh: "句型：First I ___, then I ___, and finally ___.",
      explainZh: "流程复述：First… then… finally… 把一次完整维权/办事经历讲清楚。",
      examples: [
        ["First I gathered every document, then I called, and finally I confirmed in writing.", "我先收集全部材料，然后打电话，最后书面确认。"],
        ["First I checked the bill, then I disputed it online.", "我先核对账单，然后在线申诉。"],
        ["First I read the lease, then I asked questions.", "我先读租约，再提问。"],
      ],
      sentences: [
        ["Simulations turn panic into procedure.", "模拟把慌张变成流程。"],
        ["Paper trails win long games.", "书面记录赢得长期战役。"],
        ["You now speak 'adult admin' fluently.", "你现在能流利说“成年人事务英语”了。"],
      ],
    },
    reading: [
      ["The final simulation ran forty minutes.", "最终模拟持续四十分钟。"],
      ["Teams rotated through four service desks.", "小组轮转四个服务台。"],
      ["Everyone left with a personal checklist.", "每个人都带着个人清单离开。"],
    ],
    writing: { zh: "用 First… then… finally… 复盘一次你办成的难事。", hintEn: "First I ___, then I ___, and finally ___." },
  },
];
