import type { CourseDayPlan } from "@/content/pipeline/generate-days";

/**
 * Phase 23 · Day 331-360 — Block F 综合进阶与毕业（Synthesis & Graduation）。
 * B2→C2 收官：跨模块整合、毕业演讲、路演、谈判复盘、媒体未来主义、
 * AI 时代决策、韧性收束、正式评估与结业。全部引用真实词汇。
 */
export const PLAN_331_360: readonly CourseDayPlan[] = [
  {
    day: 331,
    titleEn: "Capstone Foundations",
    titleZh: "第 331 天 · 毕业项目地基",
    goalZh: "为 360 天收官的毕业项目定下范围、里程碑与交付物。",
    vocabIds: ["w:project-based-learning", "w:scope", "w:scope-creep", "w:master-plan", "w:ipo-going-public-milestone-day"],
    grammarTopicId: "future-simple",
    phonicsRuleIds: ["ee", "st", "ai"],
    pattern: {
      titleZh: "句型：My capstone compresses six months into one pitch. / The first milestone is ___.",
      explainZh: "毕业项目三问：范围 what is the scope?;里程碑 the first milestone is…;交付 what is the deliverable?。把 30 天的学练压缩成一段能讲的成与败。",
      examples: [
        ["My capstone compresses six months into one pitch.", "我的毕业专题把六个月压进一段演讲。"],
        ["The first milestone is choosing the case study.", "第一个里程碑是选定案例。"],
        ["The deliverable is a ten-minute talk and a one-page memo.", "交付物是十分钟演讲和一张纸的备忘录。"],
      ],
      sentences: [
        ["The scope prefix sets what the project does not cover.", "范围前缀规定了项目不做什么。"],
        ["Milestones turn a mountain into a staircase.", "里程碑把山脉变成台阶。"],
        ["Course of the whole year narrows into one question here.", "全年课程在这里收拢成一个问题。"],
      ],
    },
    reading: [
      ["The capstone took the whole year of threads back up.", "毕业专题把全年线索重新拾起。"],
      ["A clear scope saved the final two weeks of drift.", "清晰的范围省下了最后两周的漂移。"],
      ["The one-page memo outlived the hundred slides.", "一张纸的备忘录活得比一百页幻灯片久。"],
    ],
    writing: { zh: "写毕业项目：范围、里程碑、交付物各一行。", hintEn: "Scope: ___. Milestone: ___. Deliverable: ___." },
  },
  {
    day: 332,
    titleEn: "Presentation Architecture",
    titleZh: "第 332 天 · 演讲构架",
    goalZh: "用开场、三段、钩尾为演讲搭骨架。",
    vocabIds: ["w:stage-fright-cold-hands-cure", "w:pitch", "w:retirement-party-speech-length-versus-memory-span-study", "w:persuasion-ethos-pathos-logos-triangle", "w:eloquent-speeches-quote-worthy-sentences"],
    grammarTopicId: "present-simple",
    phonicsRuleIds: ["ee", "st", "ai"],
    pattern: {
      titleZh: "句型：Open with the problem; close with the ask. / The three-minute story needs one number.",
      explainZh: "演讲骨架：开场 problem,收尾 ask;三段 ethos, pathos, logos;数据 one number。观众记住的是钩子，不是字幕。",
      examples: [
        ["Open with the problem; close with the loan ask.", "用问题开头，用请求结尾。"],
        ["The three-minute story needs one number that hurts.", "三分钟的故事需要一个扎心的数字。"],
        ["Ethos lends trust; pathos lends urgency; logos lends proof.", "可信度给信任，情感给紧迫，逻辑给证据。"],
      ],
      sentences: [
        ["The first thirty seconds decide the next twenty minutes.", "头三十秒决定接下来二十分钟。"],
        ["Engagement is heard in the pause, not the applause.", "投入度听在停顿里，不在掌声里。"],
        ["Practice changes the script into a voice.", "练讲把稿子变成声音。"],
      ],
    },
    reading: [
      ["The strong opening gave the whole talk a spine.", "有力的开场给了整场演讲一根脊梁。"],
      ["One painful number outlasted three pretty charts.", "一个扎心的数字比三张漂亮图表更持久。"],
      ["Audience engagement rose when the talk got one eye contact at a time.", "逐个眼神接触后，观众投入度上升了。"],
    ],
    writing: { zh: "为你的演讲写开场问题与收尾请求。", hintEn: "H0: ___. Ask: ___. Story number: ___." },
  },
  {
    day: 333,
    titleEn: "Story Data, Data Story",
    titleZh: "第 333 天 · 把数据讲成故事",
    goalZh: "给每张图表配一句人话与一个因果。",
    vocabIds: ["w:storyboarding", "w:narrative-theory", "w:correlation", "w:evidence-based-practice", "w:citation-format"],
    grammarTopicId: "past-simple",
    phonicsRuleIds: ["ee", "st", "ai"],
    pattern: {
      titleZh: "句型：The chart narrates; the axis confesses. / The effect came from the policy, not the correlation.",
      explainZh: "数据故事两戒：图表 is a narrator, its axis confesses the cut;因果 区分 correlation 与 causation。引用格式 citation-format 让每格数字有出处。",
      examples: [
        ["The chart narrates; the axis confesses the scale.", "图表叙述，坐标轴供出刻度。"],
        ["The effect came from the policy, not from the correlation alone.", "效果来自政策，不单来自相关。"],
        ["Every data slide carries a citation in small print.", "每页数据幻灯片下方都有小字引用。"],
      ],
      sentences: [
        ["A good data story names the person inside the number.", "好的数据故事说出数字里的人。"],
        ["Confidence comes from the source line, not the bar height.", "信心来自出处行，不来自柱高。"],
        ["Evidence-based practice begins with a falsifiable sentence.", "循证实践从一句可证伪的话开始。"],
      ],
    },
    reading: [
      ["The narrating chart told why; the table proved how.", "会叙事的图说为什么，表格证明怎么做。"],
      ["A missing citation turned a proud stat into a rumor.", "一个缺失的引用把自豪的统计变成谣言。"],
      ["The person inside the metric changed the board's mind.", "指标里的人改变了董事会的态度。"],
    ],
    writing: { zh: "选一个数据点写：图表说什么、谁在数字里。", hintEn: "Chart: ___. Person: ___. Source: ___." },
  },
  {
    day: 334,
    titleEn: "Handling Q&A Fire",
    titleZh: "第 334 天 · 问答火力",
    goalZh: "用转接与证据应对刁钻提问。",
    vocabIds: ["w:improvisation-art", "w:rebuttal-n2", "w:evidence-based-policy", "w:peer-review", "w:self-assessment"],
    grammarTopicId: "questions",
    phonicsRuleIds: ["ee", "st", "ai"],
    pattern: {
      titleZh: "句型：Let me reframe that as the cost question. / The hardest objection is the one I quote back.",
      explainZh: "问答三招：转接 let me reframe that as…;引用 objection 复核 quote it back;认错边界 the honest gap is…。卡住就用对手的话重新定义问题。",
      examples: [
        ["Let me reframe that as the cost question, not the design one.", "我把这个问题重构成成本问题，而非设计问题。"],
        ["The hardest objection is the one I quote back before I answer.", "最难的反驳是我先原话复述再作答的那种。"],
        ["The honest gap between expectation and evidence is small here.", "这里期望与证据之间的诚实缺口很小。"],
      ],
      sentences: [
        ["A tight answer beats a fast one every time.", "严谨的回答每次都胜过快速回答。"],
        ["Self-assessment after the session finds the weak slide.", "会后自评会找到薄弱那页。"],
        ["Peer review turns the audience into co-authors.", "同行评审让听众变成合著者。"],
      ],
    },
    reading: [
      ["The reframe stopped a rabbit-hole cold.", "重构当场把钻牛角尖的讨论闷熄。"],
      ["Quoting the objection back earned the room's respect.", "原话复述质疑赢得现场尊重。"],
      ["Post-session self-assessment cut the next talk's weakest third.", "会后自评砍掉下场的薄弱三分之一。"],
    ],
    writing: { zh: "写下你最近一次被问倒的问题及重构答案。", hintEn: "Question: ___. Reframe: ___. Evidence: ___." },
  },
  {
    day: 335,
    titleEn: "Proposal & Persuasion Lab",
    titleZh: "第 335 天 · 提案与说服实验室",
    goalZh: "用证据链构建一份站得住脚的建议书。",
    vocabIds: ["w:quarterly-report-earnings-call", "w:master-plan", "w:counterclaim-integration", "w:persuasion", "w:peer-review-process"],
    grammarTopicId: "negation",
    phonicsRuleIds: ["ee", "st", "ai"],
    pattern: {
      titleZh: "句型：The summary carries the decision; the memo carries the proof. / What would change your recommendation?",
      explainZh: "说服构件：摘要 executive summary 给决定;路线图 roadmap 给过程;反证 counterargument 给诚实。写得出可被反驳的建议才站得住。",
      examples: [
        ["The summary carries the decision; the memo carries the proof.", "摘要托着决定，备忘录托着证据。"],
        ["What would change your recommendation within a quarter?", "一个季度内，什么能改变你的建议？"],
        ["The roadmap breaks the year into useful quarters.", "路线图把一年切成分工明确的季度。"],
      ],
      sentences: [
        ["Persuasion is the art of the highway, not the unarmed argument.", "说服是铺路术，不是赤手空拳的争辩。"],
        ["A named failure mode makes the proposal honest.", "点名一个失败模式让提案变得诚实。"],
        ["Peer review reassembles the noise into structure.", "同行评审把噪音重新拼成结构。"],
      ],
    },
    reading: [
      ["The memo did what the slides could not: decide.", "备忘录做到幻灯片做不到的事：做决定。"],
      ["Naming the failure mode saved the quarter.", "点名失败模式救了这一个季度。"],
      ["A rival peer review improved the final wording.", "一次敌意式同行评审改进了最终措辞。"],
    ],
    writing: { zh: "写一句话建议书：主张、理由、失败模式。", hintEn: "Claim: ___. Reason: ___. Failure mode: ___." },
  },
  {
    day: 336,
    titleEn: "Voice & Body Rehearsal",
    titleZh: "第 336 天 · 声音与形体排练",
    goalZh: "练节奏、停顿、眼神与手的三个站位。",
    vocabIds: ["w:magic-tricks-card-palm-practice-invisible-audiences", "w:stage-fright-cold-hands-cure", "w:posture", "w:speech-prosody", "w:authenticity"],
    grammarTopicId: "articles",
    phonicsRuleIds: ["ee", "st", "ai"],
    pattern: {
      titleZh: "句型：The pause is a paragraph; the pace is a mute proof. / Cold hands warm up on the first laugh.",
      explainZh: "形体三件套：停顿 pause 是段落;节奏 pace 证明底气;手势 gesture 只在句点处给一个。紧张首招是承认紧张。",
      examples: [
        ["The pause is a paragraph; the pace is a mute proof.", "停顿是一个段落，节奏是无言的证据。"],
        ["Cold hands warm up on the first laugh from the room.", "冰冷的手在观众第一声笑里回暖。"],
        ["Authenticity in voice beats polished formula.", "声音里的真切胜过打磨过的公式。"],
      ],
      sentences: [
        ["Rehearsal is the honest bridge between script and self.", "排练是稿子与自我之间的诚实桥梁。"],
        ["The crossed-arms myth was decoded: it is comfort, not war.", "抱臂神话被解码：那是舒服，不是敌对。"],
        ["Three standing positions beat thirty gestures.", "三个站位胜过三十个手势。"],
      ],
    },
    reading: [
      ["The run-through schedule saved the dead third act.", "排练日程拯救了死掉的第三幕。"],
      ["Naming the stage fright as a fact dissolved half of it.", "把怯场称为一个事实，就消解了一半。"],
      ["The rehearsed pause landing exactly where the script ached.", "排练过的停顿正好落在稿子疼的地方。"],
    ],
    writing: { zh: "写排练单：两个停顿点、一个手势、一个语气。", hintEn: "Pause at: ___. Gesture: ___. Tone: ___." },
  },
  {
    day: 337,
    titleEn: "Feedback Into Gold",
    titleZh: "第 337 天 · 把反馈锻成金",
    goalZh: "把同伴意见分类成修改、保留与放弃。",
    vocabIds: ["w:feedback-loop", "w:feedback-loop-fast-course-correction-culture", "w:critique-balanced-review-essay", "w:peer-feedback-incorporation", "w:proofread-typo-assassin-final-gate-duty"],
    grammarTopicId: "prepositions-basic",
    phonicsRuleIds: ["ee", "st", "ai"],
    pattern: {
      titleZh: "句型：Sort the notes into change, keep, and drop. / The loop closes when I speak the change back.",
      explainZh: "反馈三桶：改 change,留 keep,丢 drop;闭环 the loop closes when I speak the change back。收下前先听，改完再讲回去。",
      examples: [
        ["Sort the notes into change, keep, and drop.", "把意见分进改、留、丢三个桶。"],
        ["The loop closes when I speak the change back to the giver.", "当我把修改讲回给给建议的人，回路才关闭。"],
        ["Direct style wins in design reviews; sandwich wins with new members.", "设计评审里直接风格赢，新人那边三明治赢。"],
      ],
      sentences: [
        ["A fast course-correction culture outruns a perfect one.", "快速纠偏的文化跑赢完美的文化。"],
        ["Incorporation is a verb: it demands a draft tomorrow.", "整合是个动词：它要求明天就有一稿。"],
        ["Revision is where the good becomes the clear.", "修订是优秀变清晰的现场。"],
      ],
    },
    reading: [
      ["The three-bucket sort ended the feedback feud.", "三桶分类结束了关于反馈的争论。"],
      ["Speaking the change back built the loop in one week.", "把修改讲回去，一周就建起回路。"],
      ["The late draft revision saved the quarter's report.", "尾声的修改救了本季度的报告。"],
    ],
    writing: { zh: "列你的反馈三桶各两条。", hintEn: "Change: ___. Keep: ___. Drop: ___." },
  },
  {
    day: 338,
    titleEn: "Impromptu on Demand",
    titleZh: "第 338 天 · 即兴就绪",
    goalZh: "用一分钟模板应对任何无准备发言。",
    vocabIds: ["w:icebreaker-question", "w:skeptic-question-everything-first", "w:problem-solving-process", "w:issue-tree", "w:empathetic-listening-without-fixing-reflex"],
    grammarTopicId: "countable-uncountable",
    phonicsRuleIds: ["ee", "st", "ai"],
    pattern: {
      titleZh: "句型：What you’re really asking is the funding one. / One minute: point, example, ask.",
      explainZh: "即兴模板：点 point,例 example,求 ask。先复述 what you're really asking,再走模板，别假设已听懂。",
      examples: [
        ["What you are really asking is the funding question.", "你真正想问的是资金那个问题。"],
        ["One minute: point, example, ask, and stop.", "一分钟：观点、例子、请求、收口。"],
        ["Spontaneity is rehearsed flexibility, not luck.", "即兴是排练过的灵活，不是运气。"],
      ],
      sentences: [
        ["The best surprise answers assume a sharp question.", "最好的临场回答先假设一个锋利问题。"],
        ["Critical thinking begins by naming the actual question.", "批判性思维从点名真正的问题开始。"],
        ["Active listening fills the pause with the right answer.", "积极聆听用正确的答案填满停顿。"],
      ],
    },
    reading: [
      ["The one-minute template survived the ambush.", "一分钟模板扛住了突袭式问答。"],
      ["Restating the question halved the answering time.", "复述问题让答题时间减半。"],
      ["Rehearsed flexibility made the off-script part shine.", "排练过的灵活让脱稿部分发光。"],
    ],
    writing: { zh: "写一分钟即兴模板：点、例、求。", hintEn: "Point: ___. Example: ___. Ask: ___." },
  },
  {
    day: 339,
    titleEn: "Negotiation as Language",
    titleZh: "第 339 天 · 谈判即语言",
    goalZh: "把谈判词汇炼成立场与让步的句型。",
    vocabIds: ["w:anchoring-offer-tactic", "w:reservation-price-floor", "w:anchoring-adjustment-effect", "w:concession-rebuttal-structure", "w:negotiation-win-win-outcome-craft"],
    grammarTopicId: "pronouns-basic",
    phonicsRuleIds: ["ee", "st", "ai"],
    pattern: {
      titleZh: "句型：If you move on the fee, I can move on the term. / The anchor holds the whole conversation.",
      explainZh: "谈判句子：让步句 if you move on X, I can move on Y;锚点 the anchor holds…;共识 look-forward 把它引向关系。语言即筹码。",
      examples: [
        ["If you move on the fee, I can move on the term.", "你在费用上让步，我就在期限上让步。"],
        ["The anchor holds the whole conversation at its level.", "锚点把整场谈话钉在它的高度。"],
        ["A concession sequence buys the relationship, not the point.", "让步序列买的是关系，不是这点。"],
      ],
      sentences: [
        ["Reservation price is the floor your ego cannot lower.", "保留价是你自尊不能下调的地板。"],
        ["The tactic that works most nights is a patient pause.", "最常奏效的战术是耐心的停顿。"],
        ["Looking forward turns a closed table into an open door.", "向前看把关闭的谈判桌变成开着的门。"],
      ],
    },
    reading: [
      ["The adjustable anchor saved the midday call.", "可调整的锚点救了中午那通电话。"],
      ["The concession sequence bought a year of goodwill.", "让步序列买下了一年的善意。"],
      ["Moving on the term, not the fee, closed the deal.", "在期限而非费用上让步，成交了。"],
    ],
    writing: { zh: "写一让步句、一锚点、一句向前看。", hintEn: "If ___, then ___. Anchor: ___. Forward: ___." },
  },
  {
    day: 340,
    titleEn: "Growth Through Difficulty",
    titleZh: "第 340 天 · 在困难中成长",
    goalZh: "把失败和反馈译成成长型心态的句子。",
    vocabIds: ["w:growth-mindset", "w:growth-mindset-dweck", "w:resilience", "w:resilience-triangle", "w:grit-long-term-perseverance-trait"],
    grammarTopicId: "be-verb",
    phonicsRuleIds: ["ee", "st", "ai"],
    pattern: {
      titleZh: "句型：The failure is data, not a verdict. / My response to the plateau is the actual lesson.",
      explainZh: "成长两句：失败是数据 failure is data, not a verdict;平台期 response to the plateau is the lesson。韧性三角平衡支持、技能与挑战。",
      examples: [
        ["The failure is data, not a verdict on the person.", "失败是数据，不是对人的判决。"],
        ["My response to the plateau is the actual lesson.", "我对平台期的回应才是真正的课。"],
        ["Resilience arranges support, skill, and challenge into a triangle.", "韧性把支持、技能与挑战排成一个三角。"],
      ],
      sentences: [
        ["Dweck's words turned 'I can not' into 'not yet'.", "德韦克的话把我不行变成还没行。"],
        ["Persistence is the arithmetic of the long game.", "坚持是长局里的算术。"],
        ["The plateau is the stair landing, not the top.", "平台期是楼梯平台，不是顶层。"],
      ],
    },
    reading: [
      ["Naming the failure as data ended a month of self-blame.", "把失败称为数据，结束了一个月的自责。"],
      ["The not-yet sentence changed how the class took feedback.", "还没行这句话改变了全班接受反馈的方式。"],
      ["The resilience triangle balanced a breaking week.", "韧性三角稳住了一周的崩溃。"],
    ],
    writing: { zh: "写一次失败的数据解读与回应。", hintEn: "Failure: ___. Data: ___. Response: ___." },
  },
  {
    day: 341,
    titleEn: "Deep Work in English",
    titleZh: "第 341 天 · 用英语进入深度工作",
    goalZh: "用英文进行专注时段与任务分区。",
    vocabIds: ["w:deep-focus", "w:time-boxed-topic", "w:screen-time", "w:flow-state-optimal", "w:digital-wellness"],
    grammarTopicId: "present-simple",
    phonicsRuleIds: ["ee", "st", "ai"],
    pattern: {
      titleZh: "句型：Ninety minutes of English focus beat four distracted hours. / The phone earns the break.",
      explainZh: "深度英语三件套：时段 ninety minutes of focus;区隔 the phone is out of the room;奖励 breaks are earned。语言在专注时才会爬坡。",
      examples: [
        ["Ninety minutes of English focus beat four distracted hours.", "九十分钟的英语专注胜过四小时的分心。"],
        ["The phone stays outside the door and earns its break.", "手机待在门外，靠功劳换取休息。"],
        ["Notification fatigue made me batch the inbox.", "通知疲劳让我把收件箱改成批量处理。"],
      ],
      sentences: [
        ["Deep work is a habit with an alarm clock.", "深度工作是有闹钟的习惯。"],
        ["Time management is attention management in disguise.", "时间管理是化了装的注意力管理。"],
        ["A focus block with no goals is just a quiet hour.", "没有目标专注块只是一个安静小时。"],
      ],
    },
    reading: [
      ["The ninety-minute English block doubled speaking output.", "九十分钟英语专注把口语产出翻倍。"],
      ["Batching the inbox returned the deep hours.", "批量处理收件箱找回深度时段。"],
      ["The phone-exile rule survived a full course week.", "手机隔离规则撑过了完整一周课。"],
    ],
    writing: { zh: "写本周一个 90 分钟深度英语块的安排。", hintEn: "When: ___. Task: ___. Phone: ___." },
  },
  {
    day: 342,
    titleEn: "Peer Instruction",
    titleZh: "第 342 天 · 教是最好的学",
    goalZh: "用讲解、提问与互评把知识教给别人。",
    vocabIds: ["w:reciprocal-teaching", "w:pedagogy-teaching", "w:socratic-questioning-method", "w:empathetic-listening-without-fixing-reflex", "w:peer-feedback-incorporation"],
    grammarTopicId: "future-simple",
    phonicsRuleIds: ["ee", "st", "ai"],
    pattern: {
      titleZh: "句型：Teach it once and the gaps introduce themselves. / My question invites the quiet student in.",
      explainZh: "教与学三招：教 why teach it once and the gaps show;问 questioning invites the quiet in;评 direct feedback 给成人学习者。",
      examples: [
        ["Teach it once and the gaps introduce themselves.", "教一遍，缺口自己就会自我介绍。"],
        ["My question invites the quiet student into the pattern.", "我的提问把安静的学生请进模式里。"],
        ["Teaching a knot unties the teacher faster than the student.", "教一个结，松开的常是老师自己。"],
      ],
      sentences: [
        ["The best explanation is the one you cannot stop giving.", "最好的解释是你停不下来的那种。"],
        ["Questioning techniques aim the room, not just the quiz.", "提问技巧对准屋子，不只对准测验。"],
        ["Peer instruction burns the syllabus into long memory.", "同伴教学把大纲烧进长时记忆。"],
      ],
    },
    reading: [
      ["Teaching the passive voice exposed my own tense habits.", "教被动语态暴露了我自己的时态习惯。"],
      ["A tiered question invited the quiet row into the answer.", "分层提问把安静那排请进了答案。"],
      ["Peer instruction turned the grammar review into a debate.", "同伴教学把语法复习变成一场辩论。"],
    ],
    writing: { zh: "选一个刚学的语法点写三句教案。", hintEn: "Point: ___. Example: ___. Question: ___." },
  },
  {
    day: 343,
    titleEn: "Synthesis Writing",
    titleZh: "第 343 天 · 综合写作",
    goalZh: "把来源综合成连贯的立场文章。",
    vocabIds: ["w:thesis-statement", "w:issue-tree", "w:citations-conventions", "w:evidence-based-practice", "w:literature-review-background-section"],
    grammarTopicId: "past-simple",
    phonicsRuleIds: ["ee", "st", "ai"],
    pattern: {
      titleZh: "句型：The thesis does not list; it decides. / Sources agree on the fact and argue the meaning.",
      explainZh: "综合三律：论点决定 the thesis decides, not lists;来源 agreement and argument 分辨;引用 citations-conventions 支撑。",
      examples: [
        ["The thesis does not list examples; it decides the angle.", "论点不列例子，它定角度。"],
        ["Sources agree on the fact and argue over the meaning.", "来源对事实一致，对含义争论。"],
        ["A concept map turns the sources into a living room.", "概念图把来源摆成一间客厅。"],
      ],
      sentences: [
        ["Every paragraph answers the thesis or gets cut.", "每段要么回答论点，要么被删。"],
        ["The convention is the contract between writer and reader.", "引用规范是作者与读者的契约。"],
        ["A synthesis is a conversation, not a collage.", "综合是对话，不是拼贴。"],
      ],
    },
    reading: [
      ["The map staged four sources into two stances.", "概念图把四个来源排成两个立场。"],
      ["One paragraph disobeyed the thesis; it was cut.", "一段回答不上论点，被删了。"],
      ["Citations turned a friendly essay into a defensible one.", "引用把一篇讨喜的文章变成可辩护的文章。"],
    ],
    writing: { zh: "写综合立场：论点句加两个来源的争点。", hintEn: "Thesis: ___. Fact: ___. Meaning debate: ___." },
  },
  {
    day: 344,
    titleEn: "Adaptation Under Review",
    titleZh: "第 344 天 · 在评审中调适",
    goalZh: "用答辩、修订与再投稿应对评审意见。",
    vocabIds: ["w:peer-review-process", "w:proofread-typo-assassin-final-gate-duty", "w:critique-balanced-review-essay", "w:scrum-agile-iteration", "w:performance-review-anxiety-season"],
    grammarTopicId: "basic-clauses",
    phonicsRuleIds: ["ee", "st", "ai"],
    pattern: {
      titleZh: "句型：The reviewer named the gap; I thank and repair. / Round two reads the first with better eyes.",
      explainZh: "评审三招：感谢 ththank and repair;逐条回应 item by item;迭代 iterative process 让第二稿更自知。焦虑见稿即减。",
      examples: [
        ["The reviewer named the gap; I thank and repair.", "评审点名缺口，我道谢并修补。"],
        ["Round two reads the first round with better eyes.", "第二轮用更清的眼读第一轮。"],
        ["An iterative process makes the draft a prototype.", "迭代让稿子变成原型机。"],
      ],
      sentences: [
        ["Every repaired point lowers the next anxiety.", "每个修好的点都降低下一次的焦虑。"],
        ["Publication anxiety dies a little at each resubmit.", "发表焦虑每次重投都会死掉一点。"],
        ["Peer revision is drafting with a mirror.", "同伴修订是面着镜子打草稿。"],
      ],
    },
    reading: [
      ["Thank-and-repair turned a harsh review into a to-do list.", "道谢加修补把苛刻评审变成待办清单。"],
      ["The item-by-item reply closed the review in one round.", "逐条回应一轮内结束了评审。"],
      ["Iteration made the third draft feel like a first decision.", "迭代让第三稿像第一次做决定。"],
    ],
    writing: { zh: "写一段评审回复：道谢、缺口、修补。", hintEn: "Thanks: ___. Gap: ___. Repair: ___." },
  },
  {
    day: 345,
    titleEn: "Project Rhetoric Review",
    titleZh: "第 345 天 · 项目修辞复盘",
    goalZh: "复核毕业项目的可视化与结论链。",
    vocabIds: ["w:pitch", "w:storyboarding", "w:issue-tree", "w:self-assessment", "w:feedback-loop"],
    grammarTopicId: "questions",
    phonicsRuleIds: ["ee", "st", "ai"],
    pattern: {
      titleZh: "句型：The map says the story; the pitch says the ask. / Engagement fell where I hurried the logic.",
      explainZh: "复盘两问：可视与结论 对齐吗;观众指 number 里谁走的。用自评和会后的数字修第四稿。",
      examples: [
        ["The map says the story; the pitch says the ask.", "概念图讲故事，演讲说请求。"],
        ["Engagement fell where I hurried the logic of slide four.", "第四页逻辑赶路的地方，投入度掉了下来。"],
        ["Self-assessment catches what the applause cannot say.", "自评能抓到掌声说不出的东西。"],
      ],
      sentences: [
        ["A concept map is the quiet rehearsal of the argument.", "概念图是论点安静的排练。"],
        ["The metric tells where the room leaned in.", "这项指标告诉我们全场何时前倾。"],
        ["Assessment is the last slide the audience never sees.", "评估是观众永远看不到的最后一页。"],
      ],
    },
    reading: [
      ["The map exposed a detour no slide had noticed.", "概念图暴露了一处没人注意的绕路。"],
      ["Where the room leaned out, the ask was buried.", "全场后仰之处，正是请求被埋之地。"],
      ["The fourth draft fixed the logic the applause had forgiven.", "第四稿修好掌声已经原谅的逻辑。"],
    ],
    writing: { zh: "写复盘三行：故事、逻辑、数据各一处修正。", hintEn: "Story: ___. Logic: ___. Metric: ___." },
  },
  {
    day: 346,
    titleEn: "Media Futures Debates",
    titleZh: "第 346 天 · 媒体的未来之争",
    goalZh: "辩论 AI 内容、聚合平台与把关人的取舍。",
    vocabIds: ["w:media-consolidation", "w:platform-regulation", "w:algorithmic-amplification-loop", "w:source-credibility", "w:news-value"],
    grammarTopicId: "articles",
    phonicsRuleIds: ["ee", "st", "ai"],
    pattern: {
      titleZh: "句型：Aggregation grows reach and thins the local room. / The gatekeeper you want is the one with a source line.",
      explainZh: "未来之争两问：聚合 reach 与本地声音的取舍 the thinned local room;把关 the gatekeeper you want has a source line。",
      examples: [
        ["Aggregation grows reach and thins the local room.", "聚合扩大触达，也削薄本地房间。"],
        ["The gatekeeper you want is the one with a source line.", "你想要的把关人是有出处行的那位。"],
        ["Amplification loops reward the loud and punish the patient.", "放大回路奖励大声，惩罚耐心。"],
      ],
      sentences: [
        ["Consolidation was a business decision with a civic price tag.", "整合是一个带公民价签的商业决定。"],
        ["Regulation aims at the lane, not the freight.", "监管瞄准车道，不瞄准货物。"],
        ["The source line is the oldest filter in the feed.", "出处行是信息流里最老的过滤器。"],
      ],
    },
    reading: [
      ["The aggregation thesis won the room until the local died.", "聚合论点赢了全场，直到本地死了。"],
      ["Debaters split on whether AI copy counts as news.", "辩手对 AI 稿件算不算新闻各执一词。"],
      ["A source-lined columnist reclaimed the young audience.", "带着出处行的专栏作者赢回年轻观众。"],
    ],
    writing: { zh: "写一句媒体未来立场与一条关切。", hintEn: "Stance: ___. Concern: ___." },
  },
  {
    day: 347,
    titleEn: "AI-Augmented Work",
    titleZh: "第 347 天 · 智能增强的工作",
    goalZh: "规划 AI 如何在流程里放大而非替代。",
    vocabIds: ["w:human-robot-interaction", "w:automation-script-weekly-report-magic-tricks", "w:machine-learning-patterns-without-rules-explained", "w:delegation-trust-but-verify-loop", "w:algorithmic-accountability"],
    grammarTopicId: "be-verb",
    phonicsRuleIds: ["ee", "st", "ai"],
    pattern: {
      titleZh: "句型：The loop keeps a human in decision and a model in draft. / Augmentation keeps me the editor.",
      explainZh: "增强三问：分工 the model drafts, the human decides;留责 human-in-the-loop;边界 who audits the output。",
      examples: [
        ["The loop keeps a human in the decision and a model in the draft.", "回路让人留在决定里，让模型留在草稿里。"],
        ["Augmentation keeps me the editor of the machine's copy.", "增强让我继续做机器稿件的编辑。"],
        ["The weekly report script buys back the Monday morning analysis.", "周报脚本买回周一早晨的分析时间。"],
      ],
      sentences: [
        ["A human-in-the-loop policy beats a hundred best hopes.", "人在回路政策胜过一百个良好愿望。"],
        ["Model patterns need a named bottom line before output.", "模型模式需要一条点名的底线再输出。"],
        ["Accountability outlives the model that ships it.", "问责制活得比发布它的模型久。"],
      ],
    },
    reading: [
      ["The tool drafted; the human decided; nobody felt replaced.", "工具起草、人类决定，没人觉得被替代。"],
      ["The loop review caught a bad recommendation in time.", "回路审核及时抓住一条坏建议。"],
      ["Editing the machine's copy became the new job description.", "编机器稿件成了新岗位说明。"],
    ],
    writing: { zh: "写一个人机分工：模型起草什么、我决定什么。", hintEn: "Model drafts: ___. I decide: ___. Audit: ___." },
  },
  {
    day: 348,
    titleEn: "Global English Interviews",
    titleZh: "第 348 天 · 环球英语面试",
    goalZh: "用 STAR 结构应对不同文化的面试问题。",
    vocabIds: ["w:stakeholder-interview", "w:performance-goals", "w:intercultural-communication", "w:organizational-culture", "w:contract-negotiation-red-lines"],
    grammarTopicId: "present-simple",
    phonicsRuleIds: ["ee", "st", "ai"],
    pattern: {
      titleZh: "句型：STAR: situation, task, action, and result. / In Tokyo they read the pause; in New York they fill it.",
      explainZh: "面试两件套：STAR 四步压缩回答;文化差异 read the pause vs fill it。价值观与期待早点对齐。",
      examples: [
        ["STAR: situation, task, action, and result.", "STAR 四步：情境、任务、行动、结果。"],
        ["In Tokyo they read the pause; in New York they fill it.", "东京人读停顿，纽约人填停顿。"],
        ["A values-fit answer names the reason beyond the role.", "符合价值观的回答说出角色之外的理由。"],
      ],
      sentences: [
        ["The behavioral interview rewards the structured past.", "行为面试奖励结构化的过去。"],
        ["Cross-cultural fluency is refusing to guess the silence.", "跨文化流畅是不去猜那阵沉默。"],
        ["Preparing the salary frame quietly changed the offer.", "认真准备薪酬框架悄悄改变了开价。"],
      ],
    },
    reading: [
      ["The STAR answer turned a ten-minute ramble into a crisp minute.", "STAR 回答把十分钟漫谈变成利落一分钟。"],
      ["Reading the pause in Tokyo won the follow-up call.", "读懂东京的停顿赢来后续通话。"],
      ["The values-fit line explained why she stayed three years.", "价值观句解释了她为何留下三年。"],
    ],
    writing: { zh: "写一条 STAR 回答：情境、任务、行动、结果。", hintEn: "S: ___. T: ___. A: ___. R: ___." },
  },
  {
    day: 349,
    titleEn: "Persuasive Writing Finale",
    titleZh: "第 349 天 · 说服写作终章",
    goalZh: "打磨一篇可参赛的说服文。",
    vocabIds: ["w:persuasion", "w:counterclaim-integration", "w:rhetoric", "w:substantiate-claims", "w:concise-cut-adjectives-payroll-halving"],
    grammarTopicId: "past-simple",
    phonicsRuleIds: ["ee", "st", "ai"],
    pattern: {
      titleZh: "句型：The draft argues; round two negotiates with itself. / The strongest paragraph answers the loudest doubt.",
      explainZh: "说服定稿三招：自辩 the draft negotiates with itself;证据路线 evidence-roadmap 从头领到尾;删字 editing for clarity。",
      examples: [
        ["The draft argues; round two negotiates with itself.", "一稿讨价，二稿与自我谈判。"],
        ["The strongest paragraph answers the loudest doubt.", "最有力的段落回答最响的怀疑。"],
        ["A rhetorical question earns the reader a breath.", "修辞问句给读者换一口气。"],
      ],
      sentences: [
        ["Clarity is the final form of conviction.", "清晰是信念的最终形态。"],
        ["Every cut reveals the sentence that meant it.", "每删一字，真正要的那句就露一分。"],
        ["The evidence roadmap ends exactly on the ask.", "证据路线图恰好停在请求上。"],
      ],
    },
    reading: [
      ["The self-negotiating draft dropped its weakest third.", "自我谈判的一稿砍掉了最弱的第三段。"],
      ["Answering the loudest doubt first won the skeptical judge.", "先答最响的怀疑说服了最怀疑的评委。"],
      ["One clarity cut saved the whole last paragraph.", "一次清晰化剪辑救了整个收尾段。"],
    ],
    writing: { zh: "写说服定稿的自我谈判一条。", hintEn: "Loud doubt: ___. My answer: ___. Cut: ___." },
  },
  {
    day: 350,
    titleEn: "Review Sprint",
    titleZh: "第 350 天 · 复习冲刺",
    goalZh: "三天回拨全年：词汇、句型、思辨。",
    vocabIds: ["w:spaced-repetition", "w:retrieval-practice", "w:forgetting-curve", "w:interleaving-practice", "w:mastery-learning"],
    grammarTopicId: "basic-clauses",
    phonicsRuleIds: ["ee", "st", "ai"],
    pattern: {
      titleZh: "句型：Retrieval beats rereading by the distance of a week. / The deck is ordered by pain, not by page.",
      explainZh: "复习三件套：提取 retrieval practice;间隔 spaced-repetition gap;混合 interleaving 换着测。卡越痛越靠前。",
      examples: [
        ["Retrieval beats rereading by the distance of a week.", "提取胜过重读，差距是一周的距离。"],
        ["The deck is ordered by pain, not by page.", "卡组按痛感排序，不按页码。"],
        ["Interleaving mixes the tenses until the brain surrenders.", "混合练习把时态混到一起直到大脑投降。"],
      ],
      sentences: [
        ["Mastery reviews are the map up the forgetting curve.", "掌握复盘是遗忘曲线上的地图。"],
        ["A painful card is a friend with news.", "一张扎心的卡是报信的朋友。"],
        ["Three-day sprints beat one endless marathon.", "三天冲刺胜过一场无尽马拉松。"],
      ],
    },
    reading: [
      ["Retrieval practice outscored rereading by a full letter grade.", "提取练习比重读高出一整个等级。"],
      ["The pain-ordered deck trained the real weaknesses.", "按痛感的卡组训练真弱点。"],
      ["Interleaved tenses confused at first, then cemented.", "混合时态先让人困惑，随后凝固成记忆。"],
    ],
    writing: { zh: "列你的最痛三卡与复习间隔。", hintEn: "Pain card: ___. Next review: ___. Mode: ___." },
  },
  {
    day: 351,
    titleEn: "Media Ethics Ring",
    titleZh: "第 351 天 · 媒体伦理答辩",
    goalZh: "用伦理学语应对媒体真实的两难。",
    vocabIds: ["w:journalism-ethics-code", "w:source-protection", "w:public-interest-defense", "w:conflict-of-interest", "w:accountability"],
    grammarTopicId: "negation",
    phonicsRuleIds: ["ee", "st", "ai"],
    pattern: {
      titleZh: "句型：Privacy yields only where the public harm is concrete. / The named conflict changes the whole lens.",
      explainZh: "伦理两难两招：隐私让步 but only where harm is concrete;利益冲突 named conflict 要显影。别用标题救人，用守则。",
      examples: [
        ["Privacy yields only where the public harm is concrete.", "只有公共伤害具体时隐私才让步。"],
        ["The named conflict changes the whole lens on the story.", "点名了的利益冲突改变整篇的取景。"],
        ["A source line is the reporter's spine under pressure.", "出处行是记者受压时的脊梁。"],
      ],
      sentences: [
        ["Ethics codes answer before the deadline rings.", "伦理守则在截稿铃响前就有了答案。"],
        ["Accountability is the contract the audience can sue.", "媒体问责是观众可以起诉的合同。"],
        ["The interest you hide is the bias you keep.", "你藏起的利益就是你保留的偏见。"],
      ],
    },
    reading: [
      ["The privacy-versus-interest case split the newsroom in two.", "隐私与公众利益之争把编辑部一分为二。"],
      ["A named conflict forced a reassignment on the spot.", "点名的利益冲突当场迫使换人。"],
      ["The protected source repaid the paper with the scoop of the year.", "受保护来源用年度独家回报了报社。"],
    ],
    writing: { zh: "写一个媒体两难及你的裁决线。", hintEn: "Case: ___. Rule: ___. Ruling: ___." },
  },
  {
    day: 352,
    titleEn: "Civic Listening",
    titleZh: "第 352 天 · 公民聆听",
    goalZh: "用专注与转述进入有质量的公共对话。",
    vocabIds: ["w:empathetic-listening-without-fixing-reflex", "w:retrospective", "w:public-discourse", "w:deliberative-democracy", "w:epistemic-humility-principle"],
    grammarTopicId: "prepositions-basic",
    phonicsRuleIds: ["ee", "st", "ai"],
    pattern: {
      titleZh: "句型：Before asserting, reflect the other view in a clean sentence. / The tone is a civic action.",
      explainZh: "公民聆听三招：复述 reflect the other view;追问 ask for the missing evidence;认错 moral humility 让对话有命可留。",
      examples: [
        ["Before asserting, reflect the other view in a clean sentence.", "断言前，用干净句子复述对方观点。"],
        ["The tone is a civic action with a long shelf life.", "语气是一种保质期很长的公民行为。"],
        ["Deliberative dialogue trades the win for the understanding.", "协商式对话拿胜负换理解。"],
      ],
      sentences: [
        ["A reflective summary is the magic mirror of the argument.", "反思式总结是争论的魔镜。"],
        ["Humility is the seat belt of the strong opinion.", "谦逊是强烈观点的安全带。"],
        ["Civil discourse grows where the interruptor sleeps.", "公民讨论在打断者睡觉处长出来。"],
      ],
    },
    reading: [
      ["The reflective summary cooled a boiling room in minutes.", "反思总结几分钟内给沸腾的屋子降温。"],
      ["Asking for the missing evidence ended the stereotype loop.", "索要缺失证据结束了刻板印象循环。"],
      ["One conceded point bought the next two minutes of hear.", "让一步买下被倾听的下两分钟。"],
    ],
    writing: { zh: "写一段对相反观点的干净复述。", hintEn: "Their view: ___. Clean restate: ___. Missing: ___." },
  },
  {
    day: 353,
    titleEn: "Global Contexts",
    titleZh: "第 353 天 · 全球化语境",
    goalZh: "用国际视野解释数字与文化的取舍。",
    vocabIds: ["w:globalization-supply-chain-effects", "w:cultural-relativism", "w:transcultural", "w:digital-human", "w:inclusive-design"],
    grammarTopicId: "countable-uncountable",
    phonicsRuleIds: ["ee", "st", "ai"],
    pattern: {
      titleZh: "句型：The same number means different things across two cultures. / Digital personhood demands a seat at the table.",
      explainZh: "全球化三件套：文化视野 the same number means different things;数字人格 digital personhood 要席位;包容语言 inclusive-languages 选词即站队。",
      examples: [
        ["The same number means different things across two cultures.", "同一个数字在两种文化里有不同含义。"],
        ["Digital personhood demands a seat at the table in law.", "数字人格要求在法里占一席。"],
        ["Inclusive language is choosing the door over the wall in every sentence.", "包容语言是每句都选门不选墙。"],
      ],
      sentences: [
        ["Globalization is a context manager, not a blank wall.", "全球化是语境管理器，不是空墙。"],
        ["A transnational framework translates local dilemmas fairly.", "跨国框架公平地翻译本地困境。"],
        ["The digital human inherits rights the hard way.", "数字人类以艰难方式继承权利。"],
      ],
    },
    reading: [
      ["The salary slide read completely differently in the two offices.", "薪酬那页在两个办公室读法完全不同。"],
      ["The transnational framework caught the translation trap early.", "跨国框架及早抓住翻译陷阱。"],
      ["Inclusive wording survived the culture review unchanged.", "包容措辞通过了文化审查，原样存活。"],
    ],
    writing: { zh: "写一个数字在两种语境中的不同含义。", hintEn: "Number: ___. Culture A: ___. Culture B: ___." },
  },
  {
    day: 354,
    titleEn: "Decision Under AI",
    titleZh: "第 354 天 · 在 AI 旁做决定",
    goalZh: "评估模型建议、偏见与人工否决权。",
    vocabIds: ["w:ai-governance", "w:ai-liability", "w:prediction-product", "w:algorithmic-accountability", "w:reinforcement-learning-human-feedback"],
    grammarTopicId: "future-simple",
    phonicsRuleIds: ["ee", "st", "ai"],
    pattern: {
      titleZh: "句型：The model proposes; the human disposes after reading the bias note. / Whose liability lands when the call fails?",
      explainZh: "决策两问：建议与否决 the model proposes, the human disposes;责任归属 whose liability lands。治理在代码之前。",
      examples: [
        ["The model proposes; the human disposes after reading the note.", "模型提案，人读完附注再裁决。"],
        ["Whose liability lands when the call fails at scale?", "大规模失败时，责任落在谁头上？"],
        ["Prediction dependence is the quiet addiction of the feed.", "对预测的依赖是信息流里安静的瘾。"],
      ],
      sentences: [
        ["Governance writes the rules the algorithm executes.", "治理写下算法执行的规则。"],
        ["A veto that is never used still changes the output.", "从不使用的否决权也改变着输出。"],
        ["The bias note belongs next to the recommendation.", "偏见附注应该贴在建议旁边。"],
      ],
    },
    reading: [
      ["The human veto overrode a model even a board liked.", "人工否决压过一个董事会都喜欢的模型。"],
      ["The liability clause took the legal department a quarter.", "责任条款花去法务一整个季度。"],
      ["Reading the bias note changed two hiring calls.", "读偏见附注改变了两条招聘决定。"],
    ],
    writing: { zh: "写一个人与模型各掌什么、谁担责。", hintEn: "Model: ___. Human: ___. Failure owner: ___." },
  },
  {
    day: 355,
    titleEn: "Learning in the Wild",
    titleZh: "第 355 天 · 野地学习",
    goalZh: "写衬线三年的自学路线图。",
    vocabIds: ["w:self-regulated-learning", "w:mastery-learning", "w:grit-long-term-perseverance-trait", "w:mastery-goals", "w:flow-state-optimal"],
    grammarTopicId: "be-verb",
    phonicsRuleIds: ["ee", "st", "ai"],
    pattern: {
      titleZh: "句型：The learning outcome names what I can do by June. / Motivation returns at the promise of the small goal.",
      explainZh: "三年路线三件套：结果 learning-outcomes 可测;小目标 motivation returns at the small goal;坚持 persistence as the real kind。",
      examples: [
        ["The learning outcome names what I can do by June.", "学习成果写明六月我能做什么。"],
        ["Motivation returns at the promise of the small goal.", "动机在小目标的承诺处回来。"],
        ["Persistence is the tuition of the long road.", "坚持是长路的学费。"],
      ],
      sentences: [
        ["Lifelong learning is a habit with a season ticket.", "终身学习是有季票的习惯。"],
        ["A three-year roadmap survives a three-week storm.", "三年路线图扛得住三周的暴风雨。"],
        ["Self-motivation is the fuel the coach no longer buys.", "自我驱动是教练不再购买的燃料。"],
      ],
    },
    reading: [
      ["The by-June outcome set a real deadline in the diary.", "六月成果在日历里设下真实期限。"],
      ["The small goal recharged a tired planner in a day.", "小目标一天内给疲惫的计划者充电。"],
      ["The season ticket outlasted the gym membership, as always.", "季票又一次打败了健身卡。"],
    ],
    writing: { zh: "写一个 12 个月的英语学习成果句。", hintEn: "By ___, I can ___. Small goal: ___. Reason: ___." },
  },
  {
    day: 356,
    titleEn: "Full Capstone Rehearsal",
    titleZh: "第 356 天 · 毕业演讲全排练",
    goalZh: "走完整套演讲并录一段自我复盘。",
    vocabIds: ["w:eloquent-speeches-quote-worthy-sentences", "w:magic-tricks-card-palm-practice-invisible-audiences", "w:stage-fright-cold-hands-cure", "w:soliloquy-speech", "w:feedback-loop"],
    grammarTopicId: "present-simple",
    phonicsRuleIds: ["ee", "st", "ai"],
    pattern: {
      titleZh: "句型：The full run-through exists to find the weak third, not to celebrate. / I record the last minute and phone the gap.",
      explainZh: "全排练两招：找弱 the weak third;录音回放 record and hear the gap。彩排不是仪式，是体检。",
      examples: [
        ["The full run-through exists to find the weak third.", "完整彩排只为找到那弱的三分之一。"],
        ["I record the last minute and listen for the gap.", "我录下最后一分钟，听出缺口。"],
        ["Cold hands return on cue; the cue is a name tag in my pocket.", "怯场准时回来，我的暗号是口袋里的一张名牌。"],
      ],
      sentences: [
        ["A rehearsal schedule is the promise the talk keeps.", "排练日程是演讲对自己守的诺言。"],
        ["Practice is where the script learns your accent.", "练习是稿子学会你口音的地方。"],
        ["Every feedback loop closed in time compounds into ease.", "每个及时闭合的反馈回路都复利成从容。"],
      ],
    },
    reading: [
      ["The weak third emerged at minute six, exactly as feared.", "薄弱第三段在第六分钟准时出现。"],
      ["The recording revealed a bossier voice than anyone expected.", "录音暴露了一个比众人预期更专横的声音。"],
      ["Closing the loop on the pause note built real stage ease.", "按暂停意见闭环打磨，台上真的从容了。"],
    ],
    writing: { zh: "写彩排发现的三个缺口。", hintEn: "Minute: ___. Gap: ___. Fix: ___." },
  },
  {
    day: 357,
    titleEn: "Oral Defense",
    titleZh: "第 357 天 · 口头答辩",
    goalZh: "用一页纸与三句话守护自己的项目。",
    vocabIds: ["w:scoring-rubric", "w:thesis-statement", "w:rebuttal-n2", "w:evidence-based-practice", "w:retrospective"],
    grammarTopicId: "past-simple",
    phonicsRuleIds: ["ee", "st", "ai"],
    pattern: {
      titleZh: "句型：One page of claims, three sentences of proof each. / The toughest question came from my own notes.",
      explainZh: "答辩三招：一页纸 one page of claims;三行证 three sentences of proof;复盘 toughest question 出自自己的笔记。",
      examples: [
        ["One page of claims, three sentences of proof each.", "一页主张，每条三句证明。"],
        ["The toughest question came quietly from my own notes.", "最难的问题悄悄出自我的笔记。"],
        ["A reflective summary closed the defense on a calm note.", "反思式总结给答辩一个平静收束。"],
      ],
      sentences: [
        ["The one-page defense is a beginner's kindness.", "一页纸答辩是对初学者的善意。"],
        ["Evidence-based practice defends better than charisma.", "循证实践比魅力更能防守。"],
        ["Your notes are the critic who knows all your shortcuts.", "你的笔记是知道你所有捷径的批评家。"],
      ],
    },
    reading: [
      ["The one-page doctrine spared the panel a rambling family tree.", "一页原则让评审团免于听一张漫谈谱系表。"],
      ["The claim-proof structure survived three hard challenges.", "主张加证明的结构扛住三次硬挑战。"],
      ["Replaying the session at home found the gap the room missed.", "回家回放时找出现场都没发现的缺口。"],
    ],
    writing: { zh: "写一页答辩：一项主张加三句证明。", hintEn: "Claim: ___. Proof 1-3: ___. Expected Q: ___." },
  },
  {
    day: 358,
    titleEn: "Capstone Dress Rehearsal",
    titleZh: "第 358 天 · 结业预演",
    goalZh: "带观众完整预演并记录第三次反馈。",
    vocabIds: ["w:ceremony-term", "w:feedback-loop-fast-course-correction-culture", "w:peer-feedback-incorporation", "w:pitch", "w:last-mile-delivery"],
    grammarTopicId: "negation",
    phonicsRuleIds: ["ee", "st", "ai"],
    pattern: {
      titleZh: "句型：The dress rehearsal is a real show with a rehearsal badge. / Feedback number three is smaller and sharper.",
      explainZh: "预演两招：当真 the dress rehearsal is a real show;反馈递减 third feedback is smaller and sharper，说明收敛。",
      examples: [
        ["The dress rehearsal is a real show with a rehearsal badge.", "带妆彩排是一场挂着彩排名牌的真演出。"],
        ["Feedback number three is smaller and sharper than round one.", "第三轮反馈比第一轮更小、更锋利。"],
        ["The cap-toss photo is choreography; the grads are the cast.", "毕业抛帽照是编排，毕业生是演员。"],
      ],
      sentences: [
        ["Engagement metrics on rehearsal night still tell the truth.", "预演之夜的核心指标照样说真话。"],
        ["Smaller feedback means the draft is becoming the final.", "反馈变小意味着草稿在变成终稿。"],
        ["The deliverable is a promise with a timestamp.", "交付物是带时间戳的承诺。"],
      ],
    },
    reading: [
      ["Round three feedback filed in under a quarter of round one.", "第三轮反馈不足第一轮的四分之一。"],
      ["Rehearsal-night engagement matched the final-night curve.", "预演夜的投入度曲线与终演吻合。"],
      ["The polished cap-toss photo ran exactly once.", "精心编排的抛帽照恰好拍了一次。"],
    ],
    writing: { zh: "写预演投放的收敛数据。", hintEn: "Feedback shrunk from ___ to ___. Time: ___." },
  },
  {
    day: 359,
    titleEn: "Termination & Handoff",
    titleZh: "第 359 天 · 收官与交接",
    goalZh: "确认交付、交接资料与十二个月计划。",
    vocabIds: ["w:quarterly-report-earnings-call", "w:master-plan", "w:documentation", "w:liminality-transition", "w:due-diligence-process"],
    grammarTopicId: "basic-clauses",
    phonicsRuleIds: ["ee", "st", "ai"],
    pattern: {
      titleZh: "句型：The closeout checklist names every deliverable and its owner. / The handoff note carries the reasons, not just the files.",
      explainZh: "收官三件套：清单 closeout checklist;交接 handoff note 带原因;路线 roadmap 给未来。文档是给明天的自己。",
      examples: [
        ["The closeout checklist names every deliverable and its owner.", "收官清单写明每项交付物及其负责人。"],
        ["The handoff note carries the reasons, not just the files.", "交接便条带上理由，不只带文件。"],
        ["The roadmap pages the next twelve months into quarters.", "路线图把未来十二月分成季度。"],
      ],
      sentences: [
        ["Documentation is memory made portable.", "文档是便携化的记忆。"],
        ["A knowledge transition outlives the farewell toast.", "知识交接比告别祝酒活得更久。"],
        ["The summary is the one page the successor reads twice.", "摘要是继任者读两遍的那一页。"],
      ],
    },
    reading: [
      ["The checklist caught one orphan deliverable on the last day.", "清单在最后一天逮住一件孤儿交付物。"],
      ["The handoff reasons saved the successor a week of archaeology.", "交接理由替继任者省下一周的考古。"],
      ["The twelve-month roadmap survived its first budget cut.", "十二月路线图扛过了第一次预算削减。"],
    ],
    writing: { zh: "写收官清单三项与一句交接原因。", hintEn: "Item: ___. Owner: ___. Reasoning: ___." },
  },
  {
    day: 360,
    titleEn: "Graduation & Assessment",
    titleZh: "第 360 天 · 毕业与总测评",
    goalZh: "完成全年测评、自我评估与毕业誓言。",
    vocabIds: ["w:graduated-nd", "w:ceremony-term", "w:eloquent-speeches-quote-worthy-sentences", "w:self-assessment", "w:ipo-going-public-milestone-day"],
    grammarTopicId: "be-verb",
    phonicsRuleIds: ["ee", "st", "ai"],
    pattern: {
      titleZh: "句型：Today I measure the year against the map, not the mirror. / The vow is in the voice I leave with.",
      explainZh: "总测评三招：对照地图 map, not mirror;自我评估六个维度;誓言 the vow is in the voice I leave with。毕业之日，方案落地为身份。",
      examples: [
        ["Today I measure the year against the map, not the mirror.", "今天我拿地图量这一年，不拿镜子。"],
        ["The vow is in the voice I leave with, not the words I studied.", "誓言在我带走的语气里，不在背下的词里。"],
        ["The cap toss marks an exit that is also a start.", "抛帽标记一个同时是出发的出口。"],
      ],
      sentences: [
        ["Self-assessment is the diploma the mirror cannot grant.", "自我评估是镜子发不出毕业证。"],
        ["Every milestone here was a door, not a wall.", "这儿的每个里程碑都是门，不是墙。"],
        ["The year's map is now the map of the next question.", "这一年的地图成了下一个问题的地图。"],
      ],
    },
    reading: [
      ["The 360-day map made the summary write itself.", "360 天地图让总结自己长出来了。"],
      ["The self-assessment dimmed the doubts of the whole cohort.", "自我评估让全班怀疑集体变暗。"],
      ["The graduation speech ended with a question, not a period.", "毕业演讲以问号收尾，不是句号。"],
    ],
    writing: { zh: "写一句毕业誓言与三个测量维度。", hintEn: "Vow: ___. Measure 1-3: ___." },
  },
];