import type { CourseDayPlan } from "@/content/pipeline/generate-days";

/**
 * Phase 23 · Day 211-240 — Block B 学术写作（Academic Writing）。
 * B2→C2 学术产出：语域切换、论点句、段落发展、释义与引用、证据分级、
 * 因果与定义、互评与修改、摘要与汇报，全部引用真实 C1/C2 词汇与
 * 12 个语法话题，供 check-360-day-content-quality.cjs 校验。
 */
export const PLAN_211_240: readonly CourseDayPlan[] = [
  {
    day: 211,
    titleEn: "Academic Register Switch",
    titleZh: "第 211 天 · 学术语域切换",
    goalZh: "区分口语与学术书面语，学会一键换挡。",
    vocabIds: [
      "w:register-formal-versus-casual-switching",
      "w:nuance-argument",
      "w:antithesis",
      "w:coherent",
      "w:abstract-concise",
    ],
    grammarTopicId: "basic-clauses",
    phonicsRuleIds: ["ee", "st", "r"],
    pattern: {
      titleZh: "句型：The data suggest that ___. / This paper argues that ___.",
      explainZh: "学术换挡：口语说 I think，论文写 This paper argues that…；口语说 lots of，论文写 a substantial number of。同一个意思，不同语域。",
      examples: [
        ["This paper argues that noise harms learning.", "本文论证噪音损害学习。"],
        ["The data suggest that early sleep matters.", "数据显示早睡很有关系。"],
        ["In spoken English, short beats formal every time.", "口语里简短永远胜过正式。"],
      ],
      sentences: [
        ["Register is a gearbox, not a costume.", "语域是变速箱，不是戏服。"],
        ["Switch up for essays, down for chats.", "写论文升高挡，聊天降挡。"],
        ["Formal writing favors nouns; chat favors verbs.", "书面语偏爱名词，聊天偏爱动词。"],
      ],
    },
    reading: [
      ["One idea, two gears: a chat version and a paper version.", "同一个意思两种挡位：闲聊版与论文版。"],
      ["Textbooks revealed nominalized verbs at every page.", "教科书写满名词化的动词。"],
      ["Learners translated their own chat into formal prose.", "学员把自己的聊天翻译成正式白话。"],
    ],
    writing: { zh: "把一句话口语改写成学术语域版本。", hintEn: "Chat: I think people sleep too little. Paper: This paper argues that sleep duration is /insufficient/." },
  },
  {
    day: 212,
    titleEn: "Thesis Statements",
    titleZh: "第 212 天 · 论点句",
    goalZh: "用一句可辩护的话锁定整篇文章的方向。",
    vocabIds: [
      "w:thesis-statement-craft",
      "w:thesis-statement",
      "w:thesis-argumentation",
      "w:stance",
      "w:assertion",
    ],
    grammarTopicId: "present-simple",
    phonicsRuleIds: ["th-vl", "er", "ai"],
    pattern: {
      titleZh: "句型：This essay will argue that ___, because ___.",
      explainZh: "论点句三件套：表态 This essay will argue that…；给理由 because…；可辩护 it is defensible。一句话说不清，说明你还没想清。",
      examples: [
        ["This essay will argue that free lunch beats vouchers, because stigma reduces uptake.", "本文将论证免费午餐优于代金券，因为污名会降低领取率。"],
        ["A thesis you can defend in one breath is a thesis.", "能一口气辩护的说法才算论点。"],
        ["Weak thesis: commuting is bad. Strong thesis: remote work lowers attrition.", "弱论点：通勤不好。强论点：远程办公降低离职率。"],
      ],
      sentences: [
        ["The thesis is the engine; everything else is the drive train.", "论点是引擎，其余都是传动系统。"],
        ["If the thesis is boring, the paper is optional.", "论点无聊，文章就可有可无。"],
        ["Narrow claims survive; broad ones drown.", "窄主张活下来，宽主张被淹死。"],
      ],
    },
    reading: [
      ["Reviewers read the thesis sentence first and smiled.", "评审先看论点句，然后笑了。"],
      ["Clear thesis statements cut rewrite cycles by half.", "清晰的论点句让修改周期减半。"],
      ["Boring theses get skimmed; bold ones get argued.", "无聊论点被跳过，大胆论点被争论。"],
    ],
    writing: { zh: "就任何争议话题写一句可辩护的论点句。", hintEn: "This essay will argue that ___, because ___." },
  },
  {
    day: 213,
    titleEn: "Paragraph Engine",
    titleZh: "第 213 天 · 段落引擎",
    goalZh: "用主题句支撑展开收尾三步写出完整段落。",
    vocabIds: [
      "w:premise-n2",
      "w:argument-structure",
      "w:coherent",
      "w:concession-rebuttal-structure",
      "w:skeleton",
    ],
    grammarTopicId: "present-simple",
    phonicsRuleIds: ["er", "th-vd", "oi"],
    pattern: {
      titleZh: "句型：One paragraph, one claim. / This connects to my argument because ___.",
      explainZh: "段落三部曲：开头甩主题句 Topic sentence；中间给证据撑腰 Evidence；结尾回扣论点 This connects to my argument because…。一段只办一件事。",
      examples: [
        ["One paragraph, one claim — the rule of thumb.", "一段一事——黄金法则。"],
        ["Topic sentence first, then the evidence train.", "先主题句，再证据列车。"],
        ["This connects to my argument because cost folds into access.", "这和我的论点相连，因为成本会叠进可及性。"],
      ],
      sentences: [
        ["The topic sentence is the paragraph's thesis.", "主题句是段落的小论点。"],
        ["Rambling paragraphs hide a missing claim.", "乱逛的段落藏着一个缺失的主张。"],
        ["Close each paragraph with a bridge, not a wall.", "每段以桥结尾，而不是以墙。"],
      ],
    },
    reading: [
      ["The five-paragraph form is a scaffold, not a cage.", "五段式是脚手架，不是牢笼。"],
      ["Paragraphs with a spine survive restructuring.", "有脊梁的段落经得起重构。"],
      ["Editors delete paragraphs that cannot swear allegiance to a claim.", "编辑删掉无法效忠某一主张的段落。"],
    ],
    writing: { zh: "写一个完整段落：主题句+两条证据+回扣句。", hintEn: "Topic claim… Evidence 1/2… This connects to ___." },
  },
  {
    day: 214,
    titleEn: "Transition Rail System",
    titleZh: "第 214 天 · 连接词铁轨",
    goalZh: "用连接词铺设逻辑轨道让读者不迷路。",
    vocabIds: [
      "w:cohesion",
      "w:coherent",
      "w:argument-structure",
      "w:concession-rebuttal-structure",
      "w:register-formal-versus-casual-switching",
    ],
    grammarTopicId: "basic-clauses",
    phonicsRuleIds: ["tr", "dr", "ee"],
    pattern: {
      titleZh: "句型：Furthermore, ___. / However, ___. / In contrast, ___.",
      explainZh: "连接词当铁轨：递进 Furthermore…；转折 However…；对比 In contrast…。轨铺到哪里，读者跟到哪里。",
      examples: [
        ["Furthermore, early starts reduce evening screen time.", "再者，早开场减少晚间屏幕时间。"],
        ["However, the sample size limits the claim.", "然而，样本量限制了结论。"],
        ["In contrast, rural workers booked cleaner sleep.", "相比之下，乡村员工睡得更干净。"],
      ],
      sentences: [
        ["Transitions are the joints that make text walk.", "连接词是让文字行走的关节。"],
        ["Every transition should buy a logical step.", "每个连接词都应买到一步逻辑。"],
        ["Cohesion stitches sentences into one fabric.", "衔接把句子缝成一块布。"],
      ],
    },
    reading: [
      ["Readers ranked paragraphs with visible rails as more logical.", "读者认为有显性铁轨的段落逻辑更强。"],
      ["Overused however lost its braking power.", "被用滥的 however 失去了刹车力。"],
      ["Sentence chains without joints read like rope.", "没有关节的句子串读起来像麻绳。"],
    ],
    writing: { zh: "写出四个不同功能的连接词及例句。", hintEn: "Furthermore/However/In contrast/Therefore + ___" },
  },
  {
    day: 215,
    titleEn: "Paraphrase Gym",
    titleZh: "第 215 天 · 释义健身房",
    goalZh: "用换词换结构调整句子而保持原意，远离抄袭。",
    vocabIds: [
      "w:paraphrase-same-meaning-new-clothes-skill",
      "w:plagiarism",
      "w:plagiarism-rules",
      "w:citation-format",
      "w:citations-conventions",
    ],
    grammarTopicId: "basic-clauses",
    phonicsRuleIds: ["gr", "j", "ar"],
    pattern: {
      titleZh: "句型：In other words, ___. / To put it differently, ___.",
      explainZh: "释义三招：换词 change the vocabulary；换骨 restructure the sentence；点名道姓 cite the source。只改单词不换结构照样算抄袭。",
      examples: [
        ["In other words, demand rose faster than supply.", "换句话讲，需求涨得比供给快。"],
        ["To put it differently, the policy taxed waiting time.", "换个说法，该政策对等待时间课税。"],
        ["Paraphrase keeps meaning; plagiarism steals it.", "释义保住意思，抄袭偷走意思。"],
      ],
      sentences: [
        ["Rewrite the structure, not just the dictionary.", "重写结构，不只是换词典。"],
        ["Say it new, say it yours, say who taught you.", "说新的、说自己的、说谁教的。"],
        ["An honest paraphrase always carries its receipt.", "诚实的释义永远带着收据。"],
      ],
    },
    reading: [
      ["The original sentence lost no meaning but gained new clothes.", "原句意思没丢，只是换了件新衣裳。"],
      ["Plagiarism checks flagged word-swapped sentences.", "查重系统揪住了只换单词的句子。"],
      ["Quote showers sank essays under other people's voices.", "引文雨把文章淹在别人的声音里。"],
    ],
    writing: { zh: "用两种不同结构改写同一句话。", hintEn: "V1: ___. V2: To put it differently, ___." },
  },
  {
    day: 216,
    titleEn: "Compressing Sources",
    titleZh: "第 216 天 · 压缩来源",
    goalZh: "把长研究压缩成一句有用的话并准确署名。",
    vocabIds: [
      "w:paraphrase-same-meaning-new-clothes-skill",
      "w:citation-integrity-check",
      "w:citations-conventions",
      "w:citation-format",
      "w:meta-analysis-synthesis",
    ],
    grammarTopicId: "present-progressive",
    phonicsRuleIds: ["pl", "st", "igh"],
    pattern: {
      titleZh: "句型：According to X, ___. / X found that ___.",
      explainZh: "压缩引述公式：交代出处 According to X…；给出发现 X found that…；修正幅度 X found that, with caveats, …。一句话交代清楚来源与强度。",
      examples: [
        ["According to Smith, screen time matters less than bedtime.", "据史密斯，屏幕时长不如就寝时间重要。"],
        ["Wang found that evening exercise shifted sleep onset.", "王发现晚间锻炼改变了入睡时刻。"],
        ["A meta-analysis found a small but stable effect.", "一项元分析发现小而稳定的效应。"],
      ],
      sentences: [
        ["Summarize the finding, not the whole paper.", "概括发现，不是整篇论文。"],
        ["The citation is the receipt of your idea.", "引用是你想法的收据。"],
        ["Compression without attribution is theft with punctuation.", "没有署名的压缩是带标点的偷。"],
      ],
    },
    reading: [
      ["A one-line summary beat a paragraph of paraphrase.", "一行总结胜过一段释义。"],
      ["Reviewers checked citations, then read conclusions.", "评审查完引用才读结论。"],
      ["Meta-analyses gave learners precedent to combine sources.", "元分析给学员提供了合并来源的先例。"],
    ],
    writing: { zh: "把一句研究结论用 According to 压缩引述。", hintEn: "According to ___, ___. (one line)" },
  },
  {
    day: 217,
    titleEn: "Citation Chain",
    titleZh: "第 217 天 · 引用链",
    goalZh: "建立引用习惯并用工具管理参考文献。",
    vocabIds: [
      "w:citation-format",
      "w:citation-integrity-check",
      "w:citations-conventions",
      "w:citation-manager-tool-save-time",
      "w:reference-point",
    ],
    grammarTopicId: "present-simple",
    phonicsRuleIds: ["ch", "sh", "al"],
    pattern: {
      titleZh: "句型：This builds on X's work on ___. / X et al. report that ___.",
      explainZh: "链式引用：承认前人 This builds on X's work…；多人署名 X et al.…；核对页码 cite the page。引用是加入对话，不是借光。",
      examples: [
        ["This builds on X's work on sleep architecture.", "这延续了 X 关于睡眠结构的研究。"],
        ["Kim et al. report that timing beats duration sign-ups.", "金等人报告签到时机比时长更重要。"],
        ["Check the page before you cite the claim.", "引用主张之前先核对页码。"],
      ],
      sentences: [
        ["A citation chain shows you read the room.", "引用链证明你读过全场。"],
        ["Citation managers turn hunting into collecting.", "引文管理器把打猎变成捡拾。"],
        ["Cite early, cite often, cite honestly.", "早引用、勤引用、老实引用。"],
      ],
    },
    reading: [
      ["Reference lists became the bibliography of a conversation.", "参考列表变成了对话的传记。"],
      ["Students who chained citations wrote deeper introductions.", "会串引用的学生写出了更深的引言。"],
      ["Mistitled references broke trust in the whole paper.", "标题错乱的引用毁掉整篇信任。"],
    ],
    writing: { zh: "写两句含引用表达且带出处的句子。", hintEn: "According to K&L…; This builds on X's work on ___." },
  },
  {
    day: 218,
    titleEn: "Evidence Grading",
    titleZh: "第 218 天 · 证据分级",
    goalZh: "按证据强度说话，给结论配上相称的证据。",
    vocabIds: [
      "w:real-world-evidence",
      "w:preponderance-evidence",
      "w:corroborate-evidence",
      "w:meta-analysis-synthesis",
      "w:substantiate-claims",
    ],
    grammarTopicId: "future-simple",
    phonicsRuleIds: ["ee", "gr", "oi"],
    pattern: {
      titleZh: "句型：The strongest evidence shows ___. / Weaker evidence suggests ___.",
      explainZh: "证据梯子：轶事 anecdote 垫底，案例 studies 中段，元分析 meta-analysis 顶上。给结论配好梯级：强证据用 shows，弱证据用 suggests。",
      examples: [
        ["The strongest evidence shows exercise cuts relapse.", "最强证据显示运动降低复发。"],
        ["Weaker evidence suggests early lunch helps.", "较弱证据提示午餐提前有助益。"],
        ["Anecdotes open doors; data close deals.", "轶事开门，数据成交。"],
      ],
      sentences: [
        ["Grade your evidence before you grade your prose.", "先给证据分级，再给文章分级。"],
        ["Show for the certain, suggest for the shaky.", "确定的用 show，摇晃的用 suggest。"],
        ["One meta-analysis outranks a hundred testimonials.", "一项元分析胜过一百条证言。"],
      ],
    },
    reading: [
      ["Reviewers matched every claim to its evidence tier.", "评审把每句话配到证据层级。"],
      ["Real-world evidence outvoted laboratory charm.", "真实世界证据压过实验室光环。"],
      ["Weak claims wearing strong verbs got rewritten.", "披着强动词的弱主张都被改写。"],
    ],
    writing: { zh: "写两个结论，一个用 shows 一个用 suggests。", hintEn: "Strong: ___ shows ___. Weak: ___ suggests ___." },
  },
  {
    day: 219,
    titleEn: "Hedging for Academics",
    titleZh: "第 219 天 · 学术缓冲",
    goalZh: "用程度词表达限定的断言并保住可信度。",
    vocabIds: [
      "w:conjecture-speculation",
      "w:nuance-argument",
      "w:stance",
      "w:knowledge-claims",
      "w:premise-n2",
    ],
    grammarTopicId: "negation",
    phonicsRuleIds: ["h", "ee", "r"],
    pattern: {
      titleZh: "句型：Evidence suggests that ___. / It may be that ___.",
      explainZh: "学术缓冲词表：probably / suggests / tends to / it may be that。限定不是含糊，是信用管理。未证实的断言配一定字眼。",
      examples: [
        ["Evidence suggests that naps beat coffee.", "证据提示午睡胜过咖啡。"],
        ["It may be that the effect is long-term.", "这种效应也许是长期性的。"],
        ["Demand tends to follow price, not morality.", "需求往往追随价格，而不是道德。"],
      ],
      sentences: [
        ["Hedges are the scholarship of uncertainty.", "缓冲词是对不确定性的学术处理。"],
        ["Unhedged claims read like ads, not papers.", "不加缓冲的断言读起来像广告。"],
        ["Perhaps is not a weakness; it is precision.", "perhaps 不是软弱，是精确。"],
      ],
    },
    reading: [
      ["Editors demanded hedges on every transfer claim.", "编辑要求每条迁移结论都加缓冲。"],
      ["The hedged abstract survived peer review.", "加了缓冲的摘要通过了同行评审。"],
      ["Learners circled absolute words and rewrote them.", "学员圈出绝对词并改写。"],
    ],
    writing: { zh: "把三句绝对断言改写为带缓冲的学术句。", hintEn: "X is… → Evidence suggests X…" },
  },
  {
    day: 220,
    titleEn: "Trend Lines",
    titleZh: "第 220 天 · 趋势描述",
    goalZh: "用转折词与幅度词准确描述数据曲线。",
    vocabIds: [
      "w:extrapolate-trends",
      "w:secular-trend",
      "w:urbanization-trend",
      "w:hypothesis-driven",
      "w:evidence-based-practice",
    ],
    grammarTopicId: "past-simple",
    phonicsRuleIds: ["tr", "st", "ee"],
    pattern: {
      titleZh: "句型：The rate rose steadily until ___. / It then plateaued and fell slightly.",
      explainZh: "趋势词库：上升 rose steadily / climbed；持平 plateaued / stayed flat；回落 dropped / fell slightly。先定方向，再给幅度，最后点节点。",
      examples: [
        ["The rate rose steadily until 2023, then plateaued.", "该比率稳步上升至 2023 年，随后持平。"],
        ["Sales fell slightly after the fee change.", "费用调整后销量小幅下滑。"],
        ["A secular trend should not be called a blip.", "长期趋势不该被称为小波动。"],
      ],
      sentences: [
        ["Trends need directions, magnitudes, and time stamps.", "趋势需要方向、幅度和时间戳。"],
        ["Extrapolate with a pencil, not a promise.", "外推要像铅笔可改，别像承诺。"],
        ["The plateau is a story, not a dead end.", "平台期是故事，不是死胡同。"],
      ],
    },
    reading: [
      ["Analysts described the dip before explaining it.", "分析师先描述拐点再解释。"],
      ["One misleading axis turned a rise into a fall.", "一根误导的坐标轴把上升画成了下降。"],
      ["Learners wrote five trend sentences from one chart.", "学员就一张图写五句趋势句。"],
    ],
    writing: { zh: "用趋势词描述生活中任何一个起伏。", hintEn: "X rose steadily until ___, then ___." },
  },
  {
    day: 221,
    titleEn: "Cause & Effect Map",
    titleZh: "第 221 天 · 因果图",
    goalZh: "区分强因果与弱关联，准确表达原因结果。",
    vocabIds: [
      "w:deduction-logic",
      "w:induction",
      "w:corroborate-evidence",
      "w:substantiate-claims",
      "w:assumptions",
    ],
    grammarTopicId: "past-simple",
    phonicsRuleIds: ["th-vd", "er", "oi"],
    pattern: {
      titleZh: "句型：A led to B. / B resulted from A. / That said, correlation is not causation.",
      explainZh: "因果句法：A led to B（原因在前）；B resulted from A（谓语被动）；紧接着提醒 correlation is not causation（相关≠因果）。",
      examples: [
        ["The fee hike led to a drop in weekday orders.", "涨价导致工作日订单下降。"],
        ["The outage resulted from a misconfigured router.", "这次中断源于路由器配置错误。"],
        ["That said, correlation is not causation.", "话说回来，相关不等于因果。"],
      ],
      sentences: [
        ["Name the mechanism, and the claim gets legs.", "说清机制，主张就有腿。"],
        ["After does not mean because.", "随后不代表因为。"],
        ["A good cause map carries both strength and direction.", "好的因果图既标强度也标方向。"],
      ],
    },
    reading: [
      ["Readers demanded the mechanism behind each claim.", "读者要求每条主张背后的机制。"],
      ["The study controlled for the usual suspects.", "研究控制了常见干扰变量。"],
      ["Reverse causes hid in plain sight.", "反向因果就藏在眼皮底下。"],
    ],
    writing: { zh: "写一个强因果句和一个弱关联提醒句。", hintEn: "A led to B. Yet correlation is not causation here." },
  },
  {
    day: 222,
    titleEn: "Definition Workshop",
    titleZh: "第 222 天 · 定义工坊",
    goalZh: "给抽象概念下边界清楚的可辩护定义。",
    vocabIds: [
      "w:reference-point",
      "w:typology-classification",
      "w:taxonomy-classification",
      "w:classification",
      "w:antithesis",
    ],
    grammarTopicId: "articles",
    phonicsRuleIds: ["sh", "ee", "st"],
    pattern: {
      titleZh: "句型：By X, I mean ___. / I define X as ___.",
      explainZh: "定义句式：界内 By X, I mean…；界外 X is not Y；给标准 I define X as…。定义是划圈，圈外圈内都要交代。",
      examples: [
        ["By remote work, I mean fully asynchronous, not hybrid.", "我这里说的远程，是完全异步，不是混合。"],
        ["I define burnout as mismatch, not tiredness.", "我把倦怠定义为错配，而不是疲累。"],
        ["A working definition admits its own border disputes.", "可用的定义承认自身有边界争议。"],
      ],
      sentences: [
        ["Definitions are fences with gates.", "定义是有门槛的围栏。"],
        ["Stipulate your terms, then argue inside the fence.", "先约定术语，再在围栏内辩论。"],
        ["Vague terms leak arguments.", "含混的词会漏掉论据。"],
      ],
    },
    reading: [
      ["The winning essay defined happiness before measuring it.", "获胜的文章先定义幸福再测量它。"],
      ["Taxonomies gave students a scaffold to sort talk types.", "分类学给了学生整理话语类型的脚手架。"],
      ["Antithesis sharpened the boundary of the concept.", "对照一词锐化了概念边界。"],
    ],
    writing: { zh: "为你常说的一个抽象词写下边界清楚的定义。", hintEn: "By ___, I mean ___, not ___." },
  },
  {
    day: 223,
    titleEn: "Compare & Contrast Scale",
    titleZh: "第 223 天 · 对比天平",
    goalZh: "用对称句法结构呈现异同，落点清晰。",
    vocabIds: [
      "w:antithesis",
      "w:counterclaim-integration",
      "w:both-sides-fallacy-critique",
      "w:concession-rebuttal-structure",
      "w:critique-balanced-review-essay",
    ],
    grammarTopicId: "articles",
    phonicsRuleIds: ["fl", "tr", "ee"],
    pattern: {
      titleZh: "句型：While A does X, B does Y. / A outperforms B on ___, but not on ___.",
      explainZh: "对比天平：对称句 While A does X, B does Y；决胜句 A outperforms B on…；平衡提醒 the comparison must include a criterion，缺少标准就是空比。",
      examples: [
        ["While paper costs less, tablets update instantly.", "纸便宜，但平板即时更新。"],
        ["A outperforms B on speed, but not on cost.", "A 在速度上胜过 B，在成本上却没有。"],
        ["Comparisons without criteria are gossip with data.", "没有标准的比较是带数据的八卦。"],
      ],
      sentences: [
        ["Equal structures make unequal facts visible.", "对称句式让不对称的事实显形。"],
        ["Name the yardstick before you claim victory.", "先报尺子再宣布胜利。"],
        ["Balanced reviews of two rows list both winners.", "两行的平衡评述要列出双方的赢面。"],
      ],
    },
    reading: [
      ["The compare essay died each time the yardstick changed.", "每换一次尺子，比较文就死一次。"],
      ["False balance gave unsupported views free seats.", "虚假平衡给无证据观点发免费座位。"],
      ["Learners built a contrast chart before writing.", "学员先画对比表再动笔。"],
    ],
    writing: { zh: "用对称句对比两个方案并给出一条标准。", hintEn: "While A does X, B does Y. On ___ only, A wins." },
  },
  {
    day: 224,
    titleEn: "Classification Cabinet",
    titleZh: "第 224 天 · 分类抽屉",
    goalZh: "用分类标准与互斥类别把复杂事物理清。",
    vocabIds: [
      "w:classification",
      "w:taxonomy-classification",
      "w:typology-classification",
      "w:subcategorization",
      "w:data-classification",
    ],
    grammarTopicId: "basic-clauses",
    phonicsRuleIds: ["oi", "ar", "st"],
    pattern: {
      titleZh: "句型：X falls into three categories. / Category A covers ___, whereas B ___.",
      explainZh: "分类句式：宣布分三类 X falls into three categories；互斥 Standard justifies the split；互补而全面 no item is left unassigned。分类标准先行。",
      examples: [
        ["Feedback falls into three categories.", "反馈分成三类。"],
        ["Category A covers praise, whereas B covers repair.", "A 类是表扬，B 类是修补。"],
        ["A good typology sorts every item without overlap.", "好的类型学既不重叠也不漏项。"],
      ],
      sentences: [
        ["State the criterion, then open the drawers.", "先报标准，再开抽屉。"],
        ["Overlapping categories smuggle confusion in.", "重叠类型走私混乱进来。"],
        ["Classification is argument with a filing cabinet.", "分类是带文件柜的论证。"],
      ],
    },
    reading: [
      ["The typology survived because its lines never crossed.", "类型学活下来是因为线条从不交叉。"],
      ["Reviewers found one unassigned case and smiled.", "评审找到一个没归类的案例就笑了。"],
      ["Data classification forced teams to define data first.", "数据分类逼团队先定义数据。"],
    ],
    writing: { zh: "把你抽屉里的东西按标准分成三类并说明互斥。", hintEn: "X falls into three classes: A (…), B (…), C (…)." },
  },
  {
    day: 225,
    titleEn: "Counterargument Dojo",
    titleZh: "第 225 天 · 反方道场",
    goalZh: "预判反驳并用让步-反击结构消化它。",
    vocabIds: [
      "w:counterclaim-integration",
      "w:concession-rebuttal-structure",
      "w:straw-man-fallacy-examples",
      "w:strawman-fallacy-label-misrepresentation",
      "w:both-sides-fallacy-critique",
    ],
    grammarTopicId: "negation",
    phonicsRuleIds: ["st", "gr", "er"],
    pattern: {
      titleZh: "句型：Critics may argue that ___. / While that is partly true, ___.",
      explainZh: "反方道场三式：先亮反方 Critics may argue…；让一截 While that is partly true…；再回马枪 the evidence points elsewhere。别树稻草人。",
      examples: [
        ["Critics may argue that the sample is small.", "批评者会说样本太小。"],
        ["While that is partly true, the effect still holds.", "这话部分成立，但效应依然成立。"],
        ["What counts is the real objection, not a scarecrow.", "要回应的是真反对，不是稻草人。"],
      ],
      sentences: [
        ["Steelman the opponent before you answer them.", "先给对手武装到最强再回应。"],
        ["A concession buys ten points of credibility.", "一次让步买十分可信。"],
        ["Fake counterarguments expose the writer, not the enemy.", "假反方暴露的是作者自己。"],
      ],
    },
    reading: [
      ["The rebuttal opened with the strongest version of criticism.", "反驳以最强的批评版本开场。"],
      ["Straw-man summaries lost the room instantly.", "稻草人总结瞬间失去全场。"],
      ["Reviewers felt respected when objections appeared first.", "反对先出场，评审感到被尊重。"],
    ],
    writing: { zh: "为你的论点写一句反方、一句让步、一句回击。", hintEn: "Critics claim X. Partly true… yet ___." },
  },
  {
    day: 226,
    titleEn: "Cohesion Glue",
    titleZh: "第 226 天 · 衔接胶水",
    goalZh: "用指代词与链接句把段落粘成整体。",
    vocabIds: [
      "w:cohesion",
      "w:coherent",
      "w:group-cohesion",
      "w:coreference-resolution",
      "w:reference-point",
    ],
    grammarTopicId: "pronouns-basic",
    phonicsRuleIds: ["ee", "th-vl", "fl"],
    pattern: {
      titleZh: "句型：This aligns with the point above. / That same logic applies to ___.",
      explainZh: "衔接胶水：指前文 this aligns with…；递逻辑 that same logic applies to…；报位置 as noted earlier。指代不清等于读者自己拼图。",
      examples: [
        ["This aligns with the point above about timing.", "这与上文关于时机的观点一致。"],
        ["That same logic applies to team size.", "同样的逻辑适用于团队规模。"],
        ["As noted earlier, the fee changed behavior.", "如前所述，费用改变了行为。"],
      ],
      sentences: [
        ["Cohesion is the glue; coherence is the logic.", "衔接是胶水，连贯是逻辑。"],
        ["Ambiguous pronouns make readers assemble puzzles.", "含混代词让读者自己拼图。"],
        ["Backward links rewrite the sentence above.", "回指句在替上文说话。"],
      ],
    },
    reading: [
      ["Paragraphs glued by referents read like one organism.", "被指代词粘住的段落读起来像同一生命体。"],
      ["Every this on the page demanded a clear ancestor.", "页面上每个 this 都要有清楚的前辈。"],
      ["Cohesion scores rose when writers replaced nouns with pronouns.", "换用代词后衔接分上升。"],
    ],
    writing: { zh: "写两句话，用指代词把后句粘到前句。", hintEn: "X is costly. That same logic applies to ___." },
  },
  {
    day: 227,
    titleEn: "Punctuation Discipline",
    titleZh: "第 227 天 · 标点纪律",
    goalZh: "用分号冒号连字符精确表达逻辑，减少长句事故。",
    vocabIds: [
      "w:proofread-typo-assassin-final-gate-duty",
      "w:coherent",
      "w:concise-cut-adjectives-payroll-halving",
      "w:cohesion",
      "w:meticulous-tiny-details-organized-love-language",
    ],
    grammarTopicId: "basic-clauses",
    phonicsRuleIds: ["ee", "st", "oi"],
    pattern: {
      titleZh: "句型：X did Y; Z followed. / Note the contrast: ___.",
      explainZh: "标点升级：分号连排比 X did Y; Z followed；冒号给解释 Note the contrast:…；破折号插旁白。一个标点就是一段逻辑。",
      examples: [
        ["She wrote; the deadline waited.", "她在写；截止日期在等。"],
        ["Note the contrast: delay raised every cost.", "注意反差：延误抬高了所有成本。"],
        ["Two clauses, one breath, zero and.", "两个分句、一口气、零个 and。"],
      ],
      sentences: [
        ["Semicolons pair equals; colons reveal.", "分号配对等，冒号揭序幕。"],
        ["Punctuation is cheap logic on the page.", "标点是纸上廉价的逻辑。"],
        ["One typo can sack a conclusion.", "一个错字就能撤掉一个结论。"],
      ],
    },
    reading: [
      ["Semicolon-rich abstracts scored as more analytical.", "分号丰富的摘要被认为更有分析力。"],
      ["Colons focused readers before the payoff line.", "冒号在点题句前把读者聚焦。"],
      ["Proofreaders caught the comma that changed meaning.", "校对抓住了改变含义的那个逗号。"],
    ],
    writing: { zh: "用分号与冒号各写一句含逻辑关系的句子。", hintEn: "A did X; B did Y. The rule: ___." },
  },
  {
    day: 228,
    titleEn: "Nominalizing for Formality",
    titleZh: "第 228 天 · 名词化升级",
    goalZh: "把动词句改写为名词化结构以提升正式度。",
    vocabIds: [
      "w:abstract-concise",
      "w:antithesis",
      "w:register-formal-versus-casual-switching",
      "w:concise-cut-adjectives-payroll-halving",
      "w:coherent",
    ],
    grammarTopicId: "articles",
    phonicsRuleIds: ["er", "ee", "th-vd"],
    pattern: {
      titleZh: "句型：S(he) needs to decide → The decision requires ___. / Ceasing X, they ___.",
      explainZh: "名词化配方：某人需要决定→决策需要…；它上升了→上升正在发生。名词让主语变抽象，人也退出前台，正式感立现。",
      examples: [
        ["The decision requires board approval.", "该决定需要董事会批准。"],
        ["The rise in fees followed the change in rules.", "费用上涨紧随规则变更。"],
        ["Nominalization trades warmth for precision.", "名词化用温度换精度。"],
      ],
      sentences: [
        ["Nouns freeze actions into inspectable objects.", "名词把动作冻成可检查的对象。"],
        ["Too many nouns freeze the page solid.", "名词太多会把纸面冻成固体。"],
        ["Formal prose reports; conversation narrates.", "正式文在报告，聊天在讲述。"],
      ],
    },
    reading: [
      ["Policy writers nouned their way to neutrality.", "政策写手靠名词化走向中立。"],
      ["The abstract preferred expressions to people.", "摘要更爱表达而非人。"],
      ["Learners converted five verbs into five nouns.", "学员把五个动词变成五个名词。"],
    ],
    writing: { zh: "把一个动词句改写成名词化版本。", hintEn: "We decided… → The decision…" },
  },
  {
    day: 229,
    titleEn: "Academic Emails",
    titleZh: "第 229 天 · 学术邮件",
    goalZh: "给导师与教授写简洁礼貌有依据的邮件。",
    vocabIds: [
      "w:thesis-advisor-weekly-meetings",
      "w:citations-conventions",
      "w:citation-integrity-check",
      "w:expedite",
      "w:proofread-typo-assassin-final-gate-duty",
    ],
    grammarTopicId: "future-simple",
    phonicsRuleIds: ["ee", "tr", "al"],
    pattern: {
      titleZh: "句型：I am writing to ask about ___. / Would it be possible to ___?",
      explainZh: "学术邮件事务化：直奔主题 I am writing to ask…；柔化请求 Would it be possible…；给出时限 by Friday。邮件是公文，不是抒情。",
      examples: [
        ["I am writing to ask about the extension policy.", "我去信想询问延期政策。"],
        ["Would it be possible to meet briefly this week?", "这周能否简短见一面？"],
        ["Could you let me know by Friday?", "能否在周五前告诉我？"],
      ],
      sentences: [
        ["One request per email, stated by line three.", "一封邮件一件事，第三行见分晓。"],
        ["The subject line is the first paragraph.", "主题行就是第一段。"],
        ["Proofread once for the reader, twice for yourself.", "替读者校对一遍，再替自己一遍。"],
      ],
    },
    reading: [
      ["Professors answered pithy emails within a day.", "教授一天内回复了的简短邮件。"],
      ["Wall-of-text messages ended up in the maybe pile.", "文字墙走进了待定区。"],
      ["A respectful deadline helped both schedules.", "礼貌的时限让双方日程都受益。"],
    ],
    writing: { zh: "写一封三行直奔主题的请求邮件。", hintEn: "Subject… I am writing to ask… Would it be possible…" },
  },
  {
    day: 230,
    titleEn: "Decoding Assignments",
    titleZh: "第 230 天 · 审题与评分表",
    goalZh: "拆解题干关键词并按评分标准分配精力。",
    vocabIds: [
      "w:thesis-statement",
      "w:thesis-argumentation",
      "w:argument-structure",
      "w:substantiate-claims",
      "w:critique-balanced-review-essay",
    ],
    grammarTopicId: "questions",
    phonicsRuleIds: ["oi", "st", "ee"],
    pattern: {
      titleZh: "句型：The prompt asks me to ___. / The rubric rewards ___ most.",
      explainZh: "审题拆解：动作词 The prompt asks me to…（argue/summarize/compare）；评分表 The rubric rewards… most。先看懂考什么再动笔。",
      examples: [
        ["The prompt asks me to evaluate, not to describe.", "题干要的是评价，不是描述。"],
        ["The rubric rewards the counterargument section most.", "评分表最奖励反方段落。"],
        ["Analyze means cut; synthesize means join.", "分析是切开，综合是缝合。"],
      ],
      sentences: [
        ["Read the prompt three times, once per question word.", "逐词读题干三遍。"],
        ["The rubric is the teacher's hidden syllabus.", "评分表是老师隐藏的教学大纲。"],
        ["Time spent on the wrong task is invisible marks lost.", "耗在错任务上的时间是悄悄流失的分。"],
      ],
    },
    reading: [
      ["Students who decoded first scored higher.", "先拆题的学生得分更高。"],
      ["Argument prompts penalized pure summaries.", "论证题会惩罚纯总结。"],
      ["Rubric-first writers shipped faster and steadier.", "先读评分表的人写得又快又稳。"],
    ],
    writing: { zh: "拆解任一作业题干并指出你要完成的动作。", hintEn: "The prompt asks me to ___; the rubric rewards ___." },
  },
  {
    day: 231,
    titleEn: "Peer-Review Pairs",
    titleZh: "第 231 天 · 互助互评",
    goalZh: "用固定规程给出既诚实又建设性的互评。",
    vocabIds: [
      "w:peer-review",
      "w:peer-review-process",
      "w:critique-balanced-review-essay",
      "w:citation-integrity-check",
      "w:proofread-typo-assassin-final-gate-duty",
    ],
    grammarTopicId: "questions",
    phonicsRuleIds: ["pl", "ee", "st"],
    pattern: {
      titleZh: "句型：The clearest part was ___. / This claim would land better if ___.",
      explainZh: "互评规程：先亮最清楚处 The clearest part…；再提一处改进 This claim would land better if…；最后核对引用。评得动刀，眼神友好。",
      examples: [
        ["The clearest part was the opening example.", "最清楚的是开头的例子。"],
        ["This claim would land better if you named the source.", "这句话点了来源会更有力。"],
        ["Give the feedback you'd want to receive.", "给出你也愿意收到的那种反馈。"],
      ],
      sentences: [
        ["Specific beats pleasant in every review.", "具体永远胜过客套。"],
        ["Review the draft, not the person.", "评初稿，不评人。"],
        ["Two compliments and one scalpel is a recipe.", "两句表扬一把手术刀，就是配方。"],
      ],
    },
    reading: [
      ["Pairs who exchanged checklists wrote cleaner finals.", "交换清单的搭档写出更干净的定稿。"],
      ["Anonymous peer review broke the politeness spell.", "匿名互评打破了客套符咒。"],
      ["One precise sentence beat a page of praise.", "一句精准胜过一页表扬。"],
    ],
    writing: { zh: "按规程给一个同学的段落写三条互评。", hintEn: "Clearest: ___. Would land better if: ___. Quote check: ___." },
  },
  {
    day: 232,
    titleEn: "Outline First",
    titleZh: "第 232 天 · 提纲先行",
    goalZh: "写提纲再动笔，让论证顺序先于措辞。",
    vocabIds: [
      "w:skeleton",
      "w:argument-structure",
      "w:premise-n2",
      "w:hypothesis-driven",
      "w:coherent",
    ],
    grammarTopicId: "present-simple",
    phonicsRuleIds: ["oi", "th-vl", "ee"],
    pattern: {
      titleZh: "句型：The structure is: claim → evidence → bridge. / Section 2 will cover ___.",
      explainZh: "提纲三行：主张 claim；证据 evidence；搭桥 bridge。先排论证顺序再填句子，写提纲的时间会在修改阶段加倍还你。",
      examples: [
        ["The structure is claim, evidence, counter claim, bridge.", "结构是主张、证据、反方、搭桥。"],
        ["Section 2 will cover the fee change.", "第二节将覆盖费用变更。"],
        ["An outline is a map; the draft is the road.", "提纲是地图，初稿是路。"],
      ],
      sentences: [
        ["Move the logic in the outline, not in the draft.", "在提纲里搬逻辑，别在初稿里搬。"],
        ["If the outline bores you, the essay will too.", "提纲让你无聊，文章也会。"],
        ["Every dashed bullet is a debt to repay.", "每个虚点都是要还的债。"],
      ],
    },
    reading: [
      ["Outline-first writers rewrote whole drafts half as often.", "先提纲的人整篇重写次数减半。"],
      ["The wrong order was fixed in minutes, not days.", "错误顺序几分钟就调整完，不用几天。"],
      ["Teachers read outlines like blood pressure charts.", "老师读提纲像读血压图。"],
    ],
    writing: { zh: "为你选定的论点写三行提纲。", hintEn: "Claim… Evidence… Bridge…" },
  },
  {
    day: 233,
    titleEn: "Draft Without the Editor",
    titleZh: "第 233 天 · 初稿不停笔",
    goalZh: "隔离初稿与编辑两种心智，先写完再改好。",
    vocabIds: [
      "w:revise-edit-without-mercy-pass",
      "w:concise-cut-adjectives-payroll-halving",
      "w:skeleton",
      "w:planning-fallacy",
      "w:coherent",
    ],
    grammarTopicId: "future-simple",
    phonicsRuleIds: ["ee", "gr", "st"],
    pattern: {
      titleZh: "句型：First draft equals finished is a lie. / Let it be bad for 25 minutes.",
      explainZh: "两段式写作：初稿别当编辑器 First draft = finished 是谎言；倒计时 25 分钟 Let it be bad for 25 minutes；第二快写法先续完再回头改。",
      examples: [
        ["First draft equals finished is a comfortable lie.", "初稿等于定稿是个舒服的谎言。"],
        ["Let it be bad for 25 minutes, then edit.", "先允许它烂 25 分钟，再修改。"],
        ["The plan fallacy promises drafts in half the real time.", "规划谬误永远把初稿时间估少一半。"],
      ],
      sentences: [
        ["Separate writer and editor into two sittings.", "把写手和编辑分到两场工作。"],
        ["A messy first draft is a completed thought.", "蓬乱的初稿是完整的想法。"],
        ["Perfection at page one kills page ten.", "第一页的完美杀死第十页。"],
      ],
    },
    reading: [
      ["Writers who banned editing while drafting finished sooner.", "初稿禁改的人更早写完。"],
      ["The 25-minute bad draft outproduced three careful hours.", "25 分钟的烂稿胜过三小时的精雕。"],
      ["Planning fallacy ate every free afternoon.", "规划谬误吃掉了每一个空闲下午。"],
    ],
    writing: { zh: "用 25 分钟倒计时写出你的初稿第一段，不回头修改。", hintEn: "Timer on. Write ___ even if it is ugly." },
  },
  {
    day: 234,
    titleEn: "Revise Like an Editor",
    titleZh: "第 234 天 · 主编式修改",
    goalZh: "用删除、合并、重排三层修改把初稿升级。",
    vocabIds: [
      "w:revise-edit-without-mercy-pass",
      "w:proofread-typo-assassin-final-gate-duty",
      "w:concise-cut-adjectives-payroll-halving",
      "w:coherent",
      "w:meticulous-tiny-details-organized-love-language",
    ],
    grammarTopicId: "past-simple",
    phonicsRuleIds: ["st", "ee", "oi"],
    pattern: {
      titleZh: "句型：Delete the sentence that does no work. / Merge ___ into the paragraph before it.",
      explainZh: "修改三层：删 Delete the sentence that does no work；并 Merge…；排 Reorder by argument。先结构再措辞最后标点。",
      examples: [
        ["Delete the sentence that does no work.", "删掉不干活的句子。"],
        ["Merge the last paragraph into the earlier one.", "把末段并进前面的段落。"],
        ["Cut adjectives in halves; keep the verbs whole.", "形容词减半，动词保持完整。"],
      ],
      sentences: [
        ["Editing is courage with a delete key.", "修改是有 Delete 键的勇气。"],
        ["The second pass is where writers are made.", "第二遍才是作家的诞生地。"],
        ["Every vague adverb hides a concrete verb running away.", "每个含糊副词都在掩护逃跑的实义动词。"],
      ],
    },
    reading: [
      ["Cut-first revisions revealed hidden strengths.", "先删后修暴露了潜在的优势。"],
      ["Merged paragraphs gained muscle and lost fat.", "合并后的段落长肌肉掉脂肪。"],
      ["Typos at the gates cost the final impression.", "门口错字伤最后印象。"],
    ],
    writing: { zh: "初稿上做一次删除、一次合并、一次重排。", hintEn: "Deleted X… Merged Y… Reordered Z…" },
  },
  {
    day: 235,
    titleEn: "Evidence Audit",
    titleZh: "第 235 天 · 证据审计",
    goalZh: "逐句核对主张与证据是否相称、出处是否可靠。",
    vocabIds: [
      "w:substantiate-claims",
      "w:corroborate-evidence",
      "w:bear-out-claim-evidence",
      "w:real-world-evidence",
      "w:evidence-based-practice",
    ],
    grammarTopicId: "past-simple",
    phonicsRuleIds: ["ee", "st", "ar"],
    pattern: {
      titleZh: "句型：The claim is supported by ___. / The evidence bears out ___, but not ___.",
      explainZh: "证据审计三步：逐句标主张 mark every claim；配证据 pair each claim with its support；查断层 the gaps face the knife。证据配不上就改说法。",
      examples: [
        ["The claim is supported by two independent studies.", "该主张有两项独立研究佐证。"],
        ["The evidence bears out the effect on prices, not on wages.", "证据支撑价格效应，不支撑工资效应。"],
        ["An audit grades every sentence by its receipts.", "审计按收据给每个句子打分。"],
      ],
      sentences: [
        ["Unsupported claims are decoration wearing a suit.", "无据的主张是穿西装的装饰。"],
        ["Match the load of the claim to the strength of the source.", "主张的斤两要配得上来源的强度。"],
        ["Real-world data beats recycled opinion.", "真实世界数据胜过翻新的观点。"],
      ],
    },
    reading: [
      ["The audit found one orphan claim per page.", "审计发现每页一个无依的主张。"],
      ["Strong verbs got demoted where evidence wobbled.", "证据摇晃处，强动词被降级。"],
      ["Receipt-carrying paragraphs sailed through review.", "带收据的段落顺利过审。"],
    ],
    writing: { zh: "挑两句初稿逐句标注：本句的主张与证据。", hintEn: "Claim: ___. Evidence: ___. Fit: strong/weak." },
  },
  {
    day: 236,
    titleEn: "Abstract Elevator",
    titleZh: "第 236 天 · 摘要电梯",
    goalZh: "用几句话讲清目的方法与发现，让人一眼懂。",
    vocabIds: [
      "w:abstract-concise",
      "w:thesis-statement",
      "w:skeleton",
      "w:concise-cut-adjectives-payroll-halving",
      "w:coherent",
    ],
    grammarTopicId: "present-simple",
    phonicsRuleIds: ["ee", "fl", "st"],
    pattern: {
      titleZh: "句型：We examined ___. / We found that ___. / The implication is ___.",
      explainZh: "摘要五句：背景 gap；目的 we examined…；方法 we surveyed…；发现 we found that…；含义 the implication is…。电梯里能讲清的摘要才是好摘要。",
      examples: [
        ["We examined how fee timing shifts orders.", "我们考察了收费时点如何改变订单。"],
        ["We found that early fees reduced cancellations.", "我们发现早期收费减少退订。"],
        ["The implication is that defaults shape behavior.", "含义是默认选项塑造行为。"],
      ],
      sentences: [
        ["An abstract is the paper in an elevator.", "摘要就是电梯里的论文。"],
        ["Every abstract sentence must survive a question.", "摘要每句都要经得起追问。"],
        ["Methods sketched, findings measured, implications timed.", "方法速写，发现量化，含义卡点。"],
      ],
    },
    reading: [
      ["Busy reviewers read only the abstract and cited it.", "忙碌的评审只读摘要就引用它。"],
      ["The five-sentence abstract won the reading race.", "五句摘要赢得阅读竞赛。"],
      ["Writers who drafted abstracts last wrote clearer ones.", "最后写摘要的人写得更清楚。"],
    ],
    writing: { zh: "为你的任何主张写五句摘要。", hintEn: "Gap… We examined… We found… Implication…" },
  },
  {
    day: 237,
    titleEn: "Presenting Your Paper",
    titleZh: "第 237 天 · 论文汇报",
    goalZh: "把论文讲成故事：动机、发现、门槛。",
    vocabIds: [
      "w:eye-contact-confidence-calibration-by-culture-map",
      "w:hesitate-two-second-buy-time-move",
      "w:eloquent-speeches-quote-worthy-sentences",
      "w:stage-fright-cold-hands-cure",
      "w:point-of-information-raised",
    ],
    grammarTopicId: "future-simple",
    phonicsRuleIds: ["st", "ee", "j"],
    pattern: {
      titleZh: "句型：Before we get to the findings, the question was ___. / What surprised us was ___.",
      explainZh: "论文汇报叙事线：先讲问题 Before we get to the findings…；再亮惊喜 What surprised us…；最后留问题预计 Q&A。汇报结构上先讲人话。",
      examples: [
        ["Before we get to the findings, the question was cost.", "在讲发现之前，先说要回答的问题是成本。"],
        ["What surprised us was the plateau at week three.", "最让我们意外的是第三周的平原期。"],
        ["Two-second pauses tuned the room's attention.", "两秒停顿在调全场注意力。"],
      ],
      sentences: [
        ["Motivate before you excavate.", "先给动机，再挖数据。"],
        ["Stage fright is adrenaline mislabeled.", "怯场是被贴错标签的肾上腺素。"],
        ["Anticipate the Q&A and write your three answers.", "预判问答，写下三个答案。"],
      ],
    },
    reading: [
      ["Story-shaped presentations outremembered data dumps.", "故事型汇报比数据倾倒更让人记住。"],
      ["One pause a slide kept ten audiences awake.", "每页一次停顿保住十个听众清醒。"],
      ["The surprise slide sparked the best questions.", "惊喜页引发了最好的提问。"],
    ],
    writing: { zh: "为你的论文写开场三句与一句惊喜句。", hintEn: "The question was… What surprised us was…" },
  },
  {
    day: 238,
    titleEn: "Data & Diagrams",
    titleZh: "第 238 天 · 图表语言",
    goalZh: "用完整句描述图表并把视觉信息翻译成文字。",
    vocabIds: [
      "w:extrapolate-trends",
      "w:secular-trend",
      "w:data-classification",
      "w:evidence-based-practice",
      "w:hypothesis-testing",
    ],
    grammarTopicId: "present-progressive",
    phonicsRuleIds: ["tr", "oi", "ee"],
    pattern: {
      titleZh: "句型：The chart shows ___. / The striking figure is ___.",
      explainZh: "图表整句：说出图名 The chart shows…；点出亮点 The striking figure is…；交代单位 the axis is in percent。图不说人话就白挂。",
      examples: [
        ["The chart shows a steady climb until March.", "图表显示直到三月都在稳步上升。"],
        ["The striking figure is the 40 percent dip in June.", "醒目的是六月百分之四十的回落。"],
        ["Never make the reader hunt for the units.", "别让读者去找单位。"],
      ],
      sentences: [
        ["A caption is a sentence about a picture.", "图注是一句关于图的话。"],
        ["Color should encode data, not decorate it.", "颜色该编码数据，不该装饰。"],
        ["An honest axis is worth a hundred footnotes.", "诚实的坐标准则抵一百个脚注。"],
      ],
    },
    reading: [
      ["Slides with sentence captions needed zero talk.", "带整句标题的幻灯片一句都不用讲。"],
      ["Three-dimensional charts hid honest numbers.", "三维图表藏起了诚实的数字。"],
      ["Learners described a chart before analyzing it.", "学员先描述再分析一张图。"],
    ],
    writing: { zh: "用两句完整句描述一张你熟悉的图表。", hintEn: "The chart shows ___. The striking figure is ___." },
  },
  {
    day: 239,
    titleEn: "Case Synthesis",
    titleZh: "第 239 天 · 案例综合",
    goalZh: "把零散案例合成完整论证，区分事实与解释。",
    vocabIds: [
      "w:meta-analysis-synthesis",
      "w:critique-balanced-review-essay",
      "w:thesis-argumentation",
      "w:counterclaim-integration",
      "w:knowledge-claims",
    ],
    grammarTopicId: "basic-clauses",
    phonicsRuleIds: ["oi", "st", "ee"],
    pattern: {
      titleZh: "句型：Across cases, the pattern is ___. / The cases agree on ___, but differ on ___.",
      explainZh: "综合句式：一句话横切 Across cases, the pattern is…；同异分表 The cases agree on…, but differ on…。结论要说清是事实还是解释。",
      examples: [
        ["Across cases, the pattern is late fees driving earlier orders.", "跨案例看，模式是晚罚早买。"],
        ["The cases agree on the trigger, but differ on the cure.", "案例对诱因一致，对解法分歧。"],
        ["Classification, not anecdotes, earns the conclusion.", "赢得结论的是分类，不是轶事。"],
      ],
      sentences: [
        ["Synthesis is the essay of essays.", "综合是论文套论文。"],
        ["Say which part is fact and which is reading.", "说清哪部分是事实，哪部分是解读。"],
        ["Three cases can suggest; only data can insist.", "三个案例只能提示，数据才能断言。"],
      ],
    },
    reading: [
      ["Synthesized cases read as one argument, not three reports.", "综合后的案例读起来是一个论证，不是三份报告。"],
      ["The strongest synthesis named its own limits.", "最强的综合主动说出自己的边界。"],
      ["Reviewers rewarded the pattern statement over the recap.", "评审奖励模式句而不是复述。"],
    ],
    writing: { zh: "用跨案例句式把你的两个例子合并成一句论证。", hintEn: "Across cases, the pattern is ___. They agree… differ…" },
  },
  {
    day: 240,
    titleEn: "Block B Review & Assessment",
    titleZh: "第 240 天 · 学术写作总结与测评",
    goalZh: "复盘 211-239 天写作技能并完成一次自评与规划。",
    vocabIds: [
      "w:peer-review-process",
      "w:thesis-statement",
      "w:paraphrase-same-meaning-new-clothes-skill",
      "w:cohesion",
      "w:citation-integrity-check",
    ],
    grammarTopicId: "basic-clauses",
    phonicsRuleIds: ["st", "ee", "oi"],
    pattern: {
      titleZh: "句型：My writing win this block was ___. / The rubric I keep on my desk is ___.",
      explainZh: "写作终测：回顾 211-239 天的七个环（语域、论点、段落、释义、证据、审题、修改）；各环自评 1-5 分；挑一个要带去 C 块的技能。",
      examples: [
        ["My writing win this block was the rubric habit.", "这一块我最大进步是养成了读评分表的习惯。"],
        ["The rubric I keep on my desk lists evidence grading.", "我贴在桌上的评分表列着证据分级。"],
        ["I rated my citation chain 4 out of 5.", "我的引用链我给 4 分（满分 5）。"],
      ],
      sentences: [
        ["Self-review is the highest-stake peer review.", "自我回顾是最高规格的互评。"],
        ["Keep the win, the gap, and one next skill.", "保留战果、差距和一个下一步技能。"],
        ["Block C will weaponize this block's argument tools.", "C 块要把这块的论证工具用起来。"],
      ],
    },
    reading: [
      ["Block B built thesis, paragraph, evidence, and email skills.", "本块搭建论点、段落、证据与邮件技能。"],
      ["The final task bundled paraphrase, citation, and rubric.", "终测捆绑了释义、引用与评分表。"],
      ["Writers audiotaped their abstract as a speaking final.", "学员把摘要录音当作口语终测。"],
    ],
    writing: { zh: "写一封信：本块最好的习惯、最大差距、带走的技能。", hintEn: "This block, I ___ . I'm taking ___ into Block C." },
  },
];