import type { CourseDayPlan } from "@/content/pipeline/generate-days";

/**
 * Phase 23 · Day 181-210 — Block A 口语流利度（Spoken Fluency）。
 * B2→C1 口语音系（元音、重音、连读、省略）、会话管理（停顿、拉回、修正、
 * 寒暄、意见软化、辩论动作），全部引用真实 C1/C2 词汇、12 个语法话题与
 * 音标规则库，供 check-360-day-content-quality.cjs 校验。
 */
export const PLAN_181_210: readonly CourseDayPlan[] = [
  {
    day: 181,
    titleEn: "Vowel Clarity",
    titleZh: "第 181 天 · 元音清晰度",
    goalZh: "区分四组易混长元音与短元音并用于朗读。",
    vocabIds: [
      "w:pronunciation-drill-minimal-pair-practice",
      "w:accent-regional-melody-of-words",
      "w:fluency-speed-with-control-balance",
      "w:syllable",
      "w:rhythm",
    ],
    grammarTopicId: "be-verb",
    phonicsRuleIds: ["a-short", "e-short", "ee", "ai"],
    pattern: {
      titleZh: "句型：That vowel is short/long here. / Compare ___ and ___.",
      explainZh: "元音训练话术：指出长短 That vowel is short here；对比最小对立对 Compare /iː/ and /ɪ/。先把嘴形做夸张再放回自然语速。",
      examples: [
        ["Compare the long vowels in 'seat' and 'beat'.", "对比 seat 和 beat 里的长元音。"],
        ["That vowel is short here, not long.", "这里的元音是短音不是长音。"],
        ["Pull the mouth wide for /iː/.", "发 /iː/ 时嘴角要往两边拉开。"],
      ],
      sentences: [
        ["Long vowels stretch, short vowels snap.", "长元音要拉长，短元音要干脆。"],
        ["Minimal pairs train the ear first.", "最小对立对先练耳朵。"],
        ["Sound exaggerated now, natural later.", "现在夸张，之后自然。"],
      ],
    },
    reading: [
      ["Vowel drills started with four pairs.", "元音训练从四对发音开始。"],
      ["Students marked stress on every syllable.", "学生给每个音节标了重音。"],
      ["Clear vowels made the accent regional, not wrong.", "清晰的元音让口音显得有地域感而不是错误。"],
    ],
    writing: { zh: "写一对你最常混淆的元音及你的发声口诀。", hintEn: "I confuse ___ and ___; my tip is ___." },
  },
  {
    day: 182,
    titleEn: "Consonant Precision",
    titleZh: "第 182 天 · 辅音精度",
    goalZh: "掌握齿音、齿龈音与唇齿音在词首词尾的差别。",
    vocabIds: [
      "w:phoneme",
      "w:speech-prosody",
      "w:pronunciation-drill-minimal-pair-practice",
      "w:cognitive-fluency",
      "w:articulate-thoughts-into-clean-sentences-skill",
    ],
    grammarTopicId: "present-simple",
    phonicsRuleIds: ["th-vl", "th-vd", "sh", "ch", "v"],
    pattern: {
      titleZh: "句型：Push air through the teeth. / The final sound is ___.",
      explainZh: "辅音要领：齿音要“过齿而出” Push air through the teeth；描述词尾音 The final sound is /θ/。宁可放慢也要咬到位。",
      examples: [
        ["Push air through the teeth for /θ/.", "发 /θ/ 要让气流从齿间穿过。"],
        ["The final sound is voiced here.", "这里的末尾辅音是浊音。"],
        ["Touch the ridge behind your upper teeth for /t/.", "发 /t/ 时舌尖抵上齿龈。"],
      ],
      sentences: [
        ["Voiced consonants make the throat hum.", "浊辅音让喉咙发麻。"],
        ["Ending sounds matter in past-tense verbs.", "词尾音在一般过去时里尤其要紧。"],
        ["Slow beats smooth when precision is the goal.", "练精度时慢胜过顺。"],
      ],
    },
    reading: [
      ["Three is not tree; thank is not sank.", "three 不是 tree，thank 不是 sank。"],
      ["Final /d/ marks the past tense by voice.", "词尾 /d/ 靠声带振动标记过去时。"],
      ["Learners marked voiced and voiceless pairs.", "学员标记了浊音与清音对。"],
    ],
    writing: { zh: "用一句话写出 陈述句过去式词尾读 /d/、/t/、/ɪd/ 的三条规则。", hintEn: "After voiced sounds → /d/; after voiceless → /t/; after t/d → /ɪd/." },
  },
  {
    day: 183,
    titleEn: "Word Stress",
    titleZh: "第 183 天 · 词重音",
    goalZh: "掌握词重音位置并让重读音节更响亮饱满。",
    vocabIds: [
      "w:tone-language-pitch",
      "w:syllable",
      "w:intonation",
      "w:rhythm",
      "w:fluency-speed-with-control-balance",
    ],
    grammarTopicId: "countable-uncountable",
    phonicsRuleIds: ["er", "al", "or"],
    pattern: {
      titleZh: "句型：The stress falls on ___. / Stretch the stressed syllable.",
      explainZh: "词重音：指出位置 The stress falls on the first syllable；加强动作 Stretch the stressed syllable。重音错位是中式口音的主因。",
      examples: [
        ["The stress falls on the second syllable of 'address'.", "address 的重音在第二个音节。"],
        ["Stretch the stressed syllable, squeeze the rest.", "拉长重读音节，压缩其余音节。"],
        ["Stress moves when the word changes class.", "词性变化时重音会移动。"],
      ],
      sentences: [
        ["One syllable gets the beat.", "一个音节承担节拍。"],
        ["Unstressed vowels shrink to schwa.", "非重读元音会弱化成中央元音。"],
        ["Record your own word, then check the map.", "先自己读一遍，再对照词典标注重音。"],
      ],
    },
    reading: [
      ["Noun and verb pairs shift stress.", "名词与动词同形词靠重音区分。"],
      ["Foreign names trip the best speakers.", "外语人名连高手也会读错重音。"],
      ["Wrong stress changes one word into another.", "重音放错就会把词读成另一个词。"],
    ],
    writing: { zh: "写出三对“名动开重音”的单词（REcord / reCORD）。", hintEn: "REcord (n.) vs reCORD (v.): ___." },
  },
  {
    day: 184,
    titleEn: "Sentence Stress",
    titleZh: "第 184 天 · 句重音",
    goalZh: "让句子里的实义词响亮、虚词弱化，传递真实意图。",
    vocabIds: [
      "w:sarcastic-vs-sardonic-tone",
      "w:intonation",
      "w:speech-prosody",
      "w:rhythm",
      "w:register-formal-versus-casual-switching",
    ],
    grammarTopicId: "articles",
    phonicsRuleIds: ["ee", "ai", "oa"],
    pattern: {
      titleZh: "句型：The stress lands on the new information. / Emphasize ___.",
      explainZh: "句重音规则：新信息扛重音 The stress lands on the new info；强调动作 Emphasize the verb。同样一句话换重音就是换意思。",
      examples: [
        ["The stress lands on the newest information.", "重音落在最新的信息上。"],
        ["Emphasize the word you'd underline in text.", "强调你在纸上会画下划线那个词。"],
        ["Function words stay light and quick.", "功能词保持轻读快读。"],
      ],
      sentences: [
        ["You said MY car, or just a car?", "你说的是我的车，还是随便一辆车？"],
        ["Stress is the strongman of meaning.", "重音是意义的举重选手。"],
        ["Reduce prepositions to a whisper.", "介词轻到像耳语。"],
      ],
    },
    reading: [
      ["Same sentence, four stress points, four meanings.", "同一句话四种重音四种意思。"],
      ["Learners found contrast stress hardest.", "对比重音最难掌握。"],
      ["Recording exposed swallowed content words.", "录音暴露了被吞掉的实义词。"],
    ],
    writing: { zh: "写一句句子并标注你重读的词及原因。", hintEn: "I/You/We ___ because ___." },
  },
  {
    day: 185,
    titleEn: "Linking Sounds",
    titleZh: "第 185 天 · 连读音",
    goalZh: "掌握辅音接元音的连读并摆脱一个词一停的西式节奏。",
    vocabIds: [
      "w:elision",
      "w:register-formal-versus-casual-switching",
      "w:speech-prosody",
      "w:rhythm",
      "w:conversational-structure",
    ],
    grammarTopicId: "present-progressive",
    phonicsRuleIds: ["l", "r", "w", "y-cons"],
    pattern: {
      titleZh: "句型：Carry the final sound into the next word. / Hold ___ to ___.",
      explainZh: "连读：把词尾辅音“送进”下一个词的元音 Carry the final sound into the next word。先慢速读通再加快，别为了连读吞音。",
      examples: [
        ["Carry the final sound into the next word.", "把词尾音送进下一个词。"],
        ["'Turn off' sounds like 'tur-noff'.", "turn off 连起来像 tur-noff。"],
        ["Link, but never drop the meaning.", "可以连读，不能丢意思。"],
      ],
      sentences: [
        ["English flows at word boundaries.", "英语在词与词的交界处流动。"],
        ["Linking hides word boundaries from learners' ears.", "连读把词界藏了起来，所以更要练听。"],
        ["Practice the phrase, not the word.", "练短语，不练孤词。"],
      ],
    },
    reading: [
      ["Linking turns two words into one breath.", "连读把两个词合成一口气。"],
      ["Listeners guessed wrong borders between words.", "听者常猜错词的边界。"],
      ["Slow dictation then fast replay cured it.", "先慢听写再快放回放治好了边界问题。"],
    ],
    writing: { zh: "写三个“辅+元”连读短语并标出连读位置。", hintEn: "turn⃗off, come⃗in: ___." },
  },
  {
    day: 186,
    titleEn: "Elision & Reduction",
    titleZh: "第 186 天 · 省音与弱化",
    goalZh: "识别口语中消失的音与弱化形式，听懂也敢用。",
    vocabIds: [
      "w:elision",
      "w:phoneme",
      "w:conversational-structure",
      "w:speech-community",
      "w:intonation",
    ],
    grammarTopicId: "negation",
    phonicsRuleIds: ["st", "sp", "gr"],
    pattern: {
      titleZh: "句型：The /t/ disappears here. / Native speakers say ___.",
      explainZh: "省音：指出消失的音 The /t/ disappears in 'almost'；给出真实说法 Native speakers say 'woncha'。会听省音才算真听懂。",
      examples: [
        ["The /t/ disappears in 'sixth'.", "sixth 里的 /t/ 消失了。"],
        ["Native speakers reduce 'want to' to 'wanna'.", "母语者把 want to 弱化为 wanna。"],
        ["Weak forms are spelled differently than they sound.", "弱读形式写出来和读出来不一样。"],
      ],
      sentences: [
        ["Reduction makes fast speech fast.", "弱化让快语速成为可能。"],
        ["You don't need to copy every reduction.", "你不必模仿每一种弱化。"],
        ["Recognizing beats reproducing.", "听得懂比说得像更重要。"],
      ],
    },
    reading: [
      ["Elision deletes letters the mouth skips.", "省音删掉了嘴巴跳过的音。"],
      ["Weak forms hide in every casual conversation.", "每一次闲聊里都藏着弱读形式。"],
      ["Recognition first, production later.", "先听懂，后输出。"],
    ],
    writing: { zh: "写出你常听见的三个弱读形式及其完整写法。", hintEn: "'wanna' = want to; ___ = ___." },
  },
  {
    day: 187,
    titleEn: "Contractions in Speech",
    titleZh: "第 187 天 · 口语缩写",
    goalZh: "熟练使用 n't / 'd / 'll 等缩写让口语自然连贯。",
    vocabIds: [
      "w:like-approximator-quotation",
      "w:elision",
      "w:authentic-no-filter-required-presence",
      "w:cognitive-fluency",
      "w:register-formal-versus-casual-switching",
    ],
    grammarTopicId: "negation",
    phonicsRuleIds: ["l", "er", "w"],
    pattern: {
      titleZh: "句型：I'll ___ . / If I'd known, I'd have ___.",
      explainZh: "缩写能量：I'll / I'd / don't 让语速与归属感齐飞。书面语想清楚再写，口语里缩写是默认选择。",
      examples: [
        ["I'll handle it first thing tomorrow.", "这事我明早第一件就办。"],
        ["If I'd known, I'd have booked earlier.", "早知道我就早点订了。"],
        ["She's been waiting twenty minutes.", "她已经等了二十分钟。"],
      ],
      sentences: [
        ["Contractions are the engine of natural rhythm.", "缩写是自然节奏的引擎。"],
        ["Formal writing, relax the rules.", "正式写作请你守规矩，口语里放宽。"],
        ["Stress the auxiliary when you make a point.", "强调观点时把助动词重读出来。"],
      ],
    },
    reading: [
      ["Spoken English defaults to contractions.", "口头英语默认用缩写。"],
      ["Auxiliaries carry stress only when challenged.", "助动词只在反驳时才重读。"],
      ["Learners wrote lyrics with every contraction.", "学员用英文歌练遍了所有缩写。"],
    ],
    writing: { zh: "写一句用三个不同缩写的口语化句子。", hintEn: "I'll ___; she's ___; don't ___." },
  },
  {
    day: 188,
    titleEn: "Thought Groups",
    titleZh: "第 188 天 · 意义群",
    goalZh: "把长句切分为意义群，每个群配一次呼吸。",
    vocabIds: [
      "w:speech-prosody",
      "w:elaborative-rehearsal",
      "w:cognitive-fluency",
      "w:rhythm",
      "w:fluency-speed-with-control-balance",
    ],
    grammarTopicId: "basic-clauses",
    phonicsRuleIds: ["ee", "sh", "al"],
    pattern: {
      titleZh: "句型：One idea, one breath. / Pause between ___ and ___.",
      explainZh: "意义群：一句一呼吸 One idea, one breath；在两个意义群之间停顿 Pause between… and…。切对群，句子自然可懂。",
      examples: [
        ["One idea, one breath — that's the rule.", "一个意思一口气，这就是规则。"],
        ["Pause between the subject phrase and the verb.", "在主语短语和谓语之间停顿。"],
        ["Long sentences are just short groups in a row.", "长句只是短意义群的串接。"],
      ],
      sentences: [
        ["Chunking halves listener effort.", "切分把听者负担砍半。"],
        ["Pauses are punctuation you speak, not write.", "停顿是说出来而不是写出来的标点。"],
        ["Breathe at group boundaries, not mid-group.", "在意义群的边界换气。"],
      ],
    },
    reading: [
      ["Same passage, wrong chunks, lost meaning.", "同一段话，群切错，意思就丢。"],
      ["Groups mirror grammar units.", "意义群常常对应语法单位。"],
      ["Learners read with slash marks for breath.", "学员用斜线标记换气点。"],
    ],
    writing: { zh: "用 / 号给一句长句标注意义群。", hintEn: "The report / we submitted on Monday / was approved. (示例)" },
  },
  {
    day: 189,
    titleEn: "Pausing for Effect",
    titleZh: "第 189 天 · 停顿的艺术",
    goalZh: "用停顿制造悬念、强调与控场，摆脱赶节奏。",
    vocabIds: [
      "w:hesitate-two-second-buy-time-move",
      "w:fluency-speed-with-control-balance",
      "w:deadpan-delivery-style",
      "w:eye-contact-confidence-calibration-by-culture-map",
      "w:eloquent-speeches-quote-worthy-sentences",
    ],
    grammarTopicId: "present-simple",
    phonicsRuleIds: ["oa", "igh", "oi"],
    pattern: {
      titleZh: "句型：Let that land. / …and then — two seconds — ___.",
      explainZh: "控场停顿：让重点落地 Let that land；制造悬念 停顿两秒再揭晓。沉默不是冷场，是重音的一部分。",
      examples: [
        ["Let that land before you continue.", "先让这句话落地再继续。"],
        ["Two seconds of silence focused the whole room.", "两秒沉默让全场聚焦。"],
        ["Pause before the conclusion, not after it.", "在结论之前停顿，而不是之后。"],
      ],
      sentences: [
        ["The pause is the punchline's shadow.", "停顿是包袱的影子。"],
        ["Rushing betrays anxiety; pausing signals mastery.", "赶话暴露焦虑，停顿显示掌握。"],
        ["End sentences on a flat, finished tone.", "句末用平稳结束的语调。"],
      ],
    },
    reading: [
      ["One pause changed a joke into a speech.", "一个停顿把玩笑变成了演讲。"],
      ["Judges timed every silence as confidence.", "评委把每段沉默都算作自信。"],
      ["Slow speakers won the debate round.", "语速慢的辩手赢了那一轮。"],
    ],
    writing: { zh: "写一段 30 字的话并标出两处“强调停顿”。", hintEn: "X —(pause)— Y。" },
  },
  {
    day: 190,
    titleEn: "Fluency Over Speed",
    titleZh: "第 190 天 · 流利而非飞快",
    goalZh: "建立“持续不卡壳”而非“越快越好”的流利观。",
    vocabIds: [
      "w:fluency-speed-with-control-balance",
      "w:cognitive-fluency",
      "w:articulate-thoughts-into-clean-sentences-skill",
      "w:hesitate-two-second-buy-time-move",
      "w:authentic-no-filter-required-presence",
    ],
    grammarTopicId: "questions",
    phonicsRuleIds: ["er", "gr", "fl"],
    pattern: {
      titleZh: "句型：Speed comes after accuracy. / Keep the thread alive.",
      explainZh: "流利观：速度排在准确之后 Speed comes after accuracy；保持思路在线 Keep the thread alive。卡壳一秒比跑火车十句更重要。",
      examples: [
        ["Speed comes after accuracy, not before it.", "速度排在准确之后。"],
        ["Keep the thread alive even when you hesitate.", "哪怕迟疑也要让思路不断线。"],
        ["Comfortable speed beats desperate speed.", "舒服的速度胜过拼命的速度。"],
      ],
      sentences: [
        ["Fluency is continuity, not velocity.", "流利是连续性不是速度。"],
        ["A steady pacer finishes the mile.", "匀速跑的选手能完赛。"],
        ["Clarity first; speed will find you.", "先求清楚，速度自会跟上。"],
      ],
    },
    reading: [
      ["Fast talkers paused twice as often as slow ones.", "语速快的人停顿次数反而多一倍。"],
      ["Accuracy debt compounds under speed.", "速度压力下准确度欠账会利滚利。"],
      ["The class benchmarked words per minute, then forgot them.", "班级先测每分钟词数，后来又忘掉了这个指标。"],
    ],
    writing: { zh: "写一句你的“流利日签”，说明你本周的目标参数。", hintEn: "This week I aim for ___ without freezing." },
  },
  {
    day: 191,
    titleEn: "Fillers That Buy Time",
    titleZh: "第 191 天 · 赢得时间的填充词",
    goalZh: "用 well / you know / I mean 自然争取思考时间。",
    vocabIds: [
      "w:well-hedge-opener",
      "w:yknow-conversational-glue",
      "w:i-mean-reformulation-marker",
      "w:actually-correction-marker",
      "w:hesitate-two-second-buy-time-move",
    ],
    grammarTopicId: "be-verb",
    phonicsRuleIds: ["er", "ee", "ai"],
    pattern: {
      titleZh: "句型：Well, actually… / I mean, the point is ___.",
      explainZh: "填充词工具箱：开场缓冲 Well, actually…；重新表述 I mean,…。每个填充词都是一次免费的思考贷款。",
      examples: [
        ["Well, actually, I think the data tells a different story.", "嗯，其实我觉得数据讲的是另一个故事。"],
        ["I mean, the point is we can't wait any longer.", "我是说，重点是我们不能再等了。"],
        ["You know, it's more about habit than talent.", "你知道嘛，这更多是习惯问题而非天赋。"],
      ],
      sentences: [
        ["Fillers are loans; pay them back with content.", "填充词是借款，要用内容来还。"],
        ["One filler per thought group keeps you honest.", "一个意义群一个填充词，保持诚实。"],
        ["Silence and filler are both tools — use one.", "沉默和填充词都是工具，选定一个用。"],
      ],
    },
    reading: [
      ["Fillers painted speakers as thoughtful, not lost.", "填充词让讲者显得沉稳而非卡壳。"],
      ["Overuse turned bridges into roadblocks.", "滥用把桥梁变成了路障。"],
      ["Contrast filled speech with drop-zone silence.", "对比填充语与完全空白的话轮。"],
    ],
    writing: { zh: "给三个场景各写一个以 well/actually/y'know 开头的句子。", hintEn: "Well… Actually… You know…" },
  },
  {
    day: 192,
    titleEn: "Repairs & Reformulation",
    titleZh: "第 192 天 · 修正与重述",
    goalZh: "说错后平滑修正，把口误变成加分项。",
    vocabIds: [
      "w:i-mean-reformulation-marker",
      "w:actually-correction-marker",
      "w:conversational-structure",
      "w:speech-act",
      "w:authentic-no-filter-required-presence",
    ],
    grammarTopicId: "past-simple",
    phonicsRuleIds: ["r", "l", "oa"],
    pattern: {
      titleZh: "句型：Sorry — I mean ___. / Or rather, ___.",
      explainZh: "修正三件套：道歉缓冲 Sorry — I mean…；精确换词 or rather…；淡定重来 Let me restart。修正办得漂亮比一次说对更显功力。",
      examples: [
        ["Sorry — I mean October, not November.", "抱歉——我是说十月，不是十一月。"],
        ["It's affordable, or rather, surprisingly cheap.", "它负担得起，或者更准确地说，便宜得出奇。"],
        ["Let me restart that sentence properly.", "让我把这句重新说一遍。"],
      ],
      sentences: [
        ["Self-correction proves self-monitoring.", "自我修正证明你在自我监控。"],
        ["The repair matters less than the recovery time.", "口误不要紧，恢复速度才要紧。"],
        ["Own the fix and move on without an apology spiral.", "承认修正，然后别陷进道歉漩涡。"],
      ],
    },
    reading: [
      ["Recruiters scored candidates who fixed errors cleanly.", "面试官给能利落修正的候选人加了分。"],
      ["Apology spirals cost more than the original slip.", "道歉漩涡比最初的失误更费分。"],
      ["Learners role-played mispronounced place names.", "学员上演了念错地名的场景。"],
    ],
    writing: { zh: "写一句改正句并注明你最近一次真实口误。", hintEn: "Sorry — I mean ___, not ___." },
  },
  {
    day: 193,
    titleEn: "Sequence Markers in Retelling",
    titleZh: "第 193 天 · 复述的顺序标记",
    goalZh: "用 first / next / meanwhile / finally 勾出事件骨架。",
    vocabIds: [
      "w:grand-narrative",
      "w:flashback-scene-memory-cut",
      "w:elaborative-rehearsal",
      "w:narrative-theory",
      "w:subplot-secondary-thread",
    ],
    grammarTopicId: "past-simple",
    phonicsRuleIds: ["st", "fl", "th-vl"],
    pattern: {
      titleZh: "句型：First, ___. Meanwhile, ___. Finally, ___.",
      explainZh: "复述骨架：时间轴 First… Next…；并线 Meanwhile…；收场 Finally…。顺序词是听者的地图，先给地图再讲故事。",
      examples: [
        ["First, the alarm failed; next, the backup kicked in.", "先警报失灵，接着备用系统启动。"],
        ["Meanwhile, the client was already signing elsewhere.", "与此同时客户已经在别处签约了。"],
        ["Finally, the team shipped two days early.", "最后团队提前两天交付。"],
      ],
      sentences: [
        ["Sequence words draw the map before the story.", "顺序词先画地图再讲故事。"],
        ["Meanwhile introduces a second lane.", "meanwhile 引出第二条车道。"],
        ["Finally signals the landing, not the takeoff.", "finally 是落地信号不是起飞信号。"],
      ],
    },
    reading: [
      ["Retelling a job-interview morning need sequence markers.", "复述面试早晨需要顺序标记。"],
      ["Flashback made the story richer, not shorter.", "倒叙让故事更丰满而不只是更短。"],
      ["Listeners drew the timeline and found three gaps.", "听者画出时间线发现三处缺口。"],
    ],
    writing: { zh: "用三个顺序词写出你今天早晨的三件事。", hintEn: "First…, meanwhile…, finally…" },
  },
  {
    day: 194,
    titleEn: "Storytelling: Setting",
    titleZh: "第 194 天 · 讲故事：场景铺垫",
    goalZh: "用时间地点氛围让听众进入场景。",
    vocabIds: [
      "w:mise-en-scene",
      "w:vivid-description-sensory-detail-craft",
      "w:flashback-scene-memory-cut",
      "w:thick-description",
      "w:narrator-unreliable-voice",
    ],
    grammarTopicId: "past-simple",
    phonicsRuleIds: ["igh", "ai", "w"],
    pattern: {
      titleZh: "句型：It was a ___ night, and ___. / You could hear ___.",
      explainZh: "场景开场：交代时间氛围 It was a cold Tuesday morning；补感官 You could hear the rain。先让听众看见，再让他们听见。",
      examples: [
        ["It was a grey Tuesday morning, and the airport was empty.", "那是一个灰蒙蒙的周二早晨，机场空荡荡的。"],
        ["You could hear every announcement in that silence.", "那份安静里每一句广播都听得见。"],
        ["The room smelled of coffee and stale decisions.", "房间里有咖啡味和陈旧决定的味道。"],
      ],
      sentences: [
        ["A setting is a mood with a place attached.", "场景是带地点的氛围。"],
        ["Sensory detail beats a dozen adjectives.", "一句感官细节胜过一打形容词。"],
        ["Narrators choose what the listener sees.", "叙述者替听众决定看到什么。"],
      ],
    },
    reading: [
      ["Story slam winners opened inside the scene.", "讲故事比赛冠军都是直接进场景。"],
      ["One smell anchored a three-minute tale.", "一种气味锚定了三分钟的故事。"],
      ["Audience eyes opened when weather became character.", "当天气变成角色时听众眼睛亮了。"],
    ],
    writing: { zh: "用两句话为你的故事设置场景（时间+一个感官细节）。", hintEn: "It was a ___ . I could ___ ." },
  },
  {
    day: 195,
    titleEn: "Storytelling: Characters",
    titleZh: "第 195 天 · 讲故事：人物塑造",
    goalZh: "用原型、对比与细节让人物立体可感。",
    vocabIds: [
      "w:archetype-character-type",
      "w:foil-character-contrast",
      "w:dialogue-model",
      "w:vivid-description-sensory-detail-craft",
      "w:unreliable-narrator",
    ],
    grammarTopicId: "past-simple",
    phonicsRuleIds: ["ch", "sh", "er"],
    pattern: {
      titleZh: "句型：He was the type who ___. / What made him ___ was ___.",
      explainZh: "人物速写：定原型 He was the type who…；点反差 What made him memorable was…。一个动作顶三句形容词。",
      examples: [
        ["He was the type who read the manual first.", "他是那种先读说明书的人。"],
        ["What made her memorable was her impossible optimism.", "让她难忘的是她那不可能的乐观。"],
        ["The quiet one roars at the climax.", "安静之人在高潮处吼出声来。"],
      ],
      sentences: [
        ["Show personality through reaction, not description.", "用反应刻画性格，不要贴标签。"],
        ["A foil makes the hero visible by contrast.", "衬托角色用反差让主角显形。"],
        ["Unreliable narrators keep listeners guessing.", "不可靠叙述者让听众持续猜谜。"],
      ],
    },
    reading: [
      ["Two characters, one scene, reader picks the hero.", "两个人一个场景，读者自己选主角。"],
      ["Reaction shots built the whole personality.", "反应镜头塑造了整个性格。"],
      ["Speakers ranked their own stories by character clarity.", "讲者按人物清晰度给自己的故事排序。"],
    ],
    writing: { zh: "用“他是那种…的人”句式一笔勾出一个真实的人。", hintEn: "She was the type who ___ ." },
  },
  {
    day: 196,
    titleEn: "Storytelling: Tension & Resolution",
    titleZh: "第 196 天 · 讲故事：悬念与收束",
    goalZh: "铺设悬念并用清晰的收束让故事落地。",
    vocabIds: [
      "w:dramatic-irony",
      "w:subplot-secondary-thread",
      "w:grand-narrative",
      "w:satire-sharp-social-mockery",
      "w:narrative-theory",
    ],
    grammarTopicId: "past-simple",
    phonicsRuleIds: ["oi", "ow-2", "igh"],
    pattern: {
      titleZh: "句型：Just then, ___. / What nobody knew was ___.",
      explainZh: "悬念机器：转折词 Just then…；秘密披露 What nobody knew was…；收束 In the end…。悬念要埋，收束要快。",
      examples: [
        ["Just then, the lights went out across the floor.", "就在那时整层楼的灯灭了。"],
        ["What nobody knew was that the alarm had been off all night.", "没人知道的是警报整晚都没开。"],
        ["In the end, the spare key was in my own bag.", "最后那把备用钥匙就在我自己包里。"],
      ],
      sentences: [
        ["Dramatic irony lets the audience know first.", "戏剧反讽让观众先知道。"],
        ["The resolution should outrun the doubt.", "收束要快于听众的困惑。"],
        ["Tension without release is cruelty; release without tension is trivia.", "只有紧张没有释放是折磨，只有释放没有紧张是琐碎。"],
      ],
    },
    reading: [
      ["The subplot explained the missing hero.", "支线情节解释了主角的缺席。"],
      ["Punchlines landed only after planted details.", "埋过的细节才能引爆结尾。"],
      ["Storytellers cut endings that wandered.", "讲故事者砍掉跑题的结尾。"],
    ],
    writing: { zh: "为你的故事写一句悬念转折和一句收束。", hintEn: "Just then, ___. In the end, ___." },
  },
  {
    day: 197,
    titleEn: "Anecdotes: Hook & Punchline",
    titleZh: "第 197 天 · 轶事的钩子与包袱",
    goalZh: "用一句话钩住注意力，用包袱收尾。",
    vocabIds: [
      "w:deadpan-delivery-style",
      "w:roast-friendly-teasing",
      "w:satire-sharp-social-mockery",
      "w:vivid-description-sensory-detail-craft",
      "w:light-at-the-end-of-the-tunnel-hope-idiom",
    ],
    grammarTopicId: "past-simple",
    phonicsRuleIds: ["th-vd", "oa", "er"],
    pattern: {
      titleZh: "句型：You won't believe what happened next. / The best part was ___.",
      explainZh: "轶事两件套：钩子 You won't believe what happened next；包袱 The best part was…。包袱要落在反差点上。",
      examples: [
        ["You won't believe what happened next — I walked into my own interview.", "你不会相信接下来发生什么——我走进了自己的面试会场。"],
        ["The best part was the interviewer had the same hometown.", "最好笑的是面试官和我同乡。"],
        ["Two minutes of silence, then the room laughed.", "两秒…两分钟的安静 之后全场笑了。"],
      ],
      sentences: [
        ["The hook trades the ending for the listener's attention.", "钩子用剧透换听众的注意力。"],
        ["The punchline lives in the gap between expectation and fact.", "包袱活在期待与事实的落差里。"],
        ["Deadpan delivery multiplies the joke.", "冷面幽默让笑话加倍。"],
      ],
    },
    reading: [
      ["Anecdotes opened every successful toast.", "成功的祝酒词都用轶事开场。"],
      ["Audience laughed at the gap, not the fact.", "听众笑的是落差不是事实。"],
      ["One hook question doubled the listening time.", "一个钩子问题让听众注意力翻倍。"],
    ],
    writing: { zh: "写一句钩子句和一句包袱句。", hintEn: "You won't believe… The best part…" },
  },
  {
    day: 198,
    titleEn: "Backchanneling & Reacting",
    titleZh: "第 198 天 · 回应式倾听",
    goalZh: "用简短回应证明你在听，掌控对话节奏。",
    vocabIds: [
      "w:yknow-conversational-glue",
      "w:actually-correction-marker",
      "w:conversational-structure",
      "w:curiosity-question-everything-license-plate",
      "w:speech-community",
    ],
    grammarTopicId: "questions",
    phonicsRuleIds: ["th-vd", "er", "ai"],
    pattern: {
      titleZh: "句型：Right. / Interesting. / Wait — say that again.",
      explainZh: "回馈三档：跟上 Right / Mm-hmm；有料 Interesting；要澄清 Wait — say that again。回馈词是对话的节拍器。",
      examples: [
        ["Right, that makes sense with what you said earlier.", "对，这样和你之前说的就对上了。"],
        ["Interesting — how did the team react?", "有意思——团队当时什么反应？"],
        ["Wait — say that again, the numbers changed?", "等等——你再说一遍，数字变了？"],
      ],
      sentences: [
        ["Reaction tokens prove comprehension cheaply.", "回馈词用很小的成本证明你在听。"],
        ["Question after reaction deepens the well.", "反应之后接提问，井就越挖越深。"],
        ["Listeners who echo win the room.", "会复述的听者赢得全场。"],
      ],
    },
    reading: [
      ["Interviewers counted the candidate's reaction tokens.", "面试官数了候选人的回馈词数量。"],
      ["Echo summaries double as memory aids.", "复述式回应一箭双雕还能当记忆工具。"],
      ["Silent listeners lost negotiation points.", "沉默的听者丢了谈判分。"],
    ],
    writing: { zh: "为三个对话瞬间各写一个回馈词。", hintEn: "Right / Interesting / Wait—say that again." },
  },
  {
    day: 199,
    titleEn: "Clarification Strategies",
    titleZh: "第 199 天 · 澄清策略",
    goalZh: "没听懂时用自然方式请求澄清而不是尴尬沉默。",
    vocabIds: [
      "w:circle-back-later-phrase",
      "w:give-a-heads-up",
      "w:take-this-offline",
      "w:conversational-implicature",
      "w:interrupt-politely-bridge-phrases-toolkit",
    ],
    grammarTopicId: "questions",
    phonicsRuleIds: ["dr", "gr", "or"],
    pattern: {
      titleZh: "句型: Could you unpack that? / Let me circle back to ___.",
      explainZh: "澄清四式：请求展开 Could you unpack that；回访搁置 Let me circle back…；预约再谈 Take this offline；确认理解 So what you're saying is…。",
      examples: [
        ["Could you unpack that second point?", "能把第二点展开讲讲吗？"],
        ["Let me circle back to the budget detail.", "让我回到预算细节。"],
        ["So what you're saying is the deadline moved up?", "所以你的意思是截止日期提前了？"],
      ],
      sentences: [
        ["Clarifying once beats pretending twice.", "澄清一次好过假装听懂两次。"],
        ["Paraphrase proves you heard, not that you forgot.", "复述证明你听懂了而不是忘了。"],
        ["Native speakers clarify constantly — copy them.", "母语者自己都在不停澄清——学他们。"],
      ],
    },
    reading: [
      ["Unpack-that questions rescued a stalled review.", "一个“展开讲讲”救活了一场卡壳的评审会。"],
      ["Circle-back built a written trail of open threads.", "回访策略留下了一条待办线。"],
      ["Offline conversations reduced meeting interruptions.", "会后单聊减少了会议打断。"],
    ],
    writing: { zh: "写两个澄清句式并各配一个场景。", hintEn: "Could you unpack X? Let me circle back to X." },
  },
  {
    day: 200,
    titleEn: "Summarizing What You Heard",
    titleZh: "第 200 天 · 听取概括",
    goalZh: "听完长段后用三句结构化地復述要点。",
    vocabIds: [
      "w:concise-cut-adjectives-payroll-halving",
      "w:concession-rebuttal-structure",
      "w:conversational-implicature",
      "w:skeleton",
      "w:prioritization-matrix",
    ],
    grammarTopicId: "basic-clauses",
    phonicsRuleIds: ["st", "oi", "ee"],
    pattern: {
      titleZh: "句型：Long story short, ___. / The gist is ___.",
      explainZh: "概括三式：直奔要点 Long story short…；抓主干部 The gist is…；表态跟进 I'd add that…。先分主次，再删枝叶。",
      examples: [
        ["Long story short, we need one more approval.", "长话短说，我们还需要一次审批。"],
        ["The gist is that costs rose faster than revenue.", "要点是成本涨得比收入快。"],
        ["I'd add that timing is our real risk.", "我想补充时间才是真正的风险。"],
      ],
      sentences: [
        ["Summaries reveal the hierarchy of your attention.", "概括暴露你注意力的优先级。"],
        ["Details that don't serve the gist get cut.", "不为要点服务的细节统统砍掉。"],
        ["A good summary ends with a forward question.", "好概括以推进性问题收尾。"],
      ],
    },
    reading: [
      ["The class summarized a ten-minute meeting in three lines.", "全班把十分钟的会概括成三行。"],
      ["Listeners who summarized retained twice as much.", "听完就概括的人记得多一倍。"],
      ["Gist-first answers won the follow-up quiz.", "先讲要点的答案赢得了随堂测验。"],
    ],
    writing: { zh: "用三句概括你今天读到的任何长内容。", hintEn: "Long story short… The gist… I'd add…" },
  },
  {
    day: 201,
    titleEn: "Small Talk: Openers",
    titleZh: "第 201 天 · 寒暄开场",
    goalZh: "用安全话题自然开场并等待对方接球。",
    vocabIds: [
      "w:small-talk-weather-elevator-scripts-unlock-doors",
      "w:curiosity-question-everything-license-plate",
      "w:script-theory",
      "w:circle-back-later-phrase",
      "w:authentic-no-filter-required-presence",
    ],
    grammarTopicId: "present-simple",
    phonicsRuleIds: ["ai", "st", "er"],
    pattern: {
      titleZh: "句型：How's your week been? / By the way, ___.",
      explainZh: "寒暄三式：近况 How's your week been；现场锚点 This place is busy；顺带再聊 By the way…。开场给的是球，不是发表。",
      examples: [
        ["How's your week been — busy or quiet?", "这周过得怎么样——忙还是闲？"],
        ["This place is always busy on Fridays.", "这地方周五总是很忙。"],
        ["By the way, where did you move here from?", "顺便问一下，你从哪搬来的？"],
      ],
      sentences: [
        ["Openers hand the ball to the other player.", "开场是把球递给对方。"],
        ["Safe topics are scaffolding for real ones.", "安全话题是通往真实话题的脚手架。"],
        ["Exit gracefully with a value line, not an escape.", "用一句有温度的话离场，而不是逃跑。"],
      ],
    },
    reading: [
      ["Elevator small talk unlocked a job referral.", "电梯寒暄解锁了一份内推。"],
      ["Weather openers fade into family questions.", "天气开场慢慢滑向家庭话题。"],
      ["Purposeful exits kept the sidewalk meetings short.", "克制的收尾让偶遇寒暄保持简短。"],
    ],
    writing: { zh: "写三个用于不同场合的安全开场问题。", hintEn: "How's your week been? (随意) / ___" },
  },
  {
    day: 202,
    titleEn: "Small Talk: Office Talk",
    titleZh: "第 202 天 · 职场寒暄",
    goalZh: "既建立人际温度又不越界、不泄密。",
    vocabIds: [
      "w:take-this-offline",
      "w:operating-cadence-rhythm",
      "w:circle-back-later-phrase",
      "w:burn-bridges-behind-you",
      "w:register-formal-versus-casual-switching",
    ],
    grammarTopicId: "articles",
    phonicsRuleIds: ["oi", "bl", "br"],
    pattern: {
      titleZh: "句型：Let's grab a coffee sometime. / Can't discuss that here.",
      explainZh: "职场寒暄护栏：约线下 Let's grab a coffee sometime；守住边界 Can't discuss that here — 温度与分寸要并存。",
      examples: [
        ["Let's grab a coffee sometime and catch up.", "改天一起去喝杯咖啡聊聊。"],
        ["Can't discuss that here — let's take it offline.", "这事不方便在这说——我们会后单聊。"],
        ["Great to see you; keep me posted on the launch.", "见到你真好，上线有新进展随时告诉我。"],
      ],
      sentences: [
        ["Office chatter builds social capital cheaply.", "办公室闲聊是低成本攒人脉。"],
        ["Temperature without boundaries becomes gossip.", "只有温度没有边界的寒暄就变成了八卦。"],
        ["You can be friendly and discreet at once.", "你完全可以既友好又守口如瓶。"],
      ],
    },
    reading: [
      ["Coffee invites turned contacts into allies.", "咖啡邀请把联系人变成了盟友。"],
      ["Discretion at the water cooler protected a launch.", "茶水间的嘴严保护了一次发布。"],
      ["The office grapevine rewarded safe talkers.", "办公室葡萄藤偏爱嘴稳的人。"],
    ],
    writing: { zh: "写一句既热情又能守住项目机密的职场寒暄。", hintEn: "Glad we met — ___ will be exciting, more later." },
  },
  {
    day: 203,
    titleEn: "Softening Opinions",
    titleZh: "第 203 天 · 软化观点",
    goalZh: "用缓冲词让观点被听见而不是被顶回来。",
    vocabIds: [
      "w:well-hedge-opener",
      "w:i-mean-reformulation-marker",
      "w:assertiveness-training",
      "w:nuance-argument",
      "w:stance",
    ],
    grammarTopicId: "negation",
    phonicsRuleIds: ["w", "er", "al"],
    pattern: {
      titleZh: "句型：I'd say ___. / To my mind, ___. / It seems to me that ___.",
      explainZh: "软化三件套：谦让 I'd say…；主观 To my mind…；推测 It seems to me that…。软化不等于软，是给你表达留余地。",
      examples: [
        ["I'd say the risk is lower than it looks.", "我倒觉得风险比看起来低。"],
        ["To my mind, the culture fit matters most here.", "在我看来，文化契合最要紧。"],
        ["It seems to me that fast is better than perfect.", "在我看来快比完美更重要。"],
      ],
      sentences: [
        ["Softened claims invite reply; hard ones invite war.", "软观点招来回应，硬观点招来反击。"],
        ["Hedging is posture, not weakness.", "缓冲是姿态不是软弱。"],
        ["Say it clearly, gently, and with a door open.", "清楚、温和、并留一扇门地说。"],
      ],
    },
    reading: [
      ["The softened proposal got approved faster.", "软化的提案批得更快。"],
      ["A hedge-opener listener heard the room's rebuttals first.", "先缓冲再开口的发言人先摸清了全场的反对意见。"],
      ["Assertive does not mean abrasive.", "坚定不等于扎人。"],
    ],
    writing: { zh: "把一句生硬观点改写成软化版。", hintEn: "We must… → I'd say we should…" },
  },
  {
    day: 204,
    titleEn: "Hedging & Speculating",
    titleZh: "第 204 天 · 推测与拿捏",
    goalZh: "在信息不足时用推测词表达不确定而不失信用。",
    vocabIds: [
      "w:conjecture-speculation",
      "w:nuance-argument",
      "w:assert",
      "w:assertiveness-training",
      "w:stance",
    ],
    grammarTopicId: "future-simple",
    phonicsRuleIds: ["er", "u-short", "z"],
    pattern: {
      titleZh: "句型：It could well be that ___. / I'm not ruling out ___.",
      explainZh: "推测梯子：低置信 It could well be…；中置信 I wouldn't rule out…；高置信 I'd bet my money on…。挑对梯级是专业的信用管理。",
      examples: [
        ["It could well be that demand drives the price.", "很可能是需求在推高价格。"],
        ["I'm not ruling out a late recovery.", "我不排除后期反弹。"],
        ["I'd bet my money on the second explanation.", "我更押第二种解释。"],
      ],
      sentences: [
        ["Speculation without a hedge reads as arrogance.", "不带缓冲的猜测读起来像傲慢。"],
        ["Choose the ladder rung that fits your evidence.", "按照证据多少挑梯级。"],
        ["Credit survives being wrong with a hedge.", "有缓冲的话，错了也保得住信用。"],
      ],
    },
    reading: [
      ["Analysts hedged every forecast and kept their jobs.", "分析师给每份预测都加了缓冲，保住了饭碗。"],
      ["The unhedged call aged badly in two weeks.", "那条不加缓冲的断言两周后就很难看。"],
      ["Hedges signal honesty about uncertainty.", "缓冲传达的是对不确定的诚实。"],
    ],
    writing: { zh: "就一个不确定的周末计划写一句推测句。", hintEn: "It could well be that ___ this weekend." },
  },
  {
    day: 205,
    titleEn: "Agreeing & Conceding",
    titleZh: "第 205 天 · 认同与让步",
    goalZh: "得体认同对方并先承认其合理点再推进自己观点。",
    vocabIds: [
      "w:concede-point",
      "w:consensus-algorithm-agree",
      "w:concession-rebuttal-structure",
      "w:rogerian-argument",
      "w:stance",
    ],
    grammarTopicId: "negation",
    phonicsRuleIds: ["er", "gr", "st"],
    pattern: {
      titleZh: "句型：Fair point. / You're right that ___, though ___. / I can't argue with that.",
      explainZh: "让步公式：认下来 Fair point；让一步 You're right that…；再接回来 though…。让步让对话往前进而不是往后缩。",
      examples: [
        ["Fair point — the timeline is genuinely tight.", "说得好——时间确实紧。"],
        ["You're right that costs matter, though the wait ones hurt more.", "你说成本重要没错，不过是等待成本更伤人。"],
        ["I can't argue with that logic.", "这个逻辑我驳不了。"],
      ],
      sentences: [
        ["Concede the point, not the argument.", "让掉这个点，别让掉整个立场。"],
        ["Acknowledgment lowers the other side's defenses.", "承认能让对方的防御降级。"],
        ["Rogers built persuasion on empathy first.", "罗杰斯式说服先共情再推进。"],
      ],
    },
    reading: [
      ["The negotiator conceded twice and won the deal.", "谈判者让了两次赢下了合同。"],
      ["Fair-point openers disarmed a hostile review.", "一句“说得对”化解了一场挑剔的评审。"],
      ["Consensus needs concession on the fringes.", "共识需要边缘让步。"],
    ],
    writing: { zh: "写一句包含让步的转换句式。", hintEn: "You're right that X, though Y." },
  },
  {
    day: 206,
    titleEn: "Disagreeing Politely",
    titleZh: "第 206 天 · 礼貌反对",
    goalZh: "反对观点而不得罪人，把分歧变成探讨。",
    vocabIds: [
      "w:nuance-argument",
      "w:steelman-argument-practice",
      "w:rogerian-argument",
      "w:point-of-information-raised",
      "w:concede-point",
    ],
    grammarTopicId: "negation",
    phonicsRuleIds: ["oi", "gr", "fl"],
    pattern: {
      titleZh: "句型：I see it differently. / Help me understand why ___.",
      explainZh: "礼貌反对：先给重述 I see it differently because…；再求理解 Help me understand…。把反对包装成学习的请求。",
      examples: [
        ["I see it a little differently, if I may.", "恕我直言，我有一点点不同的看法。"],
        ["Help me understand why the deadline can't slide.", "帮我理解一下为什么截止日期不能顺延。"],
        ["I'd push back on that reading of the numbers.", "我想对那个数据解读提出异议。"],
      ],
      sentences: [
        ["Steelman your opponent before you fight.", "先替对手武装到最强，再出手。"],
        ["Disagreement is a request for better evidence.", "分歧是一次对更好证据的请求。"],
        ["Attack the claim, never the claimant.", "攻论点，不攻发言人。"],
      ],
    },
    reading: [
      ["The rebuttal began with a restatement and softened the blow.", "异议以复述开场，缓冲了打击。"],
      ["Teams with polite pushback made fewer errors.", "有礼貌异议的团队犯错更少。"],
      ["One search-for-understanding question defused the meeting.", "一句求理解的问题化解了整个会议。"],
    ],
    writing: { zh: "改写一句生硬反对为礼貌反对。", hintEn: "That's wrong → I see it differently; help me understand…" },
  },
  {
    day: 207,
    titleEn: "Persuasion Essentials",
    titleZh: "第 207 天 · 说服基础",
    goalZh: "用 ethos/pathos/logos 三要素组织和检验自己的说服。",
    vocabIds: [
      "w:persuasion-ethos-pathos-logos-triangle",
      "w:persuasion",
      "w:convince-vs-persuade-distinction",
      "w:argument-from-example",
      "w:public-opinion-sentiment",
    ],
    grammarTopicId: "future-simple",
    phonicsRuleIds: ["er", "ee", "sp"],
    pattern: {
      titleZh: "句型：Here's the evidence. / Picture this: ___.",
      explainZh: "三要素：讲道理 give evidence（logos）；造共情 Picture this…（pathos）；亮资格 My experience is…（ethos）。缺一就弱三分。",
      examples: [
        ["Here's the evidence: three teams, same outcome.", "证据在这：三支队伍，同样的结果。"],
        ["Picture this: no wait, no calls, no paperwork.", "想象一下：不用等、不用打电话、不用填表。"],
        ["My experience running retail backs this claim.", "我做过零售的经历支撑这个说法。"],
      ],
      sentences: [
        ["Persuade the head, then reach the heart.", "先说服头脑，再触动内心。"],
        ["Convince is about proof; persuade about action.", "convince 靠证明，persuade 促行动。"],
        ["Example beats abstraction every time.", "例子永远胜过抽象。"],
      ],
    },
    reading: [
      ["The winning pitch ran ethos-pathos-logos in order.", "获胜提案按信-情-理顺序展开。"],
      ["Stats moved the analysts; a story moved the board.", "数据打动分析师，故事打动董事会。"],
      ["Persuasion without evidence is manipulation.", "没有证据的说服就是操纵。"],
    ],
    writing: { zh: "写一个三句说服mini-script，标注三要素。", hintEn: "E(L)… P… L…" },
  },
  {
    day: 208,
    titleEn: "Debate Moves",
    titleZh: "第 208 天 · 辩论动作",
    goalZh: "掌握质询、反驳与收束三个基础辩论动作。",
    vocabIds: [
      "w:point-of-information-raised",
      "w:argument-from-authority",
      "w:argument-from-example",
      "w:soundness-of-argument",
      "w:argument-structure",
    ],
    grammarTopicId: "questions",
    phonicsRuleIds: ["st", "sp", "gr"],
    pattern: {
      titleZh: "句型：Point of information. / That assumes ___. / To sum my case up: ___.",
      explainZh: "辩论三动作：插问 Point of information；拆前提 That assumes…；收束 To sum my case up…。动作比气势重要。",
      examples: [
        ["Point of information: does the policy cover part-time staff?", "质询：该政策覆盖兼职员工吗？"],
        ["That assumes the sample represents the city.", "这预设了样本代表整座城市。"],
        ["To sum my case up: cheaper, faster, safer.", "总结我的立场：更便宜、更快、更安全。"],
      ],
      sentences: [
        ["Attack premises, not just conclusions.", "拆前提，别只批结论。"],
        ["Soundness means true premises with valid links.", "可靠性=前提为真+论证有效。"],
        ["The authority argument fails when sources clash.", "权威论证在权威打架时最先崩。"],
      ],
    },
    reading: [
      ["The novices won with premises, not volume.", "新手靠拆前提赢过靠嗓门。"],
      ["Point-of-information rows forced speakers to answer.", "质询环节逼着发言人正面回答。"],
      ["Judges rewarded closing summaries of the opponent's best point.", "评委奖励能总结对方最强论的复盘。"],
    ],
    writing: { zh: "为任一话题写：一次质询、一个拆前提、一句收束。", hintEn: "P.O.I… / That assumes… / To sum up…" },
  },
  {
    day: 209,
    titleEn: "Interview Answer Structure",
    titleZh: "第 209 天 · 面试答案结构",
    goalZh: "用 STAR 结构组织行为面试答案，控制详略与节奏。",
    vocabIds: [
      "w:articulate-thoughts-into-clean-sentences-skill",
      "w:eye-contact-confidence-calibration-by-culture-map",
      "w:hesitate-two-second-buy-time-move",
      "w:eloquent-speeches-quote-worthy-sentences",
      "w:stage-fright-cold-hands-cure",
    ],
    grammarTopicId: "past-simple",
    phonicsRuleIds: ["st", "ar", "j"],
    pattern: {
      titleZh: "句型：The situation was ___. / My task was ___. / I did ___. / The result was ___.",
      explainZh: "STAR 骨架：情况 The situation…；任务 My task…；行动 I did…；结果 The result…。先给结论再补细节，30 秒讲完主杆。",
      examples: [
        ["The situation was a two-day deadline collapse.", "当时的局面是两天内要挽救整个脱轨的节点。"],
        ["My task was to reorganize the queue without new staff.", "我的任务是重组队列却不能加人。"],
        ["The result was zero missed shipments.", "结果是零漏发。"],
      ],
      sentences: [
        ["Structure beats volume in every interview.", "任何面试里结构都胜过篇幅。"],
        ["Lead with the result, then cash in the story.", "先报结果，再讲过程。"],
        ["Two-second pauses polish, not stall, the answer.", "两秒停顿让答案抛光而不是卡壳。"],
      ],
    },
    reading: [
      ["Recruiters ranked STAR answers twice as high.", "面试官给 STAR 答案打了双倍分。"],
      ["Candidates who quantified results sailed through.", "能量化结果的候选人畅通无阻。"],
      ["Practice under time pressure reduced rambling.", "限时演练治好了啰嗦。"],
    ],
    writing: { zh: "为一次真实经历写完整 STAR 四行答案。", hintEn: "S… T… A… R…" },
  },
  {
    day: 210,
    titleEn: "Block A Review & Assessment",
    titleZh: "第 210 天 · 口语流利度总结与测评",
    goalZh: "复盘 181-209 天口语技能并完成一次自评，规划下一块。",
    vocabIds: [
      "w:improvisation-art",
      "w:authentic-no-filter-required-presence",
      "w:deadpan-delivery-style",
      "w:curiosity-question-everything-license-plate",
      "w:gesture-hand-talk-free-upgrade-pack",
    ],
    grammarTopicId: "present-progressive",
    phonicsRuleIds: ["bl", "br", "oi"],
    pattern: {
      titleZh: "句型：My fluency win this block was ___. / One skill to carry into Block B is ___.",
      explainZh: "复习即终测：对照 181-209 天的五个能力环（重音连读、故事结构、寒暄、观点、面试）逐环自评 1-5 分，写下最实在的一件胜利和要带走的一个技能。",
      examples: [
        ["My fluency win this block was the storytelling arc.", "这一块我在讲故事结构上进步最大。"],
        ["One skill to carry into Block B is the two-second pause.", "要带进下一块的一个技能是两秒停顿。"],
        ["I rated my yes-and reflexes 4 out of 5.", "我的 yes-and 反应我给 4 分（满分 5）。"],
      ],
      sentences: [
        ["Review is a mini final, not a recap.", "复盘是迷你终测，不是回放。"],
        ["Carry one skill, not a shopping list.", "带走一个技能，别带购物清单。"],
        ["The next block starts where this one ends.", "下一块从这一块的终点出发。"],
      ],
    },
    reading: [
      ["Block A covered rhythm, stories, small talk, and persuasion.", "本块覆盖节奏、讲故事、寒暄与说服。"],
      ["Self-rating exposed the gap between knowing and doing.", "自评暴露了知道与做到之间的落差。"],
      ["Learners audiotaped a 90-second pitch as their final.", "学员掏出 90 秒 pitch 录音作为终测。"],
    ],
    writing: { zh: "写一封给自己的信：说出本块最好的习惯与要带走的技能。", hintEn: "This block, I ___ . I'm taking ___ into Block B." },
  },
];