import type { CourseDayPlan } from "@/content/pipeline/generate-days";

/** Day 118-125 工作沟通深化(下) - compact real plans. */
export const PLAN_118_125: readonly CourseDayPlan[] = [
  { day: 118, titleEn: "Emails: Asking for Help", titleZh: "第 118 天 · 邮件求助", goalZh: "写一封清楚、好回复的求助邮件。",
    vocabIds: ["w:request", "w:attachment", "w:respond", "w:feedback", "w:deadline"], grammarTopicId: "questions", phonicsRuleIds: ["wh", "ee"],
    pattern: { titleZh: "句型：Review and practice.", explainZh: "求助邮件三件套：背景一句、具体请求、截止时间。附上你已经试过的方法。",
      examples: [["w:feedback", "中午前能帮我看看报告吗？"], ["I've attached the failing logs.", "附件是报错日志。"], ["Any direction would help.", "给个方向就有帮助。"]],
      sentences: [["Happy to jump on a call if faster.", "电话更快的话随时可以。"], ["Thanks in advance.", "先谢过了。"], ["Ignore if you're swamped.", "如果你太忙就忽略。"]] },
    reading: [["Rosa's help email got replies in minutes.", "罗莎的求助邮件几分钟就有回复。"], ["One clear ask beats three vague ones.", "一个明确请求胜过三个含糊的。"], ["She closed the loop with a thank-you.", "她最后发了感谢收尾。"]],
    writing: { zh: "写一句具体的求助请求。", hintEn: "Practice makes perfect." } },
  { day: 119, titleEn: "Emails: Sorry & Fix", titleZh: "第 119 天 · 邮件道歉与补救", goalZh: "书面道歉：认错、影响、补救三步。",
    vocabIds: ["w:apology", "w:apologize", "w:prevent", "w:reassure", "w:refund"], grammarTopicId: "negation", phonicsRuleIds: ["sh", "o-short"],
    pattern: { titleZh: "句型：I apologize for ___. To make it right, ___.", explainZh: "书面道歉别过度自责：说清影响、给出补救时间点。",
      examples: [["I apologize for the late reply.", "回复晚了非常抱歉。"], ["To make it right, I'll expedite shipping.", "为表歉意我会加急发货。"], ["This won't happen again.", "这不会再发生。"]],
      sentences: [["Here's what went wrong, briefly.", "简单说明哪里出了问题。"], ["You'll get an update daily.", "每天给你同步进展。"], ["Thanks for your patience.", "感谢耐心等待。"]] },
    reading: [["A wrong price went live for an hour.", "错误价格上线了一小时。"], ["The email owned it in two lines.", "道歉邮件两行认错。"], ["Refunds turned angry users into fans.", "退款把愤怒用户变成粉丝。"]],
    writing: { zh: "写一句书面道歉加补救承诺。", hintEn: "I apologize for ___. To make it right, ___." } },
  { day: 120, titleEn: "Client Calls", titleZh: "第 120 天 · 客户电话", goalZh: "客户来电：倾听、确认、给下一步。",
    vocabIds: ["w:client", "w:confirm", "w:hold-on", "w:call-back", "w:solve"], grammarTopicId: "questions", phonicsRuleIds: ["ai", "ee"],
    pattern: { titleZh: "句型：Let me confirm ___. / Here's what happens next.", explainZh: "客户电话公式：听全→复述确认→给下一步和时间点。",
      examples: [["Let me confirm your order number.", "我确认一下订单号。"], ["Here's what happens next.", "接下来是这样的。"], ["I'll call back by four with news.", "四点前回电告知进展。"]],
      sentences: [["You're right to flag that.", "你指出这点很对。"], ["I don't know yet — I'll find out.", "我还不知道——我去查。"], ["w:feedback", "还有其他需要吗？"]] },
    reading: [["Clients forgive delays, not silence.", "客户能原谅延误，不能忍受沉默。"], ["A two-line recap after each call works.", "每次通话后两行总结就够了。"], ["Next steps always have owners.", "下一步永远要有负责人。"]],
    writing: { zh: "写一句通话结束前的确认语。", hintEn: "Practice makes perfect." } },
  { day: 121, titleEn: "Tech Support Calls", titleZh: "第 121 天 · 技术支持来电", goalZh: "描述技术故障并跟随指引操作。",
    vocabIds: ["w:device", "w:install", "w:bug", "w:update", "w:resolve"], grammarTopicId: "present-progressive", phonicsRuleIds: ["st", "or"],
    pattern: { titleZh: "句型：It keeps ___. / I already tried ___.", explainZh: "描述故障用 keep + doing；说明已尝试 I already tried… 避免重复指导。",
      examples: [["It keeps crashing on startup.", "它一启动就崩溃。"], ["I already tried restarting twice.", "我已经重启两次了。"], ["The screen goes black randomly.", "屏幕会随机变黑。"]],
      sentences: [["w:feedback", "序列号在哪里？"], ["w:feedback", "这种情况持续多久了？"], ["w:feedback", "我的文件会丢吗？"]] },
    reading: [["The agent walked Sam through three steps.", "客服带山姆做了三步。"], ["Step two fixed the frozen app.", "第二步就修好了卡死的应用。"], ["Sam wrote the steps down for next time.", "山姆把步骤记了下来。"]],
    writing: { zh: "写一句向支持人员描述故障的话。", hintEn: "It keeps ___ when I ___." } },
  { day: 122, titleEn: "Priorities That Fit", titleZh: "第 122 天 · 优先级排序", goalZh: "用重要/紧急四象限安排任务。",
    vocabIds: ["w:limit", "w:focus", "w:deadline", "w:goal", "w:list"], grammarTopicId: "basic-clauses", phonicsRuleIds: ["pl", "or"],
    pattern: { titleZh: "句型：___ first, because it's both urgent and important.", explainZh: "四象限：紧急且重要先做；重要不紧急排时段；紧急不重要委托；不重要不紧急删除。",
      examples: [["Pay rent first — urgent and important.", "房租最优先——紧急且重要。"], ["Exercise is important, not urgent.", "锻炼重要但不紧急。"], ["That meeting can wait a week.", "那个会可以推迟一周。"]],
      sentences: [["Three priorities max per day.", "每天最多三个重点。"], ["Say no to protect the top one.", "为了第一位要学会说不。"], ["Review the list every morning.", "每天早上过一遍清单。"]] },
    reading: [["Tara's to-do had forty-one lines.", "塔拉的待办有41行。"], ["She circled only three.", "她只圈了三个。"], ["The uncircled ones waited their turn.", "没圈的按顺序排队。"]],
    writing: { zh: "写出你今天的第一优先级及原因。", hintEn: "First, ___, because it's ___." } },
  { day: 123, titleEn: "Saying No Politely", titleZh: "第 123 天 · 婉拒的艺术", goalZh: "拒绝请求同时维护关系。",
    vocabIds: ["w:reject", "w:instead", "w:honestly", "w:politely", "w:feedback"], grammarTopicId: "negation", phonicsRuleIds: ["ng", "e-short"],
    pattern: { titleZh: "句型：I can't take that on, but here's an option.", explainZh: "婉拒公式：感谢→明确拒绝→替代方案或线索。",
      examples: [["I can't take that on this week.", "本周我接不了这个。"], ["w:feedback", "问过设计团队了吗？"], ["If it slips to May, I'm in.", "如果推到五月，我就加入。"]],
      sentences: [["My plate is full until Thursday.", "周四前我都排满了。"], ["I'd rather do it well than fast.", "我宁愿做好也不求快。"], ["No is a complete sentence.", "\"不\"本身就是完整回答。"]] },
    reading: [["Extra requests kept landing on Ken.", "额外请求不断落到肯头上。"], ["His new script: thanks, no, alternative.", "他的新话术：感谢、拒绝、给替代。"], ["Respect went up, hours went down.", "尊重上升，工时下降。"]],
    writing: { zh: "写一句婉拒并提供替代方案。", hintEn: "I can't ___, but I could ___." } },
  { day: 124, titleEn: "Stress: Talk & Reset", titleZh: "第 124 天 · 压力倾诉与调节", goalZh: "表达压力并使用恢复策略。",
    vocabIds: ["w:breathe", "w:mental-health", "w:fatigue", "w:relief", "w:routine"], grammarTopicId: "basic-clauses", phonicsRuleIds: ["st", "ee"],
    pattern: { titleZh: "句型：I'm feeling ___ because ___. What helps me is ___.", explainZh: "压力表达三段：感受+原因+应对法；倾诉时选对人和时机。",
      examples: [["I'm feeling stretched thin this month.", "我这个月有点被压垮。"], ["What helps me is a hard stop at seven.", "对我有用的是七点强制下班。"], ["Walking without my phone resets me.", "不带手机散步能让我复位。"]],
      sentences: [["Deadlines cluster at quarter end.", "季度末截止日扎堆。"], ["Saying it out loud halves the weight.", "说出来重量减半。"], ["Rest is part of the job.", "休息也是工作的一部分。"]] },
    reading: [["Priya's calendar turned all red.", "普莉娅的日历全是红色。"], ["Her lead moved two deadlines same day.", "主管当天挪走了两个截止线。"], ["Nobody knew she was drowning until she said so.", "不说出来没人知道她快撑不住。"]],
    writing: { zh: "写一句压力表达加一个应对方法。", hintEn: "I feel ___ because ___. ___ helps me." } },
  { day: 125, titleEn: "Career Map Check-in", titleZh: "第 125 天 · 职业规划检视", goalZh: "盘点技能差距并制定学习计划。",
    vocabIds: ["w:determination", "w:milestone", "w:qualification", "w:expertise", "w:strategy"], grammarTopicId: "future-simple", phonicsRuleIds: ["ai", "er"],
    pattern: { titleZh: "句型：By ___, I will have ___. / My gap is ___.", explainZh: "规划句：By + 时间点, I will have + 过去分词（未来完成）；差距叫 gap。",
      examples: [["By December, I will have finished two certificates.", "到十二月我会拿两个证书。"], ["My gap is public speaking.", "我的短板是公开演讲。"], ["Small weekly reps close gaps.", "每周小练习缩小差距。"]],
      sentences: [["Skills compound like interest.", "技能像利息一样复利。"], ["Ask for projects slightly above you.", "接略高于当前水平的项目。"], ["Review the map every quarter.", "每季度回顾一次地图。"]] },
    reading: [["Ken drew two columns: now / next.", "肯画了两栏：现在/下一步。"], ["Every \x27next\x27 had one action this month.", "每个“下一步”都有本月行动。"], ["The map fit on one card.", "地图只有一张卡片大小。"]],
    writing: { zh: "写一句未来目标加当前差距。", hintEn: "By ___, I will have ___. My gap is ___." } },
];
