import type { CourseDayPlan } from "@/content/pipeline/generate-days";

/**
 * Phase 23 · Day 301-330 — Block E 媒体与技术素养（Media & Technology Literacy）。
 * B2→C2 媒介产出：框架识读、过滤气泡、错误信息、事实核查、注意力经济、
 * 数字足迹、隐私、算法、平台权力、AI 协作、病毒机制、技术创新话语。
 * 全部引用真实 C1/C2 词汇。
 */
export const PLAN_301_330: readonly CourseDayPlan[] = [
  {
    day: 301,
    titleEn: "The Frame in the Story",
    titleZh: "第 301 天 · 新闻中的框架",
    goalZh: "识别每条新闻的框架、取舍与角度。",
    vocabIds: ["w:media-bias", "w:news-value", "w:newsworthiness-value", "w:media-outlet-news-platform", "w:journalism-ethics-code"],
    grammarTopicId: "present-simple",
    phonicsRuleIds: ["ee", "st", "ai"],
    pattern: {
      titleZh: "句型：The frame here is conflict, not process. / What the outlet chose to cut is ___.",
      explainZh: "识框三步：角度 the frame here is conflict, not process;取舍 what the outlet chose to cut;归因 whose version of the facts is this。新闻是取舍的产物。",
      examples: [
        ["The frame here is conflict, not process.", "这里的框架是冲突，不是过程。"],
        ["What the outlet chose to cut is the licensing fee.", "这家媒体选择剪掉的是许可费。"],
        ["News value picks what repeats, not what matters.", "新闻价值挑选重复的，不挑选要紧的。"],
      ],
      sentences: [
        ["Frames are choices wearing grammar.", "框架是穿着语法的选择。"],
        ["The same fact, one drama, one data set.", "同一事实，一个戏剧化，一个数据化。"],
        ["Ethics codes map the refs; they do not call the game.", "伦理守则画出裁判分工，不吹哨。"],
      ],
    },
    reading: [
      ["Two outlets framed the same study as hope and as threat.", "两家媒体把同一研究框成希望与威胁。"],
      ["The cropped paragraph changed the takeaway.", "被裁掉的一段改了结论。"],
      ["Ethics codes held the line when ratings pushed.", "评分施压时，伦理守则守住了线。"],
    ],
    writing: { zh: "挑一条新闻写出它的框架与一处裁剪。", hintEn: "Outlet: ___. Frame: ___. They cut ___." },
  },
  {
    day: 302,
    titleEn: "Inside the Filter Bubble",
    titleZh: "第 302 天 · 过滤气泡",
    goalZh: "说出算法为何只喂我们想听的。",
    vocabIds: ["w:filter-bubble-isolation", "w:echo-chamber-effect", "w:echo-chamber-reinforcement", "w:algorithm-feed-personalization", "w:algorithmic-amplification-loop"],
    grammarTopicId: "past-simple",
    phonicsRuleIds: ["ee", "st", "oi"],
    pattern: {
      titleZh: "句型：The feed learns what I click. / The bubble means I see less of ___.",
      explainZh: "气泡两句话：机制 the feed learns what I click;后果 the bubble means I see less of…。知道自己在气泡里，是第一个出气孔。",
      examples: [
        ["The feed learns what I click and shows more of it.", "信息流学会我点什么就推什么。"],
        ["The bubble means I see less of the other side entirely.", "气泡意味着我几乎看不到另一边。"],
        ["Amplification loops turn a spark into a bonfire.", "放大回路把火星变成篝火。"],
      ],
      sentences: [
        ["The algorithm is a mirror with a playlist.", "算法是带播放清单的镜子。"],
        ["Echo chambers repeat; they rarely examine.", "回音室只重复，几乎不检视。"],
        ["Pull one source from outside, and the wall cracks.", "从墙外拉进一个来源，墙就裂了。"],
      ],
    },
    reading: [
      ["Two feeds, two worlds, from one phone.", "一部手机，两个信息流，两个世界。"],
      ["The personalization loop kept feeding the worry.", "个性化回路不停投喂那份焦虑。"],
      ["Clicking one off-topic item changed a month of suggestions.", "点一条跑题内容改变了一个月的推荐。"],
    ],
    writing: { zh: "写一句你在气泡内的证据。", hintEn: "My feed mostly shows ___. A bubble sign is ___." },
  },
  {
    day: 303,
    titleEn: "Misinformation Science",
    titleZh: "第 303 天 · 错误信息学",
    goalZh: "区分误传与蓄意造假并解释其传播逻辑。",
    vocabIds: ["w:misinformation-error", "w:misinformation-false-content-spread", "w:misinformation-policy", "w:disinformation-deliberate", "w:disinformation-deliberate-campaign"],
    grammarTopicId: "future-simple",
    phonicsRuleIds: ["ee", "st", "oi"],
    pattern: {
      titleZh: "句型：Misinformation spreads by accident; disinformation is designed. / The campaign used ___ to polarize.",
      explainZh: "两词分界：误传 misinformation spreads by accident;造假 disinformation is designed。看模式：恐慌、简化、惊讶都是传播燃料。",
      examples: [
        ["Misinformation spreads by accident; disinformation is designed.", "错误信息是意外扩散，虚假信息是刻意设计。"],
        ["The campaign used outrage to polarize the room.", "那场行动用愤怒割裂全场。"],
        ["Policies lag the pace of the fabricated meme.", "政策永远追不上伪造梗的速度。"],
      ],
      sentences: [
        ["Shock is the elevator; a share is the door.", "震惊是电梯，转发是门。"],
        ["Designed lies repeat with a target; honest errors drift.", "设计过的谎言携带目标反复传播，诚实失误只是漂移。"],
        ["Speed wins in headlines; context wins in the long run.", "头条里速度赢，长期里背景赢。"],
      ],
    },
    reading: [
      ["The fabricated quote travelled four times faster than the retraction.", "伪造引语的传播速度是撤回的四倍。"],
      ["Viewers who knew the two words read the post differently.", "认得这两个词的读者读出不同含义。"],
      ["The campaign nested lies inside true frames.", "那场行动把谎言嵌进真实框架里。"],
    ],
    writing: { zh: "描述一条你见过的误传及其传播模式。", hintEn: "The piece: ___. Pattern: ___. Verdict: ___." },
  },
  {
    day: 304,
    titleEn: "Fact-Checking In Action",
    titleZh: "第 304 天 · 事实核查实操",
    goalZh: "用四步核查任意说法，判断证据强度。",
    vocabIds: ["w:fact-checking", "w:fact-checking-ratings-scale", "w:fact-checking-team-verifies", "w:source-credibility", "w:source-protection"],
    grammarTopicId: "questions",
    phonicsRuleIds: ["ee", "st", "oi"],
    pattern: {
      titleZh: "句型：Who benefits if this is true? / The rating on the original claim was ___.",
      explainZh: "核查四问：来源 who wrote it?;证据 what does the primary source say?;动机 who benefits?;评分 the rating was…。拉开原稿再谈转发。",
      examples: [
        ["Who benefits if this claim turns out to be true?", "若此说法为真，谁受益？"],
        ["The rating on the original claim was mostly false.", "原始说法的评级是基本失实。"],
        ["Cross-source checks beat the loudest single outlet.", "跨来源核对胜过最响的单家媒体。"],
      ],
      sentences: [
        ["The primary source ends most secondhand wars.", "一手来源终结大多数二手战争。"],
        ["A rating scale turns feelings into a verdict.", "评分尺把感觉变成判决。"],
        ["Source protection keeps whistleblowers airing.", "来源保护让吹哨人继续发声。"],
      ],
    },
    reading: [
      ["The four-step check exposed the cropped statistic.", "四步核查揭穿了被裁剪的统计。"],
      ["Teams that checked before sharing cut rumor spread in half.", "分享前核查的团队把谣言扩散减半。"],
      ["A named source outranked three anonymous posts.", "一个署名来源胜过三条匿名帖。"],
    ],
    writing: { zh: "对一个说法做一次四问核查。", hintEn: "Source: ___. Evidence: ___. Beneficiary: ___. Verdict: ___." },
  },
  {
    day: 305,
    titleEn: "Clickbait Anatomy",
    titleZh: "第 305 天 · 标题党解剖",
    goalZh: "拆穿悬念、夸张与惊讶的标题配方。",
    vocabIds: ["w:clickbait-headline-regret", "w:viral-coefficient", "w:virality-spread", "w:viral-trend-participation-window-48-hours-max", "w:attention-economy"],
    grammarTopicId: "articles",
    phonicsRuleIds: ["ee", "st", "oi"],
    pattern: {
      titleZh: "句型：The headline sells a surprise the article never delivers. / The number bait is the oldest trick.",
      explainZh: "标题三配方：悬念 the headline sells a surprise…;数字 number bait…;情绪 outrage opens more than curiosity。标题是餐厅菜单，正文才是菜。",
      examples: [
        ["The headline sells a surprise the article never delivers.", "标题卖出正文从不交付的意外。"],
        ["The number bait is the oldest trick on the feed.", "数字诱饵是信息流上最老的把戏。"],
        ["Clickbait farms harvest attention, not truth.", "标题党农场收割注意力，不收割真相。"],
      ],
      sentences: [
        ["Regret arrives in the tab you never read.", "后悔抵达在你永不点开的标签页上。"],
        ["The viral window favours the fast over the true.", "病毒窗口偏爱快的，不偏爱真的。"],
        ["Attention is a crop; feed content is the irrigation.", "注意力是庄稼，推送内容是灌溉。"],
      ],
    },
    reading: [
      ["The bait headline earned clicks and lost trust.", "诱饵标题赚到点击，丢掉信任。"],
      ["Readers who named the trick scrolled past the trap.", "能叫出把戏的读者直接滑过陷阱。"],
      ["Viral mechanics punisded the careful caveat.", "病毒机制惩罚了谨慎的保留意见。"],
    ],
    writing: { zh: "拆解一条标题党的配方。", hintEn: "Headline: ___. Bait: ___. Missing: ___." },
  },
  {
    day: 306,
    titleEn: "The Attention Economy",
    titleZh: "第 306 天 · 注意力经济",
    goalZh: "理解平台为何设计成让你停不下来。",
    vocabIds: ["w:attention-economy", "w:attention-mechanism", "w:attentional-blink", "w:attention-windowing", "w:information-overload"],
    grammarTopicId: "prepositions-basic",
    phonicsRuleIds: ["ee", "st", "oi"],
    pattern: {
      titleZh: "句型：The product here is attention, not content. / The design buys a blink from your focus.",
      explainZh: "生意观：产品 attention, not content;机制 the design buys a blink;成本 overload 的结果是 attention blindness。免费内容以注意力付费。",
      examples: [
        ["The product here is attention, not content.", "这里的产品是注意力，不是内容。"],
        ["The design buys a blink from your focus every scroll.", "每次滑动，设计都从你专注中买走一个眨眼。"],
        ["Overload makes careful reading a luxury choice.", "过载让细心阅读成为奢侈选项。"],
      ],
      sentences: [
        ["Free feeds bill you in minutes.", "免费信息流按分钟向你结账。"],
        ["Every notification is a tiny auction for your focus.", "每条通知都是对你专注的一场小拍卖。"],
        ["Budgeting attention is budgeting the day itself.", "为注意力做预算就是为全天做预算。"],
      ],
    },
    reading: [
      ["The infinite scroll turned an hour into a comma.", "无限滚动把一小时变成一句话的逗号。"],
      ["Designers described the feed as a farming contract.", "设计者把信息流描述成一份农耕契约。"],
      ["Attention blindness cost readers the middle section.", "注意力失明让读者错过中段。"],
    ],
    writing: { zh: "写下你昨天把注意力付给了谁。", hintEn: "I paid attention to ___. The bill was ___ minutes." },
  },
  {
    day: 307,
    titleEn: "Your Digital Footprint",
    titleZh: "第 307 天 · 数字足迹",
    goalZh: "盘点并管理自己留下的数字痕迹。",
    vocabIds: ["w:digital-footprint", "w:digital-footprint-permanent-marker-internet-lesson", "w:digital-identity", "w:digital-estate", "w:digital-trace-data"],
    grammarTopicId: "countable-uncountable",
    phonicsRuleIds: ["ee", "st", "oi"],
    pattern: {
      titleZh: "句型：The trail I leave most is ___. / A permanent marker learns; it rarely forgets.",
      explainZh: "足迹三问：最多痕迹 the trail I leave most is…;永久性 a permanent marker learns;遗产 digital estate 谁来继承账号。搜自己名字就是照镜子。",
      examples: [
        ["The trail I leave most is logged-in browsing.", "我留下最多的痕迹是登录浏览。"],
        ["A permanent marker learns but rarely forgets.", "永久标记会学习，却很少遗忘。"],
        ["My digital estate plan names who inherits the accounts.", "我的数字遗产计划写明了账号继承人。"],
      ],
      sentences: [
        ["Footprints grow while you sleep; the shovel is settings.", "足迹在你睡觉时生长，铲子叫设置。"],
        ["Google is the mirror the internet holds up.", "谷歌是网络举起的那面镜子。"],
        ["Trace data is evidence you sign with every click.", "痕迹数据是你每次点击签署的证据。"],
      ],
    },
    reading: [
      ["The search for their own name humbled a whole class.", "搜索自己名字的作业让全班谦逊。"],
      ["A deleted post resurfaced three hiring cycles later.", "一条删除的帖子在三个招聘周期后浮出。"],
      ["Students audited their public trail in one afternoon.", "学员用一个下午审计了自己的公开足迹。"],
    ],
    writing: { zh: "搜索并写下你公开足迹的三条。", hintEn: "Trail: ___. Would-avertails: ___. Fix: ___." },
  },
  {
    day: 308,
    titleEn: "Digital Wellbeing",
    titleZh: "第 308 天 · 数字健康",
    goalZh: "给屏幕与生活之间设一个可执行的界。",
    vocabIds: ["w:digital-wellness", "w:digital-detox-weekend-cabin-challenge", "w:digital-labor", "w:surveillance-capitalism", "w:attention-economy"],
    grammarTopicId: "negation",
    phonicsRuleIds: ["ee", "st", "oi"],
    pattern: {
      titleZh: "句型：The boundary is no screens after ___. / A detox shows me the habit in the mirror.",
      explainZh: "设界三招：时间界 no screens after…;空间界 no phone in ___;观察 detox shows the habit。数字健康是设计，不是节食。",
      examples: [
        ["The boundary is no screens after ten at night.", "界限是晚上十点后无屏幕。"],
        ["A detox shows me the habit in the mirror.", "一次排毒在镜子里照出我的习惯。"],
        ["My work phone is the quiet home of my labor.", "工作手机是我劳动的安静之家。"],
      ],
      sentences: [
        ["Wellness is a calendar statement, not a self-help quote.", "健康是一句日历声明，不是自愈金句。"],
        ["Surveillance capitalism pays in coupons, charges in hours.", "监控资本主义用优惠券支付，按小时计费。"],
        ["A named boundary outlives a thousand good intentions.", "一条点名界限胜过一千个好意图。"],
      ],
    },
    reading: [
      ["The ten-o-clock rule returned the evenings.", "十点规则把夜晚还了回来。"],
      ["A weekend without feeds revealed the phantom scroll.", "一个没有信息流的周末暴露了幻影滑动。"],
      ["The darkest hour was not the algorithm; it was the habit.", "最黑的时刻不是算法，是习惯。"],
    ],
    writing: { zh: "写下你的第一道数字界限。", hintEn: "No ___ after ___. Instead I will ___." },
  },
  {
    day: 309,
    titleEn: "The Digital Divide",
    titleZh: "第 309 天 · 数字鸿沟",
    goalZh: "把技术不平等的结构讲给行外人听。",
    vocabIds: ["w:digital-divide", "w:digital-divide-gap", "w:digital-commons", "w:information-society", "w:platform-economy"],
    grammarTopicId: "pronouns-basic",
    phonicsRuleIds: ["ee", "st", "oi"],
    pattern: {
      titleZh: "句型：The gap is access, skills, and trust in one. / What the divided cannot reach is ___.",
      explainZh: "鸿沟三层：接入 access;技能 skills;信任 trust。讲清 the divided cannot reach…，就能把上网说成基础教育。",
      examples: [
        ["The gap is access, skills, and trust in one.", "这条鸿沟合并了接入、技能与信任。"],
        ["What the divided cannot reach is the next tier of work.", "被隔开的人够不到的是下一层工作。"],
        ["Digital commons close a corner of the gap.", "数字公地合上鸿沟的一角。"],
      ],
      sentences: [
        ["Bandwidth is the new school bus.", "带宽是新的校车。"],
        ["A public library router outlives a hundred charity phones.", "公共图书馆的路由器比一百部慈善手机更长久。"],
        ["The information society staggers on uneven floors.", "信息社会在高低不平的地板上踉跄。"],
      ],
    },
    reading: [
      ["The library router became the village school's backbone.", "图书馆路由器成了村小的脊梁。"],
      ["Skills gaps widened faster than access gaps closed.", "技能鸿沟比接入鸿沟合拢得更快。"],
      ["Commons licensees rebuilt a town's data layer.", "公地许可人重建了一个镇的数据层。"],
    ],
    writing: { zh: "描述你社区的接入与技能差距。", hintEn: "Access: ___. Skills: ___. One bridge: ___." },
  },
  {
    day: 310,
    titleEn: "Privacy Is a Practice",
    titleZh: "第 310 天 · 隐私实践",
    goalZh: "把隐私从念头变成要件与最小化习惯。",
    vocabIds: ["w:privacy-policy-scroll-past-reflex-critique", "w:surveillance", "w:surveillance-capitalism", "w:surveillance-camera-network", "w:data-ethics"],
    grammarTopicId: "basic-clauses",
    phonicsRuleIds: ["ee", "st", "oi"],
    pattern: {
      titleZh: "句型：The consent here names what, when, and whom. / What data does this feature really need?",
      explainZh: "隐私三问：同意 what, when, and whom;最小化 what data does this feature really need?;替代 the vendor without tracking is ___。滚动即同意是隐私的逃课。",
      examples: [
        ["The consent here names what is stored, when, and why.", "这里的同意写明了存什么、何时、为何。"],
        ["What data does this feature really need in practice?", "这个功能实际真正需要哪些数据？"],
        ["The camera net watches the square and the shop queue.", "摄像头网络盯着广场和排队的人群。"],
      ],
      sentences: [
        ["Scroll-past consent is the privacy class you skipped.", "滚动即同意是你逃掉的那节隐私课。"],
        ["Minimize now, apologize never.", "现在做最小化，永远不用道歉。"],
        ["Surveillance queiter than a siren, softer but permanent.", "监控比警笛安静，柔和却永久。"],
      ],
    },
    reading: [
      ["Two minutes of reading a policy changed a user's setup.", "读两分钟政策改变了一位用户的设置在。"],
      ["The feature needed a zip code; it asked for contacts.", "功能只需要邮编，却索取了通讯录。"],
      ["A least-data shipper won a privacy-loyal client.", "一家最小化数据的物流商赢得了忠诚客户。"],
    ],
    writing: { zh: "为你的一个应用写最小化审查。", hintEn: "Feature needs ___. It asks for ___. Cut: ___." },
  },
  {
    day: 311,
    titleEn: "Algorithms Decide",
    titleZh: "第 311 天 · 算法替你决定",
    goalZh: "识别算法介入的决策点与责任归属。",
    vocabIds: ["w:algorithm", "w:algorithm-procedure", "w:algorithm-complexity", "w:algorithmic-accountability", "w:algorithmic-impact-assessment"],
    grammarTopicId: "be-verb",
    phonicsRuleIds: ["ee", "st", "oi"],
    pattern: {
      titleZh: "句型：The algorithm ranks, but the policy sets the goal. / Who audits this procedure?",
      explainZh: "算法三问：目标 the policy sets the goal;可审性 who audits this procedure?;影响 what does the impact assessment cover。算法是笔，政策是字。",
      examples: [
        ["The algorithm ranks, but the policy sets the goal.", "算法负责排序，政策负责定目标。"],
        ["Who audits this procedure when the share tilts?", "份额倾斜时谁审计这道程序？"],
        ["An impact assessment names who feels the change first.", "影响评估点名谁最先感受到变化。"],
      ],
      sentences: [
        ["Accountability outlives the debug log.", "问责制比调试日志活得更久。"],
        ["A fair procedure beats a lucky outcome.", "公平的程序胜过幸运的结果。"],
        ["The model is a vote, the policy is the constitution.", "模型是一票，政策是宪法。"],
      ],
    },
    reading: [
      ["The tilt surfaced because someone audited the ranks.", "倾斜暴露是因为有人审计了排名。"],
      ["Impact assessments moved the launch date twice.", "影响评估两次推迟了发布日期。"],
      ["A bullet point on accountability quieted the room.", "一行问责文字让满屋安静。"],
    ],
    writing: { zh: "找出一个算法替你决定的场景并标出责任人。", hintEn: "Decision: ___. Algorithm part: ___. Human part: ___." },
  },
  {
    day: 312,
    titleEn: "Platform Power",
    titleZh: "第 312 天 · 平台权力",
    goalZh: "看懂平台商业模型如何塑造内容与劳动。",
    vocabIds: ["w:platform-business-model", "w:platform-capitalism", "w:platform-economy", "w:platform-labor", "w:platform-regulation"],
    grammarTopicId: "present-simple",
    phonicsRuleIds: ["ee", "st", "oi"],
    pattern: {
      titleZh: "句型：The platform owns the lane, not the car. / Who sets the fee the maker never sees?",
      explainZh: "平台两句话：所有权 the platform owns the lane, not the car;分成 who sets the fee…。规则、流量、抽成都在平台手里。",
      examples: [
        ["The platform owns the lane, not the car.", "平台拥有车道，不拥有车。"],
        ["Who sets the fee the maker never sees printed?", "谁定下制作者永远看不见印在纸上的分成？"],
        ["Platform labor moves at the pace of the clockand the algorithm.", "平台劳动跟着时钟和算法奔跑。"],
      ],
      sentences: [
        ["The marketplace is the gate; the gate writes the rules.", "市场是门，门来写规则。"],
        ["Regulation arrives the moment the gate leaks.", "门漏水的瞬间监管就到了。"],
        ["Makers rent attention; the landlord keeps the lease.", "制作者租用注意力，房东攥着租约。"],
      ],
    },
    reading: [
      ["The driver knew every fare and nothing of the fare rule.", "司机知道每一单价，却不知价格规则的一行。"],
      ["Regulators studied the lane, not just the cars.", "监管者研究车道，不只是车辆。"],
      ["A small platform change moved a city's income curve.", "一次小平台改动移动了一座城市的收入曲线。"],
    ],
    writing: { zh: "写一个平台与你（创作者/消费者）之间的权力差。", hintEn: "Platform sets ___. I cannot ___. Fix: ___." },
  },
  {
    day: 313,
    titleEn: "AI as a Colleague",
    titleZh: "第 313 天 · AI 同事",
    goalZh: "讨论 AI 该做、不该做与谁负责。",
    vocabIds: ["w:ai-ethics-board", "w:ai-governance", "w:ai-safety", "w:ai-liability", "w:ai-regulation"],
    grammarTopicId: "future-simple",
    phonicsRuleIds: ["ee", "st", "oi"],
    pattern: {
      titleZh: "句型：The AI drafts, the human owns. / Who answers when the draft misfires?",
      explainZh: "协作两句：分工 the AI drafts, the human owns;责任 who answers when…。给 AI 设边界，就是给人类留责任。",
      examples: [
        ["The AI drafts, the human owns the final call.", "AI 起草，人类终审。"],
        ["Who answers when the model misfires in production?", "模型在生产环境失灵时谁来担责？"],
        ["An ethics board reviews the rollout before it ships.", "伦理委员会在发布前审查这次上线。"],
      ],
      sentences: [
        ["Governance is the seatbelt of automation.", "治理是自动化的安全带。"],
        ["Liability follows the last human with a lever.", "责任跟随最后握着操纵杆的人。"],
        ["Safety is a review date, not a slogan.", "安全是一个审查日期，不是口号。"],
      ],
    },
    reading: [
      ["The draft was fast; the error was inherited from the data.", "草稿很快，错误继承自数据。"],
      ["An ownership rule settled a month of blame games.", "一条归属规则结束了一个月的甩锅游戏。"],
      ["The board review found the blind spot before the leak.", "委员会审查在泄漏前找到盲区。"],
    ],
    writing: { zh: "写下你与 AI 协作的一条分工与责任线。", hintEn: "AI does ___. I own ___. If it fails, ___ answers." },
  },
  {
    day: 314,
    titleEn: "Machine Learning in English",
    titleZh: "第 314 天 · 机器学习的语言",
    goalZh: "用权日常英语解释模型工作的三件事。",
    vocabIds: ["w:machine-learning", "w:machine-learning-supervised", "w:machine-learning-patterns-without-rules-explained", "w:machine-learning-model-drift", "w:algorithm-bias-training-data-inheritance-problem"],
    grammarTopicId: "past-simple",
    phonicsRuleIds: ["ee", "st", "oi"],
    pattern: {
      titleZh: "句型：The model learns a pattern from examples, not rules. / Drift means the past stops explaining the present.",
      explainZh: "模型大白话：机制 learns a pattern from examples;监督 labeled examples teach it;漂移 the past stops explaining the present。模型不是规则表，是模式放大器。",
      examples: [
        ["The model learns a pattern from examples, not rules.", "模型从例子里学模式，不是学规则。"],
        ["Drift means the past stops explaining the present.", "漂移意味着过去不再解释现在。"],
        ["Labeled examples teach the supervised model its map.", "带标签的样本教会监督模型它的地图。"],
      ],
      sentences: [
        ["Predictions inherit the room they trained in.", "预测继承训练它的那个房间。"],
        ["Drift is the model growing old in real time.", "漂移是模型实时变老。"],
        ["Explain the pattern, not the parameters.", "解释模式，不要解释参数。"],
      ],
    },
    reading: [
      ["The spam filter learned the new trick from fresh labels.", "垃圾过滤器从新标签上学会新把戏。"],
      ["Model drift sent the winter forecast off the rails.", "模型漂移让冬季预报跑偏。"],
      ["Training-data inheritance made the algorithm an heir.", "训练数据继承让算法成了继承人。"],
    ],
    writing: { zh: "用三句话向外行解释一个模型的输出。", hintEn: "Input: ___. Learned pattern: ___. Drift risk: ___." },
  },
  {
    day: 315,
    titleEn: "Who Wrote This?",
    titleZh: "第 315 天 · 谁写的？",
    goalZh: "评估生成内容的作者性与可信度。",
    vocabIds: ["w:ai-literacy", "w:source-credibility", "w:misinformation-error", "w:fact-checking-team-verifies", "w:algorithmic-bias"],
    grammarTopicId: "questions",
    phonicsRuleIds: ["ee", "st", "oi"],
    pattern: {
      titleZh: "句型：Human or model, the claim still needs a source. / The author line is missing here.",
      explainZh: "作者三查：是否署名 the author line is missing;是否可核 the claim needs a source;是否偏见 algorithmic bias 在这里生效。生成得越顺，越要查源头。",
      examples: [
        ["Human or model, the claim still needs a source.", "无论人写还是模型写，主张都需要出处。"],
        ["The author line is missing here, and so is the date.", "这里缺作者行，也缺日期。"],
        ["AI proficiency includes spotting the model's tell.", "AI 素养包括看出模型的记号。"],
      ],
      sentences: [
        ["Fluency is not evidence, however elegant.", "流利不是证据，多优雅也一样。"],
        ["Check the claim, not the comma.", "查主张，不要查逗号。"],
        ["The unresolved question is who verifies the verifier.", "悬而未决的问题是：谁核查核查者。"],
      ],
    },
    reading: [
      ["The elegant note decayed once the source line failed.", "来源行失效后，优雅的笔记迅速瓦解。"],
      ["Learners rated author lines before rating content.", "学员先评作者行再评内容。"],
      ["A labeled AI draft read smoother but cited nothing.", "标注 AI 的草稿读起来更顺，却零引用。"],
    ],
    writing: { zh: "给你看到的任意文本做一次作者性检查。", hintEn: "Author: ___. Source offered: ___. Risk: ___." },
  },
  {
    day: 316,
    titleEn: "Viral Mechanics",
    titleZh: "第 316 天 · 病毒式机制",
    goalZh: "拆解什么让内容疯传，什么让护栏生效。",
    vocabIds: ["w:virality-spread", "w:viral-coefficient", "w:influencer-marketing-roi-debate", "w:influencer-fatigue-authenticity-premium-era", "w:news-value"],
    grammarTopicId: "articles",
    phonicsRuleIds: ["ee", "st", "oi"],
    pattern: {
      titleZh: "句型：Viral needs emotion, surprise, and a shareable frame. / The 48-hour window decides the wave.",
      explainZh: "疯传三要素：情绪 emotion;惊奇 surprise;可转框 a shareable frame。48 小时窗口决定浪高；转发是投票。",
      examples: [
        ["Viral needs emotion, surprise, and a shareable frame.", "病毒式传播需要情绪、惊奇和可分享的框架。"],
        ["The 48-hour window decides whether the wave breaks.", "四十八小时窗口决定浪会不会破。"],
        ["Authenticity fatigue made the plain voice premium again.", "真实感疲劳让朴素的声音重新值钱。"],
      ],
      sentences: [
        ["Every share is a vote for more of the same.", "每一次转发都是给同类内容投票。"],
        ["The coefficient says how many friends come with one post.", "病毒系数说明一条帖带来几位朋友。"],
        ["Influencer ROI debates are ads arguing about ads.", "网红 ROI 之争是广告在争论广告。"],
      ],
    },
    reading: [
      ["The slow truth lost to the fast emoji by a day.", "慢速真相输给快速表情一天之差。"],
      ["A community backlash flattened the sponsored wave.", "社区反弹压平了赞助式浪潮。"],
      ["Reduced amplification boosted the plain writer overnight.", "减小放大反而让朴素作者一夜爆红。"],
    ],
    writing: { zh: "描述你转发过的最后一条内容并标注三要素。", hintEn: "Post: ___. Emotion: ___. Surprise: ___. Share frame: ___." },
  },
  {
    day: 317,
    titleEn: "Reading Data Visuals",
    titleZh: "第 317 天 · 读懂数据图",
    goalZh: "检查图表的口径、截断与标尺陷阱。",
    vocabIds: ["w:information-content", "w:information-bias", "w:digital-trace-data", "w:information-retrieval-system", "w:correlation"],
    grammarTopicId: "prepositions-basic",
    phonicsRuleIds: ["ee", "st", "oi"],
    pattern: {
      titleZh: "句型：The axis starts at a number that flatters. / Who collected this trace and why?",
      explainZh: "看图四问：标尺 does the axis start at…;口径 what is counted as…?;来源 who collected this?;背景 what is beside the bars。图表是修辞的一种。",
      examples: [
        ["The axis starts at sixty, which flatters the rise.", "纵轴从六十开始，把上升衬托得更好看。"],
        ["Who collected this trace data and for what goal?", "这组痕迹数据谁采集、为了什么目的？"],
        ["The bar blinks, but the baseline whispers.", "柱子闪光，基线低语。"],
      ],
      sentences: [
        ["A chart lies politely with the mute axis.", "图表用沉默的坐标轴礼貌地说谎。"],
        ["Ask the denominator before the headline number.", "在读头条数字前先问分母。"],
        ["Retrieval finds what the index chose to keep.", "检索找到的是索引选择保留的内容。"],
      ],
    },
    reading: [
      ["The truncated axis turned a dip into a cliff.", "截断的坐标轴把一段下滑变成悬崖。"],
      ["The double chart told the same data half the truth.", "双图把同一组数据只说半句真话。"],
      ["Reading the axes first became their new habit.", "先看坐标轴成了他们的新习惯。"],
    ],
    writing: { zh: "为一张你见过的图写标尺与口径检查。", hintEn: "Axis starts at ___. Counted as ___. Missing: ___." },
  },
  {
    day: 318,
    titleEn: "Automation & Work",
    titleZh: "第 318 天 · 自动化与就业",
    goalZh: "区分被自动化取代的任务与被增强的岗位。",
    vocabIds: ["w:automation-anxiety", "w:automation-script-weekly-report-magic-tricks", "w:disruptive-technology", "w:technology-adoption-life-cycle", "w:digital-labor"],
    grammarTopicId: "countable-uncountable",
    phonicsRuleIds: ["ee", "st", "oi"],
    pattern: {
      titleZh: "句型：Automation removes tasks before it removes jobs. / The skill that survives is ___.",
      explainZh: "自动化两句话：任务先于岗位 automation removes tasks before jobs;留存技能 the skill that survives is…。写脚本替掉自己手上的杂活，是第一步。",
      examples: [
        ["Automation removes tasks before it removes jobs.", "自动化先移除任务，再触及岗位。"],
        ["The skill that survives is judging when to trust the machine.", "存活下来的技能是判断何时相信机器。"],
        ["A script that files the report buys back the Friday.", "一个自动归档报告的脚本买回了周五。"],
      ],
      sentences: [
        ["Anxiety is honest, but the task list is a better map.", "焦虑很诚实，但任务清单是更好的地图。"],
        ["Adoption curves lag the hype by at least a decade.", "采纳曲线至少滞后炒作十年。"],
        ["Digital labor grows where the guardrails sleep.", "数字劳动在护栏睡觉处长出来。"],
      ],
    },
    reading: [
      ["The payroll script did in minutes what a day measured.", "薪酬脚本用分钟完成了按天计量的活。"],
      ["Workers who automated their pain doubled their craft time.", "自动化掉痛苦环节的工人把手艺时间翻倍。"],
      ["The adoption curve disappointed the panic twice.", "采纳曲线两次让恐慌失望。"],
    ],
    writing: { zh: "找出你手上一件可自动化的重复任务。", hintEn: "Task: ___. Tool: ___. Time saved weekly: ___." },
  },
  {
    day: 319,
    titleEn: "Innovation Rhetoric",
    titleZh: "第 319 天 · 创新话语",
    goalZh: "区分创新、颠覆与炒作三种说法。",
    vocabIds: ["w:disruptive-innovation", "w:disruption-narrative", "w:technology-push", "w:technology-assessment", "w:technology-transfer"],
    grammarTopicId: "pronouns-basic",
    phonicsRuleIds: ["ee", "st", "oi"],
    pattern: {
      titleZh: "句型：Incremental improves; disruptive rewires the category. / The hype narrative outruns the assessment.",
      explainZh: "创新三词：渐进 incremental improves;颠覆 disruptive rewires;炒作 hype outruns assessment。喊颠覆之前先问成本、风险与替代。",
      examples: [
        ["Incremental improves; disruptive rewires the category.", "渐进式改善品类，颠覆式重建品类。"],
        ["The hype narrative outpaced the technical assessment.", "炒作叙事跑赢了技术评估。"],
        ["Technology push succeeds when the pull was waiting.", "技术推动在需求早已等待时才成功。"],
      ],
      sentences: [
        ["Every disruption story needs a budget line.", "每个颠覆故事都需要一个预算栏。"],
        ["Assessment is the quiet cousin of the launch party.", "评估是发布会安静的亲戚。"],
        ["The transfer is where the research meets the road.", "转移点才是研究与现实相遇之处。"],
      ],
    },
    reading: [
      ["The incremental win outprofited the circus of hype.", "渐进式胜利比喧嚣炒作更赚钱。"],
      ["The reassessment moved the pilot back a quarter.", "再评估把试点推后了一个季度。"],
      ["Technology transfer survived where the demo decayed.", "演示过期之处，技术转移仍生存。"],
    ],
    writing: { zh: "给一条最新科技说法标上创新/颠覆/炒作。", hintEn: "Claim: ___. Category: ___. Evidence: ___." },
  },
  {
    day: 320,
    titleEn: "Assessing Tech Claims",
    titleZh: "第 320 天 · 评估技术论点",
    goalZh: "用成熟度与证据评估任何新科技声明。",
    vocabIds: ["w:technology-readiness-level", "w:fact-checking", "w:algorithmic-impact-assessment", "w:media-literacy-skill", "w:information-literacy"],
    grammarTopicId: "be-verb",
    phonicsRuleIds: ["ee", "st", "oi"],
    pattern: {
      titleZh: "句型：This claim sits at readiness level two. / What would falsify this promise?",
      explainZh: "评估三问：成熟度 readiness level;可证伪 what would falsify this promise?;谁受益 who profits from the excitement。媒体素养是把冷却的审问。",
      examples: [
        ["This claim sits at readiness level two, not nine.", "这个说法在成熟度二级，不是九级。"],
        ["What would falsify this promise within a year?", "一年内什么能证伪这个承诺？"],
        ["Media literacy is the toolkit for reading the future calmly.", "媒介素养是冷静读未来的随身工具。"],
      ],
      sentences: [
        ["Readiness level beats press-release temperature.", "成熟度等级胜过新闻稿的体温。"],
        ["A falsifiable claim is a scientific citizen.", "可证伪的主张才是科学公民。"],
        ["Literacy turns headlines back into hypotheses.", "素养把头条变回假设。"],
      ],
    },
    reading: [
      ["The level-two demo starved of investment for a reason.", "二级的演示没拿到投资是有原因的。"],
      ["Falsifying the promise took less than a quarter.", "证伪那个承诺花不到一个季度。"],
      ["A cool toolkit calmed the fever of the demo room.", "冷工具包给演示间的热度降温。"],
    ],
    writing: { zh: "给一个近期技术名词做成熟度评估。", hintEn: "Claim: ___. Level: ___. Falsifier: ___." },
  },
  {
    day: 321,
    titleEn: "Media Ownership",
    titleZh: "第 321 天 · 媒体所有权",
    goalZh: "把媒体所有权与编辑选择挂起钩来。",
    vocabIds: ["w:media-consolidation", "w:media-convergence", "w:media-ecology", "w:media-relations", "w:platform-regulation"],
    grammarTopicId: "present-simple",
    phonicsRuleIds: ["ee", "st", "oi"],
    pattern: {
      titleZh: "句型：Fewer owners, quieter dissent. / Convergence merges the paper and the feed.",
      explainZh: "所有权两句话：集中 fewer owners, quieter dissent;融合 convergence merges the paper and the feed。追问谁拥有，是媒体素养的基建。",
      examples: [
        ["Fewer owners, quieter dissent in the local newsroom.", "老板越少，本地编辑部异议越安静。"],
        ["Convergence merges the paper, the feed, and the studio.", "融合把报纸、信息流和演播室揉成一团。"],
        ["The media ecology sets what counts as climate news.", "媒体生态决定什么算气候新闻。"],
      ],
      sentences: [
        ["Ownership is the first frame no one sees.", "所有权是没人看见的第一层框架。"],
        ["A healthy ecology needs at least two loud rooms.", "健康的生态至少需要两个大声的房间。"],
        ["Regulation arrives where the lane narrows.", "监管出现在车道变窄处。"],
      ],
    },
    reading: [
      ["The merger thinned the local pages and the local voices.", "合并削薄了本地版面与本地声音。"],
      ["Media-relations wires wrote a third of the news.", "媒体关系通稿写掉了三分之一的新闻。"],
      ["The studio, feed, and paper now share one boss.", "演播室、信息流与报纸如今共享一位老板。"],
    ],
    writing: { zh: "查一条你常读新闻的母公司并写一句话。", hintEn: "Outlet: ___. Owner: ___. Effect: ___." },
  },
  {
    day: 322,
    titleEn: "Sources & Trust",
    titleZh: "第 322 天 · 信源与信任",
    goalZh: "按事实验证一处来源，区分举报人与信使。",
    vocabIds: ["w:source-credibility", "w:source-protection", "w:journalistic-ethics", "w:newsroom-deadline-pressure", "w:newsworthiness-value"],
    grammarTopicId: "past-simple",
    phonicsRuleIds: ["ee", "st", "oi"],
    pattern: {
      titleZh: "句型：The whistleblower sources the claim; the outlet sources the source. / Under deadline, verification thins.",
      explainZh: "信源两句话：来源链 the whistleblower sources the claim;压力下 under deadline, verification thins。先验来源再议观点。",
      examples: [
        ["The whistleblower sources the claim; the outlet checks it.", "吹哨人给出主张，媒体去核它。"],
        ["Under deadline pressure, verification famously thins.", "截止压力下，核查容易变薄。"],
        ["Source credibility is earned in the pattern, not the scoop.", "信源可信度靠模式挣得，不是靠独家。"],
      ],
      sentences: [
        ["Trust the pattern of sources, not the single leak.", "相信来源的模式，不要迷信一次泄漏。"],
        ["A protected source pays the debt of truth.", "受保护的来源偿付真相的债务。"],
        ["Newsroom rules exist exactly for the thin hours.", "编辑部规则恰恰为最薄的时段存在。"],
      ],
    },
    reading: [
      ["The pattern of three sources held under the first attack.", "三条来源的模式在首轮攻击下站住。"],
      ["The deadline edit softened the caveat out of the piece.", "截止编辑把保留意见从稿子里软化掉。"],
      ["Whistleblowers returned when the policy protected a name.", "政策保护住一个名字后，吹哨人回来了。"],
    ],
    writing: { zh: "为你看过的报道写来源链审记。", hintEn: "Claim: ___. Original source: ___. Verified by: ___." },
  },
  {
    day: 323,
    titleEn: "Information Fitness",
    titleZh: "第 323 天 · 信息健身",
    goalZh: "给信息摄入做训练：筛源、限流、复核。",
    vocabIds: ["w:information-literacy", "w:information-overload", "w:information-asymmetry", "w:information-society", "w:media-literacy"],
    grammarTopicId: "future-simple",
    phonicsRuleIds: ["ee", "st", "oi"],
    pattern: {
      titleZh: "句型：I read three sources before I share. / The asymmetry here favors ___.",
      explainZh: "信息健身三招：多源 I read three sources before sharing;限流 a daily cap on ___;查身份 who is talking to me and why。信息不对称时强者会沉默。",
      examples: [
        ["I read three sources before I share anything.", "分享前我先读三个来源。"],
        ["The asymmetry here favours the seller of the package.", "这里的信息不对称偏向卖套餐的人。"],
        ["A daily cap on feeds made the evening longer.", "给信息流设每日上限让夜晚变长了。"],
      ],
      sentences: [
        ["Feeds are a gym; unplugging is the recovery day.", "信息流是健身房，断联是恢复日。"],
        ["The informed party prices the silence of the other.", "信息充分一方在为对方的沉默定价。"],
        ["Literacy is the set, not the machine.", "素养是那套动作，不是那台机器。"],
      ],
    },
    reading: [
      ["Three-source rule cut the regret shares immediately.", "三源规则立刻削减了后悔式转发。"],
      ["The arrangement gave the operator the quiet edge.", "安排给了运营者沉默的优势。"],
      ["A capped feed brought back a room of opinions.", "限量信息流带回一屋子的观点。"],
    ],
    writing: { zh: "写下你的信息摄入规则三条。", hintEn: "Source rule: ___. Cap: ___. Before sharing: ___." },
  },
  {
    day: 324,
    titleEn: "Bias in the Feed",
    titleZh: "第 324 天 · 信息流里的偏见",
    goalZh: "识别推荐流中训练数据与反馈的偏见。",
    vocabIds: ["w:algorithmic-bias", "w:algorithm-bias-training-data-inheritance-problem", "w:filter-bubble-isolation", "w:echo-chamber-reinforcement", "w:information-bias"],
    grammarTopicId: "negation",
    phonicsRuleIds: ["ee", "st", "oi"],
    pattern: {
      titleZh: "句型：The feed inherits the bias of its training. / What I click tunes the next round.",
      explainZh: "偏见两句：继承 the feed inherits the bias of its training;互动画笔 what I click tunes the next round。点击是最小的人工，也是最大的握手。",
      examples: [
        ["The feed inherits the bias of its training corpus.", "信息流继承训练语料的偏见。"],
        ["What I click tunes the next round of suggestions.", "我的点击给下一轮推荐调音。"],
        ["Reinforcement made the rare opinion feel mainstream.", "强化让稀有观点显得像主流。"],
      ],
      sentences: [
        ["The algorithm is a student of the swarm.", "算法是集群的学生。"],
        ["My clicks are tuition; the course is the norm.", "我的点击是学费，课程是常态。"],
        ["Information bias prunes what the frame already rejects.", "信息偏倚剪掉框架早已拒绝的内容。"],
      ],
    },
    reading: [
      ["The voting dataset signed its bias into the ranks.", "投票数据集把偏见签进了排序。"],
      ["One user's clicks retrained a month of recommendations.", "一位用户的点击重训了一个月的推荐。"],
      ["The confirmation loop tightened until a stranger broke it.", "确认回路越缩越紧，直到一个陌生人打破。"],
    ],
    writing: { zh: "识别你信息流里的一种偏向。", hintEn: "My feed over-favors ___. Inherited from: ___." },
  },
  {
    day: 325,
    titleEn: "The Digital Self",
    titleZh: "第 325 天 · 数字自我",
    goalZh: "统一线上身份、足迹与遗产的三层管理。",
    vocabIds: ["w:digital-identity", "w:digital-footprint", "w:digital-estate", "w:digital-commons", "w:surveillance-capitalism"],
    grammarTopicId: "basic-clauses",
    phonicsRuleIds: ["ee", "st", "oi"],
    pattern: {
      titleZh: "句型：Identity is what I claim; footprint is what I leave. / The estate plan names the heirs of my accounts.",
      explainZh: "三层自我：身份 what I claim;足迹 what I leave;遗产 who inherits my accounts。把三层分开写，数字自我才立得住。",
      examples: [
        ["Identity is what I claim; footprint is what I leave.", "身份是我声称的，足迹是我留下的。"],
        ["The estate plan names the heirs of my accounts.", "遗产计划写明了账号的继承人。"],
        ["Surveillance capitalism writes my profile in my quiet.", "监控资本主义在我的沉默里写我的档案。"],
      ],
      sentences: [
        ["The commons grow when the corporation gates more.", "公司圈更多地时，公地反而生长。"],
        ["A claimed identity is a promise; a footprint is evidence.", "声称的身份是承诺，足迹是证据。"],
        ["Decide your digital will before the letters decide you.", "在字母替你决定前，写好数字遗嘱。"],
      ],
    },
    reading: [
      ["The identity audit found three old selves.", "身份审计找到三个陈旧的自己。"],
      ["A clear estate note kept the family out of the reset loop.", "一份清晰的遗产说明让家人跳出重置循环。"],
      ["Shared commons digitized the town archive overnight.", "共享公地一夜之间数字化了镇档案。"],
    ],
    writing: { zh: "写三行：你的身份、足迹与遗产意图。", hintEn: "Identity: ___. Footprint: ___. Estate: ___." },
  },
  {
    day: 326,
    titleEn: "Governing the Network",
    titleZh: "第 326 天 · 治理互联网",
    goalZh: "讨论平台、监控与算法应受哪些约束。",
    vocabIds: ["w:ai-regulation", "w:platform-regulation", "w:surveillance", "w:digital-markets-act", "w:algorithmic-accountability"],
    grammarTopicId: "questions",
    phonicsRuleIds: ["ee", "st", "oi"],
    pattern: {
      titleZh: "句型：The rule exists to cap the gate, not to break it. / Who enforces this act on the serving floor?",
      explainZh: "治理两句：目标 the rule caps the gate, not breaks it;执行 who enforces this act…。规制不反平台，只反圈地与沉默。",
      examples: [
        ["The rule exists to cap the gate, not to break it.", "规则存在的目的是给门设限，不是破门。"],
        ["Who enforces this act across three jurisdictions?", "谁来横跨三个法域执行这部法案？"],
        ["Algorithmic accountability names who files the audit.", "算法问责制写明谁提交审计报告。"],
      ],
      sentences: [
        ["Regulation is the tape, not the taste.", "监管是标尺，不是口味。"],
        ["Surveillance grows fastest where the report is darkest.", "报告越暗，监控长得越快。"],
        ["A gate with a cap still opens for the honest traffic.", "有上限的门仍为诚实交通开放。"],
      ],
    },
    reading: [
      ["The markets act capped the self-preference quietly.", "市场法案悄悄限定了自优先。"],
      ["Enforcement lagged the rule by two courts.", "执行比规则落后两个法院。"],
      ["Auditors filed the first algorithmic report on time.", "审计员按时递交了第一份算法报告。"],
    ],
    writing: { zh: "写一条你支持或反对的网络规则及理由。", hintEn: "Rule: ___. For/against: ___. Reason: ___." },
  },
  {
    day: 327,
    titleEn: "Telling Tech Stories",
    titleZh: "第 327 天 · 讲述科技故事",
    goalZh: "把技术变革讲成有数据、有普通人的故事。",
    vocabIds: ["w:disruption-narrative", "w:technology-adoption-life-cycle", "w:ai-literacy", "w:media-ecology", "w:virality-spread"],
    grammarTopicId: "present-simple",
    phonicsRuleIds: ["ee", "st", "oi"],
    pattern: {
      titleZh: "句型：The story needs a user with a name and a mug. / Avoid the arc that makes machines the hero.",
      explainZh: "叙事两律：具体的人 a user with a name;别让机器当男主角 the arc that makes machines the hero。技术好事讲人变强，坏事讲谁受伤。",
      examples: [
        ["The story needs a user with a name and a daily habit.", "故事需要一个有名有姓、有日常习惯的用户。"],
        ["Avoid the arc that makes machines the hero of the workday.", "别用机器当工作日的男主角这种主线。"],
        ["The adoption curve explains the hump of lost interest.", "采纳曲线解释了兴趣的回落坡。"],
      ],
      sentences: [
        ["Great tech stories star the human, not the chip.", "好的科技故事主角是人，不是芯片。"],
        ["A named user beats a cited market twice.", "有名有姓的用户两次胜过被引用的市场。"],
        ["Media ecology shapes which future feels nearby.", "媒介生态决定哪种未来显得近在咫尺。"],
      ],
    },
    reading: [
      ["The farmer's morning became the platform's best proof.", "农户的早晨成了平台最好的证明。"],
      ["The hero-chip arc drew funding and missed users.", "芯片英雄主线招来投资，跑掉用户。"],
      ["Named users flattened the curve of the hype cycle.", "有名用户压平了炒作周期的尖峰。"],
    ],
    writing: { zh: "写两行技术故事的骨架：名+习惯。", hintEn: "User: ___. Habit: ___. Tech changed: ___." },
  },
  {
    day: 328,
    titleEn: "Debating Tech Futures",
    titleZh: "第 328 天 · 辩论技术的未来",
    goalZh: "用主张-理由-证据结构辩论 AI 与就业。",
    vocabIds: ["w:ai-safety", "w:disruptive-innovation", "w:automation-anxiety", "w:digital-divide", "w:attention-economy"],
    grammarTopicId: "articles",
    phonicsRuleIds: ["ee", "st", "oi"],
    pattern: {
      titleZh: "句型：My claim: automation will widen the divide first. / The reason is skills lag access.",
      explainZh: "辩论结构：主张 my claim…;理由 the reason is…;证据 the evidence is…。正反各说一轮再定立场，别一开场就押边。",
      examples: [
        ["My claim: automation will widen the divide first.", "我的主张：自动化会先拉大鸿沟。"],
        ["The reason is skills lag access by a decade.", "理由是技能落后接入十年。"],
        ["The evidence is the adoption curves of three sectors.", "证据是三个行业的采纳曲线。"],
      ],
      sentences: [
        ["State the other side loudly, then argue against it.", "先大声复述对方，再反驳它。"],
        ["Safety frameworks are the debate's fire escapes.", "安全框架是这场辩论的消防梯。"],
        ["The attention economy is the silent side of every vote.", "注意力经济是每次投票沉默的一方。"],
      ],
    },
    reading: [
      ["The claim-reason-evidence rule calmed the shouted room.", "主张-理由-证据规则让喧闹的屋子安静。"],
      ["The recorded rebuttal changed three minds slowly.", "录下的反驳慢慢改变三个人的观念。"],
      ["Divide arguments carried more maps than memes.", "鸿沟论战带了更多地图而非梗图。"],
    ],
    writing: { zh: "写一轮主张-理由-证据的技术辩论。", hintEn: "Claim: ___. Reason: ___. Evidence: ___." },
  },
  {
    day: 329,
    titleEn: "Designing Your Media Diet",
    titleZh: "第 329 天 · 设计媒体食谱",
    goalZh: "按目标、来源与时段设计你自己的信息摄入。",
    vocabIds: ["w:media-literacy-skill", "w:digital-wellness", "w:attention-economy", "w:information-overload", "w:source-credibility"],
    grammarTopicId: "be-verb",
    phonicsRuleIds: ["ee", "st", "oi"],
    pattern: {
      titleZh: "句型：My diet adds ___ and drops ___. / Feeding mornings news, evenings depth.",
      explainZh: "食谱设计：加一项 adds…;减一项 drops…;分时段 mornings news, evenings depth。把摄入当菜单，不是当瀑布。",
      examples: [
        ["My diet adds one primary source a week and drops the doom feed.", "我的食谱每周加一个一手来源，砍掉焦虑流。"],
        ["Feeding mornings with news, evenings with depth.", "早晨喂新闻，晚间喂深度。"],
        ["A shortlist of named outlets replaces the infinite shelf.", "一张点名媒体清单取代无限货架。"],
      ],
      sentences: [
        ["Curate the menu; the feed will curate you.", "你来策展菜单，否则信息流策展你。"],
        ["Depth is the slow digest of the fast news.", "深度是对快新闻的慢消化。"],
        ["Distance from the inbox is a form of literacy.", "与收件箱保持距离是一种素养。"],
      ],
    },
    reading: [
      ["The one-primary-source weekly rule aged well.", "每周一个一手来源的规则越用越好。"],
      ["A named-outlet shelf cut the scroll anemone.", "点名媒体清单切掉海葵般的滚动。"],
      ["Mornings-news, evenings-depth fixed the cortisol curve.", "早晨新闻晚间深度修好了皮质醇曲线。"],
    ],
    writing: { zh: "写下你的媒介食谱：加法、减法、时段。", hintEn: "Add: ___. Drop: ___. Schedule: ___." },
  },
  {
    day: 330,
    titleEn: "Block E Review & Assessment",
    titleZh: "第 330 天 · 媒介素养总结与测评",
    goalZh: "复盘 301-329 天媒介技能并完成一次媒体自评与规划。",
    vocabIds: ["w:media-literacy", "w:information-literacy", "w:digital-wellness", "w:algorithmic-accountability", "w:fact-checking"],
    grammarTopicId: "past-simple",
    phonicsRuleIds: ["ee", "st", "oi"],
    pattern: {
      titleZh: "句型：My media win this block was ___. / The check I now run daily is ___.",
      explainZh: "媒介终测：对照 301-329 的电环（框架、气泡、真伪、核查、注意力、足迹、隐私、算法、平台、AI、病毒、图表、所有权、食谱）逐环自评 1-5 分，写一份个人媒体守则。",
      examples: [
        ["My media win this block was running a real fact-check.", "这一块我最大的进步是完成了一次真实核查。"],
        ["The check I now run daily is the source-and-date scan.", "我现在每天跑的是来源加日期扫描。"],
        ["I rated my attention hygiene at four out of five.", "我给注意力卫生打四分。"],
      ],
      sentences: [
        ["A media diet built by hand survives the algorithm.", "亲手搭的媒体食谱扛得过算法。"],
        ["Fact-checking became a reflex, not a special event.", "事实核查成了反射，不是特殊事件。"],
        ["Block F applies this lens to the whole course wrap-up.", "F 块要用这个透镜给整门课收束。"],
      ],
    },
    reading: [
      ["Block E built frames, bubbles, privacy, and platform power.", "本块搭建框架、气泡、隐私与平台权力。"],
      ["The final task bundled a fact-check and a media diet.", "终测捆绑一次核查与一份媒体食谱。"],
      ["Learners recorded a two-minute media report in their voice.", "学员用自己的声音录下两分钟媒体报告。"],
    ],
    writing: { zh: "写你的个人媒体守则五条。", hintEn: "1 ___ . 2 ___ . 3 ___ . 4 ___ . 5 ___ ." },
  },
];