/**
 * Day 51-70 authored curriculum - 健康 / 兴趣 / 阶段复习 / 观点表达 / 经历描述.
 * Same factory pattern; vocab references the lexical model.
 */
import { buildDay } from "@/content/days/factory";

export const DAYS_51_70 = [
  buildDay({
    day: 51, titleEn: "Seeing a Doctor", titleZh: "第 51 天 · 看病就医",
    goalZh: "描述症状、预约医生。",
    vocabIds: ["w:appointment", "w:symptom", "w:prescription", "w:drugstore", "w:sore-throat", "w:dizzy"],
    grammarTopicId: "present-progressive",
    phonicsRuleIds: ["th-vd", "z"],
    pattern: {
      titleZh: "句型：I've had a ___ for two days. / I'm feeling dizzy.",
      explainZh: "说症状常用 I have a sore throat / I feel dizzy。说持续多久用 for + 时间。",
      examples: [["I'd like to make an appointment.", "我想预约挂号。"], ["I've had a sore-throat for two days.", "我嗓子疼两天了。"], ["I'm feeling dizzy this morning.", "我今天早上觉得头晕。"]],
      sentences: [["The doctor asks about your symptoms.", "医生会问你的症状。"], ["Take the prescription to the drugstore.", "拿处方去药房取药。"], ["Drink warm water and rest well.", "多喝温水，好好休息。"]],
    },
    reading: [
      ["Tom wakes up with a fever and a headache.", "汤姆醒来时发烧头疼。"],
      ["He calls the clinic and gets a same-day appointment.", "他打电话给诊所，约到了当天的号。"],
      ["The doctor checks him and writes a prescription.", "医生做了检查并开了处方。"],
    ],
    writing: { zh: "写一句你感冒不舒服时的感受。", hintEn: "I have a ___. I need to ___.", },
  }),
  buildDay({
    day: 52, titleEn: "Healthy Habits", titleZh: "第 52 天 · 健康习惯",
    goalZh: "谈论运动和饮食等日常健康习惯。",
    vocabIds: ["w:fitness", "w:workout", "w:junk-food", "w:organic", "w:routine", "w:balanced"],
    grammarTopicId: "present-simple",
    phonicsRuleIds: ["oo-l", "st"],
    pattern: {
      titleZh: "句型：I usually ___ every morning. / How often do you...?",
      explainZh: "谈习惯用一般现在时 + 频率词 usually / always / never。问频率用 How often?",
      examples: [["I usually work out three times a week.", "我通常一周锻炼三次。"], ["How often do you eat fast-food?", "你多久吃一次快餐？"], ["We buy organic vegetables when we can.", "条件允许时我们买有机蔬菜。"]],
      sentences: [["A balanced diet matters more than one big workout.", "均衡饮食比偶尔猛练更重要。"], ["My morning routine starts with water, not coffee.", "我的晨间流程从喝水开始，不是咖啡。"], ["Cutting junk-food is hard at first.", "戒垃圾食品一开始很难。"]],
    },
    reading: [
      ["Grandma walks thirty minutes every evening.", "奶奶每晚散步三十分钟。"],
      ["She also cooks fresh food instead of frozen meals.", "她还坚持做新鲜饭菜而不是冷冻食品。"],
      ["Her secret? A routine she never skips.", "她的秘诀？一个从不间断的日常安排。"],
    ],
    writing: { zh: "写一句你的一个健康习惯。", hintEn: "I ___ every day / week." },
  }),
  buildDay({
    day: 53, titleEn: "Mental Health", titleZh: "第 53 天 · 心理健康",
    goalZh: "谈论情绪压力，学会求助表达。",
    vocabIds: ["w:mental-health", "w:anxiety", "w:depression", "w:therapy", "w:anxious", "w:breathe"],
    grammarTopicId: "basic-clauses",
    phonicsRuleIds: ["th-vl", "ee"], phonicsPairId: "pair-three-tree",
    pattern: {
      titleZh: "句型：I feel ___ when ___. / It helps to ___.",
      explainZh: "表达情绪用 I feel + 情绪词 + when 从句。给建议说 It helps to + 动词原形（做…有帮助）。",
      examples: [["I feel anxious before big tests.", "大考前我会焦虑。"], ["I feel calm when I walk by the river.", "在河边走路让我平静。"], ["It helps to breathe slowly and count to ten.", "慢慢呼吸数到十很有帮助。"]],
      sentences: [["Talking to a friend eases stress.", "和朋友聊聊能减压。"], ["Therapy is normal and helpful.", "心理咨询很正常也很有帮助。"], ["Sleep matters for mental health too.", "睡眠对心理健康同样重要。"]],
    },
    reading: [
      ["Exams make Kevin anxious every term.", "每学期考试都让凯文焦虑。"],
      ["His school counselor teaches him a breathing trick.", "学校辅导老师教了他一个呼吸小技巧。"],
      ["Slow breaths in, slow breaths out — it really helps.", "慢慢吸气，慢慢呼气——真的很管用。"],
    ],
    writing: { zh: "写一句你放松心情的小方法。", hintEn: "When I feel stressed, it helps to ___." },
  }),
  buildDay({
    day: 54, titleEn: "Emergency!", titleZh: "第 54 天 · 紧急情况",
    goalZh: "紧急情况下的关键句型和求助表达。",
    vocabIds: ["w:ambulance", "w:first-aid", "w:emergency-room", "w:injury", "w:insurance", "w:bleed"],
    grammarTopicId: "questions",
    phonicsRuleIds: ["er", "st"],
    pattern: {
      titleZh: "句型：Call an ambulance! / Are you OK?",
      explainZh: "紧急时句子要短：Call 911! / Help! 询问状况说 Are you OK? 描述伤口用 bleed / injury。",
      examples: [["Call an ambulance, quickly!", "快叫救护车！"], ["Are you OK? Can you hear me?", "你还好吗？能听到我说话吗？"], ["My hand is bleeding.", "我的手在流血。"]],
      sentences: [["The first-aid kit is under the sink.", "急救箱在水槽下面。"], ["The emergency-room is on Maple Street.", "急诊室在枫树街。"], ["Bring your insurance card with you.", "带上你的医保卡。"]],
    },
    reading: [
      ["During the soccer game, Dan falls hard.", "足球比赛中丹重重摔倒。"],
      ["His knee bleeds; his friends run over.", "他的膝盖流血了，朋友们跑过来。"],
      ["The coach cleans the cut and calls his parents.", "教练清理了伤口并给他父母打了电话。"],
    ],
    writing: { zh: "写一句紧急情况下最重要的求助语并背下来。", hintEn: "Please call ___. My friend is ___." },
  }),
  buildDay({
    day: 55, titleEn: "Hospital & Recovery", titleZh: "第 55 天 · 医院与康复",
    goalZh: "谈论手术、治疗和康复过程。",
    vocabIds: ["w:surgeon", "w:surgery", "w:operation", "w:recovery", "w:treatment", "w:wheelchair"],
    grammarTopicId: "past-simple",
    phonicsRuleIds: ["or", "sh"],
    pattern: {
      titleZh: "句型：The operation went well. / She is recovering at home.",
      explainZh: "谈已发生的治疗用过去式：had an operation。正在康复用现在进行时 is recovering。",
      examples: [["The surgeon explained everything clearly.", "外科医生把一切解释得很清楚。"], ["The surgery took two hours.", "手术用了两小时。"], ["Grandpa had an operation on his knee.", "爷爷做了膝盖手术。"]],
      sentences: [["Recovery takes about six weeks.", "康复大约需要六周。"], ["The treatment works slowly but well.", "这种治疗见效慢但有效。"], ["He moved to a wheelchair for two weeks.", "他有两周时间坐轮椅。"]],
    },
    reading: [
      ["Aunt Lin fell and broke her wrist in March.", "林阿姨三月摔断了手腕。"],
      ["The operation was quick and safe.", "手术很快也很安全。"],
      ["Now she does therapy twice a week and feels stronger.", "现在她每周做两次理疗，感觉更有力气了。"],
    ],
    writing: { zh: "写一句鼓励病人的话。", hintEn: "Get well soon! I hope ___.", },
  }),
  buildDay({
    day: 56, titleEn: "Music & Movies", titleZh: "第 56 天 · 音乐影视",
    goalZh: "谈论喜欢的音乐、电影和节目类型。",
    vocabIds: ["w:podcast", "w:episode", "w:documentary", "w:sitcom", "w:thriller", "w:concert"],
    grammarTopicId: "basic-clauses",
    phonicsRuleIds: ["oi", "th-vd"],
    pattern: {
      titleZh: "句型：I'm watching ___ these days. / I like shows that ___.",
      explainZh: "最近在看用进行时 I'm watching...。表达喜好从句：I like movies that make me laugh.",
      examples: [["I'm watching a new documentary these days.", "我最近在看一部新纪录片。"], ["I like sitcoms that make me laugh.", "我喜欢让我大笑的情景喜剧。"], ["That thriller kept me up all night.", "那部惊悚片让我一夜没睡。"]],
      sentences: [["The concert starts at eight tonight.", "演唱会今晚八点开始。"], ["One more episode, then sleep — promise!", "再看一集就睡——说好了！"], ["My favorite podcast comes out on Fridays.", "我最爱的播客每周五更新。"]],
    },
    reading: [
      ["Friday nights are movie nights for the Wangs.", "周五晚上是王家人的观影夜。"],
      ["Dad picks thrillers; Mom wants comedies; they compromise with documentaries.", "爸爸选惊悚片，妈妈要喜剧，最后折中看纪录片。"],
      ["Everyone agrees on popcorn first.", "唯一一致的是先爆米花。"],
    ],
    writing: { zh: "写一句你最近在看的剧或听的播客及感受。", hintEn: "I'm watching/listening to ___. It's ___.", },
  }),
  buildDay({
    day: 57, titleEn: "Sports Talk", titleZh: "第 57 天 · 体育运动",
    goalZh: "谈论比赛结果和运动经历。",
    vocabIds: ["w:marathon", "w:tournament", "w:teammate", "w:referee", "w:championship", "w:opponent"],
    grammarTopicId: "past-simple",
    phonicsRuleIds: ["or", "sp"], phonicsPairId: "pair-work-walk",
    pattern: {
      titleZh: "句型：We won the game! / Who scored the last point?",
      explainZh: "比赛结果用过去式：won / lost / tied。问细节用 Who / What + 过去式？",
      examples: [["We won yesterday's game 3-1.", "我们昨天三比一赢了。"], ["Who won the championship last year?", "去年冠军是谁？"], ["The referee blew the whistle.", "裁判吹哨了。"]],
      sentences: [["My teammates cheered all game long.", "队友们整场都在欢呼。"], ["She trained six months for the marathon.", "她为马拉松训练了六个月。"], ["Respect your opponent and play fair.", "尊重对手，公平比赛。"]],
    },
    reading: [
      ["Saturday was the school basketball tournament.", "周六是学校篮球锦标赛。"],
      ["Class 2B beat Class 3A in the final minute.", "二班在最后一分钟击败了三班。"],
      ["Even the losing team smiled — it was a great match.", "连输的队伍都笑了——真是场好球。"],
    ],
    writing: { zh: "写一句你最近看或参加的一场比赛。", hintEn: "Last week, I watched/played ___. The score was ___.", },
  }),
  buildDay({
    day: 58, titleEn: "Games & Collections", titleZh: "第 58 天 · 游戏与收藏",
    goalZh: "谈论桌游、游戏与收藏爱好。",
    vocabIds: ["w:board-game", "w:video-game", "w:crossword", "w:collection", "w:puzzle", "w:riddle"],
    grammarTopicId: "present-progressive",
    phonicsRuleIds: ["igh", "ng"],
    pattern: {
      titleZh: "句型：I'm collecting ___ . / Are you good at ___?",
      explainZh: "说正在进行的爱好用 I'm collecting/playing...。问擅长什么用 be good at + 名词/动名词。",
      examples: [["I'm building a stamp collection.", "我在收集邮票。"], ["Are you good at chess?", "你国际象棋下得好吗？"], ["We're playing a board-game tonight.", "我们今晚玩桌游。"]],
      sentences: [["This puzzle has a thousand pieces.", "这个拼图有一千块。"], ["Grandma solves the crossword every Sunday.", "奶奶每周日做填字游戏。"], ["One more video-game round, then bed.", "再玩一局游戏就睡。"]],
    },
    reading: [
      ["Rainy Saturdays are for board-games at Leo's house.", "下雨的周六是利奥家的桌游日。"],
      ["His sister is winning three games in a row.", "他姐姐已经连赢三局了。"],
      ["Leo doesn't mind — he's busy with his coin collection anyway.", "利奥不介意——反正他忙着整理硬币收藏。"],
    ],
    writing: { zh: "写一句你正在进行的爱好。", hintEn: "These days, I'm ___.", },
  }),
  buildDay({
    day: 59, titleEn: "Outdoors & Nature", titleZh: "第 59 天 · 户外与自然",
    goalZh: "描述户外活动和自然风景。",
    vocabIds: ["w:cycling", "w:gardening", "w:trail", "w:mountain", "w:river", "w:forest"],
    grammarTopicId: "prepositions-basic",
    phonicsRuleIds: ["i-short", "bl"],
    pattern: {
      titleZh: "句型：Let's go ___ in the ___. / We walked along the river.",
      explainZh: "提议户外活动用 Let's go + 动名词。位置用介词：in the mountains（在山里），along the river（沿河）。",
      examples: [["Let's go cycling in the park.", "我们去公园骑车吧。"], ["We hiked up the mountain at dawn.", "我们黎明时爬山。"], ["The trail goes through a thick forest.", "小径穿过茂密的森林。"]],
      sentences: [["Gardening keeps my hands busy and my mind calm.", "园艺让我手上有活、心里平静。"], ["We set up our tent by the river.", "我们在河边搭起帐篷。"], ["Fresh air beats screen time any day.", "新鲜空气什么时候都胜过屏幕时间。"]],
    },
    reading: [
      ["Every fall, Class 2 takes a nature trip.", "每年秋天二班都组织自然之旅。"],
      ["This year they followed a new trail up the hill.", "今年他们沿着新小径上山。"],
      ["At the top, the whole valley turned gold below them.", "山顶上，整个山谷在他们脚下泛着金色。"],
    ],
    writing: { zh: "写一句你最想去的户外地点。", hintEn: "I want to go to ___, where I can ___.", },
  }),
  buildDay({
    day: 60, titleEn: "Milestone: 60 Days of Real Life", titleZh: "第 60 天 · 阶段大复习：生活交流六十天",
    goalZh: "综合复习第 31-59 天的生活交流主题，准备进入真实交流阶段。",
    vocabIds: ["w:milestone", "w:progress-n", "w:practice-n", "w:review", "w:improve-upon", "w:confidence"],
    grammarTopicId: "basic-clauses",
    phonicsRuleIds: ["ai", "er"],
    pattern: {
      titleZh: "句型：I can ___ now because I practiced every day.",
      explainZh: "复习日把购物、旅行、工作、社交、健康、兴趣串起来说。成就感句型：I can... now because...。",
      examples: [["I can order food in English now.", "我现在能用英语点餐了。"], ["I can talk about my weekend with confidence.", "我能自信地聊聊周末了。"], ["I can make an appointment by phone.", "我能打电话预约了。"]],
      sentences: [["Small daily practice brings real progress.", "每天的小练习带来真正的进步。"], ["Review old words before learning new ones.", "学新词前先复习旧词。"], ["Sixty days down — ninety more to go!", "六十天已完成——还剩九十天！"]],
    },
    reading: [
      ["Look back at Day 31: everything felt new then.", "回看第31天：那时一切都很陌生。"],
      ["Now supermarkets, airports and meetings feel familiar.", "现在超市、机场和会议都不再可怕。"],
      ["Celebrate this milestone — you earned it.", "庆祝这个里程碑吧——这是你应得的。"],
    ],
    writing: { zh: "写两句你这三十天学会的事，作为给自己的里程碑记录。", hintEn: "I can ___ now. I also learned ___.", },
  }),
  buildDay({
    day: 61, titleEn: "I Like / I Prefer", titleZh: "第 61 天 · 表达喜好",
    goalZh: "清楚表达喜欢、不喜欢和偏好。",
    vocabIds: ["w:prefer", "w:taste", "w:hate", "w:enjoy", "w:opinion", "w:genre"],
    grammarTopicId: "present-simple",
    phonicsRuleIds: ["ee", "oa"], phonicsPairId: "pair-eat-it",
    pattern: {
      titleZh: "句型：I prefer ___ to ___. / My favorite ___ is ___.",
      explainZh: "表达偏好用 prefer A to B（比起B更喜欢A）。最爱用 My favorite... is...。不喜欢可以说 I'm not a big fan of...",
      examples: [["I prefer tea to coffee.", "比起咖啡我更喜欢茶。"], ["My favorite season is autumn.", "我最喜欢的季节是秋天。"], ["I'm not a big fan of horror movies.", "我不太爱看恐怖片。"]],
      sentences: [["What kind of music do you enjoy?", "你喜欢什么音乐？"], ["In my opinion, this genre is underrated.", "在我看来这个类型被低估了。"], ["I hate waiting in long lines.", "我讨厌排长队。"]],
    },
    reading: [
      ["Everyone has opinions about food.", "每个人对食物都有自己的看法。"],
      ["Lily prefers spicy dishes; her brother likes sweet ones.", "莉莉偏爱辣菜，她哥哥喜欢甜口。"],
      ["At dinner, they take turns choosing the restaurant.", "晚饭时他们轮流选餐厅。"],
    ],
    writing: { zh: "写一句你的一个偏好并给出小理由。", hintEn: "I prefer ___ to ___ because ___.", },
  }),
  buildDay({
    day: 62, titleEn: "Agree to Disagree", titleZh: "第 62 天 · 同意与不同意",
    goalZh: "礼貌地表达同意与不同意见。",
    vocabIds: ["w:disagree", "w:debate", "w:absolutely", "w:actually", "w:point-of-view", "w:certain"],
    grammarTopicId: "negation",
    phonicsRuleIds: ["o-short", "y-cons"], phonicsPairId: "pair-cat-cut",
    pattern: {
      titleZh: "句型：I agree with you. / I see your point, but...",
      explainZh: "同意说 I agree / Absolutely! 不同意先让一步再说但书：I see your point, but...（我明白你的意思，但是…）。",
      examples: [["Absolutely — you're right.", "完全同意——你是对的。"], ["I see your point, but it costs too much.", "我懂你的意思，但太贵了。"], ["Actually, I disagree a little.", "其实我有点不同意。"]],
      sentences: [["Good debates need good listeners.", "好的辩论需要好的倾听者。"], ["From my point of view, winter is better.", "在我看来冬天更好。"], ["Are you certain about that number?", "你确定那个数字吗？"]],
    },
    reading: [
      ["The class debated: cats or dogs?", "班里辩论：猫还是狗？"],
      ["Half the room said cats; half shouted dogs.", "一半人说猫，一半人喊狗。"],
      ["Their teacher smiled: both sides argued well today.", "老师笑了：今天两边都辩得很棒。"],
    ],
    writing: { zh: "写一句礼貌表达不同意见的话。", hintEn: "I see your point, but ___.", },
  }),
  buildDay({
    day: 63, titleEn: "Comparing Choices", titleZh: "第 63 天 · 比较与选择",
    goalZh: "比较两个选项并做出决定。",
    vocabIds: ["w:compare", "w:contrast", "w:advantage", "w:disadvantage", "w:option", "w:instead"],
    grammarTopicId: "basic-clauses",
    phonicsRuleIds: ["ai", "ar"],
    pattern: {
      titleZh: "句型：___ is better than ___, because ___.",
      explainZh: "比较用 A is better than B（A比B好）。列优缺点：The advantage is... The disadvantage is...",
      examples: [["The train is better than the bus, because it's faster.", "火车比公交好，因为更快。"], ["The main advantage is the price.", "主要优点是价格。"], ["Let's walk instead of waiting.", "我们走路吧，别等了。"]],
      sentences: [["Compare both options before deciding.", "决定前把两个选项都比一比。"], ["In contrast, summer here is quiet.", "相比之下，这里的夏天很安静。"], ["Which option works for you?", "哪个方案适合你？"]],
    },
    reading: [
      ["Nina must choose: a cheap old bike or a pricey new one.", "妮娜要选：便宜的旧自行车还是贵的新车。"],
      ["She lists one advantage and one disadvantage for each.", "她给每辆车列了一条优点和一条缺点。"],
      ["In the end, she picks the old bike and saves her money.", "最后她选了旧车，省下了钱。"],
    ],
    writing: { zh: "写一句比较两个你想买/做的东西。", hintEn: "___ is better than ___, because ___.", },
  }),
  buildDay({
    day: 64, titleEn: "Reasons & Results", titleZh: "第 64 天 · 原因与结果",
    goalZh: "用 because / so / therefore 讲清因果。",
    vocabIds: ["w:therefore", "w:so-that", "w:reason", "w:result", "w:cause", "w:effect"],
    grammarTopicId: "basic-clauses",
    phonicsRuleIds: ["ee", "z"],
    pattern: {
      titleZh: "句型：___, so ___. / ___ because ___.",
      explainZh: "原因在前用 because；结果在前用 so。正式一点用 therefore（因此）。",
      examples: [["It rained, so we stayed home.", "下雨了，所以我们待在家。"], ["I stayed home because it rained.", "因为下雨我待在家。"], ["The road was icy; therefore, we drove slowly.", "路面结冰，因此我们开得慢。"]],
      sentences: [["Every effect has a cause.", "每个结果都有原因。"], ["What was the reason for the delay?", "延误的原因是什么？"], ["Practice daily and results will come.", "每天练习，成果自然会来。"]],
    },
    reading: [
      ["The bakery raised its prices last month.", "面包店上月涨价了。"],
      ["Because of that, fewer students came by.", "因此来的学生少了。"],
      ["So the owner started a student discount — problem solved.", "于是老板推出了学生折扣——问题解决了。"],
    ],
    writing: { zh: "写一句带因果关系的话。", hintEn: "___ because ___, so ___.", },
  }),
  buildDay({
    day: 65, titleEn: "Suggestions & Persuasion", titleZh: "第 65 天 · 建议与说服",
    goalZh: "提出建议、温和地劝说别人。",
    vocabIds: ["w:suggest", "w:recommendation", "w:advice", "w:persuade", "w:insist", "w:urge"],
    grammarTopicId: "questions",
    phonicsRuleIds: ["j", "st"],
    pattern: {
      titleZh: "句型：I suggest (that) you ___. / You should try ___.",
      explainZh: "提建议常用 I suggest... / You should...。更委婉：How about...? / Why don't you...?",
      examples: [["I suggest taking the earlier train.", "我建议坐早一点的火车。"], ["How about a short break?", "休息一下怎么样？"], ["Why don't you ask the teacher?", "为什么不问问老师呢？"]],
      sentences: [["My recommendation is to start small.", "我的建议是从小处开始。"], ["Can I give you some advice?", "我能给你一条建议吗？"], ["He persuaded me with one good reason.", "他用一个充分的理由说服了我。"]],
    },
    reading: [
      ["Maya wants a dog; her dad says no.", "玛雅想养狗，爸爸不同意。"],
      ["She suggests a one-month trial with clear rules.", "她提议试养一个月并定下明确规则。"],
      ["Her calm plan persuades him in the end.", "她冷静的方案最终说服了爸爸。"],
    ],
    writing: { zh: "写一句你给朋友的一条建议。", hintEn: "You should ___. It really helps.", },
  }),
  buildDay({
    day: 66, titleEn: "Opinion Words Review", titleZh: "第 66 天 · 观点表达复习",
    goalZh: "综合运用观点句型，进行一次小型讨论。",
    vocabIds: ["w:viewpoint", "w:attitude", "w:honestly", "w:personally", "w:however", "w:although"],
    grammarTopicId: "basic-clauses",
    phonicsRuleIds: ["th-vl", "ow-2"],
    pattern: {
      titleZh: "句型：Personally, I think ___. However, ___.",
      explainZh: "发表观点先说 Personally, I think...（就我个人而言），转折用 however / although 让讨论更成熟。",
      examples: [["Personally, I think morning runs are the best.", "我个人认为晨跑最好。"], ["However, rainy days are perfect for the gym.", "不过雨天正适合去健身房。"], ["Although it's hard, I enjoy the challenge.", "虽然难，但我享受挑战。"]],
      sentences: [["A positive attitude changes everything.", "积极的态度改变一切。"], ["Honestly, both viewpoints make sense.", "说实话两个观点都有道理。"], ["Listen first, then share your opinion.", "先倾听，再分享观点。"]],
    },
    reading: [
      ["The debate club met after school today.", "辩论社今天放学后活动。"],
      ["Topic: Is it better to plan or to improvise?", "话题：做计划好还是随机应变好？"],
      ["Everyone agreed on one thing — respect each viewpoint.", "大家在一件事上达成一致——尊重每个观点。"],
    ],
    writing: { zh: "写两句话表达你对一个话题的正反两面看法。", hintEn: "I think ___. However, ___.", },
  }),
  buildDay({
    day: 67, titleEn: "Last Weekend", titleZh: "第 67 天 · 上周末",
    goalZh: "用过去式讲述上个周末做了什么。",
    vocabIds: ["w:yesterday", "w:visit", "w:stay", "w:cook", "w:tired", "w:weekend"],
    grammarTopicId: "past-simple",
    phonicsRuleIds: ["oi", "z"],
    pattern: {
      titleZh: "句型：Last weekend, I ___ed ___. / It was ___.",
      explainZh: "讲过去的事动词要变过去式：visited / stayed / cooked。感受用 It was + 形容词。",
      examples: [["Last weekend, I visited my grandparents.", "上周末我看望了祖父母。"], ["We cooked dumplings together.", "我们一起包了饺子。"], ["It was tiring but wonderful.", "很累但很棒。"]],
      sentences: [["Yesterday I slept until ten.", "昨天我睡到十点。"], ["We stayed home and watched old movies.", "我们待在家看老电影。"], ["What did you do last weekend?", "你上周末做什么了？"]],
    },
    reading: [
      ["Ben's weekend had three parts: rain, ramen, and a good book.", "本的周末有三部分：雨、拉面和一本好书。"],
      ["He visited the new noodle shop on Saturday.", "周六他去了新开的面馆。"],
      ["On Sunday, he finally finished his library book.", "周日他终于读完了图书馆借的书。"],
    ],
    writing: { zh: "写两句你上个周末真实做的事。", hintEn: "Last weekend I ___ and ___.", },
  }),
  buildDay({
    day: 68, titleEn: "An Unforgettable Trip", titleZh: "第 68 天 · 难忘的旅行",
    goalZh: "按时间顺序讲一次难忘的旅行故事。",
    vocabIds: ["w:unforgettable", "w:memory", "w:camera", "w:photo", "w:journey", "w:adventure"],
    grammarTopicId: "past-simple",
    phonicsRuleIds: ["igh", "r"],
    pattern: {
      titleZh: "句型：First we ___, then we ___, in the end we ___.",
      explainZh: "讲故事用顺序词 First / Then / In the end 串起来，听的人最清楚。",
      examples: [["First, we missed the train!", "首先我们错过了火车！"], ["Then we found a tiny family hotel.", "后来我们找到一家家庭小旅馆。"], ["In the end, it became the best part of the journey.", "最后这成了旅途中最棒的部分。"]],
      sentences: [["My camera died on day two.", "第二天我的相机就没电了。"], ["We took photos with our hearts instead.", "我们改用心去记住。"], ["What an unforgettable adventure!", "多么难忘的冒险！"]],
    },
    reading: [
      ["Grandma tells one trip story every winter.", "奶奶每年冬天都讲一个旅行故事。"],
      ["Her train once stopped in the snow for six hours.", "她的火车曾在雪中停了六小时。"],
      ["Strangers shared food and stories until midnight.", "陌生人们分享食物和故事直到午夜。"],
    ],
    writing: { zh: "写两句你的一次小冒险（顺序词开头）。", hintEn: "First, ___. Then, ___.", },
  }),
  buildDay({
    day: 69, titleEn: "Childhood Memories", titleZh: "第 69 天 · 童年回忆",
    goalZh: "谈论童年：会用 used to 的意思和过去式。",
    vocabIds: ["w:childhood", "w:candy", "w:cartoon", "w:toy", "w:hide", "w:seek"],
    grammarTopicId: "past-simple",
    phonicsRuleIds: ["i-short", "ch"], phonicsPairId: "pair-cat-cut",
    pattern: {
      titleZh: "句型：When I was a kid, I ___ed every summer.",
      explainZh: "谈童年用 When I was a kid / child 开头 + 过去式。表达“过去常常”可用 used to。",
      examples: [["When I was a kid, I watched cartoons after school.", "我小时候放学后看动画片。"], ["We played hide-and-seek every evening.", "我们每天晚上玩捉迷藏。"], ["I saved candy money for comic books.", "我把买糖的钱攒下来买漫画。"]],
      sentences: [["My favorite toy was a red truck.", "我最爱的玩具是红色卡车。"], ["Summers felt endless back then.", "那时候的夏天好像没有尽头。"], ["Childhood friends know the real you.", "童年的朋友认识真正的你。"]],
    },
    reading: [
      ["In his childhood, Leo lived near a small river.", "童年时利奥住在一条小河边。"],
      ["Every summer, the kids caught tadpoles in glass jars.", "每年夏天孩子们用玻璃罐捉蝌蚪。"],
      ["Last month, he visited — the river is still there, quieter now.", "上个月他回去看了看——河还在，只是安静了许多。"],
    ],
    writing: { zh: "写两句你的一个童年回忆。", hintEn: "When I was a kid, I ___. We often ___.", },
  }),
  buildDay({
    day: 70, titleEn: "Telling Stories Well", titleZh: "第 70 天 · 把故事讲好",
    goalZh: "给故事加细节和悬念，让人想听下去。",
    vocabIds: ["w:plot", "w:scene", "w:background", "w:highlight", "w:detail", "w:vivid"],
    grammarTopicId: "past-simple",
    phonicsRuleIds: ["sh", "ee"],
    pattern: {
      titleZh: "句型：The best part was when ___. / Guess what happened next!",
      explainZh: "讲故事技巧：先设悬念 Guess what! 高潮用 The best part was when...。加一个 vivid detail 让故事活起来。",
      examples: [["Guess what happened at the airport!", "猜猜机场发生了什么！"], ["The best part was when the lights went out.", "最精彩的是灯突然全灭了。"], ["To set the scene, it was raining hard.", "交代一下背景：当时雨下得很大。"]],
      sentences: [["A good plot has a twist.", "好情节都有反转。"], ["He told the story with vivid details.", "他讲故事的细节非常生动。"], ["Don't skip the funny background parts.", "别跳过有趣的背景部分。"]],
    },
    reading: [
      ["Story night at school: two minutes each.", "学校故事之夜：每人两分钟。"],
      ["Amy started with a question, not a greeting.", "艾米以一个问题开场，而不是打招呼。"],
      ["By her last word, the whole room leaned in closer.", "讲到最后一句话时，全场都凑近了。"],
    ],
    writing: { zh: "写一句带悬念的故事开头。", hintEn: "Guess what! Last week, ___...", },
  }),
];
