/**
 * Day 31-50 authored curriculum - 生活交流强化 (shopping / travel / work / social).
 * Vocab references the 3000-word lexical model; grammar references engine topics;
 * every day carries lesson / vocab / grammar / phonics / listening /
 * speaking / reading / writing / review / assessment hooks.
 */
import { buildDay } from "@/content/days/factory";

export const DAYS_31_50 = [
  buildDay({
    day: 31, titleEn: "At the Supermarket", titleZh: "第 31 天 · 在超市",
    goalZh: "在超市找到商品并询问价格，会用 How many / How much。",
    vocabIds: ["w:aisle", "w:grocery", "w:carton", "w:coupon", "w:checkout", "w:barcode"],
    grammarTopicId: "countable-uncountable",
    phonicsRuleIds: ["ai", "ee"], phonicsPairId: "pair-eat-it",
    pattern: {
      titleZh: "句型：Excuse me, where is the ___? / How much are these ___?",
      explainZh: "问位置用 Where is + 单数名词，Where are + 复数。问价格记住固定说法 How much。开口先说 Excuse me 更礼貌。",
      examples: [["Excuse me, where is the cereal?", "请问麦片在哪里？"], ["Where are the eggs?", "鸡蛋在哪里？"], ["How much are these apples?", "这些苹果怎么卖？"]],
      sentences: [["It's in aisle five.", "在第五过道。"], ["Do you have any coupons?", "你们有优惠券吗？"], ["I'll pay at the self-checkout.", "我在自助机结账。"]],
    },
    reading: [
      ["Amy does grocery shopping every Saturday.", "艾米每周六买食品杂货。"],
      ["She grabs a carton of milk and scans the barcode at checkout.", "她拿一盒牛奶，在收银台扫条形码。"],
      ["With a coupon, she saves two dollars.", "用了优惠券，她省了两美元。"],
    ],
    writing: { zh: "写一句你上周在超市买了什么、花了多少钱。", hintEn: "I bought ___ and paid ___ dollars." },
  }),
  buildDay({
    day: 32, titleEn: "Buying Clothes", titleZh: "第 32 天 · 买衣服",
    goalZh: "说出尺码、请求试穿，用 Can I...? 提出礼貌请求。",
    vocabIds: ["w:fitting-room", "w:price-tag", "w:rack", "w:browse", "w:affordable", "w:size"],
    grammarTopicId: "questions",
    phonicsRuleIds: ["igh", "e-short"], phonicsPairId: "pair-bad-bed",
    pattern: {
      titleZh: "句型：Can I try this on? / Do you have a bigger size?",
      explainZh: "Can I...? 是最常用的礼貌请求。试穿说 try this on；要更大码说 a bigger size。店员常回答 Sure 或 Of course。",
      examples: [["Can I try this on?", "我能试试这件吗？"], ["Do you have a bigger size?", "有大一号的吗？"], ["Where is the fitting-room?", "试衣间在哪里？"]],
      sentences: [["This price-tag says forty dollars.", "价签上写着四十美元。"], ["I'm just browsing, thanks.", "我只是随便看看，谢谢。"], ["That outfit looks great on you.", "那套衣服你穿真好看。"]],
    },
    reading: [
      ["Lin browses the sale rack for twenty minutes.", "李在打折架前逛了二十分钟。"],
      ["The shirt fits well and the price is affordable.", "衬衫很合身，价格也实惠。"],
      ["She checks the fitting-room mirror one more time.", "她在试衣间的镜子前又照了一次。"],
    ],
    writing: { zh: "写一句你想买的衣服和它的颜色、尺码。", hintEn: "I want a ___ ___ in size ___." },
  }),
  buildDay({
    day: 33, titleEn: "Online Shopping", titleZh: "第 33 天 · 网上购物",
    goalZh: "谈论网购流程：下单、运费、包裹和快递。",
    vocabIds: ["w:order", "w:shipping", "w:parcel", "w:courier", "w:purchase", "w:review"],
    grammarTopicId: "present-simple",
    phonicsRuleIds: ["or", "oa"],
    pattern: {
      titleZh: "句型：I ordered ___ online. / The shipping is free.",
      explainZh: "网购常用过去式 I ordered 说明已下单；询问状态用 Where is my parcel? 免运费说 free shipping。",
      examples: [["I ordered shoes online last night.", "我昨晚在网上下单买了鞋。"], ["The shipping is free over fifty dollars.", "满五十美元免运费。"], ["My parcel arrived this morning.", "我的包裹今天早上到了。"]],
      sentences: [["The courier left it at the door.", "快递员把它放在门口了。"], ["I wrote a five-star review.", "我写了一条五星好评。"], ["Online shopping saves time.", "网上购物省时间。"]],
    },
    reading: [
      ["David orders almost everything online now.", "大卫现在几乎什么都网购。"],
      ["Last week he bought a backpack with free shipping.", "上周他买了个背包，免运费。"],
      ["He reads reviews before every purchase.", "每次下单前他都看评价。"],
    ],
    writing: { zh: "写一句你最近网购的东西和感受。", hintEn: "I ordered ___ online. It was ___." },
  }),
  buildDay({
    day: 34, titleEn: "Returns & Service", titleZh: "第 34 天 · 退换与售后",
    goalZh: "礼貌退货：说明问题、提出退换要求。",
    vocabIds: ["w:return", "w:warranty", "w:receipt", "w:refund", "w:exchange", "w:membership"],
    grammarTopicId: "negation",
    phonicsRuleIds: ["u-short", "ng"],
    pattern: {
      titleZh: "句型：I'd like to return this. It doesn't work.",
      explainZh: "退货开头句 I'd like to return this。说明问题可用 doesn't work / doesn't fit。别忘了带上收据，没有收据通常不能退款。",
      examples: [["I'd like to return this jacket.", "我想退这件夹克。"], ["It doesn't work at all.", "它完全不能用。"], ["Do you have the receipt?", "你有收据吗？"]],
      sentences: [["It's still under warranty.", "它还在保修期内。"], ["Can I exchange it for a new one?", "我能换一个新的吗？"], ["No receipt, no refund.", "没有收据就不能退款。"]],
    },
    reading: [
      ["Kate bought a blender last week.", "凯特上周买了一台搅拌机。"],
      ["It stopped working, so she brought the receipt back.", "它坏了，所以她带着收据回到店里。"],
      ["The store exchanged it without any problem.", "商店毫不犹豫地给她换了新的。"],
    ],
    writing: { zh: "写一句你退换过东西的经历（或编一个）。", hintEn: "I returned ___ because it didn't ___." },
  }),
  buildDay({
    day: 35, titleEn: "Money-Smart Shopping", titleZh: "第 35 天 · 省钱高手",
    goalZh: "谈论预算和优惠，用 I'll take it 完成购买。",
    vocabIds: ["w:budget", "w:expense", "w:savings", "w:bargain", "w:clearance", "w:deal"],
    grammarTopicId: "future-simple",
    phonicsRuleIds: ["ow-2", "oi"],
    pattern: {
      titleZh: "句型：I'll take it! / It's a great deal.",
      explainZh: "决定购买说 I'll take it（我要了）。will 缩写 'll 表示当场决定。夸便宜说 What a bargain / a great deal。",
      examples: [["I'll take it!", "我要了！"], ["Half price? What a deal!", "半价？太划算了！"], ["Everything on the clearance rack is cheap.", "清货架上的东西都便宜。"]],
      sentences: [["We keep savings for big purchases.", "我们存钱准备大额消费。"], ["Set a budget before shopping.", "购物前先定预算。"], ["Small expenses add up fast.", "小开销加起来很快。"]],
    },
    reading: [
      ["Sam loves hunting for bargains.", "山姆喜欢淘便宜货。"],
      ["He sets a monthly budget and tracks every expense.", "他设定每月预算并记录每笔开销。"],
      ["Yesterday he found winter boots at half price.", "昨天他以半价买到了冬靴。"],
    ],
    writing: { zh: "写一句你的省钱小技巧。", hintEn: "I save money by ___." },
  }),
  buildDay({
    day: 36, titleEn: "Planning a Trip", titleZh: "第 36 天 · 计划旅行",
    goalZh: "用 will / be going to 谈论旅行计划。",
    vocabIds: ["w:itinerary", "w:destination", "w:abroad", "w:guidebook", "w:adventure", "w:passport"],
    grammarTopicId: "future-simple",
    phonicsRuleIds: ["ai", "ar"],
    pattern: {
      titleZh: "句型：I'm going to visit ___ next month.",
      explainZh: "谈计划用 be going to + 动词原形。问对方计划用 What are you going to do? 行程表说 itinerary。",
      examples: [["I'm going to visit Japan next month.", "我下个月要去日本。"], ["We're going to travel abroad this summer.", "我们今年夏天要出国旅行。"], ["What's your first destination?", "你的第一站是哪里？"]],
      sentences: [["The itinerary includes three cities.", "行程包括三个城市。"], ["Don't forget your passport.", "别忘了护照。"], ["A guidebook helps a lot.", "旅游指南很有用。"]],
    },
    reading: [
      ["Nina is planning her first trip abroad.", "妮娜在计划第一次出国旅行。"],
      ["She made an itinerary and booked the flights.", "她做好了行程并订好了机票。"],
      ["It will be a big adventure.", "这将是一场大冒险。"],
    ],
    writing: { zh: "写一句你下一个想去的地方和原因。", hintEn: "I'm going to visit ___ because ___." },
  }),
  buildDay({
    day: 37, titleEn: "At the Airport", titleZh: "第 37 天 · 在机场",
    goalZh: "掌握机场高频词，看懂登机指示。",
    vocabIds: ["w:boarding-pass", "w:check-in", "w:security", "w:baggage", "w:terminal", "w:customs"],
    grammarTopicId: "prepositions-basic",
    phonicsRuleIds: ["er", "sh"], phonicsPairId: "pair-sit-seat",
    pattern: {
      titleZh: "句型：Where is Gate B12? / I'm at the check-in counter.",
      explainZh: "机场问路用 Where is...? 说明位置用 at / in：at the gate（在登机口），in terminal two（在二号航站楼）。",
      examples: [["Where is Gate B12?", "B12 登机口在哪里？"], ["I'm in terminal two.", "我在二号航站楼。"], ["Please take out your boarding-pass.", "请出示您的登机牌。"]],
      sentences: [["Security takes about fifteen minutes.", "安检大约要十五分钟。"], ["My baggage didn't come out.", "我的行李没出来。"], ["We go through customs after landing.", "落地后我们过海关。"]],
    },
    reading: [
      ["Leo arrived at the airport two hours early.", "利奥提前两小时到了机场。"],
      ["He printed his boarding-pass and checked one bag.", "他打印了登机牌并托运了一件行李。"],
      ["At security, he took out his laptop and waited.", "在安检口，他取出笔记本电脑等待。"],
    ],
    writing: { zh: "写一句描述你在机场常做的一件事。", hintEn: "At the airport, I always ___." },
  }),
  buildDay({
    day: 38, titleEn: "Checking In at the Hotel", titleZh: "第 38 天 · 入住酒店",
    goalZh: "办理入住、提出房间需求。",
    vocabIds: ["w:reservation", "w:receptionist", "w:elevator", "w:luggage", "w:towel", "w:shower"],
    grammarTopicId: "questions",
    phonicsRuleIds: ["oa", "v"],
    pattern: {
      titleZh: "句型：I have a reservation under ___. / Could I get extra towels?",
      explainZh: "报预订说 I have a reservation under + 名字。提请求用 Could I...? 比 Can I 更礼貌。",
      examples: [["I have a reservation under Chen.", "我有一个用陈姓订的房间。"], ["Could I get a room with a shower?", "能给我一间带淋浴的房吗？"], ["Where is the elevator?", "电梯在哪里？"]],
      sentences: [["The receptionist handed me two key cards.", "前台递给我两张房卡。"], ["Someone will bring your luggage up.", "有人会把行李送上来。"], ["Fresh towels are in the closet.", "干净毛巾在衣柜里。"]],
    },
    reading: [
      ["Mr. Park arrives at the hotel tired.", "朴先生疲惫地到达酒店。"],
      ["The receptionist finds his reservation quickly.", "前台很快找到了他的预订。"],
      ["His room is on the tenth floor, next to the elevator.", "他的房间在十层，挨着电梯。"],
    ],
    writing: { zh: "写一句你入住酒店时最重要的需求。", hintEn: "I need a room with ___." },
  }),
  buildDay({
    day: 39, titleEn: "Getting Around the City", titleZh: "第 39 天 · 城市交通与问路",
    goalZh: "问路、指路，描述交通状况。",
    vocabIds: ["w:metro", "w:crosswalk", "w:intersection", "w:gps", "w:traffic-jam", "w:rush-hour"],
    grammarTopicId: "questions",
    phonicsRuleIds: ["tr", "dr"],
    pattern: {
      titleZh: "句型：How do I get to ___? / Turn left at the intersection.",
      explainZh: "问路万能句 How do I get to + 地点？指路用 Turn left / right at...，直走是 Go straight。",
      examples: [["How do I get to the museum?", "去博物馆怎么走？"], ["Turn left at the next intersection.", "在下一个十字路口左转。"], ["Take the metro — it's faster.", "坐地铁——更快。"]],
      sentences: [["Use the crosswalk, please.", "请走人行横道。"], ["There's a traffic-jam on Main Street.", "主路上堵车了。"], ["Avoid rush-hour if you can.", "尽量避开高峰期。"]],
    },
    reading: [
      ["Visitors often ask Mia for directions.", "游客经常向米娅问路。"],
      ["She tells them to take the metro to Central Station.", "她告诉他们坐地铁到中央车站。"],
      ["With GPS on their phones, nobody gets lost.", "手机上有GPS，没人会迷路。"],
    ],
    writing: { zh: "写一句从家到附近一个地点的路线。", hintEn: "Go straight and turn ___ at ___." },
  }),
  buildDay({
    day: 40, titleEn: "Travel Stories", titleZh: "第 40 天 · 旅行见闻",
    goalZh: "用过去式分享一次旅行的亮点。",
    vocabIds: ["w:souvenir", "w:sightseeing", "w:landmark", "w:memorable", "w:foreigner", "w:overseas"],
    grammarTopicId: "past-simple",
    phonicsRuleIds: ["ar", "er"],
    pattern: {
      titleZh: "句型：We went sightseeing and took lots of photos.",
      explainZh: "讲旅行用过去式：went / saw / bought。说亮点用 The best part was...。",
      examples: [["We went sightseeing all day.", "我们观光了一整天。"], ["I bought a small souvenir.", "我买了一个小纪念品。"], ["The landmark was amazing.", "那个地标太震撼了。"]],
      sentences: [["The best part was the night market.", "最棒的是夜市。"], ["A local helped us find the way.", "一位当地人帮我们指了路。"], ["It was a memorable trip.", "那是一次难忘的旅行。"]],
    },
    reading: [
      ["Last spring, Grace visited her cousin overseas.", "去年春天，格蕾丝去国外看望表姐。"],
      ["They visited every famous landmark in the city.", "她们逛遍了城里著名的地标。"],
      ["Grace brought back souvenirs for the whole family.", "格蕾丝给全家人带了纪念品。"],
    ],
    writing: { zh: "写一句你（或想象中）旅行中最难忘的一幕。", hintEn: "The best part of my trip was ___." },
  }),
  buildDay({
    day: 41, titleEn: "Job Hunting", titleZh: "第 41 天 · 求职",
    goalZh: "谈论找工作：申请、简历和面试。",
    vocabIds: ["w:apply", "w:resume", "w:applicant", "w:interview", "w:hire", "w:qualification"],
    grammarTopicId: "present-simple",
    phonicsRuleIds: ["y-cons", "i-short"], phonicsPairId: "pair-eat-it",
    pattern: {
      titleZh: "句型：I'm applying for the ___ position.",
      explainZh: "申请职位用 apply for + 职位。面试常见问题 Tell me about yourself 要提前准备。",
      examples: [["I'm applying for the sales position.", "我在申请销售职位。"], ["She sent her resume this morning.", "她今天早上发了简历。"], ["They hired two new applicants.", "他们录用了两名新申请人。"]],
      sentences: [["Do you have the right qualifications?", "你有相应的资格吗？"], ["The interview is on Thursday.", "面试在周四。"], ["Good luck with your job hunt!", "祝你求职顺利！"]],
    },
    reading: [
      ["Fifty applicants want one job.", "五十名应聘者争夺一个岗位。"],
      ["Only five get interviews next week.", "只有五人能进入下周的面试。"],
      ["Ben updates his resume and practices his answers.", "本更新了简历并练习回答。"],
    ],
    writing: { zh: "写一句你理想工作的名称和一个理由。", hintEn: "I want to work as a ___ because ___." },
  }),
  buildDay({
    day: 42, titleEn: "First Day at Work", titleZh: "第 42 天 · 入职第一天",
    goalZh: "介绍新环境，询问工作安排。",
    vocabIds: ["w:coworker", "w:schedule", "w:training", "w:assignment", "w:cafeteria", "w:intern"],
    grammarTopicId: "be-verb",
    phonicsRuleIds: ["oo-l", "oo-s"], phonicsPairId: "pair-full-food",
    pattern: {
      titleZh: "句型：This is my ___. / Where is the ___?",
      explainZh: "介绍同事用 This is + 名字。问设施用 Where is the cafeteria / printer?",
      examples: [["This is my coworker, Amy.", "这是我同事艾米。"], ["Where is the cafeteria?", "食堂在哪里？"], ["My schedule starts at nine.", "我的日程九点开始。"]],
      sentences: [["Training takes two weeks.", "培训要两周。"], ["The first assignment looks easy.", "第一个任务看起来不难。"], ["The intern sits by the window.", "实习生坐在窗边。"]],
    },
    reading: [
      ["It's Mei's first day as an intern.", "今天是梅做实习生的第一天。"],
      ["Her manager shows her the desk and the schedule.", "经理带她看了工位和日程表。"],
      ["At noon, her coworkers invite her to the cafeteria.", "中午，同事们邀她一起去食堂。"],
    ],
    writing: { zh: "写一句你第一天上班（学）最想知道的事。", hintEn: "On my first day, I want to know ___." },
  }),
  buildDay({
    day: 43, titleEn: "Meetings & Emails", titleZh: "第 43 天 · 会议与邮件",
    goalZh: "听懂会议安排，写简短工作消息。",
    vocabIds: ["w:conference", "w:agenda", "w:presentation", "w:memo", "w:attachment", "w:deadline"],
    grammarTopicId: "basic-clauses",
    phonicsRuleIds: ["ee", "e-short"],
    pattern: {
      titleZh: "句型：The meeting starts at ten. / Please find the file attached.",
      explainZh: "说时间用 starts at + 点钟。邮件结尾常用 Please find... attached（请查收附件）。注意截止日期 deadline。",
      examples: [["The meeting starts at ten sharp.", "会议十点整开始。"], ["The first item on the agenda is sales.", "议程第一项是销售。"], ["Please find the report attached.", "请查收附件中的报告。"]],
      sentences: [["Her presentation was short and clear.", "她的演讲简短清晰。"], ["I sent a memo about the new policy.", "我发了一份关于新政策的备忘录。"], ["The deadline is this Friday.", "截止日期是这周五。"]],
    },
    reading: [
      ["Every Monday, the team holds a short conference.", "每周一团队开个短会。"],
      ["The manager shares the agenda by email first.", "经理会先用邮件分享议程。"],
      ["Everyone brings notes and one question.", "每个人带着笔记和一个问题参加。"],
    ],
    writing: { zh: "写一句通知同事开会的时间地点。", hintEn: "The meeting is at ___ in ___." },
  }),
  buildDay({
    day: 44, titleEn: "Calls & Messages", titleZh: "第 44 天 · 电话与信息",
    goalZh: "接打电话、留言和发信息的常用表达。",
    vocabIds: ["w:text", "w:voicemail", "w:hold-on", "w:call-back", "w:message", "w:notification"],
    grammarTopicId: "questions",
    phonicsRuleIds: ["l", "o-short"],
    pattern: {
      titleZh: "句型：Could you hold on? / Can I take a message?",
      explainZh: "请对方稍等说 Could you hold on? 对方不在时说 Can I take a message?（需要留言吗）。回电用 call back。",
      examples: [["Could you hold on a second?", "您能稍等一下吗？"], ["Can I take a message?", "需要留言吗？"], ["I'll call back after lunch.", "午饭后我回电。"]],
      sentences: [["He left a voicemail last night.", "他昨晚留了语音留言。"], ["Just text me the address.", "把地址发短信给我就行。"], ["My phone buzzes all day with notifications.", "我的手机整天响个不停。"]],
    },
    reading: [
      ["Rosa calls the clinic to change an appointment.", "罗莎打电话到诊所改预约。"],
      ["The line is busy, so she leaves a voicemail.", "电话占线，于是她留了语音留言。"],
      ["Ten minutes later, the clinic texts her a new time.", "十分钟后，诊所发来新时间的短信。"],
    ],
    writing: { zh: "写一句你给别人留言或回电时会说的话。", hintEn: "Sorry I missed your call. I'll ___." },
  }),
  buildDay({
    day: 45, titleEn: "Career Growth", titleZh: "第 45 天 · 职业成长",
    goalZh: "谈论升职加薪与职业目标。",
    vocabIds: ["w:promotion", "w:raise", "w:performance", "w:expertise", "w:training", "w:retire"],
    grammarTopicId: "future-simple",
    phonicsRuleIds: ["er", "oi"],
    pattern: {
      titleZh: "句型：If I work hard, I will get a promotion.",
      explainZh: "谈职业目标用 will / want to。升职 promotion，加薪 a raise。谈论长期打算用 I plan to...。",
      examples: [["She got a promotion last month.", "她上个月升职了。"], ["He asked for a raise politely.", "他有礼貌地请求加薪。"], ["I plan to build my expertise in design.", "我计划在设计方面积累专长。"]],
      sentences: [["Good performance gets noticed.", "好的表现会被看到。"], ["My dad will retire at sixty.", "我爸六十岁退休。"], ["Training never really stops.", "学习培训永远不会停。"]],
    },
    reading: [
      ["Aiden has worked at the company for three years.", "艾登在这家公司工作三年了。"],
      ["His performance reviews are always strong.", "他的绩效评估一直很好。"],
      ["Next year, he hopes to lead his own team.", "明年他希望能带自己的团队。"],
    ],
    writing: { zh: "写一句你未来五年的一个职业小目标。", hintEn: "In five years, I will ___.", },
  }),
  buildDay({
    day: 46, titleEn: "Making Friends", titleZh: "第 46 天 · 结识朋友",
    goalZh: "开启闲聊、介绍自己，迈出交友第一步。",
    vocabIds: ["w:acquaintance", "w:roommate", "w:small-talk", "w:outgoing", "w:personality", "w:get-together"],
    grammarTopicId: "present-simple",
    phonicsRuleIds: ["h", "r"],
    pattern: {
      titleZh: "句型：Nice weather, isn't it? / What do you do for fun?",
      explainZh: "和陌生人聊天从小话题开始：天气、周末。破冰问题用 What do you...? 开头最自然。",
      examples: [["Nice weather today, isn't it?", "今天天气不错，是吧？"], ["What do you do for fun?", "你平时喜欢做什么？"], ["How do you know the host?", "你怎么认识主人的？"]],
      sentences: [["My roommate is super outgoing.", "我室友特别外向。"], ["We're having a small get-together on Friday.", "我们周五有个小聚会。"], ["She has a warm personality.", "她性格很温暖。"]],
    },
    reading: [
      ["Moving to a new city is lonely at first.", "刚搬到一个新城市会有些孤独。"],
      ["Jack starts with small-talk at the coffee shop downstairs.", "杰克从楼下咖啡店的寒暄开始。"],
      ["Soon, acquaintances turn into real friends.", "很快，熟人变成了真正的朋友。"],
    ],
    writing: { zh: "写一句你会用来开始对话的破冰问题。", hintEn: "Hi! Do you like ___?", },
  }),
  buildDay({
    day: 47, titleEn: "Invitations & Visits", titleZh: "第 47 天 · 邀请与做客",
    goalZh: "发出/接受/婉拒邀请，做客有礼貌。",
    vocabIds: ["w:potluck", "w:housewarming", "w:gathering", "w:get-together", "w:grateful", "w:farewell"],
    grammarTopicId: "questions",
    phonicsRuleIds: ["gr", "oo-l"],
    pattern: {
      titleZh: "句型：Would you like to come over? / I'd love to, but...",
      explainZh: "邀请用 Would you like to...? 接受说 I'd love to! 婉拒先谢后拒：I'd love to, but I'm busy.",
      examples: [["Would you like to come over for dinner?", "你愿意来我家吃饭吗？"], ["I'd love to!", "我很乐意！"], ["I'd love to, but I have plans that night.", "我想去，但那晚有事。"]],
      sentences: [["It's a potluck — bring any dish you like.", "是百乐餐——带什么菜都行。"], ["Thank you so much; I'm really grateful.", "太感谢了，我真的很感激。"], ["We said our farewells at the door.", "我们在门口道了别。"]],
    },
    reading: [
      ["The Lees are hosting a housewarming this Saturday.", "李家这周六办乔迁聚会。"],
      ["Everyone brings one dish to share.", "每人带一道菜分享。"],
      ["Guests leave with full stomachs and big smiles.", "客人们吃得饱饱、笑呵呵地离开。"],
    ],
    writing: { zh: "写一句邀请朋友周末来家里的话。", hintEn: "Would you like to ___ this weekend?", },
  }),
  buildDay({
    day: 48, titleEn: "Love & Relationships", titleZh: "第 48 天 · 恋爱与关系",
    goalZh: "简单谈论感情状态，尊重他人隐私。",
    vocabIds: ["w:dating", "w:boyfriend", "w:girlfriend", "w:engaged", "w:married", "w:relationship"],
    grammarTopicId: "present-simple",
    phonicsRuleIds: ["ai", "ng"],
    pattern: {
      titleZh: "句型：Are you seeing anyone? / We got engaged last month.",
      explainZh: "问别人是否单身要谨慎：Are you seeing anyone? 比较委婉。订婚 got engaged，结婚 got married。",
      examples: [["They started dating in spring.", "他们春天开始交往。"], ["My sister just got married.", "我姐姐刚结婚。"], ["We got engaged on the beach!", "我们在海边订婚了！"]],
      sentences: [["Her boyfriend studies in Canada.", "她男朋友在加拿大读书。"], ["A good relationship takes time.", "好的关系需要时间。"], ["Don't ask about breakups unless they share.", "除非对方主动说，否则别问分手的事。"]],
    },
    reading: [
      ["At the wedding, everyone asks the couple questions.", "婚礼上大家围着新人提问。"],
      ["How did you two meet? they ask.", "大家问：“你们怎么认识的？”"],
      ["The couple laughs and tells the same story again.", "新人笑着把老故事又讲了一遍。"],
    ],
    writing: { zh: "写一句你认为好关系最重要的东西。", hintEn: "A good relationship needs ___.", },
  }),
  buildDay({
    day: 49, titleEn: "Sorry & Making Up", titleZh: "第 49 天 · 道歉与和好",
    goalZh: "真诚道歉、回应道歉，修复小摩擦。",
    vocabIds: ["w:quarrel", "w:apology", "w:forgive", "w:upset", "w:shame", "w:hug"],
    grammarTopicId: "negation",
    phonicsRuleIds: ["a-short", "o-short"], phonicsPairId: "pair-bad-bed",
    pattern: {
      titleZh: "句型：I'm sorry. It won't happen again. / It's OK. Don't worry.",
      explainZh: "道歉三步：说 sorry + 说明会改正。回应道歉说 It's OK / No worries。",
      examples: [["I'm really sorry I'm late.", "我迟到了，真的抱歉。"], ["It won't happen again, I promise.", "我保证不会再发生。"], ["It's OK — don't worry about it.", "没关系——别放在心上。"]],
      sentences: [["They had a small quarrel about money.", "他们为钱吵了一小架。"], ["A sincere apology fixes a lot.", "真诚的道歉能解决很多问题。"], ["She gave him a hug and smiled again.", "她抱了他一下，又笑了。"]],
    },
    reading: [
      ["Ben forgot Mia's birthday card this year.", "今年本忘了米娅的生日卡片。"],
      ["Mia was upset and quiet at dinner.", "晚饭时米娅很难过，话很少。"],
      ["Ben said sorry with flowers and a long hug.", "本带着花和一个长长的拥抱说了对不起。"],
    ],
    writing: { zh: "写一句你道歉时最想说的话。", hintEn: "I'm sorry for ___. Next time I will ___.", },
  }),
  buildDay({
    day: 50, titleEn: "Celebrations", titleZh: "第 50 天 · 庆祝时刻",
    goalZh: "送上祝福、参加庆祝活动。",
    vocabIds: ["w:celebrate", "w:reunion", "w:gift-card", "w:balloon", "w:fireworks", "w:congratulate"],
    grammarTopicId: "future-simple",
    phonicsRuleIds: ["igh", "ow-2"],
    pattern: {
      titleZh: "句型：Congratulations on ___! / Let's celebrate with ___!",
      explainZh: "祝贺句型 Congratulations on + 名词。提议庆祝用 Let's celebrate with...。",
      examples: [["Congratulations on your new job!", "恭喜你找到新工作！"], ["Let's celebrate with a big dinner!", "我们吃顿大餐庆祝吧！"], ["Happy graduation! Here's a small gift.", "毕业快乐！这是个小礼物。"]],
      sentences: [["The family reunion is every winter.", "家庭团聚每年冬天一次。"], ["Fireworks lit up the whole sky.", "烟花照亮了整个夜空。"], ["I gave her a gift-card instead of flowers.", "我没送花，送了张礼品卡。"]],
    },
    reading: [
      ["Tonight the city celebrates its 200th birthday.", "今晚全城庆祝建城两百周年。"],
      ["Balloons cover the park; music fills the streets.", "公园里满是气球，街上音乐飘扬。"],
      ["Strangers congratulate each other like old friends.", "陌生人像老朋友一样互道祝贺。"],
    ],
    writing: { zh: "写一句你最近一次（或想）庆祝的事。", hintEn: "Let's celebrate ___ with ___.", },
  }),
];
