/**
 * Day 71-90 authored curriculum - 新闻基础 / 职场交流 / 日常讨论 / 里程碑复习.
 * Same factory pattern; vocab references the lexical model.
 */
import { buildDay } from "@/content/days/factory";

export const DAYS_71_90 = [
  buildDay({
    day: 71, titleEn: "Achievements & Lessons", titleZh: "第 71 天 · 成就与教训",
    goalZh: "谈论做成的事和从失败学到的教训。",
    vocabIds: ["w:achievement", "w:milestone", "w:lesson", "w:proud", "w:succeed", "w:fault"],
    grammarTopicId: "past-simple",
    phonicsRuleIds: ["ee", "ch"],
    pattern: {
      titleZh: "句型：I finally ___. / I learned that ___.",
      explainZh: "谈成就用 I finally + 过去式（终于做到）。总结教训用 I learned that + 从句。功劳归自己时说 I'm proud of it。",
      examples: [["I finally passed the driving test!", "我终于通过驾照考试了！"], ["I learned that practice beats talent.", "我学到练习胜过天赋。"], ["I'm proud of my small wins.", "我为小成就感到自豪。"]],
      sentences: [["Finishing the race was a real milestone for me.", "跑完比赛对我是真正的里程碑。"], ["It wasn't your fault — stop blaming yourself.", "不是你的错——别再自责了。"], ["Every failure teaches a lesson worth keeping.", "每次失败都留下值得记住的教训。"]],
    },
    reading: [
      ["Riya's first business sold exactly one cupcake — to her dad.", "莉雅的第一笔生意只卖出一块蛋糕——买主是她爸爸。"],
      ["She laughed, then wrote down three lessons from it.", "她大笑一场，然后写下了三条教训。"],
      ["Two years later, her little bakery opened on Main Street.", "两年后，她的小面包房开在了主街。"],
    ],
    writing: { zh: "写一句你的成就加一句它教会你的事。", hintEn: "I finally ___. I learned that ___.", },
  }),
  buildDay({
    day: 72, titleEn: "Times Are Changing", titleZh: "第 72 天 · 变化与时代",
    goalZh: "比较过去与现在，谈论变化。",
    vocabIds: ["w:decade", "w:generation", "w:transform", "w:gradually", "w:nowadays", "w:recent"],
    grammarTopicId: "basic-clauses",
    phonicsRuleIds: ["ai", "er"],
    pattern: {
      titleZh: "句型：These days, ___ . Ten years ago, ___.",
      explainZh: "对比今昔：Ten years ago + 过去式；Now / These days + 现在时。逐渐的变化用 gradually。",
      examples: [["Ten years ago, we used paper maps.", "十年前我们用纸质地图。"], ["Nowadays, everything is on phones.", "如今一切都在手机上。"], ["The town has transformed gradually.", "小镇在慢慢改变。"]],
      sentences: [["Each generation complains about the next.", "每代人都抱怨下一代。"], ["Recent changes came fast.", "最近的变化来得很快。"], ["Some things never change — like grandma's cooking.", "有些事永远不变——比如奶奶的手艺。"]],
    },
    reading: [
      ["Grandpa's first job: delivering newspapers by bike.", "爷爷的第一份工作：骑车送报。"],
      ["Today his granddaughter edits videos on a phone.", "今天他的孙女在手机上剪辑视频。"],
      ["Same family, same street, different world.", "同一个家庭，同一条街，不同的世界。"],
    ],
    writing: { zh: "写一句你感受到的今昔对比。", hintEn: "Ten years ago ___, but now ___.", },
  }),
  buildDay({
    day: 73, titleEn: "Reading Headlines", titleZh: "第 73 天 · 读新闻标题",
    goalZh: "看懂简单英文标题，找到新闻要点。",
    vocabIds: ["w:headline", "w:article", "w:breaking-news", "w:journalist", "w:media", "w:topic"],
    grammarTopicId: "present-simple",
    phonicsRuleIds: ["ee", "j"],
    pattern: {
      titleZh: "句型：Did you see the news about ___?",
      explainZh: "标题常省略 be 动词：City Opens New Park = The city opens/opened... 聊新闻开头句：Did you see the news about...?",
      examples: [["Did you see the news about the new library?", "你看关于新图书馆的新闻了吗？"], ["The headline says prices are falling.", "标题说物价在降。"], ["It was breaking-news last night.", "昨晚这是突发新闻。"]],
      sentences: [["I read one article every morning.", "我每天早上读一篇文章。"], ["Local media covered the story well.", "当地媒体对这件事报道得很到位。"], ["That topic is trending online.", "那个话题正在网上刷屏。"]],
    },
    reading: [
      ["Maya reads headlines while eating breakfast.", "玛雅边吃早饭边浏览新闻标题。"],
      ["Today's front page: a new bike lane on Fifth Street.", "今天头版：第五街新增自行车道。"],
      ["She skips sad news and saves the science article for later.", "她跳过令人难过的消息，把科学文章留着稍后读。"],
    ],
    writing: { zh: "写一句你最近看到的一条（或编一条）本地新闻。", hintEn: "I read about ___ . It said ___.", },
  }),
  buildDay({
    day: 74, titleEn: "Weather Report", titleZh: "第 74 天 · 天气预报",
    goalZh: "听懂天气预报的常用表达。",
    vocabIds: ["w:forecast", "w:thunderstorm", "w:heatwave", "w:freezing", "w:humid", "w:umbrella"],
    grammarTopicId: "future-simple",
    phonicsRuleIds: ["th-vl", "ee"], phonicsPairId: "pair-three-tree",
    pattern: {
      titleZh: "句型：It will rain tomorrow. / There's a chance of ___.",
      explainZh: "天气预报常用 will 和 there's a chance of...（可能有）。温度说 It's dropping to ten degrees.",
      examples: [["It will rain tomorrow afternoon.", "明天下午会下雨。"], ["There's a chance of thunderstorms tonight.", "今晚可能有雷雨。"], ["Temperatures will drop below freezing.", "气温将降到冰点以下。"]],
      sentences: [["Take an umbrella, just in case.", "带上伞以防万一。"], ["This heatwave won't last long.", "这波热浪不会持续太久。"], ["It's humid today — my hair knows it.", "今天很潮——我的头发都知道。"]],
    },
    reading: [
      ["Monday: sunny. Tuesday: clouds move in.", "周一：晴。周二：云来了。"],
      ["By Wednesday, the forecast shows heavy rain.", "到周三，预报显示有大雨。"],
      ["Grandpa still checks the sky before he trusts any app.", "爷爷还是先看天再信应用。"],
    ],
    writing: { zh: "写一句明天的天气预测和建议。", hintEn: "Tomorrow it will ___, so take/___.", },
  }),
  buildDay({
    day: 75, titleEn: "Community News", titleZh: "第 75 天 · 社区新闻",
    goalZh: "谈论身边社区发生的事和公益活动。",
    vocabIds: ["w:community", "w:charity", "w:donate", "w:volunteer", "w:campaign", "w:festival"],
    grammarTopicId: "past-simple",
    phonicsRuleIds: ["ch", "ai"],
    pattern: {
      titleZh: "句型：Our neighborhood is raising money for ___. / Did you hear about ___?",
      explainZh: "社区活动常用现在进行时 is/are + doing。传播消息用 Did you hear about...?",
      examples: [["Did you hear about the new dog park?", "你听说新狗公园的事了吗？"], ["The school is collecting old books this week.", "学校这周在收集旧书。"], ["We donated winter coats to the shelter.", "我们向收容所捐了冬衣。"]],
      sentences: [["Volunteers cleaned the riverbank on Sunday.", "志愿者周日清理了河岸。"], ["The charity campaign helped two hundred families.", "这次慈善活动帮助了两百个家庭。"], ["Community gardens bring neighbors together.", "社区花园让邻居们聚在一起。"]],
    },
    reading: [
      ["The community center needed new bookshelves.", "社区中心需要新书架。"],
      ["A local carpenter volunteered his weekend.", "一位本地木匠贡献了他的周末。"],
      ["Now kids read under a hand-made sign: Little Free Library.", "现在孩子们在一块手写招牌下读书：小自由图书馆。"],
    ],
    writing: { zh: "写一句你想为社区做的一件事。", hintEn: "I want to help my community by ___.", },
  }),
  buildDay({
    day: 76, titleEn: "Numbers & Data", titleZh: "第 76 天 · 数据与数字",
    goalZh: "读懂图表数据，用数字表达观点。",
    vocabIds: ["w:statistics", "w:percent", "w:survey", "w:graph", "w:figure", "w:average"],
    grammarTopicId: "countable-uncountable",
    phonicsRuleIds: ["st", "ar"],
    pattern: {
      titleZh: "句型：About ___ percent of people ___. / The graph shows ___.",
      explainZh: "表达比例用 percent：Seventy percent of students...。描述图表用 The graph/chart shows...。",
      examples: [["Sixty percent of people walk to work here.", "这里百分之六十的人步行上班。"], ["The graph shows sales rising in June.", "图表显示六月销量上升。"], ["On average, we sleep seven hours.", "我们平均睡七小时。"]],
      sentences: [["A recent survey asked about screen time.", "最近一项调查询问了屏幕使用时间。"], ["The figures surprised everyone.", "这些数字让所有人意外。"], ["Numbers tell one part of the story.", "数字只是故事的一部分。"]],
    },
    reading: [
      ["Class 3B surveyed the school's breakfast habits.", "三班调查了全校的早餐习惯。"],
      ["Forty-two percent skip breakfast on test days.", "百分之四十二的人在考试日不吃早餐。"],
      ["Their teacher pinned the chart outside the office.", "老师把图表钉在办公室外。"],
    ],
    writing: { zh: "写一句用百分比描述你班上或家里情况的话。", hintEn: "About ___ percent of us ___.", },
  }),
  buildDay({
    day: 77, titleEn: "Interviews & Quotes", titleZh: "第 77 天 · 采访与引述",
    goalZh: "进行简单采访，转述别人的话。",
    vocabIds: ["w:reporter", "w:microphone", "w:record", "w:survey", "w:statement", "w:witness"],
    grammarTopicId: "questions",
    phonicsRuleIds: ["wh", "r"],
    pattern: {
      titleZh: "句型：Can you tell me about ___? / She said (that) ___.",
      explainZh: "采访提问用 Can you tell me about...? 转述用 said (that) + 从句（注意时态常后移）。",
      examples: [["Can you tell me about your trip?", "能讲讲你的旅行吗？"], ["She said the show was amazing.", "她说演出棒极了。"], ["The reporter asked a follow-up question.", "记者追问了一个问题。"]],
      sentences: [["Please speak into the microphone.", "请对着麦克风说话。"], ["Mind if I record this?", "介意我录个音吗？"], ["One witness described everything calmly.", "一位目击者冷静地描述了经过。"]],
    },
    reading: [
      ["The school paper interviewed the new principal.", "校报采访了新校长。"],
      ["Students asked about lunch, homework, and music in hallways.", "学生们问了午餐、作业和走廊音乐的问题。"],
      ["Her best quote: Schools work when students smile.", "她最好的回答是：学生微笑时，学校就在运转。"],
    ],
    writing: { zh: "写一句你想问校长/老板的问题。", hintEn: "Can you tell me about ___?", },
  }),
  buildDay({
    day: 78, titleEn: "True or Fake?", titleZh: "第 78 天 · 真假消息",
    goalZh: "判断消息可信度，谈论谣言和事实。",
    vocabIds: ["w:fake-news", "w:bias", "w:source", "w:evidence", "w:rumor", "w:fact"],
    grammarTopicId: "negation",
    phonicsRuleIds: ["oo-l", "u-short"], phonicsPairId: "pair-full-food",
    pattern: {
      titleZh: "句型：Where did you hear that? / That doesn't sound right.",
      explainZh: "质疑消息先问来源 Where did you hear that? 表示怀疑说 That sounds off / I doubt it.",
      examples: [["Where did you hear that?", "你从哪儿听说的？"], ["Check the source before sharing.", "转发前先查来源。"], ["That rumor isn't true at all.", "那个谣言完全是假的。"]],
      sentences: [["Facts need evidence.", "事实需要证据。"], ["Some news sites have strong bias.", "有些新闻站点立场很强。"], ["If it sounds too wild, it probably is.", "听起来太离谱的，多半就是。"]],
    },
    reading: [
      ["A message claimed the mall was giving free phones.", "一条消息称商场在免费送手机。"],
      ["Ben searched for the source — nothing official came up.", "本搜索了来源——没有任何官方信息。"],
      ["He didn't share it, and told his family why.", "他没有转发，还告诉家人原因。"],
    ],
    writing: { zh: "写一句你判断真假消息的方法。", hintEn: "Before I share news, I always ___.", },
  }),
  buildDay({
    day: 79, titleEn: "Online Meetings", titleZh: "第 79 天 · 线上会议",
    goalZh: "远程会议中的高频表达和礼貌用语。",
    vocabIds: ["w:mute", "w:notification", "w:screenshot", "w:wifi", "w:laptop", "w:login"],
    grammarTopicId: "questions",
    phonicsRuleIds: ["ng", "oa"],
    pattern: {
      titleZh: "句型：Can everyone see my screen? / You're on mute.",
      explainZh: "共享屏幕前问 Can you see my screen? 提醒对方静音说 You're on mute（你静音了）。",
      examples: [["Can everyone see my screen?", "大家能看到我的屏幕吗？"], ["You're on mute.", "你被静音了。"], ["My wifi keeps dropping.", "我的Wi-Fi一直掉线。"]],
      sentences: [["Let me share this screenshot in the chat.", "我在聊天里发个截图。"], ["Please silence your notifications.", "请把通知关掉。"], ["I'll send the login link by email.", "我会把登录链接发到邮箱。"]],
    },
    reading: [
      ["Monday's meeting had one rule: cameras optional, kindness required.", "周一的会有条规则：摄像头随意，善意必须。"],
      ["Someone's cat walked across the keyboard twice.", "有人的猫两次穿过键盘。"],
      ["The team laughed, then finished the agenda early.", "团队笑了一阵，然后提前完成了议程。"],
    ],
    writing: { zh: "写一句线上会议中最常用到的话。", hintEn: "Sorry, could you ___? Your ___ is ___.", },
  }),
  buildDay({
    day: 80, titleEn: "Negotiating at Work", titleZh: "第 80 天 · 工作谈判",
    goalZh: "就价格、时间和条件进行友好协商。",
    vocabIds: ["w:negotiate", "w:contract", "w:client", "w:invoice", "w:payment", "w:deadline"],
    grammarTopicId: "basic-clauses",
    phonicsRuleIds: ["oa", "st"],
    pattern: {
      titleZh: "句型：Would you be able to ___? / How about we meet halfway?",
      explainZh: "谈判语气很重要：Would you be able to...? 比 Can you 更委婉。折中说 meet halfway（各让一步）。",
      examples: [["Would you be able to extend the deadline?", "您能延长截止日期吗？"], ["How about we meet halfway?", "我们各让一步怎么样？"], ["We can offer a five-percent discount.", "我们可以提供百分之五的折扣。"]],
      sentences: [["The contract needs one small change.", "合同需要一个小改动。"], ["Payment is due within thirty days.", "付款需在三十天内完成。"], ["Happy clients come back.", "满意的客户会再回来。"]],
    },
    reading: [
      ["The client wanted delivery by Friday; the studio needed ten days.", "客户要周五交货，工作室需要十天。"],
      ["They negotiated: eight days for a slightly smaller first batch.", "双方协商：第一批少一点，八天交付。"],
      ["Both sides signed and shook hands.", "双方签字握手。"],
    ],
    writing: { zh: "写一句你在谈判中会做的让步。", hintEn: "We could accept ___ if you could ___.", },
  }),
  buildDay({
    day: 81, titleEn: "Mistakes & Fixes", titleZh: "第 81 天 · 失误与补救",
    goalZh: "承认工作失误、提出解决方案。",
    vocabIds: ["w:mistake", "w:blame", "w:solve", "w:fix", "w:apologize", "w:feedback"],
    grammarTopicId: "past-simple",
    phonicsRuleIds: ["sh", "st"], phonicsPairId: "pair-sit-seat",
    pattern: {
      titleZh: "句型：I made a mistake with ___. Here's my plan to fix it.",
      explainZh: "承认错误三步走：说清问题 + 道歉 + 给方案。不甩锅：It was my fault.",
      examples: [["I made a mistake in the report.", "我在报告里犯了个错。"], ["It was my fault — sorry about that.", "是我的错——非常抱歉。"], ["Here's my plan to fix it by noon.", "这是我的补救计划，中午前完成。"]],
      sentences: [["Don't blame the tool; let's solve the problem.", "别怪工具，我们来解决问题。"], ["Quick feedback helps us improve faster.", "及时的反馈帮我们进步更快。"], ["Every fix makes the next project smoother.", "每次补救都让下一个项目更顺利。"]],
    },
    reading: [
      ["Leo sent the invoice to the wrong client.", "利奥把发票发错了客户。"],
      ["He told his manager immediately, with a fix ready.", "他立即告诉经理，并带着补救方案。"],
      ["The manager's feedback: mistakes happen; honesty matters more.", "经理的反馈是：失误难免，诚实更重要。"],
    ],
    writing: { zh: "写一句承认错误加解决方案的话。", hintEn: "I made a mistake with ___. I will ___.", },
  }),
  buildDay({
    day: 82, titleEn: "Short Presentations", titleZh: "第 82 天 · 简短汇报",
    goalZh: "做一分钟的简短汇报：开头、要点、结尾。",
    vocabIds: ["w:presentation", "w:audience", "w:confident", "w:nervous", "w:speech", "w:practice-n"],
    grammarTopicId: "basic-clauses",
    phonicsRuleIds: ["ai", "er"],
    pattern: {
      titleZh: "句型：Today I'll talk about ___. / To sum up, ___.",
      explainZh: "汇报三段式：Today I'll talk about...（开头）→ 两三个要点 → To sum up（总结）。深呼吸能缓解紧张。",
      examples: [["Today I'll talk about our spring plans.", "今天我要讲我们的春季计划。"], ["There are two main points.", "有两个要点。"], ["To sum up, we're on track.", "总之，我们进度正常。"]],
      sentences: [["Know your audience before you speak.", "发言前先了解你的听众。"], ["Feeling nervous is completely normal.", "感到紧张完全正常。"], ["Practice out loud at least twice.", "至少出声练两遍。"]],
    },
    reading: [
      ["One minute, one idea — that's the rule for Friday updates.", "一分钟一个想法——这是周五例会的规则。"],
      ["Priya was nervous her first time; now she smiles through it.", "普里娅第一次很紧张；现在她全程微笑。"],
      ["Her secret: practice with a rubber duck as the audience.", "她的秘诀：对着一只橡皮鸭练习汇报。"],
    ],
    writing: { zh: "写一句你的汇报开头和一句总结。", hintEn: "Today I'll talk about ___. To sum up, ___.", },
  }),
  buildDay({
    day: 83, titleEn: "Small Talk at Work", titleZh: "第 83 天 · 职场闲聊",
    goalZh: "与同事进行轻松的日常寒暄。",
    vocabIds: ["w:commute", "w:chilly", "w:sunny", "w:humid", "w:weekend", "w:coffee"],
    grammarTopicId: "present-simple",
    phonicsRuleIds: ["r", "ee"],
    pattern: {
      titleZh: "句型：How was your weekend? / Any plans for tonight?",
      explainZh: "职场闲聊安全话题：天气、通勤、周末。回答后回问一句，对话才继续。",
      examples: [["How was your weekend?", "周末过得怎么样？"], ["Terrible traffic this morning, right?", "今早堵车堵得厉害吧？"], ["Any plans for the long weekend?", "小长假有什么安排吗？"]],
      sentences: [["It's chilly today — fall is coming.", "今天有点凉——秋天要来了。"], ["My commute is forty minutes by train.", "我坐火车通勤四十分钟。"], ["Coffee first, conversation second.", "先来杯咖啡再聊。"]],
    },
    reading: [
      ["The office kitchen is where friendships start.", "办公室茶水间是友谊开始的地方。"],
      ["Two minutes of weather talk builds trust for years.", "两分钟天气闲聊能建立多年的信任。"],
      ["Remember: ask, listen, then share a little about you.", "记住：提问、倾听、再分享一点自己。"],
    ],
    writing: { zh: "写两句你和同事的寒暄对话。", hintEn: "A: How's ___? B: ___. And you?", },
  }),
  buildDay({
    day: 84, titleEn: "Food & Health Debate", titleZh: "第 84 天 · 饮食健康讨论",
    goalZh: "就饮食习惯表达观点并给出理由。",
    vocabIds: ["w:organic", "w:vegetarian", "w:junk-food", "w:balanced", "w:delicious", "w:nutrition-label"],
    grammarTopicId: "basic-clauses",
    phonicsRuleIds: ["oi", "st"],
    pattern: {
      titleZh: "句型：I try to ___, but ___. / In my opinion, ___ matters more.",
      explainZh: "谈饮食习惯用 I try to + 动词原形（我尽量…）。表达观点用 In my opinion...。",
      examples: [["I try to eat breakfast every day.", "我尽量每天吃早饭。"], ["In my opinion, balance beats perfection.", "在我看来均衡胜过完美。"], ["Fast-food is fine once in a while.", "快餐偶尔吃一次没问题。"]],
      sentences: [["Organic labels don't always mean healthier.", "有机标签不一定等于更健康。"], ["Vegetarian food can be delicious and filling.", "素食也可以美味又顶饱。"], ["Good nutrition starts at the grocery store.", "好的营养从超市购物开始。"]],
    },
    reading: [
      ["The office voted: fruit basket or cookie jar?", "办公室投票：水果篮还是饼干罐？"],
      ["Fruit won by three votes, so cookies joined the fruit.", "水果多三票胜出，于是饼干也加入了果篮。"],
      ["Balance, as always.", "和往常一样——均衡至上。"],
    ],
    writing: { zh: "写一句你对健康饮食的看法和理由。", hintEn: "In my opinion, ___, because ___.", },
  }),
  buildDay({
    day: 85, titleEn: "City vs Countryside", titleZh: "第 85 天 · 城市与乡村",
    goalZh: "比较城市和乡村生活的优劣。",
    vocabIds: ["w:urban", "w:rural", "w:countryside", "w:noise", "w:convenient", "w:crowded"],
    grammarTopicId: "basic-clauses",
    phonicsRuleIds: ["ow-2", "oi"],
    pattern: {
      titleZh: "句型：City life is ___, but ___. / The countryside is ___, though ___.",
      explainZh: "对比生活用 A is + 形容词, but B is...。承认缺点用 though 让语气更客观。",
      examples: [["City life is convenient but crowded.", "城市生活方便但拥挤。"], ["The countryside is quiet, though jobs are fewer.", "乡村安静，虽然工作机会少些。"], ["Noise never stops in the city center.", "市中心噪音从不停歇。"]],
      sentences: [["Urban parks give city people room to breathe.", "城市公园给城里人喘息的空间。"], ["Fresh air is the countryside's best gift.", "新鲜空气是乡下最好的礼物。"], ["Which fits you depends on your stage of life.", "哪种适合你，取决于你的人生阶段。"]],
    },
    reading: [
      ["After ten years downtown, Ana moved to a village.", "在市中心住了十年后，安娜搬去了一个村庄。"],
      ["Her commute disappeared; her garden tripled.", "通勤消失了，花园大了三倍。"],
      ["She still takes the train into the city for concerts.", "她仍会坐火车进城看演出。"],
    ],
    writing: { zh: "写一句你喜欢城或乡的理由。", hintEn: "I prefer ___ because ___.", },
  }),
  buildDay({
    day: 86, titleEn: "Technology & Life", titleZh: "第 86 天 · 科技与生活",
    goalZh: "讨论科技带来的便利与担忧。",
    vocabIds: ["w:artificial-intelligence", "w:algorithm", "w:gadget", "w:privacy", "w:smartphone", "w:screen"],
    grammarTopicId: "basic-clauses",
    phonicsRuleIds: ["ai", "ng"],
    pattern: {
      titleZh: "句型：Thanks to ___ , we can ___. / The problem is ___.",
      explainZh: "谈好处用 Thanks to + 名词（多亏了）。谈问题用 The problem is...。",
      examples: [["Thanks to smartphones, we carry a library everywhere.", "多亏智能手机，我们随身带着图书馆。"], ["The problem is too much screen time.", "问题是屏幕时间太长。"], ["Artificial intelligence writes drafts; humans add heart.", "人工智能写初稿，人类注入温度。"]],
      sentences: [["Algorithms decide much of what we watch.", "算法决定我们看什么的大部分。"], ["Protect your privacy with strong passwords.", "用好密码保护隐私。"], ["Every new gadget needs a little self-control.", "每个新设备都需要一点自制力。"]],
    },
    reading: [
      ["Grandpa video-calls every Sunday now.", "爷爷现在每周日视频通话。"],
      ["He once feared the smartphone; now he shares memes.", "他曾害怕智能手机；现在他会分享梗图了。"],
      ["Technology didn't replace him — it connected him.", "科技没有取代他——而是连接了他。"],
    ],
    writing: { zh: "写一句科技的好处加一个隐忧。", hintEn: "Thanks to ___ we can ___, but ___.", },
  }),
  buildDay({
    day: 87, titleEn: "Protecting the Environment", titleZh: "第 87 天 · 环保行动",
    goalZh: "谈论环保话题并提出行动建议。",
    vocabIds: ["w:environment", "w:recycle", "w:pollution", "w:planet", "w:energy", "w:protect"],
    grammarTopicId: "basic-clauses",
    phonicsRuleIds: ["oi", "pl"],
    pattern: {
      titleZh: "句型：If we ___, we can protect ___. / Small actions add up.",
      explainZh: "谈环保用条件句 If we..., we can...。提出行动：Let's recycle / save energy。",
      examples: [["If we recycle more, we can cut pollution.", "如果多回收，就能减少污染。"], ["Small actions add up to big change.", "小行动累积成大改变。"], ["Saving energy also saves money.", "省能源也省钱。"]],
      sentences: [["The planet is our only home.", "地球是我们唯一的家。"], ["Bring your own bag when shopping.", "购物自带购物袋。"], ["Bike short trips instead of driving.", "短途骑车代替开车。"]],
    },
    reading: [
      ["Riverside Elementary started a green club last spring.", "河滨小学去年春天成立了绿色社团。"],
      ["Members collect bottles every Friday afternoon.", "社员每周五下午收集瓶子。"],
      ["The money bought ten new trees for the playground.", "换来的钱为操场买了十棵新树。"],
    ],
    writing: { zh: "写一句你能做到的环保行动。", hintEn: "I will ___ to help the planet.", },
  }),
  buildDay({
    day: 88, titleEn: "Learning Choices", titleZh: "第 88 天 · 教育与学习选择",
    goalZh: "谈论学习方式和教育选择。",
    vocabIds: ["w:college", "w:tuition", "w:scholarship", "w:elective", "w:knowledge", "w:course"],
    grammarTopicId: "basic-clauses",
    phonicsRuleIds: ["ee", "j"],
    pattern: {
      titleZh: "句型：I'm thinking about ___ . / It's worth it because ___.",
      explainZh: "表达考虑用 I'm thinking about + 名词/动名词。说值得用 It's worth it because...",
      examples: [["I'm thinking about taking an online course.", "我在考虑上一门网课。"], ["College tuition is high, but scholarships help.", "大学学费高，但奖学金能帮忙。"], ["Photography was my favorite elective.", "摄影是我最喜欢的选修课。"]],
      sentences: [["Knowledge grows when you share it.", "知识越分享越多。"], ["Learning never really finishes.", "学习永远不会真正结束。"], ["Choose subjects that make you curious.", "选择让你好奇的科目。"]],
    },
    reading: [
      ["Should I study more or start working? Ana wondered.", "该继续学习还是开始工作？安娜想。"],
      ["She asked three people and got three different answers.", "她问了三个人，得到三种不同答案。"],
      ["In the end, she chose night classes and a daytime job.", "最后她选择了夜校加白天工作。"],
    ],
    writing: { zh: "写一句你最近想学的东西及原因。", hintEn: "I'm thinking about learning ___, because ___.", },
  }),
  buildDay({
    day: 89, titleEn: "Money Talks", titleZh: "第 89 天 · 金钱与消费观",
    goalZh: "谈论存钱、消费和金钱观。",
    vocabIds: ["w:savings", "w:broke", "w:paycheck", "w:afford", "w:investment", "w:expense"],
    grammarTopicId: "basic-clauses",
    phonicsRuleIds: ["oi", "st"],
    pattern: {
      titleZh: "句型：I can't afford ___, so I'll save up. / It's worth the money.",
      explainZh: "买不起说 I can't afford it。攒钱说 save up。评价值不值：It's (not) worth the money.",
      examples: [["I can't afford a new phone right now.", "我现在买不起新手机。"], ["I'm saving up for a used car.", "我在攒钱买二手车。"], ["Good shoes are worth the money.", "好鞋值得花钱。"]],
      sentences: [["Half my paycheck goes to rent.", "我一半工资交了房租。"], ["Track every expense for one week.", "记录一周的每笔开销。"], ["Broke today doesn't mean broke forever.", "今天没钱不代表永远没钱。"]],
    },
    reading: [
      ["Tara's savings jar had a label: Japan.", "塔拉存钱罐上贴着标签：日本。"],
      ["She skipped takeout coffee three days a week.", "她每周三天不喝外卖咖啡。"],
      ["Eight months later, her boarding-pass matched the label.", "八个月后，她的登机牌对上了那个标签。"],
    ],
    writing: { zh: "写一句你的一个省钱或花钱原则。", hintEn: "I save money on ___ so I can spend on ___.", },
  }),
  buildDay({
    day: 90, titleEn: "Milestone: 90 Days of Real English", titleZh: "第 90 天 · 里程碑：九十天真实英语",
    goalZh: "综合复习第 61-89 天，完成阶段测评，展望下一阶段。",
    vocabIds: ["w:determination", "w:opportunity", "w:eventually", "w:dream", "w:goal", "w:future"],
    grammarTopicId: "future-simple",
    phonicsRuleIds: ["ai", "igh"],
    pattern: {
      titleZh: "句型：Ninety days ago I couldn't ___; now I can ___. Next, I will ___.",
      explainZh: "里程碑三连句：过去不会 → 现在会 → 接下来要。用对比展示真实成长。",
      examples: [["Ninety days ago, phone calls scared me; now I make them daily.", "九十天前我怕打电话；现在我天天打。"], ["I have opinions and words to share them with.", "我有观点，也有表达观点的词汇。"], ["Next, I will keep practicing real conversations.", "接下来我会继续练习真实对话。"]],
      sentences: [["Determination turned minutes into mastery.", "坚持把零碎时间变成了能力。"], ["Every new word is an opportunity waiting.", "每个新词都是等待中的机会。"], ["Eventually, English stops being homework and becomes a tool.", "最终英语不再是作业，而成为工具。"]],
    },
    reading: [
      ["Open your Day 1 notes and read them slowly.", "翻开你第1天的笔记慢慢读。"],
      ["Feel the distance between then and now.", "感受那时与此刻的距离。"],
      ["The next milestone is Day 180 — your future self is already thanking you.", "下一个里程碑在第180天——未来的你已经在道谢。"],
    ],
    writing: { zh: "写三句话：九十天的变化、感谢、下一步目标。", hintEn: "I couldn't ___. Now I can ___. Next I will ___.", },
  }),
];
