/**
 * Day 8-30 authored curriculum - real content for zero-basis Chinese adults.
 * Vocab references the lexical model; grammar references engine topics;
 * every day carries lesson / vocab / grammar / phonics / listening /
 * speaking / reading / writing / review / assessment hooks.
 */
import { buildDay } from "@/content/days/factory";

export const EXTENDED_DAYS = [
  buildDay({
    day: 8, titleEn: "Food & Ordering", titleZh: "第 8 天 · 食物与点餐",
    goalZh: "用 be 动词说出食物是什么，点一份简单的餐。",
    vocabIds: ["w:rice", "w:bread", "w:noodle", "w:salad", "w:juice", "w:menu"],
    grammarTopicId: "be-verb",
    phonicsRuleIds: ["ee", "i-short"], phonicsPairId: "pair-eat-it",
    pattern: {
      titleZh: "句型：This is ___ . / These are ___ .",
      explainZh: "介绍眼前的东西：单数用 This is，复数用 These are。这是最常用的“指认”句型。",
      examples: [["This is rice.", "这是米饭。"], ["This is my menu.", "这是我的菜单。"], ["These are noodles.", "这些是面条。"]],
      sentences: [["This is bread.", "这是面包。"], ["These are apples.", "这些是苹果。"], ["This is juice.", "这是果汁。"]],
    },
    reading: [
      ["This is a small cafe. The menu is on the table.", "这是一家小咖啡馆。菜单在桌上。"],
      ["The salad is fresh and the juice is cold.", "沙拉很新鲜，果汁是凉的。"],
      ["I like this place.", "我喜欢这个地方。"],
    ],
    writing: { zh: "用 This is… 写一句话，介绍你桌上的东西。", hintEn: "This is my ___." },
  }),
  buildDay({
    day: 9, titleEn: "My Family", titleZh: "第 9 天 · 我的家人",
    goalZh: "分清 he/she、him/her，向别人介绍家人。",
    vocabIds: ["w:brother", "w:sister", "w:cousin", "w:aunt", "w:uncle", "w:baby"],
    grammarTopicId: "pronouns-basic",
    phonicsRuleIds: ["sh", "r"], phonicsPairId: "pair-live-leave",
    pattern: {
      titleZh: "句型：She knows me. / Give him ___.",
      explainZh: "动作后面的人用宾格：me/him/her/us/them。Her 是“她的”或宾格；主语必须用 she/he。",
      examples: [["She knows me.", "她认识我。"], ["Give him the key.", "把钥匙给他。"], ["Call her tomorrow.", "明天给她打电话。"]],
      sentences: [["Tell him thanks.", "跟他说声谢谢。"], ["We help them.", "我们帮助他们。"], ["Come with us.", "跟我们走。"]],
    },
    reading: [
      ["This is my family photo. She is my mom, and he is my dad.", "这是我的全家福。她是我妈妈，他是我爸爸。"],
      ["My cousin is ten years old.", "我表弟十岁。"],
      ["We are happy together.", "我们在一起很开心。"],
    ],
    writing: { zh: "写一句话介绍一位家人（用 He/She 开头）。", hintEn: "He is my ___. / She is my ___." },
  }),
  buildDay({
    day: 10, titleEn: "Numbers & Time", titleZh: "第 10 天 · 数字与时间",
    goalZh: "用一般现在时说日常习惯，读准 th 音。",
    vocabIds: ["w:ten", "w:twenty", "w:hundred", "w:minute", "w:hour", "w:weekend"],
    grammarTopicId: "present-simple",
    phonicsRuleIds: ["th-vl", "v"], phonicsPairId: "pair-three-tree",
    pattern: {
      titleZh: "句型：I ___ every day.",
      explainZh: "说习惯用一般现在时：I work every day. 注意三单：He works every day.",
      examples: [["I work every day.", "我每天工作。"], ["She drinks tea in the morning.", "她早上喝茶。"], ["They play tennis on weekends.", "他们周末打网球。"]],
      sentences: [["I sleep eight hours.", "我睡八小时。"], ["He reads every night.", "他每晚读书。"], ["We walk twenty minutes.", "我们走二十分钟。"]],
    },
    reading: [
      ["I get up at seven. I eat breakfast at seven thirty.", "我七点起床，七点半吃早餐。"],
      ["I work five days a week.", "我每周工作五天。"],
      ["On weekends, I rest at home.", "周末我在家休息。"],
    ],
    writing: { zh: "用一般现在时写你的一天（至少一句）。", hintEn: "Every day, I ___." },
  }),
  buildDay({
    day: 11, titleEn: "Clothes & Colors", titleZh: "第 11 天 · 衣服与颜色",
    goalZh: "会用 a/an/the 描述衣服颜色。",
    vocabIds: ["w:shirt", "w:jacket", "w:purple", "w:pink", "w:brown", "w:wear"],
    grammarTopicId: "articles",
    phonicsRuleIds: ["ow-2", "ai"], phonicsPairId: "pair-bad-bed",
    pattern: {
      titleZh: "句型：I have an apple. / The car is red.",
      explainZh: "a 配辅音音开头，an 配元音音开头（an apple），the 表示特指的那一个。",
      examples: [["I have an orange jacket.", "我有一件橙色夹克。"], ["The purple shirt is nice.", "那件紫衬衫不错。"], ["She wears a pink hat.", "她戴着粉色帽子。"]],
      sentences: [["It is a brown bag.", "这是个棕色的包。"], ["The white shirt is new.", "那件白衬衫是新的。"], ["I like the gray coat.", "我喜欢那件灰外套。"]],
    },
    reading: [
      ["Look at this store. The jackets are blue and black.", "看这家店。夹克有蓝色和黑色。"],
      ["An orange hat is only ten dollars.", "一顶橙帽子只要十美元。"],
      ["I want the brown one.", "我想要那个棕色的。"],
    ],
    writing: { zh: "写一句话描述你身上的一样东西及颜色。", hintEn: "My ___ is ___." },
  }),
  buildDay({
    day: 12, titleEn: "Rooms at Home", titleZh: "第 12 天 · 家与房间",
    goalZh: "区分可数与不可数，说出家里物品位置。",
    vocabIds: ["w:kitchen", "w:mirror", "w:curtain", "w:shelf", "w:basement", "w:garden"],
    grammarTopicId: "countable-uncountable",
    phonicsRuleIds: ["er", "or"], phonicsPairId: "pair-cat-cut",
    pattern: {
      titleZh: "句型：How many books? / How much water?",
      explainZh: "可数复数问 how many；水、钱这类不可数用 how much。some 两者都能接。",
      examples: [["How many rooms?", "有几个房间？"], ["How much water do you need?", "你要多少水？"], ["There are two mirrors in the house.", "家里有两面镜子。"]],
      sentences: [["The kitchen is big.", "厨房很大。"], ["Books are on the shelf.", "书在架子上。"], ["The garden is small.", "花园很小。"]],
    },
    reading: [
      ["Our new home has six rooms.", "我们的新家有六个房间。"],
      ["in the bedroom.", "卧室里有面大镜子。"],
      ["The garden needs water every morning.", "花园每天早上需要浇水。"],
    ],
    writing: { zh: "写一句话说说你家最喜欢的房间和原因。", hintEn: "I like the ___ because it is ___." },
  }),
  buildDay({
    day: 13, titleEn: "Housework Now", titleZh: "第 13 天 · 现在就做：家务",
    goalZh: "用进行时说出正在做的家务。",
    vocabIds: ["w:cook", "w:wash", "w:clean", "w:sweep", "w:tidy", "w:mop"],
    grammarTopicId: "present-progressive",
    phonicsRuleIds: ["sh", "ng"], phonicsPairId: "pair-full-food",
    pattern: {
      titleZh: "句型：I am ___ing now.",
      explainZh: "正在做的事＝am/is/are + 动词-ing。妈妈在做饭：Mom is cooking.",
      examples: [["I am washing dishes.", "我在洗碗。"], ["Dad is cooking dinner.", "爸爸在做晚饭。"], ["She is sweeping the floor.", "她在扫地。"]],
      sentences: [["We are cleaning the kitchen.", "我们在打扫厨房。"], ["He is tidying his desk.", "他在整理书桌。"], ["They are mopping now.", "他们在拖地。"]],
    },
    reading: [
      ["It is Saturday morning. Everyone is busy.", "周六早晨，大家都很忙。"],
      ["Mom is cooking. Dad is mopping the floor.", "妈妈做饭，爸爸拖地。"],
      ["I am cleaning my room.", "我在打扫房间。"],
    ],
    writing: { zh: "写下你现在正在做的一件事。", hintEn: "I am ___ing now." },
  }),
  buildDay({
    day: 14, titleEn: "Week Two Review", titleZh: "第 14 天 · 第二周复习",
    goalZh: "综合复习第二周词汇与两个时态，查漏补缺。",
    vocabIds: ["w:water", "w:family", "w:happy", "w:morning", "w:friend", "w:learn"],
    grammarTopicId: "present-simple",
    phonicsRuleIds: ["ee", "th-vl"], phonicsPairId: "pair-sit-seat",
    pattern: {
      titleZh: "复习句型：He plays tennis on Sundays.（三单）",
      explainZh: "本周重点回顾：三单加 s、a/an 选择、many/much 区分。做错没关系——系统会安排复习。",
      examples: [["He plays soccer every weekend.", "他每周末踢球。"], ["My friend learns English daily.", "我朋友每天学英语。"], ["Water keeps me healthy.", "水让我健康。"]],
      sentences: [["She drinks coffee every morning.", "她每天早上喝咖啡。"], ["We walk together after dinner.", "晚饭后我们一起散步。"], ["They learn five words a day.", "他们每天学五个词。"]],
    },
    reading: [
      ["Learning English takes time, but it works.", "学英语花时间，但有效。"],
      ["Ten minutes every day is better than one long day.", "每天十分钟胜过突击一天。"],
      ["Keep going!", "坚持下去！"],
    ],
    writing: { zh: "写两句：你的一个习惯 + 你家人的一个习惯。", hintEn: "I ___ every day. My mom ___s every day." },
  }),
  buildDay({
    day: 15, titleEn: "Around Town", titleZh: "第 15 天 · 城市与方向",
    goalZh: "用介词说地点，听懂简单路线。",
    vocabIds: ["w:street", "w:corner", "w:elevator", "w:traffic", "w:north", "w:opposite"],
    grammarTopicId: "prepositions-basic",
    phonicsRuleIds: ["ar", "or"], phonicsPairId: "pair-work-walk",
    pattern: {
      titleZh: "句型：Meet me at the station.",
      explainZh: "at 小地点、on 表面/某天、in 里面。固定搭配 good AT English 单独记。",
      examples: [["Meet me at the corner.", "在街角见。"], ["The keys are in the drawer.", "钥匙在抽屉里。"], ["The shop is on Bridge Street.", "商店在桥街上。"]],
      sentences: [["Turn left at the light.", "红绿灯左转。"], ["The bank is opposite the park.", "银行在公园对面。"], ["Go straight ahead.", "一直向前。"]],
    },
    reading: [
      ["Our school is on Green Street.", "我们学校在格林街。"],
      ["The bus stop is near the library, not far away.", "公交站离图书馆很近。"],
      ["Walk two blocks, then turn right.", "走两个街区然后右转。"],
    ],
    writing: { zh: "写一句话告诉朋友你在哪里等他。", hintEn: "Meet me at/in/on ___." },
  }),
  buildDay({
    day: 16, titleEn: "Travel Plans", titleZh: "第 16 天 · 出行计划",
    goalZh: "用 will 说将来的行程。",
    vocabIds: ["w:luggage", "w:passport", "w:flight", "w:map", "w:journey", "w:delay"],
    grammarTopicId: "future-simple",
    phonicsRuleIds: ["dr", "tr"], phonicsPairId: "pair-cat-cut",
    pattern: {
      titleZh: "句型：It will rain tomorrow. → 将来计划",
      explainZh: "will 后动词原形：I will go. 不加 to、不加 s。更口语也可以说 I'm going to go.",
      examples: [["The flight will arrive at six.", "航班六点到。"], ["I will pack tonight.", "我今晚收拾行李。"], ["We will take a taxi.", "我们会打车。"]],
      sentences: [["Don't forget your passport!", "别忘了护照！"], ["The journey takes two hours.", "旅程两小时。"], ["Everything will be fine.", "一切都会顺利。"]],
    },
    reading: [
      ["Tomorrow we fly to New York.", "明天我们飞纽约。"],
      ["The flight leaves at nine, so we need to leave early.", "航班九点起飞，所以要早点出发。"],
      ["I will check our passports again.", "我会再检查一遍护照。"],
    ],
    writing: { zh: "写一句你明天的计划（用 will）。", hintEn: "Tomorrow, I will ___." },
  }),
  buildDay({
    day: 17, titleEn: "Weather Talk", titleZh: "第 17 天 · 天气闲聊",
    goalZh: "用进行时聊天气：It's raining.",
    vocabIds: ["w:storm", "w:fog", "w:forecast", "w:breeze", "w:autumn", "w:temperature"],
    grammarTopicId: "present-progressive",
    phonicsRuleIds: ["oo-l", "ow-2"], phonicsPairId: "pair-bad-bed",
    pattern: {
      titleZh: "句型：It's raining now.（天气进行时）",
      explainZh: "谈此刻天气常用进行时：It's raining / The sun is shining.",
      examples: [["It's raining hard outside.", "外面雨下得很大。"], ["The wind is blowing.", "风正吹着。"], ["Look! It's snowing!", "看！下雪了！"]],
      sentences: [["The fog is clearing.", "雾正在散。"], ["Autumn is coming.", "秋天来了。"], ["The temperature is dropping.", "气温在下降。"]],
    },
    reading: [
      ["What's the weather like today? It's cloudy and cool.", "今天天气如何？多云凉爽。"],
      ["The forecast says rain tomorrow.", "天气预报说明天有雨。"],
      ["Take an umbrella with you.", "带上伞。"],
    ],
    writing: { zh: "写一句今天的天气（用进行时）。", hintEn: "It's ___ing today." },
  }),
  buildDay({
    day: 18, titleEn: "Animals & Yesterday", titleZh: "第 18 天 · 动物与过去",
    goalZh: "第一次接触过去式：昨天发生的事。",
    vocabIds: ["w:rabbit", "w:horse", "w:monkey", "w:bee", "w:snake", "w:zoo"],
    grammarTopicId: "past-simple",
    phonicsRuleIds: ["i-short", "u-short"], phonicsPairId: "pair-sit-seat",
    pattern: {
      titleZh: "句型：I went to the zoo yesterday.",
      explainZh: "过去的事动词变形：go→went，eat→ate，see→saw。规则动词加 ed：worked。",
      examples: [["We went to the zoo yesterday.", "我们昨天去了动物园。"], ["I saw a snake there.", "在那儿我看到一条蛇。"], ["The monkeys ate bananas.", "猴子们吃了香蕉。"]],
      sentences: [["She liked the pandas.", "她喜欢熊猫。"], ["We walked for three hours.", "我们走了三个小时。"], ["It was fun.", "很有意思。"]],
    },
    reading: [
      ["Yesterday my family visited the zoo.", "昨天全家去了动物园。"],
      ["The elephants were big and the monkeys were funny.", "大象很大，猴子很有趣。"],
      ["We took many photos.", "我们拍了很多照片。"],
    ],
    writing: { zh: "写一句你昨天做过的事。", hintEn: "Yesterday, I ___ed / went / saw…" },
  }),
  buildDay({
    day: 19, titleEn: "Health First", titleZh: "第 19 天 · 健康第一",
    goalZh: "学会否定表达：不要/没有/不是。",
    vocabIds: ["w:throat", "w:fever", "w:exercise", "w:medicine", "w:stomach", "w:healthy"],
    grammarTopicId: "negation",
    phonicsRuleIds: ["ai", "er"], phonicsPairId: "pair-live-leave",
    pattern: {
      titleZh: "句型：I don't like coffee.",
      explainZh: "行为动词否定加 don't/doesn't/didn't；be 动词后直接 not：isn't hungry.",
      examples: [["I don't feel well.", "我不太舒服。"], ["She doesn't have a fever.", "她没发烧。"], ["Don't forget your medicine.", "别忘了吃药。"]],
      sentences: [["He isn't sick today.", "他今天没生病。"], ["We didn't sleep well.", "我们没睡好。"], ["Eat well and stay healthy.", "好好吃饭保持健康。"]],
    },
    reading: [
      ["My throat hurts and I have a headache.", "我嗓子疼还头疼。"],
      ["But I don't have a fever, so it's OK.", "但我没发烧，问题不大。"],
      ["Rest and drink warm water.", "休息多喝温水。"],
    ],
    writing: { zh: "写一句你的健康习惯或禁忌（用 don't）。", hintEn: "I don't ___ every dayI don't smoke." },
  }),
  buildDay({
    day: 20, titleEn: "Feelings", titleZh: "第 20 天 · 情绪表达",
    goalZh: "谈论昨天的感受：was/were + 情绪词。",
    vocabIds: ["w:nervous", "w:proud", "w:lonely", "w:excited", "w:mood", "w:confidence"],
    grammarTopicId: "past-simple",
    phonicsRuleIds: ["oi", "igh"], phonicsPairId: "pair-bad-bed",
    pattern: {
      titleZh: "句型：I was nervous yesterday.",
      explainZh: "be 的过去式：I/he/she 用 was；you/we/they 用 were。情绪形容词直接跟在后面。",
      examples: [["I was nervous before the test.", "考试前我很紧张。"], ["She was excited about the trip.", "她对旅行很兴奋。"], ["They were proud of him.", "他们为他骄傲。"]],
      sentences: [["We were tired last night.", "昨晚我们累了。"], ["He wasn't sad — just quiet.", "他不难过只是安静。"], ["Are you feeling better now?", "现在感觉好些了吗？"]],
    },
    reading: [
      ["Yesterday was a big day for Lin.", "对林来说昨天是大日子。"],
      ["She was nervous in the morning, but she did great.", "早上她还紧张，但表现出色。"],
      ["Now she feels confident.", "现在她自信多了。"],
    ],
    writing: { zh: "写一句你昨天的心情（用 was/were）。", hintEn: "I was ___ yesterday." },
  }),
  buildDay({
    day: 21, titleEn: "At Work", titleZh: "第 21 天 · 工作场景",
    goalZh: "掌握 Do/Does 疑问句，开口问工作问题。",
    vocabIds: ["w:meeting", "w:interview", "w:salary", "w:engineer", "w:manager", "w:career"],
    grammarTopicId: "questions",
    phonicsRuleIds: ["bl", "pl"], phonicsPairId: "pair-eat-it",
    pattern: {
      titleZh: "句型：Do you work here?",
      explainZh: "一般疑问句 Do/Does 开头；特殊疑问 What/Where + do/does。",
      examples: [["Do you work here?", "你在这儿工作吗？"], ["Does the meeting start at ten?", "会议十点开始吗？"], ["Where does she work?", "她在哪儿工作？"]],
      sentences: [["What do you do?", "你是做什么的？"], ["Do they hire new people?", "他们招新人吗？"], ["Does he like his job?", "他喜欢他的工作吗？"]],
    },
    reading: [
      ["Amy has a job interview today.", "艾米今天有工作面试。"],
      ["The manager asks, \"Do you have experience?\"", "经理问：“你有经验吗？”"],
      ["She answers honestly and smiles.", "她诚实作答并微笑。"],
    ],
    writing: { zh: "写两个你想问新同事的问题（用 Do/Does）。", hintEn: "Do you like ___? Does he/she ___?" },
  }),
  buildDay({
    day: 22, titleEn: "Back to School", titleZh: "第 22 天 · 学校生活",
    goalZh: "复习冠词 an/a/the 在校园语境的使用。",
    vocabIds: ["w:classroom", "w:blackboard", "w:homework", "w:exam", "w:library", "w:science"],
    grammarTopicId: "articles",
    phonicsRuleIds: ["ee", "e-short"], phonicsPairId: "pair-three-tree",
    pattern: {
      titleZh: "句型：I have an English class.",
      explainZh: "an + 元音音：an exam / an hour；the 特指双方都知道的东西：the classroom.",
      examples: [["I have an exam tomorrow.", "我明天有考试。"], ["Meet me in the library.", "图书馆见。"], ["The science class is fun.", "科学课很有趣。"]],
      sentences: [["Do your homework first.", "先做作业。"], ["Write it on the blackboard.", "写在黑板上。"], ["Our classroom is on the second floor.", "我们教室在二楼。"]],
    },
    reading: [
      ["School starts at eight thirty.", "八点半开始上课。"],
      ["Today we have math, science, and art.", "今天有数学、科学和美术课。"],
      ["After school, Li does homework in the library.", "放学后李在图书馆写作业。"],
    ],
    writing: { zh: "写一句你最喜欢的科目及原因。", hintEn: "I like ___ because it is ___.(because 下周学也先用)" },
  }),
  buildDay({
    day: 23, titleEn: "Smart Shopping", titleZh: "第 23 天 · 聪明购物",
    goalZh: "购物中熟练使用 many/much/some。",
    vocabIds: ["w:discount", "w:receipt", "w:cash", "w:mall", "w:price", "w:cheap"],
    grammarTopicId: "countable-uncountable",
    phonicsRuleIds: ["st", "sp"], phonicsPairId: "pair-full-food",
    pattern: {
      titleZh: "句型：How much is it?",
      explainZh: "问价格固定 How much；问数量可数 how many + 复数；some 接两类名词。",
      examples: [["How much is this shirt?", "这件衬衫多少钱？"], ["How many bags do you want?", "你要几个袋子？"], ["I need some cash.", "我需要些现金。"]],
      sentences: [["Can I pay by card?", "能刷卡吗？"], ["Is there a discount?", "有折扣吗？"], ["Keep the receipt, please.", "请留好收据。"]],
    },
    reading: [
      ["The mall has a big sale today.", "商场今天大促。"],
      ["Shoes are half price, and shirts are cheap too.", "鞋子半价，衬衫也便宜。"],
      ["Lin buys two shirts and pays cash.", "李买了两件衬衫付现金。"],
    ],
    writing: { zh: "写一句你最近买的东西和价格。", hintEn: "I bought ___ for ___ dollars.(bought 为 buy 过去式)" },
  }),
  buildDay({
    day: 24, titleEn: "Online Life", titleZh: "第 24 天 · 网络生活",
    goalZh: "用进行时描述网上正在发生的行为。",
    vocabIds: ["w:website", "w:password", "w:app", "w:message", "w:online", "w:screen"],
    grammarTopicId: "present-progressive",
    phonicsRuleIds: ["ng", "z"], phonicsPairId: undefined as never,
    pattern: {
      titleZh: "句型：He is sending messages now.",
      explainZh: "网络时代进行时超高频：uploading / downloading / chatting online.",
      examples: [["She is downloading an app.", "她在下载应用。"], ["They are chatting online.", "他们在网上聊天。"], ["I'm reading news on my phone.", "我在手机上看新闻。"]],
      sentences: [["The screen is loading.", "屏幕加载中。"], ["Who is calling me?", "谁在给我打电话？"], ["We are sharing photos.", "我们在分享照片。"]],
    },
    reading: [
      ["Wang is setting up a new account.", "小王在注册新账号。"],
      ["He chooses a strong password: letters AND numbers.", "他选了强密码：字母加数字。"],
      ["Never share passwords with strangers online.", "绝不与网上陌生人共享密码。"],
    ],
    writing: { zh: "写一句你此刻在网上做的事。", hintEn: "Right now, I'm ___ing online." },
  }),
  buildDay({
    day: 25, titleEn: "Hobbies & Why", titleZh: "第 25 天 · 爱好与理由",
    goalZh: "第一次连句：I think … because …",
    vocabIds: ["w:basketball", "w:yoga", "w:chess", "w:camping", "w:hobby", "w:race"],
    grammarTopicId: "basic-clauses",
    phonicsRuleIds: ["j", "w"], phonicsPairId: undefined as never,
    pattern: {
      titleZh: "句型：I think it is fun because ___.",
      explainZh: "I think + 完整句子；because + 完整句子。从句里也要有主语和动词！",
      examples: [["I think chess is fun because it makes me think.", "我觉得国际象棋有趣因为动脑。"], ["She loves yoga because it relaxes her.", "她爱瑜伽因为让她放松。"], ["We camp because we love nature.", "我们露营因为热爱自然。"]],
      sentences: [["Basketball is popular here.", "这里篮球很流行。"], ["My hobby needs patience.", "我的爱好需要耐心。"], ["Bike races are exciting.", "自行车赛很刺激。"]]
    },
    reading: [
      ["Everyone in our family has a hobby.", "我们家每个人都有爱好。"],
      ["Dad plays chess; Mom does yoga; I go camping.", "爸爸下棋，妈妈做瑜伽，我去露营。"],
      ["Hobbies make life colorful.", "爱好让生活多彩。"],
    ],
    writing: { zh: "写你的爱好并用 because 说明原因。", hintEn: "I like ___ because ___.(like 后动词加-ing)" },
  }),
  buildDay({
    day: 26, titleEn: "Arts & Memories", titleZh: "第 26 天 · 艺术 与回忆",
    goalZh: "不规则过去式第二课：see→saw, hear→heard.",
    vocabIds: ["w:guitar", "w:concert", "w:museum", "w:movie", "w:painting", "w:song"],
    grammarTopicId: "past-simple",
    phonicsRuleIds: ["oa", "oi"], phonicsPairId: "pair-live-leave",
    pattern: {
      titleZh: "句型：We saw a great movie last night.",
      explainZh: "更多不规则变化：see→saw, hear→heard, sing→sang。别再加-ed！",
      examples: [["We saw a great movie last night.", "昨晚我们看了部好电影。"], ["She heard a beautiful song.", "她听到一首好听的歌。"], ["I took photos at the museum.", "我在博物馆拍了照。"]],
      sentences: [["They sang together at the concert.", "音乐会上他们一起唱了歌。"], ["The painting moved me.", "那幅画打动了我。"], ["He played guitar all evening.", "他弹了一晚上吉他。"]],
    },
    reading: [
      ["with her aunt.", "上周末小梅和姑姑去了美术馆。"],
      ["She saw paintings from many countries.", "她看到了来自很多国家的画。"],
      ["In the evening, they heard live music in the park.", "晚上她们在公园听了现场音乐。"],
    ],
    writing: { zh: "写一件上周你看过/听过的美好事物（用 saw/heard）。", hintEn: "Last week, I saw/heard ___." },
  }),
  buildDay({
    day: 27, titleEn: "Holiday Plans", titleZh: "第 27 天 · 节日与打算",
    goalZh: "用 be going to 说节日打算。",
    vocabIds: ["w:birthday", "w:gift", "w:fireworks", "w:picnic", "w:balloon", "w:celebrate"],
    grammarTopicId: "future-simple",
    phonicsRuleIds: ["wh", "ai"], phonicsPairId: undefined as never,
    pattern: {
      titleZh: "句型：I'm going to visit my grandma.",
      explainZh: "be going to + 原形＝计划要做。I'm going to celebrate with friends.",
      examples: [["We're going to have a picnic.", "我们打算去野餐。"], ["I'm going to buy her a gift.", "我打算给她买礼物。"], ["They're going to watch fireworks.", "他们打算看烟花。"]],
      sentences: [["Are you going to the party?", "你会去聚会吗？"], ["What are you going to wear?", "你打算穿什么？"], ["It's going to be fun!", "一定会很好玩！"]],
    },
    reading: [
      ["Next Monday is Grandma's birthday.", "下周一是奶奶生日。"],
      ["We're going to make dumplings and buy a cake.", "我们打算包饺子买蛋糕。"],
      ["Grandma is going to love it.", "奶奶一定会喜欢。"],
    ],
    writing: { zh: "写一句你这个周末的打算。", hintEn: "This weekend, I'm going to ___." },
  }),
  buildDay({
    day: 28, titleEn: "Restaurant Polite", titleZh: "第 28 天 · 餐厅礼貌英语",
    goalZh: "礼貌提问：Could I have…? Would you like…?",
    vocabIds: ["w:server", "w:tip", "w:buffet", "w:flavor", "w:reservation", "w:takeout"],
    grammarTopicId: "questions",
    phonicsRuleIds: ["ch", "sh"], phonicsPairId: "pair-work-walk",
    pattern: {
      titleZh: "句型：Could I have a menu, please?",
      explainZh: "Could I have… 比 I want 更礼貌；Would you like… 用来问客人要什么。",
      examples: [["Could I have a menu, please?", "能给我菜单吗？"], ["Would you like some water?", "您要来点水吗？"], ["Could we sit by the window?", "我们可以坐窗边吗？"]],
      sentences: [["I'd like the fish, please.", "我要鱼，谢谢。(I'd=I would)"], ["Anything else?", "还需要别的吗？"], ["Keep the change? That's a tip.", "不用找了——那是小费。"]],
    },
    reading: [
      ["Tom takes his parents to an American restaurant.", "汤姆带父母去美餐厅。"],
      ["The server asks, \"Would you like something to drink?\"", "服务员问：“要喝点什么吗？”"],
      ["Remember: tipping 15–20% is normal in the US.", "记住：在美国给15–20%小费很正常。"],
    ],
    writing: { zh: "写一句你在餐厅的礼貌请求（用 Could I…）。", hintEn: "Could I have ___, please?" },
  }),
  buildDay({
    day: 29, titleEn: "Community Rules", titleZh: "第 29 天 · 社区与规则",
    goalZh: "用 shouldn't / must not 说禁止与建议。",
    vocabIds: ["w:law", "w:emergency", "w:safety", "w:community", "w:neighbor", "w:rule"],
    grammarTopicId: "negation",
    phonicsRuleIds: ["ng", "th-vd"], phonicsPairId: undefined as never,
    pattern: {
      titleZh: "句型：You shouldn't smoke here.",
      explainZh: "shouldn't＝不应该（建议）；must not＝绝对禁止。语气比 don't 更正式。",
      examples: [["You shouldn't park here.", "你不该停这儿。"], ["We must keep the community safe.", "我们必须维护社区安全。"], ["Neighbors shouldn't shout at each other.", "邻居不该互相吼。"]],
      sentences: [["In an emergency, call 911.", "紧急情况打911。"], ["Please don't litter.", "请不要乱扔垃圾。"], ["Rules protect everyone.", "规则保护每个人。"]],
    },
    reading: [
      ["Every community has rules.", "每个社区都有规则。"],
      ["Some rules are laws; others are just polite habits.", "有的是法律，有的只是礼貌习惯。"],
      ["Good neighbors follow both.", "好邻居两者都遵守。"],
    ],
    writing: { zh: "写一条你所在社区/学校的规则（用 should/shouldn't）。", hintEn: "We should ___. / You shouldn't ___." },
  }),
  buildDay({
    day: 30, titleEn: "Milestone Review", titleZh: "第 30 天 · 阶段总复习",
    goalZh: "串联第一个月所学：完成 Day30 综合测评。",
    vocabIds: ["w:future-n", "w:moment", "w:dream", "w:goal", "w:language", "w:learn"].map((id) => id.replace("future-n", "future")),
    grammarTopicId: "basic-clauses",
    phonicsRuleIds: ["ee", "th-vl"], phonicsPairId: "pair-sit-seat",
    pattern: {
      titleZh: "总结句型：I think English is easy because I practice daily.",
      explainZh: "把观点(I think)、原因(because)、时态串成一段话——这就是30天前做不到的事。",
      examples: [["I think I speak better English now.", "我觉得自己口语进步了。"], ["Because I practiced every day,", "因为我每天练习，"], ["my dream feels closer.", "梦想更近了。"]],
      sentences: [["Review makes memory strong.", "复习让记忆牢固。"], ["Thirty days ago, I knew nothing.", "三十天前我一无所知。"], ["Now I can talk about my life.", "现在我能聊自己的生活了。"]],
    },
    reading: [
      ["Thirty days ago, these words were noise.", "三十天前，这些词只是一串噪音。"],
      ["Today, you read them and understand.", "今天你能读懂它们。"],
      ["This is real progress. Tomorrow: more reviews, more practice.", "这是真实的进步。明天继续复习与练习。"],
    ],
    writing: { zh: "写两句：这一个月你学会了什么 + 你接下来的目标。", hintEn: "I learned ___. Next, I'm going to ___." },
  }),
];
